pkg/clustermanager/manager.go

https://github.com/rancher/rancher/issues/21129

Fix CRD store panic

---

pkg/clustermanager/manager.go

Fix CRD store panic [v2.2]

---

pkg/controllers/user/monitoring/register.go

https://github.com/rancher/rancher/issues/21211

fix missing registration for monitoring project lister

---

pkg/api/store/auth/store.go
tests/integration/suite/test_auth_configs.py

For auth providers with common secret field names, secrets
were getting generated irrespective of auth type being set,
example spKey is common for all SAML providers

Check auth type before creating secret

---

package/windows/run.ps1

**Problem:**
The `msiscsi` service enabled by flexvolume plugin will cause storage fail to mount.
**Solution:**
Start `msiscsi` service before running agent.
**Issue:**
#20192

[Windows] Fix Windows iSCSI workflow failed to start

---

vendor.conf
vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
vendor/github.com/rancher/kontainer-engine/vendor.conf

Addresses https://github.com/rancher/rancher/issues/21061
Dependency on: https://github.com/rancher/kontainer-engine/pull/165

Fix logging analytics workspace naming length

---

vendor.conf
vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
vendor/github.com/rancher/kontainer-engine/vendor.conf

Dependency: https://github.com/rancher/kontainer-engine

Update vendor for aks resource name fix

---

pkg/api/customization/monitor/cluster_graph_action.go
pkg/api/customization/monitor/handler_utils.go

**Problem:**
It can fetch workload metrics from other project.
**Solution:**
Should validate the workload if it is in this project or not.

[Monitoring]Validate namespace in workload metrics query

---

app/machinedriver_data.go

Fix https://github.com/rancher/rancher/issues/21097

Update pinganyunecs driver version to v0.2.0

---

pkg/controllers/user/certsexpiration/certsexpiration.go

https://github.com/rancher/rancher/issues/21220

Change date format for cluster cert expiration [v2.2]

---

pkg/controllers/user/certsexpiration/certsexpiration.go

https://github.com/rancher/rancher/issues/21220

Change date format for cluster cert expiration

---

pkg/auth/providers/googleoauth/goauthconfig_actions.go

Remove params for scope, state and the redirectURI since UI will append all these.
https://github.com/rancher/rancher/issues/21194

Update google oauth redirectURL params

---

app/machinedriver_data.go

Fix https://github.com/rancher/rancher/issues/20878

[master] Update pinganyunecs driver version to v0.2.0

---

package/Dockerfile

Bump UI Version

---

package/jailer.sh

Problem:
Jailer needs to use real ssh
Solution:
Pull in ssh and required libs to support it

Update jailer script v2.0

---

package/jailer.sh

Problem:
Jailer needs to use real ssh
Solution:
Pull in ssh and required libs to support it

Update jailer script v2.1

---

pkg/api/store/cluster/cluster_store.go
pkg/settings/setting.go
tests/integration/suite/test_clustertemplate.py
tests/integration/suite/test_kontainer_engine_config.py

https://github.com/rancher/rancher/issues/21084

Kubernetes Version translation during create cluster

---

pkg/api/server/managementstored/setup.go
pkg/api/store/clustertemplate/store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21200
API validation to ensure ClusterTemplate can be enforced only by an Admin

Only Admin can set or change the clustertemplate.enforced field

---

tests/integration/suite/test_rbac.py

Problem:
Upgrade tests occasionally fail with timeout, unauthorized, and modified errors.
Solution:
Stop waiting for workloads as it is not required to upgrade. Wait for app to reach "installing" state
before attempting to upgrade.
Related build:
https://drone-pr.rancher.io/rancher/rancher/2912

Fix flakey rbac tests

---

package/Dockerfile.agent

https://github.com/rancher/rancher/issues/21291

Update embedded kubectl to 1.12.9

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21142

Cluster edit cannot remove clustertemplate and revision id

---

app/role_data.go
pkg/app/utils/utils.go
pkg/controllers/user/cis/clusterScanHandler.go
pkg/controllers/user/monitoring/clusterHandler.go
pkg/controllers/user/monitoring/operatorHandler.go

Addresses: https://github.com/rancher/rancher/issues/21257

cis review comments

---

pkg/controllers/user/alert/deployer/upgradeimpl.go
pkg/controllers/user/logging/deployer/upgradeimpl.go

Problem:
got cluster not ready error when upgrade rancher server
Solution:
check cluster ready before upgrade system service
Issue:
https://github.com/rancher/rancher/issues/21323

Check cluster ready before upgrade system service

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/16050

Change scheduling for node/cluster agent pods

---

package/Dockerfile

tickets included in this build
rancher/rancher#21283

bump UI index

---

pkg/api/customization/app/app.go
pkg/api/customization/catalog/template.go
pkg/api/customization/catalog/templateversion.go
pkg/api/customization/multiclusterapp/multi_cluster_app.go
pkg/api/customization/multiclusterapp/store.go
pkg/api/customization/multiclusterapp/validator_multiclusterapp.go
pkg/api/server/managementstored/setup.go
pkg/api/store/app/store.go
pkg/catalog/manager/traverse.go
pkg/catalog/utils/version.go
tests/integration/suite/conftest.py
tests/integration/suite/test_app.py
tests/integration/suite/test_catalog.py
tests/integration/suite/test_multi_cluster_app.py

Issue: https://github.com/rancher/rancher/issues/18469

Rancher version verification

---

pkg/controllers/user/alert/deployer/upgradeimpl.go
pkg/controllers/user/logging/deployer/upgradeimpl.go

This reverts commit d8d498926c7424de9212b1dd1b36edd3790d2123.

Revert "Check cluster ready before upgrade system service"

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21406

Compare the clusterTemplateId from the revision which has the namespace added

---

vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/catalog_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_question.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_sub_question.go

Adding Question.satisfies field to schema.

Update vendor to latest types 

---

vendor.conf
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go

Addresses https://github.com/rancher/rancher/issues/21434

[backport] Update vendor for ssh keys on EKS

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21224
Since we load the data from ClusterTemplateRevision CR, all field names that are of type reference and ending in *Name need to be converted back in the norman style *Id names so that the create cluster API handles them.

Convert the *Name fields from template data to *Id field before creating cluster

---

app/role_data.go
tests/integration/requirements.txt
tests/integration/suite/pipeline_common.py
tests/integration/suite/test_pipeline.py

Fix flake8 validation issues and re-submit of https://github.com/rancher/rancher/pull/20443

[Pipeline] Add sourcecodecred/repo rules to user-base role

---

pkg/api/customization/clusterregistrationtokens/formatter.go

**Issue:**
https://github.com/rancher/rancher/issues/20773
**todo:**

[Windows] Support to run Windows worker adding command on PowerShell

---

pkg/controllers/user/logging/controller.go
pkg/controllers/user/logging/deployer/appdeployer.go
pkg/controllers/user/logging/deployer/deployer.go
pkg/controllers/user/logging/deployer/testerdeployer.go

Problem:
logging not use docker root in cluster
Solution:
add docker root when enable logging
Issue:
https://github.com/rancher/rancher/issues/21112

Fixing docker root not set in logging

---

pkg/api/customization/clustertemplate/utils.go
pkg/api/store/cluster/cluster_store.go
pkg/api/store/clustertemplate/store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21328
https://github.com/rancher/rancher/issues/21142

Validate k8sversion format during clusterTemplateRevision creation

---

app/role_data.go
pkg/api/customization/kontainerdriver/actionhandler.go
pkg/api/customization/kontainerdriver/formatter.go
pkg/api/server/managementstored/setup.go
pkg/controllers/management/kontainerdrivermetadata/data.go
pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
pkg/settings/setting.go

add roles, refresh action and calculate url based on latest commit
rancher/rancher#21296
https://github.com/rancher/rancher/issues/21310
https://github.com/rancher/types/pull/905

updates for driverMetadata

---

server/ui/ui.go

Trivial bug fix for issue #21572

Use proxy if set when fetching remote content. Resolves #21572.

---

package/Dockerfile

https://github.com/rancher/rancher/issues/21541

UI v2.2.90

---

app/machinedriver_data.go
pkg/api/customization/node/node_driver.go

https://github.com/rancher/rancher/issues/21300

mark linode active by default

---

pkg/controllers/management/kontainerdrivermetadata/data.go

https://github.com/rancher/rancher/issues/21556
https://github.com/rancher/rancher/issues/21553

driverMetadata: respect both minor and major k8s versions

---

README.md

- Updated Copyright year from 2018 to 2019

Updated Copyright year from 2018 to 2019 in README.md

---

pkg/controllers/user/logging/utils/fluentd.go
tests/validation/tests/v3_api/test_logging.py

Problem:
Get error when fluentd target not enable auth configure
Solution:
Return after sending test data
Issue:
https://github.com/rancher/rancher/issues/20120

[Logging]Fix fluentd target test function

---

pkg/controllers/user/alert/watcher/pod.go

Problem:
pod restart count cache was stored in cache when alert create, when server restart the cache disappeared, so couldn't get pre pod restart count
Solution:
store current pod restart count in the cache when check pod restart
Issue:
https://github.com/rancher/rancher/issues/20339

[Alerting]Fix pod restart not fire alerting after server restarted

---

vendor.conf
vendor/github.com/rancher/rke/cluster/etcd.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/services/etcd.go
vendor/github.com/rancher/rke/services/healthcheck.go
vendor/github.com/rancher/rke/services/services.go
vendor/github.com/rancher/rke/util/util.go

https://github.com/rancher/rancher/issues/21627

vendor update rancher/rke

---

tests/validation/tests/v3_api/test_secrets.py

@sowmyav27 Can you review this change?

Remove passing namespaceId parameter for project scoped secret

---

app/role_data.go
pkg/api/customization/cluster/validator.go
pkg/api/store/cluster/cluster_store.go
pkg/api/store/clustertemplate/store.go
tests/integration/suite/test_clustertemplate.py
vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/backup_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_template_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_template.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_template_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_s3backup_config.go

Types PR: https://github.com/rancher/types/pull/908
rancher/rancher#20420
rancher/rancher#21473

Add ClusterTemplates-Create globalrole, save questions on cluster

---

tests/validation/tests/v3_api/test_upgrade.py

@sowmyav27 can you review this change?

Fix upgrading app as part of post upgrade

---

pkg/controllers/management/etcdbackup/etcdbackup.go

https://github.com/rancher/rancher/issues/20859
Needs vendor of https://github.com/rancher/rke/pull/1476

Add ability to backup etcd snapshots to s3 folder

---

pkg/api/store/secret/store.go
tests/integration/suite/test_secrets.py

https://github.com/rancher/rancher/issues/14921

Parse certificates created through kubectl

---

tests/integration/suite/test_clustertemplate.py

Removing test that intermittently fails.

Remove flaky test for globalrolebinding change for create-clustertemplates role

---

tests/integration/suite/test_ingress.py
vendor.conf
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go

https://github.com/rancher/rancher/issues/20809
https://github.com/rancher/types/pull/915

Relaxed ingress name type

---

tests/integration/suite/test_workloads.py
vendor.conf
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_http_get_action.go

Address issues:
https://github.com/rancher/rancher/issues/20749
https://github.com/rancher/rancher/issues/19992
Depending on types pr: https://github.com/rancher/types/pull/895

Update vendor and tests for workload healthcheck probes

---

pkg/controllers/management/clusterprovisioner/driver.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/etcdbackup/etcdbackup.go
vendor.conf
vendor/github.com/rancher/rke/services/etcd.go

https://github.com/rancher/rancher/issues/21697

Add timestamp to snapshot files [v2.2]

---

pkg/controllers/management/etcdbackup/etcdbackup.go
vendor.conf
vendor/github.com/rancher/rke/cmd/common.go
vendor/github.com/rancher/rke/cmd/etcd.go
vendor/github.com/rancher/rke/services/etcd.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/backup_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_s3backup_config.go

Needs vendor of https://github.com/rancher/types/pull/918 / https://github.com/rancher/rke/pull/1497

[release/v2.2] Add ability to backup etcd snapshots to s3 folder

---

pkg/controllers/user/logging/controller.go
pkg/controllers/user/logging/deployer/appdeployer.go
pkg/controllers/user/logging/deployer/deployer.go

Problem:
Logging feature hasn't supported in windows yet
Solution:
Add logging windows supported
Issue:
http://github.com/rancher/rancher/issues/20510

Support collect docker stdout/stderr in windows logging

---

pkg/controllers/user/logging/generator/templatesource.go

https://github.com/rancher/rancher/issues/20675

[release/v2.2] increase log precision

---

pkg/api/server/managementstored/setup.go
pkg/api/store/globaldns/globaldnsprovider_store.go
pkg/api/store/password/store.go
pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
pkg/controllers/management/globaldns/globaldnsprovider_secret_syncer.go
pkg/controllers/management/globaldns/register.go
tests/integration/suite/test_globaldns.py

https://github.com/rancher/rancher/issues/21369

Save credentials as secrets for globaldnsprovider

---

pkg/api/customization/cluster/actions_kubeconfig.go
pkg/kubeconfig/kubeconfig.go
pkg/kubeconfig/templates.go

This time with support for local endpoints

Use ClusterName for KubeConfig User's name (again)

---

pkg/api/customization/roletemplatebinding/validator.go
tests/integration/suite/test_role_template.py

Backport: https://github.com/rancher/rancher/pull/21775

Disable editing non matching context binding

---

chart/values.yaml
pkg/image/export/main.go

Addresses: https://github.com/rancher/rancher/issues/20780

including busybox image in rancher-images.txt for airgap setups

---

app/machinedriver_data.go
package/Dockerfile

https://github.com/rancher/rancher/issues/21300

package linode during build

---

pkg/controllers/user/helm/common/common.go
tests/integration/suite/test_app.py

Problem:
Users are unable to successfully install apps that take longer than the helm default of 300 seconds.
Solution:
Make timeout and wait configurable for app and pass values to helm.
Issue:
https://github.com/rancher/rancher/issues/17471
intended merge order:
types -> rancher -> cli

Wait timeout fix

---

pkg/api/customization/catalog/template.go
pkg/catalog/helm/helm.go
pkg/catalog/helm/helm_test.go
pkg/httpproxy/proxy.go
pkg/httpproxy/proxy_test.go

Proxy changes

---

pkg/api/customization/catalog/template.go
pkg/httpproxy/proxy.go
pkg/httpproxy/proxy_test.go

Note: This does not include the helm parsing fix (which may not be needed in this version)

[backport] Proxy 2.1

---

vendor.conf
vendor/github.com/rancher/rke/cluster/certificates.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/cluster/reconcile.go
vendor/github.com/rancher/rke/cluster/validation.go
vendor/github.com/rancher/rke/cmd/cert.go
vendor/github.com/rancher/rke/hosts/hosts.go
vendor/github.com/rancher/rke/pki/constants.go
vendor/github.com/rancher/rke/pki/deploy.go
vendor/github.com/rancher/rke/pki/pki.go
vendor/github.com/rancher/rke/pki/services.go
vendor/github.com/rancher/rke/pki/util.go
vendor/github.com/rancher/rke/services/etcd.go

Revert "vendor update"

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/21919

Add kube apiserver proxy cluster role and binding

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/21919

[release/v2.2] Add kube apiserver proxy cluster role and binding

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/21919

[release/v2.1] Add kube apiserver proxy cluster role and binding 

---

pkg/api/customization/catalog/template.go

If the icon is a url then return the url to the browser. Otherwise,
serve the content from Rancher and build the link.

Only modify the response if the icon is a url

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/21948

Setting kubeapi proxy cluster role separately

---

pkg/api/customization/catalog/template.go

Previously, if a chart contained multiple hyphens it would break the
looking up of that chart.
Now the external id is used which has a consistent format of
catalog://?catalog=<val>&template=<val>&version=<val> which allows for
predictable lookup using the value of the template to create the tag.
This will not break since '&' is an invalid character to name a chart.

Fix parsing of charts that contain hyphens

---

pkg/controllers/user/alert/watcher/workload.go

Problem:
1. replicate number in state isn't the desired replicate number
2. convert threshold percentage to int32 will lose accurate in calculation
Solution:
get replicate number from spec and use float
Issue:
https://github.com/rancher/rancher/issues/21639

Update to get desired replicas from spec

---

vendor.conf
vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go

https://github.com/rancher/rancher/issues/20881

vendor update kontainer-engine

---

tests/integration/README.md
tests/validation/readme.md

I created integration/readme.md because readme.txt is parsed during test setup process.

update integration and validation readme's

---

pkg/auth/providers/googleoauth/goauth_helper.go
vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/alerting_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_google_oauth_config.go
vendor/github.com/rancher/types/status/status.go

Types PR: https://github.com/rancher/types/pull/934/files
https://github.com/rancher/rancher/issues/21453
Nested group membership will be disabled by default. Users can enable it using the Nested groups flag.

Allow nested membership based access for googleoauth

---

vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go

Addresses: 
https://github.com/rancher/rancher/issues/21431
_Depends on_:
https://github.com/rancher/types/pull/936

Update vendor for nodepool timeout validation

---

pkg/controllers/user/logging/generator/templatematch.go

Problem:
Could not disable hostname verify for fluentd now
Solution:
Add ssl verify enable/disable in configure file
Issue:
https://github.com/rancher/rancher/issues/18438

Add ssl verify enable/disable in configure file

---

vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go

Addresses: https://github.com/rancher/rancher/issues/21431

Update vendor for nodepool timeout max 1 year

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21752

Error out when answer is not provided for required clustertemplate question

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/22082

[v2.1] Add node subresources to api server cluster role

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/22083

[v2.2] Add node subresources to api server cluster role

---

vendor.conf
vendor/github.com/rancher/kontainer-engine/drivers/eks/templates.go

https://github.com/rancher/rancher/issues/16968

Update kontainer-engine vendor

---

vendor.conf
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/github.com/rancher/kontainer-engine/service/service.go

Includes:
* https://github.com/rancher/kontainer-engine/pull/180
* https://github.com/rancher/kontainer-engine/pull/176
* https://github.com/rancher/kontainer-engine/pull/178

upgrade kontainer-engine

---

package/jailer.sh

https://github.com/rancher/rancher/issues/21534

Check if lib64 exists before attempting to copy

---

tests/integration/suite/test_rbac.py

For pr https://github.com/rancher/rancher/pull/21922

Test for Use apiGroup for rules

---

pkg/api/customization/pipeline/pipeline.go
pkg/pipeline/remote/bitbucketcloud/client.go
pkg/pipeline/remote/bitbucketserver/client.go
pkg/pipeline/remote/github/github.go
pkg/pipeline/remote/gitlab/gitlab.go

Address issue: https://github.com/rancher/rancher/issues/17231
Problem:
1. Fails to list all branches when a pipeline repository has a large number of branches(>100).
2. It takes a long time to fetch branches and pipeline files when there are plenty of branches.
Solution:
1. Handle pagination.
2. Update branches link to get all branches. So that we can reduce API calls from n+1 to 2, one for list branches and one for getting the pipeline file in a specific branch on demand.

Fix fetching plenty of branches in pipeline

---

server/capabilities/aks_version_endpoint.go
server/capabilities/aks_virtual_networks_endpoint.go

issue: https://github.com/rancher/rancher/issues/20881
Problem:
AKS meta handlers do not support talking to different cloud environment endpoints
Solution:
Add baseURL/authBaseURL params, like how we deal with those in [KE drivers](https://github.com/rancher/kontainer-engine/blob/7804cea8b58cd0c601c92617404092356a11fe2d/drivers/aks/aks_driver.go#L122)

Add configurable endpoints to AKS meta handlers

---

pkg/controllers/user/alert/configsyncer/configsyncer.go
pkg/controllers/user/monitoring/operatorHandler.go

Problem:
After added validation to prometheus operator crd, some crd will get validation failed
Solution:
Update crd objects to match operator crd validation
Issue:
https://github.com/rancher/rancher/issues/21904

update rancher code to compatible with the prometheus operator crd validation

---

pkg/auth/providers/publicapi/login.go
pkg/settings/setting.go

Issue: https://github.com/rancher/rancher/issues/16467
UI issue: https://github.com/rancher/rancher/issues/22136
The UI will be updated at a future date to not pass this variable, no ticket needs to be created yet.

Add setting to edit user session TTL

---

app/machinedriver_data.go
package/Dockerfile

Update Linode docker machine and UI Driver

---

vendor.conf
vendor/github.com/rancher/norman/store/proxy/proxy_store.go

Related issue: https://github.com/rancher/rancher/issues/17823

Update norman vendor

---

app/machinedriver_data.go

Support private IP only configuration
Fix https://github.com/rancher/rancher/issues/22167

Update pinganyunecs driver version to v0.3.0

---

tests/integration/suite/test_app.py

Problem:
The test fails when appRevisionId is None and the error message is
unhelpful
Solution:
Wait for an appRevisionId before proceeding with the test. Update the
error message to be explicit and include the API error message for
future debugging
https://github.com/rancher/rancher/issues/22071

Refactor test_app_rollback_validation

---

.drone.yml
Dockerfile-windows.dapper
manifest-agent.tmpl
manifest.tmpl

Relates to #20804
Needs some more work at the moment - 1903 plugin images need to be built, and we need to spin up 1903 workers.

new pipeline for 1903

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/22081

Add node subresources to api server cluster role

---

pkg/api/store/clustertemplate/store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/21720#issuecomment-521759473

Remove member access type for cluster templates

---

pkg/controllers/user/logging/generator/templatefilter.go

See https://github.com/rancher/rancher/issues/15880#issuecomment-517671647
Issue:
https://github.com/rancher/rancher/issues/22219

Remove deprecated Fluentd config

---

pkg/api/store/clustertemplate/store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/22202
Will rebase once go mod changes on master are finalized.

Change error message when managing cluster templates is forbidden

---

pkg/controllers/user/endpoints/endpoints.go

The serviceEndpointController generates an annotation for NodePort services that are used by the UI to display a link to access the NodePort service. The controller originally expected only IPs for Node addresses. This fix adds support for both IP and hostname Node addresses. 
https://github.com/rancher/rancher/issues/15482

Fix service address for nodes with hostnames

---

pkg/controllers/management/node/utils.go

https://github.com/rancher/rancher/issues/22303

Forward output of docker machine rm -f to stdout

---

pkg/controllers/management/kontainerdrivermetadata/data.go

https://github.com/rancher/rancher/issues/21598
https://github.com/rancher/kontainer-driver-metadata/pull/24

make default k8s value same as UI 

---

pkg/controllers/management/kontainerdrivermetadata/data.go
pkg/controllers/management/kontainerdrivermetadata/data_getter.go

https://github.com/rancher/rancher/issues/22269

use go-version for comparison

---

go.mod
go.sum
pkg/rkenodeconfigserver/nodeserver.go
vendor/github.com/rancher/rke/cluster/defaults.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/hosts/hosts.go
vendor/github.com/rancher/rke/metadata/metadata.go
vendor/github.com/rancher/rke/pki/deploy.go
vendor/github.com/rancher/rke/services/services.go
vendor/modules.txt

Patching the missing `rancher/rke` vendor change

Windows: Update rancher/rke vendor

---

pkg/controllers/user/controllers.go

**Problem:**
The apiservice lister can't return any data by using get/list function.
The problem is that we don't start the apiservice controller
in user/controller.
**Solution:**
Enable APIService controller in user controller.
Related issue:
https://github.com/rancher/rancher/issues/20955

Start APIService controller for API usage

---

go.mod
go.sum
pkg/rkeworker/docker.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/docker/docker.go
vendor/github.com/rancher/rke/services/etcd.go
vendor/github.com/rancher/rke/services/kubeapi.go
vendor/github.com/rancher/rke/services/kubecontroller.go
vendor/github.com/rancher/rke/services/kubelet.go
vendor/github.com/rancher/rke/services/kubeproxy.go
vendor/github.com/rancher/rke/services/proxy.go
vendor/github.com/rancher/rke/services/scheduler.go
vendor/github.com/rancher/rke/services/services.go
vendor/modules.txt

This needs https://github.com/rancher/rke/pull/1556 before merging.
https://github.com/rancher/rke/issues/1520

GetProcesConfig requires Host for SELinux check

---

pkg/api/store/cluster/cluster_store.go
pkg/controllers/management/etcdbackup/etcdbackup.go

https://github.com/rancher/rancher/issues/20889

Validate S3 credentials on cluster create/update

---

.drone.yml
scripts/docker-pull-pusher.sh
scripts/istio-images-mirror

Temporary until the work associated with #21221 is done.
This mirrors istio images to the rancher docker org.

Mirror Istio images

---

pkg/api/customization/catalog/validator.go
pkg/api/customization/catalog/validator_test.go
tests/integration/suite/test_catalog.py

This will also lowercase URL scheme where possible

Error on invalid catalog url

---

package/windows/bootstrap.ps1
package/windows/cleanup.ps1
package/windows/utils.psm1

Clean up stale networks before adding Windows agent
**Issues:**
https://github.com/rancher/rancher/issues/22400

Clean up stale networks before adding Windows agent

---

go.mod
go.sum
pkg/pipeline/engine/jenkins/convert.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/tools_system_images.go
vendor/modules.txt

Related issue: https://github.com/rancher/rancher/issues/22057
Depend on: https://github.com/rancher/types/pull/950 https://github.com/rancher/pipeline-tools/pull/16

Support custom envvar substitution in pipeline publishcatalog steps

---

package/windows/bootstrap.ps1

**Problem:**
Could not setup agent on the Azure small disk series OS system.
**Solution:**
Reduce the amount of the check value.
**Issue:**
https://github.com/rancher/rancher/issues/22472

Adjust the check value of Windows disk size

---

pkg/controllers/user/nodesyncer/nodessyncer.go

https://github.com/rancher/rancher/issues/22480
https://github.com/rancher/rancher/issues/21857

Stop nodesycner reconcile during cluster restore

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/21649

change apis endpoints for system templates to work with k8s 1.16

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/certificates.go
vendor/github.com/rancher/rke/cmd/common.go
vendor/github.com/rancher/rke/pki/deploy.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/20381

go mod updates

---

pkg/controllers/user/alert/configsyncer/configsyncer.go

issue: https://github.com/rancher/rancher/issues/17962

Add SendResolved configuration to Notifier

---

pkg/controllers/user/rbac/podsecuritypolicy/metadata.go

https://github.com/rancher/rancher/issues/22539

Update psp apiversion

---

pkg/api/customization/kontainerdriver/actionhandler.go
pkg/api/customization/kontainerdriver/formatter.go
tests/integration/suite/test_kontainer_drivers.py

https://github.com/rancher/rancher/issues/22463

Separate link for windows system images

---

pkg/api/customization/kontainerdriver/actionhandler.go

https://github.com/rancher/rancher/issues/22463
The pr for having a separate link to download windows system images list is already merged.

Include windows images only for k8s 1.14 and up

---

pkg/controllers/management/kontainerdrivermetadata/data.go

for data that is not present in vendored RKE, we should allow updates to templates and service options. 
https://github.com/rancher/rancher/issues/22489

allow updates for non-vendored metadata

---

app/global_namespace.go
pkg/catalog/git/git.go
pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
pkg/settings/setting.go

- sync only if interval!=0 and hash changes
- git clone instead of using raw github content
- updated log msgs
https://github.com/rancher/rancher/issues/22483
https://github.com/rancher/rancher/issues/22329

driver metadata changes

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/22617

Bump vendor for rke and kontainer-driver-metadata

---

pkg/controllers/user/alert/deployer/notification_template.go

Issue: https://github.com/rancher/rancher/issues/17962
So as to make resolved notifications recognizable.

Add "[Resolved]" to notification title on resolved

---

pkg/controllers/management/etcdbackup/etcdbackup.go

Addresses: https://github.com/rancher/rancher/issues/19875
**Problem:**
Number of snapshots configured will be available by 1 less for a short window.
**Root cause:**
The time to delete is based on every tick (5 min) but not from the last successful backup.
**Fix:**
Don't calculate the window based on current time, but based on last backup time.

fix etcd backup cleanup issue

---

tests/integration/suite/test_rbac.py

Issue: https://github.com/rancher/rancher/issues/18874

Fix flakey test_project_owner

---

app/role_data.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/22645

Users can create new revisions for a cluster template if they have owner access

---

scripts/istio-images-mirror

**Problem:**
Missing istio coredns mirror image
https://github.com/rancher/rancher/issues/22651

Add istio coredns mirror image

---

pkg/controllers/management/clusterprovisioner/driver.go
pkg/controllers/management/clusterprovisioner/provisioner.go

https://github.com/rancher/rancher/issues/22670
Adding a worker node to an RKE cluster does not lead to rke up.
But the provisioner controller still calls the update, and sets the
taints capability after it. This commit checks if the update actually led
to rke up and sets taints capability based on that

Add taints capability only on rke up

---

package/Dockerfile
package/Dockerfile.agent

Addresses: https://github.com/rancher/rancher/issues/22658

Use upstream kubectl in server image

---

scripts/istio-images-mirror

Mirror prometheus operator images
They will be used in https://github.com/rancher/system-charts/pull/86
Issue:
https://github.com/rancher/rancher/issues/22488

Mirror prometheus operator images

---

pkg/controllers/management/clusterprovisioner/provisioner.go

https://github.com/rancher/rancher/issues/22773

Set updateTriggered to true on cluster create

---

pkg/api/store/cluster/cluster_store.go

https://github.com/rancher/rancher/issues/22711

Relax s3 validation

---

pkg/image/export/main.go

take unneeded tests out of docker commands

---

pkg/api/customization/kontainerdriver/actionhandler.go
pkg/api/server/managementstored/setup.go
pkg/image/export/main.go
pkg/image/resolve.go

https://github.com/rancher/rancher/issues/22644
Types PR: https://github.com/rancher/types/pull/974

Make image list from UI match release page list

---

pkg/api/customization/catalog/store.go
pkg/api/customization/catalog/template.go
pkg/api/server/managementstored/setup.go
tests/integration/suite/test_catalog.py

Problem:
Templates need their versionsLinks updated based off the rancher server
for both list and watch calls
Solution:
Add a Transformer to add the links and move the logic out of a
formatter
https://github.com/rancher/rancher/issues/22835

Update template to use a store

---

pkg/api/controllers/dynamicschema/dynamicschema.go

https://github.com/rancher/rancher/issues/22888

set default value for password fields

---

pkg/controllers/management/nodepool/nodepool.go
pkg/controllers/management/nodepool/nodepool_test.go
pkg/controllers/user/nodesyncer/nodessyncer.go

These commits help to improve worker node provisioning by reducing unnecessary updates
Addresses https://github.com/rancher/rancher/issues/22669

Improve worker node provisioning

---

go.mod
go.sum
vendor/github.com/rancher/types/mapper/credentialmapper.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/22832

vendor update types

---

go.mod
go.sum
vendor/github.com/rancher/types/apis/management.cattle.io/v3/tools_system_images.go
vendor/modules.txt

Issue: https://github.com/rancher/rancher/issues/22164

Update types vendor

---

pkg/controllers/management/kontainerdrivermetadata/data_getter.go
pkg/rkenodeconfigserver/nodeserver.go

https://github.com/rancher/rancher/issues/22870

Fix missing svcOptions for windows nodes

---

pkg/controllers/management/clusterprovisioner/provisioner.go

Fix for https://github.com/rancher/rancher/issues/21695
Looking at adding a unit test since this logic sits in provisioner.go

Setting KubernetesVersionsDeprecated needs to be unmarshalled

---

pkg/auth/tokens/manager_test.go

Tests for stream logic: https://github.com/rancher/rancher/pull/22697

Test stream logic

---

pkg/api/customization/catalog/validator.go
pkg/api/customization/catalog/validator_test.go
tests/integration/suite/test_catalog.py

Revert "Error on invalid catalog url"

---

pkg/api/server/managementstored/setup.go
pkg/auth/tokens/manager.go

Revert "Backport (2.2): Add logic to stream"

---

vendor.conf
vendor/github.com/rancher/norman/pkg/remotedialer/types.go

Backport: https://github.com/rancher/remotedialer/pull/5
Backport Issue: https://github.com/rancher/rancher/issues/22947

Increase ping wait to 1 minute instead of 10 seconds

---

pkg/controllers/user/nodesyncer/nodessyncer.go

https://github.com/rancher/rancher/issues/22942

Skip syncing labels when NodeConfig is nil

---

package/windows/bootstrap.ps1

Saw some text go by today that was written by a non-native English speaker. This PR cleans up some spelling and grammar mistakes.

correct log alerts

---

pkg/image/export/main.go

**Problem:**
Getting an error `refusing to amend an existing manifest list with no
--amend flag` when re-run `rancher-load-images.sh`
**Solution:**
- Add `--amend` option to create manifest
- Add `--purge` option to push manifest
https://github.com/rancher/rancher/issues/22966

Allow modifying the image manifest

---

pkg/api/store/cluster/cluster_store.go
pkg/api/store/clustertemplate/store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/22970
Trying to check the drone build with a new PR and also get more logs from the drone failure

Access check for clustertemplaterevision while creating cluster

---

server/Dockerfile

https://github.com/rancher/rancher/issues/22471

cli v0.6.14-rc1 for rancher 1.6

---

tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/23034

Flaky test fixes

---

package/windows/execute.ps1

**Problem:**
certoc.exe only accept the first cert of the certificate file.
**Solution:**
Use a loop to iterate per certificate from the file.
P.S.: The logic of this part is lost during refactoring. Patching back as the same as https://github.com/rancher/rancher/commit/45af0e6c3ab6cf70b51a7f63d4b5381c72a64efc#diff-b7a68d3a8052546f5539c0f2661ae672 but using `certoc.exe` to import certificates instead of `Import-Certificate` in the nanoserver.
**Issue:**
Reopen: https://github.com/rancher/rancher/issues/20436

Fix failed to add Windows worker with intermediary certificates

---

pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/23097

Add debug logging on cluster dialers

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_app.py
tests/validation/tests/v3_api/test_upgrade.py

@sowmyav27 @jiaqiluo Could you please review the changes?
1. Introduced get_defaut_question_answers() to getting all questions with default answers for a template version
2. Fixed flake8 errors in test_app
3. Made use of  get_defaut_question_answers() in test_upgrade scripts.

Method for getting all questions with default answers for a template version

---

pkg/controllers/management/nodepool/nodepool.go
pkg/controllers/management/nodepool/nodepool_test.go

Backport PR: https://github.com/rancher/rancher/pull/22807
Backport Issue: https://github.com/rancher/rancher/issues/23081

[Backport] 2.2: Scaling mystery

---

pkg/api/server/managementstored/setup.go
pkg/api/store/globalrolebindings/globalrolebinding_store.go
pkg/api/store/roletemplate/store.go
pkg/controllers/user/rbac/legacy_grb_cleaner.go
pkg/controllers/user/rbac/legacy_rt_cleaner.go
tests/integration/suite/test_users.py

Backport: https://github.com/rancher/rancher/pull/22521
Backport Issue: https://github.com/rancher/rancher/issues/22512

[Backport] 2.2: Cleanup grb 2.2

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_multi_cluster_app.py

Multiclusterapp test cases
One test case - test_multi_cluster_rolling_upgrade took about 1.5 hours, so I have commented out that piece of code.
Made few changes to Tiffany's code.

Validation tests for Multicluster app

---

pkg/auth/tokens/manager_test.go

Backport: https://github.com/rancher/rancher/pull/22944

[Backport] 2.2: Test stream logic

---

pkg/api/customization/catalog/validator.go
pkg/api/customization/catalog/validator_test.go
tests/integration/suite/test_catalog.py

Revert "Revert "Error on invalid catalog url""

---

vendor.conf
vendor/github.com/rancher/rke/templates/nginx-ingress.go

Rke nginx image needs to be updates

---

pkg/api/customization/workload/workload.go

https://github.com/rancher/rancher/issues/23269
During workload rollback, for deployments under apps/v1, we need to get
replicaset spec.
The rollback handler was getting replicaset from cache, but for HA setups
sometimes the replicaset wasn't getting returned from cache.
This commit adds fallback logic to fetch the replicaset from etcd if fetching
from cache fails

Fetch replicaset from etcd if not found in cache

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_app.py

Validation test cases for apps
Includes one RBAC test case: `test_app_project_scope_deploy`
Test cases pending from Tiffany's PR (Original):
- Cluster scope app deploy
- Project scope app delete
- Cluster scope app delete

Test cases for app validation

---

tests/validation/tests/v3_api/Jenkinsfile
tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade_multiple

Add support for credentials plugin
Change names of jobs to migration job names
Small bugfixes for single click upgrades

Automation - Update pipelines

---

Dockerfile.dapper
package/Dockerfile
package/jailer.sh
pkg/controllers/user/helm/common.go
pkg/controllers/user/helm/common/common.go

Problem:
Helm needs to be updated and renamed to stop name colisions
Solution:
Rebase helm, update all calls to use rancher-helm
https://github.com/rancher/rancher/issues/21070
https://github.com/rancher/rancher/issues/22684

Update helm version

---

Dockerfile.dapper
package/Dockerfile
package/jailer.sh
pkg/controllers/user/helm/common.go
pkg/controllers/user/helm/common/common.go

Revert "Update helm version"

---

pkg/clustermanager/manager.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/dialer/factory.go

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Correct misspell warnings

---

pkg/api/store/app/store.go
tests/integration/suite/test_project_catalog.py

[2.3] Add check for app creation

---

pkg/agent/main.go

https://github.com/rancher/rancher/issues/22419

Add certificate check and detail when agent starts

---

README.md

i'm pretty sure the PR workflow is somewhat different, but someone will notice it...

bump to v2.3.1

---

go.mod
go.sum
pkg/api/server/userstored/setup.go
tests/integration/suite/test_istio.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_client.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_gateway.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_gateway_spec.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_port.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_server.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_tls_options.go
vendor/github.com/rancher/types/compose/zz_generated_compose.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/20892
Depend on types pr: https://github.com/rancher/types/pull/999

[2.3.2] Add Istio gateway store

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/23485

use master branch of metadata only for release server versions

---

pkg/controllers/user/nodesyncer/cordonfieldssyncer.go

https://github.com/rancher/rancher/issues/23333
The PR won't solve the ^ issue, but it should produce more clear logs for debugging.

Node drain: error logging nit fixes

---

pkg/api/store/app/store.go
tests/integration/suite/test_project_catalog.py

Based off of https://github.com/rancher/rancher/pull/23102

Forwardport: Add check for app creation

---

pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/23331
Master pr: https://github.com/rancher/rancher/pull/23330

Fall back to node dialer when cluster one fails, for imported clusters

---

pkg/features/feature.go

Change istio-virtual-service-ui to true by default
https://github.com/rancher/rancher/issues/23582

[2.3.2] Change istio-virtual-service-ui to true by default

---

package/Dockerfile
pkg/agent/main.go
pkg/api/controllers/dynamiclistener/listener_controller.go
pkg/api/controllers/dynamiclistener/listener_controller_test.go
pkg/api/store/secret/store.go
pkg/catalog/helm/helm.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
tests/integration/suite/test_secrets.py

https://github.com/rancher/rancher/issues/23620
https://github.com/rancher/rancher/issues/23622
https://github.com/rancher/rancher/issues/23623
https://github.com/rancher/rancher/issues/23634

[forwardport] cherry-picks

---

go.mod
go.sum
tests/integration/suite/test_secrets.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/registry_credential.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema_secrets.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/types.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_client.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_gateway.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_gateway_spec.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_port.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_registry_credential.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_server.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_tls_options.go
vendor/github.com/rancher/types/compose/zz_generated_compose.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/23686
Depends on types PR: https://github.com/rancher/types/pull/1014

[forwardport ]Auth field in registry secret

---

pkg/api/server/userstored/setup.go
tests/integration/suite/test_istio.py

https://github.com/rancher/rancher/issues/23334
Depend on types pr: https://github.com/rancher/types/pull/1000

[forwardport] Add Istio gateway store - master

---

pkg/api/customization/cluster/actionhandler.go
pkg/api/customization/cluster/actions_rketemplate.go
pkg/api/customization/cluster/formatter.go
pkg/api/customization/clustertemplate/cluster_template.go
pkg/api/customization/globalnamespaceaccess/access_common.go
pkg/api/server/managementstored/setup.go
tests/integration/suite/test_cluster_defaults.py
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/22992

[2.3.3] Save a running cluster to an RKE template

---

pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/23331
Master pr: https://github.com/rancher/rancher/pull/23330

[release/v2.3] Fall back to node dialer when cluster one fails, for imported clusters

---

pkg/controllers/management/node/controller.go
tests/integration/suite/test_node.py

https://github.com/rancher/rancher/issues/23743

Add newline to all file content fields

---

tests/validation/tests/v3_api/test_cluster_templates.py

@sangeethah : Please review. 
https://github.com/rancher/rancher/issues/23328

Test case for cluster templates

---

go.mod
go.sum
pkg/api/customization/project/project_actions.go
pkg/api/server/managementstored/setup.go
pkg/api/store/cluster/cluster_store.go
pkg/controllers/management/cluster/clustercontroller.go
pkg/controllers/management/cluster/clustercontroller_test.go
tests/integration/suite/test_cluster_defaults.py
tests/integration/suite/test_pod_security_policies.py
vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_capabilities.go
vendor/modules.txt

Forwardport:
https://github.com/rancher/rancher/pull/23486
https://github.com/rancher/rancher/pull/23815
Forwardport Issues:
https://github.com/rancher/rancher/issues/23705
https://github.com/rancher/rancher/issues/23862

[Forwardport] 2.4: Capability override

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/hosts/dialer.go
vendor/modules.txt

Vendoring in latest rke commit 
https://github.com/rancher/rancher/issues/23847

Vendored in latest rke

---

pkg/rkenodeconfigserver/nodeserver.go
pkg/tunnelserver/tunnel.go

https://github.com/rancher/rancher/issues/22849

[v2.3] Add using RequestedHostname to find machines

---

pkg/rkenodeconfigserver/nodeserver.go
pkg/tunnelserver/tunnel.go

https://github.com/rancher/rancher/issues/23716

Add using RequestedHostname to find machines

---

go.mod
go.sum
tests/integration/suite/test_deployment.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_container_port.go
vendor/github.com/rancher/types/mapper/container_ports.go
vendor/modules.txt

Backport pr for https://github.com/rancher/rancher/pull/23611

[backport] Respect natively set deployment host port 

---

go.mod
go.sum
tests/integration/suite/test_deployment.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_container_port.go
vendor/github.com/rancher/types/mapper/container_ports.go
vendor/modules.txt

This PR is a type vendor update + the integration test
https://github.com/rancher/types/pull/1007
https://github.com/rancher/rancher/issues/23375

Respect natively set deployment host port 

---

tests/integration/suite/test_pipeline.py

Address issue https://github.com/rancher/rancher/issues/23757
Problem:
Test failure happens when try to get source code provider config before they are created for a new project
Solution:
Add retry and timeout mechanism

Add retry & timeout in pipeline tests

---

tests/integration/suite/test_pod_security_policies.py

**Problem:**
If a 409 error is encountered the test will break. Encountering a 409 is expected to occur occasionally and should not lead to a failed test.
**Solution:**
Added retry logic to test_pod_security_policy_template_del
**Issue:**
https://github.com/rancher/rancher/issues/23930

Fix flaky PSP test

---

pkg/controllers/user/nodesyncer/nodessyncer.go

https://github.com/rancher/rancher/issues/23571

Bug fix in node.requested resources calculation

---

go.mod
go.sum
tests/integration/suite/test_deployment.py
vendor/github.com/rancher/types/mapper/container_ports.go
vendor/modules.txt

To validate https://github.com/rancher/rancher/issues/23375#issuecomment-550438582

Test for workload with host port

---

pkg/controllers/user/nodesyncer/nodessyncer.go
pkg/node/node.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/23394

Skip node sync for specific nodes

---

main.go

https://github.com/rancher/rancher/issues/23981

[release/v2.3] ACME_DOMAIN environment variable missing (#20407)

---

pkg/controllers/user/nodesyncer/nodessyncer.go
pkg/node/node.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/23394

[release/v2.3] Skip node sync for specific nodes

---

pkg/api/store/cluster/cluster_store.go

https://github.com/rancher/rancher/issues/23702

Put weave password back in cluster store on edit

---

pkg/api/store/cluster/cluster_store.go

https://github.com/rancher/rancher/issues/24000

[release/v2.3] Put weave password back in cluster store on edit

---

pkg/api/customization/vsphere/handler.go
pkg/api/customization/vsphere/listers.go

Cleaned up VM endpoint to not show network and hosts too.

Added vSphere Datastore Clusters Lookup Endpoint

---

pkg/controllers/management/nodetemplate/nodetemplate.go

Adds a normalizer which updates legacy vSphere node templates to proper vmware object paths

[v2.3.3] Vsphere Legacy Normalizer

---

pkg/controllers/management/nodetemplate/nodetemplate.go

Adds a normalizer which updates legacy vSphere node templates to proper vmware object paths

[master] added vsphere legacy template normalizer

---

go.mod
go.sum
pkg/controllers/management/etcdbackup/etcdbackup.go
vendor/github.com/rancher/rke/services/etcd.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/22900

Do s3 snapshot remove from managed cluster side

---

pkg/api/customization/catalog/catalog.go
tests/integration/suite/test_catalog.py

https://github.com/rancher/rancher/issues/23636
Depends on https://github.com/rancher/types/pull/1008

[forwardport] Update catalog refresh to return catalogs

---

go.sum
pkg/api/customization/cluster/actionhandler.go
pkg/api/customization/cluster/actions_rketemplate.go
pkg/api/customization/cluster/formatter.go
pkg/api/customization/cluster/utils.go
pkg/api/customization/clustertemplate/cluster_template.go
pkg/api/server/managementstored/setup.go
tests/integration/suite/test_cluster_defaults.py
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/23608
Types PR: https://github.com/rancher/types/pull/1010

[forwardport] Save a running cluster to an RKE template

---

pkg/controllers/user/noderemove/nodes.go
pkg/controllers/user/nodesyncer/nodessyncer.go
pkg/node/node.go

To resolve the removal use case https://github.com/rancher/rancher/issues/23394#issuecomment-552602152

Skip v1.node removal for objects with specific nodename

---

pkg/controllers/management/nodepool/nodepool.go

This PR makes nodepool controller to do namespaces requests as described in issue  https://github.com/rancher/rancher/issues/23934
It depends on https://github.com/rancher/norman/pull/318 and generated rancher/types (not included in vendor in this PR).

Make ListNamespaced request in nodepool controller

---

go.mod
go.sum
vendor/golang.org/x/crypto/acme/acme.go
vendor/golang.org/x/crypto/acme/autocert/autocert.go
vendor/golang.org/x/crypto/acme/autocert/cache.go
vendor/golang.org/x/crypto/acme/http.go
vendor/golang.org/x/crypto/acme/jws.go
vendor/golang.org/x/crypto/acme/rfc8555.go
vendor/golang.org/x/crypto/acme/types.go
vendor/golang.org/x/crypto/acme/version_go112.go
vendor/golang.org/x/crypto/ed25519/ed25519.go
vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
vendor/golang.org/x/crypto/internal/chacha20/asm_ppc64le.s
vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
vendor/golang.org/x/crypto/internal/chacha20/chacha_ppc64le.go
vendor/golang.org/x/crypto/ssh/common.go
vendor/golang.org/x/crypto/ssh/kex.go
vendor/golang.org/x/crypto/ssh/messages.go
vendor/golang.org/x/crypto/ssh/server.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/23392

Vendor update for crypto

---

tests/validation/tests/v3_api/test_app.py
tests/validation/tests/v3_api/test_vmwarevsphere_driver.py

@luthermonson @bmdepesa Could you please review the changes?

Rename tests and made changes to vsphere provsiioning cases to use siting libraries for validation.

---

pkg/api/server/managementstored/setup.go
pkg/api/store/setting/store.go
pkg/controllers/management/kontainerdrivermetadata/data.go
tests/integration/suite/test_kontainer_drivers.py

https://github.com/rancher/rancher/issues/24146

trigger refresh after user updates metadata settings

---

app/machinedriver_data.go
pkg/api/store/nodetemplate/store.go
pkg/controllers/management/node/controller.go
tests/integration/suite/test_node.py

https://github.com/rancher/rancher/issues/23060

add region to ec2 cloud credential

---

tests/validation/tests/v3_api/common.py

@luthermonson Could you review the changes?

Fix ingress test failures

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/23795

Do not allow upgrade to a revision that might disable monitoring

---

go.mod
go.sum
tests/integration/suite/test_global_role_bindings.py
vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
vendor/modules.txt

**Forwardport:** https://github.com/rancher/rancher/pull/24145

[Forwardport] 2.4: Update types and add GRB test

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/defaults.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/modules.txt

https://github.com/rancherlabs/rancher-security/issues/362

vendor latest rke

---

pkg/api/customization/kontainerdriver/actionhandler.go
pkg/api/server/managementstored/setup.go
pkg/api/store/setting/store.go
pkg/controllers/management/kontainerdrivermetadata/data.go
pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
tests/integration/suite/test_kontainer_drivers.py

https://github.com/rancher/rancher/issues/24133
https://github.com/rancher/rancher/issues/24132

forward port issues 

---

tests/validation/tests/v3_api/test_rke_cluster_provisioning.py

Test to bring up a custom cluster with a CIS complaint cluster.yml (Can be modified when required)
No validation tests.
End of cluster provisioning, called this function - _validate_cluster_state_

CIS Scan custom cluster provisioning

---

pkg/controllers/management/kontainerdrivermetadata/data.go
tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/23774

update rancherVersionDev to 2.4

---

tests/validation/lib/aws.py
tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_import_k3s_cluster.py

Committer: ShylajaDevadiga<shylaja@rancher.com>

Add test validation to import k3s cluster to rancher

---

chart/templates/ingress.yaml
chart/templates/issuer-letsEncrypt.yaml
chart/templates/issuer-rancher.yaml
chart/tests/ingress_test.yaml
chart/tests/issuer_test.yaml
scripts/chart/test

Relies on https://github.com/rancher/helm-unittest/pull/5

check capabilities for cert-manager changes

---

tests/validation/tests/v3_api/common.py

@soumyalj Could you review these changes ?

Fix timing issue relating to access cluster version

---

pkg/api/controllers/usercontrollers/usercontroller.go

https://github.com/rancher/rancher/pull/24245

[backport] Don't loop n^2 times on stopping clusters that aren't connected

---

tests/validation/tests/v3_api/README.md
tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/conftest.py
tests/validation/tests/v3_api/test_logging.py
tests/validation/tests/v3_api/test_secrets.py
tests/validation/tests/v3_api/test_workload.py

https://github.com/rancher/rancher/issues/24223
This introduces a new global variable `RANCHER_TEST_RBAC`, and RBAC tests will be executed when `RANCHER_TEST_RBAC` is set to be `True`

Automation - RBAC for Workloads

---

tests/validation/tests/v3_api/test_group_grb.py

Note: this branch is based off group GRB branch which is where first three commits come from
**Issue:** https://github.com/rancher/rancher/issues/24076

GRB validation tests

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_cluster_templates.py

Test case to export a RKE template

---

pkg/controllers/management/etcdbackup/etcdbackup.go

https://github.com/rancher/rancher/issues/24347
https://github.com/rancher/rancher/issues/23231

Etcd backup to use its own http transport

---

tests/validation/images/container-utils/requirements.txt
tests/validation/requirements.txt
tests/validation/requirements_v3api.txt

Ran flask app in container-utils manually successfully
Ran most of v3_api tests successfully

Update versions for validation requirements

---

chart/templates/ingress.yaml
chart/templates/issuer-letsEncrypt.yaml
chart/templates/issuer-rancher.yaml
chart/tests/ingress_test.yaml
chart/tests/issuer_test.yaml
scripts/chart/test

[2.3] check capabilities for cert-manager changes

---

pkg/api/customization/project/project_actions.go
pkg/api/server/managementstored/setup.go
tests/integration/suite/conftest.py
tests/integration/suite/test_pod_security_policies.py

issue: https://github.com/rancher/rancher/issues/24391
forward this issue: https://github.com/rancher/rancher/issues/23931
and this  PR:  https://github.com/rancher/rancher/pull/23932

[forward] add check for invalid podSecurityPolicyTemplateId

---

chart/templates/ingress.yaml
chart/templates/issuer-letsEncrypt.yaml
chart/templates/issuer-rancher.yaml
chart/tests/ingress_test.yaml
chart/tests/issuer_test.yaml
scripts/chart/test

Revert "[2.3] check capabilities for cert-manager changes"

---

pkg/controllers/management/etcdbackup/etcdbackup.go

https://github.com/rancher/rancher/issues/22900

use correct snapshot name on its removal

---

pkg/api/customization/clusterregistrationtokens/formatter.go
pkg/api/customization/clusterregistrationtokens/formatter_test.go
pkg/api/customization/clusterregistrationtokens/import.go
pkg/api/server/managementstored/setup.go
pkg/cluster/private_registry.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/node/controller.go
pkg/image/resolve.go
pkg/rkenodeconfigserver/nodeserver.go
pkg/systemtemplate/import.go
pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/20029

Private registry support for cluster/node agent

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
pkg/api/controllers/dynamiclistener/listener_controller.go
pkg/api/controllers/dynamiclistener/listener_controller_test.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go

https://github.com/rancher/rancher/issues/23464

[release/v2.2] backport "resync cluster on cacert change"  and "ingress TLS fix in charts"

---

vendor.conf
vendor/github.com/rancher/rke/Dockerfile.dapper
vendor/github.com/rancher/rke/templates/canal.go

To bring in the fix for https://github.com/rancher/rancher/issues/23558

[release/v2.2] rke vendor update

---

pkg/api/customization/clusterregistrationtokens/formatter.go
pkg/api/customization/clusterregistrationtokens/formatter_test.go
pkg/api/customization/clusterregistrationtokens/import.go
pkg/api/server/managementstored/setup.go
pkg/cluster/private_registry.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/node/controller.go
pkg/image/resolve.go
pkg/rkenodeconfigserver/nodeserver.go
pkg/systemtemplate/import.go
pkg/systemtemplate/template.go

also rancher agent (including custom node registration command)
https://github.com/rancher/rancher/issues/20029

[forwardport] Private registry support for cluster/node agent

---

tests/integration/suite/common.py
tests/integration/suite/test_cluster_catalog.py

**Problem**
Flakey test due to timing issue
**Solution**
Increased timeout
**Issue**
#24446

[flakey test] test_invalid_catalog_charts

---

tests/integration/suite/common.py
tests/integration/suite/test_cluster_catalog.py

**Problem**
Flakey test due to timing issue
**Solution**
Increased timeout
**RelatedPR**
#24448
**Issue**
#24446

[forwardport][flakey test] test_invalid_catalog_charts

---

pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/22006
In proxy setup, GKE cluster will fail registration with Rancher, at the user cluster controller registration point. 
The reason for the user controller registration failure is in the way we build the dialer to the hosted k8s clusters. All the requests should go directly to hosted k8s api endpoint, but this condition will never be true if proxy environment is set:
https://github.com/rancher/rancher/blob/master/pkg/dialer/factory.go#L139
address will be a proxy ip address, and hostPort is the k8s api endpoints, and they'll never match

Hosted cluster dialer fix to work with proxy

---

package/Dockerfile

Updates the UI for API to a version with various fixes
rancher/rancher#24261

Update API UI version

---

go.mod
go.sum
pkg/controllers/user/logging/generator/template.go
pkg/controllers/user/logging/generator/templatefilter.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_network_config.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging_spec.go
vendor/modules.txt

Problem:
JSON parsing was dropped when the version of K8s metadata plugin was updated
Solution:
Add a flag to turn this option back on 
https://github.com/rancher/rancher/issues/23646

[master] Add JSON parsing option to fluentd config

---

go.mod
go.sum
pkg/controllers/user/logging/generator/template.go
pkg/controllers/user/logging/generator/templatefilter.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging_spec.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/23646

[2.3] Add JSON option for logging output

---

pkg/api/customization/alert/alert_action.go
pkg/api/customization/alert/notifier_action.go
pkg/api/server/managementstored/setup.go
pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
pkg/notifiers/sender.go

https://github.com/rancher/rancher/issues/22578

use cluster dialer

---

pkg/api/customization/alert/alert_action.go
pkg/api/customization/alert/notifier_action.go
pkg/api/server/managementstored/setup.go
pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
pkg/notifiers/sender.go

https://github.com/rancher/rancher/issues/22578

[backport 2.3] use cluster dialer

---

pkg/controllers/user/nodesyncer/nodessyncer.go

Backport PR https://github.com/rancher/rancher/pull/24192
Related Issue: https://github.com/rancher/rancher/issues/24123
Related Validation test PR: https://github.com/rancher/rancher/pull/24476

[2.3] [Backport] Node labels sync for all types of clusters

---

pkg/auth/providers/ldap/ldap_client.go

Some Freeipa servers seem to not return the entrydn attribute,
which we use in our query to get all details of the groups of a
logged in user. So in such cases, we will use queries with member
attribute to get all first level groups, and the nested logic we
have for openldap to retrieve nested parent groups.
https://github.com/rancher/rancher/issues/18927

Make freeipa group membership work without entrydn

---

chart/templates/ingress.yaml
chart/templates/issuer-letsEncrypt.yaml
chart/templates/issuer-rancher.yaml
chart/tests/ingress_test.yaml
chart/tests/issuer_test.yaml
chart/values.yaml

This is working for airgap installations. Supersed https://github.com/rancher/rancher/pull/24407
Fix issue https://github.com/rancher/rancher/issues/23424

check capabilities or cert-manager version for its api changes

---

tests/validation/tests/v3_api/test_node.py

Related Pr: https://github.com/rancher/rancher/pull/24419

Add validation test for adding node label

---

pkg/controllers/management/node/controller.go
pkg/nodeconfig/config.go

Problem:
The machine config does not use updated cloud credentials for updates
and deletes
Solution:
Before running machine, update the config on disk with updated cloud
creds

Modify machine config on disk

---

pkg/auth/providers/ldap/ldap_client.go

Forward port of https://github.com/rancher/rancher/issues/18927
Some Freeipa servers seem to not return the entrydn attribute,
which we use in our query to get all details of the groups of a
logged in user. So in such cases, we will use queries with member
attribute to get all first level groups, and the nested logic we
have for openldap to retrieve nested parent groups.

Forwardport: Make freeipa group membership work without entrydn

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/network.go
vendor/github.com/rancher/rke/cluster/validation.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_network_config.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/24096

[release/v2.3] vendor update

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
tests/validation/tests/v3_api/test_workload.py

Added tests to assert the source ports on workloads with
- nodePort
- ClusterIp
- hostport
- LB

Validation tests added for source port related checks

---

pkg/catalog/manager/catalog_sync.go
pkg/catalog/manager/cluster_catalog_sync.go
pkg/catalog/manager/project_catalog_sync.go

**Problem**
Creating a Rancher catalog using charts served from Harbor is causing issues where Rancher is not updating catalog/chart information as expected. 
**Solution**
This does not resolve the issue. This will assist with future debugging when charts are not updating as expected. 
**Issues**
#23540 
#23256

[v2.3] Add debug for chart hash

---

pkg/catalog/manager/catalog_sync.go
pkg/catalog/manager/cluster_catalog_sync.go
pkg/catalog/manager/project_catalog_sync.go

**Problem**
Creating a Rancher catalog using charts served from Harbor is causing issues where Rancher is not updating catalog/chart information as expected.
**Solution**
This does not resolve the issue. This will assist with future debugging when charts are not updating as expected.
**Related PR**
#24531 
**Issues**
#23540
#23256

[forwardport] Add debug for chart hash

---

go.mod
go.sum
tests/integration/suite/test_deployment.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_container_port.go
vendor/github.com/rancher/types/mapper/container_ports.go
vendor/modules.txt

Integration tests for port fixes from https://github.com/rancher/types/pull/1053:
https://github.com/rancher/rancher/issues/24551
https://github.com/rancher/rancher/issues/24358

[backport release/v2.3] More tests for workload ports

---

tests/integration/suite/test_deployment.py

Integration tests for port fixes from https://github.com/rancher/types/pull/1053:
https://github.com/rancher/rancher/issues/24551
https://github.com/rancher/rancher/issues/24358

More tests for workload ports

---

scripts/istio-images-mirror

Requirement for PR rancher/system-charts#95

[2.3] Added thanosio/thanos:v0.9.0 docker image to mirror on Rancher org 

---

scripts/istio-images-mirror

Requirement for PR https://github.com/rancher/system-charts/pull/95

Added thanosio/thanos:v0.9.0 docker image to mirror on Rancher org

---

pkg/auth/providers/providers.go

Forward port for https://github.com/rancher/rancher/issues/20159

[Forward port] Check token in SearhPrincipals to avoid panic

---

pkg/controllers/management/globaldns/globaldns_handler.go
pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go

**Forwarding PR**
https://github.com/rancher/rancher/pull/24585
**Issue**
#24294

[forwardport] Add missing api group

---

tests/validation/lib/aws.py
tests/validation/lib/cloud_provider.py

Updated docker to 19.03
And the ubuntu image to 18.04

Updating docker and ubuntu image to the latest

---

go.sum
pkg/controllers/user/rbac/handler_base.go
pkg/controllers/user/rbac/roletemplate_handler.go
tests/integration/suite/test_role_template.py

https://github.com/rancher/rancher/issues/23658
ClusterRoleBindings are created for the inherited roles of a roleTemplate.
This commit updates them when the inherited roles on a roleTemplate are changed during the roleTemplate sync

Update crb on roleTemplate inherited roles update

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/plan.go
vendor/modules.txt

Vendoring in rke from release/v1.0

[2.3.4] rke vendor update

---

pkg/api/customization/cluster/actions_kubeconfig.go

**Forwardport:** https://github.com/rancher/rancher/pull/23912
**Forwardport Issue:** https://github.com/rancher/rancher/issues/24668

[Forwardport] 2.4: Add nil check generateKubeconfig action

---

pkg/cluster/private_registry.go
pkg/controllers/management/node/controller.go

https://github.com/rancher/rancher/issues/20029

[backport] generate correct registry auth for private registry

---

scripts/istio-images-mirror

**Problem**
Calico images need to be mirrored into rancher to ensure accessibility 
**Solution**
Add needed calico version to be mirrored
**Issue** 
#24662

Mirror calico images

---

tests/validation/tests/v3_api/test_bkp_restore.py

to fix the needs_cluster execution logic.

moving the cluster_cleanup from the existing cluster fixture

---

go.mod
go.sum
pkg/controllers/management/clusterdeploy/clusterdeploy.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_spec_base.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
vendor/modules.txt

Adds a map of downstream cluster agents to check to keep them in sync. Especially important during upgrade/rollback process.

[forwardport] Agent tracking master

---

package/Dockerfile

https://github.com/rancher/ui/releases/tag/v2.3.28

Bumping UI version to 2.3.28.

---

tests/validation/lib/aws.py

add new AMIs: 
- ubuntu-1804-docker-1903, 
- ubuntu-1604-docker-1903

add new AMIs 

---

package/Dockerfile
scripts/package

Revert "v2.4-preview1 branches"

---

tests/validation/lib/aws.py

add rancher OS 1.5.4 1.5.5 AMI

add rancher OS 1.5.4 1.5.5 AMI

---

package/run.sh
pkg/controllers/user/rbac/prtb_handler.go
pkg/controllers/user/rbac/reconcile_roletemplate.go
pkg/controllers/user/rbac/roletemplate_handler.go
tests/integration/suite/test_role_template.py

https://github.com/rancher/rancher/issues/23658

forwardport PRs 

---

pkg/controllers/management/node/controller.go
pkg/jailer/jailer.go
pkg/nodeconfig/config.go

Backport of https://github.com/rancher/rancher/pull/24811/
https://github.com/rancher/rancher/issues/24695

[release/v2.3] Create a jail first when node gets created

---

pkg/controllers/management/etcdbackup/etcdbackup.go

Backport of https://github.com/rancher/rancher/pull/24398
https://github.com/rancher/rancher/issues/24775

[release/v2.3] use correct snapshot name on its removal

---

chart/templates/issuer-letsEncrypt.yaml

[2.3] Updated helm chart to use Issuer instead of clusterIssuer 

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_windows_service_options.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/24830

Vendor changes

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_windows_service_options.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/24830

[2.3] Vendor changes

---

pkg/api/customization/vsphere/listers.go

https://github.com/rancher/rancher/issues/24840
The govmomi library was not recursively pulling vm folders so rewrote the folder lister to pull all folders and only show return results prefixed by `/<datacenter>/vm/` which shows an entire list now of all sub-folders.
e.g. 
```
{
"data": [
"",
"/RNCH-HE-FMT/vm/Discovered virtual machine",
"/RNCH-HE-FMT/vm/vm folder"
]
}
```
Will now be
```
{
"data": [
"",
"/RNCH-HE-FMT/vm/Discovered virtual machine",
"/RNCH-HE-FMT/vm/Discovered virtual machine/asdf",
"/RNCH-HE-FMT/vm/Discovered virtual machine/asdf/fdsa",
"/RNCH-HE-FMT/vm/vm folder",
"/RNCH-HE-FMT/vm/vm folder/level 1b",
"/RNCH-HE-FMT/vm/vm folder/level 1b/level 2bb",
"/RNCH-HE-FMT/vm/vm folder/level 1b/level 2ba",
"/RNCH-HE-FMT/vm/vm folder/level 1a",
"/RNCH-HE-FMT/vm/vm folder/level …
```

[v23] vSphere VM Folder Fix

---

pkg/api/customization/vsphere/listers.go

https://github.com/rancher/rancher/issues/24840
The govmomi library was not recursively pulling vm folders so rewrote the folder lister to pull all folders and only show return results prefixed by `/<datacenter>/vm/` which shows an entire list now of all sub-folders.
e.g. 
```
{
"data": [
"",
"/RNCH-HE-FMT/vm/Discovered virtual machine",
"/RNCH-HE-FMT/vm/vm folder"
]
}
```
Will now be
```
{
"data": [
"",
"/RNCH-HE-FMT/vm/Discovered virtual machine",
"/RNCH-HE-FMT/vm/Discovered virtual machine/asdf",
"/RNCH-HE-FMT/vm/Discovered virtual machine/asdf/fdsa",
"/RNCH-HE-FMT/vm/vm folder",
"/RNCH-HE-FMT/vm/vm folder/level 1b",
"/RNCH-HE-FMT/vm/vm folder/level 1b/level 2bb",
"/RNCH-HE-FMT/vm/vm folder/level 1b/level 2ba",
"/RNCH-HE-FMT/vm/vm folder/level 1a",
"/RNCH-HE-FMT/vm/vm folder/level …
```

[master] [forwardport] vSphere VM Folder Fix

---

pkg/controllers/user/nodesyncer/nodessyncer.go

https://github.com/rancher/rancher/issues/24869

reset desired annotations after update

---

tests/validation/tests/v3_api/test_rke_cluster_provisioning.py

Added method to create custom cluster given set of node roles.

Add method to create custom cluster given set of node roles.

---

pkg/controllers/user/nodesyncer/nodessyncer.go

[2.3] reset desired annotations after update

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-driver-metadata/rke/templates/coredns.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/24854

[2.3] vendor update

---

package/run.sh

Forwardport PR to merge in master - this is for this PR merged to release/v2.3: https://github.com/rancher/rancher/pull/24873

[forwardport] Do not set facl again on certs dir

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/24062

Set node agent upgrade strategy to 25%

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_app.py

- Added rbac test cases for apps
- changed the catalogs apps to point to a local chart (modified so that they can be deployed on 1.16 clusters and above.)

Changing catalog for app and adding rbac test cases

---

tests/validation/tests/v3_api/test_configmaps.py

@sangeethah :  Please review config map test cases .

Added Config map test cases

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_upgrade.py

Fixing the catalog app during pre-upgrade and post-upgrade so it can be deployed on cluster with k8s v 1.16 and above

changing catalog for app deployment

---

tests/validation/tests/v3_api/test_custom_host_reg.py
tests/validation/tests/v3_api/test_upgrade.py

Adding tests for core dns issue

Tests for core-dns issue

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_monitoring.py

- add rbac tests for cluster and project monitoring
- add a workload in the shared project
- refactor code to meet the style requirements

add rbac tests for monitoring

---

pkg/api/customization/cluster/actions_cis.go
pkg/api/customization/cluster/formatter.go
pkg/api/customization/clusterscan/clusterscan.go
pkg/controllers/user/cis/clusterScanHandler.go
tests/integration/suite/test_cluster_scan.py

https://github.com/rancher/rancher/issues/24755
https://github.com/rancher/rancher/issues/24759

disable runSecurityScan for non-active and windows clusters

---

tests/validation/requirements.txt
tests/validation/tests/rke/Jenkinsfile

Updated few commands
Updated requirements.txt

Update rke cli files 

---

tests/validation/Dockerfile.v3api
tests/validation/lib/aws.py
tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/resource/cluster-ha.yml
tests/validation/tests/v3_api/scripts/build.sh
tests/validation/tests/v3_api/test_create_ha.py
tests/validation/tests/v3_api/test_custom_host_reg.py
tests/validation/tests/v3_api/test_gke_cluster.py
tests/validation/tests/v3_api/test_import_cluster.py

Creates load balancer, target groups, nodes, and creates/updates hostname in Route53.

Automate HA install w/ Helm 3 and supplied RKE version

---

tests/validation/lib/kubectl_client.py
tests/validation/tests/rke/Jenkinsfile
tests/validation/tests/rke/common.py
tests/validation/tests/rke/resources/k8s_ymls/daemonset_pods_per_node.yml
tests/validation/tests/rke/resources/k8s_ymls/dashboard.yaml

Jenkinsfile was not calling `build.sh` to build the test container

RKE Validation Tests - Fix Jenkinsfile not building container

---

tests/validation/tests/v3_api/test_cis_scan.py
tests/validation/tests/v3_api/test_rke_cluster_provisioning.py

Total test cases = 9
RBAC test cases = 5

Adding cis scan validation tests

---

app/role_data.go

New Istio CRDs require role data updates

---

tests/validation/tests/rke/test_upgrade.py

@sangeethah : Please review. The first 3 tests are passing with the updated images.

Updated PRE and POST K8s images

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_global_role.py

add tests for global roles
```
- 5 functional tests
- 20 RBAC tests
```

add tests for global roles

---

tests/validation/tests/v3_api/Jenkinsfile
tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade_multiple

Update pipeline to pull both ADMIN_PASSWORD and USER_PASSWORD from jenkins creds

Validation - Update pipeline credentials

---

tests/validation/tests/v3_api/test_project_quota.py

Related Pr: https://github.com/rancher/rancher/pull/24504
Related Issue: https://github.com/rancher/rancher/issues/24479

Add validation test for namespace's quota

---

pkg/controllers/management/auth/project_cluster_handler.go

Problem:
In a race a cash miss will cause a 2nd default project to get created
Solution:
Check the API before attempting to create the default projects if the
cache misses

Check API before creating default projects

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/25081

Remove tab before maxUnavailable for node-agent-windows

---

go.mod
go.sum
pkg/api/customization/cluster/actionhandler.go
pkg/api/customization/cluster/actions_cis.go
pkg/api/server/managementstored/setup.go
pkg/controllers/management/kontainerdrivermetadata/data.go
pkg/controllers/management/kontainerdrivermetadata/data_getter.go
pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
pkg/controllers/user/cis/clusterScanHandler.go
pkg/controllers/user/cis/register.go
vendor/github.com/rancher/kontainer-driver-metadata/rke/cis_config.go
vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_defaults.go
vendor/modules.txt

- handle info from k-d-m
- handle invalid overrideBenchmarkVersion from API
https://github.com/rancher/rancher/issues/24935
https://github.com/rancher/rancher/issues/24422
Dependencies:
- ~https://github.com/rancher/types/pull/1068~
- ~https://github.com/rancher/kontainer-driver-metadata/pull/108~
Blocked by: https://github.com/rancher/kontainer-driver-metadata/pull/124

Adding k-d-m support for CIS

---

main.go

Addresses: https://github.com/rancher/rancher/issues/25204
This line got missed in the refactor changes: https://github.com/rancher/rancher/pull/25186/files#diff-7ddfb3e035b42cd70649cc33393fe32cL155

fix missing cli arg destination

---

pkg/tls/tls.go

https://github.com/rancher/rancher/issues/25204

Migrate CA cert during upgrade

---

tests/validation/tests/v3_api/test_custom_host_reg.py

Changing the test name to not include while other logging tests are called

Changing the test name

---

pkg/agent/cluster/cluster.go

https://github.com/rancher/rancher/issues/25237

Make namespace file optional

---

pkg/controllers/user/monitoring/cluster_monitoring_enabled_handler.go

https://github.com/rancher/rancher/pull/23985
Issue: https://github.com/rancher/rancher/issues/25203

[2.3] Fixed panic in monitoring handler

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_kontainer_engine_config.py

Cherry-pick/backport of of https://github.com/rancher/rancher/pull/25070

[release/v2.3] Do not set k8s version or networkpolicy on update

---

tests/validation/tests/v3_api/test_secrets.py

@jiaqiluo @sangeethah : Please review . RBAC tests have been added, existing functional tests have not been modified.

Added RBAC tests for secrets

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/defaults.go
vendor/github.com/rancher/rke/cluster/etcd.go
vendor/github.com/rancher/rke/services/etcd.go
vendor/modules.txt

Addresses: https://github.com/rancher/rancher/issues/25153

bump rke version, go mod changes

---

tests/validation/tests/v3_api/test_cert_rotation.py

This PR adds RBAC tests for certificate rotation.

Add RBAC tests for cert rotation

---

pkg/tls/tls.go

https://github.com/rancher/rancher/issues/25284

Fix HA TLS

---

Dockerfile.dapper
go.mod
go.sum
package/Dockerfile
scripts/ci
tests/integration/requirements.txt
tests/integration/suite/test_app.py
tests/integration/suite/test_catalog.py
vendor/github.com/rancher/norman/pkg/kwrapper/k8s/k3s_linux.go
vendor/modules.txt

**Problem**
k3s version v0.8.0 is using k8s v1.14
**Solution**
Uplift k3s version to latest version which is using k8s v1.17
**Dependent on**
https://github.com/rancher/norman/pull/333
**Issue**
#24439

Uplift k3s to latest

---

pkg/rkenodeconfigserver/nodeserver.go
pkg/rkenodeconfigserver/nodeserver_test.go

https://github.com/rancher/rancher/issues/25244

Add node-name param to the end of nodecommand

---

tests/validation/tests/v3_api/test_monitoring.py

- add a new etcd graph `etcd-peer-traffic` 
- add a missing variable to a function call
- add more information to the output when a test fails
sample output when a test fails:
```
target graphs : ['apiserver-request-count', 'apiserver-request-latency', 'controllermanager-queue-depth', 'ingresscontroller-nginx-connection', 'scheduler-e-2-e-scheduling-latency-seconds-quantile', 'scheduler-pod-unscheduler', 'scheduler-total-preemption-attempts']
actual graphs : ['controllermanager-queue-depth', 'ingresscontroller-nginx-connection', 'scheduler-pod-unscheduler', 'scheduler-total-preemption-attempts']
missing graphs: ['apiserver-request-count', 'apiserver-request-latency', 'scheduler-e-2-e-scheduling-latency-seconds-quantile']
extra graphs  : []
FAILED
```

Fix monitoring failures

---

pkg/cert/cert.go

https://github.com/rancher/rancher/issues/24423

Add ECC support to secrets reader

---

tests/validation/lib/aws.py

Adds Oracle Linux private AMI to os validation Jenkins job.

Add oracle linux to os validation

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_kdm_changes.py
tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
tests/validation/tests/v3_api/test_service_discovery.py
tests/validation/tests/v3_api/test_upgrade.py

Test to validate the KDM changes

KDM validation test

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_group_grb.py
tests/validation/tests/v3_api/test_istio.py

These new tests will fail until #25365 is resolved. We can code around it if we think that is the best solution. Supplying a single call to `get_client_for_token` before trying to use the token to validate istio url access is a workaround that I've validated.

Added initial istio group rbac tests

---

go.mod
go.sum
pkg/tls/tls.go
vendor/github.com/rancher/dynamiclistener/listener.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25256

Fix broken TLS websockets on chrome

---

pkg/api/customization/logging/action.go
pkg/api/server/managementstored/setup.go
pkg/controllers/management/controller.go
pkg/controllers/user/alert/configsyncer/configsyncer.go
pkg/controllers/user/alert/controller.go
pkg/controllers/user/alert/deployer/deployer.go
pkg/controllers/user/alert/deployer/upgradeimpl.go
pkg/controllers/user/alert/initdata.go
pkg/controllers/user/helm/controller.go
pkg/controllers/user/logging/configsyncer/configsyncer.go
pkg/controllers/user/logging/deployer/appdeployer.go
pkg/controllers/user/logging/deployer/deployer.go
pkg/controllers/user/logging/deployer/upgradeimpl.go
pkg/controllers/user/monitoring/operatorHandler.go
pkg/controllers/user/monitoring/projectHandler.go
pkg/controllers/user/monitoring/register.go
pkg/controllers/user/pipeline/controller/project/project.go

Issue: https://github.com/rancher/rancher/issues/25295

Use listers

---

pkg/api/customization/workload/workload.go
tests/integration/suite/test_workloads.py

Revert "Add redeploy to workload API and integration test"

---

tests/validation/requirements_v3api.txt
tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_websocket.py

issue: https://github.com/rancher/rancher/issues/25405
add the following tests:
- launching the kubectl
- exec into a pod to run commands
- check a pod's log
introduce one new keyword for automation:
- test_websocket

add tests for webSockets

---

tests/validation/tests/v3_api/test_registry.py

Added rbac tests in workload registry tests. 
Tested - http://jenkins-poc.rancher.io:8080/view/Khushboo/job/khushboo-test-workload-rbac-registry/

Add rbac tests for workload registry

---

pkg/api/customization/cluster/validator.go
tests/integration/suite/test_clustertemplate.py

Issue: https://github.com/rancher/rancher/issues/23034

Change error for revision

---

tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test

Moved deploy rancher to its own stage and try/catch to properly set the condition for DELETE_RANCHER_SERVER. 
Fixed whitespace formatting.

Validation - Fix Rancher server not deleted when tests error in deploy and test pipeline

---

tests/validation/tests/v3_api/test_ingress.py
tests/validation/tests/v3_api/test_registry.py

Added create, edit and delete test cases for ingress test automation.

Add rbac ingress tests

---

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test

add test_webscoket to the list of test running for OnTag jobs

add test_webscoket to the list of test running for OnTag jobs

---

package/Dockerfile
scripts/package

Revert "Point system-charts branch to istio-1.4.4 for airgap testing"

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_service_discovery.py

Added create/edit/delete tests for service discovery.

Add rbac tests for service discovery.

---

go.mod
go.sum
tests/integration/suite/test_notifier.py
vendor/github.com/rancher/types/apis/management.cattle.io/v3/alerting_types.go
vendor/modules.txt

Problem: Notifier email configure return plaintext password
Solution: update type to password
Related PR:https://github.com/rancher/types/pull/1051
Issue: https://github.com/rancher/rancher/issues/24335

Test for setting email notifier SMTP password

---

pkg/api/customization/feature/feature.go
pkg/api/customization/feature/feature_test.go

**Problem:**
Feature formatter assigns default from where default used to be located. This causes value to not be properly set to the default.
**Solution:**
Use default from feature status.
**Issue:**
https://github.com/rancher/rancher/issues/25462

Fix feature def

---

pkg/auth/providers/ldap/ldap_provider.go
pkg/auth/providers/saml/saml_provider.go

Only using the LDAP provider doesn't work everywhere when we're just using shibboleth as a SAML provider. This will short circuit that logic so we're always at least a SAML provider.

shibboleth fallback to saml provider

---

tests/validation/tests/v3_api/resource/cluster.yml
tests/validation/tests/v3_api/test_import_cluster.py

Added a config file with 9 nodes

Added test case to generate rke config

---

go.mod
go.sum
tests/integration/suite/test_kontainer_engine_config.py
tests/integration/suite/test_kontainer_engine_validation.py
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/modules.txt

Addresses: 
https://github.com/rancher/rancher/issues/23876
https://github.com/rancher/rancher/issues/21552

Update kontainer-engine for EKS fix

---

pkg/api/customization/roletemplatebinding/validator.go

**Problem:**
Empty strings are treated as valid subjects. 
**Solution:**
Treat subject fields with empty strings as missing. Make null and empty values have identical results.
**Issue:**
https://github.com/rancher/rancher/issues/25526

Convert PRTB/CRTB subject fields to strings

---

pkg/api/customization/cluster/validator.go

**Problem:**
CanAccess was is never evaluated, and that is where the error code was converted.
**Solution:**
Remove redundant check.  Return error with correct error code if access check fails.

Remove redundant checks

---

scripts/istio-images-mirror

https://github.com/rancher/rancher/issues/23753

Adding gatekeeper image to the mirror list

---

Dockerfile.dapper
package/Dockerfile
pkg/channelserver/channelserver.go
pkg/channelserver/handler.go
server/server.go

Depends on https://github.com/rancher/kontainer-driver-metadata/pull/147

Bundle channel server

---

pkg/controllers/management/auth/globalrolebinding_handler.go
pkg/systemaccount/systemaccount.go

Problem:
On project sync API calls are being used to validate something exists
Solution:
Update to use a cache to ease the load on the API
Issue: https://github.com/rancher/rancher/issues/25605

Update role calls to use listers

---

pkg/controllers/user/logging/generator/templatesource.go

…f generated fluentd collector config file. https://github.com/rancher/rancher/issues/25048

adds skip_refresh_on_startup and read_from_head to fluentd collector

---

pkg/api/customization/cluster/actions_etcd.go

refactored the S3 restore logic as it was causing backup to still be nil since it was inside the s3 config checks.
https://github.com/rancher/rancher/issues/25609

fixing nil backup during s3 restore

---

pkg/controllers/management/node/controller.go
tests/integration/suite/test_node.py

This is technically a forward port of https://github.com/rancher/rancher/pull/23837
https://github.com/rancher/rancher/issues/23511

[forwardport] Add newlines to file content fields

---

go.mod
go.sum
pkg/steve/pkg/clusterapi/clusterapi.go
pkg/steve/setup.go
vendor/github.com/rancher/steve/pkg/dashboard/ui.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25596

Don't redirect on encoded paths

---

tests/validation/tests/v3_api/test_custom_host_reg.py

Increase wait time for rancher server to become available from 2 minutes to 5 minutes

Increase wait time for rancher server to become available

---

pkg/controllers/management/kontainerdrivermetadata/data_getter.go

https://github.com/rancher/rancher/issues/23284

[2.3] return error if service option not found

---

chart/templates/deployment.yaml

[2.3] Fix chart when specify audit-log level

---

chart/templates/deployment.yaml

Fix chart when specify audit-log level

---

go.mod
go.sum
vendor/github.com/rancher/steve/pkg/schemaserver/urlbuilder/redirect.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25650

Ensure redirector supports Hijacking if possible

---

tests/validation/tests/v3_api/test_rke_cluster_provisioning.py

Fix missing client in `create_and_validate_custom_host`

Validation - Fix custom cluster provisioning

---

go.mod
go.sum
pkg/controllers/management/kontainerdrivermetadata/data_getter.go
vendor/github.com/rancher/rke/cluster/cluster.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/cluster/reconcile.go
vendor/github.com/rancher/rke/docker/docker.go
vendor/modules.txt

fwd port of https://github.com/rancher/rancher/pull/25622 + vendor update
#23284

[2.4] return error if service option not found

---

go.mod
go.sum
vendor/github.com/rancher/rke/metadata/metadata.go
vendor/github.com/rancher/rke/services/controlplane.go
vendor/github.com/rancher/rke/services/node_util.go
vendor/github.com/rancher/rke/services/workerplane.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25648
https://github.com/rancher/rancher/issues/25677
https://github.com/rancher/rancher/issues/25583

Update RKE for maxUnavailable reset fix

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/cluster.go
vendor/github.com/rancher/rke/cmd/up.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25685

Update to rke v1.1.0-rc9

---

scripts/istio-images-mirror

https://github.com/rancher/rke/issues/1050

Adding nodelocaldns image to mirror list

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go

https://github.com/rancher/rancher/issues/25482
When kube-api-auth was being deleted when it was already removed, it would error out and block the provisioning/updating of the cluster.

Ignore not found when deleting kube-api-auth

---

Dockerfile.dapper

https://github.com/rancher/rancher/issues/25660

[backport v2.3] Add helm unitttest env version

---

go.mod
go.sum
vendor/k8s.io/apimachinery/pkg/util/proxy/dial.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25737

Fix broken websockets

---

tests/integration/suite/test_app.py

Flakey flakey flake, down into the drone.

Increase tests workload timeout

---

tests/validation/tests/v3_api/test_websocket.py

Problem:
the tests for websockets fails on k3s clusters, GKE, EKS, and AKS because there is no nginx-controller deployment under the system project
Solution:
create a new project and deploy a workload in it, then use them to do the websocket tests
Issue:
https://github.com/rancher/rancher/issues/25746

validation - deploy a workload for websocket tests

---

pkg/api/customization/cluster/actions_cis.go
pkg/api/customization/clusterscan/clusterscan.go
pkg/controllers/management/cis/scheduled_scan.go
pkg/controllers/user/cis/clusterScanHandler.go
pkg/controllers/user/cis/constants.go
pkg/controllers/user/cis/scan.go
pkg/controllers/user/cis/utils.go

Addresses: https://github.com/rancher/rancher/issues/25214
Addresses comments from: https://github.com/rancher/rancher/pull/25475

Fix CIS state and review comments

---

pkg/controllers/user/logging/deployer/appdeployer.go

Fixes panic seen at https://drone-pr.rancher.io/rancher/rancher/7685/1/2 line 6974

Save created obj

---

pkg/controllers/management/k3supgrade/k3supgrade_handler.go
pkg/controllers/management/k3supgrade/register.go
pkg/controllers/management/k3supgrade/template.go

MERGE TYPES FIRST: https://github.com/rancher/types/pull/1118

K3s drain configure

---

pkg/agent/main.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/controller.go
pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/plan.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go
pkg/controllers/user/endpoints/endpoints.go
pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
pkg/node/node.go
pkg/rkenodeconfigclient/client.go
pkg/rkenodeconfigserver/nodeserver.go
pkg/rkenodeconfigserver/nodeserver_test.go
pkg/rkeworker/docker.go
pkg/tunnelserver/tunnel.go

Types: https://github.com/rancher/types/pull/1094 
rancher/rancher#23038
related issues: 
https://github.com/rancher/rancher/issues/24073
https://github.com/rancher/rancher/issues/23897
https://github.com/rancher/rancher/issues/25503
https://github.com/rancher/rancher/issues/25329
https://github.com/rancher/rancher/issues/23898

rke worker upgrade logic

---

app/catalog_data.go
package/Dockerfile
pkg/catalog/manager/catalog_sync.go

**Problem:**
With helm version being set at the catalog level, we need a helm 3 specific catalog
**Solution**
Add helm 3 specific catalog to Rancher
**Issue**
#25754

Add helm3 catalog data

---

.gitignore

VS code creates a `.vscode/` directory to store its workspace settings.

Update .gitignore for VS code

---

pkg/api/store/cluster/cluster_store.go
pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/25739

validate and set nodeUpgradeStrategy for rke clusters

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/cluster.go
vendor/github.com/rancher/rke/cluster/reconcile.go
vendor/github.com/rancher/rke/cluster/state.go
vendor/github.com/rancher/rke/cluster/validation.go
vendor/github.com/rancher/rke/docker/docker.go
vendor/github.com/rancher/rke/hosts/tunnel.go
vendor/github.com/rancher/rke/metadata/metadata.go
vendor/github.com/rancher/rke/pki/deploy.go
vendor/github.com/rancher/rke/pki/util.go
vendor/modules.txt

This includes:
- Add logging structs/file content to trace loglevel https://github.com/rancher/rke/pull/1945
- Performance improvements https://github.com/rancher/rke/pull/1946
- Add host to logging for Docker https://github.com/rancher/rke/pull/1941

vendor update rke

---

scripts/istio-images-mirror

https://github.com/rancher/rancher/issues/24543

Add Calico v3.13.0 images

---

pkg/controllers/user/helm/common.go
pkg/controllers/user/helm/common/common.go

**Problem**
Tiller was starting even when running helm3 commands
**Solution**
Add check to determine if tiller should be started or not
**Issue**
#25834

Add start tiller helm version check

---

go.mod
go.sum
pkg/api/controllers/feature/feature_handler.go
pkg/features/feature.go
pkg/features/feature_testdata.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/global_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_feature_status.go
vendor/modules.txt

MERGE TYPES FIRST: https://github.com/rancher/types/pull/1120
Change feature flag name from steve to dashboard.
**Issue:** https://github.com/rancher/rancher/issues/25817

Change feature flag name and add description

---

pkg/features/feature.go

https://github.com/rancher/rancher/issues/25817

Set description when creating feature

---

pkg/api/customization/cluster/validator.go
pkg/api/customization/cluster/validator_test.go
pkg/api/store/cluster/cluster_store.go
pkg/controllers/management/cis/scheduled_scan.go
pkg/controllers/user/alert/watcher/cluster_scan.go
pkg/controllers/user/cis/clusterScanHandler.go
pkg/controllers/user/cis/register.go

Addresses:
- https://github.com/rancher/rancher/issues/25877
- https://github.com/rancher/rancher/issues/25838
- https://github.com/rancher/rancher/issues/25855
- https://github.com/rancher/rancher/issues/25837

cis bug fixes

---

tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/24295
Don't call `remove_resource(cluster_template)` in `create_cluster_template`, instead return it and remove everything in order.

Fix flakey cluster template tests

---

go.mod
go.sum
vendor/github.com/rancher/norman/controller/generic_controller.go
vendor/github.com/rancher/norman/objectclient/object_client.go
vendor/github.com/rancher/norman/pkg/subscribe/handler.go
vendor/github.com/rancher/norman/store/proxy/proxy_store.go
vendor/github.com/rancher/norman/types/reflection.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25965
Includes:
- https://github.com/rancher/rke/pull/1954

vendor norman and rke

---

pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

Removing support to add ignore labels. All unavailable nodes will be updated with new node plan so node can come up active when powered on/fixed.

remove ignore labels logic for rke nodes

---

app/machinedriver_data.go
pkg/api/store/nodetemplate/store.go
pkg/controllers/management/node/controller.go
tests/integration/suite/test_node.py

This reverts commit c7ad3c7a8b99e6954c0acae7cadb964b53d109bd.
https://github.com/rancher/rancher/issues/23060

Revert "add region to ec2 cloud credential"

---

pkg/api/store/cluster/cluster_store.go
pkg/rkenodeconfigserver/nodeserver.go

https://github.com/rancher/rancher/issues/25885

add more context for node plan nil log msg

---

pkg/rkenodeconfigclient/client.go

https://github.com/rancher/rancher/issues/26015

consider only nonzero agentCheckInterval from node config

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/cluster.go
vendor/github.com/rancher/rke/k8s/node.go
vendor/github.com/rancher/rke/services/controlplane.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25599
RKE pr: https://github.com/rancher/rke/pull/1965

Update rke vendor

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-driver-metadata/rke/k8s_service_options.go
vendor/modules.txt

Includes:
- https://github.com/rancher/kontainer-driver-metadata/pull/164 / https://github.com/rancher/rke/pull/1971

[release/v2.3] vendor update kdm

---

pkg/ref/parse.go

https://github.com/rancher/rancher/issues/26071

Check err not nil before calling clusterDialer

---

pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/25999: nodes get upgraded even if drain fails, this happens because node was considered prepared if node is cordoned/drained. If drain is set to true in cluster spec, only that should be considered. see https://github.com/rancher/rancher/pull/26016/files#diff-2eabb733bb0dba004b0c4c6d065eeb8cL170
https://github.com/rancher/rancher/issues/25946: even if unavailable nodes >= maxUnavailable nodes, we should still mark the upgraded nodes as active. there's no point in letting them stuck in upgrading. see https://github.com/rancher/rancher/pull/26016/files#diff-a16c43ed026936b620e2fdb9ca6196b8L273
https://github.com/rancher/rancher/issues/26023: all the fields should be read from cluster status, not spec. I am correctly doing this for rkeConfig, but …

more bugs fixes

---

pkg/image/export/main.go

**Issue:**
https://github.com/rancher/rancher/issues/26042

Add releases support to image export

---

pkg/api/store/cluster/cluster_store.go

https://github.com/rancher/rancher/issues/26053

Set maxUnavailableControlplane and worker to default values

---

pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/25647

snapshot restore for worker nodes

---

pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/26090

panic fix: check for nil node.Status.NodeConfig before update plan

---

pkg/controllers/management/k3supgrade/deployPlans.go

Problem: The cluster upgrading state would momentarily flicker during an
upgrade.
Solution: Once the upgrade state is entered, the only state that can
exit 'Upgrading' are states were worker or master plans are being
applied. This prevents the state flip flopping.
Addresses https://github.com/rancher/rancher/issues/26024

Remain in upgrading state

---

pkg/controllers/management/rkeworkerupgrader/upgrade.go

Problem: Nodes restore correctly but if cluster was upgrading
before restore, it still proceeds with  rolling update logic.
Solution: Set cluster condition upgrading true once restore is done
https://github.com/rancher/rancher/issues/25647

set upgrading true after snapshot restore

---

pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

Problem:
Lister might not always give latest updated node object.
If nodes are picked for cordon/drain out of order,
we might cordon/drain extra nodes, violating the maxUnavailable.
Solution:
Using a sorted list ensures we always pick the same node.
https://github.com/rancher/rancher/issues/25861

use sorted list to store node upgrade status

---

tests/integration/suite/test_app.py
tests/integration/suite/test_catalog.py

Add Helm 3 testing

---

app/machinedriver_data.go

upgrading to packet driver v0.2.2 with ui v1.0.1

---

go.mod
go.sum
pkg/agent/main.go
pkg/api/customization/catalog/catalog.go
pkg/steve/pkg/clusterapi/clusterapi.go
pkg/tls/tls.go
vendor/github.com/rancher/steve/pkg/accesscontrol/policy_rule_index.go
vendor/github.com/rancher/steve/pkg/auth/filter.go
vendor/github.com/rancher/steve/pkg/clustercache/controller.go
vendor/github.com/rancher/steve/pkg/server/resources/counts/counts.go
vendor/github.com/rancher/wrangler/pkg/summary/client/interface.go
vendor/github.com/rancher/wrangler/pkg/summary/client/simple.go
vendor/github.com/rancher/wrangler/pkg/summary/informer/informer.go
vendor/github.com/rancher/wrangler/pkg/summary/informer/interface.go
vendor/github.com/rancher/wrangler/pkg/summary/lister/interface.go
vendor/github.com/rancher/wrangler/pkg/summary/lister/lister.go
vendor/github.com/rancher/wrangler/pkg/summary/lister/shim.go
vendor/github.com/rancher/wrangler/pkg/summary/summarized.go
vendor/github.com/rancher/wrangler/pkg/summary/summary.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/26163

Mark projects and apps as namespaced in steve clusterapi (and reduce memory)

---

go.mod
go.sum
pkg/agent/main.go
vendor/github.com/rancher/norman/pkg/subscribe/handler.go
vendor/github.com/rancher/norman/store/proxy/proxy_store.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/26183
https://github.com/rancher/rancher/issues/26184

Fix websocket rbac again

---

go.mod
go.sum
pkg/steve/pkg/clusterapi/clusterapi.go
vendor/github.com/rancher/steve/pkg/schemaserver/store/schema/schema_store.go
vendor/github.com/rancher/steve/pkg/server/store/proxy/proxy_store.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/26186

Add missing "create" verb and fix route for apps

---

pkg/image/export/main.go

We usually download files used for things like image export in dapper, but in this scenarios we do not know what k3s version are relevant until data.json is parsed. This could be done in bash but its already being done in export/main.go.

Add all k3s images to airgap images

---

pkg/api/customization/cluster/validator.go
pkg/api/server/managementstored/setup.go

https://github.com/rancher/rancher/issues/26219

add version check when enabling scheduled scan

---

pkg/image/export/main.go

~This is WIP until grafana image from istio 1.4.3 is fixed (should be in https://github.com/rancher/system-charts/pull/152)~
This was split from https://github.com/rancher/types/pull/1065.
This errors out when images are not correctly generated so it can be fixed directly and not after release.

Add checks to needed Docker images

---

pkg/controllers/management/node/utils.go
pkg/dialer/factory.go
pkg/tunnelserver/tunnel.go

Removes most of the function/diagnostics logging to TRACE to keep DEBUG more readable.
https://github.com/rancher/rancher/issues/25965

Change frequent logs to TRACE

---

pkg/controllers/management/rkeworkerupgrader/upgrade.go

Problem:
rke reconcile (deleting node or changing cluster yaml) triggers upgrade logic. If cluster's in upgrading state, plan will always change for nodes that haven't been upgraded yet.
This will cause all upgraded nodes to cordon/drain & upgrade again.
Solution:
Skip nodes that haven't upgraded during plan change logic when
cluster's upgrading.
https://github.com/rancher/rancher/issues/26256

planChanged only for upgraded nodes if cluster's upgrading

---

Dockerfile.dapper

Backport fix for changes in helm unit-test

[2.2x] Bump helm unit-test version

---

go.mod
go.sum
vendor/modules.txt

Vendor rke v1.0.6

---

pkg/settings/setting.go

Updating the setting pointing to external dns system chart.

[2.4]Update the system catalog ID setting for external-dns chart

---

go.mod
go.sum
vendor/github.com/rancher/norman/urlbuilder/url.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/26422

Revert URL parsing logic

---

tests/integration/suite/test_cluster_catalog.py
tests/integration/suite/test_default_roles.py

https://github.com/rancher/rancher/issues/17567
https://github.com/rancher/rancher/issues/18489

Fix flaky tests

---

pkg/rkenodeconfigclient/client.go

Problem:
If there is an extra share-mnt unmanaged agent running on node,
it doesn't execute plan but sends back node version and server
incorrectly assumes node's been upgraded
https://github.com/rancher/rancher/blob/master/pkg/rkeworker/execute.go#L34 
Solution:
ExecutePlan doesn't update processes if writeCertOnly, so add check
for it and don't consider it an upgrade
https://github.com/rancher/rancher/issues/26401

share-mnt agent shouldn't send back node version

---

go.mod
go.sum
pkg/controllers/management/clusterprovisioner/provisioner.go
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/modules.txt

**Issues:**
https://github.com/rancher/rancher/issues/25835
https://github.com/rancher/rancher/issues/24171

Eks edit other

---

go.mod
go.sum
pkg/controllers/management/clusterprovisioner/provisioner.go
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/modules.txt

**Issue:**
https://github.com/rancher/rancher/issues/26476
https://github.com/rancher/rancher/issues/26484

[Backport] 2.4: Eks edit other 2.4

---

tests/validation/tests/v3_api/test_configmaps.py

Added tests for listing configmap for all roles

---

go.mod
go.sum
pkg/controllers/management/clusterprovisioner/provisioner.go
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/modules.txt

**Issues:**
https://github.com/rancher/rancher/issues/26486
https://github.com/rancher/rancher/issues/26487

[Backport] 2.3: Eks edit other

---

go.mod
go.sum
vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
vendor/modules.txt

Update types to fix it
Related PR:
https://github.com/rancher/types/pull/1125
Related Issue:
https://github.com/rancher/rancher/issues/14420

Fix the issue that preferences show other user's name

---

pkg/auth/providers/ldap/ldap_client.go

Backport of https://github.com/rancher/rancher/pull/26375
https://github.com/rancher/rancher/issues/20002

[2.4] Change scope to subtree for openldap login search

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/github.com/rancher/kontainer-engine/drivers/eks/templates.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/25613

[2.4] Update kontainer-engine vendor

---

go.mod
go.sum
pkg/api/customization/cluster/formatter.go
tests/integration/suite/test_cluster.py
vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
vendor/modules.txt

Issue https://github.com/rancher/rancher/issues/25227

[2.4] Add nodeCount to formatter

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/modules.txt

Backport for https://github.com/rancher/rancher/issues/25779

Update vendor for EKS userdata

---

tests/validation/tests/v3_api/common.py

Ensure that it appends the node only if the key exists and matches the expected value

Update logic for node label

---

vendor.conf
vendor/github.com/rancher/rke/vendor.conf
vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go

https://github.com/rancher/rancher/issues/26563

[2.2] vendor update types,rke

---

tests/validation/tests/v3_api/test_create_ha.py

Added method to upgrade HA installation. 
Kubeconfig needs to be present in base64 encoded format.

Validation - Upgrade HA installation

---

go.mod
go.sum
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/usercontrollers/controller.go
pkg/dialer/factory.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
vendor/modules.txt

Addresses https://github.com/rancher/rancher/issues/26448

[v2.4] Add basic support for k3os cluster drivers

---

pkg/api/store/app/store.go
tests/integration/suite/test_app.py

https://github.com/rancher/rancher/issues/24371
Forward port of https://github.com/rancher/rancher/pull/23642
Forward port of https://github.com/rancher/rancher/pull/26614

[2.4] Check app projectId during edit

---

pkg/api/store/app/store.go
tests/integration/suite/test_app.py

Forward port of https://github.com/rancher/rancher/pull/26630

Check app projectId during edit

---

pkg/controllers/user/helm/controller.go
pkg/controllers/user/monitoring/appHandler.go
pkg/controllers/user/monitoring/clusterHandler.go
pkg/controllers/user/monitoring/register.go

Forwardport of https://github.com/rancher/rancher/pull/26564
https://github.com/rancher/rancher/issues/26440

Force redeploy cluster-monitoring if workload doesn't exist

---

app/machinedriver_data.go

Fixed the UI url as the one merged upstream is no longer valid

Change to packet ui v1.0.2

---

go.mod
go.sum
vendor/github.com/rancher/wrangler/pkg/generic/controller.go
vendor/github.com/rancher/wrangler/pkg/generic/controllerfactory.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/21361

Vendor update of wrangler

---

pkg/api/customization/cluster/validator.go
tests/integration/suite/test_cluster_defaults.py

Previously, subnets were editable on EKS clusters which does not represent the architecture of
Kontainer Driver which does not allow for editing of subnets after the cluster has been provisioned.
This was done as a validator due to the difficulty of adding additional fields to the kontainer
engine type since this requires regenerating the protobuff files for Kontainer Driver.
Addresses https://github.com/rancher/rancher/issues/24652

Add EKS specific subnet validation

---

pkg/api/customization/cluster/validator.go
tests/integration/suite/test_cluster_defaults.py

Backport of https://github.com/rancher/rancher/pull/26640#pullrequestreview-395960028 
Addresses https://github.com/rancher/rancher/issues/24652

Add EKS specific subnet validation 

---

pkg/api/customization/cluster/validator.go
tests/integration/suite/test_cluster_defaults.py

Backport for https://github.com/rancher/rancher/issues/26518

[2.3] Add EKS specific subnet validation 

---

pkg/settings/setting.go
server/server.go

This PR backports https://github.com/rancher/rancher/pull/26706 to the 2.4 release.

Backport add ui-banners setting

---

package/Dockerfile

bumping ui version

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_hpa.py

Added basic create, edit, delete tests, RBAC tests for HPA

---

tests/validation/tests/v3_api/test_workload.py

Adds parameterized tests cases for rbac-daemonset.

Tests Coverage for RBAC-daemonset

---

pkg/controllers/management/rkeworkerupgrader/upgrade.go

I don't really know why this panic is happening, all scenarios should have been covered by L239 block. Issue was observed during an incorrect cluster upgrade on adding a worker node, but since this is a panic, arranging logic a little to always check for empty upgradeStrategy. 
#26792

[2.4] fix panic on empty worker upgrade strategy

---

pkg/controllers/management/rkeworkerupgrader/plan.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

cherry-pick of approved PRs, 
https://github.com/rancher/rancher/pull/26847
https://github.com/rancher/rancher/pull/26815
Issues: 
https://github.com/rancher/rancher/issues/26790
https://github.com/rancher/rancher/issues/26807
https://github.com/rancher/rancher/issues/26792

forward port commits 

---

pkg/api/customization/cluster/validator.go
pkg/api/customization/cluster/validator_test.go

cherry-pick https://github.com/rancher/rancher/pull/26887

[2.4] Do not validate CIS on cluster from template

---

pkg/api/customization/cluster/validator.go

Addressing review comments on https://github.com/rancher/rancher/pull/26887

Address review comments on CIS cluster validation

---

pkg/api/customization/cluster/validator.go

Backport of https://github.com/rancher/rancher/pull/26904

[release/v2.4] Address review comments on CIS cluster validation

---

scripts/ci

[2.4] Revert "Skip tests during CI process"

---

scripts/ci

[2.3] Revert "skip tests during CI process"

---

.drone.yml

Pin to last weeks docker plugin

use older 18.09 builder

---

pkg/catalog/manager/catalog_common.go

Backport https://github.com/rancher/rancher/pull/26943
**Issue**
https://github.com/rancher/rancher/issues/19615

[2.4] Support uppercase characters in version strings

---

pkg/api/store/nodetemplate/store.go
tests/integration/suite/test_node_templates.py

**Backport:**
https://github.com/rancher/rancher/pull/26806
**Issue:**
https://github.com/rancher/rancher/issues/26160

[Backport] 2.4: Forward legacy nt

---

tests/validation/lib/aws.py
tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_certificate.py

Test cases for certificate functionality in rancher.
Trusted and selfsigned certificates are being tested in these test cases.

Add certificate test automation

---

pkg/controllers/user/helm/common.go

Backport https://github.com/rancher/rancher/pull/27000
**Issue**
#26999

[2.4] Add include crds flag

---

tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix

Added the credentials to 'Jenkinsfile_deploy_and_test' and 'Jenkinsfile_deploy_and_test_support_matrix'.

Add valid and self signed certificate in jenkin files

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go
vendor/modules.txt

**Backport:**
https://github.com/rancher/rancher/pull/27048
**Issues:**
https://github.com/rancher/rancher/issues/26907
https://github.com/rancher/rancher/issues/19115

Update kontainer-engine for AKS upgrading bug

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_nfs.py
tests/validation/tests/v3_api/test_volumes.py

Added Basic volume create, edit and delete, rbac cases

---

chart/templates/ingress.yaml
chart/tests/ingress_test.yaml

Updated rancher chart to mitigate cert-manager issue #2533

---

chart/templates/ingress.yaml
chart/tests/ingress_test.yaml

[2.4] Updated rancher chart to mitigate cert-manager issue #2533

---

chart/templates/ingress.yaml
chart/tests/ingress_test.yaml

[2.3] Updated rancher chart to mitigate cert-manager issue #2533

---

chart/templates/ingress.yaml
chart/tests/ingress_test.yaml

[2.2] Updated rancher chart to mitigate cert-manager issue #2533

---

pkg/api/store/cluster/cluster_store.go
tests/integration/suite/test_clustertemplate.py

For a cluster created from RKE template, update description, labels and annotations separately
https://github.com/rancher/rancher/issues/26754

For a cluster created from RKE template, update description, labels, annotations

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go

Issue(s):
* No logging available around clusterdeploy/kubectl actions
* Randomly an error is seen during cluster provisioning when applying agent YAML
Solution:
* Add (debug) logging on the clusterdeploy/kubectl actions
* Extend retries and sleep for kubectl apply for agent YAML to give it a bit more time to be applied, also added logging (and redacted the token in the logging) (https://github.com/rancher/rancher/issues/24996)

Extend kubectl agent deploy retries, improve log

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go

Issue(s):
* No logging available around clusterdeploy/kubectl actions
* Randomly an error is seen during cluster provisioning when applying agent YAML
Solution:
* Add (debug) logging on the clusterdeploy/kubectl actions
* Extend retries and sleep for kubectl apply for agent YAML to give it a bit more time to be applied, also added logging (and redacted the token in the logging)

[2.4] Extend kubectl agent deploy retries, improve log

---

go.mod
go.sum
tests/integration/suite/test_istio.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_consistent_hash_lb.go
vendor/modules.txt

Vendoring and integration test for: rancher/types#1142
Issue: #25515

Allow istios dest rule LB to be nullable

---

go.mod
go.sum
tests/integration/suite/test_istio.py
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_consistent_hash_lb.go
vendor/modules.txt

Backport https://github.com/rancher/rancher/pull/27157

Istio dest rule nullable backport 2.4

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go

Backport of https://github.com/rancher/rancher/pull/27186

[release/v2.4] Avoid npe for cluster object in sync

---

pkg/controllers/management/kontainerdrivermetadata/data.go
tests/integration/suite/test_istio.py

https://github.com/rancher/rancher/pull/27203 
https://github.com/rancher/rancher/pull/27177

[2.4] backport PRs 

---

pkg/settings/setting.go
server/server.go

https://github.com/rancher/rancher/issues/27047

[2.4] Add ui-issues setting

---

pkg/controllers/user/helm/common.go
pkg/controllers/user/helm/controller.go

**Problem**
App install is failing when trying to install app that has CRDs with helm 3 as the command being used to generate the notes does not support CRDs to be rendered
**Solution**
Change notes logic to use `helm get notes` after install is completed.
**Additional Info** 
If install fails, the app revision available will have empty notes. This was not the behavior previously
**Issue**
https://github.com/rancher/rancher/issues/26999

Refactor render notes to use get notes

---

pkg/tls/tls.go

https://github.com/rancher/rancher/issues/27198
This seems to be reintroduced via https://github.com/rancher/rancher/pull/27158

Don't set MaxSANs

---

pkg/settings/setting.go
server/server.go

https://github.com/rancher/rancher/issues/27047

Add ui-issues setting

---

app/kontainerdriver_data.go

Update k8s version and other options for Alibaba ACK cluster driver 
Related Issue:
https://github.com/rancher/rancher/issues/27277
UI PR:
https://github.com/rancher/ui/pull/4016
Master PR:
https://github.com/rancher/rancher/pull/27285

[2.4.4] Update Aliyun ACK cluster driver

---

app/kontainerdriver_data.go

Update k8s version and other options for Alibaba ACK cluster driver 
Related Issue:
https://github.com/rancher/rancher/issues/27277
UI PR:
https://github.com/rancher/ui/pull/4017
2.4 PR:
https://github.com/rancher/rancher/pull/27286

[Master] Update Aliyun ACK cluster driver

---

pkg/controllers/management/rkeworkerupgrader/plan.go

https://github.com/rancher/rancher/issues/26871
See https://github.com/rancher/rke/pull/2058#pullrequestreview-415760627

Compare binds unordered for worker upgrade plan

---

tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
tests/validation/tests/v3_api/test_deploy_clusters.py

Use a comma separated list for `RANCHER_CLUSTER_NAMES`. e.g: `testcluster1,testcluster2,testcluster3`

Allow passing in multiple clusters to run validation tests on

---

tests/validation/lib/aws.py

fix the failure where no route53 record is found

fix the failure where no route53 record is found

---

go.mod
go.sum
pkg/auth/providers/github/github_account.go
pkg/auth/providers/github/github_client.go
pkg/auth/providers/github/github_provider.go
pkg/auth/providers/github/githubconfig_actions.go
pkg/auth/tokens/manager.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_user_attribute.go
vendor/modules.txt

This reverts commit f775702e1d0f9988a95ac44557717d419bb304f0, reversing
changes made to 170e08bd65ff7bbfbe288883dc6745293d84e917.

Revert "Merge pull request #27143 from mrajashree/ghEmail"

---

go.mod
go.sum
vendor/github.com/rancher/rke/cluster/cluster.go
vendor/github.com/rancher/rke/cluster/defaults.go
vendor/github.com/rancher/rke/cluster/plan.go
vendor/github.com/rancher/rke/hosts/hosts.go
vendor/github.com/rancher/rke/services/services.go
vendor/modules.txt

Just pulls in vendor changes for https://github.com/rancher/rke/pull/2079

Vendor changes for removing encryption by default in k8s 1.18

---

pkg/controllers/management/kontainerdrivermetadata/data.go

Problem:
Rancher only sends non-vendored addon templates to RKE, if vendor
data is calculated from external kdm's data, all templates get
considered as vendored (sendRKELabel: "false")
https://github.com/rancher/rancher/issues/26752

read vendor data from local metadata

---

pkg/controllers/management/kontainerdrivermetadata/data.go

Problem:
Rancher only sends non-vendored addon templates to RKE, if vendor
data is calculated from external kdm's data, all templates get
considered as vendored (sendRKELabel: "false")

[2.4] read vendor data from local metadata

---

pkg/controllers/management/kontainerdrivermetadata/data.go

Problem:
Rancher only sends non-vendored addon templates to RKE, if vendor
data is calculated from external kdm's data, all templates get
considered as vendored (sendRKELabel: "false")
https://github.com/rancher/rancher/pull/27355
https://github.com/rancher/rancher/pull/26761

[2.4.4] read vendor data from local metadata

---

package/Dockerfile
scripts/package

Revert "Update release-v2.3 to dev-v2.3 for system-charts"

---

pkg/controllers/management/rkeworkerupgrader/plan.go

Backport of https://github.com/rancher/rancher/pull/27280
For https://github.com/rancher/rancher/issues/26871

[release/v2.4] Compare binds unordered for worker upgrade plan

---

pkg/controllers/user/logging/utils/elasticsearch.go

Backport: https://github.com/rancher/rancher/issues/26994

[2.4] [FEATURE] Post a elasticsearch test message with a bulk request

---

go.mod
go.sum
package/Dockerfile
vendor/modules.txt

Releasing RC after this merges.

bump cli and rke for 2.4.5-rc1

---

tests/validation/tests/v3_api/common.py

check if workloads under the system project are active as part of validating a cluster

check workloads under the system project 

---

tests/validation/tests/v3_api/test_workload.py

Fixes the list test case by comparing listing by uuid.

Fix list in Daemonset RBAC

---

main.go

https://github.com/rancher/rancher/pull/27491
**Issue:**
https://github.com/rancher/rancher/issues/26624

[Forwardport] master: Revert "Reenable HTTP2"

---

.drone.yml

[BackwardPort] PR https://github.com/rancher/rancher/pull/27429

[BackwardPort]The env variable for system chart branch per release version will be set from package/Dockerfile only

---

go.mod
go.sum
vendor/github.com/rancher/norman/store/proxy/proxy_store.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/27505
**Issue:**
https://github.com/rancher/rancher/issues/27505

[Backport] 2.4: Proxy store context

---

go.mod
go.sum
vendor/github.com/rancher/norman/store/proxy/proxy_store.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/27505

[Forwardport]: Update norman for: Proxy store context 

---

chart/README.md

Added README.md for the Helm Chart rancher/rancher
Backport of: https://github.com/rancher/rancher/pull/27588

[2.4] Added README.md

---

chart/README.md

Added the README.md for rancher server

Add README.md 

---

tests/validation/lib/aws.py
tests/validation/tests/v3_api/Jenkinsfile
tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/resource/cluster-ha.yml
tests/validation/tests/v3_api/test_create_ha.py
tests/validation/tests/v3_api/test_import_k3s_cluster.py

this PR allows us to choose the local cluster (RKE/K3S) for the Rancher HA installation.

Configure rancher ha local cluster

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_monitoring.py

**Steps:**
In the setup method, 
1. Install Longhorn app 
2. Use longhorn storage class and enable monitoring 
All monitoring tests will be run with this initial setup.

Modify setup method to enable monitoring with storage class set to longhorn

---

tests/validation/tests/v3_api/test_monitoring.py

add option for whether enable storage for cluster monitoring

add option for whether enable storage for cluster monitoring

---

scripts/publish-manifests.sh

Search and replace for `1.15.0` to `1.15.2`
https://github.com/rancher/rancher/issues/27684

Add mirror for all kube-dns 1.15.2 images

---

tests/validation/tests/v3_api/test_bkp_restore_s3_recover.py

Improvements for this test https://github.com/rancher/rancher/pull/27503
A couple of extra workers as requested for the test cluster.
Randomize Cluster name.

Automation - s3 backup recover test improvements for CI

---

tests/validation/tests/v3_api/test_monitoring.py

- deploy longhorn only when storage is enabled for monitoring
-  set the storage class to "default" when persistent storage is disabled, which matches the default value in UI
-  check some of the kube-component graphs only in k8s 1.15 and 1.16

deploy longhorn only when storage is enabled for monitoring

---

tests/validation/tests/v3_api/test_kdm_changes.py

Not sure if I missed anything here, let me know if this is a valid approach.

Add DNS providers to test_kdm_changes test

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_airgap.py
tests/validation/tests/v3_api/test_create_ha.py

improve the ha deletion that it will try to delete resources no matter the URL is accessible or not

improve the ha deletion method

---

pkg/auth/providers/azure/azure_client.go

Azure AD returns access token that is encoded using URL encoding
Using Std encoding to decode it led to errors for some tokens.
This commit replaces Std encoding with URL encoding to decode token string

[2.4] Use URL encoding to decode azure AD token

---

pkg/auth/providers/azure/azure_client.go

Azure AD returns access token that is encoded using URL encoding
Using Std encoding to decoded it led to errors for some tokens.
This commit replaces Std encoding with URL encoding to decode token string

Use URL encoding to decode azure AD token

---

tests/validation/lib/rke_client.py
tests/validation/tests/rke/resources/rke_templates/cluster_install_config_11.yml.j2
tests/validation/tests/rke/test_install_config.py

Adding changes to include a test for passing a specific `K8S_VERSION` to the cluster.

Adding changes to include a test for passing a specific `K8S_VERSION` to the cluster.

---

tests/validation/tests/v3_api/test_monitoring.py

- check if the target key exists in the response to avoid KeyError
- make sure the longhorn app is deleted properly, otherwise the namespace longhorn-system will be stuck in removing

monitoring tests improvement

---

tests/validation/tests/v3_api/test_kdm_changes.py

print the list of cluster names in a comma-separated list which we can use directly in another job

print the list of cluster names in a comma separated list

---

go.mod
go.sum
vendor/github.com/rancher/types/apis/cluster.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema_secrets.go
vendor/modules.txt

Types PR:
- rancher/types#1160
Issue:
- #25955

[2.4] Update types dependency

---

go.mod
go.sum
vendor/github.com/rancher/rancher/pkg/auth/providers/common/usermanager.go
vendor/github.com/rancher/rancher/pkg/auth/providers/local/local_auth_provider.go
vendor/github.com/rancher/types/apis/cluster.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema_secrets.go
vendor/modules.txt

Types PR:
- rancher/types#1159
Issue:
- rancher/rancher#25955

Update types dependency

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go

Backport of https://github.com/rancher/rancher/pull/27697
https://github.com/rancher/rancher/issues/27218

[release/v2.4] Scope redeployAgent repo check for cluster repo

---

pkg/auth/providers/saml/saml_client.go

Backport of https://github.com/rancher/rancher/pull/27567
https://github.com/rancher/rancher/issues/27288

[release/v2.4] Avoid calling a nil handler for SAML endpoints

---

vendor/github.com/rancher/rancher/pkg/auth/providers/saml/saml_client.go

https://github.com/rancher/rancher/issues/27288

Vendor of auth pkg for SAML nil handler

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_istio.py

- disable the istio and monitoring in the finalize
- fix a bug when validating app deletion

disable the istio in the finalizer

---

pkg/httpproxy/sign.go

**Problem:**
An endpoint format is being assumed that is not compatible with public endpoints.
**Solution:**
us-east-1 will be returned for global endpoints, as mentioned in aws docs: https://docs.aws.amazon.com/general/latest/gr/sigv4_elements.html
**Issue:**
https://github.com/rancher/rancher/issues/27792

Support signing global aws requests

---

tests/validation/tests/v3_api/cli_objects.py
tests/validation/tests/v3_api/test_cli.py

Validation Test for this issue -- https://github.com/rancher/rancher/issues/23832

Adding test to install an app from local directory via Rancher CLI

---

pkg/types/apis/management.cattle.io/v3/tools_system_images.go

Bump minio version in tools_system_images
**Related Issues:**
rancher/rancher#27467
**Related PR's:**
https://github.com/rancher/types/pull/1169

Bump minio version

---

pkg/api/customization/nodetemplate/formatter.go
pkg/api/server/managementstored/setup.go
pkg/api/store/nodetemplate/store.go
tests/integration/suite/conftest.py
tests/integration/suite/test_node.py

https://github.com/rancher/rancher/issues/26456

Check node references on nodetemplate deletion

---

pkg/api/customization/nodetemplate/formatter.go
pkg/api/server/managementstored/setup.go
pkg/api/store/nodetemplate/store.go
tests/integration/suite/conftest.py
tests/integration/suite/test_node.py

Backport of https://github.com/rancher/rancher/pull/27804
https://github.com/rancher/rancher/issues/26456

[release/v2.4] Check node references on nodetemplate deletion

---

pkg/controllers/user/logging/generator/templatesource.go

added pattern for k3s logs

---

tests/validation/tests/v3_api/test_oke_cluster.py

This PR contains a few minor updates to the OCI validation tests that are required after some refactoring.

Update OCI validation tests after refactoring.

---

pkg/controllers/management/auth/role_template_lifecycle.go
pkg/controllers/management/auth/role_template_lifecycle_test.go

Original PR: 
- rancher/rancher#27898

[2.4] Backport enqueue CRTBs on RoleTemplate changes

---

app/role_data.go
pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/prtb_handler.go
tests/integration/suite/test_role_template.py

Forward port of https://github.com/rancher/rancher/pull/27941

Add "own" verb to indicate project or cluster ownership

---

go.mod
go.sum
vendor/github.com/rancher/types/apis/management.cattle.io/v3/tools_system_images.go
vendor/modules.txt

Vendor update for changes in rancher/types to bump Minio's version
**Related PR:** https://github.com/rancher/types/pull/1171

Types vendor update for minio version bump

---

pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Forward port https://github.com/rancher/rancher/pull/27778 
#23333

use v1.node name for draining node

---

pkg/controllers/user/nodesyncer/cordonfieldssyncer.go

current use of nodeMapLock at start of func with defer means it also applies to Lister calls for getNodeForMachine, which
would unnecessarily block other nodes from draining simultaneously
Backport logic from https://github.com/rancher/rancher/pull/27957
Issue: #23333

[v2.4] update nodeMapLock drain logic

---

go.mod
go.sum
vendor/github.com/rancher/types/apis/management.cattle.io/v3/tools_system_images.go
vendor/modules.txt

Vendor update for backport of minio update to
RELEASE.2020-07-13T18-09-56Z
**Related Issue:** https://github.com/rancher/rancher/issues/28025
**Related PR:** https://github.com/rancher/types/pull/1175

Vendor update for minio update

---

tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test

backport of https://github.com/rancher/rancher/pull/28053

[v2.4] move parameter to credential

---

pkg/httpproxy/sign.go

https://github.com/rancher/rancher/pull/27800
**Issue:**
https://github.com/rancher/rancher/issues/27965
**Notes:**
2.5 PR links different issue that doesn't apply to 2.4, but fix happens to address https://github.com/rancher/rancher/issues/27965 as well.

[Backport] 2.4: Sign fix

---

go.mod
go.sum
vendor/github.com/rancher/wrangler/pkg/summary/summarizers.go
vendor/modules.txt

https://github.com/rancher/rancher/issues/28029

Don't use kstate on norman objects

---

tests/validation/tests/v3_api/Jenkinsfile
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_ontag
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests
tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag
tests/validation/tests/v3_api/scripts/build.sh
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade_multiple

Adds `withFolderProperties` closure to each pipeline to use common environment variables stored in Jenkins folders.
Change JOB_NAME references to instead use last section of the path in pipeline
Update build.sh to use last section of path in JOB_NAME

Validation - 2.4 - Add withFolderProperties to pipelines for migration

---

app/machinedriver_data.go

**Problem:**
Cannot make request in UI to amazon KMS.
**Solution:**
Add the service to the accepted domain list.
**Issue:**
https://github.com/rancher/rancher/issues/28141

Add KMS endpoint to accepted listed

---

tests/validation/tests/v3_api/Jenkinsfile
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_ontag
tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests
tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag
tests/validation/tests/v3_api/scripts/build.sh
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade_multiple

Adds `withFolderProperties` closure to each pipeline to use common environment variables stored in Jenkins folders. 
Change JOB_NAME references to instead use last section of the path in pipeline
Update build.sh to use last section of path in JOB_NAME

Validation - Add withFolderProperties to pipelines for migration

---

tests/validation/lib/aws.py
tests/validation/tests/v3_api/resource/eks_nlb.yml
tests/validation/tests/v3_api/test_create_ha.py

Based on https://github.com/rancher/rancher/pull/28152

Rancher local HA installed in EKS cluster

---

tests/validation/tests/v3_api/cli_objects.py
tests/validation/tests/v3_api/test_cli.py

- Changing the test name to start with `test_cli`
- Adding code to switch back to earlier directory

Adding fixes for test_cli

---

tests/validation/tests/v3_api/cli_objects.py
tests/validation/tests/v3_api/test_cli.py

[Backport 2.4] Adding fixes for rancher CLI tests

---

pkg/kontainer-engine/drivers/eks/eks_driver.go

Reference: https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
**Related PR and Issue:**
https://github.com/rancher/rancher/issues/28120
https://github.com/rancher/kontainer-engine/pull/234

Update EKS cn region AMIs

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
vendor/modules.txt

bump the vendor of kontainer-engine

bump vendor of kontainer-engine

---

pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
pkg/controllers/user/pipeline/upgrade/upgradeimpl.go

Backport for this PR: https://github.com/rancher/rancher/pull/28166
Related Issue: #28025

[v2.3][Backport] Bump memory limit for pipeline Minio

---

pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
pkg/controllers/user/pipeline/upgrade/upgradeimpl.go

Backport for this PR: https://github.com/rancher/rancher/pull/28166
Related Issue: #28025

[v2.4][Backport] Bump memory limit for pipeline Minio

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_hosted_eks_cluster.py

Currently creates a 1 node EKS cluster.

Adding test for the new hosted EKS cluster creation

---

pkg/controllers/user/logging/generator/templatesource.go

Problem:
PR for collect containerd logs bring in dulicated configure cause dry-run return warning
Solution:
remove duplicated configure

Remove duplicated configure for cluster logging

---

go.mod
go.sum
pkg/kontainer-engine/drivers/rke/rke_driver.go
vendor/github.com/rancher/rke/cluster/defaults.go
vendor/github.com/rancher/rke/cluster/state.go
vendor/github.com/rancher/rke/cmd/cert.go
vendor/github.com/rancher/rke/cmd/encryption.go
vendor/github.com/rancher/rke/cmd/etcd.go
vendor/github.com/rancher/rke/cmd/remove.go
vendor/github.com/rancher/rke/cmd/up.go
vendor/modules.txt

* Vendor https://github.com/rancher/rke/pull/2186 using `v1.2.0-rc5`
* Change calling the changed function

Force use of local state for restore

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_rbac_2.py

add an environment variable to control  whether run tests for RBAC v2 or not

add a environment variable to control  wehter run tests for rbac v2 r not

---

tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix

JOB_NAME was still being used incorrectly in 2 places in Jenkins pipelines

Validation - Fix job_name in ontag pipelines

---

go.mod
go.sum
vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go
vendor/github.com/rancher/rke/cluster/defaults.go
vendor/github.com/rancher/rke/cluster/state.go
vendor/github.com/rancher/rke/cmd/cert.go
vendor/github.com/rancher/rke/cmd/encryption.go
vendor/github.com/rancher/rke/cmd/etcd.go
vendor/github.com/rancher/rke/cmd/remove.go
vendor/github.com/rancher/rke/cmd/up.go
vendor/modules.txt

* vendor rke v1.1.5-rc3
* vendor accompanying kontainer-engine

[release/v2.4] vendor kontainer-engine/rke

---

tests/validation/tests/v3_api/resource/istio/crds/peerauthentication.yaml
tests/validation/tests/v3_api/resource/istio/crds/requestauthentication.yaml
tests/validation/tests/v3_api/resource/istio/crds/workloadentry.yaml
tests/validation/tests/v3_api/resource/rbac/istio/istio_rbac.json
tests/validation/tests/v3_api/test_rbac_2.py

Adds cases for RBAC across new roles `istio-admin, istio-edit, istio-view`

Validation - Add Istio v2 RBAC cases

---

pkg/api/norman/customization/cluster/validator.go
tests/integration/suite/test_cluster_defaults.py

**Issue:**
https://github.com/rancher/rancher/issues/28111

Fix flaky cluster default test

---

pkg/image/export/main.go

Remove debug line

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/24955

vendor rke v1.2.0-rc6

---

pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go

This pr changes the cluster-upgrade app name to match cluster type
issue : https://github.com/rancher/rke2/issues/154

change upgrade app name to reflect cluster type

---

go.mod
go.sum
package/Dockerfile
vendor/modules.txt

Included:
- update UI version to `2.3.50`
- update rke to `v1.0.12-rc1`

[2.3] Changes for v2.3.9-rc1

---

tests/validation/lib/aws.py
tests/validation/tests/v3_api/test_hosted_eks_cluster.py

This PR tests importing an EKS cluster into Rancher.

Add import eks cluster test case

---

tests/validation/lib/aws.py
tests/validation/tests/v3_api/test_hosted_eks_cluster.py

Adding two test cases
- Edit cluster
- Delete cluster
Including validations from EKS console end.

Adding additional validation tests for hosted EKS cluster

---

pkg/api/norman/customization/cluster/validator.go

**Problem:**
A user could create an EKS cluster that did not have public or private access enabled. This is invalid and inevitably leads to an error in the eks-operator. This is because with neither enabled there is no way to communicate with the cluster. Prior, a user could create an EKS cluster that did not have public or private access enabled. This is invalid and inevitably leads
to an error in the eks-operator.
**Solution:**
An error will be returned if neither public nor private access is
enabled.
**Issue:**
https://github.com/rancher/rancher/issues/28158

Add validation for public and private access

---

pkg/systemtemplate/template.go

Add mountPropagation to node agent template

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/26506

[v2.4] Add mountPropagation to node agent template

---

go.mod
go.sum
package/windows/bootstrap.ps1
pkg/api/norman/customization/clusterregistrationtokens/formatter.go
pkg/api/norman/customization/clusterregistrationtokens/formatter_test.go
pkg/client/generated/management/v3/zz_generated_etcd_service.go
pkg/client/generated/management/v3/zz_generated_kube_apiservice.go
pkg/client/generated/management/v3/zz_generated_kube_controller_service.go
pkg/client/generated/management/v3/zz_generated_kubelet_service.go
pkg/client/generated/management/v3/zz_generated_kubeproxy_service.go
pkg/client/generated/management/v3/zz_generated_rancher_kubernetes_engine_config.go
pkg/client/generated/management/v3/zz_generated_scheduler_service.go
pkg/rkecerts/certs.go
pkg/rkeworker/docker.go

https://github.com/rancher/rancher/issues/28440
https://github.com/rancher/rancher/issues/25108
https://github.com/rancher/rancher/issues/28143

[master] win_ prefix forwardport

---

package/Dockerfile

Rebase of https://github.com/rancher/rancher/pull/28487

[v2.4] ui bump

---

pkg/clusterrouter/proxy/proxy_server.go
pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/25488

[v2.3] set proxy on transport only if cloud driver cluster

---

tests/validation/tests/v3_api/resource/rbac/logging/cr_clusterflow.yaml
tests/validation/tests/v3_api/resource/rbac/logging/cr_clusteroutput.yaml
tests/validation/tests/v3_api/resource/rbac/logging/cr_flow.yaml
tests/validation/tests/v3_api/resource/rbac/logging/cr_logging.yaml
tests/validation/tests/v3_api/resource/rbac/logging/cr_output.yaml
tests/validation/tests/v3_api/resource/rbac/logging/cr_resourcedefinition.yaml
tests/validation/tests/v3_api/resource/rbac/logging/logging_rbac.json
tests/validation/tests/v3_api/test_rbac_2.py

Based on https://github.com/rancher/rancher/pull/28190

Automation - adding logging v2 rbac tests

---

pkg/controllers/user/rbac/handler_base.go

These changes fix an issue where a cloned cluster owner RoleTemplate was not being recognized as a cluster owner role before  the `clusters+own` rule was added via the API. This was leading to an error like:
```
... rules[0].nonResourceURLs: Invalid value: []string{"*"}: namespaced rules cannot apply to non-resource URLs
```
which was backing up the workqueue for the RoleTemplate in question and leading to delays in processing time. 
Issue:
- rancher/rancher#28094

[2.4] Fix error due to cluster owner rules being applied to namespaced roles

---

pkg/clusterrouter/proxy/proxy_server.go
pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/28321
Original PR: https://github.com/rancher/rancher/pull/28412 https://github.com/rancher/rancher/pull/28506

[v2.4] forward port proxy handler fix 

---

pkg/multiclustermanager/routes.go
pkg/settings/setting.go

Adds setting to store the default place you'll go after logging in.

Add default login landing page setting

---

pkg/clustermanager/manager.go

https://github.com/rancher/rancher/issues/27736
Backport of https://github.com/rancher/rancher/commit/d7d6722296c26b9443c569e0411f6a11b1df8f28

[release/v2.4] Change user controllers timeout to be a bit longer

---

pkg/systemtemplate/template.go

https://github.com/rancher/rancher/issues/26506

revert PR #26507

---

pkg/auth/tokens/manager.go

To work with latest UI change, https://github.com/rancher/rancher/issues/28678

[v2.4] parse auth token ttl in milliseconds

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/package

Revert "changing back to dev branches"

---

pkg/controllers/managementuser/nodesyncer/nodessyncer.go
pkg/controllers/managementuser/nodesyncer/nodetaints.go

https://github.com/rancher/rancher/issues/28345

Create serviceOptions for generating plans

---

pkg/controllers/user/helm/common/common.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/28765

[backport] Make helm max history a setting

---

pkg/api/steve/proxy/proxy.go

https://github.com/rancher/rancher/issues/28223

Fix routing to local shell

---

pkg/controllers/managementuser/rbac/handler_base.go

Previous PR: 
- rancher/rancher#28516

[2.5] Forwardport cluster owner delay fix

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/28793

Set x-forwarded-proto

---

go.mod
go.sum

issue: https://github.com/rancher/rancher/issues/28279

Vendor norman to enable k3s coredns

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/26717

Vendor github.com/rancher/rke for CanalControllers

---

pkg/clusterrouter/proxy/proxy_server.go
pkg/dialer/factory.go

https://github.com/rancher/rancher/issues/28618
Original PR: https://github.com/rancher/rancher/pull/28412 https://github.com/rancher/rancher/pull/28506

forward port proxy handler fix 

---

pkg/auth/tokens/manager.go
pkg/settings/setting.go

https://github.com/rancherlabs/rancher-security/issues/478 
Original PRs:
https://github.com/rancher/rancher/pull/28674
https://github.com/rancher/rancher/pull/28683

foward port kubeconfig PRs

---

go.mod
go.sum
pkg/catalogv2/helmop/operation.go

https://github.com/rancher/rancher/issues/28816

Use local scheme for param decoding

---

pkg/controllers/management/eks/eks_cluster_handler.go

**Problem:**
Prior, cluster would appear to be in waiting state without error despite service account generation failing.
**Solution:**
Now, waiting condition will be set to false with an error message set.
**Issue:**
https://github.com/rancher/rancher/issues/28162

Set waiting to false if SA generation fails

---

tests/integration/suite/test_node.py

skip flakey test for now

---

scripts/validate

Added go mod tidy to the validate script.  This will remove any unused dependencies before we build rancher.
https://github.com/rancher/rancher/issues/28515

added go mod tidy to the validate script

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/26717

Vendor RKE to include 1.19 KDM changes

---

pkg/controllers/management/eks/eks_cluster_handler.go

**Problem:**
EKS cluster stuck in waiting if it does not have nodegroups.
**Solution:**
Fail waiting and show error message recommending the user adds a nodegroup.
**Issue:**
https://github.com/rancher/rancher/issues/28128

Fail wait on import if cluster has no nodegroups

---

tests/validation/tests/v3_api/test_hosted_eks_cluster.py

Changed the eks_config to remove unnecessary public and private access fields.

Fix eks import test

---

pkg/api/norman/customization/cluster/validator.go

**Problem:**
Prior, a user could not update a cluster unless the upstream spec had been populated on the status. The validator would also attempt to use the upstream spec to check for invalid configurations such as no nodegroups or private and public access
being disabled. This was a problem because a cluster may not have an upstream spec because a field needs to be changed in
its spec before an upstream cluster can exist. Using the upstream spec in the validation layer also added complexity even though the validations overlapped with eks-operator and the EKS API.
**Solution:**
Only validate fields in api layer if they are managed (not nil). Do not try to validate off of upstream spec and do not return an error if it does not exist yet.
**Issue:** …

Only validate managed fields

---

Dockerfile.dapper
package/Dockerfile
scripts/k3s-images.sh
scripts/package

https://github.com/rancher/rancher/issues/28916

Add k3s airgap images to build

---

pkg/api/norman/server.go

This got changed in a recent dashboard ui push but the files still live in the old location, so reverting back to the old location. 
https://github.com/rancher/rancher/issues/28971

Change filename for api-ui files

---

pkg/controllers/managementuser/controllers.go
pkg/controllers/managementuser/settings/controller.go

Set values in downstream clusters.

Sync install-uuid and system-default-registry

---

pkg/api/norman/customization/node/node.go
pkg/schemas/management.cattle.io/v3/schema.go

ignoreDaemonSets is a *bool, so it's null if user doesn't pick a value and panics.
https://github.com/rancher/rancher/issues/28905

set default for ignoreDaemonSets and return status ok

---

pkg/controllers/management/auth/manager.go

This commit fixed an issue where role/clusterRole are sent to the same
role Client for creation. This used to work before v1.19, but since
v1.19 is API server does validation which no longer allows it.

Fix role/clusterRole creation

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/26717

Vendor rancher/rke to v1.2.0-rc12 for Flannel

---

pkg/controllers/management/eks/eks_cluster_handler.go

**Issue:**
https://github.com/rancher/rancher/issues/28054

Refactor reenqueues and waits

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rke/issues/2248
https://github.com/rancher/rancher/issues/26717

Vendor rke v1.2.0-rc13

---

pkg/api/norman/customization/cluster/validator.go

**Problem:**
Previous cluster is being use without checking if it is nil.
**Solution:**
Check if previous cluster is nil.
**Issue:**
https://github.com/rancher/rancher/issues/29085

Fix nil in credential check

---

chart/templates/ingress.yaml
chart/templates/issuer-letsEncrypt.yaml
chart/templates/issuer-rancher.yaml
chart/tests/ingress_test.yaml
chart/tests/issuer_test.yaml

[2.4] Updated chart to support cert-manager v1.0.0

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rke/issues/2248

Bump to RKE v1.2.0-rc14

---

tests/validation/tests/v3_api/common.py
tests/validation/tests/v3_api/test_create_ha.py

this PR allows us to pass in the cert-manager's version in automation

add a parameter for cert-manager version

---

pkg/controllers/management/eksupstreamrefresh/eks_upstream_refresh.go

**Problem:**
Prior, it was possible for the setting's handler to sync before
the cron job was set. This caused a panic.
**Solution:**
Set refresh cron job in init function

Set refresh cron job in init function

---

cmd/rancherd/auth/auth.go
pkg/controllers/management/auth/project_cluster_handler.go

- validate that annotation map isn't nill before assigning any new annotations
- add user annotation to local cluster using reset-admin command
issue : https://github.com/rancher/rancher/issues/29051

Fix rancher pod panic in rancherd setup

---

cmd/rancherd/install.sh

To install rancherd using the public channel-server update.rancher.io
set the envvar INSTALL_RANCHERD_CHANNEL=`stable`|`testing`|`latest`
or use INSTALL_RANCHERD_VERSION for any desired version available at
'https://github.com/rancher/rancher/releases'
issue: https://github.com/rancher/rancher/issues/29209

Add rancherd install.sh

---

tests/integration/suite/test_role_template.py

Problem:
The webhook now enforces that only users with `**` in the local cluster
can create PRTBs so this causes the test to fail
Solution:
Update the test to do listing actions on PRTBs
Example: https://drone-pr.rancher.io/rancher/rancher/11319/1/2

Update test for webhook check

---

pkg/controllers/management/controller.go
pkg/controllers/management/rbac/legacy_ownerrefs_cleaner.go
tests/integration/suite/test_rbac.py

https://github.com/rancher/rancher/issues/29122
This commit updates roles and rolebindings that had incorrect ownerReferences prior to 2.4.6

Update role/rolebindings with incorrect ownerRefs

---

pkg/ui/routes.go

backports: https://github.com/rancher/rancher/issues/29330

[2.5] When no setting redirect to ember, not vue

---

pkg/catalogv2/helmop/operation.go

Backport of https://github.com/rancher/rancher/issues/29282

[2.5] Blindly create namespace and watch, don't assume get privileges

---

channels.yaml

In preparation for having an install script for rancherd, we need this
channels.yaml server so that we can stand up a channel-server that
points at it.

Add channels.yaml file

---

pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go

https://github.com/rancher/rancher/issues/29381

[release/v2.5] set default value for ignoreDaemonSets

---

pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go

https://github.com/rancher/rancher/issues/29381

set default value for ignoreDaemonSets

---

pkg/controllers/management/rkeworkerupgrader/upgrade.go
pkg/controllers/user/nodesyncer/cordonfieldssyncer.go

https://github.com/rancher/rancher/issues/29390
https://github.com/rancher/rancher/issues/29391
Original PRs: 
https://github.com/rancher/rancher/pull/29389
https://github.com/rancher/rancher/pull/29385

[release/v2.4] backport PRs

---

pkg/auth/providers/common/ldap/ldap_util.go
pkg/auth/providers/ldap/ldap_client.go

[2.5] Make ldap search for objectClass case-insensitive

---

pkg/controllers/management/eks/eks_cluster_handler.go

**Problem:**
EKS cluster not provisioning in airgap proxy setup because eks-operator requests to AWS API are timing out.
**Solution:**
Rancher will now pass HTTPS_PROXY, HTTP_PROXY, and NO_PROXY env variables to eks-operator. App will be redeployed when a change is detected in any of the aforementioned variables.
**Issue:**
https://github.com/rancher/rancher/issues/29070

Add proxy support to eks-operator integration

---

pkg/kontainer-engine/drivers/eks/eks_driver.go

Issue: https://github.com/rancher/rancher/issues/28317

update cn ami image-id to latest

---

pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementuser/rbac/crtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler.go

https://github.com/rancher/rancher/issues/29403
This PR has two commits, first is to fix the panic and to update the right set of labels
Second is to add the nil check for labels in other rbac controllers too to avoid panic. It covers the four controllers that were modified with this PR https://github.com/rancher/rancher/pull/28423

Fix panic while adding new label on CRTB

---

pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementuser/rbac/crtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler.go

https://github.com/rancher/rancher/issues/29403
Backport of https://github.com/rancher/rancher/pull/29496

[2.5] Fix panic while adding new label on CRTB 

---

pkg/controllers/management/eks/eks_cluster_handler.go

https://github.com/rancher/rancher/issues/29070
**Issue:**
https://github.com/rancher/rancher/issues/29070

[EKSv2][Backport] 2.5: Eks proxy support v2.5

---

pkg/controllers/management/node/controller.go
pkg/node/node.go

Per feedback to use an annotation with the faster ma[string]string lookup over looping finalizers.
https://github.com/rancher/rancher/issues/18221

Vsphere Drain Annotation Check
