- pkg/api/store/cluster/cluster_store.go
(This is only temporary, because condition again becomes Unknown during retry) 
Problem:
Using cond.IsUnknown doesn't include when condition has
finished with some error and it becomes cond.False. 
Solution:
Use !cond.IsTrue
https://github.com/rancher/rancher/issues/26120
> skip validation if clusterUpdated is not true

- app/role_data.go
https://github.com/rancher/rancher/issues/25990
Since UI fetches cis scan related information from the API and the user didn't have privileges, empty data was returned, hence the drop down was empty. Now this data is accessible to every "standard user"
> Adding rules for user and clusters-create roles to access cisconfigs and cisbenchmarks

- pkg/api/customization/cluster/actionhandler.go
- pkg/api/customization/cluster/actions_cis.go
- pkg/api/server/managementstored/setup.go
- pkg/controllers/user/cis/clusterScanHandler.go
- pkg/controllers/user/cis/utils.go
addresses: https://github.com/rancher/rancher/issues/25996
Minimum k8s version required for a benchmark version is available in the CRD. Added checks to compare that with the cluster version when the scan is initiated.
> verify min k8s version before running scan

- pkg/catalog/manager/catalog_common.go
Initially replaced `+` with `_` but should be `-` to be valid kubernetes name
**Related PR:** 
https://github.com/rancher/rancher/pull/25920
> Replace `+` with`-` for name compliance

- pkg/api/customization/cluster/actions_cis.go
addresses: https://github.com/rancher/rancher/issues/25996
The check should have been outside the if block, fixing the issue.
> fix for k8s version check for cis scan

- pkg/controllers/management/k3supgrade/deployPlans.go
- pkg/controllers/management/k3supgrade/deployPlans_test.go
Previously, the UI would only list one node when it was being upgraded.
Now the UI will show the top c nodes of the applying plan where c is
equal to the concurrency
Addresses https://github.com/rancher/rancher/issues/26148
> Report every node that is being upgraded

- app/kontainerdriver_data.go
- app/machinedriver_data.go
Move china cloud provider drivers to aliyun oss with global acceleration
Most of China users cannot download drivers on github due to network issues.
Also users in other places sometimes cannot download some drivers or drivers' UI (such as Baidu cluster driver UI) hosted in aliyun oss
https://github.com/rancher/rancher/issues/26204
> Move china cloud provider drivers to aliyun oss with global acceleration

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Problem:
Current design is to increment node version of cluster status on
every rke up. Deleting a node during upgrade also results into
a rke up, and it causes all nodes to upgrade again because of mismatch
between node and cluster's applied versions.
Solution:
change cluster.status.nodeversion only when plan changes on rke up
https://github.com/rancher/rancher/issues/26164
> increment cluster.Status.NodeVersion only on plan change

- app/app.go
- pkg/steve/setup.go
If local cluster is not enabled the following rules apply
disallow access to (they should result in 404)
/api/*
/apis/*
/v1/*
/k8s/clusters/local/*
allow only GET requests on
/v1/management.cattle.io* requests
> Don't allow access to the local cluster if local cluster is not enabled

- tests/validation/tests/v3_api/test_windows_cluster.py
Remove threading from windows test image pre-pull when building a Windows cluster
> Validation - Fix Windows test image pre-pull

- pkg/controllers/management/clusterprovisioner/provisioner.go
Problem:
This broke with a recent fix of moving when to increment
node version for upgrade logic. If node version is not
incremented, node plans won't get restored on rollback
https://github.com/rancher/rancher/issues/26289
> increment cluster node version for cluster rollback

- Dockerfile.dapper
- package/Dockerfile
- pkg/image/export/main.go
- pkg/image/resolve_test.go
- scripts/build-server
- scripts/package
This commit moves data.json from dockerfile.dapper into scripts/package,
also use dockerfile ARG to disable dockerfile caching.
> Fix kdm/data.json cache issue

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
saw this in logs: after RKE restore, if a node sync comes in before restore logic kicks in, it's going to reconcile thinking it's upgrade! 
```
2020/03/26 21:04:09 [INFO] image changed for [kubelet] old: rancher/hyperkube:v1.16.8-rancher1 new: rancher/hyperkube:v1.15.11-rancher1
2020/03/26 21:04:09 [INFO] cluster [c-nvgn7] worker-upgrade: plan changed for node [m-zglrc], call upgrade to reconcile cluster
2020/03/26 21:04:09 [INFO] cluster [c-nvgn7] worker-upgrade: updated cluster for upgrading: [3] 
2020/03/26 21:04:09 [INFO] cluster [c-nvgn7] worker-upgrade: updated node [m-svw2h] to cordon
2020/03/26 21:04:09 [INFO] cluster [c-nvgn7] worker-upgrade: updated node [m-tqkpp] to cordon
2020/03/26 21:04:10 [INFO] cluster [c-nvgn7] worker-upgrade: call upgrade to reconcile for node [m-svw2h] …
```
> remove unused code

- pkg/settings/setting.go
System chart version for external-dns has been changed; need to update the setting pointing to it
> Update the system catalog ID setting for external-dns chart

- pkg/agent/main.go
This double checks if manage agent is found and unmanaged agent can't be
cleaned up by managed agent due to race condition. Once managed agent
is found then the loop is immediately terminated.
> Stop reconciling if managed agent is found

- pkg/api/server/userstored/proxy_store.go
The resource name is takes from the Norman schema PluralName field.
In norman this is a plural form of the ID field which is typically
camelCase.  A Kubernetes resource field is always lowerscase. In
Rancher <=2.3 the RBAC system would do case insensitive checks
against all strings. In Rancher 2.4 the RBAC system was switch from
Norman to Steve.  Steve's implementation is much faster and more
proper and as a result does not do case insensitive checks. It is
expected that all input to the RBAC system is proper. This is the one
place in Rancher where we weird not generating a proper resource name.
> [2.4] Lowercase resource set in proxyStore

- pkg/api/server/userstored/proxy_store.go
The resource name is takes from the Norman schema PluralName field. In norman this is a plural form of the ID field which is typically camelCase.  A Kubernetes resource field is always lowerscase. In Rancher <=2.3 the RBAC system would do case insensitive checks against all strings. In Rancher 2.4 the RBAC system was switch from Norman to Steve.  Steve's implementation is much faster and more proper and as a result does not do case insensitive checks. It is expected that all input to the RBAC system is proper. This is the one place in Rancher where we weird not generating a proper resource name.
> Lowercase resource set in proxyStore

- pkg/auth/providers/ldap/ldap_client.go
https://github.com/rancher/rancher/issues/20002
Problem: For openldap during auth setup and login, after user bind, a query is executed to get the user's attributes. This query uses `base` search scope. For some users this query didn't return any user entries. As per the ldap logs provided by the user in issue description, their ldap server returns entry only if search scope is set to `subtree`. 
Solution: This commit changes ldap login query search scope from `base` to `subtree`. The query searches for entry with provided user object class so the entry returned should be that of a valid user. Works with our openldap and freeipa test setups.
> Change scope to subtree for openldap login search

- pkg/controllers/management/k3supgrade/deployPlans.go
- pkg/controllers/management/k3supgrade/register.go
While upgrading k3s clusters the controller may cause updates that do not change the cluster object. This means that the controller will not be run again to exit the updating state. In these cases the controller should re-enqueue itself.
Addresses https://github.com/rancher/rancher/issues/26286
> Enqueue controller if still in upgrading state

- pkg/controllers/management/k3supgrade/deployPlans.go
- pkg/controllers/management/k3supgrade/register.go
While upgrading k3s clusters the controller may cause updates that do not change the cluster object. This means that the controller will not be run again to exit the updating state. In these cases, the controller should re-enqueue itself.
This PR is needed to update the 2.4 release branch 
Addresses https://github.com/rancher/rancher/issues/26286, specifically https://github.com/rancher/rancher/issues/26286#issuecomment-608137620
> [2.4] Enqueue controller if still in upgrading state

- pkg/auth/providers/common/ldap/ldap_util.go
A group could have thousands of members and this makes the group query really slow on huge ldap setups. When we pull data for groups, we do not need the members unless it is for nested group functionality. For nested groups the query remains same and is not changed.
https://github.com/rancher/rancher/issues/26061
> Remove the member attribute of the group query

- pkg/auth/providers/common/ldap/ldap_util.go
Backport PR for https://github.com/rancher/rancher/issues/26061
What is the fix?
- The fix currently in test for this issue removes the "member" attribute from the search queries done for a group. This avoids pulling all the members of a group.
- It was found that when we pull details of a group, we do not need its list of members in most cases. Only case where we need to find a groups members is when nested group memberships are enabled on the auth config, since we then need to look at all sub-groups of this group.
What to test?
- We need to test and validate that all the functionalities related to OpenLDAP, FreeIPA and AD(less impacted) are unaffected.
- Especially testcases around cluster/project memberships granted to groups should let the group members correct access
- Also need to …
> [2.4]Ldap: Remove the member attribute of the group query 

- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/notifiers/sender.go
- pkg/notifiers/sender_test.go
**Problem:**
After users set a proxy url for a notifier, they can not really remove it in alert manager config. 
Rancher will always set an empty proxyUrl in alert manger config for the notifier. So alert manager cannot send out alerts due to the empty proxy url setting.
**Solution:**
So we need to check if  it's empty.
https://github.com/rancher/rancher/issues/26089
https://github.com/rancher/ui/pull/3854
> Fix the issue that users cannot remove proxyUrl of notifier

- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/notifiers/sender.go
- pkg/notifiers/sender_test.go
**Problem:**
After users set a proxy url for a notifier, they can not really remove it in alert manager config.
Rancher will always set an empty proxyUrl in alert manger config for the notifier. So alert manager cannot send out alerts due to the empty proxy url setting.
**Solution:**
So we need to check if it's empty.
https://github.com/rancher/rancher/issues/26089
https://github.com/rancher/ui/pull/3888
> [2.4] Fix the issue that users cannot remove proxyUrl of notifier

- go.mod
- go.sum
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
- vendor/modules.txt
**Problem:**
Preferences show other user's name and username instead of the logged in user
**Solution:**
Users can set `Me` field of another user to true in Rancher UI.
And it will be always true even after logout and login.
Set `Me` field to nocreate and noupdate
rancher/rancher#14420
https://github.com/rancher/types/pull/1131
> [2.4] Fix the issue that preferences show other user's name 

- pkg/controllers/user/nodesyncer/nodessyncer.go
UpdateLabel method is called for any type of node, even if nodePlan is
passed into the method. This commit fixed the bug where
node.status.NodeConfig could be nil if it is a imported node.
> Check nil pointer for node.status.NodeConfig

- app/machinedriver_data.go
When calling the AllocateEipAddress API, we need to specify the InternetChargeType parameter to PayByTraffic when the selected region is not in Mainland China (the default value is PayByBandwidth).
Update driver Aliyun ECS to support `InternetChargeType` field
Related PR:
https://github.com/rancher/ui/pull/3893
Related Issue:
https://github.com/rancher/rancher/issues/26526
> [2.3] Update Aliyun-Driver

- pkg/controllers/user/nodesyncer/nodessyncer.go
Backport: https://github.com/rancher/rancher/pull/26509
Issue: https://github.com/rancher/rancher/issues/26496
UpdateLabel method is called for any type of node, even if nodePlan is
passed into the method. This commit fixed the bug where
node.status.NodeConfig could be nil if it is a imported node.
> [2.4] Check nil pointer for node.status.NodeConfig

- pkg/controllers/user/nodesyncer/nodessyncer.go
Backport: https://github.com/rancher/rancher/pull/26509
Issue: https://github.com/rancher/rancher/issues/26497
UpdateLabel method is called for any type of node, even if nodePlan is
passed into the method. This commit fixed the bug where
node.status.NodeConfig could be nil if it is a imported node.
> [2.3] Check nil pointer for node.status.NodeConfig

- app/machinedriver_data.go
When calling the AllocateEipAddress API, we need to specify the InternetChargeType parameter to PayByTraffic when the selected region is not in Mainland China (the default value is PayByBandwidth).
Update driver Aliyun ECS to support InternetChargeType field
Related PR:
https://github.com/rancher/ui/pull/3892
Related Issue:
https://github.com/rancher/rancher/issues/15847
> [2.4] Update Aliyun-Driver

- tests/integration/suite/test_catalog.py
Problem:
Catalog refresh lists all catalogs then attempts a refresh, if another
tests deletes that test mid refresh the call errors
Solution:
Mark the test as nonparallel
Issue: https://github.com/rancher/rancher/issues/26451
> Update test to be nonparallel

- tests/integration/suite/test_catalog.py
Problem:
Catalog refresh lists all catalogs then attempts a refresh, if another
tests deletes that test mid refresh the call errors
Solution:
Mark the test as nonparallel
https://github.com/rancher/rancher/issues/26451
> [2.4] Update test to be nonparallel

- go.mod
- go.sum
- pkg/api/customization/cluster/formatter.go
- tests/integration/suite/test_cluster.py
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
- vendor/modules.txt
Problem:
The CLI displays a node count for clusters which required the CLI to make multiple API calls
Solution:
Add a new nodeCount field based off a lister and included in the formatter to help the CLI 
Depends on https://github.com/rancher/types/pull/1133
Issue https://github.com/rancher/rancher/issues/25227
> Add nodeCount to formatter

- pkg/controllers/user/alert/deployer/notification_template.go
Problem:
the resolved notification will not contain any body providing details of the cluster and deployment the error related to, but just the subject, e.g. [Resolved]Warning event of Pod occurred. As a result with multiple alerts firing it is not possible to determine from the Resolved notification which alert is resolved.
Solution:
Add body text to resolved notifications
Related Issue:
https://github.com/rancher/rancher/issues/24156
Before:
After:
2.4 Backport PR:
https://github.com/rancher/rancher/pull/26520
> [Master] Send detail information after alert is resolved

- pkg/controllers/user/alert/deployer/notification_template.go
Backport: https://github.com/rancher/rancher/pull/25551
Problem:
the resolved notification will not contain any body providing details of the cluster and deployment the error related to, but just the subject, e.g. [Resolved]Warning event of Pod occurred. As a result with multiple alerts firing it is not possible to determine from the Resolved notification which alert is resolved.
Solution:
Add body text to resolved notifications
Related Issue:
https://github.com/rancher/rancher/issues/24156
Before:
After:
> [2.4] Send detail information after alert is resolved

- scripts/istio-images-mirror
https://github.com/rancher/rancher/issues/26453
Updating the image to use latest beta version release by gatekeeper
> Updating OPA gatekeeper to latest beta version v3.1.0-beta.8

- tests/validation/tests/v3_api/Jenkinsfile
- tests/validation/tests/v3_api/test_create_ha.py
Support most cert types for HA installation: 
* Rancher self-signed
* Bring your own valid cert
* Bring your own self-signed cert
* LetsEncrypt
Certificate values are stored in Jenkins credentials
> Validation - Support HA install for most cert types

- pkg/catalog/utils/utils.go
- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- pkg/controllers/user/cis/clusterScanHandler.go
- pkg/controllers/user/cis/register.go
- pkg/controllers/user/helm/common/extra_args_test.go
- pkg/settings/setting.go
System apps like rancher-external-dns and cis-scan were using hardcoded setting to use the latest template from the system library. This requires us to always update rancher when a new version is added to the system library app. 
This fix removes the use of hardcoded settings and instead reads the latest version by listing the Catalog Template from the TemplateLister.
https://github.com/rancher/rancher/issues/26388
> Use Catalog TemplateLister to find out the latest version of system catalog apps

- pkg/agent/main.go
Problem:
Today if node is deleted from rancher, we immdiately delete v1.node from
kubernetes. Since we don't clean up agent(or did a poor job in cleaning
agent). All the system containers keep running including kubelet. This
will cause kubelet keep throwing node not found error. This is because
kubelet only register new node at start up, and without restart kubelet
it will not re-register node again. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L52
Solution:
In our agent code, add kubelet restart logic. Notice that this logic is
only added into unmanaged agent(which is only added through docker run
command). This is because once managed agents are added, kubelet should
be ready since managed agents are pods from daemonset which mean the
node is …
> Fix kubelet needs to be restart if node is deleted in UI (#25812)

- tests/validation/tests/rke/common.py
- tests/validation/tests/rke/test_upgrade.py
In this PR:
1. Removed the pre and post K8s upgrade related env variables from test_upgrade.py
2. In  validate_k8s_service_images, the expected images dictionary is built from the K8s version. 
3. Added addon verification related calls as part of validate_k8s_service_images
> Added RKE addon status/image verification methods

- pkg/api/customization/catalog/validator.go
- pkg/api/customization/catalog/validator_test.go
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
**Problem**
Helm version checks were too strict causing tiller not to start for helm2 consistently
Helm version checks were too strict so helm3 could only be one value
**Solution**
Allow for helm3 to be "helm_v3" or "v3"
Add validation for helm 3 since it needs to be specific values
Change the isHelm2 check to !isHelm3 to ensure helmVersion for helm 2 can be more flexible
**Issue**
#26450
> Helm version checks

- pkg/api/customization/catalog/validator.go
- pkg/api/customization/catalog/validator_test.go
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
**Problem**
Helm version checks were too strict causing tiller not to start for helm2 consistently
Helm version checks were too strict so helm3 could only be one value
**Solution**
Allow for helm3 to be "helm_v3" or "v3"
Add validation for helm 3 since it needs to be specific values
Change the isHelm2 check to !isHelm3 to ensure helmVersion for helm 2 can be more flexible
**Related**
https://github.com/rancher/rancher/pull/26531
**Issue**
#26450
> [2.4] helm version checks

- pkg/controllers/user/clusterauthtoken/register.go
Problem:
If a indexer already exists none of the controllers are registered so
clusterauthtokens do not get pushed downstream among other issues
Solution:
Ignore the indexer conflict error, this is expected after the first set
of controllers register.
Issue https://github.com/rancher/rancher/issues/26555
> Ignore error when adding indexer

- pkg/controllers/user/clusterauthtoken/register.go
Problem:
If a indexer already exists none of the controllers are registered so
clusterauthtokens do not get pushed downstream among other issues
Solution:
Ignore the indexer conflict error, this is expected after the first set
of controllers register.
https://github.com/rancher/rancher/issues/26555
> [forwardport] Ignore error when adding indexer

- pkg/api/store/app/store.go
- tests/integration/suite/test_app.py
https://github.com/rancher/rancher/issues/24371
During app create/update, we check if the catalog being used belongs to the current project/cluster if it's a project/cluster scoped catalog. We use `projectId` in request data for this check. If it's an app edit request, it doesn't need to contain `projectId` as we can get it from the app object. This commit adds logic to get `projectId` from app object and use that if no `projectId` is passed in the request
> [2.3] Get projectId from app obj during edit

- pkg/controllers/user/helm/controller.go
- pkg/controllers/user/monitoring/appHandler.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/register.go
https://github.com/rancher/rancher/issues/26440
Problem: Enabling rancher cluster-monitoring launches 2 apps, `cluster-monitoring` and `monitoring-operator`. If there's an error when installing these apps, monitoring controller has logic to force redeploy only the `monitoring-operator` app. So if the error is resolved, only `monitoring-operator` gets deployed but not `cluster-monitoring`
Solution: This commit adds the same logic to force deploy `cluster-monitoring` app, by checking whether the workload it should have created exists or not
> [2.4] Force redeploy cluster-monitoring if workload doesn't exist

- pkg/api/customization/persistentvolumeclaim/validator.go
- tests/integration/suite/test_persistent_volume_claim.py
https://github.com/rancher/rancher/issues/26605
Dropping the api validation to check if storageClass exists while creating a pvc from an existing pv, since it is not needed and the resources can be created without an actual storageclass existing.
> No need to check for storageClass existence while creating a pvc from pv

- pkg/api/customization/persistentvolumeclaim/validator.go
- tests/integration/suite/test_persistent_volume_claim.py
https://github.com/rancher/rancher/issues/26605
Porting to master this PR https://github.com/rancher/rancher/pull/26660
Dropping the api validation to check if storageClass exists while creating a pvc from an existing pv, since it is not needed and the resources can be created without an actual storageclass existing.
> No need to check for storageClass existence while creating a pvc

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
We initialize node upgrade strategy in cluster store, but on rancher upgrade if a cluster automatically gets upgraded, it'll panic because of nil upgradeStrategy
https://github.com/rancher/rancher/issues/26586
> check for nil upgradeStrategy

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
backport https://github.com/rancher/rancher/pull/26685 
We initialize node upgrade strategy in cluster store, but on rancher upgrade if a cluster automatically gets upgraded, it'll panic because of nil upgradeStrategy
#26586
> [v2.4] check for nil upgradeStrategy

- pkg/settings/setting.go
- server/server.go
This PR adds the ui-banners setting to Rancher, which will be used to facilitate customizable header / footer banners on the Rancher UI.
Note: GET requests to the setting are unauthenticated so that they can be queried from the login page.
Related Issue: https://github.com/rancher/rancher/issues/26562
> Add ui-banners setting

- app/machinedriver_data.go
This pull request adds preliminary backend support for the Oracle Cloud Infrastructure [node driver](https://github.com/rancher-plugins/rancher-machine-driver-oci/tree/jlamillan/initial_driver_impl). 
Notes:
- Initially, both `builtin` and `active` are set to false. 
- We plan to add some enhancements in subsequent minor releases including credential validation and fetching values from OCI dynamically (either using the meta API or directly in the JavaScript). 
- Here is a link an accompanying [article](https://medium.com/@jlamillan/self-hosted-kubernetes-clusters-on-oci-from-rancher-6b0656cdaec0) on Medium (currently in draft at the moment). 
**Cloud credentials**
**Node template**
**OCI Clusters**
> Add backend driver data for OCI cloud credentials and node template

- app/kontainerdriver_data.go
- tests/integration/suite/test_rbac.py
This pull request adds the most recent [Oracle Container Engine (OKE) cluster driver](https://github.com/rancher-plugins/kontainer-engine-driver-oke) to be `builtin` (but `inactive` by default for the time being). 
Notes:
- Link to a related [PR in the UI repo](https://github.com/rancher/ui/pull/3931) also up for review.
> Add Oracle Container Engine (OKE) as a builtin cluster driver.

- tests/validation/requirements_v3api.txt
- tests/validation/tests/v3_api/test_auth.py
The original structure and logic is untouched.
Most of the work was to remove some repetitive code like `enable_ad_nestedgroups` and `enable_openldap_nestedgroups`.
Pre-requirements are now automatically provisioned if they are not prepared. Including enabling auth and provisioning two clusters.
Updated the requirements file to be compatible with both `pip` and `pipenv` because `pipenv` is more strict and required `#egg=<app name>`
Everything else is just renaming to follow pep8 rules and making sure `flake8` report is ok.
> Changes to get test_auth working with AD auth provider

- pkg/controllers/management/rkeworkerupgrader/plan.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Problem:
creating node plan with empty dockerRootDir results into wrong kubelet's process
https://github.com/rancher/rancher/issues/26790
Problem:
change in node plan of registering nodes triggers cluster upgrade for other worker nodes
https://github.com/rancher/rancher/issues/26807
> [2.4] wait for dockerInfo to be set before creating node plan

- chart/templates/issuer-letsEncrypt.yaml
- chart/values.yaml
Removing ingress Class nginx so that any ingress controller can use the ingress defined for lets encrypt
https://github.com/rancher/rancher/issues/26323
> Add ingress class option to helm chart

- pkg/api/store/nodetemplate/store.go
- tests/integration/suite/test_node_templates.py
**Problem:**
Node template migration breaks API for any client referring to legacy node templates.
**Solution:**
Forward all request for legacy node templates to their corresponding migrated node template.
**Issue:**
https://github.com/rancher/rancher/issues/26160
> Return migrated node template

- pkg/api/customization/cluster/validator.go
- pkg/api/customization/cluster/validator_test.go
https://github.com/rancher/rancher/issues/26616
We got a panic when a cluster was validated that was created from a cluster template as it does not contain version information when posted to the API. The initial thought was to check for `spec.RancherKubernetesEngineConfig` being nil but there is a field when a cluster template is used (`ClusterTemplateRevisionID`) but this wasn't available in the type that was used (`v3.ClusterSpec`) but is available in `mgmtclient.Cluster` which is also used for the function `validateEnforcement`. So I changed the type and used that, only thing I ran into is that the field for ProfileType are strings in the other type so I have to cast them.
> Do not validate CIS on cluster from template

- tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test
- tests/validation/tests/v3_api/test_auth.py
- tests/validation/tests/v3_api/test_custom_host_reg.py
- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
Make sure to only remove the delete container if Rancher was deployed and `DELETE_RANCHER_SERVER` is `true`
Fix the `cluster` and `aws_nodes` references when cleaning up the test_auth resources.
Use the admin context when `DELETE_RANCHER_SERVER` is true to delete the clusters before deleting the Rancher server.
Added `validate` parameter for `create_and_validate_custom_host` for making the cluster validation optional. This will save resources as we won't need to validate workloads/ingresses availability for tests that don't need them for validation, in this case `test_auth` and thus no need to deploy VM instances larger than `t2.medium` in AWS.
> stabilize test_auth when used in Jenkins

- scripts/ci
Minimizing the number of calls to gh during the build process.
Will rely on docker publish plugin once merged and/or published for now.
> do not run package as part of CI

- scripts/ci
Taking package step out of script/ci to minimize chance of rate limiting during publishing steps.
> dont run package during ci process

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_create_ha.py
Now we can provide the existing hostname and k3s cluster's kubeconfig file for installing Rancher and provisioning a custom cluster on it. 
all resources (instances, target group, load balancer) will be named with a unified prefix
New parameters in Jenkins:
- RANCHER_HA_HOSTNAME
- RANCHER_HA_KUBECONFIG
> add support for installing Rancher in k3s cluster

- pkg/catalog/manager/catalog_common.go
Added support for uppercase characters in version strings by adding a ToLower in getValidTemplateNameWithVersion
> Support uppercase characters in version strings

- tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
- tests/validation/tests/v3_api/test_deploy_clusters.py
- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
This initial PR introduces a new Jenkinsfile that has three functional stages:
1. Deploy Rancher server
2. Deploy clusters into that rancher server
3. Run validation tests in parallel on those clusters
This is initially working with RKE clusters and will be expanded for EKS, GKE, and AKS very soon. Custom Clusters can also be added eventually.
> Scripts to create rancher, clusters, and run validation tests against them

- pkg/controllers/user/logging/generator/templatematch.go
Issue:
fluent-plugin-elasticsearch reloads connection after 10000 requests. Sometimes this reloading functionality bothers users to send events with ES plugin. Fluentd will stop to send logs to ES.
Solution:
Set it to false by following https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why . It works in users env with this setting. So users would like to have this configured by default. This is also the default value in upstream fluentd `kubernetes-daemonset`
https://github.com/rancher/rancher/issues/21744
Master PR
https://github.com/rancher/rancher/pull/26734
> [2.4.4] Set reload_connections to false by default for es

- pkg/controllers/user/logging/generator/templatematch.go
2.4 PR https://github.com/rancher/rancher/pull/26733
Issue:
fluent-plugin-elasticsearch reloads connection after 10000 requests. Sometimes this reloading functionality bothers users to send events with ES plugin. Fluentd will stop to send logs to ES.
Solution:
Set it to false by following https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why . It works in users env with this setting. So users would like to have this configured by default. This is also the default value in upstream fluentd `kubernetes-daemonset`
https://github.com/rancher/rancher/issues/21744
> [Master] Set reload_connections to false by default for es

- pkg/catalog/utils/utils.go
- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- pkg/controllers/user/cis/clusterScanHandler.go
- pkg/controllers/user/cis/register.go
- pkg/controllers/user/helm/common/extra_args_test.go
- pkg/settings/setting.go
Backport PR for https://github.com/rancher/rancher/issues/26388
System apps like rancher-external-dns and cis-scan were using hardcoded setting to use the latest template from the system library. This requires us to always update rancher when a new version is added to the system library app.
This fix removes the use of hardcoded settings and instead reads the latest version by listing the Catalog Template from the TemplateLister.
> [2.4] Use Catalog TemplateLister to find out the latest version of system chart

- pkg/controllers/user/helm/common.go
**Problem**
With helm 3 `helm template` errors when rendering a chart that contains crds resulting in an error being thrown and the app not getting installed
**Solution**
Use `--include-crds` flag when rendering charts with `helm template`
**Issue**
#26999
> Add include crds flag

- tests/validation/tests/v3_api/test_create_ha.py
Adding checks to validate the cluster and wait for it to come up "Active" before deploying a custom cluster.
> Adding validation for local cluster in a HA setup

- pkg/controllers/user/logging/generator/templatematch.go
Backport https://github.com/rancher/rancher/pull/26734
Issue:
fluent-plugin-elasticsearch reloads connection after 10000 requests. Sometimes this reloading functionality bothers users to send events with ES plugin. Fluentd will stop to send logs to ES.
Solution:
Set it to false by following https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why . It works in users env with this setting. So users would like to have this configured by default. This is also the default value in upstream fluentd `kubernetes-daemonset`
https://github.com/rancher/rancher/issues/27003
> [2.3] Set reload_connections to false by default for es

- pkg/catalog/manager/traverse.go
**Problem**
catalog was storing template version with toLower but using original name and version that was not lower case to try to retrieve the templates
**Solution**
Add toLower on template name and template version so its stored and called the same way
**Issue**
#19615
> Add to lower on template name and version

- scripts/istio-images-mirror
`core-dns` needs a multi-arch build and can't be included in the istio mirror images script
> Remove coredns from istio-images-mirror

- pkg/catalog/manager/traverse.go
**Backport**
------
**Problem**
catalog was storing template version with toLower but using original name and version that was not lower case to try to retrieve the templates
**Solution**
Add toLower on template name and template version so its stored and called the same way
**Issue**
#19615
> [2.4] Add to lower for name and version

- tests/validation/tests/v3_api/test_custom_host_reg.py
add support for setting the k8s version for custom cluster provisioned in auto-created Rancher server
> add support for setting the k8s version for custom cluster

- pkg/api/store/cluster/cluster_store.go
- tests/integration/suite/test_clustertemplate.py
For a cluster created from RKE template, update description, labels and annotations separately
#26754
> [ForwardPort] For a cluster created from RKE template, update description, labels, annotations

- tests/validation/lib/aws.py
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_create_ha.py
- tests/validation/tests/v3_api/test_import_k3s_cluster.py
This PR enables us to delete the rancher ha setup from AWS
it does the following:
- delete clusters within Rancher server 
- delete instances, target groups, load balancers, database, and route53 records in AWS
the only parameter needed is `CATTLE_TEST_URL`
Update:
add support for removing a k3s setup from AWS by resource name prefix  `RANCHER_RESOURCE_NAME`
> support removing rancher ha setup from AWS

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
Seen during build:
```
2020/05/21 14:26:27 [INFO] [mgmt-cluster-rbac-delete] Creating namespace local
2020/05/21 14:26:27 [INFO] [mgmt-cluster-rbac-delete] Creating Default project for cluster local
I0521 14:26:27.946919   28307 controller.go:606] quota admission added evaluator for: projects.management.cattle.io
E0521 14:26:27.948682   28269 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 4055 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3677640, 0x6bb0200)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.Handl …
```
> Avoid npe for cluster object in sync

- tests/integration/suite/test_istio.py
Should fix "ERROR at teardown of test_gateway" drone failures
> Istio tests need to be parallel

- app/kontainerdriver_data.go
Tencent has removed V2 API from their service endpoints last month. So Rancher users cannot use TKE cluster driver to provision cluster.
Upgrade Tencent Kubernetes Engine cluster driver to use V3 API .
https://github.com/rancher/rancher/issues/27121
Master PR: https://github.com/rancher/rancher/pull/27209
> [2.4.4] Update TKE cluster driver

- app/kontainerdriver_data.go
Use TKE V3 API as Tencent has removed V2 API from their service endpoints last month.
https://github.com/rancher/rancher/issues/27121
> [Master] Update TKE cluster driver

- pkg/controllers/user/endpoints/endpoints.go
- pkg/controllers/user/ingress/ingress.go
Ingress with no path will cause a panic
If no path is set the HTTP field is nil causing a panic. The below yaml cause Rancher to panic.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
spec:
rules:
- host: hostname
```
> Ingress with no path will cause a panic

- pkg/controllers/user/endpoints/endpoints.go
- pkg/controllers/user/ingress/ingress.go
If no path is set the HTTP field is nil causing a panic. The below yaml
cause Rancher to panic.
apiVersion: extensions/v1beta1
kind: Ingress
spec:
rules:
- host: hostname
> [2.4] Ingress with no path will cause a panic

- go.mod
- go.sum
- pkg/auth/providers/github/github_account.go
- pkg/auth/providers/github/github_client.go
- pkg/auth/providers/github/github_provider.go
- pkg/auth/providers/github/githubconfig_actions.go
- pkg/auth/tokens/manager.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_user_attribute.go
- vendor/modules.txt
https://github.com/rancher/rancher/issues/27028
Depends on https://github.com/rancher/types/pull/1145
This commit adds a field UserInfo on to UserAttribute CRD. The fields in
UserInfo vary per provider and can be set as a map. For github we want to save the
company, location, email and github ID.
The userInfo api endpoint of github already returns all these fields.
This commit adds 3 new fields to github Account type so we can get the
values for company,location and email from [github api response](https://developer.github.com/v3/users/#response). And saves
all these fields on the userAttribute crd object of that user
Although userinfo endpoint returns email too, it only does so for emails
set on the profile. For other users we need to request email from user/emails
endpoint. So this …
>  Store userinfo in userattribute

- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/controller.go
**Backport**
_______
**Problem**
App install is failing when trying to install app that has CRDs with helm 3 as the command being used to generate the notes does not support CRDs to be rendered
**Solution**
Change notes logic to use helm get notes after install is completed.
**Additional Info**
If install fails, the app revision available will have empty notes. This was not the behavior previously
**Issue**
#26999
> [2.4] Refactor render notes to use get notes

- tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
- tests/validation/tests/v3_api/test_deploy_clusters.py
- Added a check to be able to provide a rancher server instead of building one
- Fixed an error that was causing the cluster names to be incorrectly written to the environment variable
> Conditionally deploy rancher server for support matrix tests

- pkg/controllers/user/alert/manager/alertmanager.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/registrycertsyncer.go
**Problem:**
Rancher Server triggered alerts doesn't work when using customized cluster domain.
**Solution:**
Remove the hard code `cluster.local`
https://github.com/rancher/rancher/issues/26597
> Fix cannot use customized cluster domain

- pkg/controllers/user/logging/utils/elasticsearch.go
**problem**
With elasticsearch the test button is posting to `<cluster>/<index>/container_log`
For ES6 this is fine, but ES7 and higher types are not allowed anymore.
**suggestion**
* Fluentd ES test button with POST _bulk
* Fluentd ES test button removes the _type containerlog
**support**
ES6: type and id can be mixed
ES7: still allows a single type
ES8: types are going bye bye
**bulk request**
fluentd is posting with _bulk requests on root  
Because we use a loadbalancer that only allows _bulk requests,  
i would like to test my route with a bulk request
```
// elasticsearch <= 6
url.Path = path.Join(url.Path, index, "/container_log")
bulkTestData = httpTestData
// elasticsearch 7
url.Path = path.Join(url.Path, "/_bulk")
bulkTestData = []byte(`{"index":{"_index":"` + index + …
```
> [FEATURE] Post a elasticsearch test message with a bulk request.

- pkg/controllers/user/controllers.go
- pkg/controllers/user/nsserviceaccount/nssvcaccnt.go
- pkg/settings/setting.go
- tests/integration/suite/test_system_project.py
This change is made for the following CIS 1.5 test:
5.1.5 - Ensure that default service accounts are not actively used.
We need to make sure that an RKE cluster out of the box does not use the default serviceaccounts. Thus rancher system services (launched in any of the system namespaces) should not use default serviceaccount. 
We will exclude kube-system and default namespace since they can be used by Kubernetes and we need not control the SA usage in them.
Adding new controller to make sure default serviceaccounts of system namespaces have automountServiceAccountToken flag set to false.
> Default serviceaccounts of system namespaces should not be used

- pkg/controllers/user/controllers.go
- pkg/controllers/user/nsserviceaccount/nssvcaccnt.go
- pkg/settings/setting.go
- tests/integration/suite/test_system_project.py
This is forward port for PR rancher/rancher#27056
Adding new controller to make sure default serviceaccounts of system namespaces have automountServiceAccountToken flag set to false.
> [Forwardport] Default serviceaccounts of system namespaces should not be used

- package/Dockerfile
The branch is automatically calculated in 
https://github.com/rancher/rancher/blob/release/v2.3/pkg/settings/setting.go#L158
> Remove dev-v2.3 branch setting in Dockerfile

- Dockerfile.dapper
- package/Dockerfile
Should these be explicitly set to release-v2.4 or blank based on the settings logic? I'm thinking it should be blank, but figured I'd start with explicitly setting it since that's what we did with Release v2.4.3
https://github.com/rancher/rancher/blob/release/v2.4.4/pkg/settings/setting.go#L176
> Set KDM branch explicitly to release-v2.4

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/resource/account_update.yaml
- tests/validation/tests/v3_api/resource/default-allow-all.yaml
- tests/validation/tests/v3_api/test_cis_scan.py
- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
Also included some formatting to fix the reported `flake8` errors.
I focused on getting the following tests working only so far for this initial support.
```
test_cis_scan_run_scan
test_cis_complaint
```
There are number of tests that are assuming CIS 1.4 that will need to get updated in future update iterations.
> cis 1.5 support automation

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/resource/account_update.yaml
The latest CIS 1.5 changes include a fix for security scan id `5.1.5`. RKE based clusters won't need this step anymore as the service account patch will be applied to all namespaces except `default` and `kube-system` namespaces.
> [Automation] - removing service account patch step from CIS 1.5 requirements

- .drone.yml
Removing the env variable set by .drone.yml which was overriding the value for SYSTEM_CHART_DEFAULT_BRANCH  set in the package/Dockerfile for the head images.
It is easier to maintain this variable only at one place (package/Dockerfile) and change it in release branches at the same place as needed.
> The env variable for system chart branch per release version will be set from package/Dockerfile only

- main.go
**Problem:**
Users, especially those with clusters consisting of >100 namespace and pods, are running into a "backed up reader" error when switching between projects
**Solution:**
Disable http2 because we believe it is causing issues with the way we use websockets. @ibuildthecloud will continue to look into http2 to see what we can do to avoid these problems when we do integrate it.
**Issue:**
https://github.com/rancher/rancher/issues/26624
> Revert "Reenable HTTP2"

- tests/integration/suite/test_cluster_defaults.py
https://github.com/rancher/rancher/issues/27258
> flakey test: EKS subnet test failing because cluster is slow to create on arm

- tests/integration/suite/test_cluster_defaults.py
> [2.4] flakey test: EKS subnet test failing because cluster is slow to create on arm

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_node_annotation.py
- tests/validation/tests/v3_api/test_node_label.py
PR includes the following test wrt annotations on a node
1. Add/edit/delete via API
2. test_node_annotation_add_multiple
3. Add/edit/delete via kubectl
4. test_node_annotation_delete_multiple
5. test_node_annotation_k_add_a_delete_k_add
6. test_node_annotation_k_add_a_edit_k_edit
7. test_node_annotations_a_add_k_delete_a_add
8. test_node_annotation_a_add_k_edit_a_edit
9. RBAC tests Add/delete/edit via API
10. RBAC tests Add/delete/edit via kubectl
> Adding tests for validating annotations

- pkg/clusterrouter/lookup.go
https://github.com/rancher/rancher/issues/26482
> [forwardport] Cannot generate kubeconfig with cluster-scoped API tokens 

- tests/validation/tests/v3_api/test_secrets.py
`remove_resource(project)` was deleting the commonly used project which in turn resulted in the rest of the rbac test cases using this project to fail.
> Adding changes to fix failures in additional validation tests

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_logging.py
This fixes the `test_project_fluentd_target` test which was failing because `test_fluentd_target` removed the the fluentd app was part of the test teardown. Making the app to change state to `removing`.
When in `removing` state the `wait_for_app_to_active` check failed due to `app_data[0]` is empty when it checks for `deploying` state.
Here with this change we ensure wait until the app is removed during the test teardown before executing the next test.
Update the fluentd catalog template version to fix `test_send_log_to_fluentd` too.
> Automation - add wait for remove app in test_logging

- tests/validation/tests/v3_api/test_cis_scan.py
Fix to get the cluster context by the `User` for the RBAC test cases (RBAC tests had failures because of this)
Also added code to save nodes for CIS 1.4 and CIS 1.5 clusters
> Adding code to fix failure in cis scan run

- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
add the support for setting the value of docker_installed for instances for downstream clusters independently from the one for Rancher server
> set docker_installed for instances for downstream cluster 

- pkg/controllers/management/cloudcredential/controller.go
- pkg/controllers/management/clustertemplate/clustertemplate_rbac.go
- pkg/controllers/management/globaldns/globaldns_handler.go
- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go
- pkg/controllers/management/nodetemplate/nodetemplate.go
- pkg/controllers/management/rbac/rbac.go
This PR fixes the OwnerReferences of Role and Rolebindings created for ClusterTemplate, ClusterTemplateRevision, GlobalDNS, MulticlusterApp and NodeTemplate resources.
The OwnerReferences were using wrong kind and apiVersion for these resources. 
Example for ClusterTemplate:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
creationTimestamp: "2020-06-04T21:06:26Z"
labels:
cattle.io/creator: norman
name: ct-nlcgc-ct-a
namespace: cattle-global-data
ownerReferences:
- apiVersion: management.cattle.io
kind: clustertemplates
name: ct-nlcgc
uid: 0eb0f6ac-6e91-4a04-b9cf-8693bb702f36
resourceVersion: "25988"
selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/cattle-global-data/rolebindings/ct-nlcgc-ct-a
uid: 7f7c1263-9e01-4859-961e-099f532c0a65
roleRef:
apiGroup: …
```
> [2.4]Correct the OwnerReferences of Role and Rolebindings to use correct resource Kind and apiVersion

- pkg/auth/providers/common/usermanager.go
- pkg/auth/providers/local/local_auth_provider.go
Do enable a more "gitops" friendly flow we'd rather not prefer this
redudany field was required.  If one uses kubectl apply to create a
user with an external principal and then the controller adds
"local://" is modifies the principal list which is hard to reconcile
later on a subsequent apply.
> Do not require "local://" principal on users

- pkg/controllers/management/cloudcredential/controller.go
- pkg/controllers/management/clustertemplate/clustertemplate_rbac.go
- pkg/controllers/management/globaldns/globaldns_handler.go
- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go
- pkg/controllers/management/nodetemplate/nodetemplate.go
- pkg/controllers/management/rbac/rbac.go
[ForwardPort] for PR https://github.com/rancher/rancher/pull/27445
This PR fixes the OwnerReferences of Role and Rolebindings created for ClusterTemplate, ClusterTemplateRevision, GlobalDNS, MulticlusterApp and NodeTemplate resources.
The OwnerReferences were using wrong kind and apiVersion for these resources.
https://github.com/rancher/rancher/issues/26861
> Correct the OwnerReferences of Role and Rolebindings to use correct resource Kind and apiVersion

- tests/validation/tests/v3_api/common.py
fix the bug where the state of Longhorn app is active but workloads are not
> change the way to validate longhorn app 

- tests/validation/tests/v3_api/test_kdm_changes.py
- Cluster options now include - 2 nodes - 1 etcd/contro/worker and 1 worker nodes
- `DNS_PROVIDERS` is made optional using flag - `RANCHER_DNS_PROVIDER`
> Changing cluster spec and making DNS optional

- tests/validation/tests/v3_api/test_workload.py
Adds stateful set, cronjob, and job workload types to workload rbac tests.
> Add remaining workload types to RBAC tests

- pkg/auth/providers/saml/saml_client.go
https://github.com/rancher/rancher/issues/27288
This issue was introduced by https://github.com/rancher/rancher/pull/23814.
This is what I found out regarding this issue. For the `v1-saml` endpoint, we create a new mux router, and add named routes for the providers. This does not involve setting a handler for any of these named routes. When `root.Use` is configuring a handler for this router, and the route is called, there is no handler on the router which causes the handler to be nil, and the code will panic.
Moving this to the part of the code where we specify the `HandlerFunc` for the named routes resolves this issue.
Based on my testing, the `root.Use(responsewriter.ContentTypeOptions)` on the main mux router is already used on all the requests, but after talking to Dan, this needs to …
> Avoid calling a nil handler for SAML endpoints

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
https://github.com/rancher/rancher/issues/27218
appliedRepo is only set when private_registries is configured in the cluster config, else it is nil. The check for nil is always hit when the Rancher setup is configured to only use system default registry (when the registry does not require auth), so redeployAgent will always be hit in case where Rancher is configured with only a system default registry. This change scopes the repoChange check to clusters that have a private registry configured in the cluster (and appliedRepo is not nil). When system default registry changes, this will be caught by the logic in imageChange, as this uses the full repo path to the image (including the system default registry)
> Scope redeployAgent repo check for cluster repo

- pkg/controllers/user/logging/deployer/appdeployer.go
- pkg/controllers/user/logging/deployer/deployer.go
Problem:
When user updated docker root in cluster page, fluentd mounted docker root isn't updated. This bug is introduced in 2.3.
We need to update rancher logging's app config in this case.
Solution:
Update rancher logging app's config
Issue:
https://github.com/rancher/rancher/issues/21112
> [Master] fix fluentd mounted docker root isn't updated

- pkg/controllers/user/logging/deployer/appdeployer.go
- pkg/controllers/user/logging/deployer/deployer.go
Problem:
When user updated docker root in cluster page, fluentd mounted docker root isn't updated. This bug is introduced in 2.3.
We need to update rancher logging's app config in this case.
Solution:
Update rancher logging app's config
Issue:
https://github.com/rancher/rancher/issues/21112
Master PR:
https://github.com/rancher/rancher/pull/27585
> [2.4.6] fix fluentd mounted docker root isn't updated

- pkg/api/customization/nodepool/validator.go
- pkg/api/server/managementstored/setup.go
- tests/integration/suite/test_node.py
**Problem:** User added to cluster via cluster role binding can not update nodepool quantity.
**Cause:** Nodepool validator was only checking if the user has access to the entire nodetemplate. Since the added user had no access to the nodetemplate created by another use the error was being thrown.
**Fix:** Updated the validator to do the following.
First, check the user has access to the nodepool, this will pass for both original and added user.
Second, pull the nopepool from the lister. If the user is attempting to make a change to pool's template, validate the user has access to the new pool before letting them change it.
Validate everything else, -/+ to the nodepool quantity will validate as it is a PUT with the existing nodetemplate but a different quantity value passed. …
> [2.4] Update NodePool Validator

- tests/validation/tests/v3_api/common.py
show the total time for provisioning or updating a cluster
A sample output for the console:
```
The total time for provisioning/updating the cluster test-27340 : 00:04:24
```
> show the total time for provisioning or updating a cluster

- pkg/controllers/user/helm/controller.go
**Problem**
When `helm template` or `helm install` fails, the app continues to retry installing and the error backoff never happens so disk space fills up. This appears to be occurring due to the app status getting set to false and then set back to unknown which updates the app continuously.
**Solution**
Only change the app install status back to unknown if the app install status is true. This will allow for the controller back off to occur
**Issue**
#25383
> Change app status if true

- pkg/controllers/user/helm/controller.go
**Problem**
When helm template or helm install fails, the app continues to retry installing and the error backoff never happens so disk space fills up. This appears to be occurring due to the app status getting set to false and then set back to unknown which updates the app continuously.
**Solution**
Only change the app install status back to unknown if the app install status is true. This will allow for the controller back off to occur
**Issue**
#25383
> [2.4] Change app status if true

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/resource/account_update.yaml
Based on recent fixes for CIS 1.5 scan version, manual steps for test `5.1.5` have to be taken only for namespaces: `kube-system` and `default`
> Adding a fix for the manual steps for CIS 1.5 scan version

- tests/validation/tests/v3_api/test_kdm_changes.py
Modifying the print statement to make it easier to run validations tests on multiple clusters
```
Clusters: calico-63494,canal-89112,flannel-11742,weave-61277,
```
> Modifying the print statement to make it easier to run validations tests on multiple clusters

- pkg/api/store/app/store.go
- tests/integration/suite/test_app.py
**Problem**
When using the cli to install an app from a local chart (ex:`rancher app install . my-name`) an error is returned from the [ProjectClient.App.Create(app)](https://github.com/rancher/cli/blob/v2.4.3/cmd/app.go#L721) method stating "failed to find resource by id". Since the externalID is empty, any checks that require data from the externalID is failing on ByID checks. externalID is added to a template when the catalog it belongs to is being traversed to make those templates available [here](https://github.com/rancher/rancher/blob/b9812df065178f31eb9c5b17af79bc3106f7b8da/pkg/catalog/manager/traverse.go#L159). There is no catalog information available when installing an app from a local chart through the cli since it is a standalone chart. 
**Solution**
return nil when externalID …
> Do not check user access for user's locally stored charts

- pkg/api/store/app/store.go
- tests/integration/suite/test_app.py
**Backport**
https://github.com/rancher/rancher/pull/27591
**Problem**
When using the cli to install an app from a local chart (ex:rancher app install . my-name) an error is returned from the ProjectClient.App.Create(app) method stating "failed to find resource by id". Since the externalID is empty, any checks that require data from the externalID is failing on ByID checks. externalID is added to a template when the catalog it belongs to is being traversed to make those templates available here. There is no catalog information available when installing an app from a local chart through the cli since it is a standalone chart.
**Solution**
return nil when externalID is empty prior to ByID checks
**Issue**
#23832
> [2.4] Do not check user access for user's locally stored charts

- pkg/catalog/manager/crd.go
- tests/integration/suite/test_app.py
**Problem**
When a new version is added to a helm 3 catalog that is already in rancher, update is triggered instead of create, so the new version is not getting the helm version assigned to it
**Solution**
Add helm version to the update method to ensure new versions created on update have the helm version assigned
**Issue** 
#27252
> Add helm version to toCreate on update

- pkg/catalog/manager/crd.go
- tests/integration/suite/test_app.py
**Backport**
https://github.com/rancher/rancher/pull/27599
**Problem**
When a new version is added to a helm 3 catalog that is already in rancher, update is triggered instead of create, so the new version is not getting the helm version assigned to it
**Solution**
Add helm version to the update method to ensure new versions created on update have the helm version assigned
**Issue**
#27252
> [2.4] Add helm version to toCreate on update

- pkg/api/store/cluster/cluster_store.go
- tests/integration/suite/test_clustertemplate.py
This is a forwardport PR from release/v2.3: https://github.com/rancher/rancher/pull/24194
The fix is to ignore the template revision's "EnableClusterAlerting or EnableClusterMonitoring" flag when they are false during update cluster usecase for a cluster using a clusterTemplate.
This will allow the cluster updates (edit cluster to change overrides or update revision) to go through but keep monitoring/alerting intact.
https://github.com/rancher/rancher/issues/27753
> [2.4] Do not turn off monitoring/alerting from templateRevision during cluster updates

- pkg/api/store/cluster/cluster_store.go
- tests/integration/suite/test_clustertemplate.py
This is a forwardport PR missed from release/v2.3: #24194
The fix is to ignore the template revision's "EnableClusterAlerting or EnableClusterMonitoring" flag when they are false during update cluster usecase for a cluster using a clusterTemplate.
This will allow the cluster updates (edit cluster to change overrides or update revision) to go through but keep monitoring/alerting intact.
#27753
> Do not turn off monitoring/alerting from templateRevision during cluster updates

- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- pkg/controllers/user/nodesyncer/nodessyncer.go
nodename on v3.node changes depending on how it's registered, and it currently fails when cloud provider is enabled. Using v1.node name to run `kubectl drain` resolves the issue. 
https://github.com/rancher/rancher/issues/23333
> [2.4] get nodename from v1.Node

- pkg/controllers/management/auth/role_template_lifecycle.go
- pkg/controllers/management/auth/role_template_lifecycle_test.go
Currently when a RoleTemplate changes in the management cluster, only the ProjectRoleTemplateBindings associated with that RoleTemplate are enqueued for processing. This needs to be extended to ClusterRoleTemplateBindings associated with the RoleTemplate that is changing. This fixes an issue where RoleBindings in the management cluster are not created when a RoleTempalte with cluster context is updated. Enqueueing the CRTBs triggers the CRTB Handler logic which in turn creates the required RoleBindings in the management cluster. 
Previous related PR: https://github.com/rancher/rancher/pull/22394
> Enqueue CRTBs on RoleTemplate changes

- pkg/api/customization/nodepool/validator.go
- pkg/api/server/managementstored/setup.go
- tests/integration/suite/test_node.py
Problem: User added to cluster via cluster role binding can not update
nodepool quantity.
Cause: Nodepool validator was only checking if the user has access to
the entire nodetemplate. Since the added user had no access to the
nodetemplate created by another use the error was being thrown.
Fix: Updated the validator to do the following.
First, check the user has access to the nodepool, this will pass for
both original and added user.
Second, pull the nopepool from the lister. If the user is attempting to
make a change to pool's template, validate the user has access to the
new pool before letting them change it.
Validate everything else, -/+ to the nodepool quantity will validate as
it is a PUT with the existing nodetemplate but a different quantity
value passed. …
> [master] Update nodepool Validator

- tests/validation/tests/v3_api/test_node_template.py
Adds rbac cases to node template and cloud credential tests.
TEST CASE 1
- As a Std User1, create a node template - temp1
- As Std  User2, user should not be able to list/edit/delete node template - temp1
- As admin,  user should be able to    list/edit/delete node template - temp1
- Admin should   be able to use temp1 to create a cluster
TEST CASE 2
- As a Std User1, create a cloud credential - cred1
- As Std   User2, user should NOT be able to list/edit/delete cloud credential - cred1
- As admin,   user should be able to    list/edit/delete cloud credential - cred1
- Admin should   be able to use cred1 to create a cluster using a node template
> Add rbac cases to node template tests

- app/machinedriver_data.go
This adds the [cloudscale.ch](https://www.cloudscale.ch/en/) machine and ui-driver to the list of drivers available for installation with rancher.
This PR is essentially the same as https://github.com/rancher/rancher/pull/21347 (unfortunately, the source repo of the old PR got deleted, sorry for the noise). I have also updated the `docker-machine-driver-cloudscale` URL and rebased the commit.
Our drivers are maintained at:
* https://github.com/cloudscale-ch/ui-driver-cloudscale
* https://github.com/cloudscale-ch/docker-machine-driver-cloudscale
> Add cloudscale.ch driver.

- pkg/api/customization/logging/action.go
- pkg/controllers/user/controllers.go
- pkg/controllers/user/logging/deployer/testerdeployer.go
Problem:
1. This PR brings in some crash https://github.com/rancher/rancher/commit/4dcd2b751f1b2fecf21351b082935f8e12ca9446. It added appLister but forgot to init it here https://github.com/rancher/rancher/blob/master/pkg/controllers/user/logging/deployer/testerdeployer.go#L30. Then when we do a dry run, server crashes and returns 500, but UI still shows a success.
2. Dry run fails because it can't find the fluentd-test pod. The reason is that userContext from clustermanager does not start controller now, so we can't get pods from controller.
3. After fluentd 1.x <match fluent.**> will get deprecated warning.
Solution:
1. Init appLister
2. Use pod interface client instead of pod controller
3. Add latest fluentd suggested format <label @FLUENT_LOG>
Issue: …
> [2.4.6] Fix logging dry-run function return error

- pkg/controllers/management/auth/manager.go
https://github.com/rancher/rancher/issues/28014
Problem: On upgraded setups, clusterrolebinding for system account of a cluster
gets deleted.
The builtin cluster-owner and project-owner roles have a new verb to indicate
ownership. On upgraded setups, the cluster and project roleTemplateBindings
get reconciled before the roletemplates are reconciled. Because of which the
clusterRoleTemplateBinding controller compares a role's rules with the non-updated
cluster-owner roleTemplate. Same happens for project-owner role. This leads to the
deletion of clusterrolebindings that bind the user to owner role.
Solution: This commit adds back the check for role names of "cluster-owner" and
"project-owner" roles. So the role template binding controllers will consider
users with these roles as owners and …
> [2.4] Modify check to grant owner permissions

- pkg/controllers/management/auth/manager.go
Forward port of this: https://github.com/rancher/rancher/pull/28044
https://github.com/rancher/rancher/issues/28014
Problem: On upgraded setups, clusterrolebinding for system account of a cluster
gets deleted.
The builtin cluster-owner and project-owner roles have a new verb to indicate
ownership. On upgraded setups, the cluster and project roleTemplateBindings
get reconciled before the roletemplates are reconciled. Because of which the
clusterRoleTemplateBinding controller compares a role's rules with the non-updated
cluster-owner roleTemplate. Same happens for project-owner role. This leads to the
deletion of clusterrolebindings that bind the user to owner role.
Solution: This commit adds back the check for role names of "cluster-owner" and
"project-owner" roles. So the role template …
> Modify check to grant owner permissions

- pkg/api/norman/customization/logging/action.go
- pkg/controllers/managementuser/controllers.go
- pkg/controllers/managementuser/logging/deployer/testerdeployer.go
Problem:
1. This PR bring in some crash https://github.com/rancher/rancher/commit/4dcd2b751f1b2fecf21351b082935f8e12ca9446. it adds appLister but forget to init it here https://github.com/rancher/rancher/blob/master/pkg/controllers/user/logging/deployer/testerdeployer.go#L30. Then when we use dry run, and server got crash, return 500, but UI still show success.
2. After fluentd 1.x <match fluent.**> will get deprecated warning.
Solution:
1. Init appLister
2. Add latest fluentd suggested format <label @FLUENT_LOG>
Issue:
https://github.com/rancher/rancher/issues/26543
> [Master] Fix logging dry-run function return error

- go.mod
- go.sum
- pkg/controllers/management/eks/eks_cluster_handler.go
- vendor/github.com/rancher/eks-operator/pkg/apis/eks.cattle.io/v1/types.go
- vendor/github.com/rancher/eks-operator/pkg/apis/eks.cattle.io/v1/zz_generated_deepcopy.go
- vendor/modules.txt
**Problem:**
Cluster's with EKSConfigs are not finishing provisioning.
This is caused by two things:
1. eks-operator package is out of data, so when comparing the two EKSClusterConfig objects (the one on the cluster's spec and the one in cattle-global-data) they are evaluated as non equal. This disrupts the waiting for creation process.
2. Even in the above case the object should be re-enqueued. This is not happening because it is assumed that if the object is not observed to be in the "updating" phase, there is no need to wait on the object.
**Solution:**
1. Update eks-operator package to latest.2
2. Re-enqueue if the object is observed to be in any state other than "active".
**Issue:**
https://github.com/rancher/rancher/issues/28096
> Provisioning fix

- tests/validation/Dockerfile.v3api
- tests/validation/lib/aws.py
- tests/validation/requirements_v3api.txt
- tests/validation/tests/v3_api/test_boto_create_eks.py
Requires: 
```
RANCHER_EKS_ACCESS_KEY
RANCHER_EKS_SECRET_KEY
RANCHER_EKS_REGION
RANCHER_EKS_K8S_VERSION
AWS_SUBNET
RANCHER_EKS_ROLE_ARN
RANCHER_EKS_WORKER_ROLE_ARN
RANCHER_CLUSTER_NAME
```
To use the generated kubeconfig locally requires `aws` cli installed and configured w/ access key & secret key used to create the cluster
> Validation - Added test to create an EKS cluster using boto API

- pkg/controllers/managementuser/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/managementuser/pipeline/upgrade/upgradeimpl.go
Issue: https://github.com/rancher/rancher/issues/28031
Problem:
Newer version Minio consumes more memory. It may exceed the current limit.
Solution:
Bump memory limit from 200M to 500M and handle upgrade.
> Bump memory limit for pipeline Minio.

- pkg/controllers/managementuser/logging/generator/templatesource.go
Problem:
PR for collect containerd logs bring in dulicated configure cause dry-run return warning
Solution:
remove duplicated configure
Issue:
https://github.com/rancher/rancher/issues/26543
> Remove duplicated configure for cluster logging

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_rbac_2.py
add a check for the value of the global variable in the test_reader method, so it returns without going forward.
> fix a pytest failure caused by missing variable 

- tests/validation/tests/v3_api/test_create_ha.py
print the kubeconfig file after the cluster is accessible
> print the kubeconfig file after the cluster is accessible

- go.mod
- pkg/pipeline/providers/bitbucketcloud/provider.go
- pkg/pipeline/providers/bitbucketserver/provider.go
- pkg/pipeline/providers/common/provider.go
- pkg/pipeline/providers/common/provider_test.go
- pkg/pipeline/providers/github/actions.go
- pkg/pipeline/providers/github/provider.go
- pkg/pipeline/providers/gitlab/provider.go
Issue: https://github.com/rancher/rancher/issues/27011
Problem:
Decoding unstructured pipeline provider configs fails in k8s 1.18+ with managedFields introduced.
Solution:
Decode time fields properly.
> [2.4] Fix unstructured decoded with managedfields

- pkg/pipeline/providers/bitbucketcloud/provider.go
- pkg/pipeline/providers/bitbucketserver/provider.go
- pkg/pipeline/providers/common/provider.go
- pkg/pipeline/providers/common/provider_test.go
- pkg/pipeline/providers/github/actions.go
- pkg/pipeline/providers/github/provider.go
- pkg/pipeline/providers/gitlab/provider.go
Forward port for PR https://github.com/rancher/rancher/pull/28169
Issue: https://github.com/rancher/rancher/issues/27011
Problem:
Decoding unstructured pipeline provider configs fails in k8s 1.18+ with managedFields introduced.
Solution:
Decode time fields properly.
> [forwardport] Fix unstructured decoded with managedfields

- tests/validation/tests/v3_api/test_custom_host_reg.py
We do not want the multi-cluster-management feature flag to be enabled by default in our install.
> Validation - Disable setting mcm feature flag by default

- tests/validation/tests/v3_api/common.py
Changed line `expected_k8s_version = version[:version.find("-")]` to search for `"-rancher"`. This will allow us to continue automation on k8s versions such as `v1.19.0-rc.4-rancher1-1`. Otherwise, automation will fail searching for v1.19.0 when actual version is `v1.19.0-rc.4`.
> Change cluster_version to accommodate rc versioning

- pkg/controllers/management/auth/indexes.go
- pkg/controllers/management/auth/manager.go
Issue addressed by this PR:
- rancher/rancher#28094
We were unintentionally removing important labels from cached objects. Any modifications should go through the api server so their deltas can be consumed and processed by the controller's underlying SharedIndexInformer and cache/indices can be updated accordingly. I added a deep copy to mitigate this issue. The cache no longer contains stale keys that resolve to nil objects with this change. I also addressed an issue with the `membershipBindingOwnerIndex` where we were returning once we found a single owner. Technically there can be multiple owners, so this function now returns a list of all owner keys.
> [2.4] Fix cache inconsistencies for RoleBindings/ClusterRoleBindings

- pkg/auth/providers/common/usermanager.go
- pkg/auth/tokens/manager.go
If token's expired and still being deleted, create tokens would fail
> [v2.4] add retry for creating kubeconfig tokens

- pkg/controllers/user/rbac/globalrole_handler.go
- pkg/controllers/user/rbac/handler_base.go
A role template with cluster ownership permissions can be either:
1. Builtin `Cluster Owner`
2. Have rules for "own" on "clusters" resources
3. Inherit from a role template that has 1. or 2.
When a user is added to a cluster with any of 1, 2, or 3, there should not be any namespaced roles created, this PR fixes an issue where that was happening and leading to errors. 
When a user is created and associated to a role, if they are associated to a global role with admin permissions that isn't admin, they are not getting the proper permissions / capabilities. Changes to globalrole_handler.go fix this issue. 
Previous related PR: 
- rancher/rancher#27978
> [2.4] Changes for detecting admin & cluster ownership

- pkg/auth/tokens/manager.go
thought I forgot passing correct duration while fixing auth token bug but seems like UI is now passing the value in minutes so need to update
> [v2.4] pass correct ttl duration for validating max ttl

- pkg/auth/providers/common/usermanager.go
if the create fails, on retry we create using incorrect object
> [v2.4] don't override token during retry

- pkg/clusterrouter/proxy/proxy_server.go
https://github.com/rancher/rancher/issues/25488 
**Setup:** 
Spin up Rancher HA in semi-airgapped environment (with HTTP/HTTPS forward proxies and no ability for Rancher to directly access the internet without utilizing these forward proxies)
Attempt to provision a ClusterDriver cluster (GKE, EKS, AKS for example)
**Note** 
Only tested for ClusterDriver clusters, but I'm guessing it'd also break for RKE clusters -- Couldn't test that out because of https://github.com/rancher/rancher/issues/28411 
**Issues:** 
(1) agents are unable to deploy into the cluster and the cluster never finishes provisioning 
This is because the request doesn't go through proxy and directly to cluster's endpoint. 
(2) kubectl exec shell and view logs from UI doesn't work 
For upgrade requests, the …
> [v2.3] utilize proxy in proxy handler

- pkg/api/customization/cluster/formatter.go
Problem:
When listing large amounts of clusters (200) the call takes approx 40
seconds to complete vs 1 second when using kubectl directly
Solution:
The formatter uses a hard API call to check auth on the clusterTemplate
perms for the user. This adds 200ms per cluster when running locally.
Swap this call to use the cached access through the request
AccessControl
Issue: https://github.com/rancher/rancher/issues/27192
> Update auth check to use cache

- pkg/api/norman/customization/cluster/formatter.go
Problem:
When listing large amounts of clusters (200) the call takes approx 40
seconds to complete vs 1 second when using kubectl directly
Solution:
The formatter uses a hard API call to check auth on the clusterTemplate
perms for the user. This adds 200ms per cluster when running locally.
Swap this call to use the cached access through the request
AccessControl
https://github.com/rancher/rancher/issues/27192
> [forwardport] Update auth check to use cache

- pkg/agent/cluster/controllers.go
This set of user controllers was not running in the agent which handles the resources which are not working. 
https://github.com/rancher/rancher/issues/28338
> Add user controllers back to agent

- go.mod
- go.sum
- vendor/modules.txt
RKE v1.0.12 has been released and the dependency needs to be updated in Rancher
> [2.3] Update RKE to v1.0.12

- pkg/api/norman/customization/cluster/validator.go
- pkg/api/norman/server/managementstored/setup.go
**Problem:**
User can create multiple Rancher clusters referencing the same EKS cluster.
**Solution:**
Add validation to check that a Rancher cluster does not already exist with the given displayName.
**Issue:**
https://github.com/rancher/rancher/issues/28130
> Multi import fix

- pkg/data/management/kontainerdriver_data.go
This MR updates [OKE Cluster Driver](https://github.com/rancher-plugins/kontainer-engine-driver-oke) to version `v1.4.2`, that has a small but important [bug-fix](https://github.com/rancher-plugins/kontainer-engine-driver-oke/commit/bd5a70b80f57e57835afbbec74204915b700c5ac) to create the correct number of nodes in a single AD region.
Related Issue:
https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/14
> Update OKE cluster driver.

- pkg/data/management/machinedriver_data.go
This MR updates [OCI Node Driver](https://github.com/rancher-plugins/rancher-machine-driver-oci) to version `v1.0.1`, that has a small but critical [update](https://github.com/rancher-plugins/rancher-machine-driver-oci/commit/83f0fea460841c7150bd9a8d6d0c46c791f5e17c) to the driver's internal pre-check.
Related Issue:
#28449
> Update OCI node driver.

- channels.yaml
In preparation for having an install script for rancherd, we need this
channels.yaml server so that we can stand up a channel-server that
points at it.
The need is that channel-server allows our install script to control what is considered "stable" better than just pointing at the "latest" tag on github. The problem with the "latest" tag on github is that, for example, 2.3.17 would be marked as latest if it came out most recently if even a 2.5.1 existed. So, we standup a public service at update.rancher.io that is running channel-server which allows us to say 2.5.1 is the latest stable, but if you want the latest 2.3 release, just point at the v2.3 channel
> Add channels.yaml file

- tests/validation/tests/v3_api/test_istio.py
Skip the cert manager tests until it can be fully removed.
> Validation - Skip certmanager test in Istio tests

- pkg/settings/setting.go
The old behavior will be preserved by default. It's configurable for opt-in by changing the value. 
https://github.com/rancher/rancher/issues/28668
> [v2.4] update AuthTokenMaxTTLMinutes default to 0

- pkg/controllers/managementuser/cis/clusterScanHandler.go
- pkg/controllers/managementuser/cis/register.go
If CIS v2 is enabled via dashboard on a cluster, we want to disallow users from running a CIS v1 scan. 
Reason is that we do have a limitation of running only one CIS scan at any given time for a cluster - there cannot be parallel scans running. This limitation is due to the sonobuoy tool. 
Even if we want to just stall the scans when another one is running, it is complicated to predict the run times of scheduled scans if present on the cluster. Hence we just want to disable the v1 scans if user has enabled CIS v2 feature.
> Check if CIS v2 CRD is present and error out while running CIS v1 clusterscan

- pkg/dialer/factory.go
During cluster provisioning you could end up with a node being first in the
list that is worker only and wait to be provisioned because the control
plane is still provisioning. In this situation we chose the worker node for
the node dialer which fails because the nginx proxy does not exist yet. 
Because the node dialer fails we can't deploy the cluster agent and get
stuck in a failing loop.
> Only use the node dialer if the host is a control plane node or ready

- pkg/controllers/managementuser/helm/common/common.go
- pkg/settings/setting.go
Problem:
HelmMaxHistory is hardcoded to 10, in a setup with many helm apps this
causes a lot of secrets to be created
Solution:
Make helmMaxHistory a setting so it can be set based on customer needs
https://github.com/rancher/rancher/issues/28728
> Make helm max history a setting

- pkg/agent/steve/steve.go
If the x-forwarded-proto header is not set properly it will redirect
to HTTPS but the path will be wrong.  So just don't run on https as it's
not ever used.
> Do not run on HTTPS because it might redirect improperly

- pkg/controllers/management/nodepool/nodepool.go
This makes the logic consist where no role means worker role.  For custom this is how we do it, but for node pools it seems to be different.
https://github.com/rancher/rancher/issues/28758
> Set node role to worker if nodepool has no role assigned

- pkg/schemas/mapper/os_info.go
- pkg/schemas/mapper/os_info_test.go
**Problem:**
Aliyun virtual kubelet node cannot be displayed in the Rancher UI because the node.status.capacity.cpu of the virtual kubelet is `1M`, which is not a number.
`1000m`, `1`, `100`, `1M` are all valid values for node.status.capacity.cpu field in Kubernetes.
However, in Rancher types, the filed is int, and we will not convert it to number if they are not int in types.
**Solution:**
So we need to handle other cases
https://github.com/rancher/rancher/issues/26226
> Fix node.status.capacity.cpu conversion issue

- pkg/api/norman/customization/kontainerdriver/actionhandler.go
- pkg/image/export/main.go
- pkg/image/resolve.go
- pkg/image/resolve_test.go
- scripts/package
**This PR includes the following:**
Add support in image list generator for picking images in rancher/charts so they are included in the generated `rancher-images.txt`. The `rancher/charts` repo is cloned and pre-processed so that images are picked the same way is done for system charts. The pre-processing includes deleting the index files so that a virtual one is built, and finding and extracting the latest version's tgz of each chart. 
Functions in the image and main package were modified to take in an extra path to a local `rancher/charts` repo.
The main reason behind doing that versus just calling main.go twice (one for each chart repo) is that we would be adding in unnecessary complexity because we overwrite the generated images text file, and images are normalized before is created. …
> Add support for rancher/charts in rancher-images.txt generator

- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Errors are not displayed to user during provisioning.
**Solution:**
Copy failure message from EKS cluster config object to Rancher cluster. If it is not empty set provisioning to false.
**Issue:**
https://github.com/rancher/rancher/issues/28129
> Record provisioning errors from eks-operator

- go.mod
- go.sum
Vendor rke v1.2.0-rc9
Includes: https://github.com/rancher/rke/pull/2234
> Vendor rke v1.2.0-rc9

- scripts/test
This adds significant time to failed builds and is not used due to the
sheer volume of them when something does fail.
> Drop printing rancher logs on test failure

- go.mod
- go.sum
- pkg/catalogv2/git/download.go
- pkg/controllers/dashboard/helm/repo.go
If we fail to update a repo or the system catalog is set to bundled we do
not record any error.
> Don't error out on updating bundled helm repos

- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Prior, nodegroups were only being checked for imported clusters. This check should be performed regardless of a cluster being imported or not as neither type will be able to deploy the rancher agent without one. Prior, only the spec was being checked for nodegroups, but an imported cluster may not have nodegroups as a managed field. In this case the nodegroups should be reflected on the upstream spec.
**Solution:**
Now, it will be evaluated if a cluster has more than one nodegroup whether it is imported or not. Upstream spec will be checked for nodegroups if the field is nil on spec.
**Issue:**
https://github.com/rancher/rancher/issues/28900
https://github.com/rancher/rancher/issues/28422
> Fix nodegroup length check

- package/Dockerfile.agent
- package/share-root.sh
- pkg/controllers/management/rkeworkerupgrader/plan.go
- pkg/rkenodeconfigserver/nodeserver.go
- pkg/rkenodeconfigserver/nodeserver_test.go
Problem:
The share-mount process is ran on every install/upgrade. This was used for boot2Docker which is no longer supported. 
Solution:
Drop the share-mount binary from the agent image and stop running it. This does not stop the rke process `share-mnt` from running in order to write certs. 
These are two different things with similar names that perform different functions. 
https://github.com/rancher/rancher/issues/25702
> Drop share mount process

- pkg/agent/steve/steve.go
- pkg/api/steve/proxy/proxy.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/features/feature.go
- pkg/rbac/access_control.go
- pkg/wrangler/context.go
This will enable dashboard permanently. The feature CR will still exist but it just won't do anything to dashboard. This is being done so that rollback will not be broken if the CR is dropped on upgrade. 
https://github.com/rancher/rancher/issues/28928
https://github.com/rancher/rancher/issues/28930
> Drop dashboard from being a feature flag

- tests/validation/tests/v3_api/test_airgap.py
Change the bastion password to default to the ADMIN_PASSWORD in the airgap validation tests
> Validation - Update source of bastion credentials for airgap jobs

- main.go
- pkg/clustermanager/manager.go
By properly configure the NextProtos to disable http2. Using the
DISABLE_HTTP2 env var causes a repeated log message.
> Don't use DISABLE_HTTP2 env var

- pkg/apis/management.cattle.io/v3/tools_system_images.go
- pkg/controllers/managementuser/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/managementuser/pipeline/upgrade/upgradeimpl.go
Issue: https://github.com/rancher/rancher/issues/28167
1. Adds the `cattle.io/creatorId: norman` label on registry credential creation. It is gone due to framework changes but is required in [secret controller](https://github.com/rancher/rancher/blob/0325ea11a57b59118863483cf2d4c2167b684fad/pkg/controllers/managementuser/secret/secret.go#L73)
2. Bump rancher/pipeline-tools image version for registry-proxy configuration updates.
Depend on https://github.com/rancher/pipeline-tools/pull/23 and a newer image release(expected to be `rancher/pipeline-tools:v0.1.15`)
> Fix embeded registry pull

- package/entrypoint.sh
https://github.com/rancher/rancher/issues/28910
The idea is that it will first look for a k8s service account, if it finds it it assumes it is running in k8s, not docker standalone.
> Detect and require --privileged on container start

- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Prior, upstream spec was being checked for nodegroup length even if nodegroups were set on spec. This caused an error when nodegroups were finished provisioning in EKS so the EKS Cluster Config object was in "active" phase but the refresh handler had not updated the upstream spec since before the nodegroups were being created.
**Solution:**
Evaluate upstream only if spec nodegroups are nil.
**Issues:**
https://github.com/rancher/rancher/issues/28962
> Evaluate upstream only if spec nodegroups are nil

- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Prior, rancher would fail if deploying eks-operator returned an error. This disrupted setups that did not have a local cluster.
**Solution:**
Now, cluster condition will be set to false and error will be displayed.
**Issue:**
https://github.com/rancher/rancher/issues/28764
> Remove panic when deploying eks-operator fails

- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/data/management/role_data.go
- tests/integration/suite/test_kontainer_engine_annotations.py
**Problem**: Users with role cluster-member, project-owner and project-member cannot list Charts
**Solution**: Add rules for the `catalog.cattle.io` CRDs to these roles
With this change, 
* Cluster-member:
1. Can list all Charts
2. Can list installed Apps only of their projects (if they belong to a project or have created one)
* Project-owner and Project-member 
1. Can list all Charts
2. Can list only those Apps that are installed in namespaces belonging to their projects. (By default I can't select what namespace to install an app in in the dashboard, so I tested this by first installing an app then moving the namespace to a project)
* This commit also adds rules for the project scoped Read-only role:
1. Can list all Charts
2. Can list only those Apps that are installed in namespaces …
> RBAC for v2 apps

- pkg/api/steve/clusters/clusters.go
This commit switched to use cattle-system instead of dashboard-shells
for shell containers, in order to avoid patching dashboard-shells for
CIS compliance.
> Use cattle-system instead of dashboard-shells for shell

- pkg/api/norman/customization/cluster/validator.go
- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Users need the option to upgrade nodegroups the amazon way or to create new nodegroups and delete ones that are outdated.
**Solution:**
Nodegroup versions now must be provide. On create they must match the control plane's kubernetes version. Control plane and nodegroup versions will be validated against supported versions. More in depth validation will be performed in the eks-operator.
**Issue:**
https://github.com/rancher/rancher/issues/27777
https://github.com/rancher/rancher/issues/28968
> Nodegroup upgrade

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- pkg/controllers/managementuser/rbac/crtb_handler.go
- pkg/controllers/managementuser/rbac/globalrole_handler.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/namespace_handler.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
- tests/integration/suite/test_rbac.py
The projectroletemplatebinding and clusterroletemplatebinding UIDs are used as label keys for
clusterrolebindings and rolebindings in the management cluster as follows
* CRTB.UID is the label key for a CRB, CRTB.UID=memberhsip-binding-owner
* CRTB.UID is label key for the RB, CRTB.UID=crtb-in-project-binding-owner (in the namespace of each project in the cluster that the user has access to)
* PRTB.UID  is the label key for a CRB, PRTB.UID=memberhsip-binding-owner (with role c-xxxx-clustermember)
* PRTB.UID is the label key for RB, PRTB.UID=memberhsip-binding-owner (with role denoting the permissions in project)
* PRTB.UID is also the label key for RB, PRTB.UID=prtb-in-cluster-binding-owner (with role=exact roletemplate ID)
PRTB/CRTB are also used as label values for clusterrolebindings …
> Add labels to link PRTB/CRTB to RB/CRB  by namespace+name

- pkg/api/norman/customization/cluster/validator.go
**Problem:**
Lasso has been fixed so that passing an empty slice for a field does not automatically result in nil. Due to this, saving the same cluster spec as before would result as an empty slice instead of nil. These are technically not equal and result in an error.
**Soution:**
Now, since they are effectively equal they will be treated as such.
**Issue:**
https://github.com/rancher/rancher/issues/28999
> Treat nil and empty subnets as equal

- pkg/api/norman/customization/node/node.go
- pkg/schemas/management.cattle.io/v3/schema.go
Setting default in schema for *bool field ignoreDaemonSets doesn't work, because the `v3/schemas/nodeDrainInput` still shows ignoreDaemonSets as bool and available options = [null, true, false]. Changing the store so that it defaults to &true when null is passed. 
https://github.com/rancher/rancher/issues/28905
> set default for ignoreDaemonSets in cluster store

- pkg/data/management/role_data.go
This commit add a permission to allow cluster member to access
v1/management.cattle.io/clusters since it is required for executing
shells
> Add permission to execute shell for cluster member

- scripts/package
This fixes an issue that was creating the tarball under dist/ instead of
bin/ which prevented it from being uploaded as a release artifact.
Supplemental to rancher/rancher#28922
Addresses rancher/rancher#28131
> upload rancherd tarball as release artifact

- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/usercontrollers/controller.go
- pkg/dialer/factory.go
- pkg/types/config/context.go
**Proposed change** 
- Add a separate driver for rancherd, which can be set when the local cluster is rke2
- Set the config for rancherd cluster to nil
issue : https://github.com/rancher/rke2/issues/201
> Set local rke2 cluster to rancherd, and prevent upgrades through rancher

- chart/templates/deployment.yaml
- chart/values.yaml
- pkg/controllers/management/auth/globalrolebinding_handler.go
- pkg/controllers/managementuser/rbac/cluster_handler.go
- pkg/controllers/managementuser/rbac/globalrole_handler.go
- pkg/data/management/role_data.go
- pkg/rbac/common.go
- pkg/settings/setting.go
Problem:
With local cluster now being required the admin role will have full
access to the local cluster which is not good from a security
perspective
Solution:
Add a new restricted-admin role with limited access to the local cluster
but cluster-admin access to all downstream clusters. The
restricted-admin will not be able to create anything rbac related in the
local cluster but should have access otherwise.
Add new setting and update helm chart with the option to set the default admin created on first startup to the restricted-admin role. 
https://github.com/rancher/rancher/issues/28977
> Add new restricted-admin role

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- pkg/controllers/managementuser/rbac/crtb_handler.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/controllers/managementuser/rbac/roletemplate_handler.go
- pkg/rbac/common.go
- tests/integration/suite/test_clustertemplate.py
- tests/integration/suite/test_rbac.py
- tests/integration/suite/test_role_template.py
**Problem**: Upgrading to 2.5 adds a new label containing the CRTB/PRTB namespace and name
to the CRB/RBs created for the it. Both labels have the same value "memberhsip-binding-owner".
When a CRTB/PRTB is deleted, the indexer gets all RTBs with this label value. If there are more
than one labels with this value, the CRB/RB is not deleted. On upgrade there will be two labels with
the same value, one is the existing label with UID as key and the other is the new label with ns+name
**Solution**: Change the label value. With this, on an upgraded setup, the controllers will only check if
the RB/CRB has a label with the new value. There will be only one such label, so on CRTB/PRTB deletion
the RB/CRB will get deleted. This is also required when migrating an upgraded setup using …
> Adds a new label to CRB/RB created for a CRTB/PRTB

- scripts/test
- scripts/validate
- tests/integration/tox.ini
Problem: python linting errors only showed up after basically everything was already run, meaning it could run for 10+ minutes unnecessarily
Root cause: Tests were merged into this repo as is, meaning linting and testing are run in two envs but in one go. Another issue was that the tests still continued to run, even when flake8 failed on linting
Solution: Move linting of python to `validate`, similar to Go linting, so that code formatting issues are caught directly
> Move python linting to validate

- pkg/controllers/dashboard/fleetcharts/controller.go
- pkg/controllers/management/systemcharts/controller.go
This commit add global registry setting and pass it to the fleet charts
that are installed by controller, since these settings can't be passed
from UI.
> Fix airgap for fleet

- pkg/api/steve/clusters/shell.go
- pkg/catalogv2/helmop/operation.go
This commits removes the impersonation header when passed into the shell
proxy, as it needs admin access to exec into the shell not the user
> Remove impersonation header in shells

- chart/templates/deployment.yaml
Helm parses the value as a literal true which is incorrect and causes the error seen. Quote the value so it's parsed as a string.
https://github.com/rancher/rancher/issues/29186
> Quote true value for restricted default admin

- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/data/management/role_data.go
This commit adds cluster.management.cattle.io to project
member/owner/readonly roles, as these roles also need to access cluster
shell and part of the functionality relies on access to the local
cluster resource in downstream cluster
> Add cluster permission to project member/owner/readonly

- pkg/settings/setting.go
- tests/integration/suite/test_system_project.py
The test test_system_project.py is failing for `fleet-system` namespace. It is not present in system_namespaces setting, hence should the test should not error out for it irrespective of the value of the automount_service_account_token flag of the default SA.
Also adding fleet-system to system-namespaces setting.
> Do not look at the automount_service_account_token flag of default SA in non-system namespaces

- cmd/rancherd/auth/auth.go
- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
This commit fixed an issue where local admin is not set as the cluster
owner of local cluster. This is because when we disable the default
admin, all the controller won't be able to rerun twice since all the
conditions have been set to true. Thus in reset-admin, when we first
bootstrap the password, we need to set creatorId on the annotation and
also revert the condition to be false so that controller can be re-run
to add corresponding roles/rolebindings
> Fix rancherd not setting admin on local clusters

- pkg/data/management/role_data.go
Resource names should not be camel case, this breaks k8s rule comparison since the real role does not do camel case
> Fix resource names in project roles

- pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go
- pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go
MultiClusterAppRevision objects have incorrect ownerReferences for MultiClusterApps.
The field ownerReference.Kind should be "MultiClusterApp" and not "multiclusterapps". With
this commit, the newly created MultiClusterAppRevisions will have the right ownerReferences,
and the existing revisions on an upgraded setup will get updated
https://github.com/rancher/rancher/issues/29122
> Change MultiClusterAppRevision ownerReferences

- channels.yaml
- cmd/rancherd/install.sh
This pr sets the latest channel -if not specified via INSTALL_RANCHERD_CHANNEL- as the default install channel. 
issue : https://github.com/rancher/rancher/issues/29209
> set latest channel as default for rancherd install.sh

- pkg/controllers/management/auth/project_cluster_handler.go
- pkg/controllers/managementuser/rbac/cluster_handler.go
- pkg/data/management/role_data.go
There were multiple other places we are creating admins for local cluster, this actually ends up with the same bindings multiple times but this PR does not address that. 
https://github.com/rancher/rancher/issues/29279
> Stop creating admins if RestrictedDefaultAdmin is set

- cmd/rancherd/install.sh
This pr sets the default INSTALL_RANCHERD_CHANNEL to latest if not specified and removes the unnecessary assessment in get_version function 
Default was set to testing
```
$ curl -sfL https://get.rancher.io | sudo sh -
[INFO]  finding release for channel testing
[INFO]  using v2.5.0-rc3 as release
[INFO]  downloading checksums at https://github.com/rancher/rancher/releases/download/v2.5.0-rc3/sha256sum.txt
[INFO]  downloading tarball at https://github.com/rancher/rancher/releases/download/v2.5.0-rc3/rancherd-amd64.tar.gz
[INFO]  verifying installer
[INFO]  unpacking tarball file 
```
> Remove unnecessary channel assignment

- tests/validation/Dockerfile.v3api
- tests/validation/tests/v3_api/scripts/build.sh
Add Helm version param - default to v3.3.4
Tested locally for default version: 
```
validation % ./tests/v3_api/scripts/build.sh
validation % docker run rancher-validation /bin/bash -c 'helm_v3 version'
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```
> Validation - Add Helm version param for tools

- pkg/data/management/role_data.go
The resources have different scopes which causes issues when creating
the downstream roles
https://github.com/rancher/rancher/issues/29236
> Split rules for catalog.cattle.io

- pkg/controllers/managementuser/rbac/cluster_handler.go
- pkg/data/management/role_data.go
Problem:
The cluster admin sync is in a cluster controller which processes all
clusters so if a sync for a different cluster comes in the sync will
still happen locally
restricted-admin can't create cloud credentials
Solution:
Make the controller only work on the cluster it was registered for
Add secret create perms in the local cluster, this is the same as `user` and required to create cloud credentials
https://github.com/rancher/rancher/issues/29279
> Stop admin sync and update restricted admin perms

- pkg/controllers/management/kontainerdrivermetadata/data_getter.go
This logic was never adjusted to the new "dev" version ending with `-head`.
> -head version as dev when setting k8s versions

- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/client/generated/management/v3/zz_generated_cluster_spec_base.go
- pkg/data/dashboard/cluster_data.go
The template is holding the fleetWorkspaceName which causes the validating webhook to validate permissions a normal user does not have. rancher-operator  will set the NS if not set which is the current intended flow. 
https://github.com/rancher/rancher/issues/29349
> Move fleetWorkspaceName so it is not included in templates

- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/client/generated/management/v3/zz_generated_cluster_spec_base.go
- pkg/data/dashboard/cluster_data.go
The template is holding the fleetWorkspaceName which causes the validating webhook to validate permissions a normal user does not have. rancher-operator will set the NS if not set which is the current intended flow.
#29349
> [2.5] Move fleetWorkspaceName so it is not included in templates

- cmd/rancherd/go.mod
- package/Dockerfile.runtime
Problem: updating rke2 version in go mod didn't pull the correct hardened images 
Solution: the new rke2 version should be updated in package/Dockerfile.runtime
issue: https://github.com/rancher/rancher/issues/29354
> update rke2 version in dockerfile.runtime

- cmd/rancherd/go.mod
- package/Dockerfile.runtime
Problem: updating rke2 version in go mod didn't pull the correct hardened images
Solution: the new rke2 version should be updated in package/Dockerfile.runtime
issue: #29354
> [2.5] update rke2 version in dockerfile.runtime

- scripts/build-rancherd
This pr adds the missing build flags to build-rancherd script to fix the error logs shown in #29359
Issue : #29359
> [2.5] add missing build flags from rke2

- scripts/build-rancherd
This pr adds the missing build flags to `build-rancherd` script to fix the error logs shown in #29359
Issue : https://github.com/rancher/rancher/issues/29359
> add missing buildflags from rke2

- channels.yaml
- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
- package/Dockerfile.runtime
This Pr updates rke2 version to `v1.18.9+rke2r1` in rancherd and adds exclude expression to latest channel
> [2.5] Bump rke2 in rancherd 2.5

- channels.yaml
- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
- package/Dockerfile.runtime
This Pr updates rke2 version to `v1.18.9+rke2r1` in rancherd and adds exclude expression to latest channel
> Bump rke2 in rancherd

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
provisioner.go updates cluster's AppliedSpec and then enqueues "upgrade_" key to call this sync.
Node plan gets calculated using cluster's AppliedSpec, so fetch the object from db instead of Lister to avoid race.
https://github.com/rancher/rancher/issues/29370
> Don't use cluster Lister for toUpgrade check

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
provisioner.go updates cluster's AppliedSpec and then enqueues "upgrade_" key to call this sync.
Node plan gets calculated using cluster's AppliedSpec, so fetch the object from db instead of Lister to avoid race.
original PR: `https://github.com/rancher/rancher/pull/29385` 
Issue: https://github.com/rancher/rancher/issues/29370
> [release/v2.5] Don't use cluster Lister for toUpgrade check

- channels.yaml
Right after rancher 2.5 is launched, Latest channel needs to only show main releases (v2.5.0). this pr adds add excludeRegexp to latest channel in update.rancher.io to exclude testing releases from latest channel
> add excludeRegexp to latest channel in update.rancher.io

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_global_role.py
- tests/validation/tests/v3_api/test_monitoring.py
fix a couple of failed cases in the automation
- fix the issue that API returns empty list `[]` instead of `None`
- increase the waiting time for metrics available in cluster’s page
- fix the issue that test_rbac_cluster_owner_control_cluster_monitoring due to timing issue
> fix automation bugs

- tests/validation/tests/v3_api/resource/rbac/monitoring/monitoring_rbac.json
- add tests for `admin`, `edit` and `view` clusterroles 
- move tests for `secret` and `configmap` form should_pass to should_fail for monitoring-admin, monitoring-edit, and monitoring-view
- remove tests for grafana-config-admin, grafana-config-edit, and grafana-config-view because those clusterrols do no exist anymore.
> update the rbac tests for monitoring v2

- pkg/auth/providers/common/ldap/ldap_util.go
- pkg/auth/providers/ldap/ldap_client.go
https://github.com/rancher/rancher/issues/28077
I work with an LDAP server which the ObjectClass attribute is in lowercase, i.e., "objectclass".
When Rancher makes the search for objectclass attributes it expects the literal name "objectClass", i.e, it's case-sensitive, which makes the LDAP authentication never work because it won't find any attributes in this case.
To fix this, I changed the search to make it case-insensitive, using EqualFold function.
I also changed the isType check method from ldap_client.go so it can use the new case-insensitive function from ldap package.
I have builded and tested this fix in my environment, and LDAP provider worked just fine.
> Make ldap search for objectClass case-insensitive

- pkg/auth/providers/common/ldap/ldap_util.go
- pkg/auth/providers/ldap/ldap_client.go
I work with an LDAP server which the ObjectClass attribute is in lowercase, i.e., "objectclass".
When Rancher makes the search for objectclass attributes it expects the literal name "objectClass", i.e, it's case-sensitive, which makes the LDAP authentication never work because it won't find any attributes in this case.
To fix this, I changed the search to make it case-insensitive, using EqualFold function.
I also changed the isType check method from ldap_client.go so it can use the new case-insensitive function from ldap package.
I have builded and tested this fix in my environment, and LDAP provider worked just fine.
> [2.4] Make ldap search for objectClass case-insensitive

- pkg/controllers/managementagent/monitoring/operatorHandler.go
Context: `operatorHandler` is the Rancher controller that does two things:
1) It installs all the CRDs onto the cluster via deploying `operator-init`
2) It installs the actual Prometheus Operator pod via deploying `operator`
It's triggered to deploy when either Monitoring or Alerting is enabled since it represents that components (CRDs + Operator) that both features need in order to be deployed successfully onto a cluster.
Before https://github.com/rancher/system-charts/pull/357, we never had a reason to need to pass in values to `operator-init`, but after that change goes in we should respect overrides passed in by the user via answers for that subchart.
Related Issue: https://github.com/rancher/rancher/issues/27253
> Allow users to overwrite operator-init values

- pkg/controllers/user/monitoring/operatorHandler.go
This is a "backport" of a commit from `master` here: https://github.com/rancher/rancher/commit/0dee1debc6933c4feb062a30bd509b7d4d294b51
I was unable to cherry pick this commit since it is in a different file in `release/v2.4`.
Original PR: https://github.com/rancher/rancher/pull/29478
Related Issue: https://github.com/rancher/rancher/issues/27253
> [2.4] Allow users to overwrite operator-init values

- pkg/controllers/managementagent/monitoring/operatorHandler.go
(cherry picked from commit 0dee1debc6933c4feb062a30bd509b7d4d294b51)
Original PR: https://github.com/rancher/rancher/pull/29478
Related Issue: https://github.com/rancher/rancher/issues/27253
> [2.5] Allow users to overwrite operator-init values

- app/machinedriver_data.go
This MR is a 2.4 back-port to update [OCI Node Driver](https://github.com/rancher-plugins/rancher-machine-driver-oci) to version `v1.0.1`, that has a small but critical [update](https://github.com/rancher-plugins/rancher-machine-driver-oci/commit/83f0fea460841c7150bd9a8d6d0c46c791f5e17c) to the driver's internal pre-check.
Related Issue:
#29503
> [2.4] Update OCI node driver to v1.0.1.

- chart/templates/ingress.yaml
**BACKPORT**
**Problem**
Starting in 1.16 Ingress was no longer in the extensions/v1beta1 api, so it is not recognized
**Solution**
Update the apiVersion to a version that is supported in the following kubernetes versions
```
1.19.2 (default)
1.18.9
1.17.12
1.16.15
```
**Issue**
#29144
**Master PR**
https://github.com/rancher/rancher/pull/29336
**Additional Information**
The use of networking.k8s.io/v1beta1 started in 1.16 and will be removed in v1.22 .
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
```
The v1.22 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:
Ingress in the extensions/v1beta1 API version will no longer be served
Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. …
```
> Use newer apiVersion for ingress

- chart/templates/ingress.yaml
**Problem**
Starting in 1.16 Ingress was no longer in the `extensions/v1beta1` api, so it is not recognized 
**Solution**
Update the apiVersion to a version that is supported in the following kubernetes versions
```
1.19.2 (default)
1.18.9
1.17.12
1.16.15
```
**Issue** 
**Additional Information**
The use of `networking.k8s.io/v1beta1 ` started in **1.16** and will be removed in **v1.22** .
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
```
The v1.22 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:
Ingress in the extensions/v1beta1 API version will no longer be served
Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. Existing …
```
> [2.5.2] Use newer apiVersion for ingress

- pkg/settings/setting.go
- pkg/settings/setting_test.go
Add check and unit test for release semver. The check parses for a "head" substring.
The IsRelease function needs to be able to discern a v2.X-head branch from a release.
Add unit test for the IsRelease function.
Related issue: #29362
> Add check and unit test for release semver 

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
https://github.com/rancher/rancher/issues/29412
This PR stops the k3s portion of provisioner from setting the K3sConfig on an embedded cluster.  UI shown below. Upgrading the cluster is then not possible in the API as k3sConfig is gone. 
Embedded logic is here: https://github.com/rancher/rancher/blob/master/pkg/data/dashboard/cluster_data.go#L40-L42
~Potential caveats: Is it bad for the cluster not to be labeled as k3s ? As far as I can tell that just stops some validating logic around upgrade version, and stops k3s-upgrade-controller, which is what we want. The version on an embedded cluster should never be upgraded.~ It's labeled as K3s now. Only downside now is that we don't have a flag to see if its embedded for other features.
> Disable kubernetes upgrades on embedded cluster

- go.mod
- go.sum
- pkg/apis/management.cattle.io/v3/authn_types.go
- pkg/auth/providers/saml/saml_client.go
Problem: When configuring SAML auth for Rancher, Rancher (service provider) sets the rancher metadata URL as the authentication request issuer (service provider entity ID). This is how the saml library we use sets it, and is a common way of setting the issuer. SAML identity providers (keycloak, adfs etc) have fields that accept the service provider entity ID, which must match the auth request issuer. For Keycloak this field is called `ClientID`. Recently there has been a change in the saml library, which allows users to configure this entity ID, and set it to some custom value instead of the metadata URL. We use a fork of this library, and the version we are on does not include this change. So Keycloak can only be configured with rancher metadata URL as the clientID and users cannot …
> Make Keycloak entity ID configurable

- pkg/settings/setting.go
- pkg/settings/setting_test.go
Add check and unit test for release semver. The check parses for a "head" substring.
The IsRelease function needs to be able to discern a v2.X-head branch from a release.
Add unit test for the IsRelease function.
Original PR: #29525
Original Issue: #29362
> [2.5] Add check and unit test for release semver

- cmd/rancherd/bundle/lib/systemd/system/rancherd-agent.service
- cmd/rancherd/bundle/lib/systemd/system/rancherd-server.service
- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
- cmd/rancherd/main.go
- package/Dockerfile.runtime
Backports: 
* This pr updates rke2 version in rancherd to v1.18.10+rke2r1 https://github.com/rancher/rancher/pull/29560
* This Issue PR : https://github.com/rancher/rancher/issues/29583
> [2.5 backports] Bump rke2 rancherd and add config parse flag

- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
- package/Dockerfile.runtime
This pr updates rke2 version in rancherd to `v1.18.10+rke2r1` 
https://github.com/rancher/rancher/issues/29583
> Bump rke2 version in rancherd to v1.18.10+rke2r1

- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Prior, the error from deploying the eks-operator was evaluated but the condition update error was returned. The condition
update error is usually nil. This caused the controller to not reenqueue the cluster. Since the cluster was not reenqueued the
app was not redeployed unless a separate event caused the cluster or another cluster to reenqueue. Now, the condition error is evaluated and the original error is returned if the condition error is nil.
**Solution:**
Now, the condition error is evaluated and the original error is returned if the condition error is nil.
**Issue:**
https://github.com/rancher/rancher/issues/29127
> Evaluate proper error

- pkg/auth/providers/azure/azure_provider.go
- pkg/controllers/management/auth/setting.go
- pkg/settings/setting.go
Problem:
In large azureAD setups user sync and even on login causes a large
amount of API calls to azureAD to fetch users groups.
Solution:
Cache the group principals as this is static data so it's causing
unnecessary load on rancher and the azureAD API
User syncs are an order of magnitude faster after the cache is populated
Users before and after the cache is populated:
```
2020/10/15 12:03:48 [INFO] [AZURE_PROVIDER] Completed gathering users groups, took 228.658551ms, keys in cache:7
2020/10/15 12:03:51 [INFO] [AZURE_PROVIDER] Completed gathering users groups, took 8.517µs, keys in cache:7
```
```
2020/10/15 12:03:56 [INFO] [AZURE_PROVIDER] Completed gathering users groups, took 1.934538826s, keys in cache:1008
2020/10/15 12:03:59 [INFO] [AZURE_PROVIDER] Completed gathering users …
```
> Add a cache to the azureAD group retrieval

- pkg/auth/providers/azure/azure_provider.go
- pkg/controllers/management/auth/setting.go
- pkg/settings/setting.go
Problem:
In large azureAD setups user sync and even on login causes a large
amount of API calls to azureAD to fetch users groups.
Solution:
Cache the group principals as this is static data so it's causing
unnecessary load on rancher and the azureAD API
User syncs are an order of magnitude faster after the cache is populated
backport of: https://github.com/rancher/rancher/pull/29521
> [2.4] Add a cache to the azureAD group retrieval

- pkg/auth/providers/azure/azure_provider.go
- pkg/controllers/management/auth/setting.go
- pkg/settings/setting.go
Problem:
In large azureAD setups user sync and even on login causes a large
amount of API calls to azureAD to fetch users groups.
Solution:
Cache the group principals as this is static data so it's causing
unnecessary load on rancher and the azureAD API
User syncs are an order of magnitude faster after the cache is populated
backport of: #29521
> [2.5] Add a cache to the azureAD group retrieval

- pkg/controllers/managementuser/alert/watcher/cluster_scan.go
- pkg/controllers/managementuser/cis/clusterScanHandler.go
Check if the CisStatusScan Fail field is initialized before accessing
it. If Fail is "nil", a panic will occur.
Issue: #29518
> Check CisStatusScan Fail field before acccesing

- pkg/data/management/role_data.go
Add secrets creation rule for restrictedAdmin. This applies to all
apiGroups.
Issue: #29379
> Fix secrets creation rule for standard user

- pkg/data/management/role_data.go
Fix secrets creation rule for standard user. This applies to all
apiGroups.
Original PR: [#29575](https://github.com/rancher/rancher/pull/29575)
Original Issue: [#29379](https://github.com/rancher/rancher/issues/29379)
> [2.5] Fix secrets creation rule for standard user

- pkg/controllers/dashboard/helm/repo.go
If the helm repo url does not end with a '/' and the chart url is relative, then the end of the helm repo path was being removed.
For example, if the helm repo was `https://helm.example.com/repo/charts` and the chart url was `chart-v1.0.0.tgz`, then the url was being resolved to `https://helm.example.com/repo/chart-v1.0.0.tgz`. This was incorrect.
Ensuring that the repo url ends with a '/' fixes this problem.
Issue:
https://github.com/rancher/rancher/issues/29557
To elaborate on how this fixes the issue: when the path was being altered in the undesired way as above, the response was HTML with a 404 status. When the `gzip` reader tried to decompress the expected response, it produced and `invalid header error`because it was reading HTML instead of gzip.
> [2.5] Add trailing slash to helm repo url

- package/Dockerfile
This PR is to correct the cli tag which was changed in https://github.com/rancher/rancher/pull/29578/files#diff-c55d1ee74f32cd4b9eeeceaec981a180f52e761acb158a5b0b0e088c7725c9caL112
> [2.5] Update cli tag

- chart/templates/service.yaml
- cmd/rancherd/chart/templates/service.yaml
- pkg/tls/tls.go
This is used for fleet-controller to be able to talk to rancher API(and
downstream cluster) using k8s service name(Service IP). This is a more
efficient way and can bypass proxy if rancher is installed behind a
proxy
> Add rancher.cattle-system to tls san

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Problem:
Node plan doesn't get initialized on the v3.Node if sync is missed, so node gets stuck in registering without Edit/Delete.
Solution:
Check if node plan is set during cluster's toUpgrade logic, which is called after each rke sync.
https://github.com/rancher/rancher/issues/29620
> [2.4] enqueue node if node plan isn't initialized after rke up

- Dockerfile.dapper
- scripts/package
**Problem:**
The tarballs of the latest version of each chart needs to be extracted before the `rancher-images.txt` for airgap setups can be created. The previous logic that does this pre-processing leverages on `sort -Vr` (reverse version-sort) to find the latest version of each chart, but it's proven to be unreliable at times as shown in the related issues below.
**Solution:**
Modify pre-processing logic to read the repo's `index.yaml` using `yq` to find the latest version of each chart. Since we don't allow modifying old charts, it's safe to assume that `index.yaml` will always contain a list of chart sorted in the correct order.
Ran `make ci` locally and the generated `rancher-images.txt` contained the correct tags for `rancher/fleet` and `rancher/rancher-operator`
**Related Issues:** …
> [2.5] Fix image list for airgap

- Dockerfile.dapper
- scripts/package
- Add step in dockerfile.dapper to install yq.
- Change logic to read chart's repo index.yaml to find latest charts'
tarballs to extract for the images list text file used in airgap setups.
> [backport][release/v2.5] Fix image list for airgap

- pkg/controllers/managementuser/alert/watcher/cluster_scan.go
- pkg/controllers/managementuser/cis/clusterScanHandler.go
Check if the CisStatusScan field exists is before accessing it in
Sync. If Fail is "nil", a panic will occur in the child function:
isAlertRuleMatching. Ensure that we are using a deep copied "cs"
object when creating the CisStatusScan object.
Original PR: #29566
Original Issue: #29518
This is a backport of the original, merged PR.
> [2.5] Check CisStatusScan existence before Sync

- chart/templates/ingress.yaml
**Problem**
Deprecation warning is still visible
**Solution**
Determine if Ingress is available at the networking/v1 apiVersion and default to v1beta1 if it is not
**Issue**
#29144
**Additional Info**
Checking apiVersion has resource is available starting at helm 2.15
> [ v2.5.2 ] Use capabilities to check if has apiVersion

- pkg/controllers/management/clusterstats/statsaggregator.go
- pkg/controllers/managementuser/nodesyncer/nodessyncer.go
- pkg/controllers/managementuser/nodesyncer/nodessyncer_test.go
**Problem**
Not all nodes are registering in the UI stats due to the lack of role / role label applied. Role labels are not required. 
**Solution**
Check the existing labels on the node, ensure the Spec values reflect the label values, and default to registering it as a worker node if no labels are applied. 
**Issue**
https://github.com/rancher/rancher/issues/29139
**Additional Information**
Similar logic for determining node labels / status values  is also used [here](https://github.com/rancher/rancher/blob/cd2258c4293be86c9f3b1cb06f8a00f9e195d53a/pkg/controllers/managementuser/nodesyncer/nodessyncer.go#L719)
K3s has expected behavior where these [labels will not be applied to the node](https://github.com/rancher/k3s/issues/379#issuecomment-570933692) from requiring these label values …
> [ v2.5.2 ] Default to worker if no other role

- chart/templates/ingress.yaml
**Backport**
**Problem**
Deprecation warning is still visible
**Solution**
Determine if Ingress is available at the networking/v1 apiVersion and default to v1beta1 if it is not
**Issue**
**Additional Info**
Checking apiVersion has resource is available starting at helm 2.15
> [ v2.5.2 ]Use capabilities to check if has apiVersion

- go.mod
- go.sum
- pkg/api/norman/store/cluster/cluster_store.go
- pkg/client/generated/management/v3/zz_generated_node_upgrade_strategy.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
backport of https://github.com/rancher/rancher/pull/29573
> upgraded rke for new nodeupgradestrategy (#29573)

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Forward Port https://github.com/rancher/rancher/pull/29657
Problem:
Node plan doesn't get initialized on the v3.Node if sync is missed,
so node gets stuck in registering without an Edit/Delete.
Solution:
Check if node plan is set during cluster's toUpgrade logic, which
is called after every rke sync.
https://github.com/rancher/rancher/issues/29620
> enqueue node if node plan isn't initialized after rke up

- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Forward Port https://github.com/rancher/rancher/pull/29657
Problem:
Node plan doesn't get initialized on the v3.Node if sync is missed,
so node gets stuck in registering without an Edit/Delete.
Solution:
Check if node plan is set during cluster's toUpgrade logic, which
is called after every rke sync.
https://github.com/rancher/rancher/issues/29620
> [2.5] enqueue node if node plan isn't initialized after rke up

- pkg/controllers/management/eks/eks_cluster_handler.go
The  catalog manager was not initialized with the eksOperatorController
and this caused a nil pointer dereference when it was used.
Caused by:
https://github.com/rancher/rancher/pull/29559
> Fix nil pointer dereference in EKS controller

- pkg/catalogv2/http/download.go
- pkg/controllers/dashboard/helm/repo.go
The helm repo was being refreshed because `repoSpec.URL` and `status.URL` were different. They were different because we were ensuring that `status.URL` ended with a '/'. Now we only add the slash if it is needed to download a chart.
The issue is that `base.ResolveReference(u)` will remove the last part of the path unless it ends in a '/'.
You can see the difference in this playground: https://play.golang.org/p/DbXvDC_S6ZX
> Fix helm repo constant refreshing

- pkg/client/generated/management/v3/zz_generated_adfs_config.go
- pkg/client/generated/management/v3/zz_generated_key_cloak_config.go
- pkg/client/generated/management/v3/zz_generated_okta_config.go
- pkg/client/generated/management/v3/zz_generated_ping_config.go
- pkg/client/generated/management/v3/zz_generated_shibboleth_config.go
The following PR added the new EntityID field for SAML config: https://github.com/rancher/rancher/pull/29571
It didn't contain the generated changes, this PR adds in generated changes
> [2.5] Add generated changes for EntityID from SAML config

- pkg/controllers/management/clusterstats/statsaggregator.go
Version2 of: https://github.com/rancher/rancher/pull/29759
**Problem**
Even when some nodes are labelled as control plane, they still have the ability to run pods
**Solution**
Check for taints to determine if pods can be executed on that node and count it towards worker stats if it can
**Issue**
https://github.com/rancher/rancher/issues/29139
> Add check for taints to determine if pod can run

- pkg/data/management/machinedriver_data.go
- pkg/httpproxy/sign.go
The Amazon IAM requests use the "global" region. However, the global
region for us-gov is different from standard AWS. The global region and
host are added for us-gov.
Issue:
https://github.com/rancher/rancher/issues/27080
> Add support for Amazon us-gov regions

- pkg/controllers/managementuser/alert/configsyncer/configsyncer.go
- pkg/controllers/managementuser/alert/deployer/deployer.go
**Problem:**
User has not configured alert that requires webhook-receiver, but will still receiver the error log `secret webhook-receiver is not found`.
**Solution:**
when the secret webhook-receiver cannot be found, it will not be output as an error
**Relate issue:**
https://github.com/rancher/rancher/issues/28954
> Fix return error when secret webhook-receiver is not found

- pkg/controllers/management/k3sbasedupgrade/register.go
- pkg/controllers/managementagent/monitoring/register.go
- pkg/controllers/managementuser/alert/deployer/deployer.go
- pkg/controllers/managementuser/cis/register.go
Prior, nil pointer errors were being encountered due to
CatalogManager fields not being set.
> Ensure CatalogManager fields are set

- chart/templates/ingress.yaml
https://github.com/rancher/rancher/issues/29874
Recreated the error, and successfully fixed it with this patch, using the default `ImplementationSpecific`: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#better-path-matching-with-path-types
> add ingress pathtype

- pkg/kontainer-engine/drivers/aks/aks_driver.go
- pkg/kontainer-engine/drivers/aks/aks_driver_test.go
Add LoadBalancerSKU support to AKS creation. We default to "Standard" by
default. Add unit test for the new functionality. Update existing code
to work with new Azure SDK module. Deprecate AgentStorageProfile.
Issue: #23715
```bash
[nickgerace at rancherbook in ~/git/rancher/pkg/kontainer-engine/drivers/aks] (0) (issue-23715)
% go test -v -run TestLoadBalancerSKU
=== RUN   TestLoadBalancerSKU
--- PASS: TestLoadBalancerSKU (0.00s)
PASS
ok  	github.com/rancher/rancher/pkg/kontainer-engine/drivers/aks	0.300s
```
Continuing work from @GGGitBoy: https://github.com/rancher/kontainer-engine/pull/201
> Add LoadBalancerSKU support to AKS creation

- pkg/kontainer-engine/drivers/aks/aks_driver.go
- pkg/kontainer-engine/drivers/aks/aks_driver_test.go
Add LoadBalancerSKU support to AKS creation. We default to "Standard" by
default. Add unit test for the new functionality. Update existing code
to work with new Azure SDK module. Deprecate AgentStorageProfile.
Co-authored-by: GGGitBoy <1812041288@qq.com>
Original PR: #29901 
Original Issue: #23715
> [2.5] Add LoadBalancerSKU support to AKS creation

- cmd/rancherd/auth/auth.go
To avoid the panic presented in https://github.com/rancher/rancher/issues/29565
remove cluster.GetName() call when clusterClient returns an error
> Prevent getting cluster.name when clusterClient returns an error

- tests/validation/tests/v3_api/test_import_k3s_cluster.py
Update the environment variable for AWS security groups to look at the environment variable with the correct default.
> Validation - Fix k3s security group environment variable

- pkg/kontainer-engine/drivers/aks/aks_driver.go
- pkg/kontainer-engine/drivers/aks/aks_driver_test.go
Set LoadBalancerSKU to empty string for AKS. This allows for the field
to be omitted for older AKS clusters.
Original Issue: https://github.com/rancher/rancher/issues/23715
> Set LoadBalancerSKU to empty string for AKS

- pkg/kontainer-engine/drivers/aks/aks_driver.go
- pkg/kontainer-engine/drivers/aks/aks_driver_test.go
Set LoadBalancerSKU to empty string for AKS. This allows for the field
to be omitted for older AKS clusters.
Issue: https://github.com/rancher/rancher/issues/23715
> Set LoadBalancerSKU to empty string for AKS [2.5]

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
- vendor/modules.txt
Update Kontainer Engine to 978771216b05. This commit contains the
changes needed to change the default LoadBalancerSKU value to be empty.
KE PR: rancher/kontainer-engine#245
Original PR: #29901
Original Issue: #23715
> [2.4] Update Kontainer Engine to 978771216b05

- pkg/controllers/management/auth/indexes.go
Problem:
If an object does not implement the correct interface the binding
indexer will error and no rbac changes will be processed
Solution:
Dont return the error because the indexer only gives back valid objects
anyways so this will allow rbac changes to continue despite an invalid
object in the cache
https://github.com/rancher/rancher/issues/29947
> [2.4] Ignore Accessor error in role index

- pkg/controllers/management/auth/indexes.go
Problem:
If an object does not implement the correct interface the binding
indexer will error and no rbac changes will be processed
Solution:
Dont return the error because the indexer only gives back valid objects
anyways so this will allow rbac changes to continue despite an invalid
object in the cache
https://github.com/rancher/rancher/issues/29947
> [2.5] Ignore Accessor error in role index

- pkg/controllers/management/auth/indexes.go
Problem:
If an object does not implement the correct interface the binding
indexer will error and no rbac changes will be processed
Solution:
Dont return the error because the indexer only gives back valid objects
anyways so this will allow rbac changes to continue despite an invalid
object in the cache
https://github.com/rancher/rancher/issues/29947
> Ignore Accessor error in role index

- pkg/kontainer-engine/drivers/aks/aks_driver.go
Only change LoadBalancerSKU to standard if provided in order to maintain
backwards compatibility.
Original Issue: #23715
> Only change LoadBalancerSKU to standard if provided

- pkg/kontainer-engine/drivers/aks/aks_driver.go
Only change LoadBalancerSKU to standard if provided in order to maintain
backwards compatibility.
Original Issue: #23715 
Original PR: #29957
> [2.5] Only change LoadBalancerSKU to standard if provided

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
- vendor/modules.txt
Update Kontainer Engine to 4442123b5eaa. This commit contains the
changes needed to only change the LoadBalancerSKU for AKS to standard if
provided.
KE PR: rancher/kontainer-engine#246
Original Issue: #23715
> [2.4] Update Kontainer Engine to 4442123b5eaa

- pkg/api/norman/customization/cluster/validator.go
Previously, if a user provided a VPC ID, they were also required to
provide at least one security group. However, this requirement is
extraneous. So a user is able to provide a VPC ID and not provide any
security groups.
Conversely, if a user does provide security groups, then those security
groups are already attached to a VPC. Therefore, the VPC should be
provided as well.
Issue:
https://github.com/rancher/rancher/issues/29826
EKS Operator PR:
https://github.com/rancher/eks-operator/pull/21
> Make security groups optional when VPC is provided

- .drone.yml
https://github.com/rancher/rancher/issues/30015
Tested with drone exec and exit codes, and it appears to correctly only fire on failure now.
Hard to tell from diff but this is the new code, I just de-indented instance and status
```
when:
event:
exclude:
- pull_request
instance:
- drone-publish.rancher.io
status:
- failure
```
> Fixes notification for helm chart promotion via right indentation

- cmd/rancherd/auth/auth.go
issue : https://github.com/rancher/rancher/issues/29565
master pr : https://github.com/rancher/rancher/pull/29920
> [backport] Prevent getting cluster.name when clusterClient returns an error

- pkg/controllers/managementuser/alert/configsyncer/configsyncer.go
- pkg/controllers/managementuser/alert/deployer/deployer.go
**Problem:**
The user has not configured an alert that requires webhook-receiver, but will still receive the error log `secret webhook-receiver is not found`.
**Solution:**
Execute `syncWebhookConfig` only when `webhook-receiver.enabled` is `true`
**Relate issue:**
https://github.com/rancher/rancher/issues/28954
> [Backport]2.5: Fix return err when secret webhook-receiver is not found

- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/controllers/user/alert/deployer/deployer.go
**Problem:**
The user has not configured an alert that requires webhook-receiver, but will still receive the error log `secret webhook-receiver is not found`.
**Solution:**
Execute `syncWebhookConfig` only when `webhook-receiver.enabled` is `true`
**Relate issue:**
https://github.com/rancher/rancher/issues/28954
> [Backport]2.4: Fix return err when secret webhook-receiver is not found

- pkg/api/customization/multiclusterapp/multi_cluster_app.go
- pkg/api/customization/workload/workload.go
- pkg/api/store/workload/workload_store.go
- tests/integration/suite/test_multi_cluster_app.py
Original PR: rancher/rancher#29710 
```bash
(rancher) [nickgerace at rancherbook in ~/git/rancher/tests/integration/suite] (0) (2.3-rollback-actions)
% pytest -k test_perform_mca_action_read_only
============================================================= test session starts =============================================================
platform darwin -- Python 3.8.6, pytest-4.4.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nickgerace/git/rancher/tests/integration
plugins: metadata-1.10.0, repeat-0.8.0, html-1.20.0, xdist-1.28.0, ordering-0.6, forked-1.3.0
collected 243 items / 242 deselected / 1 selected                                                                                             
test_multi_cluster_app.py . …
```
> [2.3] Handle rollback actions

- pkg/api/customization/multiclusterapp/multi_cluster_app.go
- pkg/api/customization/workload/workload.go
- pkg/api/store/workload/workload_store.go
- tests/integration/suite/test_multi_cluster_app.py
Original PR: rancher/rancher#29710
```bash
(rancher) [nickgerace at rancherbook in ~/git/rancher/tests/integration/suite] (1) (2.4-rollback-actions)
% pytest -k test_perform_mca_action_read_only
============================================================= test session starts =============================================================
platform darwin -- Python 3.8.6, pytest-4.4.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nickgerace/git/rancher/tests/integration
plugins: metadata-1.10.0, repeat-0.8.0, html-1.20.0, xdist-1.28.0, ordering-0.6, forked-1.3.0
collected 274 items / 273 deselected / 1 selected                                                                                             
test_multi_cluster_app.py . …
```
> [2.4] Handle rollback actions

- tests/integration/suite/test_workloads.py
This does not need to be backported at all since this comment exists in PR: https://github.com/rancher/rancher/pull/30059
Reference in PR: https://github.com/rancher/rancher/pull/30059/files#diff-f9fe1ac31c61f8d586903141db84bfcfe67d1df3d2b25ad832d5c76c60719b9eR346-R348
> Add rollback actions test note for 2.4 and below

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_custom_host_reg.py
1. fix the bug that test fails because 'NoneType' object has no attribute 'rstrip'
The error in logs:
```
>           result = result.rstrip()
E           AttributeError: 'NoneType' object has no attribute 'rstrip'
tests/v3_api/common.py:894: AttributeError
```
2. print the full RANCHER_SERVER_CMD
> fix the bug that test fails because 'NoneType' object has no attribute 'rstrip'

- pkg/api/norman/customization/catalog/store.go
- pkg/api/norman/customization/catalog/store_test.go
- pkg/catalog/manager/manager.go
**Problem:**
Version displayed by dropdown in UI do not filter out template versions that are incompatible with targeted cluster.
**Solution:**
The templates API is not cluster scoped so a query param can be optionally passed to indicate which cluster is being targeted.
**Issue:**
https://github.com/rancher/rancher/issues/29773
> Add clusterName filter to templates GET and tests

- pkg/controllers/user/networkpolicy/podhandler.go
Problem:
We removed podname label for hostport pods of system ns, but doesn't return from there resulting into adding back the labels again.
https://github.com/rancher/rancher/issues/30045
> [v2.4] [netpol] don't add back hostport labels for pods of system ns

- pkg/catalog/manager/manager.go
**Problem:**
Prior, version could be accessed before it was set. This would occur on clusters that were newly provisioned or in the process of being provisioned and did not have version set yet.
**Solution:**
Added nil check for version on status. Now, if the version is not set an error will be returned so that controllers can retry until version is available.
**Issue:**
https://github.com/rancher/rancher/issues/30143
> Add nil check for version on status

- pkg/controllers/dashboard/fleetcharts/controller.go
This PR, together with https://github.com/rancher/fleet/pull/143 and https://github.com/rancher/gitjob/pull/20, helps to propagate Rancher HTTP proxy settings to fleet system chart installation, which enables fleet to work with external git repositories in environments behind corporate proxy.
Fixes #30042
> HTTP proxy support for Rancher Continuous Delivery (fleet)

- pkg/controllers/managementuser/networkpolicy/podhandler.go
Problem:
We removed podname label for hostport pods of system ns, but doesn't return from there resulting into adding back the labels again.
https://github.com/rancher/rancher/issues/30044
https://github.com/rancher/rancher/issues/30045
Forward port: https://github.com/rancher/rancher/pull/30140
> [v2.5.3] [netpol] don't add back hostport labels for pods of system ns

- pkg/clustermanager/manager.go
Problem:
When a cluster agent is diconnected rancher tries to start the
controllers in a slow loop, but this causes a memory leak. The leak
stems from adding a handler in client-go which has no method to
deregister the handler so a fixed size array leaks every time.
Solution:
Don't create access control until Rancher has verified a connection to
the cluster which is a good indication controllers will start. There is
technically a small leak here every time we start these controllers.
Issue: https://github.com/rancher/rancher/issues/29429
> Move creation of accesscontrol

- pkg/data/dashboard/add.go
- pkg/data/dashboard/fleet.go
- pkg/data/management/add.go
- pkg/data/management/role_data.go
- pkg/multiclustermanager/app.go
This PR add three built-in clusterRoles in local cluster that user can create roleBinding for:
1. Fleetworkspace admin:
Full permission on regular fleet resource(gitrepo,bundle...) 
Full permissionon clusterregistrations and clusterregistrationtokens
Full permission roleBindings
2. Fleetworkspace member
Full permissionon regular fleet resource(gitrepo,bundle...) 
3. Fleetworkspace readonly
Readonly permission on regular fleet resource(gitrepo,bundle...)
Also the standard user will now have the ability to create fleet workspace. Once a user created a fleetworkspace it is granted Fleetworkspace admin role in the fleet namespace + full permission on the current fleetworkspace. This also grants admin the ability to add cluster into fleetworkspace too since it has `*` verb. This is done …
> Add fleetworkspace admin, member and readonly roles

- cmd/rancherd/auth/auth.go
- cmd/rancherd/go.mod
This commit adds logic to fetch tls-san from rke2 config.yaml and print
it if found. Also give better output when serverURL can't be found.
> Add more serverURL print logic

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go
- vendor/modules.txt
The basic was used to generate an access token. However, the access
token was also being generated when getting a service client. Instead of
using the basic auth, we now use the access token.
Original PR:
https://github.com/rancher/rancher/pull/29683
kontainer-engine PR:
https://github.com/rancher/kontainer-engine/pull/247
Issue:
> Remove basic auth from GKE driver

- pkg/api/norman/customization/cluster/actions_monitoring.go
- pkg/api/norman/customization/cluster/utils.go
This commit introduces changes to try harder to prevent the following error from appearing:
```
2020/11/25 15:53:58 [ERROR] API error response 500 for POST /v3/clusters/c-l4bdt?action=enableMonitoring. Cause: Operation cannot be fulfilled on clusters.management.cattle.io "c-l4bdt": the object has been modified; please apply your changes to the latest version and try again
```
The root cause of this error is that we do not normally retry on a conflict, so before it was appearing even after spinning up just 4 clusters in succession and trying to immediately enable monitoring.
~Now the error still appears, but it appears extremely infrequently (around 1 in every 12 if you just hammer the API at the same time).~ **(fixed)**
Related Issue: https://github.com/rancher/rancher/issues/30188
This …
> Retry on conflict for enable monitoring actions

- pkg/api/norman/customization/cluster/actions_monitoring.go
- pkg/api/norman/customization/cluster/utils.go
Original PR (cherry-picked): https://github.com/rancher/rancher/pull/30239
Related Issue: https://github.com/rancher/rancher/issues/30188
(cherry picked from commit fa66cced3be47d4d2cb0a60eb603ca9037998959)
> [2.5] Retry on conflict for enable monitoring actions

- pkg/controllers/managementuser/networkpolicy/podhandler.go
Problem:
We removed podname label for hostport pods of system ns, but
doesn't return from there resulting into adding back the labels again.
https://github.com/rancher/rancher/issues/30208
https://github.com/rancher/rancher/issues/29714
> [netpol] don't add back hostport labels for pods of system ns

- pkg/controllers/managementuser/networkpolicy/podhandler.go
Problem:
We removed podname label for hostport pods of system ns, but
doesn't return from there resulting into adding back the labels again.
https://github.com/rancher/rancher/issues/30208
> [v2.5] [netpol] don't add back hostport labels for pods of system ns

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/controllers/management/eks/eks_cluster_handler.go
- pkg/dialer/factory.go
Rancher is able to import and create clusters with private API endpoint, but is not able to communicate with them afterwards. Now, as long as the agent is deployed, rancher is able to tunnel to communicate with the API.
Issue:
https://github.com/rancher/rancher/issues/29907
> Allow communication with EKS clusters with private API endpoint

- go.mod
- go.sum
- vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go
- vendor/modules.txt
This reverts commit 9ced45f6160cf43cfa3de96cee95fa2f3969588c.
The tokens being used expire after 1 hour and are not being refreshed. A mechanism for token refresh should be implemented.
Original PR:
https://github.com/rancher/rancher/pull/30174
Issues:
https://github.com/rancher/rancher/issues/30292
https://github.com/rancher/rancher/issues/30170
> [2.4] Revert "Remove basic auth from GKE driver"

- pkg/controllers/managementuser/alert/initdata.go
Related Issue: https://github.com/rancher/rancher/issues/29292
> [2.5] Fix for machine_cpu_cores being removed from cadvisor metrics

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
When an EKS cluster is created with private-only API endpoint, the user is responsible for deploying the cluster agent. There was a check to try to ensure that the cluster agent was not deployed by Rancher. However, this check is not needed because, in this scenario, there are no nodes detected before the cluster agent is deployed.
Issue:
https://github.com/rancher/rancher/issues/29907
Related PRs:
https://github.com/rancher/rancher/pull/30328
https://github.com/rancher/rancher/pull/30120
> Remove private endpoint check when deploying agent

- go.mod
- pkg/api/norman/customization/clusterregistrationtokens/import.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/systemtemplate/import.go
- pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/24636
This moves away from "wildcard" tolerations and adds tolerations based on the taints found on controlplane nodes. How this works:
- Nodes are listed for the cluster
- If none found, we apply default tolerations for controlplane nodes (so it at least can get scheduled by default)
- If nodes found, we collect taints and use them in the template which we use to deploy the agents
- The mechanism to cache the taints is similar to the node/cluster image, if not yet cached, retrieve and cache, if diff found, clear cache so it is refreshed
- Default label added `cattle.io/cluster-agent=true` for when there is no controlplane node found, and people want to influence the scheduling of the cattle-cluster-agent
The only issue is the naming, I used …
> Add tolerations for cattle-cluster-agent

- pkg/data/management/kontainerdriver_data.go
- tests/integration/suite/test_rbac.py
Add built-in `opentelekomcloudcontainerengine` to `release/v2.5`
Backport of PR https://github.com/rancher/rancher/pull/30286, as requested by @dramich in the [comment](https://github.com/rancher/rancher/pull/30286#issuecomment-738156970)
> [2.5] Backport built-in OTC CCE driver for v2.5

- package/Dockerfile.runtime
- scripts/build-rancherd
- scripts/package
- scripts/rancher-namespace.yaml.tmpl
- scripts/rancher.yaml.tmpl
Due to the limitation https://github.com/rancher/rke2/issues/527 we can
not use multi-doc yaml for airgap installation
> Split rancher.yaml into multiple doc

- package/Dockerfile.runtime
- scripts/build-rancherd
- scripts/package
- scripts/rancher-namespace.yaml.tmpl
- scripts/rancher.yaml.tmpl
Due to the limitation https://github.com/rancher/rke2/issues/527 we can
not use multi-doc yaml for airgap installation
> [2.5] Backport: Split rancher.yaml into multiple doc

- cmd/rancherd/auth/auth.go
Refactored logic so that only if admin user, globalrolebinding,
clusterrolebinding are created before we create the configmap. The
previous logic gated on whether user has been created which could fail
mid-way if cluster is not fully bootstraped
> Reorganize reset-admin to make sure everthing get created

- pkg/clustermanager/manager.go
Problem:
If the accessControl does not exist on the record rancher can panic if
attempting to list items
Solution:
Return an error if accessControl has not been created yet. This means
the cluster hasn't been contacted yet anyways
https://github.com/rancher/rancher/issues/29429
https://github.com/rancher/rancher/issues/30434
> Don't return nil accessControl

- pkg/clustermanager/manager.go
Problem:
If the accessControl does not exist on the record rancher can panic if
attempting to list items
Solution:
Return an error if accessControl has not been created yet. This means
the cluster hasn't been contacted yet anyways
https://github.com/rancher/rancher/issues/30434
> [master] Don't return nil accessControl

- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- pkg/client/generated/management/v3/zz_generated_eks_status.go
- pkg/controllers/management/eks/eks_cluster_handler.go
- pkg/dialer/factory.go
If public access is disabled, it is no longer assumed that Rancher cannot communicate with the cluster API. Instead, Rancher attempts to contact the API. If this is successful, then Rancher can communicate with the cluster as normal (through the API access endpoint) instead of tunneling.
This is most important on cluster creation/import. In this case, since Rancher can still communicate with the API endpoint, the user does not need to run the import command that is displayed.
Issue:
https://github.com/rancher/rancher/issues/30403
> Check for cluster connection when public access disabled

- Dockerfile.dapper
Old (and default in Helm v2): `https://kubernetes-charts.storage.googleapis.com`
New: `https://charts.helm.sh/stable/`
https://helm.sh/blog/new-location-stable-incubator-charts/
> Override deprecated charts URL for helmv2

- Dockerfile.dapper
Backport of https://github.com/rancher/rancher/pull/30572
> [release/v2.4.12] Override deprecated charts URL for helmv2

- Dockerfile.dapper
Backport of https://github.com/rancher/rancher/pull/30572
> [release/v2.4] Override deprecated charts URL for helmv2

- Dockerfile.dapper
Backport of https://github.com/rancher/rancher/pull/30572
> [release/v2.5] Override deprecated charts URL for helmv2

- pkg/controllers/managementagent/monitoring/clusterHandler.go
- pkg/controllers/managementagent/monitoring/operatorHandler.go
As part of the rewrite for 2.5, it seems like we stopped deploying the agent onto local clusters:
https://github.com/rancher/rancher/blob/2161018b5c1ffa489b299a039df508b43d41d5e0/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L251-L254
As a result, Rancher local clusters that were spun up after https://github.com/rancher/rancher/commit/079c473dea8d6b47043d1a4ace158c86b03b1bee no longer have the condition AgentDeployed set to true (checked against 2.4.8, where this is set to true for a local cluster).
Since this change has been made, we also need to modify the Monitoring V1 logic to allow it to be deployed onto a local cluster whether or not AgentDeployed is true.
Updated Summary: https://github.com/rancher/rancher/issues/30537#issuecomment-747734831
Related Issue: …
> Allow local cluster to deploy monitoring

- Dockerfile.dapper
Backport of https://github.com/rancher/rancher/pull/30572
> [release/v2.3] Override deprecated charts URL for helmv2

- pkg/api/norman/store/namespace/store.go
#18877
`data[containerResourceLimitField]` will not be nil, because the UI passes an empty `map[]` object, not nil.
1. create a project with `Resource Quotas`
2. create a namespace under the project which you created
3. edit project: set `Container Default Resource Limit`
4. edit & save namespace
Then take a look at namespace, you will find namespace's `Container Default Resource Limit` is empty.
Signed-off-by: Jason-ZW <zhenyang@rancher.com>
> Fix set default namespace's limitRange bug

- chart/README.md
The verification seems duplicated, is covered in the next step - [Verify that the Rancher Server is Successfully Deployed](https://github.com/rancher/rancher/tree/master/chart#verify-that-the-rancher-server-is-successfully-deployed).
> Remove duplicated deployment verification

- pkg/api/customization/clusterregistrationtokens/formatter.go
- pkg/controllers/management/node/controller.go
- pkg/controllers/management/node/utils.go
Issue:
- rancher/rancher#26366 
Solution:
- Resolve the agent image using the cluster object so that it is qualified with the private registry url
- If there's a cluster private registry defined, execute a docker login command on the downstream node via `rancher-machine` before the agent is deployed
- Escape special characters in password since login is via command line
Testing:
- Setup a private registry w/ rancher images
- Launch a cluster w/ a private registry
- tested w/ passwords:
```
testpassword
a$b"'@123`*\
```
> [2.4] Enable agent image to be pulled from private registry

- pkg/client/generated/project/v3/zz_generated_container.go
- pkg/client/generated/project/v3/zz_generated_environment_var.go
- pkg/schemas/mapper/env.go
- pkg/schemas/project.cattle.io/v3/schema.go
- pkg/schemas/project.cattle.io/v3/types.go
https://github.com/rancher/rancher/issues/16148
https://github.com/rancher/rancher/issues/30603
This PR contains:
- Adds a new  type `EnvironmentVar` that emulates k8s' `EnvVar` type structure, and modifies the environment mapper to keep variables as an array of `EnvironmentVar` to preserve their original order. 
- Variables based off of the k8s' `EnvVarSource` type are now kept in the same array as `EnvironmentVar` as a `EnvironmentFrom` sub-type (`EnvironmentFrom` represents everything relevant in k8s' `EnvVarSource` and `EnvFromSource`). [Reference to k8s' types](https://github.com/kubernetes/kubernetes/blob/0a839c6c3b9489716e216b4fc9dd2f9c17948c16/staging/src/k8s.io/api/core/v1/types.go#L1910-L1947)
- Variables based off of the k8's `EnvFromSource` type are still kept in a separate …
> [master] Fix environment variable interpolation

- pkg/controllers/management/globaldns/globaldns_handler.go
Adding ability to filter out globalDNS entries when  there two globalDNSProviders having same root domain (one for public hostedzone and other for private), by using an annotation-filter parameter of external-dns.
By adding an "annotation-filter" to the globalDNSProvider a user can specify which ingress will this provider look for - rancher will place that annotation on the ingresses created for the globalDNS entries using this provider.
> Add ingressClass to globalDNS ingress if the provider has the annotationFilter for it specified

- pkg/controllers/management/globaldns/globaldns_handler.go
Backward port https://github.com/rancher/rancher/pull/30673 
Add ingressClass to globalDNS ingress if the provider has the annotationFilter for it specified
> [2.4] Add ingressClass to globalDNS ingress if the provider has the annotationFilter for it specified

- pkg/controllers/management/globaldns/globaldns_handler.go
Backward port https://github.com/rancher/rancher/pull/30673
Add ingressClass to globalDNS ingress if the provider has the annotationFilter for it specified
> [2.5] Add ingressClass to globalDNS ingress if the provider has the annotationFilter for it specified

- tests/validation/tests/Dockerfiles/unprivileged-testcontainer/Dockerfile
- tests/validation/tests/Dockerfiles/unprivileged-testcontainer/run.sh
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_certificate.py
- tests/validation/tests/v3_api/test_ingress.py
- tests/validation/tests/v3_api/test_upgrade.py
- tests/validation/tests/v3_api/test_workload.py
I've built public image: `maxross/mytestcontainer:unprivileged` with the Dockerfile here. 
When running on a CIS hardened cluster, it should be run with the following parameters:
```
PYTEST_OPTIONS=-k "test_wl or test_dns_record or test_rbac or test_connectivity or test_ingress or test_secrets or test_service_discovery or test_websocket"
RANCHER_TEST_IMAGE=maxross/mytestcontainer:unprivileged
RANCHER_TEST_IMAGE_NGINX=nginxinc/nginx-unprivileged
RANCHER_TEST_IMAGE_PORT=8080
RANCHER_HARDENED_CLUSTER=True
RANCHER_SKIP_PING_CHECK_TEST=True
```
Note PYTEST_OPTIONS may include other tests as well, but I've listed what works for BOTH rke2 and rke1. For rke1, you should be able to run bkp_restore tests and CIS tests as well, though running with those options has not been fully validated with the …
> Allow automation to run on cis hardened clusters

- pkg/controllers/management/globaldns/globaldns_handler.go
The goal is to add "annotation-filter" parameter for https://github.com/kubernetes-sigs/external-dns
But to set this via Rancher's globalDNSProvider, this parameter `annotationFilter` in the external-dns chart needs to be set in additionalOptions values when Rancher controller deploys the  chart https://github.com/rancher/system-charts/blob/dev-v2.5/charts/rancher-external-dns/v0.1.2/values.yaml#L88
Now the global_dns controller reads this parameter is read from  additionalOptions map and put on the dummy ingress. The controller was reading the parameter named "annotation-filter", but instead needs to read "annotationFilter"
> Fix the additionalOption key read by rancher globaldns controller to add annotation-filter command param to external-dns

- pkg/controllers/management/globaldns/globaldns_handler.go
Backport for PR https://github.com/rancher/rancher/pull/30839 
Fix the additionalOption key read by rancher globaldns controller to add annotation-filter command param to external-dns
> [2.4] Fix the additionalOption key read by rancher globaldns controller to add annotation-filter command param to external-dns

- pkg/controllers/management/globaldns/globaldns_handler.go
Backport for PR https://github.com/rancher/rancher/pull/30839 
Fix the additionalOption key read by rancher globaldns controller to add annotation-filter command param to external-dns
> [2.5] Fix the additionalOption key read by rancher globaldns controller to add annotation-filter command param to external-dns

- pkg/data/management/kontainerdriver_data.go
- tests/integration/suite/test_rbac.py
This PR brings brings the changes from https://github.com/rancher/rancher/pull/30668 into the v2.5 release branch.
> [2.5] Backport LKE cluster driver

- pkg/controllers/management/eks/eks_cluster_handler.go
**Problem:**
Prior, error message did not specify that managed nodegroups were
necessary. This confused users who had cluster with non-managed
nodegroups. The message also states the agent cannot be deployed
which isn't true; it is possible the agent will deploy with a
non-managed nodegroup.
**Solution:**
Now, the message has been revised to be
more accurate and a comment has been added to explain some of
the reasoning behind the requirement.
**Issue:**
https://github.com/rancher/rancher/issues/30041
> Changed EKS nodegroup error message

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/resource/terraform/master/instances_server.tf
- tests/validation/tests/v3_api/resource/terraform/worker/instances_worker.tf
- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade
- tests/validation/tests/v3_api/test_custom_host_reg.py
- tests/validation/tests/v3_api/test_deploy_clusters.py
- tests/validation/tests/v3_api/test_import_k3s_cluster.py
- tests/validation/tests/v3_api/test_upgrade.py
- Adds Jenkins job to import multiple k3s clusters, run preupgrade, upgrade, and run postupgrade jobs
- Adds upgrade_cluster code for k3s clusters
- Removes some extraneous prints and "multinode" text from k3s creation code
> Create and upgrade multiple k3s clusters with validation tests

- pkg/api/norman/customization/kontainerdriver/actionhandler.go
https://github.com/rancher/rancher/issues/30840
This is for the generated image list when downloading the text file from the UI
> Remove noiro (Cisco ACI) images from image list

- pkg/api/norman/customization/kontainerdriver/actionhandler.go
https://github.com/rancher/rancher/issues/30840
Backport of https://github.com/rancher/rancher/pull/30884
> [release/v2.5] Remove noiro (Cisco ACI) images from image list

- tests/validation/tests/v3_api/test_airgap.py
- tests/validation/tests/v3_api/test_create_ha.py
- tests/validation/tests/v3_api/test_custom_host_reg.py
- tests/validation/tests/v3_api/test_proxy.py
- tests/validation/tests/v3_api/test_upgrade.py
Add trace logging to single node Docker installs through `--trace` flag in `docker run`, and through `kubectl` with a Helm install.
> [Validation] - Add trace logging to single node and HA installs for automation

- tests/validation/tests/v3_api/test_airgap.py
- tests/validation/tests/v3_api/test_rke2_airgap.py
Currently there are two ways to deploy RKE2 in an airgap environment: 
- Through a private registry that is NOT password protected but does require TLS
- Tarball method
See rke2 docs for more info on these. This just automates the process for us for easier testing. For tarball method, a bastion server is required to already be present and user must supply the ID. For private registry method, it will create the bastion server itself.
A future PR will enable importing these clusters to Rancher, but this lays the groundwork for that as well by providing options for the necessary additional server arguments as well.
> Add rke2 airgap deployment methods

- pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
- pkg/image/export/main.go
Prior, using export script with TAG set to dev, master, or a
value equal to kd.RancherVersionDev would result in no k3s
upgrade or related images being added to the images text.
This is because kd.RancherVersionDev does not contain a
valid semver version. This happens to dev and master because
those values are overwritten with the value of
kd.RancherVersionDev if detected. Now, versions are used for
comparison that match the minor and major version of
kd.RancherVersionDev and will match any constraints that
could be met by any version that would also have matching
major and minor versions.
**Issue:**
https://github.com/rancher/rancher/issues/31061
> Fix k3s upgrade dev image export

- pkg/auth/providers/activedirectory/activedirectory_client.go
- pkg/auth/providers/common/ldap/ldap_util.go
When a user logs in, we pull all the groups that he is a memberOf. While pulling details of each group, the attribute "memberOf" of a group that lists all the parent groups of this group, need not be synced from the AD as we only need the group DN and some important attributes.
This saves some time needed to sync the groups of a user during login, particularly significant if the user is part of large number(1000) of groups.
The query to gather parent groups when nested groups are enabled, remains unchanged by this fix.
https://github.com/rancher/rancher/issues/30869
> We need not pull the memberof attribute of a group when listing groups during user login

- pkg/controllers/management/node/controller.go
returning v1 node delete that was in v2.4 https://github.com/rancher/rancher/blob/release/v2.4/pkg/controllers/management/node/controller.go#L219
> returning v1 node delete

- pkg/controllers/management/node/controller.go
returning v1 node delete that was in v2.4 https://github.com/rancher/rancher/blob/release/v2.4/pkg/controllers/management/node/controller.go#L219
> [master] adding back v1 node delete

- pkg/auth/providers/saml/saml_actions.go
- pkg/auth/providers/saml/saml_client.go
- pkg/auth/providers/saml/saml_handlers.go
- pkg/auth/providers/saml/saml_provider.go
On HA setups when SAML is configured, at times login throws a 404 with this panic in the logs:
```
2021/01/21 21:00:38 [ERROR] Panic serving api request:
22/01/2021 10:00:38 am goroutine 485670 [running]:
22/01/2021 10:00:38 am runtime/debug.Stack(0xc002b1fdc0, 0x3c26060, 0x7390960)
22/01/2021 10:00:38 am 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
22/01/2021 10:00:38 am github.com/rancher/norman/api.(*Server).ServeHTTP.func1(0x4e78ba0, 0xc024211360)
22/01/2021 10:00:38 am 	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20200930000340-693d65aaffe3/api/server.go:175 +0x7a
22/01/2021 10:00:38 am panic(0x3c26060, 0x7390960)
22/01/2021 10:00:38 am 	/usr/local/go/src/runtime/panic.go:969 +0x166
22/01/2021 10:00:38 am github.com/rancher/rancher/pkg/auth/providers/saml.PerformSamlLogin(0x44d …
```
> Prevent panic seen intermittently while logging in with SAML

- pkg/systemtemplate/template.go
- tests/validation/tests/kubernetes_conformance/resources/k8s_ymls/sonobuoy-conformance.yaml
- tests/validation/tests/rke/resources/k8s_ymls/clusterrole.yml
- tests/validation/tests/rke/resources/k8s_ymls/clusterrolebinding.yml
- tests/validation/tests/rke/resources/k8s_ymls/role.yml
- tests/validation/tests/rke/resources/k8s_ymls/rolebinding.yml
Update API from "rbac.authorization.k8s.io/v1beta1" to "rbac.authorization.k8s.io/v1".  This will resolve the warning "Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding"
Update API in manifest.
None
Refs: #30043
None
Signed-off-by: cclhsu <clark.hsu@suse.com>
> Update ClusterRoleBinding to rbac.authorization.k8s.io/v1

- pkg/auth/providers/activedirectory/activedirectory_client.go
- pkg/auth/providers/common/ldap/ldap_util.go
Backport PR for release/v2.5 for https://github.com/rancher/rancher/pull/31067
When a user logs in, we pull all the groups that he is a memberOf. While pulling details of each group, the attribute "memberOf" of a group that lists all the parent groups of this group, need not be synced from the AD as we only need the group DN and some important attributes.
This saves some time needed to sync the groups of a user during login, particularly significant if the user is part of large number(1000) of groups.
The query to gather parent groups when nested groups are enabled, remains unchanged by this fix.
https://github.com/rancher/rancher/issues/30869
> [2.5]We need not pull the memberof attribute of a group when listing groups during user login

- pkg/api/steve/proxy/proxy.go
- pkg/features/feature.go
https://github.com/rancher/rancher/issues/29633
This can be dropped according to Darren, this code will only be executed if the feature flag exists (it is not created in new v2.5 installs), and is is enabled (it was disabled by default in v2.4) to avoid the agent deployment issue in the linked issue.
> Remove experimental steve proxy feature flag code

- pkg/api/steve/clusters/shell.go
- pkg/catalogv2/helmop/operation.go
- pkg/systemtemplate/template.go
Problem: boot a cluster with only etcd and controlplane nodes, with no worker coredns doesn't come up and the cluster-agent can not talk back to the rancher server url and make the cluster accessible. additionally, targeting for the shell fails due to taints.
Fix: Add dnspolicy default to the cluster-agent so when it boots it will use the node's dns settings. Add tolerations to the shell/helmop for controlplane nodes so the pods will assign and the tunnels will com up.
https://github.com/rancher/rancher/issues/31244
> adding dnspolicy and tolerations to shell/helm

- pkg/api/steve/clusters/shell.go
- pkg/catalogv2/helmop/operation.go
- pkg/systemtemplate/template.go
Problem: boot a cluster with only etcd and controlplane nodes, with no
worker coredns doesn't come up and the cluster-agent can not talk back
to the rancher server url and make the cluster accessible. additionally,
targeting for the shell fails due to taints.
Fix: Add dnspolicy default to the cluster-agent so when it boots it will
use the node's dns settings. Add tolerations to the shell/helmop for
controlplane nodes so the pods will assign and the tunnels will com up.
https://github.com/rancher/rancher/issues/31244
> [master] adding dnspolicy and tolerations to shell/helm

- pkg/systemtemplate/template.go
Problem:
Currently, this will leave a --- at the end of the document which
indicates another document is coming. This causes the k8s python client
to break as it expects another document
Solution:
Move the if check for the next section so the --- is only added if it's
needed
https://github.com/rancher/rancher/issues/31252
> Move document ending to if statment

- pkg/systemtemplate/template.go
Problem:
Currently, this will leave a --- at the end of the document which
indicates another document is coming. This causes the k8s python client
to break as it expects another document
Solution:
Move the if check for the next section so the --- is only added if it's
needed
https://github.com/rancher/rancher/issues/31252
> [master] Move document ending to if statment

- pkg/controllers/management/rkeworkerupgrader/node.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Problem:
An unavailable node is always reconciled to desired state bypassing the usual cordon->upgrade->uncordon
path. If they become ready later on, node could have already been upgraded before it's marked for upgrade
(NodeConditionUpgraded is never set). So the node never gets uncordoned since we rely on node conditions.
https://github.com/rancher/rancher/issues/30049
> [v2.5] uncordon upgraded nodes stuck in cordoned state

- pkg/controllers/management/rkeworkerupgrader/node.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Forward port: https://github.com/rancher/rancher/pull/31267
Problem:
An unavailable node is always reconciled to desired
state bypassing the usual cordon->upgrade->uncordon
path. If they become ready later on, node could have
already been upgraded before it's marked for upgrade
(NodeConditionUpgraded is never set). So the node
never gets uncordoned since we rely on node conditions.
https://github.com/rancher/rancher/issues/31268
> [v2.4] uncordon upgraded nodes stuck in cordoned state

- tests/validation/tests/v3_api/Jenkinsfile
- tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test
- tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
- tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests
Currently in Jenkins, folder properties are overriding parameters set in the jobs. 
This PR applies the parameters after the folder properties are resolved, preventing the folder properties from incorrectly overriding the job parameters.
> [Validation] - Jenkins - override folder properties with job parameters

- pkg/controllers/management/rkeworkerupgrader/node.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
Forward port https://github.com/rancher/rancher/pull/31267 
Problem:
An unavailable node is always reconciled to desired
state bypassing the usual cordon->upgrade->uncordon
path. If they become ready later on, node could have
already been upgraded before it's marked for upgrade
(NodeConditionUpgraded is never set). So the node
never gets uncordoned since we rely on node conditions.
https://github.com/rancher/rancher/issues/30049
> uncordon upgraded nodes stuck in cordoned state

- pkg/api/norman/customization/node/node.go
- pkg/apis/management.cattle.io/v3/machine_types.go
- pkg/client/generated/management/v3/zz_generated_node.go
- pkg/client/generated/management/v3/zz_generated_node_spec.go
- pkg/controllers/management/node/controller.go
- pkg/controllers/management/nodepool/nodepool.go
- pkg/schemas/management.cattle.io/v3/schema.go
- tests/integration/suite/common.py
- tests/integration/suite/test_node.py
Problem: scaling down a nodepool only allows for the +/- buttons or spec.quantity field to change, the nodepool reconciles and adds/removes nodes numerically from low to high. Allow for the ability to flag nodes for scaledown and remove them from the pool and decrement the quantity.
Solution: added node.spec.scaledown which is an RFC3339 date for when the node should be pulled from the pool. added a scaledown action which sets the scaledown time to now. nodepool will reconcile and pull the node marked for scaledown after the scaledown time. 
https://github.com/rancher/rancher/issues/22871
> [v2.5] add scaledown nodepool feature

- pkg/api/norman/customization/node/node.go
- pkg/apis/management.cattle.io/v3/machine_types.go
- pkg/client/generated/management/v3/zz_generated_node.go
- pkg/client/generated/management/v3/zz_generated_node_spec.go
- pkg/controllers/management/node/controller.go
- pkg/controllers/management/nodepool/nodepool.go
- pkg/schemas/management.cattle.io/v3/schema.go
- tests/integration/suite/common.py
- tests/integration/suite/test_node.py
Problem: scaling down a nodepool only allows for the +/- buttons or spec.quantity field to change, the nodepool reconciles and adds/removes nodes numerically from low to high. Allow for the ability to flag nodes for scaledown and remove them from the pool and decrement the quantity.
Solution: added node.spec.scaledown which is an RFC3339 date for when the node should be pulled from the pool. added a scaledown action which sets the scaledown time to now. nodepool will reconcile and pull the node marked for scaledown after the scaledown time. 
https://github.com/rancher/rancher/issues/22871
> [master] pick which node to scaledown in a pool

- pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
- pkg/image/export/main.go
**Problem:**
This fix no longer works because it depends on the default dev version being an incomplete semver version but a recent change has updated it to a complete version. The aforementioned change also solves the same issue that this fix did, the only difference being that it will now only include images that have constraints compatible with a .99 patch version.
**Solution:**
Revert fix and rely on the new fix instead: https://github.com/rancher/rancher/pull/31084
**Notes:**
Original fix was to address: https://github.com/rancher/rancher/issues/31061
> Revert "Merge pull request #31041 from rmweir/k3s-upgrade-dev-export"

- pkg/api/norman/customization/clusterregistrationtokens/formatter.go
- pkg/api/norman/customization/clusterregistrationtokens/formatter_test.go
- pkg/api/norman/customization/clusterregistrationtokens/import.go
- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- pkg/client/generated/management/v3/zz_generated_cluster.go
- pkg/client/generated/management/v3/zz_generated_cluster_status.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/multiclustermanager/routes.go
- pkg/systemtemplate/template.go
- added `AgentEnvVars` to node-agent template, same as cluster-agent 
- added `AppliedAgentEnvVars` to cluster status and redeploy agents if changed from spec 
- passing env vars to node registration command generated for custom clusters 
- passing env vars for deployAgent by node driver clusters 
- passing clusterID to the import url generated for imported clusters so `http://server_IP/v3/import/{token}_{clusterID}.yaml` has the env vars added by user on the cluster object 
https://github.com/rancher/rancher/issues/24876
https://github.com/rancher/rancher/issues/29961
https://github.com/rancher/rancher/issues/31370
> changes for agent env vars

- pkg/data/management/kontainerdriver_data.go
This PR is a 2.5 back-port of [this PR](https://github.com/rancher/rancher/pull/29727).
> [2.5] Update OKE cluster driver.

- .gitignore
- cleanup/binding-clean.sh
- cleanup/binding-clean.yaml
- cmd/agent/main.go
- pkg/agent/clean/binding.go
- pkg/agent/clean/binding_windows.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/indexes.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
This will add the ability for the agent to be ran as a job using a script and k8s manifest to cleanup duplicate roleBindings and clusterRoleBindings. 
There is nothing added to rancher yet to use this code, it can only be used externally through the script. 
Related to https://github.com/rancher/rancher/issues/29932 but this does not fix the issue, just allows a cleanup to be done on the management cluster.
> Add cleanup to the agent

- .gitignore
- cleanup/binding-clean.sh
- cleanup/binding-clean.yaml
- cmd/agent/main.go
- pkg/agent/clean/binding.go
- pkg/agent/clean/binding_windows.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/indexes.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
This will add the ability for the agent to be ran as a job using a script and k8s manifest to cleanup duplicate roleBindings and clusterRoleBindings.
There is nothing added to rancher yet to use this code, it can only be used externally through the script.
Related to #29932 but this does not fix the issue, just allows a cleanup to be done on the management cluster.
> [master] Add cleanup to the agent

- app/kontainerdriver_data.go
This PR is a 2.4 back-port of [this PR](https://github.com/rancher/rancher/pull/29727).
> [2.4] Update OKE cluster driver

- pkg/clustermanager/manager.go
- pkg/clusterrouter/proxy/proxy_server.go
- pkg/kontainer-engine/drivers/gke/gke_driver.go
Google (GKE specifically) must use OAuth2 for authentication. In order to do that efficiently, the google oauth2 library should be used for requests made to GKE. In this case, the proxy server was missing this.
Issue:
https://github.com/rancher/rancher/issues/31434
> Add OAuth2 for GKE in proxy server

- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
- package/Dockerfile.runtime
**Problem**
Need to bump rke2 1.18 to latest 1.18 version
**Solution**
Bump RKE2 to v1.18.16+rke2r1 
**Issue**
https://github.com/rancher/rancher/issues/30492
> [2.5] bump rke2 version to v1.18.16+rke2r1

- cmd/rancherd/go.mod
- cmd/rancherd/go.sum
- package/Dockerfile.runtime
**Problem**
Need to bump rke2 1.18 to latest 1.18 version
**Solution**
Bump RKE2 to v1.18.16+rke2r1
**Backport**
https://github.com/rancher/rancher/pull/31466
**Issue**
#30492
> bump rke2 version to v1.18.16+rke2r1

- scripts/build-server
Attempting to fix cache holding corrupt (reverted) types.
Alternatively we could use `go clean`
> Update build-server: Force rebuilding of packages

- tests/validation/Dockerfile.v3api
- tests/validation/tests/v3_api/scripts/build.sh
Just parameterize the terraform version.
I passed a shellcheck linter on it too.
Tested locally
```
➜  validation git:(terraform_tools_parameter) ✗ tests/v3_api/scripts/build.sh
+ set -eu
+ DEBUG=false
+ RKE_VERSION=v1.0.2
+ RANCHER_HELM_VERSION=v3.3.4
+ KUBECTL_VERSION=v1.16.6
+ CLI_VERSION=v2.4.5
+ SONOBUOY_VERSION=0.18.2
+ TERRAFORM_VERSION=0.13.6
+ JOB_NAME=testizaac1
+ BUILD_NUMBER=1
++ basename testizaac1
+ TRIM_JOB_NAME=testizaac1
+ '[' false '!=' false ']'
+++ dirname tests/v3_api/scripts/build.sh
++ cd tests/v3_api/scripts/../../../
++ pwd
+ cd /Users/izaac/repos/rancher-izaac/tests/validation
+ count=0
+ [[ 3 -gt 0 ]]
+ docker build -q -f Dockerfile.v3api --build-arg CLI_VERSION=v2.4.5 --build-arg RKE_VERSION=v1.0.2 --build-arg RANCHER_HELM_VERSION=v3.3.4 --build-arg …
```
> Adding terraform version param for validation tools

- tests/validation/tests/v3_api/resource/terraform/aks/aks.tf
- tests/validation/tests/v3_api/resource/terraform/aks/variables.tf
- tests/validation/tests/v3_api/test_create_ha.py
Realized this should be predictable, I used the resource prefix from the HA automation
> [Automation] Making the AKS cluster name predictable

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_upgrade.py
Most apps will not deploy on a hardened cluster due to the nature of its security, so better to just skip these tests during the pre/post upgrade checks.
> Skip app tests on hardened clusters

- pkg/controllers/management/drivers/nodedriver/machine_driver.go
- pkg/controllers/management/drivers/nodedriver/utils.go
- pkg/controllers/management/node/controller.go
- pkg/data/management/machinedriver_data.go
This patch adds the ability to create and store a CloudCredential via
the /v3/cloudcredentials API that can be used to drive GKE clusters.
By adding it to the machine driver controller, Rancher can expose this
credential type as a dynamic schema in the same way that other cloud
credentials are supported. However, since GKE is not a real machine
driver, we have to fake it by creating dummy flags for a pretend machine
driver binary.
The credential is identified by the private field "authEncodedJson"
where the value is an *escaped* string representing a JSON object for
the service account data obtained from Google. If the credential object
is provided as a regular JSON object rather than an escaped string,
Rancher will end up converting into a Go map and then to a string
representation of …
> Add support for creating a GKE cloud credential

- pkg/controllers/management/node/controller.go
This adds a fix to check for the case where no credentials are provided to the private registry configuration for a cluster.
Issue: 
- https://github.com/rancher/rancher/issues/31600
> [release/v2.5.7] Private Registry Regression Fix

- package/windows/Dockerfile.agent
- package/windows/Dockerfile.agent.20H2
- package/windows/bootstrap.ps1
Clusters that are created after this PR is merged will be able to use both the new Windows Monitoring V2 chart and the Wins Upgrades chart.
Related Issue: https://github.com/rancher/rancher/issues/31499
> Update bootstrapping to support Windows Monitoring V2 in fresh Windows clusters

- package/windows/bootstrap.ps1
Fixes broken windows cluster provisioning due to a mistake in the config merged in https://github.com/rancher/rancher/pull/31657.
```powershell
PS C:\Users\Administrator> C:\etc\rancher\wins.exe srv app run
FATA[2021-03-14T00:48:56Z] failed to load config from c:\etc\rancher\wins\config: could not decode config: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field WhiteListConfig.WhiteList.ProxyPorts of type int
```
Related Issue: https://github.com/rancher/rancher/issues/31499
> Fix proxyPorts to have int instead of string

- package/windows/bootstrap.ps1
Related Issue: https://github.com/rancher/rancher/issues/31499
> Whitelist windows-exporter path for Windows Monitoring

- package/windows/Dockerfile.agent
- package/windows/Dockerfile.agent.20H2
- package/windows/bootstrap.ps1
All the commits on this are cherry-picked backports with annotations to the commits on master. No changes introduced.
Related Issue: https://github.com/rancher/rancher/issues/31499
> [Backport] Upgrade bootstrapping to use wins v0.1.0 and whitelist Monitoring V2 processes

- pkg/controllers/management/drivers/nodedriver/machine_driver.go
- pkg/controllers/management/drivers/nodedriver/utils.go
- pkg/controllers/management/node/controller.go
- pkg/data/management/machinedriver_data.go
This patch adds the ability to create and store a CloudCredential via
the /v3/cloudcredentials API that can be used to drive GKE clusters.
By adding it to the machine driver controller, Rancher can expose this
credential type as a dynamic schema in the same way that other cloud
credentials are supported. However, since GKE is not a real machine
driver, we have to fake it by creating dummy flags for a pretend machine
driver binary.
The credential is identified by the private field "authEncodedJson"
where the value is an *escaped* string representing a JSON object for
the service account data obtained from Google. If the credential object
is provided as a regular JSON object rather than an escaped string,
Rancher will end up converting into a Go map and then to a string
representation of …
> [2.5] Add support for creating a GKE cloud credential

- pkg/controllers/management/node/controller.go
This adds a fix to check for the case where no credentials are provided to the private registry configuration for a cluster.
Issue:
- rancher/rancher#31733
> [release/v2.5] Private Registry Regression Fix

- pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go
- pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go
- pkg/controllers/managementuser/rbac/podsecuritypolicy/metadata.go
- pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go
Issue https://github.com/rancher/rancher/issues/22093
This PR add the feature to apply annotations defined at Rancher psp template to applied downstream cluster psp. Just annotations that its name doesn't contain `.cattle.io/` will be applied.
> [v2.5] Added downstream k8s cluster psp annotations from Rancher psp template

- pkg/metrics/metrics.go
- pkg/multiclustermanager/app.go
- pkg/multiclustermanager/routes.go
Problem:
Currently support can only get object counts through etcd, this can be a
pain and now with other backends, might not even be possible.
Solution:
Add an endpoint off /metrics/<clusterID> that will get an object count
of some of the more important object counts.
This only uses caches so there will be no API server calls.
> Add endpoint to get cluster object count

- pkg/metrics/metrics.go
- pkg/multiclustermanager/routes.go
Problem:
Currently support can only get object counts through etcd, this can be a
pain and now with other backends, might not even be possible.
Solution:
Add an endpoint off /metrics/ that will get an object count
of some of the more important object counts.
This only uses caches so there will be no API server calls.
> [2.5] Add endpoint to get cluster object count

- package/Dockerfile.agent
- package/run.sh
> use `tini` process watchdog for agent image as well.

- pkg/controllers/managementuser/networkpolicy/clusterHandler.go
When disabling PNI for a cluster, we should only delete NetworkPolicy resources in the downstream cluster that Rancher created. This change implements that behavior so that we don't also delete user created NetworkPolicy resources when disabling PNI.
I opted for a label based approach here as opposed to using NetworkPolicy names or some other approach.
I've tested this with user network policies created via kubectl and via Cluster Explorer UI. In both cases any user created NetworkPolicy resources are not deleted when PNI is disabled and the Rancher created policies are deleted, as expected.
Issue:
- https://github.com/rancher/rancher/issues/30135
> [release/v2.5] PNI - only delete Rancher created NetworkPolicy resources

- chart/scripts/post-delete-hook.sh
- chart/templates/post-delete-hook-cluster-role-binding.yaml
- chart/templates/post-delete-hook-cluster-role.yaml
- chart/templates/post-delete-hook-config-map.yaml
- chart/templates/post-delete-hook-job.yaml
- chart/templates/post-delete-hook-service-account.yaml
- chart/values.yaml
- scripts/chart/build
Add a post-delete-hook for cleaning up the apps left after uninstalling Rancher.
As of now, it will delete 
- the `helm-operation-*` pods
- the following apps from the cluster: 
```
- fleet
- fleet-agent
- rancher-operator
- rancher-webhook
```
see this comment for the behavior when the job fails: https://github.com/rancher/rancher/pull/31670#issuecomment-800437206
issue: https://github.com/rancher/rancher/issues/30924
> add a Helm post-delete-hook for Rancher

- pkg/api/norman/customization/kontainerdriver/actionhandler.go
- pkg/image/export/main.go
- pkg/image/resolve.go
- pkg/image/resolve_test.go
**Problem:**
Prior, a list of images was produced but there was no annotation included for why each image is included. This information is useful in deducing whether an airgap setup absolutely needs an image.
**Solution:**
Image export now produces a text file that includes images and which part of rancher utilizes them. Possible image sources are any feature or system chart, rke, k3sUpgrade, core (meaning it is need for rancher core functionality), and rancher (which it is either the rancher server image or the agent image).
**Testing:**
To test compare rancher-images.txt to previous version and make sure there aren't any unexpected difference. An unexpected difference would be something like many images missing. Another thing to validate is the the rancher-images-sources.txt should …
> Generate images file that includes sources

- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_rke2_upgrade
- tests/validation/tests/v3_api/test_import_k3s_cluster.py
- tests/validation/tests/v3_api/test_import_rke2_cluster.py
- tests/validation/tests/v3_api/test_upgrade.py
This enables a single-click upgrade job that will optionally deploy a rancher server, import rke2 clusters of different versions, and then run preupgrade job, upgrade the clusters, and postupgrade job. 
It works for hardened as well, but will have a bit of failures due to the nature of those jobs failing expectedly in a hardened run.
> Single click rke2-upgrade for jenkins

- pkg/controllers/management/clusteroperator/utils.go
Without this change, the behavior of the CAcert recorder for the EKS
provisioner changed when the handlers for EKS and GKE were refactored
into a single clusteroperator package (a6f0b91b), causing the cert to be
recorded on the cluster status wrongly. This change reverts the common
package to use EKS's old behavior. The GKE operator will be updated to
work in the same way.
Depends on https://github.com/rancher/gke-operator/pull/22
> Fix clusteroperator CAcert recorder

- pkg/controllers/management/clusteroperator/utils.go
Without this change, the behavior of the CAcert recorder for the EKS
provisioner changed when the handlers for EKS and GKE were refactored
into a single clusteroperator package (a6f0b91b), causing the cert to be
recorded on the cluster status wrongly. This change reverts the common
package to use EKS's old behavior. The GKE operator will be updated to
work in the same way.
(cherry picked from commit 3250af61873c82b2fda9d90fdbd1eebcdfefa910)
> [v2.5] Fix clusteroperator CAcert recorder

- pkg/api/norman/customization/gke/handler.go
- pkg/api/norman/customization/gke/listers.go
Add /meta/gkeClusters route
Add a route to list GKE clusters for the purpose of selecting one to
import.
The function can list either regional or zonal clusters. It rejects the
request if neither region nor zone are provided, and also if both
region and zone are provided.
https://github.com/rancher/rancher/issues/31461
---
Add /meta/gkeSharedSubnets route
Add a proxy route /meta/gkeSharedSubnets for querying usable subnets
shared to a service project, where the project ID provided in the URL
query is the service project. This call looks up the host project for
the provided service project, and uses that to look up the subnets that
are shared with the service project. See the `gcloud` command line
reference example[1].
The result of this query will resemble the following:
```
$ curl -k -u …
```
> Add /meta/gkeSharedSubnets and /meta/gkeClusters routes

- pkg/api/norman/customization/gke/handler.go
- pkg/api/norman/customization/gke/listers.go
Add /meta/gkeClusters route
Add a route to list GKE clusters for the purpose of selecting one to
import.
The function can list either regional or zonal clusters. It rejects the
request if neither region nor zone are provided, and also if both
region and zone are provided.
https://github.com/rancher/rancher/issues/31461
---
Add /meta/gkeSharedSubnets route
Add a proxy route /meta/gkeSharedSubnets for querying usable subnets
shared to a service project, where the project ID provided in the URL
query is the service project. This call looks up the host project for
the provided service project, and uses that to look up the subnets that
are shared with the service project. See the `gcloud` command line
reference example[1].
The result of this query will resemble the following:
```
$ curl -k -u …
```
> [v2.5] Add /meta/gkeSharedSubnets and /meta/gkeClusters routes

- pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
- pkg/settings/setting.go
Add missing gke-refresh setting and missing bits for GKE
cloud provider in clusterupstreamrefresher.
> Fix GKE integration with clusterupstreamrefresher

- pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
- pkg/settings/setting.go
Add missing gke-refresh setting and missing bits for GKE
cloud provider in clusterupstreamrefresher.
(cherry picked from commit d3959066923992147a448a132f9a3849b42e6f37)
> [v2.5] Fix GKE integration with clusterupstreamrefresher

- pkg/api/norman/customization/cluster/validator.go
**Problem:**
Prior, it could be
set which is invalid because it is expected it will be initialized by a controller when it is detected that a cluster is a k3s cluster and the cluster is not embedded. This made it possible to set the k3sConfig and attempt upgrade an embedded k3s cluster, which is not possible.
**Solution:**
Validation has been added to prevent a k3sConfig being set on a cluster that does not have one set already.
**Issue:**
https://github.com/rancher/rancher/issues/30977
> Add k3sconfig validation

- pkg/data/management/role_data.go
This fixes a dropped error variable in `pkg/data/management`.
> pkg/data/management: fix dropped error

- pkg/api/norman/customization/namespace/namespace.go
- pkg/controllers/managementuser/networkpolicy/clusterHandler.go
- pkg/controllers/managementuser/networkpolicy/netpol.go
- pkg/controllers/managementuser/networkpolicy/nssyncer.go
Issue: 
- https://github.com/rancher/rancher/issues/30211
The fix is to add an "allow all traffic" NetworkPolicy resource to each system project namespace. See the linked issue for further details on the fix
Passing scan:
Controller test cases:
1. Create namespace in no project
- Expected: no rancher network policies added
- Result: [PASS]
2. Create namespace in default project
- Expected: non system project network policies added, hn-nodes and np-default
- Result: [PASS]
3. Create namespace in system project 
- Expected: system project network policies added, np-default-allow-all
- Result: [PASS]
4. Create new project and create namespace in it
- Expected: non system project network policies added, hn-nodes and np-default
- Result: [PASS]
NOTE: I fixed a bug related to moving namespaces, …
> [release/v2.5] Fix CIS scan when PNI is enabled

- pkg/catalogv2/content/content_test.go
**Problem**
Catalog V2 needs to have a way to not show certain charts for a min, max or min/max version of rancher. 
**Solution** 
As part of completing this issue, I have created tests to validate the various semver comparison strings that could be used to filter or not filter out a chart from being available for a specific rancher version. 
As part of https://github.com/rancher/rancher/commit/fa26506587a029a7774c5bb3756772c3e95175d4, a chart annotation  was added that can be used to set a min, max, or min/max version of rancher. The version comparison string is taken from the chart annotation and is used to determine if the current rancher server version meets the criteria.  https://github.com/rancher/rancher/commit/fa26506587a029a7774c5bb3756772c3e95175d4
**Issue** …
> Add tests for min/max rancher version chart annotation

- pkg/controllers/management/auth/manager.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
Problem:
apiGroups are not taken into account when creating downstream k8s auth
objects. This causes rancher to fail comparisons and have incorrect
permissions
Solution:
Update to use the apiGroup when creating/validating roles and
clusterRoles
> Take apiGroups into account when processing auth objects

- pkg/controllers/management/auth/manager.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
Problem:
apiGroups are not taken into account when creating downstream k8s auth
objects. This causes rancher to fail comparisons and have incorrect
permissions
Solution:
Update to use the apiGroup when creating/validating roles and
clusterRoles
> [master] Take apiGroups into account when processing auth objects

- pkg/catalogv2/content/content_test.go
BACKPORT PR
Master PR: https://github.com/rancher/rancher/pull/31959
**Problem**
Catalog V2 needs to have a way to not show certain charts for a min, max or min/max version of rancher.
**Solution**
As part of completing this issue, I have created tests to validate the various semver comparison strings that could be used to filter or not filter out a chart from being available for a specific rancher version.
As part of fa26506, a chart annotation was added that can be used to set a min, max, or min/max version of rancher. The version comparison string is taken from the chart annotation and is used to determine if the current rancher server version meets the criteria. fa26506
Issue
#31264
> [release/v2.5] Add tests for min/max rancherVersion chart annotation

- pkg/apis/management.cattle.io/v3/machine_types.go
- pkg/client/generated/management/v3/zz_generated_node_driver.go
- pkg/client/generated/management/v3/zz_generated_node_driver_spec.go
- pkg/controllers/management/drivers/nodedriver/machine_driver.go
- pkg/data/management/machinedriver_data.go
A previous PR (31548) added support for Google cloud credential.
However, this made the unsupported Google node driver active. In order
to deactivate the node driver and create the cloud credential schema for
the Google driver, a new field is added to the NodeDriverSpec:
AddCloudCredentialByDefault. If this is `true` for any node driver, then
the driver is downloaded, if necessary, and the cloud credential schema
created. This would work for any node driver, not just the built-ins.
Issue:
https://github.com/rancher/rancher/issues/31858
> Add ability to create cloud creds for any node driver 

- pkg/image/export/main.go
~~This is a greedy solution that falls back to `-amd64` if the first pull without the arch is unsuccessful.~~
EDIT: talked out a better solution with @luthermonson. We will now assume there is a manifest since the original implementation predates manifests with Windows, but if an error occurs, we will fallback to the old method.
Relevant issues:
- https://github.com/rancher/rancher/issues/32016
- https://github.com/rancher/rancher/issues/28721
Proof of concept:
```powershell
PS > 1,2,3 | %{ $foo = $_; write-host $foo }
1
2
3
```
> Rely on Windows manifests instead of manual tags

- pkg/controllers/management/auth/manager.go
- pkg/controllers/user/rbac/prtb_handler.go
Problem:
apiGroups are not taken into account when creating downstream k8s auth
objects. This causes rancher to fail comparisons and have incorrect
permissions
Solution:
Update to use the apiGroup when creating/validating roles and
clusterRoles
Backport of https://github.com/rancher/rancher/pull/32018
> [2.4] Take apiGroups into account when processing auth objects

- tests/integration/suite/test_workloads.py
This undoes the following:
- master: https://github.com/rancher/rancher/commit/b9e54de9d58a630ba658bcec3a94527ff65b5590
And is related to the following:
- release/v2.5: https://github.com/rancher/rancher/commit/343ef404913a1814e7099c328724b4c33678486f
- https://github.com/rancher/rancher/pull/32094
Relevant issue(s):
- https://github.com/rancher/rancher/issues/32092
> Use mirrored images for workload test

- tests/integration/suite/test_workloads.py
This undoes the following:
- release/v2.5: https://github.com/rancher/rancher/commit/343ef404913a1814e7099c328724b4c33678486f
And is related to the following:
- master: https://github.com/rancher/rancher/commit/b9e54de9d58a630ba658bcec3a94527ff65b5590
- https://github.com/rancher/rancher/pull/32091
Relevant issue(s):
- https://github.com/rancher/rancher/issues/32092
> [2.5] Use mirrored images for workload test

- pkg/controllers/management/clusterupstreamrefresher/gke_upstream_spec.go
Without this patch, if a GKE cluster is imported to Rancher, and then a
change from GKE is synced back to the cluster in Rancher, "imported"
will flip back to false, and the guard in gke-operator that prevents
sending a DELETE request to imported clusters that are removed from
Rancher gets thwarted. This change fixes the upstream spec builder
function in the cluster refresher to always use the config spec value
for the Imported attribute.
https://github.com/rancher/rancher/issues/32065
> [v2.5] Add Imported field to GKE upstream spec builder

- pkg/controllers/management/clusteroperator/utils.go
- pkg/controllers/management/eks/eks_cluster_handler.go
- pkg/controllers/management/gke/gke_cluster_handler.go
Without this change, if a GKE cluster creation fails for some GKE-side
reason, the state of the cluster object will appear to rapidly flip
between provisioning and failed, and the Rancher logs will be filled
with a constant stream of messages:
2021/04/13 10:15:43 [ERROR] error syncing 'c-tcc2p': handler gke-operator-controller: failed setting cluster [] condition Provisioned false with message: creation failed for cluster cluster-name, requeuing
This is a confusing UI behavior and the volume of logs emitted has the
potential to generate large log files unexpectedly quickly.
This change removes the initial status update during the "creating"
phase. The Provisioning condition will be set a few lines later to
either Unknown or False, so the initial status update request is
superfluous. …
> [v2.5] Do not set unknown condition for creating cluster

- pkg/controllers/management/auth/indexes.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
- pkg/rbac/common.go
This is a foward port PR for deterministic naming changes to RoleBinding and ClusterRoleBinding resources
Previous PRs:
- https://github.com/rancher/rancher/pull/31813
- https://github.com/rancher/rancher/pull/32014
Issue:
- rancher/rancher#29932
> [master] Implement deterministic naming for Bindings to mitigate duplicate issues

- pkg/controllers/dashboardapi/settings/settings.go
- pkg/tls/tls.go
Problem:
In an HA setup ranchers will race to attempt to create things, including
settings and ca cert secrets. This can cause rancher to fatal and
restart the pod.
Solution:
Handle the error and either try again in the case of setting up
listeners or ignore it when creating settings.
https://github.com/rancher/rancher/issues/32116
> [2.5] Handle already exists errors during startup

- pkg/controllers/dashboardapi/settings/settings.go
- pkg/tls/tls.go
Problem:
In an HA setup ranchers will race to attempt to create things, including
settings and ca cert secrets. This can cause rancher to fatal and
restart the pod.
Solution:
Handle the error and either try again in the case of setting up
listeners or ignore it when creating settings.
https://github.com/rancher/rancher/issues/32116
forward port of https://github.com/rancher/rancher/pull/32163
> [master] Handle already exists errors during startup

- pkg/controllers/managementuser/networkpolicy/podhandler.go
- pkg/controllers/managementuser/networkpolicy/servicehandler.go
Issue:
- https://github.com/rancher/rancher/issues/30135
The HostPort and NodePort specific policies were not getting the label: `cattle.io/creator: norman` added when they are created. Fix this by specifying the label in the policy generation code. This will ensure the label is always there and the policies get deleted when PNI is disabled.
> [release/v2.5] Deletion fix for HostPort and NodePort NetworkPolicy resources

- pkg/api/norman/customization/cluster/validator.go
Windows is a supported image type for GKE node pools, but it can't be
the only type of node pool in the cluster. Without this change, it's
possible to send a cluster create or update request for an invalid
cluster with only Windows node pools. For create requests this is not
much of a problem, because GKE will send an HTTP 400 response and the
user can recreate the cluster with the correct configuration. It causes
more of a problem if the user starts with a valid cluster and then sends
an update request to delete the non-Windows node pools. Because of how
syncing works, the state of the cluster object will only reflect the
invalid Windows-only node pool configuration instead of the real state
of the cluster, so the mistake cannot be corrected. The solution is to
ensure this kind of …
> [v2.5] Add linux node pool GKE cluster validator

- pkg/controllers/dashboard/helm/repo.go
- pkg/controllers/dashboard/helm/repo_test.go
When the RepoSpec of a chart repo contains a git branch and an http url, shouldRefresh returns always true, because the unnecessary branch is never set in the RepoStatus. As a result the agent refreshes the repo every 4 seconds. This puts a high load on the agent as well as etcd and causes significant network traffic.
This can happen when a Repo is created manually through the Kubernetes API or with Terraform. The rancher2 terraform provider currently even sets gitBranch to "master" by default, even if a http url is set.
Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>
https://github.com/rancher/rancher/issues/23256
> [2.5] Fix Chart Repo shouldRefresh logic for inconsistent repo definitions

- pkg/controllers/dashboard/helm/repo.go
- pkg/controllers/dashboard/helm/repo_test.go
When the RepoSpec of a chart repo contains a git branch and an http url, shouldRefresh returns always true, because the unnecessary branch is never set in the RepoStatus. As a result the agent refreshes the repo every 4 seconds. This puts a high load on the agent as well as etcd and causes significant network traffic.
This can happen when a Repo is created manually through the Kubernetes API or with Terraform. The rancher2 terraform provider currently even sets gitBranch to "master" by default, even if a http url is set.
Issue: https://github.com/rancher/rancher/issues/23256.
> Fix Chart Repo shouldRefresh logic for inconsistent repo definitions

- cmd/agent/main.go
- pkg/agent/clean/binding.go
- pkg/agent/clean/binding_windows.go
- pkg/data/management/bindings_cleanup.go
- pkg/multiclustermanager/app.go
For standalone setups the inclusterconfig is not found hence the config from rancher's scaledcontext should be passed.
https://github.com/rancher/rancher/issues/32105
Tested with standalone, HA setups as well as the agent cleanup script.
> Pass  the config from scaledContext to the bindings cleanup code 

- pkg/image/resolve.go
Relevant issue: https://github.com/rancher/rancher/issues/32290
Original solution basis: https://play.golang.org/p/_Dj725132Lm
Refactor basis: https://play.golang.org/p/k-6IyqTPE66
Solution Explanation: https://github.com/rancher/rancher/pull/32291#issuecomment-825115713
> Use comma-delineated list for OS in image list generation

- scripts/package
Some of the images in rancher/charts index.yaml file are linked via the
released/assets directory instead of just the assets directory. Any of
these images in the released directory were not getting scanned by the
image exporter because the package script is explicitly using the assets
directory.
Now, in the case that the index.yaml file links to the released/
directory, the tarfile is explicitly extracted to the assets directory
to be included in the export.
Co-authored-by: Brenda Rearden <brenda@rancher.com>
Issue:
https://github.com/rancher/rancher/issues/31995
> Scan released directory for images

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
https://github.com/rancher/rancher/issues/32207
> [v2.5] Bump gke-operator to RC9

- pkg/image/resolve.go
Allows Rancher to pick up images embedded in lists like rancher-wins-upgrader [here](https://github.com/rancher/charts/blob/6cbef79083183ff1f0d1e3070de12b343dc61ff3/released/charts/rancher-wins-upgrader/rancher-wins-upgrader/0.0.100/values.yaml#L21-L22).
Related Issue: https://github.com/rancher/rancher/issues/32280
> Allow walkthroughMap to walk through list entries

- pkg/image/resolve.go
Allow walkthroughMap to walk through list entries
(cherry picked from commit 4deb12e7e8cb2fdce91aeea48fa70b5e4263b762)
Backports https://github.com/rancher/rancher/pull/32324.
Related Issue: https://github.com/rancher/rancher/issues/32280
> [2.5] Allow walkthroughMap to walk through list entries

- pkg/api/norman/customization/cluster/actions_kubeconfig.go
This fixes a dropped error in `pkg/api/norman/customization/cluster`.
> pkg/api/norman/customization/cluster: fix dropped error

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
Forward port of https://github.com/rancher/rancher/pull/32307
https://github.com/rancher/rancher/issues/32207
> Bump gke-operator to RC9

- .drone.yml
looks like drone isn't going to get their build hosts any time soon, moving the images I made for 2004/20H2 from my personal docker up to rancher's.
> Switching windows images to the rancher hub account

- cmd/rancherd/go.mod
- package/Dockerfile.runtime
- scripts/build-rancherd
- scripts/package
- scripts/version
RKE2 changed the way it sets default images and tags. This change
introduces the necessary environment variables from the RKE2 repo
necessary to set the default images and tags. These will need to be
updated when updating RKE2 version going forward.
Issue:
https://github.com/rancher/rancher/issues/31375
Related RKE2 PR:
[`2ef4906` (#715)](https://github.com/rancher/rke2/pull/715/commits/2ef4906041918071eb1c8f14a48f89834735dc8a#diff-5860f3d4051a1dbb1a2a15c593338edfd3682123f4b21cda1699a1105a3f236dR11-R22)
> Set default image:tag for RKE2 in rancherd

- cmd/rancherd/go.mod
- package/Dockerfile.runtime
- scripts/build-rancherd
- scripts/package
- scripts/version
A previous change moved the RKE2_VERSION in the environment variable
file. This caused a problem with the docker-publish-runtime drone
pipeline because this environment file is not used there.
This change moves the RKE2_VERSION back to the
package/Dockerfile.runtime and adds comments to future updaters on how
to handle updating.
Previous PR:
https://github.com/rancher/rancher/pull/32442
Issue:
https://github.com/rancher/rancher/issues/31375
> Fix docker-runtime-publish

- pkg/api/norman/customization/cluster/validator.go
Don't crash if nodepool name is unset.
https://github.com/rancher/rancher/issues/32467
> Fix nodepool name dereference

- chart/templates/_helpers.tpl
- chart/templates/post-delete-hook-job.yaml
Issue: https://github.com/rancher/rancher/issues/32436
Add a template function to better handle the system default registry in post-delete-hook-job 
Note:
A forward PR to rancher/master will be made after this PR is approved.
> [2.5.8] handle the system default registry in post-delete-hook-job better

- chart/templates/_helpers.tpl
- chart/templates/post-delete-hook-job.yaml
Issue: #32436
forward port of: https://github.com/rancher/rancher/pull/32438
Add a template function to better handle the system default registry in post-delete-hook-job
> [master] Add a template function to better handle the system default registry in post-delete-hook-job

- cmd/rancherd/bundle/lib/systemd/system/rancherd-agent.env
- cmd/rancherd/bundle/lib/systemd/system/rancherd-server.env
- scripts/build-rancherd
There was some mixups with the RKE2 changes that caused the runtime
image to be set incorrectly.
Also, there were changes in RKE2 that caused problems with containerd
not being able to find the $HOME environment variable. That is also
fixed here.
Issue:
https://github.com/rancher/rancher/issues/31375
> Correct runtime image for rancherd

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
Forward port of https://github.com/rancher/rancher/pull/32556
> Update gke-operator to v1.0.1

- go.mod
- go.sum
- pkg/apis/cluster.cattle.io/v3/types.go
- pkg/apis/cluster.cattle.io/v3/zz_generated_deepcopy.go
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/auth/audit/audit.go
- pkg/auth/providers/activedirectory/activedirectory_provider.go
- pkg/auth/providers/azure/azure_provider.go
- pkg/auth/providers/common/provider.go
- pkg/auth/providers/github/github_provider.go
- pkg/auth/providers/googleoauth/goauth_provider.go
- pkg/auth/providers/ldap/ldap_provider.go
- pkg/auth/providers/local/local_auth_provider.go
- pkg/auth/providers/providers.go
- pkg/auth/providers/saml/saml_provider.go
- pkg/auth/requests/authenticate.go
- pkg/auth/requests/chained.go
- pkg/auth/requests/filter.go
- pkg/auth/requests/impersonate.go
- pkg/client/generated/cluster/v3/zz_generated_cluster_user_attribute.go
Adding in "Impersonate-Extra-" headers to log user's principalId and username from the external IDP. 
This needs a fix in norman proxy_store as well. So includes a vendor update for new norman change https://github.com/rancher/norman/pull/396
https://github.com/rancher/rancher/issues/31166
> Audit changes for logging user info from auth provider

- tests/integration/requirements.txt
- tests/integration/suite/conftest.py
- tests/integration/suite/test_cluster.py
- tests/validation/requirements.txt
- tests/validation/requirements_v3api.txt
In https://drone-pr.rancher.io/rancher/rancher/15276/1/2 I ran into:
```
if conditions is None:
--
1312 | >           raise ValueError("Invalid value for `conditions`, must not be `None`")  # noqa: E501
1313 | E           ValueError: Invalid value for `conditions`, must not be `None`
1314 |  
1315 | ../.tox/rancher/lib/python3.8/site-packages/kubernetes/client/models/v1beta1_custom_resource_definition_status.py:101: ValueError
```
Which should be fixed in this version (https://github.com/kubernetes-client/python/issues/1022)
> Bump python k8s client

- .drone.yml
Calling `promote` with `promote-docker-image` still runs some of the chart steps as they are not scoped (I guess), see http://drone-publish.rancher.io/rancher/rancher/5520
> Scope chart promote steps to promote-stable

- package/Dockerfile.agent
- package/share-root.sh
We are abusing the downloads of the docker 1.10 cli as we only use it in one scenario which is basically deprecated. Basically this was a fix for non-shared mounted root directories. We are more or less convinced this isn't a thing any more so we're dropping this shared-mount.sh fix as it was the only thing actually using the docker cli in the agent.
To confirm your linux distro is fine you do a quick 
```
findmnt -o TARGET,PROPAGATION /
```
and you should see
```
TARGET PROPAGATION
/      shared
```
https://github.com/rancher/rancher/issues/32052
> [v2.5] remove docker 1.10 cli from agent

- pkg/wrangler/context.go
https://github.com/rancher/rancher/issues/30346
This was 50 in v2.4 (https://github.com/rancher/types/blob/release/v2.4/config/context.go#L379), thanks to Dan for looking into it. It being at 5 was causing the controller to provision 5 machines and only continue when 1 machine was finished.
> Bump management controller workers to 50

- pkg/kontainer-engine/drivers/rke/rke_driver.go
https://github.com/rancher/rancher/issues/21976
When adding logging, this was the output for the current code:
```
2021/05/07 22:11:52 [DEBUG] Going to remove state directories: [management-state/rke/rke-445186939/cluster.yml] [management-state/rke/rke-445186939/kube_config_cluster.yml] [management-state/rke/rke-445186939]                                                                                                             
2021/05/07 22:11:52 [ERROR] Error while deleting [management-state/rke/rke-445186939/cluster.yml], remove management-state/rke/rke-445186939/cluster.yml: no such file or directory                                                                                                                                           
2021/05/07 22:11:52 [ERROR] Error while …
```
> Cleanup RKE state directory

- pkg/auth/audit/audit.go
https://github.com/rancher/rancher/issues/32588
This enhancement is to log extra.username in the Rancher API audit logs at Metadata level for a Login request - the username field of the login form is read and logged in the Rancher API audit log.
This is supported only for authproviders which work with a username/password form of login like AD,LDAP, local. For other token/SAML based providers there will be no username logged for login requests at Metadata level.
> Add username from login request to rancher api audit log at level 1 (metadata) and above

- tests/validation/Dockerfile.v3api
Some python libraries require a newer version of pip to retrieve their binaries instead of compiling them.
This fix the docker build error on the automation validation.
> Automation - Upgrading pip before installing dependencies

- pkg/data/management/machinedriver_data.go
Part of AKSv2 cloud credentials is also tenantId, which has to be added.
rancher/rancher#31014
> Add tenatdId to AKSv2 cloud credentials

- pkg/multiclustermanager/app.go
https://github.com/rancher/rancher/issues/32792
I see both logs.  Rancher startup completes before the binding cleanup is started
```
2021/05/26 00:54:11 [INFO] Rancher startup complete
2021/05/26 00:54:11 [INFO] CleanupDuplicateBindings, checking configmap
2021/05/26 00:54:11 [INFO] Calling Duplicate CRB and RB cleanup
2021/05/26 00:54:11 [INFO] Starting bindings cleanup
2021/05/26 00:54:12 [INFO] Done Duplicate CRB and RB cleanup
```
> Do bindings cleanup in a separate goroutine

- pkg/api/norman/customization/cluster/formatter.go
In Formatter function keys googleKubernetesEngineConfig
and amazonElasticContainerServiceConfig exist, but values
are for them are nil.
Issue https://github.com/rancher/rancher/issues/32887
> Fix check for gke and eks configs

- pkg/httpproxy/proxy.go
The ResourceRequest field is needed to distinguish between a kubernetes
resource and a generic HTTP path.
> Add ResourceRequest to proxy SAR

- tests/integration/requirements.txt
- tests/integration/tox.ini
The python 3.x version is controlled by the Dockerfile selection already
so we can make tox use the generic "python3" version, especially for
flake8 which is version agnostic.
> Use the system python3 selected version for integration tests

- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_actions.go
- pkg/auth/providers/oidc/oidc_provider.go
**Issue(s)**
https://github.com/rancher/rancher/issues/32990
https://github.com/rancher/rancher/issues/32941
https://github.com/rancher/rancher/issues/32936
**Problem**
The type and name are not being set properly with `.GetName()` and `.GetType()` which is resulting in both Keycloak OIDC and OIDC providers to become enabled. Both of these being enabled at the same time causes
1. The login screen not to know which auth provider to show to the user
2. Once they become enabled, there is no way to disable them because the disable doesn't have the correct Name of the provider to disable it. 
**Solution**
Set the name and type values on the OIDCProvider struct so that the values are correct at time of configuration and it doesn't rely on inheritance to call the correct function.
> Use name and type string from struct for keycloak oidc & oidc

- cmd/agent/main.go
(Not more than) half of token is logged at info level now. Full token logging is now at trace level.
Replaces https://github.com/rancher/rancher/pull/32851
> Change to partial token info logging / full token trace logging

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/client/generated/management/v3/zz_generated_aks_cluster_config_spec.go
- pkg/kontainer-engine/drivers/aks/aks_driver.go
- pkg/kontainer-engine/drivers/aks/aks_driver_test.go
In AKSv2 CheckLogAnalyticsWorkspaceForMonitoring has improved function
with updated metadate. This will be maintained in aks-operator.
Issue: https://github.com/rancher/rancher/issues/32967
> [AKS] Move AKSv2 monitoring function to operator

- pkg/controllers/management/aks/aks_cluster_handler.go
- pkg/controllers/management/clusteroperator/utils.go
- pkg/controllers/management/eks/eks_cluster_handler.go
- pkg/controllers/management/gke/gke_cluster_handler.go
When the call is made to get a service account for the hosted providers,
the CA for the k8s API is used. If Rancher is running behind a proxy or
the like that uses its own CA, then this call fails.
This change will add the additional CAs to the rest config so the CAs
are used in the call to get the service account token.
Issue:
https://github.com/rancher/rancher/issues/31846
> Use additional CA for hosted providers

- chart/templates/post-delete-hook-cluster-role.yaml
- chart/templates/post-delete-hook-psp.yaml
issue: https://github.com/rancher/rancher/issues/32878
Problem:
The post-delete-hook pod fails to be scheduled because it does not have and can not use any psp. 
Solution:
Add the missing permission and psp resource. 
Note:
Rancher itself can be installed and uninstalled successfully because it uses the cluster-admin clusterrole. 
Next Step:
> add podSecurityPolicy to the post-delete-hook

- pkg/api/norman/store/cluster/cluster_store.go
This PR is for changes in validation logic for the `enableNetworkPolicy` boolean on cluster objects. The changes will allow for enabling of PNI on hosted and imported clusters.
In the cluster store, we do not have access to kontainer driver information, so the cluster type has to be inferred from *Config objects. By disallowing only for rke2 and k3s, we are effectively allowing this value to be set for other clusters.
These changes satisfy backend validation changes for these issues:
- https://github.com/rancher/rancher/issues/33016
- https://github.com/rancher/rancher/issues/32834
- https://github.com/rancher/rancher/issues/32833
- https://github.com/rancher/rancher/issues/32832
> Allow hosted and imported clusters to enable PNI

- pkg/api/norman/customization/cluster/validator.go
- pkg/apis/go.mod
Windows node pools do not currently work with Rancher charts, so add a
validator to ensure "Windows" is not set for the node pools OS Type, and
update the schema to remove windows-related fields.
Depends on https://github.com/rancher/aks-operator/pull/17
https://github.com/rancher/rancher/issues/32586
> Validate against using windows node pools for AKS

- pkg/controllers/management/drivers/nodedriver/machine_driver.go
- pkg/data/management/machinedriver_data.go
d4f32aca added `tenantId` as a public credential field for the dynamically
generated `azurecredentialconfig` schema. The corresponding machine driver
change[1] can optionally accept a tenant ID but can fall back on its
original lookup behavior if none is provided. Without this change,
Rancher sets the new field as required and breaks backwards
compatibility. This change adds a new "optional" category to the machine
driver data to allow the credential not to be marked as required.
[1] https://github.com/rancher/machine/pull/133
https://github.com/rancher/rancher/issues/32897
> Make Azure tenantId optional in cloud credential

- pkg/clustermanager/manager.go
- pkg/controllers/management/aks/aks_cluster_handler.go
- pkg/controllers/management/clustergc/cluster_scoped_gc.go
- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/eks/eks_cluster_handler.go
- pkg/controllers/management/gke/gke_cluster_handler.go
- pkg/controllers/management/node/cleanup.go
- pkg/dialer/factory.go
During the cluster delete process some things go away like cluster agent and make things time out terrible and very ugly. This PR adds some checks to confirm if errors bubbling up from the dialer factory are connectivity errors and if they are then move on to deleting nodes. This PR also adds a short circuit to the clusterprovisioner to not do it's cleanup on RKE1 custom clusters as my node-cleanup process will do everything we need and is more reliable.
https://github.com/rancher/rancher/issues/26545
> update cleanup for deleted clusters

- pkg/api/norman/customization/cluster/validator.go
PNI Should be disallowed from being enabled unless the GKE cluster has network policy support enabled.
Issue: 
- https://github.com/rancher/rancher/issues/32832
> Add validation logic around enabling PNI for GKE clusters

- pkg/api/norman/server/managementstored/setup.go
- pkg/api/norman/store/catalog/store.go
- pkg/auth/api/user/user_actions.go
- pkg/auth/api/user/user_store.go
- pkg/data/management/role_data.go
1) This PR lets a restrictedAdmin configure Authentication.
2) This PR extends restrictedAdmin permissions to allow a restrictedAdmin full access to manage
- clustertemplates
- catalogs
- users
- groups
- podsecuritypolicytemplates
- authconfigs 
- nodedrivers
- kontainerdrivers
- roletemplates
3) This PR also prohibits a restrictedAdmin from editing/deleting/setPassword for globalAdmin user
4) This PR also prohibits a restrictedAdmin from editing system-library in global catalogs.
5) Also assigns "settings" permissions in the case of bootstrapping default admin as restricted admin
> Restricted Admin permission fixes

- pkg/api/norman/customization/kontainerdriver/actionhandler.go
- pkg/image/export/main.go
- pkg/image/external/external.go
- pkg/image/resolve.go
- pkg/image/resolve_test.go
- scripts/k3s-images.sh
- scripts/package
This PR refactors the existing k3s image code to be generic, and then adds RKE2 images for airgap. Since RKE2 and k3s use the same KDM scheme and versioning scheme, the code can be interchangeable.
**Relevant issue:** https://github.com/rancher/rancher/issues/32403
```
% go test
Cloning repository https://github.com/rancher/system-charts.git (branch: dev) into /var/folders/7f/gwr4k3d15xvg9mhqq87dr6fc0000gp/T/system-charts769112054
Cloned repository https://github.com/rancher/system-charts.git (branch: dev) into /var/folders/7f/gwr4k3d15xvg9mhqq87dr6fc0000gp/T/system-charts769112054
Checking out commit 7c183b98ceb8a7a50892cdb9a991fe627a782fe6
Checked out commit 7c183b98ceb8a7a50892cdb9a991fe627a782fe6
Cloning repository https://github.com/rancher/charts.git (branch: dev-v2.5) into …
```
> Add RKE2 images to airgap, make airgap image generation amd64 only

- pkg/api/steve/clusters/shell.go
- pkg/catalogv2/helmop/operation.go
Remove Impersonate-Extra- Header that were sent through proxy header.
This is not allowed in k8s api server as requests can't only have extra
header without users.
> Fix cluster shell and helm operation

- package/Dockerfile
As the other chart repos were already cloned with --depth 1
I assume this is fine for the helmv3 charts as well.
Saves about 2MB
> Shallow clone helmv3 charts as well

- pkg/data/management/kontainerdriver_data.go
This PR updates the OKE cluster driver to version v1.7.0.
This release has a number of bug-fixes and enhancements including encrypting the key-value store that OKE uses for cluster coordination and state management at rest by specifying the following flag: --kms-key-id=ocid1.key.oc1.iad.<unique_ID>
related issue
https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/32
> Update oke kontainer engine driver v1.7.0

- pkg/auth/providers/keycloakoidc/keycloak_client.go
- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_client.go
- pkg/auth/providers/oidc/oidc_provider.go
- pkg/auth/tokens/manager.go
**Issue**
https://github.com/rancher/rancher/issues/33036
**Problem**
Client created as part of configuring Keycloak is not being used for the http call
The cert and key values are not being checked before attempting to add them to the http client
Http client is nil
Copy paste resulted in auth type of "token" being used
**Solution**
Remove the new client that is being created and use the one that is part of the keycloakClient
Ensure that cert and key are checked prior to attempting to add them to the http client tls settings 
Add code to set the http client when its created. 
Change so auth type of "bearer" is being used.
> Create check for cert and key to avoid error

- pkg/api/norman/customization/app/app.go
- pkg/api/norman/customization/cluster/actions_monitoring.go
- pkg/api/norman/customization/multiclusterapp/multi_cluster_app.go
- pkg/api/norman/customization/project/project_actions.go
- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/apis/management.cattle.io/v3/multi_cluster_app.go
- pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- pkg/apis/project.cattle.io/v3/app_types.go
- pkg/apis/project.cattle.io/v3/zz_generated_deepcopy.go
- pkg/app/utils.go
- pkg/client/generated/management/v3/zz_generated_answer.go
- pkg/client/generated/management/v3/zz_generated_bastion_host.go
- pkg/client/generated/management/v3/zz_generated_monitoring_input.go
- pkg/client/generated/management/v3/zz_generated_monitoring_output.go
- pkg/client/generated/management/v3/zz_generated_rancher_kubernetes_engine_config.go
- pkg/client/generated/project/v3/zz_generated_app.go
- pkg/client/generated/project/v3/zz_generated_app_revision_status.go
- pkg/client/generated/project/v3/zz_generated_app_spec.go
- pkg/client/generated/project/v3/zz_generated_app_upgrade_config.go
- pkg/controllers/managementlegacy/multiclusterapp/controller_multiclusterapp.go
- pkg/controllers/managementuserlegacy/helm/common/common.go
- pkg/controllers/managementuserlegacy/helm/controller.go
- pkg/controllers/managementuserlegacy/monitoring/clusterHandler.go
- pkg/controllers/managementuserlegacy/monitoring/operatorHandler.go
- pkg/controllers/managementuserlegacy/monitoring/projectHandler.go
- pkg/monitoring/monitoring.go
Problem:
When we install an app using Helm install, we pass all user provided answers as args to Helm's `--set` which changes will change a value of a quoted string `"true"` to a boolean `true` and break if the app expects a quoted string.
Solution:
Pass the answers that should keep the quoted string type as args to Helm's `--set-string`. Since both changing to the correct type and preserving the value as a quoted string are desirable outcomes depending on the situation, it should be up to the user to decide. For that reason the answers has been split into `answers` (keeps current behavior) and `answersSetString` (keeps its quoted string type). The expectation from the UI perspective is that the user will be able to choose which flag to use (A checkbox next to each answer text field …
> [master] Fix Helm changing app answers types

- pkg/auth/providers/keycloakoidc/keycloak_client.go
- pkg/auth/providers/keycloakoidc/keycloak_provider.go
**Issue**
https://github.com/rancher/rancher/issues/32920
**Problem**
` b, err := ioutil.ReadAll(resp.Body)` does not check for nil error after it
401 errors are being returned nil stead of just returning the error after `k.getFromKeyCloak`
**Solution**
Add nil check 
Return all errors if they exists after `k.getFromKeyCloak` is called.
> [keycloak oidc] Add nil check, return errors

- pkg/crds/provisioningv2/crds.go
`
2021/06/14 12:16:51 [ERROR] Reconciler error: cannot find any versions matching contract "cluster.x-k8s.io/v1alpha4" for CRD rkeclusters.rke.cattle.io as contract version label(s) are either missing or empty 
`
> add contract labels for rkeclusters.rke.cattle.io

- pkg/api/norman/server/managementstored/setup.go
- pkg/api/norman/store/catalog/store.go
- pkg/auth/api/user/user_actions.go
- pkg/auth/api/user/user_store.go
- pkg/data/management/role_data.go
Earlier added the check to avoid RestrictedAdmin editing Admin user. But this check is not needed since any user having "manage users" permissions can edit an Admin user.
Since RestrictedAdmin can manage users, they can update the globalAdmin and other admin users.
This PR is removing these checks, also this will avoid the GlobalRoleBinding CRD issue when MCM is disabled.
https://github.com/rancher/rancher/issues/33125
> RestrictedAdmin can manage admin user and also unreverting restrictedAdmin feature 

- package/run.sh
this setting is no longer in use, its last reference was removed in
https://github.com/rancher/rancher/commit/c08790d40a7565f6e64b1b942ac625fab41fa92f#diff-d0dab9599d947b7177a6ef7453f6ccc55151b7c70d52ad2ada1ba78caa438093L58
> remove outdated AGENT_IMAGE setting

- Dockerfile.dapper
- package/Dockerfile
- package/Dockerfile.agent
- package/jailer.sh
Support for SUSE BCI
Removed Leap 15.3 repo
All packages are now available via the BCI repository hence the Leap
15.3 repo added temporarily to support migration can now be removed.
Explicitly requesting gawk
awk is installed via the package gawk which is available via
patterns-base-minimal_base. When moving away from Leap 15.3 repo
that got lost hence we have to explicitly call its installation.
Explicitely call glibc-devel installation
Added glibc-devel-static to buld rancherd
Moved to SLE BCI image and repository
Use zypper internals
Use zypper internal product and architecture handling instead of hardcoding
them in repository URL. This will facilitate easy handling of newly
available versions.
Do not run 'zypper update'
In first attempt of translating from Ubuntu to SUSE there was a …
> Patchset to support SLE BCI

- pkg/jailer/jailer.go
`jailer.sh` script output is now logged not only when the script succeeds and is now at TRACE level instead of DEBUG (to prevent potentially sensitive information from being logged).
> Include output from jailer.sh to log if it fails

- chart/templates/deployment.yaml
Solves: https://github.com/rancher/rancher/issues/33133
Tested with `--set replicas=1`, and `--set replicas=3` achieving the desired outcome of helm waiting in both scenarios.
A further `helm upgrade` with `--set replicas=1` created a new Rancher pod before terminating the running pod.
> [chart] Set maxUnavailable: 0 if replicas=1 to allow helm to wait

- chart/templates/ingress.yaml
- chart/values.yaml
Our TLS secret is used by different tools and it would help us to have the possibility to configure the secret used by the ingress.
> Configurable Helm chart TLS secret name

- pkg/controllers/dashboard/fleetcharts/controller.go
https://github.com/rancher/fleet/issues/419
During the `cattle-fleet-system` namespace migration we need to run uninstall to make sure the previous release in old namespace is removed. The uninstall operation can't be run in parrallel due to the issue above.
> Add lock to uninstall to avoid launching multiple uninstall pod

- Dockerfile.dapper
- package/Dockerfile
- package/Dockerfile.agent
With the latest revision of the SLE BCI the repository is pre-configured
within the image hence no need to add it via the "zypper addrepo"
instructions.
> Remove instructions to add BCI repo

- chart/templates/deployment.yaml
- chart/values.yaml
This PR allows a configurable topologyKey. Our k8s nodes are located in different racks, each rack contains multiple nodes. We wanted to make sure only one instance of rancher runs within a rack.
> Configurable topologyKey

- pkg/api/steve/catalog/types/rest.go
- pkg/catalogv2/system/system.go
- pkg/controllers/dashboard/fleetcharts/controller.go
- pkg/controllers/dashboard/systemcharts/controller.go
https://github.com/rancher/rancher/issues/32560
https://github.com/rancher/rancher/issues/33203
Add force-adopt flag so that it can adopt crd resource that were previously installed in `fleet-system`. This can help migrating fleet-crd chart from `fleet-system` to `cattle-fleet-system`.
> Add adopt and change fleet-crd to cattle-fleet-system

- pkg/api/norman/store/cluster/cluster_store.go
Issue https://github.com/rancher/rancher/issues/27306
Issue https://github.com/rancher/rancher/issues/30628
Issue https://github.com/rancher/rancher/issues/33128
Related to issue comment, https://github.com/rancher/rancher/issues/27306#issuecomment-832985239, the previous fix were not working fine on edge cases. When a cluster has been updated (updating rancherKubernetesEngineConfig.cloudProvider.vsphereCloudProvider.virtualCenter data), eventually the changes where not propagated properly to all k8s nodes. Also at affected nodes, the rancher agent became stopped without automatic recover. If rancher agent is manually run at affected nodes, the cluster use to recover itself. Similar behaviour observed for issues, https://github.com/rancher/rancher/issues/30628, …
> [2.5] Fix to properly remove vSphere vCenter server entries

- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_provider.go
**Issue**
https://github.com/rancher/rancher/issues/33036
https://github.com/rancher/rancher/issues/32920
**Problem**
Access token is being passed as search type resulting in `invalid character 'B'` error
Refetch group principals was not implemented
**Solution** 
Pass in the correct values to `getFromKeyCloakByID` so that the auth token for the request is correctly
Refactor out the new provider and get user info code from the `LoginUser` so it can be reused to refetch the group values
> Complete refetch group principals method

- pkg/data/management/kontainerdriver_data.go
This PR is a 2.5 back-port of [this one](https://github.com/rancher/rancher/pull/33138)
> [2.5] Update oke kontainer engine driver v1.7.0

- pkg/api/norman/customization/aks/listers.go
- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- pkg/client/generated/management/v3/zz_generated_aks_status.go
- pkg/controllers/management/aks/aks_cluster_handler.go
It is possible to create an AKS cluster with RBAC disabled. In order to
display a warning message to users when RBAC is disabled, it status of
RBAC is put on the status of the cluster.
Also, the aksListClusters proxy endpoint also includes whether the RBAC
is enabled for each cluster. This would allow a warning message to be
displayed when registering AKS clusters.
Issue:
https://github.com/rancher/rancher/issues/27670
> Check RBAC status of an AKS cluster

- pkg/cluster/private_registry.go
Issue #27306
Issue #30628
Issue #33128
Required by PR https://github.com/rancher/rancher/pull/33166
When using private registry with auth, Rancher is creating/updating the `cattle-system/cattle-private-registry` secret containing `.dockerconfigjson`,  to be used by rancher cluster and node agents to be able to pull images. This secret is not working properly due to `.dockerconfigjson` is generated in a bad format. This issue was "hided" due to rancher cluster and node agents can't pull images by themselves config, but at the end they are able to use the cluster level private registry config.
This PR updates the `GeneratePrivateRegistryDockerConfig` function to use proper k8s secret `.dockerconfigjson` format so rancher cluster and node agents are able to pull docker image  by themselves …
> [2.5] Fix rancher agent docker auth config when using private registry

- app/kontainerdriver_data.go
This PR is a 2.4 back-port of this PR:[update oke kontainer engine driver v1.7.0](https://github.com/rancher/rancher/pull/33138)
> [2.4] Update oke kontainer engine driver v1.7.0

- go.mod
- go.sum
- pkg/client/generated/project/v3/zz_generated_metadata_config.go
- pkg/client/generated/project/v3/zz_generated_prometheus.go
- pkg/client/generated/project/v3/zz_generated_prometheus_spec.go
- pkg/client/generated/project/v3/zz_generated_remote_write_spec.go
- pkg/client/generated/project/v3/zz_generated_thanos_spec.go
This change is necessary since https://github.com/rancher/charts/pull/1274 bumped the Prometheus Operator APIs used in Monitoring V2.
Accordingly, we need to bump Rancher to prevent the packaged Monitoring V1 controllers from overwriting newly introduced fields for ServiceMonitors, Prometheis, Alertmanagers, and PrometheusRules (this has introduced weird edge cases in the past).
Related Issue: https://github.com/rancher/rancher/issues/32519
> Bump Prometheus Operator APIs to v0.48.0

- chart/templates/post-delete-hook-cluster-role.yaml
- chart/templates/post-delete-hook-psp.yaml
Backport of the PR https://github.com/rancher/rancher/pull/33023
Issue: https://github.com/rancher/rancher/issues/33348
This fix was already backport to the `release/v2.5` branch: https://github.com/rancher/rancher/pull/33069
But we have a dedicated branch `release/v2.5.9` for the coming release rancher:`v2.5.9`, so we need to backport this fix to `release/v2.5.9`.
> [2.5.9] add podSecurityPolicy to the post-delete-hook

- pkg/auth/providers/keycloakoidc/keycloak_client.go
**Issue**
https://github.com/rancher/rancher/issues/33356
https://github.com/rancher/rancher/issues/33352
**Side Note**
The original issues report a cluster member or owner not being able to search users after being added to those roles in Rancher. This is expected for this provider. If the user does not have get / list permissions in keycloak for users and groups, they will not be able to search those from keycloak. 
**Problem**
403 response is not returning an error so the empty response body was causing errors as it was trying to be processed
**Solution**
Add a case statement for 403 responses and create an api error reponse using the keycloak response status as the value.
> [keycloak oidc] Add error message for 403 errors

- go.mod
- go.sum
- pkg/api/norman/customization/cluster/validator.go
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/kontainer-engine/drivers/gke/gke_driver.go
Backport of https://github.com/rancher/rancher/pull/33318
Depends on https://github.com/rancher/rancher/pull/32502 since gke-operator changes depend on norman update
> Only send PrivateClusterConfig for private clusters

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/kubectl/kubectl.go
- pkg/settings/setting.go
- pkg/systemtemplate/template.go
Issue https://github.com/rancher/rancher/issues/27306
Issue https://github.com/rancher/rancher/issues/30628
Issue https://github.com/rancher/rancher/issues/33128
Requires PR https://github.com/rancher/rancher/pull/33165
The root cause of these issues seems to be related with the way that rancher agents are updated. Eventually, the rancher agent becomes updated in the middle of a node plan execution, making that the node plan execution aborts and the rancher agent is never restarted. 
This PR add the option to check that the `cattle-node-agent` daemonset has been properly updated and rollout, before continue with the cluster update. This is assuring that the rancher agent is updated and running before the cluster provision to avoid its updated during a node plan execution. This also add …
> [2.5] Wait for rancher agent daemonset rollout before update cluster

- pkg/controllers/management/aks/aks_cluster_handler.go
- pkg/controllers/management/gke/gke_cluster_handler.go
The Discovery field was mistakenly not set for AKS and GKE operators.
Issue:
https://github.com/rancher/rancher/issues/31592
> Add missing Discovery field to KEv2 operators

- chart/templates/NOTES.txt
- chart/templates/deployment.yaml
- chart/templates/secret.yaml
- chart/tests/deployment_test.yaml
- chart/values.yaml
- pkg/data/management/role_data.go
- scripts/chart/validate
- scripts/run
Adds ability to specify bootstrap password when rancher start. This adds a new Environmental variable `CATTLE_BOOTSTRAP_PASSWORD`.
1. For single docker install, user can specify password by passing `-e CATTLE_BOOTSTRAP_PASSWORD=password` to docker. If it is not specified, the password will generated randomly and user needs to grap it from docker logs.
2. For helm HA install, user can specify that with .Values.bootstrapPassword. The password will be stored in k8s secrets and there is instruction of how to retrieve password on note.txt after rancher is installed. Same that if user don't specify in values.yaml, it will be randomly generated.
> Generate a random password when rancher starts up

- go.mod
- go.sum
- pkg/api/norman/customization/cluster/validator.go
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/kontainer-engine/drivers/gke/gke_driver.go
GKE rolled out a change that denies setting PrivateClusterConfig on
Cluster objects if they are not using private nodes. Update
kontainer-engine (to handle GKEv1) and gke-operator (GKEv2) (TODO) to
conform to this.
Backport of https://github.com/rancher/rancher/pull/33379
https://github.com/rancher/rancher/issues/33277
> [v2.5.9] Only send PrivateClusterConfig for private clusters

- pkg/settings/setting.go
- This 2.5 branch was pointing to the latest Dashboard (2.6)
- Normally this should point to the latest 2.5.9 dev build, however the Dashboard hasn't branched for 2.5.9 and 2.5.8 has been released
- ui-dashboard-index, I think, by default, is only used in builds that aren't releases (pkg/settings/setting.go IsRelease)
- Builds that are releases use the correct v2.5.8 reference already (CATTLE_DASHBOARD_UI_VERSION v2.5.8)
> [2.5.9] Update default `ui-dashboard-index` setting

- pkg/settings/setting.go
- This 2.5 branch was pointing to the latest Dashboard (2.6)
- Normally this should point to the latest 2.5 dev build, however the Dashboard hasn't branched for 2.5.9 and 2.5.8 has been released
- ui-dashboard-index, I think, by default, is only used in builds that aren't releases (pkg/settings/setting.go IsRelease)
- Builds that are releases already use the correct version (CATTLE_DASHBOARD_UI_VERSION v2.5.8)
> [2.5] Update default `ui-dashboard-index` setting

- pkg/settings/setting.go
Calico creates the namespaces `calico-system` and `tigera-operator`. These namespaces are not part of a project and therefor marked as user namespace. They should be in the system project automatically instead.
Issue: https://github.com/rancher/rancher/issues/33483
> Automatically add RKE2 calico namespaces to system project

- pkg/auth/providers/keycloakoidc/keycloak_client.go
- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_provider.go
**Issue**
https://github.com/rancher/rancher/issues/33314
**Problem**
Access token was expiring and never getting refreshed
**Solution**
Utilize the oauth2 library to auto refresh the token when needed. 
- Secret is now storing all token values instead of only the access token
- Secret is being unmarshalled to be used as the token for the aouth2Config.TokenSource
- Secret is being unmarshalled and used for the creation of the keycloak client using the oauth2config client so that the token will be refresh if needed each time the client is created.
> Add refresh token support for oidc provider and keycloak client

- pkg/auth/providers/keycloakoidc/keycloak_provider.go
**Issue**
https://github.com/rancher/rancher/issues/33337
**Problem**
When a user logs in, their group information is collected from the id_token. This group information is only the name of the group they belong to. To search a specific group with the keycloak api, you have to have the group id, which is not provided on the id_token. Group principals are then added to the user using the group name as part of the principal id in rancher. When a user executes a group/user search after logging in (if they have the keycloak permissions to do so), each result returned does have the ID value included with it. If a principal was added from the search, the ID value was being used as part of the principal id in rancher. This means if a group is added by an admin, and a user with that group …
> [keycloak oidc] Change from group id to group name for searched group principals

- pkg/controllers/managementuser/helm/common/common.go
Issue https://github.com/rancher/rancher/issues/29272
Update kustomize config to not add `io.cattle.field/appId` label as selector to k8s service and networkPolicy
> [2.5] Updated kustomize config to manage io.cattle.field/appId label on apps deployment

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/client/generated/management/v3/zz_generated_gke_node_config.go
Backport of https://github.com/rancher/rancher/pull/33502
https://github.com/rancher/rancher/issues/33458
> [v2.5] Bump gke-operator to 1.1.1-rc7

- pkg/controllers/provisioningv2/cluster/controller.go
- pkg/data/management/role_data.go
The webhook adds a creatorIDAnn to the provisioning cluster so the controller will copy that over to the v3 cluster and drop the annotation from the  provisioning cluster. 
Add permissions for a standard user to create  provisioning clusters and any rke-machine-config.cattle.io
> Add creatorID anno and provisioning cluster perms

- pkg/app/utils.go
- pkg/controllers/management/auth/project_cluster_handler.go
If the creatorID annotation was missing from the local cluster object,
then Rancher would skip creating the System and Default projects. After
this change, these projects will get created regardless of the
existence of the creatorID annotation.
Also, when `app.EnsureAppProjectName` was called in preparation for
installing an app, it reassigns the namespace to the project if the
namespace annotation is not the expected projectID. This change does not
reassign the cattle-system namespace in such cases. This is to attempt
to keep the cattle-system namespace in the host cluster's tenant System
project.
Issues:
https://github.com/rancher/rancher/issues/33053
https://github.com/rancher/rancher/issues/32149
> Handle System/Default projects for hosted Rancher

- go.mod
- go.sum
- pkg/client/generated/project/v3/zz_generated_metadata_config.go
- pkg/client/generated/project/v3/zz_generated_prometheus.go
- pkg/client/generated/project/v3/zz_generated_prometheus_spec.go
- pkg/client/generated/project/v3/zz_generated_remote_write_spec.go
- pkg/client/generated/project/v3/zz_generated_thanos_spec.go
Backports https://github.com/rancher/rancher/pull/33333.
Related Issue: https://github.com/rancher/rancher/issues/33351
> [2.5] Bump Prometheus Operator APIs to v0.48.0

- package/Dockerfile.agent
With the switch to SLE Base Container the sysstat dependency
has been temporarily removed as it had excessive dependencies, which
have now been fixed.
> Dockerfile.agent: readd sysstat

- pkg/rkenodeconfigserver/nodeserver.go
https://github.com/rancher/rancher/issues/33494
We made all roles required in a cluster, but this conditional is still only applied to worker. We should error out if not all roles are registered in the cluster, so the logging is consistent with the message in the UI for the user.
> Return err to node if no applied cluster config

- chart/templates/deployment.yaml
- package/entrypoint.sh
- package/jailer.sh
The new SLE image requires update-ca-certificates be run before
additional trusted CAs are recognized. Therefore, the command is
run prior to launch Rancher.
In addition, the location of the mounted certificate is changed to the
location specified in the docs: /etc/pki/trust/anchors/
Finally, the jailer also copies the certificate information to /etc/ssl
instead of /etc/ssl/certs because the Go libraries expect the certs to
be there.
Issue:
https://github.com/rancher/rancher/issues/33398
> Run update-ca-certificates before launching Rancher

- pkg/api/norman/customization/aks/listers.go
This change optionally enables filtering by region when listing ASK
virtual networks. It is backwards compatible: if region is not set, it
defaults to the old behavior of listing all virtual networks. Also adds
"location" as an attribute returned in the list of vnets. This isn't
functionally necessary for the UI but it's nice for developers to be
able to validate the results.
https://github.com/rancher/rancher/issues/33517
> Filter by region in /meta/aksVirtualNetworks

- pkg/api/norman/customization/aks/listers.go
Add the AKS cluster's location to the list of cluster objects returned
by /meta/aksClusters. This can be used by the UI to set the
ResourceLocation field when importing a cluster.
https://github.com/rancher/rancher/issues/33534
> Add Location to /meta/aksClusters list

- pkg/api/steve/aggregation/aggregation.go
For #32117
Currently requests to `/principals/local%3A%2F%2Fu-lr7ts?sort=name` (`/principals/local://u-lr7ts?sort=name`) respond with redirect (301) to `/principals/local:/u-lr7ts?sort=name` which in turn responds with 500 (error message is `users.management.cattle.io "" not found`).
The fix is to change all mux-es in the API handler chain to not redirect requests containing multiple `/`s which is a default mux behavior.
Note that this is a regression as v2.5.8 release handles such requests correctly.
Also, note browser caches 301 HTTP responses, so if testing the fix on users the issue was reproduced previously, make sure to clear browser's cache beforehand.
**Edit after additional investigation:**
Only URL-encoded requests (like `/principals/local%3A%2F%2Fu-lr7ts?sort=name` and NOT …
> Fix API redirect for paths with //

- pkg/auth/requests/filter.go
- pkg/clusterrouter/factory.go
- pkg/clusterrouter/proxy/proxy_server.go
- pkg/clusterrouter/router.go
- pkg/controllers/managementuser/rbac/crtb_handler.go
- pkg/controllers/managementuser/rbac/globalrole_handler.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/impersonation/impersonation.go
- pkg/k8sproxy/k8s_proxy.go
- pkg/multiclustermanager/routes.go
Create an impersonator service account when cluster and project role
templates are created on downstream clusters. Check for it and create it
upon receiving a proxy request if necessary.
> Add impersonator account on downstream clusters

- pkg/clusterrouter/factory.go
- pkg/clusterrouter/proxy/proxy_server.go
- pkg/clusterrouter/router.go
- pkg/controllers/managementuser/rbac/crtb_handler.go
- pkg/controllers/managementuser/rbac/globalrole_handler.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/controllers/managementuser/rbac/prtb_handler.go
- pkg/impersonation/impersonation.go
- pkg/k8sproxy/k8s_proxy.go
- pkg/multiclustermanager/routes.go
Create an impersonator service account when cluster and project role
templates are created on downstream clusters. Check for it and create it
upon receiving a proxy request if necessary.
Backport of https://github.com/rancher/rancher/pull/33591
> [v2.5] Add impersonator account on downstream clusters

- pkg/auth/providers/keycloakoidc/keycloak_client.go
- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_client.go
- pkg/auth/providers/oidc/oidc_provider.go
- scripts/ci
**Issues** 
https://github.com/rancher/rancher/issues/33337
https://github.com/rancher/rancher/issues/33314
https://github.com/rancher/dashboard/issues/3406 Scope needed to be space separated and allow for "openid" scope to be passed in instead of set in the client always. 
Certificate and Key were not being added to the context in all situations
**Solution**
Groups were not showing up on refresh because the Keycloak api relies on IDs, but we only have the name for groups. To resolve this, I am using the basic group search endpoint and then filtering down the result to only the value that has a matching name. group names are unique in keycloak, even if its a nested group. Note: since we only return 1 principal at a time for groups, we are not able to add all of the children groups if you …
> [Keycloak oidc] Various Fixes 

- go.mod
- go.sum
Problem:
We should be able to filter harvester clusters by the provider detector.
Solution:
Bump Kubernetes provider detector to v0.1.3 to support harvester provider detector.
Related Issue:
https://github.com/rancher/dashboard/issues/3466
> Bump kubernetes provider detector

- pkg/data/management/machinedriver_data.go
This MR updates [OCI Node Driver](https://github.com/rancher-plugins/rancher-machine-driver-oci) to version `v1.1.0`, which has support for specifying the number of CPUs and the amount of memory of OCI [flexible shapes](https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm).
Related Issue:
https://github.com/rancher-plugins/rancher-machine-driver-oci/issues/7
> Update OCI node driver to v1.1.0.

- app/machinedriver_data.go
This PR is a 2.4 back-port of [this PR](https://github.com/rancher/rancher/pull/33631).
> [2.4] Update OCI node driver to v1.1.0.

- pkg/data/management/machinedriver_data.go
This PR is a 2.5 back-port of [this PR](https://github.com/rancher/rancher/pull/33631).
> [2.5] Update OCI node driver to v1.1.0.

- go.mod
- go.sum
- pkg/controllers/provisioningv2/controllers.go
- pkg/controllers/provisioningv2/rke2/secret/secret.go
- pkg/data/management/role_data.go
Problem:
The secret created for cloud creds is created in a namespace a user
doesn't normally have access to
Solution:
Add permissions for the secret in the namespace based off the creatorID
anno the webhook will add when the secret is created
Reordered user roles by apiGroup and added the perm `addRule().apiGroups("catalog.cattle.io").resources("clusterrepos").verbs("get", "list", "watch").` which is required for provisioning v2 cluster templates
> Add secret controller for cloud cred

- pkg/controllers/dashboard/hostedcluster/controller.go
**Problem:**
Prior, the old eks-operator app remained and deleting
it would cause the eks-operator deployment to get removed.
This caused both apps to be deleted and edits to no longer
work. Editing an EKS cluster would not cause the app to
redeploy either.
**Solution:**
Now, the old eks-operator app is deleted
before installing the new app. Old eks-operator app refers
to the app of type apps.project.cattle.io. Now, in v2.6+
an app of type apps.catalog.cattle.io is installed instead.
**Issue:**
https://github.com/rancher/rancher/issues/31592
> Remove legacy kev2 apps before install

- scripts/promote-docker-image.sh
https://github.com/rancher/rancher/issues/33633
We need to test this functionality and this allows us to use `rancher/rancher:donotuse` to use as tag to test and still indicate for others they cant be used. I wanted to add `testing` but that indicates it might be a testing image or something.
I guess ideally this should be a different org but this is what we have today.
> Add donotuse tag for testing Docker image promote

- pkg/controllers/dashboard/hostedcluster/controller.go
Without this, the cluster change handler segfaults the first time it
tries to look up the legacy operator app.
https://github.com/rancher/rancher/issues/33693
> Initialize app cache in hostedcluster controller

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
Take over of https://github.com/rancher/rancher/pull/33652 to fix conflict.
issue: https://github.com/rancher/rancher/issues/33446
> Bump aks-operator to 1.0.1-rc17

- pkg/api/norman/customization/cluster/actions_kubeconfig.go
We can not request and create cluster token if cluster local endpoint is
enable but generating token setting is false. The token will be
initialized through CLI.
https://github.com/rancher/rancher/issues/33474
> Do not request cluster token if token setting is false

- pkg/auth/providers/local/local_auth_provider.go
**Problem:**
Prior, the WrapAPIError function was being used which set the
Cause field as the underlying error causing the issue. When
the Cause field gets set, it is automatically logged. In this
case the error is very specific to the package it comes from
and can cause confusion. Specifically it has caused confusion
because the error mentions a hashed password which is being
mistakenly interpreted as referring to the token hashing
feature.
**Solution:**
Now, the WrapAPIError function is no longer being
used and the underlying error will only be logged if debug is
enabled.
> Only log cause if debugging is enabled

- pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
- tests/integration/pkg/tests/custom/custom_test.go
The system-agent-installer passes the node labels as "labels." Rancher
was looking for the "label" entry in the secret data and was missing the
labels that were passed. Now, Rancher will look for labels under the
"labels" entry in the secret and labels are added to the node
successfully.
Issue:
https://github.com/rancher/rancher/issues/33455
> Use "labels" for custom node labels

- chart/templates/deployment.yaml
- package/entrypoint.sh
A previous change moved the ca-additional.pem files to
/etc/pki/trust/anchors/ diretory. However, while this does allow the
additional trusted CAs to be detected in some instances, other
applications (like git) read the SSL_CERT_DIR environment variable.
Since this variable is set in the Rancher container, the additional
trusted CAs should also be put in the referenced directory
(/etc/rancher/ssl) and c_rehash run on startup.
Issues:
https://github.com/rancher/rancher/issues/33398
https://github.com/rancher/rancher/issues/31846#issuecomment-885053870
> Also run c_rehash on startup

- pkg/controllers/provisioningv2/rke2/planner/controller.go
- pkg/provisioningv2/rke2/planner/etcdcreate.go
- pkg/provisioningv2/rke2/planner/planner.go
If a user created a cluster with etcdSnapshotCreate set, then the
planner would try to create a snapshot before the node was provisioned.
Now, the planner will wait until the node is provisioned before
attempting to take a snapshot.
Issues:
https://github.com/rancher/rancher/issues/32874
https://github.com/rancher/rancher/issues/32391
> Wait for etcd snapshot if node is not provisioned

- pkg/apis/management.cattle.io/v3/authn_types.go
- pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- pkg/auth/providers/keycloakoidc/keycloak_client.go
- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_actions.go
- pkg/auth/providers/oidc/oidc_provider.go
- pkg/client/generated/management/v3/zz_generated_key_cloak_oidcconfig.go
- pkg/client/generated/management/v3/zz_generated_oidc_config.go
- pkg/client/generated/management/v3/zz_generated_private_registry.go
- pkg/client/generated/management/v3/zz_generated_rke_system_images.go
**Issue(s)**
https://github.com/rancher/rancher/issues/33337
https://github.com/rancher/rancher/issues/33314
https://github.com/rancher/rancher/issues/33782
**Problems**
1. A user's groups do not include parent groups
2. When token is expired,  the resp from a get request is nil so panic occurs when resp.statuscode is hit
3. Scope has empty scopes in it occasionally causing invalid scope error
4. Logging vs error messages were very inconsistent
**Solution**
1. Add support for additional mapper to be added to the keycloak client, so when the userInfo is returned, the full path results are included in the response. The full paths are then parsed and included in a user's group principals
2. The statusCode was not being used in a meaningful way, so I removed it. The error that is returned …
> [keycloak oidc] Add nested group support, fix 500 error on nil response

- scripts/version
Helm3 now requires semver2 for chart versions.  Leading zeros are prohibited in semver2.  This can cause some builds to fail when the commit hash starts with a zero.
> fixed chart version having leading zeros

- chart/templates/NOTES.txt
- pkg/data/management/role_data.go
- If the user supplied their own password, don't set `mustChangePassword` so the UI won't force them to change it.
- Show a more obvious visual block to make it easier to find the bootstrap info among all the noise `docker run ...` spits out
- Use go-template with internal base64 decode instead of piping and requiring base64 to be present in the commands
- Show the password on it's own line separate from the URL.  The UI will show the user instructions to grep it easily if they're already at the login screen but lacking the password.
- Don't log the password if the user provided it (but this was already done an hour ago..)
- If the user provided password is `admin`, the user is opting-in preserve existing 2.5 behavior (Don't show `?setup=admin` because it's redundant, …
> Boostrap password tweaks

- go.mod
- go.sum
- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/binding.go
Pull in the updated api server so lists don't fail with a 403
Remove the owner reference for roleBindings created for the provisioning cluster. The CRTB lives in another namespace so it can't be used as the owner. 
Update the naming convention of the roleBinding to be unique based on the CRTB name
> Add auth provisioning permissions

- package/Dockerfile
- pkg/settings/setting.go
- The dashboard has branched 2.6 from master
- This change ensures both the dashboard embedded and served bits reference the 2.6 bits
- When rancher branches for 2.6 I'll come back and change `UIDashboardIndex` in master to point to dashboard latest again
- When there are rancher 2.6 RCs `CATTLE_DASHBOARD_UI_VERSION` will need updating by the release captain as per usual
> Update Dashboard references to handle 2.6 branch

- pkg/data/management/kontainerdriver_data.go
This PR updates the OKE cluster driver to version v1.7.1.
This release includes updated support to allow choosing a private control plane for a managed oke kubernetes cluster.
related merges
https://github.com/rancher-plugins/kontainer-engine-driver-oke/pull/42
https://github.com/rancher-plugins/kontainer-engine-driver-oke/pull/43
> Update oke kontainer engine driver v1.7.1

- pkg/controllers/managementuser/rbac/namespace_handler.go
Problem:
The warn message will log multiple times on startup or new namespace
creation with conflict errors
Solution:
Wrap the log to check the type of error before logging. The framework
normally hides these errors and retries so this should not log with a
conflict error
> Check error type before logging

- chart/Chart.yaml
- cmd/rancherd/chart/Chart.yaml
Rancher does not yet run on kubernetes 1.22, so ensure the charts comply
with that.
https://github.com/rancher/rancher/issues/33777
> Set kubeVersion range in rancher charts

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
Backport of https://github.com/rancher/rancher/pull/33809
https://github.com/rancher/rancher/issues/33458
> [v2.5] Update gke-operator to 1.1.1-rc10

- pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
- pkg/provisioningv2/rke2/configserver/custom.go
- pkg/provisioningv2/rke2/planner/planner.go
If the --address and/or --internal-address flags were passed to the
system-agent-installer for a custom node, then result was ignored by
Rancher.
After this change, Rancher will look for these values in the config
secret and pass them to the config when bootstrapping the node.
Issue:
https://github.com/rancher/rancher/issues/33404
> Add node-ip and node-eternal-ip to config

- pkg/controllers/management/auth/manager.go
Issue: 
- #33814 
This PR is for a simple fix that adds the namespace to all the desiredRBs; this way the logs are outputting correct information about RoleBinding creation.
> [release/v2.5] Fix logs around RoleBinding creation

- pkg/api/steve/clusters/clusters.go
- pkg/api/steve/clusters/kubeconfig.go
- pkg/api/steve/clusters/types.go
Need to port over action `generateKubeconfig` from `v3/clusters` to `v1/management.cattle.io.clusters` since `v3/cluster` api will be disabled when running with multi-cluster-management=false and there is no equivalent api to deal with that. 
This requires UI to switch to using `/v1/management.cattle.io.clusters` api to generate kubeconfig. When multi-cluster-management is enabled, it will just redirect to `/v3/clusters` api.
https://github.com/rancher/rancher/issues/33687
> Add v1 steve api for generateKubeconfig api

- pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
- tests/integration/pkg/tests/custom/custom_test.go
The taints for custom clusters are passed as `key=value:Effect`.
However, the parsing of the taint strings were expecting something of
the form `key:value:Effect`.
This change correctly parses the taints for custom clusters.
Issue:
https://github.com/rancher/rancher/issues/33419
> Correctly parse taints for custom clusters

- pkg/data/management/kontainerdriver_data.go
This PR is a 2.5 back-port of this one [Update oke kontainer engine driver v1.7.1](https://github.com/rancher/rancher/pull/33772)
> [2.5] Update oke kontainer engine driver v1.7.1

- app/kontainerdriver_data.go
This PR is 2.4 back-port of this one: [Update oke kontainer engine driver v1.7.1](https://github.com/rancher/rancher/pull/33772)
> [2.4] Update oke kontainer engine driver v1.7.1

- pkg/controllers/provisioningv2/rke2/dynamicschema/dynamicschema.go
- pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
- pkg/data/management/role_data.go
Problem:
The dynamic rbac for the new resources is based off clusterName, if an object does not have a clusterName referenced then rbac will skip the object and not grant permissions. 
Solution:
Add clusterName on the dynamic machineTemplates as they are created so permissions will be granted. 
> Add clusterName to machineTemplates for dynamic permissions

- pkg/controllers/management/clusterprovisioner/provisioner.go
When check for upgrade we assume the same k8s version will have the same
systemImages.  This allows us to add new images (like the ACI ones) and
that won't trigger an upgrade.
> Don't consider systemImages from kdm to detect upgrade

- pkg/api/norman/store/service/service.go
https://github.com/rancher/rancher/issues/33085
Although `dnsRecord` does not seem to be exposed to the user in the UI, the automated tests that use this type were failing.
> Apply SingleStack default to dnsRecord

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/authprovisioningv2/binding.go
Problem:
The roleBindings for provisioning clusters were not being cleaned up
when the CRTB that triggered the creation was deleted
Solution:
Add a cleanup in the CRTB remove finalizer to go find all dependent
roleBindings and delete them.
> Cleanup roleBindings for provisioning clusters

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/authprovisioningv2/binding.go
Problem:
The roleBindings for provisioning clusters were not being cleaned up
when the CRTB that triggered the creation was deleted
Solution:
Add a cleanup in the CRTB remove finalizer to go find all dependent
roleBindings and delete them.
> [2.6] Cleanup roleBindings for provisioning clusters

- pkg/controllers/management/aks/aks_cluster_handler.go
Before this change, the AKS controller in Rancher would try to get the
service account by using the kubeconfig from AKS. This caused an issue
if any additional CAs are needed (like in a proxy setup).
This fix will ensure that the additional CAs are used when getting the
service account and resolve the unsigned cert errors.
Issue:
https://github.com/rancher/rancher/issues/31846
> Use additional CAs when getting AKS service account

- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_provider.go
**Issue**
https://github.com/rancher/rancher/issues/33852
**Problem**
There is nothing in the logs to indicate if the original token was being used, or if a fresh token had been requested
**Solution**
Add a log message that indicates a refresh will be attempted if the token is no longer valid
> Add oidc log message to indicate token refresh

- pkg/rancher/migrations.go
- pkg/rancher/rancher.go
https://github.com/rancher/rancher/issues/33743
With v2.6.0 rancher is shipping a new frontend.  Any user that is on the old ember ui while rancher is upgraded will not be directed to the new dashboard until they choose to logout.  This could cause some confusion after the upgrade.
When we upgrade to v2.6.0 we need to invalidate all the ember ui tokens.  This will force a logout and send all the users to a central point allowing the frontend to redirect them.  When the rancher app starts we will invalidate all the frontend tokens and then create a config map with the current rancher version.  On the next startup we will check for that configmap and as long as the stored version is greater than v2.6.0 we will not invalidate any tokens.
> [v2.6.0] ISSUE-33743 delete dashboard tokens on 2.6 upgrade

- pkg/controllers/management/aks/aks_cluster_handler.go
Issue:
https://github.com/rancher/rancher/issues/31846
> [Backport 2.6] Use additional CAs when getting AKS service account

- pkg/apis/rke.cattle.io/v1/etcd.go
Previously, the UI would put a blank ETCDSnapshotCreate object on the
cluster spec when the user wanted to create an on-demand snapshot. This
caused an issue where multiple on-demand snapshots could not be created
this way because the backend would not detect any changes (the
ETCDSnapshotCreate object would remain blank).
After this change, the UI will update the generation field when a new
on-demand snapshot should be created and the backend will detect this.
Issue:
https://github.com/rancher/rancher/issues/32391
> Add generation field to ETCDSnapshotCreate

- pkg/controllers/management/auth/role_template_lifecycle.go
- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/role.go
Problem:
roles not being cleaned up when a roleTemplate or cluster is deleted
Solution:
Add an owner reference to the cluster as this is more likely to get
deleted
Add a cleanup to the roleTemplate lifecycle to remove any dependent
roles
> Remove roles when roleTemplate is deleted

- pkg/controllers/management/auth/role_template_lifecycle.go
- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/role.go
Problem:
roles not being cleaned up when a roleTemplate or cluster is deleted
Solution:
Add an owner reference to the cluster as this is more likely to get
deleted
Add a cleanup to the roleTemplate lifecycle to remove any dependent
roles
> [2.6] Remove roles when roleTemplate is deleted

- pkg/controllers/provisioningv2/rke2/dynamicschema/dynamicschema.go
The status of a MachineTemplate was not being used and was causing
issues with backup/restore. Since this status was not being used, it is
removed.
Issue:
https://github.com/rancher/rancher/issues/33684
> Remove MachineTemplate status from CRD

- pkg/catalogv2/system/system.go
- pkg/controllers/dashboard/hostedcluster/controller.go
- pkg/settings/setting.go
- pkg/wrangler/context.go
Addressed an issue where aks/eks/gke chart is not redeployed/upgraded when cluster is changed. https://github.com/rancher/rancher/issues/31592
This has potential overhead calls to check helm releases because cluster is changed frequently and will be triggering controller code very frequently.
> Force to install charts when cluster is changed

- pkg/controllers/dashboard/clusterregistrationtoken/status.go
- tests/integration/pkg/tests/custom/custom_test.go
Noticed that the cattle label was missing from the insecure command for RKE2 registration for custom clusters.
https://github.com/rancher/rancher/issues/33977
> Adding missing label to the insecure command.

- pkg/controllers/dashboard/clusterregistrationtoken/status.go
An extra and incorrect CA checksum flag is being added to the windows registration command.
Issue: https://github.com/rancher/rancher/issues/33983
> Correcting CA checksum flag for RKE2 windows registration command.

- pkg/controllers/dashboard/clusterregistrationtoken/status.go
An extra and incorrect CA checksum flag is being added to the windows registration command.
Issue: https://github.com/rancher/rancher/issues/33983
> [backport 2.6] Correcting CA checksum flag for RKE2 windows registration command.

- pkg/provisioningv2/rke2/planner/planner.go
- pkg/provisioningv2/rke2/planner/s3args.go
Previously, enabling S3 config for etcd snapshots caused Rancher to
panic because of an uninitialized struct.
Additionally, Rancher expected the cloud credential for the S3
credentials to either be of a certain type or in a certain namespace.
This is no longer needed and the check for this has been removed.
Issue:
https://github.com/rancher/rancher/issues/33950
> Fix S3 support for etcd snapshots

- pkg/catalogv2/system/system.go
- pkg/controllers/dashboard/hostedcluster/controller.go
- pkg/settings/setting.go
- pkg/wrangler/context.go
This commit adds the ability to configure systemFeatureChart refresh
interval(interval to check and make sure system-chart are up-to-date).
Also it adds the ability to triggering redeploying operator chart if chart
is deleted manually and there is a cluster change event.
backport of https://github.com/rancher/rancher/pull/33879
#31592
> [2.6] Make sure aks/eks/gke chart are up-to-date

- scripts/package
When releasing assets to github, only files starting with `rancher-` are picked up: https://github.com/rancher/rancher/blob/release/v2.6/.drone.yml#L288
> Add rancher prefix to CSV scan results to attach to assets

- pkg/wrangler/context.go
Previously, the PeerManager in the wrangler context was not set. This
caused the cluster controllers to run on every node instead of in a
clustered/shard mode. The symptom of this was that too many v3.Nodes
were getting created when deploying RKE2/K3S clusters in an HA setup.
Now, the PeerManger will be set and the cluster controllers will run as
expected.
Issues:
https://github.com/rancher/rancher/issues/33991
https://github.com/rancher/rancher/issues/33020
> Set PeerManager to run in clustered mode

- pkg/settings/setting.go
- Following 2.6 branch master can now point back at rancher/dashboard master
- This has been done for UIDashboardIndex which is used for versions ending in `-head`
- The embedded version (CATTLE_DASHBOARD_UI_VERSION) can stay the same
> Update Dashboard reference to point to master

- chart/values.yaml
issue: https://github.com/rancher/rancher/issues/33986
`cattle-fleet-system` is the new namespace Fleet is installed in rancher v2.6, we need to add it to the `namespaceList` such that the post-delete-hook job will uninstall apps in this namespace 
`fleet-system` is removed because:
- it will not exist in a fresh installation of rancher v2.6
- and it will be cleaned up by Rancher in the case of upgrading Rancher from v2.5 to v2.6 
TODO:
> add cattle-fleet-system to the namespace list

- pkg/rancher/migrations.go
- pkg/rancher/rancher.go
https://github.com/rancher/rancher/pull/33849
https://github.com/rancher/rancher/issues/33743
> [v2.6.1] Forward Port: delete dashboard tokens on 2.6 upgrade

- tests/integration/suite/test_workloads.py
Relevant issue: https://github.com/rancher/rancher/issues/34016
> Fix workload rollback action test by reloading before actions

- tests/integration/suite/test_workloads.py
Backport of https://github.com/rancher/rancher/pull/34022
Relevant issue: https://github.com/rancher/rancher/issues/34016
> [2.6] Fix workload rollback action test by reloading before actions

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/impersonation/impersonation.go
Problem 1: When the cluster role for the impersonation service account
was created by the role template binding controller, it only added rules
for two basic authenticated groups and optionally a group derived from
the role template binding, and ignored potential groups the user is
associated with in an external provider. This meant that a user logging
in through an external provider would be blocked from impersonating
their service account due to insufficient permissions.
Solution 1: This change updates the role template binding controller to
get the true known groups for the user from the attribute lister.
Problem 2: If the user's Extras attributes changed, such as what happens
when a local user becomes associated with an external provider, the
roles' rules were never be updated. This …
> Update impersonation role based on user attributes

- scripts/package
#33995
remove the skipping of CRD charts which may contain images that need to be in the rancher-images.txt file for airgap
> [release/v2.6] remove the skipping of CRD charts

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/impersonation/impersonation.go
Problem 1: When the cluster role for the impersonation service account
was created by the role template binding controller, it only added rules
for two basic authenticated groups and optionally a group derived from
the role template binding, and ignored potential groups the user is
associated with in an external provider. This meant that a user logging
in through an external provider would be blocked from impersonating
their service account due to insufficient permissions.
Solution 1: This change updates the role template binding controller to
get the true known groups for the user from the attribute lister.
Problem 2: If the user's Extras attributes changed, such as what happens
when a local user becomes associated with an external provider, the
roles' rules were never be updated. This …
> [v2.5] Update impersonation role based on user attributes

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/impersonation/impersonation.go
Problem 1: When the cluster role for the impersonation service account
was created by the role template binding controller, it only added rules
for two basic authenticated groups and optionally a group derived from
the role template binding, and ignored potential groups the user is
associated with in an external provider. This meant that a user logging
in through an external provider would be blocked from impersonating
their service account due to insufficient permissions.
Solution 1: This change updates the role template binding controller to
get the true known groups for the user from the attribute lister.
Problem 2: If the user's Extras attributes changed, such as what happens
when a local user becomes associated with an external provider, the
roles' rules were never be updated. This …
> [v2.6] Update impersonation role based on user attributes

- pkg/controllers/managementuser/controllers.go
The impersonation mechanism needs these downstream resources cached.
Backport of https://github.com/rancher/rancher/pull/34045
https://github.com/rancher/rancher/issues/34042
> [v2.6] Register SA and ClusterRoles caches

- tests/validation/tests/v3_api/test_custom_host_reg.py
* ami was removed (?) from aws, updated to later version
* also allow `privileged` docker install of 2.6
> QA Automation: updating ami version, allow 2.6 docker installs

- pkg/controllers/managementapi/controllers.go
- pkg/controllers/provisioningv2/cluster/controller.go
Previously, the v1.Cluster indexer was created on the management plane,
but not on any of the followers. During sharding for the user management
plane, if the management plane was not selected, then the indexer would
not exist and could not be used. This would cause things like the
snapshotbackpopulate to not function.
Now, the indexer is created on startup so that every Rancher pod can
access it when necessary.
Related issue:
#32719
> Create a v1.Cluster indexer on startup.

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/binding.go
- pkg/controllers/management/authprovisioningv2/cluster.go
- pkg/controllers/management/authprovisioningv2/prtb.go
Problem:
When a user is added to a project through a PRTB they are not able to
see the provisioning cluster object
Solution:
Add a handler to create a role and binding in the provisioning cluster
namespace granting permissions to get the cluster object.
This adds an owner reference to the cluster for the role and binding
with a cleanup in the PRTB lifecycle on remove to remove the binding
when the PRTB is deleted.
> Add provisioning cluster permissions on PRTB

- chart/templates/_helpers.tpl
- chart/tests/deployment_test.yaml
Helm unittest suite is silently failing at Rancher v2.6.0-rc1 ci pipelines. The breaking change was introduced by a PR and hided by other PR:
* Merged PR https://github.com/rancher/rancher/pull/31988 was breaking the helm charts unittest. [ci log](https://drone-pr.rancher.io/rancher/rancher/14443/1/2)
* Merged PR https://github.com/rancher/rancher/pull/32749 was making silent fails (indent format issue) previous helm unittest issue. [ci log](https://drone-pr.rancher.io/rancher/rancher/17417/3/2) showed as `green` but  `chart/validate` stage is failing
```
...
-- chart/validate --
4260 | ==> Linting ../../build/chart/rancher
4261 | [WARNING] templates/ingress.yaml: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
4262 |   …
```
> [2.6] Fix helm unittest silent regression

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/binding.go
- pkg/controllers/management/authprovisioningv2/cluster.go
- pkg/controllers/management/authprovisioningv2/prtb.go
Problem:
When a user is added to a project through a PRTB they are not able to
see the provisioning cluster object
Solution:
Add a handler to create a role and binding in the provisioning cluster
namespace granting permissions to get the cluster object.
This adds an owner reference to the cluster for the role and binding
with a cleanup in the PRTB lifecycle on remove to remove the binding
when the PRTB is deleted.
> [2.6 backport] Add permissions for provisioning cluster from PRTB

- pkg/controllers/managementuser/networkpolicy/netpol.go
- pkg/controllers/managementuser/networkpolicy/register.go
Issue: 
- https://github.com/rancher/rancher/issues/33979
This PR is needed for 2 reasons:
- Ingress traffic from nodes to workloads was not making it through due to misconfigured hn-nodes NetworkPolicies for RKE1/2 clusters deployed with Calico CNI
- Labels not always getting added to Rancher managed NetworkPolicy resources. Added explicit setting of labels so that we always properly select NetworkPolicy resources for deletion when disabling PNI
> [release/v2.6] Fix host network policies for Calico CNI (RKE1/2)

- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/binding.go
- pkg/controllers/management/authprovisioningv2/role.go
- pkg/rbac/common.go
Problem:
Authv2 only gathers the rules on the roleTemplate, ignoring the
referenced roleTemplate field.
Solution:
Gather all rules for all referenced roleTemplates
https://github.com/rancher/rancher/issues/33998
> Gather all referenced roleTemplates on role create

- pkg/controllers/managementuser/rbac/impersonation_handler.go
If a user has no extra attributes, for instance a local user with no
groups, then the UserAttribute lister will not find the user. This is
expected and can be ignored, as the User lister has already found the
user.
https://github.com/rancher/rancher/issues/34076
> Ignore user not found in user attribute lister

- pkg/controllers/managementuser/rbac/impersonation_handler.go
If a user has no extra attributes, for instance a local user with no
groups, then the UserAttribute lister will not find the user. This is
expected and can be ignored, as the User lister has already found the
user.
Backport of https://github.com/rancher/rancher/pull/34117
https://github.com/rancher/rancher/issues/34076
> [v2.6] Ignore user not found in user attribute lister

- pkg/api/steve/additionalapi.go
- pkg/provisioningv2/rke2/configserver/custom.go
- pkg/provisioningv2/rke2/configserver/server.go
- pkg/provisioningv2/rke2/planner/planner.go
- pkg/provisioningv2/rke2/planner/store.go
rke2 windows install script needs a way to pull the rke2 version for the cluster so we can test RCs and general get data pushed down to the installer from KDM. As of today we force the Stable release and this let's us get around that.
> adding /v3/connect/cluster-info endpoint for windows rke2 installer

- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/binding.go
- pkg/controllers/management/authprovisioningv2/role.go
- pkg/rbac/common.go
Problem:
Authv2 only gathers the rules on the roleTemplate, ignoring the
referenced roleTemplate field.
Solution:
Gather all rules for all referenced roleTemplates
https://github.com/rancher/rancher/issues/33998
> [2.6 backport]Gather all referenced roleTemplates on role create

- pkg/controllers/provisioningv2/rke2/machinestatus/machinestatus.go
When a machine is being deleted, sometime the UI will show a status of
"waiting for machine to be defined." This is inaccurate for a machine
that is being deleted.
This change will display an accurate message in this case.
Issue:
https://github.com/rancher/rancher/issues/34235
> Add new status for machines that are being deleted

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/impersonation/impersonation.go
This change does three things:
1) Partially revert the refactor done in 8d413413 so that the service
account only needs to be retrieved once in total if it exists,
instead of as two steps in SetUpImpersonation and GetToken
2) Fix waitForServiceAccount to use the cache instead of the client
3) Add trace logs to help debug future caching problems
https://github.com/rancher/rancher/issues/34042
https://github.com/rancher/rancher/issues/34187
> Change impersonation service account retrieval

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/impersonation/impersonation.go
This change does three things:
1) Partially revert the refactor done in 8d413413 so that the service
account only needs to be retrieved once in total if it exists,
instead of as two steps in SetUpImpersonation and GetToken
2) Fix waitForServiceAccount to use the cache instead of the client
3) Add trace logs to help debug future caching problems
Backport of https://github.com/rancher/rancher/pull/34234
https://github.com/rancher/rancher/issues/34042
https://github.com/rancher/rancher/issues/34187
> [v2.6] Change impersonation service account retrieval

- pkg/controllers/management/authprovisioningv2/indexer.go
- pkg/controllers/provisioningv2/rke2/dynamicschema/dynamicschema.go
Problem:
rke-machine-config does not return a clustername becuase it does not
live in the expected locations on the object
Solution:
Update getObjectClusterNames to look for the group of the object and
then find the owner reference for the provisioning cluster. These
objects are dynamic so the switch won't work as there is no concrete
type and they don't have a spec so it can't be added there on creation.
https://github.com/rancher/dashboard/issues/3785
> Get clusterName from rke-machine-config

- pkg/controllers/management/authprovisioningv2/indexer.go
- pkg/controllers/provisioningv2/rke2/dynamicschema/dynamicschema.go
Problem:
rke-machine-config does not return a clustername becuase it does not
live in the expected locations on the object
Solution:
Update getObjectClusterNames to look for the group of the object and
then find the owner reference for the provisioning cluster. These
objects are dynamic so the switch won't work as there is no concrete
type and they don't have a spec so it can't be added there on creation.
https://github.com/rancher/dashboard/issues/3785
> [2.6 backport] Get clusterName from rke-machine-config

- scripts/package
issue: https://github.com/rancher/rancher/issues/34074
backport of https://github.com/rancher/rancher/pull/34024
remove the skipping of CRD charts which may contain images that need to be in the rancher-images.txt file for airgap
> [release/v2.5] remove the skipping of CRD charts

- pkg/auth/providers/common/usermanager.go
- pkg/auth/providers/publicapi/login.go
- pkg/auth/tokens/token_util.go
- pkg/controllers/managementuser/clusterauthtoken/token.go
**Problems:**
1. When token has expired the kubectl with embedded CLI prompts for the token twice. Cause:
Sometimes create fails despite the delete call being made
prior. This is because it is in the process of being deleted.
Already exists errors were being ignored causing the caller
to receive a 201 even though the token was not created. It
was possible that the cluster auth token was created.
2. Cluster auth tokens are not being created when kubeconfig-generate-token setting is false.
**Solutions:**
1. Now, create will be retried if an already exists error is encountered. Controller error message now explains that cluster auth token cannot be found yet, insinuating that it is not abnormal if it is found the issue will be resolved.
2. Now, the api used by the rancher CLI attempts to …
> No gen token2

- chart/templates/secret.yaml
https://github.com/rancher/rancher/issues/34227
Fixed helm failing to upgrade when the default password has not yet been initalized.
> fix error when upgrading helm chart

- pkg/catalog/manager/catalog_sync.go
- pkg/catalog/utils/utils.go
- pkg/data/management/catalog_data.go
- pkg/image/resolve.go
Currently, **for system-charts only**, we use the same scripts we use to generate the rancher-images.txt in order to produce a ConfigMap called `system-library-catalog-image-list` in the `cattle-system` namespace.
This ConfigMap contains a list of images that were extracted from system-charts stored in `management-state/catalog-cache/{HASH-OF-CATALOG}`.
However, for air-gapped setups, the system-charts do not get pulled into this directory. Instead, they only exist as packaged in the Rancher [Dockerfile](https://github.com/rancher/rancher/blob/522c7764153e4cfee6161895ae44efaa59d611d9/package/Dockerfile#L53) under `/var/lib/rancher-data/local-catalogs/system-library`. So the creation of the ConfigMap fails, triggering the 500 error seen on the ticket.
The fix pushed out in this PR modifies …
> Support pulling system imagelist cache from bundled charts

- pkg/catalog/manager/catalog_sync.go
- pkg/catalog/utils/utils.go
- pkg/data/management/catalog_data.go
- pkg/image/resolve.go
Backports changes from https://github.com/rancher/rancher/pull/34225.
Related Issue: https://github.com/rancher/rancher/issues/34172
(cherry picked from commit 6142dc4f23c9962bccaa565e305a5303705ed466)
> [2.6] Support pulling system imagelist cache from bundled charts

- pkg/controllers/managementuser/rbac/impersonation_handler.go
If a user has no extra attributes, for instance a local user with no
groups, then the UserAttribute lister will not find the user. This is
expected and can be ignored, as the User lister has already found the
user.
Backport of https://github.com/rancher/rancher/pull/34117
https://github.com/rancher/rancher/issues/34140
> [v2.5] Ignore user not found in user attribute lister

- go.mod
- pkg/rancher/migrations.go
https://github.com/rancher/rancher/issues/34149
Fixed how we decide to force a logout. All users will be logged out in ONLY the following cases:
- if the current rancher version is an rc or release and the target version is greater than the last force logout
- if the current rancher version is a `*-head` build and the last force logout version does not match the current version
> fixed version checks for force logout

- chart/templates/post-delete-hook-cluster-role.yaml
issue rancher/rancher#34188
the post-delete-hook needs the permission to create a PSP for `rancher-webhook`'s pre-delete-hook
Note:
This PR is already tested in a hardened cluster
TODO:
> add the permission for creating PSP to support uninstalling the rancher-webhook app in hardened cluster

- pkg/settings/setting.go
Revert "Add token-hashing setting"
This reverts commit 4380cb873b38ada140b92df8f96889a3b6d907f8.
> Remove token hashing setting if unused

- pkg/controllers/dashboard/helm/register.go
- pkg/controllers/dashboard/helm/repo.go
Issue: https://github.com/rancher/rancher/issues/34193
Cause: https://github.com/rancher/rancher/issues/34193#issuecomment-897984502
Fix:
add the logic to check and rebuild the missing IndexConfigMap: if the IndexConfigMap does not exist in the cluster, reset the value of `IndexConfigMapName`, `IndexConfigMapNamespace`, `IndexConfigMapResourceVersion` to `""` such that the method `shouldRefresh` will returns `true` and trigger a rebuild of the index file. 
TODO after merging:
> add checks for no-existing IndexConfigMapNamespace in repo.status

- pkg/catalogv2/helmop/operation.go
- pkg/wrangler/context.go
https://github.com/rancher/rancher/issues/34277
Add operation permission to standard users, as they should be able to use rke2 cluster template(helm chart), install and see helm operation logs.
The implemetation is changed so that when user creates operation through action, the corresponding role and rolebinding that only allow user to get this operation will be created along with operation. This only gives user ability to see operations that were created by itself.
> Add operation permission to standard user so they can see logs

- pkg/data/management/machinedriver_data.go
This PR updates Harvester Node Driver to version v0.3.0, which replace DataVolume with PVC to support Harvester 0.3.0
Related Issue:
harvester/harvester#1058
> Bump harvester node driver to 0.3.0

- pkg/provisioningv2/rke2/planner/planner.go
The flag for RKE2 uses plural snapshots; Rancher was passing it as
singular. This fix adds to the 's'
Issue:
https://github.com/rancher/rancher/issues/34175
> Fix ectd-disable-snapshots flag

- chart/templates/secret.yaml
This handles upgrade when bootstrapPassword is no in the values and
also if the bootstrap secret exists and has no data or empty
bootstrapPassword field
> Fix helm upgrade for bootstrap password

- chart/templates/secret.yaml
This handles upgrade when bootstrapPassword is no in the values and
also if the bootstrap secret exists and has no data or empty
bootstrapPassword field
backport #34343
> [2.6] Fix helm upgrade for bootstrap password

- pkg/clusterrouter/factory.go
- pkg/clusterrouter/proxy/proxy_server.go
- pkg/clusterrouter/router.go
- pkg/k8sproxy/k8s_proxy.go
When the cluster context is set for the proxy server at initialization,
it doesn't always refresh when a new request comes in. This can cause
the cache to become stale and the proxy server handler can fail to
fetch service accounts from it even though they exist in the downstream
cluster. This change pushes the cluster context getter down to the
request handling layer instead of the server creation layer so that it
is refreshed on every request.
https://github.com/rancher/rancher/issues/34187
> [2.6] Retrieve the UserContext for cluster dynamically

- pkg/clusterrouter/factory.go
- pkg/clusterrouter/proxy/proxy_server.go
- pkg/clusterrouter/router.go
- pkg/k8sproxy/k8s_proxy.go
When the cluster context is set for the proxy server at initialization,
it doesn't always refresh when a new request comes in. This can cause
the cache to become stale and the proxy server handler can fail to
fetch service accounts from it even though they exist in the downstream
cluster. This change pushes the cluster context getter down to the
request handling layer instead of the server creation layer so that it
is refreshed on every request.
https://github.com/rancher/rancher/issues/34187
> [forwardport master] Retrieve the UserContext for cluster dynamically

- Dockerfile.dapper
- scripts/package
https://github.com/rancher/rancher/issues/32600
rancher-images.txt diff between master and this branch after running local drone builds with TAG=v2.6.0
```
--- ../rancher-images-master.txt        2021-08-19 22:39:52.000000000 -0700
+++ bin/rancher-images.txt      2021-08-19 23:00:02.000000000 -0700
@@ -203,6 +203,9 @@
rancher/security-scan:v0.2.3
rancher/shell:v0.1.10
rancher/shell:v0.1.8
+rancher/system-agent-installer-k3s:v1.21.3-k3s1
+rancher/system-agent-installer-rke2:v1.21.3-rc6-rke2r2
+rancher/system-agent:v0.0.1-alpha37-suc
rancher/system-upgrade-controller:v0.7.3
rancher/system-upgrade-controller:v0.7.4
rancher/tekton-utils:v0.1.2
```
> Add system agent images to package script

- pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
- pkg/controllers/management/k3sbasedupgrade/template.go
Adding tolerate all to plans, bound by strong affinity to node names.
Updating svc account name based on updated suc chart.
https://github.com/rancher/rancher/issues/32050
> [v2.6] updates for k3s-upgrader based on updated system-upgrade-controller

- pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
- pkg/controllers/management/k3sbasedupgrade/template.go
Forward port https://github.com/rancher/rancher/pull/34376 
Adding tolerate all to plans, bound by strong affinity to node names.
Updating svc account name based on updated suc chart.
https://github.com/rancher/rancher/issues/32050
> updates for k3s-upgrader based on updated system-upgrade-controller

- pkg/data/management/role_data.go
https://github.com/rancher/rancher/issues/32711
We do not need to create bootstrap secret in single docker install, as it is only served for users to view random generated password in helm HA install. Creating the secret will cause migration problem mentioned in the issue.
cc @nickgerace Figured this might be the best way to fix it.
> Don't create bootstrap secrets if it doesn't exist

- pkg/controllers/provisioningv2/rke2/machineprovision/template.go
A previous update changed the machine-provisioning job to run as a
non-root user, as well as updating permissions to volumes to ensure the
new user can access the appropriate files. There was one volume that was
missed, and this change updates the permissions of that volume to allow
the machine-provisioning job to access the files it needs.
Issue:
https://github.com/rancher/rancher/issues/34373
> Fix provisioning machine files permissions

- pkg/controllers/dashboardapi/settings/settings.go
**Issue**
When an environment variable is used for settings, we want to know that it was set by an ENV var
**Solution**
Set the existing settings.Source field to "ENV" when an environment variable is used. This will help users know when env vars were used and will help them understand where to make settings changes. 
**Note:** I ran `go generate` and see that there were some files not generated. https://github.com/rancher/rancher/pull/34345 looks like it could've been from this.
> [2.6] Set the source on settings

- pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
- pkg/controllers/management/authprovisioningv2/cluster.go
- pkg/controllers/management/authprovisioningv2/prtb.go
- pkg/controllers/management/restrictedadminrbac/cluster.go
- pkg/controllers/management/restrictedadminrbac/register.go
- pkg/controllers/managementuser/rbac/globalrole_handler.go
- pkg/rbac/common.go
https://github.com/rancher/rancher/issues/34185
Adding rbac permissions for restrictedAdmin users to be able to access the provisioning Cluster. This has been added to two places:
1) In the cluster sync, to create a rolebinding to the cluster-admin role created for the provisioning cluster for all restrictedAdmin subjects
2) In the GRB sync, when a new restrictedAdmin user is added, we create a rolebinding to the  cluster-admin role created for the provisioning cluster for this user
> Adding rbac for restrictedAdmin to access Provisioning Clusters

- pkg/controllers/management/usercontrollers/controller.go
The cleanup job service account now needs to be able to look up the
presence of the rancher service in the cluster and fails to perform any
cleanup if it does not have permission. This change adds the appropriate
RBAC rule to the main cluster role for the cleanup job.
https://github.com/rancher/rancher/issues/33800
> [v2.6] Add RBAC rule for cleanup job user

- pkg/controllers/dashboard/clusterregistrationtoken/status.go
This prefixes commands for windows registration with `PowerShell` so that the command can be run from either CMD or PowerShell. 
rancher/dashboard#3952
> [master] Prefix RKE2 Windows node commands with "PowerShell"

- pkg/controllers/dashboard/clusterregistrationtoken/status.go
This prefixes commands for windows registration with `PowerShell` so that the command can be run from either CMD or PowerShell. 
rancher/dashboard#3952
Backports PR #34369 into release/v2.6
> [2.6] Prefix RKE2 Windows node commands with "PowerShell"

- pkg/data/management/role_data.go
Problem:
machinedeployments are required to see the pool machines are associated
with and some roles are missing that permissions.
Solution:
Add permission to roles that also have access to the machine object
https://github.com/rancher/rancher/issues/34404
> Add machinedeployment permissions

- pkg/data/management/role_data.go
Problem:
machinedeployments are required to see the pool machines are associated
with and some roles are missing that permissions.
Solution:
Add permission to roles that also have access to the machine object
https://github.com/rancher/rancher/issues/34404
> [2.6] Add machinedeployment permissions

- pkg/controllers/management/usercontrollers/controller.go
The cleanup job service account now needs to be able to look up the
presence of the rancher service in the cluster and fails to perform any
cleanup if it does not have permission. This change adds the appropriate
RBAC rule to the main cluster role for the cleanup job.
Forward port of https://github.com/rancher/rancher/pull/34421
https://github.com/rancher/rancher/issues/33800
> Add RBAC rule for cleanup job user

- pkg/controllers/management/clusterprovisioner/provisioner.go
In order to successfully enable ACE on an RKE2 cluster that was created
with ACE disabled, the cluster controllers must be restarted. This
change allows the controllers to detect when they should be restarted
because of an ACE change.
Issue:
https://github.com/rancher/rancher/issues/34500
> Restart cluster controllers on RKE2 ACE change

- pkg/controllers/management/authprovisioningv2/cluster.go
- pkg/controllers/managementuser/rbac/globalrole_handler.go
- pkg/rbac/common.go
Forward porting PR https://github.com/rancher/rancher/pull/34517
Issue https://github.com/rancher/rancher/issues/34509
Problem:
restricted-admin does not have access to the v2 provisioning resources
in the management cluster
Solution:
Tie restricted-admin to the cluster-owner role that is created with all
clusters which grants the v2 provisioning permissions for resources
marked as cluster indexed.
> [Forward port] Update restricted-admin to use cluster-owner role

- go.mod
- go.sum
- package/Dockerfile
- pkg/apis/go.mod
- pkg/apis/go.sum
- webhook and fleet min versions are already updated 
- system_agent will be bumped to GA after testing with this RC
> update tags for 2.6.0-rc9

- pkg/provisioningv2/rke2/planner/planner.go
First, and foremost, this change is to address the worker config getting
an invalid setting: advertise-address is a server only setting.
Secondly, this refactors the code that sets the IP addresses so that
advertise address is set whether or not a cloud-provider has been
chosen. This is to ensure that the internal address is always used for
the apiserver IP.
Issue:
https://github.com/rancher/rancher/issues/34497
> Fix worker config and refactor IP address setting

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/provisioningv2/cluster/controller.go
A previous attempt was made to determine when a v3.Cluster upgrade
should be administered by management or provisioning controllers. That
change was not able to distinguish imported RKE2 clusters which should be
administered by the management controllers.
This change adds an annotation to the v3.Cluster object to better
distinguish these scenarios.
Issue:
https://github.com/rancher/rancher/issues/34546
> Distinguish imported RKE2 clusters from provisioning clusters

- go.mod
- go.sum
- package/Dockerfile
- pkg/apis/go.mod
- pkg/apis/go.sum
- webhook and fleet min versions are up to date
> update tags for 2.6.0

- pkg/data/management/role_data.go
Backport to release/v2.6 of https://github.com/rancher/rancher/pull/34422 for https://github.com/rancher/rancher/issues/33110 issue targeting v2.6.1.
> [2.6] Grant full control to catalog.cattle.io.clusterrepos to restricted admins

- scripts/provisioning-tests
- tests/integration/pkg/tests/custom/custom_test.go
The provisioning tests should use the correct version of the
system-agent. This change includes a test that checks for the expected
variable in the install script to ensure the correct version is used.
Issue:
https://github.com/rancher/rancher/issues/34437
> Ensure correct system-agent version used in tests

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_airgap.py
- tests/validation/tests/v3_api/test_custom_host_reg.py
- tests/validation/tests/v3_api/test_proxy.py
I've added the argument `-e CATTLE_BOOTSTRAP_PASSWORD=<password>` for each docker run in our automation. 
Also, it turns out that the request just needed to be retried. Jenkins job is passing
> Fix for docker server deployments: retry password requests

- Dockerfile.dapper
- package/Dockerfile
- package/Dockerfile.agent
Pin sle version to `15.3.17.8.1` to avoid breaking changes in the future
Environment
-
install: docker
Verification
-
- Installed helm charts
- Tested provision a downstream cluster with Digital Ocean (cluster failed at agent image pull due to not being able to find corresponding tag, will re-verify on merge into master)
Related
-
Issue: #34580
> Fix sle version to 15.3.17.8.1

- pkg/data/management/role_data.go
This allows subjects who are bound to the `catalogs-manage` GlobalRole to manage chart repositories.
Issue:
- https://github.com/rancher/rancher/issues/34592
Testing steps:
1. Start Rancher v2.6.0 (version without this change)
2. Create a standard user, check the "Configure Catalogs" builtin role
3. Add new user as a member to a cluster (local or downstream)
4. Log in as user and go to `Apps & Marketplace > Chart Repositories` in the cluster
5. Note that chart repositories cannot be modified in any way
6. Upgrade to this PR
7. Refresh browser, user can modify chart repositories
`catalogs-manage` GlobalRole:
```yaml
rules:
- apiGroups:
- management.cattle.io
resources:
- catalogs
- templates
- templateversions
verbs:
- '*'
- apiGroups:
- catalog.cattle.io
resources:
- clusterrepos
verbs:
- …
```
> Add clusterrepos to catalog management roles

- pkg/clustermanager/manager.go
- pkg/controllers/management/node/cleanup.go
- pkg/controllers/management/usercontrollers/controller.go
There is a race condition where the cluster object on the local cluster
is being deleted, but the cluster agent on the downstream cluster is not
yet cleaned up, and without this change the controller won't get a
kubeconfig for the deleted cluster and won't be able to create the
cleanup job.
To fix this for RKE1, an exception was made in ToRESTConfig to have it
return a kubeconfig even as the cluster was being deleted, as long as
the driver was RKE1. This doesn't help for the case where the driver is
"Imported" or "RKE2". It's also problematic because it means that
controllers will be unnecessarily started when the cluster is being
deleted.
This change moves the deletion check out of ToRESTConfig and into the
internal controller handling methods, and reworks the imported cluster
cleanup …
> Fix cluster cleanup race

- pkg/data/management/machinedriver_data.go
Backport #34764
This PR updates Harvester Node Driver to version v0.3.1, which fix volume delete
Related Issue:
https://github.com/rancher/rancher/issues/33583
> [v2.6] Bump harvester node driver to 0.3.1

- pkg/data/management/machinedriver_data.go
This PR updates Harvester Node Driver to version v0.3.2, which fix volume delete with webhook error issue
Related Issue:
https://github.com/rancher/rancher/issues/33583
https://github.com/harvester/harvester/issues/1227
https://github.com/harvester/harvester/issues/1246
> [v2.6] Bump harvester node driver to v0.3.2

- pkg/controllers/managementagent/nslabels/labels.go
- pkg/controllers/managementuser/rbac/namespace_handler.go
- pkg/controllers/managementuser/secret/secret.go
Relevant issues:
- This PR partially addresses: https://github.com/rancher/rancher/issues/34746
- This PR primarily addresses: https://github.com/rancher/rancher/issues/34776
There are two fixes and one "bonus" here. Of the former, one is the actual and the other is preventative.
Fleet namespaces will not longer have the projectID annotation if the system project does not exist.
- We've observed handlers using this malformed annotation (e.g. `"local:"` instead of `local:<system-project-id>`).
- When it's removed, the namespace is no longer loaded into the cluster secrets creation sync: https://github.com/rancher/rancher/blob/ebcb2321e254a9d172a130613a1a2d6e06d23248/pkg/controllers/managementuser/secret/secret.go#L102
- Without this PR, an empty string is loaded into the management secrets …
> Only add projectID to Fleet NS when system project exists

- pkg/data/management/role_data.go
issue: https://github.com/rancher/rancher/issues/34592
This reverts commit 04bd8454fba0ee5c4227926be3598e7a39dfbe39.
> Revert "add clusterrepos permission to catalog management roles"

- pkg/clusterrouter/proxy/proxy_server.go
- pkg/controllers/managementuser/rbac/impersonation_handler.go
- pkg/impersonation/impersonation.go
- pkg/impersonation/impersonation_test.go
Without this patch, requests made on a downstream cluster through the
impersonation proxy can sometimes fail when the impersonation cluster
role fails to update. This is more likely to happen when there are a
high volume of requests. This change addresses the issue in two ways:
1) Reduce the need to update the cluster role by ensuring that the
resources in the role rules are sorted so that equality comparison is
meaningful.
2) Retry the update when a conflict is encountered so that a single
conflict error isn't fatal to the request.
https://github.com/rancher/rancher/issues/34671
> Fix conflict errors for impersonation cluster role

- pkg/controllers/provisioningv2/rke2/machineprovision/args.go
The machine job would fail if Rancher was running behind a proxy. This
change passes the proxy environment variables to the job if they are
set.
Issue:
https://github.com/rancher/rancher/issues/34801
> Pass HTTP proxy environment to machine job

- pkg/api/norman/customization/catalog/store.go
Relevant issue: rancher/rancher#28776 
This is relevant only for the old UI. A blank chart is one whose `Chart.yaml` is missing the `version` field. The `name` field is also required, but its lack is already properly handled.
> Avoid a panic when a user adds a chart catalog containing a blank Helm chart

- pkg/controllers/provisioningv2/cluster/controller.go
- pkg/controllers/provisioningv2/cluster/remove.go
- pkg/provisioningv2/kubeconfig/manager.go
Ensure provisioning cluster migration does not delete management cluster
by checking if the FleetWorkspace has changed. This is trigged in the UI
by using "assign to" in Continuous Delivery, which deletes and
re-creates the provisioning cluster as well as its corresponding Fleet
cluster. Additional changes include:
- deleting the provisioning-cluster-specific v3 User due
to potential v3 User "memory leak" upon change the Fleet cluster's
FleetWorkspace (v3 Users would be created for each migration, but never
deleted)
- changing the CRTB name to include the cluster's namespace due to a
race condition where the old provisioning cluster's deletion could
cause the CRTB to be deleted due to resource "apply"
Relevant issue: https://github.com/rancher/rancher/issues/34744
Design considerations:
- …
> Ensure provisioning cluster migration does not delete management cluster

- pkg/api/norman/customization/aks/listers.go
If an AKS cluster is already on the latest version, then the
orchestrator Upgrades field will be nil. This patch ensures that case is
handled correctly to avoid a nil dereference error.
https://github.com/rancher/rancher/issues/34901
> Fix panic for AKS when no upgrades are available

- pkg/controllers/management/usercontrollers/controller.go
Without this change, cleanupImportedCluster always deletes the
cattle-system namespace of the imported cluster, which is not always
desireable if the imported cluster is a rancher cluster. This was not
evident before f420749b because if the controller failed to get a
cluster context for the deleted cluster then it wouldn't get as far as
deleting the cluster. The controller does not need to delete the
namespace itself because the cluster agent cleanup job takes care of
it[1] and is smart enough not to delete the namespace if rancher is
running in it. This change fixes the problem by removing the deletion
from the controller and leaving it up to the agent to handle.
[1] https://github.com/rancher/rancher/blob/0dd1ce6547cbb3253a8c6f48f5d538c98e7c567d/pkg/agent/clean/cluster.go#L99-L127 …
> Don't delete system namespace from controller

- pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go
- pkg/provisioningv2/rke2/planner/planner.go
When passing the system-agent-install instruction to the machine, none
of the agent arguments were being added to the environment. This made it
impossible to use the agent args to pass things like the PROXY
environment variables to the system-agent-installer.
After this change, the agent args are passed to the environment for the
system-agent-installer and it will pull out RKE2_ and _PROXY environment
variables.
Issues:
https://github.com/rancher/rancher/issues/32633
https://github.com/rancher/rancher/issues/34908
> Add agent args to environment for instruction

- pkg/api/steve/catalog/content.go
- pkg/catalogv2/content/content.go
- pkg/catalogv2/content/content_test.go
- pkg/catalogv2/helmop/operation.go
- pkg/catalogv2/system/system.go
- pkg/controllers/provisioningv2/managedchart/managedchart.go
**Issue**
https://github.com/rancher/rancher/issues/34919
**Problem**
rancher-version filtering is causing errors when upgrading to newer versions of rancher where the currently installed chart is not longer supported in the new rancher version. When the user goes to edit/upgrade their install, an error is showing because the chart info is filtered out of the api response. 
**Solution**
Add a flag so that only the index filter charts based on chart annotations. This will allow specific chart get calls to return the chart information if it still exists in the chart repository.
> Add a skipFilter bool so that not all calls occur on a filtered index

- pkg/systemtemplate/import.go
- pkg/systemtemplate/template.go
Downstream clusters need to have the same `server-version` setting as their upstream in order to view the correct feature charts version for the current rancher installation. The `CATTLE_SERVER_VERSION` environment variable is now passed down through an environment variable when the cluster agent is deployed to ensure that the downstream cluster agent uses the correct version.
Related Issue: https://github.com/rancher/rancher/issues/34875
> populate server-version setting with env var for cluster agent

- pkg/controllers/managementuser/resourcequota/resource_quota_calculate_used.go
- pkg/controllers/managementuser/resourcequota/resource_quota_common.go
- pkg/controllers/managementuserlegacy/helm/state.go
This PR modifies the resourceQuota and appState controllers to ignore apps & projects that are not found on trying to update. This is specifically meant to mitigate CPU spikes we see in a Hosted Rancher setup.
Specifically, it encodes the following logic:
- [AppState] If a workload with an annotation that appears to point to a v3 app that is **not** tracked by our management cluster is found, we should ignore updating the app state since it's probably managed by another Rancher.
- [ResourceQuota] If a namespace with an annotation that appears to point to a v3 project that is **not** tracked by our management cluster is found, we should ignore updating the resource quota since it's probably managed by another Rancher.
---
I also made a minor change to use `ref.Parse` instead of an …
> Ignore resourceQuotas and apps in undefined projects

- pkg/api/norman/customization/catalog/store.go
Backport from PR [#34787 ](https://github.com/rancher/rancher/pull/34787)
Original Issue [#28776](https://github.com/rancher/rancher/issues/28776)
Linked backport issue [#34912 ](https://github.com/rancher/rancher/issues/34912)
> [Backport 2.5] Avoid a panic when a user adds a chart catalog containing a blank Helm chart

- pkg/image/resolve.go
The rancher-machine image was mistakenly left out of the images.txt
file. This change will include it.
Issue:
https://github.com/rancher/rancher/issues/34986
> Ensure rancher-machine image is added to images.txt

- pkg/controllers/managementagent/targetworkloadservice/target_workload_service.go
**Issue:** 
Services stopped working in v2.6-head because they have an extra selector `workloadID_`. 
https://github.com/rancher/rancher/issues/34948 
**NOTE:** 
This issue doesn't happen in v2.6.0 because the controller would error out here https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/managementagent/targetworkloadservice/target_workload_service.go#L123 due to an existing bug. This bug was recently fixed in UI so the logic now proceeds and adds selector the service.  
**Root cause:** 
Vue UI creates services for workloads itself vs backend used to create different type of services in Ember. The default service created for Ember always had Noop annotation https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/managementagent/workload/workload.go#L249 …
> add WorkloadID selector only if service is created by norman

- pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
When fleet bootstraps the local cluster it uses a non standard secret name
"local-cluster" because the loopback connect is handled different from
any other cluster. Due to a race condition on start it was possible that
Rancher would first create fleet-local/local cluster with no kubeconfig
secret.  If the kubeconfig secret is blank fleet would try to generate
one and would fail for the local cluster.  Instead if rancher creates
the local cluster first ensure that we also set the non standard secret
"local-cluster".
> Handle flapping value between rancher and fleet

- pkg/controllers/managementuser/helm/state.go
- pkg/controllers/managementuser/resourcequota/resource_quota_calculate_used.go
- pkg/controllers/managementuser/resourcequota/resource_quota_common.go
(cherry picked from commit f63a83d1c285df5399df8dc5281b1915b87b46c5)
Backports https://github.com/rancher/rancher/pull/34938 with no additional changes.
Related Issue: https://github.com/rancher/rancher/issues/34961
> [Backport 2.5] Ignore resourceQuotas and apps in undefined projects

- pkg/controllers/management/clusterprovisioner/provisioner.go
Backport https://github.com/rancher/rancher/pull/33862
When check for upgrade we assume the same k8s version will have the
same systemImages.  This allows us to add new images (like the ACI ones)
and that won't trigger an upgrade.
Issue: https://github.com/rancher/rancher/issues/33876
> [release/v2.5] Don't consider systemImages from kdm to detect upgrade

- tests/validation/tests/v3_api/test_airgap.py
This works on 2.5 but as we're using now a new variable for the bootstrap password the order matters. So I've reordered the variables order to match the proper parameters on the docker command.
> Automation - Airgap fix order of admin password of rancher docker command

- pkg/data/management/machinedriver_data.go
Part of https://github.com/rancher/rancher/issues/33758#issuecomment-946946715
- Fixes 404s when accessing the component.js for Packet
- Updates the docker-machine driver to v0.6.0
https://github.com/equinix/docker-machine-driver-metal/releases/download/v0.6.0/docker-machine-driver-metal_linux-amd64.zip contains both a packet and a metal binary, the installer will choose the packet binary.  The packet binary honors all Packet env and cli arguments (used by the UI driver), while the Metal binary adopts new name prefixes.
Signed-off-by: Marques Johansson <mjohansson@equinix.com>
> update URLs and sha256 for Equinix Metal (Packet) drivers

- pkg/api/steve/machine/download.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_bootstrap.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_client.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_condition.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_duration.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_machine.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_machine_address.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_machine_spec.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_machine_status.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_object_meta.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_object_reference.go
- pkg/client/generated/cluster/v1alpha4/zz_generated_owner_reference.go
- pkg/codegen/main.go
- pkg/controllers/management/clusterprovisioner/store.go
- pkg/encryptedstore/secrets_store.go
- pkg/nodeconfig/config.go
In order to use the CLI to get the SSH keys for machines, clients need
to be generated. This change sets up the clients to be generated with
`go generate`.
In addition to this change, the `config.json` file from the machine
state is also included in the response to the get request for SSH keys.
This is necessary because the SSH user information is stored there and
needed to connect.
Issue:
https://github.com/rancher/rancher/issues/35203
> Capi machine clients

- pkg/controllers/managementuser/rbac/project_handler.go
- pkg/rancher/migrations.go
- pkg/rancher/rancher.go
Backport of #34885, which is a forward port of #34527, addressing some issues that were missed in the original PR (namely, the `retry.RetryOnConflict` logic would never succeed if it failed the first time).
Related Issue: https://github.com/rancher/rancher/issues/32898
> [Backport v2.5] Fix namespaces not being moved to System project on upgrade

- pkg/catalogv2/http/download.go
Root cause of this issue is https://github.com/rancher/rancher/blob/5e3b154abc2b697bcd4124bfa7a38f0d7398ae5a/pkg/catalogv2/http/download.go#L65
`path.Ext(u.String())` does not necessarily represent the suffix since a URL with url encoded params can have elements after the file extension. e.g. in this case, the value returned for the suffix was `.svg?sanitize=true`.
The simple fix here is to replace `u.String()` with `u.Path`, which returns just the path without URL-encoded elements.
Related Issue: https://github.com/rancher/rancher/issues/32412
---
Note: Since this issue is for 2.6.2, it should not be merged until release branches are cut for 2.6.0 and 2.6.1.
> [2.6.2] Use u.Path instead of u.String for icon suffix

- pkg/catalogv2/helmop/operation.go
- pkg/catalogv2/helmop/operation_test.go
- pkg/controllers/managementuserlegacy/helm/common/common.go
- pkg/controllers/managementuserlegacy/helm/controller.go
- pkg/settings/setting.go
**Problem:**
Customers want to be able to migrate apps.project to dashboard apps (apps.catalog). This is blocked by two issues:
Helm3 apps that were installed by creating an app.project may
have had some of their resources changed with kustomize. Some
of these changes were to matchLabel selectors which are
immutable. This caused any updates to a migrated app to
result in an error because the manifests that were
being applied would try to remove the matchLabels, which
cannot be changed.
Need to be able to delete outdated apps (apps.project) without uninstalling resources.
**Solution:**
Now, migrated apps will continue using
kustomize to make the same changes to the manifests as
before.
Add annotation that skips helm uninstall. Revisions will still
be deleted and app will be removed from …
> Apps migration

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/imported/imported.go
- pkg/controllers/management/usercontrollers/controller.go
- pkg/controllers/provisioningv2/cluster/controller.go
- pkg/controllers/provisioningv2/cluster/remove.go
- pkg/features/migrate.go
- pkg/rancher/rancher.go
Firstly, the provisioning cluster indexer was mistakenly put behind the RKE2
feature flag. This caused an issue when deleting RKE1/imported clusters
when RKE2 feature flag was turned off.  This change puts it behind the
ProvisioningV2 feature flag.
In addition, the change adds logic to keep track of when the RKE2
feature flag can be disabled. That is, if there are RKE2 provisioned
clusters then a user should not be able to disable the RKE2 feature
flag. An annotation is added to the feature for easy tracking, and the
annotation is checked on startup and added if necessary so that RKE2
provisioning works as expected.
Issues:
https://github.com/rancher/rancher/issues/35179
https://github.com/rancher/rancher/issues/35180
> Fix disabling RKE2 feature flag

- pkg/clustermanager/manager.go
In Rancher HA mode, each replica will create an [access control cache](https://github.com/rancher/rancher/blob/release/v2.5/pkg/clustermanager/manager.go#L232) for each downstream cluster no matter it's the clusterOwner or not. In access control cache, we start a [handler](https://github.com/rancher/steve/blob/7224dc21013de5499e17cd065dfccef9400bc077/pkg/accesscontrol/role_revision_index.go#L18) here to handle role revisions change when clusterrole/role changed at the downstream cluster. 
For further investigation, I found some inconsistent context to start the access control cache. 
1. https://github.com/rancher/rancher/blob/release/v2.5/pkg/clustermanager/manager.go#L480
2. https://github.com/rancher/rancher/blob/release/v2.5/pkg/clustermanager/manager.go#L457
3. …
> [2.5] Fix the problem of handler registration failure caused by inconsistent context

- pkg/data/management/role_data.go
Issue:
- https://github.com/rancher/rancher/issues/34592
Change RoleTemplates to include `clusterrepos` permissions. This ensures that when a user is added to a cluster with this permission, they are able to modify chart repositories. 
Also, change the display name for the `catalogs-manage` GlobalRole to indicate that it is legacy, i.e. does not apply to cluster scoped catalogs managed through the dashboard UI
> Catalog Permissions

- pkg/controllers/provisioningv2/rke2/bootstrap/controller.go
- pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go
- pkg/provisioningv2/rke2/configserver/server.go
- pkg/provisioningv2/rke2/installer/installer.go
- pkg/provisioningv2/rke2/installer/server.go
- pkg/provisioningv2/rke2/planner/drain.go
- pkg/provisioningv2/rke2/planner/planner.go
- pkg/tls/tls.go
When the local cluster is provisioned via rancherd, a hostPort is used.
When Rancher is contacted via the hostPort, the internal-cacerts setting
is used instead of the regular cacerts setting. This was causing issues
with system-agent trying to verify Rancher's CA. After this change, The
install script logic with provide the corresponding CA as necessary.
In addition, when certificates were being regenerated on Kubernetes
upgrade, the clusterIP was being used but not the hostIP. This again was
causing issues with system-agent verifying Rancher's CA because the SAN
did not include the hostIP when hostPort was enabled.
Finally, once machines were "uncordoned" the annotation was never
getting removed. This change will remove the annotation after the node
is uncordoned.
Issue: …
> Add better support for upgrading local cluster

- pkg/controllers/managementuser/rbac/project_handler.go
- pkg/rancher/migrations.go
Forwardport of #35322, which is a backport of #34885, which is a forward port of #34527, addressing some issues that were missed in the original PR. A specific commit was lost as a result of a force push, which actually performed the system project assignment logic.
Related Issue: #32898
> [Forwardport v2.6] Fix namespaces not being moved to System project on upgrade (part 2)

- chart/templates/ingress.yaml
Without this patch, the `helm template` command generates Ingress
resources that use the `networking.k8s.io/v1beta1` APIVersion. This is
because the `helm template` command does not populate the
`Capabilities.APIVersions` set with real available resources, it only
creates a fake set of API versions that does not include resources, so
it does not have `networking.k8s.io/v1/Ingress` in the set. Since the
fake set also does not include `networking.k8s.io/v1beta1/Ingress`, we
can assume in that case that we are running in `helm template` and we
should default to the v1 version.
https://github.com/rancher/rancher/issues/30053
> Fix ingress template for `helm template` command

- tests/validation/tests/v3_api/resource/sysctl-config
Was missing sudo in the sysctl commands, and hence the commands never ran on the nodes. And rke up resulted in failure. Kubelet on the nodes were in a state of panic.
> Adding fixes for hardened local cluster

- tests/validation/tests/Dockerfiles/testcontainer/Dockerfile
- tests/validation/tests/Dockerfiles/testcontainer/nginx.conf
- tests/validation/tests/Dockerfiles/unprivileged-testcontainer/Dockerfile
- tests/validation/tests/Dockerfiles/unprivileged-testcontainer/nginx.conf
This should be built as `ranchertest/mytestcontainer:dualstack`
It can be validated for now using `maxross/mytestcontainer:dualstack`. I ran this in a dualstack capable cluster by deploying a hostport (8081) workload, then curling the ipv6 address like `curl [<redacted>]:8081/name.html`, which was successful. 
The only change between this and our main `ranchertest/mytestcontainer` image is that this specifics `listen [::]:80;` in the nginx.conf server.
Edit: This is now intended as an enhancement to both `ranchertest/mytestcontainer` and `ranchertest/mytestcontainer:unprivileged`. Those images should be retagged and pushed with these changes, and should now be valid when used with only ipv4 or with ipv4+ipv6 dualstack.
Closes: https://github.com/rancher/qa-tasks/issues/144
> Add a dualstack-capable QA image

- pkg/apis/project.cattle.io/v3/app_types.go
- pkg/controllers/managementuser/helm/controller.go
Issue [#20654](https://github.com/rancher/rancher/issues/20654)
The Helm controller will now limit the number of app revisions per app. By default, up to 10 revisions will be kept in etcd per app.
Users will be able to set the limit themselves. But only on app installation and only by modifying the API request.
This affects new apps and existing apps. For existing apps, a new upgrade/rollback will trigger the pruning of old app revisions. For example, if an app has 200 revisions stored in etcd, then on the next app change, a new revision will be created and 191 of the old ones will be deleted, so Rancher will maintain only the 10 newest revisions (by default) at all times.
> After creating an app revision on install/upgrade, prune old revisions

- pkg/apis/management.cattle.io/v3/tools_system_images.go
Bump kube-api-auth version to `v0.1.6`
Related Issue: https://github.com/rancher/rancher/issues/33332
> Bump kube-api-auth version

- tests/validation/tests/v3_api/resource/airgap/registries.yaml
- tests/validation/tests/v3_api/scripts/configure.sh
- tests/validation/tests/v3_api/test_airgap.py
- tests/validation/tests/v3_api/test_k3s_airgap.py
- tests/validation/tests/v3_api/test_rke2_airgap.py
- Split rke2 and k3s airgap into separate files
- Cleanup helper functions
- Ensure the following airgap scenarios are covered for both:
- private registry (registries.yaml)
- system-default-registry (flag that can be passed to use a TLS-secured registry but with no username & password)
- tarball, with the ability to pass in different types of tarballs for .tar, .gz, and .zst as desired.
- Additional flags for any extra customization (such as `--airgap-extra-registry` or using different cni's with `--cni=calico`)
> [QA-Tests] Add and enhance airgap automation for k3s and rke2

- chart/Chart.yaml
issue: https://github.com/rancher/rancher/issues/34058
lift the `kubeVersion` in Chart.yaml to allow Rancher to be installed into k8s 1.22 cluster
Dependent:
- https://github.com/rancher/rancher/pull/35117
> change the kubeVersion in Chart.yaml to allow Rancher to be installed into k8s 1.22 cluster

- pkg/controllers/provisioningv2/rke2/machinestatus/controller.go
Remove the temporary solution that was in place until RKE2 Windows nodes supported system-agent functionality.
> Remove windows plan placeholder

- pkg/controllers/managementuserlegacy/pipeline/register.go
Only start the pipeline controller if a v3.Pipeline exists for the cluster.  The pipeline controller runs all Pipeline functionality in the downstream cluster.
> Only start pipeline user controller if v3.Pipeline exists

- pkg/controllers/management/authprovisioningv2/prtb.go
If two projects in the same cluster have the same user bound to the
same name role they will conflict because the project id is not in the
name of the created rolebinding.  This causes a flapping.
> Fix name collision for prtbs

- pkg/apis/management.cattle.io/v3/authz_types.go
- pkg/apis/management.cattle.io/v3/cluster_types.go
- pkg/controllers/managementuser/rbac/project_handler.go
- pkg/rancher/migrations.go
- pkg/rancher/rancher.go
Description
-
Moved `DefaultNamespacesAssigned` and `SystemNamespacesAssigned` Conditions from cluster objects to associated default and system projects. During an upgrade, the project object may never have been updated (save for project sync), and having the cluster's status depend on the project being updated was causing issues due to the migrations having the wrangler controllers, but the project lifecycle having norman controllers. 
Info
-
Tested on HA  setup a number of times, confirmed issue was not reproducible.
Related Issue: https://github.com/rancher/rancher/issues/35411
> Migrate Namespaces Assigned conditions from project to cluster

- pkg/data/management/role_data.go
Issue:
- https://github.com/rancher/rancher/issues/34592
Dashboard uses translations to pick the display name for the GlobalRoles in the user create view. The display name field of the role resource is only used by Ember UI, so it should remain as it was, i.e. without "Legacy". The `catalogs-manage` global role grants: 
```
rules:
- apiGroups:
- management.cattle.io
resources:
- catalogs
- templates
- templateversions
verbs:
- '*'
```
The display name still needs to be changed in rancher/dashboard since the above role doesn't apply to dashboard based catalog resources (`*.catalog.cattle.io`).
The permission changes in the [previous PR](https://github.com/rancher/rancher/pull/35265) are still valid.
> Revert display name change for catalogs-manage GlobalRole

- pkg/controllers/managementuser/controllers.go
The impersonation mechanism relies on the Secrets controller being
started on the user context when a proxy request is made. Before
6b2e1359, the controller was incidentally being started as part of
registering other controllers. With 6b2e1359, the certsexpiration
controller was the last to always start it on startup and now only
conditionally starts it for RKE clusters. This change adds back the
Secrets controller startup to the cluster context unconditionally so
that it is ready the first time impersonation.GetToken is called.
https://github.com/rancher/rancher/issues/35593
> Always start the Secrets controller

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/controllers/management/controller.go
- pkg/controllers/management/settings/controller.go
- pkg/controllers/managementuser/controllers.go
- pkg/settings/setting.go
- pkg/systemtemplate/import.go
- pkg/systemtemplate/template.go
Backport of https://github.com/rancher/rancher/pull/34982 and https://github.com/rancher/rancher/pull/34846
Summary
-
- Downstream clusters need to have the same server-version setting as their upstream in order to view the correct feature charts version for the current rancher installation. The CATTLE_SERVER_VERSION environment variable is now passed down through an environment variable when the cluster agent is deployed to ensure that the downstream cluster agent uses the correct version.
- Moved the install-uuid and ingress-ip-domain settings from the settings sync-handler to cluster-agent deployment template. Moved settings sync handler from managementuser to management and redeploy agent on settings changed.
Related Issue: https://github.com/rancher/rancher/issues/35488
> [2.5] convert sync handler to env vars

- pkg/controllers/managementuserlegacy/systemimage/register.go
Only start the systemimage controller if alert, logging, or pipeline controllers started.  The system image controller is responsible for upgrading the docker images associated with alert, logging, and pipeline.
> Defer systemimage controller start

- pkg/controllers/managementagent/controllers.go
- pkg/controllers/managementagent/podresources/register.go
- pkg/controllers/managementuser/nodesyncer/nodessyncer.go
The moved logic is responsible for setting the Limits and Requests fields on the v3.Node.Status.
> Move pod aggregration logic from nodesyncer to agent

- pkg/kontainer-engine/cluster/backup.go
- pkg/kontainer-engine/cluster/cluster.go
The kev1 state secret is quite large and we do extra writes every time
we do an etcd backup or during the post-check phase of provisioning. There
is no disadvantage to just not updating the state and leaving it as Running.
https://github.com/rancher/rancher/issues/35547
> Do not set kev1 state to Upgrading during etcdsave and post-check

- tests/integration/suite/test_app.py
The latest version of the wordpress chart that we have available in
rancher/charts (master branch) is 9.0.3, which is not compatible with
kubernetes 1.22 because of its usage of the old Ingress API. Since there
are other integration tests that test the functionality of app
deployments, and we don't intend to update this chart, just remove this
test.
https://github.com/rancher/rancher/issues/34060
> Remove wordpress app integration test

- pkg/api/norman/server/userstored/setup.go
- pkg/client/generated/project/v3/zz_generated_http_ingress_path.go
- pkg/client/generated/project/v3/zz_generated_ingress.go
- pkg/client/generated/project/v3/zz_generated_ingress_backend.go
- pkg/client/generated/project/v3/zz_generated_ingress_service_backend.go
- pkg/client/generated/project/v3/zz_generated_ingress_spec.go
- pkg/client/generated/project/v3/zz_generated_service_backend_port.go
- pkg/schemas/mapper/ingress_backend.go
- pkg/schemas/project.cattle.io/v3/schema.go
- tests/integration/suite/test_ingress.py
This change updates the norman ingress store to use the
networking.k8s.io/v1 Ingress API for storing Ingress objects when
possible, and modifies the project.cattle.io schema for Ingress
resources to use the k8s.io/api/networking/v1 package. This also adds
norman mappers to copy fields where needed, such as from
"defaultBackend" to "backend", so that no matter which storage API is
used, the right data exists in the object. See the deprecation guide[1]
for notes on how the fields are translated.
[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
To make this able to work with both 1.18 and 1.22 I needed to add fields to the schema, so the schema now appears to have duplicate alias fields:
If everything is working correctly, then the Ember UI and terraform or …
> Update project.cattle.io ingress schema

- pkg/controllers/managementagent/controllers.go
- pkg/controllers/managementagent/nsserviceaccount/nssvcaccnt.go
- pkg/controllers/managementuser/nsserviceaccount/nssvcaccnt.go
The nsserviceaccount controllers is responsible for setting AutomountServiceAccountToken=false on the default service account in system namespaces (excluding kube-system and default).
> Split nsserviceaccount handler between user and agent

- pkg/catalogv2/content/content.go
- pkg/catalogv2/content/content_test.go
Issue: https://github.com/rancher/rancher/issues/35613
Fix:
add the support for filtering releases by the `catalog.cattle.io/kube-version` annotation
> filter releases by the "catalog.cattle.io/kube-version" annotation

- pkg/api/norman/customization/aks/handler.go
- pkg/api/norman/customization/aks/listers.go
- pkg/api/norman/customization/cluster/validator.go
- pkg/api/norman/customization/gke/handler.go
- pkg/api/norman/customization/oci/handler.go
- pkg/api/norman/customization/vsphere/handler.go
- pkg/controllers/dashboard/hostedcluster/controller.go
- pkg/controllers/management/cluster/indexers.go
- pkg/controllers/managementapi/controllers.go
- pkg/controllers/managementuser/rbac/handler_base.go
- pkg/controllers/provisioningv2/cluster/controller.go
- pkg/httpproxy/proxy.go
- pkg/rbac/common.go
- pkg/rbac/common_test.go
If a user is an owner of a cluster, then they should be allowed to use
the cloud credential associated to that cluster in the meta proxy. This
really only applies to KEv2 and RKE2/K3S provisioned clusters because
those clusters have cloud credentials associated to them.
In addition, if a user is a owner of a cluster, they should also be able
to change the cloud credential associated to a cluster to a cloud
credential they own regardless if they have access to the old cloud
credential.
This PR also fixes an obscure issue when running Rancher in a debugger (see the second commit message for details).
Issues:
https://github.com/rancher/rancher/issues/35413
https://github.com/rancher/rancher/issues/34800
> Allow cloud credential usage for owned clusters

- go.mod
- go.sum
When pulling in the new version of helm 3.7.1, the version of netlink that was added to the go.mod file resulted in the following errors when attempting to build rancher:
```
../../go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20201029203352-d40f9887b852/nl/parse_attr.go:26:9: undefined: rtaAlignOf
../../go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20201029203352-d40f9887b852/nl/parse_attr.go:43:23: undefined: NLA_F_NESTED
../../go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20201029203352-d40f9887b852/nl/parse_attr.go:44:57: undefined: NLA_TYPE_MASK
../../go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20201029203352-d40f9887b852/nl/parse_attr.go:53:15: undefined: NLA_F_NET_BYTEORDER
../../go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20201029203352-d40f9887b852/nl/ …
```
> Pull in specific netlink commit

- pkg/api/norman/customization/cluster/actions_kubeconfig.go
- pkg/api/norman/customization/cluster/actions_yaml.go
- pkg/api/norman/customization/cluster/shell.go
- pkg/api/norman/customization/clusterscan/clusterscan.go
- pkg/api/norman/customization/logging/action.go
- pkg/api/norman/customization/monitor/cluster_graph_action.go
- pkg/api/norman/customization/monitor/handler_utils.go
- pkg/api/norman/customization/monitor/metric_action.go
- pkg/api/norman/customization/monitor/project_graph_action.go
- pkg/api/norman/customization/namespace/link.go
- pkg/api/norman/customization/namespace/namespace.go
- pkg/api/norman/customization/persistentvolumeclaim/validator.go
- pkg/api/norman/customization/pipeline/pipeline_execution_log.go
- pkg/api/norman/customization/workload/workload.go
- pkg/api/norman/store/apiservice/filter.go
- pkg/clustermanager/manager.go
- pkg/controllers/management/auth/user.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/controllers/management/clusterstats/statsaggregator.go
- pkg/controllers/management/k3sbasedupgrade/deployPlans.go
- pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
- pkg/controllers/managementuserlegacy/logging/deployer/appdeployer.go
- pkg/controllers/managementuserlegacy/logging/deployer/testerdeployer.go
- pkg/metrics/metrics.go
- pkg/multiclustermanager/app.go
- pkg/multiclustermanager/deferred.go
- pkg/pipeline/engine/engine.go
- pkg/pipeline/engine/jenkins/engine.go
- pkg/pipeline/engine/jenkins/minio.go
- pkg/rbac/access_control.go
The norman API layer should no use any caches from the down stream cluster.  This causes scaling issues.
#35565
> Limit norman API use of downstream cluster caches

- pkg/auth/providers/keycloakoidc/keycloak_provider.go
- pkg/auth/providers/oidc/oidc_provider.go
**Issue**
https://github.com/rancher/rancher/issues/33916
**Problem**
Keycloak OIDC and OIDC providers refresh the access token, but do not store the refreshed token so once the initial access token is expired for the session, all calls will get a fresh token. This just causes more calls to happen than need to. 
**Solution**
For Keycloak OIDC, use a different method to get the access token than was being used previously. One the token is fetched, validate if it is different than the one that was fetched from the secret. If it is different, then update the secret to have the new token.
For OIDC, I left the existing calls for the tokens, but I store the token that was passed in as a separate var and validate it against the one that is returned from the existing call. If it is different, …
> Ensure keycloak oidc and oidc tokens refresh, and update store

- pkg/controllers/managementuser/healthsyncer/healthsyncer.go
- Rancher server panics when cluster.status.version is empty
Stats aggregator writes the cluster status, so we can continue relying on status version but return nil if it's not updated yet 
https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/clusterstats/statsaggregator.go#L163
https://github.com/rancher/rancher/issues/35627
- Parsing eks v2 version doesn't work with normal semver parsing because gitVersion minor has "21+".  
Upstream library has parseSemantic, but can't use it directly since it returns numbers + extra, so using the first part https://github.com/kubernetes/apimachinery/blob/v0.22.3/pkg/util/version/version.go#L43-L47 
https://github.com/rancher/rancher/issues/35628
> fix semver parsing of cluster status version

- scripts/package
If we want to print the array completely in the shell, we should use ${xxx[@]} instead of ${xxx}.
Example:
```
tt=( "1 2 3 4 5" )
echo ${tt}
echo ${tt[@]}
```
It does not seem to make a difference, however, if we do this:
```
tt=( `echo 1+ 2+ 3+ 4+ 5+ | tr + -` )
echo ${tt}
echo ${tt[@]}
```
This happens to cause some images to be missing, as shown in the figure:
> Fix the issue of missing images in rancher-images.txt

- Dockerfile.dapper
- go.mod
- go.sum
- package/Dockerfile
- package/entrypoint.sh
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/client/generated/management/v3/zz_generated_cloud_provider.go
- pkg/client/generated/management/v3/zz_generated_harvester_cloud_provider.go
- scripts/etcd.sh
- scripts/validate
Issue [33850](https://github.com/rancher/rancher/issues/33850). Exploratory issue that removes the downloaded etcd binary and starts Rancher single node k3s cluster with embedded etcd.
- Rip etcd binary and env vars out of rancher/rancher Dockerfile.dapper and package/Dockerfile
- Update the Norman API
- Remove handler function RunETCD that starts etcd
- Remove —datastore-endpoint
- Start k3s server with —cluster-init (which will use embedded etcd)
- Remove etcd binary and env vars
- Update K3S_URL in Dockerfile to avoid overwriting k3s server url during setup
- Update go.mod to reference changes in Norman API (the k3s server initialization is done in the Norman API and that's where the other half of these changes are)
- Fix bug in the validate script
- Add missing /var/lib/rancher …
> [2.6.3] Rip out etcd binary

- pkg/api/norman/customization/cluster/validator.go
A cluster owner should be able to edit a cluster without changing the
cloud credential. Therefore, if the edit isn't changing the cloud
credential, then Rancher shouldn't validate that the user has access to
the cloud credential.
After this change, Rancher validates that the user has access to the
cloud credential only if they are trying to update it.
Issue:
https://github.com/rancher/rancher/issues/35413
> Skip cloud cred check if it is not changed

- .gitignore
I vendor dependencies in my repos to speed up indexing in goland.
> ignore vendor folder

- chart/templates/secret.yaml
#34686
When upgrading from 2.6.0+ the bootstrap secret was being deleted because helm did not render the template unless the password was set.  This update copies the value of an existing secret if it is found and stops the secret from being deleted.
> fixed bootstrap password being deleted on upgrade

- tests/validation/tests/v3_api/common.py
Added fix for below nodeport and clusterIp related testcases:
- tests.v3_api.test_workload.test_wl_with_nodePort
- tests.v3_api.test_workload.test_wl_with_nodePort_scale_and_upgrade
- tests.v3_api.test_workload.test_wl_with_clusterIp
- tests.v3_api.test_workload.test_wl_with_clusterIp_scale_and_upgrade
> Add fix for nodePort and clusterIp flaky tests

- tests/validation/tests/v3_api/test_cluster_templates.py
`test_cluster_template` tests fail due to incorrect image sizes passed ("4gb" and "8gb") and cluster would not provision
This PR updates automation to use correct DO images and make clusters provision
> Update size for do images

- pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go
There is an intermittent issue when provisioning RKE2 clusters where a node may
seem to get stuck in "Ready is False" state. This is a red-herring because the
node is Ready, but the CAPI machine controller is not picking up this change.
In order to force the CAPI machine controller to see that the node is ready,
Rancher will wait to set the providerID on the infrastructure machine until the
Node is Ready. This ensures that the CAPI controller sees the Node in a ready
state.
Issue:
https://github.com/rancher/rancher/issues/35714
> Fix race on node Ready condition on provision

- pkg/api/norman/server/userstored/setup.go
- pkg/api/norman/store/ingress/store.go
Without this change, the norman store proxy setup chooses the Ingress
API to register based on the local cluster context at startup. It does
not know about other clusters at this point and can't register different
APIs on a cluster-by-cluster basis. This causes a problem when the local
cluster is version 1.18 (does not support networking.k8s.io/v1/Ingress)
and the downstream cluster is 1.22 (does not support
extensions/v1beta1/Ingress) or vice versa, where when the user tries to
navigate to the downstream cluster the wrong Ingress API will have been
registered and the Watch will fail with a 404 error.
This change addresses the problem by first statically registering the
networking.k8s.io/v1/Ingress API into the schema store on the assumption
that this will be used most of the time, and …
> Dynamically choose Ingress proxy store

- pkg/controllers/managementuser/healthsyncer/healthsyncer.go
**Issue:**
Cluster state switches between Active and Unavailable (agent disconnected) after provisioning https://github.com/rancher/rancher/issues/35640 
**Problem**
We set clusterConditionReady and connected to false if cluster agent isn't connected (steve session for cluster doesn't exist https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/clusterconnected/clusterconnected.go#L111) in https://github.com/rancher/rancher/pull/35545. Health syncer tries to get component status and updates cluster conditionReady to true even
if session doesn't exist. So the cluster state keeps switching between active and agent disconnected.
**Solution:**
If cluster agent isn't connected, we shouldn't set the cluster condition ready to true.
> don't set clusterConditionReady to true if connected is false

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
**Issue:** 
Not able to import rke1 clusters https://github.com/rancher/rancher/issues/35650
**Problem** 
For the first cluster agent deployed through template generated by cluster import handler, [CATTLE_FEATURES is empty ](https://github.com/rancher/rancher/blob/release/v2.6/pkg/api/norman/customization/clusterregistrationtokens/import.go#L49) so rancher isn't running. Without secret and aggregation controllers running, session with clientKey `"stv-cluster-{clusterName}"` never gets added for clusters.
hasSession will always remain false until cluster agent is redeployed (during redeploy, CATTLE_FEATURES is set) and then connected becomes true. But [we blocked redeploy if connected is false](https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/clusterdeploy/clu …
> redeploy cluster agent for imported clusters even if connected is false

- pkg/controllers/provisioningv2/rke2/planner/controller.go
- pkg/provisioningv2/rke2/planner/planner.go
The planner would run for a deleted cluster. When the etcd nodes were removed,
this would cause Rancher logs to be spammed by "waiting for bootstrap node"
logs.
With this change, the planner will no longer consider clusters that are deleted.
Issue:
https://github.com/rancher/rancher/issues/35730
> Stop planner controller for deleted clusters

- pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
- pkg/controllers/management/clusterupstreamrefresher/eks_upstream_spec.go
In the current implementation, an error was not checked, which led to all
nodegroups being deleted when an error was received from the AWS API when
listing nodegroups. Now, the error is checked and no deletion should occur.
In addition, to avoid setting the upstreamSpec to nil on refresh, each config on
the `upstreamConfig` object is nil-checked. At least one of them should not be
nil for the refresh to proceed.
Issue:
https://github.com/rancher/rancher/issues/35809
Original PR:
https://github.com/rancher/rancher/pull/35810
> [2.5] Fix EKS nodegroup deletion on AWS API error

- pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
Previously, when an error was received in the upstream refresher, only the
`upstreamConfig` was nil-checked. However, if retrieving the upstreamSpec
failed, then `upstreamConfig` would not be nil, but the corresponding cluster
config would be. Therefore, in addition to checking the `upstreamConfig` for
nilness, the individual cluster configs are also checked. At least one of them
should be non-nil for syncing to proceed.
Issue:
https://github.com/rancher/rancher/issues/35804
> Check for nil clusterSpec in kev2 refresher

- pkg/api/norman/customization/app/app.go
- pkg/api/norman/server/managementstored/setup.go
- pkg/types/config/context.go
**Problem:**
Prior, if a dashboard app already existed with the same ID in a
namespace that matched the targetNamespace of the
apps.project.cattle.io being created, they would be linked to
the same helm resources. This means changing one changed the
other.
**Solution:**
Now, an apps.project.cattle.io cannot be created if
a apps.catalog.cattle.io already exists with the same ID in
a namespace matching its targetNamespace.
**Issue:**
https://github.com/rancher/rancher/issues/35684
> Check if matching dashboard app exists

- pkg/multiclustermanager/routes.go
The following URLs will work from kdm data
/v1-rke2-release/channels
/v1-k3s-release/channels
> Expose channels for rke2/k3s channel servers

- pkg/controllers/managementuserlegacy/helm/controller.go
This is a code change for a reopened issue [20654](https://github.com/rancher/rancher/issues/20654).
App revisions on retrieval and listing were sorted by creation timestamp. My code used to rely on that behavior. It appears to have changed, but I don't know how or where. So it's best to explicitly sort app revisions by creation timestamp and delete the oldest revisions, as needed, according to this order.
> [2.6.3] Explicitly sort app revisions by creation timestamp

- pkg/controllers/managementuser/helm/controller.go
This is a code change for a reopened issue [20654](https://github.com/rancher/rancher/issues/20654).
App revisions on retrieval and listing were sorted by creation timestamp. My code used to rely on that behavior. It appears to have changed, but I don't know how or where. So it's best to explicitly sort app revisions by creation timestamp and delete the oldest revisions, as needed, according to this order.
> Explicitly sort app revisions by creation timestamp

- pkg/controllers/provisioningv2/rke2/machineprovision/controller.go
- pkg/controllers/provisioningv2/rke2/machineprovision/template.go
There were a few issues related to job cleanup on deletion. Jobs were getting
deleted and recreated too quickly. In addition, jobs were being leftover after
deletion that was exacerbating the problem.
After this change, jobs should not be left over and machine deletion should not
hang because Wrangler will be able to clean up old jobs before creating new
ones.
Issue:
https://github.com/rancher/rancher/issues/35823
> Ensure proper job cleanup

- tests/validation/tests/Dockerfiles/windows/metrics/Dockerfile
- tests/validation/tests/Dockerfiles/windows/nginx/Dockerfile
- tests/validation/tests/Dockerfiles/windows/testcontainer/Dockerfile
per this issue https://github.com/containerd/containerd/issues/6300 and a bunch of testing it looks like the way we were doing things with our test images was the CMD style that worked in docker and we needed to update to the string array format for containerd to work properly. additionally removed maintainers that no longer work at rancher
> updates to windows dockerfiles tp work on both docker and containerd

- pkg/controllers/management/k3sbasedupgrade/template.go
Issue:
Starting Rancher v2.6.0, serviceAccountName for k3s upgrader genericPlan was updated. But genericPlan is used only for creates (generateMasterPlan and generateWorkerPlan). On updates (configureMasterPlan and configureWorkerPlan), it picks the name from existing plan so it gets the old svc account name if the plans were created before Rancher 2.6.
https://github.com/rancher/rancher/issues/35797
> set default serviceAccountName to k3s upgrader plan on updates

- pkg/api/scheme/scheme.go
This commit excludes ClusterMonitorGraphList and ProjectMonitorGraphList from norman typers.
Related to https://github.com/rancher/rancher/pull/34847.
Related Issue: https://github.com/rancher/rancher/issues/35760
> Exclude ClusterMonitorGraphList and ProjectMonitorGraphList from norman typers

- pkg/types/config/context.go
If two controller goroutines both run deferred start it is possible to deadlock
as one goroutine is holding the start lock and waiting for the controllers
to start and the other gorouting is trying to get the start lock to wait
for the controllers to start.  Since both can not move forward the
controller start is deadlocked.
> Don't block controller thread with deferred start

- pkg/api/norman/customization/app/app.go
- pkg/api/norman/customization/catalog/store.go
- pkg/api/norman/customization/cluster/actions_monitoring.go
- pkg/api/norman/customization/multiclusterapp/multi_cluster_app.go
- pkg/api/norman/customization/multiclusterapp/store.go
- pkg/api/norman/store/app/store.go
- pkg/catalog/manager/manager.go
**Problem:**
Prior, if an app that was installed prior was rendered incompatible
due to a rancher upgrade, updates to the app would fail. This would
happen even if the update was not to the app version.
**Solution:**
Now, apps can
be updated if their current version is incompatible as long as they
are not updating to another incompatible app version.
**Issue:**
https://github.com/rancher/rancher/issues/35904
> Accept preexisting incompatible app versions

- pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go
The systemDefaultRegistry was put in at the incorrect level (global
.systemDefaultRegistry) for the latest version of the SUC chart. This change
bumps the systemDefaultRegistry to the correct level (global.cattle
.systemDefaultRegistry) so the chart picks it up properly.
Issue:
https://github.com/rancher/rancher/issues/35485
> Adjust values YAML systemDefaultRegistry

- pkg/provisioningv2/rke2/planner/planner.go
An if-statement kept the system-default-registry setting from being added to the
config for K3S clusters. This was a mistake. This change will set the
system-default-registry setting regardless of runtime.
Issue:
https://github.com/rancher/rancher/issues/35922
> Set system-default-registry for K3S clusters

- pkg/controllers/dashboardapi/controller.go
- pkg/controllers/dashboardapi/settings/settings.go
Absorbs partial changes from https://github.com/rancher/rancher/commit/261ce1344cda47126431636540b5fb6c08dcea7d#
Due to a change introduced in https://github.com/rancher/rancher/pull/35508, we need to ensure that the settings controller is started in downstream so that the downstream are capable of getting the InstallUUID setting to allow it to add chart repositories.
Related Issue: https://github.com/rancher/rancher/issues/35820
> Register settings controller in downstream
