pkg/controllers/user/networkpolicy/podhandler.go
Problem:
We add label field.cattle.io/podName to pods with host ports when network policy is enabled.
This is an issue for nginx ingress controller because it finds running pods by filtering pods
using label selector.
Solution:
We shouldn't add this label to pods of any system ns, no network policies get implemented
for system namespaces.
https://github.com/rancher/rancher/issues/28230
https://github.com/rancher/rancher/issues/26677
=> [v2.4] don't add hostport podname label for system ns pods

pkg/api/norman/store/cluster/cluster_store.go, pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/28739
=> Use cluster dialer for checking s3 availability

pkg/api/norman/store/cluster/cluster_store.go, pkg/controllers/management/etcdbackup/etcdbackup.go
Backport of https://github.com/rancher/rancher/pull/29537
https://github.com/rancher/rancher/issues/28739
=> [release/v2.5] Use cluster dialer for checking s3 availability

pkg/api/store/cluster/cluster_store.go, pkg/controllers/management/etcdbackup/etcdbackup.go
Backport of https://github.com/rancher/rancher/pull/29537
https://github.com/rancher/rancher/issues/28739
=> [release/v2.4] Use cluster dialer for checking s3 availability

go.mod, go.sum, pkg/apis/management.cattle.io/v3/authn_types.go, pkg/auth/providers/saml/saml_client.go
Backport of https://github.com/rancher/rancher/pull/29555
https://github.com/rancher/rancher/issues/29212
=> [2.5] Make Keycloak entity ID configurable

pkg/controllers/management/clusterprovisioner/provisioner.go
Backport of https://github.com/rancher/rancher/pull/29375
=> [release/v2.5] k8s version unset typo

pkg/controllers/management/clusterprovisioner/provisioner.go, pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
=> [forwardport] Disable kubernetes upgrades on embedded cluster

pkg/controllers/dashboard/helm/apps.go
https://github.com/rancher/rancher/issues/29460#issue-718459237
=> Handle and ignore all errors processing configmaps/secrets for helm

pkg/controllers/management/eks/eks_cluster_handler.go
**Original PR**:
https://github.com/rancher/rancher/pull/29576
**Issue:**
https://github.com/rancher/rancher/pull/29576
=> [EKSv2][Backport]2.5: Eks redeploy fix v2.5

pkg/controllers/managementuser/networkpolicy/podhandler.go
Problem:
We add label field.cattle.io/podName to pods with host ports when network policy is enabled.
This is an issue for nginx ingress controller finds running pods by filtering pods
using label selector.
Solution:
We shouldn't add this label to pods of any system ns, no network policies get implemented
for system namespaces.
https://github.com/rancher/rancher/issues/28230
https://github.com/rancher/rancher/issues/26677
=> [2.5] don't add hostport podname label for system ns pods

pkg/controllers/dashboard/helm/apps.go
Backport of https://github.com/rancher/rancher/pull/29477
https://github.com/rancher/rancher/issues/29460
=> [2.5] Handle and ignore all errors processing configmaps/secrets for helm

pkg/controllers/managementuser/networkpolicy/podhandler.go
Problem:
We add label field.cattle.io/podName to pods with host ports when network policy is enabled.
This is an issue for nginx ingress controller finds running pods by filtering pods
using label selector.
Solution:
We shouldn't add this label to pods of any system ns, no network policies get implemented
for system namespaces.
https://github.com/rancher/rancher/issues/28230
https://github.com/rancher/rancher/issues/26677
=> don't add hostport podname label for system ns pods

pkg/auth/data/authconfig_data.go, pkg/catalogv2/helmop/operation.go, pkg/controllers/dashboardapi/controller.go, pkg/controllers/dashboardapi/settings/settings.go, pkg/controllers/managementuser/agentupgrade/controller.go, pkg/controllers/managementuser/controllers.go, pkg/controllers/managementuser/endpoints/endpoints.go, pkg/controllers/managementuser/endpoints/workload_endpoints.go, pkg/multiclustermanager/app.go, pkg/multiclustermanager/deferred.go, pkg/rancher/rancher.go, pkg/wrangler/context.go
#29461
#29397
#29364
#29357
#29238
#29201
#22790
=> [2.5] Various cherry picks

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/29615
=> add not found checks on cluster lookup

pkg/controllers/management/controller.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go, pkg/controllers/management/rkeworkerupgrader/upgrade.go, pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go, pkg/node/node.go
https://github.com/rancher/rancher/issues/18221
=> [v2.5] [forwardport] Vsphere Drain on Delete for Cloud Providers

chart/templates/service.yaml, cmd/rancherd/chart/templates/service.yaml, pkg/tls/tls.go
Open a different port in rancher for tls so that fleet can talk to this
internal tls port with ca
=> Listen tls on a different port with unique certs

pkg/tls/tls.go
Do not setup listener if httpsPort is zero. This is because when agent
deploys it only listens to httpsPort which requires cacerts setting to
be set. Agent will not install any settings because of the usecase for
rancher in rancher(otherwise setting will be overriden)
=> Fix cluster agent failed to start if no ca setting

pkg/controllers/management/controller.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go, pkg/controllers/management/rkeworkerupgrader/upgrade.go, pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go, pkg/node/node.go
=> [master] [forwardport] Vsphere Drain on Delete for Cloud Providers

go.mod, go.sum, pkg/api/norman/store/cluster/cluster_store.go, pkg/client/generated/management/v3/zz_generated_node_upgrade_strategy.go, pkg/controllers/management/rkeworkerupgrader/upgrade.go
https://github.com/rancher/rke/pull/2278
=> upgraded rke for new nodeupgradestrategy

pkg/settings/setting.go
https://github.com/rancher/rancher/issues/29325
=> [2.5] Add setting to hide local cluster

pkg/settings/setting.go
forward port of https://github.com/rancher/rancher/pull/29684
https://github.com/rancher/rancher/issues/29325
=> Add setting to hide local cluster

pkg/controllers/managementuser/agentupgrade/controller.go
https://github.com/rancher/rancher/issues/29690
=> Only delete the local agents if the CATTLE_SERVER_URL matches

tests/integration/suite/test_alert.py, tests/integration/suite/test_dynamic_schemas.py
Forward port of https://github.com/rancher/rancher/pull/29675
=> Fix flaky tests test_dynamic_schemas_update, test_alert_access

go.mod, go.sum, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/22790
=> Fix service accounts for clusterrepos

chart/templates/ingress.yaml
**Problem** 
Spec changes needed for new apiVersion
**Solution**
Spec has been updated to match new apiVersion requirements
**Issue**
=> Change ingress spec when using newest apiVersion

tests/integration/suite/conftest.py
Forward port of https://github.com/rancher/rancher/pull/29689
=> Increase default timeout to avoid test failures

go.mod, go.sum, pkg/settings/setting.go
Backport https://github.com/rancher/rancher/pull/29694
https://github.com/rancher/rancher/issues/22790
=> [2.5] Fix service accounts for clusterrepos

chart/templates/ingress.yaml
**Backport**
**Problem**
Spec changes needed for new apiVersion
**Solution**
Spec has been updated to match new apiVersion requirements
**Issue**
#29144
**Master PR**
https://github.com/rancher/rancher/pull/29709
=> [ 2.5.2 ]Change ingress spec when using newest apiVersion

go.mod, go.sum, pkg/api/steve/clusters/clusters.go
https://github.com/rancher/rancher/issues/29511
=> Ensure that non-privileged users can still get to the shell

go.mod, go.sum, pkg/api/steve/clusters/clusters.go
=> [2.5] Ensure that non-privileged users can still get to the shell

go.mod, go.sum
PROBLEM:
go.mod was pointing to a repo owned by paynejacob
SOLUTION:
updated go.mod to use rancher
=> removed all paynejacob modules

go.mod, go.sum
BACKPORT: https://github.com/rancher/rancher/pull/29722
=> [2.5]  removed all paynejacob modules backport

go.mod, go.sum, vendor/github.com/rancher/rke/cluster/cluster.go, vendor/github.com/rancher/rke/cluster/defaults.go, vendor/modules.txt
https://github.com/rancher/rancher/issues/29745
=> [2.4] vendor update rke

pkg/controllers/managementuser/endpoints/endpoints.go, pkg/controllers/managementuser/endpoints/workload_endpoints.go
=> Disable all endpoints for local cluster if rancher agent is present.

go.mod, go.sum, pkg/api/steve/catalog/operation.go, pkg/api/steve/clusters/clusters.go
https://github.com/rancher/dashboard/issues/1693
=> Show states on relationships

pkg/controllers/managementuser/endpoints/endpoints.go, pkg/controllers/managementuser/endpoints/workload_endpoints.go
https://github.com/rancher/rancher/issues/29461
Backport of https://github.com/rancher/rancher/pull/29746
=> [2.5] Disable all endpoints for local cluster if rancher agent is present.

go.mod, go.sum
https://github.com/rancher/rancher/issues/29745
=> [2.5] vendor update rke

go.mod, go.sum, pkg/api/steve/catalog/operation.go, pkg/api/steve/clusters/clusters.go
Backport of https://github.com/rancher/rancher/pull/29743
https://github.com/rancher/dashboard/issues/1693
=> [2.5] Show states on relationships

tests/validation/tests/v3_api/resource/cluster.yml, tests/validation/tests/v3_api/test_import_cluster.py
Adding k8s version as a parameter to import cluster.
=> Adding K8s version for import clusters

pkg/controllers/management/nodepool/nodepool.go
Problem: Till k8s 1.18.10, the k8s node lifecycle controller sets these two taints on an unreachable node (or a node with Ready=Unknown): `node.kubernetes.io/unreachable:NoSchedule` and `node.kubernetes.io/unreachable:NoExecute`.
In k8s 1.19.3, the node controller is only setting the taint with NoSchedule effect for such a node.
The rancher nodepool controller checks for the presence of a taint with key `node.kubernetes.io/unreachable` and effect `NoExecute` when determining if a node is unreachable and needs to be replaced. Since the node in 1.19 does not get this taint, nodepool controller does not consider it as unreachable.
Solution: Modify the check in nodepool controller to consider a node unreachable even if only the taint key matches
`node.kubernetes.io/unreachable`. The taint …
=> Match unreachable taint key without comparing effect

pkg/controllers/management/nodepool/nodepool.go
Backport of https://github.com/rancher/rancher/pull/29790
Problem: Till k8s 1.18.10, the k8s node lifecycle controller sets these two taints on an unreachable node
(or a node with Ready=Unknown): `node.kubernetes.io/unreachable:NoSchedule` and `node.kubernetes.io/unreachable:NoExecute`.
In k8s 1.19.3, the node controller is only setting the taint with NoSchedule effect for such a node.
The nodepool controller checks for the presence of a taint with key `node.kubernetes.io/unreachable` and effect `NoExecute`
when determining if a node is unreachable and needs to be replaced. Since the node in 1.19 does not get this taint, nodepool
controller does not consider it as unreachable.
Solution: Modify the check in nodepool controller to consider a node unreachable even if only the taint key …
=> [2.5] Match unreachable taint key without comparing effect

pkg/catalogv2/http/download.go, pkg/controllers/dashboard/helm/repo.go
This needs to go in for 2.5.2
Original PR:
https://github.com/rancher/rancher/pull/29789
Related Issue:
https://github.com/rancher/rancher/issues/29557
=> [2.5] Fix helm repo constant refreshing

pkg/kontainer-engine/drivers/gke/gke_driver.go
The basic was used to generate an access token. However, the access
token was also being generated when getting a service client. Instead of
using the basic auth, we now use the access token.
Issues:
https://github.com/rancher/rancher/issues/29587
=> Remove basic auth for GKE

pkg/controllers/management/clusterstats/statsaggregator.go
https://github.com/rancher/rancher/pull/29793
**Issue:**
https://github.com/rancher/rancher/pull/29793
=> [Backport] 2.5: Worker node labels v2 v2.5

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/29801
=> [master] rewrite context/error checking in node controller

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/29801
=> [v2.5] rewrite context/error checking in node controller

tests/integration/suite/test_node.py
This test was timing out. Instead of waiting for the file to be written
to disk, the tests waits for the node to have a certain condition. This
indicates that the test is ready to check for the file.
Related Issue:
https://github.com/rancher/tasks/issues/1
=> Fix test_writing_config_to_disk timeout issues

pkg/catalogv2/helmop/operation.go
For uninstall action it is called on app we need to fetch cluster repo
from annotation.
=> Use annotation to fetch cluster repo info for uninstall

pkg/controllers/management/k3sbasedupgrade/register.go, pkg/controllers/managementagent/monitoring/register.go, pkg/controllers/managementuser/alert/deployer/deployer.go, pkg/controllers/managementuser/cis/register.go
https://github.com/rancher/rancher/pull/29876
=> [Backport] 2.5: Fix catalog panics v2.5

chart/templates/ingress.yaml
=> add ingress pathtype

go.mod, go.sum, pkg/apis/go.mod
=> [v2.5] vendor update rke

chart/templates/ingress.yaml
issue: https://github.com/rancher/rancher/issues/29144
PRs: 
* https://github.com/rancher/rancher/pull/29507/commits/07b00850e7bce6e6fb46c067dd24cdce97e7c426
* https://github.com/rancher/rancher/pull/29643/commits/ec81ef251b504639c5a19de3ce0a00c688492b9a
* https://github.com/rancher/rancher/pull/29721/commits/4fd54803e293fd3f352958ba6af57ac53565fbc9
* https://github.com/rancher/rancher/pull/29878/commits/4021ecbae7f309760c8d987dc121e329cbc8975c
=> revert ingress bump [2.5]

chart/templates/ingress.yaml
=> revert ingress bump [master]

tests/validation/tests/v3_api/resource/squid/squid.conf, tests/validation/tests/v3_api/test_proxy.py
* Creates a proxy server
* Creates a Rancher semi-airgapped configured to use the proxy (no public IP)
* Allows to create nodes for a custom cluster which are configured to use the proxy
=> Validation - Add proxy setup

tests/validation/tests/v3_api/test_hosted_eks_cluster.py
After latest changes for EKS v2, all API params need to be passed while creating a cluster.
=> Adding fixes for EKS v2 changes

.drone.yml, manifest-agent-head.tmpl, manifest-agent.tmpl
Adding support for Windows 2004 Build Hosts
https://github.com/rancher/rancher/issues/27451
=> [v2.4] Adding Windows 2004 Builds

package/Dockerfile
Forward port of https://github.com/rancher/rancher/pull/29970/files
=> Update CLI and UI tags for 2.5.2-rc7

.drone.yml
https://github.com/rancher/rancher/issues/30015
=> [Forwardport] Fixes notification for helm chart promotion via right indentation

tests/validation/tests/v3_api/test_hosted_eks_cluster.py
This PR adds fixes needed for imported cluster testing to keep up with recent changes.
=> EKS imported cluster fix

.drone.yml
=> Fixes notification for helm chart promotion via right indentation [2.4]

chart/templates/ingress.yaml
Reverts https://github.com/rancher/rancher/pull/29888
=> Add apiVersion changes back in

pkg/catalogv2/http/download.go
If a Helm repo URL contained query parameters (e.g. a token required for authentication) then these query parameters were lost while constructing the chart download URL from the repository base and relative chart URL.
See https://github.com/rancher/rancher/issues/30068 for details.
=> Support helm repository URLs that contain query parameters

pkg/controllers/managementuser/logging/generator/templatesource.go
[2.5] Backport https://github.com/rancher/rancher/pull/29806
=> [Backport] Added nanoseconds to project-container [master] 

pkg/controllers/managementuser/logging/generator/templatesource.go
[2.5] Backport https://github.com/rancher/rancher/pull/29806
=> [Backport] Added nanoseconds to project-container [2.5] 

tests/validation/tests/v3_api/test_airgap.py
Problem:
The method name `add_cluster_to_rancher` is confusing. It sounds like it will add a cluster to Rancher while it actually runs the registry command on a list of nodes. 
Solution:
Remove this method since it is being used at only 3 places and 2 of them are passed in only 1 node.
=> remove ambiguous methods.

tests/integration/suite/test_workloads.py
Backport for PR: https://github.com/rancher/rancher/pull/30100
=> [2.5] Add rollback actions test note for 2.4 and below

package/windows/bootstrap.ps1
https://github.com/rancher/rancher/issues/30148
=> add mirantis check + typos/grammar

pkg/catalog/manager/manager.go
https://github.com/rancher/rancher/pull/30154
=> [Backport] v2.5: Fix version panic v2.5

pkg/api/norman/customization/catalog/store.go, pkg/api/norman/customization/catalog/store_test.go, pkg/catalog/manager/manager.go
**Original PR**:
https://github.com/rancher/rancher/pull/29933
**Issue:**
https://github.com/rancher/rancher/issues/29773
=> [Backport] 2.5: Cluster name option v2.5

pkg/controllers/dashboard/fleetcharts/controller.go
Co-authored-by: Dan Ramich <dramich@users.noreply.github.com>
=> [2.5] Backport http proxy fleet

pkg/clustermanager/manager.go
Problem:
When a cluster agent is diconnected rancher tries to start the
controllers in a slow loop, but this causes a memory leak. The leak
stems from adding a handler in client-go which has no method to
deregister the handler so a fixed size array leaks every time.
Solution:
Don't create access control until Rancher has verified a connection to
the cluster which is a good indication controllers will start. There is
technically a small leak here every time we start these controllers.
https://github.com/rancher/rancher/issues/29429
=> [forwardport] Move creation of accesscontrol

go.mod, go.sum
Backport of https://github.com/rancher/rancher/pull/29691
=> [2.5] Update provider detector to include rke.windows

package/windows/bootstrap.ps1
https://github.com/rancher/rancher/issues/30159
=> [v2.5] add mirantis check + typos/grammar

pkg/clustermanager/manager.go
Reverts rancher/rancher#30122
Reverting due to https://github.com/rancher/rancher/issues/30220, will address after release
=> Revert "Move creation of accesscontrol"

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_aci_network_provider.go, pkg/client/generated/management/v3/zz_generated_network_config.go, pkg/client/generated/management/v3/zz_generated_rke_system_images.go, pkg/image/export/main.go
Take in ACI RKE template changes.
=> ACI CNI RKE vendor changes

Dockerfile.dapper, package/Dockerfile, scripts/package
This reverts commit 1125a1e0c22576fbe4e915a7b7dd0b63a64b9fae.
Not including new changes for emergency release v2.4.11
=> [release/v2.4] revert "set to dev-2.x for RC"

pkg/apis/management.cattle.io/v3/authn_types.go, pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/common/ldap/ldap_util.go, pkg/client/generated/management/v3/zz_generated_active_directory_config.go, pkg/client/generated/management/v3/zz_generated_free_ipa_config.go, pkg/client/generated/management/v3/zz_generated_ldap_config.go, pkg/client/generated/management/v3/zz_generated_ldap_fields.go, pkg/client/generated/management/v3/zz_generated_open_ldap_config.go
https://github.com/rancher/rancher/issues/29153
=> Add support for startTLS

go.mod, go.sum
https://github.com/rancher/client-go/pull/4
https://github.com/rancher/rancher/issues/28943
=> updated client-go

go.mod, go.sum
https://github.com/rancher/client-go/pull/4
https://github.com/rancher/rancher/issues/28943
=> [2.5] updated client-go

pkg/kontainer-engine/drivers/gke/gke_driver.go
This reverts commit 1a3e7780f842f42b747ee362a5f1ffebe456dd87.
The tokens being used expire after 1 hour and are not being refreshed. A mechanism for token refresh should be implemented.
Original PR:
https://github.com/rancher/rancher/pull/29818
Issues:
https://github.com/rancher/rancher/issues/30292
=> [2.5] Revert "Remove basic auth for GKE"

pkg/kontainer-engine/drivers/gke/gke_driver.go
This reverts commit 7e5a914b6cb789fe8b21260017ee8fcad32fbb75.
The tokens being used expire after 1 hour and are not being refreshed. A mechanism for token refresh should be implemented.
Original PR:
https://github.com/rancher/rancher/pull/29683
Issues:
https://github.com/rancher/rancher/issues/30292
=> Revert "Remove basic auth for GKE"

pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/dialer/factory.go
A mistake was made in the code for clusters with private API endpoint that caused the cluster/node agents to not be deployed.
Issue:
https://github.com/rancher/rancher/issues/30325
=> Fix deploy agents

go.mod, go.sum, pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go
Forward-port https://github.com/rancher/rancher/pull/30296
=> [master] ForwardPort: Forward port windows

pkg/controllers/managementagent/monitoring/operatorHandler.go
Problem:
We used to just log error when failed to deploy/withdraw systemMonitor, if it failed to deploy prometheus-operator, no error return cause operator isn't get deployed until next time cluster sync.
Solution:
Return error when failed to deploy/withdraw systemMonitor
Issue:
https://github.com/rancher/rancher/issues/29318
=> Fix missing handle error cause prometheus-operator dosen't deploy

pkg/data/management/kontainerdriver_data.go, tests/integration/suite/test_rbac.py
Add built-in driver for Open Telekom Cloud container engine
=> Add built-in OTC CCE driver

pkg/controllers/managementagent/monitoring/operatorHandler.go
Problem:
We used to just log error when failed to deploy/withdraw systemMonitor, if it failed to deploy prometheus-operator, no error return cause operator isn't get deployed until next time cluster sync.
Solution:
Return error when failed to deploy/withdraw systemMonitor
Issue:
https://github.com/rancher/rancher/issues/29318
=> [2.5] Fix missing handle error cause prometheus-operator dosen't deploy

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_dns_config.go, pkg/client/generated/management/v3/zz_generated_ingress_config.go, pkg/client/generated/management/v3/zz_generated_monitoring_config.go, pkg/client/generated/management/v3/zz_generated_network_config.go, pkg/client/generated/management/v3/zz_generated_toleration.go
=> [2.5] Update RKE module to 816d4cd130a9

pkg/data/dashboard/fleet.go
Forward-port of https://github.com/rancher/rancher/pull/30353
=> [Master] Add UI labels for fleet roles

pkg/controllers/management/clusterdeploy/clusterdeploy.go
Issue:
https://github.com/rancher/rancher/issues/29907
Original PR:
https://github.com/rancher/rancher/pull/30358
=> [2.5] Remove private endpoint check when deploying agent

go.mod, pkg/api/norman/customization/clusterregistrationtokens/import.go, pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/systemtemplate/import.go, pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/24636
Backport of https://github.com/rancher/rancher/pull/30304
=> [release/v2.5] Add tolerations for cattle-cluster-agent

tests/validation/tests/v3_api/test_import_rke2_cluster.py
This should fix the import job from failing in our new Jenkins environment
=> Ensure new variables are used when importing rke2 cluster

pkg/systemtemplate/import.go, pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/30373
=> Check for taints being nil before templating

pkg/systemtemplate/import.go, pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/30373
Backport of https://github.com/rancher/rancher/pull/30374
=> [release/v2.5] Check for taints being nil before templating

cmd/rancherd/go.mod, cmd/rancherd/go.sum, package/Dockerfile.runtime
issue: https://github.com/rancher/rancher/issues/29825
=> bump rke2 version to v1.18.12+rke2r2

cmd/rancherd/go.mod, cmd/rancherd/go.sum, package/Dockerfile.runtime
master pr : https://github.com/rancher/rancher/pull/30389
issue : https://github.com/rancher/rancher/issues/29825
=> [2.5]bump rke2 version to v1.18.12+rke2r2

pkg/clustermanager/manager.go
Problem:
When a cluster agent is diconnected rancher tries to start the
controllers in a slow loop, but this causes a memory leak. The leak
stems from adding a handler in client-go which has no method to
deregister the handler so a fixed size array leaks every time.
Solution:
Don't create access control until Rancher has verified a connection to
the cluster which is a good indication controllers will start. There is
technically a small leak here every time we start these controllers.
https://github.com/rancher/rancher/issues/29429
=> Move creation of accesscontrol

pkg/node/node.go
https://github.com/rancher/rancher/issues/30430
=> [master] Fix panic when deleting a node in provisioning state

pkg/node/node.go
https://github.com/rancher/rancher/issues/30430
backport of: https://github.com/rancher/rancher/pull/30454
=> [release/v2.4] Backport: Fix panic when deleting a node in provisioning state

pkg/node/node.go
https://github.com/rancher/rancher/issues/30430
backport of: https://github.com/rancher/rancher/pull/30454
=> [release/v2.5] Backport: Fix panic when deleting a node in provisioning state

cmd/rancherd/auth/auth.go
Refactored logic so that only if admin user, globalrolebinding,
clusterrolebinding are created before we create the configmap. The
previous logic gated on whether user has been created which could fail
mid-way if cluster is not fully bootstraped
=> [master] ForwardPort: Reorganize reset-admin to make sure everthing get created

pkg/api/customization/catalog/store.go, pkg/api/customization/catalog/store_test.go, pkg/catalog/manager/manager.go
**Issue:**
https://github.com/rancher/rancher/issues/30497
https://github.com/rancher/rancher/issues/29773
=> [Backport] 2.4: Add clusterName filter to templates GET and tests

pkg/catalogv2/system/system.go
This reverts commit 2104d65c8fdeb1cfe6c2b149790ad7e1ba037053.
=> [master] Revert "Sort chart based on appVersion"

scripts/package
Forward-port of https://github.com/rancher/rancher/pull/30508
=> [master]Add runtime image to image.txt

pkg/api/norman/customization/cluster/actionhandler.go, pkg/api/norman/customization/cluster/actions_key.go
Small oversight on my part in the initial PR. Currently this is not supported, so instead of allowing the key rotation to get to RKE and returning an error, we should prevent the action from being triggered in the first place when there is a custom encryption configuration being used.
Original PR:
- rancher/rancher#30381
=> [2.5] Prevent Key Rotation Action for Custom Config

chart/templates/deployment.yaml, chart/tests/deployment_test.yaml
Issue https://github.com/rancher/rancher/issues/29813
=> [2.5] Updated chart with proper vue volume mount path

pkg/controllers/managementagent/monitoring/clusterHandler.go, pkg/controllers/managementagent/monitoring/operatorHandler.go
Backports https://github.com/rancher/rancher/pull/30540
(cherry picked from commit e851baaee049f9851193e5baa649cd4db9ef273d)
=> [2.5] Allow local cluster to deploy monitoring

go.mod, go.sum
https://github.com/rancher/rancher/issues/28293
=> [release/v2.4] vendor update steve

go.mod, go.sum
=> [2.5] Update RKE

go.mod, go.sum, pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/common/ldap/ldap_util.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_active_directory_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_free_ipa_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_ldap_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_ldap_fields.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_open_ldap_config.go, vendor/modules.txt
https://github.com/rancher/rancher/issues/29810
Types PR: https://github.com/rancher/types/pull/1189
Backports https://github.com/rancher/rancher/pull/30267
=> [2.4] Add support for startTLS

go.mod, go.sum
=> [2.4.12] Update RKE

package/Dockerfile
=> [2.5] UI Bump

pkg/clustermanager/manager.go, pkg/kontainer-engine/drivers/gke/gke_driver.go, pkg/multiclustermanager/capabilities/gke_capabilities.go
Basic authentication is deprecated and will be removed. In preparation for this, basic authentication is removed for GKE clusters.
Issue:
=> Remove basic auth with GKE clusters

pkg/api/norman/store/namespace/store.go
#18877 
Signed-off-by: Jason-ZW <zhenyang@rancher.com>
=> [backport] Fix set default namespace's limitRange bug

pkg/api/norman/store/namespace/store.go
=> Revert "[backport] Fix set default namespace's limitRange bug"

manifest-agent-head.tmpl, manifest-agent.tmpl
https://github.com/rancher/rancher/issues/27451
=> reactivating manifests

.drone.yml, manifest-agent-head.tmpl, manifest-agent.tmpl
https://github.com/rancher/rancher/issues/27451
=> [v2.5] adding windows 2004

chart/README.md
Backport https://github.com/rancher/rancher/pull/30609
=> [release/v2.5] Remove duplicated deploy verification

pkg/api/norman/store/namespace/store.go
https://github.com/rancher/rancher/pull/30671
https://github.com/rancher/rancher/issues/18877
=> [2.5] Fix set default namespace's limitRange bug

pkg/clustermanager/manager.go, pkg/kontainer-engine/drivers/gke/gke_driver.go, pkg/multiclustermanager/capabilities/gke_capabilities.go
Issue:
Original PR:
https://github.com/rancher/rancher/pull/30371
=> [2.5] Remove basic auth with GKE clusters

.drone.yml, manifest-agent-head.tmpl, manifest-agent.tmpl
https://github.com/rancher/rancher/issues/30701
=> [v2.5] add windows 20h2 builds

.drone.yml, manifest-agent-head.tmpl, manifest-agent.tmpl
https://github.com/rancher/rancher/pull/30758#issue-551993282
=> Add 20h2 builds, remove purge from docker builds

.drone.yml, package/windows/Dockerfile.agent.20H2
https://github.com/rancher/rancher/issues/30701
=> 20h2 dockerfile to remove powershell 20h2 image dependency

go.mod, go.sum, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/types.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_container.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_environment_var.go, vendor/github.com/rancher/types/mapper/env.go, vendor/modules.txt
Issue: https://github.com/rancher/rancher/issues/16148
=> [release/v2.4] Vendor types

package/Dockerfile
=> [2.4] Bump rancher/cli version to v2.4.11-rc1

.drone.yml, manifest-agent-head.tmpl, manifest-agent.tmpl
=> fixing tagging/manifest

.drone.yml
=> fixing tags for manifests

pkg/catalogv2/http/download.go
Backports: #30072
Related issue:  #30068
=> [2.5] Support helm repository URLs that contain query parameters

pkg/apis/go.sum, pkg/client/generated/project/v3/zz_generated_condition.go, pkg/client/generated/project/v3/zz_generated_container_resource_metric_source.go, pkg/client/generated/project/v3/zz_generated_container_resource_metric_status.go, pkg/client/generated/project/v3/zz_generated_dns_record.go, pkg/client/generated/project/v3/zz_generated_load_balancer_ingress.go, pkg/client/generated/project/v3/zz_generated_metric.go, pkg/client/generated/project/v3/zz_generated_metric_status.go, pkg/client/generated/project/v3/zz_generated_port_status.go, pkg/client/generated/project/v3/zz_generated_service.go, pkg/client/generated/project/v3/zz_generated_service_spec.go, pkg/client/generated/project/v3/zz_generated_service_status.go
`go generate` currently failing because of https://github.com/rancher/rancher/compare/release/v2.5...kinarashah:gog?expand=1#diff-02864a92729e2b780f972f1fe2a9b0bef5414787ffac408f80e37bba233e95b5L562-L565
=> go generate

.drone.yml
=> fix second 20h2 dockerfile

pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/30782
=> add win path cleaning logic to loglinker bind

pkg/api/norman/customization/clusterregistrationtokens/formatter.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go
Issue:
- rancher/rancher#30605
Original PR:
- rancher/rancher#29769
=> [2.5][Forwardport] Enable agent image to be pulled from private registry

pkg/api/store/cluster/cluster_store.go
Fix issue https://github.com/rancher/rancher/issues/27306
Backport of https://github.com/rancher/rancher/pull/30606
=> [2.4] Fix to properly remove vSphere vCenter server entries

pkg/api/norman/store/cluster/cluster_store.go
Fix issue https://github.com/rancher/rancher/issues/30606
=> [2.5] Fix to properly remove vSphere vCenter server entries

pkg/controllers/management/eks/eks_cluster_handler.go
https://github.com/rancher/rancher/pull/30837
**Issue:**
https://github.com/rancher/rancher/issues/30041
=> [Backport] v2.5: Fix nodegroup msg

pkg/api/norman/store/cluster/cluster_store.go
Issue https://github.com/rancher/rancher/issues/30606
=> Fix to properly remove vSphere vCenter server entries

package/windows/bootstrap.ps1, pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/30782
=> [v2.4] default trailing slash

package/windows/bootstrap.ps1, pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/30966
=> [master] fix windows rke log path

package/windows/bootstrap.ps1, pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/30966
=> [v2.5] fix windows rke log path

Dockerfile.dapper, go.mod, go.sum, package/Dockerfile, vendor/github.com/rancher/rke/cluster/defaults.go, vendor/github.com/rancher/rke/cluster/etcd.go, vendor/github.com/rancher/rke/docker/docker.go, vendor/modules.txt
=> [release/v2.4] v2.4.13 Release

package/Dockerfile, scripts/package
Update system-charts branch for final v2.4.13 RC
=> [release/v2.4] v2.4.13 Final RC

Dockerfile.dapper, package/Dockerfile, scripts/package
=> [release/v2.4] Post Release

pkg/controllers/managementuser/secret/secret.go
https://github.com/rancher/rancher/issues/30666
What happened is that `default-token-X` ServiceAccount tokens were synced from Rancher's project token list, to the downstream cluster. The tokens controller in the downstream cluster will clean those tokens up, as they are ServiceAccount tokens without a ServiceAccount attached to them, see logging below:
```
I0104 15:34:21.546336       1 tokens_controller.go:309] syncSecret(kube-public/default-token-mgbv8), service account does not exist, deleting token
```
For the rewrite-secret feature, we saw that the token was too slow to clean up the tokens after the component restarts, causing the tokens to be in the cluster for up to 30 seconds. This caused the logging to be inaccurate as the total rewritten secrets would include the created …
=> Skip ServiceAccount tokens on secrets sync

pkg/controllers/managementuser/healthsyncer/healthsyncer.go
per @ibuildthecloud removing as it's now ruining a ready check by the UI for pulling kubeconfig and it ultimately didn't do what he expected.
https://github.com/rancher/rancher/issues/30427
=> removing cluster agent check before cluster is ready

pkg/controllers/managementuser/healthsyncer/healthsyncer.go
https://github.com/rancher/rancher/issues/28836
https://github.com/rancher/rancher/issues/30427
=> [master] removing cluster agent check before cluster is ready

pkg/controllers/managementuser/secret/secret.go
https://github.com/rancher/rancher/issues/30666
Backport of https://github.com/rancher/rancher/pull/30693
=> [release/v2.5] Skip ServiceAccount tokens on secrets sync

pkg/api/norman/customization/clusterregistrationtokens/formatter.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go
Issue:
- rancher/rancher#30605
Original PR:
- rancher/rancher#29769
=> [Forwardport] Enable agent image to be pulled from private registry

pkg/api/norman/customization/cluster/formatter.go
Issue: 
- rancher/rancher#30629
Tested with key rotation action, the new behavior is as follows:
- if secret encryption is disabled, the `rotateEncryptionKey` action will be disabled
- if secret encryption is enabled and the cluster is an updating state, `rotateEncryptionKey` action will be disabled
- otherwise `rotateEncryptionKey` is enabled
=> [release/v2.5] Conditionally disable rotateEncryptionKey action in API view

pkg/controllers/management/auth/globalrolebinding_handler.go, pkg/controllers/management/auth/project_cluster_handler.go, pkg/controllers/management/controller.go, pkg/controllers/management/restrictedadminrbac/cluster.go, pkg/controllers/management/restrictedadminrbac/project.go, pkg/controllers/management/restrictedadminrbac/register.go, pkg/data/management/add.go, pkg/data/management/role_data.go, pkg/rbac/common.go
Forward port of https://github.com/rancher/rancher/pull/31102
=> [Forwardport] Restricted admin role changes

go.mod, go.sum, pkg/auth/providers/saml/saml_client.go, pkg/auth/providers/saml/saml_client_cookies.go, pkg/auth/providers/saml/saml_provider.go
FP: https://github.com/rancher/rancher/pull/30858
=> use upstream saml library

go.mod, package/Dockerfile, pkg/catalogv2/system/system.go, pkg/controllers/dashboard/fleetcharts/controller.go, pkg/controllers/management/systemcharts/controller.go, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/30934
=> Add minRequiredVersion for fleet, rancher-operator and webhook

pkg/api/store/cluster/cluster_store.go, pkg/controllers/management/globaldns/globaldns_handler.go, pkg/controllers/management/k3supgrade/k3supgrade_handler.go, pkg/image/export/main.go
https://github.com/rancher/rancher/pull/31041
**Backport Issue:**
https://github.com/rancher/rancher/issues/31122
=> [Backport] v2.4: Fix k3s upgrade dev image export

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_dns_config.go, pkg/client/generated/management/v3/zz_generated_ingress_config.go, pkg/client/generated/management/v3/zz_generated_monitoring_config.go, pkg/client/generated/management/v3/zz_generated_nodelocal.go
Issue: https://github.com/rancher/rancher/issues/30047
=> [release/v2.5] Vendor rke + make addons priority class name configurable

pkg/auth/providers/saml/saml_actions.go, pkg/auth/providers/saml/saml_client.go, pkg/auth/providers/saml/saml_handlers.go, pkg/auth/providers/saml/saml_provider.go
https://github.com/rancher/rancher/issues/30710
=> [master] Prevent panic seen intermittently while logging in with SAML

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Issue: https://github.com/rancher/rancher/issues/30047
=> [release/v2.5] Vendor rke

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_dns_config.go, pkg/client/generated/management/v3/zz_generated_ingress_config.go, pkg/client/generated/management/v3/zz_generated_monitoring_config.go, pkg/client/generated/management/v3/zz_generated_nodelocal.go
Issue: https://github.com/rancher/rancher/issues/30047
To vendor this once merged: https://github.com/rancher/rke/pull/2454
=> [master] Vendor rke

pkg/api/norman/customization/cluster/actions_key.go
Related to:
- rancher/rancher#30629
Previous PR:
- rancher/rancher#31104
=> [release/v2.5] Guard against cluster updating in rotateEncryptionKey action handler

pkg/api/norman/customization/cluster/actions_key.go, pkg/api/norman/customization/cluster/formatter.go
Previous PRs:
- rancher/rancher#31215
- rancher/rancher#31104
Issue:
- rancher/rancher#30629
=> [Forwardport] Conditionally disable rotateEncryptionKey action 

pkg/api/steve/proxy/proxy.go
=> Fix proxy URL path

pkg/controllers/dashboard/helm/apps.go
Problem:
When syncing helm configMaps and secrets there is a constant loop of
updates to apps causing large amounts of load
Solution:
When attempting to compare the object to other versions the namespace
being used was based off the release, this is not the namespace the
config object lives in so there would always be zero results making it
look like we were always working on the most recent object. Use the ns
from the config object to look for more.
https://github.com/rancher/rancher/issues/30168
=> Use namespace from the object when looking for more

pkg/controllers/dashboard/helm/apps.go
Problem:
When syncing helm configMaps and secrets there is a constant loop of
updates to apps causing large amounts of load
Solution:
When attempting to compare the object to other versions the namespace
being used was based off the release, this is not the namespace the
config object lives in so there would always be zero results making it
look like we were always working on the most recent object. Use the ns
from the config object to look for more.
https://github.com/rancher/rancher/issues/30168
=> [master] Use namespace from the object when looking for more

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/31269
=> Add ssh to checkout git repo with ssh key

pkg/api/steve/proxy/proxy.go, pkg/features/feature.go
https://github.com/rancher/rancher/issues/29633
Backport of https://github.com/rancher/rancher/pull/31112 and later fix by Darren https://github.com/rancher/rancher/pull/31249
=> [release/v2.5] Fix proxy URL path

pkg/controllers/dashboard/helm/apps.go
Problem:
If nothing comes back from the list we don't want to process the app
Solution:
Exit and don't create the app so we don't spam etcd
https://github.com/rancher/rancher/issues/30168
=> Don't process objects if list is empty

pkg/controllers/dashboard/helm/apps.go
Problem:
If nothing comes back from the list we don't want to process the app
Solution:
Exit and don't create the app so we don't spam etcd
https://github.com/rancher/rancher/issues/30168
=> [2.5] Don't process objects if list is empty

pkg/apis/management.cattle.io/v3/machine_types.go, pkg/client/generated/management/v3/zz_generated_node_pool.go, pkg/client/generated/management/v3/zz_generated_node_pool_spec.go, pkg/controllers/management/node/controller.go, pkg/node/node.go
adding a bool to nodepool spec to force draining a node when they're deleted
https://github.com/rancher/rancher/issues/27458
=> [v2.5] add drain before delete to nodepool

pkg/apis/management.cattle.io/v3/machine_types.go, pkg/client/generated/management/v3/zz_generated_node_pool.go, pkg/client/generated/management/v3/zz_generated_node_pool_spec.go, pkg/controllers/management/node/controller.go, pkg/node/node.go
https://github.com/rancher/rancher/issues/27458
=> [master] add drain before delete to nodepool

pkg/ui/routes.go
https://github.com/rancher/dashboard/pull/2240
=> [v2.5] Redirect /verify-auth(-azure)?/.* to /.*

go.mod, package/Dockerfile, pkg/catalogv2/system/system.go, pkg/controllers/dashboard/fleetcharts/controller.go, pkg/controllers/management/systemcharts/controller.go, pkg/settings/setting.go
Forward-port of https://github.com/rancher/rancher/pull/31066
=> [master]Fix auto upgrade

go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum
Issue: https://github.com/rancher/rancher/issues/31222
=> [release/v2.5] Vendor rke + update UI

package/Dockerfile, pkg/catalogv2/git/download.go
Forward port of https://github.com/rancher/rancher/pull/31074
=> [master]Use unique url hash for built-in catalog git dir

pkg/api/norman/customization/clusterregistrationtokens/formatter.go, pkg/api/norman/customization/clusterregistrationtokens/formatter_test.go, pkg/api/norman/customization/clusterregistrationtokens/import.go, pkg/apis/management.cattle.io/v3/cluster_types.go, pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go, pkg/client/generated/management/v3/zz_generated_cluster.go, pkg/client/generated/management/v3/zz_generated_cluster_status.go, pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/multiclustermanager/routes.go, pkg/systemtemplate/template.go
Backport https://github.com/rancher/rancher/pull/31381 
https://github.com/rancher/rancher/issues/24876
https://github.com/rancher/rancher/issues/29961
https://github.com/rancher/rancher/issues/31370
=> [v2.5] changes for agent env vars

pkg/controllers/management/clusterprovisioner/provisioner.go
https://github.com/rancher/rancher/issues/31244
=> Update message during cluster creation to include worker

pkg/controllers/management/clusterprovisioner/provisioner.go
https://github.com/rancher/rancher/issues/31244
=> [master] Update message during cluster creation to include worker

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/31427
=> new logic for removing user-node-remove finalizer

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/31427
=> [master] new logic for removing user-node-remove finalizer

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/31455
=> change delete local data to true in the default

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/31427
=> [v2.5] adding extra logic for cleanup to node again

pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/31427
=> adding extra logic for cleanup to done again

package/Dockerfile
- update UI and dashboard versions
=> [release/v2.5] Updates for RC

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/31316
=> rke bump for tools

tests/validation/Dockerfile.v3api, tests/validation/lib/aws.py, tests/validation/tests/v3_api/Jenkinsfile, tests/validation/tests/v3_api/resource/aks_nlb.yml, tests/validation/tests/v3_api/resource/terraform/aks/aks.tf, tests/validation/tests/v3_api/resource/terraform/aks/variables.tf, tests/validation/tests/v3_api/scripts/configure.sh, tests/validation/tests/v3_api/test_create_ha.py
Using Terraform to manage the Group and AKS resources.
K8s version, location and other variables can be set using environment variables.
Task: https://github.com/rancher/rancher/issues/30957
=> AKS Rancher HA automation

package/Dockerfile
Need to force KDM branch to `master` for final `v2.3.11` RC
=> [v2.3.11] Final RC

pkg/api/norman/customization/clusterregistrationtokens/formatter.go
https://github.com/rancher/rancher/issues/31529
=> [v2.5] regenerate nodeCommand to set updated env vars for agent

pkg/api/norman/store/pod/owner.go
Fix display issue with non-standard controllers (e.g Argo)
This fixes the issue with the Ember UI in https://github.com/rancher/rancher/issues/31286
=> Set ReplicaSet owner only if its a known kind

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_pipeline.py
ran flake8, added environment variables
added clarifying comments
moved test def to top of definitions, added delete test case
moved test to correct place, moved pipeline delete to main test
=> Pipeline Automation: create, run, delete

chart/templates/_helpers.tpl, chart/templates/clusterRoleBinding.yaml, chart/templates/deployment.yaml, chart/templates/ingress.yaml, chart/templates/issuer-letsEncrypt.yaml, chart/templates/issuer-rancher.yaml, chart/templates/service.yaml, chart/templates/serviceAccount.yaml
issue: https://github.com/rancher/rancher/issues/31667
=> add a helm template to generate the label section

pkg/controllers/management/node/controller.go
Issue:
- https://github.com/rancher/rancher/issues/31682
=> [release/v2.4.15] Backport Private Registry Regression Fix

pkg/clusterrouter/proxy/proxy_server.go
=> Revert "[2.4] Add OAuth2 for GKE in proxy server"

pkg/controllers/management/node/controller.go
Issue:
- rancher/rancher#31682
=> [release/v2.4] Backport Private Registry Regression Fix

README.md
Update README for v2.5.7 emergency release
=> [v2.5.7] Update README

pkg/controllers/management/node/controller.go
Issue: 
- https://github.com/rancher/rancher/issues/31600
=> [Forwardport] Fix private registry auth when no credentials are passed

pkg/data/management/role_data.go
References role created in https://github.com/rancher/charts/pull/1008
Related Issue: https://github.com/rancher/rancher/issues/31411
=> Add View Monitoring roletemplate

pkg/data/management/role_data.go
No branch-specific changes introduced. Commit was cherry-picked from master.
Original PR: https://github.com/rancher/rancher/pull/31631
References role created in https://github.com/rancher/charts/pull/1008
Related Issue: https://github.com/rancher/rancher/issues/31411
=> [2.5] Add View Monitoring roletemplate

pkg/controllers/management/node/controller.go, pkg/node/node.go
https://github.com/rancher/rancher/issues/31765
=> [release/v2.5.8-rc1] add more error checking for nodepools

pkg/controllers/management/node/controller.go, pkg/node/node.go
https://github.com/rancher/rancher/issues/31765
=> [master] add more error checking for nodepools

pkg/controllers/management/node/controller.go, pkg/node/node.go
https://github.com/rancher/rancher/issues/31765
=> [v2.5] add more error checking for nodepools

pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/metadata.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go
Issue https://github.com/rancher/rancher/issues/22093
=> Added downstream k8s cluster psp annotations from Rancher psp template

pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/31857
=> adding quotes around 3 to force string

pkg/httpproxy/sign.go
Issue: https://github.com/rancher/rancher/issues/29666
=> [master] Fix wrong region for China IAM service

tests/validation/tests/v3_api/resource/terraform/rke2/master/install_rke2_master.sh, tests/validation/tests/v3_api/resource/terraform/rke2/master/join_rke2_master.sh, tests/validation/tests/v3_api/resource/terraform/rke2/worker/join_rke2_agent.sh
As documented in https://github.com/rancher/rke2/issues/786
=> Add workaround for networkmanager

pkg/httpproxy/sign.go
Issue: https://github.com/rancher/rancher/issues/29666
Backport of: https://github.com/rancher/rancher/pull/31855
=> [backport][release/v2.5] Fix wrong region for China IAM service

chart/templates/_helpers.tpl, chart/templates/clusterRoleBinding.yaml, chart/templates/deployment.yaml, chart/templates/ingress.yaml, chart/templates/issuer-letsEncrypt.yaml, chart/templates/issuer-rancher.yaml, chart/templates/service.yaml, chart/templates/serviceAccount.yaml
backport of the PR https://github.com/rancher/rancher/pull/31669 for the issue https://github.com/rancher/rancher/issues/31667
=> [v2.5] add a helm template to generate the label section

chart/scripts/post-delete-hook.sh, chart/templates/post-delete-hook-cluster-role-binding.yaml, chart/templates/post-delete-hook-cluster-role.yaml, chart/templates/post-delete-hook-config-map.yaml, chart/templates/post-delete-hook-job.yaml, chart/templates/post-delete-hook-service-account.yaml, chart/values.yaml, scripts/chart/build
backport of the PR https://github.com/rancher/rancher/pull/31670 for the issue https://github.com/rancher/rancher/issues/30924
dependency:
- https://github.com/rancher/rancher/pull/31904 from which a template is used by this PR 
Expect the see the build fails because the dependency is not merged.
Need to do a rebate after the dependency is merged.
=> [v2.5] aad a Helm post-delete-hook for Rancher

pkg/api/norman/customization/kontainerdriver/actionhandler.go, pkg/image/export/main.go, pkg/image/resolve.go, pkg/image/resolve_test.go
https://github.com/rancher/rancher/pull/31492
**Issue:**
https://github.com/rancher/rancher/issues/31663
=> [Forwardport]: Add image sources

package/Dockerfile.agent, package/run.sh
Backport of https://github.com/rancher/rancher/pull/31847. 
https://github.com/rancher/rancher/issues/30172
=> [2.5]Use tini process watchdog for agent image

pkg/controllers/management/auth/indexes.go, pkg/controllers/management/auth/manager.go, pkg/controllers/managementuser/rbac/handler_base.go, pkg/controllers/managementuser/rbac/prtb_handler.go, pkg/controllers/managementuser/rbac/reconcile_roletemplate.go, pkg/rbac/common.go
Issue:
- rancher/rancher#29932
=> [release/v2.5] Switch to deterministic naming for RBs and CRBs

pkg/controllers/management/clusterprovisioner/provisioner.go
Issue https://github.com/rancher/rancher/issues/31726
=> [2.5] Fix private registry update to all RKE cluster system images

pkg/controllers/management/clusterprovisioner/provisioner.go
Issue https://github.com/rancher/rancher/issues/31726
=> Fix private registry update to all RKE cluster system images

pkg/controllers/managementuser/networkpolicy/clusterHandler.go
Issue:
- https://github.com/rancher/rancher/issues/30135
Previous PR:
- https://github.com/rancher/rancher/pull/31756
=> [Forwardport] Only remove rancher created network policies when disabling PNI

pkg/agent/clean/binding.go, pkg/data/management/bindings_cleanup.go, pkg/multiclustermanager/app.go
Backport to release/v2.5 this PR https://github.com/rancher/rancher/pull/31833
https://github.com/rancher/rancher/issues/29932
=> [2.5] Duplicate Bindings cleanup on rancher startup 

go.mod, go.sum, pkg/client/generated/management/v3/zz_generated_gke_private_cluster_config.go
Backport of https://github.com/rancher/rancher/pull/31961
=> [v2.5] Update gke-operator to latest release

pkg/apis/management.cattle.io/v3/tools_system_images.go
Use new mirrored image with "mirrored-" prefix.
**Issue:**
https://github.com/rancher/rancher/issues/31598
https://github.com/rancher/rancher/issues/31758
=> Use mirrored system images with "mirrored" prefix

pkg/api/norman/customization/cluster/validator.go
https://github.com/rancher/rancher/pull/31975
**Issue:**
https://github.com/rancher/rancher/issues/30977
=> [Forwardport]: Add k3sconfig validation

pkg/apis/management.cattle.io/v3/tools_system_images.go
https://github.com/rancher/rancher/pull/31949
**Issues:**
https://github.com/rancher/rancher/issues/31598
https://github.com/rancher/rancher/issues/31758
=> [Forwardport]: Use mirrored system images with "mirrored" prefix

go.mod, go.sum
https://github.com/rancher/rancher/issues/31999
=> [release/v2.5] vendor update lasso

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
update RKE for KDM default k8s version
=> [release/v2.5] Update RKE

pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
In order to ensure the clusters that need syncing are reenqueued
properly, the last cluster refresh time is set any time the cluster is
updated. Also, the cluster is reenqueued even if the cluster should not
ready for a refresh. This fixes an issue where the refreshing would stop
if a cluster is updated successfully before a refresh is needed (the
cluster would enter the handler because the cluster object was updated,
the refresh time was not exceed so the handler would return without
re-queuing). This also prevents unnecessary log messages where the
cluster is creating, so the EKS handler is re-queuing the cluster and
the refresher is continually checking for upstream changes.
In addition, some logic was changed to better align with the
function/variable names (shouldRefresh was acting …
=> Fix syncing controller re-queuing

pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
Previous PR: 
- https://github.com/rancher/rancher/pull/31813
The original version of the code prior to merging the previous PR (for reference) can be found [here](https://github.com/rancher/rancher/blob/release/v2.5.7/pkg/controllers/managementuser/rbac/reconcile_roletemplate.go#L84)
=> [release/v2.5] Fix logic for project access to global resources

go.mod, go.sum
https://github.com/rancher/rancher/issues/31999
=> vendor update lasso

pkg/data/management/machinedriver_data.go
Issue: https://github.com/rancher/rancher/issues/29666
Addresses this comment: https://github.com/rancher/rancher/issues/29666#issuecomment-816439207
=> [release/v2.5] Whitelist eks and kms CN domains

pkg/api/norman/customization/namespace/namespace.go, pkg/controllers/managementuser/networkpolicy/clusterHandler.go, pkg/controllers/managementuser/networkpolicy/netpol.go, pkg/controllers/managementuser/networkpolicy/nssyncer.go
Previous PR:
- https://github.com/rancher/rancher/pull/31957
Issue:
- https://github.com/rancher/rancher/issues/30211
=> [master] Fix CIS scan when PNI is enabled

pkg/data/management/machinedriver_data.go
Issue: https://github.com/rancher/rancher/issues/29666
Addresses this comment: https://github.com/rancher/rancher/issues/29666#issuecomment-816439207
=> [master][forwardport] Whitelist eks and kms CN domains

tests/integration/suite/test_workloads.py
back porting something already in master
=> [v2.5] Skip flakey test

tests/validation/tests/rke/resources/k8s_templates/validation.yml.j2, tests/validation/tests/rke/resources/k8s_ymls/service_k8test1.yml, tests/validation/tests/rke/resources/k8s_ymls/single_pod.yml, tests/validation/tests/rke/resources/k8s_ymls/two_container_pod.yaml, tests/validation/tests/v1_api/common.py, tests/validation/tests/v3_api/common.py
Update image references to use `ranchertest` repo
=> Validation - Update test image repo

.drone.yml, chart/templates/_helpers.tpl, manifest-head.tmpl
=> Trim chart label to 63 characters in helm chart

pkg/controllers/management/nodepool/nodepool.go
https://github.com/rancher/rancher/issues/31999
=> [v2.5] rework nodepools to use cache during update

pkg/controllers/management/nodepool/nodepool.go
https://github.com/rancher/rancher/issues/31999
=> [master] rework nodepools to use cache during update

pkg/controllers/management/clusterupstreamrefresher/gke_upstream_spec.go
Forward port of https://github.com/rancher/rancher/pull/32066
=> Add Imported field to GKE upstream spec builder

pkg/api/norman/store/cluster/cluster_store.go, pkg/controllers/managementuser/networkpolicy/netpol.go
Issue: 
- https://github.com/rancher/rancher/issues/31338
For information on testing, [go here](https://github.com/rancher/rancher/issues/31338#issuecomment-819057626)
=> [release/v2.5] Allow PNI to be enabled for additional RKE Cluster Network Providers

app/role_data.go
backport of https://github.com/rancher/rancher/pull/32108
=> [2.4] Update apiGroups to use explicit group

pkg/controllers/management/clusteroperator/utils.go, pkg/controllers/management/eks/eks_cluster_handler.go, pkg/controllers/management/gke/gke_cluster_handler.go
Forward port of https://github.com/rancher/rancher/pull/32099
https://github.com/rancher/rancher/issues/32087
=> Do not set unknown condition for creating cluster

pkg/data/management/role_data.go
Forward port of https://github.com/rancher/rancher/pull/32108
=> [master] Update apiGroups to use explicit group

pkg/controllers/management/node/controller.go, pkg/controllers/management/nodepool/nodepool.go
https://github.com/rancher/rancher/issues/31507
=> [v2.5] moving enqueue after to nodepool to persist workqueue

pkg/controllers/management/node/controller.go, pkg/controllers/management/nodepool/nodepool.go
https://github.com/rancher/rancher/issues/31507
=> [master] moving enqueue after to nodepool to persist workqueue

pkg/api/norman/store/cluster/cluster_store.go, pkg/controllers/managementuser/networkpolicy/netpol.go
Issue:
- https://github.com/rancher/rancher/issues/31338
=> [master] Allow PNI to be enabled for additional RKE Cluster Network Providers

pkg/image/export/main.go
Undoes https://github.com/rancher/rancher/pull/32037 and is related to https://github.com/rancher/rancher/issues/32016
=> Revert Windows manifest change for airgap

pkg/image/export/main.go
Undoes #32061 and is related to #32016
=> [2.5] Revert Windows manifest change for airgap

pkg/api/norman/customization/cluster/validator.go
Forward-port of https://github.com/rancher/rancher/pull/32171
https://github.com/rancher/rancher/issues/32161
=> Add linux node pool GKE cluster validator

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Also run `go mod tidy`.
https://github.com/rancher/rancher/issues/32241
=> Bump gke-operator to RC8

package/Dockerfile
=> [release/v2.5] Update tags for ui and dashboard

pkg/controllers/managementuser/healthsyncer/healthsyncer.go
2.6 version of https://github.com/rancher/rancher/pull/31890
ISSUE: #11496
PROBLEM:
Not all providers implement component status correctly, e.g. AKS shows the scheduler in an error state. We need to ignore some component statuses as they can be misleading.
SOLUTION:
Added a filter to the health syncer that does not return some component statues based on provider.
TESTING:
I was unable to get access to an AKS cluster but, I could filter components out of a k3os cluster by adding it to the exclusion map.
=> [2.6] exclude some status checks for some providers

pkg/controllers/managementuser/networkpolicy/podhandler.go, pkg/controllers/managementuser/networkpolicy/servicehandler.go
Forwardport PR
Issue:
- rancher/rancher#30135
Previous PR:
- https://github.com/rancher/rancher/pull/32222
=> [master] Deletion fix for HostPort and NodePort NetworkPolicy resources

scripts/package
Issue:
https://github.com/rancher/rancher/issues/31995
Original PR:
https://github.com/rancher/rancher/pull/32100
=> Scan released directory for images

.drone.yml, scripts/promote-docker-image.sh
https://github.com/rancher/rancher/issues/30614
=> Add drone option to promote docker image

pkg/image/resolve.go
Backport PR for #32291
Relevant issue: #32290
=> [2.5] Use comma-delineated list for OS in image list generation

pkg/auth/providers/saml/saml_client.go
https://github.com/rancher/rancher/issues/31593
We do this for all login tokens, https://github.com/rancher/rancher/blob/master/pkg/auth/providers/publicapi/login.go#L113 but SAML login flow is different - https://github.com/rancher/rancher/blob/master/pkg/auth/providers/publicapi/login.go#L174. So need to set it when token gets created after handling SAML assertion.
=> set ttl on saml login tokens

.drone.yml
https://github.com/rancher/rancher/issues/30234
=> Add Docker image digests artifact on tag

.drone.yml
Backport of https://github.com/rancher/rancher/pull/32315
https://github.com/rancher/rancher/issues/30234
=> [release/v2.5] Add Docker image digests artifact on tag

.drone.yml
Backport of https://github.com/rancher/rancher/pull/32476
=> [release/v2.5] Pass drone image digest settings via env vars

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_gke_cluster_config_spec.go
https://github.com/rancher/rancher/issues/32433
=> [v2.5] Bump gke-operator to RC12

.drone.yml
Backport of https://github.com/rancher/rancher/pull/32478
=> [release/v2.5] Depend on linux-amd64 for drone docker img digests

pkg/api/norman/customization/cluster/validator.go
Forward port of https://github.com/rancher/rancher/pull/32468
=> Fix nodepool name dereference

pkg/controllers/management/gke/gke_cluster_handler.go
When zonal GKE clusters are updating the control plane, the control
plane usually becomes unreachable. This is expected and normal
behavior[1]. However, when the HealthSyncer controller runs, it cannot
reach the API and sets ClusterConditionReady to false with an alarming
error message. This change does not eliminate or ignore the error but
adds more context to the error message to help users understand that
this is normal.
[1] https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-upgrades#upgrading_manually
https://github.com/rancher/rancher/issues/32473
=> Add context to Ready condition while updating

pkg/api/norman/customization/gke/handler.go
**Issue:**
https://github.com/rancher/rancher/issues/32446
=> Add cluster id param

pkg/api/norman/customization/gke/handler.go
**Issue:**
https://github.com/rancher/rancher/issues/32446
=> [Forwardport] v2.6: Add cluster id param

package/windows/Dockerfile.agent, package/windows/Dockerfile.agent.20H2
~Pending release of wins for v0.1.1 to allow case-insensitive whitelist matching.~
Related Issue: https://github.com/rancher/rancher/issues/32194#issuecomment-832287457
=> [2.5] Bump wins version to v0.1.1

package/windows/Dockerfile.agent, package/windows/Dockerfile.agent.20H2
~Pending release of wins for v0.1.1 to allow case-insensitive whitelist matching.~
Related Issue: https://github.com/rancher/rancher/issues/32194#issuecomment-832287457
=> Bump wins version to v0.1.1

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/32532
=> Don't add null values to rke2/k3s config

tests/integration/requirements.txt, tests/integration/suite/conftest.py, tests/integration/suite/test_cluster.py, tests/validation/requirements.txt, tests/validation/requirements_v3api.txt
Backport of https://github.com/rancher/rancher/pull/32581
=> [release/v2.5] Bump python k8s client

.drone.yml, scripts/promote-docker-image.sh
Backport of https://github.com/rancher/rancher/pull/32311 and https://github.com/rancher/rancher/pull/32572
=> [release/v2.5] Add drone option to promote docker image

.drone.yml, scripts/create-components-file.sh, scripts/package
Backport of https://github.com/rancher/rancher/pull/32549
=> [release/v2.5] Add file with components versions as release asset

pkg/kontainer-engine/drivers/rke/rke_driver.go
https://github.com/rancher/rancher/issues/21976
Backport of https://github.com/rancher/rancher/pull/32638
=> [release/v2.5] Cleanup RKE state directory

pkg/auth/providers/saml/saml_client.go
Backport https://github.com/rancher/rancher/pull/32322 
Issue: https://github.com/rancher/rancher/issues/31593
=> [v2.5] set ttl on saml login tokens

pkg/rkenodeconfigclient/client.go
https://github.com/rancher/rancher/issues/32204
=> Clarify worker requirement in custom cluster

pkg/rkenodeconfigclient/client.go
https://github.com/rancher/rancher/issues/32683
Backport of https://github.com/rancher/rancher/pull/32192
=> [release/v2.5] Clarify worker requirement in custom cluster

pkg/image/export/main.go, scripts/windows/package.ps1
https://github.com/rancher/rancher/issues/32698
=> adding a check for 2009 and converting it to 20H2

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/31859
=> [master] Update norman

pkg/controllers/dashboard/fleetcharts/controller.go
Forward-port of https://github.com/rancher/rancher/pull/32353
=> [master]Apply HTTP_PROXY and NO_PROXY to fleet

.drone.yml
Backport of https://github.com/rancher/rancher/pull/32315 for 2.4.x
=> [release/v2.4] Add Docker image digests artifact on tag

pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/32794
=> Only log errors for etcdbackup controller

pkg/agent/node/node.go, pkg/tunnelserver/mcmauthorizer/tunnel.go
https://github.com/rancher/rancher/issues/32726
=> use docker client with api version negotiation

pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/32826
Backport of https://github.com/rancher/rancher/pull/32820
=> [release/v2.5] Only log errors for etcdbackup controller

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/32585
=> Update gke-operator to 1.0.2-rc1

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/32597
=> Update gke-operator to latest

pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/controller_test.go, pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/machineprovision/template.go
Some of the arguments to rancher-machine are paths to files needed for
provisioning. These changes add support for passing these files into the
pod when necessary.
Issue:
https://github.com/rancher/rancher/issues/32231
=> Support passing files into machine provisioning job

pkg/auth/audit/audit.go
https://github.com/rancher/rancher/issues/32588
=> Audit Log at Login - Check the content-type header having charset as well which is set by Dashboard UI

pkg/api/norman/customization/aks/handler.go, pkg/api/norman/customization/aks/listers.go
Issue: https://github.com/rancher/rancher/issues/32587
=> Add list of VM sizes to AKS UI proxy 

pkg/multiclustermanager/app.go
This is backport of https://github.com/rancher/rancher/pull/32871
https://github.com/rancher/rancher/issues/32792
=> [2.5]Do bindings cleanup in a separate goroutine

tests/integration/suite/test_node.py
https://github.com/rancher/rancher/issues/21258
=> Update node test to retry link

pkg/api/norman/customization/aks/handler.go, pkg/api/norman/customization/aks/listers.go, pkg/api/norman/customization/gke/handler.go
Issue: https://github.com/rancher/rancher/issues/32587
=> Add list Locations to AKS UI proxy

pkg/controllers/management/aks/aks_cluster_handler.go, pkg/controllers/management/gke/gke_cluster_handler.go
The previous implementation would always return `false` for
privateRequiresTunnel for any error that occurred. This may lead to some
false positives for errors that can be recovered from.
Now, privateRequiresTunnel will only be set to `false` when we detect
the proper error.
=> Add smarter private-requires-tunnel detection for AKS

pkg/controllers/management/clusterregistrationtoken/status.go
https://github.com/rancher/rancher/issues/32894
=> Add sudo to rke2 registration commands

pkg/api/norman/customization/cluster/validator.go
AKS cluster version must be validated only,
when it is provided in config.
=> Fix check for AKS cluster version in norman

chart/templates/post-delete-hook-cluster-role.yaml, chart/templates/post-delete-hook-psp.yaml
Backport of the PR https://github.com/rancher/rancher/pull/33023
issue: https://github.com/rancher/rancher/issues/33068
=> [2.5] add podSecurityPolicy to the post-delete-hook

pkg/rkenodeconfigclient/client.go
Changed NodeConfig logging to trace as it may contain sensitive data
=> Changed NodeConfig logging to trace

pkg/api/norman/customization/globalnamespaceaccess/access_common.go
This fix checks if the caller has a globalrolebinding to restricted-admin global role. If yes then as long as no local cluster target projects exist, the user is allowed to launch multiclusterapp in downstream clusters without having explicit access to those projects.
=> Fix to let restricted-admin deploy multiclusterapp in downstream clusters

pkg/controllers/management/clusteroperator/utils.go, pkg/controllers/management/eks/eks_cluster_handler.go, pkg/controllers/management/gke/gke_cluster_handler.go
Issue:
https://github.com/rancher/rancher/issues/32903
Original PR:
https://github.com/rancher/rancher/pull/32900
=> [2.5] Use additional CA for hosted providers

pkg/controllers/dashboard/fleetcharts/controller.go, pkg/features/feature.go, pkg/rancher/rancher.go
https://github.com/rancher/rancher/issues/32808
https://github.com/rancher/rancher/issues/32688
=> Add gitops feature flag, force fleet to be turned on

go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum, pkg/catalogv2/system/system.go, pkg/controllers/dashboard/fleetcharts/controller.go, pkg/provisioningv2/kubeconfig/manager.go, pkg/settings/setting.go, tests/integration/suite/test_system_project.py
https://github.com/rancher/fleet/issues/395
=> Change fleet install to cattle-fleet-system

pkg/rancher/rancher.go
Problem:
Rancher 2.5 clients are case sensitive based on the rke config that does
not use a properly tagged struct
Solution:
Update rke to use a json tagged struct for the config and migrate all
clusters to use the proper casing of the configs
https://github.com/rancher/rancher/issues/31385
=> Migrate encryption config on startup

pkg/api/norman/server/managementstored/setup.go, pkg/api/norman/store/catalog/store.go, pkg/auth/api/user/user_actions.go, pkg/auth/api/user/user_store.go, pkg/data/management/role_data.go
Reverts rancher/rancher#33101
This is causing downstream rancher pods to not run, see: https://github.com/rancher/rancher/issues/33125
=> Revert "Restricted Admin permission fixes"

pkg/controllers/managementuser/rbac/namespace_handler.go, pkg/controllers/managementuser/rbac/project_handler.go, tests/integration/suite/test_system_project.py
https://github.com/rancher/rancher/issues/31209
=> Add fleet namespaces to system project

pkg/controllers/dashboard/systemcharts/controller.go
https://github.com/rancher/rancher/issues/33203
=> Clean up rancher-operator-system namespace

pkg/api/norman/customization/vsphere/handler.go
PR allows for a new secretId param which is the name of the secret the new provisioning rke2 cloud credential is stored in and check if the user has access to it and continue on to use the cloud cred data to access the vsphere api.
https://github.com/rancher/rancher/issues/33080
=> vSphere Meta API update to support a secret instead of the old v3 CloudCredential

pkg/catalogv2/system/system.go
If the objects of a chart were installed in a non-default namespace
without the namespace being listed in the object's metadata, then the
uninstalled would seem successful but the helm is not able to find the
objects. The non-namespaced items would be removed, but any namespaced
items would be leftover.
It should be noted that the namespace provided allowed helm to find the
release secret, but would not namespace the call to delete the objects
in the release.
Issue:
https://github.com/rancher/rancher/issues/32179
=> Uninstall objects from charts in non-default namespaces

pkg/api/norman/store/cluster/cluster_store.go
Issue https://github.com/rancher/rancher/issues/27306
forward https://github.com/rancher/rancher/pull/33009
=> [2.5.9] Fix to properly remove vSphere vCenter server entries

package/Dockerfile
update the value of CATTLE_RANCHER_WEBHOOK_MIN_VERSION to match the change in rancher/charts dev-v2.6
=> update the value of CATTLE_RANCHER_WEBHOOK_MIN_VERSION

pkg/tls/tls.go
Need to add cluster IP to internal cert SAN since we are switching to use cluster IP in the [kubeconfig](https://github.com/rancher/rancher/commit/60275b1f66d2e2c0ae40a9edaa7ca874ac2c23b6#diff-a670104fda3becbf85fd10edd3[…]d40a10b690e2f02fd36a7c23R38-R48). This is due to the change in rancherd that @ibuildthecloud made because it can't resolve cluster DNS on the host for system-agent.
https://github.com/rancher/fleet/issues/420
=> Add rancher cluster IP to generated internal certs

pkg/cluster/private_registry.go
Forward https://github.com/rancher/rancher/pull/33165
=> Fix rancher agent docker auth config when using private registry

pkg/data/management/kontainerdriver_data.go
Update `opentelekomcloudcontainerengine` UI version to `v1.1.0`
Resolve #32789
=> Add AK/SK support for OTC CCE driver

pkg/apis/management.cattle.io/v3/multi_cluster_app.go
Issue: https://github.com/rancher/rancher/issues/33072
This has been removed because an answer can now contain either values or valuesSetString.
=> [master] Remove norman required tag for multicluster app answers

pkg/httpproxy/proxy.go
In the very specific case that the /meta/proxy route is being called in
order to get data about an existing EKS cluster, allow users who are
cluster owners for that cluster but not necessarily owners of the cloud
credential to call the provider API through the proxy. This is necessary
to allow these users to edit the cluster. The UI needs to pass an
additional 'clusterID' parameter in the X-API-CattleAuth-Header header.
=> Check EKS cluster access in generic proxy

pkg/httpproxy/proxy.go
In the very specific case that the /meta/proxy route is being called in
order to get data about an existing EKS cluster, allow users who are
cluster owners for that cluster but not necessarily owners of the cloud
credential to call the provider API through the proxy. This is necessary
to allow these users to edit the cluster. The UI needs to pass an
additional 'clusterID' parameter in the X-API-CattleAuth-Header header.
Backport of https://github.com/rancher/rancher/pull/33439
=> [v2.5] Check EKS cluster access in generic proxy

pkg/httpproxy/proxy.go
In the very specific case that the /meta/proxy route is being called in
order to get data about an existing EKS cluster, allow users who are
cluster owners for that cluster but not necessarily owners of the cloud
credential to call the provider API through the proxy. This is necessary
to allow these users to edit the cluster. The UI needs to pass an
additional 'clusterID' parameter in the X-API-CattleAuth-Header header.
Backport of https://github.com/rancher/rancher/pull/33440
=> [v2.5.9] Check EKS cluster access in generic proxy

pkg/api/steve/aggregation/aggregation.go
Related issue: https://github.com/harvester/harvester/issues/922
On the master head, we support Rancher API extension in the following way:
1. Create the following APIService object in a downstream cluster.
```
kind: APIService
apiVersion: management.cattle.io/v3
metadata:
name: harvester
spec:
secretName: harvester-aggregation
secretNamespace: harvester-system
pathPrefixes:
- /v1/harvester
```
2. Start the aggregation client: https://github.com/gitlawr/harvester/blob/apiservice-v1-harvester/pkg/server/types.go#L267
3. Then the extension API can be accessed via `<SERVER_URL>/k8s/clusters/name/v1/harvester`
Problem:
The X-API-URL-Prefix header is added as /v1/harvester in https://github.com/rancher/rancher/blob/92b822fb2e1437a7bacb7a5a65ab5fc02608a7f3/pkg/api/steve/aggregation/aggregation.g …
=> Set aggregation prefix to /k8s/clusters/name when applicable

vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go, vendor/modules.txt
https://github.com/rancher/rancher/issues/33276
=> Update vendored kontainer-engine

pkg/api/norman/store/service/service.go
https://github.com/rancher/rancher/issues/33085
See https://github.com/rancher/rancher/issues/33085#issuecomment-867835847.
=> Default to SingleStack for headless services

pkg/auth/audit/audit.go, pkg/auth/audit/audit_test.go, pkg/auth/audit/filter.go, pkg/data/management/machinedriver_data.go, pkg/rancher/rancher.go
backport issue:
https://github.com/rancherlabs/rancher-security/issues/786
master PR:
https://github.com/rancher/rancher/pull/33338
=> [2.5] Conceal sensitive data in audit logs

pkg/controllers/managementuserlegacy/helm/common/common.go
Forward https://github.com/rancher/rancher/pull/33436
=> Updated kustomize config to manage io.cattle.field/appId label on apps deployment

package/Dockerfile
=> bump the mcm UI to rc5

pkg/api/norman/customization/gke/listers.go
Without this patch, /meta/gkeVersions only accepts 'zone' as a location
parameter and so only returns kubernetes versions available in a given
zone. The available versions in a zone is not necessarily the same as
the versions available for a region, even if a zone is within the
region. This change updates the /meta/gkeVersions route to accept either
'zone' or 'region' and return the appropriate list.
Example usage:
GET /meta/gkeVersions?projectId=my-project&cloudCredentialId=cattle-global-data:cc-abcde?region=us-central1
GET /meta/gkeVersions?projectId=my-project&cloudCredentialId=cattle-global-data:cc-abcde?zone=us-central1-f
https://github.com/rancher/rancher/issues/33490
=> Accept zone or region for GKE versions

README.md
=> Update Copyright Date

pkg/controllers/managementuser/nodesyncer/nodetaints.go
Backport of https://github.com/rancher/rancher/pull/33479
https://github.com/rancher/rancher/issues/33478
Signed-off-by: Greg Sidelinger <sidelig@nationwide.com>
=> [2.5] Don't crash with nil node in syncTaints

package/Dockerfile
UI is for issue https://github.com/rancher/rancher/issues/33527
=> bump the mcm UI to rc6

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_gke_node_config.go
https://github.com/rancher/rancher/issues/33406
=> Bump gke-operator to 1.1.1-rc7

package/Dockerfile
ui tag https://github.com/rancher/ui/releases/tag/2.4.48-rc1
=> bump the UI tag to 2.4.48-rc1

pkg/data/management/machinedriver_data.go
Add harvester node driver
**Related issues**
harvester/harvester#861
https://github.com/rancher/dashboard/issues/3374
=> Add Harvester node driver

package/Dockerfile
https://github.com/rancher/ui/releases/tag/v2.5.9-rc7
=> [release/v2.5.9] bump the mcm UI to rc7

pkg/controllers/managementlegacy/globaldns/globaldnsprovider_catalog_launcher.go
https://github.com/rancher/rancher/issues/31638
Fix is to not use the cross namespace ownerreference (external-dns app in systemProject namespace points to GlobalDNSProvider in cattle-global-data namespace) that causes k8s 1.20 to enforce deletion of the external-dns app.
Instead of relying on the ownerRef for deletion of the app after GlobalDNSProvider is removed, fix is to handle the delete event in the controller to remove the app.
=> Remove cross namespace ownerRef, handle app delete

go.mod, go.sum, vendor/modules.txt
```
go mod tidy
go mod vendor
```
=> [release/v2.4.16] bump the RKE to v1.1.17

package/Dockerfile
Issue: https://github.com/rancher/rancher/issues/33585
=> [master] Update CLI tag

pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
https://github.com/rancher/rancher/issues/33596
Backporting the PR https://github.com/rancher/rancher/pull/33471 for the issue https://github.com/rancher/rancher/issues/31638
=> [2.5] Remove cross namespace ownerRef, handle app delete

pkg/apis/rke.cattle.io/v1/cluster.go, pkg/apis/rke.cattle.io/v1/zz_generated_deepcopy.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/probe.go, tests/integration/pkg/cluster/clusters.go
controlPlaneConfig -> machineGlobalConfig
workerConfig -> machineSelectorConfig
=> Rename controlPlaneConfig and workerConfig

.drone.yml
issue: https://github.com/rancher/rancher/issues/33423
This PR is limited to only stop publishing the rancerd assets: https://github.com/rancher/rancher/issues/33423#issuecomment-875999466
=> remove rancherd assets from the build process

pkg/rkenodeconfigserver/nodeserver.go
https://github.com/rancher/rancher/issues/32683
https://github.com/rancher/rancher/issues/33624
Backport of https://github.com/rancher/rancher/pull/33570
=> [release/v2.5] Return err to node if no applied cluster config

pkg/data/management/machinedriver_data.go
Update harvester node driver url to `releases.rancher.com/harvester-node-driver`
**Related issues**
#33583
=> Update harvester node driver url

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_pipeline.py
Added new regex dns to pipeline_view_logs.
Added a comment.
=> [Validation] Fixed test_pipelines failure

pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/kubectl/kubectl.go, pkg/settings/setting.go, pkg/systemtemplate/template.go
Forward https://github.com/rancher/rancher/pull/33166
=> Wait for rancher agent daemonset rollout before update cluster

scripts/promote-docker-image.sh
Backport https://github.com/rancher/rancher/pull/33613
https://github.com/rancher/rancher/issues/33633
=> [release/v2.5] Add donotuse tag for testing Docker image promote

tests/validation/tests/v3_api/resource/terraform/aks/variables.tf
More resources for local HA AKS clusters on automation.
=> Automation - Bump the instance type for AKS HA local clusters

pkg/controllers/dashboard/controller.go
https://github.com/rancher/rancher/issues/33711
This hostedcluster controller should only run in rancher not downsteam agent.
=> Only run hostcluster controller in rancher

tests/validation/tests/v3_api/test_create_ha.py
It seems that starting with rke 1.3 and k8s 1.21 the ingress-nginx resources take a bit longer to get into an active state, making some of the certificate install types to fail.
This check will make the test wait until the resources are active.
Related: https://github.com/rancher/rancher/issues/32797#issuecomment-885091240
=> Automation - RKE HA ingress check before installing Rancher

pkg/controllers/managementuser/controllers.go, pkg/controllers/managementuser/machinerole/machinerole.go
https://github.com/rancher/rancher/issues/33385
https://github.com/rancher/rancher/issues/32654
=> machine worker label sync

pkg/controllers/managementuser/controllers.go
Backport of https://github.com/rancher/rancher/pull/33763
=> [v2.5] Register Secrets cache for downstream cluster

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/manifests.go, pkg/systemtemplate/import.go
Note: wait for rancher/system-upgrade-controller#122 to be merged
Issue: 
https://github.com/rancher/rancher/issues/32904
https://github.com/rancher/rancher/issues/33467
=> Add taints to etcd and controlplane nodes

go.mod, go.sum
https://github.com/rancher/rancher/issues/33678
=> Bump system-upgrade-controller to v0.7.2

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/33406
=> Update gke-operator to 1.1.1-rc10

pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/cluster/controller_test.go
https://github.com/rancher/rancher/issues/33694
=> Do not match substrings of cluster name

pkg/controllers/managementuser/rbac/prtb_handler.go
https://github.com/rancher/rancher/issues/33093
=> Add navlinks to project roles that are global resources

scripts/test
Wait for the webhook deployment before running integration tests
=> Wait for webhook

pkg/api/norman/store/service/service.go
https://github.com/rancher/rancher/issues/33085
=> Default headless service to SingleStack if not passed

pkg/tls/tls.go
https://github.com/rancher/rancher/issues/33221
=> Fix upgrade for docker self-signed cert setup

scripts/package
Download v2.6 CVEs csv to include in assets.
=> Add CVEs csv as asset

pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
If a cluster was created with rancher-machine nodes the suc plan would 
failed to authorize the node.  This previously node authorization logic 
only worked for custom nodes.  The logic has been expanded to work for 
rancher-machine provisioned nodes too.
=> Fix system-agent update for rancher-machine clusters

pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/33904
=> Treat no selector as everything selector and evaluate all configs, not first

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/32891
=> [v2.6] vendor update wrangler, rke

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
=> vendor update wrangler, rke

cmd/agent/main.go
Follow same logic here https://github.com/rancher/rancher/blob/v2.5.8/package/share-root.sh#L4-L8. If container is stopped from outside the exit code will not be zero. And it will get restarted if it doesn't meet this set of [conditions](https://github.com/rancher/rancher/blob/52da4437d2c6f7d299c17f0f7f5b241160011cb3/pkg/rkeworker/docker.go#L104) 
https://github.com/rancher/rancher/issues/32727
=> [master] Trap sigterm in sharemnt so it can return exit code zero

go.mod, go.sum, pkg/api/steve/navlinks/store.go
https://github.com/rancher/rancher/issues/33093
=> Fix navlinks

pkg/apis/management.cattle.io/v3/cluster_types.go, pkg/controllers/dashboard/clusterregistrationtoken/status.go
Adding an insecure windows registration command for RKE2.
https://github.com/rancher/dashboard/issues/3580
=> [backport 2.6] Windows Insecure command for RKE2.

go.mod, go.sum, pkg/api/steve/navlinks/store.go
https://github.com/rancher/rancher/issues/33093
=> [2.6] Fix nav links

cmd/agent/main.go
Backport of https://github.com/rancher/rancher/pull/33859
=> [2.6]Trap sigterm in sharemnt so it can return exit code zero

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
https://github.com/rancher/rancher/issues/33904
=> Assign machinePool labels to machineDeployment machine template

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
https://github.com/rancher/rancher/issues/33904
=> [2.6] Assign machinePool labels to machineDeployment machine template

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
https://github.com/rancher/rancher/issues/33259
=> [2.6] Take ownership of nodeConfig objects referred to by a cluster

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
https://github.com/rancher/rancher/issues/33259
=> Take ownership of nodeConfig objects referred to by a cluster and delete them

pkg/api/norman/customization/aks/handler.go
Add a new POST endpoint /meta/aksCheckCredentials that accepts AKS
credentials, minus tenant ID, as a POST request, and checks whether they
are valid. This allows the UI to validate the user's input when a cloud
credential or cluster is being created before the cloud credential
exists.
https://github.com/rancher/rancher/issues/33861
=> Add new helper method /meta/aksCheckCredentials

chart/values.yaml
forward-port of https://github.com/rancher/rancher/pull/34001
(Please ignore the misleading branch name, I can make a new PR if needed)
=> [Forward-port] add cattle-fleet-system to the namespace list

go.mod, go.sum, vendor/github.com/rancher/rke/services/etcd.go, vendor/modules.txt
Related Issue: https://github.com/rancher/rancher/issues/33835
=> Bump rke to v1.1.19-rc1

scripts/package
forward port of https://github.com/rancher/rancher/pull/34024
=> [forward port] remove the skipping of CRD charts 

pkg/controllers/management/authprovisioningv2/binding.go
Problem:
If the provisioning cluster doesn't exist when attempting to create
permissions based off a CRTB the handler takes no action. If no other
update happens on that CRTB the permissions will never be granted.
Solution:
If the provisioning cluster doesn't exist, enqueueAfter the CRTB so we
try again
=> Enqueue CRTB again if provisioning cluster doesn't exist

pkg/controllers/management/authprovisioningv2/binding.go
Problem:
Existing logic is not taking into account the groupPrincipal field when
creating subjects
Solution:
Use the helper to create the subjects based off the CRTB
=> Use BuildSubjectFromRTB to get subjects from CRTB

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
=> [v2.6] update rke to v1.3.0-rc12

pkg/controllers/managementuser/controllers.go
The impersonation mechanism needs these downstream resources cached.
https://github.com/rancher/rancher/issues/34042
=> Register SA and ClusterRoles caches

pkg/controllers/dashboard/clusterregistrationtoken/status.go
Windows registration command was a little off and it has been tweaked to work correctly in the correct context.
* https://github.com/rancher/rancher/issues/33625#issuecomment-893600992
=> Improving windows registration command.

pkg/controllers/dashboard/clusterregistrationtoken/status.go
Windows registration command was a little off and it has been tweaked to work correctly in the correct context.
* https://github.com/rancher/rancher/issues/33625#issuecomment-893600992
=> [backport 2.6] Improving windows registration command. 

tests/validation/tests/v3_api/test_airgap.py
Allow 2.6 install of rancher in airgap automation
=> Allow 2.6 install of rancher in airgap automation

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/34066
=> [master] pin rke v1.3.0-rc13

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/34066
=> [2.6] pin rke v1.3.0-rc13

pkg/api/steve/additionalapi.go, pkg/provisioningv2/rke2/configserver/custom.go, pkg/provisioningv2/rke2/configserver/server.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/store.go
https://github.com/rancher/rancher/issues/34094
=> [backport 2.6] adding /v3/connect/cluster-info endpoint for windows rke2 installer

package/Dockerfile, package/Dockerfile.agent
Forwardport of: https://github.com/rancher/rancher/pull/34138
https://github.com/rancher/rancher/issues/34137
=> [Forwardport master] Don't remove zypper and install vim in rancher/rancher

package/Dockerfile, package/Dockerfile.agent
https://github.com/rancher/rancher/issues/34137
=> Don't remove zypper and install vim in rancher/rancher

pkg/provisioningv2/kubeconfig/manager.go
Relevant issue: https://github.com/rancher/rancher/issues/34077
=> Delete secret if it is outdated upon upgrade for fleet

pkg/provisioningv2/kubeconfig/manager.go
Relevant issue: https://github.com/rancher/rancher/issues/34077
Backport of: https://github.com/rancher/rancher/pull/34098
=> [2.6] Delete secret if it is outdated upon upgrade for fleet

pkg/controllers/managementuser/networkpolicy/netpol.go, pkg/controllers/managementuser/networkpolicy/register.go
Issue: 
- https://github.com/rancher/rancher/issues/33979
Previous PR:
- https://github.com/rancher/rancher/pull/34082
=> [master] Fix host network policies for Calico CNI (RKE1/2)

chart/templates/secret.yaml, chart/values.yaml, pkg/data/management/role_data.go
https://github.com/rancher/rancher/pull/34096
=> [2.6.1] Forward Port: save the bootstrap password

pkg/agent/clean/binding.go, pkg/data/management/bindings_cleanup.go
2.6 backport of https://github.com/rancher/rancher/pull/33681 for https://github.com/rancher/rancher/issues/33144
=> [Backport v2.6] Fixed CRBs/RBs cleanup by delaying execution

chart/templates/_helpers.tpl, chart/tests/deployment_test.yaml
Forward https://github.com/rancher/rancher/pull/34081
=> Fix helm unittest silent regression

pkg/api/steve/navlinks/store.go
https://github.com/rancher/rancher/issues/34030
=> Proper construct resource name for navlink rbac check

pkg/agent/clean/binding.go, pkg/data/management/bindings_cleanup.go
https://github.com/rancher/rancher/pull/33681 backport for https://github.com/rancher/rancher/issues/33682
=> [v2.5 Backport] CRBs/RBs cleanup fix

pkg/data/management/role_data.go
https://github.com/rancher/dashboard/issues/3780
=> Add machine-config to cluster create perms

pkg/data/management/role_data.go
https://github.com/rancher/dashboard/issues/3780
=> [2.6 backport] Add machine-config to cluster create perms

pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/34217
=> [2.6] Set system-default-registry to global setting by default on rke2

pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/34217
=> Set system-default-registry to global setting by default on rke2

pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go
Forward port https://github.com/rancher/rancher/pull/34208 
#34233
=> set kubernetes.io/cluster tag for rke2 ec2 instances

chart/templates/secret.yaml
=> [2.6.1] ForwardPort fix error when upgrading helm chart

pkg/apis/provisioning.cattle.io/v1/cluster.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/provisioningv2/kubeconfig/manager.go
Context: https://github.com/rancher/rancher/issues/34107#issuecomment-899820635
=> Add ability to redeploy system-agent

pkg/apis/rke.cattle.io/v1/etcd.go
https://github.com/rancher/rancher/issues/34088
=> Bucket is not required as it can come from the credential now

pkg/controllers/management/node/controller.go, pkg/data/management/add.go, pkg/data/management/key_cleanup.go
https://github.com/rancher/rancher/issues/34250
=> Remove sshKey field from v3.Cluster/v3.Node

pkg/controllers/provisioningv2/rke2/machineprovision/template.go, pkg/controllers/provisioningv2/rke2/machinestatus/machinestatus.go
https://github.com/rancher/rancher/issues/32601
=> Don't run machine pods as root

pkg/apis/provisioning.cattle.io/v1/cluster.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/provisioningv2/kubeconfig/manager.go
Forward-port of https://github.com/rancher/rancher/pull/34181
=> [master]Add ability to redeploy system-agent

pkg/controllers/provisioningv2/rke2/machineprovision/template.go, pkg/controllers/provisioningv2/rke2/machinestatus/machinestatus.go
https://github.com/rancher/rancher/issues/32601
=> [2.6] Don't run machine pods as root

pkg/api/norman/customization/node/node.go
https://github.com/rancher/rancher/issues/34253
=> Don't show scaledown link if not authorized

pkg/api/norman/customization/node/node.go
=> [2.6] Don't show scaledown link if not authorized

pkg/kontainer-engine/drivers/aks/aks_driver.go
https://github.com/rancher/rancher/issues/31154
=> [release/v2.5] Sync AKS regions from aks-operator

pkg/settings/setting.go
=> [2.6] Remove token hashing setting if unused

pkg/api/steve/disallow/disallow.go, pkg/api/steve/setup.go
=> [2.6]  Only allow edits to management/project.cattle.io to go through norman 

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/planner.go
=> [2.6] Fix taints for custom nodes and regression on machine pools

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/34295
=> Fix taints for custom nodes and regression on machine pools

pkg/agent/clean/cluster.go
https://github.com/rancher/rancher/issues/33800
=> Don't cleanup an imported cluster on remove if Rancher is installed

pkg/agent/clean/cluster.go
https://github.com/rancher/rancher/issues/33800
=> [2.6] Don't cleanup an imported cluster on remove if Rancher is installed

package/Dockerfile
issues
rancher/rancher#33988
rancher/rancher#34188
related PR:
https://github.com/rancher/charts/pull/1418
=> bump rancher-webhook to 0.2.0-beta05

pkg/controllers/dashboard/helm/register.go, pkg/controllers/dashboard/helm/repo.go
forward-port of https://github.com/rancher/rancher/pull/34212
=> [master forward-port] add checks for no-existing IndexConfigMap in repo.status

pkg/settings/setting.go
https://github.com/rancher/rancher/issues/34277
=> [2.6]Update shell to v0.1.10

go.mod, pkg/rancher/migrations.go
https://github.com/rancher/rancher/issues/34149
https://github.com/rancher/rancher/pull/34251
=> [2.6.1] Foward Port: fixed version checks for force logout

pkg/catalogv2/helmop/operation.go, pkg/settings/setting.go, pkg/wrangler/context.go
https://github.com/rancher/rancher/pull/34317
https://github.com/rancher/rancher/pull/34331
=> [master]Forward port

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/cluster/private_registry.go
https://github.com/rancher/rancher/issues/28693
Includes https://github.com/rancher/rke/pull/2659
=> Use ECR credential helper if configured

go.mod, go.sum
=> Update vendor to include apiserver fb33444

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go, pkg/controllers/provisioningv2/rke2/machinestatus/machinestatus.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/provisioningv2/rke2/planner/filter.go, pkg/provisioningv2/rke2/planner/planner.go
=> [2.6] Make machine pools editable

pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go
fix for the issue found in rancher/rancher#34282
=> add linux nodeselector to plans

pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go
backport fix for https://github.com/rancher/rancher/issues/34282
=> [2.6] add linux nodeselector to system-upgrade-controller plans

pkg/data/management/machinedriver_data.go
=> [2.6] Bump harvester node driver to 0.3.0

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/cluster/private_registry.go
https://github.com/rancher/rancher/issues/28693
=> [2.6] backport Use ECR credential helper if configured

Dockerfile.dapper, scripts/package
issue: https://github.com/rancher/rancher/issues/32600
backports: https://github.com/rancher/rancher/pull/34356
=> [release/v2.6 backport] Add system agent images to package script

pkg/controllers/provisioningv2/rke2/machinestatus/machinestatus.go
A previous change mistakenly set the Provision status when a machine was
being deleted. This change now updates the InfrastructureReady condition
when it has been detected that the infrastructure object has been 
deleted.
This is necessary because the CAPI machine controller is waiting for the
infrastructure object to be deleted and this is required so that the 
CAPI controller runs again.
Issues:
https://github.com/rancher/rancher/issues/34235
https://github.com/rancher/rancher/issues/34264
=> Put deleted status message on InfrastructureReady condition

pkg/client/generated/management/v3/zz_generated_ecr_credential_plugin.go, pkg/client/generated/management/v3/zz_generated_private_registry.go, pkg/settings/setting.go
Relevant issue: https://github.com/rancher/rancher/issues/32403
Relevant comment: https://github.com/rancher/rancher/issues/32403#issuecomment-903128377
=> Ensure system agent installer can use private registries

pkg/client/generated/management/v3/zz_generated_ecr_credential_plugin.go, pkg/client/generated/management/v3/zz_generated_private_registry.go, pkg/settings/setting.go
Relevant issue: #32403
Relevant comment: #32403 (comment)
=> [2.6] Ensure system agent installer can use private registries

pkg/provisioningv2/rke2/planner/s3args.go
https://github.com/rancher/rancher/issues/34365
https://github.com/rancher/rke2/issues/1685
=> [2.6] Only append s3 args if necessary

pkg/provisioningv2/rke2/planner/s3args.go
https://github.com/rancher/rancher/issues/34365
https://github.com/rancher/rke2/issues/1685
=> Only append s3 args if necessary

pkg/controllers/management/k3sbasedupgrade/template.go
https://github.com/rancher/rancher/issues/34431
=> [v2.6] add linux selector for upgrade plans

pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go, pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/registry.go
https://github.com/rancher/rancher/issues/34223
=> [2.6] Fix registry basic auth

pkg/provisioningv2/rke2/planner/planner.go
A previous change set the node-external-ip if the user did not provide
one. Instead, the node-external-ip is only set if a cloud provider is
not provided and if an IP address and private IP address can be
identified and are different. In addition, if the node-external-ip
address is set, then the advertise-address is set to the internal
address to maintain consistency.
Issues:
https://github.com/rancher/rancher/issues/32390
https://github.com/rancher/rancher/issues/34497
=> Be more particular when setting node-external-ip

Dockerfile-windows.dapper, package/windows/Dockerfile.agent
This is the fix for the following issues:
* https://github.com/rancher/rancher/issues/34292
* https://github.com/rancher/windows/issues/77
=> Cleaning up the PS Gallery and upgrading versions to match Linux

Dockerfile-windows.dapper, package/windows/Dockerfile.agent
This is the fix for the following issues:
* https://github.com/rancher/rancher/issues/34292
* https://github.com/rancher/windows/issues/77
=> [Backport 2.6] Cleaning up the PS Gallery and upgrading versions to match Linux

pkg/controllers/dashboard/helm/register.go, pkg/controllers/dashboard/helm/repo.go
issue https://github.com/rancher/rancher/issues/34466
backport of https://github.com/rancher/rancher/pull/34212
=> [2.5 Backport] add checks for no-existing IndexConfigMap in repo.status

tests/validation/lib/aws.py
Upstream related issues:
https://github.com/kubernetes/cloud-provider-aws/issues/184
https://github.com/kubernetes/kubernetes/issues/29298
=> Automation - tag subnets with cluster name before creating EKS and ELB

.drone.yml, Dockerfile-windows.dapper, Dockerfile.dapper, scripts/fossa, scripts/windows/fossa.ps1
https://github.com/rancherlabs/eio/issues/504
=> add fossa steps and setup dapper env with installer

tests/validation/tests/v3_api/resource/terraform/rke2/master/install_rke2_master.sh, tests/validation/tests/v3_api/resource/terraform/rke2/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/rke2/master/join_rke2_master.sh, tests/validation/tests/v3_api/resource/terraform/rke2/worker/instances_worker.tf, tests/validation/tests/v3_api/resource/terraform/rke2/worker/join_rke2_agent.sh, tests/validation/tests/v3_api/test_airgap.py, tests/validation/tests/v3_api/test_custom_host_reg.py
Pull the latest validation changes from `master` branch into `release/v2.6`
```
git fetch upstream
git rebase upstream/master
git push
git checkout release/v2.6
git checkout -b validation-parity
git checkout master -- tests/validation/
git status
git commit
```
=> Validation - Copy latest changes from master to release/v2.6 branch

.drone.yml
fixes this error: http://drone-publish.rancher.io/rancher/rancher/6495/5/3
=> add docker socket for dapper

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Issue: https://github.com/rancher/rancher/issues/34026
=> [release/v2.5] Update rke to v1.2.12

pkg/features/feature.go
Add harvester feature flag
https://github.com/rancher/rancher/issues/33605
=> Add harvester feature flag

pkg/provisioningv2/rke2/planner/registry.go
When provisioning an RKE2/K3S cluster with a private registry, the user
has the option to provide TLS and/or CA bundle. If the user did not
provide a TLS secret, but did provide a CA bundle, Rancher would panic.
This fixes that panic, and a user can now provide TLS secret and/or CA
bundle without issue.
Issue:
https://github.com/rancher/rancher/issues/34425
=> Stop panic if registry CA bundle given without TLS

pkg/controllers/managementuser/networkpolicy/netpol.go, pkg/controllers/managementuser/networkpolicy/register.go
Issue:
- https://github.com/rancher/rancher/issues/34084
=> [2.5 Backport] Fix host network policies for Calico CNI

package/Dockerfile
issue: 
https://github.com/rancher/rancher/issues/34453
https://github.com/rancher/rancher/issues/34320
=> bump rancher-webhook to 0.1.200

tests/validation/requirements_v3api.txt, tests/validation/tests/v3_api/test_secrets.py
Automation scrips have been failing due to a breaking change that was introduced from v2.6
- Changed the env variable to "environment" and envFrom to "environmentFrom"
- Verify for v2.5 and below releases, env and envfrom works
- Verify from 2.6 "environment" and "environmentFrom" works
=> Fixing secrets in automation. 

pkg/api/norman/customization/aks/handler.go, pkg/api/norman/customization/aks/listers.go
#34161
Old pr for reference: #34624, #34698
In AKS you cannot skip minor version updates. Currently we list all available versions in the upgrade drop down. This lets users attempt to upgrade to version that is too high causing the cluster to go into a constant error state.
I added the a new endpoint, `/meta/aksUpgrades`. This endpoint will return all available k8s versions similar to `/meta/aksVersions` however each version includes an enabled  flag.  This flag is true if the associated version is a valid upgrade version for the given cluster.
=> added aksUpgrade versions endpoint

pkg/api/steve/catalog/content.go, pkg/api/steve/catalog/content_test.go
=> [2.5] Add content headers for steve catalog server

package/Dockerfile
issue: https://github.com/rancher/rancher/issues/34691
will be merged after https://github.com/rancher/charts/pull/1476 is merged
=> bump CATTLE_RANCHER_WEBHOOK_MIN_VERSION to 1.0.1+up0.2.1

pkg/apis/management.cattle.io/v3/cluster_types.go, pkg/client/generated/management/v3/zz_generated_cluster.go, pkg/client/generated/management/v3/zz_generated_cluster_status.go, pkg/controllers/management/clusterstats/statsaggregator.go
* adds worker counts by os to the statsaggregator
* moves nodecount from a formatter to the statsaggregator
https://github.com/rancher/rancher/issues/34747
=> Add worker counts by OS

pkg/clusterrouter/factory.go, pkg/clusterrouter/proxy/proxy_server.go, pkg/clusterrouter/router.go, pkg/controllers/managementuser/rbac/impersonation_handler.go, pkg/impersonation/impersonation.go, pkg/k8sproxy/k8s_proxy.go
Backport of https://github.com/rancher/rancher/pull/34351
Backport of https://github.com/rancher/rancher/pull/34243
https://github.com/rancher/rancher/issues/34454
=> [v2.5] Retrieve the UserContext for cluster dynamically

pkg/clusterrouter/proxy/proxy_server.go, pkg/controllers/managementuser/rbac/impersonation_handler.go, pkg/impersonation/impersonation.go, pkg/impersonation/impersonation_test.go
Backport of https://github.com/rancher/rancher/pull/34766
Issue https://github.com/rancher/rancher/issues/34828
=> [v2.5] Fix conflict errors for impersonation cluster role 

pkg/apis/management.cattle.io/v3/authn_types.go
https://github.com/rancher/rancher/issues/34756
Fixing schema to make azure applicationSecret nullable.
Corresponding Dashboard PR https://github.com/rancher/dashboard/pull/4218
=> Make azure secret field nullable

tests/validation/tests/v3_api/Jenkinsfile, tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test, tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_ontag, tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix, tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests, tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_rke2_upgrade
updating all Jenkinsfiles to use release/v2.6 instead of master
=> Validation - Update jenkinsfile from `master` -> `release/v2.6`

pkg/impersonation/impersonation.go
Currently, the impersonation path checks for the existence of a matching
impersonation clusterrole on the downstream cluster and then assumes
there is an impersonation service account to go with it. If for some
reason there was an interruption in between creating the clusterrole and
creating the service account, the service account won't exist and
further requests will be perpetually stuck. This change ensures that
won't happen by checking for a Not Found error when retrieving the
service account, and continuing to create the needed resources in such
an event. This also fixes an unclear error message to clarify that the
missing resource is the service account, not the secret, and to
distinguish it from another similar error message.
https://github.com/rancher/rancher/issues/34824
=> Make impersonation service account more resilient

pkg/agent/rancher/rancher.go, pkg/api/steve/catalog/catalog.go, pkg/api/steve/catalog/operation.go, pkg/api/steve/clusters/clusters.go, pkg/api/steve/clusters/shell.go, pkg/api/steve/proxy/proxy.go, pkg/catalogv2/helmop/operation.go, pkg/catalogv2/system/system.go, pkg/controllers/managementuser/settings/controller.go, pkg/rancher/rancher.go, pkg/systemtemplate/import.go, pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/34863
=> [2.6]Add support for cluster-level registry(rke) for shell and helm

pkg/settings/setting.go, tests/integration/suite/test_system_project.py
Backport of https://github.com/rancher/rancher/pull/33701
=> Add impersonation namespace to system namespaces

pkg/impersonation/impersonation.go
Currently, the impersonation path checks for the existence of a matching
impersonation clusterrole on the downstream cluster and then assumes
there is an impersonation service account to go with it. If for some
reason there was an interruption in between creating the clusterrole and
creating the service account, the service account won't exist and
further requests will be perpetually stuck. This change ensures that
won't happen by checking for a Not Found error when retrieving the
service account, and continuing to create the needed resources in such
an event. This also fixes an unclear error message to clarify that the
missing resource is the service account, not the secret, and to
distinguish it from another similar error message.
Backport of …
=> [v2.5] Make impersonation service account more resilient

pkg/controllers/dashboard/fleetcharts/controller.go, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/34866
=> Assign fleet-local/local agentNamespace from helm install

pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/provisioningv2/rke2/planner/planner.go
Reverts PR https://github.com/rancher/rancher/pull/34922
=> Revert "Add agent args to environment for instruction"

scripts/provisioning-tests, scripts/test
Also if the Rancher dies echo the log so we can debug why it failed to start
=> Add restart hack to provisioning tests

pkg/api/norman/customization/kontainerdriver/actionhandler.go, pkg/channelserver/channelserver.go
https://github.com/rancher/rancher/issues/34473
=> [v2.6] reload rke2/k3s config on kdm refresh action

pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go
We need to add provider label `provider.cattle.io` to v3 cluster so that we know the type of the cluster based its label. This is used by harvester team to filter out clusters in UI/fleet based on labels. It also provides a way to filter clusters based on provider label without inspecting status.provider.
Related 
https://github.com/rancher/rancher/issues/34954
https://github.com/rancher/rancher/issues/34880
cc @yasker
=> Add provider labels to v3 cluster

pkg/controllers/managementuser/settings/controller.go
Make error more useful by including cluster ID.
=> Add cluster ID to error

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/35164
=> [release/v2.5.11] Bump RKE to v1.2.14-rc2

package/Dockerfile
Related Issue:
https://github.com/rancher/rancher/issues/35203
=> Bump CLI to 2.6.0-rc1

pkg/auth/providerrefresh/refresher.go, pkg/controllers/management/auth/manager.go, pkg/controllers/managementuser/alert/deployer/upgradeimpl.go, pkg/controllers/managementuser/rbac/handler_base.go, pkg/controllers/managementuser/rbac/prtb_handler.go, pkg/controllers/managementuser/rbac/roletemplate_handler.go, pkg/controllers/managementuser/secret/secret.go, pkg/wrangler/context.go
Refer to the comments of the individual commits.
=> Performance fixes

pkg/controllers/management/auth/manager.go
Issue:
- rancher/rancher#33815
=> Add namespace to desiredRBs so subsequent logs are accurate

package/Dockerfile
Issue:
https://github.com/rancher/rancher/issues/35203
=> Bump CLI to 2.6.0-rc2

pkg/controllers/managementuser/nsserviceaccount/nssvcaccnt.go
Patch default serviceAccount for new namespaces that get added to the local cluster by Rancher while deploying a downstream cluster.
The rancher controller will also look at the namespaces having system-namespace annotation ("management.cattle.io/system-namespace") and also those added to the system project, and patch the default serviceAccounts for them so that 5.1.5 test is not broken.
=> Patch default serviceAccount for new system namespaces

cmd/agent/main.go, go.mod, go.sum, main.go, pkg/apis/go.mod, pkg/apis/go.sum
#34712
see https://github.com/rancher/wrangler/pull/183 for details
=> [2.6.3] bump wrangler

pkg/catalogv2/helmop/operation.go, pkg/catalogv2/helmop/operation_test.go, pkg/controllers/managementuser/helm/common/common.go, pkg/controllers/managementuser/helm/controller.go, pkg/settings/setting.go
**Backport Issue:**
https://github.com/rancher/rancher/issues/35407
https://github.com/rancher/rancher/issues/35410
https://github.com/rancher/rancher/pull/35202
=> [Backport] v2.5: Apps migration

package/Dockerfile, pkg/controllers/management/feature/feature_handler.go, pkg/data/management/machinedriver_data.go
address https://github.com/rancher/rancher/issues/34886
Harvester issue [#1465](https://github.com/harvester/harvester/issues/1465)
=> toggle harvester node driver based on global harvester feature 

pkg/controllers/managementuser/settings/controller.go
https://github.com/rancher/rancher/pull/34939
=> [Backport] v2.5: Update error

pkg/clustermanager/manager.go
Issue: 
- https://github.com/rancher/rancher/issues/35446
2.5 PR: 
- https://github.com/rancher/rancher/pull/35172
=> Use correct context when creating access control

pkg/types/config/context.go
This PR lays the framework to allow user controllers to watch for
conditions before they start their caches/controllers. This is to allow
performance gains if the user is not using any legacy features.
Also included is the ability to limit which namespaces a controller is
watching which will be used by the impersonation logic in a follow on
PR.
https://github.com/rancher/rancher/issues/35503
=> Add the ability to defer the start of user controllers

pkg/api/scheme/scheme.go
#35445
#35491
Some resources in norman have values stored on them that are not part of go struct associated with their GVK.  When norman uses the appropriate go struct it will drop any field not on that go struct causing fields to be missing when listing resources. 
Do not inform norman about the struct associated with some GVKs so that it will fall back to the unstructured object and allow the missing fields to be included.
I confirmed with a digital ocean node template that the list objects matched the individual get object responses.
=> [2.6.3] exclude resources that do not represent all their potential fields

pkg/api/norman/customization/cluster/validator.go
Issue:
https://github.com/rancher/dashboard/issues/4410
=> Update norman validation to allow RKE2/K3S ACE config

pkg/controllers/managementuser/clusterauthtoken/register.go
The clusterauthtoken controller is only started if v3.Cluster.Spec.LocalClusterAuthEndpoint.Enabled is true.  This controller is responsible for syncing tokens to the downstream clusters for ACE to work properly
=> Only start clusterauthtoken controller if ACE is enabled

pkg/controllers/managementuserlegacy/alert/controller.go
If the Legacy feature flag is enabled or a ClusterAlert or a Notifier exists then the alert user controller will be started. This controller is responsible for alerts from monitoring v1.
=> Only enable alert user controller is used

pkg/controllers/managementuser/networkpolicy/register.go
Network policy controller is only started if v3.Cluster.Spec.EnableNetworkPolicy is true.  The controller is responsible for programing Project Network Policies.
=> Only start networkpolicy user controller if EnabledNetworkPolicy is set

pkg/controllers/provisioningv2/cluster/controller.go
When an imported cluster is created, it is created as a provisioningv2
cluster. However, after an imported cluster is recognized as an RKE2/K3S
cluster, then the management cluster is edited. This caused a problem
because the provisioning cluster controllers would overwrite the ACE
config on the management cluster as soon as the management cluster was
edited.
Now, the ACE config is deleted before the provisioning controller saves
the management cluster preventing the ACE config on the management
cluster from being overwritten.
Issue:
https://github.com/rancher/rancher/issues/35161
=> Stop overwriting ACE config for imported RKE2/K3S clusters

pkg/controllers/managementuserlegacy/cis/register.go
Only start CIS v1 controller if a v3.ClusterScan exists.  The CIS controller is responsible for running CIS benchmark scan using v1 framework.
=> Only start cis v1 user controller if a ClusterScan exists

pkg/controllers/managementuserlegacy/globaldns/user_cluster_ingress.go
Only start the globaldns controller if a v3.GlobalDns exists that points to this cluster.  The globaldns controllers is responsible for updating the v3.GlobalDns.Status.Endpoints field for the specific downstream cluster.
=> Only start globaldns user controller if GlobalDns object exists

pkg/controllers/managementuserlegacy/helm/controller.go
helm controller is started only if a v3.App for this cluster exists.  The helm controller will install apps from catalog v1.
=> Only start helm controller if v3.App exists

pkg/controllers/managementuserlegacy/logging/controller.go
The logging controller is responsible for instantiating logging v1 in the downstream clusters.
=> Only start logging user controller if Cluster/ProjectLogging exists

pkg/controllers/managementuserlegacy/monitoring/register.go
Only start monitoring user controller if EnableClusterMonitor on v3.Cluster is true or EnableProjectMonitoring on v3.Project is true. This controller runs the monitoring v1 components.
=> Defer start of monitoring user controller

pkg/controllers/managementuser/resourcequota/register.go
Only start the resourcequota controller if ContainerDefaultResourceLimit, ResourceQuota, or NamespaceDefaultResourceQuota is set on a project.  The resourcequota controller is used for programming Project resource quotas
=> Only start resourcequota controller if quotas are set on project

pkg/controllers/managementuser/certsexpiration/certsexpiration.go
Cert expiration controller is only started for RKE1 clusters.  This controller is responsible for populating the v3.Cluster.Status.CertificatesExpiration field.
=>  Only start cert expiration controller on RKE1 clusters 

pkg/apis/management.cattle.io/v3/authz_types.go, pkg/apis/management.cattle.io/v3/cluster_types.go, pkg/controllers/managementuser/rbac/project_handler.go, pkg/rancher/migrations.go, pkg/rancher/rancher.go
Forwardport of #35359 addressing some issues that were missed in the original PR.
Related Issue: #32898
=> Fix namespaces not being moved to System project on upgrade

pkg/types/config/context.go, pkg/wrangler/context.go
https://github.com/rancher/rancher/issues/35513
=> Prefer protobuf encoding

pkg/controllers/managementuser/secret/secret.go
Only start secret controller if a secret is found in the project namespace in the management cluster that doesn't start with "default-token-".  The secret controller is what populates projects secrets that are available to all namespaces in a project.
=> Only start secret controller if more that one secret exists in project ns

pkg/controllers/managementuserlegacy/approuter/approuter.go
Only start the approuter user controller if configured to a different API
endpoint.  This feature does not seem to be used anymore as the default
setting points to a service that doesn't exist (https://api.lb.rancher.cloud/v1).
If the setting points to the default we know it doesn't work so only
start the user controller if it's set to some other non-empty string.
The approuter controller will call RancherDNS service and get a hostname
for is the hostname of ingress rule is set to lb.rancher.cloud and the
ingress-ip-domain setting is set to lb.rancher.cloud. Since there is
no know working version of the RancherDNS service the only way you can
test would be to set the setting rdns-base-url to something like
http://example.com and log for errors in rancer like
"udpate fqdn [%s] to server …
=> Defer start of approuter user controller

pkg/controllers/managementuser/controllers.go, pkg/impersonation/impersonation.go
The only controllers that should run on followers for user controllers
are
roles
rolebindings
clusterroles
clusterrolebindings
namespaces
Then specifically for impersonation we run secret and serviceaccount but
only watching the cattle-system-impersonation namespace
#35565
=> Minimize the caches ran on followers

pkg/controllers/managementuser/pspdelete/pspdelete.go
Only start pspdelete user controller if DefaultPodSecurityPolicyTemplateName is set on the v3.Cluster and its RKE2 managed cluster.  The pspdelete controller is used specifically for RKE2 to PSP with "psp.rke2.io/global-unrestricted" and "psp.rke2.io/global-restricted" annotations that are created by default for RKE2.
=> Defer start of pspdelete user controller

pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/machinestatus/machinestatus.go
The CAPI machine controller will automatically sync the Ready condition
on the infra machine object to the InfrastructureReady condition on the
machine. This was causing issues when setting the InfrastructureReady
condition on the Machine (which we needed to to so the CAPI machine
controller would pick up the changes).
Now, the Ready condition on the infra machine and the
InfrastructureReady condition on the machine are set to the same thing
to avoid this confusion.
Issue:
https://github.com/rancher/rancher/issues/34945
=> Better sync of infra machine conditions

pkg/controllers/management/clusterconnected/clusterconnected.go, pkg/controllers/management/clusterdeploy/clusterdeploy.go
=> If a cluster agent is disconnect show disconnected message, not error

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/35614
=> pin rke release/v1.3 for windows + 1.22

pkg/controllers/managementuser/healthsyncer/healthsyncer.go
https://github.com/rancher/rancher/issues/34055
=> disable component status for k8s >=1.22

package/Dockerfile
Relevant issue: https://github.com/rancher/rancher/issues/35366
=> Bump webhook min version to 0.2.2-rc2

go.mod, go.sum, pkg/api/norman/customization/catalog/store.go, pkg/api/norman/customization/catalog/store_test.go, pkg/api/norman/server/managementstored/setup.go, pkg/api/norman/server/userstored/proxy_store.go, pkg/api/norman/store/secret/store.go, pkg/api/scheme/scheme.go, pkg/apis/go.mod, pkg/apis/go.sum, pkg/apis/management.cattle.io/v3/catalog_types.go, pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go, pkg/auth/api/setup.go, pkg/catalog/manager/manager.go, pkg/catalog/manager/manager_test.go, pkg/controllers/managementuser/clusterauthtoken/crd.go, pkg/controllers/managementuser/helm/controller.go, pkg/generated/controllers/management.cattle.io/v3/catalogtemplate.go, pkg/generated/controllers/management.cattle.io/v3/catalogtemplateversion.go
=> [2.5.12] Backport: pass typers to norman stores 

pkg/data/management/role_data.go
Issue:
- https://github.com/rancher/rancher/issues/34669
=> [2.5] Backport catalog permissions

pkg/rancher/rancher.go
=> The project type is not available when MCM=false

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/35656
Bumping version of Wrangler to one that includes the fix (https://github.com/rancher/wrangler/pull/187)
=> Fix Import YAML when mix of namespaced and cluster-scoped objects is used

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_docker_info.go, pkg/client/generated/management/v3/zz_generated_launch_template.go, pkg/client/go.mod, pkg/client/go.sum
Issue:
https://github.com/rancher/terraform-provider-rancher2/issues/693
=> Bump norman id fix

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/rkeworker/docker.go
* Vendors https://github.com/rancher/rke/pull/2750
* Adds a dummy version parameter as function changed but is not used in this call
=> [release/v2.6] vendor rke

pkg/provisioningv2/rke2/planner/planner.go
To ensure we update only as many nodes in parallel as configured a running
count of unavailable nodes is kept. Previously only nodes with out of sync
plans would be treated as unavailable.  We now also check that the node
is in a drain state and treat it as unavailable so that we don't drain
more nodes in parallel than configured.
Additionally when considering the concurrency of updates of the init node
we were not looking at all etcd nodes.  This meant that if one etcd node
was being updated and that node was not the init node, and then you make
another provisioning change, we would update the init node before the other
etcd node finished provisioning.  This could violate the configured
concurrency.
#35464
=> Count draining nodes as unavailable

pkg/controllers/managementuser/nodesyncer/nodessyncer.go
**Issue:**
When powered down, node shows Unavailable from Cluster explorer view but shows up as Active from cluster management view. 
**Solution**
Norman embeds internalNodeStatus.Conditions to node.status.Conditions which causes the ready condition to show up correctly on v3 calls. Syncing it to v3 node.status.conditions for steve v1 node calls to get the same effect. 
https://github.com/rancher/rancher/issues/35646
=> sync internal node ready condition to v3 node condition

pkg/api/norman/customization/catalog/store.go
**Problem:**
Versions that are not compatible with current
setup but are already in use are being filtered out. This is required to facilitate the UI, otherwise the version is treated
as though the version doesn't exist, despite being in use.
**Solution:**
A currentVersion query parameter can now be passed when making
templates requests to norman. This parameter will cause any
version matching it to be included in versionLinks. This is
being done so versions that are not compatible with current
setup but are already in use do not have to be filtered out.
This is required to facilitate the UI, otherwise it is treated
as though the version doesn't exist, despite being in use.
**Issue:**
https://github.com/rancher/rancher/issues/35680
=> Add currentVersion query parameter for templates

pkg/rancher/rancher.go
If upgrading a Docker install to Rancher v2.6.3+, then the k3s cluster
that runs in the Docker container has version 1.22+. The issue is that
the rancher-webhook v0.2.1 or less doesn't support Kubernetes 1.22+.
Rancher will try to upgrade rancher-webhook on startup, but it will
fail in this case because the validation webhook (that is called when
the service account is created for the helm pod) fails because the
currently installed rancher-webhook crashed. Therefore, in the Docker
install scenario, rancher-webhook has to be upgrade to a supported
version for Kubernetes 1.22+
Issues:
https://github.com/rancher/rancher/issues/35696
https://github.com/rancher/rancher/issues/35763
=> Check rancher-webhook version on Docker container startup

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/35831
https://github.com/rancher/rancher/issues/35437#issuecomment-989860581
=> [release/v2.6] vendor rke v1.3.3-rc5

pkg/metrics/metrics.go
https://github.com/rancher/rancher/issues/35838
=> Metrics must use usercontext with controllers

pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/probe.go
https://github.com/rancher/rancher/issues/35683
=> Switch `kube-controller-manager` and `kube-scheduler` to using secure ports for v2prov probe

pkg/controllers/managementuserlegacy/monitoring/register.go
issue: https://github.com/rancher/rancher/issues/35776
The app `monitoring-operator`, which is the prometheus-operator under the hook,  is required for alerting to work, so we need to enable the prometheus-operator-handler when either monitoring or alerting is enabled.
=> enable the prometheus-operator-handler when either monitoring or alerting is enabled

pkg/controllers/management/clusterstats/statsaggregator.go
When a cluster is created with version 1.18 or lower, various
controllers will start a watch for the extensions/v1beta1/Ingress type.
Without this patch, if that cluster is then upgraded to 1.22, those
watches will start to fail because that API is no longer available, and
the controllers using those watches will stop syncing because they don't
see events for the new Ingress type, networking.k8s.io/v1/Ingress.
This patch adds a check to the clusterstats controller, where the
cluster version status is updated, and annotates the cluster agent
deployment template which forces a restart of the cluster agents. Simply
forcing the agent to be reapplied via the clusterdeploy controller does
not necessarily fix the problem because if there is no change to the
cluster agent deployment template then …
=> Restart agent pods after upgrade to 1.22

pkg/provisioningv2/rke2/planner/probe.go
https://github.com/rancher/rancher/pull/35749#discussion_r766898782
=> Correct comment in probe

pkg/multiclustermanager/routes.go
=> Add ui-brand as an unauthenticated setting

package/Dockerfile
This needs to be a non-rc version for release. 
Charts PR: 
- https://github.com/rancher/charts/pull/1655
=> Update webhook version

tests/validation/tests/Dockerfiles/windows/testcontainer/Dockerfile, tests/validation/tests/Dockerfiles/windows/testcontainer/run.ps1
move everything to run.ps1 and use CMD instead of ENTRYPOINT
=> fixing testcontainer windows dockerfile

pkg/controllers/management/clusterstats/statsaggregator.go
There is no cluster agent on the local cluster so it does not need to be
restarted. Attempting to look up the local cluster agent and update it
was failing because the Deployment object returned from Get was non-nil
but empty, so trying to Update that object was invalid. This change 1)
skips the agent restart for local clusters, 2) moves the restart to
after the cluster update so that any errors that occur don't interfere
with saving the version on the cluster object, and 3) fixes the
deployment lookup to check for Not Found rather than nil.
https://github.com/rancher/rancher/issues/35902
=> Ignore cluster agent restart for local cluster

pkg/controllers/management/clusterstats/statsaggregator.go
EKS clusters are reporting their minor version in a non-numeric way:
```
kubectl  version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
The version comparison in the statsaggregator is expecting an int-like
value in the Minor field. This change adds some sanitization to make
sure the field looks the way it is expected to. …
=> Sanitize version input

go.mod, go.sum
https://github.com/rancher/lasso/commit/3c6118a30611c8412937e1773f158f7cf27f2256
=> Update lasso for deadlock fix

pkg/api/norman/customization/app/app.go, pkg/api/norman/server/managementstored/setup.go, pkg/types/config/context.go
https://github.com/rancher/rancher/pull/35779
**Issue:**
https://github.com/rancher/rancher/issues/35948
=> [Backport] v2.5: Check if matching dashboard app exists

pkg/controllers/management/usercontrollers/controller.go
On error of cleaning up an imported cluster, the `clusterUnavailable` error was expected, however this was because attempting to get the `UserContext` was always trying to create controllers, which would fail if the deletion timestamp was not nil. Now that this is not necessary, the cleanup is able to use a `UserContext` without creating any controllers, and therefore fails when trying to create a cluster role on the unavailable downstream, thus generating a `url.Error` with `Error() == "cluster agent disconnected"`.
This PR fixes the above issue by checking for `cluster agent disconnected` instead of `httperror.ClusterUnavailable`.
- It may be necessary to hard refresh (F5) to see these changes in effect, as my imported cluster stayed in the sidebar until doing so (after about 30 …
=> Cluster cleanup now ignores cluster agent disconnected error

pkg/apis/catalog.cattle.io/v1/types.go, pkg/catalogv2/content/content.go, pkg/catalogv2/http/client.go, pkg/catalogv2/http/client_test.go, pkg/catalogv2/http/download.go, pkg/client/generated/project/v3/zz_generated_app.go, pkg/client/generated/project/v3/zz_generated_app_spec.go, pkg/controllers/dashboard/helm/repo.go
https://github.com/rancher/rancher/issues/35940
https://github.com/rancher/rancher/pull/35648
=> [v2.5] Backport auth header

tests/framework/clients/rancher/client.go, tests/framework/extensions/configmaps/configmaps.go, tests/framework/extensions/namespaces/namespaces.go, tests/framework/extensions/secrets/basicAuth.go, tests/framework/extensions/secrets/secrets.go, tests/framework/extensions/storageclasses/awsebs/create.go, tests/framework/extensions/storageclasses/awsebs/volumetype.go, tests/framework/extensions/storageclasses/storageclasses.go, tests/framework/extensions/volumes/persistentvolumeclaims/persistentvolumeclaims.go, tests/framework/extensions/volumes/persistentvolumes/awsebs/create.go, tests/framework/extensions/volumes/persistentvolumes/nodeselectorterms.go, tests/framework/extensions/volumes/persistentvolumes/persistentvolumes.go
Core and storage k8s helpers
**Framework:**
Implemented new client functionality to be able to get a downstream k8s client.
Added helpers for volumes (persistent volumes and persistent volume claims), storage classes, secrets, and config maps
=> Extensions for core and storage k8s functionality.

pkg/settings/setting.go
- Ensure dashboard served up is latest 2.5, rather than fixed 2.5.8
=> [2.5] Update default ui-dashboard-index setting

package/Dockerfile
Needed for https://github.com/rancher/rancher/issues/36079
=> [2.6] Bump rancher-webhook minimum version

pkg/data/management/role_data.go
Removing calls to rolebuilder which overwrote earlier defined
permissions - and a function only used in this process.
=> Removing duplicated rule addition for restricted-admin

pkg/controllers/provisioningv2/rke2/machineprovision/args.go
The constructFilesSecret function will copy the contents of files like
cloud-config to a secret to be passed as a volume to the machine create job. A
previous change reorder these calls, so it did not work correctly. This change
reorders these calls for the intended outcome.
Issue:
https://github.com/rancher/rancher/issues/36109
=> Construct files secret before cmd

package/Dockerfile
Needed for https://github.com/rancher/rancher/issues/35068
=> [2.5] Bump rancher-webhook minimum version

scripts/test
https://github.com/rancher/rancher/pull/36146
https://github.com/rancher/rancher/pull/36143
=> Backport test changes

pkg/apis/rke.cattle.io/v1/etcd.go, pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go, pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/defaultplan.go, pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/initnode.go, pkg/provisioningv2/rke2/planner/instructions.go, pkg/provisioningv2/rke2/planner/manifests.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/planner_test.go, pkg/provisioningv2/rke2/planner/registry.go, pkg/provisioningv2/rke2/planner/s3args.go
https://github.com/rancher/rancher/issues/35344
=> v2prov cluster etcd snapshot object storage

pkg/rancher/migrations.go
I have no idea if this is going to work for https://github.com/rancher/rancher/issues/34971
Part of the work for https://github.com/rancher/rancher/issues/36162
=> Attempt to resolve indexer conflict

package/Dockerfile
Related Issue: https://github.com/rancher/rancher/issues/33724
=> Bump rancher-webhook to 0.1.300-rc2

pkg/api/norman/store/cluster/cluster_store.go
Problem:
When the cluster is provisioned using a clusterTemplate,  new values for the private registry are not applied.
It turns out that the key for registry-related questions contains an index, such as [0], because the data type of the field is a list of PrivateRegistry. But the backend does not handle the bracket notation properly when processing those new values.
Fix:
When a registry-related question is detected, generate a list of PrivateRegistry based on the index value and set it to the correct position in the Cluster object.
GH Issue: https://github.com/rancher/rancher/issues/27166
Related UI issue: https://github.com/rancher/dashboard/issues/3940
=> Fix the issue where private registry url, user and password overrides do not work when the cluster is  provisioned using a clusterTemplate

package/Dockerfile
=> V2.5.12 rc5

package/Dockerfile
Dependent on https://github.com/rancher/charts/pull/1702.
=> Bump rancher-webhook to 0.1.3

tests/framework/clients/rancher/client.go, tests/framework/extensions/secrets/secrets.go, tests/framework/extensions/workloads/cronjobs/create.go, tests/framework/extensions/workloads/daemonsets/create.go, tests/framework/extensions/workloads/deployments/create.go, tests/framework/extensions/workloads/jobs/create.go, tests/framework/extensions/workloads/template.go
**Framework changes**
Created extensions for the different types of workloads: batch jobs, cronjobs, deployments, and daemon sets. Also fixed some comments.
=> Added extensions for workloads

package/Dockerfile, pkg/settings/setting.go, scripts/package
Related to https://github.com/rancher/rancher/issues/36177.
=> [v2.6.3-patch1] Set chart repo and webhook version for release v2.6.3-patch1

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Updated go mod to include RKE v1.2.17-rc1
=> Update tags for v2.5.12-rc7

.drone.yml, Dockerfile.dapper, package/Dockerfile
- fix drone git clone step stuck on s390x
- fix wrong images for drone digests step on s390x
- add missing kubectl on s390x
=> Fix s390x issues

pkg/api/norman/customization/cluster/actionhandler.go, pkg/api/norman/customization/cluster/formatter.go
Address [GitHub 35828](https://github.com/rancher/rancher/issues/35828)
=> Fix rke1 cluster member action logic

.drone.yml
Update the Fossa step in .drone.yml to address an issue with Fossa when it runs on drone-publish
=> update fossa step in drone

pkg/apis/provisioning.cattle.io/v1/rke.go
Fixing a minor typo
https://github.com/rancher/dashboard/issues/4449#issuecomment-1029580145
=> fixed unhealthyNodeTimeout naming

pkg/controllers/managementuser/nodesyncer/nodessyncer.go
There is a strange panic on Rancher startup where a concurrent map iteration and
map write panic can happen in the nodesyncer.
This change will pass deep copies to the functions where this has been seen to
ensure that the iterations are happening on a different map to get around the
concurrent panic.
The DeepCopy was already happening in these cases, but it was happening after
the iteration. Now it happens before.
=> Fix concurrent map iteration and map write panic

pkg/api/norman/store/cluster/cluster_store.go
Issue:  https://github.com/rancher/rancher/issues/36333
Problem: 
Rancher will crash if setting `rotateEncryptionKey: true` by editing as YAML when creating an RKE cluster. 
Solutions:
1. It turns out to be a bug in rancher/rke which will be fixed in a separate [PR](https://github.com/rancher/rke/pull/2842) there. 
2. It is not a valid operation to enable the rotateEncryptionKey when the encryption configuration is disabled when creating or updating a cluster. When it happens, rke will either panic(will be fixed) or leave the cluster stuck in updating state and ask users to restore a backup.  That is not a good user experience, so this PR will prevent it from happening during the request validating stage. 
Tests:
the following tests are passed:
- create a new RKE cluster, set …
=> Prevent rotating encryption key when encryption configuration is disabled

package/entrypoint.sh
=> Make entrypoint more helpful, and don't immediately exit on error

pkg/apis/rke.cattle.io/v1/certificaterotation.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/provisioningv2/rke2/planner/certificaterotation.go, pkg/provisioningv2/rke2/planner/planner.go
issue #35343
Minor change to make service stop on certificate rotation more effective.
=> use more effective shutdown command for certificate rotation

cmd/agent/main.go, pkg/agent/clean/orphan_bindings.go, pkg/agent/clean/orphan_bindings_windows.go, pkg/controllers/management/auth/globalrole_handler.go, pkg/controllers/management/auth/globalrolebinding_handler.go, pkg/data/management/bindings_cleanup.go, pkg/rbac/common.go, pkg/rbac/common_test.go
Upgrding global role bindings to use new method of creation
=> Upgrading Catalog Role Bindings to use new method of creation

tests/v2/validation/.gitignore, tests/v2/validation/Dockerfile.validation, tests/v2/validation/Jenkinsfile, tests/v2/validation/build.sh, tests/v2/validation/configure.sh
Implemented Jenkinsfile
.gitignore for config files
Dockerfile
configure.sh
build.sh
=> Go Automation Jenkins Pipeline

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
=> Safely create etcd snapshot objects

pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go, pkg/provisioningv2/rke2/configserver/server.go, pkg/provisioningv2/rke2/planner/store.go, scripts/provisioning-tests
https://github.com/rancher/rancher/issues/36162
=> Better log dump for v2prov tests + v2prov reliability enhancements

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
Attempt to fix potential regression caused by: https://github.com/rancher/rancher/pull/36614
https://github.com/rancher/rancher/issues/36162
=> Always provide an rkebootstraptemplate when reconciling MachineDeployment

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Issue: https://github.com/rancher/rancher/issues/34749
Issue: https://github.com/rancher/rancher/issues/36425
Bumped EKS and AKS operator versions to pull in unblocking changes.
=> Bump eks and aks operator versions

pkg/controllers/management/node/cleanup.go
Forwardport of https://github.com/rancher/rancher/pull/36398
https://github.com/rancher/rancher/issues/36645
=> [Forwardport v2.6.3-patch2] Foreground deletion on node-cleanup-job

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
https://github.com/rancher/rke2/issues/2531
This PR fixes four issues
1. Snapshot names can be longer than 63 characters and don't belong in the "labels" field, and are moved to annotations
2. Snapshot storage locations are moved to annotations instead of labels
3. Snapshot CR names had two `-` characters, and those are now removed
4. Snapshot CRs kept being deleted/created because of a miss in indexing.
=> Snapshot name length resolution + cosmetic correction to snapshot name

pkg/provisioningv2/rke2/configserver/server.go
During work related to optimizing the v2provisioning framework code organization, a change was made to a function (`GetServiceAccountSecretNames`) that required additional scaffolding/logic to retrieve a secret from the Kubernetes API/cache. Unbeknownst to me, the carefully crafted return logic and if statements in the configserver allowed for a "watch" of the plan service account secrets to begin if the plan SA was unavailable. 
This change can be seen in the commit found here: https://github.com/rancher/rancher/commit/26d42ee8c689f92a317738494dc76f2a24cb4bdd#diff-af9ef7a0d21257d3c3e8b63041a67a9ec60a605fd47c0f3d083d548a92c58b90R337
This change will correct this issue and should significantly speed up custom cluster provisioning as the system-agent will no longer have to poll at 5 second …
=> [v2prov] Continue waiting for plan secret to become available for custom cluster

pkg/controllers/management/auth/project_cluster_handler.go
#35899 
When a cluster is deleted the rbac is deleted before the cluster finishes deleting.  This prevents standard users from seeing the resource delete event and can hide clusters that encounter errors deleting.
Delete rbac as the last finalizer to ensure the cluster deleted correctly before deleting it.
=> ensure the rbac finalizer is the last finalizer to be removed

pkg/data/management/machinedriver_data.go
This PR integrate Nutanix Rancher Node driver in the default provided list of driver
https://github.com/rancher/rancher/issues/36348
=> Nutanix Rancher Node driver

pkg/controllers/management/rkeworkerupgrader/plan.go, pkg/controllers/management/rkeworkerupgrader/upgrade.go
https://github.com/rancher/rancher/issues/36679
=> Assemble full rke config during rke upgrade

pkg/controllers/management/rkeworkerupgrader/plan.go, pkg/controllers/management/rkeworkerupgrader/upgrade.go
Backport https://github.com/rancher/rancher/pull/36743
=> [v2.4] Assemble full rke config during rke upgrade

pkg/controllers/management/rkeworkerupgrader/plan.go, pkg/controllers/management/rkeworkerupgrader/upgrade.go
Backport https://github.com/rancher/rancher/pull/36743
=> [2.5] Assemble full rke config during rke upgrade

chart/Chart.yaml
https://github.com/rancher/rancher/issues/35739
=> update kubeVersion to allow rancher install on k8s 1.23

scripts/provisioning-tests
https://github.com/rancher/rancher/issues/36483
=> Dump full rancher + k3s logs if rancher/k3s fail

pkg/provisioningv2/rke2/planner/certificaterotation.go
#35343 
If the planner runs the rotation plan more than once per generation  a server's certificate will be rotated multiple times
track the generation on each node and only rotate certificates if the generation is different.
=> made certificate rotation idempotent

pkg/controllers/management/etcdbackup/etcdbackup.go
This reverts commit 7340aeee317a76984ec5b270bf97d48772d686bc.
Discussed with @snasovich, since the last commit wasn't validated yet (and was absent from `v2.5.12` entirely) it's best to revert this commit.
=> Revert "Queue etcd snapshots if snapshot is currently being taken"

pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/store.go
https://github.com/rancher/rancher/issues/36823
https://github.com/rancher/rancher/issues/36807
https://github.com/rancher/rancher/issues/36801
=> Remove retrieval of existing objects in wrangler apply

pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go
https://github.com/rancher/rancher/issues/36842
=> Retrieve snapshot by direct CR name rather than through manipulated CR name

pkg/controllers/management/secretmigrator/clusters.go
Clean questions and answers from AppliedSpec and FailedSpec too.
=> Fully clean rke template answers

pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go
https://github.com/rancher/rancher/issues/36885
=> Compare selective fields for v2prov etcd snapshot restore

pkg/controllers/management/secretmigrator/clusters.go
Clean questions and answers from AppliedSpec and FailedSpec too.
Backport: https://github.com/rancher/rancher/pull/36856
=> [2.4] Fully clean rke template answers

pkg/controllers/managementuserlegacy/alert/configsyncer/configsyncer.go, pkg/controllers/managementuserlegacy/alert/controller.go, pkg/controllers/managementuserlegacy/controllers.go
Ensure notifier configs are assembled for alertmanager.yaml and the
webhook config.yaml for alertmanager.
=> Assemble notifier config for alertmanager

pkg/controllers/managementuser/alert/configsyncer/configsyncer.go, pkg/controllers/managementuser/alert/controller.go, pkg/controllers/managementuser/controllers.go
Ensure notifier configs are assembled for alertmanager.yaml and the
webhook config.yaml for alertmanager.
Backport https://github.com/rancher/rancher/pull/36880
=> [2.5] Assemble notifier config for alertmanager

pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/controller.go, pkg/controllers/user/controllers.go
Ensure notifier configs are assembled for alertmanager.yaml and the
webhook config.yaml for alertmanager.
Backport https://github.com/rancher/rancher/pull/36880
=> [2.4] Assemble notifier config for alertmanager

pkg/controllers/management/etcdbackup/etcdbackup.go
This reverts commit 3700af749996ac8fc16f3349d9ab516c94b4b42f, reversing
changes made to d5d54bf9a8094742c5bea5acd8a9b4de7cecf913.
Pull etcd thrashing fix back into patch release.
=> Revert "Merge pull request #36734 from jakefhyde/revert-thrashing"

pkg/controllers/management/clusterprovisioner/driver.go
Ensure S3 credentials and other credentials are persisted to the
encrypted store during update and restore in addition to create. Without
this, the empty values may be persisted and then will interfere with the
RKE driver's ability to use the credentials for S3 backups.
=> Assemble cluster state before persisting state

pkg/controllers/management/clusterprovisioner/driver.go
Ensure S3 credentials and other credentials are persisted to the
encrypted store during update and restore in addition to create. Without
this, the empty values may be persisted and then will interfere with the
RKE driver's ability to use the credentials for S3 backups.
Backport: https://github.com/rancher/rancher/pull/36903
=> [2.5] Assemble cluster state before persisting state

pkg/controllers/management/clusterprovisioner/driver.go
Ensure S3 credentials and other credentials are persisted to the
encrypted store during update and restore in addition to create. Without
this, the empty values may be persisted and then will interfere with the
RKE driver's ability to use the credentials for S3 backups.
Backport: https://github.com/rancher/rancher/pull/36903
=> [2.4] Assemble cluster state before persisting state

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
https://github.com/rancher/rancher/issues/36899
=> bump rke to fix kube-scheduler authentication kubecfg for 1.23

package/Dockerfile
wins.exe was missed as an ui asset
=> adding wins.exe to the ui assets

pkg/controllers/managementuser/nodesyncer/nodessyncer.go
Backport: https://github.com/rancher/rancher/pull/36902
=> [2.5] Assemble registry config during node sync

pkg/controllers/management/clusterprovisioner/driver.go, pkg/controllers/management/rkeworkerupgrader/plan.go, pkg/controllers/management/secretmigrator/assemblers.go, pkg/controllers/managementuser/nodesyncer/nodessyncer.go
Backport https://github.com/rancher/rancher/pull/36930
=> [2.5] Assemble full RKE config before generating node plan

package/Dockerfile, pkg/provisioningv2/rke2/installer/installer.go, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/36910
=> pinning versions for system agent install and wins agent install scripts

tests/framework/extensions/namespaces/namespaces.go
**Background**
When creating a namespace as a standard user project owner/member there were instances when the cleanup would occur before the cluster role for that namespace had been created therefore logging an RBAC error. There would be cases where the cleanup would not be successful and cause failures in the `project_user_test.go` tests. 
To fix it, I put in a watch to make sure that specific cluster role for that namespace had been created before registering the delete function. Also I used the admin client to watch if the namespace had been deleted, as this was causing permissions issues since the cluster role had been deleted. One the thing remains since the namespace delete function (cleanup) is registered twice, the second delete logs this error because of …
=> Implemented fix to address the timing issue with namespace creation

pkg/cluster/private_registry.go
=> added check when parsing docker config from registry secret

cmd/agent/main.go, pkg/agent/clean/orphan_bindings.go, pkg/agent/clean/orphan_bindings_windows.go, pkg/controllers/management/auth/globalrole_handler.go, pkg/controllers/management/auth/globalrolebinding_handler.go, pkg/data/management/bindings_cleanup.go, pkg/rbac/common.go, pkg/rbac/common_test.go, tests/integration/requirements.txt
Upgrding global role bindings to use new method of creation
=> [Backport] Upgrading Role bindings to use new method of creation

go.mod, go.sum, pkg/api/store/cluster/cluster_store.go, pkg/api/store/clustertemplate/store.go, pkg/controllers/management/etcdbackup/etcdbackup.go, pkg/controllers/management/secretmigrator/assemblers.go, pkg/controllers/management/secretmigrator/clusters.go, pkg/controllers/management/secretmigrator/clustertemplaterevisions.go, pkg/controllers/management/secretmigrator/register.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_template_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
Backport https://github.com/rancher/rancher/pull/37084
=> [2.4] Migrate cluster template fields to secrets

pkg/api/norman/store/cluster/cluster_store.go
Issue: https://github.com/rancher/rancher/issues/37054
Backport the fix from the following PR https://github.com/rancher/rancher/pull/36468
=> [v2.6.3-patch3] drop the field ecrCredentialPlugin when there are no values in it

pkg/controllers/dashboard/clusterregistrationtoken/status.go
* https://github.com/rancher/rancher/issues/36732
=> Removing PowerShell from RKE2 custom registration command.

tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/37107
=> Temporarily disable test_disable_template_revision

pkg/api/norman/customization/clustertemplate/cluster_template.go, pkg/controllers/management/secretmigrator/clustertemplaterevisions.go, tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/37107
=> Fix clustertemplate condition

package/Dockerfile, pkg/settings/setting.go
This updates UI Dashboard index to `release-2.6.3-patch3`
Signed-off-by: Phillip Rak <rak.phillip@gmail.com>
=> Tick UI Dashboard index to release-2.6.3-patch3

pkg/catalogv2/git/download.go, pkg/controllers/dashboard/helm/repo.go
The changes made in this PR has been reviewed already, but they were reverted due to the issue getting pushed to the next milestone.
SURE-3086
Issue: https://github.com/rancher/rancher/issues/31676
Docs Issue: https://github.com/rancher/docs/issues/3864
Original PR: https://github.com/rancher/rancher/pull/36399
Revert PR: https://github.com/rancher/rancher/pull/36977
**Leaving this as a draft until we are done with 2.6.4**
=> Add support in cluster git repos for custom/self-signed certs

pkg/provisioningv2/rke2/planner/initnode.go
This change addresses https://github.com/rancher/rancher/issues/36870
=> [DNM] Change `designateInitNode` log from `INFO` to `DEBUG`

tests/framework/extensions/clusters/aks/aks_cluster_config.go, tests/framework/extensions/clusters/aks/create.go, tests/v2/validation/provisioning/hosted_provisioning_test.go
Implemented helper for provisioning an AKS hosted cluster
Implemented config file read for the particulars of an AKS cluster and its node group
Implemented simple test for an AKS cluster
=> Aks hosted provisioning

tests/v2/validation/Jenkinsfile
**Jenkins File Updates:**
- Added support to specify branch and forked repo for a go automation Jenkins Job.
- Removed the qa credentials that are appended to the config file, and will require them instead.
=> Freeform Jenkins File Update

pkg/api/scheme/scheme.go
https://github.com/rancher/rancher/issues/36267
=> Alerts (v1) do not display alert category or description

tests/framework/extensions/cloudcredentials/cloudcredentials.go, tests/framework/extensions/cloudcredentials/google/create.go, tests/framework/extensions/cloudcredentials/google_config.go, tests/framework/extensions/clusters/gke/create.go, tests/framework/extensions/clusters/gke/gke_cluster_config.go, tests/v2/validation/provisioning/hosted_provisioning_test.go
Framework Updates
Implemented helper for provisioning an GKE hosted cluster
Implemented config file read for the particulars of an GKE cluster.
Validation Tests
Implemented simple test for an GKE cluster
=> Gke hosted provisioning

pkg/controllers/managementuser/rbac/impersonation_handler.go, pkg/impersonation/impersonation.go, pkg/impersonation/impersonation_test.go
The impersonation module checks for Extra attributes in the user.Info
object and adds principal IDs and usernames from an auth provider to the
impersonation ClusterRole rules. Without this patch, this only works
when a user makes a request, because the request includes the
Extra data in the token, but does not work for the role template binding
controllers, which only send the user's UID and groups. The result is
that when a user sends a request, the ClusterRole is updated to include
the Extra data from the request, but after some time, the CRTB and PRTB
controllers will change it back.
With d9ba4d the user's principal IDs and usernames from the auth
provider should now be populated in the UserAttributes for that user, so
we can rely on that instead of whatever data may be in the …
=> [2.6.5] Use UserAttributes for impersonation

pkg/controllers/provisioningv2/rke2/machineprovision/controller.go
Issue: https://github.com/rancher/rancher/issues/37252
When infrastructure machine creation fails, Rancher would sit and never retry
the creation. In certain cases, retrying would solve any creation issues.
This change will delete machines when creation fails, similar to how RKE1
handles retries.
Test provisioning, ensuring failures would occur (in Linode with 3 etcd, 2cp, and 3 worker nodes)
=> Retry machine provisioning on failure

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go, pkg/provisioningv2/rke2/planner/instructions.go, scripts/provisioning-tests
https://github.com/rancher/rancher/issues/34417
=> Fix S3 snapshots to work with newer versions of K3s/RKE2

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
Follow up of: https://github.com/rancher/rancher/pull/37398
https://github.com/rancher/rancher/issues/34417
=> Fix S3 snapshots to work with newer versions of K3s/RKE2 pt. 2

chart/templates/deployment.yaml, chart/tests/deployment_test.yaml
https://github.com/rancher/rancher/issues/26192
=> [release/v2.6] Add conditions for sidecar auditLog.destination in deployment.yaml

chart/scripts/post-delete-hook.sh, chart/templates/post-delete-hook-job.yaml, chart/templates/secret.yaml
https://github.com/rancher/rancher/issues/37060
Content in https://github.com/rancher/rancher/issues/37060#issuecomment-1102157986
=> [release/v2.6] Treat bootstrap-secret as non Helm resource

chart/templates/deployment.yaml, chart/tests/deployment_test.yaml
Backport https://github.com/rancher/rancher/pull/37175
=> [release/v2.5] Add conditions for sidecar auditLog.destination in deployment.yaml

pkg/apis/rke.cattle.io/v1/controlplane.go, pkg/apis/rke.cattle.io/v1/encryptionkeyrotation.go, pkg/apis/rke.cattle.io/v1/etcd.go, pkg/apis/rke.cattle.io/v1/zz_generated_deepcopy.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/provisioningv2/rke2/planner/certificaterotation.go, pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/35436
=> Refactor encryption key rotation

go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum
Updating rke to v1.3.10
Updating UI/Dashboard to v2.6.5-rc5
=> Update rke and UI tags for v2.6.5-rc6

pkg/apis/rke.cattle.io/v1/etcd.go, pkg/provisioningv2/rke2/planner/etcdrestore.go
https://github.com/rancher/rancher/issues/37499
=> add new etcd restore phase to start node

pkg/controllers/management/authprovisioningv2/authprovisioningv2.go, pkg/controllers/management/authprovisioningv2/cluster.go, pkg/controllers/management/authprovisioningv2/crtb.go, pkg/controllers/management/authprovisioningv2/prtb.go, pkg/controllers/management/authprovisioningv2/role.go
Reverts rancher/rancher#37416 due to the issues found in https://github.com/rancher/rancher/issues/36072#issuecomment-1112872889
=> Revert cluster-delete-persist

tests/validation/tests/v3_api/common.py
Logic breaks at cmd_output, because ping command cannot reach to the pod.
So, added a retry ping logic to check again if the pod is reachable.
=> flaky test test_bkp fixes
