rancher/rancher

pkg/controllers/management/etcdbackup/etcdbackup.go
TLDR: Adds a check for backups that are currently running.
If a user sets the backup timeout to 10 minutes due to a slow S3-alike or similar, the backup will still be running during the next tick of the check interval. The cluster backup sync function will see that the last **completed** backup was longer than the backup interval (ignoring the one that's currently running) so it'll start a new backup and bulldoze the running one.
My addition basically checks that if since a backup's creation time is less than the backup config's timeout and "completed" is unknown. Then skip until the next iteration.
#34890
=> Better handling of still running etcd backups

pkg/provisioningv2/rke2/installer/installer.go, pkg/provisioningv2/rke2/installer/installer_test.go
Windows requires a CSI Proxy windows service to be executing on the host for enabling CSI drivers to allocate resources on Windows nodes. We have already added that capability to Wins to support installing and starting the service. The configuration for that service needs to be driven by Rancher. We are currently defaulting this to enabled by default. If we later determine to make this configurable by Rancher, then we just need to update the this code in Rancher and the corresponding unit test to test that behavior.
* https://github.com/rancher/windows/issues/114
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
=> Adding CSI Proxy config to Windows RKE2 Install script.

pkg/controllers/management/k3sbasedupgrade/deployPlans.go, pkg/controllers/managementuserlegacy/helm/common/extra_args_injection.go
Issue: https://github.com/rancher/rancher/issues/32803
Problem:
Images are not pulled from Rancher's global private registry when upgrading the k8s version of RKE2 clusters via Rancher UI, which will fail the upgrade because the cluster's nodes cannot connect to docker.io in the air-gapped environment.
Fixes:
Append the global private registry to the image used in the upgrade plan for RKE2 clusters;
Add 'global.cattle.systemDefaultRegistry:reg' to the default values passed to the app `rancher-rke2-upgrade`
=> fix the issue that global private registry is not used when upgrading imported RKE2 clusters 

pkg/controllers/management/k3sbasedupgrade/deployPlans.go
Issue: https://github.com/rancher/rancher/issues/36000
Problem:
When an upgrade of the k8s version in the imported k3s cluster is triggered, the Plan does not use the system-default-registry as the source for pulling images. As a result, the upgrade job and pod fail in pulling images as they cannot reach docker.io in the air-gapped environment.
Fixes:
Append the global private registry to the image used in the upgrade plan for RKE2 clusters
=> append the global private registry to the image used in the upgrade plan for K3s clusters

pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/machineprovision/template.go, tests/integration/pkg/cluster/clusters.go, tests/integration/pkg/tests/custom/custom_test.go, tests/integration/pkg/tests/machineprovisioning/machine_test.go, tests/integration/pkg/wait/wait.go
When provisioning a machine, if the bootstrap secret is optional and not found,
then the name will be changed. This causes Wrangler Apply to delete the job and
recreate it with the new name, which in turn may cause the job to hang because
the process of create -> delete -> create is too fast for Kubernetes to handle.
Now, the volume and volume mount are only include if the bootstrap secret is
required. This keeps the job from being deleted and recreated when the bootstrap
secret cannot be found.
In addition, this change also adds tests for deleting clusters. Now, after we ensure
a cluster is created successfully, the cluster is deleted and we ensure the cluster
is cleaned up successfully.
Related Issue:
https://github.com/rancher/rancher/issues/35795
=> Leave out bootstrap secret if it is optional

pkg/catalog/manager/manager.go, pkg/catalog/manager/manager_test.go, tests/integration/suite/test_app.py, tests/integration/suite/test_multi_cluster_app.py
Replace `go-version` check with `blang/semver`. 
Elected to use `blang/semver` as opposed to `Masterminds/semver` because the former was already being used in the file, and does handle prerelease correctly (after removing v prefix). Also updated unit tests to include `-0` in min and max versions, as well as add tests for max/min only present.
Related Issue: https://github.com/rancher/rancher/issues/32930
=> Swap go-version for blang/semver in catalog version validation

pkg/controllers/management/etcdbackup/etcdbackup.go
Backport of https://github.com/rancher/rancher/pull/35132
Issue: https://github.com/rancher/rancher/issues/36038
Original PR description:
TLDR: Adds a check for backups that are currently running.
If a user sets the backup timeout to 10 minutes due to a slow S3-alike or similar, the backup will still be running during the next tick of the check interval. The cluster backup sync function will see that the last completed backup was longer than the backup interval (ignoring the one that's currently running) so it'll start a new backup and bulldoze the running one.
My addition basically checks that if since a backup's creation time is less than the backup config's timeout and "completed" is unknown. Then skip until the next iteration.
#34890
=> [Backport v2.5] Better handling of still running etcd backups

main.go, package/entrypoint.sh
Address https://github.com/rancher/rancher/issues/35955
For an upgrade in k3s single node, I updated the etcd migration code to migrate old etcd data to embedded etcd from `/var/lib/rancher/management-state/etcd` to `/var/lib/rancher/k3s/server/db/etcd`, instead of from `/var/lib/rancher/etcd`. The `/var/lib/rancher/etcd` dir gets overwritten if you upgrade a Rancher container that has bind mounted volumes.
Customers were losing downstream clusters on upgrade. Now, if you upgrade single node in Docker all cluster data will be preserved, even if you just update the Rancher version of a container with bind mounted volumes.
=> Update k3s single node etcd migration code

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Related Issue: https://github.com/rancher/rancher/issues/35750
This PR bumps the version of rke to one that includes the fix for clusters reporting as active after an upgrade when removing old addons had failed. Now, a cluster will correctly transition to the `error` state.
=> Bump rke for fix where addon jobs are stuck in removing

pkg/data/management/role_data.go
A user with the "User-Base" global permission and the "Create new Clusters" role could not use rke2 templates, as the role did not have any rules regarding the `catalog.cattle.io.clusterrepos` resource. This PR allows a user with these permissions to `get`, `list`, and `watch` this resource for use when creating a new cluster from an rke2 template.
Also, was no longer able to reproduce https://github.com/rancher/rancher/issues/34844 with this user:
Related Issues: https://github.com/rancher/rancher/issues/35177, https://github.com/rancher/rancher/issues/34844
=> Add rke2 template clusterrepos to create-clusters role

pkg/apis/provisioning.cattle.io/v1/rke.go, pkg/controllers/management/nodepool/nodepool.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, tests/integration/pkg/tests/machineprovisioning/machine_test.go
CAPI (cluster API) drains nodes on deletion by default, although it is possible to force a node not to drain by adding the `ExcludeNodeDrainingAnnotation` annotation (e.g.  `machine.cluster.x-k8s.io/exclude-node-draining: true`). This PR adds that annotation to the `MachineTemplateSpec` in the `MachineDeployment`, which will apply to each machine created. This creates parity with RKE1 "Drain Before Delete", by allowing users the option to apply a drainage policy to each machine pool.
Related Issue: #35274
=> Add rke2 support for drain before delete

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Backport of #36076 
---
Related Issue: https://github.com/rancher/rancher/issues/36037
This PR bumps the version of rke to one that includes the fix for clusters reporting as active after an upgrade when removing old addons had failed. Now, a cluster will correctly transition to the error state.
=> [Backport v2.5] Bump rke for fix where addon jobs are stuck in removing

scripts/create-components-file.sh, scripts/package
This changes the `rancher-components.txt` file (which is used as release description for release candidates) from listing all components to only listing components containing `-rc` as those are the components that need attention before released. This was based done on feedback from Brenda from last release.
=> [release/v2.6] Only show -rc components/images in components file

.drone.yml, Dockerfile-windows-1809.dapper, Dockerfile-windows-2004.dapper, Dockerfile-windows-20H2.dapper
Switch from pointing to the manifest for each Windows dapperfile `rancher/golang:1.14-windowsservercore` to the specific build version image `rancher/golang:1.14-windowsservercore-2004` as the manifest only has the 1809 and 20H2 versions.
Dapper cannot consume build-args when being run directly without a build step, which is how we are currently using it. This caused us to need to make a Dapper file for each Windows build version.
This unblocks 2.5.12 drone issues that keep popping up.
```
docker manifest inspect rancher/golang:1.14-windowsservercore
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 4233,
"digest": …
```
=> [2.5] fix issue with 2004SAC missing from manifest

pkg/catalogv2/content/content.go, pkg/catalogv2/content/content_test.go
The package used to make semver comparisions for catalog v2, e.g. https://github.com/Masterminds/semver, has a known constraint when it comes to working with prerelease versions, as described in https://github.com/Masterminds/semver#working-with-prerelease-versions:
```
SemVer comparisons using constraints without a prerelease comparator will skip prerelease versions. 
```
As a result, if the `catalog.cattle.io/rancher-version` is set to something like `< v2.6.3`, something like `v2.5.9-rcXX` will automatically fail due to the fact that it has a pre-release identifier attached to it (namely `-rcXX`).
Therefore, the fix put forward in this PR first checks to see if the Rancher version is valid for the given constraint; if the output of the validation indicates that it is invalid because …
=> Support checking rancher-version constraints against Rancher prereleases

scripts/create-components-file.sh, scripts/package
Backport of https://github.com/rancher/rancher/pull/36033
Test run:
```
rancher/backup-restore-operator v1.2.1-rc1
rancher/rancher-webhook v0.1.3-rc1
DASHBOARD_UI_VERSION v2.5.12-rc2
RANCHER_WEBHOOK_MIN_VERSION 0.1.300-rc1
UI_VERSION 2.5.12-rc2
```
=> [release/v2.5] Only show -rc components/images in components file

scripts/test
On CI runs, K3s was continuously failing with a `time="2022-01-13T22:57:27.410144766Z" level=fatal msg="starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use"`
or something similar. 
In my debugging of this, I have a theory that the `keepalive` loop monitoring Rancher health is not being terminated and is causing problems. Even on a graceful cleanup of Rancher, the keepalive loop is attempting to start a new Rancher, which is then providing conflicting (and unmanaged) rancher instances. 
This PR changes the method of running Rancher for testing.
=> Run rancher more reliably during testing

scripts/test
Continuation of https://github.com/rancher/rancher/pull/36143
As a continuation of my conquest to fix the flaky testing in Rancher, I discovered that there is a condition in which Rancher can die (concurrent map read write on rancher startup and `panic: indexer conflict: map[byPod:{}]`, I'm looking at you)
When this happens, the K3s processes that are started under the parent Rancher process are NOT cleaned up/killed, and instead, the K3s processes get inherited by PID 1. This is not good, and is why when subsequent attempts to start rancher end up with the `bind address already in use` message.
This PR adds functionality to properly clean up the K3s processes if Rancher fails.
Realistically, this should probably be fixed properly in norman, but for now, this bandaid will have to do to …
=> Kill all child processes that are owned by k3s if Rancher fails

Dockerfile.dapper, package/Dockerfile, scripts/k3s-images.sh
SURE-3522
[GitHub Issue](https://github.com/rancher/rancher/issues/35101)
Currently, the Dockerfiles download K3s as a binary that is a self-extracting archive from the main K3s repo. When a container is run, the binary starts extracting various files it needs at runtime (kubectl, cni and containerd dependencies, for example).
This PR modifies the Dockefiles, so that at build time they download the already extracted binaries from a dedicated K3s image, rather than the archive. The unnecessary extraction is then eliminated.
=> Replace downloaded K3s binary with rancher/k3s Docker image

tests/framework/extensions/cloudcredentials/cloudcredentials.go, tests/framework/extensions/cloudcredentials/harvester/create.go, tests/framework/extensions/cloudcredentials/harvester_config.go, tests/framework/extensions/machinepools/harvester_machine_config.go, tests/v2/validation/provisioning/provisioning_node_driver_test.go
adding harvester node driver and dependencies
New Yaml options:
```
//below are some of the default values used. values with <> should be pulled from your setup
harvesterCredentials:
clusterId: <>
clusterType: "imported"
kubeconfigContent: <>
harvesterMachineConfig:
diskSize: "40"
cpuCount: "2"
memorySize: "8"
networkName: <>
imageName: <>
vmNamespace: "default"
sshUser: "ubuntu"
diskBus: "virtio"
```
this was tested using a harvester setup for 1, 3 node all roles, and 3 node dedicated roles clusters.
=> Go Automation: Harvester provisioning

pkg/rancher/migrations.go
Issue:
https://github.com/rancher/rancher/issues/35489
Original PR:
https://github.com/rancher/rancher/pull/35964
=> Only migrate CAPI CRDs if EmbeddedClusterAPI is enabled

tests/validation/lib/aws.py
Rebuilt the Ubuntu 18.04 image to fix the tests execution as the AMI used was pointing to other AMI without pre-installed Docker.
=> Automation - rebuilt ubuntu-18.04 for validation tests

pkg/controllers/management/etcdbackup/etcdbackup.go
If etcd is particularly saturated and a snapshot cannot be completed within the timeout, starting a recurring timeout while a snapshot is currently underway will cause the two snapshots to fight for the `etcd-snapshot-once` container. This PR defers creating the recurring snapshot until the user snapshot finishes (in addition to existing recurring snapshots). This PR also fixes an instance where a user can create a snapshot before the initial recurring one.
=> Prevent recurring backups from running if backup is in progress

tests/validation/Dockerfile.v3api
The curl version in `python:3.7.0` started to have issues with the `test_certificates` test suite.
The image `python:3.7.12` has a newer `curl` version that worked fine locally while running these tests.
=> Automation - Bumping the upstream Dockerimage version to python:3.7.12 for validation tests

pkg/provisioningv2/rke2/planner/planner.go
#35999 
When pre-drain hooks are configured rancher will ignore any concurrency limits set on node upgrade.  
The planner was considering machines with stale plans to be unavailable and triggering a drain on them.  The node hooks cause the machine drain controller to send more updates than it would on machine without.  I think this was causing the events to be pushed to the controller with stale plans causing the nodes to be drained even when the concurrency limit had been reached.   Instead the planner checks if the node is explicitly being drained before updating it.   I don't think this problem was unique to clusters with pre drain hooks but I think the hooks caused enough churn to cause this issue reliably. 
- single node cluster
- 3 controlplane
- 5 controlplane
- 3 worker
For all …
=> fixed concurrency limit being ignored on upgrade

package/Dockerfile, pkg/controllers/management/authprovisioningv2/authprovisioningv2.go, pkg/controllers/management/authprovisioningv2/machineconfigs.go, pkg/controllers/management/nodetemplate/nodetemplate.go, pkg/controllers/management/rbac/rbac.go, pkg/controllers/management/wrangler.go
Currently, if a standard user creates a rke-machine-config, they won't have
access to modify it until it is associated to a provisioning cluster that
the user owns. This creates issues in the UI when using the "Edit as YAML"
during cluster creation.
Now, roles and rolebindings will be added for rke-machine-configs when they are
created. This also requires changes to rancher-webhook (to add the creatorID).
Issue:
https://github.com/rancher/rancher/issues/35868
=> Add roles and rolebindings when creating rke-machine-configs

pkg/controllers/management/auth/project_cluster_handler.go
If a cluster gets deleted, then we don't want to create namespaces and projects
for the cluster. Now, the sync handler will ignore deleting clusters to ensure
this won't happen.
Issue:
https://github.com/rancher/rancher/issues/31546
=> Ignore deleting clusters in project_cluster_handler

main.go, package/entrypoint.sh
Address #35955
For an upgrade in k3s single node, I updated the etcd migration code to migrate old etcd data to embedded etcd from /var/lib/rancher/management-state/etcd to /var/lib/rancher/k3s/server/db/etcd, instead of from /var/lib/rancher/etcd. The /var/lib/rancher/etcd dir gets overwritten if you upgrade a Rancher container that has bind mounted volumes.
Customers were losing downstream clusters on upgrade. Now, if you upgrade single node in Docker all cluster data will be preserved, even if you just update the Rancher version of a container with bind mounted volumes.
=> [Backport v2.6.3-patch1] Embedded etcd migration fix

pkg/apis/provisioning.cattle.io/v1/rke.go, pkg/apis/provisioning.cattle.io/v1/zz_generated_deepcopy.go, pkg/apis/rke.cattle.io/v1/controlplane.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/controllers/provisioningv2/rke2/rkecluster/controller.go, pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go, pkg/provisioningv2/capi/capi.go
#35275 
Using CAPI machine health checks we can replace the machine associated with an unready node after a given period of time.  CAPI health checks require all other components in  a cluster to  have  a ready condition to replace nodes.  Once the cluster's infrastructure is ready, the control plane is initialized and the machine is ready the machine health check controller will start checking the related node's conditions on the interval defined by the node pool's `UnhealthyNodeTimeout`.   If the node  goes unhealthy before the `nodeStartupTimeout` it will be marked as unhealthy but not replaced.  This is also the case if the number of nodes in a pool that are unhealthy exceeds the `MaxUnhealthy` or is not in the `UnhealthyRange`.  If all these conditions are not true the machine will …
=> self-healing machine pools for rke2

tests/integration/requirements.txt
Deprecation warnings are showing up due to version of flask
```
/go/src/github.com/rancher/rancher/tests/integration/.tox/rancher/lib/python3.8/site-packages/flask/json/__init__.py:31
/go/src/github.com/rancher/rancher/tests/integration/.tox/rancher/lib/python3.8/site-packages/flask/json/__init__.py:31: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
_slash_escape = "\\/" not in _json.dumps("/")
```
Update version of flask from 1.1.1 to 2.0.2
=> Update version of flask

pkg/controllers/management/node/cleanup.go
If the cleanup job timed out (like if the VM was deleted), then the node
will still exist in the cluster but it will have a Not Ready status.
Therefore, the cleanup job will get created to tolerate this status, but
the pod will never be scheduled because the VM was deleted.
After this change, if the cleanup job times out, then it will be
deleted.
Issue:
https://github.com/rancher/rancher/issues/35334
=> Don't try to cleanup node if it does not exist

scripts/create-components-file.sh
- Some images were shown twice as a result of being in linux and windows images
- Removed `MIN_VERSION` as those are not components but a version limitation for components
=> [release/v2.6] Only show unique images in components file

tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/providers.go, tests/v2/validation/provisioning/provisioning_node_driver_test.go
additional config in go:
```
provisioningInput:
providers: ["aws", "harvester", "do", ...]
```
this will be a required field in the config file. Tests will provision for each provider listed. Currently supported are aws, do, and harvester.
=> refactoring provisioning v1 tests to simplify future node drivers/providers

pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, tests/integration/pkg/cluster/clusters.go, tests/integration/pkg/tests/machineprovisioning/machine_test.go
CAPI identifies which templates certain objects are cloned from. For example,
CAPI will identify that an infrastructure machine is cloned from a specific
machine template.
This change will do the same for machine templates: it will identify which
machine config a machine template is cloned from.
Issue:
https://github.com/rancher/rancher/issues/35452
=> Put cloned-from annotations on machine templates

package/Dockerfile, package/jailer.sh, pkg/controllers/management/node/utils.go
issue: https://github.com/rancher/rancher/issues/28411
add the support for provisioning cluster behind a proxy by letting rancher-machine use external ssh binary and adding dependencies to both Rancher image and the Jail directory
another part of the fix goes into rancher/machine: https://github.com/rancher/machine/pull/159
=> fix ssh behind proxy 

package/Dockerfile
=> Bump UI, webhook to final release for 2.6.3-patch1

pkg/catalogv2/content/content.go, pkg/catalogv2/content/content_test.go
Forward ports https://github.com/rancher/rancher/pull/36124.
Related Issue: https://github.com/rancher/rancher/issues/36120
(cherry picked from commit 638b14ccac39caace9887c23177ffbf18ad66d80)
=> [2.6] Support checking rancher-version constraints against Rancher prereleases

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, tests/integration/pkg/cluster/clusters.go, tests/integration/pkg/tests/machineprovisioning/machine_test.go
By default, the CAPI controllers will delete a random machine when a machine
deployment is scaled down. This is different from the RKE1 implementation, which
deletes the oldest machine first.
After this change, a deletion policy will be added to the machine deployments
with a deletion policy to delete the oldest machine on scale down.
Issue:
https://github.com/rancher/rancher/issues/35753
=> Delete oldest machines on scale down

pkg/image/export/main.go, scripts/create-components-file.sh
This will:
- Create `rancher-rke-k8s-versions.txt` with RKE Kubernetes versions included in the (pre) release
- Add the content of this file to `rancher-components.txt` which is used for pre-release release notes
Example on current code:
```
v1.19.16-rancher1-3                                                                                                                                                                                                                                                                                                           
v1.20.14-rancher2-1 …
```
=> [release/v2.6] add k8s versions txt file

tests/framework/clients/dynamic/dynamic.go, tests/framework/clients/rancher/client.go, tests/framework/extensions/namespaces/namespaces.go, tests/framework/pkg/session/session.go
**Framework updates**
- Dynamic client not takes a testing.T object to log the host of the dynamic client.
- Removed GenerateKubeconfig from GetDownStreamClusterClient, and instead just updated the host.
=> Updated dynamic client

.drone.yml
In case the release already exist (when the tag/release is created using the UI for example), Drone won't update it unless `overwrite: true` is specified. As we use release notes to show `-rc` components and included RKE k8s versions, we want this information in the pre release notes.
=> [release/v2.6] Overwrite prerelease title and note on tag

tests/validation/requirements.txt, tests/validation/tests/rke/common.py
**Adding this fix for rke_support_matrix job**
**Issue:**
- The etcdctl health check command `ETCDCTL_API=2 etcdctl --endpoints "https://127.0.0.1:2379"  --ca-file /etc/kubernetes/ssl/kube-ca.pem --cert-file  $ETCDCTL_CERT --key-file  $ETCDCTL_KEY cluster-health` fails for k8s 1.22 clusters. Because of which rke_support_matrix jenkins job also fails.
Hence updated the command (to use etcdctl v3) for k8s 1.22 clusters : `ETCDCTL_API=3 etcdctl endpoint health --cluster` and based on it's output changed the assert conditions as well.
- Verified the changes locally using these [steps](https://github.com/rancher/rancher/tree/release/v2.6/tests/validation/tests/rke) and the test case `pytest -k "test_install_config_1"` got passed. **Used RKE v1.3.4-rc1**
- **Note:** For k8s version 1.21 and …
=> Update health check command as per etcdctl v3 API

pkg/controllers/management/etcdbackup/etcdbackup.go
Issue: #36209 
Etcd backups should not run concurrently, as rke/rke-tools expects to use the same container (`etcd-snapshot-once`) for snapshots, and multiple concurrent backups will cause thrashing for these resources. Backups (both manual and recurring) are now queued, and will be popped on cluster sync (5 minute interval), or on creation. Recurring snapshots will not be queued if another recurring snapshot is running or in queue.
=> 36209 etcd backup thrashing

pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
Draining etcd nodes causes issues in RKE2, where some pods are unhealthy. This PR never drains etcd nodes, which is the current approach in RKE1.
Related Issue: #35274
=> Don't drain etcd nodes

pkg/controllers/managementuser/resourcequota/resource_quota_common.go
https://github.com/rancher/rancher/issues/18877
This allows container default limits defined in a project to be propagated to new namespaces (which don't override them) even if the project does not have resource quotas defined.
This is a quick solution that works, however, I have noticed two things in my tests, but they are insignificant.
1. Sometimes the propagated limits are duplicated on the namespace. This does not affect anything, just looks strange.
2. Having created a new namespace with propagated container default limits, one can see that they are missing in the UI. This could be a UI issue from before.
=> Allow container default limits propagation in absence of project resource quotas

pkg/data/management/podsecuritypolicytemplate_data.go
Add `restricted-noroot` PSP policy to match upstream Kubernetes `restricted` PSP.
Fix https://github.com/rancher/rancher/issues/35191
=> Add restricted-noroot PSP policy to match upstream Kubernetes restricted PSP

tests/framework/clients/rancher/client.go, tests/framework/extensions/kubeconfig/contexts.go, tests/framework/extensions/kubeconfig/kubeconfig.go
**Framework updates**
Implemented helper to retrieve the kubeconfig from a cluster.
Implemented helper to get the contexts from the kubeconfig of a cluster
Implemented elper to switch the context, that instantiates a dynamic client with an updated current-context.
=> Implemented kubeconfig helpers.

pkg/controllers/management/node/cleanup.go
A customer is hitting an issue where nodes deleted from Cluster Explorer don't get their cleanup jobs run on them so the jobs-pods just get stuck in pending. The nodes seem to be removed from the cluster before the Job is created so the node scheduling never resolves. I've noticed that the Job gets deleted, but the pod does not.
The problem for them is that they re-add nodes with the same name as part of their patching procedure. So when they do the pod gets scheduled to that node and cleaned. This PR adds a step to clean the nodes belonging to the Job after the fact.
Issue:
https://github.com/rancher/rancher/issues/35334
=> Ensure node-cleanup pods are deleted

go.mod
```
% go mod why -m github.com/apache/thrift  
(main module does not need module github.com/apache/thrift)
```
The remaining Thrift in [`go.sum`](https://github.com/macedogm/rancher/blob/108719c435c029f5f719c37bd39126a7729b4f47/go.sum#L179) is imported through another dependency, but not shipped:
```
go.opencensus.io@v0.20.1 github.com/apache/thrift@v0.12.0
```
=> Remove unused Thrift direct dependency

tests/validation/tests/v3_api/common.py
Jenkins tested. 
Currently, automation special-cases rke2 control plane, but it is no longer the case that CP is schedulable by default. Reverting the code, and looking only for the `NoExecute` and `NoSchedule` taints instead of looking at node roles for schedulability.
=> removing rke2 specific test for getting schedulable nodes

pkg/catalogv2/git/download.go, pkg/controllers/dashboard/helm/repo.go
SURE-3618
Issue: https://github.com/rancher/rancher/issues/31676
Technically, the conversion to PEM is not required since you could encode the contents of a ca.pem file with the header, footer, and line breaks into base64, pass it in as `caBundle` and it will be accepted (git based requires header, footer and line breaks). However, this approach doing the conversion makes setting up git-based repos with a CA bundle match the HTTP-based repo setup from a user standpoint (see [here](https://rancher.com/docs/rancher/v2.6/en/helm-charts/#repositories)). It also allows for re-using the logic to load the chart's icons without any further modifications.
=> [release/v2.6] Add support in cluster git repos for custom/self-signed certs

tests/validation/tests/v3_api/resource/terraform/rke2/master/instances_server.tf, tests/validation/tests/v3_api/test_create_ha.py, tests/validation/tests/v3_api/test_import_rke2_cluster.py
Few changes made here:
- Remove unnecessary `-route53` addition to name of route53 resource on rke2 clusters that create LB
- Remove unnecessary environment variable `RANCHER_K3S_VERSION` from `test_create_ha.py`
- Add RKE2 as a valid local cluster type
- Fix a check that was only valid for RKE1
- Provide a one-click URL at the end of the test output to open the rancher UI that this creates
- Only run terraform for worker node for rke2 clusters when the count is greater than 0 (k3s already does this correctly)
=> Update HA local cluster deployment test to include RKE2 #36426 

pkg/controllers/managementuser/resourcequota/resource_quota_sync.go
https://github.com/rancher/rancher/issues/27750
To enable the propagation of container default limits from a project to its new namespaces made via `kubectl` directly, we must explicitly set project limits (if defined), if the namespace itself does not provide its own (override) values.
=> Pass container limits from project in a new namespace if it does not override them

tests/framework/clients/rancher/client.go, tests/v2/integration/project_user_test.go
Previously, the `AsUser` function was using the token client to create a new token for the specified ID, however rancher will create a derived token based on the bearer token, and disregard the token in the request. The framework has been updated to use the login action for parity the python framework.
=> Fix bug where tokens were always being created for the admin user

pkg/api/norman/customization/cred/store.go, pkg/api/norman/server/managementstored/setup.go
Currently, it is possible to delete a cloud credential if it is referenced by a
provisioning cluster. This causes issues if a user wants to add or delete nodes
after the cloud credential is gone.
After this change, Rancher will prevent a user from deleting a cloud credential
if it is referenced by a provisioning cluster.
Issue:
https://github.com/rancher/rancher/issues/36294
=> Disallow deleting cloud credential referenced by provisioning cluster

pkg/controllers/management/restrictedadminrbac/fleet.go
Changing the rbac fleet handler to properly parse the subject
from the grb rather than assuming a user subject
=> [Backport] Fixing rbac fleet handler to handle group subjects

pkg/metrics/metrics.go, pkg/metrics/node.go
This PR implements two new prometheus gauge metrics: `cluster_manager_nodes` and `cluster_manager_node_cores`. Both metrics are labeled by `cluster_id` and `provider`.
For example, with a one node management cluster w/ 4 cores, a 3 node downstream RKE cluster w/ 2 cores per node, and a 1 node downstream RKE2 cluster w/ 2 cores, we should see something like this reported in the Rancher `/metrics` endpoint:
```
cluster_manager_node_cores{cluster_id="c-6zt8w",provider="rke"} 6
cluster_manager_node_cores{cluster_id="c-m-w5mpglzf",provider="rke2"} 2
cluster_manager_node_cores{cluster_id="local",provider="k3s"} 4
cluster_manager_nodes{cluster_id="c-6zt8w",provider="rke"} 3
cluster_manager_nodes{cluster_id="c-m-w5mpglzf",provider="rke2"} 1
cluster_manager_nodes{cluster_id="local",provider="k3s"} …
```
=> Node and Node Core Metrics

pkg/controllers/management/drivers/dynamic_driver.go, pkg/kontainer-engine/service/service.go
When enabling node and kontainer-engine drivers, Rancher wasn't waiting for the
command which caused zombie processes in the rancher pod.
After this change, Rancher will wait for these processes and will not cause
zombie processes to appear.
Issue:
https://github.com/rancher/rancher/issues/25443
=> Wait for commands spawned by Rancher

package/Dockerfile
For issue https://github.com/rancher/rancher/issues/36552
Add wins install script to Rancher during packaging CI steps to ensure that airgap setups can support rke2 windows cluster provisioning
=> add wins install script for rancher airgap

package/Dockerfile, pkg/controllers/management/drivers/dynamic_driver.go, pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/provisioningv2/rke2/installer/installer.go
The harvester node driver is bundled in Rancher in order to provide support for
air-gapped installs of Rancher to provision Harvester clusters. However, the
download URL passed to the create job was still the external URL. This wouldn't
allow Harvester clusters to be created in air-gapped environments.
After this change, any enabled node driver will be copied to the appropriate
location so that the create job can download it directly from Rancher.
Issue:
https://github.com/rancher/rancher/issues/36488
=> Allow node driver download in air-gapped environments

pkg/data/management/role_data.go
Changing default permissions for cluster members to include
permission to read node/nodemetrics in the metrics.k8s.io group
=> Adding node metrics view capability to cluster members

package/jailer.sh
Issue: https://github.com/rancher/rancher/issues/36469
rancher-tiller wasn't properly being copied into the jail because of a typo. This made install legacy apps (like rancher-k3s-upgrader) impossible because rancher-tiller is required.
Fix the typo
1. Upgraded local K3S cluster
2. Upgraded imported K3S cluster
3. Upgraded imported RKE2 cluster
=> Fix typo in rancher-tiller in jailer script

pkg/provisioningv2/rke2/planner/store.go
https://github.com/rancher/rancher/issues/36562
Per the issue linked, what appears to have been happening is:
a new etcd-only init node is elected, but originally did not have a periodic instruction for scraping the joinURL set -- the planner then attempts to load the join URL but errors out before it ever has the opportunity to set the plan to a version with the periodic instruction to scrape the join URL.
=> [release/v2.6] Don't error if periodic instruction output is not found

pkg/apis/provisioning.cattle.io/v1/rke.go, pkg/apis/provisioning.cattle.io/v1/zz_generated_deepcopy.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
#35275
rancher returns an error when parsing the max unhealthy in node pools because int's are parsed as strings.
accept maxUnhealthy as a string and parse into to string inside rancher.
=> fix health check serialization

tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf
PR to avoid creation of db parameter group when etcd is used. 
db parameter group should be created only when externaldb is used as backend
Signed-off-by: Shylaja Devadiga <shylaja.devadiga@suse.com>
=> fix create_db parameter resource

tests/framework/clients/ec2/client.go, tests/framework/clients/ec2/config.go, tests/framework/clients/rancher/client.go, tests/framework/extensions/nodes/ec2/ec2.go, tests/framework/extensions/tokenregistration/tokenregistration.go, tests/framework/pkg/nodes/nodes.go, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/custom_cluster_test.go, tests/v2/validation/provisioning/nodeproviders.go, tests/v2/validation/provisioning/provisioning_node_driver_test.go
**Framework updates:**
- EC2 client for the aforementioned creation/deletion of nodes.
- EC2 extension for creating and deleting nodes
- Node library to be used by any provider. Including reading from a config for an already existing external node setup.
- Cluster token registration extension to facilitate getting the registration token
**Validation Tests:**
- Custom cluster tests that are not just dependent ec2 node provider.
- Helpers in the v2/validation/provisioning directory to setup the different kind of node providers. Currently only support EC2 and already existing node configuration information in the config file.
=> Ec2 node library and custom cluster tests

pkg/metrics/node.go
Because the `setMetrics` method accepts the absolute state of what should be reported to the `cluster_manager_nodes, cluster_manager_node_cores` metrics, there could be leftover gauge values from previous calls to `setMetrics`. For this reason we need to first reset the metrics before setting them. 
Issue: 
- https://github.com/rancher/rancher/issues/36410
=> Prometheus node metrics gauge value fix

pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/machineprovision/template.go
There is a possible race that could cause the jobComplete field to be false
(indicating that the creation job has not finished successfully), but the
providerID field set (indicating that the machine is running and has been
bootstrapped). These are contradictory states.
This change will re-enqueue the job if the infrastructure machine gets into this
state, which will set the jobComplete field and re-enqueue the infrastructure
machine to be processed again.
In addition, it is possible for the `GetJobName` to return a different
value every time if the infrastructure machine name is too long. This
change mitigates that by using labels to get the job.
Issue: https://github.com/rancher/rancher/issues/36547
=> Re-enqueue infra machine if provider ID set with jobComplete false

pkg/auth/requests/token_review.go, pkg/multiclustermanager/routes.go
**Problem:**
A service monitor pointing at rancher doesn't work with mounted service account token. This means a user needs to create an api token, then created a secret containing it.  Supporting the SA token will remove that process and also ensure that the used tokens expired since a rancher api token by default does not. Currently the API layer does not appear to support JWT tokens at all.
**Solution:**
Use a token review to auth tokens that have errored for /metrics path.
**Issue:**
https://github.com/rancher/rancher/issues/36234
=> Add sa token support for /metrics

pkg/controllers/management/secretmigrator/assemblers.go
Prevent a nil dereference panic if the RKE config has BackupConfig set
but S3BackupConfig unset.
https://github.com/rancher/rancher/issues/36588
=> Fix nil dereference error for S3 credentials

pkg/controllers/management/secretmigrator/assemblers.go
Prevent a nil dereference panic if the RKE config has BackupConfig set
but S3BackupConfig unset.
Backport of https://github.com/rancher/rancher/pull/36617
Issue https://github.com/rancher/rancher/issues/36619
=> [2.5] Fix nil dereference error for S3 credentials

pkg/controllers/management/secretmigrator/assemblers.go
Prevent a nil dereference panic if the RKE config has BackupConfig set
but S3BackupConfig unset.
Backport of https://github.com/rancher/rancher/pull/36617
Issue https://github.com/rancher/rancher/issues/36620
=> [2.4] Fix nil dereference error for S3 credentials

tests/framework/clients/k3d/k3d.go, tests/framework/extensions/clusters/import.go
- Updated `CreateK3DCluster` to use the updated flags for the newest version of k3d. `"no-hostip"` and `"k3s-server-arg"` are no longer supported. Also `"no-image-volume"` was also causing errors.
- Updated `ImportCluster` to use the `provisioning.cattle.io/v1` api to remove confusion from future users that would need to use two different apis for cluster creating and monitoring. Also updated so the container running the `kubectl apply -f` command uses the insecure command instead.
- Updated CreateAndImportK3DCluster to use the` provisioning.cattle.io/v1` api to monitor and import a cluster.
=> Updates to CreateK3DCluster, CreateAndImportK3DCluster, and ImportCluster

pkg/provisioningv2/rke2/planner/store.go
Currently, plans are synced twice in a typical v2prov machine provisioning cycle; once during the initNode process and later when setting the machineJoinURL. 
This change adds an additional plan sync earlier on. One situation this should address is when a plan has been generated for a machine but the machine does not have the UID label assigned to it yet. This appears to cause provisioning of a v2prov machine to become infinitely stuck as it specifically fails during this [check](https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go#L98-L105) with no way to recover due to the label from the plan not being synced until after the providerID would be set.
```console
2022/02/23 21:44:21 [DEBUG] Searching for providerID for …
```
=> add extra plan sync prior to setting the machineJoinURL

pkg/clusterrouter/proxy/proxy_server.go, pkg/controllers/managementuser/rbac/crtb_handler.go, pkg/controllers/managementuser/rbac/impersonation_handler.go, pkg/controllers/managementuser/rbac/prtb_handler.go, pkg/impersonation/impersonation.go, pkg/impersonation/impersonation_test.go
When CRTBs and PRTBs are created, they are either created for Users or
Groups, not both. Impersonation only needs to be set up for a user, and
the impersonation account must be able to impersonate the groups that
are found in the user's attributes. This change ensures that we don't
try to create an impersonation account for a group and removes unneeded
code for when an account is being created for a user.
https://github.com/rancher/rancher/issues/36054
=> Fix group handling for impersonation

pkg/controllers/management/restrictedadminrbac/cluster.go, pkg/controllers/management/restrictedadminrbac/project.go, pkg/controllers/managementuser/rbac/cluster_handler.go, pkg/controllers/managementuser/rbac/globalrole_handler.go
Fixing several areas where the subject of rolebindings was assumed
to be a user so that they can properly handle group roles, both in
the subject and in the naming of the role
=> Fixing bugs related to group bindings to admin/restricted admin

pkg/tunnelserver/chain.go
While debugging failed requests, it helps to add the forwarded address so you can directly see what the origin of the request is.
In trace, we can dump the whole request to debug what the client is sending to use it to compare with what we are seeing.
=> [release/v2.6] Add more logging on failed tunnel requests

pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go
Issue: https://github.com/rancher/rancher/issues/36062
When Rancher is migrated, a new service-account token is created for
system-agent. However, this new service-account was not being deployed to the
downstream nodes because SUC wouldn't detect that the change occurred.
After this change, SUC will be told to watch spec.upgrade.envFrom for changes
and deploy a new plan when this field changes. This field is the correct one for
SUC to watch because the secret name contains a hash of the service-account
token that needs to be updated.
I deployed a cluster with multiple nodes and took a backup with the backup-restore operator. Then, I migrated to a new cluster, restored the backup with backup-restore operator, and installed Rancher. The system-agent got the new service-account token and …
=> Add spec.upgrade.envFrom to SUC upgrade watch

pkg/controllers/management/etcdbackup/etcdbackup.go
Forwardport of https://github.com/rancher/rancher/pull/35132, https://github.com/rancher/rancher/pull/36202 and https://github.com/rancher/rancher/pull/36251.
Note: These are 3 distinct commits, because they were made in 3 distinct commits across `release/v2.6`. 
https://github.com/rancher/rancher/issues/36644
=> [Forwardport v2.6.3-patch2] Better s3 etcd backups

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_bkp_restore_local.py
After some testing locally I had to reload the cluster state before triggering an etcdBackup.
This was consistently failing in Jenkins
=> Automation - fix test of  etcd backup create for RKE1 clusters

pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go
The API version of CustomMachines is different from all other machines used by
Rancher. This change ensures we properly detect Custom machines and delete them
properly.
Issue:
https://github.com/rancher/rancher/issues/36704
=> Delete RKE2 custom cluster machines

tests/integration/requirements.txt
itsdangerous 2.1.0 removed its json module, so pin it to the last known
working version 2.0.1.
=> Pin itsdangerous integration test dependency

pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/provisioningv2/rke2/planner/planner.go
Issue: https://github.com/rancher/rancher/issues/36505
Currently, when upgrading an RKE2 cluster, the planner will go onto the next
machine type before the upgrade finishes. For example, the planner will move
onto upgrade worker nodes before the control plane nodes are completely
upgraded. That is because the plan was considered in-sync after the system-agent
applied it and not after the upgrade completed.
Now, a plan will remain in-sync at the point the system-agent has applied it,
but the machine will not be considered to be in-sync until the version of the
node has been updated.
Because of this change, we must include the CAPI machines as "related resources"
so that the planner runs when the node version has been updated. This should
speed up provisioning slightly because the planner …
=> Wait for version upgrades before proceeding with more upgrades

pkg/clustermanager/manager.go, pkg/controllers/managementuser/controllers.go, pkg/controllers/managementuserlegacy/controllers.go, pkg/controllers/managementuserlegacy/helm/controller.go
Without this patch, the secret assembler for Catalogs was trying to use
the secret lister from the UserContext which is not populated with
secrets from the management cluster. This was causing apps to not be
able to find the secret when deployed on downstream, non-local clusters.
This change passes the ScaledContext down to the helm controller so that
the secretmigrator assembler can use the correct secret lister.
https://github.com/rancher/rancher/issues/36723
=> Use management context for catalog secrets

pkg/clustermanager/manager.go, pkg/controllers/managementuser/controllers.go, pkg/controllers/managementuser/helm/controller.go
Without this patch, the secret assembler for Catalogs was trying to use
the secret lister from the UserContext which is not populated with
secrets from the management cluster. This was causing apps to not be
able to find the secret when deployed on downstream, non-local clusters.
This change passes the ScaledContext down to the helm controller so that
the secretmigrator assembler can use the correct secret lister.
Backport https://github.com/rancher/rancher/pull/36745
=> [2.5] Use management context for catalog secrets

pkg/clustermanager/manager.go, pkg/controllers/user/controllers.go, pkg/controllers/user/helm/controller.go
Without this patch, the secret assembler for Catalogs was trying to use
the secret lister from the UserContext which is not populated with
secrets from the management cluster. This was causing apps to not be
able to find the secret when deployed on downstream, non-local clusters.
This change passes the ScaledContext down to the helm controller so that
the secretmigrator assembler can use the correct secret lister.
Backport https://github.com/rancher/rancher/pull/36745
=> [2.4] Use management context for catalog secrets

pkg/controllers/management/clusterprovisioner/driver.go, pkg/controllers/management/etcdbackup/etcdbackup.go, pkg/controllers/management/secretmigrator/assemblers.go, pkg/controllers/management/secretmigrator/catalog/assemblers.go, pkg/controllers/management/secretmigrator/clusters.go
An early draft of the secretmigrator controller used resource-specific
keys when creating the secrets, and when that was refactored the
assemblers were never updated, so for example the S3 secret assembler
was looking for a key 'secretKey' in the secret data, when it was
actually stored under the 'credential' key.
This also fixes the etcdbackup controller to use the assembled
BackupConfig, instead of the BackupConfig from the newly fetched Cluster
which does not have the credential on it.
https://github.com/rancher/rancher/issues/36660
=> Fix secretmigrator assemblers and s3 snapshots

pkg/controllers/provisioningv2/cluster/remove.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go
When deleting a cluster, the controller was deleting the control plane object
first before deleting the CAPI cluster. That led to nodes being drained when a
cluster was being deleted, which is not correct.
This change deletes the CAPI cluster so that draining does not occur on deletion
=> Delete CAPI cluster first

pkg/controllers/management/clusterprovisioner/driver.go, pkg/controllers/management/etcdbackup/etcdbackup.go, pkg/controllers/management/secretmigrator/assemblers.go, pkg/controllers/management/secretmigrator/catalog/assemblers.go, pkg/controllers/management/secretmigrator/clusters.go
An early draft of the secretmigrator controller used resource-specific
keys when creating the secrets, and when that was refactored the
assemblers were never updated, so for example the S3 secret assembler
was looking for a key 'secretKey' in the secret data, when it was
actually stored under the 'credential' key.
This also fixes the etcdbackup controller to use the assembled
BackupConfig, instead of the BackupConfig from the newly fetched Cluster
which does not have the credential on it.
Backport https://github.com/rancher/rancher/pull/36672
=> [2.5] Fix secretmigrator assemblers and s3 snapshots

pkg/controllers/management/clusterprovisioner/driver.go, pkg/controllers/management/etcdbackup/etcdbackup.go, pkg/controllers/management/secretmigrator/assemblers.go, pkg/controllers/management/secretmigrator/catalog/assemblers.go, pkg/controllers/management/secretmigrator/clusters.go
An early draft of the secretmigrator controller used resource-specific
keys when creating the secrets, and when that was refactored the
assemblers were never updated, so for example the S3 secret assembler
was looking for a key 'secretKey' in the secret data, when it was
actually stored under the 'credential' key.
This also fixes the etcdbackup controller to use the assembled
BackupConfig, instead of the BackupConfig from the newly fetched Cluster
which does not have the credential on it.
Backport https://github.com/rancher/rancher/pull/36672
=> [2.4] Fix secretmigrator assemblers and s3 snapshots

pkg/api/norman/customization/project/project_store.go, pkg/api/norman/store/namespace/store.go, pkg/controllers/managementuser/resourcequota/resource_quota_sync.go, pkg/resourcequota/quota_validate.go
Issue: https://github.com/rancher/rancher/issues/35647
For scenarios where namespaces are created with kubectl:
- If requested quota fits the project, then it is granted and associated with the namespace.
- If requested quota does not fit, then zero quota only for overfilled resources is granted.
It should not matter whether requested quota comes from project defaults or annotation.
The goal is to fix the current behavior where namespaces created with kubectl would receive an all-restrictive resource quota, if the namespace does not fit the project with any resource.
With this change, we will never create the all-restrictive quota (zeros for all resources).
Also, the current behavior with Rancher granting the `min(available, requested)` of a resource is unchanged for requests made with …
=> Create zero quota only for overused resources

Dockerfile.dapper, package/Dockerfile
s390x build is failing because it tries to copy k3s, which is not available on s390x yet.
To fix this error we create a blank k3s file in the k3s-builder used just by s390x.
=> Fix s390x build

pkg/controllers/dashboard/clusterregistrationtoken/agentvars.go, pkg/controllers/dashboard/clusterregistrationtoken/agentvars_test.go, pkg/controllers/dashboard/clusterregistrationtoken/status.go
This adds the envvars before the cURL command since proxy ENVVARS needs to be consumed by the cURL command. In addition this adds the ability to handle Linux, Docker, and PowerShell environment variables.
* https://github.com/rancher/rancher/issues/36732
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
=> Improving envvar handling for custom cluster registration command.

tests/framework/extensions/cloudcredentials/aws/create.go, tests/framework/extensions/cloudcredentials/azure/create.go, tests/framework/extensions/cloudcredentials/azure_config.go, tests/framework/extensions/cloudcredentials/cloudcredentials.go, tests/framework/extensions/cloudcredentials/digitalocean/create.go, tests/framework/extensions/cloudcredentials/harvester/create.go, tests/framework/extensions/machinepools/azure_machine_config.go, tests/v2/validation/provisioning/custom_cluster_test.go, tests/v2/validation/provisioning/providers.go, tests/v2/validation/provisioning/provisioning_node_driver_test.go
**Framework updates** 
- Helper for creating a cloud credential for azure 
- Helper for creating a machine config for an azure provider.
- Updates to spelling mistakes in comments in the other cloud credential helpers
**Validation updates**
- Added azure to providers
- Updates to method names to adhere to go lang naming conventions
=> Added support to provisioning rke2 azure node driver clusters

pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/provisioningv2/rke2/planner/initnode.go, pkg/provisioningv2/rke2/planner/planner.go
It appears that the planner was always receiving an ErrSkip when electing/designating init nodes, due to a change in behavior where we started to not validate that the label didn't exist before deleting it. This is an attempt to fix this issue, which should unblock the planner and allow forward progress.
https://github.com/rancher/rancher/issues/36794
https://github.com/rancher/rancher/issues/36694
https://github.com/rancher/rancher/issues/36773
=> Check for initnode mark existence before blindly returning ErrSkip

tests/validation/lib/aws.py
Just moving to `gp3` volume type by default in our automation for EC2 instances.
Reference: https://aws.amazon.com/ebs/general-purpose/
=> [Automation] - use gp3 as default volume type for ec2 instances

package/Dockerfile, package/jailer.sh
Fix a bug in 2.6-head where rke1 nodes cannot be provisioned due to the jailer for the cluster missing the `mkisofs` binary. This PR adds mkisofs to the rancher image and creates a hard link into the jail.
=> add mkisofs to rancher image and jailer.sh

pkg/api/norman/customization/aks/listers.go
Issue: https://github.com/rancher/rancher/issues/36690 
We never check whether `kubernetesVersion` is set in the `aksConfig` and if it's nil, the `aksUpgrades` endpoint was failing to return a list of valid Kubernetes upgrade versions.
I added a check to make sure if `kubernetesVersion` isn't set, use the current version set in `aksStatus`.
* Create an AKS cluster in Azure portal
* Import the AKS cluster using the Rancher UI
* Go to Cluster Management -> Edit Config for your imported cluster and check that you can edit the configuration and then save it, and the cluster updates
=> Add kubernetes version check to aksUpgrades endpoint

pkg/controllers/provisioningv2/rke2/bootstrap/controller_test.go, pkg/provisioningv2/rke2/installer/installer.go, pkg/provisioningv2/rke2/installer/installer_test.go
This fixes a formatting issue that causes machine provisioning of windows VMs using cloudbase-init to break
current (broken): `$env:CATTLE_ROLE_NONE=true` results in
```log
2022-03-05 16:13:47.421 3872 DEBUG cloudbaseinit.plugins.common.userdatautils [-] User_data stderr:
b"C:\\install.ps1 : The term 'true' is not recognized as the name of a cmdlet, function, script file, or operable \r\nprogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.\r\nAt line:1 char:1\r\n+ C:\\install.
ps1\r\n+ ~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (true:String) [install.ps1], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException,install.ps1\r\n \r\n" execute_user_data_script C:\Program …
```
=> fix formatting issues in wins install script

pkg/controllers/management/secretmigrator/clusters.go
Clean questions and answers from AppliedSpec and FailedSpec too.
Backport: https://github.com/rancher/rancher/pull/36856
=> [2.5] Fully clean rke template answers

pkg/controllers/management/rkeworkerupgrader/plan.go
https://github.com/rancher/rancher/issues/36860
Sometimes the `cluster` parameter will be updated in the apiserver (outside of this function), so a `DeepCopy()` is required to prevent modifying the cluster (and thus rewriting the first node to have all roles).
=> Added deepcopy when modifying node roles for nonWorker

pkg/apis/rke.cattle.io/v1/cluster.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/machinedrain/machinedrain.go, pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go, pkg/provisioningv2/rke2/planner/drain.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/probe.go, pkg/provisioningv2/rke2/planner/store.go, pkg/rancher/migrations.go
Issues:
https://github.com/rancher/rancher/issues/36506
https://github.com/rancher/rancher/issues/36782
https://github.com/rancher/rancher/issues/35999
https://github.com/rancher/rancher/issues/36776
https://github.com/rancher/rancher/issues/36763
During provisioning and upgrading, there were no statuses being put on the machine objects. Therefore, if there was a problem with a specific machine, one would have to look at the cluster status, find the machine name, and look at that specific machine to attempt to understand what was happening. This change adds the status (to either Provisioned or Updated conditions) so the proper status is shown directly in the UI. (#36782)
Now, that we are properly showing statuses on the machine objects, we can now show errors statuses as well when they …
=> Display drain errors on machine

pkg/controllers/management/clustergc/cluster_scoped_gc.go
**Issue:** [#36877](https://github.com/rancher/rancher/issues/36877)
**Problem:** 
The deletion of `Nodes` is triggered by the deletion of the namespace for holding the cluster's resources: https://github.com/rancher/rancher/blob/520235ade2f0db8a8789b98209f2dad577d4e95e/pkg/controllers/management/auth/project_cluster_handler.go#L249
But the namespace never be deleted because the `Remove` function for the cluster's lifecycle returns before deleting the namespace because the there are always more than two finalizers in the `Cluster` object : https://github.com/rancher/rancher/blob/520235ade2f0db8a8789b98209f2dad577d4e95e/pkg/controllers/management/auth/project_cluster_handler.go#L231-L236
The purpose of checking the number of finalizer is to make sure rbac stuff is deleted last. 
As the …
=> Delete Nodes during the cluster-scope garbage collection

pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go, pkg/rancher/migrations.go
Migrations were added to infrastructure and CAPI machines on Rancher upgrade.
However, there were both broken.
The infrastructure migrations were attempted to be done on an unstructured
struct. The migrations would fail because the unstructured struct doesn't have
the expected layout; there is an object field in the way. Therefore, this
migration is switched to the same condition setting as in the machine-provision
controller.
The CAPI machine migration was broken for a different reason. Because the
conversion webhook for CAPI objects is embedded in rancher-webhook, the
migration would require rancher-webhook to be upgraded before it would complete.
However, this could not happen because the migration would fail and cause
Rancher to restart.
Instead of migrating (which added a label to …
=> Fix migration of machines on Rancher upgrade

package/Dockerfile, pkg/provisioningv2/rke2/installer/installer.go, pkg/settings/setting.go, scripts/provisioning-tests, tests/integration/pkg/tests/custom/custom_test.go
Problem: if airgapped and you try to install CSI Proxy you will be met with an outbound call to an azure endpoint to download the node in wins. This needs to be configured so we can use the ui assets server in rancher to allow the wins install script to get configured to point at the rancher assets server to pull CSI Proxy.
Fix: Add two settings for proxy url and version, default version to be the azure endpoint and pass v1.0.0 in the dockerfile to lock the version in the assets server.
This is a sister PR to https://github.com/rancher/rancher/pull/36909 which got wins.exe into the ui assets server.
=> adding csi proxy to ui assets + version setting to control it

pkg/controllers/provisioningv2/rke2/common.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/planner.go
Issue: https://github.com/rancher/rancher/issues/36772
Ranging over maps does not guarantee key order, so the contents, and hence the
checksum of the managed chart file could be different on different runs through
the planner and causes machines to look like they are provisioning when they shouldn't be.
The change orders the keys of the map to ensure consistent output.
Provisioned RKE2 clusters with multus CNI so that managed charts were sent in the plan to the downstream nodes.
=> Order map keys for managed charts

tests/validation/tests/v3_api/test_airgap_ha.py
Regular HA Airgap defaults to what version RKE1 has as default.
This add the option to specify the k8s version for the specific RKE1 we are going to use.
=> Automation - adding_k8s_version parameter for local HA Airgap cluster 

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
This brings in fixes for rke1 regressions across the 1.20, 1.21, 1.22, and 1.23 latest versions.
https://github.com/rancher/wins/pull/100 
https://github.com/rancher/rke-tools/pull/146 
https://github.com/rancher/kontainer-driver-metadata/pull/859
https://github.com/rancher/rke/pull/2878
=> pinning v1.3.8-rc10 of rke

pkg/settings/setting.go
- Ensure the dashboard served up in rancher builds with version ending in `-head` tracks the 2.6.4 dashboard (lastest/master dashboard now tracks 2.6.5)
- When `rancher/rancher` branches for 2.6.5 we'll revert this change in that new branch
=> [2.6.4] Update default ui-dashboard-index setting

pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
Issue: GH-36727
Problem:
The v1 Node is not deleted when a CAPI Machine is deleted in the cluster manager UI.
Solutions:
1. Add the missing CAPI label "cluster.x-k8s.io/control-plane" to the control plane node. Otherwise, we cannot remove a node because of the errNoControlPlaneNodes error.
2. Delete the CAPI Machines which have the control plane role and are managed by an RKEControlPlane object. The deletion of the RKEControlPlane object is triggered by the deletion of the CAPI cluster.
Testing:
the following are tested on rancher which is running locally in Goland:
- provision an RKE2 custom cluster with 1 (control plane + etcd +worker) and 1 worker. First, delete the worker node, then delete the cluster 
- provision an RKE2 custom cluster with 1 (control plane + etcd +worker) and 1 …
=> Fix node deletion in RKE2 cluster

pkg/controllers/management/clusterdeploy/clusterdeploy.go
#36937 
rke1 clusters could not be provisioned in airgap environments.
The problem was due to a secret object being initialized as an empty object instead of a nil pointer.  When rancher was configured with a system image registry it would attempt to parse the registry secret to look for credentials.  Because this secret was an empty object instead of nil pointer it would attempt to parse an empty string as json.
I did, it works.
=> Fix rke deploy in airgap

Dockerfile.dapper, package/Dockerfile, package/Dockerfile.agent
1.23 is experimental for 2.6.4, so setting default to 1.22. Changing packaged binaries back to containerd because it was
an update specific to 1.23 k3s.
=> set local k3s to 1.22.7

pkg/provisioningv2/rke2/planner/instructions.go, pkg/provisioningv2/rke2/planner/instructions_test.go
The instructions being generated were not handling Windows PowerShell environment variables correctly. Unit tests were also added to ensure that the logic is valid.
* https://github.com/rancher/rancher/issues/37044
* https://github.com/rancher/windows/issues/143
=> Updating the instructions to handle Windows and PowerShell

pkg/apis/provisioning.cattle.io/v1/rke.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
CAPI supports the `NodeDrainTimeout` field on a machine as the duration draining should be attempted before giving up and deleting the infrastructure machine, which will allow deletion of the node to proceed. If the node drain timeout is 0, the infrastructure machine will not be deleted until the node drains successfully.
Related Issue: https://github.com/rancher/rancher/issues/36631
=> Add NodeDrainTimeout in MachineTemplateSpec

pkg/api/customization/clustertemplate/cluster_template.go, pkg/controllers/management/secretmigrator/clustertemplaterevisions.go
Add retries to the clustertemplaterevision action handler in case it
gets caught trying to update the CTR at the same time as the
secretmigrator controller.
Backport https://github.com/rancher/rancher/pull/37096
https://github.com/rancher/rancher/issues/37107
=> [2.4] Fix clustertemplate condition and add retries

scripts/build-server
**Problem**
------ 
Local data in rancher needs to be consistent with vendored RKE1 data. Refer to https://github.com/rancher/rancher/issues/37088 for more details. This is handled by our release process for normal release tags but not patch releases which are tagged adhoc. 
**Solution** 
------ 
Pinning KDM data for patch releases. Setting it to v1.3.7, because patch2 uses v1.3.7 and we want the behavior to remain the same as v2.6.3-patch2. Special branch `release-rke-v1.3.7` created here: https://github.com/rancher/kontainer-driver-metadata/pull/879
=> pin kdm data for v2.6.3 patch releases

pkg/controllers/management/node/cleanup.go, pkg/features/feature.go
Issues:
https://github.com/rancher/rancher/issues/36981
https://github.com/rancher/rancher/issues/37079
https://github.com/rancher/rancher/issues/37063
Add feature flag for custom RKE1 node cleanup
It is common for users to cleanup their own custom nodes when deleting
them from Rancher. This has caused issue with jobs and/or pods being
left around or nodes not being deleted properly.
This change adds a feature flag to turn the cleanup off globally if a
user doesn't need it.
Refactor node-cleanup job implementation
It was determined that some of the code around creating and deleting the
node-cleanup job was producing unexpected results like non-nil errors
with empty error messages. In addition, the cleanup job is being
leftover in some case.
This code makes the error messages more …
=> Private registry cleanup job

pkg/apis/rke.cattle.io/v1/controlplane.go, pkg/controllers/management/node/controller.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go, pkg/provisioningv2/capi/capi.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/planner.go
Issue: https://github.com/rancher/rancher/issues/37001
The fundamental issue being fixed here is restoring an RKE2 cluster with 1 
etcd-only node, 1 control plane node, and 1 worker node. Previously, the etcd 
and control plane nodes would be shutdown before the restore happened. The 
cluster-agent would then be rescheduled to the worker node because it wouldn't 
be updated. This caused some issues because it looked like the agent was 
connected, but Rancher couldn't use it in any way because the api-service was 
shutdown. This would cause the restore to hang because the etcd-only node's 
kubelet version was not getting updated.
After this change, all nodes in the cluster are shutdown before the restore 
happens. This caused the cluster agent to disconnect, as desired.
However, this …
=> Be more intelligent when the cluster-agent is disconnected

tests/framework/clients/rancher/client.go, tests/framework/extensions/charts/ranchermonitoring.go
**Background:**
Currently in the framework when attempting to install a chart we would just hit this endpoint `v1/catalog.cattle.io.clusterrepos` as a result chart installation was only supported in local clusters.
**Framework updates:**
Updated Catalog client to support chart installation in downstream clusters with the prefix `/k8s/clusters/<clusterid>`. Updated the ranchermonitoring extension to account for this new change.
=> Updated Catalog client to support chart installation in downstream clusters

pkg/controllers/managementuser/controllers.go, pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
This should possibly help to resolve https://github.com/rancher/rancher/issues/36948 and other weird issues we are having with the snapshotbackpopulate controller.
Also, will stop the duplicate snapshot create error message for https://github.com/rancher/rancher/issues/36711
=> Remove usage of snapshotbackpopulate tweaklist for reliability

go.mod, go.sum, pkg/channelserver/channelserver.go, pkg/controllers/management/kontainerdrivermetadata/data.go, pkg/settings/setting.go
Issue: https://github.com/rancher/rancher/issues/36827
The default rke2/k3s version should be configurable per rancher version. 
Both the default rke2/k3s version and rancher version need to be a range so we do not need to add a new entry each time when we release a new rancher version. 
Rancher will get the version ranges from the channelserver, calculate the default versions for the current rancher version, and expose them as new `Settings` items: 
- `rke2-default-version`
- `k3s-default-version`
And they are available under the `/v1/management.cattle.io.settings` endpoint automatically. 
We need to add the support for `appDefaults` to the channelsesrver : https://github.com/rancher/channelserver/pull/17
- the correct default versions show up in the settings after rancher runs up 
- the …
=> Add New Settings for RKE2/K3S Default Versions 

pkg/api/norman/customization/clustertemplate/cluster_template.go, pkg/controllers/management/secretmigrator/clustertemplaterevisions.go
Add retries to the clustertemplaterevision action handler in case it
gets caught trying to update the CTR at the same time as the
secretmigrator controller.
(cherry picked from commit 8ee27472bb0e299cb962e724eb165d22c72e1f5e)
=> Fix clustertemplate condition and add retries

pkg/apis/management.cattle.io/v3/tools_system_images.go
Issue: https://github.com/rancher/rancher/issues/36518
Problem:
If we create an RKE/RKE2 downstream cluster with multiple control plane nodes and with ClusterAuthEndpoint enabled, then use the secondary contexts in the kubeconfig file downloaded from Rancher UI to access the cluster, we will hit the following error with one of the secondary contexts:
```
error: You must be logged in to the server (Unauthorized)
```
meanwhile, the logs of the `kube-api-auth` pod on this control plane show the following kind of error:
```
time="2022-02-24T21:11:46Z" level=info msg="  ...looking up token for kubeconfig-user-qmk2kdmjlt"
time="2022-02-24T21:11:46Z" level=error msg="clusteruserattributes.cluster.cattle.io \"cattle-system/user-qmk2k\" not found"
```
Solution:
It turns out to be a bug in …
=> bump the image tag of kube-api-auth to v0.1.8

pkg/image/resolve_test.go
Fixes a test that would occasionally fail - windows and linux now use the same mirrored-pause image, so this needs to be added to the `bothImages` slice.
=> Adding rancher/mirrored-pause to expected image list for win/linux

pkg/settings/setting.go
- As per description in #37011, this PR reverts those changes
- `rancher/rancher` `release/v2.6` tracks 2.6.5 (and later), so it should track `rancher/dashboard` `master` (2.6.5 and later)
=> Update ui-dashboard-index setting

pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go, pkg/provisioningv2/image/resolve.go, pkg/provisioningv2/rke2/planner/planner.go
Issue: https://github.com/rancher/rancher/issues/36137
There were a few images like rancher-agent, system-agent, and
system-upgrade-controller that were not being pulled from the private registry
setup in an RKE2 cluster.
This change adds image resolvers, similar to those for v3 clusters, to ensure
that the images are being pulled from private registries whenever one is defined
for Rancher images.
Provisioning RKE2 cluster with private registry and ensure that all images (except for fleet-agent) are pulled from the private registry.
=> Pull Rancher images from private registry in RKE2 clusters

pkg/image/resolve_test.go
TestGetImages uses selectFirstEntry (which takes in a map) to
find the WindowsRKE image. In the newest version of kdm, this
image will be the same in win/linux. Now we check to see if
it is an image that should be used by both before calling
it win only.
=> Fixing flaky test TestGetImages

tests/validation/tests/v3_api/resource/terraform/k3s/master/nginx-ingress.yaml
Removed the serviceMonitor part because it now requires CRDs to be installed manually, otherwise the helm chart fails to install with the following error: `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`. I don't think we need this part so I just removed it.
=> Update ingress-nginx chart version and include necessary values for k3s

pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/machineprovision/template.go
Issue: https://github.com/rancher/rancher/issues/36287
The infrastructure and CAPI machines have different names. This makes
identifying machine provisioning logs difficult to match with the machines to
which they belong.
This change adds more details to the machine provisioning and error messages to
make this easier.
Provisioned RKE2 clusters to ensure more detailed messages are logged and appear in the UI.
=> Improve machine provisioning messages

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/controllers/management/clusterprovisioner/provisioner.go, pkg/controllers/management/imported/imported.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go, pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/planner.go
Issue: https://github.com/rancher/rancher/issues/36993
There were issues with different pages of the UI showing different status for
the cluster based on which object it was showing (management vs. provisioning).
This change adds better syncing between the cluster objects so they have the
same conditions and statuses.
In addition, the planner always used the Provisioned condition when
changing/applying the node plans. This was confusing, especially when a machine
was being updated. This change will use the Reconciled condition instead.
Provisioning and upgrading clusters of all types. Making sure that the Home page and Cluster Management page.
=> Add better condition syncing for v2 provisioning objects

pkg/data/management/kontainerdriver_data.go
This pull request bumps the LKE kontainer-engine driver to [v0.0.4](https://github.com/linode/kontainer-engine-driver-lke/releases/tag/v0.0.4). This version resolves an issue that would prevent LKE clusters running Kubernetes >= 1.22 from being created or managed in Rancher.
This fix specifically switches the cluster service account creation routine to RBAC v1 from RBAC v1beta1, which was [removed in Kubernetes v1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122).
The corresponding change can be found [here](https://github.com/linode/kontainer-engine-driver-lke/pull/11/commits/57f6b5f9f65c65004241332ed41b45a6607806b0#diff-3a710ab6a1dd3264a76a1e4c4c3ebcee14762ef3a66f707726e17fd5fa255715R25).
=> Bump kontainer-engine-driver-lke to v0.0.4

package/Dockerfile
Update Rancher webhook min version in Dockerfile to remove `-rc1`
=> Update Rancher webhook min version in Dockerfile

tests/framework/extensions/cloudcredentials/cloudcredentials.go, tests/framework/extensions/cloudcredentials/linode/create.go, tests/framework/extensions/cloudcredentials/linode_config.go, tests/framework/extensions/machinepools/linode_machine_config.go, tests/v2/validation/provisioning/providers.go, tests/v2/validation/provisioning/provisioning_node_driver_test.go
**Framework Updates:**
Added support for provisioing linode RKE2 clusters. Including: 
- linode cloud credential helper
- rke-machine-config.cattle.io.linodeconfig machine pool config helpers.
**Validation test updates**
Updated provisioning validation tests to account for linode node provider.
=> Linode node driver RKE2 Provisioning

pkg/controllers/management/node/cleanup.go, pkg/controllers/management/usercontrollers/controller.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go
Issues:
https://github.com/rancher/rancher/issues/36798
https://github.com/rancher/rancher/issues/37256 
Rancher will try to clean up imported clusters when they are removed. If this
failed for any reason, then the cluster would never get removed from Rancher.
This change adds a retry of 3 times: if Rancher is unable to clean up the
imported cluster, then it will move on with removal.
Removing imported clusters from Rancher that are Available and Unavailable.
=> Imported cluster cleanup retry

tests/validation/tests/v3_api/common.py
tests.v3_api.test_service_discovery.test_dns_record_type_multiple_workloads
Above test fails almost always while running the **rancher-v3_ontag_custom_certification**. 
Here is a link to the above failed job. - jenkns 77
In this PR I've added the possible fix for the test failure.
Here is a link to the passing test with the fix - 620 - freeform
=> Added a fix for service discovery related error.

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/plansecret/plansecret.go, pkg/provisioningv2/rke2/planner/planner.go
Today, etcd snapshots are currently created and maintained by the `snapshotbackpopulate` controller. 
It is possible that the `nodeName` of a node changes, which can throw accountability off. This was causing the issue https://github.com/rancher/rancher/issues/37052 to occur.
This PR changes snapshot creation and maintenance behavior to being properly split between two controllers.
There are two cases of snapshots to consider -- snapshots that are local and snapshots that are stored in S3.
In the local case, snapshots will be created by the `plansecret` controller using the minimal amount of information found from the output of the `etcd-snapshot ls` command, and then populated using the `snapshotbackpopulate` controller.
In the case of S3, snapshots will always be created and maintained …
=> More elegantly create and manage v2prov snapshots

tests/validation/tests/v3_api/resource/terraform/rke2/master/define_node_role.sh, tests/validation/tests/v3_api/resource/terraform/rke2/master/install_rke2_master.sh, tests/validation/tests/v3_api/resource/terraform/rke2/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/rke2/master/variables.tf, tests/validation/tests/v3_api/test_import_rke2_cluster.py
This PR allows for our rke2 cluster creation automation to be run using either:
- The default approach (server and agent nodes, where server nodes have ALL roles)
- Split node roles (server and agent nodes, but server nodes can be any of 6 possibilities: all roles, etcd-only, etcd-cp, etcd-worker, cp-only, or cp-worker)
Most of the logic added does just that using `define_node_role.sh` which gets run as part of the terraform script. This file places the configuration for the defined node role in a yaml on the node in `/etc/rancher/rke2/config.yaml.d`, so when using split roles there are actually 2 defined configuration yamls: one for general configuration args (`/etc/rancher/rke2/config.yaml`) and one for the role configuration (`/etc/rancher/rke2/config.yaml.d/role_config.yaml`).
As part …
=> Implement automation for split node roles on rke2

pkg/controllers/management/authprovisioningv2/authprovisioningv2.go, pkg/controllers/management/authprovisioningv2/cluster.go, pkg/controllers/management/authprovisioningv2/crtb.go, pkg/controllers/management/authprovisioningv2/prtb.go, pkg/controllers/management/authprovisioningv2/role.go
Changes CRTBs and PRTBs so that they persist until the cluster is
fully deleted. This allows users to see deletion messages as
the cluster is removed and to see the cluster gone on the UI
=> Changing cluster/project roles so they persist until cluster delete

pkg/controllers/provisioningv2/rke2/provisioninglog/provisioninglog.go
The original intention of the provisioning log was to put all logs related to
cluster provisioning in the log. When we switched to using the `Updated`
condition, this was not the case.
After this change, provisioning all provisioning logs will be included.
=> Put more logs in provisioning log

pkg/provisioningv2/rke2/installer/installer.go, pkg/provisioningv2/rke2/installer/server_test.go
Currently, Rancher is attempting to serve a `wins-install.ps1` script when airgapped and the remote script is not available. This PR addresses this by switching to serving `wins-agent-install.ps1` instead as well as adding unit tests that attempt to mock airgap by testing with an unstarted http test server, to mimic an airgap setup.
=> Ensure that Rancher serves the right Windows install script when airgapped

pkg/auth/providers/saml/saml_client.go
`err` is checked for nil on the lines above and is guaranteed to be nil
in this log message, so don't use it. Add more wording to indicate that
it could be a group membership problem and to align better with the
wording in the UI.
SURE-4509
=> Fix SAML unauthorized log message

pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/manifests.go
Issue: https://github.com/rancher/rancher/issues/37301
The system-default-registry configuration was added to all RKE2/K3S plans if the
setting was non-empty. The caused a problem with K3S worker-only nodes because
K3S agent binary would error for the unexpected parameter.
This change only includes the system-default registry parameter for
non-worker-only nodes.
=> Don't include system-default-registry in worker-only plan

Dockerfile.dapper
This workaround is causing issues with our build and is no longer
needed.
=> Remove binutils-gold workaround for arm64

tests/validation/tests/v3_api/test_rke2_airgap.py
Allow the following config param to work correctly during tarball install:
`--cni=multus,<calico|cilium>` 
Before this change, it would only allow multus to be used with canal during tarball install in airgap.
=> Fix small bug in rke2 airgap creation tests

pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/planner_test.go
This prevents restarting the node because the cluster agent doesn't run on Windows making it not necessary.
* https://github.com/rancher/rancher/issues/36748
=> Going to try to skip Windows since it doesn't run a cluster agent.

pkg/controllers/managementuserlegacy/alert/deployer/upgradeimpl.go
Fix for panic in https://github.com/rancher/rancher/issues/36260
I marked this as a release blocker due to the simplicity of the reproduction steps(upgrading from Rancher v2.5 -> 2.6 and then upgrading a downstream RKE1 Windows cluster)  and that Rancher seemingly cannot recover without the cluster being deleted.
=> fix v1 monitoring app panic

pkg/controllers/provisioningv2/rke2/bootstrap/controller.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/data/management/machinedriver_data.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/initnode.go, pkg/provisioningv2/rke2/planner/instructions.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/store.go
Issues: 
https://github.com/rancher/rancher/issues/37500
https://github.com/rancher/rancher/issues/37501
https://github.com/rancher/rancher/issues/37502
There were several issues related to IP addresses that were causing issues with
RKE2 provisioning and multiple etcd-only nodes.
1. If there were multiple etcd-only nodes, then joinURL may change and be for
another node when the scraping happens. The reason was that the clientURLs would
be listed for each etcd node. When Rancher was scraping it, it was taking the
first one no matter what which may have been for another node.
The fix here is to add an addition periodic instruction to "cat" the db name
file and use it to identify the clientURL with the correct node.
2. The machine plan for the bootstrap node may have been created before the …
=> Fix planner address issues

pkg/controllers/management/node/controller.go
**Issue:** https://github.com/rancher/rancher/issues/37449
**Problem:**
When rancher provisions an RKE node-driver cluster, one of the steps is to authenticate the machine to a private registry if one is defined in the cluster's spec. A [recent change](https://github.com/rancher/rancher/pull/36578) of migrating the private registry's password to a secret makes Rancher think there is no private registry in the cluster's spec, so it skips authenticating step.  As a result, the error "no basic auth credentials" is returned.
**Solution:**
The fix is to add the password to the cluster's spec before the authenticating step. The cluster object is used only within the function, so there should be no negative impact on security.
**Testing:**
Although I cannot get a setup to test the fix by …
=> [2.6] Fix the "no basic auth credentials" error when using private registry 

Dockerfile.dapper, scripts/go-get
This is to automate `go get` from any module that we use in Rancher. Most commonly used is `rancher/rke`, so we can use this make target in a GitHub Actions workflow to automatically update `rancher/rke` library in this repository after a tag has been created.
This could be a 100% Actions workflow (meaning that Dapper is not involved) but in this way, people can also use it locally if needed:
```
GOGET_MODULE=github.com/rancher/rke GOGET_VERSION=v1.3.10-rcX make go-get
```
=> [release/v2.6] Add target to automate go get

Dockerfile.dapper, package/Dockerfile, package/Dockerfile.agent
Issue: https://github.com/rancher/rancher/issues/37432
bump the local k3s cluster to v1.23.6-k3s1
=> [2.6.5] Set local k8s 1.23.6

pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/planner.go
https://github.com/rancher/rancher/issues/37575
The reported issue was that the etcd nodes were drained after an etcd snapshot was created. This is caused due to the fact that etcd snapshot creation is done by replacing the plan on etcd nodes with an `%s etcd-snapshot` command.
Originally, we relied on the next step in the iterative `planner.Process` to reconcile the plans on the etcd nodes back to the desired state (which is just the install script of the runtime). If drain on upgrade is enabled, reconcile would attempt to drain the etcd nodes before applying the install script command. 
We are now adding an additional phase to etcd snapshot creation, which will replace the plan of etcd nodes back to the install script. This means that when the etcd snapshot creation is complete, the …
=> Deliver etcd/controlplane plans after snapshot creation to avoid drain

pkg/image/external/external.go, pkg/image/external/external_test.go
Fixes https://github.com/rancher/rancher/issues/37577
Ensures that the required images for rke2 Windows functionality in airgap are present in the published rancher images lists
I lightly refactored external.go and broke our the download function for urls as well as simplified the downloadExternalSupportingImages function.
The unit tests validate that the changes are working as expected. However, a full airgap validation is required to definitively know.
These changes should not regress any existing functionality.
Output from unit tests with latest changes:
```console
=== RUN   TestGetExternalImages
--- PASS: TestGetExternalImages (8.15s)
=== RUN   TestGetExternalImages/k3s-test
time="2022-05-04T21:54:46-04:00" level=info msg="generating k3s image list..."
time="2022-05-04T21:54:49-04:00" …
```
=> Fix windows image lists for airgap

pkg/provisioningv2/rke2/planner/certificaterotation.go, pkg/provisioningv2/rke2/planner/certificaterotation_test.go
#37587 
#37588
When rotating certificates on k3s or rke2 all nodes would be updated regardless of if they were running the relevant service.
Only call certificate rotation on nodes when the specified services are related to the node's roles.
I tested rotating etcd and only saw etcd and all role nodes updated.  There is a unit test to confirm the behavior for other combinations.
=> certificate rotation only rotates certificates on applicable nodes

pkg/apis/provisioning.cattle.io/v1/rke.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
https://github.com/rancher/rancher/issues/37613
There is a potential issue where utility operations cause unnecessary thrashing of the controlplane nodes (i.e. unnecessary draining).
This PR removes storage of the various utility fields for the RKE config struct to ensure that the RKE config does not change unnecessarily on operations like etcd snapshot creation.
=> Drop unnecessary cluster spec fields to prevent unnecessary plan thrashing

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, scripts/go-get
Used the new make target `go-get`: `GOGET_MODULE=github.com/rancher/rke GOGET_VERSION=v1.3.11-rc2 make go-get`, but needed a reverse in order as `go.sum` didn't get cleaned up properly.
=> [release/v2.6] Bump RKE to v1.3.11-rc2

pkg/settings/setting.go
- Ensure the dashboard served up in rancher builds with a version ending in -head tracks the 2.6.5 dashboard (lastest/master dashboard now tracks 2.6.6)
- When rancher/rancher branches for 2.6.6 we'll revert this change
- Similar change to https://github.com/rancher/rancher/pull/37011
=> [2.6.5] Update default ui-dashboard-index setting

pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/initnode.go
https://github.com/rancher/rancher/issues/37641
Upon attempts to correct forced init node designation during etcd restore, the wrong name was used (machine name vs. node name). This PR corrects this behavior, so that the machine ID is properly used.
This PR also makes the waiting message when no potential init nodes are available a little less vague, using the term `viable` rather than `possible`.
=> use machine ID directly when designating init node during etcd restore and make init node waiting message less vague

scripts/create-components-file.sh
Adding it as the release process requires to check for `-rc` versions here, easier to have it in each release to see what the status is.
=> [release/v2.6] Add min versions with -rc to components file

tests/framework/clients/rancher/catalog/clusterrepo.go, tests/framework/clients/rancher/config.go, tests/framework/extensions/charts/charts.go, tests/framework/extensions/charts/payloads.go, tests/framework/extensions/charts/rancheristio.go, tests/framework/extensions/charts/ranchermonitoring.go, tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/workloads/deployments/list.go, tests/v2/validation/charts/demobookapp.yaml, tests/v2/validation/charts/istio.go, tests/v2/validation/charts/istio_test.go
- Implemented:
- Payload structs to generate catalog client payloads
- Install & upgrade rancher Istio chart helpers as well as their specific payload helpers with chart values options
- Watch and wait helper to wait for deployments in a given namespace
- A custom request helper built on top of the management client
- Cluster id getter with the given cluster name
- List deployments helper with the given namespace and list options
- Refactored:
- Get the latest chart version method of catalog client, created get list chart versions method from the same logic
- Rancher config to add the ability to point the desired cluster for chart installations
- Rancher monitoring chart install helper to remove hardcoded payloads
- Implemented: 
- Istio p0 & …
=> Add istio p0 & upgrade validation test cases including their helpers

tests/v2/validation/Jenkinsfile
**Validation Changes:**
Timeout is now tied to an environment variable set by the Jenkins job. Also Made a fix in the Jenkinsfile to support both setting a repo fork, and have it set by default by in GitSCM."
=> Enable Per-test timeouts for Jenkins jobs

pkg/auth/tokens/manager.go, pkg/controllers/management/auth/register.go, pkg/controllers/management/podsecuritypolicy/template.go, pkg/controllers/managementapi/controllers.go, pkg/controllers/managementuser/clusterauthtoken/register.go, pkg/controllers/managementuser/rbac/globalrole_handler.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/serviceaccount.go, pkg/controllers/managementuserlegacy/monitoring/register.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go
Issue: https://github.com/rancher/rancher/issues/36845
There was an issue where a concurrent map read and write would happen. It is
difficult to diagnose, but this is one place where an unstructured object was
being modified without first deep copying the object.
Deep copying the object before changing it should stop the panic.
This is an intermittent issue. Previously, the panic would happen on approximately 1 out of 3 CI runs. The CI has run 6 times for this PR and no panic has been seen.
=> Deepcopy infra machine remove

pkg/rancher/rancher.go
Use the apiserver NoCache middleware to set "Cache-Control: no-cache,
no-store, must-revalidate" on all Rancher endpoint responses. This
prevents problems with clients trying to use cached data that is not
properly invalidated when it becomes stale on the server.
Technically, "no-cache" and "must-revalidate" are superfluous when
"no-store" is set[1].
The header is set early in the middleware chain, and can be overridden
by another middleware or by a route handler. This happens, for instance, with
the catalog endpoint response[2].
[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#preventing_storing
[2] https://github.com/rancher/rancher/blob/6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1/pkg/api/norman/customization/catalog/template.go#L133 …
=> [2.6.6] Set Cache-Control header default on all responses

pkg/api/norman/customization/cluster/actions_kubeconfig.go, pkg/controllers/management/feature/feature_handler.go, pkg/controllers/managementuser/clusterauthtoken/token.go
Issue: https://github.com/rancher/rancher/issues/37147
A previous change added token hashing implementation. When token hashing is
enabled, then ClusterAuthToken must be created in the downstream cluster when
the kubeconfig is generated. This means that the kubeconfig cannot be generated
until the cluster is active. If token hashing is disabled, then this requirement
is not needed and the kubeconfig can be generated without requiring that the
ClusterAuthToken be created in the downstream cluster.
This change will check the token hashing feature flag when generating a
kubeconfig and will not create the ClusterAuthToken. In addition, the
controller that would create the ClusterAuthToken in the downstream cluster is
restored to create the ClusterAuthToken if token hashing is disabled. …
=> Stop creating ClusterAuthToken on kubeconfig generation if token hashing disabled

pkg/controllers/management/k3sbasedupgrade/deployPlans.go
Rancher was checking all namespaces for plans, and trying to update ones not currently managed by rancher in order to force rancher to manage them. By reusing the same client (created using `metav1.NamespaceAll`, the generated client (wrangler uses the kubernetes client generator) uses the namespace of the client in the API request, which is always empty so the object cannot be updated. 
Now rancher will create a separate client for the namespace it finds existing plans in, and disables all plans not managed by rancher.
Creating plans manually in any namespace should result in them being disabled, unless they are explicitly managed by rancher.
Currently, all non rancher-managed plans will be disabled once an upgrade is started, due to uncertainty around what other plans could exist and …
=> [2.6.6] Only check cattle-system for existing plans

pkg/settings/setting.go
- The PR reverts https://github.com/rancher/rancher/pull/37662
- Ensure the dashboard served up in rancher builds with a version ending in `-head` tracks the `master` (`2.6.6`) dashboard branch
=> [2.6.6] Update default ui-dashboard-index setting

.drone.yml
This PR addresses the following scenarios:
* Our automation triggers two builds because of the push event (see https://github.com/rancher/rancher/actions/runs/2371727306 and https://github.com/rancher/rancher/pull/37794), scoping the steps to specific branches and tags will eliminate wasting time and resources.
* This removes running provisioning-tests on tag, as tagging is just a build of an already working copy. This should speed up creating releases/release candidates
* Removed slack_notify steps as they do not seem to work (~I have an open request with EIO to check on the status~) EIO confirmed its not setup for current Slack
=> [release/v2.6] Scope Drone steps depending on push to branch/tag

pkg/api/norman/store/cluster/cluster_store.go
Issue: 
https://github.com/rancher/rancher/issues/37708
For REK clusters that are created from a cluster template revision,  the private registry info ( url, username, or password) from the existing cluster is always used when updating the cluster, this causes the problem in this very specific scenario: if the private registry info is changed in the newly-applied cluster template revision AND those fields are not marked as "allow user override", the new values will never be applied. 
The private registry info from the existing cluster is used only when the "allow user override" is enabled for the private registry info in the cluster template revision; otherwise, apply the values from the revision. 
Steps (exactly same to the one in the issue):
- Create an RKE1 cluster template with a …
=> Fix Cluster Templates - private registry support without override option enabled

tests/framework/extensions/machinepools/amazonec2_machine_config.go, tests/v2/validation/provisioning/README.md
**PR Description**
This PR adds support for EC2 images to be specified when testing with the Go automation framework. If you choose to not set this optional parameter, then the prior behavior of the default AMI per AWS region still maintains; this simply offers more configuration choice.
Tested with multiple quick start / community AMIs for the following distros:
- Ubuntu 20.04: PASS
- SUSE 15SP3: PASS
- Ubuntu 22.04: PASS
- Not supported, but the automation should still allow to pass, which it did.
=> Add AMI support for EC2 node drivers

go.sum
HEAD of release/v2.6 branch currently has a dirty status in Drone CI due to a go.sum change that was missed in a previous https://github.com/rancher/rancher/commit/dbddead8c39f38dc83f5da8bf18cdcd5c449a5eb and is brought in when a go mod tidy is run during CI. This PR addresses that and should resolve CI issues in combination with https://github.com/rancher/rancher/pull/37891 once it is merged.
```
git diff go.sum
diff --git a/go.sum b/go.sum
diff --git a/go.sum b/go.sum
--- a/go.sum
+++ b/go.sum
@@ -1240,7 +1240,6 @@ github.com/prometheus/tsdb v0.7.1/go.mod h1:qhTCs0VvXwvX/y3TZrWD7rabWM+ijKTux40T
github.com/qri-io/starlib v0.4.2-0.20200213133954-ff2e8cd5ef8d/go.mod h1:7DPO4domFU579Ga6E61sB9VFNaniPVwJP5C4bBCu3wA=
github.com/quobyte/api v0.1.8/go.mod …
```
=> Fix missing entry in go.sum for aks-operator

.drone.yml
This reverts commit c3deb1123080159ea73a909d072fdf931f1217e5.
Provisioning tests were turned off for more than this PR intended. Due to the PR only having one commit, I have to revert the entire commit and have @superseb address this later.
This PR will require https://github.com/rancher/rancher/pull/37892 to be merged first
=> Revert "Scope Drone steps depending on push to branch/tag"

tests/framework/extensions/machinepools/amazonec2_machine_config.go
**PR Description**
There was a small issue in my earlier PR https://github.com/rancher/rancher/pull/37884 in where the json for the new `AMI` variable duplicated `region` instead of `ami`. This is a small update to fix that so that the change properly works.
=> Fix json ami configuration

pkg/controllers/management/auth/crtb_handler.go, pkg/data/management/role_data.go
Snapshots get stored in the local cluster under the `fleet-default`
namespace. Because of this, roles get access to individual
snapshots. If no snapshots are stored, the users do
not have access to view or create snapshots in the UI.
Users now have access to the `etcdsnapshots.rke.cattle.io`
in the namespace of the cluster. Making the CRD visible in
the schema when no snapshots are present.
#37630
The "Manage Cluster Backup" role also did not have the
`etcdsnapshots.rke.cattle.io` rule in its template.
#37752
=> Fixed snapshot RBAC for RKE2 clusters

pkg/controllers/management/etcdbackup/etcdbackup.go, pkg/controllers/management/etcdbackup/etcdbackup_test.go
Previously, retention was limited to the total number of recurring etcd backups, which could leave a cluster without any successful etcd backups if the cluster entered a bad state (for example, if the etcd container was stopped on the downstream node, a backup would never be taken, but it would be counted towards the total). An attempt was made to remediate this by not removing failed recurring backups, temporarily. This PR follows parity with RKE2, by using the retention set for the cluster as the number of successful backups to keep, as well as the number of failed backups to keep (e.x. a retention of 5 means potential of 5 successful and 5 failed backups).
Some minor refactoring and improvements have been made, mostly notably that we no longer rotate backups in cluster sync, but rather …
=> Added retention for failed snapshots

pkg/auth/providers/azure/clients/ad_graph_client.go, pkg/auth/providers/azure/clients/ms_graph_client.go
Fixing a linter issue that was not caught in the pervious PR CI run due to the `build` stage not having run, giving a fake pass.
There were three instances of a linter error like this: `unexported-return: exported func NewADGraphClientFromCredential returns unexported type *clients.azureADGraphClient, which can be annoying to use (revive)`
We may want to think about this rule - whether it warrants an exception to our golang-ci config.
=> Fix a linter issue blocking the CI

pkg/catalogv2/git/download.go, pkg/catalogv2/git/download_test.go
Issue: SURE-3512, https://github.com/rancher/rancher/issues/35135
Our existing logic for git repo SSH URL validation only allows URLs with the prefix `git@`, but users may have a username different than `git`. This PR modifies that logic to allow URLs with other usernames such as `gitrepos@`
=> Fix git repo SSH URLs with custom usernames

pkg/data/dashboard/rbac.go, pkg/settings/setting.go
This PR adds a new setting `ui-favicon` and adds this to the unauthenticated list, so that this setting is retrievable by the UI before the user has logged in.
This is in support of UI ticket - https://github.com/rancher/dashboard/issues/5067 - to allow users to configure a custom favicon for Rancher.
=> Add ui-favicon setting to support custom favicon for the UI

tests/framework/extensions/charts/charts.go, tests/framework/extensions/charts/ranchermonitoring.go, tests/framework/extensions/projects/projects.go, tests/framework/extensions/secrets/getsecrets.go, tests/framework/extensions/secrets/patchsecrets.go, tests/framework/extensions/secrets/secrets.go, tests/framework/extensions/services/create.go, tests/v2/validation/charts/monitoring.go, tests/v2/validation/charts/monitoring_test.go
- Implemented:
- Project getter with the given project name
- Watch and wait helpers for stateful sets and deployment annotations
- Rancher monitoringv2 chart upgrade helper
- Create service, secrets & patch secrets helpers
- Refactored:
- Rancher monitoringv2 chart install helper to get the correct URL value in the payload
Implemented:
- Monitoringv2 p0 & upgrade cases
- Private wait healthy response helper built on top of the custom request helper for charts
- Private wait for unknown Prometheus targets and targets check helpers built on top of the custom request helper for charts
- Private alert config/secret manipulators for routes and receivers
- Private Prometheus rule creation helper
- Private webhook receiver creation and its required …
=> Add monitoringv2 p0 & upgrade validation test cases including helpers

tests/framework/clients/rancher/provisioning/client.go, tests/framework/clients/rancher/provisioning/cluster.go
**Background** 
When using the provisioning client we were not getting the Steve API endpoint but rather the Kubernetes API. So when attempting to do some calls it would fail differently in comparison to the rancher monitoring UI.
**Updates**
- Over wrote most of the API calls to hit the steve API endpoint
- For now just not including watch was we need to monitor the cluster resource using the Kubernetes API
- We get an unknown error during clean up for a standard user, which is expected because the user no longer has the proper RBAC to view the resource it had just deleted
- We also get an expected error when cleaning up the rke-machine-config.cattle.io resource, because now when we delete the cluster using the steve API endpoint, the rke-machine-config.cattle.io resource gets deleted as …
=> Updated the provisioning client to hit the steve API endpoint.

pkg/api/norman/customization/cluster/actionhandler.go, pkg/api/norman/customization/setting/setting.go, pkg/api/steve/clusters/kubeconfig.go, pkg/auth/providers/common/usermanager.go, pkg/auth/tokens/manager.go, pkg/settings/setting.go
Users request kubeconfigs with tokens via the CLI or through the UI.
kubeconfig tokens created through the CLI did not have
randomized names. Thus invalidating any previously created tokens.
Tokens requested via the UI did not have a TTL set creating an
endless list of tokens to store.
=> Added randomization and TTL for all kubeconfig tokens.

pkg/provisioningv2/capi/logger/log.go
This PR adds a `[CAPI]` prefix to log messages that are logged by the CAPI controllers in Rancher for the v2provisioning framework. 
https://github.com/rancher/rancher/issues/37981
=> Prefix CAPI log messages with [CAPI]

tests/validation/tests/v3_api/test_custom_host_reg.py
This PR serves the purpose of fixing one of the flaky tests related to -> _test_cluster_template_.
Analysis suggests that the test fails due to failure in creating admin_client.
Hence, added a logic that retries to create admin_client.
=> admin-client fixes

pkg/auth/providers/azure/azure_provider.go
Rancher now sets the proper permission scope for its redirect URL for Azure AD, so that MFA works with a specific app registration in Azure AD.
=> Specify the openid scope for MFA to work with the Azure AD app

pkg/auth/providers/azure/clients/ms_graph_client.go
Related to https://github.com/rancher/rancher/issues/29306, there has been an issue found by QA in their tests of China endpoints for Microsoft Azure AD.
Issue: https://github.com/rancher/rancher/issues/38022
The SDK client we use implicitly sets the global Graph Endpoint value in its constructor. This PR explicitly sets the Graph Endpoint necessary at runtime. The global (https://graph.microsoft.com) is not the only Graph Endpoint, since there is also one for China and other regions. The code now passes it from the auth config to this base contractor for the client.
=> Explicitly set Graph Endpoint for new Graph SDK client

pkg/auth/providers/azure/azure_provider.go, pkg/auth/providers/azure/clients/ad_graph_client.go
Main issue: https://github.com/rancher/rancher/issues/29306
Direct issues: https://github.com/rancher/rancher/issues/37969 and https://github.com/rancher/rancher/issues/38067
The PR does two things:
1. Sets refresh callbacks on service principle token (SPT) explicitly to nil. This had been accidentally removed when a major refactoring of the old Azure AD client was taking place. The nil-pointer panic happened in the third-party SDK if this refresh callback is not set to nil. It would happen on periodic principal refresh that Rancher does to see if an Azure user known to Rancher still exists in Azure.
2. Properly parses the principal ID and extracts the actual user ID for the old flow via Azure AD Graph.
=> Fix panic on refresh; properly parse principal ID before getting a user

pkg/auth/providers/azure/azure_provider.go, pkg/auth/providers/azure/config.go
Main issue: https://github.com/rancher/rancher/issues/29306
Direct issue: https://github.com/rancher/rancher/issues/38022
This fully synchronizes the endpoints defined in the UI initially when Azure AD is set up on a fresh v2.6.6+ setup (https://github.com/rancher/dashboard/issues/5671) with the endpoints defined by the backend on endpoint upgrade (only relevant for China endpoints).
The auth config update is reorganized for better readability.
The end scenario (which I tested and verified) is the following: whether you upgrade the endpoints (Global or China) or start anew with the new endpoints already defined (without the need to upgrade them), the resulting auth configs in both cases should be the same.
Specifically, we're interested in Endpoint (login endpoint), Graph Endpoint, Auth …
=> Simplify Azure AD auth config migration; update login, token, auth endpoints for China

go.mod, go.sum
Issue: #37766
When creating a Rancher cluster with a `server_url` that would cause an overflow of the TLS cert annotation, an rke cluster could not be provisioned:
```
2022/03/17 00:09:46 [INFO] failed to create TLS cert for: 127.0.0.1, Secret "serving-cert" is invalid: metadata.annotations: Invalid value: "listener.cattle.io/cn-internal-abcdefghij-rancher-lb-int-123456789.us-west-2.elb.amazonaws.com": name part must be no more than 63 characters
```
This PR updates the dynamiclistener dependency to the latest ~commit of v0.3.1~ release in order to pick up the following change: https://github.com/rancher/dynamiclistener/pull/49
Create a Rancher deployment with a `server_url` setting that is longer than 63 characters.
Deployed a Rancher instance internally that is frontend by an ELB.
_TBD_ …
=> update dynamiclistener to released v0.3.3

pkg/controllers/management/auth/crtb_handler.go
Snapshots get stored in the local cluster under the `fleet-default`
namespace. Because of this, roles get access to individual
snapshots. If no snapshots are stored, the users do
not have access to view or create snapshots in the UI.
Users now have access to the `etcdsnapshots.rke.cattle.io`
in the namespace of the cluster. Making the CRD visible in
the schema when no snapshots are present.
#37630
=> Fixed snapshot RBAC for RKE2 cluster-owner

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/37639
Removed retry logic for etcd snapshot from rancher, as it will be implemented in rke-tools and controlled from rke.
Depends on https://github.com/rancher/rke-tools/pull/153 and subsequent KDM update, and then https://github.com/rancher/rke/pull/2952.
=> Migrate etcdbackup retry from rancher to rke

pkg/data/management/kontainerdriver_data.go
This change updates the Linode Kubernetes Engine cluster driver to `v0.0.6`. This version introduces some stability improvements (retries to significantly reduce provisioning failures) and a nullable `HighAvailability` create/update field. 
Specifically, intermittent K8s polling connection issues now triggers a retry within the driver rather than throwing an error to Rancher.
`v0.0.4` -> `v0.0.6` contains no breaking changes.
Thanks in advance! 🙂 
https://github.com/rancher/rancher/issues/38120
=> Bump kontainer-engine-driver-lke v0.0.4 -> v0.0.6

scripts/run
When running provisioning tests in Drone, the harvester node driver binary is not available and causes errors to be thrown in rancher.
I downloaded the logs from this Drone step https://drone-pr.rancher.io/rancher/rancher/22709/1/2 and then decrypted the base64 logs, showing the error was present 46 times. This is an expected error based on how rancher is run (dev mode) in the provisioning tests and the presence of the errors may confuse those who do not realize this.
```console
for CHUNK in $(grep -A1 LOG-DUMP-START logs_rancher_rancher_22709_1_2.log | grep -v LOG-DUMP); do echo -e "\n---\nSTART LOG DUMP\n---\n"; echo -n "${CHUNK}" | base64 -d | zcat; done | grep 'Driver "harvester" not found' | wc -l
46
```
```log
2022/06/24 21:27:24 [ERROR] error syncing 'harvester': handler …
```
=> disable harvester node driver in drone prov tests

scripts/build-server, scripts/provisioning-tests
**Problem**
We released KDM out of band and RKE v1.3.12 after Rancher v2.6.5. Rancher v2.6.6 is still using RKE v1.3.11 so the local data during build time for v2.6.6 needs to be consistent with RKE v1.3.11 copy. Reference: https://github.com/rancher/rancher/pull/37149 
**Solution**
Pinning KDM data to [release-rke-v1.3.11](https://github.com/rancher/kontainer-driver-metadata/tree/release-rke-v1.3.11) based off of https://github.com/rancher/kontainer-driver-metadata/pull/905. 
**Testing**
Verify the versions from RKE v1.3.12 show up as out of band versions for Rancher v2.6.6 same as v2.6.5: 
https://github.com/rancher/rke/releases/tag/v1.3.12
=> pin kdm data to rke v1.3.11 for v2.6.6

pkg/settings/setting.go
Issue: https://github.com/rancher/rancher/issues/37433
`calico-apiserver` was not present in the list of `CATTLE_SYSTEM_NAMESPACES`
Added `calico-apiserver` to the list of `CATTLE_SYSTEM_NAMESPACES` in `setting.go`. This should be automatically added on upgrade, based on the work done for this issue: https://github.com/rancher/rancher/issues/32898
=> Add calico-apiserver to list of system namespaces

.drone.yml
This is a second attempt at scope drone-publish steps. Previous attempt was reverted in https://github.com/rancher/rancher/pull/37891. It caused not any step to run anymore.
My guess is that the events `pull_request` and `push`/`tag` can't be combined with a `ref include` which scopes to branches/tags, which caused the filter not to apply to `pull_request` (or maybe it did but not to the target branch as that was definitely correct). This separates the events into 2 build steps, one will run based on what event and the scope to branch/tag is done in the build step that triggers on `push`/`tag`.
This also removes the `tag` run for provisioning tests as they have already passed in PRs before and don't need to slow down cutting (pre-)releases.
=> [release/v2.6] Scope drone-publish steps to specific tag/branch

pkg/apis/rke.cattle.io/v1/plan/plan.go, pkg/provisioningv2/rke2/planner/manifests.go, pkg/provisioningv2/rke2/planner/planner.go
This PR adds functionality to allow v2prov to skip the conventional drain/cordon plan update operations, when a plan change is minor. Minor in this case is that the only change in the plan are files that are considered "minor", as designated by the v2prov engineering team. Currently, the two files that are minor are the etcd-metadata and cluster agent manifest files.
https://github.com/rancher/rancher/issues/37465
=> Add minor file support to v2prov to allow for immediate plan updates

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/rke1/nodepools/nodepools.go, tests/v2/validation/provisioning/hosted/hosted_provisioning_test.go, tests/v2/validation/provisioning/rke1/providers.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/config.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/nodeproviders.go, tests/v2/validation/provisioning/rke2/providers.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
**PR Description**
PR addressing enhancements requested in issue https://github.com/rancher/rancher/issues/38135. This PR contains the following enhancements:
- `hosted_provisioning_test.go` is moved out of `rke2` folder and is in a new `hosted` folder
- Fixed spelling errors in the functions as well
- Created constructors for RKE1 cluster creation and node pool creation. These are moved into `clusters.go` and `nodepools.go`, respectively
- Included a standard user to test with, before only admin user was here
- Removed `fmt.println` that was in the code before
- Ensured that `rke1` and `rke2` files each refer to their respective packages. Before, they all just referred to parent package `provisioning`
=> Updates to RKE1 provisioning_node_driver_test.go

pkg/impersonation/impersonation.go
Issue: https://github.com/rancher/rancher/issues/38198 
Problem:
The function waitForServiceAccount checks the length of Secrets on the service account to determine if the service account is ready. 
However, starting from k8s 1.24, there is no service account token secret being auto-generated, so the length is always 0. 
As a result, we see the following error in rancher logs 
```
2022/07/06 03:35:53 [ERROR] error syncing 'p-8mdtt/creator-project-owner': handler cluster-prtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
2022/07/06 03:35:53 [ERROR] error syncing 'c-q69rl/creator-cluster-owner': handler cluster-crtb-sync: couldn't …
```
=> fix the issue that waitForServiceAccount times out  

pkg/auth/data/authconfig_data.go, pkg/auth/providers/azure/azure_actions.go, pkg/auth/providers/azure/azure_provider.go, pkg/auth/providers/azure/config.go
Related to https://github.com/rancher/rancher/issues/29306
UI issue with background: https://github.com/rancher/dashboard/issues/6236
The main problem is as follows: when admins upgrade Rancher to v2.6.7, while having a custom Azure AD endpoint, they will not see the banner in the UI because the UI (and the backend) only checks if the config has one of the two known old endpoints (for Global and China). Therefore, Rancher will assume it needs to use the new authentication flow via Microsoft Graph, since a custom endpoint (by virtue of being able to hold any value) cannot be known to be deprecated. As a result, admins won't even see the warning about the change and, most importantly, a reminder to add the necessary permissions to the app in Azure. This means Rancher will use the new …
=> Make an annotation the only variable in Azure AD auth flow choice

pkg/auth/providerrefresh/refresher.go, pkg/controllers/management/auth/user_attribute_handler.go
In d9ba4df ExtraByProvider was added to UserAttributes and would be
refreshed when a new login token was created. With 4fa4285 the
impersonation code began depending on ExtraByProvider existing in
UserAttributes. However, if the UserAttributes was created before
d9ba4df, it would not have ExtraByProvider unless a new token triggered
adding it, for example by logging out and logging back in. The effect is
that if a Rancher server was created prior to v2.6.2 (prior to d9ba4df)
and then upgraded to v2.6.5 (includes 4fa4285) then users would lose
access to their downstream clusters because the impersonation
clusterrole would be missing the provider extras. This change ensures
that if ExtraByProvider is empty, the refresh is triggered by a
controller instead of waiting for the user to get a …
=> Trigger user attribute refresh for empty extras

go.mod, go.sum
=> Update aws-iam-authenticator to v0.5.9 from Rancher's fork

pkg/agent/cluster/cluster.go, pkg/api/norman/customization/monitor/handler_utils.go, pkg/serviceaccounttoken/secret.go, pkg/tunnelserver/peermanager.go
**Problem**
Peermanager in HA uses token from service account secret on startup. It doesn't error out or complain if the token is empty and uses it as is here https://github.com/rancher/rancher/blob/release/v2.6/pkg/tunnelserver/peermanager.go#L113. This results into cluster not found errors because we cannot find the cluster by token for tunnel authentication. 
```
2022/07/06 03:38:02 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-m-mfhzj6w6: ClusterUnavailable 503: cluster not found, requeuing
2022/07/06 03:39:20 [ERROR] Failed to handle tunnel request from remote address 10.42.1.4:34690 (X-Forwarded-For: 18.224.63.142): response 401: failed authentication
```
**Solution**
Adding wait to not return secret until token …
=> add wait to createSecretForServiceAccount

tests/validation/tests/v3_api/resource/terraform/k3s/master/audit.yaml, tests/validation/tests/v3_api/resource/terraform/k3s/master/cis_masterconfig.yaml, tests/validation/tests/v3_api/resource/terraform/k3s/master/install_k3s_master.sh, tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/k3s/master/join_k3s_master.sh, tests/validation/tests/v3_api/resource/terraform/k3s/master/policy.yaml, tests/validation/tests/v3_api/resource/terraform/k3s/worker/join_k3s_agent.sh
N/A
Automation for K3s hardened installs did not include audit policy. Also, a recent change to the k3s codebase changed the label for required network policies, so it needs to be updated to allow svclb to work in hardened environments.
- Update the network policy applied to k3s in automated tests
- Include audit policy file and args required for the check
I've run this in my local environment to ensure the test runs and works as expected
=> Update k3s hardened install to be in line with docs

pkg/image/export/main.go
Fix for issue: https://github.com/rancher/rancher/issues/37742
There was already a semver version set for rke2 images when building the image lists but there was not one set for k3s images. This change brings the same 1.21+ version restriction for k3s upgrade images for system agent.
To verify this change, once the first rc is generated for Rancher 2.6.6 the list of `rancher/system-agent-installer-k3s` images should not have any versions prior to 1.21 included.
=> introduce version restriction for k3s upgrade images starting with 1.21.0

package/Dockerfile
Updating the csp adapter min version in line with the latest chart version. Needs to go in about the same time as rancher/charts#1970
=> Updating csp adapter min version to 1.0.0-rc3

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go, pkg/controllers/provisioningv2/rke2/plansecret/plansecret.go
https://github.com/rancher/rancher/issues/38304
When using S3 snapshots with RKE2/K3s downstream clusters, it is possible to have S3 objects that have "invalid" snapshot file names. This PR makes a change to the various snapshot handling controllers to allow Rancher to properly handle invalid characters in snapshot file names, and not stall out processing if there are snapshot files that are completely invalid.
Create a v2prov cluster with S3-backed snapshots, and create an object in the bucket/folder with an invalid name, like `cluster-name-c-xx-rs-cwn4m_2022-03-24T20:07:42Z.zip`.
For a freshly provisioned K3s/RKE2 cluster, make sure you "snapshot now" to force K3s/RKE2 to create the corresponding `etcd-snapshots` configmap to backpopulate snapshot data. Once this is done, observe the …
=> Replace all invalid characters for v2prov snapshots with -

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go, pkg/controllers/provisioningv2/rke2/plansecret/plansecret.go, pkg/provisioningv2/rke2/planner/etcdrestore.go
https://github.com/rancher/rancher/issues/38304
https://github.com/rancher/rancher/issues/38338
When restoring an etcd snapshot that is local on a cluster that is S3 enabled, the config mile argument for `--etcd-s3` overrides the snapshot path and causes an issue when doing the restore.
Also, if a snapshot file name had capital letters in it, it was not usable as a snapshot CR name.
When performing a local snapshot restore, set `--etcd-s3=false`
Convert snapshot names to lower case
Perform a snapshot restore from a snapshot that exists locally, on a cluster that is S3 enabled.
Tested a local snapshot restore on an S3 enabled cluster. 
N/A
We should ensure etcd restore continues to work across both S3 and non-S3 clusters for v2prov.
=> Add --etcd-s3=false when restoring a local snapshot and make snapshot CRD names lower case

pkg/controllers/management/secretmigrator/clusters.go
These log messages were appearing very often and will repeat until the service account token is populated for all cluster types.
Moved the log messages to debug.
=> Move credential secret warnings to debug

Dockerfile-windows-1809.dapper, Dockerfile-windows-2004.dapper
default-windows-1809 and 2004 pipelines in Drone use the Go 1.14 version of the toolchain, and we have a 3rd-party package used in release/v2.5 that uses code from the stdlib of Go 1.16. The build fails because Go 1.14 fails to compile that package.
https://drone-pr.rancher.io/rancher/rancher/23039/3/2
=> Update the Go toolchain version for the Windows Drone pipelines

pkg/settings/setting.go
This PR adds a new `ui-performance` setting.
This is required by the frontend to be able to store settings that will enable/configuration new settings in the UI that will allow users to customise certain behaviours in the UI, typically when there are large amounts of resources.
=> Add ui-performance setting to toggle performance settings in the UI

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/image/external/external_test.go
The fleet API packages used were 10 months old and the dependencies far older than that.
This updates to the latest fleet API package which has up to date dependencies.
=> Fleet update to 0.3.10-rc5

pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go
Encryption key rotation was failing, but looked like it was succeeding. This was caused by an issue where the follower controlplane nodes have the incorrect (previous) status post restart, and because we have already left the `system-agent` space, there was no way to run subsequent plans to ensure that the phase really was correct. Although this issue rights itself rather quickly (as in before the first status check) for specific cluster configurations (i.e. non split-role), for split-role configurations subsequent restarts would exacerbate the issue, creating a long enough gap that the time between verifying the follower nodes and running the next command was not long enough of an interval for all nodes to have the correct (identical) stage. Because failures are not very well reported, …
=> 38277 unable to rotate after rotating once

tests/validation/tests/v3_api/resource/terraform/aks/aks.tf, tests/validation/tests/v3_api/resource/terraform/aks/variables.tf, tests/validation/tests/v3_api/test_create_ha.py
When running the `test_create_ha.py` function in the Python legacy framework, attempting to run the function while specifying an AKS cluster failed. The failure would include the following error:
```
[WARNING]: error: b'\nError: Unsupported block type\n\n  on aks.tf line 42, in resource "azurerm_kubernetes_cluster" "default":\n  42:   role_based_access_control {\n\nBlocks of type "role_based_access_control" are not expected here.\n\nError: Unsupported block type\n\n  on aks.tf line 46, in resource "azurerm_kubernetes_cluster" "default":\n  46:   addon_profile {\n\nBlocks of type "addon_profile" are not expected here.\n'
(1, '', '\nError: Unsupported block type\n\n  on aks.tf line 42, in resource "azurerm_kubernetes_cluster" "default":\n  42:   role_based_access_control {\n\nBlocks of type …
```
=> Remove deprecated blocks and update service_principal in `test_create_ha.py` test

Dockerfile.dapper, scripts/check-chart-kdm-source-values, scripts/create-components-file.sh
One of the first steps in the current release process is to check the charts/KDM sources, and if they are set correctly based on if its a regular RC or the final RC. We implemented a script to change these values, but we still have to manually check the values that are set. This script can be run as a replacement of that step. Without `RELEASE_TYPE` set, it will show the values (and this will be used in the `rancher-components.txt` file).
`RELEASE_TYPE` can be `rc` or `final-rc` and will check if the values are correct based on this.
This PR results in current `release/v2.6` in the following `rancher-components.txt` file content:
```
rancher/rancher-webhook v0.2.6-rc3
RANCHER_WEBHOOK_MIN_VERSION 1.0.5+up0.2.6-rc3
v1.18.20-rancher1-3
v1.19.16-rancher1-5
v1.20.15-rancher1-3 …
```
=> [release/v2.6] Add script to show/check rc/final-rc chart/kdm src

Dockerfile.dapper, Makefile, docs/release.md, scripts/list-gomod-updates, scripts/post-release-checks
* Adds script to show Go modules updates from `rancher`
* Adds script to do post release checks, also added a distinction between check actions and actual builds. This will cause `dapper` to be run using `-q --no-out` to have a clearer output from the checks.
* Adds release steps into `docs/` folder, this should be the foundation of keeping changes in the repository and when something was changed/automated
=> [release/v2.6] Add release docs

pkg/settings/setting.go
The setting name was misleading
Update the name.
Verify endpoints are available for the new name.
=> Changes setting name for kubeconfig TTL.

tests/validation/tests/v3_api/test_bkp_restore_s3_recover.py, tests/validation/tests/v3_api/test_bkp_restore_s3_with_creds.py, tests/validation/tests/v3_api/test_bkp_restore_s3_with_iam.py, tests/validation/tests/v3_api/test_cluster_templates.py
test_bkp_restore_s3_with_creds
test_bkp_restore_s3_with_iam
Above mentioned tests were failing due to wrong endpoint for s3 bucket, hence updated the s3 bucket endpoint to correct one.
=> update s3 bucket endpoint

scripts/ci, scripts/only-ui-bumps.sh, scripts/provisioning-tests, scripts/provisioning-tests-rke
We now have a workflow to bump environment variable values automatically, so we can tie tagging a UI or dashboard release to creating a PR in `rancher/rancher`. The idea was to skip CI for those PRs because it takes a lot of time and it makes no sense to build the whole thing for a bump of UI or dashboard. But it seems that skipping CI will not kick off a Drone build (which is expected) but GitHub has Drone check marked as required so it will set the state to `Expected` but it will never get a response from Drone as the build is not kicked off.
To still be able to save time, I added a script that checks if we are only bumping UI or dashboard and skip time consuming scripts that are not needed in this case. Although this doesn't save time for tagging (we need to figure that out next), at …
=> [release/v2.6] Add script to check if to skip CI for UI bumps

tests/validation/tests/v3_api/test_configmaps.py
Below test related to `test_configmaps` fails in the `rancher-v3_additional_tests` job:
- test_cmap_create_single_ns_env_variable
- test_cmap_edit_single_ns
The tests fails because of the deprecated field:
```
rancher.ApiError: (ApiError(...), 'InvalidBodyContent : field `environmentFrom` is deprecated, please use Kubernetes native fields `env` and `valueFrom` for the container\'s environment variables\n\t{\'baseType\': \'error\', \'code\': \'InvalidBodyContent\', \'message\': "field `environmentFrom` is deprecated, please use Kubernetes native fields `env` and `valueFrom` for the container\'s environment variables", \'status\': 422, \'type\': \'error\'}')
```
- Updated the environmentFrom field to envFrom.
=> Add fix for configmap related flaky tests

tests/framework/pkg/nodes/nodes.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go
Changed func ExecuteCommand to use session.Output instead of session.Run so we can also get an output of the command executed.
=> Changed func ExecuteCommand to use session.Output

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/rke1/nodepools/nodepools.go, tests/v2/validation/provisioning/README.md, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/hosted/hosted_provisioning_test.go, tests/v2/validation/provisioning/rke1/providers.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
[RKE1 cluster cleanup needs to occur before second cluster creation, not after all clusters are created](https://github.com/rancher/qa-tasks/issues/452)
[rke1/provisioning_node_driver_test.go should add test cases to allow cluster creation and distribute roles amongst three nodes](https://github.com/rancher/qa-tasks/issues/453)
**Problem 1**
The `rke1/provisioning_ node_driver_test.go` test case had an issue where all of the clusters would be deleted AFTER all of the clusters were provisioned. This is incorrect behavior and we want clusters to clean up immediately after they are successfully provisioned.
This is the behavior the `rke2/provisioning_node_driver_test.go` exhibits, so we should ensure parity.
**Problem 2**
Before this PR, the RKE1 `provisioning_node_driver_test.go` would not …
=> Refactor RKE1 cluster cleanup and support static/dynamic nodepools

.drone.yml, scripts/check-release-images-exist
We've had a few occurrences of missing images, and adding this check will make sure that each (pre) release, we will check the existence of at least the manifest of the image, it will not guarantee all the architectures are present but thats "automatically" handled by https://github.com/rancher/image-mirror/.
This is added as last step so it does not delay the (pre) release as it will take a while (~ 30 minutes).
When we integrate with Slack, we can send a notification when the release and release artifacts are ready and if there are images missing after its finished checking.
=> [release/v2.6] Check if all container images exist on tag

Dockerfile.dapper, scripts/only-ui-bumps.sh
Initially the check was created to diff against the branch it was being merged into, but after merging, I checked how the repository was cloned (see http://drone-publish.rancher.io/rancher/rancher/8161/1/1) and it seems to clone the repository and then merge the changes onto the branch.
So for this logic to work, we need to diff against the last commit (`HEAD~1`) and use that as the source to see if we can skip. As we don't need the branch check anymore, I changed it to checking for `DRONE_BUILD_EVENT` being `push` or `pull_request`.
For the `push` event, we need to check the before and after commit, and compare those to get the actual diff.
=> [release/v2.6] Check if only UI bumps are in commits to skip CI

scripts/only-ui-bumps.sh
For push, we check out the latest commit which causes the previous commit to be the merged PR which should be enough to use the same logic as with pull-request. I also saw this error;
```
Only package/Dockerfile changes found
fatal: ambiguous argument 'package/Dockerfile': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
Which I can't reproduce but added the separation in there just in case.
=> [release/v2.6] Logic is same for pr and push for CI skip

package/Dockerfile
[Charts PR](https://github.com/rancher/charts/pull/2011)
=> Bump rancher-webhook min version to 0.1.5-rc2

tests/validation/tests/v3_api/common.py
Some tests in the v3_additional_tests_long fails with timeout error.
```
wait_for_backup_to_active
wait_for_app_to_active
```
This PR serves to fix that by changing timeout condition.
`timeout = start + timeout` fixes the timeout error.
=> fix for the failing tests due to timeout

pkg/settings/setting.go, tests/framework/extensions/clusters/import.go, tests/v2/validation/charts/monitoring.go
Update `rancher/shell` version to non-rc `v0.1.18`.
=> Update `rancher/shell` version to non-rc `v0.1.18`

package/Dockerfile
Bump rancher-csp-adapter to non-rc'd version for initial release. 
Depends on rancher/charts#2028
=> Bump rancher-csp-adapter to v1.0.0

Dockerfile.dapper, package/Dockerfile
v1.24.2 k3s cannot run pods on centos 7.9 
https://github.com/rancher/rancher/issues/38610
=> use k3s v1.24.1

pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/management/node/controller.go, scripts/provisioning-tests, scripts/provisioning-tests-rke, tests/integration/pkg/defaults/defaults.go, tests/integration/pkg/nodeconfig/nodeconfig.go, tests/integration/pkg/systemdnode/systemnode.go
The provisioning-tests stopped working at some point for K3s/RKE2. They were disabled in CI, rather than debugged.
This PR fixes the provisioning tests to allow them to work again.
This PR is a continuation of https://github.com/rancher/rancher/pull/38531
=> Reenable provisioning tests

tests/validation/tests/v3_api/test_create_ha.py
N/A
The HA create job is failing for k3s/rke2 due to a recent change that I think this will fix
=> Skip ingress rollout check for k3s/rke2 clusters

tests/framework/extensions/rke1/nodepools/nodepools.go, tests/framework/extensions/rke1/nodetemplates/harvester/create.go, tests/framework/extensions/rke1/nodetemplates/harvester_config.go, tests/framework/extensions/rke1/nodetemplates/nodetemplates.go, tests/v2/validation/provisioning/README.md, tests/v2/validation/provisioning/nodeproviders.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/providers.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
[[RKE1] Add support for Harvester for RKE1 cluster provisioning](https://github.com/rancher/qa-tasks/issues/454)
[[RKE1] Create custom_cluster_test.go test case for RKE1 cluster provisioning](https://github.com/rancher/qa-tasks/issues/456)
As part of the broader effort to have parity between RKE1 and RKE2, there are two additional items that have yet to be implemented:
- Harvester cluster provisioning
- Custom cluster provisioning
Both of these functionalities need to be present to provide additional test coverage, but also to be more on parity with the existing RKE2 tests. This PR addresses both of those and adds the functionality.
For Harvester support, added the following:
- `tests/framework/extensions/rke1/nodetemplates/harvester/create.go`
- …
=> Support RKE1 custom clusters and Harvester provisioning

tests/framework/extensions/nodes/nodes.go
This is a part of getting automation put in for qa-task [462](https://github.com/rancher/qa-tasks/issues/462)
Currently, there is no helper function to get node information and nodeIPs. 
Creating a helper function to get node information and get nodeIPs would help improve testing and also expand testing.
- GetNodes() will return a list of nodes corev1.Node
- GetNodeIP() will return node IP list. User will have to pass which address type they want such as External IP, Internal IP, etc.
Manual Testing on local machine was done. Automated testing was not done because I would have to also change another file to add these helper functions into already existing tests. This PR will allow me to move onto getting ssh keys qa-task [462](https://github.com/rancher/qa-tasks/issues/462)
=> Add helper function to get node information and also get nodeIPs

tests/validation/tests/v3_api/resource/aks_nlb.yml, tests/validation/tests/v3_api/resource/eks_nlb.yml
[Fix AKS and EKS local cluster failures in the rancher-v3_ha_deploy Jenkins job](https://github.com/rancher/qa-tasks/issues/473
) 
When specifying AKS or EKS as the local cluster to have a hosted Rancher setup, this fails with internal Jenkins job. GKE, however, succeeds fine without issues. Specifically, the AKS and EKS clusters do provision successfully, but they do not stand up Rancher.
Looking deeper into it, the culprit was that the networking was outdated. GKE works because it uses updated Ingress versions as well as other manifests.
Copying the `gke_nlb.yml` into both `aks_nlb.yml` and `eks_nlb.yml` resolves this issue. Looking at each provider's respective `nlb.yml` file, there were no differences; they were exactly identical to one another. As such, I have done the same here.
If …
=> Update aks_nlb.yml and eks_nlb.yml to fix AKS and EKS local clusters in Jenkins job

tests/validation/tests/v3_api/common.py
As per the analysis mentioned on the confluence page, **rancher-v3_ontag_az_certification** job fails to remove all the resources created for the testing. 
Made changes in the timeout parameter.
This PR serves the purpose to fix this issue.
=> increase timeout

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/users/passwordgenerator/passwordgenerator.go, tests/v2/validation/provisioning/hosted/hosted_provisioning_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
[Create test to check if serviceAccountTokenSecret parameter appears in cluster's YAML](https://github.com/rancher/qa-tasks/issues/458)
[Update tests to have standard user passwords generated](https://github.com/rancher/rancher/issues/38659
) 
**Problem 1**
Per the release of 2.6.7, we introduced new parameter `serviceAccountTokenSecret`. This is because previously when looking in a cluster's YAML, the `serviceAccountToken` was fully exposed. Depending on the RBAC, this could be a potential security vulnerability, so `serviceAccountTokenSecret` abstracts the token completely.
As a result, there is a need in our automation to verify that when we provision any cluster that we also check that `serviceAccountTokenSecret` not only exists in the cluster's YAML, but that we verify exactly what …
=> Check if serviceAccountTokenSecret exists and remove hardcoded passwords

package/Dockerfile, pkg/settings/setting.go, scripts/package
Modifies Rancher in this particular release/v2.6.8 branch to use https://github.com/rancher/charts/tree/release-v2.6.8 as the release branch. 
This PR will later be reverted once release/v2.6.8 is merged into release/v2.6.
=> Point charts to release-v2.6.8 branch

tests/validation/tests/v3_api/common.py
After changes in timeout parameter the wait_for_app_to_active test kept running for many hours. Hence this PR serves to refactor those changes. The changes do not affect any other test.
=> refactoring of timeout change for app_to_active.

tests/validation/lib/aws.py
Task:
https://github.com/rancher/rancher/issues/36273
The goal is to use a security group that has only the Rancher documented network ports for the infrastructure.
This PR attempts to change the current open-all to the new JenkinsCommonPorts
Tested with the create HA 
Jenkins jobs updates here: https://github.com/rancherlabs/jenkins-job-builder/pull/148
=> [Automation] - Use the new SG id which use documented Rancher network ports

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Bump EKS operator to v1.1.5-rc1 to incorporate fix for EKS security group regression and AWS SDK bump to 1.44 which fixes https://github.com/rancher/rancher/issues/38698.
=> Bump eks operator to v1.1.5-rc1

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
https://github.com/rancher/qa-tasks/issues/429 tackling in 2 sets (one in fixes, another in adding rke2)
ontag was broken. 
We are removing GKE for now. Some other fixes include a check in the jenkinsfile for 2.5 or 2.6, and setting versions to run based on the rancher version. This will allow the user to set RKE_VERSION and RANCHER_K3S_VERSION, as well as has some defaults set in jenkinsfile for 2.5 and 2.6. 
Tested in jenkins, will send runs separately.
=> Removing GKE from OnTag. Add rules for 2.5 v. 2.6.

scripts/build-server
**Problem**
------ 
Local data in rancher needs to be consistent with vendored RKE1 data. Refer to https://github.com/rancher/rancher/issues/37088 for more details. This is handled by our release process for normal release tags but not patch releases which are tagged adhoc. 
**Solution** 
------ 
Pinning KDM data for patch releases. Setting it to v1.3.13, because v2.6.8 uses v1.3.13 and we want the behavior to remain the same as v2.6.8. Similar pattern as https://github.com/rancher/rancher/pull/37149
=> pin kdm data for v2.6.8 patch releases

pkg/controllers/management/auth/crtb_handler.go, pkg/controllers/management/auth/manager.go, pkg/controllers/management/auth/manager_test.go, pkg/controllers/management/auth/prtb_handler.go, pkg/controllers/managementuser/rbac/crtb_handler.go, pkg/controllers/managementuser/rbac/handler_base.go, pkg/controllers/managementuser/rbac/handler_base_test.go, pkg/controllers/managementuser/rbac/namespace_handler.go, pkg/controllers/managementuser/rbac/prtb_handler.go, pkg/controllers/managementuser/rbac/roletemplate_handler.go
This is in addition to the validation done in #38419
#38419
Roles referencing a role that references the first role cause a stack overflow when attempting to gather all the roles related to the role.
Track how many time the function has recursed. At the soft-limit of 100, a warning is logged. The upper limit originally discussed was 1000, but that still caused a stack overflow before reaching that limit so I've lowered it to 500.
Created a roletemplate and used it to on a user. Got the expected output.
=> Prevent circular role inheretance causing a crash

pkg/data/management/machinedriver_data.go
Hello Rancher team,
As part of a series of PR to support [Outscale](https://fr.outscale.com/) as a cloud provider:
- quickstart: https://github.com/rancher/quickstart/pull/207
- docs: https://github.com/rancher/docs/pull/4138
Here is our contribution to add node driver information into the rancher server.
Best regards,
Maxime
Ref: https://github.com/rancher/rancher/issues/37886
=> Add Outscale Node driver into Rancher

tests/framework/clients/rancher/generated/management/v3/zz_generated_aci_network_provider.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_catalog.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_catalog_secrets.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_catalog_spec.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_cluster.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_cluster_catalog.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_cluster_secrets.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_cluster_spec.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_cluster_spec_base.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_project_catalog.go, tests/framework/clients/rancher/generated/provisioning/v1/zz_generated_duration.go, tests/framework/pkg/schemas/provisioning.cattle.io/v1/schema.go
When the structs for the v1 Provisioning client were generated, Duration was coming up as empty struct. This was because of the original struct was using protobuf instead of json to unmarshall the API response.
When using the provisioning to do a get or list, it would return an unmarshall error. 
Fixed the order of importing the appropriate structs. Also included some v3 updates, as the generation code is all together.
Locally provisioned a cluster, and did a list call.
=> Fixed Duration Struct in the Generated V1 Provisioning Client

tests/framework/extensions/charts/charts.go, tests/framework/extensions/charts/rancherlogging.go, tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/ingresses/create.go, tests/framework/extensions/ingresses/ingresses.go, tests/framework/extensions/ingresses/list.go, tests/framework/extensions/namespaces/create.go, tests/framework/extensions/namespaces/list.go, tests/framework/extensions/namespaces/namespaces.go, tests/framework/extensions/projects/projects.go, tests/framework/extensions/secrets/create.go, tests/framework/extensions/secrets/list.go, tests/framework/extensions/secrets/secrets.go, tests/framework/extensions/services/create.go, tests/framework/extensions/workloads/daemonsets/list.go, tests/framework/extensions/workloads/deployments/list.go, tests/v2/validation/charts/istio_test.go, tests/v2/validation/charts/monitoring_test.go
- Implemented:
- Rancher logging v2 chart installation and its options as a struct
- Cluster name getter with the given cluster id
- Create & list ingress and a getter to get a specific ingress with the given name
- List namespaces, secrets, daemon sets, and deployments
- Refactored:
- If the `extensions/resource/resources.go` has a helper (such as a getter on top of the list call) move the resource creations to `extensions/resource/create.go`.
- Lists return <ResourceList> struct that contains a slice of the resource, and that struct can be used to add further methods such as `Names`
- `ByName` postfix changes all getters if they use the resource name.
- Refactored:
- Monitoring v2 secret getter rename
- Istio list looping since the list return …
=> Extend workload extension helpers for the validation tests

pkg/auth/audit/audit.go, pkg/auth/audit/audit_test.go, pkg/auth/audit/filter.go, pkg/auth/audit/logwriter.go, pkg/rancher/rancher.go
The audit logger silently fails when attempting to marshal gzip data to JSON.
The audit logger should decode encoded response messages and log errors to Rancher.
=> Adds decompression and error handling to the audit logger.

tests/framework/clients/rancher/client.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_bootstrap.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_client.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_cluster.x-k8s.io.machine.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_condition.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_duration.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_machine_address.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_machine_spec.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_machine_status.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_node_system_info.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_object_meta.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_object_reference.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_owner_reference.go, tests/framework/codegen/main.go, tests/framework/extensions/sshkeys/downloadsshkeys.go, tests/framework/pkg/schemas/cluster.x-k8s.io.machines/v1beta1/mapper.go, tests/framework/pkg/schemas/cluster.x-k8s.io.machines/v1beta1/schema.go, tests/framework/pkg/schemas/provisioning.cattle.io/v1/types.go
Needed to add support to the automation framework to be able to download ssh keys from a specific machine pool node on rancher.
I generated the cluster.x-k8s.io client, and also implemented a helper to download the private ssh key from the machine pool node.
=> Generated the new cluster.x-k8s.io client

tests/validation/tests/v3_api/test_node_annotation.py
Following test cases fails from the `rancher-v3_additional_tests` jenkins job
- test_node_annotation.test_rbac_node_annotation_add_kubectl[project-owner]
- test_node_annotation.test_rbac_node_annotation_delete_kubectl[project-owner]
- test_node_annotation.test_rbac_node_annotation_edit_kubectl[project-owner]
The assert condition for `project-owner` role was incorrect, hence during adding, editing and deleting the node annotation it was failing.
- Below is the assert error in jenkins logs:
`assert 'cannot get resource "nodes"' in 'Error from server (Forbidden): nodes "ip-<REDACTED>" is forbidden: User "u-jc7q7" cannot patch resource "nodes" in API group "" at the cluster scope\n'`
- When the role is project-owner the kubectl command fails for patch operation and not for the get operation. …
=> Add fix for test_node_annotation flaky tests

tests/validation/tests/v3_api/test_nfs.py
Below test fails from the `rancher-v3_additional_tests` jenkins job:
- test_nfs.test_nfs_wl_upgrade
It was failing due the k8s deprecated field. Logs from the jenkins job:
`rancher.ApiError: (ApiError(...), 'InvalidBodyContent : field `environment` is deprecated, please use Kubernetes native field `env` for the container\'s environment variables\n\t{\'baseType\': \'error\', \'code\': \'InvalidBodyContent\', \'message\': "field `environment` is deprecated, please use Kubernetes native field `env` for the container\'s environment variables", \'status\': 422, \'type\': \'error\'}')`
Updated the `environment` field to `env`.
=> Add fix for test_nfs flaky test

pkg/auth/providers/azure/azure_actions.go, pkg/auth/providers/azure/azure_provider.go, pkg/auth/providers/azure/azure_provider_test.go, pkg/auth/providers/azure/clients/ms_graph_client.go
Issue: https://github.com/rancher/rancher/issues/38753
This addresses a corner case where the auth config is enabled but is re-registered (by Editing it in the UI).
Rancher now properly parses the annotations sent from the UI and correctly decides when to use the new auth flow.
=> Properly parse annotations from UI when admins edit Auth Config in the UI

pkg/controllers/management/secretmigrator/clusters.go, pkg/controllers/management/secretmigrator/clusters_test.go
https://github.com/rancher/rancher/issues/38699
Previously, there were a few problems with how objects were being passed and used. Conditions were being set on clusters, but the change was not committed with a client Update call.
A Do function would pass in one pointer but then return a different pointer value pointing to a more updated cluster object. The code would then proceed to use the outdated object. This would cause the service account token secret migration update to fail here: https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/secretmigrator/clusters.go#L661. This was not a problem for some types of clusters like AKSV2 clusters because there is redundant code for migrating the service account token in their respective sync handlers and the migration …
=> Fix migrator

tests/validation/tests/v3_api/resource/squid/squid.conf, tests/validation/tests/v3_api/test_proxy.py
https://github.com/rancher/qa-tasks/issues/486
our proxy was not allowing downstream node driver clusters to be created. This was due to missing parameters in the squid.conf 
We also were lacking parameters for a specific use case, where a rancher setup is behind proxy with downstream nodes behind a proxy (see https://github.com/rancher/rancher/issues/37295#issuecomment-1111380535 for more details on the use case)
* added new rules to squid.conf to open ports for node driver clusters
* added new parameter that appends to NO_PROXY if specified. This should allow for testing the proxy/airgap use case.
see offline link for more details. Tested with and without the CIDR override setting. Also have supporting jenkinsjob PR ready.
=> Updating proxy to allow node driver provisioning

pkg/settings/setting.go
Issue: https://github.com/rancher/dashboard/issues/4109
Required by PR https://github.com/rancher/dashboard/pull/6794
- This supports step 3 from https://github.com/rancher/dashboard/issues/4109#issuecomment-1239387071
- The dashboard will load the harvester ui plugin contained in the harvester cluster, except when the cluster does not contain one (aka legacy clusters)
- For those cases the dashboard will fall back on one that the dashboard itself contains
- However to support QA testing pre-release updates to this plugin... we need to supply an override referring to the `-head` build of the package
- Add a new setting to supply the build
> This is the same pattern as `UI_INDEX` / `UI_DASHBOARD_INDEX` and QA validation of pre-released UI features
>  This is only required for legacy …
=> Add new `ui-dashboard-harvester-legacy-plugin` setting to support Harvester UI Plugin work

pkg/controllers/managementuser/rbac/handler_base.go
Previous logging would result in a lot of logs when a recursive role was encountered. Addressing re-opening of https://github.com/rancher/rancher/issues/38419
Logging and errors resulting from circular roles fills up logs.
The error gets wrapped before returning in a recursive function.
Just return the error.
Debug and printed err to confirm it is no longer a big string.
n/a
=> Fixes circular roles prevention filling up logs

pkg/controllers/management/auth/manager.go, pkg/controllers/management/authprovisioningv2/authprovisioningv2.go, pkg/controllers/management/authprovisioningv2/crtb.go, pkg/controllers/management/authprovisioningv2/mocks_test.go, pkg/controllers/management/authprovisioningv2/prtb.go, pkg/controllers/management/authprovisioningv2/role.go, pkg/controllers/management/authprovisioningv2/role_test.go
https://github.com/rancher/rancher/issues/36072
Cluster role was being deleted before the cluster was fully deleted, leading to the final signal not being sent to the frontend saying the cluster was deleted.
Added an OnRemove handler for the cluster role and cluster binding which re-queues the deletion of the role and binding until the cluster is fully deleted.
Follow repro steps in issue.
Adding tests
=> Added OnRemove bindings and annotations

Dockerfile.dapper, go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum, pkg/settings/setting.go, scripts/package
Updating the dependencies in rancher/rancher after branches for v2.7 are created.
Versions for UI, DASHBOARD and CLI will be the same as 2.6 until new releases are made to these
Updated RKE to latest release  v1.3.14
=> Update dependencies after branching for v2.7

pkg/controllers/management/node/cleanup.go, pkg/controllers/management/node/cleanup_test.go, pkg/controllers/management/node/controller.go, pkg/controllers/managementuser/nodesyncer/nodessyncer.go, pkg/nodeconfig/config.go
The `user-node-remove` handler has been removed, but the finalizer is not being cleaned up.
If the node-controller finalizer has already run for the node (or was never present in the first place), the remove handler won't run again. Because of this, we need to add sync back, but ignore the annotation if the object is already being deleted.
I tested by setting the finalizer on the object, on a previous version of rancher, deleting the node, then upgrading, which caused the finalizer to be removed correctly.
=> Add sync back to check for user-node-remove, add tests

chart/templates/deployment.yaml, chart/values.yaml
This PR adds priorityClassName option to rancher helm chart.
By default it will be set to `system-node-critical`. 
This is needed to avoid eviction.
=> Add priorityClassName to avoid eviction

package/entrypoint.sh
Adding script to entrypoint per https://github.com/rancher/rancher/issues/36238#issuecomment-1222658982 to support cgroups v2. This will allow running docker install out of the box without user changes. 
Issue: 
https://github.com/rancher/rancher/issues/36238
=> [v2.7] add cgroupv2 script for k3s

tests/validation/tests/v3_api/resource/terraform/aks/aks.tf
With previous changes done to the `aks.tf` file, RBAC was not defined to be set to true. As per the AKS documentation, we should ensure that it is enabled to follow best practices.
Added `role_based_access_control_enabled` parameter to ensure that RBAC is set to true.
Locally tested that a Rancher server is stood up with AKS as the local cluster. Once done, provisioned an RKE1 cluster and validated that came up successfully.
=> Add role_based_access_control_enabled to AKS

pkg/settings/setting.go, pkg/settings/setting_test.go
SUSE/Rancher needs the ability to set the default registry to pull images from. This is separate from the user setting so that user settings (especially from charts) do not overwrite this default value.
Add a new environment variable that's the default value for the CATTLE_SYSTEM_DEFAULT_REGISTRY
N/A
An automated test was added to ensure the default value for the system default registry is the same as it was before the change when the new environment variable is not set.
No test was added for when the new environment variable was set because I didn't see a good way to inject it into the current test setup. Pointers welcome if there is a good place to do this.
Testing this on a new install and an upgrade would be useful. An upgrade where CATTLE_BASE_REGISTRY starts as "" and moves to a …
=> Adding environment variable for SUSE to set base registry

Dockerfile.dapper, package/Dockerfile, pkg/controllers/provisioningv2/rke2/bootstrap/controller.go, pkg/provisioningv2/rke2/configserver/server.go, pkg/serviceaccounttoken/secret.go, scripts/provisioning-tests
With K8s v1.24+, service account tokens are now created by Rancher if they do not exist (as the token-controller no longer automatically creates service account tokens). Before this PR, Rancher would open a watch for service accounts, relying on the `.secrets` field of the service account to contain the service account token (as this was populated by the token-controller). The secrets field is no longer populated, so opening a watch for service accounts is no longer a valid approach for waiting for service account token.
Now, Rancher will watch for the service account, then once it finds a valid service account, open a watch for secrets that specifically correspond to the service account.
Create a v2prov custom cluster in v2.6.8, and observe that running the curl script takes 60+ seconds …
=> [release/v2.6] Add specific watch for secrets in rke2configserver to ensure v2prov provisioning timeliness, Bump embedded K3s to v1.24.4+k3s1

pkg/controllers/management/aks/aks_cluster_handler.go
Rancher was panicking when attempting to access a field from `cluster.Status.AKSStatus.UpstreamSpec`, because `UpstreamSpec` was nil.
Add a nil check. Although this isn't reproducible in isolation, it is reproducible by either deleting the UpstreamSpec from the management cluster and letting it reconcile (which I haven't tested personally and can't confirm other side effects), or by stopping rancher immediately after the cluster is created (which I have confirmed works).
Manually forced fields to be nil (that shouldn't be, but otherwise shouldn't cause rancher to panic).
=> [release/v2.7] Reenqueue aks cluster if upstream spec is nil

pkg/controllers/management/aks/aks_cluster_handler.go
Rancher was panicking when attempting to access a field from `cluster.Status.AKSStatus.UpstreamSpec`, because `UpstreamSpec` was nil.
Add a nil check. Although this isn't reproducible in isolation, it is reproducible by either deleting the UpstreamSpec from the management cluster and letting it reconcile (which I haven't tested personally and can't confirm other side effects), or by stopping rancher immediately after the cluster is created (which I have confirmed works).
Manually forced fields to be nil (that shouldn't be, but otherwise shouldn't cause rancher to panic).
=> [release/v2.6] Reenqueue aks cluster if upstream spec is nil

Dockerfile.dapper, package/Dockerfile
The CI system regularly has flakes. The underlying error reads:
> machine_test.go:552: Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": EOF
This can come at various times during the k3s provisioning tests.
The k3s project has an issue for it at https://github.com/k3s-io/k3s/issues/5835
We have been running k3s 1.24.1. Since that time there have been fixes to the egress selector mode. That issue notes that disabling the egress selector mode or trying to update to a newer k3s may fix the problem. In the release notes for k3s it notes they have fixed bugs around this.
This PR updates the version of k3s to 1.24.4.
It passed in CI.
=> [release/v2.7] Incrementing the version of k3s to the latest 1.24.x

pkg/controllers/management/drivers/nodedriver/machine_driver.go
https://github.com/rancher/rancher/issues/38901
In certain cases, it is possible to have Rancher panic due to the `machine_driver.go` controller, as it unsafely mutates objects returned from the cache.
DeepCopy the object before allowing mutation.
N/A
=> [release/v2.6] DeepCopy nodeSchema after listing from cache

pkg/multiclustermanager/routes.go, pkg/version/version.go, pkg/version/version_test.go
Expose the rancher version as an unauthenticated endpoint on
/rancherversion. This now includes a flag indicating whether the build
version is Rancher "plus" or not. The version and "plus" indicator is
set at build time and cannot be overridden by an environment variable at
run time. The endpoint is /rancherversion instead of /version because
the /version endpoint is just passed through to kubernetes and gives the
local cluster kubernetes version. The endpoint is unauthenticated rather
than authenticated because the k8s /version is already exposed[1] as
well as the /v1-{k3s,rke2}-release/* endpoints, so security through
obscurity doesn't buy us much here.
[1] https://github.com/kubernetes/kubernetes/issues/84040
https://github.com/rancher/rancher/issues/38554
=> Expose rancher version endpoint

pkg/auth/providerrefresh/refresher.go, pkg/auth/providerrefresh/refresher_test.go, pkg/auth/providers/providers.go, pkg/auth/tokens/test_utils.go
If a user has no fresh UI login tokens, they may still need to log in using a kubeconfig or API token. Without this change, if the provider refresher happens to have run, ExtraByProvider will become empty, which will cause requests to fail because the impersonation logic depends on extras found in UserAttributes. This change ensures that extras are refreshed either from login tokens or derived tokens, as long as the user still has access to the provider.
The problem this PR addresses is that the refresher may set the `ExtraByProvider` field in a `UserAttribute` resource to empty, `{}`. if the user has no active login tokens. Login tokens come from logging into the UI, but some users rarely or never log into the UI, for example automated Jenkins or Terraform users. Impersonation uses …
=> Refresh ExtrasByProvider from derived tokens

pkg/client/generated/management/v3/zz_generated_cluster.go
This `go generate` change was supposed to be part of https://github.com/rancher/rancher/pull/38738 but was missed to be pushed along with that PR. 
Linked issue: https://github.com/rancher/rancher/issues/37322
=> Add missing go generate changes.

pkg/settings/setting.go
https://github.com/rancher/dashboard/issues/6294
Related dashboard PR: https://github.com/rancher/dashboard/pull/6720
`ui-issues` is deprecated use `ui-custom-links` instead
=> Update support page and enable custom links

tests/v2/validation/Dockerfile.validation
Validation tests' Docker is about to become outdated, as following this #38960:
This PR contains the version update and an update to the gotestsum installation for the validation test environments.
=> [release/v2.6] Update validation tests' Dockerfile to use Go 1.19

pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/store.go, pkg/provisioningv2/rke2/planner/store_test.go
The join URL that control plane nodes would use to join a cluster would always be an ipv4 address, scraped from the etcd leader. The join URL that worker nodes would use would instead be the first controlplane node's last `InternalIP` address (or `ExternalIP` if no suitable `InternalIP` is found) as shown in it's status, like so:
```
status:
addresses:
- address: 165.227.189.32
type: InternalIP
- address: 2604:a880:800:10::7c6:7001
type: InternalIP
- address: jhyde-rke2-test-controlplane-838bba1c-8fhkh
type: Hostname
```
In this case, the ipv6 address was being used, but it was being rendered as `https://2604:a880:800:10::7c6:7001:9345`, with `9345` being appended as the port. This is an invalid URL, as ipv6 hosts must be enclosed with `[]` like so: …
=> [release/v2.7] Surround ipv6 address in brackets for join URL

pkg/provisioningv2/rke2/planner/config.go
This is a back-port PR, description is largely copied from original PR. 
System images for RKE2 and K3s clusters were being pulled incorrectly when both a global level private registry and a cluster level private registry are defined. It is expected that all system images will be pulled from the cluster level private registry if it has been defined, however a number of system images for RKE2/K3s are being pulled from the global registry.
Do not pass the --system-default-registry flag if a cluster level registry is defined. This ensures that all image pulls (including system images) first attempt to pull the image from the cluster level private registry (defined within registries.yaml), and if an image is not present there it will attempt to pull from docker hub
1. Create 1 unauthenticated …
=> [v2.6] Ensure RKE2/K3s Pull System Images From Correct Registry

pkg/controllers/management/node/cleanup.go, pkg/controllers/management/node/cleanup_test.go, pkg/controllers/management/node/controller.go, pkg/controllers/managementuser/nodesyncer/nodessyncer.go, pkg/nodeconfig/config.go
The `user-node-remove` handler has been removed, but the finalizer is not being cleaned up.
If the node-controller finalizer has already run for the node (or was never present in the first place), the remove handler won't run again. Because of this, we need to add sync back, but ignore the annotation if the object is already being deleted.
I tested by setting the finalizer on the object, on a previous version of rancher, deleting the node, then upgrading, which caused the finalizer to be removed correctly.
=> [release/v2.6] Add sync back to check for user-node-remove, add tests

pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/store.go, pkg/provisioningv2/rke2/planner/store_test.go
The join URL that control plane nodes would use to join a cluster would always be an ipv4 address, scraped from the etcd leader. The join URL that worker nodes would use would instead be the first controlplane node's last `InternalIP` address (or `ExternalIP` if no suitable `InternalIP` is found) as shown in it's status, like so:
```
status:
addresses:
- address: 165.227.189.32
type: InternalIP
- address: 2604:a880:800:10::7c6:7001
type: InternalIP
- address: jhyde-rke2-test-controlplane-838bba1c-8fhkh
type: Hostname
```
In this case, the ipv6 address was being used, but it was being rendered as `https://2604:a880:800:10::7c6:7001:9345`, with `9345` being appended as the port. This is an invalid URL, as ipv6 hosts must be enclosed with `[]` like so: …
=> [release/v2.6] Surround ipv6 address in brackets for join URL

pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/planner.go
k3s clusters did not have taints applied to etcd/controlplane nodes.
Ensure k3s clusters also have taints applied to also have taints.
Manually tested by provisioning all 7 permutations of node roles:
| etcd               | controlplane       | worker             | node-role.kubernetes.io/control-plane=:NoSchedule | node-role.kubernetes.io/etcd=:NoExecute |
|--------------------|--------------------|--------------------|---------------------------------------------------|-----------------------------------------|
| :heavy_check_mark: |                    |                    |                                                   | :heavy_check_mark:                      |
|                    | :heavy_check_mark: |                    | :heavy_check_mark:                                | …
=> Allow taints to apply to k3s clusters

pkg/controllers/managementuser/nodesyncer/nodessyncer.go
Just want `release/v2.6` and `release/v2.7` to be in line when I merge https://github.com/rancher/rancher/pull/39016, this check didn't do anything useful.
=> Don't check for deletionTimestamp when reconciling machines

pkg/controllers/management/drivers/nodedriver/machine_driver.go
https://github.com/rancher/rancher/issues/38854
In certain cases, it is possible to have Rancher panic due to the `machine_driver.go` controller, as it unsafely mutates objects returned from the cache.
DeepCopy the object before allowing mutation.
N/A
=> [release/v2.7] DeepCopy nodeSchema after listing from cache

pkg/auth/api/user/user_actions.go, pkg/auth/api/user/user_actions_test.go, pkg/auth/api/user/user_store.go
This will also prevent re-use of the existing password on the changepassword action api call.
We now compare the existing password with the proposed new password, if they match, we reject it.
Tried re-using bootstrap password as well as other current password, both rejected as designed.
Added unit test to verify this funcitonality
=> Prevent user from re-using the bootstrap password

package/Dockerfile
=> [2.7] Set the initial version of the CSP Adapter min version 

pkg/auth/providers/azure/azure_actions.go, pkg/auth/providers/azure/azure_provider_test.go, pkg/auth/providers/azure/config.go, pkg/auth/providers/azure/migrate.go
Rancher picks the new auth flow in cases where it should pick the old. Specifically, when admins have a deprecated Azure AD setup in Rancher v2.6.7+ and when they want to simply reconfigure their existing setup (by changing the Application Secret, for example). 
On `testAndApply`, implement the annotation-setting logic so that it behaves in the following way:
Before setting or not setting an annotation on a new auth config, fetch an existing config from the database. Inspect this config.
1. If it is disabled, then use the new auth flow and thus set the annotation on the new config.
2. If it is enabled and has the annotation, also use the new auth flow and thus set the annotation on the new config.
3. If it is enabled and **does not** have the annotation, use the old auth flow and and thus …
=> [release/v2.7] Allow admins to reconfigure existing deprecated Azure AD authconfig

tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_duration.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_machine_spec.go, tests/framework/clients/rancher/generated/provisioning/v1/zz_generated_duration.go, tests/framework/clients/rancher/generated/provisioning/v1/zz_generated_rke_machine_pool.go, tests/framework/pkg/schemas/cluster.x-k8s.io.machines/v1beta1/schema.go, tests/framework/pkg/schemas/provisioning.cattle.io/v1/schema.go, tests/framework/pkg/schemas/provisioning.cattle.io/v1/types.go
Since the native Duration type used to generate the appropriate types for the provisioning and cluster clients, doesn't use a native type, and has `protobuf` tag, it doesn't get generated appropriately and cause unmarshaling errors. 
Updated schemas to change the field types to strings to fix the error.
=> [release/v2.7] Updated fields that previously used Duration to use string, to fix an unmarshaling error

Dockerfile.dapper, package/Dockerfile, pkg/controllers/provisioningv2/rke2/bootstrap/controller.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/provisioningv2/rke2/configserver/server.go, pkg/serviceaccounttoken/secret.go, scripts/provisioning-tests
With K8s v1.24+, service account tokens are now created by Rancher if they do not exist (as the token-controller no longer automatically creates service account tokens). Before this PR, Rancher would open a watch for service accounts, relying on the `.secrets` field of the service account to contain the service account token (as this was populated by the token-controller). The secrets field is no longer populated, so opening a watch for service accounts is no longer a valid approach for waiting for service account token.
Now, Rancher will watch for the service account, then once it finds a valid service account, open a watch for secrets that specifically correspond to the service account.
Create a v2prov custom cluster in v2.6.8, and observe that running the curl script takes 60+ seconds …
=> [release/v2.7] Add specific watch for secrets in rke2configserver to ensure v2prov provisioning timeliness

pkg/settings/setting.go
- `rancher/dashboard` and `rancher/ui` have both now branched for 2.6.9
- This change ensures the `rancher/rancher` 2.6 branch points to the correct builds
- These builds are used, when settings are default, when the version ends in `-head` as an alternative to the embedded builds
=> Update references to new 2.6.9 UI branches

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/rke1/nodepools/nodepools.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
[[RKE1] Scale up/down nodes](https://github.com/rancher/qa-tasks/issues/461)
[In automation framework rke1 extension doesn't use k8's version parameter](https://github.com/rancher/rancher/issues/38961)
**_Problem 1_**
In the test framework, there is currently no scaling tests for RKE1 or RKE2. Scaling is a fundamental Kubernetes operation and it is crucial that we have routine testing for this.
**_Problem 2_**
In the existing `clusters.go`, there was no field to properly set the Kubernetes version; it was left up to the user-defined `cattle-config.yaml` file. This needed to be properly defined.
_**Solution 1**_
`nodepools.go` was modified to include new `ScaleWorkerNodePool` that performs the following:
- Creates new worker node pool
- Increases quantity from 1 to 2 to scale upwards to …
=> [v2.7] Add RKE1 node scaling

pkg/apis/management.cattle.io/v3/cluster_types.go, pkg/client/generated/management/v3/zz_generated_cluster_secrets.go, pkg/cluster/private_registry.go, pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/controllers/management/node/cleanup.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/provisioningv2/image/resolve.go, pkg/provisioningv2/rke2/planner/agent.go, pkg/systemtemplate/import.go
When deploying RKE2/K3s clusters which have a cluster level private registry configured, the cluster agent manifest did not incorporate that registry. Instead, the global system-default-registry was used. This resulted in images created by the cluster agent (namely the `shell` image when creating the `dashboard-shell` container) being pulled from the incorrect registry, which has implications for clusters which only have access to the cluster level registry. This issue is apart of a larger set of issues regarding the use of cluster level private registries and their precedence over the global system-default-registry. 
This issue only occurs with RKE2/K3s clusters.
The location of the private registry details differs between the `v3.Cluster` objects for RKE1 and RKE2/K3s. 
This results in …
=> [2.7] Fix registries within the cluster agent manifest for Prov V2

pkg/controllers/dashboard/fleetcharts/controller.go, pkg/controllers/dashboard/hostedcluster/controller.go, pkg/controllers/dashboard/systemcharts/controller.go
Specifically addresses this comment: https://github.com/rancher/rancher/issues/37927#issuecomment-1263542957
If a user is using rancher via docker, the new rancher-config configMap is not installed causing a warning message when feature charts attempt a lookup on the map. This can fill the logs since feature charts are ensured every 5 minutes.
Only log the error if it is not a NotFound error.
Fresh install rancher via docker.
Wait 5 minutes
Verify that the logs do not contain the message `Failed to get rancher priorityClassName`
=> Reduce logging verbosity when installing feature charts.

tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_duration.go, tests/framework/clients/rancher/generated/cluster/v1beta1/zz_generated_machine_spec.go, tests/framework/clients/rancher/generated/provisioning/v1/zz_generated_duration.go, tests/framework/clients/rancher/generated/provisioning/v1/zz_generated_rke_machine_pool.go, tests/framework/pkg/schemas/cluster.x-k8s.io.machines/v1beta1/schema.go, tests/framework/pkg/schemas/provisioning.cattle.io/v1/schema.go, tests/framework/pkg/schemas/provisioning.cattle.io/v1/types.go
Since the native Duration type used to generate the appropriate types for the provisioning and cluster clients, doesn't use a native type, and has `protobuf` tag, it doesn't get generated appropriately and cause unmarshaling errors. 
Updated schemas to change the field types to strings to fix the error.
=> [release/v2.6] Updated fields that previously used Duration to use string, to fix an unmarshaling error

pkg/clustermanager/manager.go, pkg/controllers/management/node/cleanup.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go, pkg/controllers/managementuser/nodesyncer/nodessyncer.go, pkg/nodeconfig/config.go
If a node is provisioned on <v2.5.1, rancher is stopped, and the node is deleted; Remove will not be called for the node causing orphaned v1.Nodes which default unmanaged v3.Nodes are then created for.
Remove the annotation on sync and v3.Node removal.
Tested with a 1 etcd, 1 controlplane, 1 worker. On upgrade from v2.5.1 to v2.7-head, the node is properly cleaned up.
=> Remove user-node-remove on node remove

Makefile
Dapper is available on the Darwin ARM64 platform since v0.6.0: https://github.com/rancher/dapper/releases/tag/v0.6.0
This PR is to reenable the downloading of dapper on the Darwin ARM64 platform.
=> enable the downloading of dapper on the Darwin ARM64 platform

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/machinepools/machinepools.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/providers.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/cert_rotation_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
As of now, the Go test framework only has test cases for RKE1 and RKE2. As we look towards pushing K3S to become GA, it is only right that we account for that in our testing as well. This includes node drivers and custom clusters, just as we currently do for RKE1 and RKE2.
This PR adds support for K3S provisioning for both node drivers and custom clusters. Essentially, majority of the functionality is taken from RKE2, with the exception that CNI is removed, as K3S does not utilize CNI.
Locally, validated that a 1 node all roles provisions for both the admin and standard user for node provisioned cluster AND custom cluster.
Offline Jenkins jobs will be handed to the reviewers prior to approval of the PR.
=> [v2.7] Add K3S provisioning support for node driver/custom clusters

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/machinepools/machinepools.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/providers.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
As of now, the Go test framework only has test cases for RKE1 and RKE2. As we look towards pushing K3S to become GA, it is only right that we account for that in our testing as well. This includes node drivers and custom clusters, just as we currently do for RKE1 and RKE2.
This PR adds support for K3S provisioning for both node drivers and custom clusters. Essentially, majority of the functionality is taken from RKE2, with the exception that CNI is removed, as K3S does not utilize CNI.
Locally, validated that a 1 node all roles provisions for both the admin and standard user for node provisioned cluster AND custom cluster.
Offline Jenkins jobs will be handed to the reviewers prior to approval of the PR.
=> [v2.6] Add K3S provisioning support for node driver/custom clusters

package/entrypoint.sh
https://github.com/rancher/rancher/issues/39281
=> [v2.6] enable v2 cgroup nesting only for rancher standalone container

package/entrypoint.sh
This PR is forward port PR. Original PR: https://github.com/rancher/rancher/pull/39286
Issue: https://github.com/rancher/rancher/issues/39283
=> [v2.7] enable v2 cgroup nesting only for rancher standalone container

pkg/controllers/management/node/controller.go
Issue: https://github.com/rancher/terraform-provider-rancher2/issues/969
=> Bump rke docker defaultEngineInstallURL to 20.10

pkg/client/generated/management/v3/zz_generated_azure_cloud_provider.go
Running `go generate`  on rancher/rancher is adding the following file since rke version has changed:
modified:   pkg/client/generated/management/v3/zz_generated_azure_cloud_provider.go
=> Adding generated files added after updating rke v1.4.0-rc4

pkg/channelserver/channelserver.go, pkg/settings/setting.go, tests/integration/suite/test_clustertemplate.py, tests/integration/suite/test_kontainer_drivers.py
https://github.com/rancher/rancher/issues/39239
For RKE, RKE1, and K3s, the available versions in the version list are not right when creating a node-drive cluster on **v2.7-head**
- bump the RancherVersionDev to 2.7.99, so that the available k8s versions can be calculated correctly on 2.7-head and the dev build
- fix the server version for rke2/k3s channel server
- fix tests
Built and ran rancher locally and see only the latest  1.23 and 1.24 as the available version for For RKE, RKE1, and K3s
=> [2.7] bump the RancherVersionDev to 2.7.99 

tests/validation/lib/aws.py
Internal automation is currently using Ubuntu 18.04 as default AMIs. While Ubuntu 18.04 is still actively supported and has not reached EOL, we should update the default AMI to use Ubuntu 20.04.
Updated the `aws.py` to use an Ubuntu 20.04 AMI that has been validated to successfully work.
Ran internal automation with updated AMI and each of the tests were successful.
=> [v2.6] Update Ubuntu 18.04 to Ubuntu 20.04

tests/validation/lib/aws.py
Internal automation is currently using Ubuntu 18.04 as default AMIs. While Ubuntu 18.04 is still actively supported and has not reached EOL, we should update the default AMI to use Ubuntu 20.04.
Updated the `aws.py` to use an Ubuntu 20.04 AMI that has been validated to successfully work.
Ran internal automation with updated AMI and each of the tests were successful.
=> [v2.7] Update Ubuntu 18.04 to Ubuntu 20.04

pkg/auth/providers/azure/azure_actions.go, pkg/auth/providers/azure/azure_provider_test.go, pkg/auth/providers/azure/config.go, pkg/auth/providers/azure/migrate.go
Rancher picks the new auth flow in cases where it should pick the old. Specifically, when admins have a deprecated Azure AD setup in Rancher v2.6.7+ and when they want to simply reconfigure their existing setup (by changing the Application Secret, for example). 
On `testAndApply`, implement the annotation-setting logic so that it behaves in the following way:
Before setting or not setting an annotation on a new auth config, fetch an existing config from the database. Inspect this config.
1. If it is disabled, then use the new auth flow and thus set the annotation on the new config.
2. If it is enabled and has the annotation, also use the new auth flow and thus set the annotation on the new config.
3. If it is enabled and **does not** have the annotation, use the old auth flow and and thus …
=> [2.6 backport] Allow admins to reconfigure existing deprecated Azure AD authconfig

tests/v2/validation/provisioning/rke1/README.md, tests/validation/tests/v3_api/resource/airgap/config_yamls/config_body.yaml, tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/k3s/worker/instances_worker.tf, tests/validation/tests/v3_api/resource/terraform/rke2/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/rke2/worker/instances_worker.tf, tests/validation/tests/v3_api/test_upgrade.py
https://github.com/rancher/qa-tasks/issues/505
rke2 clusters in jenkins fail to create when using ubuntu 22.04 but not other (older) versions. 
upon further investigation, this was due to an incompatibility with TF when sshing into 22.04 node(s)
created an elliptic-based ssh key in aws to use. 
tested in jenkins (see thread) and locally
this PR updates _ALL_ jenkins ssh keys to use the new key. This will require an update in jenkins and all engineers using jenkins to acquire the new key.
=> Allow TF to ssh into 22.04 nodes

tests/validation/tests/v3_api/test_create_ha.py
When running the `test_install_rancher_ha` function from `test_create_ha.py`, there is a failure when you attempt to have environment variables `RANCHER_HA_HOSTNAME` and `RANCHER_HA_KUBECONFIG` set and `RANCHER_HA_HARDENED` is set to `True`. To get around this, a workaround is to set `RANCHER_HA_HARDENED` to `False` when these variables are present.
This should not happen and disrupts automation when trying to import an RKE1 cluster with the existing automation.
The variable `rke-cis-1.5` needed to be declared outside of its parental conditionals. This is done so that the variable is always set and not set only in a conditional.
Additionally, there needs to be a new check in the `set_route53_with_ingress` function that looks for `RANCHER_HA_HARDENED.upper() == "TRUE" and …
=> [v2.7] Support RANCHER_HA_HOSTNAME and RANCHER_HA_KUBECONFIG to be set with RANCHER_HA_HARDENED when set to True

tests/validation/tests/v3_api/test_create_ha.py
When running the `test_install_rancher_ha` function from `test_create_ha.py`, there is a failure when you attempt to have environment variables `RANCHER_HA_HOSTNAME` and `RANCHER_HA_KUBECONFIG` set and `RANCHER_HA_HARDENED` is set to `True`. To get around this, a workaround is to set `RANCHER_HA_HARDENED` to `False` when these variables are present.
This should not happen and disrupts automation when trying to import an RKE1 cluster with the existing automation.
The variable `rke-cis-1.5` needed to be declared outside of its parental conditionals. This is done so that the variable is always set and not set only in a conditional.
Additionally, there needs to be a new check in the `set_route53_with_ingress` function that looks for `RANCHER_HA_HARDENED.upper() == "TRUE" and …
=> [v2.6] Support RANCHER_HA_HOSTNAME and RANCHER_HA_KUBECONFIG to be set with RANCHER_HA_HARDENED when set to True

scripts/change-final-rc-values, scripts/check-chart-kdm-source-values
* `scripts/package` variables were changed to `scripts/package-env` in https://github.com/rancher/rancher/pull/39191
* Other `scripts` reference to 2.6 changed to 2.7
=> [release/v2.7] Fix scripts references for 2.7

scripts/provisioning-tests, tests/integration/pkg/nodeconfig/nodeconfig.go, tests/integration/pkg/systemdnode/systemnode.go
* k3s agent setup changed systemd detection in https://github.com/k3s-io/k3s/pull/5851, and the version that gets determined to test in KDM got bumped was bumped to version that includes that fix (backported). This started to fail the tests.
* the system-agent-installer-rke2 image built for the version that got bumped in KDM does not contain all artifacts, so the test would never succeed (rancher-system-agent -> plan -> extract from image -> failing to find checksum file). You can see the curl failures in the build for the image https://drone-publish.rancher.io/rancher/system-agent-installer-rke2/286/1/2
Logs from rancher-system-agent:
```
Nov 02 13:07:21 test-single-node-all-roles-with-delete-pool-0-6aadef12-f9hhh rancher-system-agent[243]: time="2022-11-02T13:07:21Z" level=info …
```
=> [release/v2.7] Set force cgroup env for k3s agent as well

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_custom_host_reg.py
Automation is not using `--privileged` flag when deploying Rancher using Docker because there's no `--privileged` flag
Add Rancher version 2.7 to the Docker Rancher deployment logic
=> [release/v2.7] - Adding 2.7 in the logic to use --privileged with Docker

tests/validation/tests/v3_api/common.py
test_websocket_launch_kubectl was failing with timeout when running with the other tests. 
Increasing the timeout fixed the error.
=> kubectl-websocket-fix

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
ontag jobs were failing due to rules explicit to 2.6 and 2.5 in jenkinsfiles
add an explicit rule to set versions in 2.7
functional test of rke version done in jenkins (did not test jenkinsfile changes themselves)
=> [v2.7] updating ontag to allow v2.7

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_azure_cloud_provider.go
The Azure cloud provider was updated in RKE recently, (https://github.com/rancher/rke/pull/2580), but the recent RC containing the change was not brought into Rancher. This prevents terraform support of this new field.
This PR updates the RKE version used by Rancher to `1.4.0-rc4`, which includes the additional field in the Azure Cloud Provider. `go generate` has been run to update the generated types used by Rancher. This change is needed for terraform support, the goal of #26955 is to provide the ability to add tags to VM instances and supporting infrastructure using both the UI and terraform. 
This bump increases the minor version of RKE1 from `3` to `4`. As far as I can tell this is okay, and haven't seen any issues with it, but let me know if there is a reason why we do not want to …
=> [v2.6] Update RKE & regenerate Azure Cloud-provider

pkg/image/origins.go
The artifact `rancher-image-origins.txt` should match the naming of other artifacts created by rancher 
Update the artifact name to `rancher-images-origins.txt`
new artifact name should be produced on next build of rancher 
ran `dapper ci` and confirmed new artifact name
=> Pluralize rancher-images-origins

chart/templates/deployment.yaml, chart/tests/deployment_test.yaml, chart/values.yaml
Adds values to the chart for rancher server to override the livenessProbe and readinessProbe's initialDelaySeconds and periodSeconds
https://github.com/rancher/rancher/issues/38177
In some situations the liveness probe does not report within the default time, this makes it easier to expand that window.
Added values to the helm chart that override the default values
Added helm tests
=> Add option to override initialDelay and period

tests/integration/pkg/nodeconfig/nodeconfig.go, tests/integration/pkg/systemdnode/systemnode.go
Partial backport of https://github.com/rancher/rancher/pull/39479
We don't need to modify the KDM data as we are leaving KDM to dev-v2.6 on `release/v2.6`
=> [release/v2.6] Set force cgroup env for k3s agent as well

tests/validation/tests/v3_api/test_create_ha.py
For the validation test CI runs, HA cluster creation uses the hardened environment variable as a string, and the condition accepts the hardened option as always true.
**Modified**
- Wrapped `RANCHER_HA_HARDENED` environment variable with `ast.literal.eval()`
- Removed string comparisons related with `RANCHER_HA_HARDENED` environment variable
=> [2.7] Fix hardened cluster environment value in HA creation validation test

tests/validation/tests/v3_api/test_create_ha.py
https://github.com/rancher/qa-tasks/issues/515
currently, rancher helm URL was hard coded. 
This PR will allow different URLs for a rancher install to be used.
Introduced `RANCHER_HELM_URL` variable with previous hardcoded value as the default. 
supporting PR in job builder
=> [v2.7] allow usage of other helm repos to install rancher

package/Dockerfile, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/39456
We need a flag to indicate whether or not a given install is a Rancher Prime install.  It needs to default to an env var that is set in the Dockerfile, but still be able to be set by users if they prefer to use their own branding.
Introduce a new fallback env setting, base-ui-brand (not user-facing) that will pick-up the value of an env var (BASE_UI_BRAND) set by the Dockerfile at build time
Manually tested resultant image to verify that the setting
=> Adding fallback env setting for base-ui-brand

pkg/settings/setting.go
- `rancher/dashboard` and `rancher/ui` have both now branched for 2.7.0
- This change ensures that `rancher/rancher` `release-2.7` branch points to the correct builds
- These builds are used when the version ends in `-head` as an alternative to the embedded builds
> When there's a 2.7.0 branch, or 2.7.0 is released, this PR should be reverted to ensure `release-2.7` (aka 2.7.1+) tracks UI `master` builds again 
=> Update references to new 2.7.0 UI branches

scripts/provisioning-tests
Issue: https://github.com/rancher/rancher/issues/39484
As part of a workaround to get provisioning tests to pass, RKE2 was hard coded to an older version. This PR reverts that change, and also bumps the consumed version of KDM to dev-v2.7
=> Revert rke2 version hardcoding and use KDM dev-v2.7

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Unrc gke operator chart v1.1.5-rc1 -> v1.1.5
AKS and EKS are already unrc
=> Unrc gke operator chart for kev2 v2.7.0

tests/validation/tests/v3_api/test_create_ha.py
https://github.com/rancher/qa-tasks/issues/515
backport of https://github.com/rancher/rancher/pull/39482
currently, rancher helm URL was hard coded. 
This PR will allow different URLs for a rancher install to be used.
Introduced `RANCHER_HELM_URL` variable with previous hardcoded value as the default. 
supporting PR in job builder
=> [v2.6] allow rancher install from different helm URL

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
backport of https://github.com/rancher/rancher/pull/39498
ontag jobs were failing due to rules explicit to 2.6 and 2.5 in jenkinsfiles
add an explicit rule to set versions in 2.7
functional test of rke version done in jenkins (did not test jenkinsfile changes themselves)
=> [v2.6] updating ontag to allow v2.7 

tests/validation/tests/v3_api/test_airgap.py, tests/validation/tests/v3_api/test_airgap_ha.py
https://github.com/rancher/qa-tasks/issues/528
airgap currently has no way to test various versions of rancher. only what is on rancher-latest 
make the install variable
also updated the sed script so that we don't zip/unzip all the images (takes a lot of time and space that isn't necessary)
the scripts were tested locally as part of another issue
the helm changes have been tested as part of the ha_deploy python job, as these changes are the same.
=> [2.6] updating airgap to allow helm

.github/workflows/update-readme.yml
There are two things this PR addresses:
1. 2.6 changes are wiping out 2.7 changes to the README.md
2. If the stable release does not exist (i.e. with 2.7.0 initially), it should be omitted from the outputted README.md
=> Fix Github Workflow for README.md changes

pkg/controllers/managementuser/resourcequota/resource_quota_common.go, pkg/controllers/managementuser/resourcequota/resource_quota_sync.go, tests/framework/extensions/resourcequotas/list.go, tests/framework/extensions/resourcequotas/resourcequotas.go, tests/v2/integration/resource_quota_test.go
When users remove a resource quota from a project, it still exists and is associated with existing namespaces inside the project.
In these cases, when Rancher computes the new resource quota, it needs to include only those resources on the quota that are defined with some limit value on the project. If the project quota does not define a limit for some resource, then ignore the resource quota requested. Keep the current behavior where the requested amount trumps the default one, if the default exists in the project.
**Note:** this breaks current behavior, one that we discourage and should mention in the docs. Specifically, the updated logic will prevent users from **adding** new quota resource in their override via Kubectl. Rancher will honor only those resource overrides that actually …
=> Remove quotas from namespaces when they are removed from project

pkg/auth/api/user/user_actions.go, pkg/auth/api/user/user_actions_test.go, pkg/auth/api/user/user_store.go
Prevent user from re-using the bootstrap password
The existing bootstrap password could be reused when the password is changed for the first time.
We now compare the existing password with the proposed new password, if they match, we reject it.
Tried re-using bootstrap password as well as other current password, both rejected as designed.
Added unit test to verify this funcitonality
On the first visit to the dashboard, login as usual to the dashboard with the bootstrap password
When prompted to change the password, try re-using the same (bootstrap) password. It should be rejected with the message, The new password must not be the same as the current password
Try changing the password to a valid password value (either user-typed or the randomly generated password). It should succeed.
From …
=> [v2.6] Prevent user from re-using the bootstrap password

tests/validation/tests/v3_api/test_catalog_library.py, tests/validation/tests/v3_api/test_cis_scan.py, tests/validation/tests/v3_api/test_logging.py, tests/validation/tests/v3_api/test_logging_e2e.py, tests/validation/tests/v3_api/test_monitoring.py, tests/validation/tests/v3_api/test_multi_cluster_app.py
From _rancher-v3_additional_tests_ jenkins job below tests were failing due to incompatibility with latest rancher server versions:
- test_catalog_library
- test_cis_scan
- test_logging
- test_monitoring
- test_multi_cluster_app
- Added pytest.skip(allow_module_level=True) to skip all the related tests.
=>  Skip flaky tests that are no longer supported

pkg/controllers/management/node/utils.go
#21637 
Add the cluster-id to log messages during cluster creation in order to make trouble shooting easier.
Add the Node's cluster id to the logs when forwarding messages coming from the driver.
1. Create a new cluster with the UI and look at the logs produced in stdout/stderr.
=> [v2.7.1] Add the cluster-id to log messages during cluster creation

tests/framework/extensions/projects/projects.go, tests/framework/extensions/users/users.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/qa-tasks/issues/380
https://github.com/rancher/qa-tasks/issues/168
Forward port of https://github.com/rancher/rancher/pull/38685 
Same as the problem statement for https://github.com/rancher/rancher/pull/38685 but this PR includes the new steve client changes that were merged recently for v2.7 branch
In this PR we are creating a test suite that covers P0 test cases for RBAC cluster owner and cluster member that touches v1 endpoints. Following are the test scenarios covered in the PR:
**Cluster Owner:**
1. Standard user cannot list downstream cluster
2. Cluster owner can list the downstream cluster
3. Cluster owner should be able to list projects the user does not own
4. Cluster owner should be able to list namespaces the user does not own
5. Cluster owner should …
=> [2.7] Adding validation for cluster owner and cluster member v1 endpoints 

tests/framework/extensions/projects/projects.go, tests/framework/extensions/users/users.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go
Issue:
https://github.com/rancher/qa-tasks/issues/380
https://github.com/rancher/qa-tasks/issues/168
Problem
Currently we do not have test suite to validate the P0 use cases for cluster owners/ cluster members that touches v1 endpoints
Solution
In this PR we are creating a test suite that covers P0 test cases for RBAC cluster owner and cluster member that touches v1 endpoints. Following are the test scenarios covered in the PR:
Automated Testing
Cluster Owner:
Cluster Member:
=> [2.6]Adding validation for cluster owner and cluster member v1 endpoints

pkg/data/management/machinedriver_data.go
Cloud credentials for AWS and Azure are used both when creating clusters with Rancher node drivers as well as when creating clusters using Rancher cluster drivers for AKS/GKE/EKS/etc. However, the API schema for cloud credentials is altered depending on the current status of the infrastructure providers node driver. If the node driver is disabled, the API schema will be altered to no longer include the fields for that cloud provider. In the case where you only want to create EKS or AKS clusters, and want to disable the node driver for those providers, you are not able to create the required cloud credentials. 
Ensure that the cloud credential API schema always includes the sections for amazon and azure by setting the `addCloudCredential` field to `true` for each of the node drivers. This …
=> [v2.7.1] Always allow creation of cloud credentials for AWS and Azure

pkg/image/external/external.go, pkg/image/external/external_test.go, pkg/image/utilities/utilities.go
`rancher-images.txt` contains Windows-only images which causes issues when users try to pull images using this file in Linux environment.
Only fetch the Linux images from the RKE2 releases when we're producing the Linux images list.
The list of images downloaded from RKE2 is the amd64 list. Hopefully those images all have multi-arch manifests, but if not, we might need to revisit this code to add proper s390x and arm64 support.
`rancher-images.txt` diff:
```diff
@@ -239,8 +239,6 @@ rancher/nginx-ingress-controller:nginx-1.2.1-hardened7
rancher/nginx-ingress-controller:nginx-1.2.1-hardened9
rancher/nginx-ingress-controller:nginx-1.2.1-rancher1
rancher/pause:3.6
-rancher/pause:3.6-windows-1809-amd64
-rancher/pause:3.6-windows-ltsc2022-amd64
rancher/prom-alertmanager:v0.21.0 …
```
=> [v2.7.1] Remove windows images from rancher-images.txt

pkg/settings/setting.go
- As the `rancher/rancher` `release/v2.7` branch now tracks post `2.7.0` it needs to pick up post `2.7.0` ui builds
- Revert https://github.com/rancher/rancher/pull/39526
=> Update references to 2.7 UI builds

pkg/api/norman/customization/cred/store.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/rancher/rancher.go
When deleting cloud credentials an error would intermittently appear stating `Index with name by-cloud-cred does not exist`, and the cloud credential would not be deleted. This issue only reproduces in HA setups. 
The root cause of this issue is, as the error mentions, a missing indexer in the provisioning cluster cache. This indexer is used to determine if any provisioning clusters are currently using the cloud credential being deleted. The reason that this issue only appears in HA setups is that only the leader pod will actually register the indexer. In cases where there is only one replica, or the Rancher server is being run in docker/IDE, this issue will not reproduce.
The indexer is registered as apart of other prov v2 controllers, which are only active on the leader pod. When the UI …
=> [v2.7.1] Ensure ProvV2 indexers are registered for all replicas

go.mod, go.sum, tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/hardening/k3s/audit.yaml, tests/framework/extensions/hardening/k3s/harden_nodes.go, tests/framework/extensions/hardening/k3s/psp.yaml, tests/framework/extensions/hardening/k3s/system-policy.yaml, tests/framework/pkg/nodes/nodes.go, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go
Currently, the Go test framework allows for provisioning K3s custom clusters. By default, these are non-hardened clusters. In realistic customer environments, hardened clusters are at the forefront, so we need to be able to support this in our testing. This PR addresses this problem by providing the option to harden the custom K3s clusters.
This is a multi-step solution, please find a summary of the changes incorporated:
1. There needed to be an option available to select whether or not the user wishes to harden the cluster. This is done by adding a new `Hardened` bool type in the `config.go` struct.  Inside the user's `cattle-config.yaml`, they will have to define a new `hardened` value and set it to true or false.
2. In the `custom_clusters_test.go` file, new functions …
=> [v2.6] Add support for hardening K3s custom clusters

go.mod, go.sum, tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/hardening/k3s/audit.yaml, tests/framework/extensions/hardening/k3s/harden_nodes.go, tests/framework/extensions/hardening/k3s/psp.yaml, tests/framework/extensions/hardening/k3s/system-policy.yaml, tests/framework/pkg/nodes/nodes.go, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go
Currently, the Go test framework allows for provisioning K3s custom clusters. By default, these are non-hardened clusters. In realistic customer environments, hardened clusters are at the forefront, so we need to be able to support this in our testing. This PR addresses this problem by providing the option to harden the custom K3s clusters.
This is a multi-step solution, please find a summary of the changes incorporated:
1. There needed to be an option available to select whether or not the user wishes to harden the cluster. This is done by adding a new `Hardened` bool type in the `config.go` struct.  Inside the user's `cattle-config.yaml`, they will have to define a new `hardened` value and set it to true or false.
2. In the `custom_clusters_test.go` file, new functions …
=> [v2.7] Add support for hardening K3s custom clusters

pkg/apis/management.cattle.io/v3/authn_types.go
Added omitempty to the defintion of the GroupPrincipals field in the Token struct.  This will prevent that field from showing GroupPrincipals: null when a token is created without GroupPrincipals set.
https://github.com/rancher/rancher/issues/39107
Currently, it is possible for a Token to be generated with the GroupPrincipals field set to null in the yaml. When someone tries to update that token, the effort will fail since null is not a valid value. To make their update stick, they would need to change GroupPrincipals to be [] (or another valid value) as part of their update.
The GroupPrincipals field is now set to "omitempty" in the definition of the Token struct, so it will just not be present if it is not set rather than defaulting it to null.
I've ran many clusters and created many …
=> Omit GroupPrincipals if field is empty

pkg/api/norman/customization/aks/handler.go
When creating new Cloud Credentials for Azure it's impossible to get more information on what exactly is wrong with specified credentials as UI shows a generic "Authentication test failed, please check your credentials" message, response from `aksCheckCredentials` simply has `{"error":"invalid credentials"}` and Rancher server log doesn't have any relevant messages logged.
* Error message returned by `aksCheckCredentials` now has Azure API error appended to it. Note the following:
* While the messages can be pretty long, in my testing they did not include any sensitive information and were very helpful to understand what exactly is wrong with the credentials (see "testing" section below)
* UI still shows the generic "Authentication test failed, please check your credentials" (which is OK …
=> Improved Azure login error handling

pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/planner.go
k3s clusters did not have taints applied to etcd/controlplane nodes.
Ensure k3s clusters also have taints applied to also have taints.
Manually tested by provisioning all 7 permutations of node roles:
| etcd               | controlplane       | worker             | node-role.kubernetes.io/control-plane=:NoSchedule | node-role.kubernetes.io/etcd=:NoExecute |
|--------------------|--------------------|--------------------|---------------------------------------------------|-----------------------------------------|
| :heavy_check_mark: |                    |                    |                                                   | :heavy_check_mark:                      |
|                    | :heavy_check_mark: |                    | :heavy_check_mark:                                | …
=> [v2.6.10][release/v2.6] Add k3s taints

pkg/clustermanager/manager.go, pkg/controllers/management/node/cleanup.go, pkg/controllers/management/node/cleanup_test.go, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go, pkg/controllers/managementuser/nodesyncer/nodessyncer.go, pkg/nodeconfig/config.go
If a node is provisioned on <v2.5.1, rancher is stopped, and the node is deleted; Remove will not be called for the node causing orphaned v1.Nodes which default unmanaged v3.Nodes are then created for.
Remove the annotation on sync and v3.Node removal.
Tested with a 1 etcd, 1 controlplane, 1 worker. On upgrade from v2.5.1 to v2.6-head, the node is properly cleaned up.
=> [v2.6.10] Add sync back to check for user-node-remove, add tests

tests/framework/extensions/charts/rancherlogging.go, tests/framework/extensions/ingresses/ingresses.go, tests/framework/extensions/ingresses/template.go, tests/framework/extensions/kubeapi/workloads/daemonsets/create.go, tests/framework/extensions/kubeapi/workloads/daemonsets/daemonsets.go, tests/framework/extensions/kubeapi/workloads/template.go, tests/framework/extensions/secrets/template.go, tests/framework/extensions/services/template.go, tests/framework/extensions/workloads/daemonsets/daemonsets.go, tests/framework/extensions/workloads/template.go, tests/v2/validation/upgrade/workload.go, tests/v2/validation/upgrade/workload_test.go
- Implemented:
- A function to access an ingress externally to `extensions/ingresses/ingresses.go`
- Implemented:
- Post-upgrade and pre-upgrade resource validation cases
- Private wait healthy response helper built on top of the access an ingresses helper
- Private wait ingress hostname update helper built on top of the wait package
- Private string prefix helpers to get an item and check an item in a slice of strings
- Private name constructor to generate random suffixes with given names
=> [2.6] Add post and pre upgrade resource validation tests

tests/framework/extensions/charts/rancherlogging.go, tests/framework/extensions/ingresses/ingresses.go, tests/framework/extensions/ingresses/template.go, tests/framework/extensions/kubeapi/workloads/daemonsets/create.go, tests/framework/extensions/kubeapi/workloads/daemonsets/daemonsets.go, tests/framework/extensions/kubeapi/workloads/template.go, tests/framework/extensions/secrets/template.go, tests/framework/extensions/services/template.go, tests/framework/extensions/workloads/daemonsets/daemonsets.go, tests/framework/extensions/workloads/template.go, tests/v2/validation/upgrade/workload.go, tests/v2/validation/upgrade/workload_test.go
- Implemented:
- A function to access an ingress externally to `extensions/ingresses/ingresses.go`
- Implemented:
- Post-upgrade and pre-upgrade resource validation cases
- Private wait healthy response helper built on top of the access an ingresses helper
- Private wait ingress hostname update helper built on top of the wait package
- Private string prefix helpers to get an item and check an item in a slice of strings
- Private name constructor to generate random suffixes with given names
=> [2.7] Add post and pre upgrade resource validation tests

pkg/api/norman/customization/cred/store.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/rancher/rancher.go
This is a back port of https://github.com/rancher/rancher/pull/39622. More detailed description and testing steps can be found in the original PR.
=> [v2.6] Back-Port #39300: Ensure ProvV2 indexers are registered for all replicas

tests/framework/extensions/users/users.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/qa-tasks/issues/538
We are automating a few additional rbac test cases to run during release testing 
1. As a cluster owner, add another user as a cluster owner
2. As a cluster owner, add a user as Project Owner
3. As a cluster owner, add cluster member to a project as a project owner 
In this PR we are using the existing rbac test suite that covers additional test cases for RBAC cluster owner listed above.
This PR also includes a fix to add an admin dynamic client for watchinterface, which would otherwise fail if we pass a standard user to the function. We are dynamically getting the admin client token and using it for the watch interface in the users.go function.
=> [2.6]Adding additional test cases to the rbac suite

tests/integration/suite/test_node.py
https://github.com/rancher/rancher/issues/39564
Seen in https://drone-pr.rancher.io/rancher/rancher/24580/4/2
As the test is running rancher with CATTLE_DEV_MODE, there is no jail and the hostnamePrefix used are equal which can cause a race condition when they are executed in a certain order.
Do not use the same hostnamePrefix
I tested this by continuously running the `"not nonparallel"` tox from `scripts/test`:
```
while true; do
tox -e rancher -- -m "not nonparallel" -n $(nproc) test_node.py test_kontainer_engine_config.py
done
```
See Testing above
This is an automated test
n/a
n/a
=> [release/v2.7] Randomize hostnamePrefix in test_node

tests/framework/clients/rancher/v1/client.go, tests/framework/extensions/clusters/bundledclusters/bundledclusters.go, tests/framework/extensions/clusters/bundledclusters/get.go, tests/framework/extensions/clusters/bundledclusters/list.go, tests/framework/extensions/clusters/bundledclusters/update.go, tests/framework/extensions/clusters/clustermeta.go, tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/clusters/import.go, tests/framework/extensions/clusters/versions/all.go, tests/framework/extensions/clusters/versions/available.go, tests/framework/pkg/environmentflag/environmentflag.go, tests/framework/pkg/environmentflag/environmentflags.go, tests/framework/pkg/environmentflag/zz_environmentflags.go, tests/v2/validation/upgrade/kubernetes.go, tests/v2/validation/upgrade/kubernetes_test.go
- Refactored:
- `environmentflags` configuration key to be used as `desiredflags` instead of `use`
- Implemented:
- A new package called `bundledclusters`:
- Enables to interact of v1 and v3 clusters as one struct
- Get, List, and Update `bundledcluster` methods for both v1 and v3
- A method to update the Kubernetes version of a cluster for all different provider types
- A method to list available versions for all different provider types
- Cluster meta struct to contain cluster’s meta for v1 and v3 clusters such as provider type, imported cluster or hosted cluster
- A listener to watch a cluster in the upgrade state
- Versions package:
- List all functions for different cluster types versions
- List available functions built on a list of all functions with a …
=> [2.6] Add kubernetes version upgrade validation tests

pkg/controllers/management/usercontrollers/controller.go
The cleanup pod cannot run as root when the cluster is running in hardened mode. It requires that all pods run as a non-root user.
Use the job/pod security context options to run the pod as unix user/group 1000.
Testing was done on `v1.23.14+rke2r1`
- created an Ubuntu 20.04 machine on digital ocean.
- installed RKE2 using the [quickstart guide](https://docs.rke2.io/install/quickstart).
- hardened the cluster using the [hardening guide](https://docs.rke2.io/security/hardening_guide)
- started the RKE2 cluster
- imported the cluster into my local rancher instance and deleted it.
I repeated these steps twice, once to confirm the issue still existed, and it did, and another time to confirm that this patch fixes the issue, and it did.
See the testing section
N/A
It can be a bit tricky to …
=> Run agent cleanup pod with user id 1000 instead of root

pkg/controllers/management/usercontrollers/controller.go
Backport of https://github.com/rancher/rancher/pull/39788 to v2.6
=> [v2.6] Backport - Run agent cleanup pod with user id 1000 instead of root

pkg/controllers/management/node/cleanup.go
In situations where a node is set to be drained before deletion, but that drain operation consistently fails, the node and its related resources will not be deleted from the infrastructure provider. This is due to how we handle errors returned from a `wait.ExponentialBackoff` call. While the function we pass to the exponential backoff never returns an error, an error (`wait.ErrWaitTimeout`) can still be returned if the operation is not completed in the specified amount of time. This prevents the node from being deleted for RKE1 clusters.
Explicitly drop that error so that the node is always deleted regardless of the drain operations outcome. This change aligns behavior with the existing comments regarding deletion after drain. 
This can be tested by creating a cluster with an invalid …
=> [v2.7.1] Ensure node deletion even if drain fails to complete

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/workloads/template.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go, tests/v2/validation/provisioning/rke2/providers.go, tests/v2/validation/upgrade/workload.go
https://github.com/rancher/qa-tasks/issues/406
**Note:** 
- This validation test takes around 20 mins to complete which is more than default timeout for the test that's why we need to  use `-timeout` option with value either greater than 20mins or 0. Similar to below command
`go test providers.go etcd_bkp_restore_test.go -v -timeout 0`
- Also it will also require at least two k8s version in ascending order in the cattle config file and at least one CNI provider as per below:
```
kubernetesVersion: 
- v1.22.13+rke2r1
- v1.23.10+rke2r1
cni:
- calico
```
=> Add validation test for etcd backup and restore with k8s upgrade

scripts/run
This fix is specficially for linux distros that make use of cgroups v2, which were previously unable to run `make test` and by extension, `make ci`.
When running the rancher process inside of dapper, rancher needs to be moved to the init process group if running on a machine using cgroups v2 (for me, this is Ubuntu 22.10, but IIRC first occured on 20.04). Otherwise, the [embedded k3s created by norman](https://github.com/rancher/norman/blob/32ef2e185b999ee40e041406080fcefffe045f22/pkg/kwrapper/k8s/k3s_linux.go#L38) will continuously exit.
Add the following workaround to `scripts/run`: https://github.com/rancher/rancher/blob/2c312a9880434a9f8ead53e4a822563cd018c4c9/package/entrypoint.sh#L16-L23
I was finally able to run `make test` and `make ci` without it crashing on a linux box for the …
=> Add cgroups v2 evacuation to scripts/run for embedded k3s

pkg/data/management/machinedriver_data.go
cherry picked back port of: https://github.com/rancher/rancher/pull/39566
Cloud credentials for AWS and Azure are used both when creating clusters with Rancher node drivers as well as when creating clusters using Rancher cluster drivers for AKS/GKE/EKS/etc. However, the API schema for cloud credentials is altered depending on the current status of the infrastructure providers node driver. If the node driver is disabled, the API schema will be altered to no longer include the fields for that cloud provider. In the case where you only want to create EKS or AKS clusters, and want to disable the node driver for those providers, you are not able to create the required cloud credentials. 
Ensure that the cloud credential API schema always includes the sections for amazon and azure by setting …
=> [v2.6] Backport #39399 : Always allow creation of cloud credentials for AWS and Azure

tests/validation/tests/v3_api/Jenkinsfile
The Jenkinsfile in tests/validation/v3api does not have the Linode access token so then tests that would use that token would fail, and hang.
Added the RANCHER_LINODE_ACCESSKEY in the Jenkinsfile.
=> [v2.7] Update Jenkinsfile in tests/validation/v3api tests

tests/validation/tests/v3_api/test_ingress.py
The test_ingress_rule_with_only_path test fails because the way Traefik ingress handles the ingress.
This PR is one of the possible fix for the wrong failure.
k3s clusters uses Traefik ingress manager, hence, the current changes in the code checks if the RANCHER_K3S_VERSION is not empty.
If so, the ingress rule created is slightly different than if the RANCHER_K3S_VERSION is empty.
=> k3s-cert traefik ingress fixes

pkg/apis/management.cattle.io/v3/cluster_types.go, pkg/client/generated/management/v3/zz_generated_cluster_secrets.go, pkg/cluster/private_registry.go, pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/controllers/management/node/cleanup.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/provisioningv2/image/resolve.go, pkg/provisioningv2/rke2/planner/agent.go, pkg/systemtemplate/import.go
cherry picked back port of https://github.com/rancher/rancher/pull/39059
I did a quick smoke check to make sure these changes are also functional for 2.6, the testing information below should still be followed
When deploying RKE2/K3s clusters which have a cluster level private registry configured, the cluster agent manifest did not incorporate that registry. Instead, the global system-default-registry was used. This resulted in images created by the cluster agent (namely the `shell` image when creating the `dashboard-shell` container) being pulled from the incorrect registry, which has implications for clusters which only have access to the cluster level registry. This issue is apart of a larger set of issues regarding the use of cluster level private registries and their precedence over …
=> [2.6] Back port Issue #38897 : Fix registries within the cluster agent manifest for Prov V2

tests/validation/tests/v3_api/Jenkinsfile
The Jenkinsfile in tests/validation/v3api does not have the Linode access token so then tests that would use that token would fail, and hang.
Added the RANCHER_LINODE_ACCESSKEY in the Jenkinsfile.
=> [v2.6] Update Jenkinsfile in tests/validation/v3api tests

pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/common_test.go
Part of groundwork for #39139
We need a mechanism to get the owning CAPI cluster or machine objects in controllers to determine if reconcilation is paused.
Add functions to get these objects.
Added unit tests to ensure this works.
=> Add functions to find CAPI cluster from objects

Makefile, package/Dockerfile, package/Dockerfile.agent
Rancher and Rancher Agent is currently based on SLE BCI 15 SP3, which goes out of general support on 2022-12-31. 
For about half a year there is already SLE BCI 15 SP4 available, so switch to that. 
Also small optimisation on size by using vim-small only instead of full vim in the image.
=> [2.7] SLE BCI update to 15.4

package/Dockerfile, package/Dockerfile.agent
This is a backport of https://github.com/rancher/rancher/pull/39767 for 2.6.
Rancher and Rancher Agent is currently based on SLE BCI 15 SP3, which goes out of general support on 2022-12-31.
For about half a year there is already SLE BCI 15 SP4 available, so switch to that.
None other than CI testing
There are no known breakages between 15.3 and 15.4.
=> [v2.6] SLE BCI update to 15.4

pkg/api/norman/customization/aks/handler.go, pkg/api/norman/customization/aks/listers.go
Rancher should provide the old `aksVMSizes` API for backwards compatibility within the UI. In the case that related UI aspects are not included in the next release, we want to make sure things still function as expected. When the related UI tasks are worked on, they can use the new API introduced in the previous PR.
Reinstate the initial functionality of the `aksVMSizes` API. Add a new endpoint called `aksVMSizesV2` which will give a response body which contains all VM sizes for a given region as well as the supported availability zones and if they support accelerated networking. 
+ Call these endpoints with CURL, similar testing steps as https://github.com/rancher/rancher/pull/39675
I've called these endpoints with CURL and have confirmed their expected response body.
none added
=> [2.7] Update AKSVmSizes endpoints

pkg/controllers/dashboard/systemcharts/controller.go, pkg/data/management/role_data.go
#39365
We need to be able to know who should be able to edit PSA-related labels on projects and namespaces
Any user that has the custom verb, updatepsa, on projects will be able to make edits to the PSA-specific labels (cluster-owner and above)
In order for the webhook to validate those requests, the webhook will need to run on all downstream clusters.  This PR also has a commit to enable that.
Verify that permission for the new custom verb is present for cluster-owner.
The enforcement of this policy is done in the webhook, automated testing has been added there
In order to test this fully, there will be other changes that need to be in place.
1) webhook admission handlers--Those changes are in https://github.com/rancher/webhook/pull/155
2) webhook running on all downstream clusters--This …
=> Adding custom verb for projects to cluster-owner for updating PSAs

tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/README.md, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/README.md, tests/v2/validation/provisioning/rke2/cert_rotation_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
In its current implementation it is not possible to run provisioning tests across packages. This is something we do with code coverage runs,
I add inputs for the the different cluster types: rke1, rke2, and k3s in the provisioningInput config entry.
=> [v2.6] Update-provisioning-input-k8s-versions-v2.6

tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/README.md, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/README.md, tests/v2/validation/provisioning/rke2/cert_rotation_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
In its current implementation it is not possible to run provisioning tests across packages. This is something we do with code coverage runs,
I add inputs for the the different cluster types: rke1, rke2, and k3s in the provisioningInput config entry.
=> [v2.7] Updated KubernetesVersion of the provisioningInput

tests/validation/tests/v3_api/test_node_label.py
The tests in tests/validation/tests/v3api/test_node_label.py would clean the clusters after tests. There should be option where we can disable this.
Added the RANCHER_CLEANUP_CLUSTER flag in the clean up portion of that test.
Jenkins runs with both clean up set to true or false.
=> [v2.7] Updated create_project_client in test_node_label to have an optional cleanup with the boolean flag RANCHER_CLEANUP_CLUSTER

tests/validation/tests/v3_api/test_node_label.py
The tests in tests/validation/tests/v3api/test_node_label.py would clean the clusters after tests. There should be option where we can disable this.
Added the RANCHER_CLEANUP_CLUSTER flag in the clean up portion of that test.
Jenkins runs with both clean up set to true or false.
=> [v2.6] Updated create_project_client in test_node_label to have an optional cleanup with the boolean flag RANCHER_CLEANUP_CLUSTER

chart/Chart.yaml
The current chart version is not compatible with Helm 2, so the chart apiVersion should be moved to `v2`.
Attempting to template the chart with Helm 2 results in the following error:
```
$ helm template rancher/chart
Error: parse error in "rancher/templates/secret.yaml": template: rancher/templates/secret.yaml:3: function "lookup" not defined
```
=> [HELM] Bump chart apiVersion as it is not Helm 2 compatible

chart/Chart.yaml
Forwardports https://github.com/rancher/rancher/pull/36838
(cherry picked from commit 713da95c2f6a550dd4684fd16ae79decf561730a)
=> [2.7 Forwardport] [HELM] Bump chart apiVersion as it is not Helm 2 compatible

pkg/catalog/manager/manager.go, pkg/controllers/managementuserlegacy/systemimage/systemimage.go
Forward ports https://github.com/rancher/rancher/pull/39917
Related Issue: https://github.com/rancher/rancher/issues/39916
=> [2.7] Avoid printing spammy logs when a Kubernetes version does not have legacy system tools available for install

cmd/agent/agent_test.go, cmd/agent/main.go, pkg/rkenodeconfigserver/nodeserver.go
A denial of service is encountered when many clusters configured with `generate_serving_certificate` connect to the Rancher server at the same time. This is due to the fact that Rancher cannot intelligently determine if a certificate must be regenerated or not as kubelet certificates are not stored or tracked by the Rancher server. This resulted in Rancher always regenerating the kubelet certificate whenever the node agent reconnects with the Rancher server. At scale, this behavior results in all CPU time being dedicated to generating certificates. Additionally, Rancher was regenerating all of the nodes certificates for each node, resulting in many unused certificates being placed on each node and additional CPU resources being consumed. 
Before attempting to reconnect with the Rancher …
=> [V2.7] Only Regenerate Kubelet Serving Certificate When Necessary  

pkg/catalog/manager/manager.go, pkg/controllers/managementuserlegacy/systemimage/systemimage.go
Related Issue: https://github.com/rancher/rancher/issues/37039
=> [2.6] Avoid printing spammy logs when a Kubernetes version does not have legacy system tools available for install

chart/templates/post-delete-hook-cluster-role.yaml, chart/templates/post-delete-hook-psp.yaml
Part of the epic https://github.com/rancher/rancher/issues/38701
1. Currently, the chart deploys one PSP resource, which Kubernetes v1.25 will not support.
2. There is also a cluster role created that has a rule that references PSP's - not needed anymore for v1.25.
For the two cases above, I add a condition that checks the underlying cluster's version. If it's v1.25 or newer, do not render the whole resource (or a relevant YAML block). 
I tried deploying the chart without these changes onto a v1.25 cluster, and the release deployed, although there were errors on deletion of the release.
=> [chart] Do not apply manifests or blocks if they reference PSP's in K8s v1.25

chart/templates/deployment.yaml, chart/tests/README.md, chart/tests/deployment_test.yaml, chart/values.yaml
https://github.com/rancher/rancher/issues/39841
Users need to be able to override probes as sometimes Rancher takes a very long time to start. If they do that manually to the deployment, helm will override it the following upgrade. 
This PR allows users to set probes via helm directly.
Ran helm template, helm install, and all the helm unit tests
Tests added, originally from: https://github.com/rancher/rancher/pull/39319/commits/fd4caac9e835ad862ce3869b8fd66c9e9bfeafbd
Should not cause any regressions, as this will operate functionally the same.
=> Adds chart option to configure the initialDelay and periodSeconds of probes

tests/validation/tests/v3_api/test_custom_host_reg.py
ontag was failing
adding 2.7 catch in custom_host_reg python test
=> adding 2.7 catch in custom_host_reg python test

tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/instances_worker.tf, tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/join-rke2.tftpl, tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/outputs.tf, tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/variables.tf, tests/validation/tests/v3_api/test_import_rke2_cluster.py
Currently there is no support to add Windows node as agent to a rke2 standalone cluster. The process of adding the agent is tedious and time consuming, specially during rke2 patch or minor release validation.
This PR adds the ability to automatically add Windows node as agent to a rke2 cluster
=> PR for Windows automation 

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/hardening/rke2/account-update.sh, tests/framework/extensions/hardening/rke2/account-update.yaml, tests/framework/extensions/hardening/rke2/harden_nodes.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go
Currently, the Go test framework allows for provisioning RKE2 custom clusters. By default, these are non-hardened clusters. In realistic customer environments, hardened clusters are at the forefront, so we need to be able to support this in our testing. This PR addresses this problem by providing the option to harden the custom RKE2 clusters.
This is a multi-step solution, please find a summary of the changes incorporated:
- There needed to be an option available to select whether or not the user wishes to harden the cluster. This is done by adding a new Hardened bool type in the config.go struct. Inside the user's cattle-config.yaml, they will have to define a new hardened value and set it to true or false.
- In the custom_clusters_test.go file, new functions HardenNodes, …
=> Add hardening config for rancher provisioned rke2 clusters

pkg/apis/management.cattle.io/v3/pod_security_types.go, pkg/generated/controllers/management.cattle.io/v3/interface.go, pkg/generated/controllers/management.cattle.io/v3/podsecurityadmissionconfigurationtemplate.go
During the initial implementation of the PodSecurityAdmissionConfigurationTemplate the `// +genclient:nonNamespaced
` attribute was omitted, resulting in some generated controllers incorrectly requiring a namespace
Add the `// +genclient:nonNamespaced` attribute and run `go generate` 
Attempted to test creation of CRD in the `v1` API, however a recent web-hook error has prevented me from logging into the Rancher UI. I will retest once this issue has been addressed. However, a change such as this is unlikely to introduce any issues, as the controllers for this CRD are not currently being used in the code base. 
Edit: The webhook issue has been resolved and I've confirmed you can still create this CRD with the `v1` API
=> [v2.7] Ensure `PodSecurityAdmissionConfigurationTemplate` is non-namedspaced

pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/clusterrole.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/deferred.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/namespace.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/podsecuritypolicy.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/serviceaccount.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/version.go
Rancher may attempt to register various controllers (https://github.com/rancher/rancher/tree/release/v2.7/pkg/controllers/managementuser/rbac/podsecuritypolicy) for a downstream cluster that work with resources (namespaces, cluster roles, and others) for PSP management. If the downstream cluster's version is v1.25 or later, Rancher will have constant controller errors when doing any operation pertaining to PSP resources, since the K8s API server will throw an error when it is asked to fetch an unknown resource. And PSP's are not resources known to K8s API as of v1.25.
There are two conditions which currently allow controllers to be registered:
1. If the downstream cluster has a project that has PSP's configured. Specifically, if there exists a PSPProjectTemplateBinding that has …
=> Do not register podsecuritypolicy controllers for clusters >= v1.25

tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/instances_worker.tf, tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/join-rke2.tftpl, tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/outputs.tf, tests/validation/tests/v3_api/resource/terraform/rke2/windows_worker/variables.tf, tests/validation/tests/v3_api/test_import_rke2_cluster.py
Raising similar PR as https://github.com/rancher/rancher/pull/39546 against release/v2.7 branch
Currently there is no support to add Windows node as agent to a rke2 standalone cluster. The process of adding the agent is tedious and time consuming, specially during rke2 patch or minor release validation.
This PR adds the ability to automatically add Windows node as agent to a rke2 cluster
=> QATASKS-151 adds setup and install script and windows worker tf

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_node_label.py
There was a bug with how the timeout in validate_cluster_state was being set causing an absurdly long timeout. Also there is a chance that an updating state happens after it is checked with this function, so a conditional was added to not fail if the updating state is missed.
Removed `timeout = start_time + timeout` since it's just adding to be a super long timeout.
Jenkins runs
=> [v2.6] Fix timeout issue with validate_cluster_state

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_node_label.py
There was a bug with how the timeout in validate_cluster_state was being set causing an absurdly long timeout. Also there is a chance that an updating state happens after it is checked with this function, so a conditional was added to not fail if the updating state is missed.
Removed `timeout = start_time + timeout` since it's just adding to be a super long timeout.
Jenkins runs
=> [v2.7] Fix timeout issue with validate_cluster_state 

pkg/api/norman/store/cluster/cluster_store.go, pkg/api/norman/store/clustertemplate/store.go
https://github.com/rancher/rancher/issues/38701
https://github.com/rancher/rancher/issues/40009
https://github.com/rancher/rancher/issues/39992
Due to the addition of checks for PSA in rancher-webhook, it does more validations on the request for creating/updating a v3 Management cluster and could return an error if the validation fails.  
Previously, rancher-webhook did not return such an error and rancher also did not catch it, so a panic error did not happen before but happens now. 
Return the error properly. 
Steps:
- create an RKE1 cluster in rancher; during the creation, edit the cluster as YAML and add the following 
```
default_pod_security_admission_configuration_template_name: privileged
```
- update the above cluster to change the template name to an non-existing one 
Expected …
=> Fix Panic Error Caused by Rancher-Webhook

pkg/settings/setting.go
Update the default for rancher-agent to be v2.7-head instead of 2.6-head
=> Bump rancher-agent image to use v2.7-head

pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/jailer/jailer.go, pkg/jailer/jailer_linux.go, pkg/jailer/jailer_test.go, pkg/settings/setting.go
This allows passing down environment variables to rancher machine during provisioning.
This is an alternative solution to #39375 because there were [concerns](https://github.com/rancher/rancher/pull/39375#issuecomment-1351688797) regarding security. We need to be able to enable debug logging in RKE2.
Instead of passing the `--debug` flag to rancher machine, we allow RKE2 provisioning to pass down to rancher machine whitelisted environments variables, one of which can be `MACHINE_DEBUG`, which solves the needs of the original issue reporter.
1. Start rancher with `MACHINE_DEBUG=true` and `CATTLE_WHITELIST_ENVVARS=NO_PROXY,HTTP_PROXY,HTTPS_PROXY,MACHINE_DEBUG` env vars.
2. Create an RKE2 cluster
3. Make sure rancher machine debug logs are displayed
=> [2.7] Support CATTLE_WHITELIST_ENVVARS in RKE2 provisioning code

tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/qa-tasks/issues/168
https://github.com/rancher/qa-tasks/issues/455
Currently we do not have a rbac suite for v1 P0 cases to check project RBAC. In this PR we aim to automate the P0 cases for the project RBAC
We are levaraging the current rbac suite the addresses cluster owner/member. The P0 cases for the project RBAC/cluster RBAC are similar except for two test cases. We are adding those additional cases and also add a few changes on how we validate for project members - Project Owner/Project Member
=> Adding the project rbac test cases to the existing rbac suite

pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/jailer/jailer.go, pkg/jailer/jailer_linux.go, pkg/jailer/jailer_test.go, pkg/settings/setting.go
This allows passing down environment variables to rancher machine during provisioning.
Backport of #40015
=> [2.6] Backport: Support CATTLE_WHITELIST_ENVVARS in RKE2 provisioning code

package/Dockerfile.agent, package/run.sh
When deploying the Rancher node agent no value for `CATTLE_ADDRESS` is provided. `CATTLE_ADDRESS` is used by the node agent to determine the external IP address of the host. Previously, this value was not used by the node agent so its value was unimportant. However, the implementation of #39497 requires that this variable hold the correct external IP address. 
If this environment variable is not provided upon initial deployment of the agent, then the command `ip -o route get 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'` will be run by the agent on startup in an attempt to determine the external IP address of the host. This works for most providers, however for some (Azure & Linode, and potentially others) it actually returns the private IP address of the host. 
Attempt to get the …
=> [2.7] Use `dig` to get external IP address

package/Dockerfile
This PR bump tags for UI and CLI to `v2.7.2-rc1`
=> bump tags for UI and CLI to v2.7.2-rc1

tests/v2/validation/Jenkinsfile
https://github.com/rancher/qa-tasks/issues/527
go jenkinsfile did not allow overriding of global variables
load global vars first, then load user entered variables. 
tested in jenkins
=> [2.6] update go jenkinsfile to use user entered variables when available instead of global ones. 

pkg/settings/setting.go
- `rancher/dashboard` and `rancher/ui` have both now branched for generic 2.6 work
- This change ensures the `rancher/rancher` 2.6 branch points to the correct builds
- These builds are used (when settings are default and the version ends in `-head`) as an alternative to the build embedded in to Rancher)
=> Update references to new 2.6 UI branches

tests/integration/suite/test_cluster_defaults.py, tests/integration/suite/test_clustertemplate.py, tests/integration/suite/test_pod_security_policies.py
builds have been failing due to some PSP tests running on the latest (1.25+ does not support PSPs)
adding a condition to pytest to check the k8s version of the cluster. If the cluster is 1.25 or above, we will not run the tests marked as including PSPs. 
testing is part of integration -> drone
we should add PSA tests for 1.25+ in the new (golang) integration tests.
=> fixing PSP integration tests for 1.25+

tests/framework/clients/corral/config.go, tests/framework/clients/corral/corral.go, tests/framework/pkg/namegenerator/namegenerator.go, tests/v2/validation/.gitignore, tests/v2/validation/Dockerfile.validation, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/cert_rotation_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go, tests/v2/validation/standalone/README.md, tests/v2/validation/standalone/corral_generic_test.go
forward port of: https://github.com/rancher/rancher/pull/39752
https://github.com/rancher/qa-tasks/issues/357
we want a way to rehydrate an rke2 cluster - specifically the local cluster running rancher
In order to modify a local cluster, I added a test case for Corral. This also required modifying the dockerfile to install corral. The test suite currently can only handle running corrals that do not depend on eachother in any way, as the order is psudorandom ([see this issue](https://github.com/rancher/qa-tasks/issues/540) for more details)
In the test case, I include 2 corral packages: one to provision the local cluster (which was largely based on packges from the example https://github.com/rancherlabs/corral-packages repo) and another to modify it, replacing x number of server nodes in …
=> go + corral initial test case (v2.6)

tests/framework/clients/corral/config.go, tests/framework/clients/corral/corral.go, tests/framework/pkg/namegenerator/namegenerator.go, tests/v2/validation/.gitignore, tests/v2/validation/Dockerfile.validation, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/cert_rotation_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go, tests/v2/validation/standalone/README.md, tests/v2/validation/standalone/corral_generic_test.go
https://github.com/rancher/qa-tasks/issues/357
we want a way to rehydrate an rke2 cluster - specifically the local cluster running rancher
In order to modify a local cluster, I added a test case for Corral. This also required modifying the dockerfile to install corral. The test suite currently can only handle running corrals that do not depend on eachother in any way, as the order is psudorandom ([see this issue](https://github.com/rancher/qa-tasks/issues/540) for more details)
In the test case, I include 2 corral packages: one to provision the local cluster (which was largely based on packges from the example https://github.com/rancherlabs/corral-packages repo) and another to modify it, replacing x number of server nodes in the cluster. Please see the updated readmes in their respective …
=> Corral base use cases in Go Framework

.drone.yml
Fix for Windows 1809 build, see https://github.com/rancher/system-agent-installer-rke2/pull/37 for details on reasons.
Also, removed usage of custom `rancher/drone-images:git-amd64-ltsc2022` image as linked issue is now closed per https://github.com/drone/drone-git/pull/25#issuecomment-761946952
For "testing", it will mostly be apparent once we `drone-publish` runs after merging as it's the part that is failing (e.g. https://drone-publish.rancher.io/rancher/rancher/8799/6/2 is failing due to https://drone-publish.rancher.io/rancher/rancher/8799/6/1 not actually cloning as expected).
However, you can see how after the change there are no errors in `git clone` step for Windows 1809 build (compare new https://drone-pr.rancher.io/rancher/rancher/25737/6/1 to old …
=> Fix for Windows 1809 build; also removal of custom ltsc2022 image

pkg/controllers/provisioningv2/rke2/provisioninglog/provisioninglog.go
There are intermittent error messages reported in the provisioning log relating to object version conflicts. In all observed scenarios these error messages are benign and resolve themselves automatically. However, the presence of these error messages and subsequent UI display gives the end user an impression that something has failed, when in fact the issue is only temporary.
Prepend a message stating that this is a transient error, so as to ensure the end user that the provisioning process has not encountered a significant error that needs to be remediated 
+ Create a rancher server 
+ provision an RKE2 cluster on any infrastructure provider. Create 3-5 nodes in a single all role node pool
+ observe that the error message is now prepended with `Transient Error Encountered: ...` 
I've …
=> [v2.7] Adjust object conflict messages seen in provisioning log

.drone.yml
(cherry picked from commit 9a016a853b0fdaf11e894da259542382ea2a7ffd)
Backport of https://github.com/rancher/rancher/pull/40115
=> [v2.6] Fix for Windows 1809 build; also removal of custom ltsc2022 image

tests/v2/validation/provisioning/hosted/aks/provisioning/hosted_provisioning_test.go, tests/v2/validation/provisioning/hosted/eks/hosted_provisioning_test.go, tests/v2/validation/provisioning/hosted/gke/hosted_provisioning_test.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go
- Updated:
- Hosted provisioning validation tests package and imports.
- ETCD validation tests package and imports.
- Removed unnecessary namespace creation duplication in RBAC validation tests.
=> [2.6] Fix validation tests' random string generator imports

pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/common_test.go, pkg/controllers/provisioningv2/rke2/machineprovision/args.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go
Part of groundwork for #39139
We need a mechanism to support pausing the various CRs in our CAPI implementation, so we can disable cluster reconciliation during disruptive actions such as encryption key rotation.
Add missing predicates to rke machine controller, including checking for pausing as well as other required predicates we were missing.
https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html#normal-resource
=> Add CAPI predicates to RKEMachine

tests/framework/clients/ec2/client.go, tests/framework/clients/ec2/config.go, tests/framework/extensions/nodes/ec2/ec2.go, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/nodeproviders.go, tests/v2/validation/provisioning/rke2/README.md, tests/v2/validation/provisioning/rke2/custom_cluster_test.go
[QA-Task 428](https://github.com/rancher/qa-tasks/issues/428)
Currently all testing of the provisioning of Custom clusters with Windows worker nodes has to be handled manually or with bash scripts, therefore having the ability to run automated CI/CD tests for the provisioning of these clusters to ensure they are still working properly will be much more efficient on time.
This PR will allow for automation of Windows Custom Cluster nodes, to allow expedited regression/smoke testing.
This PR is intended to add automated tests for the provisioning of Custom Clusters with Windows worker nodes. The additions of new Windows provisioning tests (1 Node all roles Admin User + 1 Windows Worker, 1 Node all roles Standard User + 1 Windows Worker, 3 unique role nodes as Admin User + 1 Windows Worker, 3 …
=> Windows Custom Cluster Automation

pkg/apis/rke.cattle.io/v1/controlplane.go, pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go, pkg/provisioningv2/rke2/planner/certificaterotation.go, pkg/provisioningv2/rke2/planner/certificaterotation_test.go, pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go, pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/rancher/migrations.go
This PR fixes node auto replace and encryption key rotation by changing how the control plane's ready status field is set, and fixing planner thrashing respectively.
1. Delete a node from an Active cluster with Auto Node Replace set to 30 seconds
2. The planner will attempt to reconcile the node, fail, and set the RKEControlPlane (and Provisioning cluster) to `Updated = False` (to indicate there was an error applying the plan).
3. This is then reconciled onto the management cluster here: [https://github.com/rancher/rancher/blob/da810a7523fb4c1b529bee374e9d2574f33ab0c8/p[…]ntrollers/provisioningv2/rke2/provisioningcluster/controller.go](https://github.com/rancher/rancher/blob/da810a7523fb4c1b529bee374e9d2574f33ab0c8/pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go#L291) …
=> Refactor planner handler and add capi predicates

tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go
Due to a change that was made to the NodeCreationFunc to accommodate Windows Custom Cluster tests, the RKE1 and K3s custom cluster tests are failing
Updated the RKE1 and K3s custom cluster tests to accommodate the changes made to the NodeCreationFunc
=> Modified existing tests to reflect changes to NodeCreationFunc

pkg/controllers/managementapi/usercontrollers/usercontroller.go, pkg/controllers/managementapi/usercontrollers/usercontroller_test.go
If a remote cluster is upgraded to a different K8s version, the controllers for the cluster are not restarted. This might make informers watch over resources that are no longer known by the remote cluster's API server. Because of that, there might be lots of informer errors in the local cluster's logs.
Restart all cluster controllers in the local cluster for the downstream cluster when its K8s version has been upgraded or downgraded to a non-patch version. The controller now stores the current cluster's K8s version as an annotation and compares it to the new version.
Created a K8s v1.24 remote cluster with PSPs enabled. Then upgraded the cluster to v1.25, saw that there were no errors about PSPs being unknown by the remote cluster.
=> Restart cluster controllers when remote cluster's major or minor version changes

tests/framework/extensions/rke1/nodepools/nodepools.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
Recently, we refactored the hosted provisioning tests to do two of the following:
- Rework redundant provisioning code into a private method
- Separate provisioning test and additional test cases into their own, unique test functions
This greatly helps moving forward for internal CI/CD pipeline and overall helps to better organize our ever-growing test framework. As such, the same approach has been made to the RKE1 provisioning tests.
Once this is done, the same effort will be done for RKE2/K3s, to ensure full parity across the board.
Like with the hosted provisioning tests, the redundant provisioning code for node provider and custom clusters has been put into a single private method. The now separated unique test functions reference this private method and only keep unique code in their …
=> [v2.7] Refactor RKE1 into separate test functions

tests/framework/extensions/rke1/nodepools/nodepools.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
Recently, we refactored the hosted provisioning tests to do two of the following:
- Rework redundant provisioning code into a private method
- Separate provisioning test and additional test cases into their own, unique test functions
This greatly helps moving forward for internal CI/CD pipeline and overall helps to better organize our ever-growing test framework. As such, the same approach has been made to the RKE1 provisioning tests.
Once this is done, the same effort will be done for RKE2/K3s, to ensure full parity across the board.
Like with the hosted provisioning tests, the redundant provisioning code for node provider and custom clusters has been put into a single private method. The now separated unique test functions reference this private method and only keep unique code in their …
=> [v2.6] Refactor RKE1 into separate test functions

pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/planner.go
#40016
K3s cluster system pods + charts do NOT have the correct tolerations to be able to run on a controlplane + etcd node
Do not add the etcd taint to etcd nodes if the runtime is k3s and it is also a controlplane node.
Tested manually, confirmed etcd taint was not present for split role clusters. Tested upgrade from v2.7.0 v1.24.8+k3s1.
=> Skip adding etcd taint for k3s

chart/templates/deployment.yaml, chart/tests/deployment_test.yaml
https://github.com/rancher/rancher/issues/39841
Break out of https://github.com/rancher/rancher/issues/38177.
This gives another way of further delaying readiness probes. This is sometimes necessary now because startup time for rancher has increased since v2.5.
Install chart using --set settings to set `startupProbe.periodSeconds` and/or `startupProbe.failureThreshold`. Just configuring one should be enough. The rest of startupProbe should use sensible defaults. It should work when configuring both as well. Can check the rancher deployment to confirm everything is as expected.
=> Add startup probe

pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/probe.go
With the removal of the killall script, some resources are left over after restarting the `rke2-server/k3s` services during encryption key rotation.
Wait for probes after restarting the nodes to ensure the nodes are actually healthy and ready to receive API requests.
Tested manually with a freshly provisioned single node cluster.
Tested with a freshly provisioned single node cluster, then again with 10k secrets.
Tested with a freshly provisioned 3 etcd + 2 controlplane + 3 worker cluster, then again with 10k secrets.
During testing, https://github.com/rancher/rke2/issues/3801 was discovered. This issue is unrelated to rancher, but will not be fixed until a future release of k3s/rke2. If this bug is encountered during encryption key rotation, there is no recourse except for an etcd …
=> Wait for probes during encryption key rotation restart

pkg/provisioningv2/rke2/planner/agent.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/planner.go
Original Issue: #40016
K3s cluster system pods + charts do NOT have the correct tolerations to be able to run on a controlplane + etcd node
Do not add the etcd taint to etcd nodes if the runtime is k3s and it is also a controlplane node.
Tested manually, confirmed etcd taint was not present for split role clusters. Tested upgrade from v2.7.0 v1.24.8+k3s1 on original PR.
=> [Backport v2.6] Skip adding etcd taint for k3s

pkg/auth/providers/keycloakoidc/keycloak_client.go
Rancher assumes that Keycloak issuer URL contains `/auth/`
Handle other cases.
=> Fix Rancher crash loop in case if Keycloak URL doesn't have /auth/

go.mod, go.sum
When a watch was started for a namespace, the namespace wasn't being included in the returned start event over the websocket, making it hard to verify that the watch was correctly started even though it was correct in the backend.
Include the namespace in the start event.
Used websocat to start a watch and verify the result:
```
$ websocat -k wss://127.0.0.1:9443/v1/subscribe?sockId=1
🔼 {"resourceType": "pods", "namespace": "default"}
🔽 {"name":"resource.start","namespace":"default","resourceType":"pods","data":{"type":"subscribe","links":{}}}
```
Unit tests added in the apiserver change: https://github.com/rancher/apiserver/pull/20
This change is very minimal, no regressions likely.
=> Bump steve and apiserver

pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go, pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/etcdrestore.go
Rancher would panic during an etcd restore when dereferencing the nil status field during state checking. 
Pass pointer values instead.
Also, there was a bug where etcd snapshot restore would not advance to the next stage due to identical waiting messages in the planner.
Tested manually performing an etcd restore.
=> Fix panic in etcd snapshot restore

package/Dockerfile, pkg/settings/setting.go
The system agent was built for arm64 but the system agent update controller was not, which made updates to the system agent impossible.
This PR updates the version of the system agent in use by rancher, this new version has arm64 builds.
* Create a new downstream cluster using arm64 on AWS, no issues coming online.
* Create a cluster on the release/v2.7 branch which has v0.2.13, then stop rancher, switch to this branch and restart rancher. The system agent version should now be v0.3.1 in rancher. **The cluster does not automatically update and I might need help figuring out the exact outcome expected from this.**
* Not sure how rancher updates the system agent when the version changes.
=> Update system-agent to v0.3.1 which includes arm64 support for the SUC

pkg/data/management/role_data.go
Only admin users were able to view or modify PSACT's. This prevented standard users from attaching PSACT's to clusters they create / administrate, as well as modifying the PSACT attached to clusters they own / administrate. Additionally, no RBAC role existed which permitted non-admin users to modify existing PSACTs or create new PSACT's. 
Update `role_data.go` to 
1. Update the standard user permissions for PSACT
a. The verbage for PSACT's matches those for PSP's
2. Update the restricted admin user and provide them with full CRUD access to PSACT's  in similar fashion to PSP's
3. Introduce a new built-in role which provides full CRUD access to PSACT's, mirroring the built-in role for PSP's
**Note:** The name of the built-in role shown in the UI differs from the value in `role_data.go`. It …
=> [2.7] Update RBAC surrounding PSACTs

pkg/data/management/kontainerdriver_data.go
- https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/46
- https://github.com/rancher/rancher/pull/39085
- https://github.com/rancher-plugins/kontainer-engine-driver-oke/issues/59
- See also: https://github.com/rancher/rancher/pull/39085
Previous versions of the [OKE Cluster Driver](https://github.com/rancher-plugins/kontainer-engine-driver-oke) did not have support for Kubernetes 1.24, which requires manually creating `Secrets` that contain access an token for service accounts (returning an access token for newly provisioned clusters to Rancher is part of the driver's responsibilities).
Additionally, previous versions of the OKE Cluster Driver did not have support for specifying [cloud-init](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingcustomcloud …
=> [2.7] Bump OKE cluster driver to v1.8.3 (support for k8s 1.24+)

pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
fixes https://github.com/rancher/fleet/issues/1079
fixes https://github.com/rancher/fleet/issues/759
Fleet uses a hardcoded label "name=local" for the local cluster and local cluster group.
Provisioning overwrites labels with their own, breaking  the local cluster and reportedly leading into a situation where the "name=local" label is flip flopping. This would result in bundles targeting the local cluster being removed and then redeployed infrequently or daily.
Make sure the "name: local" label is not lost.
The local cluster group works now and can be used to select the local cluster.
The "name: local" is always visible on the fleet cluster resource.
The labels remain, even when:
* changing an agent related value in fleet-controller configmap (like `AgentCheckinInterval`)
* restarting the …
=> Retain Fleet Name Label for Local Cluster

pkg/data/dashboard/repo.go, pkg/settings/setting.go
When testing different fleet builds in Rancher, we need to set up a fork of rancher/charts (described here: https://github.com/rancher/fleet/blob/master/DEVELOPING.md#fleet-in-rancher---using-a-custom-fork).
However we don't want to (should not) create a test branch in rancher/charts directly, so we have to change the rancher code and change the [hard coded URL](https://github.com/manno/rancher/blob/release/v2.7/pkg/data/dashboard/repo.go#L29).
This adds a setting for `ChartDefaultURL` (env var `CATTLE_CHART_DEFAULT_URL`), which will be used for rancher-charts when the controller is started and adds its repos.
Since we only use this variable for dev purposes, everything should work as before.
=> Add ChartDefaultURL to support custom rancher-charts repo in testing

pkg/data/management/podadmissionconfigurationtemplate_data.go
https://github.com/rancher/rancher/issues/40306 
Rancher allows users to set the profile when creating an RKE2 custom cluster.
When the REK2 cluster version is 1.25, and the profile is set as cis-1.23, the RKE2 engine will configure the cluster to use RKE2-builtin [restricted PSA config file](https://github.com/rancher/rke2/blob/0ab4614b13daa5a49e484249a49012918d46ed22/pkg/rke2/psa.go#L40-L60).
The problem is that the config file does not include rancher's namespaces in its exception list, so Rancher's components can not be deployed into the cluster. Therefore, cluster provision will fail.
Instead of using RKE2's default restricted PSA config, we will use Rancher's default restricted PSA config when `profle=cis-1.23` is set on the RKE2 cluster, which means we need to append the namespace …
=> add the namespaces from RKE2's default restricted PSA config to Rancher's

package/Dockerfile
New versions for Dashboard and rancher-webhook only.
=> updating versions for v2.6.11-rc2

pkg/data/management/podadmissionconfigurationtemplate_data.go
Issue: #40306
This PR removes duplication from the list, otherwise `kube-apiserver` does not work.
=> remove duplication from the list, otherwise kube-apiserver does not work

pkg/data/dashboard/repo.go, pkg/settings/setting.go
This reverts commit b052966f27047d2eab9f9e2a82685b0bb2806179.
There are several concerns regarding https://github.com/rancher/rancher/pull/40281 
Let's revert it for now and discuss a better solution later.
=> Revert "Add ChartDefaultURL to support different registries in testing"

pkg/api/norman/store/cluster/cluster_store.go
`useInstanceMetadataHostname` is of type `*bool`, so it doesn't default to false automatically. It is only configured for aws cloud provider right now, so setting default only if cloud provider is aws. 
https://github.com/rancher/rancher/issues/40317
=> [v2.6] set default for useInstanceMetadataHostname

pkg/image/origins.go
Adds source repo for `mirrored-skopeo-skopeo` to origins.go so it may be included in the `image-origins.txt` release artifact
=> Add mirrored-skopeo-skopeo

pkg/controllers/management/auth/auth_config.go, pkg/controllers/management/auth/auth_config_test.go
Adresses https://github.com/rancher/rancher/issues/40360. This changes how the auth config annotation is updated. We must use the unstructured client to preserve all the fields of a config when it is updated. When using a regular interface, I was having issues with fields disappearing on update because of the structure of auth config as a type - it's not a regular CRD.
=> [2.6] Use the unstructured client to update auth config objects

.drone.yml
This fix is similar to https://github.com/rancher/rancher/pull/37806.
As more and more automation is going to be used, the "waste" of running CI on `drone-publish` is growing. We already scoped most of the steps in the previously linked PR, this PR also scopes the `provisioning-tests` to only when it is actually needed (`pull_request` or `push` to specific branches). This saves cost and time on each PR created using automation.
=> [release/v2.6] Skip provtest CI when local repo branch is used

pkg/data/management/machinedriver_data.go
Hello Rancher team,
Here is an update of our node driver with fixes for rke2 and addition of VPC support.
We have also migrated our repo to /outscale.
Best regards,
Maxime
=> Update Outscale Node driver to the latest

package/Dockerfile, pkg/settings/setting.go
The arm64 image for the SUC is not working properly because the wrong kubectl binary is being downloaded.
This PR merges `0.3.2-rc1` so the QA team can test this fix. If the tests succeed, it will be followed up by another PR to use a non `rc` version. 
This bumps the version of system agent to use fixes in https://github.com/rancher/system-agent/pull/106
=> Update system agent to 0.3.2-rc1 with fixed arm64 image

pkg/data/management/machinedriver_data.go
Hello Rancher team,
Here is an update of our node driver with fixes for rke2 and addition of VPC support.
We have also migrated our repo to /outscale.
Ref: #40382
Best regards,
Maxime
=> Update Outscale Node driver to the latest - For release/2.6

tests/v2/codecoverage/Dockerfile.buildcodecoverage, tests/v2/codecoverage/Dockerfile.codecoverage, tests/v2/codecoverage/scripts/build_docker_images.sh
SUSE golang 1.20 has not been released yet.
Revert `Dockerfile.codecoverage` back to 1.19, and since 1.20 is needed for build code coverage images, changed the image for `Dockerfile.buildcodecoverage` to a different docker image that does support golang 1.20
Latest ranchertest images are from this docker build.
=> [v2.6] Modified docker files to account for the new golang 1.20 release

tests/v2/codecoverage/Dockerfile.buildcodecoverage, tests/v2/codecoverage/Dockerfile.codecoverage, tests/v2/codecoverage/scripts/build_docker_images.sh
SUSE golang 1.20 has not been released yet.
Revert `Dockerfile.codecoverage` back to 1.19, and since 1.20 is needed for build code coverage images, changed the image for `Dockerfile.buildcodecoverage` to a different docker image that does support golang 1.20
Latest ranchertest images are from this docker build.
=> [v2.7] Modified docker files to account for the new golang 1.20 release

tests/framework/extensions/hardening/k3s/harden_nodes.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
Recently, we refactored the hosted provisioning tests to do two of the following:
- Rework redundant provisioning code into a private method
- Separate provisioning test and additional test cases into their own, unique test functions
This greatly helps moving forward for internal CI/CD pipeline and overall helps to better organize our ever-growing test framework. As such, the same approach has been made to the RKE2/K3s provisioning tests.
Like with the hosted provisioning tests, the redundant provisioning code for node provider and custom clusters has been put into a single private method. The now separated unique test functions reference this private method and only keep unique code in their respective functions.
Additionally, I added two new Windows test for specifically the …
=> [v2.6] Refactor RKE2/K3s provisioning tests

pkg/controllers/management/secretmigrator/clusters.go
This is an urgent fix for v2.6 that was authored by @jakefhyde.
=> [v2.6] Check if secret already exists before migrating

tests/validation/tests/v3_api/common.py
Backport PR for failing kubectl websocket test. 
Reference - https://github.com/rancher/rancher/pull/39455
=> backport kubectl-websocket-fix

manifest-runtime.tmpl, scripts/check-release-images-exist, scripts/package
Codebase still contained references to `rancher/rancher-runtime` which are no longer needed.
Backport of https://github.com/rancher/rancher/pull/40473
Remove the references
Nothing specific, it was already not in use but obviously it shouldn't break anything. Only test is to check that `rancher/rancher-runtime` is no longer present in `rancher-images.txt` and `rancher-images-origins.txt`.
=> [release/v2.6] Remove rancher-runtime references

pkg/auth/api/secrets/cleanup.go, pkg/auth/cleanup/service.go, pkg/auth/cleanup/service_test.go, pkg/auth/providers/azure/clients/ms_graph_client.go, pkg/controllers/management/auth/auth_config.go, pkg/controllers/management/auth/auth_config_test.go
The first [commit](https://github.com/rancher/rancher/pull/40378/commits/b208a1c5619125578010c0cf13b82c8da197606e) has the same as the code changes already reviewed for auth provider cleaning up resources after being disabled.
The [second](https://github.com/rancher/rancher/pull/40378/commits/353738f265f3107bf0d096982550a0f3185c5c4c) is just a quick fix to address a small issue https://github.com/rancher/rancher/issues/39908, since it's related to auth providers.
~The [third](https://github.com/rancher/rancher/pull/40378/commits/d1d6ac8d75139106bf3e576325cca79fc751f56f) addresses https://github.com/rancher/rancher/issues/40354. This changes how the auth config annotation is updated. We must use the unstructured client to preserve all the fields of a config when it is updated. When using a …
=> Add CRTB, PRTB, GRB, User cleanup when an auth provider is disabled

pkg/auth/api/secrets/fields.go
When admins enable the KeyCloak OIDC provider, the following secrets get created as secrets in the cattle-global data:
- keycloakoidcconfig-clientsecret
- keycloakoidcconfig-privatekey
There are also per-user login tokens in the same namespaces created.
On provider disable, the `keycloakoidcconfig-clientsecret` is not deleted.
While OIDC providers have common logic for secret creation, deletion is different because 
the cleanup expects that full secret name also includes the provider type, and KeyCloak is separate and has its own config, it's not under OIDC config.
Add a dedicated entry to the cleanup matrix for the client secret (its constant string value is the same as that for general OIDC providers).
=> Add a cleanup entry for KeyCloak OIDC client secret

pkg/apis/management.cattle.io/v3/authz_types.go
https://github.com/rancher/terraform-provider-rancher2/issues/1006
#40494 
The Norman client, used by the terraform provider, has omitempty set for podSecurityPolicyTemplateId.  https://github.com/rancher/rancher/blob/cd8eea1fdf0dd0071bfdcae4f1eb7de2c5b3722f/pkg/client/generated/management/v3/zz_generated_set_pod_security_policy_template_input.go#L9
And that results in an empty request body being sent when trying to unset the value via the terraform provider. 
Since fixing the client generation logic would result in a very large number of changes, we have opted to just handle this situation in Rancher by removing the "required" attribute in the schema spec.
Testing can be done through UI, curls to the api, and most importantly through the terraform provider, as described in the original …
=> Handle setpodsecuritypolicytemplate setting to null by norman client

package/Dockerfile, pkg/client/generated/management/v3/zz_generated_cluster_secrets.go, pkg/client/generated/management/v3/zz_generated_cluster_template_revision.go, pkg/client/generated/management/v3/zz_generated_cluster_template_revision_status.go, tests/v2/codecoverage/package/Dockerfile
This PR contains the following changes for preparing the v2.7.2-rc2 tag:
- run `go generate` 
- bump ui tag to v2.7.2-rc2
=> preparation for v2.7.2-rc2 

pkg/cluster/private_registry.go, pkg/cluster/private_registry_test.go, pkg/controllers/management/node/cleanup.go, pkg/rkenodeconfigserver/nodeserver.go, pkg/systemtemplate/import.go
During merging of the v2.6.10 backports, a base64 encoding was dropped. 
Add the base64 encoding of the private registry auth credentials back.
I am still setting up an environment to test this, but I am fairly confident this will work.
Updated unit tests to ensure that the base64 encoding is returned.
=> Encoded private registry auth config

pkg/data/management/role_data.go
https://github.com/rancher/rancher/issues/40289
This removes the Manage PodSecurityAdmissionConfiguration Templates role.  It has been decided that this is an admin-only operation.
=> Remove the Manage PodSecurityAdmissionConfigurationTemplates role

pkg/data/dashboard/cluster_data.go
https://github.com/rancher/rancher/issues/40335
On warm restarts of a Rancher docker install, Rancher cannot start because the rancher-webhook deployment is not running yet.
Add a retry to the local cluster creation/mutation that will retry if the error received is a 503, which could be that the rancher webhook is unavailable at the time. Since this is a warm restart of Rancher, the webhook deployment will eventually come up and the 503's will stop being emitted.
Start rancher as a docker install, let it come up, log into it
Restart the rancher install, observe it can still start
N/A
=> [release/v2.7] Allow for 503 when creating or mutating local cluster

pkg/cluster/private_registry.go, pkg/cluster/private_registry_test.go, pkg/controllers/management/node/cleanup.go, pkg/controllers/management/secretmigrator/clusters.go, pkg/rkenodeconfigserver/nodeserver.go, pkg/systemtemplate/import.go
If a migrated secret already exists during secrets migration, and the migration fails at any point, a secret may get deleted.
Check if the secret exists prior to migrating.
Also includes fix from https://github.com/rancher/rancher/pull/40534 for private registry base64 encoding.
Tested manually on release/v2.6 based on this commit from 2.6 backport: https://github.com/rancher/rancher/pull/40476
N/A
Need to test with ECR private registries and regular private registries.
=> Check if secret already exists before migrating

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_cluster_secrets.go, pkg/client/generated/management/v3/zz_generated_cluster_template_revision.go, pkg/client/generated/management/v3/zz_generated_cluster_template_revision_status.go
@geethub97 @HarrisonWAffel Mistake on my part, Rancher v2.6.11 will use RKE v1.3.19 and RKE v1.3.20 will be for next release with out of band KDM.
=> [v2.6] update rke to v1.3.19-rc1 for v2.6.11

Dockerfile.dapper, scripts/check-release-images-exist
`docker manifest inspect` does not support OCI manifest, see https://github.com/rancher/rancher/issues/40492#issue-1579690051 for details
Switch to `skopeo` to check images
Drone build step should succeed (especially for `rancher/mirrored-skopeo-skopeo:v1.10.0` as that has an OCI manifest)
Check build step `check-release-images-exist`
=> [release/v2.7] Check release images using skopeo

tests/framework/clients/corral/config.go, tests/v2/validation/standalone/README.md
https://github.com/rancher/qa-tasks/issues/626
there was a default value for the corral repo that has some overhead when using local images to test with
remove the default registry, and suggest this in the README for new users instead of enforcing the default.
=> removing default value for corral repo to reduce overhead

tests/framework/clients/corral/config.go, tests/v2/validation/standalone/README.md
https://github.com/rancher/qa-tasks/issues/626
there was a default value for the corral repo that has some overhead when using local images to test with
remove the default registry, and suggest this in the README for new users instead of enforcing the default.
=> remove corral repo (backport to 2.6)

pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/store.go
Kubernetes 1.25 has removed support for `PodSecurityPolicy`'s, however several Rancher components deploy them by default via helm. Helm tracks all of the resources it deploys so that it can fully manage them during upgrades or uninstall operations. However, helm does not handle the scenario wherein one of the managed resources no longer has API support for a given Kubernetes version. In such a case, Helm will error out and the deployed chart will become unmanageable, preventing uninstalls/upgrades/any changes at all. This presents a problem for several aspects of Rancher, however this PR simply focuses on the management of the System-Upgrade-Controller. 
As described in the linked issue above, this solution has several steps 
1. The system-upgrade-controller chart has been modified to …
=> [2.7] Delay Planner Execution Based Off Of System-Upgrade-Controller Status

pkg/api/norman/customization/cluster/actions_etcd.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go
https://github.com/rancher/rancher/issues/40433
When we restore the snapshot on an RKE1/RKE2/K3S cluster and choose "restore cluster config, Kubernetes version and etcd", the PSACT is not restored. 
It happens because the field ".spec.defaultPodSecurityAdmissionConfigurationTemplateName" is not set back to the value from the backup. 
This fix is to set the field to the value from the backup.
See the steps in the issue. 
The PR is tested locally in the dev env.   
On an RKE1/RKE2/K3S cluster:
- create a snapshot
- change the defaultPodSecurityAdmissionConfigurationTemplateName
- restore the snapshot
Result:
- see the defaultPodSecurityAdmissionConfigurationTemplateName is set back to the value from the backup 
n/a 
the normal tests around cluster backup/restore 
n/a
=>  Fix the issue that PSACT is not restored on RKE1/RKE2/K3S clusters.

pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/controllers.go, pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
https://github.com/rancher/rancher/issues/40300
There is a potential for the kubeconfigManager to race when creating a user/kubeconfig secret for a v2prov cluster. This is particularly bad on a cold-start of Rancher. 
Testing this is quite difficult, but if can be specifically exasperated by stopping rancher (scale to 0), deleting the kubeconfig secret + v3 token object, then scaling back up to 1 replica. After Rancher starts, validate the kubeconfig token and the v3 token match.
```
kubectl scale deployment rancher -n cattle-system --replicas=0
kubectl delete tokens u-f4b4i23dy3; kubectl delete secret test1-kubeconfig -n fleet-default
kubectl scale deployment rancher -n cattle-system --replicas=1
kubectl get tokens u-f4b4i23dy3 -o json | jq -r .token; kubectl get secret -n fleet-default …
```
=> [release/v2.6] Use one instance of the kubeconfig manager

pkg/auth/providers/common/ldap/ldap_util.go
Go 1.17 defaulted to tls version 1.0 for new tls.Config objects. Go 1.18 and 1.19 default to tls 1.2. This PR pins the min version supported by the client to tls 1.0 to ensure that this continues to work for the 2.6 release line.
=> Pinning TLS Min Version to 1.0 for LDAP

pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go
This is a partial (non-cherry picked) backport of PR https://github.com/rancher/rancher/pull/40500
The managed chart for the system-upgrade-controller cannot have a release name exceeding 53 characters, otherwise fleet will return the following error:
```
Error Encountered Waiting for System Upgrade Controller Deployment To
Roll Out: release name "mcc-haffel-upgrade-test-321-managed-system-upgrade-controller":
invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
and the length must not be longer than 53
```
Unfortunately, the logic within Rancher limits the name to at most 63 characters. This results in the failure to deploy the chart depending upon the length of the cluster name (since the cluster name is included within the managed …
=> Limit the SUC release name to at most 52 characters

pkg/data/dashboard/cluster_data.go, pkg/rancher/rancher.go
https://github.com/rancher/rancher/issues/40664
A 500 or 503 can be encountered during encryption config migration. This PR makes a change to allow for 500 or 503s in addition to 409's on migration.
=> [release/v2.7] Allow 500 or 503 on cluster encryption config migration and local cluster creation

pkg/channelserver/channelserver.go
Fix the issue where the returned default version for rke2/k3s is not the highest because versions are sorted as a list of strings.
https://github.com/rancher/rancher/issues/40694
When we calculate the default version for rke2/k3s, it treats and sorts version candidates as a list of strings. As a result, version `v1.24.9+rke2r2` became a higher version than `v1.24.10+rke2r1` and was returned. 
Now, we treat version candidates as a list of `semver.Version` and use the [server.Sort()](https://pkg.go.dev/github.com/blang/semver/v4#Sort)  to sort it properly. 
see the original issue 
When running Rancher locally in the dev env, the correct default version (`v1.24.10+rke2r1`) is returned by the backend; therefore, the UI  does not mark it as experimental. 
n/a
n/a
n/a
=> Fix the default version for rke2/k3s 

pkg/channelserver/channelserver.go
This is the forward port of the PR https://github.com/rancher/rancher/pull/40720  
The [original issue](https://github.com/rancher/rancher/issues/40694) is found in rancher v2.6-head but is not reproducible in v2.7-head because the default rke2/k3s version is 1.25.x where the patch version is a single-digit value in v2.7 
I do not create a forwarding GH issue because this is not reproducible in 2.7-head. But I can make one if it is desired.
=> [2.7] Fix the default version for rke2/k3s

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/ingresses/template.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go
https://github.com/rancher/qa-tasks/issues/405
**Note:** 
This validation test takes around 16 mins to complete which is more than default timeout for the test that's why we need to use -timeout option with value either greater than 16 mins or 0. Similar to below command
`go test providers.go etcd_backup_restore.go etcd_only_backup_restore_test.go -v -timeout 0`
Also it will also requires one k8s version and CNI provider in the cattle config file as per below:
```
kubernetesVersion: 
- v1.24.8+rke2r1
cni:
- calico
```
=> Add validation test for etcd only backup and restore

pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/controllers.go, pkg/controllers/provisioningv2/rke2/machinenodelookup/controller.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go
Forwardport of: https://github.com/rancher/rancher/pull/40660
https://github.com/rancher/rancher/issues/40080
There is a potential for the kubeconfigManager to race when creating a user/kubeconfig secret for a v2prov cluster. This is particularly bad on a cold-start of Rancher. 
Testing this is quite difficult, but if can be specifically exasperated by stopping rancher (scale to 0), deleting the kubeconfig secret + v3 token object, then scaling back up to 1 replica. After Rancher starts, validate the kubeconfig token and the v3 token match.
```
kubectl scale deployment rancher -n cattle-system --replicas=0
kubectl delete tokens u-f4b4i23dy3; kubectl delete secret test1-kubeconfig -n fleet-default
kubectl scale deployment rancher -n cattle-system --replicas=1
kubectl get tokens …
```
=> [release/v2.7] Forwardport: Use one instance of the kubeconfig manager

pkg/catalogv2/system/system.go, pkg/controllers/dashboard/chart/chart.go, pkg/controllers/dashboard/chart/fake/manager.go, pkg/controllers/dashboard/controller.go, pkg/controllers/dashboard/cspadaptercharts/controller.go, pkg/controllers/dashboard/fleetcharts/controller.go, pkg/controllers/dashboard/fleetcharts/controller_test.go, pkg/controllers/dashboard/hostedcluster/controller.go, pkg/controllers/dashboard/hostedcluster/controller_test.go, pkg/controllers/dashboard/systemcharts/controller.go, pkg/controllers/dashboard/systemcharts/controller_test.go, pkg/rancher/rancher.go
#40685
The rancher webhook is now deployed in downstream clusters. This caused an issue where, in airgap scenarios, the webhook and the pods that were deploying the webhook would not use the specified airgap registry. This change allows the agent to pass down an override image, when applicable.
The systemcharts install logic now accepts an override image, which is passed down by the agent. 
In the case where an override image was specified for the webhook, the systemDefaulRegistry value for the webhook's chart will not be set. In addition, the override image will be specified using the `values.image.repository` field. 
In addition, the chart.Manager (used by system charts for installing/upgrading charts) now accepts a parameter for an override image. All other consumers of this logic …
=>  Changing webhook in remote to use the right image

pkg/controllers/provisioningv2/managedchart/managedchart.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/common_test.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go
Release names for bundles deployed by fleet must not exceed 53 characters, however the current `SafeConcatName` function used is only limiting these values to 63 characters or less. In scenarios where the release name exceeds 53 the bundle will fail to deploy. 
Limit bundle names and release names to 53 characters at most, this conforms with the fleet naming requirements.
1. Happy path testing
+ Create an RKE2/K3s cluster with a very long name, such as `haffel-test-very-long-name-for-edge-cases-and-stuff`
+ run `kubectl get bundles.fleet.cattle.io -A` and ensure that all bundles are less than or equal to 53
2. Rancher Upgrade Testing
+ Create an RKE2/K3s cluster on an older version of Rancher where this issue is not seen
+ Wait for the cluster to become available 
+ Watch the bundles …
=> [2.6 Backport] Limit bundle release names to 53 characters

pkg/controllers/provisioningv2/managedchart/managedchart.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/common_test.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go
Release names for bundles deployed by fleet must not exceed 53 characters, however the current `SafeConcatName` function used is only limiting these values to 63 characters or less. In scenarios where the release name exceeds 53 the bundle will fail to deploy. 
Limit bundle names and release names to 53 characters at most, this conforms with the fleet naming requirements.
1. Happy path testing
+ Create an RKE2/K3s cluster with a very long name, such as `haffel-test-very-long-name-for-edge-cases-and-stuff`
+ run `kubectl get bundles.fleet.cattle.io -A` and ensure that all bundles are less than or equal to 53
2. Rancher Upgrade Testing
+ Create an RKE2/K3s cluster on an older version of Rancher where this issue is not seen
+ Wait for the cluster to become available 
+ Watch the bundles …
=> Limit bundle names and release names to 53 characters

pkg/apis/rke.cattle.io/v1/cluster.go, pkg/provisioningv2/rke2/planner/config.go
We need to merge this PR first, then update the Go mod file in the [rancher/webhook PR](https://github.com/rancher/webhook/pull/198). 
Except for the Go mod file, the rest of the rancher/webhook PR is ready for review.
https://github.com/rancher/rancher/issues/40755
When PSACT is used in the rke2 cluster and we upgrade the cluster from k8s 1.24 to 1.25, the Secret holding the generated admission config file is updated by rancher-webhook because the API version inside the config file is changed from v1beta1 to v1; meanwhile, the planner in Rancher keeps monitoring the RKEControlPlane and updating the Plan.   But there is a time lag between Rancher getting the updated Secret and the Plan. As a result, the planner sends the old Plan and the content from the new Secret to the control plane …
=> Fix RKE2 upgrade failure

pkg/controllers/provisioningv2/cluster/controller.go
We have a corresponding mgmt cluster for each provisioning cluster.  The mgmt cluster's value is in sync with the provisioning cluster. 
Previously, the value for `DefaultPodSecurityAdmissionConfigurationTemplateName` is not synced from the provisioning cluster to the mgmt cluster. 
This PR adds the missing sync for completeness, although it doesn't affect anything functionally because the mgmt cluster object is bypassed by all handlers as its annotation indicates it is administrated by the provisioning cluster.
=> add the missing sync of the field Default PSACT 

pkg/settings/setting.go
rancher/dashboard and rancher/ui have branched for 2.7.2 - `latest` builds will begin including code for 2.7 q2
* This change ensures the rancher/rancher `release/v2.7` points to the right rancher/ui and rancher/dashboard builds in `UiIndex` and `UiDashboardIndex` setting defaults, respectively
* By default `-head` versions use these builds instead of the embedded builds 
Updated settings on an existing instance and verified the dashboard/ui load
=> update uidashboardindex and uiindex settings to reference release-2.7.2

pkg/apis/provisioning.cattle.io/v1/rke.go
CI won't pass for https://github.com/rancher/rancher/pull/40730 until the apis are updated and pulled into the webhook.
=> Add dynamic schema spec to machine pools

pkg/catalogv2/helm/helm3.go
JIRA: [SURE-5139](https://jira.suse.com/browse/SURE-5139)
If the obj data is less than 3 bytes, checking magiczip string gives error as the codebase checks for first three bytes of the data by indexing which causes panic.
Check obj data only if it has more than 3 bytes of data.
=> Ignore obj being as helm release obj if data is too small

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Fixes: https://github.com/rancher/aks-operator/issues/97
=> [dev-v2.7] Bump aks-operator to rc6

pkg/image/origins.go
This is to fix the error in this CI build https://drone-publish.rancher.io/rancher/rancher/9282/3/2
Add the image source code origins for the following two new images 
- mirrored-sig-storage-snapshot-controller 
- mirrored-sig-storage-snapshot-controller-webhook 
They are from the new charts introduced and used  by RKE2 (https://github.com/rancher/rke2-charts/pull/303)
=> Prepare for RC6 - update the image source code origins

pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
An error was shown on the cluster immediately after creation while another controller was waiting to populate the dynamic schema.
Log a debug message instead and skip reconciliation.
Tested manually, no error and cluster provisioned successfully.
Just CI
N/A
N/A
=> Log waiting for dynamic schema instead of error

pkg/auth/providers/common/actions.go, pkg/controllers/management/auth/auth_config.go, pkg/controllers/management/auth/auth_config_test.go
When admins disable an auth provider through the API (by editing the auth config resource or using Terraform), they switch the `enabled` field to false. Cleanup runs, but after it, the admins cannot re-enable the provider.
Our auth provider logic for all of them is such that the backend does not treat each new setup request as a new POST request. It actually looks at the current state found in an auth config. Specifically, it looks for a reference to an "application secret" (named differently for each provider), instead of **always** looking at only the secret found in the request.
If the auth config is bare, that is, has only basic metadata fields and no reference to the application secret, then the backend detects that and uses the secret in the request. But if the config is not bare …
=> Reset an auth config's fields when admins disable it through API

pkg/api/norman/customization/cluster/actions_etcd.go, pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go
https://github.com/rancher/rancher/issues/40899
After restoring the etcd backup on a downstream cluster, the Default Pod Security Policy selection is not reset to the value in the backup.
This happens to both RKE1 and RKE2 node-driver clusters.
It happens because we never sync back the value from the backup to the Cluster object 
Add the missing syncing. 
This PR also fixes the minor issue that the value of `status.appliedPodSecurityPolicyTemplateId` is not cleared up after upgrading a 1.24 cluster with PSP enabled to 1.25. 
Run this PR in dev env, and perform the restore following the steps in the issue, I can confirm the value of  Default Pod Security Policy is set to the one from the backup. 
n/a 
The scenario described in the issue. 
n/a
=> Fix PSP restore 

pkg/settings/setting.go
This is needed to be able to backup Elemental resources.
This is a newer version/rebase of https://github.com/rancher/rancher/pull/39064.
Elemental Operator namespace needs to be included in the system namespaces in Rancher in order for Backup to properly work. 
Add Elemental namespace to the list of system ones.
Tested manually on my lab.
Manually added all resources needed to be able to backup Elemental resources and did the backup/restore test.
It will be done in Elemental CI.
N/A. 
This change should be transparent, only a new namespace is added in the list.
=> Add cattle-elemental-system to list of system namespaces

tests/scripts/prime/compare-registry.sh, tests/scripts/prime/scan-registry.sh, tests/scripts/rollback/rollback-rancher.sh, tests/scripts/upgrade/upgrade-rancher.sh
Currently, there are a number of different standalone scripts that are spread out throughout different local machines amongst QA. These particular scripts are used in release testing and validation checks. The owner of those scripts is typically the one who runs the scripts, but if they are not around and the scripts are needed, it's a chore having to track the automation down.
There needs to be a central location for more individuals to access the scripts, this way, more individuals can run various release checks easier.
Created a new `rancher/rancher/test/scripts` folder that will host the standalone scripts. To start off, I shared the following folders/scripts:
- `upgrade/upgrade-rancher.sh` -> Upgrade a Docker installation of Rancher
- `rollback/rollback-rancher.sh` -> Rollback …
=> Add new scripts folder for standalone scripts

go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum, tests/v2/codecoverage/package/Dockerfile
Changes:
- bump UI tags to v2.7.2-rc7
- bump rke to v1.4.4-rc6
=> Prepare for v2.7.2-rc7

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/hardening/rke2/account-update.sh, tests/framework/extensions/hardening/rke2/account-update.yaml, tests/framework/extensions/hardening/rke2/harden_nodes.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go
Currently, the Go test framework allows for provisioning RKE2 custom clusters. By default, these are non-hardened clusters. In realistic customer environments, hardened clusters are at the forefront, so we need to be able to support this in our testing. This PR addresses this problem by providing the option to harden the custom RKE2 clusters.
This is a multi-step solution, please find a summary of the changes incorporated:
- There needed to be an option available to select whether or not the user wishes to harden the cluster. This is done by adding a new Hardened bool type in the config.go struct. Inside the user's cattle-config.yaml, they will have to define a new hardened value and set it to true or false.
- In the custom_clusters_test.go file, new functions HardenNodes, …
=> [2.6 Backport]Add hardening config for rancher provisioned rke2 clusters

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_rke2_upgrade, tests/validation/tests/v3_api/test_airgap.py, tests/validation/tests/v3_api/test_service_discovery.py, tests/validation/tests/v3_api/test_windows_cluster.py, tests/validation/tests/v3_api/test_workload.py
Forward port PR - https://github.com/rancher/rancher/pull/40855
https://github.com/rancher/qa-tasks/issues/491
Sidekick test fails to start nginx container along with ranchertest/mytestcontainer due to port 80 is already occupied.  
This PR serves the purpose to fix the issue by changing from the nginx container to redis:latest container.
=> newimage for sidekick backport

tests/validation/tests/v3_api/resource/terraform/gke/gke.tf
Need to resolve the ability to create Hosted GKE Rancher servers using the [HA Deploy Job](https://jenkins.int.rancher.io/job/rancher_qa/job/rancher-v3_ha_deploy/).
When running the HA Deploy Jenkins job for GKE Rancher servers, we are getting the following error. in the Console Output Logs:
```
14:31:18.25  ------------------------------ Captured log call -------------------------------
14:31:18.25  __init__.py                306 WARNING  error: b'\nError: Failed to query available provider packages\n\nCould not retrieve the list of available versions for provider\nhashicorp/google: no available releases match the given constraints ~> 3.42.0,\n>= 4.47.0, != 4.49.0, != 4.50.0, < 5.0.*\n\n'
14:31:18.25  __init__.py                306 WARNING  error: b'\nError: Could not load …
```
=> Update Google Provider version in gke.tf

tests/framework/extensions/hardening/k3s/harden_nodes.go
K3s hardening in the v2.7 branch is referencing RKE2 instead of K3s. This is only happening for this cluster type in this branch; I validated RKE2/K3s in v2.6 branch are fine. Additionally, RKE2 in the v2.7 branch points to the correct directory path.
Updated the K3s hardening directory path to reference K3s and not RKE2.
=> Fix directory path for hardening K3s

cmd/agent/main.go, package/run.sh, pkg/rkenodeconfigclient/certificates.go, pkg/rkenodeconfigclient/certificates_test.go, pkg/rkenodeconfigclient/client.go
Prior changes to the node agent `run.sh` file resulted in the agent improperly determining the nodes IP address in certain environments.  This resulted in scenarios where multiple nodes would register with the same IP address. The agent was changed to gather the public IP address using DNS, however in environments where all nodes share a single public IP via a network gateway or other infrastructure this poses issues during node registration. This issue occurs in custom clusters.
The change to use DNS to determine node IP was done in an attempt to determine the filename used to generate the `kubelet_serving_certificate` certificate file for the node. Before the prior PRs, the agent had no awareness of what IP address RKE1 was using to generate the certificate files, resulting in an …
=> [2.7] Update kubelet certificate Verification by Node Agent

cmd/agent/main.go, package/run.sh, pkg/rkenodeconfigclient/certificates.go, pkg/rkenodeconfigclient/certificates_test.go, pkg/rkenodeconfigclient/client.go
This is a cherry picked backport of #40939 
Prior changes to the node agent `run.sh` file resulted in the agent improperly determining the nodes IP address in certain environments.  This resulted in scenarios where multiple nodes would register with the same IP address. The agent was changed to gather the public IP address using DNS, however in environments where all nodes share a single public IP via a network gateway or other infrastructure this poses issues during node registration. This issue occurs in custom clusters.
The change to use DNS to determine node IP was done in an attempt to determine the filename used to generate the `kubelet_serving_certificate` certificate file for the node. Before the prior PRs, the agent had no awareness of what IP address RKE1 was using to generate …
=> [2.6] Backport kubelet cert validation

tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go
https://github.com/rancher/qa-tasks/issues/407
**Note:**
- This validation test takes around 20 mins to complete which is more than default timeout for the test that's why we need to use -timeout option with value either greater than 20mins or 0. Similar to below command
`go test providers.go etcd_bkp_restore_test.go -v -timeout 0`
- Also it will require at least two k8s version in ascending order in the cattle config file and at least one CNI provider as per below:
```
rke2KubernetesVersion: 
- v1.23.16+rke2r1
- v1.24.10+rke2r1
cni:
- calico
```
=> Add validation test for etcd backup and restore with cluster config

tests/v2/validation/provisioning/k3s/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke1/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke2/post_kdm_oob_release_test.go
https://github.com/rancher/qa-tasks/issues/612
- This PR adds KDM checks(as mentioned in the issue above) in the RKE1, RKE2 and K3S package that validates released k8s versions on rancher server are present or not and provisions single node, all role clusters using released k8s versions. In order to validate whether new k8s versions are present on rancher server, we need to add those k8s version in the cattle-config.yaml file as per below:
```
nodesAndRoles:
- etcd: true
controlplane: true
worker: true 
quantity: 1 
nodesAndRolesRKE1: 
- etcd: true
controlplane: true
worker: true 
quantity: 1 
rke2KubernetesVersion: 
- v1.23.16+rke2r1
- v1.24.10+rke2r1
rke1KubernetesVersion: 
- v1.23.16-rancher2-1
- v1.24.10-rancher4-1
k3sKubernetesVersion: 
- v1.23.16+k3s1
- …
```
=> Add validation test for post kdm OOB release checks

tests/framework/extensions/namespaces/create.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_psa_test.go, tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/qa-tasks/issues/543
In this PR we are covering the RBAC cases for the new feature PSA.  
PodSecurityAdmission is a new feature in k8s where we allow cluster owners/admins to configure a few labels to capture pod security. Other members such as Project owner/cluster member/Project members/Project read-only permissions should not be able to configure the labels at namespace level. This only fixes the namespace level permissions and not project level permissions.
=> Adding automation script to validate PSA rbac

package/Dockerfile
Bump rancher-webhook to v0.3.2 and rancher-csp-adapter to v2.0.1
Related to rancher/charts#2516 - since the adapter and webhook are system charts, their pinned versions must be updated in rancher after new versions are created.
=> Un-rc rancher-webhook and rancher-csp-adapter

tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go
https://github.com/rancher/qa-tasks/issues/407
**Note:**
- This validation test takes around 20 mins to complete which is more than default timeout for the test that's why we need to use -timeout option with value either greater than 20mins or 0. Similar to below command
`go test providers.go etcd_bkp_restore_test.go -v -timeout 0`
- Also it will require at least two k8s version in ascending order in the cattle config file and at least one CNI provider as per below:
```
rke2KubernetesVersion: 
- v1.23.16+rke2r1
- v1.24.10+rke2r1
cni:
- calico
```
=> [Backport] Add validation test for etcd backup and restore with cluster config

tests/v2/validation/provisioning/k3s/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke1/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke2/post_kdm_oob_release_test.go
https://github.com/rancher/qa-tasks/issues/612
- This PR adds KDM checks(as mentioned in the issue above) in the RKE1, RKE2 and K3S package that validates released k8s versions on rancher server are present or not and provisions single node, all role clusters using released k8s versions. In order to validate whether new k8s versions are present on rancher server, we need to add those k8s version in the cattle-config.yaml file as per below:
```
nodesAndRoles:
- etcd: true
controlplane: true
worker: true 
quantity: 1 
nodesAndRolesRKE1: 
- etcd: true
controlplane: true
worker: true 
quantity: 1 
rke2KubernetesVersion: 
- v1.23.16+rke2r1
- v1.24.10+rke2r1
rke1KubernetesVersion: 
- v1.23.16-rancher2-1
- v1.24.10-rancher4-1
k3sKubernetesVersion: 
- v1.23.16+k3s1
- …
```
=> [Backport] Add validation test for post kdm OOB release checks

tests/v2/validation/provisioning/k3s/custom_cluster.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
Node driver and custom cluster creation for rke1, rke2 and k3s clusters is bound to the provisioning test suite and not available to be used in other tests. Refactoring the files to be made use for other test suites.
In this PR, we are abstracting the cluster creations for all the cluster types and making it public, so the cluster creation function can be made use in other PRs as well.
Verified the custom cluster creation for RKE2 clusters. will need to run a few more checks from the jenkins job.
=> Refactoring cluster provisioning for rke1,rke2 and k3s cluster creation

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Issue: https://github.com/rancher/charts/pull/2516
=> [dev-v2.7] Bump aks and eks opeator to final versions

tests/v2/validation/provisioning/k3s/custom_cluster.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
Node driver and custom cluster creation for rke1, rke2 and k3s clusters is bound to the provisioning test suite and not available to be used in other tests. Refactoring the files to be made use for other test suites.
In this PR, we are abstracting the cluster creations for all the cluster types and making it public, so the cluster creation function can be made use in other PRs as well.
Verified the custom cluster creation for RKE2 clusters. will need to run a few more checks from the jenkins job.
=> 26 Refactoring cluster provisioning for rke1,rke2 and k3s cluster creation

tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/qa-tasks/issues/644
Currently we do not have a rbac suite for v1 P0 cases to check restricted admin RBAC. In this PR we aim to automate the P0 cases for the restricted admin RBAC
We are leveraging the current rbac suite that addresses cluster owner/member. The P0 cases for the restricted admin RBAC . We are adding those additional cases and also add a few changes on how we validate for restricted admins 
Note: This PR slightly depends on fixes from https://github.com/rancher/rancher/pull/40792
=> Automate P0 restricted admin use cases

tests/framework/extensions/users/users.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go
Backport: https://github.com/rancher/qa-tasks/issues/644
Currently we do not have a rbac suite for v1 P0 cases to check restricted admin RBAC. In this PR we aim to automate the P0 cases for the restricted admin RBAC
We are leveraging the current rbac suite that addresses cluster owner/member. The P0 cases for the restricted admin RBAC . We are adding those additional cases and also add a few changes on how we validate for restricted admins 
Note: This PR slightly depends on fixes from https://github.com/rancher/rancher/pull/40792
=> Adding restricted admin P0 cases

tests/framework/clients/corral/corral.go, tests/framework/clients/rancher/config.go, tests/framework/extensions/pipelineutils/setup.go, tests/framework/extensions/registries/registries.go, tests/framework/pkg/environmentflag/environmentflags.go, tests/framework/pkg/environmentflag/zz_environmentflags.go, tests/v2/validation/Dockerfile.e2e, tests/v2/validation/Jenkinsfile.e2e, tests/v2/validation/ranchercleanup/main.go, tests/v2/validation/rancherha/main.go, tests/v2/validation/registries/config.go, tests/v2/validation/registries/registry_test.go, tests/v2/validation/scripts/build_corral_packages.sh, tests/v2/validation/scripts/build_registries_images.sh, tests/v2/validation/scripts/rancher_cleanup.sh, tests/v2/validation/scripts/setup_registries_environment.sh
Depends on: https://github.com/rancherlabs/corral-packages/pull/6
There isn't automated way to start building a Rancher deployment with downstream clusters with configured private registries.
With the code in this PR we can use the corral client to build the test environment with three private registries. 
- Registry with no authentication for Rancher. Rancher is also deployed.
- Registry with no authentication for a downstream Cluster 
- And a final registry with authentication enabled for a downstream Cluster
Using the go framework the code proceeds to configure Rancher creating an admin user with his password and an auth token.
The Rancher client creates two downstream clusters one with an authentication enabled registry and the other disabled.
Then it validates the pod images have the …
=> Initial registries setup and validation

tests/framework/extensions/users/users.go
Watch interface needs an admin client. when using tests if we are trying to use a standard user client, watch interface gets a forbidden error.
This is to make sure we get the user admin client and make use of it in the watch interface
=> Watch interface needs an admin client

tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
Recently, there has been an uptick in the number of issues QA has seen regarding etcd/cp sharing a node. As such, we should add test cases in our provisioning automation that will always account for this scenario.
In node provider and custom clusters, I added a new test case that has etcd/controlplane share a node, while the worker role is on a separate node; in short, there will be test cases accounting for 2 nodes (1 etcd/cp and 1 worker).
None, since this is just adding new test cases modeled after existing ones. I will run automated runs, however.
Jenkins runs will be given offline to the reviewers.
=> [v2.7] Add etcd/cp shared node test cases to provisioning suite

tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
Recently, there has been an uptick in the number of issues QA has seen regarding etcd/cp sharing a node. As such, we should add test cases in our provisioning automation that will always account for this scenario.
In node provider and custom clusters, I added a new test case that has etcd/controlplane share a node, while the worker role is on a separate node; in short, there will be test cases accounting for 2 nodes (1 etcd/cp and 1 worker).
None, since this is just adding new test cases modeled after existing ones. I will run automated runs, however.
Jenkins runs will be given offline to the reviewers.
=> [v2.6]Add etcd/cp shared node test cases to provisioning suite

tests/framework/extensions/sshkeys/downloadsshkeys.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver.go, tests/v2/validation/provisioning/ssh.go
Adding ssh test package to run tests that require ssh to run. Also adjusted downloadsshkeys.go to send a byte instead of string to be used in the node object.
https://github.com/rancher/qa-tasks/issues/451
There were tickets around CPU usage being too high and we wanted to add automated checks to more consistently check CPU usage during releases.
Adding this automation will allow us to more frequently check if the CPU Usage issue were to ever come back. Also with downloadsshkeys.go we are now able to run any ssh related tests within the provisioning package. Currently just added to rke2 package, but since Node object is also used in rke1 and k3s, I will also add there after approval.
Tested the actual ssh command manually multiple times to ensure that it works.
Will run jenkins job
The …
=> Adding ssh test to allow check for CPU usage

pkg/controllers/management/clusterprovisioner/provisioner.go
https://github.com/rancher/rancher/issues/41107
In certain cases, it is possible to have the cluster health syncer controller, the cluster provisioner controller, and the statsAggregator controller race with each other. While I have not been able to prove it definitively, my theory on what  exasperates this race condition is a slow downstream API server (or slow link between the Rancher installation and the downstream cluster). 
This PR makes a change to the clusterprovisioner controller's Create lifecycle, and makes it stop attempting to set a message on the Waiting condition if the condition status has already been defined. This should prevent thrashing if the Create lifecycle is unsuccessful (and the healthsyncer is able to reconcile the cluster).
I have tested importing and …
=> Don't overwrite Waiting condition message on v3 cluster object if already set in clusterprovisioner

pkg/apis/rke.cattle.io/v1/plan/plan.go, pkg/controllers/provisioningv2/controllers.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/plansecret/plansecret.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/provisioningv2/rke2/planner/certificaterotation.go, pkg/provisioningv2/rke2/planner/config.go, pkg/provisioningv2/rke2/planner/drain.go, pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go, pkg/provisioningv2/rke2/planner/errors.go, pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/initnode.go, pkg/provisioningv2/rke2/planner/instructions.go, pkg/provisioningv2/rke2/planner/instructions_test.go, pkg/provisioningv2/rke2/planner/messages.go, pkg/provisioningv2/rke2/planner/planentry.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/planner_test.go, pkg/provisioningv2/rke2/planner/store.go
https://github.com/rancher/rancher/issues/41080
~This may also work on https://github.com/rancher/rancher/issues/39167~
The planner currently will re-bootstrap a cluster with a brand new datastore if the entire controlplane + etcd nodes have been removed. This is not ideal behavior, and gets in the way of disaster recovery situations.
Pause processing of plans if there is no current init node, none of the etcd nodes have plans delivered to them, and the cluster is "initialized"
TO BE FILLED OUT
=> Stop planner from processing machine plans if the cluster is missing its controlplane/etcd nodes and has been initialized

package/Dockerfile
When using user namespace remapping [userns-remap](https://docs.docker.com/engine/security/userns-remap/), Docker fails to load a specific layer of the `rancher/rancher` image because it cannot map the UID associated with a file that was copied into that layer to a UID on the host system because the UID in the container (114762) falls outside the mappable range.
When pulling/using the rancher image with `userns-remap` enabled:
```
$ docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --userns=host --privileged rancher/rancher:latest
[...]
docker: failed to register layer: Error processing tar file(exit status 1): Container ID 114762 cannot be mapped to a host ID.
```
The cause is the file /usr/bin/etcdctl in the image, which has an unusually high UID (114762).  This is because, by …
=> Update tar command in package/Dockerfile so it doesn't copy file owners

pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/rancher/migrations.go
Rancher panics because the machine config does not have an associated dynamic schema
Only check for dynamic schema if `APIVersion` is `rke-machine-config.cattle.io/v1`, indicating it is from rancher-machine.
=> Only validate dynamic schema for rancher/machine infra

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix, tests/validation/tests/v3_api/test_aks_cluster.py
The OnTag runs that are ran currently lack a number of different provisioning tests. These include node provisioning tests for RKE2/K3s and custom cluster provisioning tests for RKE2/K3s. This PR aims to add support for those missing provisioning tests so that they are covered in the OnTag runs.
Added EC2/Azure node provider support for RKE2/K3s in the `Jenkinsfile_ontag_matrix` file. In the same file, added support for custom cluster provisioning for RKE2/K3s.
Additionally, this PR changes AKS version to get the second highest version available. In Azure Portal, the highest version available typically is not the most stable version. This PR fixes that concern.
Jenkins runs will be provided to the reviewers.
=> [v2.7] Add additional provisioning tests to OnTag

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix, tests/validation/tests/v3_api/test_aks_cluster.py
The OnTag runs that are ran currently lack a number of different provisioning tests. These include node provisioning tests for RKE2/K3s and custom cluster provisioning tests for RKE2/K3s. This PR aims to add support for those missing provisioning tests so that they are covered in the OnTag runs.
Added EC2/Azure node provider support for RKE2/K3s in the `Jenkinsfile_ontag_matrix` file. In the same file, added support for custom cluster provisioning for RKE2/K3s.
Additionally, this PR changes AKS version to get the second highest version available. In Azure Portal, the highest version available typically is not the most stable version. This PR fixes that concern.
Jenkins runs will be provided to the reviewers.
=> [v2.6] Add additional provisioning tests to OnTag

tests/v2/validation/provisioning/rke2/custom_cluster.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go
RKE2 was passing forward the whole `provisioning.Config` instead of just bool value, when that is all that is needed. This PR updates that to make the code a bit simpler and to reduce overhead.
Replaced `provisioning.Config` with just `bool` for the harden parameter that the user defines in their configuration files.
Offline Jenkins runs will be given to reviewers.
=> Replace provisioning.Config with just bool for harden

package/Dockerfile
=> Prepare For 2.6.12-rc1

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
During release testing, we noted that the quotations in the defined environmental variables are causing credentials to be interpreted as an actual string. This causes unexpected failures to occur.
Removed the quotations completely and the syntax of how the environmental variables are defined to address this issue.
=> [v2.6] Remove quotations in OnTag environmental variables

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
During release testing, we noted that the quotations in the defined environmental variables are causing credentials to be interpreted as an actual string. This causes unexpected failures to occur.
Removed the quotations completely and the syntax of how the environmental variables are defined to address this issue.
=> [v2.7] Remove quotations in OnTag environmental variables

tests/validation/tests/v3_api/test_create_ha.py
Forward port of https://github.com/rancher/rancher/pull/40642
=> Adding the RANCHER_PSP_ENABLED parameter to be able to toggle to true or false depending on the k8s cluster

Dockerfile.dapper
K3D doesn't publish a binary for s390x, so it breaks the s390x phase
Added conditional that will skip the installation if the arch is s390x
Drone check
=> Added if statement where if the arch is s390x it will skip the k3d installation

pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagent.go
https://github.com/rancher/rancher/issues/40768
If the same backup operator backup is used to perform multiple migrations, the system-agent will not be updated past the first migration. This stems from the use of a "generation" integer that is incremented by the backup-operator. The issue is that the backup contains the generation as a set integer, and the value will be rolled back to that integer on restore. This poses a problem in a new cluster because SUC will not detect a plan change and thus not reinstall the system-agents on the downstream cluster.
Add the UID of the clusters.provisioning.cattle.io object to the generation secret, to guarantee uniqueness. This UID will be unique between installations, which is important when using the same backup for multiple migration/restore …
=> Add cluster-uid to the system-agent generation secret

Dockerfile.dapper
K3D doesn't publish a binary for s390x, so it breaks the s390x phase
Added conditional that will skip the installation if the arch is s390x
Drone check
=> [v2.6] Added if statement where if the arch is s390x it will skip the k3d installation

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
During release testing, found that the URL for both the Go tests and Python tests are both shaving the `https://` prefix, when only that is needed for the Go tests. As a result, some Python tests are failing as they expect the `https://`. This PR fixes that issue.
Created local variable that will only use the updated URL that removes the `https://` for the Go tests only. Otherwise, it is left alone for the Python tests.
=> [v2.7] Separate Go tests URL from Python tests URL

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
During release testing, found that the URL for both the Go tests and Python tests are both shaving the `https://` prefix, when only that is needed for the Go tests. As a result, some Python tests are failing as they expect the `https://`. This PR fixes that issue.
Created local variable that will only use the updated URL that removes the `https://` for the Go tests only. Otherwise, it is left alone for the Python tests.
=> [v2.6] Separate Go tests URL from Python tests URL

tests/framework/extensions/prime/primechecks.go, tests/framework/extensions/rancherversion/config.go, tests/v2/validation/prime/README.md, tests/v2/validation/prime/prime_test.go
In the `prime_test.go` file, we currently are only checking the branding and versioning. There are additional UI checks we do in release testing, namely ensuring the pulled images are using the right registry.
This PR addresses that by adding additional UI checks.
Refactored the `prime_test.go` to have separate all different test functions. Additionally, added two new checks:
- Check the system default registry.
- Check the pulled image from the workloads in the system project page.
On the chance that a non-Prime server is running the `prime_test.go` test, logic has been put in place to account for this.
Jenkins runs will be given to reviewers offline.
=> Add additional Prime UI checks

go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum, pkg/client/generated/management/v3/zz_generated_aci_network_provider.go
=> Prepare for 2.6.12-rc2

Dockerfile.dapper, package/Dockerfile
=> Prepare for `2.6.12-rc3`

go.mod, go.sum, package/Dockerfile, pkg/apis/go.mod, pkg/apis/go.sum
=> Prepare For `2.6.12-rc4`

pkg/controllers/management/clusterstats/statsaggregator.go
https://github.com/rancher/rancher/issues/41070
Prior, in the case of a timeout the there would be no receiver on
the channel. This would cause the go routine to block.
Demonstration of the issue: https://go.dev/play/p/LZhJ3slW1Xf
Now, closing the channel will signal the go routines completion. This will not
be prevented by the timeout.
Demonstration of the solution. Can swap the timeout to simulate either the scenario where the parent function receives timeout signal first or the scenario where the go function finishes before the timeout: https://go.dev/play/p/H5j2TQGRp_S
=> Fix go routine leak

tests/framework/extensions/clusters/kubernetesversions/default.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
Continuation of https://github.com/rancher/rancher/pull/41287
Addresses request for qa-task- 608, to remove testing.T from `extensions > clusters > kubernetesversions > default.go`
=> remove testing.T from default.go extension

pkg/apis/management.cattle.io/v3/authn_types.go, pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go, pkg/auth/providers/ldap/ldap_provider.go, pkg/auth/providers/saml/saml_provider.go, pkg/client/generated/management/v3/zz_generated_okta_config.go
SAML does not offer an interface for searching for principals. Therefore, in order to allow such a search, it would be necessary to use a separate mechanism, similar to how the Shibboleth provider currently works with OpenLDAP-powered search.
Change the backend to use the same logic currently in-use by Shibboleth to allow the Okta provider to also search for principals in an OpenLDAP backend.
* Enabled the Okta provider without OpenLDAP.
* Checked that groups list when clicking the principal box and can be selected, but no users appear.
* Checked that upon typing a username a principal is generated and is available to select, but no actual search happens.
* Enabled the Okta provider with OpenLDAP, providing information on an OpenLDAP server.
* Checked that it's possible to search for …
=> Enable Okta to use OpenLDAP for user and group search

scripts/provisioning-tests, scripts/run, tests/integration/DEBUG.md, tests/integration/pkg/cluster/clusters.go, tests/integration/pkg/defaults/defaults.go, tests/integration/pkg/systemdnode/systemnode.go, tests/integration/pkg/tests/custom/custom_test.go
It would be ironic if the provisioning-tests successfully passed for this PR, but ideally we can provide an example of a failed run.
https://github.com/rancher/rancher/issues/41334
=> Enhance provisioning failure logs to include more objects

pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/rke2/bootstrap/controller.go, pkg/controllers/provisioningv2/rke2/common.go, pkg/controllers/provisioningv2/rke2/machineprovision/controller.go, pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go, pkg/controllers/provisioningv2/rke2/planner/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/rke2/provisioningcluster/controller_test.go, pkg/controllers/provisioningv2/rke2/unmanaged/controller.go, pkg/provisioningv2/rke2/planner/errors.go, pkg/provisioningv2/rke2/planner/etcdcreate.go, pkg/provisioningv2/rke2/planner/etcdrestore.go, pkg/provisioningv2/rke2/planner/instructions.go, pkg/provisioningv2/rke2/planner/planentry.go, pkg/provisioningv2/rke2/planner/planner.go, pkg/provisioningv2/rke2/planner/planner_test.go, pkg/provisioningv2/rke2/planner/probe.go, pkg/provisioningv2/rke2/planner/s3args.go, pkg/provisioningv2/rke2/planner/store.go, scripts/quick
https://github.com/rancher/rancher/issues/41080
Also:
https://github.com/rancher/rancher/issues/41174
https://github.com/rancher/rancher/issues/40994
Partially:
https://github.com/rancher/rancher/issues/41024
Today, it is impossible to restore a K3s/RKE2 cluster from etcd snapshot if you lose the underlying machines.
This PR adds quite a bit of functionality to the planner. It introduces a few new conditions (namely `Bootstrapped` and `Stable`) that is used to indicate whether the cluster has been bootstrapped and stable, and uses this condition to block reconciliation of a cluster if there are no "alive" etcd machines within the cluster. It adds the ability to skip safe removal of an etcd node for emergency purposes, and uses this functionality to allow for complete removal of the etcd …
=> Allow etcd snapshot restoration on a fresh set of etcd nodes

tests/framework/extensions/clusters/bundledclusters/list.go, tests/framework/extensions/clusters/clustertypes.go, tests/framework/extensions/clusters/kubernetesversions/all.go, tests/framework/extensions/clusters/kubernetesversions/available.go, tests/framework/extensions/clusters/kubernetesversions/default.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
BACKPORT FOR v2.6
https://github.com/rancher/qa-tasks/issues/608
Currently, the Go automation specifically asks for the K8s version to be inputted in the user's config file. Within Rancher, if you do not specify a K8s version while provisioning, the default version is selected. `rke up` works in a similar fashion.
Implemented an enhancement to the provisioning tests for RKE1/RKE2/K3s, where the k8s version is optional and if it is not provided, then the default K8s version will be selected and used.
RFE - no reproduction steps
Automation task - no manual testing conducted
Run both locally and via Jenkins Freeform job to ensure desired behavior seen
N/A
N/A
=> qa-task-608 backport to release/v2.6 branch

Dockerfile.dapper
`yq` was added in https://github.com/rancher/rancher/pull/29664/files but the script lines that require `yq` were removed in https://github.com/rancher/rancher/pull/36283/files#diff-4dc87a76100aa810a62ff49805181a37a94d05a814447664b487220ac2783527. 
@PennyScissors Do we still need it?
Remove `yq` from build environment
=> [release/v2.7] yq no longer needed in build env

tests/framework/extensions/kubeapi/tokens/patchtokens.go, tests/v2/validation/token/token_test.go
https://github.com/rancher/qa-tasks/issues/673
When creating a token , there was no validation happening by default and groupPrincipals is setting as null. When trying to edit that token , it's not allowing to save the token yaml.  
Created a PatchToken in extensions/kubeapi, and testing that patching a created token is successful
=> Invalid groupPrincipals token patch test

tests/validation/tests/v3_api/test_airgap_ha.py
https://github.com/rancher/qa-tasks/issues/392
setting bootstrap password via helm template was not working
* mimic ha_deploy job (allow extra settings to be applied during helm install)
* manually create bootstrap secret
* re-enable password setting after installing rancher
tested using jenkins
=> QA 392: improve airgap HA bootstrap setting

tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/k3s/master/variables.tf, tests/validation/tests/v3_api/resource/terraform/rke2/master/instances_server.tf, tests/validation/tests/v3_api/resource/terraform/rke2/master/variables.tf, tests/validation/tests/v3_api/resource/terraform/scripts/optional_write_files.sh, tests/validation/tests/v3_api/test_import_k3s_cluster.py, tests/validation/tests/v3_api/test_import_rke2_cluster.py
When using automation to deploy a hardened HA cluster for k3s or rke2 on Rancher 2.7.2, it requires a specialized PSA configuration as noted in https://ranchermanager.docs.rancher.com/reference-guides/rancher-security/psa-restricted-exemptions.
This enables the ability to add that specialized PSA configuration. This also gives an opportunity to add other files in, such as easier ways to fill out a config.yaml or HelmChartConfig files to customize some of the default HelmChart installs.
It can be passed through the new terraform variable, `optional_files`. This takes data in the form of a file name separated by a comma to the data it should write to the file (from a URL). More files can be passed with a space separator, e.g. `<file name 1>,<url of raw data 1> <file name 2>,<url of raw data …
=> Add ability to pass files in during k3s and rke2 installs

tests/framework/extensions/kubeapi/tokens/patchtokens.go
backport surrounding this issue: https://github.com/rancher/qa-tasks/issues/673
When creating a token , there was no validation happening by default and groupPrincipals is setting as null. When trying to edit that token , it's not allowing to save the token yaml.  
The fix wasn't backported by dev. So this isn't a full backport of the test. But bringing in the patchtokens functionality to 2.6 as requested by @igomez06 
Created a PatchToken in extensions/kubeapi, and testing that patching a created token is successful
=> adding patchtokens to extensions/kubeapi

tests/framework/extensions/clusters/eks/eks_cluster_config.go, tests/framework/extensions/clusters/kubernetesversions/available.go, tests/framework/extensions/pipeline/configuration.go, tests/framework/extensions/pipeline/releaseupgrade.go, tests/v2/validation/pipeline/scripts/build_registries_images.sh, tests/v2/validation/pipeline/scripts/rancher_cleanup.sh, tests/v2/validation/pipeline/scripts/setup_registries_environment.sh
- Refactored:
- Added volume-type options to cluster matrix for release upgrade, specifically for AWS.
- Changed the comparison logic for the cluster Kubernetes versions to support and detect minor versions.
**Pipelines Updates**
- Refactored:
-  Made a fix to private registry scripts' directory level
=> Release Tests - Private Registry Fix & Upgrade HA support improvements

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py, tests/validation/tests/v3_api/test_eks_v2_hosted_cluster.py
The EKS certification tests is using v1 and not v2. This needs to be updated as v1 has since been deprecated and we are seeing several issues in the certification test. See them below:
- The certification test itself passes, but there is no nodegroup defined. In other words, the cluster is made through individual nodes and not through a managed node group.
- Node group specification came in EKS v2, hence why this happens in the certification test.
As far as this PR is concerned, there is a small change needed for the `test_eks_v2_hosted_cluster.py` to include `requestSpotInstances` and `resourceTags` in order to get the EKS cluster to properly provision.
A separate PR changing the internal automation to reference the `test_eks_v2_hosted_cluster.py` has already been merged. This PR ensures …
=> [v2.6] Update EKS certification test to have required fields

tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py, tests/validation/tests/v3_api/test_eks_v2_hosted_cluster.py
AKS and EKS v2 hosted cluster tests are auto-deleting themselves before the certification tests have a chance to run. This is because we are calling for the cluster deletion to occur before the certification tests are called.
Disable the clusters auto-deleting themselves.
=> [v2.7] Set autouse to False in AKS/EKS v2 tests

tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py, tests/validation/tests/v3_api/test_eks_v2_hosted_cluster.py
AKS and EKS v2 hosted cluster tests are auto-deleting themselves before the certification tests have a chance to run. This is because we are calling for the cluster deletion to occur before the certification tests are called.
Disable the clusters auto-deleting themselves.
=> [v2.6] Set autouse to False in AKS/EKS v2 tests

.github/renovate.json
N/A
Renovate bot currently has over [30 opened PRs](https://github.com/rancher/rancher/pulls/app%2Frenovate-rancher) for version bumps. It is inefficient to keep multiple parallel PRs, as each merge may lead to a cascading impact of rebasing in the remaining opened PRs. 
Limit the max number of concurrent PRs to `4`. So that at any point in time there are only `4` branches / PRs created by renovate bot.
As currently there are more than the new concurrent limit, most in-flight PRs will need to be merged before new PRs are created.
N/A
N/A
N/A
N/A
N/A
=> [release/v2.7] renovate: Limit number of concurrent PRs/Branches

pkg/catalogv2/system/system.go, pkg/catalogv2/system/system_test.go, pkg/settings/setting.go, pkg/settings/setting_test.go
Increase the time between refreshes 
Upgrade the rancher version and checked if the timer changed
unit tests
=> Changing the default system chart refresh time to 21600 seconds

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix, tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py, tests/validation/tests/v3_api/test_eks_v2_hosted_cluster.py
AKS and EKS clusters are deleting themselves upon successful provisioning. This is an issue as the certification tests are not being called right after, which defeats the point of the automation.
Removed the `create_project_client` function that is deleting the cluster based upon the cluster creating.
=> [v2.7] Stop hosted clusters from deleting before tests run

tests/validation/tests/v3_api/common.py, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix, tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py, tests/validation/tests/v3_api/test_eks_v2_hosted_cluster.py
AKS and EKS clusters are deleting themselves upon successful provisioning. This is an issue as the certification tests are not being called right after, which defeats the point of the automation.
Removed the `create_project_client` function that is deleting the cluster based upon the cluster creating.
=> [v2.6] Stop hosted clusters from deleting before tests run

pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/activedirectory/activedirectory_provider.go, pkg/auth/providers/common/ldap/ldap_util.go, pkg/auth/providers/common/provider_util.go, pkg/auth/providers/common/provider_util_test.go, pkg/auth/providers/ldap/ldap_client.go, pkg/auth/providers/ldap/ldap_provider.go, pkg/auth/providers/migration/activedirectory_migration.go, pkg/auth/providers/migration/activedirectory_migration_test.go, pkg/multiclustermanager/app.go
If Rancher is configured to use AD for authentication, and AD user accounts get moved between OUs, then when the users log back into Rancher a new user is created and all their old permissions are not preserved.
This is because the principalID was based on the DN of each user.  When the OU changes, it results in a new DN, which results in a new Rancher user.
Active Directory has an attribute, objectGUID, which is unique and immutable.  We now use that attribute as the basis for the principalID
The repro steps in the original issue are correct.
With a fresh Rancher install, set up Active Directory as the auth provider.  Verify that you can login as usual with valid users from that auth provider.  All Rancher functionality should appear normal.
You can verify that the user has been assigned …
=> Use GUID for the PrincipalID for Active Directory

Dockerfile.dapper, chart/templates/_helpers.tpl, chart/templates/post-delete-hook-cluster-role.yaml, chart/templates/post-delete-hook-psp.yaml, chart/templates/validate-psp-install.yaml, chart/tests/README.md, chart/tests/deployment_test.yaml, chart/tests/ingress_test.yaml, chart/tests/issuer_test.yaml, chart/tests/psp_test.yaml, chart/values.yaml, dev-scripts/helm-unittest.sh, scripts/chart/test
#41455
The current default for `global.cattle.psp.enabled` is not compatible with k8s 1.25. This requires users to manually set this value to `false` when installing on this version of k8s. As 1.25+ is becoming more widely adapted, this pain point will become more apparent for our users.
- There is no default for `global.cattle.psp.enabled` (i.e. the default value is "").
- If this value is "" and the cluster does not support PSPs (i.e. is k8s version 1.25 or higher), then PSPs will not be used.
- If this value is "" and the cluster does support PSPs (i.e. is k8s version 1.24 or lower), then PSPs will be used.
- If the value is set to true, no capabilities check will be used, and the chart will attempt to use PSPs. This will cause the above error message for k8s 1.25 clusters.
- If the …
=> Improving k8s 1.25 compatibility for rancher/chart

chart/templates/ingress.yaml, chart/tests/ingress_test.yaml
The ingress rule in the Rancher chart is missing a `path`, which is required by some ingress controllers.
Add a path to the Ingress rule in the Rancher chart to make it compatible with ingress controllers that require a path to be present.
Install Rancher with the updated chart.
I did the following tests:
* Installing Rancher with the updated chart into a K3s cluster
* Installing Rancher with the 2.7.0 chart and upgrading it with the updated chart into a K3s cluster
* Installing Rancher with the updated chart into a RKE2 cluster
* Installing Rancher with the 2.7.0 chart and upgrading it with the updated chart into a RKE2 cluster
Rancher installations and upgrades should work.
=> Add a path to the Ingress rule in the Rancher chart

pkg/capr/common.go, pkg/capr/planner/etcdrestore.go, scripts/provisioning-tests, tests/v2prov/operations/etcdsnapshot.go, tests/v2prov/tests/custom/operation_etcdsnapshot_inplace_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_combined_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_inplace_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_multietcd_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_test.go
https://github.com/rancher/rancher/issues/41563
CAPR only keeps nodes that have a matching machine UID label -- this poses problematic when dealing with a migrated Rancher and a snapshot from "before the migration", as the nodes within the snapshot will not have the correct machine ID label. While we do attempt to run the cluster, there is no guarantee that the kubelet will update its labels before we come through to prune the nodes.
To make this operation safer, we will keep all nodes that match the machine ID label or have a corresponding machine.Status.NodeRef.Name value.
This specifically makes it possible to handle the cases where a node has not had its noderef backpopulated into Machine object, or a snapshot is from a pre-migration Rancher installation.
I ran a basic etcd snapshot …
=> [CAPR] Keep all nodes with machine noderef node value

pkg/auth/providers/ldap/ldap_provider.go, pkg/auth/providers/saml/saml_provider_test.go
This compliments PR https://github.com/rancher/rancher/pull/41269 
Adds three relatively simple unit tests. These check that Okta+SAML providers are performing searches through the LDAP provider when one is configured, and continuing to fall back to principal generation otherwise.
This changes the `ldap.IsNotConfigured` function to use an Error type rather than a formatted string as its underlying value. The behavior should be identical, using a type simply allows the mock to produce an equivalent error for testing purposes.
=> Add unit tests for Okta+LDAP principal search

pkg/cluster/agent_customization_test.go, pkg/controllers/management/clusterdeploy/clusterdeploy_test.go, pkg/controllers/provisioningv2/cluster/controller_test.go
https://github.com/rancher/rancher/issues/41035
Add unit tests for backend cluster agent customization functionality.
Added unit tests based on this design plan, approved by Hostbusters and QA
Updated test plan
I verified all tests pass by running the ones I added via,
```
go test ./pkg/cluster ./pkg/controllers/management/clusterdeploy ./pkg/controllers/provisioningv2/cluster
```
=> Add cluster agent unit tests

pkg/controllers/capr/machineprovision/args.go
Some NodeDrivers need to have access to the same secrets they used when creating the node. For example, the Openstack node driver needs access to the cacert file that is used to connect to Openstack.
https://github.com/rancher/rancher/issues/39222
The Openstack node driver fails to delete nodes when a cacert is used to connect to the Openstack cluster. The cause is that the secret containing the certificate is not mounted on the ``rancher-machine` pod that deletes the node. See the issue for more details.
run the constructFilesSecret function when deleting the node to add the required secrets to the rancher-machine pod
The fix was tested on the EngCloud Openstack cluster.
=> Make sure the required secret is available to the rancher-machine pod when deleting a node

scripts/run
CI fix to have `scripts/run` check for args.
This just fixes an error message in the logs, not the actual problem of
```
2023/05/17 12:54:29 listen tcp 127.0.0.1:6060: bind: address already in use
time="2023-05-17T12:54:23Z" level=fatal msg="starting kubernetes: preparing server: init cluster datastore and https: listen tcp :6443: bind: address already in use"
```
=> Fix run script to check for args

pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go, pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go, tests/v2prov/tests/fleet/fleetcluster_test.go
This adds the tests for the fleet agent customization settings.
The integration test uses the local cluster to verify defaults exists and can be changed.
=> Add test for agent customization in fleetcluster

tests/validation/tests/v3_api/resource/terraform/aks/aks.tf, tests/validation/tests/v3_api/resource/terraform/aks/variables.tf
The HA deploy automation job appears to be failing with AKS due to how the SKU tier is formatted in `aks.tf`. The automation incorrectly states that the SKU used is wrong, when it is not.
What's incorrect is the syntax we are using in TF to call it, so that needs to be adjusted.
Refactored the TF call for SKU tier.
Jenkins run will be given offline to reviewers.
=> [v2.7] Modify how SKU is formatted in `aks.tf`

tests/validation/tests/v3_api/resource/terraform/aks/aks.tf, tests/validation/tests/v3_api/resource/terraform/aks/variables.tf
The HA deploy automation job appears to be failing with AKS due to how the SKU tier is formatted in `aks.tf`. The automation incorrectly states that the SKU used is wrong, when it is not.
What's incorrect is the syntax we are using in TF to call it, so that needs to be adjusted.
Refactored the TF call for SKU tier.
Jenkins run will be given offline to reviewers.
=> [v2.6] Modify how SKU is formatted in aks.tf

tests/v2/validation/registries/config.go, tests/v2/validation/registries/registry_test.go
Private registries tests create new registries only for running the tests on clusters. 
Creating new registries during test setup take time between tests runs. If there are multiple runs needed.
This adds the capability of setup configuration using existing registries. This is mainly for downstream clusters.
The local cluster is configured during the setup build with Corral. And there's a [change already in](https://github.com/rancherlabs/corral-packages/pull/9) corral packages for this.
This adds support for both type of registries. Auth and No Auth.
Testing adding existing registries flags with the new existing registries configuration keys.
Test run without specifying registries. Test keep creating new registries for the setup as expected.
None
Just the private registries automated …
=> [v2.6] - Adding external registry configuration capability to registry tests

tests/v2/validation/provisioning/rke2/hostname_truncation.go, tests/v2/validation/provisioning/rke2/hostname_truncation_test.go
There were recent changes to the framework to add support for cluster/fleet agent customization. One area we forgot to update was in the new `hostname_truncation_test.go`, we didn't update the cluster configuration function for RKE2/K3S. This PR makes that fix.
Add the required parameter needed to not have this function call out error out for the hostname truncation feature.
It's a very small fix, but can provide a freeform job if it's needed.
=> Fix RKE2/K3S cluster config in hostname truncation test

package/Dockerfile, pkg/capr/common.go, pkg/capr/planner/certificaterotation.go, pkg/capr/planner/certificaterotation_test.go, pkg/capr/planner/config.go, pkg/capr/planner/encryptionkeyrotation.go, pkg/capr/planner/etcdrestore.go, pkg/capr/planner/idempotent.go, pkg/capr/planner/planner.go, pkg/settings/setting.go, tests/v2prov/nodeconfig/nodeconfig.go, tests/v2prov/systemdnode/systemnode.go
https://github.com/rancher/rancher/issues/41587
https://github.com/rancher/rancher/issues/41125
https://github.com/rancher/rancher/issues/41174
This PR tackles CI flakiness with CAPR provisioning tests in Rancher. A couple of issues were identified, and are addressed as part of this PR.
1. Overriding the Type of systemd unit and clearing the `NOTIFY_SOCKET` environment variable lead to premature actions against K3s/RKE2 as the units do not wait for activation.
2. After clearing the `NOTIFY_SOCKET`, the planner started delivering plans that would restart units repeatedly, and K3s/RKE2 are brittle at handling successive restarts.
3. The `kube-scheduler` certificate rotation instructions did not rotate the correct files.
4. The `rm -rf /var/lib/rancher/rke2/server/manifests/rke2-*.yaml` …
=> [CI] Improve CAPR reliability + drop systemd-node workaround for cgroups

tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_test.go
In the rbac test suite, we have a test case where we create an RKE1 custom cluster. We have a new change that went in recently to provision rke1 clusters where there were a few parameters [Advanced options] that need to be added. Resolving the missing parameters in this PR to the rbac suite.
=> resolving conflicts

pkg/controllers/management/aks/aks_cluster_handler.go, pkg/controllers/management/eks/eks_cluster_handler.go, pkg/controllers/management/gke/gke_cluster_handler.go
Issue??
Someone apparently saw this here https://github.com/rancher/rancher/issues/41299#issuecomment-1523015726
If an empty secret is returned then attempting to set `cluster.Status.ServiceAccountTokenSecret` will cause panic
I added a check for nil pointer that will likely not solve the root cause of the problem but the controller won't panic and return some meaningful error and include debug logs.
=> [DNM investigation needed] Fix panic when SA token secret is empty for eks cluster

go.mod, go.sum
We get a panic on some apiserver logs when in debug mode
Fix was made in https://github.com/rancher/apiserver/pull/23
This just updates the apiserver version to include the fix by running `go get -u github.com/rancher/apiserver`
1. Start Rancher with the --debug flag
1. Create a standard user with no roles or privileges
1. Login as that standard user
1. navigate to `v1/management.cattle.io.globalroles/podsecurityadmissionconfigurationtemplates-manage`
=> Upgrade the apiserver version

pkg/controllers/capr/machineprovision/controller.go
Force deletion wasn't working
Check if the deletion job has passed as well as failed when considering the `force-machine-remove` annotation.
Tested happy path with a 3 node all roles cluster and a single node cluster, was able to both rotate nodes and remove the cluster as expected. Tested deleting the cloud credential after provisioning, verified that force deletion worked now works as expected.
CI
Deleting a cluster, versus deleting a single node
Shouldn't be any regressions, deletion should still work as expected for both happy path and with force deletion case.
=> Fix force deletion for machineprovision

tests/validation/tests/v3_api/resource/cluster-ha.yml, tests/validation/tests/v3_api/resource/cluster.yml
As of Rancher v2.7.2, PSACT support has been included. For QA's automation regarding importing RKE1 clusters, we have not updated the `cluster.yml` to account for this new feature. As a result, automation is failing as the RKE1 cluster is not successfully able to be stood up.
Updated the `cluster.yml` and `cluster-ha.yml` files to include the `services` block with the appropriate parameters needed for a PSACT cluster.
Locally, provisioned a standalone RKE1 cluster with the updated YAML and it was successful.
Automated testing will have to come after this PR is merged to ensure all of the expected tests run successfully.
=> Update cluster.yml to include PSACT

tests/v2/integration/catalogv2/system_charts_version_test.go
Pin webhook tests are currently causing the webhook to stay on an older version this PR disables those tests to allow other pipelines to pass before we find a fix.
=> Disable pin webhook tests.

pkg/controllers/dashboard/hostedcluster/controller.go, pkg/settings/setting.go
In the current implementation, it's not possible to install a custom helm chart for hosted providers. When a cluster is created,   helm chart from the upstream repo will be installed.
We need a way to install custom charts that are built for every PR as part of our e2e test suite https://github.com/rancher/aks-operator/blob/master/.github/workflows/e2e.yaml.
Providing an alternative helm chart repository will not work for us. 
This PR adds a new setting for skipping helm chart installation and will be used for development purposes only.
Issue: https://github.com/rancher/highlander/issues/4
=> Add setting to skip hosted cluster chart installation

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
OnTag runs currently utilize our freeform job when running through the automation. This is fine and works, but we should make it a point to consolidate all of our OnTag automation into one location. This PR does that by referencing a newly created Jenkins job.
Updating the name of the build job used to reference the Go jobs used during OnTag automation.
=> Update build job for Go matrix certification automation

pkg/controllers/management/aks/aks_cluster_handler.go
Upgrading Rancher version from v2.7.3 to v2.7-head when using Rancher on Docker causes a panic if an AKS cluster has been previously provisioned. After this panic, Rancher restarts and recovers.
This panic can be avoided by identifying the null object that triggers it and returning a meaningful error. This results in Rancher not crashing during the upgrade.
The reported issue specifies how to reproduce the error in a Docker installation of Rancher. May need to repeat the process to reproduce it multiple times to get the error, as stated in the original description.
Upgraded v2.7.3 to a version with this code change and the error was caught with no panic. Rancher runs as expected after the upgrade.
=> Fix aks clusters panic when upgrading rancher version

tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go
https://github.com/rancher/qa-tasks/issues/717
- Updated the pods status check logic for capturing the error if the pod is not up and running.
- Below is the output from jenkins logs where it captures the pod error after the cluster is restored:
```
/root/go/src/github.com/rancher/rancher/tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go:626
17:12:13.300          	Error:      	Received unexpected error:
17:12:13.300          	            	Error in running pods : [ERROR: helm-install-rke2-snapshot-controller-crd-rq226: container helm is in CrashLoopBackOff ERROR: helm-install-rke2-snapshot-controller-zxfpl: container helm is in CrashLoopBackOff]
17:12:13.300          	Test:       	TestEtcdSnapshotRestore/TestEtcdSnapshotRestoreWithK8sUpgrade
17:12:13.300      --- FAIL: …
```
=> Fix pod status check logic

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/etcdsnapshot/etcdsnapshot.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_etcd_backup_test.go
Adding RBAC tests for snapshot creation on an RKE2 cluster
- Perform snapshot action on a cluster
- Verify only Cluster owner and restricted admin have access. Cluster member, project owner and member do not have access. And get `Resource type [provisioning.cattle.io.cluster] is not updatable` error
N/A
Adding these automated tests - https://github.com/rancher/qa-tasks/issues/410
N/A
N/A
=> Adding rbac tests for Cluster Action : snapshot on an RKE2 cluster

tests/framework/extensions/charts/gatekeeperconfig.go, tests/framework/extensions/charts/gatekeeperresources.go, tests/framework/extensions/charts/opaconstraint.go, tests/framework/extensions/kubeapi/customresourcedefinitions/delete.go, tests/framework/pkg/environmentflag/environmentflags.go, tests/framework/pkg/environmentflag/zz_environmentflags.go, tests/v2/validation/Jenkinsfile_pre_post_upgrade, tests/v2/validation/charts/gatekeeperallowednamespaces_test.go, tests/v2/validation/charts/gatekeeperallowednamespacespostupgrade_test.go
https://github.com/rancher/qa-tasks/issues/471 
Customers are reporting that upgrading Rancher fails when a new namespace is added to Rancher and the customer has an OPA Gatekeeper constraint that restricts the creation of namespaces.
This test creates a Jenkins pipeline that checks that Rancher can be successfully upgraded as long as the required list of namespaces is allowed by Gatekeeper. It also adds functions that create OPA constraints & Gatekeeper config objects
This solution relies on many namespaces that are necessary for rancher and gatekeeper to function being excluded from the Gatekeeper constraint. some of these are static, such as "cattle-gatekeeper-system" and some are dynamically generated, such as pod-impersonation-helm-op-xxxx or cattle-impersonation-user-xxxx-token …
=> [2.7]Jenkins pipeline for pre and post rancher upgrade testing

tests/framework/extensions/nodes/node_status.go, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/etcd_node_delete_and_replace_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver.go, tests/v2/validation/provisioning/rke1/etcd_node_delete_and_replace_test.go, tests/v2/validation/provisioning/rke2/etcd_node_delete_and_replace_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver.go
https://github.com/rancher/qa-tasks/issues/660
- This PR adds validation test for ETCD node deletion in RKE1/RKE2/K3S clusters.
- Also it fixes the logic in `isNodeReady` function. Previously it was taking cluster ID and only checking for one node to be in Active state and returning from the fuction. Made changes so that it checks for all nodes to be in Active state in a cluster.
Here's the example config for nodesAndRoles used for testing this PR:
```
nodesAndRoles:
- etcd: true
controlplane: false
worker: false 
quantity: 3
- etcd: false
controlplane: true
worker: false 
quantity: 1
- etcd: false
controlplane: false
worker: true 
quantity: 1
nodesAndRolesRKE1: 
- etcd: true
controlplane: false
worker: false 
quantity: 3
- etcd: false
controlplane: true
worker: false …
```
=> Add validation test for etcd node deletion

tests/framework/extensions/clusters/clusters.go
`clusters.go` file has been using the integration defaults. This causes tests to wait for less than usual for the watch interfaces in this file.
Updated import, and removed a duplicated import which has seen while fixing this.
=> Fix defaults package import in the test extensions

tests/framework/extensions/secrets/template.go, tests/v2/validation/registries/registry_test.go, tests/v2/validation/upgrade/workload_test.go
The current Private Registries tests only validate RKE1 clusters. 
This change adds support to provision RKE2 and K3S clusters.
Additional:
The test structure was refactored and the provisioning method `NewK3SRKE2ClusterConfig` was updated to include the registry hostname and a registry secret as parameter.
I added also a parameter to set the Secret Type in the Secrets' `NewSecretTemplate`
A small fix when running the test with flag `UseExistingRegistries`. When Rancher hadn't the system default registry the test setup code path wasn't getting reached.
Ran tests locally
```
--- PASS: TestRegistryTestSuite (3175.16s)
--- PASS: TestRegistryTestSuite/TestRegistriesK3S (510.44s)
--- PASS: TestRegistryTestSuite/TestRegistriesRKE (1912.02s)
--- PASS: TestRegistryTestSuite/TestRegistriesRKE2 …
```
=> Support for k3s and rke2 cluster types in private registries validations

tests/framework/clients/ec2/config.go, tests/framework/extensions/machinepools/machinepools.go, tests/framework/extensions/nodes/ec2/ec2.go, tests/framework/pkg/nodes/nodes.go, tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster.go, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/nodeproviders.go, tests/v2/validation/provisioning/rke1/README.md, tests/v2/validation/provisioning/rke1/custom_cluster.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/README.md, tests/v2/validation/provisioning/rke2/custom_cluster.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go
https://github.com/rancher/qa-tasks/issues/547
with the last addition to custom clusters in the framework, we were limited to only 2 node pools when provisioning.
* refactor to allow any node to be provisioned through ec2 without explicitly defining windows vs. linux. 
* this was done by adding new role `windows` to nodesAndRoles, and adding a new field `roles` for a given ec2Config
* add logic to include public address in the registration command for rke2 (this was causing issues when registering windows nodes)
* for rke1, specify both public and private IP address in registration command
* for ec2.go, refactor to provision all nodes first, then check status = ready to speed up testing time -> O(n) is now O(1) where n = node ready time
tested locally using multiple pools in rke2 with …
=> refactoring custom clusters to allow multi-pool configurations -- including windows

pkg/apis/management.cattle.io/v3/global_types.go, pkg/controllers/management/feature/feature_handler.go, pkg/features/feature.go
PR introduces an additional feature flag for `harvester-baremetal-container-workload` which will be introduced with harvester v1.2.0
The flag is an experimental option, allowing users to enable multi-cluster-management view on the integrated rancher available in the harvester packaging.
feature flag also introduces a handler method, which checks and enables the `harvester` feature flag if required, when the `harvester-baremetal-container-workload` is enabled.
=> Introduce harvester-baremetal-container-workload feature flag

tests/framework/clients/rancher/v1/client.go, tests/framework/extensions/clusters/clusters.go
https://github.com/orgs/rancher/projects/34
Occasionally after a cluster has been provisioned doing a proxy v1 List call using said cluster results in an unknown schema type error.
Add a back off poll
Jenkins job.
=> Added a backoff wait to fix an intermittent unknown schema type error

pkg/controllers/provisioningv2/provisioningcluster/controller.go, pkg/controllers/provisioningv2/provisioningcluster/controller_test.go
When finalizers are removed from a provisioning cluster object, there is a race condition between adding the finalizers back, and the generating framework deleting the generated `rkecluster`, `rkecontrolplane`, `cluster.cluster.x-k8s.io` and `machinedeployment`s.
Skip current iteration until finalizers are present again.
Repro steps are not reliable due to raciness of issue.
- Test types added/modified:
- Unit
- Added test cases surrounding expected invariants to cluster inputs.
No chances for regressions, as we are not affecting any other code paths.
=> Return errskip when finalizers not present

pkg/image/origins.go
Fix broken PRs pipelines due to missing origin of `rancher/mirrored-s3gw-s3gw` image.
=> Add s3gw image origin

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/rke1/componentchecks/etcdversion.go, tests/framework/extensions/workloads/pods/pod_status.go, tests/v2/validation/provisioning/rke1/README.md, tests/v2/validation/provisioning/rke1/custom_cluster.go, tests/v2/validation/provisioning/rke1/custom_cluster_test.go
Currently, we manually perform our support matrix checks. This is tedious because we need to provision each supported RKE1 version for that Rancher release and then check the etcd, canal and flannel versions. We should  have a way to have this automated so that we don't need to manually do this anymore.
This PR checks the etcd, canal and flannel image versions across each supported K8s version for the release for CNIs canal and flannel. This is done through adding a separate test run in the `custom_clusters_test.go` file to eliminate code redundancy when provisioning RKE1 clusters.
Additionally, there was a small bug with not all of the pods status being shown after the cluster successfully provisions; fixed that as part of this PR.
Locally tested against v1.26 and v1.25 with canal and …
=> Add support matrix checks for RKE1 custom clusters

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/psact/createdeployment.go, tests/v2/validation/provisioning/k3s/custom_cluster.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver.go, tests/v2/validation/provisioning/rke1/custom_cluster.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver.go, tests/v2/validation/provisioning/rke2/custom_cluster.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver.go, tests/v2/validation/upgrade/config.go, tests/v2/validation/upgrade/kubernetes_test.go
When we perform fresh install provisioning in the Go framework, we perform additional checks after the cluster is provisioned. These are general validation checks we perform manually alongside actual cluster provisioning. If and when QA performs upgrades on their clusters, we perform the same validation checks as well.
In our automation, we do not have those same additional resource checks when upgrading. This PR adds those checks.
Added additional resource checks to `kubernetes_test.go`, so that after a single cluster upgrade, we are covering the same checks that we have in the fresh install use-cases.
Tested RKE1 and K3S and validated that the resource checks are working as expected, after an upgrade.
Jenkins jobs will be provided to the reviewers offline.
=> Add additional resource checks to upgrade testing

pkg/settings/setting.go
- `rancher/dashboard` and `rancher/ui` have both now branched for 2.7.5
- This change ensures the `rancher/rancher` 2.7 branch points to the correct builds
- These builds are used, when settings are default, when the version ends in `-head` as an alternative to the embedded builds
=> Update references to new 2.7.5 UI branches

tests/v2/validation/Jenkinsfile.e2e
Automation Jenkins job fail due to configuration
The Jenkins e2e pipeline fails when there isn't a second url set for the corral packages.
Add a check to see if the configuraiton is set otherwise default to job variables.
Created a manual job with the same configuration as the jjb definition. Second SCM url not set.
Ran the job with default values. No more errors
Ran the job without the url set. No more errors
Pipeline runs
=> Adding a check in case the corral packages repo url is not set

tests/v2/validation/provisioning/config.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore.go, tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go
https://github.com/rancher/qa-tasks/issues/716
https://github.com/rancher/qa-tasks/issues/714
https://github.com/rancher/qa-tasks/issues/715
This test creates and restores a backup on s3 if the correct configuration is provided . 
This validation test takes around 16 mins to complete which is more than default timeout for the test that's why we need to use -timeout option with value either greater than 16 mins or 0. Similar to below command
go test providers.go etcd_backup_restore.go etcd_only_backup_restore_test.go -v -timeout 0
Also it will also requires one k8s version, CNI provider, and s3BackupConfig in the cattle config file as per below:
```
kubernetesVersion: 
- v1.24.13+rke2r1
- v1.25.9+rke2r1
cni:
- calico
s3BackupConfig:
bucket_name: 
folder:  
region: …
```
=> add etcd backup-restore on s3

pkg/image/charts.go, pkg/image/charts_test.go, pkg/image/utilities/utilities.go
https://github.com/rancher/rancher/issues/41952
The CI step `check-release-images-existing` detects the following missing image tags:
```
ERROR: Summary of missing image(s):
rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:latest
rancher/mirrored-cloud-provider-vsphere-csi-release-driver:latest
rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:latest
rancher/mirrored-sig-storage-csi-attacher:latest
rancher/mirrored-sig-storage-csi-node-driver-registrar:latest
rancher/mirrored-sig-storage-csi-provisioner:latest
rancher/mirrored-sig-storage-csi-resizer:latest
rancher/mirrored-sig-storage-livenessprobe:latest
time="2023-06-12T19:29:56Z" level=fatal msg="exit status 1"
```
ref https://drone-publish.rancher.io/rancher/rancher/9924/5/9
They come from the following chart:
``` …
```
=> add the support for ignoring specified tags in specified charts and system charts

tests/v2/validation/Jenkinsfile.e2e, tests/v2/validation/registries/registry_test.go
No issue. Additional coverage for private registries
Current private registries release validations haven't support for the use cases when the cluster level registry wasn't configure but Rancher has Global set.
Add new validations for RKE1/RKE2/K3S
Local test runs
Provide Jenkins run.
=> [Automation] - Support for private registries test cases with no cluster level config

scripts/provisioning-tests
Provisioning tests periodically fail to deploy the webhook after 5 minutes. This can happen for multiple reasons that may or may not be related to Webhook itself. This PR adds a dump of the rancher logs when the webhook fails to deploy, which will allow us to determine the problem.
=> Dump logs when Webhook fails to deploy during CI.

tests/v2/validation/Jenkinsfile
go validation provisioning Jenkins job was using `release/v2.6` instead of `release/v2.7`, causing the test to fail, since v2.6 is out of date
=> changed Jenkinsfile branch variable from 2.6 to 2.7

README.md
The workflow we have to update this seems to need an update as it changed a link from 2.7 to 2.6 which is not a desired change. This PR applies the changes from the auto-generated PR with that change excluded.
Auto-generated README update PR: https://github.com/rancher/rancher/pull/41974
=> [release/v2.7] update README with latest/stable

package/Dockerfile, package/Dockerfile.agent, tests/v2/codecoverage/package/Dockerfile, tests/v2/codecoverage/package/Dockerfile.agent
Keep BCI version in our base images up to date.
I expect that with our regular flow of creating daily `-head` images and day to day tests from our dev teams should be enough in terms of QAing.
* Unit
* None
_TODO_
* _TODO_
=> [2.7] Bump BCI to 15.5

pkg/controllers/management/secretmigrator/clusters.go, pkg/controllers/management/secretmigrator/clusters_test.go
The cluster object was being updated four times whenever the `cluster-secret-migrator` handler was called, however these updates were no-ops because the cluster was equal. This handler gets enqueued whenever the cluster object actually get's updated, on startup, or after a timeout. This causes the apiserver to be updated much more than normal for cluster resources.
Check if a migration needs to happen before migrating, and only update if there is a change.
* Unit
Summary: Updated existing unit tests to make sure an object is not updated unless it needs to be
- Provision on v2.6.11
- Monitor how many times a given cluster object gets updated via the `rancher-2.6.11-secrets-migrator` user agent
- Upgrade
- Observe less updates from user agent
Secrets migration …
=> Only update cluster if secrets migrated

pkg/controllers/management/clusterprovisioner/driver.go
https://github.com/rancher/rancher/issues/40889
When Rancher restores the etcd snapshot, one of the steps is to [update the cluster](https://github.com/rancher/rancher/blob/f2faf1a8aa1081301e1fe6c21637fe9b7044f188/pkg/controllers/management/clusterprovisioner/driver.go#L136-L139), which fails because of conflicting (see error msg below) if PSP is disabled in the cluster's current spec but was enabled in the backup (and vice versa).
The conflicting error message:
`Operation cannot be fulfilled on clusters.management.cattle.io "c-gdzsq": the object has been modified; please apply your changes to the latest version and try again`
However, the call to update the cluster looks unnecessary because the [driverUpdate](https://github.com/rancher/rancher/blob/f2faf1a8aa1081301e1fe6c21637fe9b7044f188 …
=> Omit the error when the upgrading of the cluster fails in the process of restoring etcd snapshot

pkg/capr/planner/etcdrestore.go, tests/v2prov/cluster/clusters.go
https://github.com/rancher/rancher/issues/41808
This PR contains some general improvements around the v2 provisioning operation tests:
- clear error message
- include the etcdSnapshpt object in the output for troubleshooting
=> general improvements on error messages

tests/v2/validation/registries/config.go, tests/v2/validation/registries/registry_test.go
No issue. Additional coverage for private registries
Current private registries release validations haven't support for the ECR RKE registry use case of Downstream clusters.
Add new test for RKE1 ECR
Local test runs
Provide Jenkins run.
Related for infra creation: https://github.com/rancherlabs/corral-packages/pull/14
=> [Automation] - Adding test coverage for ECR repos

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/image/origins.go
This PR does the following two things:
- bump RKE to v1.4.8-rc2
- add the source of the image `mirrored-kube-vip-kube-vip-iptables`, which [fails the CI](https://drone-pr.rancher.io/rancher/rancher/30696/5/2)
=> bump RKE to v1.4.8-rc2 and fix CI 

pkg/controllers/managementagent/endpoints/endpoints.go
Rancher's cattle-cluster-agent will crash if ingress's backend is not a service.
Ingress's backend maybe is a resource like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: ingress-resource-backend
spec:
rules:
- http:
paths:
- path: /icons
pathType: ImplementationSpecific
backend:
resource:
apiGroup: k8s.example.com
kind: StorageBucket
name: icon-assets
```
https://github.com/alibaba/higress/discussions/360 
crash log:
```bash
E0601 09:09:13.447021      39 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 12171 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3ccd600, 0x6eb69c0)
/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtim …
```
=> Fix crash about ingress backend is not a service

generate.go, pkg/client/generated/management/v3/zz_generated_eks_cluster_config_spec.go, pkg/controllers/options.go, pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml, pkg/data/management/role_data.go, pkg/data/management/rolebuilder.go, pkg/data/management/rolebuilder_test.go
When Rancher starts, we create/update all built-in RoleTemplates, such as (cluster-owner). With new validation going into the webhook, we will no longer allow modification to built-in RoleTemplates or GlobalRoles. Rancher will still need a way to manage the resources, so it must be able to bypass the Webhook validation that blocks mutation to built-in RoleTemplates and GlobalRoles.
We will leverage the Webhook bypass mechanism to allow Rancher to manage built-in RoleTemplats, which requires us to impersonate the Webhook's sudo service account. This can be done using a Wrangler client's `WithImpersonation(..)` method. 
To accomplish this, we need to do the following steps
- Update the code that installs roles to use wrangler clients instead of norman clients
- Add Unit test for changed …
=> Role binding reconciliation

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/psact/createdeployment.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_psa_test.go
Adding RBAC tests for editing cluster and modifying the PSACT value on RKE1/RKE2/K3S clusters.
- Edit the cluster
- Verify only Cluster owner and restricted admin have access to edit the cluster and modify the PSACT value. After modifying the PSACT value, verify creating a deployment fails when the PSACT value is set to "rancher-restricted" while it succeeds otherwise.
- Verify Cluster member, project owner, project member and readonly do not have access to edit the cluster
N/A
Adding these automated tests - [rancher/qa-tasks#610](https://github.com/rancher/qa-tasks/issues/610)
Note: There is new change coming in where the cluster creation would be an extension that will be fixed as part [#780](https://github.com/rancher/qa-tasks/issues/780). So, the test case does not currently include …
=> RBAC tests for GH610

package/Dockerfile
`rancher cluster create --import <cluster>` is broken due to the above issue.
Bump the Rancher CLI version to a version with the fix for the above issue.
Tested `rancher cluster create --import <cluster>` manually.
Tested `rancher cluster create --import <cluster>` manually.
* None
* If "None" - Reason: We don't currently have a test suite for the Rancher CLI. For this small regression, I think it's okay to just make sure the command works again by running it from the latest release.
Summary:
`rancher cluster create --import <cluster>` and make sure the empty cluster is created in Rancher.
None that I can think of given that the command was broken previously.
Existing / newly added automated tests …
=> Bump CLI to v2.7.6-rc1

go.mod, go.sum
The Steve API adds some fields to its output for easier consumption by the UI, but when the UI takes those same objects and tries to update them, Steve was passing through those fields to Kubernetes which did not recognize them.
Steve now removes the fields it added before trying to update the object in Kubernetes.
The issue appears on Kubernetes 1.25.
Create a Kubernetes built-in resource like a Pod.
Open developer tools in the browser.
Try to update the pod in the Cluster Explorer UI, to add or remove labels, for example.
The response headers should NOT include anything like `warning: 299 - unknown field ...`.
* Unit
Issue occurs only for k8s >= 1.25.
Change is in steve, so anything using the /v1 steve API could be affected.
Existing / newly added automated …
=> Update steve to fix unknown fields warning

pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/migration/activedirectory_migration.go
https://github.com/rancher/rancher/issues/41985
At Rancher startup, both the AD migration and Groups refresh processes are kicked off.  For any nontrivial setup, this will result in the refresh process trying to refresh not-yet-migrated users with their DN-based principal and will cause a slew of error messages in the log.  
Additionally, the refresh process is not very fault tolerant.  Things like attempting to migrate a user that no longer exists in AD will kill the migration (which will result in more problems later).  
Allow the RefreshGroupPrincipals function to search appropriately for DN-based principals in addition to GUID-based principals.
This also lowers the backoff time for a failed migration from 10 minutes down to 30 seconds and adds retries in case of any brief network …
=> Update active directory refetchgroupprincipals to use either DN or GUID

pkg/capr/planner/etcdrestore.go, pkg/capr/planner/initnode.go, pkg/capr/planner/planner.go, pkg/controllers/capr/bootstrap/controller.go, scripts/provisioning-tests, tests/v2prov/cluster/clusters.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_combined_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_test.go, tests/v2prov/tests/machineprovisioning/machine_test.go
https://github.com/rancher/rancher/issues/42034
The `rkebootstrap` controller was given a new responsibility around management of the `pre-terminate` CAPI annotation on the corresponding CAPI machine objects. This pre-terminate annotation is to be used for safe removal/quorum loss prevention of deleting etcd nodes from a cluster (due to an order of operations problem with CAPI's management of nodes in a cluster, where it wants to remove infrastructure before the v1 node object).
Additionally, in certain cases, it was possible that the planner would start delivering new plans to etcd nodes and cause `k3s` or `rke2` to restart while in the middle of a safe node removal. 
Finally, provisioning tests were not properly triggering a failure of CI through an inadvertent change introduced with …
=> [CAPR] Fix rkebootstrap controller pre-terminate annotation management and prevent planner from re-electing init node on standard reconciliation

chart/templates/configMap.yaml, chart/tests/configmap_test.yaml, chart/values.yaml, pkg/controllers/dashboard/chart/chart.go, pkg/controllers/dashboard/chart/chart_test.go, pkg/controllers/dashboard/fleetcharts/controller.go, pkg/controllers/dashboard/hostedcluster/controller.go, pkg/controllers/dashboard/systemcharts/controller.go, pkg/controllers/dashboard/systemcharts/controller_test.go, pkg/settings/setting.go
This commit adds the ability to customize the values used to install a cluster's webhook. Users can now store the custom webhook helm values on the cluster object. These values are synced to a ConfigMap in the cluster and are referenced when installing the helm chart.
Scenario: The user wants their downstream webhook to run on with the `hostNetwork=true`
1. User edits the `cluster.management.cattle.io` object for their downstream cluster.
2. User updates the new field `cluster.Spec.ChartValues` [Code](https://github.com/rancher/rancher/compare/release/v2.7...KevinJoiner:rancher:webhook-config?expand=1#diff-14e664fa98838cd14681732355577f709eab97c04ca75bfe33103cd77cccae90R132-R136)
- *Note:* This new field is a `map[string]string` with the key being the name of the chart and the values …
=> Adds configuration for a cluster's webhook values.

tests/framework/clients/rancher/config.go, tests/framework/extensions/settings/shell.go, tests/v2/validation/shell/README.md, tests/v2/validation/shell/shell_test.go
https://github.com/rancher/qa-tasks/issues/807
Automating P0 shell checks
In this PR we are verifying the shell version and a usecase where we check if shell pods have all succeeded. 
Jenkins run
=> Shell P0 checks

pkg/auth/providers/migration/activedirectory_migration.go
https://github.com/rancher/rancher/issues/42144
We need some sort of indicator for the start/finish of the AD migration process
Info log messages added:  `Active directory principalID migration starting` and `Active directory principalID migration complete` will now appear in the logs bookending the process.
Manually verified
* Unit
* None
_TODO_
* _TODO_
=> Adding start/complete info messages for AD migration

tests/scripts/custodian/Dockerfile, tests/scripts/custodian/Jenkinsfile, tests/scripts/custodian/README.md, tests/scripts/custodian/aws.yaml, tests/scripts/custodian/azure.yaml, tests/scripts/custodian/gcp.yaml, tests/scripts/custodian/tag-to-save.yaml, tests/scripts/custodian/untag-to-delete.yaml
https://github.com/rancher/qa-tasks/issues/28
QA should have a way to manage its own resources automatically. 
This PR introduces the use of cloud custodian, a tool that cleans our resources based on rules we define for it. Currently, the work done includes AWS instances and NLBs. In the future, we can add support for GCR and Azure, and extend AWS custodian support further. Please see the introduced README for more details.
The changes between this and the last proposal are mostly just changing from GH actions -> Jenkins
Everything in this PR is a proof of concept, so I have the following 'placeholders' until we decide on a definite route:
* automation is not cron based yet, and can only be triggered manually
* the custodian is in `--dry-run` mode, meaning it will report the number of …
=> adding custodian scripts for QA

pkg/controllers/capr/bootstrap/controller_test.go, pkg/serviceaccounttoken/secret.go, pkg/serviceaccounttoken/secret_test.go
Without this patch, if the first secret stored in the service account object is invalid, the impersonation module will time out waiting for it to become valid. This change ensures that invalid secrets are discarded from the object and only the most recent, known working one is kept. The pointer to the service account is updated so that later references to the secret name will be correct.
This change also ignores the "not found" error if it both fails to update the service account and delete the accompanying secret, because if the service account doesn't exist then the secret is probably already deleted by virtue of its owner reference.
If there's a problem with the service account token secret, it will stay on the service account and new secrets will get created to replace it, but the …
=> Update service account object with attached secret

cleanup/binding-clean.yaml, pkg/agent/clean/orphan_bindings.go, pkg/agent/clean/orphan_bindings_test.go, pkg/controllers/management/auth/crtb_handler.go, pkg/controllers/management/auth/manager.go, pkg/controllers/management/auth/prtb_handler.go, pkg/controllers/managementuser/rbac/handler_base.go, pkg/controllers/managementuser/rbac/prtb_handler.go, pkg/controllers/managementuser/rbac/reconcile_roletemplate.go, pkg/rbac/common.go, pkg/rbac/common_test.go
When users add a new CRTB or PRTB, Rancher ensures that the various role bindings and cluster role bindings are also created in the cluster for which that CRTB or PRTB had been created.
Rancher uses the RTB name in the **label** name of the synced cluster role binding. Kubernetes does not allow label names to be longer than 63 characters.
```
kind: ClusterRoleBinding
metadata:
labels:
{namespace}-{very-long-rtb-name}: owner-user
```
If  the string `{namespace}-{very-long-rtb-name}` is longer than 63 characters, Kubernetes rejects the request to create the object.
Users can run into this if they create a CRTB or PRTB when bypassing Norman and specifying a long name (close to 63 characters).
Use the [SafeConcatName](https://github.com/rancher/wrangler/blob/39a4707f0689cc97ca955f5eea5d0b37e16 …
=> Safely concatenate long namespace and binding name for CRTBs and PRTBs

pkg/controllers/management/drivers/base_driver.go, pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/nodedriver/nodedriver.go, pkg/controllers/nodedriver/nodedriver_test.go, pkg/rancher/rancher.go, scripts/test
Node drivers are not downloaded in each rancher replica. Because the replicas are loadbalanced, when querying the `/assets` directory for `docker-machine-driver-*` files, the docker machine drivers cannot be downloaded on non-leader replicas because they are only installed on the leader node.
Download the docker machine drivers on all replicas. This controller runs all the time, but will prevent processing if a node becomes the leader. This does not unregister the handler, but I do not want to introduce such a change into wrangler yet.
Manually tested with 3 replicas, confirmed that the machine provision job had no issues downloading the custom node driver. The driver is present in all replicas at `/usr/share/rancher/ui/assets`.
* None, we do not currently …
=> 38481 download custom drivers each pod

pkg/apis/rke.cattle.io/v1/plan/plan.go, pkg/capr/common.go, pkg/capr/planner/initnode.go, pkg/capr/planner/planner.go, pkg/capr/planner/store.go, pkg/controllers/capr/bootstrap/controller.go, pkg/controllers/capr/planner/controller.go, pkg/controllers/capr/plansecret/plansecret.go
https://github.com/rancher/rancher/issues/41126
https://github.com/rancher/rancher/issues/42034
In certain cases, it is possible to hit a situation where probes for a node start to fail for various reasons (for example, init node is deleted/dies). If this occurs, the planner would get stuck attempting to update the plan for the node as it would artificially inflate the number of "unavailable" nodes based on probes.
This PR changes the way that unavailable nodes are determined -- it now only considers a node unavailable if it
1. is not "in sync" (plan has not been applied)
2. is draining
If during processing, the node is found to have a successfully applied plan but the probes are failing, it is added to the unavailable count.
* …
=> [CAPR] Handle failing previous plans and ensure init node is not used before allowing deletion

pkg/api/steve/disallow/disallow.go
Follow up after https://github.com/rancher/webhook/pull/234
CRTB validation has been migrated to the webhook and now it needs to be exposed by Steve
Add `clusterroletemplatebindings` to the `allowAll` list
=> Expose ClusterRoleTemplateBindings

pkg/capr/planner/etcdrestore.go, tests/v2prov/cluster/clusters.go, tests/v2prov/defaults/defaults.go, tests/v2prov/operations/certificaterotation.go, tests/v2prov/operations/downstream_kc.go, tests/v2prov/operations/etcdsnapshot.go, tests/v2prov/tests/custom/operation_etcdsnapshot_inplace_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_combined_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_test.go, tests/v2prov/tests/machineprovisioning/machine_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_inplace_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_multietcd_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_test.go
https://github.com/rancher/rancher/issues/42179
The provisioning tests for K3s/RKE2 were flaky and causing issues where drone PR and publish runs would fail unnecessarily.
1. The etcd restoration tests would intermittently fail as the "stock" configuration of K3s/RKE2 ship with a cron strategy for snapshot creation. This meant that snapshots would possibly be created before Rancher was finished setting up the downstream cluster, and this issue was further compounded by the fact that the test would simply choose a random snapshot from the list which had a chance of not containing the correct data. This was further compounded by the fact that the service accounts for `cattle-impersonation-system` would only be set up once and the lifecycle controller would not reconcile the accounts, a …
=> [CAPR] fix nil point exception in v2prov etcd scaling test and improve general reliability of v2prov tests

pkg/controllers/management/drivers/base_driver.go, pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/nodedriver/nodedriver.go, pkg/controllers/nodedriver/nodedriver_test.go, pkg/rancher/rancher.go, scripts/test
Backport of https://github.com/rancher/rancher/pull/42076
Node drivers are not downloaded in each rancher replica. Because the replicas are loadbalanced, when querying the `/assets` directory for `docker-machine-driver-*` files, the docker machine drivers cannot be downloaded on non-leader replicas because they are only installed on the leader node.
Download the docker machine drivers on all replicas. This controller runs all the time, but will prevent processing if a node becomes the leader. This does not unregister the handler, but I do not want to introduce such a change into wrangler yet.
Manually tested with 3 replicas, confirmed that the machine provision job had no issues downloading the custom node driver. The driver is present in all replicas at `/usr/share/rancher/ui/assets`.
* …
=> 42128 download custom drivers each pod

pkg/apis/go.mod, pkg/apis/go.sum
Kubernetes 1.13.0 has known CVEs in it
Update kubernetes to 1.25.4, which matches https://github.com/rancher/rancher/blob/39c4c345bcfba5eec8582012629c82917c8eb050/go.mod#L49
=> Update kubernetes module

pkg/image/origins.go
https://github.com/rancher/rancher/issues/41094
Before I can merge the new `rancher/mirrored-cluster-api-controller` chart into `rancher/charts`, the origin for this image must be added to Rancher.
Add the image origin to Rancher.
N/A
=> [release/v2.7] Add image origin for rancher/mirrored-cluster-api-controller

pkg/clustermanager/manager.go, pkg/controllers/capr/unmanaged/controller.go, pkg/controllers/managementuser/controllers.go, pkg/controllers/managementuser/nodesyncer/nodessyncer.go
After a second etcd restore, custom machines are removed from the cluster. 
Prevent nodesyncer controller from running during a restore. Remove legacy code that removes unmanaged machines when a corresponding v1 node is not present in the downstream cluster.
Tested manually. 
* None
* If "None" - Reason: Existing tests should be able to be chained together to verify this behavior; i.e. we would be able to perform snapshot and restore tests back to back on a custom cluster to ensure this isn't reproducible. This should not require any new tests cases to be written, only higher level orchestration code to compose and run such a test.
Since this affects custom clusters, the following cases should be tested:
- Taking a snapshot, restoring, taking another snapshot, …
=> Prevent custom node deletion during restore

pkg/catalogv2/git/download.go, pkg/catalogv2/git/download_test.go, pkg/data/dashboard/repo.go, pkg/data/management/catalog_data.go
We need to test Fleet inside of Rancher. Eventually, we want to be able to do that nightly or in PRs.
Fleet is installed and maintained by controllers in Rancher. That makes it impossible to compile and test Fleet, without branching the rancher-charts repo and publishing it. 
Furthermore, manual testing showed that Rancher will `git reset` and update the bundled repos in the container image, if it has internet. That is a strange behavior for air gap mode and should not happen in the bundled folders (`/var/lib`) at all. It does make sense if the user changed the repo via settings, but then the folder is not in `/var/lib`.
Having the bundled repos reset, might bring back another version of fleet, which Rancher will then deploy instead of the version that should be tested. 
* Add a local …
=> Fleet chart from bundled

pkg/apis/rke.cattle.io/v1/plan/plan.go, pkg/capr/common.go, pkg/capr/planner/etcdrestore.go, pkg/capr/planner/initnode.go, pkg/capr/planner/planner.go, pkg/capr/planner/store.go, pkg/controllers/capr/bootstrap/controller.go, pkg/controllers/capr/planner/controller.go, pkg/controllers/capr/plansecret/plansecret.go, scripts/provisioning-tests, tests/v2prov/cluster/clusters.go, tests/v2prov/defaults/defaults.go, tests/v2prov/operations/certificaterotation.go, tests/v2prov/operations/downstream_kc.go, tests/v2prov/operations/etcdsnapshot.go, tests/v2prov/tests/custom/operation_etcdsnapshot_inplace_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_combined_test.go, tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_test.go, tests/v2prov/tests/machineprovisioning/machine_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_inplace_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_multietcd_test.go, tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_test.go
https://github.com/rancher/rancher/issues/42121
https://github.com/rancher/rancher/pull/42124
https://github.com/rancher/rancher/pull/42164
https://github.com/rancher/rancher/pull/42180
There were problems with CAPR and the way it handled deleting etcd (init) nodes. Through extensive testing, multiple fixes were merged and this PR encapsulates the backport for this.
* The rkebootstrap controller now properly manages the CAPI pre-terminate annotation on machine objects to prevent premature infrastructure deletion
* The rkebootstrap controller now checks the cluster to ensure no other nodes within the cluster refer to the existing machine as an init node before allowing deletion of the infrastructure to prevent unexpected cluster node downtime
* Add v2prov test framework bug fixes to help …
=> [release/v2.7.6] Backport CAPR planner etcd management fixes 

tests/framework/extensions/users/users.go
Related to #41853
The logic that is commonly used to add/remove users from projects/clusters does not currently wait for the backing RBAC to be created before returning to the calling function. This leads to issues when tests are ran of the form "bind a user, then execute a command as the user to ensure that the binding worked", since the backing RBAC may not be made yet.
The common logic in `users/users.go` has been updated to look for ClusterRoleBindings with a label key (a format used by RBAC which backs both PRTBs and CRTBs, though the form is slightly different) matching a particular binding before returning from the various functions to manage user membership. 
Since both PRTBs and CRTBs appear to be backed by at least one ClusterRoleBinding matching this form, this logic can be …
=> Adding rollout wait to *RTB creation

tests/framework/extensions/users/users.go
In the functions for waitForCRTBRollout, waitForCRTBRollout, we are attempting to use rancherClient. But for cases when project members/project owners try to add other project members this call fails as the client defined is not an admin client and they will not have access to get the prtbs/crtbs. Added adminClient so the wait Rollout does not error out for other users.
=> Adding admin client so the waitRollout does not fail for non admin users

pkg/capr/planner/etcdrestore.go, pkg/capr/planner/idempotent.go
https://github.com/rancher/rancher/issues/42201
The idempotent script to wrap important cluster operations was not properly accounting for changed target hashes, and subsequently not executing instructions more than once ever. This means that an etcd restore is only possible once, and is not possible on subsequent restores.
Additionally, there is a problem with etcd restorations of the same snapshot. Given two snapshots, for example, snapshot A and snapshot B, a snapshot restoration attempt of snapshot A then B then back to A without incrementing the generation would lead to snapshot A not being restored.
Use the target hash in the idempotent tracking path to ensure that attempt numbers don't cross, and clean up idempotent tracking for `etcd-restore` when a new etcd restoration attempt is …
=> [CAPR] Utilize target hash in idempotent tracking path

cmd/agent/main.go
[#42241](https://github.com/rancher/rancher/issues/42241) 
`cattle-cluster-agent` can be run on debug-level using `CATTLE_DEBUG` or `RANCHER_DEBUG`, the same is not true for the trace-level.
If the env `CATTLE_TRACE` or `RANCHER_TRACE` is set to `true` wile initializing the `cattle-cluster-agent` it will use trace-level, in the same way it works for debug-level
* Builded an rancher-agent image localy. 
* Setted up a cluster with `RANCHER_TRACE=true`
* Changed the cattle-cluster-agent image.
=> accepts CATTLE_TRACE and RANCHER_TRACE as envs to set logrus trace level on rancher-agent

tests/v2/validation/rbac/rbac_psa_test.go
Related to https://github.com/rancher/qa-tasks/issues/857
This PR updated the local createUser call: https://github.com/rancher/rancher/pull/41888/files#diff-a7219180abad4cf82364da85734797831cf2d733e2d745eadeaf7952bad2ba2f and when it was merged this PR didn't update the new call https://github.com/rancher/rancher/pull/41901/files just need fix it on this line: https://github.com/rancher/rancher/blob/4dc8b1808c17c7c19fe42a56b60b33b81dfa6452/tests/v2/validation/rbac/rbac_psa_test.go#L379C15-L379C15
Updated rbac/rbac_psa_test.go with the new CreateUserWithRole call
local
=> Fix create user

pkg/settings/setting.go
rancher/dashboard and rancher/ui have branched for `2.7.6`
* This change ensures the rancher/rancher `release/v2.6` points to the right rancher/ui and rancher/dashboard builds in `UiIndex` and `UiDashboardIndex` setting defaults, respectively
* By default `-head` versions use these builds instead of the embedded builds 
Updated settings on an existing instance and verified the dashboard/ui load
=> Update UI settings 2.7.6

tests/framework/extensions/rke1/componentchecks/etcdversion.go, tests/v2/validation/provisioning/rke1/custom_cluster.go
The `CheckETCDVersion` is throwing a panic when the user defines multiple nodes per role with the `nodeRoles` parameter. This causes inconsistency with the test, which inadvertently affects our test suite at large when ran in bulk.
We are now reading the node's metadata directly. Doing this, we eliminate the possibility of a panic and can achieve consistent results each time. Which is what we expect from this test to begin with.
Manually validated that I still can provision a custom cluster and get the etcd version and image versions.
* Unit
* None
* If …
=> Fixing CheckETCDVersion function to read from metadata

pkg/catalogv2/git/download.go, pkg/catalogv2/git/git.go, pkg/controllers/dashboard/helm/repo.go, pkg/data/dashboard/add.go, pkg/data/dashboard/repo.go
https://jira.suse.com/browse/SURE-5190
Installed Apps, e.g. fleet and rancher-webhook, don't update after upgrade from v2.6.3 to v2.6.8 when Rancher chart uses --set useBundledSystemChart=true. As a result, fleet is left on chart version 100.0.2+up0.3.8 versus 100.0.5+up0.3.11 and rancher-webhook is left on chart version 1.0.2+up0.2.2 versus 1.0.5+up0.2.6.
When updating rancher versions there was no logic to check the different branches or commits and if the configMap should be updated. 
Ensure method had to change the behavior to work by the branch instead of the commit hash. 
Also, added a check for the default branch of each version and the specified clusterRepo branch from the previous version.
Forced the update of the configMap upon specific condition.
=> fixed bug, refactored and added proper documentation

chart/templates/configMap.yaml, chart/tests/configmap_test.yaml, pkg/controllers/dashboard/chart/chart.go, pkg/controllers/dashboard/systemcharts/controller_test.go
Whether users specify the webhook configuration as a string in a file (using Helm's set-file flag) or a map (using Helm's set flags), the chart must have a properly rendered object.
=> Adjust the rendering of config map values for the webhook in main chart

go.mod, go.sum
The dependency versions below have known public CVE's.
**Go**
- `github.com/aws/aws-sdk-go`
- Bump `github.com/aws/aws-sdk-go` to `v1.44.308`.
=> Bump `github.com/aws/aws-sdk-go`

tests/v2/validation/rbac/rbac_test.go
!-- Describe what manual testing you did (if no testing was done, explain why). -->
While verifying if additional users can be added to the cluster roles. The user added as the additional user should be a standard user, but while restricted admins are adding users, we are adding the additional user global role as a restricted admin. Updating the global role of the additional user to be a standard user in this PR.
https://github.com/rancher/qa-tasks/issues/870
=> [2.7]Changing the additional user role to be a standard user 

pkg/controllers/managementuser/controllers.go
When the  S3  ETCD snapshots backup is configured directly through RKE2 the rke2 configMap that is used to generates ETCDSnapshots is populated.
Once that cluster is imported Rancher creates ETCDSnapshots based on the configMap but never deletes them.
The deletion occurs based on a machine-plan secret that doesn't exist for imported clusters. 
The ETCDSnapshots are used to store the snapshot location and to be "recovered" on rancher UI. That only can be done to clusters administrated by rancher .
Do not register the `snapshotbackpopulate` controller for imported clusters.
Create a cluster with etcds s3 backup configured. Import it to rancher. Check if the ETCDSnapshots were created (they were not supposed to be created).
Create a cluster through rancher with etcds s3 backup enabled.  They …
=> Remove etcdsnapshot controller from imported cluster

tests/scripts/custodian/Dockerfile
https://github.com/rancher/qa-tasks/issues/876
found a way to login interactively to azure and GCP. 
azure is now able to login correctly
GCP was not tested, due to not having the same type of file as we have in jenkins, but I tested the same type of function on my machine and it was working. 
possibly more work required here depending on how GCP goes 
- will not have any affect on existing codebase nor framework - this is currently its own script
=> allow cloud custodian to login to azure, gcp

go.mod, go.sum
Update docker/docker to:
- `github.com/docker/docker v23.0.6+incompatible`
- `github.com/docker/docker => github.com/docker/docker v20.10.25+incompatible`
Fix CVE-2023-28840, CVE-2023-28841 and CVE-2023-28842 and removes false positives being flagged due to Docker's version being replaced.
=> [2.7] chore(deps): update module github.com/docker/docker

go.mod, go.sum
Update docker/docker to:
- `github.com/docker/docker v23.0.6+incompatible`
- `github.com/docker/docker => github.com/docker/docker v20.10.25+incompatible`
Fix CVE-2023-28840, CVE-2023-28841 and CVE-2023-28842 and removes false positives being flagged due to Docker's version being replaced.
=> [2.8] chore(deps): update module github.com/docker/docker

cleanup/ad-guid-README.md, cleanup/ad-guid-unmigration.sh, cmd/agent/main.go, pkg/agent/clean/adunmigration/ldap.go, pkg/agent/clean/adunmigration/migrate.go, pkg/agent/clean/adunmigration/rtbs.go, pkg/agent/clean/adunmigration/tokens.go, pkg/agent/clean/adunmigration/users.go, pkg/auth/providers/activedirectory/activedirectory_provider.go, pkg/auth/providers/common/provider_util.go, pkg/multiclustermanager/app.go
https://github.com/rancher/rancher/issues/42161
https://github.com/rancher/rancher/issues/42162
https://github.com/rancher/rancher/issues/42163
In Rancher v2.7.5 we attempted to automatically migrate Active Directory users, changing their internal ID within Rancher from their fully qualified Distinguished Name to a GUID. There were two fatal flaws in this initial migration that were missed during testing:
- The LDAP search to locate the matching GUID for a Distinguished Name was incorrectly scoped, and failed to locate users in nested directories
- A race condition during migration caused user objects to be duplicated if anyone tried to log in before their account had been processed
Affected users were instructed to restore from a backup if one was available, and 2.7.5 is no longer …
=> Add GUID unmigration script to revert Active Directory user modifications in v2.7.5

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/psact/checkpsact.go, tests/framework/extensions/psact/createdeployment.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_psa_test.go
https://github.com/rancher/qa-tasks/issues/873
The extensions CreateNginxDeployment and UpdateK3SRKE2Cluster were designed in way that it was possible to exit out the polls too soon, and therefore creating flakey behavior specifically in our rbac_psa tests.
update the polls
release testing.
* Unit
* None
_TODO_
* _TODO_
=> [v2.7] Updated flakey extensions that was causing errors in the psa rbac tests.

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/psact/checkpsact.go, tests/framework/extensions/psact/createdeployment.go, tests/v2/validation/rbac/rbac.go, tests/v2/validation/rbac/rbac_psa_test.go
https://github.com/rancher/qa-tasks/issues/873
The extensions CreateNginxDeployment and UpdateK3SRKE2Cluster were designed in way that it was possible to exit out the polls too soon, and therefore creating flakey behavior specifically in our rbac_psa tests.
update the polls
release testing.
* Unit
* None
_TODO_
* _TODO_
=> [v2.8] Updated flakey extensions that was causing errors in the psa rbac tests

pkg/tls/config.go, pkg/tls/config_test.go, pkg/tls/tls.go
Admins cannot specify "tis-min-version" to be "1.3". Rancher validates the setting value and doesn't start.
Change min version value validation and cipher list validation (the "tis-ciphers" setting), so that admins can start Rancher with a TLS min version 1.3 and its corresponding ciphers.
If admins set the version to 1.2, then we allow 1.2 and 1.3 ciphers.
If admins set the version to 1.3, then Rancher allows only 1.3 ciphers.
The default value is still 1.2 with its corresponding ciphers, so no change there.
* Unit
_TODO_
* _TODO_
=> Allow admins to specify TLS min version 1.3

cleanup/ad-guid-unmigration.sh, pkg/agent/clean/adunmigration/ldap.go, pkg/agent/clean/adunmigration/migrate.go, pkg/agent/clean/adunmigration/rtbs.go, pkg/agent/clean/adunmigration/tokens.go, pkg/agent/clean/adunmigration/users.go
This cleans up the logging output for a run of the unmigration script, and removes an otherwise noisy debug log during setup.
Successful runs now look something like this:
```
time="2023-08-18T12:13:44Z" level=info msg="[migrate-ad-user] beginning ad-guid unmigration"
time="2023-08-18T12:13:44Z" level=info msg="[migrate-ad-tokens] DRY RUN: would migrate token 'token-m6wj6' from GUID principal 'activedirectory_user://953d82a03d47a5498330293e386dfce1' to DN principal 'activedirectory_user://CN=testuser1,CN=Users,DC=qa,DC=rancher,DC=space'. Would add annotation, ad-guid-migration-data, and label, ad-guid-migration, to indicate migration status"
time="2023-08-18T12:13:44Z" level=info msg="[migrate-ad-tokens] DRY RUN: would migrate token 'token-7hrl2' from GUID principal …
```
=> Tidy up debug logs during AD unmigration

pkg/agent/clean/adunmigration/ldap.go, pkg/agent/clean/adunmigration/migrate.go
While refactoring this, I neglected to check for the generic failure case of an unexpected error, and it turns out that's what gets thrown when LDAP fails to connect entirely. Missing this was causing users to get migrated with emptystring as their DN, which is definitely not the intended result.
=> Fix error handling for LDAP lookups during unmigration

tests/framework/extensions/clusters/clusters.go, tests/v2/validation/v2prov/encryption_key_rotation_test.go
The way we were getting the cluster ID to run encryption key rotation was the wrong ID. So I created new extension and updated the test.
new extension that gets the Steve cluster ID
release testing.
* Unit
* None
_TODO_
* _TODO_
=> [v2.7] Added a new extension to be able to get a steve id for a cluster

tests/framework/extensions/clusters/clusters.go, tests/v2/validation/v2prov/encryption_key_rotation_test.go
The way we were getting the cluster ID to run encryption key rotation was the wrong ID. So I created new extension and updated the test.
new extension that gets the Steve cluster ID
release testing.
* Unit
* None
_TODO_
* _TODO_
=> [v2.8] Added a new extension to be able to get a steve id for a cluster

tests/v2/validation/charts/istio.go
With the latest Istio chart, the path of Kiali has changed.
Updated the path of Kiali to the new path
Ran locally
=> Fix istio tests in 27

tests/v2/validation/provisioning/rke2/ace_test.go
Current RKE2 ACE tests fail cause of: `Should NOT be empty, but was ...`
Updated the [the configuration empty check](https://github.com/rancher/rancher/blob/release/v2.8/tests/v2/validation/provisioning/rke2/ace_test.go#L94) should be updated as a nil check in RKE2 ACE tests.
=> [2.8] Update configuration input check in RKE2 ACE validation tests

tests/framework/clients/corral/config.go, tests/framework/clients/corral/corral.go, tests/framework/extensions/provisioning/creates.go, tests/framework/extensions/provisioning/verify.go, tests/v2/validation/pipeline/releaseupgrade/main.go, tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go, tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go, tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go, tests/v2/validation/provisioning/permutations/permutations.go
The pre-existing airgap tests were broken following a recent code refactor
Run permunatations for all three clusters were using the wrong identifier, updated the verify kubernetes upgrade function to account rke1 clusters as well, and fixed the create provider function.
* Unit
* None
_TODO_
* _TODO_
=> [v2.7] Fix Air gap provisioning automation tests

tests/framework/clients/corral/config.go, tests/framework/clients/corral/corral.go, tests/framework/extensions/provisioning/creates.go, tests/framework/extensions/provisioning/verify.go, tests/v2/validation/pipeline/releaseupgrade/main.go, tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go, tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go, tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go, tests/v2/validation/provisioning/permutations/permutations.go
The pre-existing airgap tests were broken following a recent code refactor
Run permunatations for all three clusters were using the wrong identifier, updated the verify kubernetes upgrade function to account rke1 clusters as well, and fixed the create provider function.
* Unit
* None
_TODO_
* _TODO_
=> [v2.8] Fix Air gap provisioning automation tests.

tests/framework/extensions/nodes/node_status.go, tests/framework/extensions/provisioning/creates.go, tests/framework/extensions/registries/registries.go, tests/v2/validation/provisioning/registries/registry_test.go
https://github.com/rancher/qa-tasks/issues/888
Registries were broken as part of the last refactor 
updated k3s/rke2 registry logic in automation in order to match what is expected. mostly were missing some initial parameters. 
tested more extensively locally. There may be some flakiness in checking registry container images, specifically saw some inconsistency in rke2. 
ecr was not able to be successful, but as you can see the code is the same as it was before the refactor. Izaac said this could be due to dependencies in the ami itself, not necessarily the code.
=> Update Registry Automation 

tests/framework/clients/helm/helm.go, tests/framework/extensions/kubeapi/helm/helm.go
Adding helm framework to tests so that integration or validation tests which require doing `helm install rancher` can use this framework.
=> Add helm framework to tests

pkg/api/steve/catalog/content.go, pkg/catalogv2/content/content.go, pkg/catalogv2/system/system.go
https://github.com/rancher/rancher/issues/40641
When we are about to create a downstream REK2  cluster, UI retrieves the chart index file of the builtin repo `rancher-rke2-charts` via the `/v1/catalog.cattle.io.clusterrepos/rancher-rke2-charts?link=index` endpoint.  UI uses the index file as the source of truth to determine whether it retrieves a particular version of the `rancher-vsphere-csi` and  `rancher-vsphere-cpi` charts to populate forms. 
The versions in the index file are filtered by the local cluster k8s version and Rancher server version. 
It becomes a problem when the versions of those two charts for the particular REK2 version are not in the index file because they are incompatible with the local cluster's k8s version.  Examples are in [this …
=> Support passing  `skipFilter` and `k8sVersion` when getting chart index

tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/hardening/k3s/harden_nodes.go, tests/framework/extensions/hardening/k3s/psa.yaml, tests/framework/extensions/hardening/rke2/harden_nodes.go, tests/framework/extensions/provisioning/creates.go, tests/framework/extensions/provisioninginput/config.go
The go framework currently only supports hardening custom RKE2/K3S clusters if the Kubernetes version is below v1.25. This was always meant to be a temporary solution until we understood the steps needed to harden downstream clusters v1.25+.
Now that the steps are available, we need to update the existing automation to account for these changes while still preserving the changes made.
Depending on the K8s version specified, the appropriate hardening steps will be applied to the RKE2/K3S downstream cluster. The tests remains dynamic as it is up to how the K8s version is defined in the user's config that dictate these steps.
RKE2 steps remain relatively the same, excluding that the CIS profile is 1.23. K3S no longer utilizes PSPs and now utilizes PSA, as was introduced in K8s v1.25+ and …
=> [v2.8] Add support for hardening RKE2/K3S v1.25+ custom clusters

tests/v2/validation/charts/webhook_test.go
Current test for webhook fails for downstream clusters while validating the pod logs, as the steveclient is set to the local cluster. Changing the steveclient to proxy to downstream to make sure this works for both local and downstream clusters.
Resolves: https://github.com/rancher/qa-tasks/issues/891
=> Update webhook test to work for both downstream and local 

pkg/data/management/machinedriver_data.go
Issue: https://github.com/rancher/rancher/issues/42576
Update Nutanix Rancher Node Driver to v3.4.0
manual installation of the node driver and cluster deployment with it
Driver is activated
RKE2 install
RKE1 install
=> update nutanix node driver to v3.4.0

pkg/settings/setting.go, pkg/settings/setting_test.go
Note: in draft until this can go into 2.8
As of Rancher 2.7, both `auth-token-max-ttl-minutes` and `kubeconfig-default-token-ttl-minutes` default to zero. Tokens in general have had a 0 TTL since Rancher 2.0, meaning they last forever. This has resulted in several problems. These include: a concern in our default security posture, performance issues around too many unexpired tokens, and confusion about which settings to adjust.
Updated the values to 30 days (43200 minutes) for default `kubeconfig-default-token-ttl-minutes` and 90 days (129600 minutes) for `auth-token-max-ttl-minutes`
When you start a rancher instance, go to settings and see that the default for both these values is set to the new values. When you go to create an auth token, the UI shows "30 days"
* Test types …
=> Update token ttl default

.drone.yml
Fix drone error while running `docker-image-promote`:
https://drone-publish.rancher.io/rancher/rancher/10463/2/2 
```
Error response from daemon: unknown: Tag v1.1.1 was deleted or has expired. To pull, revive via time machine
```
=> Bump skopeo to v1.13.2

pkg/cluster/private_registry.go, pkg/cluster/private_registry_test.go
Generating a private registry `.dockerconfigjson` used URL encoding instead of standard b64 encoding.
Use standard encoding.
* Unit
Summary: Updated existing unit tests to confirm expected config
Test system default registries and cluster private registries
Regressions should be unlikely, either private registries work or they don't.
Covered by existing private registry automation tests
=> [2.8] Update dockerconfigjson to use base64 StdEncoding

pkg/api/steve/disallow/disallow.go, pkg/api/steve/proxy/proxy.go, pkg/api/steve/proxy/proxy_test.go
All users need some level of access to the local cluster. For example, they may need to add a user to their project in a downstream cluster. This requires the ability to create a PRTB in the local cluster. They should have not only the RBAC permissions for it (granted, in this case, by virtue of being a project-owner), but also permission from the router to access the API paths. With the new public API, v3 management resources aren't available yet. 
Modify the routing logic, so that Rancher doesn't check a request for special access to local cluster if the resource is a v3.management resource and one in a set of allowed resources.
* Unit
=> Allow select management CRDs to be used in local cluster by kubectl

pkg/agent/clean/orphan_bindings.go, pkg/apis/management.cattle.io/v3/authz_types.go, pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go, pkg/client/generated/management/v3/zz_generated_global_role.go, pkg/clustermanager/errors.go, pkg/clustermanager/errors_test.go, pkg/controllers/management/auth/globalroles/enqueue.go, pkg/controllers/management/auth/globalroles/enqueue_test.go, pkg/controllers/management/auth/globalroles/globalrole_handler.go, pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go, pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go, pkg/controllers/management/auth/globalroles/register.go, pkg/controllers/management/auth/register.go, pkg/controllers/management/auth/role_template_lifecycle.go, pkg/controllers/management/auth/user.go, pkg/controllers/options.go, tests/framework/clients/rancher/generated/management/v3/zz_generated_global_role.go
#42213
This introduces a new field on GlobalRoles - `InheritedClusterRoles`, as well as the controllers for this field.
Note that a complete solution will require webhook changes to prevent privilege escalation and manipulation of key labels. This will be addressed as part of a separate issue (#42214).
Fields:
- `InheritedClusterRoles` - Roles granted in every cluster (except the local cluster). Each role specified here results in one CRTB from the subject of the GRB to the specified role for every cluster (besides the local cluster). 
Controllers/related functionality was implemented for the `InheritedClusterRoles` field which has the following basic funcitonality:
- The primary controller is on the `GlobalRoleBinding` object (since this field results in CRTBs, we can't orchestrate new …
=> Global roles v2

pkg/api/norman/customization/setting/setting.go, pkg/auth/providers/common/usermanager.go, pkg/settings/setting.go, tests/integration/suite/test_tokens.py
The `kubeconfig-token-ttl-minutes` setting has been deprecated and has reached end of life.
Removed the deprecated setting and removed any references to it. This removes the setting from the back end, however a UI change is required to remove the setting from the dashboard. It currently still appears, but does nothing.
Ran unit tests to make sure no references to the setting exist
=> Remove the deprecated kubeconfig-token-ttl-minutes setting

pkg/auth/providers/common/ldap/ldap_util.go, pkg/auth/providers/ldap/ldap_actions.go, pkg/auth/providers/ldap/ldap_client.go, pkg/auth/providers/ldap/ldap_client_test.go, pkg/auth/providers/ldap/ldap_provider.go, pkg/auth/providers/ldap/ldap_provider_test.go
https://github.com/rancher/rancher/issues/42324
Need unit tests for LDAP auth provider. 
Initially the idea was to write a basic unit test for the AuthenticateUser function as we identified it to be a good start point, but after exploring multiple approaches this was not possible for several reasons. One being a higher level interface all providers belong to prevents me from modifying the function signature (to inject mocks) without significant refactoring and the codebase structure in general is very limiting because many of our functions have multiple responsibilities. Instead, I implemented unit tests for the inner functions that make up the important logic within AuthenticateUser.
Some minor refactoring was necessary in order to mock some structures successfully.
1. Functions taking …
=> Add unit tests for LDAP auth provider

pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
Some logs for hosted downstream clusters are spammed, so we want to move them from info to debug level.
Change logging level from info to debug level for hosted downstream clusters
=> [2.8] Move AKS/EKS/GKE operators logs to debug level

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Update EKS operator to v1.2.2-rc6
Changelog: https://github.com/rancher/eks-operator/releases/tag/v1.2.2-rc6
=> [2.7] Update EKS operator to v1.2.2-rc6

package/Dockerfile
Bumps the csp adapter to a 2.8/1.27 compatible version for #41790. This PR also changes the versioning scheme of the adapter to align better with upstream versioning policy
=> Bump csp adapter to v3.0.0-rc1

pkg/image/extensions.go, pkg/image/extensions_test.go, pkg/image/origins.go, pkg/image/resolve.go
`SURE-6065`
***Note***
`ui-plugin-catalog` image can be found on [Docker Hub](https://hub.docker.com/r/rancher/ui-plugin-catalog/tags)
In order for a user to add any of the UI extensions into an air-gapped instance of Rancher, they will need to manually mirror the image from the [ui-plugin-charts repository](https://github.com/rancher/ui-plugin-charts) into an accessible registry.
This adds a mechanism to the `image` package to fetch the latest release from the ui-plugin-charts repo and add the catalog image to the `rancher-images.txt` as well as the `rancher-images-sources.txt` and `rancher-images-origins.txt` files. This mechanism has the ability to add more images to the extension catalog list which may include images from the [partner-extensions …
=> Add mechanism for adding extension catalog image to rancher-images.txt

pkg/api/steve/disallow/disallow.go, pkg/apis/management.cattle.io/v3/authz_types.go, pkg/crds/names.go, pkg/crds/yaml/generated/management.cattle.io_clusterroletemplatebindings.yaml
CRTB validation has been migrated. We need to expose them in steve and to generate the CRD
Add the information to generate the crd and expose CRTBs in steve
Ran the integration tests to make sure none of the field changes caused issues. No new tests needed
* Unit
* None
_TODO_
* _TODO_
=> Generate crd and expose CRTB

tests/framework/extensions/prime/primechecks.go, tests/v2/validation/prime/prime_test.go
When running our Prime UI checks, the `TestLocalClusterRancherImages` function keeps returning an error message regarding some pods. Manually looking, the errors are false-positives and is a result of how the function itself is written. We have `StatusPods` which is doing the exact thing, but yields the correct result.
Removed the faulty function and replaced it with `StatusPods`. Additionally, did some minor refactoring to polish up how the test runs to make it more smooth.
Ran this locally and the tests passed as expected.
=> [v2.7] Fix TestLocalClusterRancherImages in prime checks

tests/framework/extensions/prime/primechecks.go, tests/v2/validation/prime/prime_test.go
When running our Prime UI checks, the `TestLocalClusterRancherImages` function keeps returning an error message regarding some pods. Manually looking, the errors are false-positives and is a result of how the function itself is written. We have `StatusPods` which is doing the exact thing, but yields the correct result.
Removed the faulty function and replaced it with `StatusPods`. Additionally, did some minor refactoring to polish up how the test runs to make it more smooth.
Ran this locally and the tests passed as expected.
=> [v2.8] Fix TestLocalClusterRancherImages in prime checks

pkg/image/resolve.go, pkg/image/resolve_test.go
When importing new generic clusters in Rancher, the global entry for system-default-registry is not being honored by Rancher and is reverting to pulling from docker.io.
It was coded to behave like that if no cluster was passed to the function. 
The funcion cals: 
GetPrivateRegistryURL(cluster) ->  GetPrivateRegistry(cluster) -> GetPrivateClusterLevelRegistry(cluster)
GetPrivateClusterLevelRegistry() will return nill if there is  no cluster. 
on GetPrivateRegistry()  if  GetPrivateClusterLevelRegistry() retruns nill it will get the default registry. 
This way the function will work as intended if the cluster is nill. 
Instantiate Rancher with CATTLE_BASE_REGISTRY set. Import a custom cluster. Download the .yaml and check the image. 
Instantiate Rancher with CATTLE_BASE_REGISTRY  empty. …
=> Use CATTLE_BASE_REGISTRY even when the cluster is nill. 

pkg/image/resolve.go, pkg/image/resolve_test.go
Backport for PR : https://github.com/rancher/rancher/pull/42673
When importing new generic clusters in Rancher, the global entry for system-default-registry is not being honored by Rancher and is reverting to pulling from docker.io.
It was coded to behave like that if no cluster was passed to the function. 
The funcion cals: 
GetPrivateRegistryURL(cluster) ->  GetPrivateRegistry(cluster) -> GetPrivateClusterLevelRegistry(cluster)
GetPrivateClusterLevelRegistry() will return nil if there is no cluster. 
on GetPrivateRegistry()  if  GetPrivateClusterLevelRegistry() returns nill it will get the default registry. 
This way the function will work as intended if the cluster is nill. 
Instantiate Rancher with CATTLE_BASE_REGISTRY set. Import a custom cluster. Download the .yaml and check the …
=> [release/v2.7] Backports: Use CATTLE_BASE_REGISTRY even when the cluster is nill. 

pkg/apis/management.cattle.io/v3/authz_types.go, pkg/controllers/management/auth/prtb_sa_controller.go, pkg/controllers/management/auth/prtb_sa_controller_test.go, pkg/controllers/management/auth/register.go, pkg/controllers/management/authprovisioningv2/prtb.go, pkg/controllers/managementuser/rbac/namespace_handler.go, pkg/controllers/managementuser/rbac/prtb_handler.go
The ServiceAccount field on PRTB is only needed for legacy monitoring v1 and serves no other purpose. We intend to fully remove it from the type in a later version.
1. Add a controller that gets all PRTBs that have the serviceAccount field set and copy the value to an annotation that can be used for cleanup when the field is eventually deleted.
2. Document the PRTB.serviceAccount as deprecated in the CRD def.
3. Remove the Current PRTB controller behavior that acts on the deprecated field.
* Unit
_TODO_
* _TODO_
=> Deprecate the ServiceAccount field on ProjectRoleTemplateBindings

.drone.yml
See issue
See issue
None, will be testable only after merging
* None
* If "None" - Reason: Changing build pipeline
* If "None" - GH Issue/PR: N/A
None
None
None
=> Provisioning tests no longer fail `publish` build

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Update EKS operator to v1.3.0-rc2
Changelog: https://github.com/rancher/eks-operator/releases/tag/v1.3.0-rc2
=> [2.8] Update eks-operator to v1.3.0-rc2

tests/integration/README.md
While attempting to use the integration tests locally, I found the README to be lacking important information.
Some of the information I needed was in the wiki, so I added a reference to that. I also added a couple notes that I think are important to have up front, such as setting the password and using the correct version of python.
None needed as this is just documentation
=> Update the readme with some useful information

tests/framework/clients/rancher/v1/client.go, tests/framework/extensions/configmaps/configmaps.go, tests/v2/validation/configmaps/generatedfields.go, tests/v2/validation/configmaps/generatedfields_test.go
- Issue being tested: https://github.com/rancher/rancher/issues/41772
The need to verify that Steve is discarding unrecognized fields prior to the PUT request.
The solution involved utilizing a framework to generate a config map, followed by the creation of a PUT request using the `net/http` package to capture the response headers. A review of the response headers was then performed to search for any possible errors.
Note:
The use of the `net/http` package was authorized in collaboration with Israel. This step was necessary to capture HTTP response headers following a PUT request.
Manual testing / validations done in the original issue.
Summary: Added P0 validation test case for config maps.
=> verifying generated fields are removed

pkg/apis/management.cattle.io/v3/authz_types.go, pkg/crds/yaml/generated/management.cattle.io_clusterroletemplatebindings.yaml
Several of the CRTB fields reference `project` instead of `cluster` in their description
Replace all references to `project` with `cluster` and re-generate CRD
Just an update to docs. No tests needed
=> Replace references to projects with clusters in CRD definition

pkg/agent/clean/adunmigration/ldap.go, pkg/agent/clean/adunmigration/migrate.go
In a few cases, the unmigration logic was running into an error and returning it without writing it to logrus. In the Rancher startup case, due to this running in a goroutine, the return value is not kept and was getting silently discarded, leading to cases where the unmigration could enter a "Failed" status without writing any relevant details to the logs.
I took the simplest route and made sure that the unmigration self-reports any errors as it goes along. There should be no logic changes here, just increased error reporting.
This actually uncovered a fun bug with AD Allowed Users, which I'll fix in an upcoming PR. You can thus test the changes by running the script in standalone mode against any cluster with an empty allowed users list, and you should see:
``` …
```
=> uuid-unmigration: when an error happens, make sure it is actually logged

scripts/test, tests/v2/integration/catalogv2/rancher_managed_charts_test.go
By default, Go runs tests in different packages in parallel. This is disabled by using the -p flag.
The RancherManagedChartsSuite changes some CRDs during it's run which may cause other tests to fail sometimes. There may be other suites the do the same
=> Changing ci to not run integration tests in parallel

tests/v2/integration/catalogv2/cluster_repo_test.go
[test_cluster_catalog_creation Issue](https://github.com/rancher/rancher/issues/42339)
- Old Flaky Test written in Python 5 years ago.
- Randomly breaks the Drone Build Pipeline.
Removing the test in Python, the same functionalities test are partially tested by:
[catalogv2/cluster_repo_test.go](https://github.com/rancher/rancher/blob/release/v2.8/tests/v2/integration/catalogv2/cluster_repo_test.go)
This is the PR updating the test functionalities for replacing the removed python function from this [PR](https://github.com/rancher/rancher/pull/42753)
=> [Flaky-test] updating functionalities for cluster_repo_test

pkg/agent/clean/adunmigration/ldap.go, pkg/agent/clean/adunmigration/migrate.go
This is a forward port of https://github.com/rancher/rancher/pull/42762
In a few cases, the unmigration logic was running into an error and returning it without writing it to logrus. In the Rancher startup case, due to this running in a goroutine, the return value is not kept and was getting silently discarded, leading to cases where the unmigration could enter a "Failed" status without writing any relevant details to the logs.
I took the simplest route and made sure that the unmigration self-reports any errors as it goes along. There should be no logic changes here, just increased error reporting.
This actually uncovered a fun bug with AD Allowed Users, which I'll fix in an upcoming PR. You can thus test the changes by running the script in standalone mode against any cluster with an …
=> [2.8] uuid-unmigration: when an error happens, make sure it is actually logged

tests/validation/tests/v3_api/test_airgap.py
https://github.com/rancher/qa-tasks/issues/92
when we don't use the FQDN as the registry hostname, the test was failing. 
remove explicit check for the registry name. Leave in the first `/`, which implies that it is being pulled from a registry
=> removing explicit check for exact registry name from assertions

pkg/apis/management.cattle.io/v3/authz_types.go, pkg/crds/yaml/generated/management.cattle.io_clusterroletemplatebindings.yaml
It's not initially clear from `kubectl explain clusterroletemplatebindings` that the ClusterName must match the namespace. I also added the clarification that it must be the Name, not the DisplayName of the cluster.
=> Added clarifications for ClusterName field

pkg/cluster/private_registry.go, pkg/cluster/private_registry_test.go
This was happening wile creating a RKE2/K3S downstream cluster with a different public registry that the upstream cluster. 
Both webhook and the Helm/Shell are created from the Rancher Agent. 
The code that created the rancher agent template was only getting the v2prov registry if Auth was set.
With that for public registries it was  getting the upstream default registry instead of the downstream one. 
Change the logic to get the RegistryUrl so it checks the RKE2 even if it doesn't have auth. 
Create RKE1 and RKE2 clusters with custom and non custom registries. 
* Unit: 
Added some cases: 
* Registry set for upstream and downstream cluster with secret. 
* Registry set for upstream and downstream cluster without secret.
* Registry set for upstream cluster and …
=> Get registry from v2prov even without a secret

tests/integration/suite/test_clustertemplate.py
Tests were running with 1.24, which is unsupported
Bump to 1.25
CI
=> Bump cluster template k8s version to 1.25.x

pkg/agent/clean/adunmigration/ldap.go, pkg/agent/clean/adunmigration/migrate.go, pkg/agent/clean/adunmigration/rtbs.go, pkg/agent/clean/adunmigration/tokens.go
Small adjustments to facilitate easier unit testing. Mostly this reworks the various "identify" functions to accept their state, rather than accepting a means to query it. For LDAP the retryable connection is hoisted into an interface so it can be more easily mocked.
The goal of these changes is to facilitate unit test writing, those will come later. I just want to get eyes on this early.
=> Refactor guid-unmigration identification routines to not rely on cluster state

pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go, pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go
Updates the grbLifecycle create/update functions to tolerate errors from the sub-fuctions that it calls so that if one fails it doesn't derail the other.
This is what the [globalRole handler](https://github.com/rancher/rancher/blob/a9ea4ce4a5bab9dd112cd20c9e250aba4dbe5176/pkg/controllers/management/auth/globalroles/globalrole_handler.go#L46) currently does, and I think is a good enhancement to make sure that the new changes don't negatively impact existing functionality.
=> Updating create/update functions to tolerate errs

pkg/image/charts.go
JIRA Issue - https://jira.suse.com/browse/SURE-5595
GitHub Issue - https://github.com/rancher/rancher/issues/42885
Currently, we only support the latest version of a particular chart in `rancher/charts` in Rancher airgap setups that is we only add container images of the latest version of a chart in rancher/charts in rancher-images.txt for a particular Rancher release. This cannot be valid for the rancher-istio chart since Istio recommends not skipping minor versions while upgrading Istio https://istio.io/latest/docs/setup/upgrade/
Post Merge
=> Allow all supported versions of Istio in airgap setups in a particular Rancher version

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Update aks-operator to v1.2.0-rc4
Changelog: https://github.com/rancher/aks-operator/releases/tag/v1.2.0-rc4
=> [2.8] Update aks-operator to v1.2.0-rc4

tests/scripts/custodian/Jenkinsfile, tests/v2/codecoverage/Jenkinsfile_buildcodecoverage, tests/v2/codecoverage/Jenkinsfile_codecoverage, tests/v2/validation/Jenkinsfile, tests/v2/validation/Jenkinsfile.e2e, tests/v2/validation/Jenkinsfile_pre_post_upgrade, tests/v2/validation/Jenkinsfile_vpn, tests/v2/validation/pipeline/Jenkinsfile_release_upgrade, tests/validation/tests/v3_api/Jenkinsfile, tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test, tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_ontag, tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix, tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests, tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag, tests/validation/tests/v3_api/Jenkinsfile_vpn, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_rke2_upgrade
After creating a new default branch for release/2.8 we need our Jenkins test jobs to point to the new branch
Modified the default in all Jenkinsfiles to release/2.8
=> Updated Jenkinsfiles to default to release/2.8

tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
In order to avoid index errors all []int have to be the same size.  To get around this I added an extra value in the Cluster and machine pool level truncation test.
The Hostname truncation test was throwing an index error in its test loop because one of the int slices contained only two values. 
For the test to work all of the slices have to be the same length, so the easy solution was to add the extra value to the Cluster and machine pool truncation test case.  I also added a comment to the test function to describe what the numbers in each int slice represent. 
https://github.com/rancher/rancher/pull/42925
=> Fix hostname truncation test

pkg/catalogv2/git/git.go, pkg/catalogv2/git/git_test.go
GitHub Issue - https://github.com/rancher/rancher/issues/42888
Gogit has a bug https://github.com/go-git/go-git/issues/845. Until it is fixed, we follow as they recommended i.e use depth=1 for fetching
=> Add depth=1 for git fetch in pkg/catalogv2

pkg/controllers/management/drivers/nodedriver/machine_driver.go
We want to use the `.metdata.Name` field of the node driver object rather than the `.spec.DisplayName` field since the displayName field isn't guaranteed unique. This was already changed in the webhook in https://github.com/rancher/webhook/pull/277  
1. fixed in webhook to look at the right field
2. fixed in rancher to generate the dynamic schemas based on the new field 
Nothing too crazy - just make sure that node driver enabling/disabling still works as well as validation that one can rename node drivers to have conflicting display names and it still all works. 
None done - this shouldn't effect anything other than fixing the dynamic schema generation to work off of the guaranteed unique field rather than just the display name. 
* None
* If "None" - Reason: …
=> Change DynamicSchema generation to go off of .metadata.Name rather than .spec.Displayname

pkg/apis/management.cattle.io/v3/authz_types.go, pkg/crds/yaml/generated/management.cattle.io_globalroles.yaml
#42965
The description of inheritedClusterRoles needed to be edited to remove references to future fields.
The description of inheritedClusterRoles was edited to remove references to future roles.
N/A - description-only change
=> Updating inheritedClusterRoles description

pkg/apis/provisioning.cattle.io/v1/cluster.go, pkg/controllers/capr/managesystemagent/managesystemagent.go, pkg/controllers/capr/managesystemagent/managesystemagentplan.go, pkg/controllers/capr/managesystemagent/managesystemagentplan_test.go, pkg/controllers/provisioningv2/cluster/controller.go, pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go, pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go, pkg/features/feature.go
https://github.com/rancher/rancher/issues/36132
It is not possible to change the fleet workspace name for a provisioned (v2prov) cluster 
Introduce a new feature flag called `provisioningv2-fleet-workspace-back-population` which will allow for fleet workspace names to be changed on the management cluster object. 
Provision a cluster, then change the mgmt cluster fleet workspace name. Observe the fleet workspace name can change.
As this is an alpha-level feature, we should smoke test the ability to change the fleet workspace name, and ensure that clusters can still provision with default settings.
Note, there was an observed issue with Fleet: https://github.com/rancher/fleet/issues/1807
=> [release/v2.8] [v2prov] Allow fleet workspace name to be changed on management cluster object

tests/framework/extensions/clusters/clusterconfig.go, tests/framework/extensions/provisioning/creates.go, tests/framework/extensions/provisioning/customcluster.go, tests/framework/extensions/provisioning/verify.go, tests/framework/extensions/provisioninginput/config.go, tests/v2/codecoverage/setuprancher/main.go, tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go, tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go, tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go, tests/v2/validation/provisioning/k3s/README.md, tests/v2/validation/provisioning/k3s/custom_cluster_test.go, tests/v2/validation/provisioning/k3s/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go, tests/v2/validation/provisioning/permutations/permutations.go, tests/v2/validation/provisioning/registries/registry_test.go, tests/v2/validation/provisioning/rke1/README.md, tests/v2/validation/provisioning/rke1/custom_cluster_test.go, tests/v2/validation/provisioning/rke1/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go, tests/v2/validation/provisioning/rke2/README.md, tests/v2/validation/provisioning/rke2/ace_test.go, tests/v2/validation/provisioning/rke2/custom_cluster_test.go, tests/v2/validation/provisioning/rke2/post_kdm_oob_release_test.go, tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go, tests/v2/validation/rbac/rbac_additional_test.go
part 1 of: https://github.com/rancher/qa-tasks/issues/560
there are additional fields that we didn't have access to via automation, specified on custom clusters during the node registration process 
**breaking change** : updating `nodesAndRoles` (and RKE1NodesAndRoles) to a new object, machinePools (nodePools) with the following config update:
```
machinePools: # for rke1, nodePools
- nodeRoles:
etcd: true
controlplane: true
quantity: 1
- nodeRoles:
worker: true
quantity: 1
nodeLabels:
label1: "value1"
label2: "value2"
nodeTaints:
- key: TestKey
value: testValue
effect: NoSchedule
specifyPrivateIP: true
specifyPublicIP: true
nodeNameSuffix: "qa"
```
also, I updated our tests' variable names to provisioningConfig from clustersConfig in places where that was more clear now that we have a …
=> [2.8]allow customization of custom clusters' registration command

pkg/agent/clean/adunmigration/ldap_test.go, pkg/agent/clean/adunmigration/rtbs_test.go, pkg/agent/clean/adunmigration/users_test.go
Adds unit tests for several utility functions, as well as identifyCRTBs, identifyPRTBs and identifyGRBs, improving overall coverage. These test only business logic, and require no network calls or external state, so they should be quite lightweight.
* Unit
=> guid-unmigration: add unit tests for utility functions and duplicate resource identification

pkg/agent/clean/adunmigration/ldap_test.go, pkg/agent/clean/adunmigration/migrate.go, pkg/agent/clean/adunmigration/migrate_test.go, pkg/agent/clean/adunmigration/rtbs_test.go, pkg/agent/clean/adunmigration/tokens_test.go, pkg/agent/clean/adunmigration/users_test.go
Adds unit tests for token resources (very similar to cluster and project resources), and a bunch of tests for the core migration logic which identifies users and resolves their duplicates. Lots of edge cases to handle here.
* Unit
=> Unmigration: add additional unit tests for user and token identification

pkg/cluster/private_registry.go, pkg/cluster/private_registry_test.go
Backport Issue #42044 
Backport PR #42069 
Generating a private registry `.dockerconfigjson` used URL encoding instead of standard b64 encoding.
Use standard encoding.
* Unit
Summary: Updated existing unit tests to confirm expected config
Test system default registries and cluster private registries
Regressions should be unlikely, either private registries work or they don't.
Covered by existing private registry automation tests
=> [DNM v2.7.8] Update dockerconfigjson to use base64 StdEncoding

Dockerfile.dapper
The dapper `bind` mode (`dapper --mode=bind` or `DAPPER_MODE=bind`) is ~~only available on linux and it~~ improves the build time by quite a bit:
**Copy mode (default)**
```
$ time DAPPER_MODE=copy make build
...
real	0m21.415s
user	0m0.930s
sys	0m0.667s
```
**Bind mode**
```
$ time DAPPER_MODE=bind make build
...
real	0m6.928s
user	0m0.195s
sys	0m0.111s
```
**Direct go build**
Slightly faster than bind mounts. This is what I currently use (along with `go run`) to avoid having to wait 20+ second every build. I'd rather be able to use the standard dapper scripts as everyone else though.
```
real	0m4.861s
user	0m9.663s
sys	0m1.907s
```
Builds fail when using `DAPPER_MODE=bind` due to the following git error:
```
fatal: detected dubious ownership in repository at …
```
=> Trust /go/src/github.com/rancher/rancher with git in the build image

tests/framework/clients/dynamic/dynamic.go, tests/framework/extensions/kubeapi/authorization/authorization.go, tests/framework/extensions/users/users.go, tests/v2/integration/projects/project_user_test.go, tests/v2/integration/rtbs/rtbs_test.go, tests/v2/integration/steveapi/steve_api_test.go, tests/v2/validation/rbac/rbac_additional_test.go, tests/v2/validation/rbac/rbac_etcd_backup_test.go, tests/v2/validation/rbac/rbac_psa_test.go, tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/rancher/issues/41825
The following tests were flaky:
- TestRTBTestSuite/TestPRTBRoleTemplateInheritance
- TestRTBTestSuite/TestCRTBRoleTemplateInheritance
This is because `AddClusterRoleToUser` and `AddProjectMember` attempts to detect if the new role templates bindings have been reconciled. This detection is flawed (eg: waiting for > 0 resources means 1 / 4 could exist but the test would rely one one of the 3 not yet created).
Use the [SelfSubjectAccessReview API](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access) which allow us to check if the current user has access to some resources.
It would be best to use this `WaitForAllowed` function whenever `AddClusterRoleToUser` or `AddProjectMember` is called, however I have …
=> Fix flaky CRTB and PRTB tests

pkg/capr/planner/etcdrestore.go, pkg/capr/planner/etcdrestore_test.go
When force deleting etcd machines by applying the capi `"machine.cluster.x-k8s.io/exclude-node-draining"` annotation, the annotations map may be nil.
Check if nil before assignment, and initialize if nil.
Added extensive unit testing
* Unit
Summary: Added unit tests for every code path in the function.
Test P0 etcd restore use cases
Shouldn't be any regressions, etcd restore should just work.
* Added unit tests
=> Fix panic in etcd restore

tests/framework/extensions/clusters/kubernetesversions/all.go, tests/framework/extensions/clusters/kubernetesversions/available.go
`ListAKSAllVersion` currently requires a cluster to fetch all the versions, unlike other providers. This PR modifies it to not require a cluster.
Modify the function signature to directly accept the cloud credential secret and region instead of obtaining them via cluster.
=> [2.8] Fix ListAKSAllVersions to not require a cluster

pkg/apis/management.cattle.io/v3/authz_types.go, pkg/crds/yaml/generated/management.cattle.io_projects.yaml
Updates the docs for the ClusterName field on the project spec to be immutable, in line with recent webhook changes which enforce this requirement
Related to #42913, but does not make any effective changes.
The webhook, with 0.4.0-rc10, now makes the `project.Spec.ClusterName` field immutable. The docs, however, do not state this. 
The field description (available through `kubectl explain`) has been updated to specify that the `ClusterName` field of the projectSpec is immutable.
N/A - docs only change.
=> Updating docs for project.Spec.ClusterName

pkg/capr/common.go, pkg/capr/configserver/server.go, pkg/controllers/capr/bootstrap/controller.go, pkg/controllers/capr/bootstrap/controller_test.go, pkg/controllers/dashboard/apiservice/apiservice.go, pkg/impersonation/impersonation.go, pkg/serviceaccounttoken/secret.go, pkg/serviceaccounttoken/secret_test.go, pkg/types/config/context.go
A token for a service account can be generated by creating a secret for that service account with the annotation
`kubernetes.io/service-account.name` pointing to that service account.
In Kubernetes 1.23 and below, a reference to the secret was automatically stored directly on the service account by Kubernetes, making it easy to look up. For Kubernetes 1.24, Rancher started explicitly adding the secret to the service account so that it could refer back to it.
In k8s 1.27, storing references to the secret is discouraged[1] in favor of explicitly using the TokenReview API[2]. This does not serve Rancher's purposes because the service account token needs to be long-lived and is not intended to be mounted in a pod. To avoid the warning, this change stops storing the secret reference on the …
=> Stop recording secrets on service account

pkg/controllers/capr/unmanaged/controller.go, pkg/controllers/provisioningv2/provisioningcluster/template.go, tests/v2prov/tests/custom/custom_test.go
When deleting a K3s/RKE2 custom cluster, control-plane machines never get deleted and prevent the cluster from being deleted.
This is happening because control plane machines are missing the `ownerReference` pointing to their corresponding cluster objects, and as a result the CAPI machine controller does not clean them up when the cluster object is deleted. The reason they're missing the `ownerReference` is because they were mistakenly given the `cluster.x-k8s.io/control-plane-name` label in a recent upgrade PR [here](https://github.com/rancher/rancher/commit/38c4f2fbe4b594bac4876fa18c4f4014fe353574#diff-b6a77716404a711f2ad4441849495e70f631b4631f80b0f70f1a2fe0532e7e4dR146) instead of the `cluster.x-k8s.io/control-plane` label. The purpose of the `cluster.x-k8s.io/control-plane-name` label …
=> Fix control-plane labels for unmanaged machines

package/Dockerfile
Rancher images currently being built no longer run due to the missing package openssh-clients. `jail.sh` [uses the ssh binary](https://github.com/rancher/rancher/blob/release/v2.8/package/jailer.sh#L76) when running and causes Rancher to exit if it does not exist.
The package is missing since git-core which was being installed by rancher no longer requires openssh-clients.
2 Root causes of this issue are 
1. Rancher does not explicitly install versions of the following pakacges
```
gcc binutils glibc-devel-static ca-certificates git-core wget curl unzip tar vim less file xz gzip sed gawk iproute2 iptables 
jq skopeo
```
2. Rancher does not explicitly install openssh-clients.
This PR attempts to fix the issue by addressing point number 2.
=> Adds openssh-clients package installation.

tests/framework/extensions/clusters/kubernetesversions/all.go, tests/framework/extensions/clusters/kubernetesversions/available.go
`ListAKSAllVersion` currently requires a cluster to fetch all the versions, unlike other providers. This PR modifies it to not require a cluster.
Modify the function signature to directly accept the cloud credential secret and region instead of obtaining them via cluster.
=> [2.7] Fix ListAKSAllVersions to not require a cluster

tests/framework/extensions/clusters/clusterconfig.go, tests/framework/extensions/clusters/clusters.go, tests/framework/extensions/clusters/dynamicSchema.go, tests/framework/extensions/defaults/defaults.go, tests/framework/extensions/machinepools/machinepools.go, tests/framework/extensions/nodes/node_status.go, tests/framework/extensions/provisioning/ssh.go, tests/framework/extensions/provisioning/verify.go, tests/framework/extensions/provisioninginput/config.go, tests/framework/extensions/rke1/nodepools/nodepools.go, tests/framework/extensions/sshkeys/downloadsshkeys.go, tests/v2/validation/nodescaling/replace.go, tests/v2/validation/snapshot/snapshot.go, tests/v2/validation/upgrade/kubernetes_test.go
[645](https://github.com/rancher/qa-tasks/issues/645) This is a forward port of [42854](https://github.com/rancher/rancher/pull/42854)
We currently do not have an automated test where we reboot a node and check to see if the cluster comes back up `Active`. We should do the following to rectify that:
- Create a 1 node, all roles RKE1 cluster, reboot the cluster and validate that the cluster and nodes are `Active`
- Create a 1 node, all roles RKE2 cluster, reboot the cluster and validate that the cluster and nodes are `Active`
- Create a 1 node, all roles K3s cluster, reboot the cluster and validate that the cluster and nodes are `Active`
Adding an ssh test to the automation framework to reboot a node and verify the cluster comes up active.
Manual steps taken:
1. Provision a 1 node all role …
=> Adding sshTest to verify a cluster comes back up active after rebooting node

tests/framework/clients/dynamic/dynamic.go, tests/framework/extensions/kubeapi/authorization/authorization.go, tests/framework/extensions/users/users.go, tests/v2/integration/projects/project_user_test.go, tests/v2/integration/rtbs/rtbs_test.go, tests/v2/integration/steveapi/steve_api_test.go, tests/v2/validation/rbac/rbac_additional_test.go, tests/v2/validation/rbac/rbac_etcd_backup_test.go, tests/v2/validation/rbac/rbac_psa_test.go, tests/v2/validation/rbac/rbac_test.go
https://github.com/rancher/rancher/issues/43134
This is a backport of https://github.com/rancher/rancher/pull/42962.
The following tests were flaky:
- TestRTBTestSuite/TestPRTBRoleTemplateInheritance
- TestRTBTestSuite/TestCRTBRoleTemplateInheritance
This is because `AddClusterRoleToUser` and `AddProjectMember` attempts to detect if the new role templates bindings have been reconciled. This detection is flawed (eg: waiting for > 0 resources means 1 / 4 could exist but the test would rely one one of the 3 not yet created).
Use the [SelfSubjectAccessReview API](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access) which allow us to check if the current user has access to some resources.
It would be best to use this `WaitForAllowed` function whenever …
=> Fix flaky CRTB and PRTB tests (Backport 2.7)

tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
In order to avoid index errors all []int have to be the same size.  To get around this I added an extra value in the Cluster and machine pool level truncation test.
The Hostname truncation test was throwing an index error in its test loop because one of the int slices contained only two values. 
For the test to work all of the slices have to be the same length, so the easy solution was to add the extra value to the Cluster and machine pool truncation test case.  I also added a comment to the test function to describe what the numbers in each int slice represent.
=> Fix Flakey hostname truncation test backport

pkg/image/origins.go
Add to the origins.go file the Elemental container images needed for adding the chart in the Rancher Marketplace (see https://github.com/rancher/image-mirror/pull/428).
=> Add new Elemental images to Rancher's images origins file.

package/Dockerfile
git-core dropped dependency for openssh-clients but this package is needed by jailer.
=> [2.7] Adds openssh-clients package installation.

go.mod, go.sum
Related to rancher/rancher#43030 
In the scenario described by the above issue (a user with `get` permissions limited by `resourceNames` at the cluster scope), steve would panic on calls to get all objects of a specific type.
Steve now returns an empty object instead of nil, avoiding a panic. This PR bumps the version of Steve to the one with this fix included.
As a note, this PR did bump steve from rancher/steve@5df31b9c15cc7136702dcf63269616e443b2cc1f to rancher/steve@9935404019063126b6ac856db1ad56e0bc457ff8, which pulled in a few unrelated commits. These commits were either test-only, docs only, or changes made to the dockerfile configuration (rancher uses steve as a go library, not as a container-dependency), so no they should not have an impact. A full listing and brief description …
=> Bump steve version

pkg/capr/planner/etcdrestore.go
This is a partial solution and isn't enough to close the issue. 
Using RKE2: 1.26.8, 1.26.9, 1.15.13
Wile restoring ETCDs  or Upgrading to a Newer k8s version and then restoring the ETCD back to a older one we were facing some distinct errors: 
* Nodes got stuck w8ing for the etcd node (that usually got reconciled after ~35 minutes) 
* Nodes got stuck wile waiting for Calico. 
This doesn't solve all the problems described in the issue and on the tread, but fixes the problem where pods get Stuck wile waiting for Calico. 
Nodes that get stuck with "waiting for probes: etcd"  tend to get "reconciled" after ~35 minutes stuck.  
This was discussed and debugged on this tread: https://suse.slack.com/archives/C02D01ARDL5/p1696872411064999   (internal link)
And seems to be caused for some race …
=> delete pod-manifests/kube-proxy for rke2 on etcd restore

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Update eks-operator to v1.3.0-rc4
Changelog: https://github.com/rancher/eks-operator/releases/tag/v1.3.0-rc4
=> [2.8] Update eks-operator to v1.3.0-rc4

tests/framework/extensions/machinepools/machinepools.go, tests/framework/extensions/provisioning/creates.go, tests/framework/extensions/provisioning/nodeproviders.go, tests/framework/extensions/rke1/nodepools/nodepools.go, tests/framework/extensions/scalinginput/config.go, tests/v2/validation/nodescaling/README.md, tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go, tests/v2/validation/nodescaling/scaling_custom_cluster_test.go, tests/v2/validation/nodescaling/scaling_nodepools.go
Recently, we introduced a new scaling test suite in the test framework for machine pools for RKE2/K3S node driver clusters. However, we currently do not support adding/deleting nodes in a custom RKE2/K3S cluster.
With the new scaling test suite, that is a test that we should ensure that we're covering in our Go framework.
Implemented a test that adds/delete custom cluster nodes in a provisioned RKE2/K3S custom cluster. Using the `scalingInput` block in your config file, you can customize the quantity of your desired node role. An example is you can have the following block:
```
scalingInput:
nodeProvider: "ec2"
machinePools:
nodeRoles:
worker: true
quantity: 2
```
This will add two new nodes to the cluster and then delete the nodes from Rancher and the underlying EC2 instance.
- …
=> [v2.7] Add support for adding/deleting RKE1/RKE2/K3S custom cluster nodes

tests/framework/pkg/config/config.go
Original Issue description:
---
Problem
We are currently unable to load our config files directly into certain rancher objects as well as all k8s objects because they only have tags for json. This results in us having to parse the config file into custom objects that we have to create and maintain that are nearly identical to k8s and certain rancher objects.
Solution
Swap the yaml library to a the sigs.k8s.io/yaml library which handles both json and yaml objects. This allows us to load into any json/yaml tagged object without having to go back and update the tags for all of the objects.
Testing on 2.7
---
Ran the dynamic version of the RKE2 cluster provisioning test which utilized load_config
=> [Backport 2.7] Load config

pkg/capr/planner/etcdrestore.go
Reverts rancher/rancher#43158
As discussed on Slack and on #42895  the issue will be fixed on RKE2 side, https://github.com/rancher/rke2/issues/4930. 
As the newest RKE2 versions (the ones with problem) are not on KDM we will replace them there with the new versions that not contain the bug before releasing it.
=> Revert "delete pod-manifests/kube-proxy for rke2 on etcd restore"

pkg/api/norman/store/cluster/cluster_store.go
https://github.com/rancher/rancher/issues/43175
Setting default value for the field `useInstanceMetadataHostname` when using `external-aws`. Docs and release notes would be updated to note it'll have to be disabled when users are passing custom node names for custom clusters. For all other usecases, the field will be true so that external cloud provider can find the node without `providerID`.
=> set default useInstanceMetadataHostname true for external-aws

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum
Update operator to v1.3.0
Changelog: https://github.com/rancher/eks-operator/releases/tag/v1.3.0
=> [2.8] Updating eks-operator to operator v1.3.0
