pkg/controllers/management/node/controller.go

Issue: https://github.com/rancher/rancher/issues/37515
backport of the PR https://github.com/rancher/rancher/pull/37504
Please check the original PR for details

[2.5] [Backport] Fix the "no basic auth credentials" error when using private registry

---

chart/README.md

Feel free to reject and fix on your side if this is not the correct merge workflow.

docs(readme): Typo intructions -> instructions

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/controllers/options.go
pkg/generated/norman/apiregistration.k8s.io/v1/zz_generated_k8s_client.go
pkg/generated/norman/apps/v1/zz_generated_k8s_client.go
pkg/generated/norman/autoscaling/v2beta2/zz_generated_k8s_client.go
pkg/generated/norman/batch/v1/zz_generated_k8s_client.go
pkg/generated/norman/batch/v1beta1/zz_generated_k8s_client.go
pkg/generated/norman/cluster.cattle.io/v3/zz_generated_k8s_client.go
pkg/generated/norman/core/v1/zz_generated_k8s_client.go
pkg/generated/norman/extensions/v1beta1/zz_generated_k8s_client.go
pkg/generated/norman/management.cattle.io/v3/zz_generated_k8s_client.go
pkg/generated/norman/monitoring.coreos.com/v1/zz_generated_k8s_client.go
pkg/generated/norman/networking.istio.io/v1alpha3/zz_generated_k8s_client.go
pkg/generated/norman/networking.k8s.io/v1/zz_generated_k8s_client.go
pkg/generated/norman/policy/v1beta1/zz_generated_k8s_client.go
pkg/generated/norman/project.cattle.io/v3/zz_generated_k8s_client.go
pkg/generated/norman/rbac.authorization.k8s.io/v1/zz_generated_k8s_client.go
pkg/generated/norman/storage.k8s.io/v1/zz_generated_k8s_client.go
pkg/types/config/context.go
pkg/wrangler/context.go

**Issue:**
https://github.com/rancher/rancher/issues/37360

Only update changed v2.5

---

pkg/provisioningv2/rke2/planner/etcdrestore.go

https://github.com/rancher/rancher/issues/37641
Init node designation is done in two places during an etcd restore, and only one was covered. 
In the event that a snapshot is restored for an init node that doesn't match node names anymore (cloud provider changed node name), we must correlate the node name based on the machine infra.

designate proper init node in etcd restore stop plan

---

pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go

https://github.com/rancher/rancher/issues/37673
Encryption key rotate state was being set to `Failed` as it is currently short circuited. This PR will reset encryption key rotate state if the spec is nil.

reset encryption key rotate state if spec is nil

---

Dockerfile.dapper
scripts/change-final-rc-values

This script automates the step to change values for final RC (and revert). Making this a make target allows everyone to use it consistently and allows us to call it using GitHub Actions workflow when we implement that later.

[release/v2.6] Add target to change final rc values

---

pkg/controllers/management/secretmigrator/clusters.go

#37658 
It will fix the logic of the function `CreateOrUpdatePrivateRegistrySecret` to store secrets for multiple registries.
https://github.com/rancher/rancher/blob/dfe44512d12d5674607be1848e53ce83f5b67e6c/pkg/controllers/management/secretmigrator/clusters.go#L661
The relevant secrets in the namespace `cattle-global-data` will be created correctly.

Support for multiple private registries in 2.6 (secretmigrator code)

---

pkg/controllers/management/secretmigrator/clusters.go

Backport of https://github.com/rancher/rancher/pull/37659

[2.5] Support for multiple private registries in 2.6

---

pkg/image/export/main.go
scripts/create-components-file.sh

Changes made to creating components file from `release/v2.6`

[release/v2.5] Backport components file changes

---

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
tests/validation/tests/v3_api/test_cluster_templates.py
tests/validation/tests/v3_api/test_node_label.py
tests/validation/tests/v3_api/test_node_template.py
tests/validation/tests/v3_api/test_rke_cluster_provisioning.py

https://github.com/rancher/qa-tasks/issues/318
This takes care of the RKE1 provisioning tests.
Migrate existing tests to Linode

Automation - Disabling DO automation tests

---

package/Dockerfile

Issues:
https://github.com/rancher/rancher/issues/37544
https://github.com/rancher/rancher/issues/37535

Bump rancher-webhook to 1.0.5+up0.2.6-rc3

---

.github/workflows/README.md

Describe what workflows we implemented and why

[release/v2.6] Add GitHub Actions workflows README

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/37608

Bump aks operator version to 1.0.6-rc1

---

pkg/api/scheme/scheme.go

Issue: https://github.com/rancher/rancher/issues/37644

Excluded GVK of Logging v1 schemes for projectlogging and clusterlogging

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/37608

Bump AKS operator version to v1.0.6-rc2

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/37627

Bump steve for new watch changes

---

.drone.yml

https://github.com/rancherlabs/eio/issues/1045

[release/v2.6] Remove broken Slack notifications from Drone

---

pkg/data/management/machinedriver_data.go

testing completed, ready for review.
Issue: https://github.com/rancher/rancher/issues/37964

Updated pnap machine driver version to 0.4.0

---

pkg/controllers/management/auth/crtb_handler.go
pkg/data/management/role_data.go

This reverts commit 086a8ae6ca1d1afb1df524266af9b332c9c4f18d, reversing
changes made to c5e6c94d7cf2396b3a556144349f47e29f9d7b9b.

Revert "Merge pull request #37753 from KevinJoiner/snapshot-rbac"

---

pkg/api/steve/supportconfigs/generator.go

Winnowing fix

---

pkg/settings/setting.go
tests/framework/extensions/clusters/import.go
tests/v2/validation/charts/monitoring.go

See https://github.com/rancher/rancher/issues/36138

Update `rancher/shell` to version using SLE-BCI as base image

---

pkg/settings/setting.go
tests/framework/extensions/clusters/import.go
tests/v2/validation/charts/monitoring.go

Update `rancher/shell` to version

---

package/Dockerfile
pkg/api/steve/supportconfigs/generator.go
pkg/controllers/dashboard/controller.go
pkg/controllers/dashboard/cspadaptercharts/controller.go
pkg/managedcharts/cspadapter/cspadapter.go
pkg/multiclustermanager/routes.go
pkg/settings/setting.go

Adds the ability for rancher to upgrade the csp-adapter to a
specified minimum version.

Adding automatic upgrade for csp-adapter

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/37250

Bump remotedialer for pause/resume fix

---

pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go

Issue: https://github.com/rancher/rancher/issues/38064
Cluster with etcd only nodes require the etcd nodes to be restarted during encryption key rotation before restarting the control plane nodes.
There was a bug in rancher's encryption key rotation implementation where etcd nodes would not be restarted on subsequent iterations, because their plans were already in sync. This was fixed by adding an environment variable which utilizes the current control plane encryption key rotation phase to cause the plans to rerun. ~Also added `--force` to plan for `secrets-encrypt` command, so encryption key rotation can be reattempted, otherwise cluster could be stuck forever if something went wrong past prepare.~
Tested the following cases:
configuration | status
-|-
1 node all roles | ✔️
1 etcd, 1 …

Fixed etcd-only plans always in sync post-prepare

---

go.mod
go.sum

Backport of https://github.com/rancher/rancher/pull/38098
https://github.com/rancher/rancher/issues/38097

[2.5.15] Bump remotedialer for pause/resume fix

---

go.mod
go.sum

Backport of https://github.com/rancher/rancher/pull/38093
https://github.com/rancher/rancher/issues/38097

[2.5] Bump remotedialer for pause/resume fix

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/37681

Bump aks operator version to v1.0.6-rc3

---

go.mod
go.sum

Backport of https://github.com/rancher/rancher/pull/38093
https://github.com/rancher/rancher/issues/37250

[2.6.6] Bump remotedialer for pause/resume fix

---

package/Dockerfile

Opened in favor of https://github.com/rancher/rancher/pull/38154

Update ui version to v2.6.7-rc1

---

tests/validation/requirements.txt

ran in local the nodes were created and `rke up` was success.
Related PR (v3 tests) https://github.com/rancher/rancher/pull/37130
```
pytest -v -s --junit-xml=results.xml -k "test_install_config_1" tests/rke/
========================================================================================================================================================================================================== test session starts ==========================================================================================================================================================================================================
platform darwin -- Python 3.8.9, pytest-3.8.1, py-1.11.0, pluggy-1.0.0 -- /Users/izaac/repos/rancher-izaac/tests/validation/.venv/bin/python
cachedir: .pytest_cache …
```

[Automation] update boto library for rke tests to support latest ebs changes

---

pkg/controllers/dashboard/apiservice/apiservice.go
pkg/controllers/provisioningv2/rke2/bootstrap/controller.go
pkg/controllers/provisioningv2/rke2/bootstrap/controller_test.go
pkg/controllers/provisioningv2/rke2/common.go
pkg/impersonation/impersonation.go
pkg/serviceaccounttoken/secret.go

https://github.com/rancher/rancher/issues/38190

1.24 updates

---

.github/pull_request_template.md

Issue: Internal task
To ensure all PRs have all info including Test scenarios for QA to validate
This template will be implemented for every PR
No testing required.
No testing required. Just need a review
N/A
N/A
Does not affect any other code.

Adding Issue template for Devs to fill

---

pkg/controllers/management/aks/aks_cluster_handler.go
pkg/controllers/management/secretmigrator/clusters.go

Issue: https://github.com/rancher/rancher/issues/37164 
Thank you team, @jakefhyde

Fix panic from empty svc acc secret value

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/37164 (for panic fix)
https://github.com/rancher/rancher/issues/37681 (so @Josh-Diamond can retest!)

Bump aks operator to version v1.0.6

---

pkg/image/export/main.go

https://github.com/rancher/rancher/issues/37738

[release/v2.6] Check if image tag is empty during export

---

pkg/api/norman/store/cluster/cluster_store.go

**Issue**
Upgrades to 1.24 fail if cri dockerd isn't enabled on the rke config. https://github.com/rancher/rancher/issues/38160 
**Solution**
- Enable cri dockerd by default on creates and updates for >=1.24 clusters. 
- Introduce annotation on cluster `"io.cattle.cluster.cridockerd.enable"` in case user wants to override default behavior. Note that in this case cluster will break if docker runtime isn't available. We don't expect users to use this annotation unless they know what they're doing.

default cridockerd to true for >=1.24 unless set by annotation

---

pkg/agent/cluster/cluster.go

**Issue**
Agents for 1.19 and 1.18 clusters failing with `fatal msg="looking up cattle-system/cattle ca/token: failed to find configmap containing the CA crt: configmaps \"kube-root-ca.crt\" not found` https://github.com/rancher/rancher/issues/38255 
**Solution**
root ca configmap was introduced by default in every namespace starting [1.20](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#introducing-rootcaconfigmap). so we use the default secret for svc account to fetch ca.crt for <1.20 clusters. It's expected for this secret to exist for these clusters, the behavior changed with 1.24. Confirmed it by checking `cattle` service account and its corresponding secret in `cattle-system` with local 1.24 cluster.

use default svcaccount secret if root ca configmap not found

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/38014

Bump eks operator to version v1.1.4-rc3

---

package/Dockerfile

The automation caused a merge conflict and the drone build is failing preventing it from being resolved.

Automation caused a merged conflict.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Our issue templates don't automatically label or pre-fix with bug or RFE.
Prefix the title with [BUG] or [RFE].
Add the label kind/bug or kind/feature to the issue based on the issue type.

Add in distinction for bugs and RFEs in our issue templates

---

.drone.yml

Follow up on https://github.com/rancher/rancher/pull/37902, hopefully the final step that needs to be scoped.

[release/v2.6] Also scope stage-binaries to branch/tags in Drone

---

pkg/settings/setting.go
tests/framework/extensions/clusters/import.go
tests/v2/validation/charts/monitoring.go

Update rancher/shell version to v0.1.18-rc8.

Update rancher/shell version

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/38014

bump eks operator to version v1.1.4-rc4

---

package/Dockerfile

related to #38351 
Adapter version needs to be bumped to include a fix to the issue linked above

Adapter bump to 1.0.0-rc4

---

pkg/api/norman/server/managementstored/setup.go
pkg/api/norman/store/catalog/store.go
pkg/api/norman/store/cluster/cluster_store.go
pkg/apis/management.cattle.io/v3/catalog_types.go
pkg/apis/management.cattle.io/v3/cluster_types.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/management/etcdbackup/etcdbackup.go
pkg/controllers/management/node/cleanup.go
pkg/controllers/management/secretmigrator/assemblers.go
pkg/controllers/management/secretmigrator/catalog/assemblers.go
pkg/controllers/management/secretmigrator/catalogs.go
pkg/controllers/management/secretmigrator/clusters.go

Norman assumes that no updates to Status happen through the API,
including through the store, and so overwrites any changes[1]. This
means it is impossible to set a new value on Status for clusters or
catalogs upon update, it can only be done on create. This was resulting
in references to secrets being lost.
This change addresses the issue by moving secret values from Status to
Spec for clusters and catalogs.
Implementation notes:
- Notifiers are unaffected because the secret reference is the only
value in status, since there are no status values in the original
object it is not overwritten.
- SourceCodeProviderConfigs are unaffected because the secret reference
was not in status.
- ClusterTemplateRevisions are unaffected because they are never
updated, only new versions are created.
- …

Move cluster and catalog secrets to Spec

---

package/Dockerfile

Bump UI tags to v2.6.7-rc4

---

go.mod
go.sum

**Issues:**
https://github.com/rancher/rancher/issues/38417

Bump dynamiclistener

---

go.mod
go.sum
pkg/api/steve/proxy/proxy.go

Relies on rancher/steve#56 to go in first.

Adding enhancement to route for v2 prov

---

tests/v2/validation/Jenkinsfile_vpn
tests/validation/tests/v3_api/Jenkinsfile_vpn

adding option for jenkins environment variables for vpn connection

adding option for jenkins environment variables for vpn connection

---

tests/framework/extensions/charts/ranchergatekeeper.go
tests/framework/extensions/customresourcedefinitions/customresourcedefinitions.go
tests/framework/extensions/customresourcedefinitions/delete.go
tests/framework/extensions/customresourcedefinitions/list.go
tests/v2/validation/charts/gatekeeper.go
tests/v2/validation/charts/gatekeeper_test.go
tests/v2/validation/charts/resources/opa-k8srequiredlabels.yaml

Validation Tests
Implemented:
•	OPA Gatekeeper p0 test cases
o	Helper functions to install Gatekeeper chart
o	Helper to get unstructured List from a cluster resource
o	Helper to parse unstructured list to extract nested values
o	K8srequiredlabels.yaml constraint file to be applied by test
o	P0 validations

OPA Gatekeeper v2 p0 validation test cases

---

pkg/api/steve/proxy/proxy.go

related to rancher/rancher#38581

Fixing issues with cluster yaml and v2 prov

---

tests/validation/tests/v3_api/resource/gke_nlb.yml
tests/validation/tests/v3_api/resource/terraform/gke/gke.tf
tests/validation/tests/v3_api/resource/terraform/gke/variables.tf
tests/validation/tests/v3_api/test_create_ha.py

This will require terraform v0.13 for the gke_auth module to work. That was prepared for parameterization https://github.com/rancher/rancher/pull/31557.

Adding create GKE HA cluster to the create HA test

---

package/Dockerfile
pkg/settings/setting.go
scripts/package

Point back into the released charts post-merging https://github.com/rancher/charts/pull/2050

Revert "Merge pull request #38740 from aiyengar2/point_to_oob_charts_dev_branch"

---

pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/gke/gke_cluster_handler.go

https://github.com/rancher/rancher/issues/38715

Fix eks and gke panic errors

---

pkg/controllers/management/node/cleanup.go
pkg/controllers/management/node/controller.go

The `user-node-remove` handler has been removed, but the finalizer is not being cleaned up.
If the node is deleted and the finalizer is there, remove the finalizer anyway.
I tested by setting the finalizer on the object, and deleting the node, in which case the finalizer was successfully removed and the node deleted.

Remove user-node-remove if node is already being deleted

---

pkg/controllers/management/nodepool/nodepool.go

The nodepool controller is dangerous and spawns off reconciliation in uncontrolled goroutines. In certain cases, it is possible to see the nodepool controller trigger multiple reconciliation goroutines for the same nodepool concurrently, which can create and/or delete too many nodes. In addition, the nodepool controller was operating off of the node cache which is not ideal, and led to potential creation/deletion of too many nodes. Lastly, the nodepool controller was not properly returning the latest version of the nodepool object, which was causing the nodepool cache to be stale and lead to stale objects being returned. This was particularly exasperated by the fact that the nodepool controller would retrieve the latest object from API for mutation, rather than operating on the cached …

[release/v2.6.8-patch1] Make nodepool controller more reliable

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/37955

Bump aks operator to v1.0.7-rc1

---

package/Dockerfile

Bumps minimum version for https://github.com/rancher/rancher/issues/38794

Update CSP Adapter minimum version

---

pkg/auth/providers/azure/azure_actions.go
pkg/auth/providers/azure/clients/ms_graph_client.go

Rancher must fail the AuthConfig migration process if the Azure App registrations does not have the necessary permissions configured prior to migration.
Verify that admins have properly configured an existing app registration's permissions
in the Azure portal before they update their Azure AD auth config to use the new authentication flow.
Fetch the current AuthConfig from the database, update it in-memory to use the new endpoints,
and create a new test Azure client, thereby getting an access token to the Graph API.
Then parse the JWT and inspects the permissions contained within. If the admins had not set those as per docs,
then Rancher won't find the permissions in the test token and will return an error.
I am integrating the code from the https://github.com/rancher/rancher/issues/38754 …

Check Azure AD permissions before trying to migrate auth config

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/38877 
https://github.com/rancher/rancher/issues/38876

update rke to v1.3.15-rc1

---

pkg/controllers/dashboard/helm/operations.go

After successfully installing any chart through the Rancher UI (Apps menu) the `proxy` container of the `helm-operation-xxxxx` pod is not properly terminated and it receives status `NotReady`. This happens because we migrated the old `rancher/shell` image from Alpine to SLE-BCI (in v2.6.7 - https://github.com/rancher/rancher/pull/38622) and it doesn't contains the `killall` command (from `psmisc` program) used by [Helm operations](https://github.com/rancher/rancher/blob/v2.6.8/pkg/controllers/dashboard/helm/operations.go#L136).
This PR modifies [Helm operations](https://github.com/rancher/rancher/blob/v2.6.8/pkg/controllers/dashboard/helm/operations.go#L136) to use the `pkill` command instead of `killall`.
To reproduce this issue, install any valid chart from Apps and wait for it to …

[2.7] Use `pkill` instead of `killall` for `helm-operation`

---

pkg/auth/providers/azure/azure_actions.go
pkg/auth/providers/azure/clients/ms_graph_client.go

Rancher must fail the AuthConfig migration process if the Azure App registrations does not have the necessary permissions configured prior to migration.
Verify that admins have properly configured an existing app registration's permissions
in the Azure portal before they update their Azure AD auth config to use the new authentication flow.
Fetch the current AuthConfig from the database, update it in-memory to use the new endpoints,
and create a new test Azure client, thereby getting an access token to the Graph API.
Then parse the JWT and inspects the permissions contained within. If the admins had not set those as per docs,
then Rancher won't find the permissions in the test token and will return an error.
I am integrating the code from the https://github.com/rancher/rancher/issues/38754 …

[2.7] Validate config migration process for Azure AD

---

pkg/controllers/management/nodepool/nodepool.go

See original issue for details. This is a forwardport.

[release/v2.6] make nodepool controller more reliable

---

package/entrypoint.sh

This is to backport PR https://github.com/rancher/rancher/pull/38924 
Backport issue: https://github.com/rancher/rancher/issues/38918

[v2.6] add cgroupv2 script for k3s

---

pkg/controllers/dashboard/controller.go
pkg/controllers/management/clusterconnected/clusterconnected.go
pkg/controllers/management/wrangler.go
pkg/controllers/managementapi/controllers.go
pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/rke2/common.go
pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go

Issue: https://github.com/rancher/rancher/issues/38706

[release/v2.6] Correct v2prov controllers to be compatible with feature-flag multi-cluster-manager=false

---

pkg/auth/providerrefresh/refresher.go
pkg/auth/providerrefresh/refresher_test.go
pkg/auth/providers/providers.go
pkg/auth/tokens/test_utils.go

Issue: https://github.com/rancher/rancher/issues/36096 
Backport of https://github.com/rancher/rancher/pull/38894

[2.6.9] Refresh ExtrasByProvider from derived tokens

---

go.mod
go.sum
package/Dockerfile
pkg/apis/go.mod
pkg/apis/go.sum
pkg/settings/setting.go

Updating versions for v2.7.0-rc1

updates for v2.7.0-rc1 

---

pkg/controllers/options.go
pkg/types/config/context.go
pkg/wrangler/context.go

**Issue:**
https://github.com/rancher/rancher/issues/37350
https://github.com/rancher/rancher/pull/37436

[Forward Port] v2.6: Only update changed v2.6

---

pkg/controllers/provisioningv2/rke2/common.go
pkg/provisioningv2/rke2/configserver/server.go

Issue: https://github.com/rancher/rancher/issues/38916

[release/v2.6] Make rke2configserver more clear and concise in delivering secrets

---

pkg/controllers/management/nodepool/nodepool.go

See original issue for details. This is a forwardport.

[release/v2.7] make nodepool controller more reliable

---

tests/framework/clients/corral/config.go
tests/framework/clients/corral/corral.go

Implemented the corral client able to execute corral commands. As well as an extension for the corral aws package template.

[release/v2.7] Implemented a corral client in the automation framework

---

pkg/provisioningv2/rke2/planner/config.go

This is a back-port PR of https://github.com/rancher/rancher/pull/39173

[V2.6] Better handling of system-default-registry flag for RKE2/K3s

---

go.mod
go.sum

Related to rancher/rancher#38330. This required a change in steve, so I am pulling in steve ot the newest version available in steve's master branch.

Bump steve version

---

pkg/controllers/options.go
pkg/types/config/context.go
pkg/wrangler/context.go

https://github.com/rancher/rancher/pull/39081
**Forwardport Issue:**
https://github.com/rancher/rancher/issues/39160

Only update changed v2.7

---

pkg/controllers/dashboard/controller.go
pkg/controllers/management/clusterconnected/clusterconnected.go
pkg/controllers/management/wrangler.go
pkg/controllers/managementapi/controllers.go
pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/rke2/common.go
pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go

Issue: https://github.com/rancher/rancher/issues/38952

[release/v2.7] Correct v2prov controllers to be compatible with feature-flag multi-cluster-manager=false

---

package/Dockerfile

Updating UI tags for v2.7.0-rc3

Updating UI tags for v2.7.0-rc3

---

tests/framework/clients/corral/config.go
tests/framework/clients/corral/corral.go

Implemented the corral client able to execute corral commands. As well as an extension for the corral aws package template.

[release/v2.6] Implemented a corral client in the automation framework

---

tests/validation/tests/v3_api/resource/terraform/k3s/master/cis_v125_masterconfig.yaml
tests/validation/tests/v3_api/resource/terraform/k3s/master/cluster-level-pss.yaml
tests/validation/tests/v3_api/resource/terraform/k3s/master/install_k3s_master.sh
tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf
tests/validation/tests/v3_api/resource/terraform/k3s/master/join_k3s_master.sh
tests/validation/tests/v3_api/resource/terraform/k3s/master/v125_policy.yaml
tests/validation/tests/v3_api/resource/terraform/k3s/master/variables.tf
tests/validation/tests/v3_api/test_import_k3s_cluster.py

Signed-off-by: Shylaja Devadiga <sdevadiga@suse.com>
Updates to automation with respect to change to psa in k8s v1.25

remove_psp_in_cis_mode_for_k3s_v1.25

---

pkg/settings/setting.go

This should be an array instead of an object.

Change customLinks default to empty string

---

chart/README.md

https://github.com/rancher/rancher/issues/39236
This PR adds EULA & T&C to Rancher Helm Chart README.

add EULA & T&C to Rancher Helm Chart README

---

pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go

Refers to https://github.com/rancher/fleet/issues/948

Support cluster specific registry for managed fleet agent

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Unrc versions
* aks operator: v1.0.7
* eks operator: v1.1.5
* rke: v1.3.15

Unrc aks operator, eks operator, and rke charts

---

pkg/image/origins.go

Adds new `hardened-node-feature-discovery` dependency to `origins.go`

add hardened-node-feature-discovery to origins.go

---

package/Dockerfile

Bumps the version of CSP adapter to 2.0.0

Bump rancher-csp-adapter version

---

pkg/cluster/private_registry.go
pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go

https://github.com/rancher/rancher/issues/39468
When a v3 (rke1) cluster is used, Rancher deploys the fleet agent (by way of fleet) incorrectly.
The solution for this is a 5 line change, but to illustrate the actual change being made, I will describe how Fleet-agent is deployed into a Rancher cluster.
Rancher has a controller called the "fleetcluster" controller, which creates corresponding Cluster objects for Fleet. Fleet deploys the fleet-agent into the downstream cluster by way of [manager initiated registration](https://fleet.rancher.io/cluster-overview#manager-initiated-registration). As such, Fleet cluster objects need to be created. The original logic that was implemented for private registry assumed that the private registry information always existed on the …

[release/v2.7] Fix fleet cluster creation to include private registry in spec when legacy/management cluster is detected

---

tests/framework/pkg/clientbase/ops.go

The session.Cleanup was not working properly for v1 resources being created.
Missing line that sets the resources, so any empty resources attempted to be deleted.
Ran tests with cleanup enabled. Mainly the go integration test.

Minor Bug fix for session.Cleanup of v1 resources.

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Unrc rancher rke chart for v2.7.0

[DNM KDM release v2.7.0] Unrc rancher rke chart for v2.7.0

---

tests/validation/tests/v3_api/resource/terraform/k3s/master/policy.yaml

Update policy.yaml needed with the move of the servicelb controller.

update policy for k3s hardened cluster

---

tests/validation/tests/v3_api/test_airgap.py
tests/validation/tests/v3_api/test_airgap_ha.py

https://github.com/rancher/qa-tasks/issues/528
airgap currently has no way to test various versions of rancher. only what is on rancher-latest 
make the install variable
also updated the sed script so that we don't zip/unzip all the images (takes a lot of time and space that isn't necessary)

adding modular helm repo install

---

Dockerfile.dapper
package/Dockerfile

Signed-off-by: PratikforCoding <kotalpratik@gmail.com>

Updated embedded k3s version for rancher to 1.24.8+

---

pkg/settings/setting.go
tests/framework/extensions/clusters/import.go
tests/v2/validation/charts/monitoring.go

Bump rancher/shell version to v0.1.19-rc7

---

pkg/image/export/main.go
pkg/image/external/external.go
pkg/image/external/external_test.go

Need to backport #39584 to v2.6
This PR
I disabled `./test`, `./validate` and `./chart/ci` in `scripts/ci` and used `make ci` to test the generation of the images lists. Then verified manually the Windows images were no longer present in the Linux lists. 
Updated some unit tests.

[v2.6] Backport #39584: Remove windows images from rancher-images.txt

---

Dockerfile.dapper
package/Dockerfile

[v2.6] Backport: Updated embedded k3s version for rancher to 1.24.8+

---

pkg/api/norman/customization/aks/handler.go

No-conflict cherry picked from commit 0aceac57876633ad31a49b3053dbe89aee1d4754
Backport of https://github.com/rancher/rancher/pull/39612, see details there.

Improved Azure login error handling

---

tests/framework/extensions/users/users.go
tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_test.go

Same as the problem statement for https://github.com/rancher/rancher/pull/39666 
Task: https://github.com/rancher/qa-tasks/issues/538

[2.7]Adding additional test cases to the rbac suite

---

tests/integration/suite/test_node.py

Backport of https://github.com/rancher/rancher/pull/39565

[release/v2.6] Randomize hostnamePrefix in test_node

---

tests/validation/tests/v3_api/common.py

There are many flaky tests in jenkins job rancher-v3_ontag_import_k3s_certification
Latest run show following tests that fails despite everything is fine in the cluster.
tests.v3_api.test_service_discovery.test_dns_record_type_workload_when_workload_scale_down
tests.v3_api.test_service_discovery.test_dns_record_type_multiple_workloads
tests.v3_api.test_websocket.test_websocket_view_logs
tests.v3_api.test_service_discovery.test_dns_record_type_hostname
tests.v3_api.test_service_discovery.test_service_discovery_when_workload_upgrade
tests.v3_api.test_service_discovery.test_dns_record_type_workload_when_workload_scale_up
tests.v3_api.test_service_discovery.test_dns_record_type_workload_when_workload_upgrade
tests.v3_api.test_websocket.test_websocket_launch_kubectl …

ontag_k3s_certification job flaky test fixes

---

pkg/controllers/management/auth/token.go
pkg/controllers/management/auth/token_test.go
pkg/controllers/management/auth/user_attribute_handler.go

https://github.com/rancher/rancher/issues/39401
Before, a userattribute handler would check if the ExtraByProvider
field was null and trigger a refresh. ExtraByProvider contains
data that is available only on tokens. When there was no token
associated with the user corresponding to the userattribute, the
handler would fire endlessly. This happened because the field
continued to be null but the refresh process would update the
LastRefreshed field which would cause the userattribute handler
to execute again.
Now, the ExtraByProvider check is done on a token
handler. The token handler is aware that the tokens existence
may make populating the field possible and the refresh process,
makes no changes to the token object. This avoids nonstop firing
of handlers.
1. Create a user in v2.6.2
2. …

Fix userattribute

---

tests/framework/clients/rancher/catalog/clusterrepo.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Issue: https://github.com/rancher/qa-tasks/issues/397, https://github.com/rancher/qa-tasks/issues/396, https://github.com/rancher/rancher/issues/38793
Add test to validate create/update/delete of HTTP and Git cluster repos

Add integration test for Catalog V2 cluster repos

---

pkg/api/norman/customization/aks/listers.go

The API used to gather all Azure VM sizes does not include information on the capabilities of each VM in a given region. This prevents the UI from determining if a given VM supports features such as Availability Zones or Accelerated Networking.
After discussion, we agreed that the existing API used to gather Azure VM sizes should be enhanced to also return the capabilities of each VM, so that particular UI fields can be enabled or disabled based off of the VM selection and given Azure region. Also, while the URL of the API includes the term `aks`, this API has been used for Azure node driver clusters for some time so I have not changed the name of the path.
Perform CURL requests against the Azure VM size API, `https://<RANCHER_SERVER_URL>/meta/aksVMSizes?cloudCredentialId=<AZURE_CLOUD_CRED …

enhance aksVmSizes path to include information on VM feature support

---

pkg/api/steve/disallow/disallow.go

https://github.com/rancher/rancher/issues/38701

psact update

---

tests/framework/extensions/users/users.go

https://github.com/rancher/rancher/issues/39710
There was a bit of a timing issue when adding a `project-member` role to a user in order to create a namespace, where the `project-member` role is not fully set causing a `Resource type [namespace] is not creatable` error. 
I added two extra checks to make sure the ProjectRoleTemplateBinding is successfully created.
CI drone tests pass.

[v2.6] Fixed intermittent failure with TestCreateNamespaceProjectMember test case

---

tests/validation/tests/v3_api/common.py

Backport (https://github.com/rancher/rancher/pull/39602) PR for k3s-cert flaky test fixes.

backport k3s-cert fixes

---

tests/framework/extensions/users/users.go

There was an issue with adminClient in extensions/users.go it was being initialized twice, causing failures in the drone CI pipeline.
Go syntax issue that was missed, because the branch wasn't rebased.
Rebased branch and removed the extra adminClient variable.

Fixed variable issue that was causing failures in CI drone Pipeline

---

pkg/data/management/machinedriver_data.go

update Nutanix Rancher Node driver to v3.3.0
https://github.com/rancher/rancher/issues/39333

Update Nutanix driver to v3.3.0

---

pkg/crds/dashboard/crds.go

https://github.com/rancher/rancher/issues/38701

psact update 2

---

tests/validation/tests/v3_api/test_ingress.py

Backport PR (https://github.com/rancher/rancher/pull/39816) for k3s-cert traefik ingress fixes

backport k3s-cert traefik ingress fixes

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/39860

Bump AKS and EKS operators to new branch tags

---

go.mod
go.sum

Related to rancher/rancher#36681. Since the code for this change was in Steve, Steve's version needs to be bumped to pull the changes in.

Bump steve version for counts-diff changes

---

pkg/controllers/management/auth/token.go
pkg/controllers/management/auth/token_test.go
pkg/controllers/management/auth/user_attribute_handler.go

**Backport Issue:**
https://github.com/rancher/rancher/issues/39888
https://github.com/rancher/rancher/pull/39624

[Forwardport] v2.7: Fix userattribute

---

chart/templates/deployment.yaml
chart/tests/README.md
chart/tests/deployment_test.yaml
chart/values.yaml

backport: https://github.com/rancher/rancher/issues/39942
pr: https://github.com/rancher/rancher/pull/39865/

[Backport 2.6] Add probe customization backport

---

chart/Chart.yaml

Bump required K8s version in Rancher chart

---

pkg/api/norman/customization/project/project_actions.go
pkg/api/norman/customization/project/project_actions_test.go
pkg/api/norman/server/managementstored/setup.go

Rancher does not properly detect if PSPs are enabled in a K3s cluster. This prevents creating a project with a specific PSP within the cluster.
Check the `kube-apiserver-arg`s to see if PSPs are enabled for the cluster.
The repro steps are mostly valid, although I did have to use a different guide than the one linked in the issue. I have synthesized the steps required to setup a k3s hardened cluster with PSPs enabled in this [repo](https://github.com/sbstp-suse/x-notes/blob/main/k3s-hardened/) and there's an `install.sh` script in there to perform all the steps necessary to setup hardening. Once the machine is ready, you can create a custom cluster using a spec similar to the one in the `README` file and register the cluster by running the command provided by rancher.
We're discussing the …

­[2.7] Properly detect if PodSecurityPolicies are enabled in K3s clusters during project creation

---

package/Dockerfile

https://github.com/rancher/rancher/issues/39940

Bump csp-adapter

---

pkg/api/norman/customization/project/project_actions.go
pkg/api/norman/customization/project/project_actions_test.go
pkg/api/norman/server/managementstored/setup.go

[2.6] Properly detect if PodSecurityPolicies are enabled in K3s clusters during project creation

---

tests/validation/tests/v3_api/test_node_label.py

Accidentally left debug print statements in the test_node_label_custom_edit test.
Removed print statements from test node label custom edit

[v2.6 ]Removed print statements from test node label custom edit

---

pkg/settings/setting.go

* Ensure our apps are installable once PSAs are rolled out on Rancher clusters.
* Mark charts namespaces as system namespaces.

Update system namespaces for Helm charts

---

Dockerfile.dapper
package/Dockerfile

https://github.com/rancher/rancher/issues/39960

bump the embedded k3s version to 1.25.5

---

pkg/types/config/context.go

https://github.com/rancher/rancher/issues/38775
Wrangler context's user agent should be configured as well if it is on the management context.
Configure it in management context's WithAgent function.

Change management's wrangler context's user agent

---

pkg/controllers/management/node/cleanup.go

In situations where a node is set to be drained before deletion, but that drain operation consistently fails, the node and its related resources will not be deleted from the infrastructure provider. This is due to how we handle errors returned from a `wait.ExponentialBackoff` call. While the function we pass to the exponential backoff never returns an error, an error (`wait.ErrWaitTimeout`) can still be returned if the operation is not completed in the specified amount of time. This prevents the node from being deleted for RKE1 clusters.
Explicitly drop that error so that the node is always deleted regardless of the drain operations outcome. This change aligns behavior with the existing comments regarding deletion after drain. 
This can be tested by creating a cluster with an invalid …

[v2.6] Back port #39557: Ensure node deletion even if drain fails to complete

---

tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_test.go

Back port of https://github.com/rancher/rancher/pull/39949

[2.6]Adding the project rbac test cases to the existing rbac suite

---

tests/v2/validation/Jenkinsfile

Forwardport of: https://github.com/rancher/rancher/pull/39578

[forwardport] allow user-entered variables priority over global variables

---

go.mod
go.sum
pkg/api/steve/userpreferences/rancherpref.go

The AdminClient call now needs an extra parameter.  This change adds that. 
~~Requires https://github.com/rancher/steve/pull/70 to be merged first and then update go.mod in this PR~~  This has merged
Issue:  https://github.com/rancher/rancher/issues/39413

Bump steve version and update affected calls to AdminClient

---

pkg/controllers/provisioningv2/rke2/bootstrap/controller.go

Part of groundwork for #39139
We need a mechanism to support pausing the various CRs in our CAPI implementation, so we can disable cluster reconciliation during disruptive actions such as encryption key rotation.
Add missing predicates to rke bootstrap controller, including checking for pausing as well as other required predicates we were missing.
https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html?highlight=bootstrap#bootstrap-provider-specification
**Note:** there are some predicates which have been added, which do not appear in the upstream docs as requirements, however these predicates (for example, checking if `capiCluster.Status.InfrastructureReady == false`) are added because although we functionally always set `InfrastructureReady = true`, bootstrapping before the …

Add CAPI predicates to RKEBootstrap

---

pkg/controllers/management/auth/register.go
pkg/controllers/management/secretmigrator/register.go
pkg/controllers/managementuser/rbac/handler_base.go
pkg/wrangler/context.go

Some handlers have been configured to use clients with useragents that are named to reference the handlers that use them.
https://github.com/rancher/rancher/issues/38775
We would like to use the new useragent functionality in a small way that only mainly only affects team1 before rolling it out to more parts of rancher.
Add useragent to some select handlers.

Add useragent to handlers

---

scripts/provisioning-tests

[v2.7] Remove debug echo & add docs on version selection in provisioning-tests

---

scripts/provisioning-tests

[v2.6] Backport - Remove debug echo & add docs on version selection in provisioning-tests

---

tests/framework/clients/ec2/client.go
tests/framework/clients/ec2/config.go
tests/framework/extensions/nodes/ec2/ec2.go
tests/v2/validation/provisioning/config.go
tests/v2/validation/provisioning/nodeproviders.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/custom_cluster_test.go

Backport of [40031](https://github.com/rancher/rancher/pull/40031)

[v2.6 Backport] Windows Custom Cluster Automation

---

tests/v2/validation/Jenkinsfile

When running our go validation Jenkins job, aborting them meant that the images and containers created were not properly cleaned up causing issues down the line.
Updated the Jenkinsfile to ensure that the docker image and container created from the Jenkins job will be cleaned up even during a failure or an abort by adding a catch.
Ran Jenkins job and aborted to make sure the job was cleaned up.

[v2.6] Updated the Jenkinsfile to ensure proper docker cleanup

---

package/Dockerfile

[2.6] Update UI tag

---

package/Dockerfile

https://github.com/rancher/dashboard/releases/tag/v2.7.1
https://github.com/rancher/ui/releases/tag/v2.7.1

[2.7] Updates UI tags for 2.7.1

---

pkg/apis/rke.cattle.io/v1/cluster.go
tests/integration/pkg/tests/machineprovisioning/machine_test.go

Issue: https://github.com/rancher/rancher/issues/40267
Make provisioning tests drain super aggressive

[release/v2.7] make drain in provisioning tests aggressive

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml

https://github.com/rancher/rancher/pull/40190
**Issue:**
https://github.com/rancher/rancher/issues/39841

[Forwardport] v2.7: Add start probe

---

pkg/data/management/machinedriver_data.go

- https://github.com/rancher-plugins/rancher-machine-driver-oci/issues/17
- See also: https://github.com/rancher/rancher/pull/39255
- 
Previous versions of the [OCI Node Driver](https://github.com/rancher-plugins/rancher-machine-driver-oci) only allowed the user to specify Oracle Linux based platform images to the driver (even though RKE/RKE2) has support for multiple operating systems. 
This MR updates [OCI Node Driver](https://github.com/rancher-plugins/rancher-machine-driver-oci) to version `v1.3.0`, which allows the user to specify operating system base images other than Oracle Linux (e.g. Ubuntu).
Tested machine driver installing RKE & RKE2 on multiple operating systems and versions of Ubuntu, Oracle Linux, and Red-Hat Linux.

[2.7] Update OCI node driver to v1.3.0

---

chart/templates/post-delete-hook-psp.yaml
chart/templates/validate-psp-install.yaml
chart/values.yaml

Add setting and logic to handle PSP enablement

---

pkg/client/generated/management/v3/zz_generated_aks_node_pool.go

The only thing this PR does is run `go generate` to update the generated files.

run go generate

---

pkg/controllers/provisioningv2/rke2/provisioninglog/provisioninglog.go

If the provisioning log config map fails to reconcile on it's first iteration, it will never reconcile. 
If a config map meets the expected criteria to be the provisioning log, but the provisioning cluster cannot be accessed, reenqueue it for evaluation later. 
Due to this being a race condition, testing is quite difficult, as the window between creating a cluster and the config map being reconciled is quite slim.

reenqueue provisioning log config map if cluster not found

---

pkg/controllers/provisioningv2/rke2/provisioninglog/provisioninglog.go

If the provisioning log config map fails to reconcile on it's first iteration, it will never reconcile. 
If a config map meets the expected criteria to be the provisioning log, but the provisioning cluster cannot be accessed, reenqueue it for evaluation later. 
Due to this being a race condition, testing is quite difficult, as the window between creating a cluster and the config map being reconciled is quite slim.

[Backport v2.6] reenqueue provisioning log config map if cluster not found

---

chart/templates/post-delete-hook-cluster-role.yaml
chart/templates/post-delete-hook-psp.yaml
chart/templates/validate-psp-install.yaml
chart/values.yaml

https://github.com/rancher/rancher/issues/40327

Add PSP references along with setting and logic to handle PSPs

---

pkg/apis/rke.cattle.io/v1/cluster.go
tests/integration/pkg/tests/machineprovisioning/machine_test.go

Issue #: https://github.com/rancher/rancher/issues/40268
Backport of https://github.com/rancher/rancher/pull/40236

[v2.6] make drain in provisioning tests aggressive

---

chart/templates/validate-psp-install.yaml

Updated handling per https://github.com/rancher/rancher/issues/40327

Update check for PSP capabilities

---

pkg/auth/api/secrets/cleanup.go
pkg/auth/cleanup/service.go
pkg/auth/cleanup/service_test.go
pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/controllers/management/auth/auth_config.go
pkg/controllers/management/auth/auth_config_test.go

The first [commit](https://github.com/rancher/rancher/pull/40379/commits/588db18d1ac81602bc27eef9812f79f4d48642b4) has the same as the code changes already reviewed for auth provider cleaning up resources after being disabled.
The [second](https://github.com/rancher/rancher/pull/40379/commits/97fdbe14cacdac975befacf3838d107a99902afc) is just a quick fix to address a small issue https://github.com/rancher/rancher/issues/39908, since it's related to auth providers.
~~The [third](https://github.com/rancher/rancher/pull/40379/commits/d3dc6a7e92a4d9aa05f96ca3dfe85e27bb32d46c) addresses https://github.com/rancher/rancher/issues/40360. This changes how the auth config annotation is updated. We must use the unstructured client to preserve all the fields of a config when it is updated. When using …

[2.6] Add CRTB, PRTB, GRB, User cleanup when an auth provider is disabled

---

pkg/api/norman/store/cluster/cluster_store.go

Forward port PR for https://github.com/rancher/rancher/pull/40419 
Issue: https://github.com/rancher/rancher/issues/40318

[v2.7] set default for useInstanceMetadataHostname

---

package/Dockerfile
pkg/settings/setting.go

[v2.7] Update system agent to 0.3.2 (un-rc)

---

pkg/controllers/dashboard/systemcharts/controller.go

Related to #40326. Since the mutating webhook will now be included in the chart definition of the webhook (see rancher/webhook#189), rancher will need to "adopt" the pre-existing mutating webhook configurations that didn't belong to the webhook's chart definition.
Since we only want this to work for the webhook, we only set the force adopt flag to true when the webhook is the chart that we are installing.

Forcing adoption of resources for rancher-webhook

---

pkg/agent/clean/cluster.go
pkg/controllers/management/usercontrollers/controller.go

Re-importing previously detached clusters on fails on v2.7.2. The problem is that on initial detachment, some cluster-wide webhook resources remain (such as its configurations), so on re-import, Rancher tries to talk to a non-existing webhook service because it detects a configuration. 
Delete all cluster-wide resources related to rancher-webhook on cluster detachment. Specifically:
1. MutatingConfiguration "rancher.cattle.io"
2. ValidatingConfiguration "rancher.cattle.io"
3. Cluster Role Binding "rancher-webhook"
All the other resources are taken care of by the agent job that already deletes the `cattle-system` namespace.
There are two changes:
1. Change the agent code that performs actual deletion of resources.
1. Change the Rancher code that configures the agent's job permissions - add …

Delete webhook-related resources on cluster detachment

---

pkg/controllers/management/auth/auth_config.go
pkg/controllers/management/auth/auth_config_test.go

Use the unstructured client to update auth config objects

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

bump ui tag to v2.7.2-rc3

---

pkg/auth/api/secrets/fields.go

forward port of the https://github.com/rancher/rancher/pull/40525 PR.

[2.7] Add a cleanup entry for KeyCloak OIDC client secret

---

tests/framework/extensions/rancherversion/config.go
tests/framework/extensions/rancherversion/rancherversion.go
tests/v2/validation/prime/README.md
tests/v2/validation/prime/prime_test.go

https://github.com/rancher/qa-tasks/issues/544
we need some automation for checking rancher p
This PR includes checking /rancherversion and ui-brand, ensuring that it matches what we expect. This can also be used ( and may need to be checked ) for the community version. 
local run is passing, will post jenkins run separately

init test cases for rancher p

---

pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go

When importing RKE2/K3s clusters into Rancher, we allow users to upgrade the Kubernetes version in the UI. Doing so deploys the System Upgrade Controller, which executes a plan that upgrades the RKE2/K3s service. The System Upgrade Controller also deploys `PodSecurityPolicy` resources. This presents a problem when we are upgrading to a version of Kubernetes which no longer supports PSPs. If we continue to use the version of SUC which deployed PSPs after the upgrade to 1.25, or any version that does not support PSPs, we would not be able to delete or modify the controller as the helm operations which deploys it would fail due to an inability to clean-up / modify the PSPs still tracked by the chart. 
This problem and its solution are somewhat tied to #40384, which defines a similar problem …

[2.7] Pass specific values to SUC chart to enable/disable PSPs for imported RKE2/K3s clusters

---

.drone.yml

Forwardport of https://github.com/rancher/rancher/pull/39707

[release/v2.7] Skip provtest CI when local repo branch is used

---

pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go

Custom clusters were never getting deleted.
Make sure to check for correct APIVersion and Kind when deleting.
Tested manually, cluster was successfully cleaned up.

Fix custom clusters not deleting controlplane nodes

---

pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go

Custom clusters were never getting deleted.
Make sure to check for correct APIVersion and Kind when deleting.
Tested manually, cluster was successfully cleaned up.

[v2.7] Fix custom clusters not deleting controlplane nodes

---

go.mod
go.sum

Related to https://github.com/rancher/rancher/issues/40667

[2.6] Bump steve to latest 2.6 version

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/40668

[v2.6] update rke to v1.3.19-rc3

---

.github/workflows/stale.yml

To avoid stale bot closing issues like this: https://github.com/rancher/rancher/issues/39158

Adds kind/tech-debt label to stale bot ignore list

---

pkg/provisioningv2/kubeconfig/manager.go

https://github.com/rancher/rancher/issues/40742
In certain cases, the v2prov kubeconfig manager will generate the kubeconfig with stale data. If the following parameters get changed, then the kubeconfig secret will not be updated.
* Internal Server URL 
* Internal Server CA
* User token
* Management cluster name
This PR adds checking to the kubeconfig secret value to ensure it is up to date.
There is a possibility that Rancher will thrash and constantly recreate the kubeconfig, if something doesn't match correctly. I did my best to add logging to detect this, and these logs are available at the INFO level.
Past this, there is no functional change to the method that generates the kubeconfig, but there was some rearrangement of the function calls for optimization (and to expose information …

[release/v2.6] Validate kubeconfig on retrieval in kubeconfigmanager

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/40688

[v2.7] update rke to v1.4.4-rc2

---

pkg/provisioningv2/kubeconfig/manager.go

Forwardport of: https://github.com/rancher/rancher/pull/40744
https://github.com/rancher/rancher/issues/40741
In certain cases, the v2prov kubeconfig manager will generate the kubeconfig with stale data. If the following parameters get changed, then the kubeconfig secret will not be updated.
* Internal Server URL 
* Internal Server CA
* User token
* Management cluster name
This PR adds checking to the kubeconfig secret value to ensure it is up to date.
There is a possibility that Rancher will thrash and constantly recreate the kubeconfig, if something doesn't match correctly. I did my best to add logging to detect this, and these logs are available at the INFO level.
Past this, there is no functional change to the method that generates the kubeconfig, but there was some rearrangement of …

[release/v2.7] Validate kubeconfig on retrieval in kubeconfigmanager

---

package/Dockerfile
pkg/client/generated/management/v3/zz_generated_aks_node_pool.go
tests/v2/codecoverage/package/Dockerfile

prepare for rc5

---

tests/v2/validation/prime/prime_test.go

session was refactored not to need testingT anymore, this was missed due to rebase caching.

refactor to remove testingT from session call

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/40787
Note: `go generate` run locally and there were no new types generated, as expected!

Unrc aks operator to v1.0.9

---

pkg/data/management/podadmissionconfigurationtemplate_data.go

https://github.com/rancher/rancher/issues/40761
The current description for the built-in [PSACT templates](https://github.com/rancher/rancher/blob/2691d3557c76de96bdb0ff8735105fac2650c0c0/pkg/data/management/podadmissionconfigurationtemplate_data.go) are vague, and convey very little about the security posture they provide. 
Update the descriptions based on the suggestions from the linked issue: 
Run a fresh installation of Rancher, check the description on the builtin PSACTs, and we should see the new ones. 
N/A 
N/A 
N/A 
N/A

update the descriptions of PSACT rancher-restricted and rancher-privileged to be more specific

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Prepare v2.7.2-rc6

---

pkg/controllers/managementapi/usercontrollers/usercontroller.go
pkg/controllers/managementapi/usercontrollers/usercontroller_test.go

Before 23d89f9, when a cluster entered the managementapi user controller, it was guaranteed to enqueue all cluster controllers at the end of the sync unless it encountered an error. With 23d89f9, the sync would exit early in many cases, thereby failing to enqueue the cluster controllers. When a cluster is deleted, one of these cluster controllers is supposed to call Stop on the cluster manager and thereby stop the context, but since this was not always happening, the context sometimes remained running and would mean the healthsyncer controller continued to run and interminably emit errors for the now missing cluster.
This change addresses the problem by adding calls to enqueue the cluster controllers after every success return.
It also prevents reenqueuing nil clusters by copying the …

Ensure cluster controllers are always reenqueued

---

pkg/auth/providers/ldap/ldap_client.go

Related to issue #35259. Forward port of the changes made for 2.6 in #38736.

[2.7] OpenLDAP re-bind SA as fallback

---

tests/framework/extensions/clusters/import.go
tests/v2/validation/charts/monitoring.go

Rancher/shell images were hardcoded values.
Updated places where rancher/shell images have been used to their corresponding v3 setting IDs.

[2.6] Update validation tests to use rancher shell image's setting value

---

pkg/auth/providers/ldap/ldap_client.go

This reverts commit f2faf1a8aa1081301e1fe6c21637fe9b7044f188, reversing changes made to 8835c43d5d3e1599695a5d9bba989afac5c93436. Related to #35259

Revert "Merge pull request #40391 from MbolotSuse/ldap-rebind-2.7"

---

tests/scripts/final_rc_checks/final_rc_checks.py

This is a standalone script for final RC checks that was previously stored locally and now adding to the repo.
This script was used for multiple releases for the final RC checks the qa team runs on the final RC. This was part of [qa-task 613](https://github.com/rancher/qa-tasks/issues/613)
The problem was that this script was floating around internally and there was no actual place the script lived in for others to use when needed.
Markus created a standalone script directory to hold all the standalone scripts. Adjustments were made to the script to pass arguments into the script while running it.
This script has been used many times for about the past 3 releases to do the final RC checks.
This is not a part of Jenkins as it is a standalone script. This script as of now is run manually. …

Standalone script for final RC checks

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Changes:
- bump UI tag to v2.7.2-rc8

Prepare for v2.7.2-rc8

---

tests/framework/pkg/session/session.go

Add retry to cleanup

---

tests/framework/pkg/session/session.go

https://github.com/rancher/rancher/pull/41040

[Backport] v2.6: Add retry to cleanup

---

tests/framework/extensions/kubeapi/rbac/create.go
tests/framework/extensions/kubeapi/rbac/list.go
tests/framework/extensions/kubeapi/rbac/rbac.go
tests/framework/extensions/users/users.go

User can be removed from a project but continue to have permissions for a window of time that is significant in a scripting/testing context.
Wait for rolebindings that back the PRTB to be deleted before moving on.
Tested with an integration tests using this function on local and downstream cluster.
This will be used by multiple tests including one I am adding.

Wait for user removal from project to finish

---

tests/framework/extensions/kubeapi/namespaces/namespaces.go
tests/framework/extensions/kubeapi/rbac/list.go
tests/framework/extensions/kubeapi/rbac/rbac.go
tests/framework/extensions/users/users.go

1. Getting namespace depends on list permissions for a user because it is actually using the dynamic client's list function.
2. User still has relevant permissions for a window of time after removing user from cluster.
3. Adding cluster role to user can get stuck waiting for the `ClusterConditionInitialRolesPopulated` condition to be when targeting the "local" cluster. This will never be true because the "local" cluster does not have a creator.
1. Use the dynamic client's get function.
2. Wait for clusterrolebindings to be deleted before proceeding when removing user from a cluster.
3. Skip waiting for `ClusterConditionInitialRolesPopulated` condition if targeting the "local" cluster.

Add crb wait

---

tests/framework/extensions/kubeapi/namespaces/namespaces.go
tests/framework/extensions/kubeapi/rbac/list.go
tests/framework/extensions/kubeapi/rbac/rbac.go
tests/framework/extensions/users/users.go

https://github.com/rancher/rancher/pull/41064

[Backport] v2.6: Add crb wait v2.6

---

tests/framework/clients/corral/corral.go
tests/framework/clients/rancher/config.go
tests/framework/extensions/pipelineutils/setup.go
tests/framework/extensions/registries/registries.go
tests/framework/pkg/environmentflag/environmentflags.go
tests/framework/pkg/environmentflag/zz_environmentflags.go
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Jenkinsfile.e2e
tests/v2/validation/ranchercleanup/main.go
tests/v2/validation/rancherha/main.go
tests/v2/validation/registries/config.go
tests/v2/validation/registries/registry_test.go
tests/v2/validation/scripts/build_corral_packages.sh
tests/v2/validation/scripts/build_registries_images.sh
tests/v2/validation/scripts/rancher_cleanup.sh
tests/v2/validation/scripts/setup_registries_environment.sh

Forward port of: https://github.com/rancher/rancher/pull/40930

initial registries setup and validation v2.7

---

tests/v2/validation/Dockerfile.validation
tests/v2/validation/Jenkinsfile
tests/v2/validation/Jenkinsfile_vpn
tests/v2/validation/provisioning/rke2/custom_cluster.go
tests/v2/validation/provisioning/rke2/etcd_backup_restore.go
tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go

https://github.com/rancher/qa-tasks/issues/679
The go path in our Dockerfile was not in a traditional directory structure, and was causing issues when attempting to access local files using the `user.HomeDir` function to get absolute paths. 
Move `/go` to `/root/go` (since in our Docker container the go path should be at root).
Jenkins run with a rke2 hardened cluster.

[v2.7] Updated Dockerfile and Jenkinsfile to account for new Go path.

---

tests/v2/validation/Dockerfile.validation
tests/v2/validation/Jenkinsfile
tests/v2/validation/Jenkinsfile_vpn
tests/v2/validation/provisioning/rke2/custom_cluster.go
tests/v2/validation/provisioning/rke2/etcd_backup_restore.go
tests/v2/validation/provisioning/rke2/etcd_backup_restore_test.go

https://github.com/rancher/qa-tasks/issues/679
The go path in our Dockerfile was not in a traditional directory structure, and was causing issues when attempting to access local files using the `user.HomeDir` function to get absolute paths. 
Move `/go` to `/root/go` (since in our Docker container the go path should be at root).
Jenkins run with a rke2 hardened cluster.

[v2.6] Updated Dockerfile and Jenkinsfile to account for new Go path

---

tests/v2/validation/provisioning/rke2/custom_cluster.go

For RKE1/RKE2/K3S cluster types, recently I made a change to include additional resource checks. This was to ensure that we aren't solely testing that a cluster provisioning, but other basic checks we already do manually. It seems that custom clusters specifically was missed, so this PR addresses.
Add in the missing resource checks for RKE2 custom clusters that were missed in the original PR.
Jenkins runs can be provided offline if needed.

[v2.6] Add missing resource checks to RKE2 custom cluster

---

README.md

Updated build status to release/v2.7

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/41200

Bump rancher/system-agent version to v0.3.3-rc2

---

dev-scripts/build-local.sh
docs/development.md

There's no script available for a local build with cross-platform support.
Add a local build script that developers can leverage when building dev tagged images.

Add build-local.sh script

---

pkg/controllers/provisioningv2/controllers.go
pkg/provisioningv2/rke2/planner/instructions_test.go
pkg/provisioningv2/rke2/planner/planner.go
pkg/provisioningv2/rke2/planner/planner_test.go

Abstract system-default-registry logic from controlplane

---

pkg/controllers/provisioningv2/controllers.go
pkg/provisioningv2/rke2/planner/planner.go

Abstract KDM release data

---

README.md

Post release task for `v2.6.12` release

Update the latest README.md 2.6 version to `v2.6.12`

---

tests/validation/tests/v3_api/test_airgap_ha.py

backport of https://github.com/rancher/rancher/pull/41293

[v2.6] allow bootstrap password to be set in airgap setup

---

tests/validation/tests/v3_api/test_secrets.py
tests/validation/tests/v3_api/test_upgrade.py

backport of: https://github.com/rancher/rancher/pull/41297

[v2.6] update windows v3 tests with node affinity

---

pkg/capr/planner/certificaterotation.go

Follow up of: https://github.com/rancher/rancher/pull/41398

[CAPR] Restart correct runtime unit and only rotate healthz certificates if specified

---

pkg/settings/setting.go

Bump the rancher/shell image version

---

pkg/controllers/management/auth/setting.go
pkg/controllers/management/auth/setting_test.go

Issue: https://github.com/rancher/rancher/issues/40887

Fix atoi call with empty string in azure auth provider

---

package/Dockerfile

Adapter bump for #39087 and #41510

Bump csp adapter to 2.0.2-rc2

---

tests/v2/validation/provisioning/rke2/hostname_truncation.go
tests/v2/validation/provisioning/rke2/hostname_truncation_test.go

Add hostname truncation validation test

---

pkg/api/norman/customization/aks/handler.go

Issue: https://github.com/rancher/aks-operator/issues/98

Add multi-environment support for AKS

---

tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_test.go

Backport of https://github.com/rancher/rancher/pull/41235

2.6 Additional restricted admin tests

---

tests/framework/clients/rancher/client.go
tests/framework/extensions/kubeconfig/exec.go
tests/framework/extensions/kubeconfig/restgetter.go
tests/v2/integration/catalogv2/system_charts_version_test.go

Do not export RestConfig of test Client; configure a RestGetter instead

---

tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_psa_test.go
tests/v2/validation/rbac/rbac_test.go

Issue:
https://github.com/rancher/qa-tasks/issues/164
Problem
Adding additional tests p1 cases to be covered for restricted admin.
Also fixed a few issues seen around rbac test cases.
Automated Testing
Jenkins job will be sent as part of the review.
Related: https://github.com/rancher/rancher/pull/41235

Additional restricted admin tests

---

pkg/api/steve/catalog/catalog.go
pkg/api/steve/catalog/content.go
pkg/api/steve/catalog/operation.go
pkg/api/steve/catalog/types/rest.go

Issue: https://zube.io/rancher/rancher/epics/28
Adding comments to pkg/api/steve/catalog

release/v2.7 documenting pkg/api/steve/catalog folder

---

pkg/catalogv2/helmop/operation.go

add docs for helmop/operation.go

---

package/Dockerfile.agent

Add pinned webhook version to agent's Dockerfile

---

tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_psa_test.go
tests/v2/validation/rbac/rbac_test.go

https://github.com/rancher/qa-tasks/issues/680
This PR addresses the additional tests required to validate PSA test cases. 
We have a new custom role that needs to be validated. Created a new role updatePSA for this validation and this role should allow users to update, create and remove PSA labels in the test. 
Jenkins test run.
This PR depends slightly on the commit  https://github.com/rancher/rancher/pull/41560/commits/23250d2a0582dc06493a354ca2aa4c0a9a192a29, so the PR needs to be rebased once the changes for the linked commit were merged.

Psa additional tests

---

tests/v2/validation/provisioning/config.go
tests/v2/validation/provisioning/rke2/ace_test.go

Added automated test for RKE2 Authorized Cluster Endpoints

[v2.7] Automate test for RKE2 Authorized Cluster Endpoints 

---

pkg/httpproxy/sign.go

When upgrading the AWS SDK from version 1.44.253 to 1.44.266 this caused the proxy calls to AWS to fail with `SignatureDoesNotMatch` error. This was caused as a new partition was added (`aws-iso-e`) which currently only has 1 service listed and does not contain IAM.
The logic loops around all the partitions trying to get the service and region. As the new partition is last then the value for service is overwritten with a blank string and the signing fails as the service isn't included in the signature.
AWS add partitions occasionally and these new partitions gradually introduce services into the regions of the partition. 
This change checks if a partition returns a global service. If it does, then it stops processing partitions and breaks out so the existing logic then takes over for …

fix: proxy calls to aws fail with newer AWS SDK version

---

.github/pull_request_template.md

Updated PR template to request information about automated testing; continuation of closed stale https://github.com/rancher/rancher/pull/40549
Note that actual text (rather than comment blocks ``) is often used here to increase the probability these sections will actually be filled out - one needs to consciously delete placeholders instead of simply leaving sections empty.
Looking forward to the suggestions on what to add/change.

PR Template Updated for Automated Testing

---

tests/framework/extensions/nodes/ec2/ec2.go
tests/v2/validation/provisioning/rke2/custom_cluster.go
tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_test.go

quick fix for last commit
check for each role in list instead of -> string
* Unit
* None
_TODO_
* _TODO_

add logic to custom cluster roles check

---

pkg/controllers/capr/machineprovision/controller.go

https://github.com/rancher/rancher/issues/41915
The machineprovision controller can accidentally prematurely determine that a infrastructuremachine is ready. This is because condition reconciliation happens after object rendering, and if the provider ID is set on the machine too quickly (before condition reconciliation), the machine will prematurely have its job cleaned up and conditions will never be reconciled properly,.
This PR adds a check to ensure that the Ready condition is set to True before considering cleaning up the job object.
This was tested manually and does not block provisioning.
* None
* If "None" - Reason: It is unreasonable to attempt to add a unit test for the `run` function, as it would require generating a significant number of mock …

Fix machineprovision race with Ready status

---

tests/v2/validation/rbac/rbac_additional_test.go
tests/v2/validation/rbac/rbac_test.go

https://github.com/rancher/qa-tasks/issues/796
Separated RBAC additional tests into a separate file and make sure below tests run and green.
- rbac_test.go
- additonal_rbac_test.go
- fixed restricted admin test
- Removed comments and added new log statements 
_TODO_
* _TODO_

Separated rbac and rbac additional test cases

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Update aks-operator to v1.1.2-rc2

---

package/Dockerfile
package/Dockerfile.agent
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent
tests/v2/codecoverage/package/Dockerfile.agenttest
tests/v2/codecoverage/package/Dockerfile.ranchertest

Keep BCI version in our base images up to date.
I expect that with our regular flow of creating daily `-head` images and day to day tests from our dev teams should be enough in terms of QAing.
* Unit
* None
_TODO_
* _TODO_

[2.6] Bump BCI to 15.5

---

pkg/rancher/migrations.go

https://github.com/rancher/rancher/issues/41757 
Starting from Rancher v2.7.2, a new field [DynamicSchemaSpec](https://github.com/rancher/rancher/blob/32b5ffd41f698ce32c5cbe962c23d707b70a984e/pkg/apis/provisioning.cattle.io/v1/rke.go#L31) is added to the RKEMachinePool which can be found in the Provisioning Cluster object under spec.rkeConfig.machinePools[*].
When Rancher is upgrading, it migrates the existing Provisioning Cluster object, specifically for the RKE2 node-driver cluster, to set the above-mentioned field. The current implementation simply returns the error when it fails to update the cluster ([code](https://github.com/rancher/rancher/blob/32b5ffd41f698ce32c5cbe962c23d707b70a984e/pkg/rancher/migrations.go#L533-L536)). If another process or program updates the same cluster …

Fix the panic indexer conflict

---

pkg/catalogv2/content/content.go
pkg/catalogv2/content/translate.go
pkg/catalogv2/secret.go

Adding comments to pkg/catalogv2/content

release/v2.7 documenting pkg/catalogv2/content folder

---

tests/framework/extensions/charts/rancherwebhook.go
tests/framework/extensions/kubeapi/webhook/webhook.go
tests/framework/extensions/kubeconfig/podlogs.go
tests/framework/extensions/users/users.go
tests/v2/validation/charts/webhook.go
tests/v2/validation/charts/webhook_test.go
tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_additional_test.go
tests/v2/validation/rbac/rbac_etcd_backup_test.go
tests/v2/validation/rbac/rbac_psa_test.go
tests/v2/validation/rbac/rbac_test.go

This PR is to automate the P0 webhook checks for release testing.
In this PR 
- adding an extension to create user config that is used in multiple rbac files. By making sure this extension is in place we can use the config to create users for any tests. 
- P0 webhook checks to make sure the release testing checks performed are automated
Jenkins run

P0 webhook checks

---

pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/capr/bootstrap/controller_test.go

The RKEBootstrap data secret is deleted after the associated CAPI Machine object transitions into the Provisioned phase. This prevents upstream infrastructure providers from working properly, since the system-agent will fail to connect if the bootstrap secret does not exist.
Do not delete the bootstrap secret until the machine is deleted.
I also considered waiting until the machine phase was `Running` to delete the bootstrap secret, however this implementation keeps us in parity with upstream, and I feel strongly that if we are going to make a deviation it needs to be purposeful and documented.
Tested manually with both v2prov docker machine based infrastructure providers, and upstream digital ocean provider.
N/A
N/A. QA will not be able to test that this works with upstream …

Do not delete bootstrap secret until machine object is deleted

---

tests/v2/integration/README.md

Just added some docs about how integration tests are set up as I think it would help people who are unfamiliar with them.

Add integration test setup docs

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/image/origins.go

https://github.com/rancher/rancher/issues/42127

[v2.7.6] bump rke to v1.4.8-rc3

---

pkg/image/origins.go

To fix rancher/rancher pipeline https://drone-publish.rancher.io/rancher/rancher/10125/5/2

Adding image sources for NeuVector registry adapter and prometheus exporter

---

tests/scripts/custodian/Jenkinsfile

There was a typo / copy/paste error in my jenkinsfile

fix typo in jekninsfile for cloud custodian

---

pkg/auth/providers/migration/activedirectory_migration.go

Reverts rancher/rancher#42145
Issue: #42161

Revert "Adding start/complete info messages for AD migration"

---

pkg/auth/providers/activedirectory/activedirectory_client.go
pkg/auth/providers/migration/activedirectory_migration.go

Reverts rancher/rancher#42077
Issue: #42161

Revert "Update active directory refetchgroupprincipals to use either DN or GUID"

---

pkg/auth/providers/activedirectory/activedirectory_client.go

Reverts rancher/rancher#42022
Issue:  #42161

Revert "Update the search scope for getPrincipal and refetchPrincipal to whole subtree"

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml

#42139
Role template description was slightly confusing.
Roletemplate description was updated, and crds were re-made using `make build-crds`
N/A: description-only change.

Updating description of role templates

---

pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Just backporting a commit found during the forwardport that was breaking imported clusters, don't mind me.

Sync nodes for imported v2prov clusters

---

pkg/capr/planner/etcdrestore.go
pkg/capr/planner/idempotent.go

https://github.com/rancher/rancher/issues/42210
Backport: https://github.com/rancher/rancher/pull/42240

[release/v2.7.6] [CAPR] Utilize target hash in idempotent tracking path (#42240)

---

tests/scripts/custodian/Dockerfile
tests/scripts/custodian/Jenkinsfile

cloud custodian wasn't working properly off of other machines, this fixes that issue. 
Tested jenkinsfile via `replay` feature.

revert cloud custodian dockerfile to ubuntu, install cli for gcp + azure

---

pkg/controllers/management/feature/feature_handler.go

https://github.com/rancher/rancher/issues/42200
The new feature flag for `harvester-baremetal-container-workload` introduced a bug where enabling the flag would cause a nil pointer exception by default the feature flag `harvester` is not set, and feature operates the default value in the status.
PR introduces a check to ensure if `harvester` feature flags value is `null` or `false` when `harvester-baremetal-container-workload` is enabled the corresponding feature flag for `harvester` is also set to true.
* Unit
* None
* If "None" - GH Issue/PR: _LINK TO GH …

check for nil value of harvester feature

---

pkg/catalogv2/git/download.go
pkg/catalogv2/git/git.go
pkg/controllers/dashboard/helm/repo.go
pkg/data/dashboard/add.go
pkg/data/dashboard/repo.go

Revert "fixed bug, refactored and added proper documentation"

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/controllers/management/aks/test/buildakscccreateobject.json
pkg/controllers/management/aks/test/onclusterchange_active.yaml
pkg/controllers/management/aks/test/onclusterchange_akscc_active.json
pkg/controllers/management/aks/test/onclusterchange_akscc_create.json
pkg/controllers/management/aks/test/onclusterchange_akscc_default.json
pkg/controllers/management/aks/test/onclusterchange_akscc_update.json
pkg/controllers/management/aks/test/onclusterchange_create.yaml
pkg/controllers/management/aks/test/onclusterchange_default.yaml
pkg/controllers/management/aks/test/onclusterchange_update.yaml
pkg/controllers/management/aks/test/updateaksclusterconfig.json
pkg/controllers/management/aks/test/updateaksclusterconfig.yaml
pkg/controllers/management/aks/test/updateaksclusterconfig_updated.json

Issue: https://github.com/rancher/aks-operator/issues/131

Bump aks-operator to v1.1.3-rc1

---

tests/framework/extensions/workloads/pods/pod_status.go

Currently, the tests that are using `workloads/pods.StatusPods` (https://github.com/rancher/rancher/blob/release/v2.7/tests/framework/extensions/workloads/pods/pod_status.go#L49) are flaky because of two separate issues:
- Default true makes the check happen for once, and pods might not be in the expected conditions and cause to send empty slices to the tests where they are expected not to be empty, with this error: `Should NOT be empty, but was []`
- If the container statuses aren't initialized given time, indexing panics with this error: `Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)`
- Prevent poll exit by default to false
- Make errors and results length check, and If the results slice is greater than zero …

Update poll break condition in pod status check in the test extensions

---

tests/framework/extensions/provisioning/verify.go

https://github.com/rancher/qa-tasks/issues/877
The psact validation part specifically with creating a deployment was failing because of the wrong cluster ID
Use the correct cluster ID
Jenkins Run
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fixed psact verification, just used the wrong cluster ID

---

tests/framework/extensions/provisioning/verify.go

https://github.com/rancher/qa-tasks/issues/877
The psact validation part specifically with creating a deployment was failing because of the wrong cluster ID
Use the correct cluster ID
Jenkins Run
* Unit
* None
_TODO_
* _TODO_

[v2.7] Fixed psact verification, just used the wrong cluster ID

---

package/Dockerfile

UI Tags update that is in place of 
https://github.com/rancher/rancher/pull/42474
https://github.com/rancher/rancher/pull/42475

Update to 2.7.6 UI tags

---

pkg/agent/clean/adunmigration/rtbs.go

This workaround happens to get RBAC sync to play nice with the newly updated tokens. Otherwise it misses the memo due to the safer update order (create first, *then* delete) and would take a long time to refresh again on its own. If we miss this, user sessions in the UI tend to be missing permissions for downstream clusters until manually refreshed, leading to a poor UX.
The name of the RBAC resource in the downstream cluster is based on the user being assigned to and the permission being granted. Since we are creating a duplicated binding, the name is the same, and so when removing the duplicate, RBAC syncs the removal and removes the downstream object, despite our newly created duplicate still existing upstream.
Since we need to add an annotation to the migrated binding anyway, we delay …

Delay unmigration annotation until after creating/deleting *RTB

---

tests/v2/validation/rbac/rbac_test.go

Forward port: https://github.com/rancher/rancher/pull/42404

[2.8]Changing the additional user role

---

tests/v2/validation/charts/istio.go

Forward port to 2.8 of Istio test fixes

Corrected kiali path that changed.

---

pkg/controllers/management/feature/feature_handler.go

PR introduces a backport for fix made by https://github.com/rancher/rancher/pull/42282
This needs to be available in v2.7.6
* Unit
* None
_TODO_
* _TODO_

[release/v2.7.6] check for nil value of harvester feature

---

tests/framework/extensions/nodes/node_status.go
tests/framework/extensions/provisioning/creates.go
tests/framework/extensions/registries/registries.go
tests/v2/validation/provisioning/registries/registry_test.go

forwardport of https://github.com/rancher/rancher/pull/42554

[2.8] fixes registries automation after refactor

---

tests/framework/clients/helm/helm.go
tests/framework/extensions/kubeapi/helm/helm.go

Backport of https://github.com/rancher/rancher/pull/42503

Add helm framework to tests

---

tests/v2/validation/charts/webhook_test.go

Forwardport: https://github.com/rancher/qa-tasks/issues/891

[2.8]Changed steve client to proxydownstream

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Issue No - https://github.com/rancher/rancher/issues/42606

adding kwait to operations and configmap

---

pkg/auth/providers/common/ldap/ldap_util.go
pkg/auth/providers/ldap/ldap_actions.go
pkg/auth/providers/ldap/ldap_client.go
pkg/auth/providers/ldap/ldap_client_test.go
pkg/auth/providers/ldap/ldap_provider.go
pkg/auth/providers/ldap/ldap_provider_test.go

Issue: https://github.com/rancher/rancher/issues/42324
Forward-port of: https://github.com/rancher/rancher/pull/42321

[v2.8 forwardport] Add unit tests for LDAP auth provider

---

tests/framework/extensions/users/users.go
tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Issue No - https://github.com/rancher/rancher/issues/42606

Changing deleted secrets

---

scripts/generate-linux-digests.sh

Forwardport of https://github.com/rancher/rancher/pull/42392

[release/v2.8] Use jq to determine arch because skopeo is too old

---

pkg/api/steve/disallow/disallow.go
pkg/apis/management.cattle.io/v3/authz_types.go
pkg/crds/names.go
pkg/crds/yaml/generated/management.cattle.io_projectroletemplatebindings.yaml

Generate the projectroletemplatebinding CRD and expose it to Steve

---

tests/v2/validation/rbac/rbac.go
tests/v2/validation/rbac/rbac_additional_test.go

Fixes bugs that caused rbac_additional_test.go to fail after it was refactored
2.8 version: https://github.com/rancher/rancher/pull/42679

rbac bug fixes

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Github Issue - https://github.com/rancher/rancher/issues/42606
We do not need the removed assertion to achieve the desired result.
If `latest == app.Spec.Chart.Metadata.Version` and `latestVersion > latest`, then `latestVersion > app.Spec.Chart.Metadata.Version`, which is what we want to test anyways

removing uncessary assertion from test

---

tests/v2/validation/rbac/rbac_test.go

Forward port: https://github.com/rancher/rancher/pull/42090/

[2.8] check rbac resources for user

---

tests/v2/validation/rbac/rbac_test.go

Adding additional steps in the existing RBAC tests to validate the creation/deletion of GRB, CRTB and PRTB
Adding additional steps in the existing RBAC tests to validate:
- creation of GRB when a user is created.
- creation of CRTB when a user is added to a downstream cluster.
- creation of PRTB when a user is added to a project.
- deletion of CRTB when a user is removed from a downstream cluster.
- deletion of PRTB when a user is removed from a project.
Note: The step to validate the deletion of GRB is omitted as user deletion is performed during the cleanup process. 
N/A
Jenkins Run
**Note**: In this PR, we are not introducing new tests but are only adding additional validation steps to the existing "TestRBAC" test within the "TestRBACTestSuite" test suite. Test "TestRBAC" with the new …

GRB, CRTB, PRTB validation for GH781

---

tests/validation/tests/v3_api/resource/cluster-ha.yml

https://github.com/rancher/rancher/issues/42719#issuecomment-1712352279

add all exempt namespaces for psc in rke1 local cluster automation

---

scripts/test

Backport of https://github.com/rancher/rancher/pull/42776

changing CI to not run integration tests in parallel

---

tests/validation/tests/v3_api/test_airgap.py

backport of https://github.com/rancher/rancher/pull/42820

removing explicit check for exact registry name from assertions

---

pkg/controllers/capr/machineprovision/args.go
pkg/controllers/capr/machineprovision/args_test.go

When using CAPR, ec2 instances are automatically tagged with the cluster id of the newly generated cluster (c-m-xxxxxxx). This tag is only know after the cluster is created, and therefore if a user selects their own security group and/or subnet, they will have to manually tag them later by interacting with their cloud provider. This proposed change only tags the ec2 instances if there is not an existing kubernetes.cluster.io/<id>,owned or kubernetes.cluster.io/<id>,shared tag, as an ec2 object cannot be owned by multiple entities.
Only add tag if existing tags wouldn't conflict.
Tested manually with a 1.26 upgrade to 1.27 AWS out of tree cluster and a fresh 1.27 AWS out of tree cluster
* Unit
Summary: Added test cases to ensure the tag is added properly and …

Only add aws cluster owned tag if non-conflicting

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go

Prepare final RC - switch KDM branch to release-v2.7
This PR is based on [#41956 (files)](https://github.com/rancher/rancher/pull/41956/files)

[v2.7] Prepare final RC - switch KDM branch to release-v2.7

---

README.md

update README with latest/stable

---

go.mod
go.sum

Issue: https://github.com/rancher/rancher/issues/42961

update dynamiclistener to v0.3.6

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go

Switch KDM branch back to dev

---

package/Dockerfile

Bump csp adapter to 3.0.0-rc2

---

pkg/cluster/private_registry.go
pkg/cluster/private_registry_test.go

This reverts commit fc395565305facaaf1943acb364421574ecdf0a6.

Revert "Update dockerconfigjson to use base64 StdEncoding"

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go

Switch KDM branch  to release-v2.7
This reverts commit 785052a2af5c610c54e2a61e3fee1d28a19f1f23.

Switch KDM branch  to release-v2.7

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Bump rancher/system-agent version to v0.3.4-rc1

---

pkg/features/feature.go

Fleet feature is not installed by default.
Install it by default.
No testing done, this is a simple change
No testing done.
* Unit
* None
_TODO_
* _TODO_

Install Fleet Backpopulation Feature By Default

---

pkg/api/norman/customization/aks/listers.go

Issue: https://github.com/rancher/aks-operator/issues/98

[2.8] Improve Azure client functions and add base URL

---

tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent

Outdated versions in the code coverage Dockerfiles
Update said versions according the main rancher and agent Dockerfiles.
* Unit
* None
_TODO_
* _TODO_

Updated versions in rancher and agent Dockerfiles.

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go

switch the KDM branch back to dev-v2.7

[release/v2.7] switch the KDM branch back to dev-v2.7

---

Dockerfile.dapper
package/Dockerfile
tests/v2/codecoverage/package/Dockerfile
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix

Related: https://github.com/rancher/rancher/issues/42868

Update K3s version to v1.27.6

---

tests/framework/extensions/clusters/clusterconfig.go
tests/framework/extensions/provisioning/creates.go
tests/framework/extensions/provisioning/customcluster.go
tests/framework/extensions/provisioning/verify.go
tests/framework/extensions/provisioninginput/config.go
tests/v2/codecoverage/setuprancher/main.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/post_kdm_oob_release_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/post_kdm_oob_release_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/post_kdm_oob_release_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/rbac/rbac_additional_test.go

backport of https://github.com/rancher/rancher/pull/42836
pending unfreeze of 2.7

[2.7] update cluster config for advanced options, machine pools, and node pools

---

tests/framework/extensions/charts/charts.go
tests/v2/validation/charts/monitoring.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/charts/resources/alertmanagerstypes.go

Monitoring tests in validation were failing due to changes in configuration for alerts.
Modified the configuration of routes and receivers for alerts so they would successfully be configured and setting an alert could be verified.

Fixed Flakey Monitoring Test Backport 2.7

---

.github/workflows/manual.yml

rancherbot was disabled, so creating this for the only functionality i used it for.

add backport workflow

---

pkg/catalogv2/git/download.go
pkg/catalogv2/git/git.go
pkg/controllers/dashboard/helm/repo.go
pkg/data/dashboard/add.go
pkg/data/dashboard/repo.go
scripts/package
scripts/package-env
tests/integration/pkg/defaults/defaults.go
tests/v2/integration/catalogv2/cluster_repo_test.go

GitHub Issue https://github.com/rancher/rancher/issues/39532

Don't contact internet when bundled mode is set

---

pkg/capr/planner/etcdcreate.go

https://github.com/rancher/rancher/issues/42709
If the init node for a cluster is being removed after an etcd snapshot has been created, it is possible that the cluster will error out with `init node not found`.
This changes the etcd snapshot creation logic to only look for an init node if the snapshot needs to be created.

[release/v2.8] Only look for init node when the snapshot phase is started

---

pkg/capr/planner/etcdcreate.go

https://github.com/rancher/rancher/issues/43142
Backport of: https://github.com/rancher/rancher/pull/43141

[release/v2.7.9] Only look for init node when the snapshot phase is started

---

package/Dockerfile

Backport issue for https://github.com/rancher/rancher/issues/43115

[2.7.9] ssh dep

---

pkg/image/origins.go

Add new image origin for GMSA Webhook image

---

tests/integration/suite/test_app.py

GitHub Issue https://github.com/rancher/rancher/issues/42711
Apps v3 is deprecated and is going to be removed in a future release. It makes sense to remove this flaky test and if there is a customer issue, we can fix it then

Remove flaky test test_app_namespace_annotation

---

tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/validation/tests/v3_api/common.py

set url is not updated for v2.8
add v2.8 in the if statement.
* Unit
* None
_TODO_
* _TODO_

updated set url password

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/43175

update rke to v1.5.0-rc9

---

tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go

dynamic k3s node driver test was commented out.
Put it back in.
* Unit
* None
_TODO_
* _TODO_

Uncommented a commented test case

---

tests/framework/extensions/provisioning/creates.go

Forgot to change this to `err` when doing work for the adding/deleting custom cluster nodes PR. Small PR to fix that issue.
Fixed the `nil` to `err`.

Small fix to provisioning/creates.go

---

tests/v2/validation/certrotation/README.md
tests/v2/validation/deleting/README.md
tests/v2/validation/nodescaling/README.md
tests/v2/validation/prime/README.md
tests/v2/validation/provisioning/README.md
tests/v2/validation/provisioning/hosted/README.md
tests/v2/validation/provisioning/hostnametruncation/README.md
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/snapshot/README.md
tests/v2/validation/upgrade/README.md

The provisioning READMEs in the Go framework are not as clear as they need to be. Regardless if you're new to the framework or more seasoned, there are a couple of problems. These include:
- Automated tests missing completely in a README
- Unclear steps on how to run an automated test
The overall provisioning READMEs should be refactored so that it is much more clear as to what tests exist and how to actually run the tests.

[v2.7] Refactor provisioning READMEs

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Releases the CSP adapter for the upcoming 2.8 release.

Release csp adapter version 3.0.0

---

tests/framework/extensions/provisioning/ssh.go
tests/framework/extensions/provisioning/verify.go

List call uses annotation instead of the steve type.
Update List call to steve type instead the annotation

[2.8] Fix Machine Steve Type in Provisioning Verify Test Extensions

---

package/Dockerfile

Bump UI to v2.8.0-rc3

---

tests/validation/tests/v3_api/resource/terraform/k3s/master/cis_masterconfig.yaml
tests/validation/tests/v3_api/resource/terraform/k3s/master/install_k3s_master.sh
tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf
tests/validation/tests/v3_api/resource/terraform/k3s/master/join_k3s_master.sh
tests/validation/tests/v3_api/resource/terraform/k3s/master/v125_policy.yaml
tests/validation/tests/v3_api/resource/terraform/k3s/master/variables.tf
tests/validation/tests/v3_api/test_import_k3s_cluster.py

This PR removes psp and add optional files option required in k3s for rancher install to allow namespaces

remove_psp_add_optional_files_to_k3s

---

tests/validation/tests/v3_api/resource/terraform/k3s/master/cis_125_masterconfig.yaml

This PR add missing file to psp removal change

add missing file to k3s

---

tests/validation/tests/v3_api/resource/terraform/k3s/master/install_k3s_master.sh
tests/validation/tests/v3_api/resource/terraform/k3s/master/instances_server.tf
tests/validation/tests/v3_api/resource/terraform/k3s/master/join_k3s_master.sh

update psa file location

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Bump system agent to v0.3.4

---

README.md

This PR will remove the latest release section from README.md

Remove latest release from README.md v2.5

---

README.md

This PR will remove the latest release section from README.md

Remove latest releases from readme v2.6

---

README.md

This PR will remove the latest release section from README.md

Remove latest releases from README.md v2.7

---

tests/framework/extensions/pipeline/setup.go
tests/v2/validation/Jenkinsfile.recurring
tests/v2/validation/pipeline/hapostinstall/main.go
tests/v2/validation/pipeline/ranchercleanup/main.go

A fatal can occurring during when the infrastructure is being build, that can cause issues with clean up. Also not passing the correct token to non provisioning tests.
Change fatal to log, and make sure the updated config file works.
Recurring runs.
* Unit
* None
_TODO_
* _TODO_

Fixed unchecked errors, that could cause problems with cleanup. Token fix for the main config file.

---

tests/framework/extensions/pipeline/setup.go
tests/v2/validation/Jenkinsfile.recurring
tests/v2/validation/pipeline/hapostinstall/main.go
tests/v2/validation/pipeline/ranchercleanup/main.go

A fatal can occurring during when the infrastructure is being build, that can cause issues with clean up. Also not passing the correct to token to non provisioning tests.
Change fatal to log, and make sure the updated config file works.
Recurring runs.
* Unit
* None
_TODO_
* _TODO_

[v2.7] Fixed unchecked errors, that could cause problems with cleanup. Token fix for the main config file

---

tests/framework/extensions/provisioning/verify.go
tests/framework/extensions/registries/registries.go
tests/framework/extensions/workloads/pods/pod_status.go
tests/framework/extensions/workloads/pods/verify.go
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/prime/prime_test.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/upgrade/kubernetes_test.go

backport of https://github.com/rancher/rancher/pull/42927

[v2.7] validate all pods during provisioning

---

tests/framework/extensions/pipeline/releaseupgrade.go
tests/framework/extensions/provisioninginput/config.go
tests/v2/validation/Jenkinsfile_support_matrix_os
tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

- Because of multiple unmarshal and marshal while updating the generating configuration, glue codes are generating zero value fields, causing some nil checks in the tests to pass. 
- Support matrix OS can't point to different branches and repos.
- Release upgrade HA's last step is dependent on generated patched configs rather than initial configurations, this was causing not to provision the new clusters on the upgraded version if the initial cluster provision failed.
- Added omit empty tags to provisioning input fields
- Updated support OS matrix and release HA upgrade Jenkinsfiles' repo logics to unify with e2e Jenkinsfile.
- Updated release upgrade HA's last loop to use the initially generated configuration files. 
- Updated release upgrade HA configuration matrix fields to have JSON …

[2.8] Update Provisioning Input & Release Upgrade fields'  tags and Support OS & Upgrade HA Jenkinsfiles

---

tests/framework/extensions/pipeline/releaseupgrade.go
tests/framework/extensions/provisioninginput/config.go
tests/v2/validation/Jenkinsfile_support_matrix_os
tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

- Because of multiple unmarshal and marshal while updating the generating configuration, glue codes are generating zero value fields, causing some nil checks in the tests to pass. 
- Support matrix OS can't point to different branches and repos.
- Release upgrade HA's last step is dependent on generated patched configs rather than initial configurations, this was causing not to provision the new clusters on the upgraded version if the initial cluster provision failed.
- Added omit empty tags to provisioning input fields
- Updated support OS matrix and release HA upgrade Jenkinsfiles' repo logics to unify with e2e Jenkinsfile.
- Updated release upgrade HA's last loop to use the initially generated configuration files. 
- Updated release upgrade HA configuration matrix fields to have JSON …

[2.7] Update Provisioning Input & Release Upgrade fields'  tags and Support OS & Upgrade HA Jenkinsfiles

---

tests/v2/validation/publicapi/crdgeneration/crd_generation.go
tests/v2/validation/publicapi/crdgeneration/crd_generation_test.go

Test cases automated in this suite are applicable to local cluster. Therefore updated the clusterName to be taken as local.

Test suite uses local cluster for all validations. 

---

tests/framework/extensions/charts/charts.go
tests/framework/extensions/clusters/clusterconfig.go
tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/ingresses/ingresses.go
tests/framework/extensions/machinepools/amazonec2_machine_config.go
tests/framework/extensions/provisioninginput/config.go
tests/framework/extensions/services/verify.go
tests/v2/validation/charts/istio.go
tests/v2/validation/charts/istio_test.go
tests/v2/validation/charts/monitoring.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/resources/out-of-tree/aws.yml
tests/v2/validation/upgrade/workload.go

backport of https://github.com/rancher/rancher/pull/42974

[backport 2.7] adding out-of-tree automation support for aws

---

pkg/controllers/management/drivers/nodedriver/machine_driver.go

This reverts commit 812fb8c388c429c557ce8d329f04f4199e3132cc, reversing changes made to 5cffa891781908dcbe2c6bb8be2084b362e2ff00 as part of https://github.com/rancher/rancher/issues/42378.
Node drivers must be in the form `docker-machine-driver-<NAME>`. There were some updates to change node drivers from using the autogenerated `nd-xxxxx` name in the backend, but they were not propagated everywhere, and the ember UI was also not updated. This caused node drivers that were not builtin nor predefined (nutanix is a non-builtin but predefined node driver, whereas for example proxmoxve is not) to perpetually be stuck in a downloading state, as the resulting driver binary (for example, `docker-machine-driver-proxmoxve`) could not be determined from the node driver name `nd-xxxxx`.
Revert …

Revert "Merge pull request #42785"

---

tests/v2/validation/publicapi/crdgeneration/crd_generation_test.go

Backport of https://github.com/rancher/rancher/pull/43507

[2.7] Error fix for CRD gen

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump UI & Dashboard versions to v2.8.0

Bump UI & Dashboard versions to v2.8.0

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

bump rke to v1.5.0

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/check-chart-kdm-source-values

Prepare final RC - switch KDM branch to release-v2.8

switch KDM branch to release-v2.8

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go

Switch KDM from release-v2.8 to dev-v2.8

Switch KDM from release-v2.8 to dev-v2.8

---

tests/v2/validation/publicapi/crdgeneration/crd_generation_test.go

There are a few errors noticed for CRD gen fix that went in recently. This PR aims to fix those errors.

Error fix for CRD gen

---

tests/framework/clients/rancher/catalog/clusterrepo.go
tests/framework/extensions/charts/awsoutoftree.go
tests/framework/extensions/charts/charts.go
tests/framework/extensions/charts/payloads.go
tests/framework/extensions/charts/ranchergatekeeper.go
tests/framework/extensions/charts/rancheristio.go
tests/framework/extensions/charts/rancherlogging.go
tests/framework/extensions/charts/ranchermonitoring.go
tests/framework/extensions/charts/verify.go
tests/framework/extensions/clusters/clusterconfig.go
tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/defaults/defaults.go
tests/framework/extensions/provisioning/verify.go
tests/framework/extensions/provisioninginput/config.go
tests/framework/extensions/workloads/pods/pod_status.go
tests/v2/integration/catalogv2/system_charts_version_test.go
tests/v2/validation/charts/gatekeeper_test.go
tests/v2/validation/charts/istio_test.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/charts/webhook_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/upgrade/workload_test.go
tests/validation/tests/rke/common.py

adding rke1 out of tree support
backport of https://github.com/rancher/rancher/pull/43593

[v2.7] rke1 out-of-tree automation support

---

tests/framework/extensions/projects/projects.go
tests/framework/extensions/projects/template.go
tests/framework/extensions/rbac/config.go
tests/framework/extensions/rbac/verify.go
tests/v2/validation/rbac/README.md
tests/v2/validation/rbac/rbac_test.go

Back port of https://github.com/rancher/rancher/pull/43298

[2.7] Refactoring RBAC

---

tests/validation/tests/rke/common.py

backport of https://github.com/rancher/rancher/pull/43687

removing sh exec due to distroless upstream

---

go.mod
go.sum
tests/framework/extensions/pipeline/setup.go
tests/v2/validation/Jenkinsfile
tests/v2/validation/Jenkinsfile.e2e
tests/v2/validation/Jenkinsfile.recurring
tests/v2/validation/Jenkinsfile_pre_post_upgrade
tests/v2/validation/configure.sh
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/pipeline/qase/README.md
tests/v2/validation/pipeline/qase/defaults.go
tests/v2/validation/pipeline/qase/reporter/main.go
tests/v2/validation/pipeline/qase/testcase/testcase.go
tests/v2/validation/pipeline/qase/testrun/main.go
tests/v2/validation/pipeline/scripts/build_qase_auto_testrun.sh
tests/v2/validation/pipeline/scripts/build_qase_reporter.sh

back port: rancher/rancher/pull/43719
Reporting our automation tests including recurring runs in our Qase project for the public to see.
Implemented go bins to start recurring test runs in an automated was, as well a parser to be able to post test results to our Qase projects. If tests don't exist then the parser will write new tests, and update them accordingly.
* Unit
* None
_TODO_
* _TODO_

[v2.8] Qase automation reporter

---

go.mod
go.sum
tests/framework/extensions/pipeline/setup.go
tests/v2/validation/Jenkinsfile
tests/v2/validation/Jenkinsfile.e2e
tests/v2/validation/Jenkinsfile.recurring
tests/v2/validation/Jenkinsfile_pre_post_upgrade
tests/v2/validation/configure.sh
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/pipeline/qase/README.md
tests/v2/validation/pipeline/qase/defaults.go
tests/v2/validation/pipeline/qase/reporter/main.go
tests/v2/validation/pipeline/qase/testcase/testcase.go
tests/v2/validation/pipeline/qase/testrun/main.go
tests/v2/validation/pipeline/scripts/build_qase_auto_testrun.sh
tests/v2/validation/pipeline/scripts/build_qase_reporter.sh

Reporting our automation tests including recurring runs in our Qase project for the public to see.
Implemented go bins to start recurring test runs in an automated was, as well a parser to be able to post test results to our Qase projects. If tests don't exist then the parser will write new tests, and update them accordingly.
* Unit
* None
_TODO_
* _TODO_

[v2.7] Qase automation reporter

---

pkg/image/charts.go

Right now we add the images of the latest version of every chart, regardless if it passes the constraint check, and only add the remaining ones if it's added to [this](https://github.com/rancher/rancher/blob/dae31f3bbd66763c5a0ecbde397278dfece0d75e/pkg/image/charts.go#L28) map.
We check if the latest version of a chart passes the rancher version constraint before adding it. This is [already done](https://github.com/rancher/rancher/blob/dae31f3bbd66763c5a0ecbde397278dfece0d75e/pkg/image/charts.go#L147) for system charts.

Only adding the latest version of a chart to images.txt if it passes the constraint check

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go
tests/framework/clients/rancher/generated/management/v3/zz_generated_aci_network_provider.go

Bumping rke for ACI changes https://github.com/rancher/rancher/issues/43893

[v2.8] update rke to v1.5.2-rc1

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go
tests/framework/clients/rancher/generated/management/v3/zz_generated_aci_network_provider.go

Bumping RKE for ACI changes https://github.com/rancher/rancher/issues/43893

[v2.8.1] update rke to v1.5.2-rc1

---

pkg/controllers/management/rkeworkerupgrader/plan.go

https://github.com/rancher/rancher/issues/41547
The kubelet container does not restart on the **worker-only** node of the RKE1 node-driver cluster after performing an etcd snapshot restore, which causes chaos and unexpected behaviors because of the stale cache inside the container. 
The kubelet container needs to be restarted. 
A new environment variable, `CATTLE_ETCD_RESTORE_GENERATION=<some-value>`, is added or updated in the node plan for the kubelet process (container) when a restore is performed.  This allows the node agent to detect a change in the node plan and redeploy the kubelet container with the new plan during the upgrading process after the etcd restore is finished. 
The kubelet containers on the etcd and control plane node are restated by RKE during the restore process. …

fix kubelet on etcd snapshot restore

---

pkg/controllers/dashboard/chart/chart_test.go
pkg/controllers/dashboardapi/feature/feature_handler_test.go
pkg/features/feature_test.go
pkg/features/feature_testdata.go

```shell
go version
go version go1.21.4 darwin/amd64
go vet ./...
pkg/controllers/dashboard/chart/chart_test.go:179:38: loop variable tt captured by func literal
vet: pkg/features/feature_test.go:36:15: undefined: IsDefFalse
```
* Unit
* None
_TODO_
* _TODO_

Fix issues identified by go vet 1.21

---

pkg/controllers/management/rkeworkerupgrader/plan.go

https://github.com/rancher/rancher/issues/43949
backport of the PR https://github.com/rancher/rancher/pull/43288

[2.7] fix kubelet on etcd snapshot restore

---

pkg/controllers/management/rkeworkerupgrader/plan.go

https://github.com/rancher/rancher/issues/43948
forwardport of the PR https://github.com/rancher/rancher/pull/43288

[2.9] fix kubelet on etcd snapshot restore

---

tests/v2/validation/Dockerfile.validation
tests/validation/Dockerfile.v3api
tests/validation/tests/v3_api/test_airgap_ha.py

port of: https://github.com/rancher/rancher/pull/43959

[2.9] fixing relative path for airgap automation

---

tests/v2/validation/Dockerfile.validation
tests/validation/Dockerfile.v3api
tests/validation/tests/v3_api/test_airgap_ha.py

port of https://github.com/rancher/rancher/pull/43959

[2.7] fixing relative path for airgap automation

---

pkg/controllers/dashboardapi/settings/settings.go
pkg/controllers/dashboardapi/settings/settings_test.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/43992
This is a backport of https://github.com/rancher/rancher/pull/43656
* Unit
* None
_TODO_
* _TODO_

[v2.8] Label unknown/deprecated settings on startup

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/providers/oidc/oidc_provider.go

https://github.com/rancher/rancher/issues/44016
Backport of https://github.com/rancher/rancher/pull/43667
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fix OIDCConfig.Scopes struct field tag

---

tests/validation/lib/aws.py

[2.7] update python airgap to disable ipv6

---

pkg/controllers/management/eks/eks_cluster_handler.go

Issue: https://github.com/rancher/eks-operator/issues/301 (cherry picked from commit f1acaafa66cf2b6dfde0022da650a0ddf704f525)
* Unit
* None
_TODO_
* _TODO_

[v2.9] Allow import EKS cluster with self-managed nodes

---

pkg/controllers/management/eks/eks_cluster_handler.go

Allow import EKS cluster with self-managed nodes
* Unit
* None
_TODO_
* _TODO_

[v2.8] Allow import EKS cluster with self-managed nodes

---

tests/validation/lib/aws.py

[2.8] update python airgap to disable ipv6

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Un-rc-ing rke for 2.8.1 release.

[v2.8.1] update rke to v1.5.2

---

tests/validation/tests/v3_api/test_airgap.py

docker airgap job wasn't fixed after dependency bump

[2.9] fix python docker airgap from dependency bump break

---

tests/validation/tests/v3_api/test_airgap.py

backport of https://github.com/rancher/rancher/pull/44074

[v2.7] fix python docker airgap from dependency bump break

---

tests/validation/tests/v3_api/test_custom_host_reg.py

Backport of https://github.com/rancher/rancher/pull/44078

[2.8 Backport]Adding repository and image as a param

---

tests/validation/tests/v3_api/test_create_ha.py

Backport https://github.com/rancher/rancher/pull/44079

[2.8 Backport] 28updatehelmsettings

---

tests/validation/tests/v3_api/test_create_ha.py

Backport https://github.com/rancher/rancher/pull/44079

[2.7 Backport]27updatehelmsettings

---

tests/framework/extensions/pipeline/releaseupgrade.go
tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

Extensions PR: https://github.com/rancher/shepherd/pull/32

Adding pipeline options for helm extra settings

---

tests/framework/extensions/pipeline/releaseupgrade.go
tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

Backport of https://github.com/rancher/rancher/pull/44093

[2.7 Back port]Adding pipeline options for helm extra settings

---

tests/framework/extensions/pipeline/releaseupgrade.go
tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

Backport of https://github.com/rancher/rancher/pull/44093

[2.8 Backport]Adding pipeline options for helm extra settings

---

tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

Back port https://github.com/rancher/rancher/pull/44156

[2.8] Missing comma in the variables list 

---

tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

Back port https://github.com/rancher/rancher/pull/44156

[2.7]Missing comma in the variables list

---

tests/v2/validation/pipeline/Jenkinsfile_release_upgrade

Related to: https://github.com/rancher/rancher/pull/44093/files

Missing comma in the variables list

---

README.md

This PR is a copy of https://github.com/rancher/rancher/pull/44187 where the Github Action was not triggered.

[release/v2.9]  update README to add 2.8.1 as the latest 

---

README.md

update README with v2.8.1 as the stable

update README with v2.8.1 as the stable

---

pkg/controllers/dashboardapi/settings/settings.go
pkg/controllers/dashboardapi/settings/settings_test.go

https://github.com/rancher/rancher/issues/44009
Since https://github.com/rancher/rancher/pull/43656 we mark unknown setting with a label.
The ultimate goal is to delete such settings.
Delete unknown settings on Rancher startup.
Create a new setting e.g. via kubectl
Start Rancher
Make sure that the setting is no longer exists
* Unit
_TODO_
* _TODO_

[v2.9] Delete unknown settings on startup

---

pkg/settings/setting.go

This ensures that the QA team is assessing the UI in the most recent 2.7 version until the creation of UI branches for version 2.7.11.

Update ui settings

---

scripts/chart/promote-to-stable.sh

https://github.com/rancher/rancher/issues/44267
Please check the[ original PR](https://github.com/rancher/rancher/pull/44269) for more information.

[2.7] [Backport] fix the issue that the promote-to-stable script can not find the target build number

---

scripts/chart/promote-to-stable.sh

https://github.com/rancher/rancher/issues/44267
Please check the[ original PR](https://github.com/rancher/rancher/pull/44269) for more information.

[2.8] [Backport] fix the issue that the promote-to-stable script can not find the target build number

---

.drone.yml

2.7.11 release artifacts should not be published to dockerhub 
temporarily remove drone steps related to publishing docker containers  

Update drone.yaml push steps

---

scripts/chart/promote-to-stable.sh

https://github.com/rancher/rancher/issues/44267
Please check the[ original PR](https://github.com/rancher/rancher/pull/44269) for more information.

[2.7.11] [Backport] fix the issue that the promote-to-stable script can not find the target build number

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

https://github.com/rancher/rancher/issues/44355
Releated Harvester issues:
* https://github.com/harvester/harvester/issues/4588
* https://github.com/harvester/harvester/issues/2764
* https://github.com/harvester/harvester/issues/4777
This PR bump Harvester Node Driver to version v0.6.7

[v2.7.11] feat: bump harvester node driver to v0.6.7

---

tests/v2/validation/Jenkinsfile.e2e

Qase reporter for the .e2e Jenkinsfile was not running properly
Fixed the shell command
Ran it using the air gap Jenkins pipeline.
* Unit
* None
_TODO_
* _TODO_

[v2.8] Updated Jenkinsfile to appropriately run the qase reporter

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md

port of https://github.com/rancher/rancher/pull/43775

[2.9] updating readme and Shepherd for qa multi-config

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md

port of: https://github.com/rancher/rancher/pull/43775

[v2.7] updating readme and Shepherd for qa multi-config

---

tests/v2/validation/Jenkinsfile.e2e

Qase reporter for the .e2e Jenkinsfile was not running properly
Fixed the shell command
Ran it using the air gap Jenkins pipeline.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Updated Jenkinsfile to appropriately run the qase reporter.

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

updated rke version includes fix for issue: https://github.com/rancher/rancher/issues/44218

[v2.7.11] bumped rke to v1.4.15-rc2

---

tests/validation/tests/v3_api/test_airgap_ha.py

https://github.com/rancher/rancher/pull/44380

[2.8] Cwarren/v2.8/validate airgap helm

---

tests/integration/suite/test_users.py

https://github.com/rancher/rancher/issues/44393
Please check the original [PR](https://github.com/rancher/rancher/pull/44377) for more info.

[Backport 2.7] Fix test_globalrolebinding_finalizer_cleanup flaky test 

---

pkg/controllers/managementuser/pspdelete/pspdelete.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/clusterrole.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/deferred.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/namespace.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/podsecuritypolicy.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/serviceaccount.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version_test.go

Special port of https://github.com/rancher/rancher/pull/43201 - 2.7 issue https://github.com/rancher/rancher/pull/43201

[2.7.11] Fix cluster version check for PSP

---

tests/validation/tests/v3_api/test_custom_host_reg.py

Back port of https://github.com/rancher/rancher/pull/44081/commits

[2.7 Backport]Adding repository and image as a param

---

tests/v2/validation/rbac/rbac_test.go

Forward port of https://github.com/rancher/rancher/pull/44004

Skipping dynamic tests when no input is provided

---

build.yaml
pkg/buildconfig/constants.go

The webhook doesn't allow user to grant inherited permissions to other users in some cases
Allow user to grant inherited permissions to other users
Webhook CI + some manual testing was done.

Bump webhook to v0.5.0-rc4

---

tests/validation/lib/rke_client.py

N/A -- found during post release testing for rke1
yaml.load has been deprecated as it was used here. yaml.safe_load is preferable and is used in other places of the Python tests already.
Update function to use safe_load instead of load
None -- I think this is enough for it to work and want to finish post release checks quickly.
* ~Unit~
* ~Integration (Go Framework)~
* ~Integration (v2prov Framework)~
* ~Validation (Go Framework)~
* Other - Explain: _Old python tests that are still used for rke1 checks_
The test should now work.
This already fails, so it could just fail again and it would be the same difference.

Use safe_load instead of load for yaml contents

---

tests/validation/lib/rke_client.py

Backport: https://github.com/rancher/rancher/pull/44451

[Backport] [release/v2.8] Use safe_load instead of load for yaml contents

---

tests/v2/validation/rbac/rbac_test.go

Backport of https://github.com/rancher/rancher/pull/44004

Skipping dynmaic tests when no input is provided

---

tests/validation/lib/rke_client.py

Backport: https://github.com/rancher/rancher/pull/44451

[Backport] [release/v2.7] Use safe_load instead of load for yaml contents

---

.drone.yml

Add chart-publish step

---

.drone.yml

fix chart-publish source pattern

---

.drone.yml

remove bucket prefix on chart-publish target

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Update UI settings v2.7.11-rc1

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

https://github.com/rancher/rancher/issues/43318
kube-api-auth was updated to fix CVEs.
Use a newer kube-api-auth version with fixed CVEs.
* None
Create a downstream cluster with ACE enabled and check if you can authenticate using ACE.
N/A

[2.9] Update kube-api-auth to v0.2.1

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

https://github.com/rancher/rancher/issues/43318
kube-api-auth was updated to fix CVEs.
Use a newer kube-api-auth version with fixed CVEs.
* None
Create a downstream cluster with ACE enabled and check if you can authenticate using ACE.
N/A

[2.8] Update kube-api-auth to v0.2.1

---

.drone.yml

update chart publish to push to new repo

---

tests/v2/validation/provisioning/rke2/agent_customization_test.go

port of https://github.com/rancher/rancher/pull/44080

[v2.7] adding static tests for agent customization

---

tests/v2/validation/provisioning/rke2/agent_customization_test.go

port of https://github.com/rancher/rancher/pull/44080

[2.8] adding static tests for agent customization

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Bumping RKE to 1.4.15 to remove the rc.

[2.7.11] Bump RKE to 1.4.15

---

tests/v2/validation/pipeline/ranchercleanup/main.go

Updating the rancher version to have the new shepherd, but there was an issue with cleaning the rancher instance if there has been error.
If there is an issue with cleaning up clusters, delete the corral regardless so there aren't any leftover resources.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Fix post clean up steps

---

tests/v2/validation/pipeline/ranchercleanup/main.go

Updating the rancher version to have the new shepherd, but there was an issue with cleaning the rancher instance if there has been error.
If there is an issue with cleaning up clusters, delete the corral regardless so there aren't any leftover resources.
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fix post clean up steps

---

tests/v2/validation/pipeline/ranchercleanup/main.go

Updating the rancher version to have the new shepherd, but there was an issue with cleaning the rancher instance if there has been error.
If there is an issue with cleaning up clusters, delete the corral regardless so there aren't any leftover resources.
* Unit
* None
_TODO_
* _TODO_

[v2.7] Fix post clean up steps

---

.drone.yml

Revert "update chart publish to push to new repo"

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
pkg/controllers/management/clusterupstreamrefresher/gke_upstream_spec.go
pkg/controllers/management/gke/gke_cluster_handler.go

Issue: https://github.com/rancher/gke-operator/issues/92
* Unit
* None
_TODO_
* _TODO_

[v2.9] Update GKE with new BuildUpstreamClusterState functions

---

go.mod
go.sum
tests/v2/validation/projects/projects.go
tests/v2/validation/publicapi/crdgeneration/crd_generation.go

Had to make changes to kubectl extension for other issues. Updating where kubectl apply and explain were previously used to the new kubectl command.
Updated kubectl from apply and explain to a single kubectl command function that can handle any kubectl situation. Also fixed a bug in the previous apply implementation.
- https://github.com/rancher/rancher/pull/44608
- https://github.com/rancher/rancher/pull/44609

[Draft][v2.9] Implement new kubectl command function

---

go.mod
go.sum
tests/v2/validation/projects/projects.go
tests/v2/validation/publicapi/crdgeneration/crd_generation.go

Reverts rancher/rancher#44607 still needs updates from rancher/shepherd and one more approval

Revert "[Draft][v2.9] Implement new kubectl command function"

---

.github/workflows/verify-generated-code-changes.yml
Dockerfile-windows.dapper
Dockerfile.dapper
go.mod
pkg/apis/go.mod
pkg/capr/planner/store.go
pkg/catalog/manager/catalog_common.go
pkg/client/go.mod
pkg/controllers/capr/planner/controller.go
pkg/controllers/managementuser/clusterauthtoken/setting.go
pkg/controllers/managementuser/resourcequota/resource_quota_sync.go
pkg/controllers/managementuserlegacy/helm/common.go
tests/README.md
tests/v2/codecoverage/Dockerfile.buildcodecoverage
tests/v2/codecoverage/Dockerfile.codecoverage
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation

Fleet 0.10.0 api requires Go toolchain 1.22.
Update Go to 1.22.
N/A

[v2.9] Bump to Go 1.22

---

tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.ha

Back port of https://github.com/rancher/rancher/pull/44516

[2.7] Adding configs to take in prime rep

---

tests/v2/validation/charts/README.md
tests/v2/validation/charts/webhook.go
tests/v2/validation/charts/webhook_test.go

Back port of https://github.com/rancher/rancher/pull/44645

[2.7] Updating local cluster to be run as part of webhook checks

---

tests/v2/validation/charts/README.md
tests/v2/validation/charts/webhook.go
tests/v2/validation/charts/webhook_test.go

Back port of https://github.com/rancher/rancher/pull/44645/commits

[2.8] Updating local cluster to be run as part of webhook checks

---

tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.ha

Back port of https://github.com/rancher/rancher/pull/44516

[2.8] Adding configs to take in prime rep

---

go.mod
go.sum

Backport of https://github.com/rancher/rancher/pull/44654

[Backport 2.8] Bump Steve to include https://github.com/rancher/steve/pull/165

---

go.mod
go.sum
tests/v2/validation/charts/webhook_test.go
tests/v2/validation/publicapi/crdgeneration/crd_generation.go

Had to make changes to kubectl extension for other issues. Updating where kubectl apply and explain were previously used to the new kubectl command.
Updated kubectl from apply and explain to a single kubectl command function that can handle any kubectl situation. Also fixed a bug in the previous apply implementation.

[v2.7] Implement new kubectl command function #44637

---

go.mod
go.sum
tests/v2/validation/charts/webhook_test.go
tests/v2/validation/projects/projects.go
tests/v2/validation/publicapi/crdgeneration/crd_generation.go

Had to make changes to kubectl extension for other issues. Updating where kubectl apply and explain were previously used to the new kubectl command.
Updated kubectl from apply and explain to a single kubectl command function that can handle any kubectl situation. Also fixed a bug in the previous apply implementation.

[v2.9] Implement new kubectl command function

---

go.mod
go.sum
tests/v2/validation/charts/webhook_test.go
tests/v2/validation/publicapi/crdgeneration/crd_generation.go

Had to make changes to kubectl extension for other issues. Updating where kubectl apply and explain were previously used to the new kubectl command.
Updated kubectl from apply and explain to a single kubectl command function that can handle any kubectl situation. Also fixed a bug in the previous apply implementation.

[v2.8] Implement new kubectl command function

---

go.mod
go.sum
tests/v2/validation/rbac/rbac_test.go

Backport https://github.com/rancher/rancher/pull/44667

[2.8] Updating rbac tests for qase parser

---

go.mod
go.sum
tests/v2/validation/rbac/rbac_test.go

Backport https://github.com/rancher/rancher/pull/44667

[2.7] Updating rbac tests for qase parser

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

https://github.com/rancher/rancher/issues/44313
Releated Harvester issues:
* https://github.com/harvester/harvester/issues/4588
* https://github.com/harvester/harvester/issues/2764
* https://github.com/harvester/harvester/issues/4777
This PR bump Harvester Node Driver to version v0.6.7

[v2.8] feat: bump harvester node driver to v0.6.7

---

.drone.yml
pkg/image/external/external_test.go
scripts/generate-linux-digests.sh
tests/scripts/prime/compare-registry.sh
tests/scripts/privateregistry/populate-ecr.sh

* Remove artifacts upload
* Fix helm chart path
* The drone github-release plugin requires files to work, since we are not uploading assets, it isn't possible to use this plugin anymore. To address this, I'm removing the step and changing the github release creation process.
* Since artifacts still need to be stored, I'm adding a step to upload artifacts to a s3 bucket
* Stripping the `bin/chart` prefix from the helm chart repo because it is just a build prefix, not meant to be used.

Update the GitHub Release process

---

.drone.yml

update images digests linux to upload to bucket

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

https://github.com/rancher/rancher/issues/43594
Releated Harvester issues:
* https://github.com/harvester/harvester/issues/4588
* https://github.com/harvester/harvester/issues/2764
* https://github.com/harvester/harvester/issues/4777
This PR bump Harvester Node Driver to version v0.6.7

[v2.9] feat: bump harvester node driver to v0.6.7

---

package/Dockerfile

Bump UI to v2.8.3-rc1

---

package/Dockerfile

Bump UI to v2.7.12-rc1

---

go.mod
go.sum
tests/v2/validation/nodescaling/README.md
tests/v2/validation/nodescaling/auto_replace_test.go
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/provisioning/README.md
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/agent_customization_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go

Taking up work from https://github.com/rancher/rancher/pull/43353

[v2.8] adding machineConfig and test for AutoReplace RKE2/K3s

---

Dockerfile.dapper
package/Dockerfile
tests/v2/codecoverage/package/Dockerfile
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix

Fixes https://github.com/rancher/rancher/issues/44444.

[v2.7] chore: Bump k3s to v1.27.10+k3s2

---

tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.ha

Back port of https://github.com/rancher/rancher/pull/44874

[2.8] Adding helm repo to upgrade for prime checks

---

tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.ha

Back port of https://github.com/rancher/rancher/pull/44874

[2.7] Adding helm repo to upgrade for prime checks

---

package/Dockerfile
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/44891
Because the tag is left as `v0.15.0-rancher109` in the setting.go file, the generated images.txt file  contains 
that tag instead of the expected `v0.15.0-rancher110` 
fix the wrong tag in the settings.go file, and also add a comment in the main Dockerfile. 
* Unit
* None
_TODO_
* _TODO_

Fix rancher machine version 

---

tests/v2/validation/pipeline/qase/reporter/main.go

Where there is a timeout failure in a go test the Qase reporter fails
Updated parsing to account for parsing timeout failures
Ran on Qase
* Unit
* None
_TODO_
* _TODO_

[v2.9] Fix Qase reporting timeout failure

---

tests/v2/validation/pipeline/qase/reporter/main.go

Where there is a timeout failure in a go test the Qase reporter fails
Updated parsing to account for parsing timeout failures
Ran on Qase
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fix Qase reporting timeout failure

---

tests/v2/validation/pipeline/qase/reporter/main.go

Where there is a timeout failure in a go test the Qase reporter fails
Updated parsing to account for parsing timeout failures
Ran on Qase
* Unit
* None
_TODO_
* _TODO_

[v2.7] Fix Qase reporting timeout failure

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

 bump rke to v1.5.7-rc5

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/README.md

Docker version was hardcoded rather than it being allowed to be changed.
Update shepherd extensions to be able to parameterize docker version link for rke1 node provider provisioning
Jenkins runs
* Unit
* None
_TODO_
* _TODO_

[v2.9] Updated shepherd version, and updated the rke1 node provider README for new node template changes.

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/README.md

Docker version was hardcoded rather than it being allowed to be changed.
Update shepherd extensions to be able to parameterize docker version link for rke1 node provider provisioning
Jenkins runs
* Unit
* None
_TODO_
* _TODO_

[v2.8] Updated shepherd version, and updated the rke1 node provider README for new node template changes.

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/README.md

Docker version was hardcoded rather than it being allowed to be changed.
Update shepherd extensions to be able to parameterize docker version link for rke1 node provider provisioning
Jenkins runs
* Unit
* None
_TODO_
* _TODO_

[v2.7] Updated shepherd version, and updated the rke1 node provider README for new node template changes.

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

System-agent needs to be bumped for v2.8

Bump system-agent to v0.3.6

---

build.yaml
pkg/buildconfig/constants.go

bump rancher shell to non-rc version

bump rancher shell to v0.1.23

---

package/Dockerfile

Bump UI to v2.8.3

---

package/Dockerfile

Bump UI to v2.7.12

---

pkg/controllers/managementuser/networkpolicy/netpol.go

When enabling the PNI on RKE2 cluster with calico CNI, the Hostnetwork Networkpolicies (hn-nodes) causes problem with traffic getting to workloads from the nodes, this problem arises because the hn-nodes netpol retrieves IP addresses from the Node's `PodCIDR` network, omitting the actual `vxlan.calico` IP address. 
Set Rke2Config while creating a custom rke2 cluster and use node annotations to detect cni.
The repro steps in the issue are correct.
After fixing it, I tried reproducing the issue with the same steps and got the expected result.

[SURE-7621] fix: update the method to detect calico cni

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go

Switch KDM from dev-v2.7 to release-v2.7

[v2.7] Switch KDM from dev-v2.7 to release-v2.7

---

Dockerfile.dapper
go.mod
go.sum
package/Dockerfile
pkg/apis/go.mod
pkg/apis/go.sum
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Changes:
- Switch KDM from dev-v2.8 to release-v2.8
- Bump rke to v1.5.7

Switch KDM from dev-v2.8 to release-v2.8

---

pkg/kontainer-engine/drivers/aks/aks_driver.go

For aks-operator there is huge update for Azure SDK https://github.com/rancher/aks-operator/issues/132. This change will break KEv1 driver, so that's why we have to move back two functions from aks-operator to aks_driver KEv1.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Revert LogAnalyticsWorkspaceForMonitoring changes

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Switch KDM from release-v2.8 to dev-v2.8

[2.8] Switch KDM from release-v2.8 to dev-v2.8

---

go.mod
go.sum
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_retention_test.go

Backport of https://github.com/rancher/rancher/pull/44535

[backport ]Snap retention2.8

---

go.mod
go.sum
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_retention_test.go

Backport of https://github.com/rancher/rancher/pull/44535

[backport] Snap retention2.7

---

pkg/data/dashboard/rbac.go
pkg/settings/setting.go

Ref: https://github.com/rancher/rancher/issues/44577
We would add ability to customize the background's images of the login and landing pages.
Adding new ui settings.
- `ui-banner-light`, `ui-banner-light` - should be available only after authentication.
- `ui-login-background-light` , `ui-login-background-light` - should be available even before authentication.
Note:
- The login background settings are added to the list of settings that an un-authenticated user can fetch - these store logo images and are equivalent to the favicon in terms of sensitivity
- These new settings follow the existing UI settings and do not expose any sensitive information and do not introduce new patterns for UI settings
The tests for this are covered by the UI tests for this feature - see: …

Add UI settings to customize login and landing page

---

tests/v2/validation/provisioning/registries/README.md

Adding documentation for the Private Registries tests execution.

[Automation] - Docs: Adding the private registries README

---

tests/v2/validation/provisioning/registries/README.md

Forward port of https://github.com/rancher/rancher/pull/43645
Adding documentation for the Private Registries tests execution.

[Automation] - Docs: Adding the private registries README - Forward port

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/rancher/issues/22417
Need to pickup webhook changes in order for QA to be able to test the issue

Bump rancher-webhook to v0.5.0-rc8

---

tests/v2/validation/provisioning/hostnametruncation/README.md
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke2/README.md

[#1170](https://github.com/rancher/qa-tasks/issues/1170)
Commit to update rke1/rke2 and the hostname truncation readmes
Readmes need to be updated due to outdated/incorrect information
Readme update
None needed

Readme update

---

tests/v2/validation/provisioning/hostnametruncation/README.md
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke2/README.md

Backport of: https://github.com/rancher/rancher/pull/44601

Backport readmeupdate28

---

tests/v2/validation/provisioning/hostnametruncation/README.md
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke2/README.md

Backport of:  https://github.com/rancher/rancher/pull/44601

Backport readmeupdate27

---

go.mod
go.sum
tests/v2/validation/rbac/globalrolesv2/README.md
tests/v2/validation/rbac/globalrolesv2/globalroles_v2.go
tests/v2/validation/rbac/globalrolesv2/globalroles_v2_webhook_test.go
tests/v2/validation/rbac/rbac_additional_test.go

Forward port of https://github.com/rancher/rancher/pull/43363

[2.9] Adding webhook checks for global roles v2

---

go.mod
go.sum
tests/v2/integration/rtbs/rtbs_test.go

Backport https://github.com/rancher/rancher/pull/44834

[2.8] Updated the tests to use the modified CreateNamespace function

---

go.mod
go.sum
tests/v2/integration/rtbs/rtbs_test.go

Backport https://github.com/rancher/rancher/pull/44834

[2.7] Updated the tests to use the modified CreateNamespace function

---

tests/scripts/shepherd/update-gomod-shepherd.sh

part one for the following effort: https://github.com/rancher/qa-tasks/issues/1136
updating shepherd versions in go is a little tedious and may lead to human error down the road.  
This script takes out the manual steps of updating go.mod
tested on linux. Needs to be tested on mac
make sure to chmod the file first so that it works properly. 
```
chmod 777 tests/scripts/shepherd/update-gomod-shepherd.sh
./update-gomod-shepherd.sh -h`
```

[2.9] adding a script that updates go.mod for shepherd

---

tests/scripts/shepherd/update-gomod-shepherd.sh

backport of https://github.com/rancher/rancher/pull/44340

[2.8] shepherd QA scripts

---

tests/scripts/shepherd/update-gomod-shepherd.sh

backport of https://github.com/rancher/rancher/pull/44340

[2.7] shepherd qa scripts

---

go.mod
go.sum
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/upgrade/README.md
tests/v2/validation/upgrade/cloud_provider_aws_migration.go
tests/v2/validation/upgrade/cloud_provider_aws_migration_test.go

https://github.com/rancher/qa-tasks/issues/1031
tested on jenkins and locally, DM for results

[2.9] add migration tests for AWS cloud provider

---

go.mod
go.sum
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/upgrade/README.md
tests/v2/validation/upgrade/cloud_provider_aws_migration.go
tests/v2/validation/upgrade/cloud_provider_aws_migration_test.go

port of: https://github.com/rancher/rancher/pull/44534

[2.8] add migration tests for AWS cloud provider

---

go.mod
go.sum
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/upgrade/README.md
tests/v2/validation/upgrade/cloud_provider_aws_migration.go
tests/v2/validation/upgrade/cloud_provider_aws_migration_test.go

port of https://github.com/rancher/rancher/pull/44534

[v2.7] migrate cloud provider aws

---

package/Dockerfile

Bump UI to 2.9.0-alpha1

---

pkg/image/origins.go

backport of https://github.com/rancher/rancher/pull/45048

[v2.7] Add mirrored-sig-storage-csi-snapshotter origin 

---

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_go_provisioing_sanity

https://github.com/rancher/qa-tasks/issues/1265
provisioning using v3 is outdated. Moving everything to go

[2.9] adding new jenkinsfile for QA release validation

---

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_go_provisioing_sanity

port of https://github.com/rancher/rancher/pull/45071

[2.8] release provisioning sanity tests

---

tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_go_provisioing_sanity

port of https://github.com/rancher/rancher/pull/45071

[2.7] adding new jenkinsfile for QA release validation

---

tests/v2/validation/certrotation/cert_rotation.go
tests/v2/validation/certrotation/cert_rotation_test.go

port of https://github.com/rancher/rancher/pull/44977

[2.8] validate cert rotation

---

tests/v2/validation/certrotation/cert_rotation.go
tests/v2/validation/certrotation/cert_rotation_test.go

port of https://github.com/rancher/rancher/pull/44977

add rke1 to cert rotation test. Add validation to cert rotation.

---

README.md

set stable release to v2.8.3

---

tests/integration/suite/conftest.py

Forwardport of https://github.com/rancher/rancher/pull/43580

[Forwardport 2.9] integration test suite: unbreak f-string

---

tests/integration/suite/conftest.py

Forwardport of https://github.com/rancher/rancher/pull/43580

[Forwardport 2.8] integration test suite: unbreak f-string

---

pkg/data/dashboard/rbac.go
pkg/settings/setting.go

Ref: https://github.com/rancher/rancher/issues/45017
Related UI issue: https://github.com/rancher/dashboard/issues/10788
We would add ability to customize the colors for login and logout pages.
Adding new ui settings.
- `ui-primary-color` , `ui-link-color` - should be available even before authentication.
Note:
- These settings follow the existing UI settings and do not expose any sensitive information and do not introduce new patterns for UI settings (they are already in use and only expose rgb colors)
The related frontend issue may contain an e2e test to cover possible regressions
* e2e (to be added to Rancher Dashboard)

add missing settings for branding customisation of login/logout page

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[v2.8] bump rke to v1.5.9-rc1

---

pkg/controllers/managementuser/rbac/handler_base_test.go
pkg/controllers/managementuser/rbac/namespace_handler_test.go
pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler_test.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go
pkg/controllers/managementuser/rbac/roletemplate_handler.go

Ref: https://github.com/rancher/rancher/issues/44942
Backport of https://github.com/rancher/rancher/pull/44765

[v2.8] fix: update 'promoted' ClusterRole when removing all permissions from RoleTemplate

---

pkg/settings/setting.go

Bakport of #45084
https://github.com/rancher/rancher/issues/43992
N/A
Migrate from rancher v2.7. Make sure `eula-agreed` setting doesn't receive `cattle.io/unknown` label.
N/A
N/A

[v2.8] Make eula-agreed setting known to Rancher

---

pkg/image/origins.go

This is a backport of https://github.com/rancher/rancher/pull/45097

Add new image rancher/mirrored-longhornio-openshift-origin-oauth-proxy

---

go.mod
go.sum
pkg/auth/providers/azure/clients/ms_graph_client.go

While migrating away from the old Azure SDK, it was discovered that `github.com/AzureAD/microsoft-authentication-library-for-go` was pinned to an older version which caused build errors when importing the [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) package.
Bumped `github.com/AzureAD/microsoft-authentication-library-for-go` to v1.2.2 and migrated code as per https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/380. This allows us to import [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) without any issues.
* None
* If "None" - Reason: No application logic is modified by this change (refactoring).
Summary: …

Bump `github.com/AzureAD/microsoft-authentication-library-for-go` to v1.2.2

---

go.mod
go.sum
tests/v2/integration/catalogv2/rancher_managed_charts_test.go
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go

port of https://github.com/rancher/rancher/pull/44787/files

[2.8] add vsphere chart validation to automation framework

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go

port of https://github.com/rancher/rancher/pull/44787

[2.7] add vsphere chart validation to automation framework

---

tests/v2/validation/provisioning/import/README.md
tests/v2/validation/provisioning/import/import_cluster_test.go
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_go_provisioing_sanity

port of https://github.com/rancher/rancher/pull/45123

[2.7] adding an import test to the go framework

---

tests/v2/validation/provisioning/import/README.md
tests/v2/validation/provisioning/import/import_cluster_test.go
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_go_provisioing_sanity

port of https://github.com/rancher/rancher/pull/45123

[2.8] adding an import test to the go framework

---

tests/scripts/shepherd/update-gomod-shepherd.sh

script wasn't updating the go.* in some cases, so this is addressing that issue
* pull from upstream
* fix local variable naming
local testing

updating script to help sync shepherd with rancher

---

tests/scripts/shepherd/update-gomod-shepherd.sh

port of https://github.com/rancher/rancher/pull/45033

[v2.7] shepherd script improvements

---

tests/scripts/shepherd/update-gomod-shepherd.sh

port of https://github.com/rancher/rancher/pull/45033

[v2.8] shepherd script improvements

---

go.mod
go.sum

Shepherd had outdated packages that were causing the aks operator package to be downgraded.
Upgraded shepherd.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Bumped the shepherd version to avoid downgrade of the aks-operator

---

tests/v2/validation/provisioning/import/import_cluster_test.go

import cluster test has been flaky. 
This PR adds a wait to getting the kubeconfig. This is sometimes a problem that I noticed during testing
it also restricts the test to only run the corral that will run the test. This is to help refine exactly what runs as part of the test.

[2.9] updating import cluster test to be less flaky

---

go.mod
go.sum
tests/v2/validation/provisioning/import/import_cluster_test.go

port of https://github.com/rancher/rancher/pull/45197

[v2.8] update import cluster

---

go.mod
go.sum
tests/v2/validation/provisioning/import/import_cluster_test.go

port of https://github.com/rancher/rancher/pull/45197

[v2.7] update import cluster

---

pkg/image/origins.go

Add origin of image `hardened-addon-resizer` to unblock failing pipelines.
* Unit
* None
_TODO_
* _TODO_

[release/v2.7] Add `hardened-addon-resizer` image origin

---

pkg/image/origins.go

Add origin of image `hardened-addon-resizer` to unblock failing pipelines.
* Unit
* None
_TODO_
* _TODO_

[release/v2.9] Add `hardened-addon-resizer` image origin

---

build.yaml
pkg/buildconfig/constants.go

Bump to this chart version: https://github.com/rancher/charts/pull/3837

[2.8] Bump rancher webhook v0.4.4-rc1

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/43563
Unicode character support in rancher/shell (terminal) via Web UI. 
Bump `rancher/shell` to use new version with ENV patched for unicode chars.
Repro steps on issue are accurate.

[v2.7] bump default shell version to v0.1.24-rc1

---

pkg/image/origins.go

Add origin of image `hardened-addon-resizer` to unblock failing pipelines.
* Unit
* None
_TODO_
* _TODO_

[release/v2.8] Add `hardened-addon-resizer` image origin

---

tests/v2/validation/upgrade/workload.go

**Issue**
local ha upgrade job was failing workload checks for `daemonSets` in the local cluster due to `worker` node filtering.  For example, if 3 `server_nodes` are requested for the local cluster with no `agent_nodes`, the daemonSets are deployed on the `server_nodes`, and the validation check filters out `server_nodes` to explicitly target the `workers` (agent_nodes). So in this example, the test will fail, expecting 3 replicas, and only finding 0.
**Solution**:
enhance job to check `daemonSets` against the total number of nodes, for the local cluster.  This will function as expected now, regardless of the number of `server_nodes` and `agent_nodes` requested for the local cluster. 
So, with the fix: 
- if 3 `server_nodes` are requested as the local cluster, validation will ensure 3 …

Fix local ha upgrade jenkins job failures

---

pkg/settings/setting.go

Awaiting QA to promote `*-rc1` to stable - preparing draft in advance.

[v2.7] bump default shell version to v0.1.24

---

go.mod
go.sum
tests/v2/validation/deleting/README.md
tests/v2/validation/deleting/delete_init_machine.go
tests/v2/validation/deleting/delete_init_machine_test.go

backport of:
https://github.com/rancher/rancher/pull/45260

Adds automated support to test Init node cannot be deleted issue

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

All jobs were attempting to pull the image from the staging registry instead of just the v2.7 job.
Fix the way the config file is written. 
Jenkins job
* Unit
* None
_TODO_
* _TODO_

[v2.9] Fixed config logic for our recurring runs.

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

All jobs were attempting to pull the image from the staging registry instead of just the v2.7 job.
Fix the way the config file is written. 
Jenkins job
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fixed config logic for our recurring runs.

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

All jobs were attempting to pull the image from the staging registry instead of just the v2.7 job.
Fix the way the config file is written. 
Jenkins job
* Unit
* None
_TODO_
* _TODO_

[v2.7] Fixed config logic for our recurring runs.

---

go.mod
go.sum

[v2.8] Upgrade rancher/steve to include race condition fix

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/44980

[v2.8] update rke to v1.5.9-rc2

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

Backport of https://github.com/rancher/rancher/pull/45391.

[v2.8] Update snapshot names to use S3 or local

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

Backport of https://github.com/rancher/rancher/pull/45391.

[v2.7] Update snapshot names to use S3 or local

---

build.yaml
pkg/buildconfig/constants.go

rancher/rancher#44980
Webhook Bump to resolve the above issue to v0.4.5-rc2.

bump rancher-webhook to v0.4.5-rc2

---

pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Fixes #44347 
* Unit
* None
_TODO_
* _TODO_

Add sync.Mutex to stop concurrent secret creation

---

pkg/catalogv2/oci/oci.go
pkg/catalogv2/oci/oci_test.go

See the issue for more information.
This PR implements a logic to remove deleted tags from the helm index file

removing deleted tags from the helm index file

---

tests/v2/validation/Jenkinsfile.rc

the jenkinsfile for provisioning sanity checks needs some revision after testing.

[2.9] update jenkinsfile for provisioning automation

---

tests/v2/validation/Jenkinsfile.rc

port of https://github.com/rancher/rancher/pull/45397

[2.8] update jenkinsfile for provisioning automation

---

tests/v2/validation/Jenkinsfile.rc

port of https://github.com/rancher/rancher/pull/45397

[2.7] update jenkinsfile for provisioning automation

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

* CI is failing across the v2.9 PRs. eg https://github.com/rancher/rancher/pull/45441/commits
* This reverts commit 96d79a80b2d649775a14a99d26764c2b11f76556, reversing changes made to d97e9fc6b0f03cb84ab91615fcc9cf564b09c83d.

Revert "Merge pull request #45391 from markusewalker/markusv29/updatte-snapshot-names"

---

Dockerfile.dapper
go.mod
go.sum
package/Dockerfile
pkg/apis/go.mod
pkg/apis/go.sum
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Bump RKE to v1.4.18
Switch KDM branch to release-v2.7

[2.7] Prepare Final RC

---

Dockerfile.dapper
go.mod
go.sum
package/Dockerfile
pkg/apis/go.mod
pkg/apis/go.sum
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Bump RKE to v1.5.9
Switch KDM branch to release-v2.8

[2.8] Prepare Final RC

---

tests/integration/suite/test_app.py

Please see the issue for more details. 
Removing a flaky test that is causing delays in CI. This test is being removed since the codebase that is related to the test is dead code.

[2.8] Remove flaky test of appsv1

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump `rancher/cli` to v2.8.4

---

.github/workflows/verify-generated-code-changes.yml
Dockerfile.dapper
pkg/crds/yaml/generated/catalog.cattle.io_uiplugins.yaml
pkg/crds/yaml/generated/management.cattle.io_clusterproxyconfigs.yaml
pkg/crds/yaml/generated/management.cattle.io_clusterroletemplatebindings.yaml
pkg/crds/yaml/generated/management.cattle.io_globalrolebindings.yaml
pkg/crds/yaml/generated/management.cattle.io_globalroles.yaml
pkg/crds/yaml/generated/management.cattle.io_projectroletemplatebindings.yaml
pkg/crds/yaml/generated/management.cattle.io_projects.yaml
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml

controller-gen v0.12.0 panics on go 1.22
Bump to v0.14.0
Ran go generate locally, succeeded and comitted changes

45503 bump controller gen

---

pkg/auth/providers/github/github_client.go
pkg/auth/providers/github/github_client_test.go
pkg/auth/providers/github/github_provider.go
pkg/auth/providers/github/github_provider_test.go
pkg/auth/providers/github/githubconfig_actions.go

Backport of #45162
* Unit
N/A
N/A

[v2.8] GitHub Auth Provider: allow to search teams

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/README.md

Backport of https://github.com/rancher/rancher/pull/45532.

[v2.8] Fix RKE1 nodetemplates to include cloud credentials

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/README.md

Backport of https://github.com/rancher/rancher/pull/45532.

[v2.7] Fix RKE1 nodetemplates to include cloud credentials

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

Prime repo needed to be added for v2.7-head rancher setup.
Rancher install was not working for prime
update the prime var
* Unit
* None
_TODO_
* _TODO_

[v2.9] Added prime as a var.

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

Prime repo needed to be added for v2.7-head rancher setup.
Rancher install was not working for prime
update the prime var
* Unit
* None
_TODO_
* _TODO_

[v2.8] prime repo fix

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

Prime repo needed to be added for v2.7-head rancher setup.
Rancher install was not working for prime
update the prime var
* Unit
* None
_TODO_
* _TODO_

[v2.7] prime as a var fix

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Switch KDM branch to dev-v2.7
This reverts commit 1a558ed76ad746bd406f04103358cb5cd493aa92.

[2.7] Switch KDM branch to dev-v2.7

---

tests/v2/validation/projects/README.md
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_test.go

Backport https://github.com/rancher/rancher/pull/45381
Issue: https://github.com/rancher/qa-tasks/issues/1248

[2.8] Generic P0 Test Cases for Project

---

tests/v2/validation/cli/cli_test.go

CLI tests are running in all of our QA recurring runs because we do not have a Go build tag.
Add a simple Go build tag to the CLi test.

[v2.9] Add Go tag for CLI test

---

tests/v2/validation/cli/cli_test.go

Backport for https://github.com/rancher/rancher/pull/45592.

[v2.7] Add Go tag for CLI test

---

tests/v2/validation/Jenkinsfile.rc
tests/v2/validation/certrotation/cert_rotation.go

https://github.com/rancher/qa-tasks/issues/1321

update provisioning test jenkinsfile for further compatibility

---

tests/v2/validation/Jenkinsfile.rc
tests/v2/validation/certrotation/cert_rotation.go

port of: https://github.com/rancher/rancher/pull/45579

[v2.8] update provisioning jenkinsfiles

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/resources/cisbenchmark/cisbenchmark.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go

This is the Rancher counterpart for shepherd PR https://github.com/rancher/shepherd/pull/198.
Jenkins jobs will be given to reviewers offline.

[v2.9] Enhance existing hardened clusters tests to install CIS chart

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/resources/cisbenchmark/cisbenchmark.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go

Backport of https://github.com/rancher/rancher/pull/45578.

[v2.8] Enhance existing hardened clusters tests to install CIS chart

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/resources/cisbenchmark/cisbenchmark.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go

Backport of https://github.com/rancher/rancher/pull/45578.

[v2.7] Enhance existing hardened clusters tests to install CIS chart

---

pkg/features/feature.go

#43131
https://github.com/rancher/dashboard/issues/9823
This PR adds a new feature flag to allow a user to hide the RKE1 functionality in the UI.
Simple new feature flag in support of the UI work here - https://github.com/rancher/dashboard/issues/9823 and https://github.com/rancher/dashboard/pull/10056
Testing will be covered by the UI PR.
* Unit - UI Unit tests
None
See UI tests

Add new feature flag to allow RKE1 UI functionality to be hidden

---

pkg/controllers/dashboard/helm/repo.go
pkg/controllers/dashboard/helm/repo_oci.go

Changing the error when an OCI repository fails to be more user friendly

changing OCI errors to be more user friendly

---

tests/v2/validation/rbac/clusterandprojectroles/README.md

Back port https://github.com/rancher/rancher/pull/45705

[2.7] Updating the readme for the provisioning part of the tests

---

tests/v2/validation/rbac/clusterandprojectroles/README.md
tests/v2/validation/rbac/globalrolesv2/README.md

Updating the read me for the following files, as some of them have outdated configs.

[2.9] Updating the readme for the provisioning part of the tests.

---

tests/v2/validation/Jenkinsfile.rc

https://github.com/rancher/qa-tasks/issues/1321

[2.9] update sanity check jenkinsfile for provisioning

---

tests/v2/validation/Jenkinsfile.rc

port of https://github.com/rancher/rancher/pull/45693

[v2.8] update jenkinsfile corral rc

---

tests/v2/validation/Jenkinsfile.rc

port of https://github.com/rancher/rancher/pull/45693

[v2.7] update sanity check jenkinsfile for provisioning

---

tests/v2/validation/rbac/clusterandprojectroles/README.md
tests/v2/validation/rbac/globalrolesv2/README.md

Back port https://github.com/rancher/rancher/pull/45705

[2.8] Updating the readme for the provisioning part of the tests.

---

tests/scripts/custodian/Dockerfile
tests/scripts/custodian/Jenkinsfile
tests/scripts/custodian/azure.yaml
tests/scripts/custodian/gcp.yaml

https://github.com/rancher/qa-tasks/issues/1377

[2.9] updating dry-run custodian scripts for automation

---

tests/scripts/custodian/Dockerfile
tests/scripts/custodian/Jenkinsfile
tests/scripts/custodian/azure.yaml
tests/scripts/custodian/gcp.yaml

port of https://github.com/rancher/rancher/pull/45719

[2.8] updating dry-run custodian scripts for automation

---

tests/scripts/custodian/Dockerfile
tests/scripts/custodian/Jenkinsfile
tests/scripts/custodian/azure.yaml
tests/scripts/custodian/gcp.yaml

port of https://github.com/rancher/rancher/pull/45719

[2.7] updating dry-run custodian scripts for automation

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
pkg/client/generated/management/v3/zz_generated_role_template.go
pkg/controllers/management/auth/manager.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml
pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go
pkg/data/management/rolebuilder_test.go
pkg/features/feature.go
pkg/rbac/common.go

[v2.7.14] s4: Fix 374

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
pkg/client/generated/management/v3/zz_generated_role_template.go
pkg/controllers/management/auth/manager.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml
pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go
pkg/data/management/rolebuilder_test.go
pkg/features/feature.go
pkg/rbac/common.go

[v2.8.5] s4: Fix 374

---

.drone.yml
generate.go
scripts/configure-drone

[v2.8.5] s4: Fixes 45418

---

go.mod
tests/v2/validation/auth/lastlogin/README.md
tests/v2/validation/auth/lastlogin/last_login.go
tests/v2/validation/auth/lastlogin/last_login_test.go

[v2.8.5] s4: Fixes 227 tests

---

package/Dockerfile

Bump ui version to v2.9.0-alpha5

Update ui settings - v2.9.0-alpha5

---

.drone.yml
build.yaml
pkg/buildconfig/constants.go

[v2.8.5] s4: Bump rancher-webhook to v0.4.6

---

pkg/settings/setting.go

[2.7] Add new setting agent-tls-mode

---

pkg/settings/setting.go

[2.8] Add new setting agent-tls-mode 

---

.drone.yml
build.yaml
pkg/buildconfig/constants.go

[v2.8.5] s4: Bump rancher-webhook to v0.4.7

---

pkg/api/steve/supportconfigs/generator_test.go

The test suite is missing a test case where the metering archive is not found
Adding test case throwing a not found error
* Unit

Adds test case when metering archive is not found

---

.drone.yml
build.yaml
pkg/buildconfig/constants.go

Bump fleet version to resolve airgap release issues to v0.9.5

Bump fleet version to v0.9.5

---

pkg/controllers/management/secretmigrator/clusters.go

https://github.com/rancher/rancher/issues/45605
We can configure RKE1 downstream clusters to use a private registry, Rancher migrates the credential to a Secet and wipes out the password value from the mgmt cluster object for security reasons when creating or updating the cluster. When updating the private registries on an RKE1 downstream cluster Rancher always skips the entry whose password is empty. Rancher thinks the reason for an empty password is it has been migrated to a Secret, so skipping the entry can avoid wiping out the password from the Secret. 
The logic works well in most cases but causes a problem in the following one: once the username and password are set for a private registry on the RKE1 downstream cluster, we will not be able to unset those two values at the same time …

Fix the issue where we could not unset the username and password of an existing private registry in the RKE1 downstream cluster

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/template_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/template_test.go

RKE2 templates are currently tested manually.
Automated rke2 template tests
Tested changes using Jenkins and my local config.

RKE2 template test

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/template_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/template_test.go

PR updates
Pr Update
k3s update
updated with generic create
readmes
readme update
Update commits
Update go.sum
Update function naming
go.mod update
* Unit
* None
_TODO_
* _TODO_

[Backport 2.7] RKE2 templates test

---

pkg/controllers/management/secretmigrator/clusters.go

Issue: https://github.com/rancher/rancher/issues/45820
This PR cherry-picks this commit from https://github.com/rancher/rancher/pull/45781 
Please check the original PR for details

[Backport][2.8] Fix the issue where we could not unset the username and password of an existing private registry in the RKE1 downstream cluster

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/template_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/template_test.go

PR updates
Pr Update
k3s update
updated with generic create
readmes
readme update
Update commits
Update go.sum
Update function naming
go.mod update
* Unit
* None
_TODO_
* _TODO_

[Backport 2.8] Rke2 template test

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
pkg/client/generated/management/v3/zz_generated_role_template.go
pkg/controllers/management/auth/manager.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml
pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go
pkg/data/management/rolebuilder_test.go
pkg/features/feature.go
pkg/rbac/common.go

port of https://github.com/rancher/rancher/pull/45735

[v2.7] s4: Fix 374 

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
pkg/client/generated/management/v3/zz_generated_role_template.go
pkg/controllers/management/auth/manager.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml
pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go
pkg/data/management/rolebuilder_test.go
pkg/features/feature.go
pkg/rbac/common.go

port of https://github.com/rancher/rancher/pull/45733

[v2.9] s4: Fix 374 

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
pkg/client/generated/management/v3/zz_generated_role_template.go
pkg/controllers/management/auth/manager.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml
pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go
pkg/data/management/rolebuilder_test.go
pkg/features/feature.go
pkg/rbac/common.go

port of https://github.com/rancher/rancher/pull/45733

[v2.8] s4: Fix 374

---

go.mod
go.sum
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/resources/cisbenchmark/cisbenchmark.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

rancher/rancher counterpart to shepherd PR https://github.com/rancher/shepherd/pull/205.

[v2.9] Provide general stability for snapshot tests

---

go.mod
go.sum
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/resources/cisbenchmark/cisbenchmark.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

Backport of https://github.com/rancher/rancher/pull/45668.

[v2.8] Provide general stability for snapshot test

---

go.mod
go.sum
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/resources/cisbenchmark/cisbenchmark.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

Backport of https://github.com/rancher/rancher/pull/45668.

[v2.7] Provide general stability for snapshot test

---

tests/v2/validation/auth/lastlogin/README.md
tests/v2/validation/auth/lastlogin/last_login.go
tests/v2/validation/auth/lastlogin/last_login_test.go

Port of #45773
* Adding end to end validations for user last login
* Unit
* None
_TODO_
* _TODO_

[v2.8] s4: Fixes 227 tests

---

tests/v2/validation/auth/lastlogin/README.md
tests/v2/validation/auth/lastlogin/last_login.go
tests/v2/validation/auth/lastlogin/last_login_test.go

Port of #45773
* Adding end to end validations for user last login
* Unit
* None
_TODO_
* _TODO_

[v2.9] s4: Fixes 227 tests

---

pkg/controllers/management/rkeworkerupgrader/plan.go
pkg/controllers/management/secretmigrator/assemblers/assemblers.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Porting fix 524 from https://github.com/rancher/rancher/pull/45767

[v2.9] Port fix 524

---

pkg/controllers/management/rkeworkerupgrader/plan.go
pkg/controllers/management/secretmigrator/assemblers/assemblers.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Porting fix 524 from https://github.com/rancher/rancher/pull/45767

[v2.8] Port fix 524

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

User-retention UI changes were introduced in v2.8.5 and v2.7.14.
Bump `CATTLE_DASHBOARD_UI_VERSION` to `v2.9.0-alpha6` that contains these changes.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Bump CATTLE_DASHBOARD_UI_VERSION to v2.9.0-alpha6

---

pkg/settings/setting.go

Since v2.9 (#44070) all unknown settings are deleted by Rancher on startup.
There are some dashboard UI settings that Rancher is currently unaware of.
Add those settings.
* Unit
* None
N/A
N/A

[v2.9] Add UI settings

---

.drone.yml
generate.go
scripts/configure-drone

Make Drone pick up build-config env vars
* Unit
* None
_TODO_
* _TODO_

[v2.8] s4: Make Drone run scripts/export-config to pick up build time env vars (#536)

---

go.mod
go.sum
tests/v2/validation/Dockerfile.validation
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/upgrade/README.md
tests/v2/validation/upgrade/cloud_provider_version.go
tests/v2/validation/upgrade/cloud_provider_version_test.go

https://github.com/rancher/qa-tasks/issues/1291
we need automated support for upgrading vsphere charts

[2.9] update for vsphere charts upgrade support

---

go.mod
go.sum
tests/v2/validation/Dockerfile.validation
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/upgrade/README.md
tests/v2/validation/upgrade/cloud_provider_version.go
tests/v2/validation/upgrade/cloud_provider_version_test.go

port of https://github.com/rancher/rancher/pull/45792

[2.8] Automation for upgrade cpi csi

---

.drone.yml
build.yaml
pkg/buildconfig/constants.go

[v2.8] s4: Bump webhook to v0.4.8-rc1

---

build.yaml
pkg/buildconfig/constants.go

Bump the rancher-webhook to the latest RC `v0.5.0-rc9`.
N/A
N/A
N/A

[v2.9] Bump rancher-webhook to v0.5.0-rc9

---

pkg/controllers/management/rkeworkerupgrader/plan.go
pkg/controllers/management/secretmigrator/assemblers/assemblers.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Porting fixes from https://github.com/rancher/rancher/pull/45774

[v2.7] Port fixes 524

---

go.mod
go.sum

Includes https://github.com/rancher/steve/pull/211

Upgrade rancher/steve to include cache key fix

---

.github/runs-on.yml

https://github.com/rancherlabs/eio/issues/2399
Jobs are not assigned to custom runners without extra configuration inherited from a private repository
A configuration file must be added to the default branch.
https://github.com/rancherlabs/eio/issues/2399#issuecomment-2169056941
None – configuration must be installed prior to testing.

Add configuration for custom runners

---

pkg/image/origins.go

New images from https://github.com/rancher/image-mirror/pull/641 caused drone CI to fail: https://drone-pr.rancher.io/rancher/rancher/40495/6/2
Add new images to `origins.go`
* Unit
* None
_TODO_
* _TODO_

[release/v2.9] Add mirrored-prometheus-operator-admission-webhook to image origins

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/controllers/management/certsexpiration/certsexpiration.go
pkg/controllers/management/clusterprovisioner/driver.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/rancher/migrations.go

Porting https://github.com/rancher/rancher/pull/45767

[v2.7] Port fix 478 v2.7

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/controllers/management/certsexpiration/certsexpiration.go
pkg/controllers/management/clusterprovisioner/driver.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/rancher/migrations.go

Porting https://github.com/rancher/rancher/pull/45767

[v2.9] Port fixes 478

---

pkg/controllers/management/certsexpiration/certsexpiration.go
pkg/controllers/management/clusterprovisioner/driver.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/rancher/migrations.go

Porting https://github.com/rancher/rancher/pull/45767

[v2.8] Port fix 478

---

go.mod
go.sum

Bumps Shepherd version to `v0.0.0-20240628185912-bd372ac2e2e1`

[2.9] Bump Shepherd Version

---

go.mod
go.sum

Bumps Shepherd version to `v0.0.0-20240628185929-7dadbb861c35`

[2.8] Bump Shepherd Version

---

package/Dockerfile

Bump UI & Dashboard index to v2.9.0-alpha7

Bump UI & Dashboard index to v2.9.0-alpha7

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

- https://github.com/rancher/rancher/issues/45783

[release/v2.7] Bump rancher/rke v1.4.20-rc1

---

pkg/auth/tokens/manager.go
pkg/auth/tokens/manager_test.go

#45956
Group principals are not being updated outside of the login path.
Make sure group principals and user extras are compared prior to applying changes.
* Unit
_TODO_
* _TODO_

[v2.9] Make sure group principals are updated

---

build.yaml
pkg/buildconfig/constants.go

[v2.8] Bump shell version to RC

---

package/Dockerfile

Bump ui version to v2.8.6-alpha2

Update UI settings - v2.8.6-alpha2

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/authconfig_test.go

Backport of #44917  
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fix migration of broken secret name for Shibboleth AuthConfig.

---

go.mod
go.sum

Upgrade rancher/remotedialer to include fix for goroutines leak

---

pkg/auth/tokens/manager.go
pkg/auth/tokens/manager_test.go

Backport of #45970
* Unit
_TODO_
* _TODO_

[v2.7] Make sure group principals are updated

---

pkg/auth/tokens/manager.go
pkg/auth/tokens/manager_test.go

#45993
Backport of #45970
* Unit
_TODO_
* _TODO_

[v2.8] Make sure group principals are updated

---

go.mod
go.sum

Bumps steve to include fix for apigroups issue
rancher/rancher#45955
N/A, see the steve PR: rancher/steve#230.
N/A, see the steve PR.

Bumping steve

---

build.yaml
pkg/buildconfig/constants.go

Bump rancher-webhook to v0.5.0-rc11

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.schema.json
chart/values.yaml

https://github.com/rancher/rancher/issues/45938
v2.8 also needs: https://github.com/rancher/rancher/pull/45522
We backport. 
* Unit - Helm unit tests added to cover new value and possible results.
Summary: The tests verify all expected results based on potential valid inputs.
_TODO_
* _TODO_

[v2.8] Add new agent TLS chart value & validation jsonSchema

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/45038

Bump system-agent to v0.3.7-rc3

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/authconfig_test.go

Backport of #45900 
* Unit
* None
_TODO_
* _TODO_

[v2.8] Fix the storage of Okta Config passwords.

---

pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

[WIP] Use Mutex & Lease to stop concurrent secret creation

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/43356

[v2.9] update rke to v1.6.0-rc9

---

pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

https://github.com/rancher/rancher/issues/45950

[v2.8] go generate for aci fields

---

build.yaml
pkg/buildconfig/constants.go

Bump webhook to 104.0.0+up0.5.0-rc12

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[v2.8] Bump eks-operator to v1.3.3-rc.2

---

tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go

Backport of https://github.com/rancher/rancher/pull/46052.

[v2.8] Remove admin user tests from provisioning

---

tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go

Backport of https://github.com/rancher/rancher/pull/46052.

[v2.7] Remove admin user tests from provisioning

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Bump aks-operator to v1.2.3-rc.5

---

pkg/auth/providers/saml/saml_client.go

#46124
* Unit
* None
_TODO_
* _TODO_

[v2.9] Set LastLogin on SAML login

---

pkg/auth/providers/saml/saml_client.go

#46125
Backport of #46120
* Unit
* None
_TODO_
* _TODO_

[v2.8] Set LastLogin on SAML login

---

pkg/auth/providers/saml/saml_client.go

#46126
Backport of #46120
* Unit
* None
_TODO_
* _TODO_

[v2.7.15] Set LastLogin on SAML login

---

pkg/auth/providers/saml/saml_client.go

#46126
Backport of #46120
* Unit
* None
_TODO_
* _TODO_

[v2.7] Set LastLogin on SAML login

---

.github/workflows/push-release.yml
.github/workflows/validate.yml
package/Dockerfile
package/Dockerfile.agent

#46160
* [v2.9-head](https://hub.docker.com/layers/rancher/rancher/v2.9-head/images/sha256-595eb0f09c9243f5317c0f865b0c0cc4d5c666f434e2feca0ed4883bde320282?context=explore) image has `VERSION=dev` which is not correct
* The validate workflow is failing with an invalid python version
* Set the correct tag at build time
* Install the correct python version
* Unit
* None
_TODO_
* _TODO_

[v2.9] Fix validate script and rancher version

---

.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml
package/Dockerfile
package/Dockerfile.agent
package/windows/Dockerfile.agent

https://github.com/rancher/rancher/issues/46152
* The server version is not set on the final image
* The agent image build can't pull the server image from the local registry
* Set version args on the final image
* Use `127.0.0.1` instead of `localhost` on the local registry.
* Unit
* None
_TODO_
* _TODO_

[v2.9] fix registry and rancher server version env

---

.github/workflows/push-release.yml

[v2.9] fix agent build

---

.github/workflows/provisioning-tests.yml
.github/workflows/push-release.yml

[v2.9] fix images push

---

build.yaml
pkg/buildconfig/constants.go

[v2.9] Un-rc the Rancher Shell image

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[v2.9] Bump eks-operator to v1.9.0-rc.11

---

pkg/auth/providers/activedirectory/activedirectory_actions.go
pkg/auth/providers/azure/azure_actions.go
pkg/auth/providers/github/githubconfig_actions.go
pkg/auth/providers/googleoauth/goauthconfig_actions.go
pkg/auth/providers/ldap/ldap_actions.go
pkg/auth/providers/oidc/oidc_actions.go
pkg/auth/providers/saml/saml_client.go

#46164
There is a chance that provider refresh gets to updating userattribute first causing the conflict.
Retry the update on conflict.
_TODO_
* _TODO_

[v2.9] Retry updating userAttribute when enabling auth provider

---

pkg/auth/providers/activedirectory/activedirectory_actions.go
pkg/auth/providers/azure/azure_actions.go
pkg/auth/providers/github/githubconfig_actions.go
pkg/auth/providers/googleoauth/goauthconfig_actions.go
pkg/auth/providers/ldap/ldap_actions.go
pkg/auth/providers/oidc/oidc_actions.go
pkg/auth/providers/saml/saml_client.go

Backport of #46184
_TODO_
* _TODO_

[v2.8] Retry updating userAttribute when enabling auth provider

---

pkg/auth/providers/activedirectory/activedirectory_actions.go
pkg/auth/providers/azure/azure_actions.go
pkg/auth/providers/github/githubconfig_actions.go
pkg/auth/providers/googleoauth/goauthconfig_actions.go
pkg/auth/providers/ldap/ldap_actions.go
pkg/auth/providers/oidc/oidc_actions.go
pkg/auth/providers/saml/saml_client.go

Backport of #46184
_TODO_
* _TODO_

[v2.7.15] Retry updating userAttribute when enabling auth provider

---

pkg/auth/providers/activedirectory/activedirectory_actions.go
pkg/auth/providers/azure/azure_actions.go
pkg/auth/providers/github/githubconfig_actions.go
pkg/auth/providers/googleoauth/goauthconfig_actions.go
pkg/auth/providers/ldap/ldap_actions.go
pkg/auth/providers/oidc/oidc_actions.go
pkg/auth/providers/saml/saml_client.go

Backport of #46184
_TODO_
* _TODO_

[v2.7] Retry updating userAttribute when enabling auth provider

---

package/Dockerfile

Update UI settings to v2.9.0-rc2

Update UI settings to v2.9.0-rc2

---

build.yaml
pkg/buildconfig/constants.go

Related to https://github.com/rancher/rancher/issues/46254

[v2.8] Fix missing feature-flag error in webhook

---

.github/actions/k3s-images/action.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml
package/Dockerfile

* The `k3s-airgap-images.tar` file was empty and had a typo in it
* Added an action to populate the file and fixed the typo
* Unit
* None
_TODO_
* _TODO_

[v2.9] fix k3s-airgap images

---

cmd/agent/main.go

https://github.com/rancher/rancher/issues/46257

[release/v2.9] Make strict root CA validation more explicit

---

cmd/agent/main.go

https://github.com/rancher/rancher/issues/46263
https://github.com/rancher/rancher/pull/46261/
https://github.com/rancher/rancher/issues/46257

[release/v2.8] Make strict root CA validation more explicit

---

.github/workflows/push-release.yml

Github Actions charts upload

---

package/Dockerfile

Update ui settings for v2.9.0-rc3

Update ui settings - v2.9.0-rc3

---

go.mod
go.sum
tests/v2/integration/catalogv2/rancher_managed_charts_test.go
tests/v2/integration/catalogv2/ui_plugin_test.go
tests/v2/integration/projects/project_user_test.go
tests/v2/integration/setup/main.go

Needed to skip flakey tests
Remove skips also updated rancher/shepherd version that has new fixes.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Removed the skips to the UI plugins test and the ServerIcons test.

---

.github/workflows/push-release.yml

[v2.7.15] fix docker login

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml
package/Dockerfile.installer

* AWS CLI commands were failing, probably due to missing the default region env variable
* Define the region env variable
* Add needs push images before publishing charts
* Update step names
* Unit
* None
_TODO_
* _TODO_

[v2.7.15] fix aws upload and chart publish
