rancher/rancher

tests/framework/extensions/machinepools/machinepools.go
tests/framework/extensions/provisioning/creates.go
tests/framework/extensions/provisioning/nodeproviders.go
tests/framework/extensions/rke1/nodepools/nodepools.go
tests/framework/extensions/scalinginput/config.go
tests/v2/validation/nodescaling/README.md
tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_test.go
tests/v2/validation/nodescaling/scaling_nodepools.go

Recently, we introduced a new scaling test suite in the test framework for machine pools for RKE2/K3S node driver clusters. However, we currently do not support adding/deleting nodes in a custom RKE2/K3S cluster.
With the new scaling test suite, that is a test that we should ensure that we're covering in our Go framework.
Implemented a test that adds/delete custom cluster nodes in a provisioned RKE2/K3S custom cluster. Using the `scalingInput` block in your config file, you can customize the quantity of your desired node role. An example is you can have the following block:
```
scalingInput:
nodeProvider: "ec2"
machinePools:
nodeRoles:
worker: true
quantity: 2
```
This will add two new nodes to the cluster and then delete the nodes from Rancher and the underlying EC2 instance.
- …

[v2.8] Add support for adding/deleting RKE1/RKE2/K3S custom cluster nodes

---

pkg/settings/setting.go

- `rancher/dashboard` and `rancher/ui` have both now branched for 2.8.0
- This change ensures the `rancher/rancher` 2.8 branch points to the correct builds
- These builds are used, when settings are default, when the version ends in `-head` as an alternative to the embedded builds

Update references to new 2.8.0 UI branches

---

tests/framework/extensions/machinepools/machinepools.go
tests/framework/extensions/rke1/nodepools/nodepools.go
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke2/README.md

This issue is a forward port of [42839](https://github.com/rancher/rancher/pull/42839)
[513](https://github.com/rancher/qa-tasks/issues/513)
We don't have the option to set the value for drainBeforeDelete in our automation suite. We want to include test cases for this feature and need this option in our framework.
We are adding the drainBeforeDelete field to allow us to use this feature in our automation suite.
Manual testing was done on local setup to ensure that the field was being added correctly.
Jenkins jobs will be available upon request
This is for the qa team to be able to run automated tests around the drainBeforeDelete feature
There are no regressions as the feature already exists and we are just adding the field to enable the feature on the automation suite.

Adding drainBeforeDelete field to enable the feature in provisioning tests

---

tests/v2/validation/certrotation/README.md
tests/v2/validation/deleting/README.md
tests/v2/validation/nodescaling/README.md
tests/v2/validation/prime/README.md
tests/v2/validation/provisioning/README.md
tests/v2/validation/provisioning/hosted/README.md
tests/v2/validation/provisioning/hostnametruncation/README.md
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/snapshot/README.md
tests/v2/validation/upgrade/README.md

The provisioning READMEs in the Go framework are not as clear as they need to be. Regardless if you're new to the framework or more seasoned, there are a couple of problems. These include:
- Automated tests missing completely in a README
- Unclear steps on how to run an automated test
The overall provisioning READMEs should be refactored so that it is much more clear as to what tests exist and how to actually run the tests.

[v2.8] Refactor provisioning READMEs

---

tests/framework/clients/rancher/v1/client.go

backport of: https://github.com/rancher/rancher/pull/43277
The problem was that when creating this test I personally only use Rancher setups with certs. However, if someone runs this on a Rancher setup without certs it doesn't execute the test
Add a step to check if we need to skip cert verification
```go
if skipCertVerification {
tr.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
}
```
Summary: Updated the configmaps test to work with secure or insecure Rancher setups

fix test to work with rancher envs without cert bp

---

tests/framework/extensions/provisioning/verify.go
tests/framework/extensions/registries/registries.go
tests/framework/extensions/workloads/pods/pod_status.go
tests/framework/extensions/workloads/pods/verify.go
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/prime/prime_test.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/upgrade/kubernetes_test.go

https://github.com/rancher/qa-tasks/issues/937
currently, validation only checks that once one pod is ready, that no others are in an error state. 
update the pod validation to validate that no pods are in an error state, and that all pods are healthy. 
locally on rke2, windows
* Unit
* None
_TODO_
* _TODO_

[2.8] requiring all healthy pods when deploying a cluster

---

tests/framework/extensions/charts/charts.go
tests/framework/extensions/clusters/clusterconfig.go
tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/ingresses/ingresses.go
tests/framework/extensions/machinepools/amazonec2_machine_config.go
tests/framework/extensions/provisioninginput/config.go
tests/framework/extensions/services/verify.go
tests/v2/validation/charts/istio.go
tests/v2/validation/charts/istio_test.go
tests/v2/validation/charts/monitoring.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/resources/out-of-tree/aws.yml
tests/v2/validation/upgrade/workload.go

https://github.com/rancher/qa-tasks/issues/936
https://github.com/rancher/rancher/issues/42749
There is currently no automation for cloud providers. 
This PR is addressing the recent upstream change to depreciate in-tree aws cloud provider, by automating the out-of-tree path for aws. 
introducing 
```
provisioningInput:
...
cloudProvider: "aws"
```
which follows [the new documentation](https://github.com/rancher/rancher-docs/pull/844/files#diff-4838044f24960fb879a1eec2cad40448fe714e9f963e569d6197799b52e7dc75L138) around adding an out-of-tree provider for aws
For this, we need the supporting aws field
```
awsMachineConfig:
...
iamInstanceProfile: <string>
...
```
tested locally, will get jenkins runs on request. 
* Unit
* …

[2.8] adding out-of-tree cloud provider automation support for aws during provisioning, RKE2

---

tests/v2prov/operations/etcdsnapshot.go

https://github.com/rancher/rancher/issues/42778
Provisioning operations tests were printing false failures even if the tests were succeeding
Set the dump variable to false if the test succeeds
Look at Drone logs
Summary: Modify v2prov integration test to disable test data collection/dumping if the test is successful
None

[release/v2.7] Stop printing debug data if etcd restore test succeeds

---

pkg/controllers/managementuser/pspdelete/pspdelete.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/clusterrole.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/deferred.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/namespace.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/podsecuritypolicy.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/serviceaccount.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version_test.go

When admins upgrade a downstream RKE2 cluster that has the PSP feature (version <1.25) to one that doesn't (version >=1.25) and still has a non-empty value for `defaultPodSecurityPolicyTemplateName` in cluster configuration, there are two issues.
1. Recurring controller failures to `list *v1beta1.PodSecurityPolicy: the server could not find the requested resource`.
2. Many handlers do not run - Rancher isn't creating LimitRanges in project namespaces that have container default limits, isn't creating v3.Tokens when users download their Kubeconfigs, and so on.
1. Fix the cluster version check for compatibility of remote clusters with PSPs. Make it return an error for clusters v1.25+ and whose version string has additional characters, like `v1.26.9+rke2r1`.
2. Ensure the `pspdelete` …

Fix cluster version check for PSP and use it in pspdelete controller registration for RKE2

---

tests/v2prov/operations/etcdsnapshot.go

https://github.com/rancher/rancher/issues/43509
Provisioning operations tests around etcd snapshots were printing false failures even if the tests were succeeding
Use `t.Failed()` to determine whether we should print debug data, as the debug dump is contained within a `defer` func.
Secondarily, change from using `logrus.Errorf` to `fmt.Printf` to print debug data as `logrus` was escaping the `\n` and performing weird formatting/wrapping with the base64gz blob. This brings the debug data printing in line with the rest of the tests that also potentially print debug logs.
Look at Drone logs
Summary: Modify v2prov integration test to disable test data collection/dumping if the test is successful
None

Stop printing debug data if etcd restore test succeeds

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

For https://github.com/rancher/rancher/issues/43624
Bump rke to v1.5.0-rc11
Go Mod treats `v1.5.0-rc11` as a lower version than `v1.5.0-rc9`, so the `replace` directive is necessary here to enforce the `v1.5.0-rc11` version of RKE is applied. 
The root cause is that we do not follow the Semantic Versioning Specification (SemVer) strictly when tagging versions in RKE: SemVer requires the pre-release identifier tp be dot-separated, such as `1.5.0-rc.11`, whereas ours is `v1.5.0-rc11`.  As a result, when Go Mod determines the precedence of `v1.5.0-rc9` and `v1.5.0-rc11`, it treats `rc9` and `rc11` as strings in which `rc11` is lower than `rc9`. 
**The `replace` directive can be dropped when we bump the version to the released one, ie. `v1.5.0`**

bump rke to v1.5.0-rc11

---

tests/framework/pkg/clientbase/ops.go

Backport
Currently, hosted cluster tests don't properly remove clusters in cloud providers because cloud credentials are deleted before other resources that need cloud credentials are removed.
Bypass deleting cloud credentials since they don't pose a significant load to Rancher

Bypass deleting cloud credential resources in validation tests backport

---

pkg/controllers/capr/machinenodelookup/controller.go
pkg/controllers/capr/machineprovision/args.go

https://github.com/rancher/rancher/issues/43511
The `providerID` field is set on an infrastructuremachine object after the node corresponding to the machine has successfully registered. If this field is set before the infrastructuremachine object ready condition is set to `True`, it can cause a re-run of the machine provision job that will error due the unrecognized argument.
Ignore the providerID field if it is set in the `InfrastructureMachine` spec.
I provisioned a vSphere cluster with this change.
* None
* If "None" - Reason: The existing machineprovision tests in the e2e framework should cover regression validation of the change
Summary: N/A
_TODO_
* _TODO_

[release/v2.7] Don't render providerID field into machine provision arguments

---

.drone.yml
tests/v2prov/tests/custom/operation_certificaterotation_test.go
tests/v2prov/tests/custom/operation_encryptionkeyrotation_test.go
tests/v2prov/tests/custom/operation_etcdsnapshot_inplace_test.go
tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_combined_test.go
tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_test.go
tests/v2prov/tests/machineprovisioning/operation_certificaterotation_test.go
tests/v2prov/tests/machineprovisioning/operation_encryptionkeyrotation_test.go
tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_inplace_test.go
tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_multietcd_test.go
tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_test.go

https://github.com/rancher/rancher/issues/43560
Due to bloat, the `provisioning-operations-tests-rke2` were frequently hitting the 1 hour mark for test run time.
Run the provisioned and custom tests in different pipelines.
Run in CI and ensure this passes within a reasonable amount of time >10 minutes, < 60 minutes
~Notably, until https://github.com/rancher/rancher/pull/43510 is merged, the tests will likely give "false positive" failures from the etcd operations tests. Ideally, we run the CI for this once the other PR is merged, or I can just meld the two PRs into one.~

[release/v2.8] Split provisioning-operations-tests-rke2

---

.drone.yml
tests/v2prov/tests/custom/operation_certificaterotation_test.go
tests/v2prov/tests/custom/operation_encryptionkeyrotation_test.go
tests/v2prov/tests/custom/operation_etcdsnapshot_inplace_test.go
tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_combined_test.go
tests/v2prov/tests/custom/operation_etcdsnapshot_newnode_test.go
tests/v2prov/tests/machineprovisioning/operation_certificaterotation_test.go
tests/v2prov/tests/machineprovisioning/operation_encryptionkeyrotation_test.go
tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_inplace_test.go
tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_multietcd_test.go
tests/v2prov/tests/machineprovisioning/operation_etcdsnapshot_newnode_test.go

https://github.com/rancher/rancher/issues/43560
Backport of https://github.com/rancher/rancher/pull/43625
Due to bloat, the `provisioning-operations-tests-rke2` were frequently hitting the 1 hour mark for test run time.
Run the provisioned and custom tests in different pipelines.
Run in CI and ensure this passes within a reasonable amount of time >10 minutes, < 60 minutes

[release/v2.7] Split provisioning-operations-tests-rke2

---

tests/framework/extensions/etcdsnapshot/config.go
tests/framework/extensions/etcdsnapshot/etcdsnapshot.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

This PR is another entry in the overall epic issue to add to the new etcd snapshot restore test suite. The test suite, currently, does not allow for customization of values when it comes to the upgrade strategy. This is the only entry where this problem exists as Kubernetes version and snapshot restore options are customizable.
Additionally, the RKE1 snapshots were referencing the incorrect function call. This was resulting in flaky behavior when running the snapshot restore for RKE1 clusters.
- Implemented customization for upgrade strategy values
- Fixed flakiness in RKE1 snapshots by calling the correct functions for etcd backup and etcd restore.
- Added customization to the amount of times the same snapshot is restored
Manually tested changing the concurrency values for K3S clusters …

[v2.8] Add upgrade strategy customization and fix RKE1 snapshots

---

tests/framework/clients/rancher/catalog/clusterrepo.go
tests/framework/extensions/charts/awsoutoftree.go
tests/framework/extensions/charts/charts.go
tests/framework/extensions/charts/payloads.go
tests/framework/extensions/charts/ranchergatekeeper.go
tests/framework/extensions/charts/rancheristio.go
tests/framework/extensions/charts/rancherlogging.go
tests/framework/extensions/charts/ranchermonitoring.go
tests/framework/extensions/charts/verify.go
tests/framework/extensions/clusters/clusterconfig.go
tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/defaults/defaults.go
tests/framework/extensions/provisioning/verify.go
tests/framework/extensions/provisioninginput/config.go
tests/framework/extensions/workloads/pods/pod_status.go
tests/v2/integration/catalogv2/rancher_managed_charts_test.go
tests/v2/integration/catalogv2/system_charts_version_test.go
tests/v2/validation/charts/gatekeeper_test.go
tests/v2/validation/charts/istio_test.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/charts/webhook_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/upgrade/workload_test.go

https://github.com/rancher/qa-tasks/issues/1030
out of tree requires chart(s) be installed post creation of a cluster. So simply setting the provider type for the cluster won't suffice. We must also add the charts repo, deploy the necessary charts, and finally do standard provider checks. 
* add logic for setting cloud provider in rke1 (This also opens the door for in-tree support, however this workflow has not been tested as thoroughly as it isn't the primary purpose of this ticket)
* add logic to install a repo and charts of a repo to the cluster as part of provisioning -- This should be considered part of provisioning because the cluster won't work properly when `external*` is set as the cloud provider, as nodes are tainted. 
* add logic to verify charts are installed
* plugin existing …

[2.8] add automation support for out-of-tree cloud provider testing with AWS RKE1

---

tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/defaults/defaults.go
tests/framework/extensions/kubeapi/rbac/create.go
tests/framework/extensions/kubeapi/rbac/delete.go
tests/framework/extensions/kubeapi/rbac/list.go
tests/framework/extensions/kubeapi/rbac/rbac.go
tests/framework/extensions/kubeapi/rbac/update.go
tests/v2/validation/rbac/globalrolesv2/README.md
tests/v2/validation/rbac/globalrolesv2/globalroles_v2.go
tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go

https://github.com/rancher/qa-tasks/issues/930
- Adding automated tests listed in the issue ^^ for **Global Roles v2** feature 
- Added few helper functions to list, create, update, delete RBAC resources (global roles, global role binding, cluster role template binding etc) using kube api 
- Added the following automated tests - [rancher/qa-tasks#930](https://github.com/rancher/qa-tasks/issues/930)
- Fresh install - Create custom roles and inherit the role[nested check]
- Update the existing user and add the global role
- Create a global role with multiple inheritedClusterRoles
- Fresh Install Create downstream clusters after the global role is added to user should list the clusters for the user
- Delete the inherited cluster role and verify all users should lose access and CRTBs should …

Global roles v2 feature tests

---

tests/framework/extensions/projects/projects.go
tests/framework/extensions/projects/template.go
tests/framework/extensions/rbac/config.go
tests/framework/extensions/rbac/verify.go
tests/v2/validation/rbac/README.md
tests/v2/validation/rbac/rbac_test.go

https://github.com/rancher/qa-tasks/issues/892
RBAC test suite needs modification so it is more easily readable and avoid confusions.
In this PR, we are making rbac tests run with two different input
1. Standard input: We only provide rancher server and cluster details, the tests will run for all the roles namely:
- cluster owner
- cluster member
- project owner
- project member
- restricted admin
2. User provided input: If users want to make use of an already created user, they would need to provide a single role and the tests are run only for the role provided.
Jenkins run

Refactoring RBAC

---

tests/framework/pkg/clientbase/ops.go

[link](https://github.com/rancher/rancher/pull/43374)
Currently, hosted cluster tests don't properly remove clusters in cloud providers because cloud credentials are deleted before other resources that need cloud credentials are removed.
Bypass deleting cloud credentials since they don't pose a significant load to Rancher

Bypass deleting cloud credential resources in validation tests

---

tests/validation/tests/rke/common.py

rke-support-matrix job was failing
https://github.com/rancher/qa-tasks/issues/1072
as of coreos/etcd:v1.5.7 (rke v1.5.0 bumped this from 1.5.6 -> 1.5.7), upstream switched to a distroless image. This greatly reduces the image size, however limits the functionality of the container to basically only etcd and etcdctl. 
change commands in rke standalone test to only use etcd / etcdctl instead of sh. 
local testing done

[2.8] removing sh exec due to distroless upstream

---

tests/validation/tests/v3_api/test_airgap.py

https://github.com/rancher/qa-tasks/issues/1050
docker container was failing. We have to currently manually add each minor release to the job.
remove the logic for special casing future versions. We never run airgap on 2.5 or below, so it doesn't make sense to keep that in. 
_TODO_
* _TODO_

[2.8] removing logic for 2.4 and below from docker airgap, adding 2.7+

---

tests/validation/tests/v3_api/test_airgap.py

backport https://github.com/rancher/rancher/pull/43554

[2.7] removing logic for 2.4 and below from docker airgap, adding 2.7+

---

package/Dockerfile
pkg/capr/installer/server_test.go
pkg/controllers/capr/bootstrap/controller_test.go
pkg/image/external/external.go
pkg/image/external/external_test.go
pkg/settings/setting.go
scripts/provisioning-tests
tests/v2/codecoverage/package/Dockerfile
tests/v2prov/operations/etcdsnapshot.go

https://github.com/rancher/rancher/issues/43658
During v2prov/CAPR day-2 operations, it is possible that the system-agent is restarted in the middle of applying a plan, which can lead to unexpected results.
Add interlocks to the system-agent to prevent it from restarting when the applyinator is active and stops the applyinator from applying if a restart is pending (to prevent a deadlock)
I performed manual testing in various scenarios to ensure the interlocks were working as expected, see the screenshot for example
* None
Summary: The existing integration tests test the change
_TODO_
* _TODO_

[release/v2.8] Bump rancher/system-agent to v0.3.5-rc1

---

tests/framework/clients/rancher/client.go
tests/framework/clients/rancher/v1/client.go
tests/framework/clients/rkecli/rkecli.go
tests/framework/clients/rkecli/state.go
tests/framework/extensions/clusters/bundledclusters/list.go
tests/framework/extensions/clusters/bundledclusters/update.go
tests/framework/extensions/clusters/clustermeta.go
tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/clusters/kubernetesversions/available.go
tests/framework/extensions/kubeapi/cluster/summary.go
tests/framework/pkg/config/config.go
tests/framework/pkg/config/file.go
tests/framework/pkg/file/file.go
tests/framework/pkg/nodes/nodes.go
tests/v2/validation/pipeline/downstreamcleanup/main.go
tests/v2/validation/pipeline/hapostinstall/main.go
tests/v2/validation/pipeline/releaseupgrade/main.go
tests/v2/validation/upgrade/config.go
tests/v2/validation/upgrade/kubernetes.go
tests/v2/validation/upgrade/kubernetes_test.go
tests/v2/validation/upgrade/workload_test.go

Currently imported clusters and local cluster upgrades tests happen manually.
Add local upgrade test case and expand existing upgrade Kubernetes validation test to enable testing on downstream imported clusters.
Existing / newly added automated tests that provide evidence there are no regressions: Runs will be provided offline.
Todos:

[2.7] Expand Kubernetes Upgrade Validation Tests for Local and Imported Clusters

---

tests/framework/clients/rancher/client.go
tests/framework/clients/rancher/v1/client.go
tests/framework/clients/rkecli/rkecli.go
tests/framework/clients/rkecli/state.go
tests/framework/extensions/clusters/bundledclusters/list.go
tests/framework/extensions/clusters/bundledclusters/update.go
tests/framework/extensions/clusters/clustermeta.go
tests/framework/extensions/clusters/clusters.go
tests/framework/extensions/clusters/kubernetesversions/available.go
tests/framework/extensions/kubeapi/cluster/summary.go
tests/framework/pkg/config/config.go
tests/framework/pkg/config/file.go
tests/framework/pkg/file/file.go
tests/framework/pkg/nodes/nodes.go
tests/v2/validation/pipeline/downstreamcleanup/main.go
tests/v2/validation/pipeline/hapostinstall/main.go
tests/v2/validation/pipeline/releaseupgrade/main.go
tests/v2/validation/upgrade/config.go
tests/v2/validation/upgrade/kubernetes.go
tests/v2/validation/upgrade/kubernetes_test.go
tests/v2/validation/upgrade/workload_test.go

Currently imported clusters and local cluster upgrades tests happen manually.
Add local upgrade test case and expand existing upgrade Kubernetes validation test to enable testing on downstream imported clusters.
Existing / newly added automated tests that provide evidence there are no regressions: Runs will be provided offline.
Todos:

[2.8] Expand Kubernetes Upgrade Validation Tests for Local and Imported Clusters

---

README-template.md

A user opened an issue on rancher/rancher pointing out that the Rancher v2.8 README contained an incorrect link to the docs installation page. The issue was transferred over to the docs repo. I initially opened a PR correcting the rancher/rancher README. However, the rancher/rancher README is actually generated from the file, README-template.md, and README-template.md contains several other broken links. 
Correcting links to point to the v2.8 docs site, https://ranchermanager.docs.rancher.com/v2.8 
* Unit
* None
* If "None" - GH Issue/PR: _LINK TO GH …

The README-template links to the docs site are broken

---

pkg/auth/providers/oidc/oidc_client.go
pkg/auth/providers/oidc/oidc_client_test.go

When connecting Rancher to an auth provider such as keycloak, there were a few issues.
1. The oidc client does not use certificates provided via `tls-ca` or `tls-ca-additional` secrets.
2. The client certificate provided in the UI must also contain the specific CA that signed the server cert for the auth provider.
To verify this, you can
1. Create a CA and an Intermediate CA
2. Sign a server cert with the Intermediate CA
3. Sign a client cert with either CA
4. Use that server cert with something like Keycloak
5. Configure a X509 browser flow with Keycloak for PKI auth
6. Install Rancher using `privateCA: true`
7. Connect Rancher with Keycloak using the client cert and key
In this scenario, connecting Rancher to Keycloak for auth delegation will fail **unless** you also provide the …

Use provided CAs for oidc client connections

---

pkg/agent/clean/adunmigration/ldap.go
pkg/agent/clean/adunmigration/ldap_test.go
pkg/agent/clean/adunmigration/migrate.go
pkg/agent/clean/adunmigration/migrate_test.go
pkg/agent/clean/adunmigration/rtbs.go
pkg/agent/clean/adunmigration/rtbs_test.go
pkg/agent/clean/adunmigration/tokens.go
pkg/agent/clean/adunmigration/tokens_test.go
pkg/agent/clean/adunmigration/users_test.go

When we originally merged in the uuid-unmigration, unit test writing was deferred so we could get the fix out to affected users more quickly. These are those tests.
I realized that the *RTB functions were accepting the full shared context, making them reliant on Rancher infrastructure that is somewhat tricky to mock. I reworked these functions to accept the list of prefetched resources instead, making them stateless and simpler to test.
Since I wanted to test reporting logic related to missing and skipped users, I wrapped the LDAP retry logic into a small interface and reworked the migration code accordingly. This setup makes it simpler to mock for error injection.
Within `pkg/agent/clean/adunmigration` the following functions are now covered by the new tests:
escapeUUID and isGUID …

Add unit tests for GUID unmigration

---

tests/v2prov/operations/etcdsnapshot.go

Issue: https://github.com/rancher/rancher/issues/43658
Continuation of https://github.com/rancher/rancher/pull/43776 
While attempting to backport the original commit to release/v2.7, a fix was needed to be added to `release/v2.7`: https://github.com/rancher/rancher/pull/43789
Synchronize `release/v2.7` and `release/v2.8` tests so that they do not deviate and lead to different results.

[release/v2.8] [v2.7 forwardport] check that snapshot creation time is not nil

---

package/Dockerfile
pkg/capr/installer/server_test.go
pkg/controllers/capr/bootstrap/controller_test.go
pkg/image/external/external.go
pkg/image/external/external_test.go
pkg/settings/setting.go
scripts/provisioning-tests
tests/v2/codecoverage/package/Dockerfile
tests/v2prov/operations/etcdsnapshot.go

https://github.com/rancher/rancher/issues/43784
https://github.com/rancher/rancher/issues/43658
During v2prov/CAPR day-2 operations, it is possible that the system-agent is restarted in the middle of applying a plan, which can lead to unexpected results.
Add interlocks to the system-agent to prevent it from restarting when the applyinator is active and stops the applyinator from applying if a restart is pending (to prevent a deadlock)
I performed manual testing in various scenarios to ensure the interlocks were working as expected, see the screenshot for example
* None
Summary: The existing integration tests test the change
_TODO_
* _TODO_

[Backport v2.7] Bump rancher/system-agent to v0.3.5-rc1

---

pkg/controllers/capr/machinenodelookup/controller.go
pkg/controllers/capr/machineprovision/args.go

https://github.com/rancher/rancher/issues/43505
The `providerID` field is set on an infrastructuremachine object after the node corresponding to the machine has successfully registered. If this field is set before the infrastructuremachine object ready condition is set to `True`, it can cause a re-run of the machine provision job that will error due the unrecognized argument.
Ignore the providerID field if it is set in the `InfrastructureMachine` spec.
I provisioned a vSphere cluster with this change.
* None
* If "None" - Reason: The existing machineprovision tests in the e2e framework should cover regression validation of the change
Summary: N/A
_TODO_
* _TODO_

[release/v2.8] Don't render providerID field into machine provision arguments

---

pkg/controllers/capr/machinenodelookup/controller.go
pkg/controllers/capr/machineprovision/args.go

https://github.com/rancher/rancher/issues/43505
The `providerID` field is set on an infrastructuremachine object after the node corresponding to the machine has successfully registered. If this field is set before the infrastructuremachine object ready condition is set to `True`, it can cause a re-run of the machine provision job that will error due the unrecognized argument.
Ignore the providerID field if it is set in the `InfrastructureMachine` spec.
I provisioned a vSphere cluster with this change.
* None
* If "None" - Reason: The existing machineprovision tests in the e2e framework should cover regression validation of the change
Summary: N/A
_TODO_
* _TODO_

[Forwardport release/v2.9] Don't render providerID field into machine provision arguments

---

generate.go
scripts/build-crds

Github action UI automatically classifies lines containing the string `errors` as an error with the action even if the return code is 0.
Suppress the messages of expected errors during go generate.
None

Adds the ability to supress crd-gen output.

---

tests/validation/tests/v3_api/test_ebs_volume_backed_instance.py

After the pytest bump, the below error was introduced while running the Python validation tests:
```
11:08:08.491  tests/v3_api/test_ebs_volume_backed_instance.py:71: in <module>
11:08:08.491      ???
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1333: in fixture
11:08:08.492      return fixture_marker(fixture_function)
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1210: in __call__
11:08:08.492      function = wrap_function_to_error_out_if_called_directly(function, self)
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1172: in wrap_function_to_error_out_if_called_directly
11:08:08.492      ).format(name=fixture_marker.name or function.__name__)
11:08:08.492  E   AttributeError: 'str' object has no attribute …
```

[2.9] Update Fixture Changes in the Validation Tests

---

tests/validation/tests/v3_api/test_ebs_volume_backed_instance.py

After the pytest bump, the below error was introduced while running the Python validation tests:
```
11:08:08.491  tests/v3_api/test_ebs_volume_backed_instance.py:71: in <module>
11:08:08.491      ???
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1333: in fixture
11:08:08.492      return fixture_marker(fixture_function)
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1210: in __call__
11:08:08.492      function = wrap_function_to_error_out_if_called_directly(function, self)
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1172: in wrap_function_to_error_out_if_called_directly
11:08:08.492      ).format(name=fixture_marker.name or function.__name__)
11:08:08.492  E   AttributeError: 'str' object has no attribute …
```

[2.8] Update Fixture Changes in the Validation Tests

---

tests/validation/tests/v3_api/test_ebs_volume_backed_instance.py

After the pytest bump, the below error was introduced while running the Python validation tests:
```
11:08:08.491  tests/v3_api/test_ebs_volume_backed_instance.py:71: in <module>
11:08:08.491      ???
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1333: in fixture
11:08:08.492      return fixture_marker(fixture_function)
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1210: in __call__
11:08:08.492      function = wrap_function_to_error_out_if_called_directly(function, self)
11:08:08.492  /usr/local/lib/python3.11/site-packages/_pytest/fixtures.py:1172: in wrap_function_to_error_out_if_called_directly
11:08:08.492      ).format(name=fixture_marker.name or function.__name__)
11:08:08.492  E   AttributeError: 'str' object has no attribute …
```

[2.7] Update Fixture Changes in the Validation Tests

---

tests/v2/validation/rbac/crtb/README.md
tests/v2/validation/rbac/crtb/crtb_create_steve_test.go
tests/v2/validation/rbac/crtb/crtb_steve.go

**Issue:**
https://github.com/rancher/qa-tasks/issues/922
**Problem**
Create automation tests for ClusterRoleTemplateBindings(CRTB) by using Steve endpoint, we do not have tests earlier.
**Solution**
Create automation tests for ClusterRoleTemplateBindings(CRTB) by using Steve endpoint
**Validate Test cases:**
POST -- Success
POST-- Errors
Testing
Validate Test cases:
POST -- Success
POST-- Errors

[v2.9] Added CRTB create test cases by using SteveAPI

---

tests/v2/validation/rbac/crtb/README.md
tests/v2/validation/rbac/crtb/crtb_create_steve_test.go
tests/v2/validation/rbac/crtb/crtb_steve.go

https://github.com/rancher/qa-tasks/issues/922
Create automation tests for ClusterRoleTemplateBindings(CRTB) by using Steve endpoint, we do not have tests earlier.
Create automation tests for ClusterRoleTemplateBindings(CRTB) by using Steve endpoint
Validate Test cases:
1. POST -- Success
2. POST-- Errors
Validate Test cases:
1. POST -- Success
2. POST-- Errors

[v2.8] Backport Added CRTB create test cases by using SteveAPI

---

pkg/settings/setting.go

`v2.9-head` builds currently serve up `release.2.8.0` instead of 2.9
Change CDN links to point to builds created from `master` (which tracks 2.9)
Both links are in use in local dev system

Update references to 2.9 UI builds 

---

.github/renovate.json

The changes will force renovate to only consider `release/v2.9` going forward.

build: Set renovate base branch to v2.9

---

pkg/image/extensions.go
pkg/image/extensions_test.go
pkg/image/resolve.go
pkg/image/resolve_test.go
pkg/image/utilities/utilities.go

fixes https://github.com/rancher/rancher/issues/43779
The [GetImages](https://github.com/rancher/rancher/blob/release/v2.9/pkg/image/resolve.go#L64) func is indirectly being called by a codebase in the catalogv1 package in airgap scenario.
[GetImages](https://github.com/rancher/rancher/blob/release/v2.9/pkg/image/resolve.go#L64) =>calls=> [AddImagesToImageListConfigMap](https://github.com/rancher/rancher/blob/release/v2.9/pkg/image/resolve.go#L109) =>calls=>[CatalogV1 Package](https://github.com/rancher/rancher/blob/release/v2.9/pkg/catalog/manager/catalog_sync.go#L123)
The [GetImages](https://github.com/rancher/rancher/blob/release/v2.9/pkg/image/resolve.go#L64) func is also called by [utility package](https://github.com/rancher/rancher/blob/release/v2.9/pkg/image/utilities/utilities.go#L …

Align image collection of extensions with existing pattern

---

pkg/image/extensions.go
pkg/image/extensions_test.go
pkg/image/resolve.go
pkg/image/resolve_test.go
pkg/image/utilities/utilities.go

Cherry-pick backport of https://github.com/rancher/rancher/pull/43825, see details in the linked PR.

[v2.8.1] Align image collection of extensions with existing pattern

---

chart/templates/configMap.yaml
chart/tests/configmap_test.yaml
chart/values.yaml
pkg/controllers/dashboard/fleetcharts/controller.go
pkg/controllers/dashboard/fleetcharts/controller_test.go

Currently Rancher installs Fleet with fixed values (see https://github.com/rancher/rancher/blob/9c5a25675676b680898f933681abde88f53dba95/pkg/controllers/dashboard/fleetcharts/controller.go#L89-L100), making the solution less flexible than Fleet standalone cases.
These changes allow Rancher users to specify additional arbitrary values for the Fleet chart, so that their Fleet installation can be customized flexibly, by adding a new `fleet` entry to the `rancher-config` ConfigMap.
This is particularly useful as a catch-all measure when assisting customers to introduce Fleet-specific experimental tuning settings, debug settings, etc. even if they are not yet covered by the Rancher UI.
A new unit tests have been added for the chart and relevant code.
1. I built the `rancher` image pushed it to …

Make Fleet helm chart values configurable

---

pkg/controllers/dashboardapi/settings/settings.go
pkg/controllers/dashboardapi/settings/settings_test.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/43103
When a deprecated setting is removed from the codebase the corresponding `Setting` resource is left behind in the cluster. We would like to clean up such orphaned setting resources on Rancher startup and potentially prevent creating custom setting resources via the webhook.
On Rancher startup we list all the setting resources in the cluster and mark all unknown/unrecognized (e.g. deprecated) settings with a label. In a future release e.g. 2.9 we'll be removing them instead. This gives an opportunity to someone who used setting resources, e.g. for integration purposes, to transition to something else.
Migrate from 2.7 to 2.8+, and run Rancher which should lead to some deprecated/removed and any custom settings being marked as unknown e.g. …

Label unknown/deprecated settings on startup

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/providers/oidc/oidc_provider.go

https://github.com/rancher/rancher/issues/43668
There is a typo in the type declaration
```golang
type OIDCConfig struct {
// ...
Scopes             string `json:"scope", norman:"required,notnullable"`
//                                     ^
//...
}
```
Tags shouldn't be separated by a comma.
```
struct field tag `json:"scope", norman:"required,notnullable"` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spacesstructtag[default](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/structtag)
```
And another one
```golang
type ClaimInfo struct {
// ...
PreferredUsername string   `json:preferred_username`
GivenName         string   `json:given_name`
FamilyName        string   `json:family_name`
// ...
}
```
Missing double quotes around the field names. …

Fix OIDCConfig.Scopes struct field tag

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
pkg/client/generated/management/v3/zz_generated_global_role.go
pkg/controllers/management/auth/globalroles/enqueue.go
pkg/controllers/management/auth/globalroles/enqueue_test.go
pkg/controllers/management/auth/globalroles/globalrole_handler.go
pkg/controllers/management/auth/globalroles/globalrole_handler_test.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go
pkg/controllers/management/auth/globalroles/register.go
pkg/crds/yaml/generated/management.cattle.io_globalroles.yaml
tests/framework/clients/rancher/generated/management/v3/zz_generated_global_role.go

Adds `NamespacedRules` to the GlobalRole field. Details of the field can be found in the issue, but in summation: 
- When a global role (GR) is created, a role is created in each namespace with the listed rules
- When a global role binding (GRB) is created, a role binding is created in each namespace that binds to the namespaced roles
- When the role/role binding is modified, it checks if it's owned by a GR/GRB and then enqueues it to be verified
The work is split in the following commits:
1. Add the NamespacedRules field
2. Add GRB support
3. Add GR support
4. Add enqueueing
1. Create a GlobalRole with the new NamespacedRules field
- It creates Roles based on the NamespacedRules
2. Create a GlobalRoleBinding with the above GlobalRole
- It creates RoleBindings based on the NamespacedRules …

Adding NamespacedRules and handling to GR/GRB

---

tests/v2/validation/Dockerfile.validation
tests/validation/Dockerfile.v3api
tests/validation/tests/v3_api/test_airgap_ha.py

https://github.com/rancher/qa-tasks/issues/1097
the ha airgap job started failing, and would not finish bringing up the airgapped environment.,
Further investigation shows that the python:3.11 dependency was updated in the upstream docker package, and now scp complains when the trailing `/` is included in the command. 
removed the `/` from the `basic-registry` scp lines. 
also addressing some Dockerfile issues with VPN to unblock some vsphere testing. 
tested using jenkins freeform job, and is getting past this step now.

[2.8] fix airgap automation for python framework

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

This PR helps solve, at least partially, https://github.com/rancher/rancher/issues/43065.
Change in `package/Dockerfile` and `tests/v2/codecoverage/package/Dockerfile` a total of 06 `git clone` operations done against `git.rancher.io` that might fail intermittently due to 502 errors in `git.rancher.io` backend. The operations are now done against the main repos in `github.com` during only the Dockerfile build process, and then it changes the `origin` URL back to `git.rancher.io` to avoid possible problems during Rancher's runtime execution. It's expected that this will help reduce a portion of the unnecessary load in `git.rancher.io` due to all the running PRs that will stop pulling directly from it.
Note: this doesn't change the URL inside Rancher's Go code. This can be done later and …

[release/v2.9] Change `git.rancher.io` clone to `github.com` repos only during Dockerfile build

---

Dockerfile.dapper

Installing via pip installs the newest released version as 'root' user, which can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead, "--user", or simply use the SUSE maintained system package instead.
The root cause here is duplicating the packages that are installed system wide via package manager with the ones installed system wide via pip. These meshups are hard to predict and might lead to breakage (as seen in the SLE BCI integration tests that is trying to build rancher). 
The solution is to install the python ecosystem from a single vendor.

[2.9] Use SLE maintained tox version for integration tests

---

Dockerfile.dapper

Installing via pip installs the newest released version as 'root' user, which can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead, "--user", or simply use the SUSE maintained system package instead.
The root cause here is duplicating the packages that are installed system wide via package manager with the ones installed system wide via pip. These meshups are hard to predict and might lead to breakage (as seen in the SLE BCI integration tests that is trying to build rancher).
The solution is to install the python ecosystem from a single vendor.
- GH Issue/PR: https://github.com/rancher/rancher/pull/43868

[2.8] Use SLE maintained tox version for integration tests

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Backport https://github.com/rancher/rancher/pull/43698 and https://github.com/rancher/rancher/pull/43846.

[release/v2.8.1] Change `git.rancher.io` clone to `github.com` only during image build

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Backport https://github.com/rancher/rancher/pull/43698
This PR helps solve, at least partially, https://github.com/rancher/rancher/issues/43065.
Change in `package/Dockerfile` and `tests/v2/codecoverage/package/Dockerfile` a total of 06 `git clone` operations done against `git.rancher.io` that might fail intermittently due to 502 errors in `git.rancher.io` backend. The operations are now done against the main repos in `github.com` during only the Dockerfile build process, and then it changes the `origin` URL back to `git.rancher.io` to avoid possible problems during Rancher's runtime execution. It's expected that this will help reduce a portion of the unnecessary load in `git.rancher.io` due to all the running PRs that will stop pulling directly from it.
Note: this doesn't change the URL …

[release/v2.7] Change `git.rancher.io` clone to `github.com` repos only during Dockerfile build

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

This PR helps solve, at least partially, https://github.com/rancher/rancher/issues/43065.
Change in `package/Dockerfile` and `tests/v2/codecoverage/package/Dockerfile` a total of 06 `git clone` operations done against `git.rancher.io` that might fail intermittently due to 502 errors in `git.rancher.io` backend. The operations are now done against the main repos in `github.com` during only the Dockerfile build process, and then it changes the `origin` URL back to `git.rancher.io` to avoid possible problems during Rancher's runtime execution. It's expected that this will help reduce a portion of the unnecessary load in `git.rancher.io` due to all the running PRs that will stop pulling directly from it.
Note: this doesn't change the URL inside Rancher's Go code. This can be done later and …

[release/v2.8] Change `git.rancher.io` clone to `github.com` repos only during Dockerfile build

---

Dockerfile.dapper

Installing via pip installs the newest released version as 'root' user, which can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead, "--user", or simply use the SUSE maintained system package instead.
Installing via pip installs the newest released version as 'root' user, which can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead, "--user", or simply use the SUSE maintained system package instead.
The solution is to install the python ecosystem from a single vendor.
- GH Issue/PR: https://github.com/rancher/rancher/pull/43868

[2.7] Use SLE maintained tox version for integration tests

---

tests/validation/lib/aws.py

airgap isn't airgapped; aws recently set ipv6 to enabled by default, which broke our airgap which didn't explicitly set it to off
disable ipv6 if pubic_ip is disabled

[2.9] update legacy framework to override ipv6 default

---

pkg/provisioningv2/kubeconfig/manager.go
pkg/provisioningv2/kubeconfig/manager_test.go
pkg/rancher/migrations.go

If we upgrade to use CAPI 1.5.0 or higher its required that the secrets used for kubeconfigs contain a label `cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}`. Without this, the CAPI cluster/machine reconcilers will fail with a `failed to retrieve kubeconfig secret for Cluster` error.
See the CAPI migration guide: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md#other
This adds the required label when we create the secret that contains the kubeconfig. A migration has also been added thats called at startup (on leader election) that will add the label to any kubeconfig secret for an RKE2 cluster.
Even though 1.4.4 will be used with the un-embedding it would be good to get this change in upfront.
1. Create an RKE2 based …

[v2.8] feat: added capi label to kubeconfig secrets

---

pkg/provisioningv2/kubeconfig/manager.go
pkg/provisioningv2/kubeconfig/manager_test.go
pkg/rancher/migrations.go

> This is a forward port of #42406
If we upgrade to use CAPI 1.5.0 or higher its required that the secrets used for kubeconfigs contain a label cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}. Without this, the CAPI cluster/machine reconcilers will fail with a failed to retrieve kubeconfig secret for Cluster error.
See the CAPI migration guide: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md#other
This adds the required label when we create the secret that contains the kubeconfig. A migration has also been added thats called at startup (on leader election) that will add the label to any kubeconfig secret for an RKE2 cluster.
Even though 1.4.4 will be used with the un-embedding it would be good to get this change in …

[v2.9] feat: added capi label to kubeconfig secrets

---

pkg/settings/setting.go

`v2.8-head` builds currently serve up `release.2.8.0` instead of 2.8 latest
Change CDN links to point to builds created from `release.2.8` (which tracks 2.8 latest)
Both links are in use in local dev system

Update references to 2.8 UI builds

---

tests/validation/tests/v3_api/test_custom_host_reg.py

rancher/rancher repository and image has been hardcoded in our automation tests. Adding a new param so we can change the values. If no value is provided rancher/rancher will be taken as default

Adding repository and image as a param

---

build.yaml
pkg/buildconfig/constants.go
tests/v2/codecoverage/package/Dockerfile.agent

Updating to the latest chart: https://github.com/rancher/charts/pull/3351

bump rancher-webhook to v0.5.0-rc2

---

tests/validation/tests/v3_api/test_create_ha.py

Updating extra settings in install_rancher to be an empty list as for test_upgrade_rancher_ha when extra settings are passed, since it is defined as None, appending helm settings errors out with `'NoneType' object has no attribute 'append'`

Passing empty list for extra settings

---

pkg/api/steve/catalog/content.go
pkg/catalogv2/content/content.go
pkg/catalogv2/content/content_test.go
pkg/catalogv2/git/content.go
pkg/catalogv2/git/download.go
pkg/catalogv2/git/index.go
pkg/catalogv2/git/utils.go
pkg/catalogv2/git/utils_test.go
scripts/package
scripts/package-env
tests/framework/clients/rancher/catalog/clusterrepo.go
tests/v2/integration/catalogv2/rancher_managed_charts_test.go

This PR will solve these issues: 
- https://github.com/rancher/rancher/issues/41765
- https://github.com/rancher/rancher/issues/41603
Rancher when operating at airgap mode with bundled catalogs is still trying to get the logos of the charts from the internet.
This will be a 2 step solution, this PR aims to implement the 1st one
The 1st solution only fixes the 2 above-mentioned issues.
The 2nd solution will ensure a better user experience even when in air-gapped mode by providing all logos locally.
1. Detect when in Bundled Mode (Airgapped environment), 
2. Try to get the image from the local bundled repository, 
3. if not possible just return a `nil chart` with a `nil error` that will trigger the generic catalog image from the default directory on the front end. 
4. Update `git.Icon` …

Icons airgap fetching the internet

---

pkg/api/steve/catalog/content.go
pkg/catalogv2/content/content.go
pkg/catalogv2/content/content_test.go
pkg/catalogv2/git/content.go
pkg/catalogv2/git/download.go
pkg/catalogv2/git/index.go
pkg/catalogv2/git/utils.go
pkg/catalogv2/git/utils_test.go
scripts/package
scripts/package-env
tests/framework/clients/rancher/catalog/clusterrepo.go
tests/v2/integration/catalogv2/rancher_managed_charts_test.go

This PR will solve these issues: 
- https://github.com/rancher/rancher/issues/44148
Rancher when operating at airgap mode with bundled catalogs is still trying to get the logos of the charts from the internet.
This will be a 2 step solution, this PR aims to implement the 1st one
The 1st solution only fixes the 2 above-mentioned issues.
The 2nd solution will ensure a better user experience even when in air-gapped mode by providing all logos locally.
1. Detect when in Bundled Mode (Airgapped environment), 
2. Try to get the image from the local bundled repository, 
3. if not possible just return a `nil chart` with a `nil error` that will trigger the generic catalog image from the default directory on the front end. 
4. Update `git.Icon` function to work with `index.yaml > icon(field): …

Icons airgap [Forwardport from 2.8 to v2.9]

---

pkg/data/dashboard/repo.go
pkg/settings/setting.go

Testing any system chart against Rancher requires following one of these methods:
* using a custom `rancher/charts` branch to be specified in `CATTLE_CHART_DEFAULT_BRANCH`, which would end up polluting `rancher/charts` with test branches
* using airgap mode ("bundled") and building a [custom repository](https://github.com/rancher/rancher/pull/41523/commits/1aaba7da2187cec6301e7fe11891571558241771) to install a specific version of a Helm chart, which in turn requires running Rancher outside of a cluster or `ADD`ing that custom repository over the [clone in the rancher/rancher image](https://github.com/rancher/rancher/blob/e5deaaf81f8af41a1219d3470a0876d384119386/package/Dockerfile#L64C1-L74)
* adding another layer to the Rancher image, which contains our bundled system chart version in the …

Add charts url setting

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

https://github.com/rancher/rancher/issues/44195
Integration tests for Serving Icons under Mapps was relying on a few charts based on `rancher/charts`, someone made a mistake while updating some of the charts and updated the icons field with an image that does not exist in the repository. 
Switch to only using `rancher/charts-small-fork` for having the same structure of `rancher/charts` to test but in a controlled environment.

fixing by testing only small fork

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

https://github.com/rancher/rancher/issues/44195
Integration tests for Serving Icons under Mapps were relying on a few charts based on `rancher/charts`, someone made a mistake while updating some of the charts and updated the icons field with an image that does not exist in the repository. 
Switch to only using `rancher/charts-small-fork` for having the same structure of `rancher/charts` to test but in a controlled environment.

fixing by testing only small fork - [Forwardport to 2.9] 

---

pkg/controllers/managementuser/pspdelete/pspdelete.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/clusterrole.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/deferred.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/namespace.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/podsecuritypolicy.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/serviceaccount.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version_test.go

Forward port https://github.com/rancher/rancher/pull/43201 from 2.7.
https://github.com/rancher/rancher/issues/43864

[2.9 forwardport] Fix cluster version check for PSP and use it in pspdelete controller registration for RKE2

---

pkg/controllers/management/eks/eks_cluster_handler.go

After merging https://github.com/rancher/rancher/pull/43881, imported EKS clusters without managed node groups no longer cause an error as long as the agent is installed in a self-managed node. The error message when the cluster has zero nodes (either managed or self-managed) is still the same and not aligned with the requirements.
The error message is updated to include self-managed nodes as a valid compute option.
* Unit
* None
_TODO_
Existing / newly added automated tests that …

[v2.8] chore: improve error message when eks cluster does not have nodes

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

From the linked PR: 
Change in package/Dockerfile and tests/v2/codecoverage/package/Dockerfile a total of 06 git clone operations done against git.rancher.io that might fail intermittently due to 502 errors in git.rancher.io backend. The operations are now done against the main repos in github.com during only the Dockerfile build process, and then it changes the origin URL back to git.rancher.io to avoid possible problems during Rancher's runtime execution. It's expected that this will help reduce a portion of the unnecessary load in git.rancher.io due to all the running PRs that will stop pulling directly from it.
Note: this doesn't change the URL inside Rancher's Go code. This can be done later and might require some extra logic.
Existing / newly added automated tests that provide …

Backport #43700

---

go.mod
go.sum

This PR contains an update to containerd. It is the latest 1.6.x patch release which contains a security fix.
This update has a fix for security issue https://github.com/advisories/GHSA-7ww5-4wqc-m92c. 1.6.x is an LTS supported version of containerd and this should be compatible with docker 20.10.x.
Note, github.com/microsoft/hcsshim had to be upgraded to support this version of containerd

Updating containerd package to the latest 1.6.x

---

pkg/cluster/private_registry.go
pkg/cluster/private_registry_test.go

Backport Issue rancher/rancher#42044 
Backport PR rancher/rancher#42069 
Generating a private registry `.dockerconfigjson` used URL encoding instead of standard b64 encoding.
Use standard encoding.
* Unit
Summary: Updated existing unit tests to confirm expected config
Test system default registries and cluster private registries
Regressions should be unlikely, either private registries work or they don't.
Covered by existing private registry automation tests

Update dockerconfigjson to use base64 StdEncoding

---

pkg/controllers/capr/machinenodelookup/controller.go
pkg/controllers/capr/machineprovision/args.go

https://github.com/rancher/rancher/issues/44198
https://github.com/rancher/rancher/issues/43505
https://github.com/rancher/rancher/issues/43511
https://github.com/rancher/rancher/pull/43512
The `providerID` field is set on an infrastructuremachine object after the node corresponding to the machine has successfully registered. If this field is set before the infrastructuremachine object ready condition is set to `True`, it can cause a re-run of the machine provision job that will error due the unrecognized argument.
Ignore the providerID field if it is set in the `InfrastructureMachine` spec.
I provisioned a vSphere cluster with this change.
In order to specifically exasperate this issue, I had to create a patched version of `rancher-machine` that introduces a 5 minute delay to vSphere …

[Backport v2.7.11] Don't render providerID field into machine provision arguments

---

scripts/chart/promote-to-stable.sh

https://github.com/rancher/rancher/issues/44267
The script `promote-to-stable.sh` errors out like the below:
```
./scripts/chart/promote-to-stable.sh v2.8.1
2024/01/31 10:25:51 proto: duplicate proto type registered: PluginSpec
2024/01/31 10:25:51 proto: duplicate proto type registered: PluginPrivilege
drone version 1.7.0
2024/01/31 10:25:51 proto: duplicate proto type registered: PluginSpec
2024/01/31 10:25:51 proto: duplicate proto type registered: PluginPrivilege
No Build Found for TAG: v2.8.1
```
It happens because the output of the 'drone build ls' command is paged, and `promote-to-stable.sh` does not handle the paging so it checks only the 1st page.  
Add the logic for  handling the paging, which has been implemented in the …

fix the issue that the promote-to-stable script can not find the target build number

---

package/Dockerfile
pkg/capr/installer/server_test.go
pkg/controllers/capr/bootstrap/controller_test.go
pkg/image/external/external.go
pkg/image/external/external_test.go
pkg/settings/setting.go
scripts/provisioning-tests
tests/v2/codecoverage/package/Dockerfile
tests/v2prov/operations/etcdsnapshot.go

https://github.com/rancher/rancher/issues/44199
https://github.com/rancher/rancher/issues/43658
https://github.com/rancher/rancher/issues/43784
https://github.com/rancher/rancher/pull/43789
During v2prov/CAPR day-2 operations, it is possible that the system-agent is restarted in the middle of applying a plan, which can lead to unexpected results.
Add interlocks to the system-agent to prevent it from restarting when the applyinator is active and stops the applyinator from applying if a restart is pending (to prevent a deadlock)
I performed manual testing in various scenarios to ensure the interlocks were working as expected, see the screenshot for example
* None
Summary: The existing integration tests test the change
No known areas of potential regression. …

[Backport v2.7.11] Bump rancher/system-agent to v0.3.5-rc1

---

package/Dockerfile

Support for k8s 1.27
-  Built the rancher image locally with the changes that support k8s 1.27 and installed this on EKS K8s 1.27 cluster
-  Install this version (2.0.3+up2.0.3-rc1) of the rancher-csp-adapter on an EKS Kubernetes (K8s) 1.27 cluster.
-  Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. When the downstream cluster was destroyed, validate that the out-of-compliance message is no longer displayed.
-  Validate support config

Bump csp adapter to 2.0.3-rc1

---

pkg/capr/planner/etcdrestore.go
pkg/capr/planner/etcdrestore_test.go

Original PR: https://github.com/rancher/rancher/pull/43005
When force deleting etcd machines by applying the capi `"machine.cluster.x-k8s.io/exclude-node-draining"` annotation, the annotations map may be nil.
Check if nil before assignment, and initialize if nil.
Added extensive unit testing
* Unit
Summary: Added unit tests for every code path in the function.
Test P0 etcd restore use cases
Shouldn't be any regressions, etcd restore should just work.
* Added unit tests

[V2.7.11] Fix panic in etcd restore

---

pkg/controllers/managementuser/pspdelete/pspdelete.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/binding.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/cluster.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/clusterrole.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/deferred.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/namespace.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/podsecuritypolicy.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/serviceaccount.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/template.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version.go
pkg/controllers/managementuser/rbac/podsecuritypolicy/version_test.go

Forward port https://github.com/rancher/rancher/pull/43201 from 2.7.
https://github.com/rancher/rancher/issues/43351

[2.8 forwardport] Fix cluster version check for PSP and use it in pspdelete controller registration for RKE2

---

pkg/agent/clean/adunmigration/ldap.go
pkg/agent/clean/adunmigration/ldap_test.go
pkg/agent/clean/adunmigration/migrate.go
pkg/agent/clean/adunmigration/migrate_test.go
pkg/agent/clean/adunmigration/rtbs.go
pkg/agent/clean/adunmigration/rtbs_test.go
pkg/agent/clean/adunmigration/tokens.go
pkg/agent/clean/adunmigration/tokens_test.go
pkg/agent/clean/adunmigration/users_test.go

Note: This is a forward port of https://github.com/rancher/rancher/pull/43734
When we originally merged in the uuid-unmigration, unit test writing was deferred so we could get the fix out to affected users more quickly. These are those tests.
I realized that the *RTB functions were accepting the full shared context, making them reliant on Rancher infrastructure that is somewhat tricky to mock. I reworked these functions to accept the list of prefetched resources instead, making them stateless and simpler to test.
Since I wanted to test reporting logic related to missing and skipped users, I wrapped the LDAP retry logic into a small interface and reworked the migration code accordingly. This setup makes it simpler to mock for error injection.
Within `pkg/agent/clean/adunmigration` the …

[Forwardport 2.8] Add unit tests for GUID unmigration

---

pkg/agent/clean/adunmigration/ldap.go
pkg/agent/clean/adunmigration/ldap_test.go
pkg/agent/clean/adunmigration/migrate.go
pkg/agent/clean/adunmigration/migrate_test.go
pkg/agent/clean/adunmigration/rtbs.go
pkg/agent/clean/adunmigration/rtbs_test.go
pkg/agent/clean/adunmigration/tokens.go
pkg/agent/clean/adunmigration/tokens_test.go
pkg/agent/clean/adunmigration/users_test.go

Note: This is a forward port of https://github.com/rancher/rancher/pull/43734
When we originally merged in the uuid-unmigration, unit test writing was deferred so we could get the fix out to affected users more quickly. These are those tests.
I realized that the *RTB functions were accepting the full shared context, making them reliant on Rancher infrastructure that is somewhat tricky to mock. I reworked these functions to accept the list of prefetched resources instead, making them stateless and simpler to test.
Since I wanted to test reporting logic related to missing and skipped users, I wrapped the LDAP retry logic into a small interface and reworked the migration code accordingly. This setup makes it simpler to mock for error injection.
Within `pkg/agent/clean/adunmigration` the …

[Forwardport 2.9] Add unit tests for GUID unmigration

---

pkg/controllers/management/eks/eks_cluster_handler.go

After merging https://github.com/rancher/rancher/pull/43882, imported EKS clusters without managed node groups no longer cause an error as long as the agent is installed in a self-managed node. The error message when the cluster has zero nodes (either managed or self-managed) is still the same and not aligned with the requirements.
The error message is updated to include self-managed nodes as a valid compute option.
* Unit
* None
_TODO_
Existing / newly added automated tests that …

[v2.9] chore: improve error message when eks cluster does not have nodes

---

tests/integration/suite/test_default_roles.py

Currently the integration tests are failing because this issue https://github.com/rancher/webhook/pull/320 checks for ClusterRoles that match the RoleTemplates. If a user hasn't enabled monitoring (like in our CI or dev environments) 3 of the ClusterRoles referenced by RoleTemplates don't exist.
Names of ClusterRoles not created:
`monitoring-ui-view`
`navlinks-view`
`navlinks-manage`
For the particular integration tests that require these CRs, check that they get created before the tests run. Otherwise the test will fail
Integration tests pass, on the first attempt and on any subsequent runs.

Check if necessary clusterroles exist on test

---

package/Dockerfile

csp-adapter support for k8s 1.27
scenario 1.
-  Install rancher v2.7.11 and csp-adapter v2.0.4 on an EKS Kubernetes (k8s) 1.27 cluster.
- Validated the support config and licence entitlement functionality. Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. Scaled down the cluster to 17 nodes, validated that the out-of-compliance message is no longer displayed. Scaled back up to 21 nodes, validated the out-of-compliance message popped up.
- uninstall/downgrade/upgrade
scenario 2.
- Install rancher v2.7.11 and csp-adapter v2.0.4 on an EKS Kubernetes (k8s) 1.26 cluster.
- Upgraded EKS cluster to k8s 1.27 in aws
- Validated the support config and licence entitlement functionality. Created a downstream EKS cluster with 21 nodes (with 1 …

Release csp adapter version 2.0.4

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/README.md

https://github.com/rancher/qa-tasks/issues/523
vsphere node driver requires multiple configuration support in order to use windows nodes. 
Enable multiple configuration for all node drivers **Breaking Change** (see readme) following the following format:
```
GenericMachineConfigs:
region: your_region
GenericMachineConfig:
- config_1_var_1: ...
config_1_var_2: ...
- config_2_var_1: ...
config_2_var_2: ...
...
```
locally tested using aws and vsphere
* Unit
* None
_TODO_
Existing / …

[2.8] allow multiple configs for k3s/rke2 automation

---

.drone.yml
manifest-agent-head.tmpl
manifest-agent.tmpl
manifest-head.tmpl
manifest-installer-head.tmpl
manifest-installer.tmpl
manifest.tmpl

Relates to: https://github.com/rancher/rancher/issues/44141
We want to push images relating to the v2.7.11 release to a staging docker registry, and not docker.io. 
Reenable the push steps in drone.yaml, for each step which publishes a docker image change the following 
1. For each step which uses the `plugin/docker` Drone plugin
1.  add an extra environment variable (`DOCKER_REGISTRY`), which is picked up by the `drone/docker` plugin (As can be seen here, [1](https://github.com/drone-plugins/drone-docker/blob/939591f01828eceae54f5768dc7ce08ad0ad0bba/cmd/drone-docker/main.go#L209-L214), [2](https://github.com/drone-plugins/drone-docker/blob/939591f01828eceae54f5768dc7ce08ad0ad0bba/cmd/drone-docker/main.go#L317), [3](https://github.com/drone-plugins/drone-docker/blob/939591f01828eceae54f576 …

Update drone.yaml push steps to use staging registry

---

pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/manager_test.go

When a user is granted permissions to a project, it creates a role and roleBinding in that project namespace. If the project namespace is terminating it produces an error in the logs.
Added 2 new checks, one that the namespace exists and another that checks if the namespace is terminating.
I also did some small refactoring to change the RBAC clients to make them more easily testable and added some comments.
Fully tested the reproduction steps from the issue, and I tested that the normal flow, where the project namespace is not terminating, and saw no errors and all Roles/RoleBindings were successfully created.
* Unit
Summary: Added complete unit test coverage for `reconcileDesiredMGMTPlaneRoleBindings` and `reconcileManagementPlaneRole`
With the small …

Check that namespace is active before adding management Role and RoleBinding in it

---

tests/integration/suite/test_users.py

`test_globalrolebinding_finalizer_cleanup` is asserting that the finalizer `clusterscoped.controller.cattle.io/grb-sync_fake` is cleaned up. The issue arises from the assumption in the test that metadata always contains a `finalizers` field. Although `finalizers` will eventually be present, there's a small window where `metadata` doesn't have `finalizers`. This happens when `clusterscoped.controller.cattle.io/grb-sync_fake` is removed, and before the `controller.cattle.io/mgmt-auth-grb-controller` finalizer is added. This creates a race condition in the test, leading to failures from time to time.
Check if `finalizers` is present in the `metadata` field before asserting. If there is no finalizers, it indicates that `clusterscoped.controller.cattle.io/grb-sync_fake` has been removed.
I ran …

Fix test_globalrolebinding_finalizer_cleanup flaky test

---

.drone.yml

Additional changes are needed to publish steps in order to properly authenticate with and push images to the staging registry
The `windows-ltsc2022` pipeline uses the `rancher/drone-images` image to publish images to dockerhub. It seems this approach was taken a few years ago due to drone not publishing `ltsc2022` tags of the `plugins/docker` image. Unfortunately documentation on how this image works, and what its settings are, seems to have been misplaced. This makes it difficult to update this pipeline.
Specifically, this PR aims to solve the CI failure seen here https://drone-publish.rancher.io/rancher/rancher/11482/8/4, which is due to `rancher/drone-images` not having a well documented list of settings that can be used to define image registries other than docker.io. 
In the past …

Update drone.yaml to use `plugins/docker`, update publishing steps

---

tests/validation/tests/v3_api/test_airgap_ha.py

airgap job was failing for python tests
helm was using k8s client version, not server version
add `--validate` flag to helm template command to match behavior for helm install, which checks the server version
tested locally during release testing

[v2.9] require helm check cluster version in airgap setup

---

.drone.yml

Both the rancher agent and installer Dockerfiles use the rancher image as a base. By default, we attempt to retrieve the base from dockerhub. In situations where a staging registry is used, this will fail, as the base image will not be present. 
Both the agent and installer Dockerfiles provide a `RANCHER_REPO` argument, which is used in the `FROM` statement. By setting the `RANCHER_REPO` argument within drone, we will ensure that 
```
FROM rancher/rancher:${RANCHER_TAG} as rancher
```
becomes 
```
FROM STAGING_REGISTRY/rancher/rancher:${RANCHER_TAG} as rancher
```

Ensure drone passes proper registry url to agent and installer dockerfiles 

---

pkg/api/norman/store/cluster/cluster_store.go

https://github.com/rancher/rancher/issues/41662
We can create an RKE1 cluster template revision with the private registry enabled but without a password. Panic happens when we create an RKE cluster with that cluster template revision, regardless of whether we set the password or not in the cluster creation page.
In the backend, we need to load the cluster template revision when generating the MgmtCluster object for the cluster, the cluster template revision is converted into an object of the type  `[]map[string]interface{}` where the values are also of the type  `[]map[string]interface{}`. It means that if the password value is not set then the key "password" will not be in the map. 
Later on, when we try to get the password value from a `[]map[string]interface{}` object,  we do not check …

fix the bug that a panic happens when we create an RKE cluster with clusterTemplateRevision 

---

tests/v2/validation/rbac/rbac_test.go

In rbac tests, we have dynamic tests that run even when role is not provided but error out. Skipping these tests so it wont run when a role is not provided.

Skipping dynamic tests when no input is provided

---

pkg/api/norman/store/cluster/cluster_store.go

https://github.com/rancher/rancher/issues/44410
backport of the PR https://github.com/rancher/rancher/pull/44373 
Below is copied from the original PR
---
We can create an RKE1 cluster template revision with the private registry enabled but without a password. Panic happens when we create an RKE cluster with that cluster template revision, regardless of whether we set the password or not in the cluster creation page.
In the backend, we need to load the cluster template revision when generating the MgmtCluster object for the cluster, the cluster template revision is converted into an object of the type  `[]map[string]interface{}` where the values are also of the type  `[]map[string]interface{}`. It means that if the password value is not set then the key "password" will not be in the map. …

[v2.8] [Backport] fix the bug that a panic happens when we create an RKE cluster with clusterTemplateRevision

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

`system-agent` issue: https://github.com/rancher/system-agent/issues/145
If maximum retries are met attempting to download the rancher2_connection_info.json, the script continues with invalid data in that file causing the rancher-system-agent to fail to start.
This change cleans up the errant json file and exits the installer instead of continuing to setup a service doomed for failure.
Manually validated
* None
* If "None" - Reason: Not possible given nature of issue requires node to fail to download connection info, which is not permissive in CI
Want to call out that upgrade testing isn't particularly relevant, since previous instances of the system-agent would happily attempt to proceed without connection info. …

Bump system-agent to v0.3.5-rc2

---

go.mod
go.sum
tests/v2/validation/nodescaling/replace.go
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

v2.8 backport of https://github.com/rancher/rancher/pull/44338.

[v2.7] Add support for rotating worker nodes after creating an etcd snapshot

---

build.yaml
pkg/buildconfig/constants.go

[ rancher/rancher#43729  ](https://github.com/rancher/rancher/issues/43729)
Support for k8s 1.28
Spun up an EKS cluster with k8s 1.27 and install rancher v2.8.2 and install csp adapter chart 103.0.0+up3.0.0
Upgrade rancher to a locally built 2.8 image (with k8s 1.28 support) with CATTLE_CSP_ADAPTER_MIN_VERSION="103.0.1+up3.0.1-rc2" (build.yaml change)
Updated charts repo to point to my forked repo/branch with 103.0.1+up3.0.1-rc2 charts
Upgraded csp-adapter to the new chart version
Ran the tests: 
Validated the support config and licence entitlement functionality. Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. Deleted the cluster, validated that the out-of-compliance message is no longer displayed.
Uninstall the chart

Bump csp adapter to 3.0.1-rc2

---

tests/v2/validation/provisioning/rke2/agent_customization_test.go

https://github.com/rancher/qa-tasks/issues/1100 supporting https://github.com/rancher/rancher/issues/41606
we are gearing toward automation first, and we should have a static test for happy path features. Adding this for agent customization (cluster and fleet) as well as 1 non-happy path test. 
The linked ticket is for this non-happy path (currently no code is merged for this, so the test will fail until this is merged).
add static test for happy path (good config) for fleet and cluster agent customization as a standard user.
add static test for bad config with fleet and cluster agent customization. Test will pass if creating the cluster fails (negative test)
tested locally, passing. Would like some guidance for how to run a test that we expect to fail at this time, but should pass later …

[2.9] adding static tests for agent customization

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

This PR does the following:
- switch KDM branch to release-v2.7 
- bump system-agent image tag to v0.3.5

[v2.7.11] switch KDM branch to release-v2.7 and bump system-agent image tag to v0.3.5

---

pkg/controllers/managementuser/rbac/handler_base.go
pkg/controllers/managementuser/rbac/handler_base_test.go

If a `RoleTemplate` is created with an empty list in any `Rule`, then rancher creates a corresponding `ClusterRole` with a nil list. When Rancher goes to sync `RoleTemplates` and `ClusterRoles` it will detect that emptyList != nil list and attempt to update the `ClusterRole`.
Use apimachinery [semantic.DeepEqual()](https://github.com/kubernetes/apimachinery/blob/v0.29.2/third_party/forked/golang/reflect/deep_equal.go#L263) instead of `reflect.Equal()` to compare `Rules`. This function considers a nil list to be equal to an empty list.
Followed the steps to reproduce the bug and didn't see the following message:
```
Updating clusterRole rt-77txz because of rules difference with roleTemplate Custom Test Role (rt-77txz).
```
* Test types added:
* Unit
No specific recommendations on fresh and …

Use apimachinery semantic.DeepEqual to compare Rules

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/43991
`rancher/system-agent` was bumped to `v0.3.5-rc2` in PR here: https://github.com/rancher/rancher/pull/44314 but as `v2.7` was pinned to `v0.3.5-rc1` and no official system-agent tag was cut for that commit, we cut commit `v0.3.5` with identical commit ID to `v0.3.5-rc1` and bumped `v0.3.5-rc2` to the `v0.3.6` commit line.
Cut `rancher/system-agent` `v0.3.6-rc1`: https://github.com/rancher/system-agent/releases/tag/v0.3.6-rc1 and bump the `rancher/system-agent` version references in `rancher/rancher` to `v0.3.6-rc1`
N/A
* None
* If "None" - GH Issue/PR: N/A
Summary: Existing integration tests should be able to validate whether bump is valid.
N/A
N/A …

[release/v2.9] Bump rancher/system-agent to v0.3.6-rc1

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

The embedded CAPI webhook in rancher/webhook is no longer used and it is causing dependencies conflicts for k8s 1.28 support: https://github.com/rancher/rancher/issues/44018.
We're removing the CAPI webhook from webhook completely. See https://github.com/rancher/rancher/issues/43619#issuecomment-1971574484 for details.
There is no need to set capi.enabled false since this will no longer be used in the webhook chart. (https://github.com/rancher/webhook/pull/336)
This change should have exactly 0 impact on anything because the default value for `capi.enabled` is already false, so not providing it would be the same. (Also, we're removing it completely here: https://github.com/rancher/webhook/pull/336). 
* Unit
* Integration (v2prov …

[v2.8] Remove unused capi.enabled helm value for webhook

---

pkg/catalogv2/system/manager_test.go
pkg/catalogv2/system/system.go

Forward port of #43498.
When installing a system chart by version, Rancher now errors if the version of the chart found in the index is not the requested one. In such a case, the chart is not installed. This previously happened only when the version to be installed would overwrite whatever other version was already installed.
Broadening the scope of this check fixes a bug whereby a system chart, eg. Fleet, would be installed in its latest available version if an invalid version number was specified in environment variables (eg. `CATTLE_FLEET_VERSION`).

Fix check for exact version in Helm index

---

pkg/catalogv2/system/manager_test.go
pkg/catalogv2/system/system.go

When installing a system chart by version, Rancher now errors if the version of the chart found in the index is not the requested one. In such a case, the chart is not installed. This previously happened only when the version to be installed would overwrite whatever other version was already installed.
Broadening the scope of this check fixes a bug whereby a system chart, eg. Fleet, would be installed in its latest available version if an invalid version number was specified in environment variables (eg. `CATTLE_FLEET_VERSION`).
* [fleet#1590](https://github.com/rancher/fleet/issues/1590) and [fleet#1948](https://github.com/rancher/fleet/issues/1948)
* https://github.com/rancher/fleet/issues/1948
Rancher installs a version of a Helm chart which differs from the version specified in the …

[2.8] Fix check for exact version in Helm index

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot_additional_test.go

As we move towards the idea of prioritizing static test cases, a point of conversation was ensuring existing functionality is properly being tested in static functions. For snapshots, recurring restores and replacing worker nodes, these are not tested in static functions, which isn't ideal for QA's code coverage.
Created new test additional snapshot file that have static test cases around snapshot recurring restores and replacing worker nodes.

[v2.9] Add additional snapshot test file that tests replacing worker nodes and recurring restores

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot_additional_test.go

As we move towards the idea of prioritizing static test cases, a point of conversation was ensuring existing functionality is properly being tested in static functions. For snapshots, recurring restores and replacing worker nodes, these are not tested in static functions, which isn't ideal for QA's code coverage.
Created new test additional snapshot file that have static test cases around snapshot recurring restores and replacing worker nodes.

[v2.8] Add snapshot test files catered to replace worker nodes and recurring restores

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot_additional_test.go

As we move towards the idea of prioritizing static test cases, a point of conversation was ensuring existing functionality is properly being tested in static functions. For snapshots, recurring restores and replacing worker nodes, these are not tested in static functions, which isn't ideal for QA's code coverage.
Created new test additional snapshot file that have static test cases around snapshot recurring restores and replacing worker nodes.

[v2.7] Add snapshot test files catered to replace worker nodes and recurring restores

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/44520
- bumped rke version to `v1.5.7-rc3` from `v1.5.7-rc2`

[v2.8] Bump RKE to v1.5.7-rc3

---

pkg/data/management/kontainerdriver_data.go

kontainer-engine-driver-lke v0.0.8 fails to start with the following error:
```
/management-state/bin/kontainer-engine-driver-lke: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /management-state/bin/kontainer-engine-driver-lke)
```
This error is raised because the release binaries for v0.0.8 were not built using the proper compiler flags.
This PR bumps kontainer-engine-driver-lke to v0.0.9 which has release binaries that were built with the proper compiler flags.

[v2.8] Bump kontainer-engine-driver-lke to v0.0.9

---

pkg/data/management/kontainerdriver_data.go

kontainer-engine-driver-lke v0.0.8 fails to start with the following error:
```
/management-state/bin/kontainer-engine-driver-lke: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /management-state/bin/kontainer-engine-driver-lke)
```
This error is raised because the release binaries for v0.0.8 were not built using the proper compiler flags.
This PR bumps kontainer-engine-driver-lke to v0.0.9 which has release binaries that were built with the proper compiler flags.

[v2.7] Bump kontainer-engine-driver-lke to v0.0.9

---

tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.ha

Using the current ha pipeline, we cannot add helm urls to be able to install prime charts
In this PR, we are adding the helm repo urls as a config, so we can update the prime repos in the configs.

Updating configs in the jenkins pipeline to take in rule as a config

---

tests/v2/validation/charts/README.md
tests/v2/validation/charts/webhook.go
tests/v2/validation/charts/webhook_test.go

https://github.com/rancher/qa-tasks/issues/1171
Current automation runs only for a single cluster. Added local cluster in the configs, so the validations are run for the local cluster as well as the cluster name provided in the config.yaml.
This requires back ports to 2.8 and 2.7

Updating local cluster to be run as part of webhook checks

---

pkg/data/management/kontainerdriver_data.go

kontainer-engine-driver-lke v0.0.8 fails to start with the following error:
```
/management-state/bin/kontainer-engine-driver-lke: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /management-state/bin/kontainer-engine-driver-lke)
```
This error is raised because the release binaries for v0.0.8 were not built using the proper compiler flags.
This PR bumps kontainer-engine-driver-lke to v0.0.9 which has release binaries that were built with the proper compiler flags.

[v2.9] Bump kontainer-engine-driver-lke to v0.0.9

---

pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go
pkg/controllers/provisioningv2/fleetcluster/mock_cluster_host_getter_test.go
pkg/fleet/fleet.go
pkg/fleet/fleet_test.go

This should prevent the Fleet agent from failing to reach the management cluster with errors about a certificate being signed by an unknown authority.
This is a follow-up to #44612.
When installing Rancher (eg. basic install via Helm), the Fleet agent fails to reach the management cluster and logs something like:
```
time="2024-03-06T09:51:55Z" level=error msg="Failed to register agent: registration failed: cannot create clusterregistration on management cluster for cluster id '<id>': Post "https://<ip>:443/apis/fleet.cattle.io/v1alpha1/namespaces/fleet-local/clusterregistrations](": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```
Add CA data, for the cluster for which the host is extracted, to the local kubeconfig secret.
1. Built a custom Rancher …

Add CA of cluster beside host in local kubeconfig secret

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Fixes memory leak due to leaking downstream cluster caches. See original issue and PR for more details.
Unregister informers when related context is cancelled. 
I manually tested this by registering a downstream cluster, create a significant amount of 1MB-sized Secrets, then repeatedly registering/unregistering the cluster, watching how the heap grows. With this patch, this does not happen anymore and everything continues working correctly.

[2.8] deps(wrangler): bump wrangler to v2.1.4

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

If maximum retries (5) are met attempting to download the rancher2_connection_info.json, the installation script continues with invalid data in that file causing the rancher-system-agent to fail to start.
Block the `https://<SERVER_URL>/v3/connect/agent` endpoint from the downstream node (or for a custom cluster, run the install command once successfully, then run it again with an invalid server-url).
Manually tested both above scenarios
* None
* If "None" - Reason: Not possible to do in current framework
Provisioned and custom clusters. Re-registration behavior for failed custom installations would be a useful test case.
Very low regression chance, but may be possible that intermittent networking issues cause provisioning to fail, but this is recoverable.

[v2.8] Bump system-agent to v0.3.6-rc2

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

If maximum retries (5) are met attempting to download the rancher2_connection_info.json, the installation script continues with invalid data in that file causing the rancher-system-agent to fail to start.
Block the `https://<SERVER_URL>/v3/connect/agent` endpoint from the downstream node (or for a custom cluster, run the install command once successfully, then run it again with an invalid server-url).
Manually tested both above scenarios
* None
* If "None" - Reason: Not possible to do in current framework
Provisioned and custom clusters. Re-registration behavior for failed custom installations would be a useful test case.
Very low regression chance, but may be possible that intermittent networking issues cause provisioning to fail, but this is recoverable.

[v2.7] Bump system-agent to v0.3.6-rc2

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

If maximum retries (5) are met attempting to download the rancher2_connection_info.json, the installation script continues with invalid data in that file causing the rancher-system-agent to fail to start.
Block the `https://<SERVER_URL>/v3/connect/agent` endpoint from the downstream node (or for a custom cluster, run the install command once successfully, then run it again with an invalid server-url).
Manually tested both above scenarios
* None
* If "None" - Reason: Not possible to do in current framework
Provisioned and custom clusters. Re-registration behavior for failed custom installations would be a useful test case.
Very low regression chance, but may be possible that intermittent networking issues cause provisioning to fail, but this is recoverable.

Bump system-agent to v0.3.6-rc2

---

tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/psact_test.go

As part of having better Qase coverage across our provisioning tests, we need to ensure that PSACT is covered as part of this effort. This includes `rancher-privileged`, `rancher-restricted` and `rancher-baseline`.
Created test files that specifically provision dedicated role clusters with each PSACT value type. This is across RKE1/RKE2/K3S and the READMEs have been updated accordingly.
Manually tested RKE1, RKE2 and K3s node driver test.

[v2.9] Add PSACT test files for Qase coverage

---

tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/psact_test.go

As part of having better Qase coverage across our provisioning tests, we need to ensure that PSACT is covered as part of this effort. This includes `rancher-privileged`, `rancher-restricted` and `rancher-baseline`.
Created test files that specifically provision dedicated role clusters with each PSACT value type. This is across RKE1/RKE2/K3S and the READMEs have been updated accordingly.
Manually tested RKE1, RKE2 and K3s node driver test.

[v2.8] Add PSACT test files for Qase coverage

---

tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/psact_test.go

As part of having better Qase coverage across our provisioning tests, we need to ensure that PSACT is covered as part of this effort. This includes `rancher-privileged`, `rancher-restricted` and `rancher-baseline`.
Created test files that specifically provision dedicated role clusters with each PSACT value type. This is across RKE1/RKE2/K3S and the READMEs have been updated accordingly.
Manually tested RKE1, RKE2 and K3s node driver test.

[v2.7] Add PSACT test files for Qase coverage

---

pkg/controllers/management/auth/crtb_handler.go

This is a continuation of a previous solution related to namespaces stuck in terminating. This particular bug is related to projects being stuck while getting deleted. During a project deletion, it deletes the project namespaces, but if the project hasn't finished deleting, there will be an attempt to create the necessary cluster role bindings in those project namespaces for any cluster owners. That results in the logs being spammed with error messages.
To prevent this from happening, I added a check before we create the bindings to see if `DeletionTimestamp` is set. If it is, that means we are in the process of deleting the project and should not create bindings for it.
Steps:
1. Create a downstream cluster
2. Create a project in that downstream cluster
3. Get it stuck in deleting (for …

Do not add bindings for projects that are being deleted

---

pkg/data/management/role_data.go

#40303 
Users assigned "manage workloads" for a given project do NOT have the ability to scale statefulsets.
The required rbac for statefulsets is present, but not on statefulsets/scale, which appears to be an accidental omission.
Grant rbac for the "manage workloads" role on group: apps resource: statefulsets/scale.
Create a downstream cluster
In that new cluster, create the following:
1. A user (which will be assigned "manage workloads") below
2. A project, here is where you can also add the newly created user as a workload manager
3. A namespace inside the new project
4. A statefulset inside the namespace created above
Login as the new user created above.
Navigate to the cluster/project/namespace where the statefulset was created
You should be able to see the statefulset and navigate …

Add RBAC for statefulsets/scale for the Manage Workloads RoleTemplate

---

README.md
chart/templates/ingress.yaml
chart/values.yaml

Certain load balancers (such as AWS Load Balancer controller or GKE Ingress) require a slightly different path to work with Rancher.
Making both the path and the pathType customisable via helm values will mean wider compatibility and greater flexibility.
Having tried the native chart with both AWS Load Balancer controller and GKE Ingress, the ingress returned 404 consistently on the /dashboard/ endpoint.
I created a helm installation with the following values:
```
hostname: rancher.mycompany.net
ingress:
ingressClassName: alb
includeDefaultExtraAnnotations: false
extraAnnotations:
alb.ingress.kubernetes.io/scheme: internal
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80, "HTTPS": 443}]'
alb.ingress.kubernetes.io/target-type: ip
tls: external
```
After deploying, the Rancher …

add ingress path+pathType customization to helm chart

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

We have removed CAPI webhook values in https://github.com/rancher/rancher/pull/44616 since webhook no longer use those values.
Previous values from `helm install` commands are kept stored in k8s. This means that the PR above, while working correctly, did let some values lingering there. This has no impact other than being confusing while troubleshooting. These values are not supposed to be looked at by users and the command to do so does not appear in the docs. Nonetheless, we prefer to remove them.
We're reverting https://github.com/rancher/rancher/pull/44616 and instead of removing the `capi` field, we set it explicitely to `nil`.
We go from:
```
$ helm get values -n cattle-system rancher-webhook
USER-SUPPLIED VALUES:
capi:
enabled: false
global:
cattle:
systemDefaultRegistry: ""
mcm: …
```

Remove CAPI webhook Helm values

---

tests/v2/validation/provisioning/rke2/custom_cluster_test.go

In the RKE2 custom clusters test file, we only are covering dedicated cluster use case for Windows. We should add an additional use-case so that it more so is parallel to the other test cases by not having an isolated use-case.
Added an admin and standard use case for the following cluster configuration:
- 1 etcd
- 1 cp
- 1 Linux worker
- 2 Windows worker
Locally tested this use-case.
Jenkins runs will be provided offline upon request.

[v2.9] Add test cases for RKE2 Windows custom clusters for 2 Windows worker nodes

---

tests/v2/validation/provisioning/rke2/custom_cluster_test.go

In the RKE2 custom clusters test file, we only are covering dedicated cluster use case for Windows. We should add an additional use-case so that it more so is parallel to the other test cases by not having an isolated use-case.
Added an admin and standard use case for the following cluster configuration:
- 1 etcd
- 1 cp
- 1 Linux worker
- 2 Windows worker
Locally tested this use-case.
Jenkins runs will be provided offline upon request.

[v2.7] Add test cases for RKE2 Windows custom clusters for 2 Windows worker nodes

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

The CSI Agent Proxy version v1.1.1 contains a bug which prevents a storage class from being used by multiple PVCs on Windows nodes
Bump the CSI Proxy version to v1.1.3
A good guide on setting up an smb server locally and verifying that the CSI Proxy works as expected can be found here https://www.phillipsj.net/posts/how-to-use-the-windows-csi-proxy-and-csi-smb-driver-for-kubernetes/
To summarize the above
+ Create a cluster with at least 1 Windows node
+ Add a new Helm repository using this URL: `https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts`
+ Install the chart added by the new helm repository `csi-driver-smb`
+ During installation, ensure that `windows.enabled` is equal to `true` and that `windows.csiproxy.enabled` is set to `false`. The csi-proxy is …

[2.7] Bump csi proxy agent version to v1.1.3

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

The CSI Agent Proxy version v1.1.1 contains a bug which prevents a storage class from being used by multiple PVCs on Windows nodes
Bump the CSI Proxy version to v1.1.3
A good guide on setting up an smb server locally and verifying that the CSI Proxy works as expected can be found here https://www.phillipsj.net/posts/how-to-use-the-windows-csi-proxy-and-csi-smb-driver-for-kubernetes/
To summarize the above
+ Create a cluster with at least 1 Windows node
+ Add a new Helm repository using this URL: `https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts`
+ Install the chart added by the new helm repository `csi-driver-smb`
+ During installation, ensure that `windows.enabled` is equal to `true` and that `windows.csiproxy.enabled` is set to `false`. The csi-proxy is …

[2.8] Bump csi proxy agent version to v1.1.3

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

The CSI Agent Proxy version v1.1.1 contains a bug which prevents a storage class from being used by multiple PVCs on Windows nodes
Bump the CSI Proxy version to v1.1.3
A good guide on setting up an smb server locally and verifying that the CSI Proxy works as expected can be found here https://www.phillipsj.net/posts/how-to-use-the-windows-csi-proxy-and-csi-smb-driver-for-kubernetes/
To summarize the above
+ Create a cluster with at least 1 Windows node
+ Add a new Helm repository using this URL: `https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts`
+ Install the chart added by the new helm repository `csi-driver-smb`
+ During installation, ensure that `windows.enabled` is equal to `true` and that `windows.csiproxy.enabled` is set to `false`. The csi-proxy is …

Bump CSI proxy agent version to v1.1.3

---

pkg/apis/catalog.cattle.io/v1/plugin.go
pkg/crds/yaml/generated/catalog.cattle.io_uiplugins.yaml

Status must always be a subresource. This fix wasn't the case for the UIPlugin CRD and this PR fixes that

Setting status as subresource

---

build.yaml
pkg/buildconfig/constants.go

We're unRCing webhook which contains these changes:
Also includes CAPI removal from https://github.com/rancher/rancher/issues/44619 to make bump to 1.28 k8s possible.
We want to support 1.28 k8s.
Bump relevant dependencies. cluster-api v1.5.5 conflicts with k8s.io/* 0.28. One option is to remove it entirely from webhook since we aren't using it anymore (since v2.7.7).
The changes are:
- Upgraded cluster-api to v1.5.5 to match rancher/rancher v2.8
- Upgraded controller-runtime to v0.15.3
- Upgraded github.com/rancher/rke to v1.5.7-rc2
- Upgraded lasso which supports 1.28
- Upgraded to wrangler v2 so that's why there is a LOT of files modified.
- Upgraded dynamiclistener to v0.4.0-rc2 because it contains 1.28 support + wrangler v2. Otherwise conflicts, can't compile. Here's the comparison …

[v2.8] Bump rancher-webhook to v0.4.3

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

Forwardport of https://github.com/rancher/rancher/issues/44619
The embedded CAPI webhook in rancher/webhook is no longer used and it was causing dependencies conflicts for k8s 1.28 support: https://github.com/rancher/rancher/issues/44018.
We're removing the CAPI webhook from webhook completely. See https://github.com/rancher/rancher/issues/43619#issuecomment-1971574484 for details.
We're setting `capi` to nil explicitely to make sure it removes references to it in the webhook Helm values. This is just to make it less confusing if we troubleshoot those values. Those values are no longer used in webhook, so it doesn't actually matter what they are.
* Unit
* Other - Explain: …

[Forwardport v2.9] Remove unused capi.enabled helm value for webhook

---

tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.ha

For prime releases, helm repo differs before and after upgrade. This is to make sure we are able to use the repo in ha upgrade pipeline
Note: Once approved, this requires a back port in 2.8 as well as 2.7

Adding helm repo to upgrade for prime checks

---

tests/v2/validation/nodescaling/scaling_node_driver_aks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_eks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_gke_test.go

In Qase, GKE is not being reported in its own section. In fact, it is being reported as an additional run under the EKS section. This is because the test case name is the exact same.
So the Qase parser is unable to distinguish between the two.
Updated the hosted cluster's test case names so that the Qase parser can properly distinguish between the two.

[v2.7] Update hosted clusters nodescaling test case names

---

tests/v2/validation/nodescaling/scaling_node_driver_aks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_eks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_gke_test.go

In Qase, GKE is not being reported in its own section. In fact, it is being reported as an additional run under the EKS section. This is because the test case name is the exact same.
So the Qase parser is unable to distinguish between the two.
Updated the hosted cluster's test case names so that the Qase parser can properly distinguish between the two.

[v2.8] Update hosted clusters nodescaling test case names

---

tests/v2/validation/nodescaling/scaling_node_driver_aks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_eks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_gke_test.go

In Qase, GKE is not being reported in its own section. In fact, it is being reported as an additional run under the EKS section. This is because the test case name is the exact same.
So the Qase parser is unable to distinguish between the two.
Updated the hosted cluster's test case names so that the Qase parser can properly distinguish between the two.

[v2.9] Update hosted clusters nodescaling test case names

---

build.yaml
pkg/buildconfig/constants.go

Update Fleet to v0.9.1
Changelog: https://github.com/rancher/fleet/releases/tag/v0.9.1

[2.8] Update Fleet to 0.9.1

---

pkg/auth/api/secrets/store.go
pkg/auth/providers/activedirectory/activedirectory_actions.go
pkg/auth/providers/azure/azure_provider.go
pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/common/password.go
pkg/auth/providers/common/password_test.go
pkg/auth/providers/github/github_provider.go
pkg/auth/providers/googleoauth/goauth_provider.go
pkg/auth/providers/ldap/ldap_actions.go
pkg/auth/providers/oidc/oidc_provider.go
pkg/auth/providers/saml/saml_provider.go
pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/clusters.go

The generated name of the secret in [SavePasswordSecret](https://github.com/rancher/rancher/blob/941d6d3102a39fff855fd07ca99e2c6e39f7a6de/pkg/auth/providers/common/password.go#L90) was not correctly converting fieldName to lower when generating the secret name.
The initial fix was to generate it with the correct name.
But these functions delegate via a `CreateOrUpdateSecrets` function which generates the name itself, there's scope for discrepancies anywhere the combination of `CreateOrUpdateSecrets` and `GetFullSecretName` were called.
This code makes `CreateOrUpdateSecrets` return the name of the generated secret which is used instead of generating the name again.
* Unit …

Fix shibboleth bug

---

tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_test.go
tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
tests/v2/validation/nodescaling/scaling_node_driver_test.go

In Qase, nodescaling for RKE1 and v2 prov is not being reported in its own section. This is because the test case name is the exact same. So the Qase parser is unable to distinguish between the appropriate test cases.
Updated the node driver and custom cluster's test case names so that the Qase parser can properly distinguish between the test cases.

[v2.9] Update nodescaling names for RKE1 and v2prov clusters

---

tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_test.go
tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
tests/v2/validation/nodescaling/scaling_node_driver_test.go

In Qase, nodescaling for RKE1 and v2 prov is not being reported in its own section. This is because the test case name is the exact same. So the Qase parser is unable to distinguish between the appropriate test cases.
Updated the node driver and custom cluster's test case names so that the Qase parser can properly distinguish between the test cases.

[v2.8] Update nodescaling names for RKE1 and v2prov clusters

---

tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_test.go
tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
tests/v2/validation/nodescaling/scaling_node_driver_test.go

In Qase, nodescaling for RKE1 and v2 prov is not being reported in its own section. This is because the test case name is the exact same. So the Qase parser is unable to distinguish between the appropriate test cases.
Updated the node driver and custom cluster's test case names so that the Qase parser can properly distinguish between the test cases.

[v2.7] Update nodescaling names for RKE1 and v2prov clusters

---

go.mod
go.sum

`release/v2.8` is still using an RC version of the `dynamiclistener` dependency 
Update `go.mod` to point to the non-rc `v0.4.0` tag of dynamic listener 
The `v0.4.0` tag of dynamic listener uses the same commit as `v0.4.0-rc2`, so this bump does not change any functionality or invalidate any prior testing. 

[v2.8] Bump dynamic listener to `v0.4.0`

---

tests/v2/validation/shell/README.md
tests/v2/validation/shell/shell_test.go

The existing Shell automation is pulling the cluster name from the config file, but these tests are only ever run on the local cluster. 
I've updated the `s.clusterName` to now be the string `"local"`
Summary: Updated automation to use local cluster only

[2.7] Fixes for Shell automation

---

tests/v2/validation/shell/README.md
tests/v2/validation/shell/shell_test.go

The existing Shell automation is pulling the cluster name from the config file, but these tests are only ever run on the local cluster. 
I've updated the `s.clusterName` to now be the string `"local"`
Summary: Updated automation to use local cluster only

[2.9] Fixes for Shell automation

---

pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute.go
pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute_test.go
pkg/controllers/managementuser/clusterauthtoken/register.go

Ref: https://github.com/rancher/rancher/issues/44914
If the ClusterUserAttribute becomes orphaned the corresponding controller will spin not being able to find related UserAttribute.
Delete orphaned ClusterUserAttribute's. 
* Unit
N/A
N/A

[2.9] Clean up orphaned ClusterUserAttribute

---

go.mod
go.sum
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_retention_test.go

Snapshot retention check
We need a test to verify that the snapshot retention limit is respected.
Created a test that sets the retention limit and snapshot schedule of an existing cluster and then waits for the limit + 1 snapshots to be taken before checking to make sure the retention limit is respected. 
Local testing and Jenkins testing.
Ran the test against an RKE1, RKE2 and K3s cluster

Snapshot Retention test

---

go.mod
go.sum
tests/v2/validation/charts/gatekeeper.go
tests/v2/validation/charts/istio.go
tests/v2/validation/charts/monitoring.go
tests/v2/validation/charts/webhook_test.go

The charts test became flaky after recent HTTP call updates in external ingress helpers. The root cause; the body is drained as it's closed. But it's not read or stored anywhere. The same drained response body is used on the Rancher validation side, but it happens too late to read the body.
Added read body part to the function where the HTTP call happens. And now it returns the body as a string for further use of the same body.

[2.9] Fix Response Body Reading in Charts Validation Tests

---

go.mod
go.sum
tests/v2/validation/charts/gatekeeper.go
tests/v2/validation/charts/istio.go
tests/v2/validation/charts/monitoring.go
tests/v2/validation/charts/webhook_test.go

The charts test became flaky after recent HTTP call updates in external ingress helpers. The root cause; the body is drained as it's closed. But it's not read or stored anywhere. The same drained response body is used on the Rancher validation side, but it happens too late to read the body.
Added read body part to the function where the HTTP call happens. And now it returns the body as a string for further use of the same body.

[2.8] Fix Response Body Reading in Charts Validation Tests

---

go.mod
go.sum
tests/v2/validation/charts/gatekeeper.go
tests/v2/validation/charts/istio.go
tests/v2/validation/charts/monitoring.go
tests/v2/validation/charts/webhook_test.go

The charts test became flaky after recent HTTP call updates in external ingress helpers. The root cause; the body is drained as it's closed. But it's not read or stored anywhere. The same drained response body is used on the Rancher validation side, but it happens too late to read the body.
Added read body part to the function where the HTTP call happens. And now it returns the body as a string for further use of the same body.

[2.7] Fix Response Body Reading in Charts Validation Tests

---

pkg/controllers/managementuser/rbac/handler_base_test.go
pkg/controllers/managementuser/rbac/namespace_handler_test.go
pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler_test.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate_test.go
pkg/controllers/managementuser/rbac/roletemplate_handler.go

Fix #43292 
- https://github.com/rancher/rancher/issues/43292
This PR fixes the missing update of the `-promoted` ClusterRole when removing all the permissions.
The issue was due to a check of the length of the `newVerbs`. When `0` the update was skipped.
To fix the issue I moved the check internally, removing the matching rules when no verbs are specified.
The small refactor of the func was made to have a more linear and clear flow, with some early returns/checks.
Added also some unit tests.
One note: in the previous implementation this was the check:
```go
if role, err := m.crLister.Get("", roleName); err == nil && role != nil {
// update ClusterRole
}
// else create new ClusterRole
```
that means if an error occured (not only a "not found" error) then an update will be performed. I …

[v2.9] fix: update 'promoted' ClusterRole when removing all permissions from RoleTemplate

---

build.yaml
pkg/buildconfig/constants.go

Also includes the CAPI removal from https://github.com/rancher/rancher/issues/43619
We want k8s 1.28 support, so needed to remove CAPI webhook from inside webhook and bump the dependencies

Bump rancher-webhook to v0.5.0-rc7

---

pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute.go
pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute_test.go
pkg/controllers/managementuser/clusterauthtoken/register.go

Backport of #44915
Ref: https://github.com/rancher/rancher/issues/44985
* Unit
_TODO_
* _TODO_

[2.8] Clean up orphaned ClusterUserAttribute

---

pkg/auth/providers/common/password.go
pkg/auth/providers/common/password_test.go

Fixes #44917 
Ported #44836 
Only two commits backported, with minimal changes to fix the actual bug, the broader fix to prevent it happening again was not backported in this change.

[Port v2.8] Fix shibboleth Secret bug  Backport 44917

---

go.mod
go.sum
tests/v2/integration/rtbs/rtbs_test.go

Create Namespace function in the kube api package has been modified to keep the function generic and not tied to any specific API (norman/steve/public): https://github.com/rancher/shepherd/pull/110
The function now accepts clusterID and projectID as inputs instead of norman project. So, the integration tests using this function has been modified to use the updated function.
Backports:
- 2.7: https://github.com/rancher/rancher/pull/44841
- 2.8: https://github.com/rancher/rancher/pull/44842

Updated the tests to use the modified CreateNamespace function

---

pkg/data/management/role_data.go

https://github.com/rancher/rancher/issues/44918 which is the backport issue for https://github.com/rancher/rancher/issues/40303
User unable to scale statefulsets when given "manage workloads"
Add RBAC to allow the manage workloads role to have scale on statefulsets
To test this:
Start up a Rancher instance (issue is 2.5, but you can certainly use something more modern, 2.7.x or 2.8.x).
Create standard user
Create a downstream cluster, project, and namespace.
Assign the user from above "manage workloads" permission in that project.
Create a statefulset inside that project/namespace.
Login as the standard user for which you have granted the manage workload permissions.
Navigate to the statefulset you created inside the project/namespace.
In the UI, the scale buttons will work.
If you try …

[2.8] Add RBAC for statefulsets/scale for the Manage Workloads RoleTemplate

---

go.mod
go.sum
tests/v2/validation/deleting/delete_cluster_rke1_test.go
tests/v2/validation/deleting/delete_cluster_test.go
tests/v2/validation/nodescaling/README.md
tests/v2/validation/nodescaling/scale_replace_rke1_test.go
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
tests/v2/validation/nodescaling/scaling_nodepools.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

During release testing, there were several issues seen with custom clusters and node driver for the `nodescaling` package. Additionally, there wasn't a way to see which cluster type is being ran for the `nodescaling` and `snapshot` package.
This makes it hard for Qase for reviewers to see exactly what cluster type was being ran against tests.
- Addressed flakiness with nodescaling in counterpart shepherd PR with this
- Specified cluster types in test case names
- Ran against RKE1/RKE2/K3S for node scaling - custom cluster and node driver
- Ran snapshot test for each cluster type and made sure it is made clear in the test case header which cluster type is being used

[v2.9] Fix flaky nodescaling test cases + specify cluster types

---

go.mod
go.sum
tests/v2/validation/deleting/delete_cluster_rke1_test.go
tests/v2/validation/deleting/delete_cluster_test.go
tests/v2/validation/nodescaling/README.md
tests/v2/validation/nodescaling/scale_replace_rke1_test.go
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
tests/v2/validation/nodescaling/scaling_nodepools.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

During release testing, there were several issues seen with custom clusters and node driver for the `nodescaling` package. Additionally, there wasn't a way to see which cluster type is being ran for the `nodescaling` and `snapshot` package.
This makes it hard for Qase for reviewers to see exactly what cluster type was being ran against tests.
- Addressed flakiness with nodescaling in counterpart shepherd PR with this
- Specified cluster types in test case names
- Ran against RKE1/RKE2/K3S for node scaling - custom cluster and node driver
- Ran snapshot test for each cluster type and made sure it is made clear in the test case header which cluster type is being used

[v2.8] Fix flaky nodescaling test cases + specify cluster types

---

go.mod
go.sum
tests/v2/validation/deleting/delete_cluster_rke1_test.go
tests/v2/validation/deleting/delete_cluster_test.go
tests/v2/validation/nodescaling/README.md
tests/v2/validation/nodescaling/scale_replace_rke1_test.go
tests/v2/validation/nodescaling/scale_replace_test.go
tests/v2/validation/nodescaling/scaling_custom_cluster_rke1_test.go
tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
tests/v2/validation/nodescaling/scaling_nodepools.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

During release testing, there were several issues seen with custom clusters and node driver for the `nodescaling` package. Additionally, there wasn't a way to see which cluster type is being ran for the `nodescaling` and `snapshot` package.
This makes it hard for Qase for reviewers to see exactly what cluster type was being ran against tests.
- Addressed flakiness with nodescaling in counterpart shepherd PR with this
- Specified cluster types in test case names
- Ran against RKE1/RKE2/K3S for node scaling - custom cluster and node driver
- Ran snapshot test for each cluster type and made sure it is made clear in the test case header which cluster type is being used

[v2.7] Fix flaky nodescaling test cases + specify cluster types

---

pkg/data/management/machinedriver_data.go

update Nutanix node driver to v3.6.0
manual installation of the node driver and cluster deployment with it
Driver is activated
RKE2 & RKE1 install succesfull

update Nutanix node driver to v3.6.0

---

pkg/image/origins.go

Charts PR https://github.com/rancher/charts/pull/3654 introduced a new image `mirrored-sig-storage-csi-snapshotter` which is not tracked in the origins list, resulting in https://drone-publish.rancher.io/rancher/rancher/11965/6/2. This PR adds the origin of that image. This will be backported to other release lines once merged

[2.9] Add origin for `mirrored-sig-storage-csi-snapshotter`

---

pkg/image/origins.go

backport of https://github.com/rancher/rancher/pull/45048

[v2.8] Add `mirrored-sig-storage-csi-snapshotter` origin

---

pkg/auth/requests/service_account.go
pkg/auth/requests/service_account_test.go

https://github.com/rancher/rancher/pull/44925 broke the build - for some reason it was not caught by CI.
```
+ go build -tags k8s -gcflags=all= -ldflags '-X github.com/rancher/rancher/pkg/version.Version=6cb38f2fa
-X github.com/rancher/rancher/pkg/version.GitCommit=6cb38f2fa
-X github.com/rancher/rancher/pkg/settings.InjectDefaults={"rke-version":"v1.5.3"} -extldflags -static -s' -o bin/rancher
...
...
pkg/multiclustermanager/routes.go:97:76: cannot use clustermanager.ToRESTConfig (value of type func(cluster *"github.com/rancher/rancher/pkg/apis/management.cattle.io/v3".Cluster, context *"github.com/rancher/rancher/pkg/types/config".ScaledContext, secretLister "github.com/rancher/rancher/pkg/generated/norman/core/v1".SecretLister, reconnect bool) (*"k8s.io/client-go/rest".Config, error)) …
```

Fix build after ToRESTConfig signature change

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go
pkg/data/management/rolebuilder_test.go

Standard users are able to create secrets in any namespace. While a collision is unlikely, a user could preempt where secrets get created and make one themselves, which could lead to some unexpected/undefined behaviour. However, they do need to be able to create secrets in the cattle-global-data namespace for cloud credentials.
Using the new GlobalRole NamespacedRules field, I've moved the ability to create secrets from all namespaces, to just within the cattle-global-data namespace. That way they can't create secrets in any other namespace.
I chose not to add an opt-out flag. I think if a system would like their users to create secrets in any namespace, that should be added as an additional permission, not be granted by default. A release note will be added for this informing users of …

Improve standard user default permissions

---

tests/v2/validation/shell/README.md
tests/v2/validation/shell/shell_test.go

The existing Shell automation is pulling the cluster name from the config file, but these tests are only ever run on the local cluster. 
I've updated the `s.clusterName` to now be the string `"local"`
Summary: Updated automation to use local cluster only

[2.8] Fixes for Shell automation

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/43103
Since rancher v2.8 we mark (#43989) unknown settings with a label and remove (#44070) them in v2.9.
`eula-agreed` settings is used by UI but is not known to the rancher and therefore will be removed in v2.9.
```
2024/04/10 15:40:10 [WARNING] Unknown setting eula-agreed
```
Add this setting so that rancher knows about it.
N/A
N/A
N/A

[v2.9] Make eula-agreed setting known to Rancher

---

tests/v2/validation/certrotation/cert_rotation.go
tests/v2/validation/certrotation/cert_rotation_test.go

We want parity with python cert_rotation testing. Upon investigation, it was found that there is no validation done of the cert rotation for rke2, and that rotation automation is missing for rke1.  
add logic to rotate certs on rke1
add validation via ssh'ing into each node and checking that the cert has been renewed. 
locally tested, passing. Some more investigation needed for rke1 expected behavior, but rke2 tests resulted in this bug being filed: 
https://github.com/rancher/rke2/issues/5652
* Unit
* None …

[v2.9] add rke1 to cert rotation test. Add validation to cert rotation.

---

pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute.go

This is a forward port of d0d4b45317efa3e63ba24b57dada651811270f69 from #44990 that minimizes the code indentation in ClusterUserAttribute controller.
Original issue https://github.com/rancher/rancher/issues/44914
N/A
N/A
N/A

Flatten conditionals in ClusterUserAttribute controller

---

go.mod
go.sum
tests/v2/integration/catalogv2/rancher_managed_charts_test.go
tests/v2/validation/provisioning/k3s/README.md
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/rke1/README.md
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/README.md
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go

add vsphere chart validation to automation framework
https://github.com/rancher/qa-tasks/issues/936
https://github.com/rancher/qa-tasks/issues/872
we need a way to use vsphere cloud provider in our automation 
implement a similar method to what was used for aws cloud provider support. 
_TODO_
* _TODO_

[2.9] add vsphere chart validation to automation framework

---

pkg/image/origins.go

Image `mirrored-kube-logging-logging-operator` was added to the Rancher charts, but its origin is missing. This may lead to failing PRs.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Add missing `mirrored-kube-logging-logging-operator` origin

---

pkg/image/origins.go

Image `mirrored-kube-logging-logging-operator` was added to the Rancher charts, but its origin is missing. This may lead to failing PRs.
* Unit
* None
_TODO_
* _TODO_

[v2.8] Add missing `mirrored-kube-logging-logging-operator` origin

---

tests/v2/validation/provisioning/import/README.md
tests/v2/validation/provisioning/import/import_cluster_test.go
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_go_provisioing_sanity

https://github.com/rancher/qa-tasks/issues/1263
currently, there's no end to end provisioning test that imports a cluster into rancher
add a solution that works with Corral to import a cluster. 
Also addressed some changes to the sanity job. 
tested locally, jenkins jobs upon request.

[2.9] adding an import test to the go framework

---

go.mod
pkg/apis/go.mod

* https://github.com/rancher/rancher/issues/45152
* Added missing endpointslice dependency overwrite in `go.mod` and `pkg/apis/go.mod`

[v2.8] Add missing endpointslice dependency

---

tests/v2/integration/catalogv2/ui_plugin_test.go

Some [changes](https://github.com/rancher/ui-plugin-examples/pull/38) in the chart caused the tests to break due to [this](https://github.com/rancher/rancher/blob/82aab25da503e4a2c70976585495ae76020391c8/pkg/controllers/dashboard/plugin/fscache.go#L72) check
New [changes](https://github.com/rancher/ui-plugin-examples/pull/39) were made to the chart and the url used in the test is updated
Manual and CI/CD

changing integration test to use new version of uk-locale

---

go.mod
go.sum
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/build.sh
tests/v2/validation/cli/README.md
tests/v2/validation/cli/cli_test.go

As part of broader efforts to fix flaky tests, it was discussed to shift away from the flaky Python tests for the Rancher CLI and transition them over to Go. As such, all of the tests minus apps have been translated. This is because rancher apps has known failures in the Rancher CLI.
Transitioned away from the flaky Python tests and ported over to Go.
Jenkins jobs will be given to reviewers offline.

[v2.9] Convert flaky Python CLI tests to Go

---

go.mod
go.sum
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/build.sh
tests/v2/validation/cli/README.md
tests/v2/validation/cli/cli_test.go

Backport of https://github.com/rancher/rancher/pull/45049.

[v2.8] Convert flaky Python CLI tests to Go

---

go.mod
go.sum
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/build.sh
tests/v2/validation/cli/README.md
tests/v2/validation/cli/cli_test.go

Backport of https://github.com/rancher/rancher/pull/45049.

[v2.7] Convert flaky Python CLI tests to Go

---

go.mod
go.sum
tests/v2/validation/charts/gatekeeper_test.go
tests/v2/validation/charts/istio_test.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/upgrade/cloud_provider_aws_migration.go
tests/v2/validation/upgrade/workload_test.go

Chart installations only support RKE1 clusters. Ultimately for chart installations on the Airgap environment, the chart tests need to be enhanced to include an Alerting Driver chart too.
Add Monitoring and Logging charts' payload mappers. Update chart installs option struct to have cluster meta - which is used within these mappers. Add Alerting Driver installation function that supports RKE1/RKE2/K3s installations.
TODOs:

[2.8] Update Charts Installations in the Validation Tests to Use Cluster Meta

---

go.mod
go.sum
tests/v2/validation/charts/gatekeeper_test.go
tests/v2/validation/charts/istio_test.go
tests/v2/validation/charts/monitoring_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/upgrade/cloud_provider_aws_migration.go
tests/v2/validation/upgrade/workload_test.go

Chart installations only support RKE1 clusters. Ultimately for chart installations on the Airgap environment, the chart tests need to be enhanced to include an Alerting Driver chart too.
Add Monitoring and Logging charts' payload mappers. Update chart installs option struct to have cluster meta - which is used within these mappers. Add Alerting Driver installation function that supports RKE1/RKE2/K3s installations.

[2.7] Update Charts Installations in the Validation Tests to Use Cluster Meta

---

pkg/catalogv2/oci/oci.go
pkg/controllers/dashboard/helm/repo_oci.go

Please check issue for more information. 
When the clusterrepo spec is changed, it should retrigger the OCI handler for syncing with the registry.

Retrigger if the clusterrepo oci spec changed.

---

package/Dockerfile
package/Dockerfile.agent
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent

Both packages needed to be added after the transition from `bci-base` to `bci-micro` (#44348). The former contains key Linux utilities such as `mount` and `umount`, which are needed by upstream dependencies. The latter contain static certificate files which are needed for the `update-ca-certificates` operation that takes place at `entrypoint.sh`.
Fixes https://github.com/rancher/rancher/issues/45199.
Potentially linked to https://github.com/rancher/rancher/issues/45199.

[v2.9] Add `util-linux` `ca-certificates-mozilla`

---

pkg/controllers/management/clusterconnected/clusterconnected.go
pkg/controllers/managementuser/healthsyncer/healthsyncer.go
pkg/data/management/podadmissionconfigurationtemplate_data.go
pkg/data/management/podadmissionconfigurationtemplate_data_test.go

https://github.com/rancher/rancher/issues/43150
Rancher can create two built-on PSACTs (`rancher-prviledge` and `rancher-restricted`) on start-up but does not have the ability to update them if they already exist. It becomes a problem that any update on the built-in PSACT templates (in the newer version of Rancher) will not be applied to the existing PSACT after upgrading Rancher. 
The chance of users modifying the built-in PSACTs is low, normally they would/should create a new one based on the built-in ones and make any customization they need there. But we need to handle the possible situation to minimize any negative impact on user experience.
This PR is to add support for updating the built-in PSACTs on Rancher's start-up.
With this PR, Rancher will update the built-in PSACTs such …

Add support for updating builtin PSACTs

---

pkg/api/steve/supportconfigs/generator.go
pkg/api/steve/supportconfigs/generator_test.go

for CSP billing auditing purposes
The csp-adapter functionality for Rancher PAYG instances is being enhanced with an archive of the previous billing data so that customers and support can validate what was submitted to AWS/Azure to generate their bill. Currently this data only exists in a configmap on the customer system, which makes it difficult to access for either the customer or support.
Include the metering archive in the supportconfig tarball.
Scenario 1: Metering archive is not available
1. Deploy Rancher Prime (with CSP Adapter, the BOYL version) in AWS.
2. Generate a supportconfig tarball
3. Verify that the supportconfig tarball contains `config.json` only.
Scenario 2: Metering archive is available
1. Deploy Rancher Prime (with CSP Adapter, the PAYG version) in AWS.
2. Generate a …

Include metering archive in support config

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Bump aks-operator Go module version used in Rancher.
The new release addresses a bug reported in https://github.com/rancher/aks-operator/issues/132#issuecomment-2082011679
Related to https://github.com/rancher/charts/pull/3842

[v2.9] Bump aks-operator to v1.3.0-rc12

---

tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go

jenkins was failing on 2.7 for this test due to go 1.20 not supporting slice package
wrote my own slice.contains function.

[2.7] Fix Slice Package Dependency in Tests

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Fixes: #45010
Fixes: #45005
The upstream package (github.com/manicminer/hamilton) was dropping errors from the underlying Go HTTP Transport, this was being reported by the Go HTTP Client as an error, and the original error was lost, for example, if you had egress rules that prevented access, any "connection" errors would be lost.,
This changes the behaviour of our use of the hamilton msgraph client to return errors when connecting which will pass the message through.
This is a reimplementation of the fix that was upstreamed here https://github.com/manicminer/hamilton/pull/280
This would require blocking of access to Azure's endpoints, or a misconfiguration of the Graph API custom endpoint, see https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions- …

Backport hamilton error fix

---

build.yaml
pkg/buildconfig/constants.go

Awaiting QA to promote `*-rc1` to stable - preparing draft in advance.
(This PR will be squash merged; or just as likely rebased before undrafted.)

[v2.8] bump default shell version to v0.1.24

---

go.mod
go.sum
tests/v2/validation/deleting/README.md
tests/v2/validation/deleting/delete_init_machine.go
tests/v2/validation/deleting/delete_init_machine_test.go

adds a test to delete the init node machine of a downstream rke2/k3s cluster, then verify successful deletion
Issue:
https://github.com/rancher/rancher/issues/42709
Link to previous PRs (draft) for additional context around requested changes:
https://github.com/rancher/rancher/pull/44155
https://github.com/rancher/rancher/pull/45113

Adds automated support to test Init node cannot be deleted issue

---

tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go
tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
tests/v2/validation/snapshot/snapshot_restore_test.go
tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go

In our `snapshot` package, we allow the support of local snapshots and s3 snapshots. However, we don't have a way to exactly know when we are testing which use-case.
Updated the name to check if S3 is enabled in the cluster. If it is, then specify `S3` in the name. If not, then specify `local`.
Manually tested RKE1/RKE2/K3S with snapshot restore ETCD only.
Jenkins jobs will be given offline to reviewers.

[v2.9] Update snapshot names to use S3 or local

---

build.yaml
pkg/buildconfig/constants.go

Releases rancher-webhook to v0.4.5 for to 2.8.

Release rancher-webhook v0.4.5

---

pkg/apis/catalog.cattle.io/v1/types.go
pkg/apis/catalog.cattle.io/v1/zz_generated_deepcopy.go
pkg/catalogv2/oci/client.go
pkg/catalogv2/oci/client_test.go
pkg/controllers/dashboard/helm/repo.go
pkg/controllers/dashboard/helm/repo_oci.go
pkg/controllers/dashboard/helm/repo_oci_test.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Previously, the retries were handled by the oras library, and because of that, the handler would get stuck while waiting for it. This PR implements changes that make the handler itself handle the retries, instead of the oras library.

[2.9] Making the OCI cluster repo handler take care of retries instead of using the oras library

---

go.mod
go.sum
tests/v2/validation/deleting/delete_init_machine.go
tests/v2/validation/deleting/delete_init_machine_test.go

Rancher PR for shepherd PR https://github.com/rancher/shepherd/pull/181.

[v2.9] Fix delete init node for RKE2 clusters

---

go.mod
go.sum
tests/v2/validation/deleting/delete_init_machine.go
tests/v2/validation/deleting/delete_init_machine_test.go

Backport of https://github.com/rancher/rancher/pull/45413.

[v2.8] Fix delete init node for RKE2 clusters

---

go.mod
go.sum
tests/v2/validation/deleting/delete_init_machine.go
tests/v2/validation/deleting/delete_init_machine_test.go

Backport of https://github.com/rancher/rancher/pull/45413.

[v2.7] Fix delete init node for RKE2 clusters

---

pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/authconfig_test.go
pkg/controllers/management/secretmigrator/register.go

The secret for accessing OpenLDAP for lookups when using Okta is stored inside the `AuthConfig`, this should be migrated (as happened for the Shibboleth config) to a separate `Secret` resource.
Very similar to the fix for Shibboleth, this includes a `Migration` which splits the password to a `Secret` and updates the `AuthConfig` to reference the `Secret`.
Configure Okta and OpenLDAP, the password should not be stored in the `AuthConfig` and the password field should point to a `Secret` which contains the password.
Configured OpenLDAP and confirmed that the secret is not stored in the `AuthConfig` resource.
* Unit
* None
* _REMOVE NOT …

Okta ldap password for release/v2.9

---

pkg/provisioningv2/kubeconfig/manager.go
pkg/provisioningv2/kubeconfig/manager_test.go
pkg/rancher/migrations.go

If we upgrade to use CAPI 1.5.0 or higher its required that the secrets used for kubeconfigs contain a label `cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}`. Without this, the CAPI cluster/machine reconcilers will fail with a `failed to retrieve kubeconfig secret for Cluster` error.
See the CAPI migration guide: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md#other
This adds the required label when we create the secret that contains the kubeconfig. A migration has also been added thats called at startup (on leader election) that will add the label to any kubeconfig secret for an RKE2 cluster.
Even though 1.4.4 will be used with the un-embedding it would be good to get this change in upfront.
1. Create an RKE2 based …

[v2.7] feat: added capi label to kubeconfig secrets

---

pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/authconfig_test.go
pkg/controllers/management/secretmigrator/register.go
tests/integration/suite/test_dns.py

Backport of #45507 for release/v2.8
Same as it was for #45507 
* Unit
* None
_TODO_
* _TODO_

Okta openldap v2.8 backport

---

pkg/provisioningv2/kubeconfig/manager.go
pkg/provisioningv2/kubeconfig/manager_test.go

Related issue: https://github.com/rancher/rancher/issues/42402
Reverts rancher/rancher#42318
The PR needs to be rebased -- it was referring to constants that are undefined:
```
pkg/provisioningv2/kubeconfig/manager.go:294:59: undefined: capi.ClusterLabelName
pkg/provisioningv2/kubeconfig/manager.go:380:10: undefined: capi.ClusterLabelName
```

Revert "[v2.7] feat: added capi label to kubeconfig secrets"

---

go.mod
go.sum
tests/v2/validation/provisioning/rke1/README.md

This is the rancher/rancher counterpart to shepherd PR https://github.com/rancher/shepherd/pull/194. Jenkins jobs will be given to reviewers offline.

[v2.9] Fix RKE1 nodetemplates to include cloud credentials

---

pkg/api/steve/catalog/plugin.go
pkg/api/steve/catalog/plugin_test.go
tests/v2/integration/catalogv2/ui_plugin_test.go

This PR uses `mime.TypeByExtension` to set the `Content-Type` header of proxied extension requests. If it fails to get the type, we use the one returned by the request.

setting content type header for successful proxied requests

---

go.mod
go.sum
tests/v2/validation/nodescaling/scaling_node_driver_aks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_eks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_gke_test.go
tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/eks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/gke/hosted_provisioning_test.go

Hosted Provisioning test cases are already tested in rancher/hosted-providers-e2e repo, so it has been decide to deprecate these tests and mark them as skip.

[v2.7] Deprecate hosted provisioning, nodescaling tests and bump rancher/shepherd version to 8ffe7983dc26

---

go.mod
go.sum
tests/v2/validation/nodescaling/scaling_node_driver_aks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_eks_test.go
tests/v2/validation/nodescaling/scaling_node_driver_gke_test.go
tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/eks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/gke/hosted_provisioning_test.go

Hosted Provisioning test cases are already tested in rancher/hosted-providers-e2e repo, so it has been decide to deprecate these tests and mark them as skip.
```
=== RUN   TestHostedEKSClusterProvisioningTestSuite
hosted_provisioning_test.go:81: This test has been deprecated; check https://github.com/rancher/hosted-providers-e2e for updated tests
--- SKIP: TestHostedEKSClusterProvisioningTestSuite (0.00s)
Test ignored.
PASS
Process finished with the exit code 0
```

[v2.9] Deprecate hosted provisioning, nodescaling tests and bump rancher/shepherd version to 9f5a881

---

cmd/agent/main.go
go.mod
pkg/agent/clean/dupe_bindings.go
pkg/agent/clean/orphan_bindings.go
pkg/auth/api/secrets/cleanup.go
pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/globalroles/globalrole_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/project_cluster_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/management/auth/role_template_lifecycle.go
pkg/controllers/management/restrictedadminrbac/cluster.go
pkg/controllers/management/restrictedadminrbac/fleet.go
pkg/controllers/managementuser/rbac/crtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/data/management/role_data.go
pkg/rancher/rancher.go
tests/v2/codecoverage/agent/main.go

The package `go-multierror` from [here](https://github.com/hashicorp/go-multierror) uses the MPL 2.0 license, which is considered an incompatible license in rancher.  
Multierrors can be replaced with `errors.Join` and get similar results. Multierror is formatted a little nicer, but both combine errors and can be checked for the existence of specific errors.
Here is an example of the formatting difference:
https://go.dev/play/p/qYefpBQ81GL
While I was working on removing `multierror`, I also replaced `https://github.com/pkg/errors` with the `errors` standard library. Specifically, I replaced instances of `errors.Wrap(err, "message")` with `fmt.Errorf("message: %w", err)`. Both wrap the error and create the same error message. The motivation behind this is that …

Replace multierror.Append with errors.Join

---

cmd/agent/main.go
go.mod
pkg/agent/clean/dupe_bindings.go
pkg/agent/clean/orphan_bindings.go
pkg/auth/api/secrets/cleanup.go
pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/globalroles/globalrole_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/project_cluster_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/management/auth/role_template_lifecycle.go
pkg/controllers/management/restrictedadminrbac/cluster.go
pkg/controllers/management/restrictedadminrbac/fleet.go
pkg/controllers/managementuser/rbac/crtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/data/management/role_data.go
pkg/rancher/rancher.go
tests/v2/codecoverage/agent/main.go

Issue:
CI is failing across the v2.9 PRs. after https://github.com/rancher/rancher/pull/45344 was merged much after CI has passed on it and incompatible changes got into `release/v2.9` between CI pass and actual merge time.
Solution
This reverts commit https://github.com/rancher/rancher/commit/e7fe01a32, reversing changes made to https://github.com/rancher/rancher/commit/60d17a338ccfbe0ca9a7c45d40aa51bb734ac0a7.

Revert "Replace multierror.Append with errors.Join (#45344)"

---

go.mod
go.sum

We observed high memory and CPU usage due to this dependency.
We agreed on temporarily use a fork of this library in order to include performance fixes, while working on a permanent solution for 2.9. This is based on the current `0.46.0` version being used plus this patch: https://github.com/manicminer/hamilton/pull/271
Changes have been testes both locally and using debug builds.

[2.8] Use patched hamilton library

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Fixes: #45010
Fixes: #45005
The upstream package (github.com/manicminer/hamilton) was dropping errors from the underlying Go HTTP Transport, this was being reported by the Go HTTP Client as an error, and the original error was lost, for example, if you had egress rules that prevented access, any "connection" errors would be lost.,
This changes the behaviour of our use of the hamilton msgraph client to return errors when connecting which will pass the message through.
This is a reimplementation of the fix that was upstreamed here https://github.com/manicminer/hamilton/pull/280
This would require blocking of access to Azure's endpoints, or a misconfiguration of the Graph API custom endpoint, see https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions- …

Improve error from communicating with Azure API.

---

scripts/provisioning-tests

https://github.com/rancher/rancher/issues/45577
Starting with `v1.27.11+rke2r1`, `certificate rotation` operations suddenly started taking significantly more time.
Temporarily pin RKE2 version for provisioning tests to `v1.27.10+rke2r1`.
Repeatedly ran `make provisioning-tests` and timed result.
Summary: Pinned RKE2 version for tests to `v1.27.10+rke2r1`
N/A
N/A
N/A

[release/v2.9] Pin provisioning-tests RKE2 version to v1.27.10+rke2r1 to unblock CI

---

pkg/settings/setting.go

https://github.com/rancher/dashboard/issues/7366
Presently, all banners are in a single setting as a single JSON blob - this makes it hard for users wishing to individually configure banners outside of the UI.
Add optional individual banner settings that will be used if defined, rather than the single setting we currently have.
UI will add automated e2e tests to cover this feature and the correct operation of these  new settings.

Add new UI Settings for page banners

---

pkg/settings/setting.go

https://github.com/rancher/dashboard/issues/11047
Need a way to more easily enable/disable extensions without install/uninstall - especially useful for built-in extensions that we might want to allow the user to disable.
Add a new setting `ui-extensions` that can be used to store the required configuration.
Testing will be covered by end-to-end and unit tests in the relating UI work.

Add new setting for UI Extension configuration

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

- Update rke tag from `v1.6.0-rc4` to `v1.6.0-rc5`
- https://github.com/rancher/rancher/issues/45567

[v2.9] Tag update for May patches 

---

pkg/data/dashboard/rbac.go

https://github.com/rancher/dashboard/issues/7366
Presently, all banners are in a single setting as a single JSON blob - this makes it hard for users wishing to individually configure banners outside of the UI.
Add optional individual banner settings that will be used if defined, rather than the single setting we currently have.
This is a follow-on to PR: https://github.com/rancher/rancher/pull/45528
That PR added the new settings.
This PR makes an update so that these new individual banner settings can be retrieved before login - this ensures if they are used, we can show the banners on the login screen.
Note that `ui-banners` is already exposed this way, and this is about allowing the same for the 3 new settings which specify the banners individually, rather than in a single setting.
UI …

UI: Allow separate banner settings to be fetched before login

---

scripts/provisioning-tests
scripts/test

As per the linked issue, integration and v2prov tests run Rancher which deploys certain charts like `rancher-webhook` making it dependent on and producing additional load for our Git mirror https://git.rancher.io/charts - so when it's down/unstable CI fails blocking merging of PRs etc.
Leverage `ChartDefaultURL` setting introduced in https://github.com/rancher/rancher/pull/43530 via `CATTLE_CHART_DEFAULT_URL` to pull Rancher charts from https://github.com/rancher/charts instead.
Note: Commits will be squashed on merge
No testing is required, part of CI
Initial commit had `CATTLE_CHART_DEFAULT_URL` set to invalid URL and the related build has failed due to failure to deploy webhook - https://drone-pr.rancher.io/rancher/rancher/39661/6/2
Then the setting was changed to …

Reduce reliance on Git Mirror for CI tests

---

pkg/auth/audit/audit.go
pkg/auth/audit/audit_test.go

https://github.com/rancher/rancher/issues/44359
If the audit log handler attempts to redact info from data that is not valid json it returns invalid json, which later causes errors when compacting the full audit log json.
Return valid json, while exposing the errors that occur while handling response and request bodies.
Steps in the issue are valid. Was not able to reproduce locally, but testing in EKS works as described.
1. Deploy rancher in EKS
2. Deploy / Modify / Scale workloads via rancher UI
3. View audit logs for values at `.responseBody` for error content
* Unit
Summary: Add unit test(s) to test for invalid json

Handle redaction errors in audit log

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/45645
The bug was reported in the standalone RKE cluster (https://github.com/rancher/rke/issues/3587),  but it is possible to be triggered in Rancher as well.  
If we provision or edit an RKE1 node-driver cluster and set the `extra_env` for the `kube-api` server, Rancher will fail to create or update the cluster with an error message like below 
`cluster health check failed: Failed to communicate with AP| server during namespace check: Get "https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces/kube-system?timeout=45s": dial tcp xxx.xxx.xxx.xxx:6443: connect: connection refused:[controlPlanel
Failed to upgrade Control Plane: [[Failed to create [kube-apiserver] container on host [xxx.xxx.xxx.xxx]: Failed to create Docker container [kube-apiserver] on host …

[2.9] Bump RKE to v1.6.0-rc6

---

pkg/capr/planner/planner.go
pkg/controllers/capr/managesystemagent/managesystemagentplan.go
pkg/controllers/capr/managesystemagent/managesystemagentplan_test.go
pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go

* https://github.com/rancher/rancher/issues/44922
* PSP is completely removed from k8s 1.29 onwards
* * [x] https://github.com/rancher/system-charts/pull/606
* * [x] https://github.com/rancher/charts/pull/3951
* Remove PSP checks from SUC charts and it's upgrade process
* Created a rancher server with `v2.8.3`. Deployed rke2 1.28 k8s downstream cluster.
* Upgraded rancher server to custom image with the PSP checks removed.
* Rancher server and SUC chart upgrade went successful, PSP was removed from the `values.yaml` of SUC chart.

[v2.9] Remove PSP checks from SUC charts and it's upgrade process

---

pkg/controllers/dashboardapi/settings/settings.go
pkg/controllers/dashboardapi/settings/settings_test.go
pkg/settings/setting.go

Rancher needs a new setting for specifying the TLS mode to be used by agent. In 2.9, the Default value is `strict`. Rancher needs to keep the existing `system-store` Default value (from 2.7 and 2.8) for upgrades to 2.9. Only for new installations of 2.9 should Rancher use the new `strict` Default value.
Add a new setting. And implement functionality that allows to add a special `DefaultOnUpgrade` value to any setting. Rancher will then be more reserved about accepting the new Default value on upgrades, if it has changed. Some settings' Default may need to be the same on upgrades for backward compatibility.
To do so, augment the Setting struct type with a new `DefaultOnUpgrade` field. 
DefaultOnUpgrade represents a desired Default value that the setting should have on upgrade from a …

[2.9] Add new setting agent-tls-mode

---

build.yaml
pkg/buildconfig/constants.go

Bump shell version for new RC - increments kubectl to more appropriate version for Rancher 2.9.
- PR bumping shell kubectl to 1.28: https://github.com/rancher/shell/pull/237
- bump helm to v3.15.1-rancher2: https://github.com/rancher/shell/pull/241

bump shell rc version

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/systemtemplate/import.go

Ensure cached backed API is available in downstream clusters without manually applying feature setting in downstream clusters.
Currently separate steps are needed to enable the feature upstream and downstream: https://confluence.suse.com/display/RANQA/Rancher+Setup+with+Vai+Cache+Setup
Propagate the feature setting from upstream to downstream on activation.
1. Check that feature is off. From a machine with a kubeconfig pointing to any downstream cluster:
```sh
pod=$(kubectl -n cattle-system get pods -l app=cattle-cluster-agent --no-headers -o custom-columns=name:.metadata.name) 
kubectl exec -n cattle-system ${pod} -- ls | grep .db
```
Output should be empty.
2. Turn on the feature flag upstream
1. In the upper left corner, click **☰ > Global Settings > Feature Flags**.
1. Go to …

Steve SQLite cache: propagate setting downstream

---

pkg/data/dashboard/repo.go
pkg/settings/setting.go

Backport of #43530 to `release/v2.8`.
Refers to #45677.
* Add default chart URL setting
This adds new settings to control the origin of system, partner and RKE2 charts, which can now be tested with custom versions prior to releasing corresponding RCs to their respective repositories:
* `ChartDefaultURL` (`rancher/charts`)
* `PartnerChartDefaultURL` (`rancher/partner- charts`)
* `RKE2ChartDefaultURL` (`rancher/rke2- charts`)
These options are intended for internal use only. When in use, Rancher issues a warning suggesting to unset them should any issues be encountered when fetching charts.
* Group settings by repo type
This moves each default branch setting, for the partner and RKE2 charts repositories, next to the default URL settings for the respective repository, to make configuration …

[v2.8] Add charts url setting (#43530)

---

build.yaml
pkg/buildconfig/constants.go

##Issue: 
rancher/rancher#45461
##Problem:
Support k8s 1.29
##Testing:
scenario 1 (fresh install):
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 104.0.0+up4.0.0-rc8
scenario 2 (upgrade scenario):
Start with an EKS cluster (k8s version 1.28), install rancher 2.8.4 with csp-adapter 3.0.1
Upgrade rancher to locally built rancher with cspAdapterMinVersion: 104.0.0+up4.0.0-rc8
Update charts url repo/branch and …

[v2.9] csp adapter 4.0.0-rc8

---

pkg/data/management/role_data.go

Restricted Admins are not able to create Standard Users. They get the following error:
```
admission webhook "rancher.cattle.io.globalrolebindings.management.cattle.io" denied the request: errors due to escalation: user "u-pvmqd" (groups=["system:authenticated" "system:cattle:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["secrets"], Verbs:["create"]}
```
The Restricted Admin permission specified `secret` when it should be `secrets`.
- Create a Restricted Admin user without Standard User as well
- Login as the Restricted Admin
- Create a Standard User
- Before the change, failure. After, success

Restricted Admins can't create Standard Users due to typo in rules

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

https://github.com/rancher/rancher/issues/45656
https://github.com/rancher/rke/issues/3596
The bug was reported in the standalone RKE cluster (https://github.com/rancher/rke/issues/3587),  but it is possible to be triggered in Rancher as well.  
If we provision or edit an RKE1 node-driver cluster and set the `extra_env` for the `kube-api` server, Rancher will fail to create or update the cluster with an error message like below 
`cluster health check failed: Failed to communicate with AP| server during namespace check: Get "https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces/kube-system?timeout=45s": dial tcp xxx.xxx.xxx.xxx:6443: connect: connection refused:[controlPlanel
Failed to upgrade Control Plane: [[Failed to create [kube-apiserver] container on host [xxx.xxx.xxx.xxx]: Failed to create …

[2.8] Bump RKE to v1.5.11-rc1

---

scripts/provisioning-tests

https://github.com/rancher/rancher/issues/45577
https://github.com/rancher/rancher/pull/45660
An accidental usage of `.channels[0].latest` was introduced (which is a reversion to prior logic that was used for `provisioning-tests`) when we pinned RKE2 provisioning tests to `v1.27.10+rke2r1`.
Revert the usage of `.channels[0].latest` to `.releases[-1].version`

Use correct version of K3s in provisioning-tests

---

pkg/agent/clean/adunmigration/ldap.go
pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/providers/activedirectory/activedirectory_client.go
pkg/auth/providers/common/ldap/ldap_util.go
pkg/auth/providers/ldap/ldap_client.go
pkg/auth/providers/ldap/ldap_provider.go

During the investigation and WIP for https://github.com/rancher/rancher/issues/37994 I did some cleanup that can be safely merged in the codebase.
(updated description based on requested changes)
In the past we had an issue performing an LDAP search request, because of a wrong scope. To avoid this issue this small PR adds a `NewWholeSubtreeSearchRequest` and a `NewBaseObjectSearchRequest` func in the ldap_util, in order to create a specific search request with some parameters already set to some defaults:
```go
// NewWholeSubtreeSearchRequest will return a NewDefaultSearchRequest with a ScopeWholeSubtree scope
func NewWholeSubtreeSearchRequest(baseDN, filter string, attributes []string) *ldapv3.SearchRequest {
return NewDefaultSearchRequest(baseDN, filter, ldapv3.ScopeWholeSubtree, …
```

[v2.9] LDAP utils cleanup

---

tests/v2/validation/auth/openldap.go
tests/v2/validation/auth/openldap_test.go

Open LDAP enabling and disabling happen manually.
Adds initial Open LDAP test cases that enable and disable the auth.

[2.9] Add validation tests to enable and disable Open LDAP

---

tests/v2/validation/auth/openldap.go
tests/v2/validation/auth/openldap_test.go

Open LDAP enabling and disabling happen manually.
Adds initial Open LDAP test cases that enable and disable the auth.

[2.8] Add validation tests to enable and disable Open LDAP

---

tests/v2/validation/auth/openldap.go
tests/v2/validation/auth/openldap_test.go

Open LDAP enabling and disabling happen manually.
Adds initial Open LDAP test cases that enable and disable the auth.

[2.7] Add validation tests to enable and disable Open LDAP

---

tests/v2/validation/charts/installations_test.go

Currently, chart tests in an Airgap Environment happen manually.
Add a new validation test suite that installs;
- Monitoring
- Alerting
- Logging
- Istio
And checks all pods are coming from the registry. 
Sanity checks will be provided offline.

[2.9] Add a New Chart Test Suite that Installs Monitoring, Alerting, Istio and Logging

---

tests/v2/validation/charts/installations_test.go

Currently, chart tests in an Airgap Environment happen manually.
Add a new validation test suite that installs;
- Monitoring
- Alerting
- Logging
- Istio
And checks all pods are coming from the registry. 
Sanity checks will be provided offline.

[2.8] Add a New Chart Test Suite that Installs Monitoring, Alerting, Istio and Logging

---

tests/v2/validation/charts/installations_test.go

Currently, chart tests in an Airgap Environment happen manually.
Add a new validation test suite that installs;
- Monitoring
- Alerting
- Logging
- Istio
And checks all pods are coming from the registry. 
Sanity checks will be provided offline.

[2.7] Add a New Chart Test Suite that Installs Monitoring, Alerting, Istio and Logging

---

tests/v2/validation/schemas/README.md
tests/v2/validation/schemas/resources/crd_create.yaml
tests/v2/validation/schemas/schemas.go
tests/v2/validation/schemas/schemas_test.go

QA Task: https://github.com/rancher/qa-tasks/issues/1277
Following P0 tests have been automated in this PR:
Note:
- This is applicable only for 2.9 so no backports will be created.

Automate P0 tests for GH41301

---

pkg/controllers/management/auth/manager.go
pkg/features/feature.go
pkg/rbac/common.go

`external-rules` feature flag was added in Rancher v2.7 and v2.8 to help admins with the transition of the new `RoleTemplate` field `ExternalRules`. That's no longer needed in Rancher v2.9
Remove `external-rules` feature flag. It will work as it is always enabled, and can't be disabled. 
* Unit
* None
_TODO_
* _TODO_

Remove external-rules feature flag

---

tests/integration/suite/test_clustertemplate.py

https://github.com/rancher/rancher/issues/45882
the support for v1.25 and v1.26 k8s is removed from KDM v2.9 and python test cases are still running on v1.25 CI.
updated the kubernetes version to v1.27.x for python test cases. so that CI passes.
* Unit
* None
_TODO_
* _TODO_

[v2.9] update kubernetes version for cluster to v1.27.x for python integration tests

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/providers/genericoidc/genericoidc_provider.go
pkg/auth/providers/oidc/oidc_provider.go
pkg/auth/providers/oidc/oidc_provider_test.go
pkg/client/generated/management/v3/zz_generated_generic_oidcconfig.go
pkg/client/generated/management/v3/zz_generated_key_cloak_oidcconfig.go
pkg/client/generated/management/v3/zz_generated_oidc_config.go

This PR adds a check for an ACR value, which is an optional configuration.  It piggybacks on https://github.com/rancher/rancher/pull/45366
Also includes a fix to allow an empty Authentication URL, which is ok now since it will just trigger "discovery".
If a required ACR value is present in the authconfig (supplied when configuring the auth provider), verify that the correct value is present in the token when the user logs in.
Unit tests added
Configured Keycloak OIDC to provide an ACR value and then configured Rancher' authconfig to require it.  Logins with the correct ACR work while those without will fail.
* Unit
This is added for the new genericoidc implementation, so I would not expect any existing functionality to be affected.
Existing / newly added …

Add ACR validation check for OIDC auth

---

pkg/controllers/dashboard/fleetcharts/controller.go
pkg/controllers/dashboard/fleetcharts/controller_test.go

This ensures that Fleet is installed with Rancher's configured agent TLS mode, and that any change to that setting leads to Fleet being reinstalled.
Depends on [fleet#2507](https://github.com/rancher/fleet/pull/2507).
The new `agent-tls-mode` setting was not taken into account when installing Fleet.
Included that setting in values used to install the `fleet` chart.
1. Installed Rancher via Helm, built locally using `dev-script/build-local.sh`:
```
$ helm upgrade --install rancher rancher-latest/rancher --devel \
--namespace cattle-system --create-namespace \
--set bootstrapPassword=admin \
--set replicas=1 \
--set hostname=172.17.0.2.sslip.io \
--set rancherImageTag=test-strict-tls \
--set extraEnv[0].name=CATTLE_CHART_DEFAULT_BRANCH \
--set …
```

Honor agent TLS mode when installing Fleet

---

go.mod
go.sum

Bumps steve to include 1.30 support and fixes for schema definitions
#45157 
CRD fields which weren't included in openapi/v2 endpoints weren't included in the schema definitions. See #45157 and rancher/steve#215 for more.
Steve was bumped. See rancher/steve#215 for more details on the full solution.
N/A - see the steve PR.

Bumping steve

---

scripts/provisioning-tests
scripts/test

(cherry picked from commit c8097db7b89900f9cbd11fd3178094a27e8ea071)
Direct cherry-pick of https://github.com/rancher/rancher/pull/45681 (the same description applies)

[Backport v2.8] Reduce reliance on Git Mirror for CI tests

---

go.mod
go.sum

Bumps Shepherd version to `v0.0.0-20240628195837-fce9bdc2bcf0`

[2.7] Bump Shepherd Version

---

build.yaml
pkg/buildconfig/constants.go

We need 1.30 k8s support in webhook
- Bumps webhook to a version that supports k8s 1.30

Bump rancher-webhook to v0.5.0-rc10

---

build.yaml
pkg/buildconfig/constants.go

per title, this just ensures that Rancher RCs/alphas are using the newest Shell RC.

[v2.9] bump shell RC version to newest

---

build.yaml
pkg/buildconfig/constants.go

rancher/rancher#45744
Problem
Support k8s 1.30
Testing
scenario 1 (Fresh Install):
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 104.0.0+up4.0.0-rc9.
Start with an EKS cluster (k8s version 1.28), install rancher 2.8.4 with csp-adapter 3.0.1.
Upgrade rancher to locally built rancher with cspAdapterMinVersion: 104.0.0+up4.0.0-rc9
Update charts url repo/branch and upgrade csp-adapter version to 104.0.0+up4.0.0-rc9
Upgrade Management and compute node to K8s 1.30. Validated the support config and licence entitlement functionality. Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. Scaled down the cluster to 17 nodes, validated that the out-of-compliance message is no longer displayed. Scaled back up to 21 …

Updated cspadapter version 4.0.0-rc9

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/authconfig_test.go

This ensures that when Okta is used with OpenLDAP and the password is stored in the AuthConfig, it will be split out into a separate secret. 
This adds an additional migration condition and splits the secret out using the same logic as is used for Shibboleth.
Configure Okta with OpenLDAP and the password will appear in the authconfig/okta resource.
Upgrading to code with this fix will split it out and a secret is created `serviceAccountPassword: cattle-global-data:oktaconfig-serviceaccountpassword` with a new condition `OktaPasswordMigrated`.
* Unit
* None …

Fix the storage of Okta Config passwords.

---

pkg/multiclustermanager/app.go
tests/controllers/README.md
tests/controllers/common/common.go
tests/controllers/globalroles/globalrole_test.go

This PR adds some initial integration tests to Global Roles. It covers 4 basic create cases
1. Testing that the cluster role gets created and uses generated name
2. Testing that the cluster role gets created and uses given name based on annotation
3. Creating a global role with namespaced rules creates the right roles in the right namespaces
4. Creating a global role with catalog rules (ie the resource `template`) creates a role in `cattle-global-data`
To make it as easy as possible to add new tests, I kept the tests very simple. The test is this structure
```
struct {
name        string
globalRole  v3.GlobalRole
roles       []rbacv1.Role
clusterRole rbacv1.ClusterRole
}
```
- name: name of the test
- globalRole: the created global role
- roles: expected roles to be created
- clusterRole: …

Add framework for global role integration tests

---

tests/v2prov/defaults/defaults.go

Bumping provisioning test wait timeout from 15 minutes to 45.

Bump provisioning test wait to 45 minutes

---

tests/v2/validation/rbac/globalrolesv2/globalroles_v2.go
tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go
tests/v2/validation/rbac/globalrolesv2/globalroles_v2_webhook_test.go

Updated the RBAC global role functions to use Wrangler in the GlobalRolesV2 test suite. This includes the functions for creating global roles and getting global role bindings for a user. Also, minor changes are included in globalroles_v2_webhook_test.go file to align with the new function names.
Backport of https://github.com/rancher/rancher/pull/45131

Refactor global role functions to use Wrangler Backport 2.8

---

tests/v2prov/defaults/defaults.go

backport of https://github.com/rancher/rancher/pull/45996

[v2.7] Bump provisioning test wait to 45 minutes

---

tests/v2prov/defaults/defaults.go

backport of https://github.com/rancher/rancher/pull/45996

[v2.8] Bump provisioning test wait to 45 minutes

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump `rancher/cli` to v2.9.0-rc4

[v2.9] Bump `rancher/cli` to v2.9.0-rc4

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump `rancher/cli` to v2.8.6-rc1

[v2.8] Bump `rancher/cli` to v2.8.6-rc1

---

pkg/controllers/dashboard/fleetcharts/controller.go
pkg/controllers/dashboard/fleetcharts/controller_test.go

Backport of [rancher#45842](https://github.com/rancher/rancher/pull/45842) to 2.8.
Depends on [fleet#2577](https://github.com/rancher/fleet/pull/2577).
1. Installed Rancher via Helm, built locally using `dev-script/build-local.sh`:
```
$ helm upgrade --install rancher rancher-latest/rancher --devel \
--namespace cattle-system --create-namespace \
--set bootstrapPassword=admin \
--set replicas=1 \
--set hostname=172.17.0.2.sslip.io \
--set rancherImageTag=2.8-test-strict-tls \
--set extraEnv[0].name=CATTLE_CHART_DEFAULT_BRANCH \
--set extraEnv[0].value=fleetci-dev-v2.8-20240703115101 \
--set extraEnv[1].name=CATTLE_CHART_DEFAULT_URL \
--set extraEnv[1].value=https://github.com/fleetrepoci/charts \
--set extraEnv[2].name=CATTLE_FLEET_VERSION \
--set extraEnv[2].value=999.9.9+up9.9.9
``` …

[2.8] Honor agent TLS mode when installing Fleet

---

pkg/controllers/dashboard/fleetcharts/controller.go
pkg/controllers/dashboard/fleetcharts/controller_test.go

Backport of #45842 to 2.7.
Depends on [fleet#2596](https://github.com/rancher/fleet/pull/2596).
1. (locally) cherry-picked [this commit](https://github.com/rancher/rancher/commit/62e6a3f7f901c4ae426f6641544b29a29a614dd1) to enable Rancher to use a custom charts repository URL
2. Installed Rancher via Helm, built locally using `dev-script/build-local.sh`:
```
$ helm upgrade --install rancher rancher-latest/rancher --devel \
--namespace cattle-system --create-namespace \
--set bootstrapPassword=admin \
--set replicas=1 \
--set hostname=172.17.0.2.sslip.io \
--set rancherImageTag=2.7-test-strict-tls \
--set extraEnv[0].name=CATTLE_CHART_DEFAULT_BRANCH \
--set extraEnv[0].value=fleetci-dev-v2.7-20240704155138 \
--set extraEnv[1].name=CATTLE_CHART_DEFAULT_URL \
--set …
```

[2.7] Honor agent TLS mode when installing Fleet

---

pkg/auth/providers/genericoidc/genericoidc_provider.go
pkg/auth/providers/genericoidc/genericoidc_provider_test.go

https://github.com/rancher/rancher/issues/10053
Searching principals only returns user principals when the principalType was empty. 
Change the SearchPrincipals function to return both User and Group principals when the principalType is empty
Tested by adding both users and groups as cluster member/owner via the search interface in the UI.
Unit tests added
You should notice that the search box when adding cluster/project members will now display a user entry as well as a group entry.  
None: new feature
Existing unit tests adjusted to expect users/groups as intended

Allow GenericOIDC SearchPrincipals to return groups as needed

---

tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go

In the `provisioning` package, we are currently using admin and standard users. Admin testing is not realistic to what customers are doing with the product. Additionally, this adds more overhead to the provisioning tests and should be removed.
Removed the admin tests.

[v2.9] Remove admin user tests from provisioning

---

build.yaml
pkg/buildconfig/constants.go

This RC of webhook unRCs wrangler to use v3.0.0.

Bump webhook to 104.0.0+up0.5.0-rc13

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/rancher/issues/45744
Problem
Support k8s 1.30
Testing
scenario 1 (Fresh Install):
```
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 104.0.0+up4.0.0-rc9.
Start with an EKS cluster (k8s version 1.28), install rancher 2.8.4 with csp-adapter 3.0.1.
Upgrade rancher to locally built rancher with cspAdapterMinVersion: 104.0.0+up4.0.0-rc9
Update charts url repo/branch and upgrade csp-adapter version to 104.0.0+up4.0.0-rc9
Upgrade Management and compute node to K8s 1.30. Validated the support config and licence entitlement functionality. Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. Scaled down the cluster to 17 nodes, validated that the out-of-compliance message is no longer …
```

csp adapter 4.0.0

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump `rancher/cli` to v2.8.6-rc4.
Contains fix for: https://github.com/rancher/rancher/issues/46068
Now releases are available also on GCS:
- https://releases.rancher.com/cli2/v2.8.6-rc4/sha256sum.txt

[v2.8] Bump `rancher/cli` to v2.8.6-rc4

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump `rancher/cli` to v2.9.0-rc5.
Contains fix for: https://github.com/rancher/rancher/issues/46068
Now releases are available also on GCS:
- https://releases.rancher.com/cli2/v2.9.0-rc5/sha256sum.txt

[v2.9] Bump `rancher/cli` to v2.9.0-rc5

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

When fetching the list of groups a user is a member of, the query was not fetching the transitive groups.
This switches to using the TransitiveMemberOf mechanism for listing the groups a user is a member of
* Unit
* None
_TODO_
* _TODO_

[v2.9] Use the Transitive membership when listing groups.

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Please see the issue for more details 
- Unskip the OCI integration test which was skipped due to disk pressure. Now the disk pressure is solved.

Unskip OCI Integration Test

---

pkg/controllers/management/secretmigrator/authconfig.go
pkg/controllers/management/secretmigrator/authconfig_test.go

Enabling Shibboleth was causing a panic.
This was caused when we migrated the original secret and fixed the secret in a single reconciliation.
The second part got a struct that wasn't converted to a ShibbolethConfig
This fix ensures that we convert the Shibboleth struct before looking for the status.
**NOTE**: The tests should be improved further, while the code uses an `UnstructuredClient` the implementation in the test acts like an AuthConfig client, this can be done in a separate PR.
Enable Shibboleth.
* Unit
* None
* If "None" - GH Issue/PR: _LINK TO …

Fix the AuthConfig migrator for Shibboleth secrets.

---

pkg/auth/api/secrets/cleanup_test.go
pkg/auth/api/secrets/fields.go

This ensures that the secret that was split out in the migration is cleaned up.
This adds the OKTA LDAP Credentials to the list of secrets to be removed when OKTA is disabled.
This is a cherry-pick from  #46112
* Unit
* None
_TODO_
* _TODO_

[BACKPORT] v2.8 Trigger removal of OKTA LDAP SA Credentials.

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

There were issues testing https://github.com/rancher/rancher/issues/44952 that were ultimately pinned down on mismatch of `system-agent` versions in `CATTLE_SYSTEM_AGENT_VERSION` and `SystemAgentInstallScript`.
This PR addresses the mismatch and at the same time bump to the latest RC (which doesn't contain any breaking changes for v2.8 and only introduces new functionality slated for v2.9).

Bump system-agent to v0.3.7-rc3

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

[v2.8] Bump `rancher/cli` to v2.8.6

---

pkg/settings/setting.go

- `rancher/dashboard` and `rancher/ui` have both now branched for 2.9, meaning `master` becomes 2.10
- This change ensures the `rancher/rancher` 2.9 branch points to new 2.9 ui builds, rather than master ui builds
- These builds are used, when settings are default, when the version ends in `-head` as an alternative to the embedded builds
Note - Similar to previous branches like https://github.com/rancher/rancher/pull/43273

Ensure rancher 2.9 references 2.9 UI dev builds

---

build.yaml
package/Dockerfile
pkg/buildconfig/constants.go
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/system-agent/releases/tag/v0.3.7
https://github.com/rancher/provisioning/commit/0dc534ccd9a129cfb671b5213cc4654f5e89a58b

[release/v2.9] Bump rancher/system-agent to v0.3.7 and un-RC rancher/provisioning chart in build.yaml

---

go.mod
go.sum
pkg/controllers/managementuser/cavalidator/cavalidator.go
tests/controllers/common/common.go
tests/controllers/globalroles/globalrole_test.go

We have migrated from using `github.com/rancher/wrangler/v2` to `github.com/rancher/wrangler/v3`
This PR finalizes the removal of references to `github.com/rancher/wrangler/v2`

[release/v2.9] Remove github.com/rancher/wrangler/v2

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Changing from git.rancher.io to github.com/rancher to reduce stress on git mirror

changing from git.rancher.io to github.com/rancher in test cases

---

pkg/controllers/management/auth/user_attribute_handler.go
pkg/controllers/management/auth/user_attribute_handler_test.go

Not all use cases are covered with unit tests for the userattribute handler.
This PR adds a couple of new tests:
- A non conflict error is returned when we first try to update userattribute.
- Updating userattribute fails both times.
* Unit
N/A
N/A

[v2.9] Additional tests for userattribute handler

---

pkg/controllers/management/k3sbasedupgrade/deployPlans.go
pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go

https://github.com/rancher/rancher/issues/46147
This PR improves the logging message in the`k3sbasedupgrade` module for better tracking and easier debugging

[2.9] improve the logging for k3s-based-upgrader for imported rke2/k3s cluster

---

pkg/auth/api/user/user_actions.go

Panic setting password to Azure AD (Entra ID) user: https://github.com/rancher/rancher/issues/45451
Setting the password of an external user will cause a panic. This is not related only to AD users.
We are discouraging the use of the local provider, or local users. Also an external user doesn't have a username that can be used to login. So the set password is useless, without a manual workaround, like setting manually a `username` field.
This PR will prevent the set password for users without a `username`:
It also removes the unused `actionName string` and `action *types.Action` arguments from the func signatures.

[v2.9] Prevent set password of external users

---

go.mod
go.sum
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/eks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/gke/hosted_provisioning_test.go
tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/template_test.go

- Changed provisioning tests to use TimeoutRKEReport and TimeoutClusterReport

[2.7] Implemented time out report to log cluster status and condition information to the provisioning tests

---

tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/eks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/gke/hosted_provisioning_test.go
tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/template_test.go

- Changed provisioning tests to use TimeoutRKEReport and TimeoutClusterReport

[2.8] Implemented time out report to log cluster status and condition information to the provisioning tests

---

pkg/controllers/provisioningv2/cluster/controller.go

When creating a custom cluster with a system agent data directory, the custom cluster registration command does not include the `CATTLE_AGENT_VAR_DIR` env var.
When generating a mgmt cluster from a prov cluster, insert the `CATTLE_AGENT_VAR_DIR` env var if the system agent data dir is configured.
Tested manually, webhook only validates the provisioning cluster env vars so there is no issue adding it into the mgmt cluster object, and confirmed the clsuter registration token which populates the registration command in the UI was formatted correctly (confirmed in backend & frontend).
Would be a good idea to test all cluster registration commands for RKE2/K3s clusters, so confirm linx+windows, and insecure/secure commands.
N/A

[46362] Add CATTLE_AGENT_VAR_DIR to mgmt cluster env vars

---

pkg/capr/planner/etcdrestore.go

When doing a etcd snapshot restore after upgrading the rke2 cluster k8s version the cluster hangs and all pods on the control plane remain in a pending state.
Add `RKE2_DATA_DIR` and `K3S_DATA_DIR` to killall calls within the planner, which will cause the manifests to be successfully removed.
Confirm etcd restore happens successfully for both RKE2 and K3s provisioned clusters.
Manually confirmed RKE2 & K3s clusters perform a restore
* None
* If "None" - Reason: Existing tests will validate this once this is merged and KDM bumps RKE2/K3s versions to a version which includes the fixes required on the distro side:
* https://github.com/rancher/rke2/issues/6292
* https://github.com/k3s-io/k3s/issues/10471
N/A (no considerations besides regular test cases).
Would be …

[46066] Add data-dir support to killall in etcd restore

---

scripts/provisioning-tests
scripts/retry

Occasionally, the webhook may fail to deploy during `provisioning-tests`. 
Dump Rancher logs if webhook fails to deploy.

[46412] Dump rancher logs when webhook fails to deploy

---

pkg/capr/common.go
pkg/capr/planner/idempotent.go
pkg/controllers/capr/managesystemagent/managesystemagent.go

The `system-agent-upgrader` SUC plan does not contain the environment variables for the `system-agent` data directory (`CATTLE_AGENT_VAR_DIR`), so when the system upgrade controller applies the plan, the previous configuration is lost and the default of `/var/lib/rancher/agent` is used.
Add the `CATTLE_AGENT_VAR_DIR` env var to the `system-agent-upgrader` SUC plan if the data directory is configured for the `system-agent`.
Manually tested that after the `system-agent-upgrader` plan was run successfully, that the `/var/lib/rancher/agent` directory does not exist.
* None
* If "None" - Reason: Not currently feasibly to create tests for this usecase.
* If "None" - GH Issue/PR: https://github.com/rancher/rancher/issues/46413
Should be tested both with and without a …

[46361] Add system-agent data-dir env var to suc plan

---

pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go
pkg/controllers/management/authprovisioningv2/cluster.go
pkg/controllers/management/authprovisioningv2/cluster_test.go

User loses access to a cluster as cluster owner when the cluster `RKE1` is moved to another namespace(workspace) in the Continuous Delivery tab. The problem is that `RoleBindings` are not created.
The issue does not happen while switching `RKE2` clusters, only `RKE1`. The reason is that `Role` and `RoleBindings` are moved to the new namespace of the workspace only in `RKE1`. In `RKE2` `Role` and `RoleBindings` stay in the `fleet-default` namespace, which means they don't need to be recreated.
Enqueue `CRTBs` for `RKE1` clusters to recreate `RoleBindings`. We do this only when the `Role` is not found and we are going to create it to minimize the impact.
Tested that RoleBindins are created when moving RKE1 clusters to a different workspace.
* Unit
* Integration …

Enqueue CRTBs for rke clusters to recreate RoleBindings

---

.github/workflows/controller-test.yml
tests/controllers/README.md
tests/controllers/run_controller_tests.sh

Added a new step to the CI to run the controller tests. I used `verify-generated-code-changes.yml` as a reference.
I also updated the `run_controller_tests.sh` script to remove an unused environment variable and to run in the right directory.

Add controller integration tests to the CI

---

pkg/controllers/provisioningv2/cluster/controller.go

When creating a custom cluster with a system agent data directory, the custom cluster registration command does not include the `CATTLE_AGENT_VAR_DIR` env var.
When generating a mgmt cluster from a prov cluster, insert the `CATTLE_AGENT_VAR_DIR` env var if the system agent data dir is configured.
Tested manually, webhook only validates the provisioning cluster env vars so there is no issue adding it into the mgmt cluster object, and confirmed the clsuter registration token which populates the registration command in the UI was formatted correctly (confirmed in backend & frontend).
Would be a good idea to test all cluster registration commands for RKE2/K3s clusters, so confirm linx+windows, and insecure/secure commands.
N/A

[46362] [2.9] Add CATTLE_AGENT_VAR_DIR to mgmt cluster env vars

---

pkg/controllers/management/usercontrollers/controller.go

Backport of https://github.com/rancher/rancher/pull/46335
Testing steps can be found in https://github.com/rancher/rancher/pull/46335
* Unit
* None
_TODO_
* _TODO_

[v2.8] Use system-default-registry when running cattle-cleanup job

---

pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/capr/managesystemagent/managesystemagent.go
pkg/controllers/provisioningv2/cluster/controller.go

Day 2 ops do not work for clusters running SLE Micro 6 since `rke2` is installed into `/opt/rke2/bin`, which is not in the PATH
Add `/opt/rke2/bin` or `/opt/bin` into the PATH variable in the system-agent systemd env file depending on whether RKE2 or K3s is selected.
Manually tested cert rotation, encryption key rotation, etcd snapshot and restore
* None
* If "None" - Reason: Not feasible to test SLE Micro 6 with current testing framework
Test all Day 2 ops, I tested 1 node all roles but it would be worth it to verify HA setups as well.
N/A
N/A

[45815] [2.9] Add support for CATTLE_AGENT_FALLBACK_PATH

---

pkg/capr/common.go
pkg/capr/planner/idempotent.go
pkg/controllers/capr/managesystemagent/managesystemagent.go

Forwardport of https://github.com/rancher/rancher/pull/46363
The `system-agent-upgrader` SUC plan does not contain the environment variables for the `system-agent` data directory (`CATTLE_AGENT_VAR_DIR`), so when the system upgrade controller applies the plan, the previous configuration is lost and the default of `/var/lib/rancher/agent` is used.
Add the `CATTLE_AGENT_VAR_DIR` env var to the `system-agent-upgrader` SUC plan if the data directory is configured for the `system-agent`.
Manually tested that after the `system-agent-upgrader` plan was run successfully, that the `/var/lib/rancher/agent` directory does not exist.
* None
* If "None" - Reason: Not currently feasibly to create tests for this usecase.
* If "None" - GH Issue/PR: …

[46429] [2.10] Add system-agent data-dir env var to suc plan

---

pkg/capr/planner/etcdrestore.go

Forwardport of https://github.com/rancher/rancher/pull/46103
When doing a etcd snapshot restore after upgrading the rke2 cluster k8s version the cluster hangs and all pods on the control plane remain in a pending state.
Add `RKE2_DATA_DIR` and `K3S_DATA_DIR` to killall calls within the planner, which will cause the manifests to be successfully removed.
Confirm etcd restore happens successfully for both RKE2 and K3s provisioned clusters.
Manually confirmed RKE2 & K3s clusters perform a restore
* None
* If "None" - Reason: Existing tests will validate this once this is merged and KDM bumps RKE2/K3s versions to a version which includes the fixes required on the distro side:
* https://github.com/rancher/rke2/issues/6292
* https://github.com/k3s-io/k3s/issues/10471 …

[46431] [2.10] Add data-dir support to killall in etcd restore

---

scripts/provisioning-tests
scripts/retry

Forwardport of https://github.com/rancher/rancher/pull/45602
Occasionally, the webhook may fail to deploy during `provisioning-tests`. 
Dump Rancher logs if webhook fails to deploy.

[46512] [2.10] Dump rancher logs when webhook fails to deploy

---

package/Dockerfile
package/Dockerfile.agent

This PR does:
1. Migrate the Agent image to BCI-Micro, which is a backport of https://github.com/rancher/rancher/pull/44044 and that was missed in https://github.com/rancher/rancher/pull/46205, where the main Rancher image was migrated to Micro (due to the backport), but not the Agent.
2. Add the missing FIPS packages in the Rancher image, backport of https://github.com/rancher/rancher/pull/46575.
3. Bump kubectl to `v1.27.15`, to fix some CVEs and because the K8s version in v2.8 is already at `1.28.x`.
4. Bump BCI to `15.6` in the Agent image, because the Rancher image is already at `15.6`.
Execute the same tests as in https://github.com/rancher/rancher/issues/46486#issuecomment-2276205364.
* Unit …

[2.8] Move agent image to bci-micro and add missing FIPS packages

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.9.1-rc2

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.9.1-rc2

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc2

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc2

---

tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

The `psact_test.go` is testing both node driver and custom cluster. We don't necessarily need to test both for this feature; node driver is enough. Additionally, just is causing release testing to be a bit longer with no real benefit.
Removing custom cluster PSACT test in RKE1/RKE2/K3S.

[Main] Remove custom cluster PSACT test

---

dev-scripts/quick

https://github.com/rancher/rancher/issues/46352
This is a follow up of #46561, aligning it with the behavior in release/v2.9 and main.
It tags the build without the arch, which makes it easier to work with the helm chart.
This is a developer-only script. Tested locally.

make quick: remove arch part of tag

---

pkg/auth/requests/authenticate.go
pkg/auth/requests/authenticate_test.go
pkg/auth/requests/service_account_test.go

When rancher authenticates a request using a token it doesn't check if the token auth provider exists or is enabled. Therefore if the auth provider was disabled and tokens weren't cleaned up they can still be used to authenticate with rancher.
If the auth provider is set in the token check that the provider exists or enabled and reject the request if the check fails.
* Unit
N/A
N/A

Check if the provider is enabled when authenticating

---

package/Dockerfile
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/capr/managesystemagent/managesystemagent.go
pkg/controllers/provisioningv2/cluster/controller.go
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Day 2 ops do not work for clusters running SLE Micro 6 since `rke2` is installed into `/opt/rke2/bin`, which is not in the PATH
Add `/opt/rke2/bin` or `/opt/bin` into the PATH variable in the system-agent systemd env file depending on whether RKE2 or K3s is selected.
Manually tested cert rotation, encryption key rotation, etcd snapshot and restore
* None
* If "None" - Reason: Not feasible to test SLE Micro 6 with current testing framework
Test all Day 2 ops, I tested 1 node all roles but it would be worth it to verify HA setups as well.
N/A
N/A

[46445] [2.10] sle micro 6

---

pkg/api/steve/catalog/types/rest.go
pkg/apis/catalog.cattle.io/v1/types.go
pkg/apis/catalog.cattle.io/v1/zz_generated_deepcopy.go
pkg/catalogv2/helmop/operation.go
pkg/catalogv2/helmop/operation_test.go
pkg/wrangler/context.go
tests/v2/integration/catalogv2/charts_test.go

This PR adds two fields to the input of requests for installing, upgrading, or uninstalling charts:
- automaticCPTolerations: Automatically adds toleration for all taints of a CP node
- operationTolerations: An array of toleration to add to the helm operation pod

adding custom tolerations to helm operations pod

---

pkg/auth/providers/saml/saml_provider.go
pkg/auth/providers/saml/saml_provider_test.go

https://github.com/rancher/rancher/issues/46658
If LDAP is not configured with the SAML provider then `SearchPrincipals` returns an incorrect principal type (`user` instead of `group`)when searching for groups.
Check and take into account the requested principal type when building the response.
* Unit
N/A
N/A

Fix SAML search for group principals without LDAP

---

tests/v2/actions/auth/auth.go
tests/v2/actions/rbac/rbac.go
tests/v2/validation/auth/lastlogin/last_login_test.go
tests/v2/validation/auth/userretention/README.md
tests/v2/validation/auth/userretention/userretention.go
tests/v2/validation/auth/userretention/userretention_delete_user_test.go
tests/v2/validation/auth/userretention/userretention_disable_user_test.go
tests/v2/validation/auth/userretention/userretention_settings_test.go

**Problem**
https://github.com/rancher/qa-tasks/issues/1372
**Testing**
1. Validate user retention settings
2. Validate User Disable Functionality by using user retention settings
3. Validate User Delete Functionality by using user retention settings
4. Validate dryrun flag for disable and delete functionalities
5. Added actions
6. Adjust the automation code for Last login to use actions
Note: Detailed test cases are in confluence

Automation tests for userretention

---

pkg/auth/providers/common/provider.go
pkg/auth/providers/saml/saml_provider.go
pkg/auth/providers/saml/saml_provider_test.go

https://github.com/rancher/rancher/issues/46658
Complementary to #46657
If LDAP is not configured when searching for principles without specifying the principle type the SAML provider returns only a user, which makes it impossible to choose a group in Add member UI e.g. when adding a cluster/project member.
Return both user and group principles with the same name in such cases.
* Unit
N/A
N/A

SAML: return both group and user principals when searching without LDAP

---

tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go

Changed TestProvisioningHostedAKS to use TimeoutRKEReport
Issue
https://github.com/rancher/qa-tasks/issues/1486
Backport
v2.9 https://github.com/rancher/rancher/pull/46651
v2.8 https://github.com/rancher/rancher/pull/46653
v2.7 https://github.com/rancher/rancher/pull/46655

<main> Fixed TestProvisioningHostedAKS to use correct TimeoutReport

---

scripts/provisioning-tests
scripts/retry

Forwardport of https://github.com/rancher/rancher/pull/45602
Occasionally, the webhook may fail to deploy during `provisioning-tests`. 
Dump Rancher logs if webhook fails to deploy.

[46510] [2.9] Dump rancher logs when webhook fails to deploy

---

tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go

Changed TestProvisioningHostedAKS to use TimeoutRKEReport

<2.8> Fixed TestProvisioningHostedAKS to use correct TimeoutReport

---

tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go

Changed TestProvisioningHostedAKS to use TimeoutRKEReport

<v2.9> Fixed TestProvisioningHostedAKS to use correct TimeoutReport

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc3
- https://github.com/rancher/ui/actions/runs/10406585937
- https://github.com/rancher/dashboard/actions/runs/10406586796

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc3

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc5
- https://github.com/rancher/dashboard/actions/runs/10422590630
- https://github.com/rancher/ui/actions/runs/10422591046

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc5

---

build.yaml
pkg/buildconfig/constants.go

This is to facilitate QA testing of the following two PRs:
https://github.com/rancher/webhook/pull/484
https://github.com/rancher/webhook/pull/478
Due to hosted operator updates to pkg/apis, the Go version was bumped to 1.22 for webhook, so we need to re-validate the release candidate. There should be no change in behavior between RC2 and RC3.

[v2.8] Update webhook to v0.4.10-rc3

---

dev-scripts/quick

Align `make quick` scripts to changes introduced by #46568
While at it, make the script robust when:
1. $TAG is not explicitly set
2. build dependency files need to be refreshed
(I am adding 2. because current behavior hid the breakage from me)
- source default variable values in the same way GHA scripts do after #46568
- unconditionally redownload build dependency files
- use the correct image TAG if no TAG is explicitly set
This is a developer-only script. Tested locally.
None - current functionality is completely broken.

[2.9] dev-scripts/quick: align retrieval of variables to changes in #46568

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc6
- https://github.com/rancher/dashboard/actions/runs/10457216593
- https://github.com/rancher/ui/actions/runs/10457208267

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc6

---

tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go

Changed TestProvisioningHostedAKS to use TimeoutRKEReport

<v2.7> Fixed TestProvisioningHostedAKS to use correct TimeoutReport

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Backport of https://github.com/rancher/rancher/pull/46416

[backport] changing from git.rancher.io to github.com/rancher in test

---

build.yaml
pkg/buildconfig/constants.go

This release is nothing more than a version bump, containing the previous RC3's changes: https://github.com/rancher/rancher/pull/46729
https://github.com/rancher/charts/pull/4366
https://github.com/rancher/webhook/releases/tag/v0.4.10

[v2.8] Un-rc webhook v0.4.10

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Un-rc the image after  https://github.com/rancher/rancher/issues/46721 was closed.

[2.8] bump system-agent to v0.3.8

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Un-rc the rancher-agent image after the validation is done.

[2.9] bump system-agent to v0.3.8

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc7
- https://github.com/rancher/dashboard/actions/runs/10493756937
- https://github.com/rancher/ui/actions/runs/10493757313

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7-rc7

---

pkg/auth/providers/activedirectory/activedirectory_client.go
pkg/auth/providers/activedirectory/activedirectory_provider.go
pkg/auth/providers/activedirectory/guid/guid.go
pkg/auth/providers/activedirectory/guid/guid_test.go

Rancher is missing a way to perform a search in ActiveDirectory though the `objectGUID` attribute.
In order to fix the issue https://github.com/rancher/rancher/issues/37994 we need a way to fetch the `objectGUID` attribute from ActiveDirectory.
This PR adds the `guid` package (with tests). This package can be used to create a GUID object from the raw bytes, following the DSP0134 specification for the UUID used as objectGUID in ActiveDirectory.
* Unit
No regressions expected.

[v2.10] Add GUID search support

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

This PR switches the KDM branch to `release-v2.9`

[2.9] update kdm branch to release-v2.9

---

README.md

SECURITY.md was removed in https://github.com/rancher/rancher/pull/43139 in favour of an organization level security policy.  Presumably https://github.com/rancher/rancher/security is a reasonable choice to use for a link to this.

Update security policy link in README.md

---

pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/manager_test.go
pkg/controllers/managementuser/rbac/handler_base.go
pkg/controllers/managementuser/rbac/handler_base_test.go

Issues: #46735 #46736
Backports: #42924 #44519 
These changes are part of 2.9.0, in addition to #45518 which was already backported (although the order now is not preserved vs. 2.9)
I have tested those 3 patches on top of 2.8.5 and confirmed they are effective.

Backport RBAC-related fixes

---

package/Dockerfile

Bump UI to v2.9.2-alpha1
https://github.com/rancher/dashboard/releases/tag/v2.9.2-alpha1
https://github.com/rancher/ui/releases/tag/v2.9.2-alpha1

Bump UI to v2.9.2-alpha1

---

pkg/capr/planner/certificaterotation.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/idempotent.go
scripts/provisioning-tests

https://github.com/rancher/rancher/issues/46034
Also, unpins RKE2 version pinned per https://github.com/rancher/rancher/issues/45577
The original logic for certificate rotation would rotate certificates unsafely.
This PR adds a correct order of operations and properly stops the K3s/RKE2 services on the nodes that are being rotated.
Perform certificate rotation
* Unit
Summary: Added a new unit test to ensure full coverage of cluster configurations

[release/v2.9] Use correct order-of-operations when performing certificate rotation of K3s/RKE2 clusters

---

pkg/capr/planner/store.go
pkg/capr/planner/store_test.go

https://github.com/rancher/rancher/issues/42856
In certain cases, it is possible to encounter errors as the join URL annotation was added to a later version of Rancher. If the join URL was not already set on the plan secret, the planner may error out.
Set the join URL on loading the plan.
Ran through the test case
* Unit
I attempted to cover regression potential with the unit test cases I added.

[release/v2.9] [v2prov] Set machine join URL annotation on plan secret if not already set when loading plan

---

pkg/capr/planner/certificaterotation.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/idempotent.go
scripts/provisioning-tests

https://github.com/rancher/rancher/issues/46943
https://github.com/rancher/rancher/issues/46034
Also, unpins RKE2 version pinned per https://github.com/rancher/rancher/issues/45577
The original logic for certificate rotation would rotate certificates unsafely.
This PR adds a correct order of operations and properly stops the K3s/RKE2 services on the nodes that are being rotated.
Perform certificate rotation
* Unit
Summary: Added a new unit test to ensure full coverage of cluster configurations

[release/v2.8] Use correct order-of-operations when performing certificate rotation of K3s/RKE2 clusters

---

tests/v2/actions/auth/auth.go
tests/v2/actions/rbac/rbac.go
tests/v2/validation/auth/lastlogin/last_login_test.go
tests/v2/validation/auth/userretention/README.md
tests/v2/validation/auth/userretention/userretention.go
tests/v2/validation/auth/userretention/userretention_delete_user_test.go
tests/v2/validation/auth/userretention/userretention_disable_user_test.go
tests/v2/validation/auth/userretention/userretention_settings_test.go

https://github.com/rancher/rancher/pull/46341
This is a backport PR: 
Problem
https://github.com/rancher/qa-tasks/issues/1372
Testing
Validate user retention settings
Validate User Disable Functionality by using user retention settings
Validate User Delete Functionality by using user retention settings
Validate dryrun flag for disable and delete functionalities
Added actions
Adjust the automation code for Last login to use actions
Note: Detailed test cases are in confluence

Automation Backport userretention to v2.8

---

pkg/agent/cluster/cluster.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/controllers/management/aks/aks_cluster_handler.go
pkg/controllers/management/clusteroperator/utils.go
pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/gke/gke_cluster_handler.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/aks/aks_driver.go
pkg/kontainer-engine/drivers/eks/eks_driver.go
pkg/kontainer-engine/drivers/import/import_driver.go
pkg/kontainer-engine/drivers/rke/rke_driver.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Backport of #46312
Use Mutex & Lease to stop concurrent secret creation
This reduces the number of concurrent secrets created for service account access in clusters by mutexing the creation by cluster/namespace/name.
This should reduce the created secrets.
* Unit
* None
_TODO_
* _TODO_

Re sync fix (#46312)

---

pkg/capr/planner/certificaterotation.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/idempotent.go
scripts/provisioning-tests

https://github.com/rancher/rancher/issues/46434
https://github.com/rancher/rancher/issues/46034
Also, unpins RKE2 version pinned per https://github.com/rancher/rancher/issues/45577
The original logic for certificate rotation would rotate certificates unsafely.
This PR adds a correct order of operations and properly stops the K3s/RKE2 services on the nodes that are being rotated.
Perform certificate rotation
* Unit
Summary: Added a new unit test to ensure full coverage of cluster configurations

[main] Use correct order-of-operations when performing certificate rotation of K3s/RKE2 clusters 

---

pkg/capr/planner/store.go
pkg/capr/planner/store_test.go

https://github.com/rancher/rancher/issues/46441
https://github.com/rancher/rancher/issues/42856
In certain cases, it is possible to encounter errors as the join URL annotation was added to a later version of Rancher. If the join URL was not already set on the plan secret, the planner may error out.
Set the join URL on loading the plan.
Ran through the test case
* Unit
I attempted to cover regression potential with the unit test cases I added.

[release/v2.8] [v2prov] Set machine join URL annotation on plan secret if not already set when loading plan

---

pkg/api/norman/customization/vsphere/handler.go
pkg/api/norman/customization/vsphere/listers.go
pkg/multiclustermanager/routes.go

https://github.com/rancher/rancher/issues/44779 
Will unblock UI: https://github.com/rancher/dashboard/issues/9817
When creating a node-driver vSphere cluster, if duplicate network names exist in the same data center, Rancher UI stalls when provisioning at the networks tab and the provisioning process fails.
On the backend, a new HTTP endpoint, `/meta/vsphere/networks-extended`, will be introduced to provide additional details about network resources within the data center. The data returned will include both the network name and the managed object identifier (MOID), with each network having a unique MOID.
On the frontend, the UI will use this new endpoint to display the network name and MOID on the NodeTemplate (for RKE1) and VmwarevsphereConfig (for RKE2/K3s) configuration pages, …

Add new endpoint networks-extended

---

pkg/capr/planner/store.go
pkg/capr/planner/store_test.go

https://github.com/rancher/rancher/issues/46403
https://github.com/rancher/rancher/issues/42856
In certain cases, it is possible to encounter errors as the join URL annotation was added to a later version of Rancher. If the join URL was not already set on the plan secret, the planner may error out.
Set the join URL on loading the plan.
Ran through the test case
* Unit
I attempted to cover regression potential with the unit test cases I added.

[main]  [v2prov] Set machine join URL annotation on plan secret if not already set when loading plan

---

pkg/agent/cluster/cluster.go
pkg/api/norman/customization/monitor/handler_utils.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/controllers/management/aks/aks_cluster_handler.go
pkg/controllers/management/clusteroperator/utils.go
pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/gke/gke_cluster_handler.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/aks/aks_driver.go
pkg/kontainer-engine/drivers/eks/eks_driver.go
pkg/kontainer-engine/drivers/import/import_driver.go
pkg/kontainer-engine/drivers/rke/rke_driver.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Backport of #46312
Use Mutex & Lease to stop concurrent secret creation
This reduces the number of concurrent secrets created for service account access in clusters by mutexing the creation by cluster/namespace/name.
This should reduce the created secrets.
* Unit
* None
_TODO_
* _TODO_

Backport v28 re sync fix

---

pkg/controllers/managementuser/certsexpiration/certsexpiration.go

This component list all secrets in the downstream cluster, to later filter by namespace ("kube-system") and secret type (opaque).
Also, this controller is exclusive for RKE1-based clusters, which is being deprecated.
These changes replace the cache with a simple `ListNamespaced` operation, using the a `FieldSelector` with a specific secret type, which will apply the filter server-side.
* Unit
* None
_TODO_
Existing / newly added automated tests that provide evidence there are no …

refactor(pkg/managementuser/certsexpiration): remove cached client

---

chart/Chart.yaml
package/Dockerfile
package/Dockerfile.agent

The transition to BCI-based images meant that we started releasing Rancher Manager with BCI labels. These changes ensure that the metadata baked into the released images are now Rancher Manager specific, whilst retaining all base image related labels for both SLE and BCI.
Here's the diff on labels between a local version and `rancher/rancher:v2.8.2`:
```diff
"com.suse.bci.micro.authors": "SUSE LLC (https://www.suse.com/)",
"com.suse.bci.micro.created": "2024-08-09T15:24:32.303161690Z",
"com.suse.bci.micro.description": "A micro environment for containers based on the SLE Base Container Image.",
"com.suse.bci.micro.disturl": "obs://build.suse.de/SUSE:SLE-15-SP6:Update:CR/images/c4136c6519a0f7f58d2c0ca542aee82a-micro-image",
"com.suse.bci.micro.eula": "sle-bci", …
```

Overwrite BCI labels

---

pkg/auth/providerrefresh/daemon.go
pkg/auth/providers/azure/azure_provider.go
pkg/controllers/management/auth/setting.go
pkg/controllers/management/auth/setting_test.go

The recent changes in packages `pkg/auth/providers/azure` and `pkg/auth/providerrefresh/`  introduced the bug linked above.
Revert the changes to restore the previous behavior.

fix: restore previous logic on providers/azure and providerrefresh pkgs

---

.github/workflows/push-release.yml

Migrating release/v2.7 to use Github Actions most up-to-date jobs.

[release-v2.7] GH Actions migration [small-fixes]

---

pkg/controllers/dashboard/helm/repo.go

Changing the refresh interval to 1h to match with other Rancher releases

2.8 changing clusterrepo interval to 1h

---

tests/v2/actions/hardening/k3s/audit.yaml
tests/v2/actions/hardening/k3s/harden_nodes.go
tests/v2/actions/hardening/rke1/account-update.sh
tests/v2/actions/hardening/rke1/account-update.yaml
tests/v2/actions/hardening/rke1/harden_nodes.go
tests/v2/actions/hardening/rke2/account-update.sh
tests/v2/actions/hardening/rke2/account-update.yaml
tests/v2/actions/hardening/rke2/harden_nodes.go

When we first moved to shepherd, the `hardening` package initially maintained the YAML and bash scripts found in the `hardening` package. However, at that time, we did not consistently perform testing with hardened clusters. Hence, there was an issue with Jenkins in running the tests.
The workaround was to remove the YAML and bash scripts and run directly in the go file. This was always meant to be a temporary solution.
Revert back to the YAML and bash scripts now that `hardening` lives once again in rancher/rancher.
Jenkins runs will be provided to reviewers offline.

[Main] Update hardening action to include YAML and bash scripts

---

pkg/controllers/managementuser/secret/secret.go

Follow up for #46789, where I accidentally left a `secretLister`, which should be also removed.
Use non-cached client.

refactor(pkg/managementuser/secret): leftover secret lister

---

chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.schema.json
chart/values.yaml
pkg/image/resolve.go

See title; using old BCI images for audit log
Bump audit logs
Install rancher and check the audit log image tag in use.
Manually rendered via template command.
* Unit - Helm unit tests updated as needed
The primary concern here is just bumping the BCI image we're using.
I also added Scheme for values I touched - these improve user experience while editing values files.
Highly unlikely - auditLog sidecar simply `tail`'s the log. As long as the image still has tag it should work fine.

[main] Bump Audit Log Image versions

---

package/Dockerfile

Bump UI to v2.9.2-alpha2
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.9.2-alpha2
https://github.com/rancher/ui/releases/tag/v2.9.2-alpha2
Workflow runs:
https://github.com/rancher/ui/actions/runs/10795637741
https://github.com/rancher/dashboard/actions/runs/10795550430

Bump UI to v2.9.2-alpha2

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

* Bump RKE to `v1.6.2-rc.2`
* go generate

[v2.9] Bump RKE to `v1.6.2-rc.2`

---

pkg/capr/common.go
pkg/capr/planner/config.go
pkg/capr/planner/filter.go
pkg/capr/planner/planner.go

https://github.com/rancher/rancher/issues/46855
There was no effective mechanism for determining release data validity for CAPR clusters. 
This blocks provisioning from delivering bad configurations if release data is not available for a given version.
1. Provision a RKE2 (custom) cluster w/ Rancher v2.8.7
1. Upgrade Rancher to this version
1. Ensure that Rancher errors saying release data was invalid
* None
* If "None" - Reason: Difficult to test across Rancher versions

[release/v2.9] Block provisioning if release data is not found for a CAPR cluster

---

tests/v2/validation/serviceaccounts/README.md
tests/v2/validation/serviceaccounts/sa_test.go

[rancher/qa-tasks#1343](https://github.com/rancher/qa-tasks/issues/1343)
Note: Backports will be created once this gets approved

[v2.9] Migrating serviceaccounts test from python to go

---

pkg/capr/common.go
pkg/capr/planner/config.go
pkg/capr/planner/filter.go
pkg/capr/planner/planner.go

https://github.com/rancher/rancher/issues/47084
https://github.com/rancher/rancher/issues/46855
There was no effective mechanism for determining release data validity for CAPR clusters. 
This blocks provisioning from delivering bad configurations if release data is not available for a given version.
1. Provision a RKE2 (custom) cluster w/ Rancher v2.8.7
1. Upgrade Rancher to this version
1. Ensure that Rancher errors saying release data was invalid
* None
* If "None" - Reason: Difficult to test across Rancher versions

[release/v2.8] Block provisioning if release data is not found for a CAPR cluster

---

tests/v2/actions/etcdsnapshot/config.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go

The `snapshot_additional_test.go` currently has a function that will replace only worker nodes. This should be enhanced so that all roles in a cluster are replaced as that would be good to test. Additionally, since etcd nodes will be replaced, this test needs to be converted to S3 only as we need to save a copy of the snapshot that gets lost once you replace the etcd node.
Enhanced `TestSnapshotReplaceNodes` to replace control plane, etcd and worker nodes, not just worker nodes. Additionally, enhanced this test to be an S3-only test so that we save the snapshot in cloud storage, not just in local storage.

[Main] Enhance replace worker nodes to replace all cluster roles

---

pkg/controllers/management/auth/project_cluster/cluster_handler.go
pkg/controllers/management/auth/project_cluster/cluster_handler_test.go
pkg/controllers/management/auth/project_cluster/common.go
pkg/controllers/management/auth/project_cluster/project_handler.go
pkg/controllers/management/auth/project_cluster/project_handler_test.go

https://github.com/rancher/rancher/issues/46828
Related webhook changes https://github.com/rancher/webhook/pull/501
Currently when a project or a cluster is created by a user who is logged in using an external authentication provider Rancher shows that user's principal ID as the owner in the UI only to be replaced later by it's local user's counterpart.
Add `field.cattle.io/creator-principal-name` annotation that can carry the creator's principal ID to complement the existing `field.cattle.io/creatorId` that is set when the corresponding project/cluster object is created.
```
curl https://<rancher-url>/v3/projects \
...
--data-raw '{
"type":"project",
"name":"test-project",
"annotations": {
"field.cattle.io/creator-principal-name": "keycloak_user://testuser1@example.com"
},
...
}'
```
- …

Respect creator principal when creating project or cluster

---

package/Dockerfile

Bump UI to v2.9.2-alpha3
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.9.2-alpha3 
https://github.com/rancher/ui/releases/tag/v2.9.2-alpha3 
Workflow runs:
https://github.com/rancher/ui/actions/runs/10852555202
https://github.com/rancher/dashboard/actions/runs/10852566331

Bump UI to v2.9.2-alpha3

---

package/Dockerfile

Bump UI to v2.8.8-alpha1
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.8.8-alpha1
https://github.com/rancher/ui/releases/tag/v2.8.8-alpha1
Workflow runs:
https://github.com/rancher/dashboard/actions/runs/10854317939
https://github.com/rancher/ui/actions/runs/10854332967

Bump UI to v2.8.8-alpha2

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Issue: https://github.com/rancher/rancher/issues/47139

[v2.9] bump rke to v1.6.2-rc.3

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

[v2.8] Bump `rancher/cli` to v2.8.8

---

pkg/capr/planner/config.go

Two minor spelling errors inside error messages (cotain -> contain).
Fixed the spelling.
I do not believe any extra testing is needed.
I do not believe any extra testing is needed as there are only very minor changes in text strings.
* None
* If "None" - Reason: No application logic is modified by this change, e.g. refactoring/cosmetic/non-code/test change
Summary: Two minor spelling erros are fixed.
_TODO_
* _TODO_

Fix spelling error in two error messages

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

[v2.9] Bump `rancher/cli` to v2.9.2

---

package/Dockerfile

Bump UI to v2.9.2-alpha4
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.9.2-alpha4
https://github.com/rancher/ui/releases/tag/v2.9.2-alpha4
Workflow runs:
https://github.com/rancher/dashboard/actions/runs/10910268758
https://github.com/rancher/ui/actions/runs/10910286290

Bump UI to v2.9.2-alpha4

---

package/Dockerfile

Bump UI to v2.9.2-rc1
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.9.2-rc1
https://github.com/rancher/ui/releases/tag/v2.9.2-rc1
Workflow runs:
https://github.com/rancher/dashboard/actions/runs/10931092236
https://github.com/rancher/ui/actions/runs/10931091677

Bump UI to v2.9.2-rc1

---

package/Dockerfile

Bump UI to v2.8.8-rc1
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.8.8-rc1
https://github.com/rancher/ui/releases/tag/v2.8.8-rc1
Workflow runs:
https://github.com/rancher/dashboard/actions/runs/10931092031
https://github.com/rancher/ui/actions/runs/10931091155

Bump UI to v2.8.8-rc1

---

pkg/controllers/management/authprovisioningv2/role.go
pkg/controllers/management/authprovisioningv2/role_test.go

I've observed some `role` objects being updated quite often. Using `kubectl get -w` I observed the only change was the order of the `resourceNames` inside the rules.
Since `wrangler`'s `apply` is being used, the update produced by previous applies trigger new reconciliation, possibly causing an endless update loop due to successive lists of resourceNames not being equal.
Sort the names obtained from the result of `GetByIndex`, ensuring the result is stable.
A small refactor was needed in order to add a unit tests (`dynamic.Controller` is not an interface so it can't be mocked).

Sort ResourceNames in Role rules created from RoleTemplates

---

package/Dockerfile

Bump UI to v2.8.8
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.8.8
https://github.com/rancher/ui/releases/tag/v2.8.8
Workflow runs:
https://github.com/rancher/dashboard/actions/runs/10946642451
https://github.com/rancher/ui/actions/runs/10946673570

Bump UI to v2.8.8

---

package/Dockerfile

Bump UI to v2.9.2
Releases:
https://github.com/rancher/dashboard/releases/tag/v2.9.2
https://github.com/rancher/ui/releases/tag/v2.9.2
Workflow runs:
https://github.com/rancher/dashboard/actions/runs/10946583875
https://github.com/rancher/ui/actions/runs/10946661299

Bump UI to v2.9.2

---

dev-scripts/quick
package/Dockerfile.agent

this PR enhances the quick script to allow setting the image repository during the build process, enabling Rancher to deploy the cluster agent with the correct image into the downstream cluster.  
Example usage: `REPO=my-repo make quick` 
The changes was validated in my local environment during development.

[main ] improve the quick script

---

pkg/data/management/role_data.go

Use defined verbs instead of `*` for some resources in the "Manage Workloads" RoleTemplate.
A Project Owner should be able to assign the Manage Workloads role template. This was not possible, because some of the permissions defined in the template where broader than the one inherited from the Kubernetes Admin role.
i.e. the Manage Workloads template is allowed to use any verbs (`*`) for the `pods` and others resources, while the Kubernetes Admin is restricted to some of them (`get`, `list`, `watch`, `create`, `delete`, `deletecollection`, `patch`, `update`).
The implemented solution narrows the verbs to the same defined from the Kubernetes Admin.
| resource | old verbs | new verbs
|--------------|---------------|---------------
| `pods`, `pods/attach`, `pods/exec`, `pods/portforward`, …

Use defined verbs instead of `*` in "Manage Workloads" RoleTemplate

---

tests/validation/tests/v3_api/test_certificate.py

QA task: https://github.com/rancher/qa-tasks/issues/1545
test_certificate is currently failing due to an issuer mismatch error:
```
failed on setup with "AssertionError: assert 'E6' == 'R3'
- R3
+ E6"
Stacktrace
request = <SubRequest 'create_project_client' for <Function test_certificate_create_validcert_for_single_ns>>
@pytest.fixture(scope='module', autouse="True")
def create_project_client(request):
client, cluster = get_user_client_and_cluster()
create_kubeconfig(cluster)
project, ns = create_project_and_ns(USER_TOKEN, cluster,
project_name="test-certificate",
ns_name="ns-certificate")
p_client = get_project_client_for_token(project, USER_TOKEN)
c_client = get_cluster_client_for_token(cluster, USER_TOKEN)
certificate_valid = p_client.create_namespaced_certificate(
name="cert-valid", …
```

Update certificate issuer in test_certificate

---

pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/rbac/namespace_handler_test.go

https://github.com/rancher/rancher/issues/43799
The UI fails to remove a deleted namespace because as part of the finalizer for the namespace, we remove the RBAC required for the UI to see that the namespace has been removed.
We now hold on to the RBAC until the namespace is fully deleted.
Manual and unit tests
As a cluster member (remember admins will always have the required RBAC and will not show the problem).  Create a namespace in a project.  Then delete that namespace.  Prior to this fix, the namespace would linger as "Terminating" in the UI until the page was refreshed.  After this fix, the namespace will be removed after a few seconds.
Unit tests added
Nothing comes to mind, but it's worth making sure that this works for other user levels (admin, other cluster …

Wait for namespace to be fully deleted before removing entry in associated namespaced cluster role

---

Dockerfile.dapper
go.mod
go.sum
package/Dockerfile
pkg/apis/go.mod
pkg/apis/go.sum
pkg/settings/setting.go
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

Updating KDM to dev-v2.8 post release and bumping RKE to `v1.5.14-rc.1` for https://github.com/rancher/rancher/issues/47185

[v2.8] update kdm to dev-v2.8 and rke to v1.5.14-rc.1

---

package/Dockerfile
package/Dockerfile.agent
package/loglevel
package/windows/Dockerfile.agent
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent
tests/v2/codecoverage/package/loglevel

The loglevel binary is built from a separate project that is essentially unmaintained: https://github.com/rancher/loglevel/blob/master/main.go
It serves very little purpose and is just a thin wrapper around a HTTP API presented via unix socket within the rancher container.
Replace project and binary with shell script. Shell script should support the same CLI flags and env vars as the binary.
Covered by tests
Ran the script myself, seems to work

Replace loglevel binary with small shell script

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

Related Harvester issue: https://github.com/harvester/harvester/issues/6053
Related Rancher issue: https://github.com/rancher/rancher/issues/47238
Currently rancher builds package amd64 only driver in the multi-arch builds. As a result end users running Rancher on arm64 hosts cannot provision downstream clusters on harvester since the driver is hardcoded to amd64.
Harvester node driver v0.6.9 now publishes multi-arch driver images and the change introduced packages the correct driver arch in rancher image builds.
In addition, the additional check in machinedriver_data.go ensures the arch appropriate checksum is used.
* Unit
* None
* _REMOVE …

Harvester arm driver

---

tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Backports
v2.9 https://github.com/rancher/rancher/pull/47225
v2.8 https://github.com/rancher/rancher/pull/47226
v2.7 https://github.com/rancher/rancher/pull/47227

<main> Converted to go the test_wl_pod_scale_down and test_wl_pod_scale_up python tests

---

chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.schema.json
chart/values.yaml
pkg/image/resolve.go

https://github.com/rancher/rancher/issues/47042
See title; using old BCI images for audit log
Bump audit logs
Install rancher and check the audit log image tag in use.
Manually rendered via template command.
* Unit - Helm unit tests updated as needed
The primary concern here is just bumping the BCI image we're using.
I also added Scheme for values I touched - these improve user experience while editing values files.
Highly unlikely - auditLog sidecar simply `tail`'s the log. As long as the image still has tag it should work fine.

[v2.8] Bump Audit Log Image versions

---

tests/v2/actions/configmaps/configmaps.go
tests/v2/validation/rbac/configmaps/README.md
tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go

Back port https://github.com/rancher/rancher/pull/45780

[2.8] Migrating configmaps tests from python to go

---

pkg/auth/context/context.go
pkg/auth/requests/impersonate.go
pkg/auth/requests/impersonate_test.go
pkg/auth/requests/mocks/sar.go
pkg/auth/requests/sar/sar.go
pkg/auth/requests/sar/sar_test.go
pkg/auth/util/common_util.go
pkg/clusterrouter/proxy/proxy_server.go
pkg/clusterrouter/proxy/proxy_server_test.go
pkg/multiclustermanager/routes.go

Users can't impersonate `ServiceAccounts` on downstream clusters.
Impersonating users was done in https://github.com/rancher/rancher/pull/46968
Allow users to impersonate `ServiceAccounts` on downstream clusters:
- Verify the user making the request have enough permissions to impersonate SA in the downstream cluster. Reject the request if the user doesn't have enough permissions.
- Get a token for the impersonated SA using the `TokenRequest` api.
- Use this token in the `Authorization` header.
Unit tests added. Minor refactor in `proxy_server.go` in order to make it testable.
We were setting a `userInfo` with `system:cattle:error` or `system:unauthenticated` in the context of the request in the [ToMiddleware](https://github.com/rancher/steve/blob/main/pkg/auth/filter.go#L145) if the …

Impersonate ServiceAccount on downstream clusters

---

pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go

This replicates behavior which already exists for labels, for the sake of consistency and reducing the risk of confusion for users.
Editing a cluster in the UI, through `Cluster Management` then selecting `Edit Config` on a cluster enables a user to create, update or delete labels and annotations, among other fields, for a cluster.
While updates to labels would be visible on the corresponding Fleet cluster, such was not the case for annotations.
Update the Fleet cluster provisioning controller to take annotations into account when creating a Fleet cluster, just as labels already are.
Tested reproduction steps on the UI (for a local cluster), with and without this patch.
* Unit
Test reproduction steps on downstream/imported cluster
N/A
Existing / newly added …

Propagate annotations from management cluster to Fleet cluster

---

pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
pkg/controllers/management/authprovisioningv2/role.go
pkg/controllers/management/authprovisioningv2/role_test.go

Using `OnRemove`  adds a finalizer to all the resources for the specific kind. Currently, this Rancher component does that for `Role`, `RoleBinding`, `ClusterRole` and `ClusterRoleBinding` kinds, but later it will skip some of them depending on certain annotations being present.
This creates unnecessary activity, or even a conflict if resources owned by another controller try to fight for the same resource (see https://github.com/tigera/operator/issues/3480).
At the moment, `wrangler` does not allow for specifying a smaller granularity, so I've added a pre-condition to the `NewRemoveHandler` and used `AddGenericHandler` directly.
The condition func was extracted from the existing validation being performed (see `hasAnnotationsForDeletingCluster`).
I've confirmed that after removing …

fix(authprovisioningv2): only add finalizers to necessary RBAC resources

---

go.mod
go.sum
tests/v2/actions/clusters/clusterconfig.go
tests/v2/actions/clusters/clusters.go
tests/v2/actions/provisioning/creates.go
tests/v2/actions/provisioninginput/config.go
tests/v2/validation/provisioning/proxy/README.md
tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/proxy.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go

Added proxied rancher provisioning tests for https://github.com/rancher/qa-tasks/issues/479
Port: https://github.com/rancher/rancher/pull/45266
Tests added:
- rke1 node driver
- rke1 custom clusters
- rke2 node driver
- rke2 custom clusters
- k3s node driver
- k3s custom cluster
Runs in Jenkins

[v2.8] Added proxied rancher provisioning tests

---

go.mod
go.sum
tests/v2/actions/clusters/clusterconfig.go
tests/v2/actions/clusters/clusters.go
tests/v2/actions/provisioning/creates.go
tests/v2/actions/provisioninginput/config.go
tests/v2/validation/provisioning/proxy/README.md
tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/proxy.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go

Added proxied rancher provisioning tests for https://github.com/rancher/qa-tasks/issues/479
Port: https://github.com/rancher/rancher/pull/45266
Tests added:
- rke1 node driver
- rke1 custom clusters
- rke2 node driver
- rke2 custom clusters
- k3s node driver
- k3s custom cluster
Runs in Jenkins

[v2.7] Added proxied rancher provisioning tests

---

pkg/auth/cleanup/service.go

A reference to a loop variable is used leading to unexpected results.
This causes unit tests [to fail](https://github.com/rancher/rancher/actions/runs/11145755402/job/30982471888?pr=47354)
```
--- FAIL: TestRunCleanup (0.00s)
service_test.go:140: 
Error Trace:	/home/runner/work/rancher/rancher/pkg/auth/cleanup/service_test.go:140
Error:      	"[local://boss azuread_user://authprincipal]" should have 1 item(s), but has 2
Test:       	TestRunCleanup
Messages:   	every user after cleanup must have only one principal ID, got 2
FAIL
```
The behavior of for loops was fixed in Go 1.22 but v2.7 still uses 1.20.
Make a copy of the loop variable.
* Unit
N/A
N/A

[v2.7] Fix auth provider cleanup service

---

pkg/settings/setting.go

Currently Rancher head builds are loading ui for the next 2.9 release. 
Similar to https://github.com/rancher/rancher/pull/46309, ui-index and ui-dashboard-index settings need to be updated to point back to ui built from the rancher/dashboard `master` branch, which tracks 2.10
Updated the settings in an existing rancher instance with the new values and ensured both UIs load correctly

update ui-index and ui-dashboard-index to use 2.10 UI builds

---

.github/workflows/provisioning-tests.yml

Fixed branch filter to make v2prov tests run on PRs in `main` branch

Run provisioning tests on `main`

---

tests/v2/actions/rbac/rbac.go
tests/v2/actions/rbac/verify.go
tests/v2/validation/rbac/rbac_test.go

https://github.com/rancher/qa-tasks/issues/943
Will create a backport for this once PR is approved. 
- Adding RBAC test to validate corresponding role bindings were created for user, as described in issue above.
- Added helper function to get rolebindings based on user using kubeapi
- Added test to rbac_test to use helper function and validate rolebindings for user
Jenkins run

Adding VerifyRoleBindingsForUser to rbac_test

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/rancher/issues/47246
Bump shell to the RC that includes helm with 1.31 support

[head/2.10] Bump shell for k8s 1.31

---

pkg/agent/rancher/rancher.go
pkg/api/norman/customization/clusterregistrationtokens/import.go
pkg/apis/management.cattle.io/v3/cluster_types.go
pkg/capr/common.go
pkg/capr/planner/agent.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/planner.go
pkg/capr/planner/planner_test.go
pkg/clustermanager/manager.go
pkg/controllers/capr/controllers.go
pkg/controllers/management/clusterconnected/clusterconnected.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/managementuser/controllers.go
pkg/controllers/managementuser/secret/secret.go
pkg/controllers/managementuser/secret/secret_test.go
pkg/features/feature.go
pkg/provisioningv2/prebootstrap/resolve.go
pkg/settings/setting.go
pkg/systemtemplate/import.go
pkg/systemtemplate/import_test.go
pkg/systemtemplate/template.go
scripts/provisioning-tests

Issue: https://github.com/rancher/rancher/issues/47469
Support synchronizing resources directly to downstream clusters (https://github.com/rancher/rancher/pull/47437)
* conditionally bootstrap controllers based on condition
* finish pre-bootstrap templating
* change to feature-flag for feature and implement controllers
* update tests to expect second call to planner#mgmtClusters.Get(...)
* code review comments
* refactor boostrapManifests into an InfoFunction
---------
This is a backport of https://github.com/rancher/rancher/pull/47437

[backport v2.9] Support synchronizing resources directly to downstream clusters

---

pkg/agent/rancher/rancher.go
pkg/api/norman/customization/clusterregistrationtokens/import.go
pkg/apis/management.cattle.io/v3/cluster_types.go
pkg/capr/common.go
pkg/capr/planner/agent.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/planner.go
pkg/capr/planner/planner_test.go
pkg/clustermanager/manager.go
pkg/controllers/capr/controllers.go
pkg/controllers/management/clusterconnected/clusterconnected.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/managementuser/controllers.go
pkg/controllers/managementuser/secret/secret.go
pkg/controllers/managementuser/secret/secret_test.go
pkg/features/feature.go
pkg/provisioningv2/prebootstrap/resolve.go
pkg/systemtemplate/import.go
pkg/systemtemplate/import_test.go
pkg/systemtemplate/template.go
scripts/provisioning-tests

Issue: https://github.com/rancher/rancher/issues/47470
Support synchronizing resources directly to downstream clusters (https://github.com/rancher/rancher/pull/47437)
* conditionally bootstrap controllers based on condition
* finish pre-bootstrap templating
* change to feature-flag for feature and implement controllers
* update tests to expect second call to planner#mgmtClusters.Get(...)
* code review comments
* refactor boostrapManifests into an InfoFunction
---------
This is a backport of https://github.com/rancher/rancher/pull/47437

[backport 2.8] Support synchronizing resources directly to downstream clusters (#46722)

---

tests/v2/validation/auth/userretention/userretention_disable_user_test.go
tests/v2/validation/auth/userretention/userretention_settings_test.go

https://github.com/rancher/qa-tasks/issues/1578
Currently, slack reporter for recurring run fails with:
05:15:58.491  [31mERRO[0m[0114] error reporting: error with slack message post: 400 Bad Request 400: **** 
The potential problem is: that it uses string manipulation to check the [forward slashes](https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/pipeline/slack/slack.go#L46). It sends the wrong parsed string to the slack API.
Example names (there are more, make sure to check names) that need updates: https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/auth/userretention/userretention_settings_test.go#L191-L193
Extra information about forward slashes in the test names: https://github.com/rancher/rancher/tree/main/tests#how-to-write-tests

Removed forward slashes from the tests

---

pkg/controllers/management/authprovisioningv2/authprovisioningv2.go
pkg/controllers/management/authprovisioningv2/cluster.go
pkg/controllers/management/authprovisioningv2/cluster_test.go

Same as https://github.com/rancher/rancher/pull/46498 but for `RoleBindings` created for `Projects` instead of `Clusters`
Enqueue `PRTBs` for RKE1 clusters to recreate `RoleBindings`. We do this only when the Role is not found and we are going to create it to minimize the impact.
Tested that RoleBindings are created when moving RKE1 clusters to a different workspace.
Unit Tests

Enqueue PRTBs for RKE clusters to recreate RoleBindings

---

pkg/api/norman/customization/cred/store.go

Previously, the cloud credential expiry annotation used a "cattle.io" prefix. This lead to norman preventing updates to the value. Since the value needs to be updated on rotation, this was changed to rancher.io, which is not protected.
#47491
Currently, Harvester's cloud credentials have an expiry time in the "cattle.io/expiration-timestamp" annotation. Norman (as linked in the issue) views this annotation as protected, and does not allow updating this value through Norman, even when the change originates from internal Rancher code rather than the end user.
The annotation now is named "rancher.io/expiration-timestamp". Because this has a different prefix, it's no longer protected, and now be updated. 
Small manual testing was done to validate that the original issue was resolved.

Updates the name of cloud credential expiry time

---

.github/workflows/provisioning-tests.yml
.github/workflows/pull-request.yml

A decent amount of time is wasted running tests against changes to the repo that have nothing to do with the product or the tests that run in CI
A decent amount of time is wasted running tests against changes to the repo that have nothing to do with the product or the tests that run in CI
add `paths-ignore` to github-actions that will be excluded by default in CI. 
Starting by omitting tests outside of tests that run on CI from triggering provisioning-tests and building artifacts. 
**note** - .github folder is a proof of concept so you can see what CI will run on 'excluded' PRs. It will be removed upon approval of initial design / idea.

omit e2e tests from triggering CI, unless CI tests are changed

---

.github/workflows/provisioning-tests.yml
.github/workflows/pull-request.yml

port of https://github.com/rancher/rancher/pull/47471/commits

[2.9] omit e2e tests from triggering CI, unless CI tests are changed

---

.github/workflows/provisioning-tests.yml
.github/workflows/pull-request.yml

port of https://github.com/rancher/rancher/pull/47471

[2.8] omit e2e tests from triggering CI, unless CI tests are changed

---

.github/workflows/provisioning-tests.yml
.github/workflows/pull-request.yml

port of https://github.com/rancher/rancher/pull/47471

[2.7] omit e2e tests from triggering CI, unless CI tests are changed

---

tests/v2/validation/auth/userretention/userretention_disable_user_test.go
tests/v2/validation/auth/userretention/userretention_settings_test.go

https://github.com/rancher/qa-tasks/issues/1578
Currently, slack reporter for recurring run fails with:
05:15:58.491 [31mERRO[0m[0114] error reporting: error with slack message post: 400 Bad Request 400: ****
The potential problem is: that it uses string manipulation to check the [forward slashes](https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/pipeline/slack/slack.go#L46). It sends the wrong parsed string to the slack API.
Example names (there are more, make sure to check names) that need updates: https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/auth/userretention/userretention_settings_test.go#L191-L193
Extra information about forward slashes in the test names: https://github.com/rancher/rancher/tree/main/tests#how-to-write-tests

Removed forward slashes from the tests (#47474)

---

tests/v2/actions/clustertemplates/clustertemplates.go
tests/v2/actions/provisioning/creates.go
tests/v2/validation/clustertemplates/provisioning/README.md
tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go

https://github.com/rancher/qa-tasks/issues/1509 
Current need to migrate tests from python to golang.
The RKE1 cluster template tests were originally written in Python and utilized Monitoring v1. Since Monitoring v1 has been deprecated, the related code had to be removed, which affected the RKE1 cluster templates. Given the current need to migrate the tests from Python to Golang, rewrote the tests for the RKE templates in Golang.
Results from Jenkins pipeling.
Cluster templates are applicable for rke1 clusters only. These tests are written to run against the latest RKE1 kubernetes or any one kubernetes version[User's input if any] and on node driver clusters.
RKE templates can be created by admins only unless additional permissions are provided to the standard users.
These tests are …

Migrating rke1 templates test from python to go

---

pkg/controllers/dashboard/chart/chart.go
pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go
pkg/controllers/management/k3sbasedupgrade/deployPlans.go
pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/features/feature.go
pkg/settings/setting.go
pkg/systemtemplate/import.go

Notes
The `Provisioning tests` are failing because the CI is not using the agent image built from the CI itself, causing it to exit due to an unrecognized feature flag. To move this PR forward, we will temporarily ignore those CI failures and rerun the tests once the CI issue is resolved.
https://github.com/rancher/rancher/issues/42448
unblocks https://github.com/rancher/dashboard/issues/11942
We need a new approach for installing the system-upgrade-controller app in downstream RKE2/K3s imported clusters, aiming to completely phase out support for the legacy [Catalog and Catalog App feature](https://ranchermanager.docs.rancher.com/v2.0-v2.4/how-to-guides/new-user-guides/helm-charts-in-rancher) in Rancher.  
We will leverage the established SystemCharts mechanism to install the …

[2.10] Deprecate rancher-k3s-upgrader

---

pkg/capr/common.go
pkg/capr/planner/config.go
pkg/capr/planner/filter.go
pkg/capr/planner/planner.go

https://github.com/rancher/rancher/issues/47086
https://github.com/rancher/rancher/issues/46855
There was no effective mechanism for determining release data validity for CAPR clusters. 
This blocks provisioning from delivering bad configurations if release data is not available for a given version.
1. Provision a RKE2 (custom) cluster w/ Rancher v2.8.7
1. Upgrade Rancher to this version
1. Ensure that Rancher errors saying release data was invalid
* None
* If "None" - Reason: Difficult to test across Rancher versions

[main] Block provisioning if release data is not found for a CAPR cluster

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

Also includes Linode version bump for https://github.com/rancher/rancher/issues/46432
When spinning up Rancher on an arm64 host, the linode driver attempts to install the amd64 versions, which cannot be run. This causes node driver initialization to get stuck, preventing users from creating cloud credentials and subsequently other node driver clusters.
Download linode as arm64 within arm64 Rancher image. Linode is also v0.1.12 on release/v2.9, so I bumped it.
Test creating cloud credentials for unrelated node drivers on arm64 and provisioning linode on amd64 and arm64.
Verify other cloud credentials are unimpacted, and no differences between amd64 & arm64.
* N/A (Existing validations …

[47569] [2.10] Download linode as arm64 on arm64

---

tests/v2/validation/networking/README.md
tests/v2/validation/networking/connectivity/network_policy.go
tests/v2/validation/networking/connectivity/network_policy_test.go
tests/validation/tests/v3_api/test_network_policy.py

Introduce new network policy connectivity tests using Rancher client, including setup and teardown processes. Verifies namespace and daemonset creation, as well as basic pod-to-pod connectivity with ping command.
To deprecate Python tests, we need to convert existing tests to Go. This test is part of the Network Connectivity suite of Python tests.
Convert test to Go and use extensions built into the Shepherd test framework.

Add network policy connectivity tests

---

pkg/controllers/management/auth/auth_config.go
pkg/controllers/management/auth/auth_config_test.go

#47489 
When disabling an auth provider supporting logout-all as per its auth config resource the flag reporting this is reset, and the auth provider will from then report that it does not support logout-all.
The function which strips all the irrelevant keys out of auth configs on reset is modified to retain the `logoutAllSupported` field.
* Unit tests of the auth config controller
Scenario:
- Enable a external auth provider supporting logout-all (any of the SAML providers).
- Disable the provider again
- Re-enable the same provider and verify that logout-all is still supported.

saml logoutall - retain `logoutAllSupported` flag when resetting an auth config back to unused when it is disabled.

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml

chart have no ability to tolerate custom taints leading to chart not installable on tainted nodes
Introduce additional value to add tolerations
run through `helm template -n cattle-system rancher ./  --debug -f foo.yaml --show-only templates/deployment.yaml`
with foo.yaml containing:
```yaml
tolerations:
- key: "node.cloudprovider.kubernetes.io/uninitialized"
value: "true"
effect: "NoSchedule"
```
* Unit
* None
_TODO_ …

[CHART] Support additional taints tolerations

---

pkg/tls/tls.go

Related to issue https://github.com/rancher/rancher/issues/46956 (v2.10)
This change displays any error messages and panic output from the dynamic listener's http server in rancher's log output

Display error output from dynamiclistener.Server

---

go.mod
pkg/api/norman/customization/cluster/validator.go
pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/management/k3sbasedupgrade/deployPlans.go
pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/controllers/management/k3sbasedupgrade/template.go
pkg/controllers/management/k3sbasedupgrade/template_test.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go
pkg/image/external/external.go

When new nodes are added to an imported cluster, if that cluster has ever been upgraded, nodes are cordoned and the `rke2-upgrade`/`k3s-upgrade` SUC plans are run against them, despite being a no-op.
Add a label selector to the SUC plan that only selects nodes that have been determined to be out of date. Update the nodesyncer to apply this label when a cluster has been upgraded.
* Unit
- Test case where new node is added on current version after cluster has already been upgraded
- Test case where new node is added on older version after cluster has already been upgraded
- Test case where new node is added on higher version after cluster has already been upgraded
N/A
Existing / newly added automated tests that provide evidence there are no …

[41143] [2.10] Add label to imported cluster nodes that require upgrades

---

.github/workflows/go-get.yml
scripts/go-get

- Move the `go generate ./...` command out of the "go-get" script because the script runs inside a Dapper container, which only copies specific files back to the local system. The generated files in `pkg/client/generated/` are not part of those files, so running `go generate` inside the container won't update them locally. By moving it outside, we ensure the files are correctly generated and available in the local environment.
- Update GitHub Actions workflow to use the latest checkout and script versions.
- `go generate` in dapper: https://github.com/rancher/rancher/actions/runs/11334681389/job/31521368140
- `go generate` outside dapper: https://github.com/chiukapoor/rancher/actions/runs/11343938394/job/31547612220
- https://github.com/rancher/rancher/issues/47076

[v2.10] Fix go generate in go-get script

---

build.yaml
pkg/buildconfig/constants.go

##Issue:
rancher/rancher#46833
##Problem:
Support k8s 1.31
##Testing:
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.0-rc1
Validated the support config and license entitlement functionality. Created a downstream EKS cluster with 21 nodes (with 1 entitlement) to trigger out-of-compliance message. Scaled down the cluster to 17 nodes, validated that the out-of-compliance message is no longer displayed. Scaled back up to 21 nodes, validated the out-of-compliance message popped up

Update rancher-csp-adapter version

---

scripts/provisioning-tests

After introducing [some agent changes](#47356) the provisioning tests were continually failing since the `scripts/provisioning-tests` script did not use the built agent image it instead was pulling from dockerhub.
Mirror necessary rancher-agent image to dockerhub and then update the script to use that in the interim of fixing the CI
If the provisioning tests pass -> we're good.

[2.8] Tag agent for tests

---

go.mod
go.sum

#47601
See rancher/steve#300. Steve previously did not add metadata.state through the formatter when the cache was enabled.
The formatter will always add metadata.state, even if the cache is enabled.
Manual, based on rancher/dashboard#12262

Bumping steve version

---

tests/v2/validation/Dockerfile.validation
tests/v2/validation/Jenkinsfile

Our Jenkins currently only has authentication support for ed25519. This is a problem for Windows-based testing as we need to have RSA authentication as well. Our release testing that uses Windows clusters has not been properly been reported to Qase as a result.
Added RSA key authentication support in the Jenkinsfile and Dockerfile.
Jenkins jobs will be given to reviewers offline.

[Main] Add RSA key authentication support to Jenkins

---

pkg/rancher/migrations.go

https://github.com/rancher/rancher/pull/47594 prevented crashloop but creds with expired token did not get new annotation added to them which does not allow UI to rotate them.
When harvester credentials are migrated, this now adds a 0 ttl for tokens which were not found, rather than simply skipping those tokens.
To be handled by Harvester team

Adding 0 ttl on harvester migration

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

The Azure client login was using the access token cache which led to additional tokens being cached.
Changed to create a new client for every token authentication which doesn't use the cache.
Configure Rancher for the Azure provider and login and it should create a secret cattle-global-data/azuread-access-token there should be no `RefreshToken`, `IdToken` or `Account` data, there should only be an access token for the Application client_id/tenant id in the data.
Logged in, checked for reduced data, compared against v2.8.5 storage.
* Unit
* None
* If "None" …

Fix cached azure client

---

pkg/capr/planner/etcdcreate.go
pkg/capr/planner/etcdrestore.go
pkg/capr/planner/planner.go
pkg/capr/planner/store.go

https://github.com/rancher/rancher/pull/47500 updated the `max-failures` value on Windows plans. This ensures that plans  which fail due to transient Windows issues unrelated to Rancher are reattempted. In order to properly reattempt plans, changes to the rancher-system agent were required (https://github.com/rancher/system-agent/pull/201). However, #47500 unconditionally updates the `max-failures` value on all Windows plans, even those delivered to nodes running out dated versions of rancher-wins which do not contain the required system-agent changes. This has an unintended side effect of suppressing plan failure errors in the UI. As older versions of rancher-wins do not reattempt plans which have previously succeeded, but have recently failed, Rancher will never display an error in its …

[2.10] Conditionally update max-failures value for windows plans

---

tests/v2/actions/kubeapi/rbac/list.go
tests/v2/validation/rbac/fleetworkspaces/README.md
tests/v2/validation/rbac/fleetworkspaces/fleetworkspaces.go
tests/v2/validation/rbac/fleetworkspaces/fleetworkspaces_test.go

QA task: https://github.com/rancher/qa-tasks/issues/1577
Automate the following P0 tests for GH45811
Note: No backports will be created for this PR

[main] P0 tests for GH45811

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/rancher/issues/46833
Support k8s 1.31
scenario 1 (fresh install):
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.0

Csp-adapter v5.0.0

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

https://github.com/rancher/rancher/issues/45732
kube-api-auth (v0.2.3) was updated to capture LastUsedAt for ClusterAuthToken's.
Bump the kube-api-auth's version.
N/A
N/A

Bump kube-api-auth to v0.2.3

---

pkg/auth/data/authconfig_data.go

Noticed while working on https://github.com/rancher/rancher/pull/47669
The code setting up AuthConfig resources on startup of Rancher ignores already existing resources.
This means that when migrating from a older version of Rancher to the version containing SAML logout
the existing AuthConfig resources are not updated to have a `logoutAllSupported` field with a proper value.
While the CRD update makes the field available it will be set to the default, `false`, for all providers, even those
that do support the new feature.
The code setting up `AuthConfig` resources is extended to not ignore `AlreadyExists` errors.
Instead it uses this as a signal to patch the proper value of `logoutAllSupported` into the existing resource.
This migrates the `AuthConfig` resources of old clusters to have …

Fix: SAML logout AuthConfig migration

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

Backport of #47570 
When spinning up Rancher on an arm64 host, the linode driver attempts to install the amd64 versions, which cannot be run. This causes node driver initialization to get stuck, preventing users from creating cloud credentials and subsequently other node driver clusters.
Download linode as arm64 within arm64 Rancher image
Test creating cloud credentials for unrelated node drivers on arm64 and provisioning linode on amd64 and arm64.
Verify other cloud credentials are unimpacted, and no differences between amd64 & arm64.
* N/A (Existing validations should cover if run on arm).

[47547] [2.9] Download linode as arm64 on arm64

---

go.mod
go.sum
tests/v2/actions/clustertemplates/clustertemplates.go
tests/v2/actions/provisioning/creates.go
tests/v2/validation/clustertemplates/provisioning/README.md
tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
tests/v2/validation/rbac/snapshotrbac/snapshot_rbac_test.go

Backport: https://github.com/rancher/rancher/pull/47256
Note:
Also, includes an error fix on snapshots rbac caused by recent changes and a bump to the latest go.mod and go.sum

[2.8]  Migrating rke templates tests from python to go

---

.github/workflows/go-get.yml
scripts/go-get

- Move the `go generate ./...` command out of the "go-get" script because the script runs inside a Dapper container, which only copies specific files back to the local system. The generated files in `pkg/client/generated/` are not part of those files, so running `go generate` inside the container won't update them locally. By moving it outside, we ensure the files are correctly generated and available in the local environment.
- Update GitHub Actions workflow to use the latest checkout and script versions.
- `go generate` in dapper: https://github.com/rancher/rancher/actions/runs/11334681389/job/31521368140
- `go generate` outside dapper: https://github.com/chiukapoor/rancher/actions/runs/11343938394/job/31547612220
- https://github.com/rancher/rancher/issues/47050

[v2.9] Fix go generate in go-get script

---

.github/workflows/go-get.yml
scripts/go-get

- Move the `go generate ./...` command out of the "go-get" script because the script runs inside a Dapper container, which only copies specific files back to the local system. The generated files in `pkg/client/generated/` are not part of those files, so running `go generate` inside the container won't update them locally. By moving it outside, we ensure the files are correctly generated and available in the local environment.
- Update GitHub Actions workflow to use the latest checkout and script versions.
- `go generate` in dapper: https://github.com/rancher/rancher/actions/runs/11334681389/job/31521368140
- `go generate` outside dapper: https://github.com/chiukapoor/rancher/actions/runs/11343938394/job/31547612220
- https://github.com/rancher/rancher/issues/47014

[v2.8] Fix go generate in go-get script

---

pkg/controllers/management/authprovisioningv2/role.go
pkg/controllers/management/authprovisioningv2/role_test.go

Backport #47192 (almost clean cherry-pick, only a small conflict in the imports)

[v2.9] Sort ResourceNames in Role rules created from RoleTemplates

---

pkg/capr/common.go
pkg/capr/common_test.go
pkg/capr/installer/installer.go
pkg/capr/planner/instructions.go
pkg/capr/planner/instructions_test.go
pkg/capr/planner/planner_test.go

This is a _partial_ backport of https://github.com/rancher/rancher/pull/47500. Only the changes which fix how Windows environment variables are formatted have been included. This is needed so that the changes in the `system-agent-installer-rke2` will be leveraged on 2.9. 
+ Provision a Windows cluster using any version of rke2 
+ Look at the machine-plan secret in the local cluster for the Windows node
+ Verify that the environment variables set in the plan key are not prefixed with `$env:`, do not include quotes around strings and numbers, and does not prefix boolean values with `$`. 
+ Note the `$env:RKE2_DATA_DIR` variable was intentionally not fixed, and will still have the `$env:` prefix and value quotes 
+ Ensure that `WINS_RESTART_STAMP`, `INSTALL_RKE2_VERSION` and …

[v2.9] Backport Windows Environment Variable Formatting Fixes 

---

pkg/api/norman/customization/cluster/validator.go
pkg/controllers/management/k3sbasedupgrade/deployPlans.go
pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/controllers/management/k3sbasedupgrade/template.go
pkg/controllers/management/k3sbasedupgrade/template_test.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go
pkg/image/external/external.go

Backport of https://github.com/rancher/rancher/pull/47271
When new nodes are added to an imported cluster, if that cluster has ever been upgraded, nodes are cordoned and the `rke2-upgrade`/`k3s-upgrade` SUC plans are run against them, despite being a no-op.
Add a label selector to the SUC plan that only selects nodes that have been determined to be out of date. Update the nodesyncer to apply this label when a cluster has been upgraded.
* Unit
- Test case where new node is added on current version after cluster has already been upgraded
- Test case where new node is added on older version after cluster has already been upgraded
- Test case where new node is added on higher version after cluster has already been upgraded
N/A
Existing / newly …

[47589] [2.9] Fix imported cluster node selector

---

tests/v2/actions/projects/projects.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_resource_quota_test.go
tests/v2/validation/projects/projects_test.go

QA Task: https://github.com/rancher/qa-tasks/issues/1599
The "project container default limit" tests are currently failing intermittently with the following error:
```
/root/go/src/github.com/rancher/rancher/tests/v2/validation/projects/projects_container_default_resource_limit_test.go:208
16:33:20          	Error:      	Received unexpected error:
16:33:20          	            	expected label field.cattle.io/projectId not present in namespace labels
```
Solution:
Fix timeout issue in container default limit tests by adding a wait for the project label/annotation to update 
**Backport PRs:** 
- 2.8: https://github.com/rancher/rancher/pull/47755
- 2.9: https://github.com/rancher/rancher/pull/47741

[main] Fix timeout issue in project tests

---

pkg/api/norman/customization/globalnamespaceaccess/access_common.go
pkg/api/norman/customization/multiclusterapp/multi_cluster_app.go
pkg/api/norman/customization/multiclusterapp/validator_multiclusterapp.go
pkg/api/norman/server/managementstored/setup.go
pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go
pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/crtb_handler_test.go
pkg/controllers/management/auth/project_cluster/cluster_handler.go
pkg/controllers/management/auth/project_cluster/common.go
pkg/controllers/management/auth/project_cluster/common_test.go
pkg/controllers/management/auth/project_cluster/project_handler.go
pkg/controllers/management/auth/project_cluster/project_handler_test.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementlegacy/multiclusterapp/handler_multiclusterapp.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml
pkg/systemaccount/systemaccount.go

The project namespace used to get created based on the name of the project. Now it gets created based on the cluster ID and project ID.

[v2.10] Change the backing namespace of projects

---

tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/proxy.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go

The proxy tests do not have a build tag on them, causing the recurring runs to fail. This needs to be addressed.
Added build tags to the proxy tests.

[Main] Add build tags to the proxy tests

---

go.mod
go.sum

Updated to include https://github.com/rancher/steve/pull/311 to facilitate QA testing
* Unit
Steve now reliably honors a namespace filter (during watch/list operations) that it was previously ignoring in some cases, depending on how the API request was formatted. This is strictly a bugfix, so well behaved consumers shouldn't be affected, but anything accidentally relying on the missing filter behavior may need to be adjusted.

[v2.8] go get steve to include refactored partitioning

---

pkg/auth/providers/local/local_auth_provider.go
pkg/auth/providers/local/local_auth_provider_test.go

This fixes the case where the search string exactly matches a user's display name.
Searching for exact match strings with non-ASCII strings was failing.
Improved the string comparison for the iterate-and-match search approach. 
* Unit
* None
_TODO_
* _TODO_

Fix exact-match search for strings in user-search.

---

.github/workflows/integration-tests.yml
.github/workflows/provisioning-tests.yml
scripts/gha/run
scripts/gha/tests
scripts/provisioning-tests
scripts/run
tests/v2prov/defaults/defaults.go

https://github.com/rancher/rancher/issues/46222
This PR bumps `rancher/systemd-node` to `v0.0.5`, which contains a script that facilitates the usage of cgroupsv2.
It makes corrections to the logic used to run the integration-tests environment, as well as adding cgroups draining logic to the `provisioning-tests` script and corresponding Rancher `run`.

[main] Enable provisioning-tests and integration-tests to use cgroupsv2

---

tests/v2/validation/networking/README.md
tests/v2/validation/networking/connectivity/network_policy.go
tests/v2/validation/networking/connectivity/network_policy_test.go
tests/v2/validation/networking/connectivity/port_test.go
tests/v2/validation/workloads/workload.go
tests/validation/tests/v3_api/test_workload.py

Backports
v2.9: https://github.com/rancher/rancher/pull/47840
v2.8 https://github.com/rancher/rancher/pull/47841
v2.7 https://github.com/rancher/rancher/pull/47842

<main> Convert connection workload tests from Python to Go

---

pkg/agent/clean/cluster.go
pkg/controllers/dashboard/scaleavailable/scale.go
pkg/controllers/management/usercontrollers/controller.go

fix the cluster-cleanup logic where finalizers on the deployments are not properly removed
https://github.com/rancher/rancher/issues/47863
In the downstream cluster, the `systemChart` handler runs within the cattle-cluster-agent, adding the `wrangler.cattle.io/legacy-k3sBasedUpgrader-deprecation` finalizer to all Deployments in all namespaces. When an imported cluster is removed from Rancher, Rancher triggers a cleanup job on the downstream cluster to delete all Rancher-related resources. However, due to this finalizer, Deployments in the `cattle-system` namespace, as well as the namespace itself, become stuck in the removal process. This occurs even though the cleanup job reports success because it successfully initiates the namespace deletion.
Note that this issue is generic and can be …

[2.10] fix the cluster-cleanup logic

---

pkg/settings/setting.go

- `rancher/dashboard` and `rancher/ui` have both now branched for 2.10
- This change ensures the `rancher/rancher` points to the correct builds for the 2.10 release
- These builds are used, when settings are default, when the version ends in head as an alternative to the embedded builds
- This change will need to be reverted in `main` after `rancher/rancher` branches for 2.10

Update references to new 2.10 UI branches

---

pkg/agent/clean/cluster.go
pkg/controllers/dashboard/scaleavailable/scale.go
pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go
pkg/controllers/management/usercontrollers/controller.go

~The provisioning tests are failing to wait for the `rancher-webhook` deployment to become active, as the image `registry.rancher.com/rancher/rancher-webhook:v0.6.1-rc.9` is missing.~
~Once the image-missing issue is resolved by other teams, I'll run the failed CI tests again.~
https://github.com/rancher/rancher/issues/47863
The usage of  Wrangler's `onRemove()` function results in adding the `wrangler.cattle.io/legacy-k3sBasedUpgrader-deprecation` finalizer to all Deployments across namespaces. This leads to resource cleanup failures in downstream imported clusters when removed from Rancher. While [the cleanup logic was enhanced](https://github.com/rancher/rancher/pull/47882) to address this, it does not resolve the broader issue of the finalizer being applied to all Deployments in all …

[2.10] replace the usage of Wrangler's onRemove() function with onChange(), combined with a custom finalizer

---

build.yaml
pkg/buildconfig/constants.go

* [0.6] Revert backing namespace changes by @JonCrowther in https://github.com/rancher/webhook/pull/539
* Sync dependencies with Rancher by @tomleb in https://github.com/rancher/webhook/pull/540
**Full Changelog**: https://github.com/rancher/webhook/compare/v0.6.1-rc.11...v0.6.1-rc.12
- Commit comparison: https://github.com/rancher/webhook/compare/v0.6.1-rc.9...v0.6.1-rc.12
- Release v0.6.1-rc.9: https://github.com/rancher/webhook/releases/tag/v0.6.1-rc.9

Bump rancher-webhook to v0.6.1-rc.12

---

build.yaml
pkg/buildconfig/constants.go

* Revert "[v0.5] Populate backing namespace field for projects" by @JonCrowther in https://github.com/rancher/webhook/pull/538
* [v0.5] Sync dependencies with Rancher by @tomleb in https://github.com/rancher/webhook/pull/541
**Full Changelog**: https://github.com/rancher/webhook/compare/v0.5.4-rc.1...v0.5.4-rc.2
- Commit comparison: https://github.com/rancher/webhook/compare/v0.5.3...v0.5.4-rc.2
- Release v0.5.3: https://github.com/rancher/webhook/releases/tag/v0.5.3

Bump rancher-webhook to v0.5.4-rc.2

---

pkg/controllers/management/node/controller.go

https://github.com/rancher/rancher/issues/47938
When provisioning RKE1 node driver clusters, if cloud-init user data is set in the node template (currently available only for vSphere node templates in the Rancher UI, though it can be added to other node template types via the API), node creation will fail due to permission issues.
This PR adjusts the cluster provisioning logic to set the appropriate ownership of the affected files. 
The issue was reproduced by creating a node-driver RKE1 cluster with a Digital Ocean node template, where user data was added via the API. 
The fix has been validated on a Rancher build from the PR. Using the same Digital Ocean node template, the cluster is created successfully, confirming the fix works as expected.
Please reach out to me for more details if …

[2.10] fix RKE1 cluster provisioning failures

---

build.yaml
pkg/buildconfig/constants.go

Addresses https://github.com/rancher/csp-adapter/issues/104
Remove csp-adapter k8s 1.27 support 
Scenario 01:
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.1-rc1
Scenario 02:
Start with an EKS cluster (k8s version 1.30), install rancher 2.9.3 with csp-adapter 4.0.0
Upgrade rancher to locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.1-rc1
Update charts url repo/branch and upgrade …

[v2.10] Csp-adapter v5.0.1-rc1

---

tests/v2/validation/fleet/provisioning/airgap/README.md
tests/v2/validation/fleet/provisioning/airgap/airgap.go
tests/v2/validation/fleet/provisioning/airgap/fleet_in_airgap_test.go

https://github.com/rancher/qa-tasks/issues/1524 
we need to test deploying fleet repos in airgap, as well as checking that the resources from the repo are deployed correctly to specified clusters. 
* add ssh helpers to a new file in fleet/ that clone the fleet-examples repo for use in the airgapped cluster(s)
* add helpers to create fleet secrets that can pull the git repo from the bastion node using SSH
* add airgap + fleet provisioning test
local and CI (jenkins) passed

[main] add airgap tests for fleet -- approved, waiting for thaw

---

build.yaml
pkg/buildconfig/constants.go

Addresses https://github.com/rancher/csp-adapter/issues/104
Remove csp-adapter k8s 1.27 support 
Scenario 01:
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.1-rc1
Scenario 02:
Start with an EKS cluster (k8s version 1.30), install rancher 2.9.3 with csp-adapter 4.0.0
Upgrade rancher to locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.1-rc1
Update charts url repo/branch and upgrade …

[v2.10] Backport csp adpater v5.0.1 rc1

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[v2.10] Bump rke to v1.7.0-rc.7

---

build.yaml
pkg/buildconfig/constants.go

* [v0.4] Sync dependencies with Rancher by @tomleb in https://github.com/rancher/webhook/pull/542
**Full Changelog**: https://github.com/rancher/webhook/compare/v0.4.12...v0.4.13
- Commit comparison: https://github.com/rancher/webhook/compare/v0.4.13-rc.1...v0.4.13
- Release v0.4.13-rc.1: https://github.com/rancher/webhook/releases/tag/v0.4.13-rc.1

[v2.8] Bump rancher-webhook to v0.4.13

---

build.yaml
pkg/buildconfig/constants.go

* Add validation for ClusterRepo by @rohitsakala in https://github.com/rancher/webhook/pull/470
* Remove a race condition from a flakey integration test by @ericpromislow in https://github.com/rancher/webhook/pull/469
* [46381] [2.10] Add validation to data directories on creation by @jakefhyde in https://github.com/rancher/webhook/pull/474
* Change the base branch from "release/v0.5" to "main" in renovate config by @maxsokolovsky in https://github.com/rancher/webhook/pull/486
* Current dev work is now for rancher 2.10 by @ericpromislow in https://github.com/rancher/webhook/pull/468
* Update actions/upload-artifact digest to 834a144 by @renovate-rancher in https://github.com/rancher/webhook/pull/487
* Update module github.com/rancher/dynamiclistener to v0.6.0 by @renovate-rancher in …

[v2.10] Bump rancher-webhook to v0.6.1

---

build.yaml
pkg/buildconfig/constants.go

* Validate LastUsedAt for Token and ClusterAuthToken by @andreas-kupries in https://github.com/rancher/webhook/pull/480
* Revert "Validate LastUsedAt for Token and ClusterAuthToken (#480)" by @pmatseykanets in https://github.com/rancher/webhook/pull/519
* Revert "[v0.5] Populate backing namespace field for projects" by @JonCrowther in https://github.com/rancher/webhook/pull/538
* [v0.5] Sync dependencies with Rancher by @tomleb in https://github.com/rancher/webhook/pull/541
* [v0.5] unRC *-operator by @tomleb in https://github.com/rancher/webhook/pull/544
**Full Changelog**: https://github.com/rancher/webhook/compare/v0.5.3...v0.5.4
- Commit comparison: https://github.com/rancher/webhook/compare/v0.5.4-rc.2...v0.5.4
- Release v0.5.4-rc.2: …

[v2.9] Bump rancher-webhook to v0.5.4

---

build.yaml
pkg/buildconfig/constants.go

* Add validation for ClusterRepo by @rohitsakala in https://github.com/rancher/webhook/pull/470
* Remove a race condition from a flakey integration test by @ericpromislow in https://github.com/rancher/webhook/pull/469
* [46381] [2.10] Add validation to data directories on creation by @jakefhyde in https://github.com/rancher/webhook/pull/474
* Change the base branch from "release/v0.5" to "main" in renovate config by @maxsokolovsky in https://github.com/rancher/webhook/pull/486
* Current dev work is now for rancher 2.10 by @ericpromislow in https://github.com/rancher/webhook/pull/468
* Update actions/upload-artifact digest to 834a144 by @renovate-rancher in https://github.com/rancher/webhook/pull/487
* Update module github.com/rancher/dynamiclistener to v0.6.0 by @renovate-rancher in …

Bump rancher-webhook to v0.6.1

---

build.yaml
pkg/buildconfig/constants.go

This PR un-rc's csp-adapter v5.0.1 and takes into consideration rancher/wrangler versioning changes.
Scenario 01:
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.1
Scenario 02:
Start with an EKS cluster (k8s version 1.30), install rancher 2.9.3 with csp-adapter 4.0.0
Upgrade rancher to locally built rancher with cspAdapterMinVersion: 105.0.0+up5.0.1
Update charts url repo/branch and upgrade …

[v2.10] Csp-adapter v5.0.1 (un-rc)

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/47151
The UI relies on the `cli-version` setting to show Rancher CLI version on /dashboard/about page, but this setting is not defined in Rancher.
Define the setting so it can be read and materialized from the `CATTLE_CLI_VERSION` env variable defined in the Dockerfile.
N/A
N/A

[v2.8] Make cli-version setting known to Rancher

---

pkg/data/management/bootstrap_password.go

https://github.com/rancher/rancher/issues/47964
Add proper checks to verify secret exists and has valid PW data, then read the data by base64 decoding it.
I've verified this works by following the reproduction steps from the issue. First to verify the bug, then again using my local built image with this change verifying the issue is gone.
The debug image I used is:
```
rancherImage: mallardduck/rancher
rancherImageTag: v2.10.0-dev.35
```

Address bug when bootstrap secret is created outside of Rancher helm-chart

---

pkg/capr/planner/etcdcreate.go
pkg/capr/planner/etcdrestore.go
pkg/capr/planner/planner.go
pkg/capr/planner/store.go

In all previously released versions of Rancher, the `rancher-wins` service does have its underlying binary automatically upgraded to the latest version after an upgrade of the Rancher server. This behavior differs from Linux, and forces users to reprovision their Windows nodes in order to receive the latest enhancements within the `system-agent` (which is embedded in `rancher-wins`). This has resulted in unnecessary conditional logic within Rancher to account for behavior differences on nodes joined to the same cluster.
While implementing https://github.com/rancher/rancher/issues/46620 for Windows nodes, an issue was encountered where plan failures would not be accurately reported as out-dated versions of `rancher-wins` did not contain the necessary `system-agent` changes. To address …

[main] Always reset failure counts on existing plans

---

pkg/agent/cluster/cluster.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Backport of https://github.com/rancher/rancher/pull/47273
Mitigate the impact of the client cache on detecting secrets.
When we can't find a secret in EnsureSecretForServiceAccount, create a secret and annotate the ServiceAccount that it's for with the secret reference.
If we get a conflict error doing this, then rollback the newly created secret.
* Unit
* None
_TODO_
* _TODO_

[2.10] Backport Cache mitigation

---

tests/v2/actions/auth/auth.go
tests/v2/actions/rbac/rbac.go
tests/v2/validation/auth/userretention/userretention.go
tests/v2/validation/auth/userretention/userretention_delete_user_test.go
tests/v2/validation/auth/userretention/userretention_disable_user_test.go
tests/v2/validation/auth/userretention/userretention_settings_test.go

**This PR has two changes:**
1. Userretention settings updates to main branch (These changes were approved on v2.9 already and merged)
2. Added new tests related to Auth TTL https://github.com/rancher/rancher/issues/46648
**Note:**
The recent changes related to Auth TTL were in the file tests/v2/validation/auth/userretention/userretention_settings_test.go

Userretention settings tests to main

---

build.yaml
pkg/buildconfig/constants.go

Update the CAPI chart to the new version from this PR: https://github.com/rancher/charts/pull/4784
This incorporates two fixes:
- https://github.com/rancher/provisioning/pull/15
- https://github.com/rancher/provisioning/pull/16
The related issues are:
- https://github.com/rancher/rancher/issues/48005
- https://github.com/rancher/rancher/issues/48094

[v2.10] Pin CAPI chart to 105.1.0+up0.6.0

---

build.yaml
pkg/buildconfig/constants.go

Update the CAPI chart to the new version from this PR: https://github.com/rancher/charts/pull/4793
This incorporates one fix:
- https://github.com/rancher/provisioning/pull/17
The related issues are:
- https://github.com/rancher/rancher/issues/48164

[v2.9] Pin CAPI chart to 104.1.0+up0.3.1

---

pkg/auth/providers/local/local_auth_provider.go
pkg/auth/providers/local/local_auth_provider_test.go

When the string is lower-cased to a shorter-string because it becomes an ASCII character when lower-cased, this was causing an issue when slicing the string for indexing because the slice length was too long.
This necessitates two small changes, one to recalculate the length for the sub-slice _after_ lower-casing the string, and the other is to trim \x00 characters because the length is predetermined in `indexField`.
Create a user with a character that is lower-cased to an ASCII character e.g. https://www.compart.com/en/unicode/U+212A and it will crash-loop on startup during the indexing.
* Unit
* None
* _REMOVE NOT APPLICABLE BULLET POINTS …

[v2.10] Fix local search unicode

---

tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go

supports https://github.com/rancher/qa-tasks/issues/1619
fleet wasn't deploying on hardened clusters
created new fleet in the example repo, this PR points the hardened provisioning + fleet case to the new hardened example. 
via jenkins

updating fleet provisioning to be hardened by default

---

pkg/auth/providers/local/local_auth_provider.go
pkg/auth/providers/local/local_auth_provider_test.go

When the string is lower-cased to a shorter-string because it becomes an ASCII character when lower-cased, this was causing an issue when slicing the string for indexing because the length was too long.
This necessitates two small changes, one to recalculate the length for the sub-slice _after_ lower-casing the string, and the other is to trim \x00 characters because the length is predetermined in `indexField`.
Create a user with a character that is lower-cased to an ASCII character e.g. https://www.compart.com/en/unicode/U+212A and it will crash-loop on startup during the indexing.
* Unit
* None
* …

Handle conversion to shorter-strings in user-indexing

---

pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/eks/eks_cluster_handler_test.go

If an error occurs when the upstream state is being constructed, `.status.eksStatus.upstreamSpec` will remain nil causing a panic later when it is accessed. This PR check if field is nil and returns an error to avoid a panic.
Added a nil check to prevent panic.
* Unit
_TODO_
* _TODO_

fix: Check if upstreamSpec is nil

---

cleanup/binding-clean.sh
cleanup/user-cluster.sh

Backport of https://github.com/rancher/rancher/pull/48318
Works towards resolving https://github.com/rancher/rancher/issues/47402
Repro steps in https://github.com/rancher/rancher/issues/43343 are valid, specifically workarounds in [this comment](https://github.com/rancher/rancher/issues/43343#issuecomment-2521230888) should no longer be required

[2.8] Have both cleanup scripts reference their yml from the current branch

---

cleanup/binding-clean.sh
cleanup/user-cluster.sh

Backport of https://github.com/rancher/rancher/pull/48318
Works towards resolving https://github.com/rancher/rancher/issues/47402
Repro steps in https://github.com/rancher/rancher/issues/43343 are valid, specifically workarounds in [this comment](https://github.com/rancher/rancher/issues/43343#issuecomment-2521230888) should no longer be required

[2.9] Have both cleanup scripts reference their yml from the current branch

---

cleanup/binding-clean.sh
cleanup/user-cluster.sh

Works towards resolving https://github.com/rancher/rancher/issues/47402
Repro steps in https://github.com/rancher/rancher/issues/43343 are valid, specifically workarounds in [this comment](https://github.com/rancher/rancher/issues/43343#issuecomment-2521230888) should no longer be required

[main] Have both cleanup scripts reference their yml from the main branch

---

cleanup/binding-clean.sh
cleanup/user-cluster.sh

Backport of https://github.com/rancher/rancher/pull/48318
Works towards resolving https://github.com/rancher/rancher/issues/47402
Repro steps in https://github.com/rancher/rancher/issues/43343 are valid, specifically workarounds in [this comment](https://github.com/rancher/rancher/issues/43343#issuecomment-2521230888) should no longer be required

[2.10] Have both cleanup scripts reference their yml from the current branch

---

pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/eks/eks_cluster_handler_test.go

If an error occurs when the upstream state is being constructed, `.status.eksStatus.upstreamSpec` will remain nil causing a panic later when it is accessed. This PR check if field is nil and returns an error to avoid a panic.
This is a forward port of #48298 .
Added a nil check to prevent panic.
* Unit
_TODO_
* _TODO_

[v2.10] fix: Check if upstreamSpec is nil

---

pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/cluster/controller_test.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go
pkg/settings/setting.go

https://github.com/rancher/turtles/issues/622
Management v3 cluster creation always creates a fleet agent for the cluster import. This prevents having more granular settings regarding fleet agent configuration.
Prevent setting default fleet workspace name for the clusters annotated with “provisioning.cattle.io/externally-managed”. Users can always explicitly specify the `fleetWorkspaceName` on the cluster, in order to provision fleet agent.
As the `fleetWorkspaceName` is a discriminating value between legacy and non-legacy clusters, treat clusters which are annotated with `provisioning.cattle.io/externally-managed` as requiring provisioning cluster creation, due to https://github.com/rancher/dashboard/issues/11664 (imported clusters are not visible).
Original solution using `setting` was …

Allow to disable fleet cluster provisioning via provisioning.cattle.io/externally-managed annotation

---

pkg/nodeconfig/archive.go
pkg/nodeconfig/config.go

https://github.com/rancher/rancher/issues/48320
After upgrading from 2.9.2 to 2.9.4, deleting a downstream RKE1 cluster node (e.g., scaling down a node pool) created before the upgrade results in the node being successfully removed from Rancher and the downstream cluster. However, the VM remains undeleted on the infrastructure provider. 
The root cause is a file permission issue preventing `rancher-machine`, running as a non-root user, from accessing the necessary files to delete the machine.
Set the file permissions properly during the file creation process. 
The fix was validated using a custom build of Rancher from this branch. Following the same steps outlined in the issue, the VMs are now correctly removed from the infrastructure provider as expected. Digital Ocean was used as the …

[main] Fix the issue where VM not being deleted from the cloud

---

pkg/api/norman/customization/node/node.go
pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go
pkg/node/node.go

https://github.com/rancher/rancher/issues/48375
delete-local-data flag was removed in k8s v1.31 so the cluster upgrades with drain enabled are failing.
ref: https://github.com/kubernetes/kubernetes/blob/8a39b6062060ffb4fba52f53c011bd00428db194/CHANGELOG/CHANGELOG-1.31.md?plain=1#L1197
* Unit
* None
_TODO_
* _TODO_

[v2.10] replace delete-local-data flag with delete-emptydir-data

---

pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementuser/rbac/handler_base.go
pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/rbac/project_handler.go
pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/roletemplate_handler.go
pkg/namespace/namespace.go
pkg/namespace/namespace_test.go

When a RoleTemplate is removed, those projects where a member was granted that RoleTemplate will error reconciling with the following error:
```
handler namespace-auth: couldn't get role template rt-2bmwx: roletemplates.management.cattle.io "rt-2bmwx" not found, requeuing
```
It will be retried indefinitely although rate limited to a maximum of 2 minutes wait.
Returning an error makes the handler(s) to be retried. Instead just log a warning message and skip that PRTB.

fix(rbac): Avoid returning an error when RoleTemplate does not exist

---

.github/workflows/integration-tests.yml
.github/workflows/validate.yml
Dockerfile-windows.dapper
Dockerfile.dapper
go.mod
hack/airgap/go.mod
package/Dockerfile
package/Dockerfile.agent
package/windows/Dockerfile.agent
pkg/apis/go.mod
pkg/client/go.mod
pkg/codegen/buildconfig/main.go
pkg/codegen/main.go
tests/v2/codecoverage/Dockerfile.buildcodecoverage
tests/v2/codecoverage/Dockerfile.codecoverage
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/steve/vai/scripts/script.sh

Ref: https://github.com/rancher/rancher/issues/48404
The new stable BCI golang image `registry.suse.com/bci/golang:1.23` is now available.
Start building with Go 1.23 using the latest available toolchain in the BCI image.
N/A
N/A
N/A

Bump Go to 1.23.4

---

pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go

This changes the logic to ensure that we update a copy of the resource so that we can avoid updating the cached version and concurrent map updates.
* Unit
* None
_TODO_
* _TODO_

Fix concurrent SA updates for Secrets

---

pkg/controllers/management/cluster/clustercontroller.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/clusterprovisioner/store.go
pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
pkg/controllers/management/etcdbackup/etcdbackup.go
pkg/controllers/managementuser/certsexpiration/certsexpiration.go
pkg/encryptedstore/secrets_store.go
pkg/nodeconfig/config.go
pkg/rkenodeconfigserver/lookup.go

Re-opening PR: https://github.com/rancher/rancher/pull/44560
Custom downstream cluster secrets remain in the local cluster after the custom downstream cluster is deleted 
Add owner reference to the secret so that the secret will be automatically deleted once the cluster is deleted.
- Create a custom rke1 cluster
- Check secret (kubectl -n cattle-system get secrets -l cattle.io/creator=norman) if it's created or not
- Delete the custom cluster
- Check secret (kubectl -n cattle-system get secrets -l cattle.io/creator=norman) if it's deleted or not
* Unit
* None
* If "None" - Reason: _EXPLAIN THE …

[SURE-5388]: add owner reference to the secret

---

build.yaml
pkg/buildconfig/constants.go

Contains https://github.com/rancher/charts/pull/4884
With these changes https://github.com/rancher/webhook/releases/tag/v0.5.5-rc.1
No new webhook features this round, just a dependency sync with `rancher/rancher`, so we're just looking out for regressions.

[v2.9] Update webhook to 0.5.5-rc1

---

go.mod
go.sum
tests/v2/actions/upgradeinput/load.go
tests/v2/validation/upgrade/kubernetes.go
tests/v2/validation/upgrade/kubernetes_test.go
tests/v2/validation/upgrade/workload_test.go

Local upgrade jenkins job fails to upgrade local cluster with a panic    
```
panic.go:114: test panicked: runtime error: index out of range [0] with length 0
12:37:55          github.com/rancher/rancher/tests/v2/validation/upgrade.upgradeLocalCluster(_, {_, _}, _, {_, _}, _, {{0xc000b09bca, 0x5}, {0x0, ...}, ...}, ...)
12:37:55          	/root/go/src/github.com/rancher/rancher/tests/v2/validation/upgrade/kubernetes.go:50 +0x725
12:37:55          github.com/rancher/rancher/tests/v2/validation/upgrade.(*UpgradeKubernetesTestSuite).TestUpgradeKubernetes(0xc000289260)
12:37:55          	/root/go/src/github.com/rancher/rancher/tests/v2/validation/upgrade/kubernetes_test.go:55 +0x26b
```
This PR fixes two isses: 
1. Local cluster upgrade fix: The issue occurs because the code depends on …

Fixes the local upgrade failure

---

build.yaml
pkg/buildconfig/constants.go

Contains: https://github.com/rancher/charts/pull/4882
Which includes all of: https://github.com/rancher/webhook/releases/tag/v0.4.14-rc.1
Shouldn't be any new features, though we had to wrangle more than usual with upstream k8s pinning. Keep an eye out for regressions.

[v2.8] Update webhook to 0.4.14-rc.1

---

build.yaml
pkg/buildconfig/constants.go

Contains: https://github.com/rancher/charts/pull/4883
Including: https://github.com/rancher/webhook/releases/tag/v0.6.2-rc.1
No new webhook features, just testing for regressions.

[2.10] Update webhook to v0.6.2-rc1

---

pkg/catalogv2/helmop/operation.go
pkg/catalogv2/system/system.go
tests/v2/integration/catalogv2/charts_test.go

* Fix adding tolerations automatically when spec.tolerations is nil.
* Checking for rke1 control plane label.

Fix automatic toleration merge when performing chart upgrades and add support for rke1 tolerations

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

As wrangler v3.0.1 is released, refer to the release artifact rather than the last rc4 candidate: https://github.com/rancher/wrangler/releases/tag/v3.0.1

[2.9] unRC wrangler to v3.0.1

---

build.yaml
pkg/buildconfig/constants.go

Containing: https://github.com/rancher/charts/pull/4887
Now with wrangler pinned to its `v3.0.1` release

[v2.9] update webhook to v0.5.5-rc3

---

pkg/data/dashboard/fleet.go

That code is no longer needed.
Context:  `Gitjob`, an old resource used by Fleet <0.10, used [steve](https://github.com/rancher/steve) code in the context of exposing git jobs via an API service object.
It is unclear whether that feature has ever worked, as there was a mismatch between secret names used ([stv-aggregation](https://github.com/rancher/rancher/commit/a94662178cd7874807a604fad5dec0f2dd8ba57c) in `rancher/rancher` vs [steve-aggregation](https://github.com/rancher/gitjob/commit/cc95fddcdd98d5f910977776f6da78c8c5c87a21#diff-df64e37f2222b761c62bd8bf32c0347aae0fe1f46ff6acf0e66c2b61bd30d761) in `rancher/gitjob`).
This removes the mentioned remote dialer code.
N/A (functionality did not work and was not used)
N/A (functionality did not work and was not used)
N/A (functionality did …

Remove remote dialer code from Fleet dashboard

---

pkg/capr/installer/installer.go
pkg/capr/installer/installer_test.go

The `WindowsInstallScript` function does not properly append new lines to agent environment variables when generating the rancher-wins install script. In the event that multiple agent environment variables are specified, they will be placed on a single line - preventing rancher-wins from installing. This issue only occurs with vSphere node driver clusters, which is likely why it was not caught when validating other issues relating to proxy env vars.
Ensure that each agent environment variable string has a newline appended to it when generating the rancher-wins install script.
Create a new vSphere cluster using the Rancher UI. Add two agent environment variables in the UI before creating the cluster (the name and value can be arbitrary). Ensure that the node joined successfully, and that …

[main] Fix vSphere Node Driver Windows Install Script Env Vars 

---

pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/crtb_handler_test.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go
pkg/controllers/managementuser/rbac/crtb_handler.go
pkg/controllers/managementuser/rbac/crtb_handler_test.go
pkg/controllers/managementuser/rbac/globalrolebinding_handler.go
pkg/controllers/managementuser/rbac/globalrolebinding_handler_test.go

Update the `CRTB` and `GRB` Status fields to ensure the `lastUpdatedTime` format matches the format of other fields by using `time.RFC3339`

Change CRTB Status lastUpdatedTime format 

---

chart/templates/ingress.yaml
chart/tests/ingress_test.yaml
chart/values.yaml

Rancher's helm chart hardcodes the `.spec.rules[].http.paths[].path` to `"/"` and `.spec.rules[].http.paths[].pathType` to `ImplementationSpecific` in the ingress crd. It is common practice in other helm charts to allow the user to modify these 2 spec parameters in the values.yaml. The reporter in Issue https://github.com/rancher/rancher/issues/48167 reported:
>on GKE, ingress path should be set to `"/*"` not `"/"` .
PR adds `.Values.ingress.path` and `.Values.ingress.pathType` to the ingress template and values.yaml making these parameters configurable while keeping the current default. 
Ran the helm-unittest.sh script with no errors.
```bash
% ./dev-scripts/helm-unittest.sh
==> Linting ./
1 chart(s) linted, 0 chart(s) failed
2024/12/18 17:53:02 warning: skipped value for …
```

[CHART] Support user modifying ingress path/pathType

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml

A backport of recent chart change: https://github.com/rancher/rancher/pull/47038

[Backport v2.9][CHART] Support additional taints tolerations

---

pkg/data/management/bootstrap_password.go

This is a backport of: https://github.com/rancher/rancher/pull/47965

[Backport v2.10] Address bug when bootstrap secret is created outside of Rancher helm-chart

---

pkg/data/management/bootstrap_password.go

This is a backport of: https://github.com/rancher/rancher/pull/47965

[Backport v2.9] Address bug when bootstrap secret is created outside of Rancher helm-chart

---

go.mod
go.sum
tests/v2/actions/upgradeinput/load.go
tests/v2/validation/upgrade/kubernetes.go
tests/v2/validation/upgrade/kubernetes_test.go
tests/v2/validation/upgrade/workload_test.go

Back port of 
https://github.com/rancher/rancher/pull/48292
shepeherd changes are yet to be merged for this release. once that is merged, would need to update the go.mod changes in this PR.

[2.8] Fixes the local upgrade failure 

---

chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml

Rancher's chart doesn't allow much control over certain aspects due to requirements of the system. Specifically the requirement/expectation that "Rancher expects to be the sole application on and owning the 'local' cluster".
Some of these related values can be - with an acceptable amount of risk - be exposed to users for configuring _additional_ values. This applies to areas like Node Selector / Affinity / Tolerations and some what to `resources`. Overall it's probably OK if users add to the required rancher rules, but they still need to use them with care to ensure it fits their specific use-case.
Add new helm chart values to control these areas that can be modified in an additive manner with lower risk.
For Sidecar resources, try using:
```
auditLog:
level: 3
resources:
requests:
cpu: …
```

[2.11] Add new Rancher chart value fields

---

pkg/controllers/provisioningv2/provisioninglog/provisioninglog.go
pkg/controllers/provisioningv2/provisioninglog/provisioninglog_test.go

We currently pop the newest logs from the provisioning-log configmap instead of the oldest, so once it hits the self-imposed limit of 10k it will just never update.
Rotate oldest logs first
Added unit tests to confirm behavior.

Remove oldest lines from provisioning-log instead of newest

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

Bump Harvester machine driver to version v0.7.1.
https://github.com/harvester/harvester/issues/6829
https://github.com/rancher/rancher/issues/47631
Bump kubernetes package version in `go.mod`.
1. Confirm that the Harvester node driver shows up in Version v0.7.1
2. Install a Harvester cluster and import into Rancher for virtualization management
3. Create new cloud credentials
4. Create a downstream cluster using the Harvester node driver
5. Rotate cloud credentials as explained in https://harvesterhci.io/kb/renew_harvester_cloud_credentials/
6. Scale down / delete the downstream cluster. This should complete without errors.
* Unit
* None
* …

feat: bump harvester driver to v0.7.1

---

pkg/controllers/provisioningv2/provisioninglog/provisioninglog.go
pkg/controllers/provisioningv2/provisioninglog/provisioninglog_test.go

Backport of #48285
We currently pop the newest logs from the provisioning-log configmap instead of the oldest, so once it hits the self-imposed limit of 10k it will just never update.
Rotate oldest logs first
Added unit tests to confirm behavior.

[2.10] Remove oldest lines from provisioning-log instead of newest

---

pkg/controllers/provisioningv2/provisioninglog/provisioninglog.go
pkg/controllers/provisioningv2/provisioninglog/provisioninglog_test.go

Backport of #48285
We currently pop the newest logs from the provisioning-log configmap instead of the oldest, so once it hits the self-imposed limit of 10k it will just never update.
Rotate oldest logs first
Added unit tests to confirm behavior.

[2.9] Remove oldest lines from provisioning-log instead of newest

---

pkg/controllers/capr/managesystemagent/managesystemagent.go

Backport of #48569
When the `stv-aggregation` secret changes, which is used to populate the `system-agent-upgrader` SUC plan, SUC will not check the contents of the secret, and thus the plan will not be updated.
Utilize the `secrets` feature within SUC.
Tested manually, confirming the values from the secret were used and changing the secret results in the plan being applied.

[2.9] [48441] Add stv-aggregation secret to system-agent-upgrader suc plan

---

pkg/api/norman/customization/aks/listers.go

We want to list only official Kubernetes versions and skip LTS which required additional paid support in Azure
Issue: https://github.com/rancher/aks-operator/issues/717 (cherry picked from commit f9879edd52f3df6ee678eb56d25e2be698b2ab81)
* Unit
* None
_TODO_
* _TODO_

[v2.9] [aks-operator] List only supported Kubernetes versions

---

pkg/api/norman/customization/aks/listers.go

We want to list only official Kubernetes versions and skip LTS which required additional paid support in Azure
Issue: https://github.com/rancher/aks-operator/issues/717 (cherry picked from commit f9879edd52f3df6ee678eb56d25e2be698b2ab81)
* Unit
* None
_TODO_
* _TODO_

[v2.10] [aks-operator] List only supported Kubernetes versions

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Unlike Linux, Windows nodes do not currently upgrade the installed version of the rancher-wins (and thus the system-agent) alongside Rancher upgrades. This is problematic in cases where a given version of Rancher relies on functionality recently added to the system-agent installed on Windows nodes.
The rancher-wins SUC image has been enhanced to automatically upgrade the installed version if it differs from the version embedded within the currently running version of Rancher. This ensures that nodes are always running the correct version of `rancher-wins` (and thus the `system-agent`) for the given version of Rancher
+ Setup a released version of Rancher and manually override the `CATTLE_WINS_AGENT_UPGRADE_IMAGE` environment variable to point to `rancher/wins:v0.5.0-rc.1`
+ Using a …

[Main] Bump wins to `v0.5.0-rc.1`

---

pkg/settings/setting.go

Rancher head builds contain Dashboard 2.10 artifacts.
This reverts #47891. 2.10 has been released and head builds should direct to Dashboard `master` branch for 2.11 testing.

Revert: Update references to new 2.10 UI branches

---

pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go

Issue: #48470
Backport of https://github.com/rancher/rancher/pull/48422

[v2.9] Backport Fix concurrent SA updates for Secrets (#48422)

---

pkg/kontainer-engine/drivers/util/utils.go

https://github.com/rancher/rancher/issues/48417
Etcd snapshot restore fails in PostCheck step when GenerateServiceAccountToken is called in some cases. If rke1 cluster k8s upgrade is done with Drain nodes enabled in upgrade strategy and then if we try to restore it to old k8s version using etcd snapshot the restore continuously fails in PostCheck with following error
`
err: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces.create-non-kubesystem": failed to call webhook: Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/validation/namespaces?timeout=10s)": dial tcp 10.43.113.34:443: i/o timeout,
`
it happens when Create request is made for the cattle-system …

[main] updated logic for creating cattle-system namespace

---

pkg/kontainer-engine/drivers/util/utils.go

https://github.com/rancher/rancher/issues/48419
Etcd snapshot restore fails in PostCheck step when GenerateServiceAccountToken is called in some cases. If rke1 cluster k8s upgrade is done with Drain nodes enabled in upgrade strategy and then if we try to restore it to old k8s version using etcd snapshot the restore continuously fails in PostCheck with following error
`
err: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces.create-non-kubesystem": failed to call webhook: Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/validation/namespaces?timeout=10s)": dial tcp 10.43.113.34:443: i/o timeout,
`
it happens when Create request is made for the cattle-system …

[v2.10] updated logic for creating cattle-system namespace

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This is a maintenance bump to bring in the latest RC of `rancher-wins`. This version simply includes several dependency bumps

[main] Bump wins to `v0.5.0-rc.2`

---

pkg/api/norman/store/cluster/cluster_store.go
pkg/settings/setting.go

When creating or updating a RKE1 cluster configured with a S3 bucket for storing ETCD backups, the store functions check if the bucket exists. This was done without a timeout, so if S3 wasn't reachable, it could take a long and system-dependent time for the check to fail. These functions hold a lock while doing this check, as part of a mechanism for ensuring unique cluster names. This meant that no new cluster could be created as long as the the request didn't fail and the lock was held.
This commit adds a 30s timeout to the check, and a setting for this timeout so that users in laggy environments can easily increase it if needed.
1. Checked if normal cluster creation with S3 etcd backups works: created cluster, created a snapshot, and checked if the snapshot appears in the S3 web …

Add timeout when checking if a S3 bucket exists

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

https://github.com/rancher/rancher/issues/48570 
cherry-pick  of https://github.com/rancher/rancher/pull/48633 
Please check the original PR for more information 
--------------
Notes: **the CI failure is not related to the changes in the PR**.

[2.10] Fix the image registries for the system-upgrade-controller chart in imported clusters

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

https://github.com/rancher/rancher/issues/48564 
Since Rancher 2.10, the `system-upgrade-controller` chart is installed into the imported cluster via the systemcharts mechanism.
The `system-upgrade-controller` chart uses two images, which are defined in the values file with the following structure:
```yaml
systemUpgradeController:
image:
repository: rancher/system-upgrade-controller
tag: v0.14.2
kubectl:
image:
repository: rancher/kubectl
tag: v1.31.1
```
Rancher expects the `image` field to be at the top level so that it can append the system registry to the image name correctly:
```yaml
image:
repository: registry.rancher.com/rancher/system-upgrade-controller
```
Because the structure of the values in this chart differs from the expected format, the private registry is not properly …

[main] Fix the image registries for the system-upgrade-controller chart in imported clusters

---

tests/scripts/custodian/Dockerfile
tests/scripts/custodian/Jenkinsfile

https://github.com/rancher/qa-tasks/issues/1634
aws custodian was giving errors when ran on jenkins, but not locally.
since jenkins runs on aws nodes, the region the node was in affects which regions custodian could be checked against. Hard coding custodian to use the vpn'd node.
also updated the dockerfile to use 24.04

[main] run custodian on vpn'd node to avoid aws region errors

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Issue: https://github.com/rancher/rancher/issues/48425
This reduces the "unknown resource" message to a Debug which will prevent unexpected resources (that we skip) from being logged out.

Improve Azure Client logging for group resources

---

tests/scripts/custodian/aws.yaml
tests/scripts/custodian/azure.yaml

noticed some inconsistencies / better logic for these after seeing it run on prod. 
* azure won't let you tag an instance to delete if its in a failed state
* aws job is tagging instances that have already been matched before

improving logic for qa custodian

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/providers/ldap/ldap_client.go
pkg/auth/providers/ldap/ldap_client_test.go
pkg/client/generated/management/v3/zz_generated_free_ipa_config.go
pkg/client/generated/management/v3/zz_generated_ldap_config.go
pkg/client/generated/management/v3/zz_generated_ldap_fields.go
pkg/client/generated/management/v3/zz_generated_open_ldap_config.go

Originally:  https://github.com/rancher/rancher/pull/46357
Users on certain LDAP setups do not have the permissions to search as their user. This lead to the error outlined in the issue (Result code 32), since Rancher attempted to bind as their user to perform searches (in order to show the user only the groups/users that they could see as part of their auth configs).
The solution is to expose a field on the auth config (search_using_service_account, a bool) which will cause Rancher to always use the service account (and never the user) to search for users/groups. This value will default to false, to keep Rancher's current behavior for our existing consumers.
* None
* If "None" - Reason: Lack of the framework capable of testing this fix/change
Summary: No …

[main/2.11] Add auth config field that allows Rancher to use the service account to search for users

---

pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go
pkg/controllers/managementuser/rbac/globalrolebinding_handler.go
pkg/controllers/managementuser/rbac/globalrolebinding_handler_test.go
pkg/rbac/common.go
pkg/rbac/common_test.go

We only create resources in the downstream clusters for admin `GlobalRoles`. The GRB status includes `observedGenerationRemote`, `summaryRemote` for non-admin `GlobalRoles` which are intended only for admin GlobalRoles.
Don't display `observedGenerationRemote`, `summaryRemote` for non-admin `GlobalRoles` 
Unit tests

Don't display SummaryRemote in Status if the GlobalRole is not admin

---

pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/status/status.go
pkg/controllers/status/status_test.go

The `lastTransitionTime` for conditions are being updated even though its status hasn't changed.
Dont update `lastTransitionTime` if the condition hasn't changed
Unit tests added

Don't update LastTransitionTime for a condition that hasn't changed

---

pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

If a node is drained via UI and then uncordoned via kubectl uncordon <node> UI continues to display it as State = Drained.
Check if the underlying node is schedulable; if it is, then remove the Drained condition from the machine's status conditions.
Repro steps in the GitHub issue are valid.
After applying the fix, I followed the repro steps from the issue, and the problem did not reproduce.
* Unit
* None
_TODO_
Existing / newly added automated tests that provide evidence there …

fix: remove Drained condition from machine status if schedulable

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml
go.mod
go.sum
main.go
pkg/ext/certs.go
pkg/ext/extension_apiserver.go
pkg/rancher/rancher.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/47035
Needed feature flag for extension server as well as integrating new authentication features from the steve extension server.
Added new setting and cli to allow toggling extension server. When enabled, create new `APIService` and `Service` to route traffic requesting resources from `ext.cattle.io`. Generated new SNI certs for apiservice `caBundle` to authenticate requests coming from the kube apiserver.
1. build charts with `scripts/chart/build chart`
2. Add a test type including a sample store (see https://github.com/joshmeranda/rancher-rancher/blob/imperative-api-setting/pkg/apis/ext.cattle.io/v1/types.go and https://github.com/joshmeranda/rancher-rancher/blob/imperative-api-setting/pkg/ext/stores/install.go for details)
3. Install rancher …

[main] Imperative api setting

---

package/Dockerfile.agent

It looks like the env var `AGENT_IMAGE` in the agent image is not set correctly in `head` and `v2.10.2`, `v2.10.1` and `v2.10.0`. Also, some labels are set wrong because they also depend on `${VERSION}`.
This is because we're missing the `ARG VERSION=${VERSION}` line in the final image.
So we get the following:
```
$ docker run -it --entrypoint sh rancher/rancher-agent:v2
.10.0
sh-4.4# env | grep AGENT_IMAGE
AGENT_IMAGE=rancher/rancher-agent:
$ docker inspect rancher/rancher-agent:v2.10.0 | jq '.[].Config.Labels."org.opensuse.reference"' -r
rancher/rancher-agent:
``` 
Here's what it's supposed to look like:
```
$ docker run -it --entrypoint sh registry.suse.com/ranche
r/rancher-agent:v2.9.6
sh-4.4# env | grep AGENT_IMAGE
AGENT_IMAGE=rancher/rancher-agent:v2.9.6
$ docker run -it …
```

Fix AGENT_IMAGE var and labels not set correctly

---

package/Dockerfile.agent

Backport of https://github.com/rancher/rancher/pull/48940
It looks like the env var `AGENT_IMAGE` in the agent image is not set correctly in `head` and `v2.10.2`, `v2.10.1` and `v2.10.0`. Also, some labels are set wrong because they also depend on `${VERSION}`.
This is because we're missing the `ARG VERSION=${VERSION}` line in the final image.
So we get the following:
```
$ docker run -it --entrypoint sh rancher/rancher-agent:v2
.10.0
sh-4.4# env | grep AGENT_IMAGE
AGENT_IMAGE=rancher/rancher-agent:
$ docker inspect rancher/rancher-agent:v2.10.0 | jq '.[].Config.Labels."org.opensuse.reference"' -r
rancher/rancher-agent:
``` 
Here's what it's supposed to look like:
```
$ docker run -it --entrypoint sh registry.suse.com/ranche
r/rancher-agent:v2.9.6
sh-4.4# env | grep AGENT_IMAGE …
```

[v2.10] Fix AGENT_IMAGE var and labels not set correctly

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go
tests/v2/actions/provisioning/verify.go
tests/v2/validation/certrotation/cert_rotation.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

There have been reports of flaky release testing automation in the following areas:
- RKE1 cert-rotation
- RKE2/K3S S3 snapshots
Outside of that, there are some general QOL updates that need to be made, such as deprecating certain tests and enhancing the default Kubernetes versions that are selected.
Addressed the issues noted above.
Manually tested the above scenarios.

[Main] Fix flaky release testing automation and QOL updates

---

pkg/auth/providers/saml/saml_client.go
pkg/auth/providers/saml/saml_handlers.go

Large rancher log chatter around the SAML login/logout flow, useful only for internal debugging.
Remove the most expensive/large  element from the logs.
* Unit
* None
_TODO_
* _TODO_

reduce saml log chatter

---

pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Cluster with Windows nodes stuck in "Upgrading" state for imported rke2 cluster.
When determining whether a cluster K8s version upgrade is needed, skip any Windows nodes and skip Windows nodes if the upgrade was kicked off.
https://github.com/rancher/rancher/issues/48134#issuecomment-2597336099
- Import a rke2 cluster with windows node
- Upgrade the cluster
- Check if windows node was upgraded or not

fix: exclude Windows nodes from the upgrade process in imported clusters

---

tests/v2/actions/workloads/cronjob/cronjob.go
tests/v2/actions/workloads/cronjob/verify.go
tests/v2/actions/workloads/daemonset/verify.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/deployment/verify.go
tests/v2/actions/workloads/statefulset/statefulset.go
tests/v2/actions/workloads/statefulset/verify.go

Issue: dockerhub throttles pulls, this causes the workload tests to fail if several clusters are running them sequentially.
Solution: change the image to point at the public aws ecr registry.
Note: Also added some updates to the logs so they don't spam as much when running the workload tests on several clusters

Workload test fixes and QOL

---

pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Original/Merged PR: https://github.com/rancher/rancher/pull/48879

[v2.9.7] Backport: exclude Windows nodes from the upgrade process in imported clusters

---

pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Original/Merged PR: https://github.com/rancher/rancher/pull/48879

[v2.10.3] Backport: exclude Windows nodes from the upgrade process in imported clusters

---

tests/v2/validation/Dockerfile.validation

Currently automation jobs running against the main branch are failing due to openssh not being installed in the container as well as using `apt-get` instead of `zypper`.
This PR adds a line to the Dockerfile to install openssh as well as updates the use of `apt-get` to `zypper`

[main] Add line to install openssh to Dockerfile

---

pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/cluster/controller_test.go

UI requires a field or annotation on the provisioning cluster object that has the user entered cluster name. For more details, see: https://github.com/rancher/rancher/issues/48509

Store user-provided cluster name on clusters.provisioning.cattle.io/v1

---

pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/cluster/controller_test.go

Imported clusters should not override fields on the management cluster based on the provisioning cluster. Instead, the management cluster should remain the source of truth. With v2.11, the UI will send all requests for imported clusters to `clusters.management.cattle.io` (https://github.com/rancher/dashboard/issues/13151) but this fix is required so updates to the management cluster aren't lost for clusters created prior to v2.11. 
Rancher webhook will be updated to return an error on update calls to provisioning clusters, making the change in behavior explicit.
https://github.com/rancher/rancher/issues/48700
https://github.com/rancher/rancher/issues/47593 
When importing a cluster, the UI sends a POST request to `v1/provisioning.cattle.io.clusters`, creating a v1 object. Rancher then …

Use management cluster reference for imported clusters

---

pkg/controllers/capr/machineprovision/controller.go
pkg/controllers/provisioningv2/controllers.go
pkg/controllers/provisioningv2/harvestercleanup/controller.go

Signed-off-by: Volker Theile <vtheile@suse.com>
https://github.com/harvester/harvester/issues/2825
If a guest cluster is deleted, the [PVCs of the workloads are not deleted](https://github.com/harvester/docker-machine-driver-harvester/blob/03e510a33007aeb9ab9fbd63b85f7a4d6acc4488/harvester/harvester.go#L183) in Harvester. This is because the Harvester node driver does not know why the associated VM has to be deleted, e.g. because its parameters have changed or because the guest cluster is deleted.
To solve the problem, a `OnChange` handler on `harvestermachines.rke-machine.cattle.io` will be implemented that checks whether the deletion timestamp is set for the associated cluster when the machine resource is deleted. If this is the case, an annotation is set on the VM in the downstream …

Set annotation to guest cluster VM when deleting the cluster

---

pkg/auth/providers/ldap/ldap_provider.go
pkg/auth/providers/ldap/ldap_provider_test.go

If the `openLdapConfig` of a SAML auth provider (ie shibboleth or okta) is set to `nil` (or `null` in the UI) Rancher panics.
Return a `ErrorNotConfigured` when the `openLdapConfig` is set to `nil`
Manually tested by setting the `openLdapConfig` to `null` in the UI for an Okta provider.
* Unit
Summary: Added a unit test for this and for a couple other code paths as well.
_TODO_
* _TODO_

Add handling for nil openLdapConfigs

---

tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go

Go build tags were missing from the tests as a result these tests are failing in the recurring runs. 
Added go build tags and added `stress` tag for this to be a bi-weekly run.

Updating tags for the cluster templates provisioning tests

---

chart/Chart.yaml

One `sources` link links to an outdated repo.
Remove link to archived repo as the chart is managed in this repo.
None

Fix links in Chart.yaml

---

pkg/controllers/managementuser/networkpolicy/netpol.go

```
github.com/rancher/rancher/pkg/controllers/managementuser/networkpolicy.(*netpolMgr).handleHostNetwork(0xc00509c6e0, {0xc0052f2aa0, 0x7}) /app/pkg/controllers/managementuser/networkpolicy/netpol.go:189 +0xee5
```
The panic is caused by [this line](https://github.com/rancher/rancher/blob/v2.9.0/pkg/controllers/managementuser/networkpolicy/netpol.go#L189) where it doesn't confirm the nodes list is not empty before accessing to node[0].
Added a condition to ensure `nodes` is not empty before calling `getClusterCNI`, preventing potential index out-of-range errors.

fix: add check for empty nodes before calling getClusterCNI on nodes[0]

---

docs/development.md

The commands specified in the Developing Rancher section of [developing.md](https://github.com/rancher/rancher/blob/main/docs/development.md), value of `TAG` is expected to be `tag` of the image, and `REPO` should be as the required repository.
Set the repository value to `REPO` variable and just the tag value to `TAG`.
* None
* If "None" - Reason:  
- No application logic is modified by this change - doc change

Adds the missing REPO parameter

---

build.yaml
pkg/buildconfig/constants.go

Per title this bumps Rancher Shell to use the new branch (and RC) targeting Rancher 2.11.
This includes the updated helm and updated kubectl versions for the +-1 versions of k8s Rancher 2.11 will support.

Bump Rancher Shell for 2.11

---

build.yaml
pkg/buildconfig/constants.go

Per title this bumps Rancher Shell to use the new branch (and RC) targeting Rancher 2.10.

Bump Rancher Shell for 2.8

---

tests/scripts/custodian/aws.yaml

noticed that LBs weren't being cleaned up by the custodian as often as they should. Turns out the ARN lookup doesn't like keys with `|`
lookup by name instead fixes the issue.

fix lookup of LB when using OR'd values

---

tests/scripts/custodian/gcp.yaml

noticed an issue with gcp in custodian: 
```
Label value 'setForDeletion' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes.
```

adjust labels for gcp custodian

---

tests/v2/validation/kdm/kdm_test.go

There's a test, `kdm_test.go`, that checks if all replicas get updated kdm data after a change the kdm url change. Change the comments to make it clear this is the intention, and avoid confusion when updating KDM release branches before and after releases (this test shouldn't be updated).

Make comment in kdm_test.go more clear

---

go.mod
hack/airgap/go.mod
package/windows/Dockerfile.agent
pkg/apis/go.mod
pkg/client/go.mod
tests/v2/validation/steve/vai/scripts/script.sh

The new BCI golang stable image registry.suse.com/bci/golang:1.23 is now available.
```sh
docker pull registry.suse.com/bci/golang:1.23
docker inspect registry.suse.com/bci/golang:1.23 | grep GOLANG_VERSION
"GOLANG_VERSION=1.23.6",
```
Match the Go toolchain to the one in the new bci/golang:1.23 image.
N/A
N/A

Bump Go toolchain to 1.23.6

---

scripts/provisioning-tests

KDM tests are failing on the provisioning-tests side due to some mis-handlings:
- we don't properly set `TAG` in the workflow env
- `docker create rancher/rancher:$TAG` will fail and exit the script if it doesnt exist
so by defaulting the tag to head instead of dev (from scripts/version) it fixes the first issue, and using `docker image inspect` instead of `docker create` and checking if the string is non-existent.

Few fixes on scripts/provisioning-tests for KDM to function

---

pkg/ext/extension_apiserver.go
pkg/features/feature.go
pkg/settings/setting.go

https://github.com/rancher/rancher/issues/47035 
Currently the imperative API only checks an envvar to determine if the imperative api should be enabled. This does not allow users to enable or disable it via UI. Due to the current setting, rancher server, and steve initialization workflow it does not make sense to support toggling the imperative api at runtime. Since rancher setting do not easily support restart rancher on change, we need a feature to support the desired functionality. 
* Unit
* None
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD …

[main] Imperative api feature

---

pkg/ext/certs.go
pkg/ext/certs_test.go
pkg/ext/extension_apiserver.go

https://github.com/rancher/rancher/issues/48915
The certs currently generated for the imperative api `APIService` will expire in ~1 year and will not be replaced. We should have control over how long the certs are valid for, and be able to replace them before they expire to ensure minimal downtime fro the imperative api.
Store the certs in a `Secret` and monitor the `Secret` for expiring certs and update the underlying extension api cert provider whenever the cert is changed.
Installed rancher with the imperative api enabled and modified expiration times. Let it run until the cert expires and a new one replaces it and update the associated `Secret` and `APIService`
* Unit …

[main] Imperative api rotating certs

---

pkg/rancher/migrations.go
pkg/rancher/migrations_test.go
pkg/rancher/rancher.go

Performing a Rancher downgrade can currently cause issues due to migrations running at startup being version specific. Currently, when a downgrade of Rancher is performed, the backup restore operator must be used.
Add the Rancher version as a tombstone, preventing Rancher from starting if a downgrade is detected.
- Build an image of Rancher including this change with a semver compliant tag and run it
- Confirm value is written to `rancherVersionTombstone` config map
- Build another image of Rancher with a higher tag and upgrade
- Confirm upgrade success new value is written to `rancherVersionTombstone` config map
- Downgrade to original version
- Confirm Rancher exits with clear error message
- Remove `rancherVersionTombstone` config map and confirm Rancher starts
* Test …

[41179] Add version tombstone to migrations

---

build.yaml
pkg/buildconfig/constants.go

Per title, this un-RCs shell after [QA verification](https://github.com/rancher/shell/issues/316).
~Shell image is still building here: https://github.com/rancher/shell/actions/runs/13528419295/job/37804635595~

[v2.8] Unrc the Shell image version

---

pkg/controllers/management/feature/feature_handler.go
pkg/controllers/management/wrangler.go
pkg/data/management/machinedriver_data.go
tests/controllers/feature/feature_test.go

Fix Harvester feature flag enabling/disabling the Harvester node driver. When the Harvester feaature flag is disabled, the Harvester node driver needs to be disabled to, e.g. to prevent trying do download the node driver in an airgapped environment.
When the Harvester feature flag is enabled, the node driver must be enabled too. Should the node driver have been deleted, it must be re-created when the Feature flag is enabled.
related-to: rancher/rancher#48920
GitHub Issue: rancher/rancher#48920
Jira: SURE-9678
User reported that in an airgapped environment Rancher tries to download the Harvester node driver from the public internet, despite the Harvester feature being disabled.
The download fails of course, but is retried indefintively.
Set the `.spec.active` field of the …

Fix: Harvester Feature Flag

---

pkg/apis/management.cattle.io/v3/cluster_types.go

https://github.com/rancher/dashboard/issues/13063 
UI is blocked because API currently doesn't allow creates or updates on `ImportedConfig`, this is an issue for private registry url for imported clusters. This works correctly with `kubectl`.

Allow imported config to be created and updated

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

Not a strict revert, since I kept the comment changes in `kdm_test.go` that were added in the PR that updated the references to release.

[2.10] Change KDM back to dev

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

Not a strict revert, since I kept the comment changes in `kdm_test.go` that were added in the PR that updated the references to release.

[2.9] Change KDM back to dev

---

pkg/ext/rdp.go

RDPClient is trying to connect to RDP in downstream cluster. RDP will not be deployed to downstream what makes RDPClient to keep trying and printing messages forever. 
Deactivate RDPClient when rancher is deployed in downstream cluster
* Unit
* None
_TODO_
* _TODO_

#49286 - Deactivate RDPClient if it's in downstream cluster

---

pkg/controllers/management/feature/feature_handler.go

Fix Harvester baremetal container workload feature flag. The Harvester baremetal container workload feature flag depends on the Harvester feature flag. This fix disables the Harvester baremetal container workload feature flag when the Harvester feature flag is disabled.
related-to: rancher/rancher#48922
GitHub Issue: rancher/rancher#48922
The dependency of the Harvester baremetal container workload feature on the Harvester feature is insufficiently modeled in the code base. As a result it's possible for a user to end up with the Harvester baremetal container workload feature enabled, but with the Harvester feature disabled.
When the Harvester feature is disabled, automatically also disable the Harevester baremetal container workload feature.
* Unit
* …

Fix Harvester Baremetal Container Feature Flag

---

pkg/systemtemplate/template.go

Two if statements in the cluster agent manifest template did not include `-`, resulting in unintended white space in the resulting yaml. After testing the feature using the latest alpha, I'm able to confirm that this does not have a functional impact on the linked issue, but should be addressed to generate clean yaml.
Update the if statements to prevent unintentional whitespace. 
I provisioned an rke2 cluster with this change and confirmed that the agent manifest placed on disk no longer has an unintended newline. I confirmed that the agent deploys properly with the expected fields.
I've done the above
* Unit
* None
* _REMOVE NOT APPLICABLE …

[main] Remove whitespace when generating agent yaml

---

pkg/capr/planner/certificaterotation.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/planner.go
pkg/capr/planner/windows.go

When rotating cluster certificates via the Rancher UI, clusters with Windows nodes will report an error. This is due to the fact that certificate rotation commands are wrapped in a bash script that is intended to ensure that the commands are idempotent. Windows is not able to run bash scripts natively.  
Implement a Windows specific idempotent script that mirrors the linux idempotent script and use it to run the necessary commands to restart the rke2 service. 
+ Create a custom Windows cluster in Rancher
+ A vSphere node driver provisioned cluster will also work
+ Once provisioned, click the three dots next to the 'Explore' button, and select 'Rotate Certificates'
+ Wait for the operation to complete and ensure that no error is reported in the Rancher UI
To further confirm that this is …

[main] Fix certificate rotation for Windows clusters

---

go.mod
go.sum

Related to #49288
This change indexes `metadata.annotations[provisioning.cattle.io/management-cluster-display-name]` in `provisioning.cattle.io/clusters`

Bump steve to v0.5.10 to fix issue 49288

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring
tests/v2/validation/pipeline/Jenkinsfile.recurring

After the rancher's default branch to main update, multiple SCM init checkout failures were observed in the recurring runs. This is due to using multiple remotes in the defaults.
Update remote repositories as hardcoded parameters, and update default branches in the recurring runs related Jenkinsfiles
Will be provided offline

[main] Update Checkout Repos and Branches in Recurring Runs

---

pkg/capr/common.go
pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go

https://github.com/rancher/rancher/issues/49230
There is a situation where the K3s/RKE2 etcd snapshot configmap can have node names that do not comply with RFC-1123. This causes snapshot data to never be correlated, which can lead to a bad user experience.
Transform the node name to all lowercase.
* Unit
* None
_TODO_
* _TODO_

[release/v2.10] Transform node names to lowercase to handle potentially incorrect data in K3s/RKE2 configmap

---

pkg/capr/planner/certificaterotation.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/planentry.go
pkg/capr/planner/planner.go
pkg/capr/planner/windows.go

This is a backport of https://github.com/rancher/rancher/pull/49071 for 2.9. The only additional logic is the addition of the `isOnlyWindowsWorker` function.

[2.9] Deliver windows specific idempotent script

---

pkg/cluster/agent_customization.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/kubectl/kubectl.go

When enabling scheduling customization on imported clusters, the cluster agent deployment eventually has its `priorityClassName` field removed. This is due to the `clusterDeploy` controller only setting the PC reference on the manifest during updates to the PC definition. In the event that the cluster agent is changed outside of the PC definition, the reference is lost. This can happen due to the agent environment variables being changed, or agent features being automatically adjusted by the Rancher server. Additionally, as the `clusterDeploy` controller only compares the status and spec to determine if the PC has been created, it is possible that the cluster agent may fail to redeploy if the PC is deleted from the downstream cluster
If the agent manifest needs to be reapplied due to a …

[main] Ensure downstream PC exists

---

dev-scripts/quick

channelserver breaks if dev builds don't have `-head` or `-main`:
https://github.com/rancher/rancher/blob/main/pkg/settings/setting.go#L564-L573
https://github.com/rancher/rancher/blob/main/pkg/channelserver/channelserver.go#L46-L51

Add -head suffix to make quick tag

---

pkg/capr/common.go
pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go

https://github.com/rancher/rancher/issues/49238
https://github.com/rancher/rancher/issues/49230
There is a situation where the K3s/RKE2 etcd snapshot configmap can have node names that do not comply with RFC-1123. This causes snapshot data to never be correlated, which can lead to a bad user experience.
Transform the node name to all lowercase.
* Unit
* None
_TODO_
* _TODO_

[release/v2.9] Transform node names to lowercase to handle potentially incorrect data in K3s/RKE2 configmap

---

pkg/controllers/managementuser/networkpolicy/netpol.go

Original/Merged PR: https://github.com/rancher/rancher/pull/49072

[v2.9] Backport fix: add check for empty nodes before calling getClusterCNI on nodes[0]

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/rancher/issues/48824
csp-adapter version needs to be updated to one that supports K8s 1.30-1.32 in line with Rancher 2.11
Update csp-adapter version to 106.0.0+up6.0.0-rc1
automated testing performed of the changes using the csp-adapter-rancher-e2e-automation script (internal)

[v2.11] Csp-adapter v6.0.0, bump k8s version support

---

chart/templates/deployment.yaml

The `hostPort` defined for imperative API is triggering an issue related to CA cert selection (see linked issue for more detail).
The easiest fix for this is to simply remove that `hostPort` because we don't need it, we just need the pod to be reachable by a Service.
Deployed Rancher with this chart changed and the APIService for ext.catte.io's status is ok so no regression there.

Remove hostPort for imperative API

---

pkg/controllers/dashboard/helm/repo_oci.go
pkg/controllers/dashboard/helm/repo_oci_test.go
pkg/controllers/dashboard/plugin/controller.go
pkg/controllers/dashboard/plugin/controller_test.go

Issue https://github.com/rancher/rancher/issues/49047
Summary
This issue was reopened because now, we are able to reproduce it clearly.

[release/v2.10] Make sure to limit variables in calculateBackOff func 

---

pkg/settings/setting.go

Similar to https://github.com/rancher/rancher/pull/39058, we need to update the ui and dashboard index settings now that 2.11 builds are available.

update ui-dashboard-index and ui-index settings to use 2.11 dashboard and ui builds

---

.github/workflows/integration-tests.yml
.github/workflows/provisioning-tests.yml

Removing spot instances so CI won't get cancelled

Remove spot instances from provisioning and integration tests

---

pkg/apis/ext.cattle.io/v1/types.go
pkg/apis/ext.cattle.io/v1/zz_generated_deepcopy.go
pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/accessor/accessor.go
pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/ext/stores/useractivity/store.go
pkg/ext/stores/useractivity/store_test.go
pkg/generated/openapi/zz_generated_openapi.go

Support ext tokens in user activities.
The new user activities currently support only v3 tokens.
The stores for user activities and ext tokens were extended so that UA is able to work with ext tokens.
Passes unit tests.
* Unit
* None
_TODO_
* _TODO_

Link Ext Tokens and Useractivities

---

.github/workflows/integration-tests.yml
.github/workflows/provisioning-tests.yml

Backport of https://github.com/rancher/rancher/pull/49441

[2.11] Remove spot instances from provisioning and integration tests

---

.github/workflows/integration-tests.yml
.github/workflows/provisioning-tests.yml

Backport of https://github.com/rancher/rancher/pull/49441

[2.10] Remove spot instances from provisioning and integration tests

---

.github/workflows/integration-tests.yml
.github/workflows/provisioning-tests.yml

Backport of https://github.com/rancher/rancher/pull/49441

[2.9] Remove spot instances from provisioning and integration tests

---

build.yaml
pkg/buildconfig/constants.go

This PR un-rc's csp-adapter v6.0.0.
On an EKS cluster, install locally built rancher with cspAdapterMinVersion: 106.0.0+up6.0.0

[v2.11] Csp-adapter v6.0.0 un-rc

---

pkg/apis/management.cattle.io/v3/global_types.go
pkg/apis/management.cattle.io/v3/global_types_test.go
pkg/controllers/management/feature/feature_handler.go
pkg/features/migrate.go

Invalid memory access when syncronizing the Harvester feature flag and the Harvester Baremetal Container Workload feature flag.
This is a backport of an existing fix.
See also https://github.com/rancher/rancher/pull/49340
See also https://github.com/rancher/rancher/pull/49340
* Unit
* None
_TODO_
* _TODO_

[Backport v2.11] Fix invalid memory access

---

pkg/apis/management.cattle.io/v3/global_types.go
pkg/apis/management.cattle.io/v3/global_types_test.go
pkg/controllers/management/feature/feature_handler.go
pkg/features/migrate.go

Fix invalied memory access when syncronizing the Harvester feature flag and the Harvester Baremetal Container Workloads feature flag.
The update of the Harvester Baremetal Container Workload feature flag contained an invalid memory access at the point where the new value of that feature flag is set.
The problem was that a feature flag's value is a pointer to a boolean that may be nil. The nil check was only performed for the Harvester feature flag, but not for the Harvester Baremetal Container Workload Feature flag. As a result, when syncronizing the two feature flags, depending on whether the Harvester Baremetal Container Workload feature flag had been set before or not, there could be an assignment to the memory address pointed to by a nil pointer - which is invalid.
In case the …

Fix invalid memory access

---

pkg/controllers/management/auth/roletemplates/roletemplate_handler.go
pkg/controllers/management/auth/roletemplates/roletemplate_handler_test.go
pkg/controllers/managementuser/rbac/roletemplates/roletemplate_handler.go
pkg/controllers/managementuser/rbac/roletemplates/roletemplate_handler_test.go

https://github.com/rancher/rancher/issues/49231
https://github.com/rancher/rancher/issues/49224
When a RoleTemplate inherits another RoleTemplate with management plane rules, it doesn't create an aggregation cluster role for those management plane rules. That means any user bound to the parent RoleTemplate doesn't inherit all the rules properly.
For promoted rules in the downstream cluster, I had originally designed it so that an aggregating cluster role would be created if the roletemplate inherited any other roletemplates. Instead of doing that for management plane resources, I instead look at each inherited role template for any management plane resources. I also modified promoted rules to work the same way.
The repro steps in both issues are accurate
I tested by performing the tests …

Only create management plane and promoted cluster roles when they exist

---

build.yaml
go.mod
go.sum
pkg/buildconfig/constants.go

* [release/v0.7] bump dynamiclistever version by @joshmeranda in https://github.com/rancher/webhook/pull/845
* @joshmeranda made their first contribution in https://github.com/rancher/webhook/pull/845
**Full Changelog**: https://github.com/rancher/webhook/compare/v0.7.0-rc.10...v0.7.0-rc.11
- Commit comparison: https://github.com/rancher/webhook/compare/v0.7.0-rc.10...v0.7.0-rc.11
- Release v0.7.0-rc.10: https://github.com/rancher/webhook/releases/tag/v0.7.0-rc.10
The workflow was triggered by joshmeranda.

[release/v2.11] Bump rancher-webhook to v0.7.0-rc.11

---

pkg/data/management/machinedriver_data.go

Prevent nodes from being activate/deactivated with the exception of the Harvester node driver, which has an activation status tied to the feature flag.
Tested manually, and with Harvester feature flag to ensure behavior is as intended.

[2.11] Prevent node drivers from defaulting to default activation status on startup

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This PR bumps wins from `v0.5.0-rc.2` to the release `v0.5.0`. `v0.5.0` was already released with rancher `v2.10.2`, and uses the same commit as `v0.5.0-rc.2`.

[v2.11] Bump `rancher-wins` to `v0.5.0`

---

package/Dockerfile
package/Dockerfile.agent
package/entrypoint.sh

Decrease the generated `rancher/rancher` image size from `2.3 GB` to `1.6GB`.
The commits should be self-explanatory, but from a high-level:
- Rancher binary debug symbols were removed  (13MB saving).
- The git worktrees for all cloned repositories are being lazy-loaded (~600MB saving).
- The image now only has the dotgit store data, and creates each worktree on first load.
**Latest from `main`**
**Latest from `main` + these changes**
Follow-up from https://github.com/rancher/rancher/pull/45802.

Decrease `rancher/rancher` image size from `2.3 GB` to `1.6GB`

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This PR bumps wins from `v0.5.0-rc.2` to the release `v0.5.0`. `v0.5.0` was already released with rancher `v2.10.2`, and uses the same commit as `v0.5.0-rc.2`.

[main] Bump `rancher-wins` to `v0.5.0`

---

pkg/controllers/dashboard/fleetcharts/controller.go
pkg/controllers/dashboard/fleetcharts/controller_test.go

The `gitjob` chart is no longer used.
Refers to: https://github.com/rancher/fleet/issues/2987

Delete Fleet gitjob chart values

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This PR bumps `rancher-wins` to `v0.5.1-rc.1` in order to pick up dependency bumps

[2.11] Bump rancher-wins to `v0.5.1-rc.1`

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This PR bumps `rancher-wins` to `v0.5.1-rc.1` in order to pick up dependency bumps

[main] Bump rancher-wins to `v0.5.1-rc.1`

---

pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/ext/stores/tokens/zz_token_fakes.go

See #49588 
The kube controller manager responsible for resource GC attempts to list ext tokens using a SA which is not recognized as admin. This subsequently causes an error listing the secrets, as the SA name is not a proper label selector. This failure to list then in turn breaks the GC code.
The GC SA is detected by (hardwired) name, and then treated as having admin permissions, to list all tokens.
* Unit
* None
_TODO_
Existing / newly added automated tests that provide …

fix garbage collection broken by ext tokens?

---

pkg/ext/certs.go
pkg/ext/extension_apiserver.go

The offending code was introduced in v2.11.0 as part of https://github.com/rancher/rancher/pull/48956.
The for/select loop that reacts to either watch events, canceling and a timer. However, the watch event case does not handle [`Error` events](https://pkg.go.dev/k8s.io/apimachinery/pkg/watch#Interface), which are a signal from the producer aborting the request (normally followed by the channel being closed). Then reading from that closed channel makes the for/select loop to iterate very quickly, while still creating a new `time.After` (and the corresponding inner `Timer`) on every iteration, hence causing high CPU, both due to the rapidly executing loop and GC operations due to the amount of object allocations.
Reading from the watcher's `ResultChan` now detects if the channel is …

[v2.11] Avoid infinite loop on Ext. API cert rotation on watcher error

---

pkg/api/steve/proxy/proxy.go

A new `http.Transport` is created from scratch for every new `rest.Config` (every request to the Steve aggregation API running downstream). However, this `http.Transport` does not include sane defaults, as opposed to `http.DefaultTransport`, especially `IdleConnTimeout` is not set. This, combined with the use of a `remotedialer` connection, makes connections to stay idle and never closed, causing the problem described in the parent issue. 
We could just set `IdleConnTimeout` to a non-zero value, making the client close the connections after the specified time. However, it's just cleaner to get a copy of the `DefaultTransport` and then apply any required customizations (the dialer in this case).
(An alternative fix in steve was created [here](https://github.com/rancher/steve/pull/576), but …

Use default transport as a base for k8s client in steve aggregation

---

pkg/catalogv2/system/system.go
pkg/catalogv2/system/system_test.go

This is part of that issue and is necessary along with https://github.com/rancher/charts-build-scripts/pull/202 to correctly support multiple RCs in rancher/charts. This will prevent breaking the CI whenever we bump webhook for example (or worse when both webhook and fleet are bumped at the same time).
The thing that deploys charts treats a version `106.0.0+up0.7.0-rc.10` as equal to `106.0.0+up0.7.0-rc.11`. So even if we pin the webhook (most commonly during development) to a newer version (say `106.0.0+up0.7.0-rc.10`) but the older version is running, the charts deployer will NOT deploy the newer version and it'll keep running the old one. (**Note:** this is only a problem in development, not for released Rancher. For released Rancher, we only release unRCd version which a new patch …

Distinguish between semver metadata for exact-versioned charts

---

pkg/api/steve/proxy/proxy.go

[v2.11] Use default transport as a base for k8s client in steve aggregation

---

pkg/api/steve/proxy/proxy.go

[v2.10] Use default transport as a base for k8s client in steve aggregation

---

pkg/controllers/managementuser/resourcequota/resource_quota_sync.go
pkg/controllers/managementuser/resourcequota/resource_quota_sync_test.go

The user wasn't able to set Limits or Requests for namespace when it wasn't previously defined in project. 
We changed the logic to the user be able to set the values in namespace and when some value is missing, we copy it from project, this way project values work like default values.
The repro steps are in the original issue. For the testing, I suggest you to create a new project in the UI and then set some values for Limits or Requests. Then after, create a namespace in that project and add other values. The values you add in namespace will be the ones set, but in case you don't set one or more of them, it will copy it from project if you previously defined it in there.

#45641 - Adjusted Resource Limit Logic

---

pkg/api/norman/customization/cluster/validator.go

- Eliminate the requirement for at least one nodegroup in the EKS cluster validation process.
- Remove Norman API validation related to managed node groups.
- https://github.com/rancher/rancher/issues/45972

[main] remove validation for empty nodegroups in EKS cluster

---

pkg/api/norman/customization/cluster/validator.go

Eliminate the requirement for at least one nodegroup in the EKS cluster validation process.
https://github.com/rancher/rancher/issues/49723

[v2.10] remove validation for empty nodegroups in EKS cluster

---

pkg/catalogv2/system/system.go
pkg/catalogv2/system/system_test.go

**Backport**
Backport of https://github.com/rancher/rancher/pull/49717
---
This is part of that issue and is necessary along with https://github.com/rancher/charts-build-scripts/pull/202 to correctly support multiple RCs in rancher/charts. This will prevent breaking the CI whenever we bump webhook for example (or worse when both webhook and fleet are bumped at the same time).
The thing that deploys charts treats a version `106.0.0+up0.7.0-rc.10` as equal to `106.0.0+up0.7.0-rc.11`. So even if we pin the webhook (most commonly during development) to a newer version (say `106.0.0+up0.7.0-rc.10`) but the older version is running, the charts deployer will NOT deploy the newer version and it'll keep running the old one. (**Note:** this is only a problem in development, not for released …

[release/v2.11] Distinguish between semver metadata for exact-versioned charts

---

pkg/catalogv2/system/system.go
pkg/catalogv2/system/system_test.go

**Backport**
Backport of https://github.com/rancher/rancher/pull/49717
---
This is part of that issue and is necessary along with https://github.com/rancher/charts-build-scripts/pull/202 to correctly support multiple RCs in rancher/charts. This will prevent breaking the CI whenever we bump webhook for example (or worse when both webhook and fleet are bumped at the same time).
The thing that deploys charts treats a version `106.0.0+up0.7.0-rc.10` as equal to `106.0.0+up0.7.0-rc.11`. So even if we pin the webhook (most commonly during development) to a newer version (say `106.0.0+up0.7.0-rc.10`) but the older version is running, the charts deployer will NOT deploy the newer version and it'll keep running the old one. (**Note:** this is only a problem in development, not for released …

[release/v2.10] Distinguish between semver metadata for exact-versioned charts

---

pkg/oidc/provider/token.go

Fix `non-constant format string in call to github.com/sirupsen/logrus.Warnf` go vet error

fix go vet error

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml

Introducing a new field to projects to contain what namespace to store PRTBs and project scoped secrets. Subsequent PRs will properly fill the field, but first we need the field to exist.

Add backingnamespace field to projects

---

pkg/apis/ext.cattle.io/v1/types.go
pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/generated/openapi/zz_generated_openapi.go

No issue. During the discussion about https://github.com/rancher/rancher/issues/49588 it was realized that the
comparison of TTL values forgot to properly handle special cases (infinity, default).
See above
A custom comparison function is used to handle all edge cases properly.
Added unit tests for the new comparator.
* Unit
* None
_TODO_
* _TODO_

ext token ttl mishandling of edge cases when comparing

---

pkg/catalogv2/git/utils.go
pkg/controllers/dashboard/helm/repo.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Issue : https://github.com/rancher/rancher/issues/49794
Modifying the code so that Rancher deletes the folder when the clusterRepo is deleted.

Delete dir when cluster repo is deleted

---

pkg/api/steve/additionalapi.go
pkg/capr/common.go
pkg/capr/configserver/agent.go
pkg/capr/configserver/server.go
pkg/capr/planner/agent.go
pkg/capr/planner/config.go
pkg/capr/planner/manifests.go

https://github.com/rancher/rancher/issues/41132
There are two controllers possibly conflicting deploying the cluster agent: the cluster deploy controller and the manifest delivered by planner.
The planner will now deploy the cluster agent only if it doesn't exist. This ensures that the planner initiates the first cluster agent necessary for establishing a connection to the Rancher server but is no-op once the cluster deploy controller takes over.
Note: This code is from @Oats87's pull request (https://github.com/rancher/rancher/pull/41573), with minor changes in the installation script for provisioning tests, calculate unique taints and manage the agent TLS mode.
Tested cluster provisioning and upgrades manually to ensure the changes work as expected.
Existing provisioning tests already …

[main] Deploy cluster agent from manifest only if it doesn't exist

---

pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go
tests/v2prov/tests/fleet/fleetcluster_test.go

Adds the control plane nodes taints to tolerations in the local cluster created by Fleet. Those tolerations will be propagated to the Fleet agent, that will be scheduled successfully in a cluster with all nodes tainted.
Refers to: https://github.com/rancher/rancher/issues/49101
Taints in Control Plane are not propagated as toleration to the local Fleet cluster.
In a cluster with all nodes tainted the Fleet Agent won't be scheduled due to those taints.
Copy all taints in the Control Plane as tolerations to the Fleet's local cluster.
Those tolerations will be assigned to the Fleet agent that will be scheduled.
Deploy rancher in a cluster with all nodes tainted. (Use --set to pass tolerations to the helm chart)
For example:
```bash
--set "extraTolerations[0].key=key1" --set …
```

Adds CP taints to Fleet's local cluster tolerations

---

.github/workflows/push-release.yml
package/Dockerfile
package/Dockerfile.agent

`make quick` is pretty slow when developing Rancher. I don't use it for that reason, instead I use `make build` because it's much quicker (because dapper currently caches go build better than our dockerfiles).
This PR attempt to make `make quick` much faster by leveraging "more modern" docker build features: [RUN --mount=type=cache](https://docs.docker.com/reference/dockerfile/#run---mounttypecache).
First, the result..
**TL;DR**
|Step|Before changes|After changes|Speed up|
|:---  |    ----:|   ----:|   ----:|
|Cold build|~5m7s|~3m18s|1.55x|
|No changes|~7s|~7s|1x|
|Editing Go file|~3m21s|~29s|6.9x|
|Updating go.mod|~4m54s|~49s|6.0x|
<details>
<summary>Gimme `time` output</summary>
Here are the results from two scenarios I typically run into: (1) editing Go files directly in Rancher and …

Make `make quick` quick

---

pkg/data/management/role_data.go

https://github.com/rancher/rancher/issues/48621
The issue came up in regards to the [Kubeconfig Public API](https://github.com/rancher/rancher/issues/48621) but really is applicable to any Imperative API resource that doesn't support/implement `patch` operation.
When a standard or base rancher user attempts to create an imperative API resource e.g. `kubeconfigs.ext.cattle.io`, which doesn't implement `patch` operation, the validation fails for them with the following error:
```
kubectl --context ext2 create -f  -<<EOF
apiVersion: ext.cattle.io/v1
kind: Kubeconfig
spec:
clusters: [c-m-tbgzfbgf]
EOF
error: error validating "STDIN": error validating data: failed to check CRD: failed to list CRDs: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "u-s857n" cannot list resource …
```

Allow read-only access to CRD definitions for the base and standard Rancher users

---

pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go

Project and project members not displaying on Cluster and Project Members page. The issue is that the UI expects the `projectId` in the format `c-m-xxxx:p-yyy`, but it has been updated to match the project namespace name `c-xxxx-p-yyy`. This only affects downstream clusters because [this condition](https://github.com/rancher/rancher/blob/main/pkg/api/norman/store/scoped/store.go#L28) works for the local cluster as the name does not contain a `-`.
Replace all `-` when comparing the strings, so it also works for clusters with `-` in their name
Unit tests added.
[Unit test](https://github.com/raulcabello/rancher/blob/e39fb1859f1cad1be09bf49403530111a3debbae/pkg/api/norman/store/scoped/store_test.go#L152) for local cluster is passing without the fix in this PR
[Unit …

fix projectId for downstream clusters

---

package/Dockerfile

On MacOS with ARM (could affect other systems too who knows), I am seeing this error:
```
------
> [chroot-builder-server 1/2] COPY --from=final / /chroot/:
------
Dockerfile:27
--------------------
25 |
26 |     FROM chroot-builder AS chroot-builder-server
27 | >>> COPY --from=final / /chroot/
28 |     RUN zypper refresh && \
29 |         zypper --installroot /chroot -n in --no-recommends \
--------------------
ERROR: failed to solve: failed to commit 4slhj7et8e43m0aekstqi0378 to 7ois4967oz61ftl23vgg0le77 during finalize: failed to stat active key during commit: snapshot 4slhj7et8e43m0aekstqi0378 does not exist: not found
```
The cause of this seems related to the `final` layer not being created or in the build cache. I was able to verify that adding any `RUN` directive to this - …

[main] Adjust dockerfile to fix builds on arm+macos

---

pkg/controllers/capr/unmanaged/controller.go

https://github.com/rancher/rancher/issues/49895
Set the taint annotation on the CAPI customMachine and Machine for custom clusters 
When provisioning a custom K3s cluster where all roles are assigned to each node, 
an issue arises if the first machine to register has a taint that is not tolerated 
by the rancher-cluster-agent or other K3s addon components. In this case, no 
other machine can complete the registration process because the only available node 
is unschedulable due to the taint. As a result, the cluster remains with a single 
tainted node, and provisioning cannot proceed.
This occurs because the taint information is not set on the corresponding CAPI 
Machine object - specifically, the rke.cattle.io/taints annotation is missing. 
Without this annotation, Rancher does not apply …

Fix flaky-test Test_Provisioning_Custom_ThreeNodeWithTaints

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

#49252
Rancher was keeping RDP even with Imperative API disabled. 
Changed the Uninstall flag to indicate to Rancher it can remove RDP

#49252 - Uninstalling RDP when Imperative API is off

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Issue : https://github.com/rancher/rancher/issues/49668
- Couldn't reproduce the flakiness in the CI for 10 runs. 
Test Name   :  GitRepoRetries
Test 1 of 10 :        ✅ 
Test 2 of 10 :        ✅ 
Test 3 of 10 :        ✅ 
Test 4 of 10 :        ✅ 
Test 5 of 10 :        ✅  
Test 6 of 10 :        ✅ 
Test 7 of 10 :        ✅ 
Test 8 of 10 :        ✅ 
Test 9 of 10 :        ✅ 
Test 10 of 10 :       ✅ 
- I am adding a log statement to understand the flakiness. This will be temporary until I understand the root cause of flakiness. It might be annoying to see these log statements in the CI temporarily.

Add log statements to testcase for more visibility on flakiness

---

pkg/data/management/kontainerdriver_data.go
pkg/data/management/kontainerdriver_data_test.go
pkg/data/management/machinedriver_data.go
pkg/data/management/machinedriver_data_test.go
tests/integration/suite/test_rbac.py

https://github.com/rancher/rancher/issues/48758
https://github.com/rancher/rancher/issues/48759
Some node and kontainer driver objects that Rancher automatically creates have URLs that are no longer active, and can be removed.
Remove the node and kontainer drivers.
This is done alongside the code that used to add them.
1. New installations of rancher will just no longer add the invalid drivers.
2. If the drivers exist, are inactive, and their url has the prefix for the invalid domain, they are removed. This is to handle upgrades in installations that already had the object.
They are only removed if they are inactive and domain in its URL matches the invalid one. This is to account for cases where a user hosted the driver somewhere else and edited the same driver object with a different …

Remove invalid node/kontainer drivers

---

pkg/api/norman/customization/cred/store.go
pkg/api/norman/customization/cred/store_test.go

When creating a cloud credential for Harvester, an annotation containing the expiration date of the authentication token used in the kubeconfig for the Harvester cluster needs to be set.
To figure out the correct expiration date, the token needs to be identified, but this needs to account for the fact that the token has a different naming scheme for the default admin user and additional users.
As described in [the issue](https://github.com/rancher/rancher/issues/49810#issuecomment-2827389345)
By matching tokens with either `kubeconfig-user-` prefix or `kubeconfig-u-` prefix, any eligible token is correctly identified.
As a result, the annotation is correctly added to the cloud credential and both the renewal menu entry as well as the expiration date correctly appear in the cloud …

fix token identification

---

pkg/controllers/capr/unmanaged/controller.go

**Do Not Merge Until v2.11.1 is released.** 
Issue: https://github.com/rancher/rancher/issues/49983
Cherry-pick from https://github.com/rancher/rancher/pull/49923

[2.11] [Backport] Fix flaky-test Test_Provisioning_Custom_ThreeNodeWithTaints

---

pkg/api/norman/customization/cred/store.go
pkg/api/norman/customization/cred/store_test.go

original issue: rancher/rancher#49810
backport issue: rancher/rancher#50040
When creating a cloud credential for Harvester, an annotation containing the expiration date of the authentication token used in the kubeconfig for the Harvester cluster needs to be set.
To figure out the correct expiration date, the token needs to be identified, but this needs to account for the fact that the token has a different naming scheme for the default admin user and additional users.
As described in https://github.com/rancher/rancher/issues/49810#issuecomment-2827389345
As described in rancher/rancher#50028
This is a backport of #50028 to v2.10 branch.
As described in rancher/rancher#50028
* Unit
* Validation (Go …

[backport v2.10] fix token identification

---

pkg/api/steve/disallow/disallow.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/management/auth/roletemplates/roletemplate_handler.go
pkg/controllers/management/auth/roletemplates/roletemplate_handler_test.go
pkg/controllers/management/secretmigrator/clusters.go
pkg/data/management/role_data.go

Several `project.cattle.io` CRDs were removed with this PR in 2.7 https://github.com/rancher/rancher/pull/38579. However, a few references were missed. Specifically, `sourcecodeproviderconfigs`, `sourcecoderepositories` and `sourcecodecredentials`. 
Removed all references to those resources.
* Unit
* None
_TODO_
* _TODO_

Remove references to removed project.cattle.io CRDs

---

pkg/api/norman/customization/cred/store.go
pkg/api/norman/customization/cred/store_test.go

original issue: rancher/rancher#49810
backport issue: rancher/rancher#50039
When creating a cloud credential for Harvester, an annotation containing the expiration date of the authentication token used in the kubeconfig for the Harvester cluster needs to be set.
To figure out the correct expiration date, the token needs to be identified, but this needs to account for the fact that the token has a different naming scheme for the default admin user and additional users.
As described in https://github.com/rancher/rancher/issues/49810#issuecomment-2827389345
As described in rancher/rancher#50028
This is a backport of #50028 to v2.11 branch.
As described in rancher/rancher#50028
* Unit
* Validation (Go …

[backport v2.11] fix token identification

---

.github/workflows/push-release.yml
package/Dockerfile
package/Dockerfile.agent

Backport of https://github.com/rancher/rancher/pull/49633. The original description has been copy pasted here.
---
`make quick` is pretty slow when developing Rancher. I don't use it for that reason, instead I use `make build` because it's much quicker (because dapper currently caches go build better than our dockerfiles).
This PR attempt to make `make quick` much faster by leveraging "more modern" docker build features: [RUN --mount=type=cache](https://docs.docker.com/reference/dockerfile/#run---mounttypecache).
First, the result..
**TL;DR**
|Step|Before changes|After changes|Speed up|
|:---  |    ----:|   ----:|   ----:|
|Cold build|~5m7s|~3m18s|1.55x|
|No changes|~7s|~7s|1x|
|Editing Go file|~3m21s|~29s|6.9x|
|Updating go.mod|~4m54s|~49s|6.0x|
<details>
<summary>Gimme `time` …

[v2.11] Make `make quick` quick

---

.github/workflows/push-release.yml
package/Dockerfile
package/Dockerfile.agent

Backport of https://github.com/rancher/rancher/pull/49633. The original description has been copy pasted here.
---
`make quick` is pretty slow when developing Rancher. I don't use it for that reason, instead I use `make build` because it's much quicker (because dapper currently caches go build better than our dockerfiles).
This PR attempt to make `make quick` much faster by leveraging "more modern" docker build features: [RUN --mount=type=cache](https://docs.docker.com/reference/dockerfile/#run---mounttypecache).
First, the result..
**TL;DR**
|Step|Before changes|After changes|Speed up|
|:---  |    ----:|   ----:|   ----:|
|Cold build|~5m7s|~3m18s|1.55x|
|No changes|~7s|~7s|1x|
|Editing Go file|~3m21s|~29s|6.9x|
|Updating go.mod|~4m54s|~49s|6.0x|
<details>
<summary>Gimme `time` …

[v2.10] Make `make quick` quick

---

.github/workflows/integration-tests.yml
tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Issue : https://github.com/rancher/rancher/issues/49896 https://github.com/rancher/rancher/issues/49457
Test Name   :  TestUpgradeToBrokenVersion
Test 1 of 10 :    ✅     
Test 2 of 10 :    ✅      
Test 3 of 10 :    ✅     
Test 4 of 10 :    ✅     
Test 5 of 10 :    ✅     
Test 6 of 10 :    ✅      
Test 7 of 10 :    ✅     
Test 8 of 10 :    👎🏽  Failed, the app aks-operator from the previous testcase didn't uninstall properly.    
🔨  Made a fix to uninstall properly like in other integration tests.  Restarting the count. 
Test Name   :  TestUpgradeToBrokenVersion, TestUpgradeChartToLatestVersion
Test 1 of 10 :   ✅       
Test 2 of 10 :  👎🏽 Failed, investigating....Adding more logs to find the reason...same as above the previous testcase didn't uninstall properly. 
🔨  Added more asserts to …

Make sure all helm release secrets are deleted in integration tests before moving on

---

pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/eks/eks_cluster_handler_test.go

https://github.com/rancher/rancher/issues/48366
to fix issue https://github.com/rancher/rancher/issues/48144 a check was added in PR https://github.com/rancher/rancher/pull/48298 which throws error in case the upstreamSpec is nil.
The UpstreamSpec field is only populated while the config is in creating phase.
Due to missing DescribeAddon Permission  the upstreamSpec was not being set. And the EksClusterConfig was in updating phase since addon configuration is done after the cluster is created. Even after the permission is resolved the cluster handler was not populating the upstreamSpec since there were failures when the eksClusterConfig was in creating stage.
And the error `initial upstreamSpec on cluster .. has not been set, unable to continue` was being thrown causing the cluster to be …

[main] fix upstream spec initialization for eks cluster

---

pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/eks/eks_cluster_handler_test.go

https://github.com/rancher/rancher/issues/50106
backport PR of https://github.com/rancher/rancher/pull/50047 cherry-picked from https://github.com/rancher/rancher/commit/458954b82fa9bce3638f87f6fa6ac8642420bb4d
* Unit
* None
_TODO_
* _TODO_

[release/v2.10] fix upstream spec initialization for eks cluster

---

pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/eks/eks_cluster_handler_test.go

https://github.com/rancher/rancher/issues/48366
backport PR of https://github.com/rancher/rancher/pull/50047 cherry-picked from https://github.com/rancher/rancher/pull/50047/commits/458954b82fa9bce3638f87f6fa6ac8642420bb4d
* Unit
* None
_TODO_
* _TODO_

[release/v2.11] fix upstream spec initialization for eks cluster

---

tests/controllers/oidc/oidc_provider_test.go

This integration test leverages [envtest](https://book.kubebuilder.io/reference/envtest.html) to simulate a Kubernetes environment, enabling testing of the OIDCClient controller in a realistic setting.
It initializes Rancher’s embedded OIDC provider and performs a simulated login using go-oidc, mimicking the behavior of a real OIDC client. This helps validate the full authentication flow and ensures that the controller behaves as expected.

OIDC Provider Integration Test

---

build.yaml
pkg/buildconfig/constants.go

This is related to: https://github.com/rancher/shell/issues/340

[main] Bump Shell to version with k8s support for 2.12

---

pkg/image/origins.go

https://github.com/rancher/rancher/issues/49503
A new `rancher/pushprox` image was created. This PR adds it to the list of image origins

[2.11] add pushprox to image origins

---

pkg/image/origins.go

https://github.com/rancher/rancher/issues/49503
A new `rancher/pushprox` image was created. This PR adds it to the list of image origins

adding new pushprox image to image origins

---

pkg/tunnelserver/peermanager.go
pkg/utils/utils.go

The formatting performed for websocket URL is not ipv6 compatible.
backport PR of #49945. Cherry pick of [c9b6585](https://github.com/rancher/rancher/commit/c9b65852391036244e7a03b3fe3ec2c08b005d20)
* Unit
* None
_TODO_
* _TODO_

[backport v2.11] Handles IPv6 addresses during Rancher peer communication

---

pkg/tunnelserver/peermanager.go
pkg/utils/utils.go

The formatting performed for websocket URL is not ipv6 compatible.
backport PR of https://github.com/rancher/rancher/pull/50047 cherry-picked from https://github.com/rancher/rancher/commit/c9b65852391036244e7a03b3fe3ec2c08b005d20
* Unit
* None
_TODO_
* _TODO_

[backport v2.10] Handles IPv6 addresses during Rancher peer communication

---

tests/controllers/oidc/oidc_provider_test.go

Previously, the status subresource was not registered in the `envtest` environment, causing patch request to fail. This change explicitly registers the status subresource in `envtest`, aligning test behavior with actual cluster behavior and allowing status patches to function correctly in tests.

Fix OIDC provider test

---

cmd/agent/main.go

https://github.com/rancher/rancher/issues/50156
Backport of the PR https://github.com/rancher/rancher/pull/50158
For details, please check the original PR

[2.11] [Backport] Fix the issue where cattle-node-agent deletes the cattle-credential secret unexpectedly

---

cmd/agent/main.go

https://github.com/rancher/rancher/issues/50157
Backport of the PR https://github.com/rancher/rancher/pull/50158
For details, please check the original PR

[2.10] [Backport] Fix the issue where cattle-node-agent deletes the cattle-credential secret unexpectedly

---

cmd/agent/main.go

https://github.com/rancher/rancher/issues/50155
Backport of the PR https://github.com/rancher/rancher/pull/50158
For details, please check the original PR

[2.9] [Backport] Fix the issue where cattle-node-agent deletes the cattle-credential secret unexpectedly

---

pkg/apis/ext.cattle.io/v1/types.go
pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/generated/controllers/ext.cattle.io/v1/interface.go
pkg/generated/controllers/ext.cattle.io/v1/token.go

- Throwing away `Bookmark` and `Error` watch event types
- Not passing through all ListMeta fields
- Not having `+genclient:nonNamespaced` directive on the `Token` to generate correct controllers
- Process `Bookmark` and `Error` watch event types
- Pass through `Continue` and `RemainingItemCount` field
- Add `+genclient:nonNamespaced` directive to the `Token` type
* Unit
* None
_TODO_
* _TODO_

ext Tokens fixes

---

pkg/catalogv2/system/system.go

#50176
When there is no taint, the tolerations in the actual chart values is nil. But because `jsonpatch.MergePatch()` removes null fields, the expected chart values have no tolerations field. The `desiredVersionAndValues()` function considers the chart values do not match and the chart should be upgraded. It leads to repeated system chart installation.
Skip adding empty tolerations to the chart values.
Please follow the steps in the linked issue.
Manually tested. With this fix, the number of `helm-operation-` pods is reduced to 5 in a fresh install. There is no repeated system chart install anymore.
N/A
_TODO_
* _TODO_

Skip empty tolerations to fix repeated system chart install

---

pkg/oidc/provider/authorize.go
pkg/oidc/provider/authorize_test.go

Access-Control-Allow-Origin header is set for non-registered redirect URLs.
Add Access-Control-Allow-Origin header after checking the redirect URL is registered.

[OIDC]  Access-Control-Allow-Origin only for registered urls

---

pkg/controllers/provisioningv2/provisioningcluster/controller.go

Even with MCM feature flag disabled, rancher tries to fetch managementCluster cache and reports some benign errors.
As the management cluster can operate without MCM, its cache population has been refactored to occur regardless of the feature’s state.
[NOTE: test cases should include both **traditional Rancher** environments and **Rancher-on-Harvester**.]
- Deploy Rancher with MCM feature disabled
- Rancher pod logs should no longer report management cache to be `nil`.
- Observe the behavior during upgrades too.
- None: No application logic is directly modified by this change, structural change.
Summary: 
- The `management cluster is nil` errors reported were expected, as the managment cluster cache was initialised here only when the MCM feature flag was enabled, but the cache was …

Decouples mgmtCluster client/cache initialization from MCM feature

---

tests/controllers/oidc/oidc_provider_test.go

Call defer after checking error to fix the following `go vet` error:
```
tests/controllers/oidc/oidc_provider_test.go:269:8: using res before checking for errors
```

Fix go vet: check error before using variable

---

pkg/controllers/management/oidcprovider/controller.go
pkg/controllers/management/oidcprovider/controller_test.go

A secret is created for each `OIDCClient` to store the `ClientSecret`, using the `ClientID` as the secret's name. The `OIDCClient` controller generates a new secret whenever `OIDCClient.Status.ClientID` is missing. This status field is updated after the secret is successfully created. If the controller fails to patch `OIDCClient.Status.ClientID`, the absence of this field will cause a new secret to be created on each reconciliation loop.
Delete the secret if an error occurs while patching the `OIDCClient` to update `Status.ClientID`
Unit test added

OIDC provider - Remove OIDCClient Secret if patch fails

---

pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go
pkg/controllers/managementuserlegacy/helm/controller.go

#50372
- #49859 introduced project backing namespaces which is the namespace that contains project related resources. I missed a reference to the project namespace in the k3s upgrade controller.
- helm controller tries to infer the app namespace from the project name instead of using App's Namespace.
Use the backing namespace instead of the project name for the namespace.
N/A

[v2.9] Use project backing namespace to list apps in k3sbased upgrade handler

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
main.go
pkg/ext/extension_apiserver.go
pkg/rancher/rancher.go

https://github.com/rancher/rancher/issues/50370
When creating the `APIService` for the imperative api we use a hardcoded label selector `"app": "rancher"`. If the user install rancher via helm chart using a release name name that is not "rancher" the APIService will not function. 
Provide a command line flag to control the value for the `app` label the `APIService` is selecting for.
1. Build new rancher chart with `scripts/chart/build chart`
2. If testing off of the dev brancher build the rancher image `make quick` or `make quick-server`
3. Install the built rancher chart pointing to either the rancher head image or the image built in the previous step `helm upgrade --install --create-namespace --namespace cattle-system --set rancherImage=<image_repository> --set …

[main] add flag for controlling APIService app label selector

---

pkg/controllers/dashboard/systemcharts/controller.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test

https://github.com/rancher/rancher/issues/50398
The `remotedialer-proxy` chart does not become "up" until late in the rancher start up process. This will make it difficult to determine if the underlying k8s distribution is configured to support the aggregated API layer and ultimately hinder progress on https://github.com/rancher/rancher/issues/50399.
Move the chart installation earlier in the startup process.
* Unit
* None
_TODO_
Existing / newly added automated tests that …

[main] Early rdp

---

pkg/controllers/managementuser/secret/project_scoped_secrets.go
pkg/controllers/managementuser/secret/project_scoped_secrets_test.go
pkg/controllers/managementuser/secret/secret.go
pkg/rbac/common.go

The primary desire of this change is to re-introduce the project scoped secrets feature in a well defined way. Currently it's an available feature by enabling the `Legacy` feature flag, and is only supported through Norman. It's possible to trigger the controllers used by Norman by applying specific annotations and then manually triggering the namespace controllers. There's also no tests around this feature.
Took this as an opportunity to re-work the controllers that implement the project scoped secret feature. Some key points:
- Using Wrangler controllers and clients
- Unit tests
- Improved comments, logging and readability
- Splitting it into it's own file
The new (or at least more complete) functionality is as follows:
1. Secrets in the local cluster with the label …

Improve consistency of project scoped secrets controllers

---

pkg/data/management/role_data.go

The new Imperative API resource Kubeconfig is no longer ephemeral and implements `rest.Patcher`. Thus it's no longer needed.
Reverts #49318

Revert "Allow read-only access to CRD definitions for the base and standard Rancher users"

---

pkg/controllers/managementuser/networkpolicy/netpol.go
pkg/controllers/managementuser/networkpolicy/register.go

#49765
Default network policies (np-default, np-default-allow-all) were not being restored when deleted or edited in downstream clusters, leading to inconsistent security postures across namespaces and clusters.
Solution
A new handler was added to watch and reconcile default network policies created by Rancher in managed clusters.
Manual Testing
Deleted np-default, hn-nodes, and np-default-allow-all in various namespaces and verified they were recreated as expected.

fix: add handler to watch and reconcile default network policies

---

pkg/data/management/role_data.go

This PR adds a built-in `GlobalRole` to manage `OIDCClient` resources.

Add manage-oidc-clients builtin GlobalRole

---

pkg/ext/stores/tokens/tokens.go

#50473 
kubeconfig and ext token are inconsistent in the label with which to filter by user id.
modified ext token store to use the same label as kubeconfigs: `cattle.io/user-id`.
unit tests pass after the change.
The ext token test plan requires updates to all test cases referencing the old label.
Filtering by user id requires re-testing.

ext token userid filter label changed to match new kubeconfig work

---

pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler_test.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
pkg/controllers/managementuser/rbac/roletemplate_handler.go

https://github.com/rancher/rancher/issues/50534
Project RoleTemplates can give access to non-namespaced resources, which we refer to as "promoted rules". Full list can be found here https://github.com/rancher/rancher/blob/a54be8cc6e3ccf16a61b253d4f98f4345ec3052c/pkg/controllers/managementuser/rbac/prtb_handler.go#L34
When a Project RoleTemplate has these, we create a ClusterRole that contains all the promoted rules. Then, any time the RoleTemplate is updated, there is a check to ensure that the ClusterRole has the correct verbs. The problem that users were noticing was that they would be seeing logs of `[INFO] Updating clusterRole admin-promoted for project access to global resource.` over and over. In systems with thousands of users and PRTBs, this could flood the logs with thousands of …

Prevent unnecessary updates to promoted clusterroles

---

pkg/image/origins.go

Backport of: https://github.com/rancher/rancher/pull/50117
Now that we've backported the updated chart to 2.10 the origins in 2.10 need to match.

add new pushprox image name

---

pkg/rancher/rancher.go

https://github.com/rancher/rancher/issues/50286
With the deprecation and removal of RKE in Rancher v2.12, it's necessary to ensure that existing installations don't inadvertently upgrade without first removing RKE-related resources. Currently, there's no enforcement mechanism in place to block such upgrades, which could lead to failures or inconsistent states.
**Key Changes**
- Validation logic added at startup to detect the presence of RKE1 resources:
1. Cluster templates referencing RKE1
2. Node templates used by RKE1 clusters
3. Existing RKE1 clusters
- If any RKE1-related resource is detected, Rancher fails fast with a clear error message.
**_This ensures: No unsupported RKE1 workloads are managed in Rancher v2.12+. Admins are forced to clean up or migrate before upgrading_**
**How to …

Enforce RKE1 Resource Pre-Upgrade Validation in Rancher Manager

---

pkg/catalogv2/oci/oci.go
pkg/catalogv2/oci/oci_test.go

[50499](https://github.com/rancher/rancher/issues/50499)
Rancher pods go into a CrashLoopBackoff when an OCI repo after an upgrade from 2.11.1 to 2.11.2
```log
panic: runtime error: index out of range [0] with length 0 [recovered]                                                           panic: runtime error: index out of range [0] with length 0                                                                                                                                
```
after[0] needs to evaluated only after we check that it is not empty and it is safe to do so, as suggested in the original issue [50499](https://github.com/rancher/rancher/issues/50499)
K3S version: 1.30.13-k3s1
1. Installed Rancher
2. Created an OCI repo with (oci://code.forgejo.org/forgejo-helm/forgejo)
3. Created …

Fix #50499 prevent index out of range panic when `after` is empty

---

pkg/controllers/management/auth/register.go
pkg/controllers/management/auth/roletemplates/register.go
pkg/controllers/management/auth/roletemplates/roletemplate_handler.go
pkg/controllers/management/auth/roletemplates/roletemplate_handler_test.go
pkg/controllers/managementuser/rbac/roletemplates/register.go
pkg/controllers/managementuser/rbac/roletemplates/roletemplate_handler.go
pkg/controllers/managementuser/rbac/roletemplates/roletemplate_handler_test.go
pkg/rbac/common.go
pkg/rbac/common_test.go

With the Aggregated ClusterRoles feature enabled, when a RoleTemplate is created, it creates 2 ClusterRoles in each cluster. One named after the RoleTemplate and another that aggregates the first ClusterRole. The problem is that when the RoleTemplate was deleted, it removed the ClusterRoles on the management cluster, but not the downstream clusters.
Another issue I noticed while fixing this was the promoted ClusterRoles weren't being created properly in downstream clusters. For project role templates, certain resources are considered "promoted" and we need to create a separate ClusterRole.
The issue was that I had registered multiple `OnRemove` handlers, 1 per cluster per RoleTemplate. They all rely on the same finalizer, so what was happening was that the first `OnRemove` handler would …

Remove ClusterRoles made by RoleTemplates from downstream clusters

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

For information about the PR please refer to this old PR:
https://github.com/rancher/rancher/pull/49604
This was re-opened after a chat with the security team where we agreed with that there are no security concerns with this solution.
After the PR will be merged, we'll proceed with the backport to 2.9

fix: add create secrets permissions in fleet-default namespace

---

pkg/controllers/managementuser/secret/project_scoped_secrets.go
pkg/controllers/managementuser/secret/project_scoped_secrets_test.go

When restarting Rancher, the Project Scoped Secret controller would delete the original project scoped secret.
Added a new annotation to track which secrets are copies. Then the controller checks for that annotation and only modifies/deletes those.
Followed the steps in the issue. On restart the original project scoped secret is no longer removed.
* Unit
Summary: Added checks for the annotation in the unit tests.
_TODO_
* _TODO_

Add new annotation to track which project scoped secrets are copies

---

pkg/auth/providerrefresh/refresher_test.go
pkg/auth/requests/authenticate_test.go
pkg/auth/requests/impersonate_test.go
pkg/controllers/management/auth/user_test.go
pkg/ext/stores/install.go
pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/ext/stores/useractivity/store_test.go

kubeconfig and token stores used different places and methods in the code to initialize the namespace for their backing store.
Reworked token store to match kubeconfig. Updated unit tests. Added unrelated unit tests.
* Unit
* None
_TODO_
* _TODO_

Ensure ext.Token namespace exists on Rancher start

---

pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler_test.go

During QA tests session @Priyashetty17 reported a failing test when using `updatepsa` permissions on a downstream cluster: https://github.com/rancher/rancher/issues/48721#issuecomment-2899052383
The user is unable to create a namespace with PSA labels within a project (having `updatepsa` permissions).
This PR allow the user to create namespaces with PSA labels within projects in downstream clusters.
The problem was due to the use of the wrong package (`pkg/controllers/management/auth` instead of `pkg/controllers/managementuser/rbac` which allow to watch resources on both local and downstream cluster).
The following code creates a `ClusterRole` and a `ClusterRoleBinding` to allow the `updatepsa` verb on the user permissions.
The `ClusterRole` has this name: `<project_name>-namespaces-psa` …

fix: enable psa permissions on downstream clusters

---

pkg/ext/stores/install.go
pkg/features/feature.go

Given that Imperative API is in its infancy we'd like to have a feature flag (for one or two minor versions of Rancher) that can be used to disable Tokens resource store in case we encounter issues with it.
Add feature flag that enables Imperative Kubeconfigs resource store.
* Unit
* None
_TODO_
* _TODO_

Add feature flag that enables ext Tokens

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

Revert "(backport of #50482) fix: add create secrets permissions in fleet-default namespace"

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

In the anticipation of v2.12.0 release set Rancher CLI to [v2.12.0-rc.1](https://github.com/rancher/cli/releases/tag/v2.12.0-rc.1).

Bump Rancher CLI to v2.12.0-rc.1

---

pkg/controllers/managementuser/secret/project_scoped_secrets.go
pkg/controllers/managementuser/secret/project_scoped_secrets_test.go

The original intention was to use a new migration framework to convert existing project scoped secrets to use the new label. Due to time constraints, the migration framework was not implemented for v2.12 release. So we need to introduce a different migration mechanic for those existing secrets.
Add a new step to the controller that removes a label, finalizer, and annotation from the old controllers and adds a label used by the new controllers.
* Unit
* None
_TODO_
Existing / …

Migrate project scoped secret controllers

---

pkg/oidc/provider/token.go
pkg/oidc/provider/token_test.go

Patch to update the OIDC client secret last used timestamp fails when the `OIDCClient` annotations is `nil`. This is an issue when creating `OIDCClients` from the UI as no annotations are created. This issue is not reproducible when using `kubectl apply` as it adds an annotation.
Check if annotation is `nil` to create the relevant patch for updating the client secret last used timestamp. Do the same when doing a patch to add the OIDC client to a token.

[OIDC provider] Fix oidc client secret last used

---

scripts/artifacts-list.sh

We stopped writing to `rancher-rke-k8s-versions.txt` as it included only RKE1 versions so far in [this PR](https://github.com/rancher/rancher/commit/7e4dc583125ee4624f341777f9d44268e425aed8#diff-2623863f3d8249bed94fa69df203ba439413583a04367f68031f176af5187200L99).

[main] Remove rancher-rke-k8s-versions.txt from artifacts list

---

pkg/apis/management.cattle.io/v3/condition.go
pkg/apis/management.cattle.io/v3/machine_types.go
pkg/crds/names.go
pkg/crds/yaml/generated/management.cattle.io_nodedrivers.yaml

`kubectl explain` does not describe the various fields included in the Node Driver CRD. This makes it more difficult to work with the CRD directly from the CLI. 
Add kube builder annotations to the struct and ensure each field has a useful description. I could not find a case where the `externalID` field was used within Rancher or the UI, so I marked that field as unused. If a reviewer knows if this field is still in use by Rancher, let me know and I will update the description accordingly. 
After making these changes I confirmed I was able to provision a cluster via the Rancher UI. I also confirmed that changing various properties of an existing node driver (activating / deactivating, updating names and urls) via `kubectl` worked as expected and were properly reflected in the Rancher UI. …

[main] Node Driver Public API

---

dev-scripts/quick

It makes sense that this script runs `docker push` in the background, but it should wait on all background
processes before exiting.

Stop 'make quick' from returning to the command-line prematurely.

---

pkg/apis/rke.cattle.io/v1/machine.go
pkg/controllers/capr/controllers.go
pkg/controllers/capr/dynamicschema/dynamicschema.go
pkg/controllers/capr/dynamicschema/sample/rke-machine.cattle.io_samples.yaml
pkg/controllers/capr/dynamicschema/sample/sample.go
pkg/controllers/dashboard/controller.go
scripts/build-crds

Document API for dynamic schemas.
Dynamic schemas for node drivers have missing descriptions.
Add descriptions for each dynamic schema as it is generated in the dynamic schema controller.
Each node driver generates three schemas: the configuration schema, the CAPI infrastructure machine schema, and the CAPI infrastructure machine template schema.
For instance, the digital ocean driver results in the three following `schemas`:
- `digitaloceanconfigs.rke-machine-config.cattle.io`
- `digitaloceanmachines.rke-machine.cattle.io`
- `digitaloceanmachinetemplates.rke-machine.cattle.io`
Each schema includes the flags used to call the node driver. The descriptions for those flags come from the node driver flag descriptions, and were already working.
All the other properties in the schemas are now …

[main] API doc for dynamic schemas

---

pkg/ext/stores/kubeconfig/store.go
pkg/ext/stores/kubeconfig/store_test.go
pkg/kubeconfig/kubeconfig.go

https://github.com/rancher/rancher/issues/50855
Cluster's CACert is already base64 encoded which was leading to double encoding when generating a kubeconfig for an ACE cluster.
Don't base64 encode Cluster's CACert. 
N/A

Don't double encode ACE cluster's CACert when generating a kubeconfig

---

pkg/apis/management.cattle.io/v3/machine_types.go
pkg/crds/yaml/generated/management.cattle.io_nodedrivers.yaml

The links included in the current Node Driver struct, and now the `kubectl explain` output, are dead. 
Update the links to the correct upstream documentation urls
Ran `kubectl explain` and confirm that the description is updated. 
I've done the above
* Unit
* None
_TODO_
* _TODO_

[main] Node Driver API Followup

---

Dockerfile.dapper
package/Dockerfile
pkg/rkecerts/certs_test.go
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh
tests/v2/validation/kdm/kdm_test.go

v2.9.10 was released in May, switching it back to dev-v2.9 to pull in June patches for v2.9.11.

[v2.9] update kdm branch to dev-v2.9

---

go.mod
go.sum
pkg/ext/extension_apiserver.go
pkg/rancher/rancher.go

Relates to #50661
The new Imperative API is now enabled by default for Rancher 2.12. This means there is now a hard requirement for API Aggregation to be supported in the upstream cluster. The only reliable way we currently have for verifying that is to make Rancher run and become available for Kubernetes to contact it, after which we'll unblock Steve from working as normal (hence unblocking the UI usage).
This could introduce a delay in the startup process, affecting the user and development/testing experience.
Minimize the impact of the new check by implementing some sort of memory:
- Whenever the Aggregation API is proven to first work, the corresponding `apiservice` resource will be annotated.
- Subsequent Rancher starts can now check the `apiservice` resource for the annotation …

Fast-track Steve startup if the aggregation API was previously proven to work

---

pkg/ext/stores/install.go
pkg/ext/stores/kubeconfig/store.go
pkg/ext/stores/kubeconfig/store_test.go

https://github.com/rancher/rancher/issues/50865
The Imperative resource Kubeconfigs makes use of nodes.managements.cattle.io for listing control plane nodes for an ACE-enabled cluster. When the MCM is not enabled this CRD is not available.
Make sure nodes are not being used when the MCM is disabled.
* Unit
N/A

Make sure Kubeconfigs work when MCM is disabled

---

pkg/controllers/managementuser/rbac/roletemplates/prtb_handler.go
pkg/controllers/managementuser/rbac/roletemplates/prtb_handler_test.go

This fix allow the user to not use a pre-defined RoleTemplate to allow access to `updatepsa` for users.
Instead of using the aggregated CR generated from the applied RoleTemplate, I'm creating a dedicated CR in order to better manage the flow of granting access to the `Project` resource.
* Unit
* None
_TODO_
* _TODO_

Use a dedicated ClusterRole for projects

---

pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/management/clusterstats/statsaggregator.go
pkg/controllers/management/k3sbasedupgrade/template.go
pkg/controllers/management/k3sbasedupgrade/template_test.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go
pkg/controllers/managementuser/nodesyncer/nodessyncer_test.go
pkg/controllers/managementuser/windows/linux_node_taints.go
pkg/controllers/managementuser/windows/node_test.go
pkg/settings/agent_customization.go
pkg/systemtemplate/import_test.go
pkg/systemtemplate/template.go

The node selector is hardcoded, which is deprecated with k8s v1.14, hence leads to warnings while applying the templates.
This commit:
- Removes the `cattle-node-agent-windows` daemonset from the template, as it's no longer being used since `rke1` deprecation.
- Cleans up `SystemTemplate()` by removing `isWindowsCluster` parameter, which is no longer relevant post Windows support deprecation
- Replaces the other occurrences of deprecated label `beta.kubernetes.io/os` with `kubernetes.io/os`.
- Replaces occurrences of deprecated node role `"node-role.kubernetes.io/master"` with `"node-role.kubernetes.io/control-plane"`.
- Updates the checksum for affected resources in the tests.
Steps in the GitHub issue are valid.
reference doc: https://ranchermanager.docs.rancher.com/how-to-guides/new-use …

Update the deprecated k8s node selectors

---

go.mod
go.sum

No related issue #, but the fix prevents rancher from always entering debug mode when `remotedialer:proxy.Start()` is invoked.

Bump remotedialer to v0.4.5-rc.4

---

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate_test.go

If an etcdsnapshot already exists but doesn't match the indexer criteria, it will fail to be updated with the following message:
```
[ERROR] error syncing 's3-etcd-snapshot-...': handler snapshotbackpopulate: etcdsnapshots.rke.cattle.io "...-etcd-snapshot-..." is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update, requeuing
```
If the etcdsnapshot object already exists, fetch the existing one before updating.
Tested manually.
* Unit
Summary: Updated existing unit tests to confirm the snapshot is updated.
**NOTE**: when testing, the snapshot will only be reconciled when the downstream snapshot is changed. This will happen automatically after some time (when the object is reenqueued within rancher), but can be forced by …

Regenerate etcd snapshot if it exists but doesn't not match indexer criteria

---

pkg/scc/systeminfo/offline/offline.go

Offline Cert validation causes panic instead of an error.
```
│ rancher-cbcccfcfd-gnglk github.com/rancher/rancher/pkg/scc/systeminfo/offline.(*offlineCertError).Unwrap(0x108a0230?)           │
│ rancher-cbcccfcfd-gnglk     /app/pkg/scc/systeminfo/offline/offline.go:36 +0x4                                                  │
│ rancher-cbcccfcfd-gnglk errors.is({0xb294fc0?, 0xc007268320?}, {0xb294b60, 0x10898360}, 0x1)  
```
Fix the `Unwrap` contract by returning nil if not a wrapped error.

[main][scc] Fix offline cert error Unwrap panic

---

pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate_test.go

Backport of https://github.com/rancher/rancher/pull/50889
If an etcdsnapshot already exists but doesn't match the indexer criteria, it will fail to be updated with the following message:
```
[ERROR] error syncing 's3-etcd-snapshot-...': handler snapshotbackpopulate: etcdsnapshots.rke.cattle.io "...-etcd-snapshot-..." is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update, requeuing
```
If the etcdsnapshot object already exists, fetch the existing one before updating.
Tested manually.
* Unit
Summary: Updated existing unit tests to confirm the snapshot is updated.
**NOTE**: when testing, the snapshot will only be reconciled when the downstream snapshot is changed. This will happen automatically after some time (when the object …

[2.11] 50849 etcd snapshot invalid resource version

---

pkg/controllers/managementuser/cavalidator/cavalidator.go
pkg/controllers/managementuser/cavalidator/cavalidator_test.go
pkg/controllers/managementuser/controllers.go
pkg/watcher/watcher.go
pkg/watcher/watcher_test.go

[v2.11] Make cavalidator handler use a single-object watch

---

pkg/apis/rke.cattle.io/v1/etcdsnapshot_types.go
pkg/apis/rke.cattle.io/v1/rkecontrolplane_types.go
pkg/crds/names.go
pkg/crds/yaml/generated/provisioning.cattle.io_clusters.yaml
pkg/crds/yaml/generated/rke.cattle.io_etcdsnapshots.yaml
pkg/crds/yaml/generated/rke.cattle.io_rkecontrolplanes.yaml

https://github.com/rancher/rancher/issues/50231
`kubectl explain etcdsnapshots.rke.cattle.io` does not have meaningful output.
Add comments and kube builder markers to improve kubectl explain output. 
Tested output of `kubectl explain etcdsnapshot.snapshotFile`, `kubectl explain kubectl explain etcdsnapshots.snapshotFile.s3` and  `kubectl get crd etcdsnapshots.rke.cattle.io -o yaml`. 
Created a downstream cluster and confirmed etcd snapshots continue to work for local and s3.
Explained above

[main] EtcdSnapshot Public API

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/systemtemplate/import.go

https://github.com/rancher/rancher/issues/51051
The `system-upgrade-controller` app is required on downstream node-driver RKE2/K3s clusters for Rancher to perform Kubernetes version upgrades.
However, if the `managed-system-upgrade-controller` feature flag is disabled, the SUC app will not be installed on these clusters. This flag is intended for internal use to control SUC app management in imported clusters, not node-driver clusters, where the app should always be installed.
This occurs because, starting with Rancher 2.12.0, the installation of the `system-upgrade-controller` app in node-driver clusters is managed by the cluster agent. Therefore, we need to update the logic that determines whether the `managed-system-upgrade-controller` feature should be enabled in the …

[2.12] ensure the SUC app to be always installed on node-driver/custom RKE2/K3s clusters

---

pkg/api/steve/clusters/shell.go

dashboard-shell pod tolerations using controlplane(rke1) instead of control-plane in rke2
RKE1-specific taint node-role.kubernetes.io/controlplane will be removed with RKE1 cleanup. Retaining it for now; adding RKE2 tolerations.
* Unit
* None
_TODO_
* _TODO_

add-rke2-toleration to dashboard shell pod

---

pkg/apis/provisioning.cattle.io/v1/cluster_types.go
pkg/apis/rke.cattle.io/v1/rkecontrolplane_types.go
pkg/crds/yaml/generated/provisioning.cattle.io_clusters.yaml
pkg/crds/yaml/generated/rke.cattle.io_rkecontrolplanes.yaml

RBAC was all messed up because I forgot to add the `"auth.cattle.io/cluster-indexed=true"` label to the provisioning cluster and controlplane CRDs.
Add it back
Tested manually, clusters no longer hang on creation and the `crt-<CLUSTER_NAME>-cluster-admin` and `crt-<CLUSTER_NAME>-cluster-owner` roles show the provisioning cluster object and controlplane object.
Just make sure to test with the expected standard users/create cluster role.

Fix rbac for v2prov

---

.github/actions/setup-build-env/action.yml
dev-scripts/quick
package/Dockerfile

The CATTLE_HELM_VERSION variable — this was completely [removed](https://github.com/rancher/rancher/pull/47661/commits/356f6c38e9c0a4f5dc111c3c1d193862fe70e585#diff-c55d1ee74f32cd4b9eeeceaec981a180f52e761acb158a5b0b0e088c7725c9caL60) from the backend starting with Rancher v2.11. Since then, Helm version is fetched from the dev environment. However, in upgraded clusters, it still seems to fall back to the old CATTLE_HELM_VERSION value, leading to inconsistencies.
reintroduce CATTLE_HELM_VERSION
* Unit
* None …

add env CATTLE_HELM_VERSION

---

Makefile
dev-scripts/quick
package/Dockerfile

We'll be able to build the binary like `make build` by running `make quick-binary-server`. It's going to be fast, re-use caches for images and support local Go replace directive.
Currently building Rancher can be done in many ways:
- build the image with `make quick` (or `make quick-server` or `make quick-agent`)
- build the go binary with `make build` (or `make build-server` or `make build-agent`) (uses Dapper)
- running your own go build script
I usually use `make build` because I want to build an image. This works fine and is quick because it mounts volumes for `GOCACHE` and `GOMODCACHE`. It has one limitation though: it doesn't support local Go replace directive. So if I want to build Rancher with a `steve` local to my machine, I must edit `Dockerfile.dapper` to add a volume OR push …

Add `make quick-binary-server` command

---

pkg/auth/requests/authenticate_test.go
pkg/auth/requests/impersonate_test.go
pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/ext/stores/useractivity/store_test.go

#51113
The ext token store mishandles deletion with uid preconditions.
Translate the token uid found in the incoming precondition into the uid of the backing secret and use that in the precondition handed to the backend.
Additional unit test.
* Unit
* None
_TODO_
* _TODO_

[Post 2.12] Properly support uid preconditions for ext token deletion

---

pkg/settings/setting.go

- `rancher/dashboard` and `rancher/ui` have both now branched for 2.12
- This change ensures the `rancher/rancher` points to the correct builds for the 2.12 release
- These builds are used, when settings are default, when the version ends in head as an alternative to the embedded builds
- This change will need to be reverted in `main` after `rancher/rancher` branches for 2.12

Update references to new 2.12 UI branches

---

pkg/settings/setting.go

#51228 
The namespace `cattle-token` is the backing store for the data of ext token and ext kubeconfig.
This namespace should belong to the system project.
Added the namespace to the set of namespaces for the system project.

Add namespace `cattle-tokens` to system project

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

#49473
See #49493 and associated https://github.com/rancher/kube-api-auth/pull/35
This PR bumps r/r to the kube-api-auth 2.5.0-rc.1 image so that the combination of the above-referenced PR's can be properly tested together.

bump kube-api-auth to 2.5.0-rc.1

---

pkg/oidc/provider/token_test.go

go vet shows the following error:
```
pkg/oidc/provider/token_test.go:114:23: k8s.io/apimachinery/pkg/apis/meta/v1.Time struct literal uses unkeyed fields
```
Add key to time struct when initializing it.

Fix go vet

---

pkg/image/origins.go

Add origins for RKE2 hardened images:
- `hardened-multus-dynamic-networks-controller`
- `hardened-multus-thick`

[release/v2.10] Add `hardened-multus-dynamic-networks-controller` and `hardened-multus-thick` images origins

---

.github/workflows/controller-test.yml
.github/workflows/verify-generated-code-changes.yml
Dockerfile-windows.dapper
Dockerfile.dapper
go.mod
hack/airgap/go.mod
pkg/api/norman/customization/cluster/validator.go
pkg/api/norman/customization/oci/handler.go
pkg/api/norman/customization/yaml/link.go
pkg/api/norman/store/cluster/cluster_store.go
pkg/apis/go.mod
pkg/auth/providers/saml/saml_client.go
pkg/capr/planner/planner.go
pkg/catalogv2/system/system.go
pkg/client/go.mod
pkg/controllers/capr/plansecret/plansecret.go
pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go
pkg/kontainer-engine/service/service.go
pkg/rkeworker/docker.go
tests/v2/codecoverage/Dockerfile.buildcodecoverage
tests/v2/codecoverage/Dockerfile.codecoverage
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent

v2.11 is currently built with Go 1.23. Go 1.25 is about to be released and main + v2.12 were built with Go 1.24 for a while now.
Start building v2.11 with Go 1.24.
It also allows us to use go tool for v2.11, v2.12, and main.
N/A

[v2.11] Bump Go to 1.24

---

pkg/auth/providers/azure/clients/group_cache.go
pkg/auth/providers/azure/clients/group_cache_test.go
pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Backport of https://github.com/rancher/rancher/pull/51283 to v2.12
Fix panic when accessing empty fields
This avoids a nil panic when extracting the DisplayName for a Group and the DisplayName or PrincipalName for Users.

[backport v2.12] Handle users with no DisplayName or PrincipalName

---

pkg/auth/providers/azure/clients/group_cache.go
pkg/auth/providers/azure/clients/group_cache_test.go
pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

User and Group objects returned from the Azure Graph queries _may not_ include some fields that we assume are populated.
This can lead to a panic when these fields are not populated.
This uses the ptr.Deref function to return an empty string when necessary (the value is nil).
Tests are added.
* Unit
* None
_TODO_
* _TODO_

[v2.11] Fix dereference of the empty displayname

---

pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/ext/stores/tokens/zz_token_fakes.go

#51332
The retrieval of the session id from the request context swallows lower errors in one place, instead of passing them through. 
pass the errors, and abort properly in the higher levels
Updated unit tests.
* Unit
* None
_TODO_
* _TODO_

Don't ignore errors when retrieving authentication token ID

---

pkg/auth/providers/local/pbkdf2/pbkdf2.go
pkg/auth/providers/local/pbkdf2/pbkdf2_test.go
pkg/data/management/resetpassword.go

Reset admin password is not working. It returns an error because it tries to create a secret that already exists.
Update the secret that contains the password. 
Additionally, this PR also checks that the password is not empty when using the legacy password field in User,

Users Public API: Update secret when resetting admin password

---

pkg/catalogv2/git/git.go
pkg/catalogv2/http/client.go
pkg/catalogv2/oci/client.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Issue : https://github.com/rancher/rancher/issues/49109
- This is required since some version control implementations such as Azure DevOps repos implement checking of useragent to see if it starts with "git/" or not ?
- If we don't follow the format of `git/` for `user-agent` header, Azure will redirect to interactive URL login and disregard the PAT token we provided through env variable.

[v2.12.1] Slightly change the formatting of user agent

---

pkg/catalogv2/git/git.go
pkg/catalogv2/http/client.go
pkg/catalogv2/oci/client.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Issue : https://github.com/rancher/rancher/issues/51385
- This is required since some version control implementations such as Azure DevOps repos implement checking of useragent to see if it starts with "git/" or not ?
- If we don't follow the format of `git/` for `user-agent` header, Azure will redirect to interactive URL login and disregard the PAT token we provided through env variable.

Slightly change the formatting of user agent

---

go.mod
go.sum

Bump steve to v0.7.4 to move default sorting from `namespace+name` to `id`

---

build.yaml
pkg/apis/telemetry.cattle.io/v1/types.go
pkg/buildconfig/constants.go
pkg/scc/deployer/params/params.go
pkg/scc/scc.go
pkg/telemetry/controllers/secretrequest/secretrequest.go
pkg/telemetry/exporter.go

Bug fixes include:
- Updating related condition when SyncNow used
- Remove Failure condition on `SecretRequest` when it works successfully (if failure set)
- remove redundant logic check

[release/v2.12] Bump scc-operator to tag & minor bug fixes

---

pkg/catalogv2/content/content.go
pkg/catalogv2/content/content_test.go
pkg/settings/setting.go

This aims at keeping the default behavior for head builds as is today, while adding a setting to skip the filtering of the helm index

Add setting to filter helm versions in head builds

---

pkg/data/management/kontainerdriver_data.go

Checksum was `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`, which is a sha256sum of zero bytes.

[2.11] fix lke checksum

---

pkg/data/management/kontainerdriver_data.go

Checksum was `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`, which is a sha256sum of zero bytes.

[2.12] fix lke checksum

---

build.yaml
pkg/buildconfig/constants.go

It needs to be bumped anyway, but bumping because the RC no longer exist in charts due to https://github.com/rancher/charts/pull/6102

Bump remotedialer-proxy charts to 106.0.1+up0.5.0

---

pkg/controllers/management/clusterprovisioner/provisioner.go

Backporting changes from https://github.com/rancher/rancher/pull/51473 
Issue: https://github.com/rancher/rancher/issues/51487

[v2.12] fix: skip cluster reconciliation if config is unchanged

---

cmd/agent/main.go

The formatting performed for websocket URL is not ipv6 compatible.
Added a check to determine the peer IP belongs to which family, and wrap the IP is [] square brackets if belongs to ipv6.
* Unit
* None
_TODO_
* _TODO_

fix: adding safe validation for ipv6 host

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml
pkg/wrangler/context.go

https://github.com/rancher/rancher/issues/46267
When syncing controller caches in `WaitForCacheSync` it is possible to block in some cases (ex CRD has not served versions) and prevent controllers from starting.
Add timeout to the `context.Context` which defaults to `5m`, but can be changed by the `CACHE_SYNC_TIMEOUT` evnvar to prevent blocking all controllers indefinitely.
Created CRD with no served versions and observed rancher warn of unsycnhed caches with information about no served versions.
* Unit
* None …

[main] Cachesync timeout

---

Makefile
dev-scripts/quick
package/Dockerfile

**Backport**
Backport of https://github.com/rancher/rancher/pull/51098
You can make changes to this PR with the following command:
```
git clone https://github.com/rancher/rancher
cd rancher
git switch backport-51098-release-v2.12-17663
```
---
We'll be able to build the binary like `make build` by running `make quick-binary-server`. It's going to be fast, re-use caches for images and support local Go replace directive.
Currently building Rancher can be done in many ways:
- build the image with `make quick` (or `make quick-server` or `make quick-agent`)
- build the go binary with `make build` (or `make build-server` or `make build-agent`) (uses Dapper)
- running your own go build script
I usually use `make build` because I want to build an image. This works fine and is quick because it …

[release/v2.12] Add `make quick-binary-server` command

---

Makefile
dev-scripts/quick
package/Dockerfile

**Backport**
Backport of https://github.com/rancher/rancher/pull/51098
You can make changes to this PR with the following command:
```
git clone https://github.com/rancher/rancher
cd rancher
git switch backport-51098-release-v2.11-18256
```
---
We'll be able to build the binary like `make build` by running `make quick-binary-server`. It's going to be fast, re-use caches for images and support local Go replace directive.
Currently building Rancher can be done in many ways:
- build the image with `make quick` (or `make quick-server` or `make quick-agent`)
- build the go binary with `make build` (or `make build-server` or `make build-agent`) (uses Dapper)
- running your own go build script
I usually use `make build` because I want to build an image. This works fine and is quick because it …

[release/v2.11] Add `make quick-binary-server` command

---

pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go
pkg/ext/stores/tokens/zz_token_fakes.go

Issue #51364 . This PR is a backport of #49916 for ticket #51332

[backport 2.12] Don't ignore errors when retrieving authentication token ID

---

pkg/settings/setting_test.go

Backport of https://github.com/rancher/rancher/pull/51782

[backport v2.12] drop parallel test quantities

---

pkg/settings/setting_test.go

Backport https://github.com/rancher/rancher/pull/51782

[backport v2.10] Drop Parallel from Settings tests for Quantities

---

pkg/controllers/nodedriver/nodedriver.go
pkg/multiclustermanager/app.go
pkg/rancher/rancher.go
pkg/wrangler/context.go

PR main: https://github.com/rancher/rancher/pull/51582
This is a backport issue for https://github.com/rancher/rancher/issues/47898, automatically created via [GitHub Actions workflow](https://github.com/rancher/rancher/actions/runs/16942184490) initiated by @tomleb
Original issue body:
We hit an issue when starting up Rancher, where the functions executed by the OnLeader handler were not idempotent and caused a panic.
https://github.com/rancher/wrangler/blob/master/pkg/leader/manager.go#L47-L59
Given that we have no guarantees that the handlers are idempotent we should drop the retry mechanism, this would allow error

[backport v2.12] 47898 bug onleaderordie 

---

pkg/settings/setting_test.go

Backport of https://github.com/rancher/rancher/pull/51782

[backport v2.11] drop parallel test quantities

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml
pkg/wrangler/context.go

https://github.com/rancher/rancher/issues/51754
When syncing controller caches in `WaitForCacheSync` it is possible to block in some cases (ex CRD has not served versions) and prevent controllers from starting.
Add timeout to the `context.Context` which defaults to `5m`, but can be changed by the `CACHE_SYNC_TIMEOUT` evnvar to prevent blocking all controllers indefinitely.
Created CRD with no served versions and observed rancher warn of unsycnhed caches with information about no served versions.
* Unit
* None …

[release/v2.12] Cachesync timeout

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml
pkg/wrangler/context.go

https://github.com/rancher/rancher/issues/51813
When syncing controller caches in `WaitForCacheSync` it is possible to block in some cases (ex CRD has not served versions) and prevent controllers from starting.
Add timeout to the `context.Context` which defaults to `5m`, but can be changed by the `CACHE_SYNC_TIMEOUT` evnvar to prevent blocking all controllers indefinitely.
Created CRD with no served versions and observed rancher warn of unsycnhed caches with information about no served versions.
* Unit
* None …

[releasev/2.11] Cachesync timeout

---

pkg/ext/stores/tokens/tokens.go
pkg/ext/stores/tokens/tokens_test.go

See issue #51832, this PR is a backport of  #51829 for #51830

[v2.12] Pass through error events when watching ext tokens

---

pkg/ext/certs.go

https://github.com/rancher/rancher/issues/51640
When logging an error in the watcher event the wrong error value is referenced. This results in always logging a `nil` error.
Reference the `event.Object` when logging the error.
* Unit
* None
_TODO_
* _TODO_

report watch event object on err

---

.github/CODEOWNERS

Fixes:
```
Unknown owner on line 2: make sure the team @rancher/observation-backup exists, is publicly visible, and has write access to the repository
chart @rancher/observation-backup
```
Also needs backport to 2.12 and 2.11 probably. EOL branches may not matter as much.

[main] CI: Codeowners fix O&B -> ORBS

---

build.yaml
pkg/buildconfig/constants.go

Per title this PR will unRC the scc-operator - to a yet to be tagged version, awaiting QA validation.
This is an alternative to: https://github.com/rancher/rancher/pull/52079

[release/v2.12] Un-RC the SCC Operator image

---

chart/templates/deployment.yaml
chart/templates/post-delete-hook-job.yaml
chart/templates/pre-upgrade-hook-job.yaml
chart/tests/images_test.yaml
chart/values.yaml
dev-scripts/prepare-chart

https://github.com/rancher/rancher/issues/52108
Rancher chart values not acting as expected with system default registry.
Fix missing chart logic (and follow up in `rancher-prime` too).
N/A
Manual testing with `helm template` commands
Add more helm-unittest to cover this use case.
_TODO_
* _TODO_

[main] Ensure all `r/r` chart images use systemDefaultRegistry value

---

pkg/data/management/role_data.go

"Manage Users" role cannot update password via `PasswordChangeRequest`
Grant "Manage Users" role update secrets in the `cattle-local-user-passwords` namespace. This will allow to change any password for any user. That's the current behavior and it is documented (see danger box [here](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#combining-built-in-globalroles)).

manage-user can't update password for other users

---

chart/templates/NOTES.txt
chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/templates/post-delete-hook-job.yaml
chart/templates/pre-upgrade-hook-job.yaml
chart/values.schema.json
chart/values.yaml
scripts/chart/build

https://github.com/rancher/rancher/issues/52128
Build Error: https://github.com/rancher/rancher/actions/runs/18036563542/job/51328120261#step:6:637
TL;DR: Helm unit tests fail after my fix because we customize the chart to have `docker.io` on the `rancherImage`. After the fix, this causes the image to be incorrect in Helm unit tests that validate overriding the `systemDefaultRegistry`.
```
-registry.company.com/rancher/rancher:v1.0.0-testing
+registry.company.com/docker.io/rancher/rancher:v1.0.0-testing
```
Note: `registry.company.com` is the helm unit test local customization - `docker.io` comes from `rancherImage`.
A logical fix might be changing the build script to match the change made to `rancher/rancher-prime`. Unfortunately, after adjusting the build script to customize …

[main] Follow up to systemDefaultRegistry fixes

---

tests/controllers/oidc/oidc_provider_test.go

Backport of https://github.com/rancher/rancher/pull/52141
This test keeps failing for me on my steve bump PR here: https://github.com/rancher/rancher/actions/runs/18105171812/job/51528059145?pr=52135:
```
=== RUN   TestOIDCProviderSuite/TestOIDCAuthorizationCodeFlow
I0929 19:34:49.078877   33553 warnings.go:110] "Warning: unknown field \"userPrincipal.metadata\""
oidc_provider_test.go:242: 
Error Trace:	/home/runner/work/rancher/rancher/tests/controllers/oidc/oidc_provider_test.go:242
/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.5.linux-amd64/src/runtime/asm_amd64.s:1700
Error:      	Received unexpected error:
resource name may not be empty
Test:       	TestOIDCProviderSuite/TestOIDCAuthorizationCodeFlow
time="2025-09-29T19:34:50Z" level=info msg="Shutting down …
```

[release/v2.12] Fix OIDC test failures

---

.github/workflows/updatecli.yml

Had to increase the timeout due to the amount of Go dependencies being updated. As we add more workflows, will make sure to check what we can parallelize and then reduce it again if needed.

Increase updatecli workflow timeout

---

updatecli/updatecli.d/update-k8s-k3s/autodiscovery-k8s-deps.yaml
updatecli/updatecli.d/update-k8s-k3s/update-kubectl.yaml

In https://github.com/rancher/rancher/pull/52175 I forgot to:
1. To include `k8s.io/client-go` in the K8s dependency bumps, because it follows the same `v0.<minor>.<patch>` versioning scheme.
2. To bump `KUBECTL_VERSION` in multiple files.
Please see https://github.com/macedogm/fork-rancher/pull/78 for an example PR.

updatecli: bump `k8s.io/client-go` and `KUBECTL_VERSION` 

---

.github/workflows/updatecli.yml
updatecli/updatecli.d/update-wins-system-agent/update-wins-system-agent.yaml
updatecli/values.d/values.yaml

This PR does:
1. Add a updatecli workflow to bump Wins and System Agent versions. An example PR is https://github.com/macedogm/fork-rancher/pull/81.
2. Temporarily disable the workflow that bumps K8s and K3s. Will re-enable once Rancher moves to K8s 1.34.

updatecli: Add workflow to bump Wins and System Agent

---

pkg/controllers/management/auth/roletemplates/roletemplate_handler.go
pkg/controllers/management/auth/roletemplates/roletemplate_handler_test.go
pkg/controllers/managementuser/rbac/roletemplates/roletemplate_handler.go
pkg/rbac/common.go
pkg/rbac/common_test.go

When a RoleTemplate has management plane rules, 2 special ClusterRoles are created in the management cluster to provide those special rules. The problem is that if you then edit the RoleTemplate to not have those management plane rules, the ClusterRoles were not getting deleted. That left users still bound to them.
Similar to other aggregation controllers, we instead do a check for existing ClusterRoles and remove any that aren't in the list of desired ClusterRoles. 
I tested this by making Project RoleTemplates and Cluster RoleTemplates with management plane rules and then editing the rules.
- Removing the management plane rules removes the permissions
- Adding the rules back re-adds the permissions
- Works with inheritance as well, tried with parent and child RoleTemplates
* Test types …

[RoleTemplate Aggregation] Add a mechanism for removing management plane cluster roles when they shouldn't exist

---

pkg/controllers/managementuser/cavalidator/cavalidator.go
pkg/controllers/managementuser/controllers.go
pkg/types/config/context.go

Follow-up of #51375 
`UserContext` was polluted to include fields only needed for the `cavalidator` controller. This wan ad-hoc solution for a problem, but should reworked for a cleaner implementation.
Add a new method to register non-default controller factories, then start them together with the rest of controllers.
Then, move the creation and configuration of the dedicated cache factory to the downstream controller implementation and make it use the new registration interface.

Remove caValidatorDedicatedCache from UserOnlyContext
