rancher/rancher

go.mod
go.sum
tests/v2/integration/setup/main.go

[v2.9] Updated the shepherd version to fix integration test setup.

---

.github/workflows/push-release.yml
package/Dockerfile.agent

aws uploads were failing due to a missing flag
add the recursive flag to aws storage cp
* Unit
* None
_TODO_
* _TODO_

[v2.7.15] fix aws upload

---

package/Dockerfile

Update ui settings - v2.8.6-rc1

Update ui settings - v2.8.6-rc1

---

package/Dockerfile.agent

[v2.9] fix agent args

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Changing TestInstallChartLatestVersion to use `charts-small-fork` instead of `rancher/charts` to not rely on actual production charts

changing rancher-repo for TestInstallChartLatestVersion

---

Dockerfile.dapper
dev-scripts/build-local.sh
package/Dockerfile
pkg/settings/setting.go
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

KDM for v2.7.15 is released, updating the branch

[v2.7.15] Update kdm to release-v2.7 branch 

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/46316

[v2.9] update machine to v0.15.0-rancher114

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/system-agent/releases/tag/v0.3.7

[release/v2.8] Bump rancher/system-agent to v0.3.7

---

package/Dockerfile

Bump UI to v2.9.0-rc4

---

package/Dockerfile

Bump UI to v2.8.6-rc2

---

go.mod
go.sum
tests/v2/integration/steveapi/steve_api_test.go

There is a bit of flakiness in the integration setup, due to how slow the cluster is in loading the Steve API schema. This PR updates the shepherd version that address that issue.
Update Shepherd version to address flakiness when loading the Steve API schema. 
* Unit
* None
_TODO_
* _TODO_

[v2.9] Updated shepherd version to address the flakiness on integration setup.

---

package/Dockerfile

Bump ui to v2.8.6-rc3

---

package/Dockerfile

Bump ui to v2.9.0-rc5

---

go.mod
go.sum

Bumps dynamic listener to a non-rc tag for the release.

Bump dynamic listener to v0.6.0

---

package/Dockerfile

Bump UI to v2.8.6

---

package/Dockerfile

Bump ui to v2.9.0

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml

* forwardport for `v2.7` stage registry changes
* Unit
* None
_TODO_
* _TODO_

[v2.8] staging registry

---

.github/actions/k3s-images/action.yml

k3s-airgap-images.tar would never contain anything
remove the empty k3s-airgap-images condition
* Unit
* None
_TODO_
* _TODO_

[v2.7.15] fix k3s airgap images

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/46090

Bump rancher/system-agent to v0.3.8-rc1

---

go.mod
go.sum
tests/v2/actions/projects/projects.go
tests/v2/actions/rbac/rbac.go
tests/v2/actions/secrets/secrets.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_test.go
tests/v2/validation/projects/rbac_terminating_project_test.go
tests/v2/validation/rbac/secrets/README.md
tests/v2/validation/rbac/secrets/rbac_secrets_test.go

**Issue**: https://github.com/rancher/qa-tasks/issues/1341
**Note**: 2.8 Backport PR will be created once this gets approved

RBAC Secret test cases

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/46400

[2.10] Bump rancher/system-agent to v0.3.8-rc1

---

pkg/controllers/management/k3sbasedupgrade/deployPlans.go
pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go

Issue: https://github.com/rancher/rancher/issues/46444
cherry-pick of https://github.com/rancher/rancher/pull/46149

[2.10] improve the logging for k3s-based-upgrader for imported rke2/k3s cluster

---

go.mod
go.sum
tests/v2/actions/projects/projects.go
tests/v2/actions/rbac/rbac.go
tests/v2/actions/secrets/secrets.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_test.go
tests/v2/validation/projects/rbac_terminating_project_test.go
tests/v2/validation/rbac/secrets/README.md
tests/v2/validation/rbac/secrets/rbac_secrets_test.go

Forwardport https://github.com/rancher/rancher/pull/45601/

[main] RBAC secret test cases

---

chart/templates/ingress.yaml
chart/values.yaml

Related to issue [#44780](https://github.com/rancher/rancher/issues/44780)

Forwardport solution from PR 42014

---

pkg/auth/api/user/user_actions.go

Forward port of https://github.com/rancher/rancher/pull/46177

[v2.10] Prevent set password of external users

---

tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/hosted/aks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/eks/hosted_provisioning_test.go
tests/v2/validation/provisioning/hosted/gke/hosted_provisioning_test.go
tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/permutations/permutations.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/template_test.go

https://github.com/rancher/qa-tasks/issues/1011

[main] Implemented time out report to log cluster status and condition information to the provisioning tests

---

package/Dockerfile

Bump UI to `v2.9.1-alpha1`

---

pkg/controllers/management/auth/manager.go
pkg/controllers/managementuser/rbac/handler_base.go
tests/integration/suite/test_role_template.py

issue https://github.com/rancher/rancher/issues/45518
backport https://github.com/rancher/rancher/pull/45951

Fix RoleTemplate nonstop syncing (#45951)

---

.github/workflows/promote-docker-image.yml

Since drone was decommissioned, there wasn't a way to promote images
Adds a promote docker image workflow
* Unit
* None
_TODO_
* _TODO_

[v2.9] Add promote docker image workflow

---

.github/workflows/promote-docker-image.yml

backport of https://github.com/rancher/rancher/pull/46543
* Unit
* None
_TODO_
* _TODO_

[v2.8] backport promote docker image

---

.github/workflows/promote-docker-image.yml

Forward port for: https://github.com/rancher/rancher/pull/46543
* Unit
* None
_TODO_
* _TODO_

[main] Add promote docker image workflow

---

pkg/controllers/management/auth/user_attribute_handler.go
pkg/controllers/management/auth/user_attribute_handler_test.go

Forwardport of #46373
* Unit
N/A
N/A

Additional tests for userattribute handler

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadDeployment test
v2.9 https://github.com/rancher/rancher/pull/46387
v2.7 https://github.com/rancher/rancher/pull/46393
v2.8 https://github.com/rancher/rancher/pull/46392
https://github.com/rancher/qa-tasks/issues/1441

<main> Convert test_wl_deployment test to go

---

pkg/controllers/management/usercontrollers/controller.go

This is a cherry picked forward port of https://github.com/rancher/rancher/pull/46335

[main] Use system default registry when running cattle-cleanup job

---

package/Dockerfile
package/Dockerfile.agent

Add 2 packages related to OpenSSL and FIPS that were missed during the transition to BCI Micro. These packages are required for running Rancher under FIPS.
* Unit
* None
_TODO_
* _TODO_

Add packages required for FIPS

---

package/Dockerfile
package/Dockerfile.agent

Backport https://github.com/rancher/rancher/pull/46571
Add 2 packages related to OpenSSL and FIPS that were missed during the transition to BCI Micro. These packages are required for running Rancher under FIPS.
* Unit
* None
_TODO_
* _TODO_

[v2.9] Add packages required for FIPS

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/46530
https://github.com/rancher/rancher/issues/46532

[main] bump rancher/system-agent to v0.3.8-rc.2

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/46531
https://github.com/rancher/rancher/issues/46529

[2.8] bump rancher/system-agent to v0.3.8-rc.2

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/46526
https://github.com/rancher/rancher/issues/46527

[2.9] bump rancher/system-agent to v0.3.8-rc.2

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Migrated test_wl_deployment test to TestWorkloadDeployment

<2.9> Convert test_wl_deployment test to go

---

pkg/data/management/machinedriver_data.go

Create new cluster using RKE2 and phoenixNAP node driver.
Verify cluster is up and active.

phoenixNAP node driver update

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

Backport of #46594
N/A
N/A
N/A

[v2.9] Update kube-api-auth to v0.2.2

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

https://github.com/rancher/rancher/issues/46334
A new release of kube-api-auth with updated dependencies was tagged.
Use a new release of kube-api-auth.
N/A
N/A
N/A

Update kube-api-auth to v0.2.2

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

[45815] [2.9] bump system agent

---

pkg/auth/cleanup/service.go
pkg/auth/cleanup/service_test.go
tests/controllers/authconfig/authconfig_test.go
tests/controllers/cleanup/delete_tokens_test.go

[v2.10] Tokens cleanup

---

.github/workflows/push-release.yml

Closes: https://github.com/rancher/rancher/issues/46559
The manifest for `v2.9.0` is missing the `os.version` key on windows manifests
Use `docker manifest create` for windows images to preserve that key
* Unit
* None
_TODO_
* _TODO_

[v2.9] fix windows images os.version key

---

tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

Backport of https://github.com/rancher/rancher/pull/46628.

[v2.9] Remove custom cluster PSACT test

---

tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

Backport of https://github.com/rancher/rancher/pull/46628.

[v2.8] Remove custom cluster PSACT test

---

build.yaml
pkg/buildconfig/constants.go

Update webhook version to 105.0.0+up0.6.0-rc.1

---

build.yaml
pkg/buildconfig/constants.go

Bump webhook version to 104.0.1+up0.5.1-rc.1

---

tests/v2/validation/steve/vai/pod_filter_test_cases.go
tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/secret_filter_test_cases.go
tests/v2/validation/steve/vai/secret_limit_test_cases.go
tests/v2/validation/steve/vai/secret_sort_test_cases.go
tests/v2/validation/steve/vai/vai.go
tests/v2/validation/steve/vai/vai_test.go

Adding in test cases to test Steve with Vai first disabled, then enabled. In addition to testing the results from Steve, also check within the cache database as well.
Added in validation tests to test with Steve, disabled, enabled and to also check the databases.

vai disabled/enabled tests

---

build.yaml
pkg/buildconfig/constants.go

Bump webhook version to 103.0.9+up0.4.10-rc.1

---

.github/actions/setup-build-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

backport: https://github.com/rancher/rancher/pull/46568
* Unit
* None
_TODO_
* _TODO_

[main] backport setup-build-env

---

tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

Backport of https://github.com/rancher/rancher/pull/46628.

[v2.7] Remove custom cluster PSACT test

---

.github/actions/setup-build-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

Backport: https://github.com/rancher/rancher/pull/46568
* Unit
* None
_TODO_
* _TODO_

[v2.8] backport setup build env

---

.github/workflows/push-release.yml

https://github.com/rancher/rancher/pull/46619 accidentally included an additional trailing `\` when generating the agent manifest, which causes the build to fail https://github.com/rancher/rancher/actions/runs/10325635462/job/28637316878
Remove the trailing slash when creating the agent manifest using `buildx`
* Unit
* None
_TODO_
* _TODO_

[v2.9] Remove trailing `\` when creating agent manifests

---

.github/workflows/push-release.yml

backport: #46619 
* Unit
* None
_TODO_
* _TODO_

[main] backport fix windows images os.version key

---

.github/workflows/push-release.yml

backport: #46619 
* Unit
* None
_TODO_
* _TODO_

[v2.8] backport windows os version

---

.github/actions/setup-tag-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

* the main branch isn't building head images
* update the workflow files to build the head images
* Unit
* None
_TODO_
* _TODO_

[main] enable head images

---

.github/workflows/push-release.yml

* the main branch is not producing head images due to a missing check
* add the main branch check to head images steps
* Unit
* None
_TODO_
* _TODO_

add main check to head manifest

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

https://github.com/rancher/rancher/issues/46681

[v2.9] update kdm branch to dev-v2.9

---

.github/workflows/integration-tests.yml

There is an issue where importing the k3d cluster times and fails due to disk usage. The high disk usage is interpreted as node pressure and therefore the import fails.
Clean unused docker images, as well as us the EIO hosted runner. 
* Unit
* None
_TODO_
* _TODO_

Additional clean up steps.

---

.github/workflows/integration-tests.yml

There is an issue where importing the k3d cluster times and fails due to disk usage. The high disk usage is interpreted as node pressure and therefore the import fails.
Clean unused docker images, as well as us the EIO hosted runner. 
* Unit
* None
_TODO_
* _TODO_

[v2.9] Additional clean up steps. Used hosted github runner.

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

- Implemented TestWorkloadSideKick test
https://github.com/rancher/qa-tasks/issues/1433
Backports:
https://github.com/rancher/rancher/pull/46353
https://github.com/rancher/rancher/pull/46359
https://github.com/rancher/rancher/pull/46360

<main> Convert test_wl_sidekick test to go

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

- Implemented TestWorkloadSideKick test
https://github.com/rancher/qa-tasks/issues/1433

<2.8> Convert test_wl_sidekick test to go

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

- Created workload_test.go and workload.go files on connection package
https://github.com/rancher/qa-tasks/issues/1433

<2.9> Convert test_wl_sidekick test to go

---

package/Dockerfile

Bump CATTLE_DASHBOARD_UI_VERSION & CATTLE_UI_VERSION to v2.9.1-rc3
- https://github.com/rancher/dashboard/actions/runs/10394268999
- https://github.com/rancher/ui/actions/runs/10394275690

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.9.1-rc3

---

tests/v2/actions/workloads/deamonset/deamonset.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadDaemonSet

<v2.9> Convert test_wl_deamonset test to go

---

tests/v2/actions/workloads/deamonset/deamonset.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadDaemonSet test

<2.8> Convert test_wl_deamonset test to go

---

tests/v2/actions/workloads/deamonset/deamonset.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadDaemonSet
Backport
v2.9 https://github.com/rancher/rancher/pull/46596
v2.8 https://github.com/rancher/rancher/pull/46590
v2.7 https://github.com/rancher/rancher/pull/46587

<main> Convert test_wl_deamonset test to go

---

Dockerfile.dapper
package/Dockerfile
pkg/image/utilities/utilities.go
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

https://github.com/rancher/rancher/issues/46700

update kdm branch to dev-v2.10 and include -main in rancher dev versions

---

.github/workflows/push-release.yml

[v2.8] fix merge manifest

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.9.1-rc4
- https://github.com/rancher/dashboard/actions/runs/10422521935
- https://github.com/rancher/ui/actions/runs/10422522362

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.9.1-rc4

---

build.yaml
pkg/buildconfig/constants.go

This includes the following webhook PRs:
https://github.com/rancher/webhook/pull/475
https://github.com/rancher/webhook/pull/482

[v2.9] Un-rc webhook v0.5.1

---

dev-scripts/quick

Port of https://github.com/rancher/rancher/pull/46732
This is a straight cherry-pick

[2.8] dev-scripts/quick: align retrieval of variables to changes in #46568

---

dev-scripts/quick

Port of https://github.com/rancher/rancher/pull/46732
This is a straight cherry-pick

[main] dev-scripts/quick: align retrieval of variables to changes in #46568

---

tests/v2/validation/Dockerfile.validation

Our Dockerfile.validation didn't have the proper Golang version
Update the version to 1.22
* Unit
* None
_TODO_
* _TODO_

[v2.8] Updated Golang dependency in test validation Dockerfile

---

scripts/chart/index
scripts/chart/package

* The dev helm index was skipped
* The helm index URL was outdated
* Remove the dev index skip
* Update the helm index URL
* Unit
* None
_TODO_
* _TODO_

[v2.8] update helm index URL

---

scripts/chart/index
scripts/chart/package

Backport: https://github.com/rancher/rancher/pull/46753
* Unit
* None
_TODO_
* _TODO_

[v2.7] update helm index URL

---

.github/workflows/push-release.yml

Release notes were always empty
Add the content of `rancher-components.txt` to the release notes
* Unit
* None
_TODO_
* _TODO_

[main] add release notes step

---

.github/workflows/push-release.yml

Backport: https://github.com/rancher/rancher/pull/46755
* Unit
* None
_TODO_
* _TODO_

[v2.9] add release notes step

---

.github/actions/setup-tag-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml

* Using the `-main` suffix is causing issues with image tag validations
* Update the head images suffix to `-head` to maintain consistency with other versions
* Unit
* None
_TODO_
* _TODO_

[main] update head images suffix to `-head` instead of `-main`

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Need to git repo for failing test
Change to  github.com/rancher
* Unit
* None
_TODO_
* _TODO_

[v2.9] Changing from git.rancher.io to github.com/rancher in test

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Need to git repo for failing test
Change to  github.com/rancher
* Unit
* None
_TODO_
* _TODO_

[v2.8] Changing from git.rancher.io to github.com/rancher in test

---

pkg/controllers/dashboard/helm/repo.go
pkg/controllers/dashboard/helm/repo_test.go

[2.8 backport] Increasing the sync interval from 5 min to 6 hours

---

pkg/controllers/dashboard/helm/repo.go
pkg/controllers/dashboard/helm/repo_test.go

[2.7 backport] Increasing the sync interval from 5 min to 6 hours

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7
- https://github.com/rancher/dashboard/actions/runs/10513363044
- https://github.com/rancher/ui/actions/runs/10513363803

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.8.7

---

package/Dockerfile

Bump `CATTLE_DASHBOARD_UI_VERSION` & `CATTLE_UI_VERSION` to v2.9.1
- https://github.com/rancher/dashboard/actions/runs/10515649473
- https://github.com/rancher/ui/actions/runs/10515670955

Bump CATTLE_DASHBOARD_UI_VERSION & CATTLE_UI_VERSION to v2.9.1

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[2.9] bump rke to v1.6.1

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[2.8] bump rke to v1.5.12

---

tests/v2/actions/workloads/cronjob/cronjob.go
tests/v2/actions/workloads/deamonset/deamonset.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/actions/workloads/statefulset/statefulset.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadCronjob test
Implemented TestWorkloadStatefulset test
Backports
[v2.9 ](https://github.com/rancher/rancher/pull/46717)
[v2.8](https://github.com/rancher/rancher/pull/46716)
[v2.7](https://github.com/rancher/rancher/pull/46725)

<main> Convert test_wl_cronjob and test_wl_statefulset test to go

---

pkg/auth/providerrefresh/daemon.go
pkg/auth/providers/azure/azure_provider.go
pkg/controllers/management/auth/indexes.go
pkg/controllers/management/auth/indexes_test.go
pkg/controllers/management/auth/legacy_grb_cleaner.go
pkg/controllers/management/auth/legacy_grb_cleaner_test.go
pkg/controllers/management/auth/legacy_rt_cleaner.go
pkg/controllers/management/auth/legacy_rt_cleaner_test.go
pkg/controllers/management/auth/setting.go
pkg/controllers/management/auth/setting_test.go

The `pkg/controllers/management/auth` was poor of tests.
Adding more comments to the functions, refactoring them by splitting the code and adding more tests to these fresh new functions we can now have more coverage into this package and be less prone to regressions.
I worked on the following files by improving their coverage as follow:
* https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/setting.go (from 40% to 53%)
* https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/legacy_rt_cleaner.go (form 0% to 70%)
* https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/legacy_grb_cleaner.go (from 0% to 50%)
* https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/indexes …

add unit tests to the auth package

---

pkg/auth/providerrefresh/daemon.go
pkg/auth/providers/azure/azure_provider.go
pkg/controllers/management/auth/indexes.go
pkg/controllers/management/auth/indexes_test.go
pkg/controllers/management/auth/legacy_grb_cleaner.go
pkg/controllers/management/auth/legacy_grb_cleaner_test.go
pkg/controllers/management/auth/legacy_rt_cleaner.go
pkg/controllers/management/auth/legacy_rt_cleaner_test.go
pkg/controllers/management/auth/setting.go
pkg/controllers/management/auth/setting_test.go

* add unit tests to the auth package
Porting of unit-tests form `release/v2.9` to `main` branch.
Original PR here: https://github.com/rancher/rancher/pull/46191

add unit tests to the auth package (#46191)

---

README.md

This aims to solve: https://github.com/rancher/rancher/issues/46799

[main] Fix broken link "security policy"

---

README.md

Backport from https://github.com/rancher/rancher/pull/46815

[2.8] Fix broken link "security policy"

---

README.md

Backport from https://github.com/rancher/rancher/pull/46815

[2.7] Fix broken link "security policy"

---

pkg/auth/requests/authenticate.go
pkg/auth/requests/authenticate_test.go
pkg/auth/requests/service_account_test.go

Backport of #46394
* Unit
N/A
N/A

[v2.9] Check if the provider is enabled when authenticating

---

pkg/auth/providers/common/provider.go
pkg/auth/providers/saml/saml_provider.go
pkg/auth/providers/saml/saml_provider_test.go

Backport of #46657 and #46685
Original issue https://github.com/rancher/rancher/issues/44441
* Unit
N/A
N/A

[v2.9] SAML provider SearchPrincipals fixes

---

scripts/version

Backport: https://github.com/rancher/rancher/pull/46863 
* Unit
* None
_TODO_
* _TODO_

[v2.8] backport add hotfix to latest helm repo

---

scripts/chart/package
scripts/version

Backport: https://github.com/rancher/rancher/pull/46863
* Unit
* None
_TODO_
* _TODO_

[v2.9] backport add hotfix to latest helm repo

---

scripts/chart/package
scripts/version

Hotfix tags would be added to the dev repo that doesn't have an index and that would cause them to not be usable
Add hotfix tags to the latest repo and don't skip the index step for the dev repo for testing future non-standard releases
* Unit
* None
_TODO_
* _TODO_

Add hotfix tags to the latest helm repo

---

tests/v2/actions/workloads/cronjob/cronjob.go
tests/v2/actions/workloads/deamonset/deamonset.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/actions/workloads/statefulset/statefulset.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadDeployment test
Implemented TestWorkloadSideKick test
Implemented TestWorkloadDaemonSet test
Implemented TestWorkloadCronjob test
Implemented TestWorkloadStatefulset test

<v2.7> Convert deployment, statefulset, deamonset and cronjob validations test_wl tests to go

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

[2.8] update kdm branch to dev-v2.8

[2.8] update kdm branch to dev-v2.8

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

[2.9] update kdm branch to dev-v2.9

[2.9] update kdm branch to dev-v2.9

---

pkg/settings/setting.go

The `telemetry-uid` setting is used by https://github.com/rancher/telemetry but is not known to Rancher, and is removed on startup since v2.9.
Make the setting known to Rancher.
N/A
N/A

Add telemetry-uid setting

---

go.mod
go.sum
tests/v2/actions/charts/rke2template.go
tests/v2/actions/provisioning/creates.go
tests/v2/actions/provisioning/providers.go
tests/v2/actions/rke1/nodetemplates/aws/create.go
tests/v2/actions/rke1/nodetemplates/azure/create.go
tests/v2/actions/rke1/nodetemplates/harvester/create.go
tests/v2/actions/rke1/nodetemplates/linode/create.go
tests/v2/actions/rke1/nodetemplates/vsphere/create.go
tests/v2/validation/provisioning/k3s/template_test.go
tests/v2/validation/provisioning/rke2/template_test.go

Backport of https://github.com/rancher/rancher/pull/46604

[2.9] Credentials update

---

go.mod
go.sum
tests/v2/actions/charts/rke2template.go
tests/v2/actions/provisioning/creates.go
tests/v2/actions/provisioning/providers.go
tests/v2/actions/rke1/nodetemplates/aws/create.go
tests/v2/actions/rke1/nodetemplates/azure/create.go
tests/v2/actions/rke1/nodetemplates/harvester/create.go
tests/v2/actions/rke1/nodetemplates/linode/create.go
tests/v2/actions/rke1/nodetemplates/vsphere/create.go
tests/v2/validation/provisioning/k3s/template_test.go
tests/v2/validation/provisioning/rke2/template_test.go

Backport of https://github.com/rancher/rancher/pull/46604

[2.8] Credentials update

---

go.mod
go.sum
tests/v2/actions/charts/rke2template.go
tests/v2/actions/provisioning/creates.go
tests/v2/actions/provisioning/providers.go
tests/v2/actions/rke1/nodetemplates/aws/create.go
tests/v2/actions/rke1/nodetemplates/azure/create.go
tests/v2/actions/rke1/nodetemplates/harvester/create.go
tests/v2/actions/rke1/nodetemplates/linode/create.go
tests/v2/actions/rke1/nodetemplates/vsphere/create.go
tests/v2/validation/provisioning/k3s/template_test.go
tests/v2/validation/provisioning/rke2/template_test.go

Backport of https://github.com/rancher/rancher/pull/46604

[2.7] Credentials update

---

pkg/agent/cluster/cluster.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/controllers/management/aks/aks_cluster_handler.go
pkg/controllers/management/clusteroperator/utils.go
pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/gke/gke_cluster_handler.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/aks/aks_driver.go
pkg/kontainer-engine/drivers/eks/eks_driver.go
pkg/kontainer-engine/drivers/import/import_driver.go
pkg/kontainer-engine/drivers/rke/rke_driver.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

We are generating too many secrets for accessing the downstream cluster, because we are doing this concurrently.
This adds a mutex per service-account, which will _reduce_ the number of secrets created, but not totally eliminate the problem.
* Unit
* None
_TODO_
* _TODO_

Re sync fix

---

pkg/image/origins.go

New image was added for fluentd: https://github.com/rancher/image-mirror/pull/706
* Unit
* None
_TODO_
* _TODO_

[release/v2.9] Add new image source for fluentd

---

pkg/image/origins.go

New image was added for fluentd: https://github.com/rancher/image-mirror/pull/706
* Unit
* None
_TODO_
* _TODO_

[main] Add new image source for fluentd

---

README-template.md
README.md

* Drone was deactivated and the build status badge was broken
* v2.9.1 was missing from the versions
* The update readme action is broken, it needs to be updated (not included in this PR)
* Remove the drone badge
* Add v2.9.1 and remove v2.6
* Unit
* None
_TODO_
* _TODO_

remove drone build status and update versions

---

tests/v2/actions/workloads/cronjob/cronjob.go
tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/actions/workloads/statefulset/statefulset.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadCronjob test
Implemented TestWorkloadStatefulset test

<v2.8> Convert test_wl_cronjob and test_wl_statefulset test to go

---

tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadUpgrade test
Backports
v2.7 https://github.com/rancher/rancher/pull/46875
v2.8 https://github.com/rancher/rancher/pull/46910
v2.9 https://github.com/rancher/rancher/pull/46911

<main> Convert test_wl_upgrade to go

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/agent_customization_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

backport of: https://github.com/rancher/rancher/pull/46759

[2.9] update provisioning to run all minor versions by default

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/agent_customization_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

backport of: https://github.com/rancher/rancher/pull/46759

[2.8] update provisioning to run all minor versions by default

---

go.mod
go.sum
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/registries/registry_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/agent_customization_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

backport of: https://github.com/rancher/rancher/pull/46759

[2.7] update provisioning to run all minor versions by default

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/46098

[main] Bump rancher/system-agent to v0.3.9-rc.2

---

pkg/auth/providerrefresh/daemon.go
pkg/auth/providers/azure/azure_provider.go
pkg/controllers/management/auth/setting.go
pkg/controllers/management/auth/setting_test.go

The recent changes in packages pkg/auth/providers/azure and pkg/auth/providerrefresh/ introduced the bug linked above.
Revert the changes to restore the previous behavior.

fix: restore previous logic on providers/azure and providerrefresh pkg

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

[46623] [2.8] Bump system-agent to v0.3.9-rc.4

---

pkg/controllers/dashboard/helm/repo.go

Changing the refresh interval to 1h to match with other Rancher releases

changing clusterrepo interval to 1h

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadUpgrade test

<v2.9> Convert test_wl_upgrade to go

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadUpgrade test

<v2.8> Convert test_wl_upgrade to go

---

tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Implemented TestWorkloadUpgrade test

<2.7> Convert test_wl_upgrade to go

---

tests/v2/actions/hardening/k3s/audit.yaml
tests/v2/actions/hardening/k3s/harden_nodes.go
tests/v2/actions/hardening/rke1/account-update.sh
tests/v2/actions/hardening/rke1/account-update.yaml
tests/v2/actions/hardening/rke1/harden_nodes.go
tests/v2/actions/hardening/rke2/account-update.sh
tests/v2/actions/hardening/rke2/account-update.yaml
tests/v2/actions/hardening/rke2/harden_nodes.go

Backport of https://github.com/rancher/rancher/pull/46977.

[v2.9] Update hardening action to include YAML and bash scripts

---

tests/v2/actions/hardening/k3s/audit.yaml
tests/v2/actions/hardening/k3s/harden_nodes.go
tests/v2/actions/hardening/rke1/account-update.sh
tests/v2/actions/hardening/rke1/account-update.yaml
tests/v2/actions/hardening/rke1/harden_nodes.go
tests/v2/actions/hardening/rke2/account-update.sh
tests/v2/actions/hardening/rke2/account-update.yaml
tests/v2/actions/hardening/rke2/harden_nodes.go

Backport of https://github.com/rancher/rancher/pull/46977.

[v2.8] Update hardening action to include YAML and bash scripts

---

tests/v2/actions/hardening/k3s/audit.yaml
tests/v2/actions/hardening/k3s/harden_nodes.go
tests/v2/actions/hardening/rke1/account-update.sh
tests/v2/actions/hardening/rke1/account-update.yaml
tests/v2/actions/hardening/rke1/harden_nodes.go
tests/v2/actions/hardening/rke2/account-update.sh
tests/v2/actions/hardening/rke2/account-update.yaml
tests/v2/actions/hardening/rke2/harden_nodes.go

Backport of https://github.com/rancher/rancher/pull/46977.

[v2.7] Update hardening action to include YAML and bash scripts

---

pkg/controllers/provisioningv2/controllers.go
pkg/controllers/provisioningv2/machineconfigcleanup/controller.go

Issue: 
https://github.com/rancher/rancher/issues/46469 
Backport PR for https://github.com/rancher/rancher/pull/46710

[v2.9] cleanup orphaned rke-machine-configs

---

.github/workflows/push-release.yml

After publishing the charts, it takes some time to refresh the cache and this causes other CI jobs to fail
Invalidate the cloudfront cache
* Unit
* None
_TODO_
* _TODO_

[v2.8] add invalidate cloudfront charts cache

---

tests/v2/validation/rbac/snapshotrbac/snapshot_rbac_test.go

[QA Task #1435](https://github.com/rancher/qa-tasks/issues/1435)
Previously `snapshot_rbac_test` only ran against rke2/k3s clusters.
This PR adds tests that can be run against rke1 clusters.

Adding rke1 compatibility to rbac etcdsnapshot test

---

tests/v2/validation/rbac/snapshotrbac/snapshot_rbac_test.go

Backport [#46343](https://github.com/rancher/rancher/pull/46343)

[2.8] Adding rke1 compatibility to rbac etcdsnapshot test

---

tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_test.go

Forward port **https://github.com/rancher/rancher/pull/45006**

[main] P0 tests for GH39700

---

tests/v2/validation/v2prov/encryption_key_rotation_test.go

Forward port of https://github.com/rancher/rancher/pull/46932

[Main]Updating secret encryption for vai enabled

---

tests/v2/validation/rbac/rbac_test.go
tests/v2/validation/workloads/workload_test.go

Added logs to get information about clusterID

<v2.9> Fix Missing Cluster ID Qase test

---

tests/v2/validation/rbac/rbac_test.go
tests/v2/validation/workloads/workload_test.go

Added logs to get information about clusterID

<v2.8> Fix Missing Cluster ID Qase test

---

tests/v2/validation/rbac/rbac_test.go
tests/v2/validation/workloads/workload_test.go

Added logs to get information about clusterID

<v2.7> Fix Missing Cluster ID Qase test

---

build.yaml
pkg/buildconfig/constants.go

Bump rancher-webhook to 103.0.10+up0.4.11-rc.1

[v2.8] Bump rancher-webhook to 103.0.10+up0.4.11-rc.1

---

tests/v2/validation/projects/rbac_terminating_project_test.go

Backport [#43670](https://github.com/rancher/rancher/pull/43670)

[v2.8] P0 tests for terminating project

---

go.mod
go.sum

CRTB Create returns wrong response code
Fixed response code in steve and added tests to the Create function
Reproduction steps can be found at the issue link
* Unit
* None
_TODO_
* _TODO_

[Release v2.9] Fix/42788

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

* Bump RKE to `v1.5.13-rc.2`
* go generate

[v2.8] Bump RKE to `v1.5.13-rc.2`

---

go.mod
go.sum
tests/v2/actions/fleet/fleet.go
tests/v2/validation/fleet/public_repo_test.go

port of https://github.com/rancher/rancher/pull/46914

[2.7] adding fleet tests in tests/v2/validation

---

go.mod
go.sum
tests/v2/actions/fleet/fleet.go
tests/v2/validation/fleet/public_repo_test.go

port of https://github.com/rancher/rancher/pull/46914

[2.8] adding fleet tests in tests/v2/validation

---

go.mod
go.sum
tests/v2/actions/fleet/fleet.go
tests/v2/validation/fleet/public_repo_test.go

port of https://github.com/rancher/rancher/pull/46914

[2.9] adding fleet tests in tests/v2/validation

---

tests/v2/validation/serviceaccounts/README.md
tests/v2/validation/serviceaccounts/sa_test.go

Forwardport [#46682 ](https://github.com/rancher/rancher/pull/46682)
Jenkins test

Migrating serviceaccounts test from python to go

---

tests/v2/actions/etcdsnapshot/config.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go

Backport of https://github.com/rancher/rancher/pull/47072.

[v2.9] Enhance replace worker nodes to replace all cluster roles

---

tests/v2/actions/etcdsnapshot/config.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go

Backport of https://github.com/rancher/rancher/pull/47072.

[v2.8] Enhance replace worker nodes to replace all cluster roles

---

tests/v2/actions/etcdsnapshot/config.go
tests/v2/validation/snapshot/README.md
tests/v2/validation/snapshot/snapshot.go
tests/v2/validation/snapshot/snapshot_additional_test.go

Backport of https://github.com/rancher/rancher/pull/47072.

[v2.7] Enhance replace worker nodes to replace all cluster roles

---

tests/v2/validation/serviceaccounts/README.md
tests/v2/validation/serviceaccounts/sa_test.go

Backport [#46682](46682)
Jenkins run

[v2.8] Migrating serviceaccounts test from python to go

---

pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/manager_test.go

https://github.com/rancher/rancher/issues/44694
Additional unit testing needed in the RBAC manager
Additional unit tests added.  This change does not refactor any of the code.  There will be a separate issue created for refactoring/additional tests (the refactoring will facilitate the additional tests).
Unit tests
* Unit
No QA necessary
None

Add unit tests to RBAC manager

---

pkg/auth/providers/publicapi/login.go

Backport of #47106
_TODO_
* _TODO_

[v2.9] Avoid panics on login

---

pkg/auth/providers/publicapi/login.go

Log messages try to use a variable that may not be set if `EnsureUser()` call fails.
Use a variable that is set ahead of time instead.
_TODO_
* _TODO_

Avoid panics on login

---

pkg/auth/providers/publicapi/login.go

Backport of #47106
_TODO_
* _TODO_

[v2.8] Avoid panics on login

---

tests/v2/actions/fleet/fleet.go
tests/v2/validation/fleet/README.md
tests/v2/validation/fleet/public_repo_test.go

addresses issues: 
https://github.com/rancher/qa-tasks/issues/1530
https://github.com/rancher/qa-tasks/issues/1521

[QA] fleet dynamic test + fleet windows support

---

README.md

update readme to promote v2.9.2

---

tests/v2/actions/provisioning/creates.go
tests/v2/validation/rbac/README.md
tests/v2/validation/rbac/clusterandprojectroles/restrictedadmin_role_test.go
tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go
tests/v2/validation/rbac/rbac_test.go
tests/v2/validation/workloads/workload_test.go

Backport
v2.9 https://github.com/rancher/rancher/pull/47121
v2.8 https://github.com/rancher/rancher/pull/47150
v2.7 https://github.com/rancher/rancher/pull/47154

<main> Fix Missing Cluster ID Qase test

---

tests/validation/tests/v3_api/test_certificate.py

Backport https://github.com/rancher/rancher/pull/47144
QA Task: https://github.com/rancher/qa-tasks/issues/1545

[2.8] Update certificate issuer in test_certificate

---

.github/workflows/push-release.yml

Updating the helm index with concurrent jobs can lead to race conditions, where one chart might override another.
Merge the build and publish chart steps and add a concurrency group check to the job.
* Unit
* None
_TODO_
* _TODO_

[v2.8] update chart build and publish

---

.github/workflows/push-release.yml

The push-release file fails because it has an inexistent job dependency
Remove the `build-chart` dependency, since it has been renamed
* Unit
* None
_TODO_
* _TODO_

[v2.8] remove build chart dependency from installer build

---

pkg/image/origins.go

Adding NeuVector compliance config

---

pkg/image/origins.go

Adding NeuVector compliance config v2.9

---

.github/workflows/push-release.yml

Follow-up for https://github.com/rancher/rancher/pull/47228
GitHub hosted runners are subject to limits on parallel runs, and jobs sometimes are queued for a long time before being picked up by a runner.
Use self-hosted runners with docker containers
* Unit
* None
_TODO_
* _TODO_

[2.8] self hosted runners for push and tag

---

.github/workflows/push-release.yml

The arch env is missing from the build installer step, which is causing inconsistencies on the docker tag
add the arch env
* Unit
* None
_TODO_
* _TODO_

[v2.8] add arch env

---

.github/actions/setup-build-env/action.yml
.github/workflows/push-release.yml
scripts/create-components-images-files.sh

* Create components images files is failing due to not having go installed
* The k3s images script is outdated
* Install golang using the setup-go action
* Replace the k3s images script with the k3s images action
* Unit
* None
_TODO_
* _TODO_

[v2.8] fix create-components images files

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml
scripts/artifacts-hashes.sh
scripts/create-components-images-files.sh

* unwanted files were being uploaded to the s3 bucket
* improve the upload filters
* remove unused file copy
* Unit
* None
_TODO_
* _TODO_

[2.8] fix create components upload

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/pods/pods.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go

Backport https://github.com/rancher/rancher/pull/46139
Issue: https://github.com/rancher/qa-tasks/issues/1250

[2.8] P0 Project Container Default Resource Limit tests

---

.github/workflows/push-release.yml

* Using `aws s3 cp --recursive` can be problematic and cause issues uploading unwanted files
* define a list of expected artifacts
* Unit
* None
_TODO_
* _TODO_

[v2.8] define artifacts list

---

.github/workflows/push-release.yml
scripts/create-components-images-files.sh

[v2.8] fix data.json file name

---

.github/workflows/push-release.yml

* Using self-hosted runners, the gh token is not available as a secret (https://github.com/rancher/rancher/actions/runs/11116834048/job/30887781385#step:12:78)
* Use vault secrets to generate a token for the GH CLI
* Unit
* None
_TODO_
* _TODO_

[2.9] generate token for gh uploads

---

pkg/auth/cleanup/service.go
pkg/auth/cleanup/service_test.go
tests/controllers/authconfig/authconfig_test.go

[v2.10/main] Use the userClient instead of userCache when cleaning up auth provider users

---

pkg/auth/cleanup/service.go
pkg/auth/cleanup/service_test.go

[v2.9] Use the userClient instead of userCache when cleaning up auth provider users

---

pkg/auth/cleanup/service.go
pkg/auth/cleanup/service_test.go

[v2.8] Use the userClient instead of userCache when cleaning up auth provider users

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml

* The docker-image-digests job failed because `gh` was not installed
* Install the `gh` cli
* Unit
* None
_TODO_
* _TODO_

[2.9] install gh on docker image digests

---

build.yaml
pkg/buildconfig/constants.go

Issue: https://github.com/rancher/rancher/issues/44352

bump webhook to 105.0.0+up0.6.1-rc.3

---

go.mod
go.sum
tests/v2/actions/clusters/clusterconfig.go
tests/v2/actions/clusters/clusters.go
tests/v2/actions/provisioning/creates.go
tests/v2/actions/provisioninginput/config.go
tests/v2/validation/provisioning/proxy/README.md
tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/proxy.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go

Added proxied rancher provisioning tests for https://github.com/rancher/qa-tasks/issues/479
Tests added:
- rke1 node driver
- rke1 custom clusters
- rke2 node driver
- rke2 custom clusters
- k3s node driver
- k3s custom cluster
Runs in Jenkins

[v2.9] Added proxied rancher provisioning tests

---

tests/v2/actions/projects/projects.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go

Forwardport https://github.com/rancher/rancher/pull/46139
Issue: https://github.com/rancher/qa-tasks/issues/1250

[main] P0 Project Container Default Resource Limit tests

---

pkg/controllers/management/aks/aks_cluster_handler.go
pkg/controllers/management/aks/aks_cluster_handler_mockc_interface_test.go
pkg/controllers/management/clusteroperator/utils.go
pkg/controllers/management/eks/eks_cluster_handler.go
pkg/controllers/management/eks/eks_cluster_handler_mockc_interface_test.go
pkg/controllers/management/gke/gke_cluster_handler.go
pkg/controllers/management/gke/gke_cluster_handler_mockc_interface_test.go
pkg/dialer/factory.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/types/config/dialer/dialer.go

Backport #47015 (straightforward cherry-pick from the commit there)

[v2.9] Avoid leaking transports cache

---

pkg/image/origins.go

Add origin for mirrored-cloud-provider-vsphere

Add mirrored-cloud-provider-vsphere origin

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

Needed to fix the hostname suffix so its distinct
Updated the map
* Unit
* None
_TODO_
* _TODO_

Fixed qase run hostname suffix

---

pkg/image/origins.go

Missing sources for images related to rancher-logging

[v2.9] Add new image sources for logging-related images

---

pkg/image/origins.go

Missing sources for images related to rancher-logging

[main] Add new image sources for logging-related images

---

pkg/auth/providers/publicapi/login.go

[v2.7] Avoid panics on login

---

pkg/tls/tls.go
pkg/types/config/context.go
pkg/wrangler/context.go

`lasso_controller_total_cached_object` does not update overtime and is not completely accurate, as there can be multiple caches from different contexts.
Use the new changes from https://github.com/rancher/lasso/pull/95, and annotate different contexts for a more detailed overview of the caches.
I tested this locally, which produced metrics like:
We can observe how at 12:40 I intentionally created a new secret to see how the metrics will reflect it.
* Unit
* None
_TODO_
Existing / …

Improve lasso_controller_total_cached_object metrics

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/workloads/workload.go
tests/v2/validation/workloads/workload_test.go
tests/validation/tests/v3_api/test_workload.py

Backports:
v2.9 https://github.com/rancher/rancher/pull/47344
v2.8 https://github.com/rancher/rancher/pull/47343
v2.7 https://github.com/rancher/rancher/pull/47342

<main> Converted test_wl_pause_orchestration from python to go

---

tests/v2/actions/projects/projects.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/projects/projects_resource_quota_test.go

**Issue**: https://github.com/rancher/qa-tasks/issues/1249
**Note**: 2.8 Backport PR and forward port PR will be created once this gets approved

P0 Project Resource Quota tests

---

pkg/api/norman/customization/cred/store.go
pkg/api/norman/customization/cred/store_test.go
pkg/api/norman/server/managementstored/setup.go
pkg/rancher/migrations.go

Backport of https://github.com/rancher/rancher/pull/47285

[47243] [2.9] Add expiration annotation to harvester cloud credential via norman

---

tests/v2/actions/projects/projects.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/projects/projects_resource_quota_test.go

Backport https://github.com/rancher/rancher/pull/45734
Issue: https://github.com/rancher/qa-tasks/issues/1249

[2.8] P0 Project Resource Quota tests

---

tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/projects/projects_resource_quota_test.go

Forwardport https://github.com/rancher/rancher/pull/45734
Issue: https://github.com/rancher/qa-tasks/issues/1249

[main] P0 Project Resource Quota tests

---

tests/v2/actions/configmaps/configmaps.go
tests/v2/validation/rbac/configmaps/README.md
tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go

Forward port of https://github.com/rancher/rancher/pull/45780

[Main] Migrating configmaps tests from python to go

---

pkg/image/origins.go

This is a backport of https://github.com/rancher/rancher/pull/47398

Add new image rancher/mirrored-longhornio-longhorn-cli

---

tests/v2/actions/rbac/rbac.go
tests/v2/actions/rbac/verify.go
tests/v2/validation/rbac/rbac_test.go

Backport of [#47447 ](https://github.com/rancher/rancher/pull/47447)
Jenkins run

[v2.9] Adding VerifyRoleBindingsForUser to rbac_test

---

tests/v2/actions/rbac/rbac.go
tests/v2/actions/rbac/verify.go
tests/v2/validation/rbac/rbac_test.go

Backport of [#47447 ](https://github.com/rancher/rancher/pull/47447)
Jenkins run

[v2.8] Added VerifyRoleBindingsForUser to rbac_test

---

tests/v2/actions/rbac/rbac.go
tests/v2/actions/rbac/verify.go
tests/v2/validation/rbac/rbac_test.go

Backport of [#47447 ](https://github.com/rancher/rancher/pull/47447)
Jenkins run

[v2.7]Added VerifyRoleBindingsForUser to rbac_test

---

go.mod
go.sum
tests/v2/actions/provisioning/creates.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go

[## Issue: 
* Unit
* None
_TODO_
* _TODO_](https://github.com/rancher/rancher/pull/47414)

[2.7] adding full k8s tests to airgap

---

go.mod
go.sum
tests/v2/actions/provisioning/creates.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go

port of https://github.com/rancher/rancher/pull/47414

[2.9] adding full k8s tests to airgap

---

go.mod
go.sum
tests/v2/actions/provisioning/creates.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go

port of https://github.com/rancher/rancher/pull/47414

[2.8] adding full k8s tests to airgap

---

tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go

Error fix from: https://github.com/rancher/rancher/pull/47256

Removing standard user from the test

---

package/Dockerfile
package/Dockerfile.agent

#47394
* the `VERSION` ARG was not set in some stages on the server and agent dockerfiles
* set the `VERSION` ARG
Tested locally by downloading and running the image built in the PR `build-server` job
* Unit
* None
_TODO_
* _TODO_

V2.7 fix docker default dev server-version

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

https://github.com/rancher/rancher/issues/47383

[v2.8] update rke to v1.5.14-rc.3

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

https://github.com/rancher/rancher/issues/47384

[v2.9] update rke to v1.6.3-rc.2

---

pkg/api/norman/customization/cred/store_test.go
pkg/rancher/migrations.go

When attempt to migrate existing harvester credentials to add the `rancher.io/expiration-timestamp` annotation, if the cloud credential secret's kubeconfig contains a token which no longer exists, a `NotFound` error will be returned when attempting to get the `v3.Token` object.
Ignore not found errors during migrations (note: the error is still valid during a norman Update, since we don't want users to create invalid credentials, but we have no control over whether the token was already removed during migrations).
Tested Manually & with unit tests
Updated existing unit tests to cover this case
N/A
N/A
* Updated tests in `store_test.go`

Fix harvester cloud credential migration when using non-existent token

---

build.yaml
pkg/buildconfig/constants.go

[2.9] Un-rc Shell image

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_aci_network_provider.go

[2.7] bump RKE to v1.4.22-rc.1

---

go.mod
go.sum

Pull in version of steve for indexing more fields in sqlite.

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

the CI failed so I just made the PR myself

[2.7] bump rke to v1.4.22

---

pkg/auth/providers/local/local_auth_provider.go
pkg/auth/providers/local/local_auth_provider_test.go

Searching to add users is fairly limited and case-sensitive. 
This adds tests and improves search by making matching case-insensitive (for longer searches).
Create a user, "John Smith", username `johns`.
Create a project "demo" and try and add the newly created "John Smith" user to the project, try using their second name "Smith", it won't be found.
With this branch, the same instructions, the user will be found.
Also, try creating a user with a DisplayName that contains non-ASCII latin characters, and the same behaviour should also be observed.
Followed the above.
* Unit
* None
* If "None" - …

Fuzzy local search

---

pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go
pkg/controllers/managementuser/rbac/globalrolebinding_handler_test.go

Add unit tests for `GlobalRoleBinding` handlers

Add unit test for grb handlers

---

tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_rbac_test.go
tests/v2/validation/projects/projects_resource_quota_test.go
tests/v2/validation/projects/projects_test.go
tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
tests/v2/validation/rbac/secrets/rbac_secrets_test.go
tests/v2/validation/workloads/deployment_test.go
tests/v2/validation/workloads/workload_test.go

Forwardport https://github.com/rancher/rancher/pull/46095

[main] P0 Project RBAC Tests

---

package/Dockerfile

Update to Dashboard refs to v2.7.16

---

package/Dockerfile

Update to Dashboard refs to v2.8.9

---

package/Dockerfile

Update to Dashboard refs to v2.9.3

---

README.md

Updating README after promoting latest/stable version

updating latest/stable version for v2.9.3

---

pkg/auth/principals/handler.go

https://github.com/rancher/rancher/issues/47702
The `/v3/principal` endpoint returns `500 ServerError` when the principal can't be found.
It should return `404 Not Found` instead.
N/A
N/A

Make /v3/principal return 404 instead of 500 when principal can't be found

---

tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_rbac_test.go
tests/v2/validation/projects/projects_resource_quota_test.go
tests/v2/validation/projects/projects_test.go
tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
tests/v2/validation/rbac/secrets/rbac_secrets_test.go
tests/v2/validation/workloads/workload_test.go

Backport https://github.com/rancher/rancher/pull/46095

[v2.8] P0 Project RBAC Tests

---

tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_rbac_test.go
tests/v2/validation/projects/projects_resource_quota_test.go
tests/v2/validation/projects/projects_test.go
tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
tests/v2/validation/rbac/secrets/rbac_secrets_test.go
tests/v2/validation/workloads/workload_test.go

Issue: https://github.com/rancher/qa-tasks/issues/1251
Note: 2.8 Backport and forwardport PRs will be created once this gets approved

P0 Project RBAC and Additional tests

---

go.mod
go.sum

- Upgrade steve to include: https://github.com/rancher/steve/pull/292

Pull in version of steve with refactored accesscontrol

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Backport of #47642 
* Unit
* None
A simple cherry-pick of commit `b95a5a2c66e165d421f3e8822a461f9233584b18`.
_TODO_
* _TODO_

Backport v29 fix cached azure client

---

tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Jenkinsfile.rc

The provisioning sanity Jenkins job has some fixes that need to occur. These include:
- Removing excess Corral validation job
- Running the CLI test and provisioning test in separate test packages
- Add Windows support
Fixes the above listed issues.
Jenkins runs will be provided to reviewers offline.

[Main] Provide fixes for provisioning sanity recurring Jenkins job

---

tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/Jenkinsfile
tests/v2/validation/Jenkinsfile.rc

Backport of https://github.com/rancher/rancher/pull/47729. Also includes backport fixes for adding RSA support to Jenkins.

[v2.9] Provide fixes for provisioning sanity recurring Jenkins job

---

tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/Jenkinsfile
tests/v2/validation/Jenkinsfile.rc

Backport of https://github.com/rancher/rancher/pull/47729. Also includes backport fixes for adding RSA support to Jenkins.

[v2.8] Provide fixes for provisioning sanity recurring Jenkins job

---

cleanup/user-cluster.yml

cherry-pick from https://github.com/rancher/rancher/pull/44854 
Issue https://github.com/rancher/rancher/issues/43343
* Unit
* None
_TODO_
* _TODO_

[2.10] [Cherrypick] fix-user-cluster.yml

---

build.yaml
pkg/buildconfig/constants.go

Depends on PR https://github.com/rancher/charts/pull/4658
Related to #46201

Bump webhook to v0.6.1-rc.9

---

tests/v2/actions/projects/projects.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_resource_quota_test.go
tests/v2/validation/projects/projects_test.go

Backport https://github.com/rancher/rancher/pull/47754
QA Task: https://github.com/rancher/qa-tasks/issues/1599

[2.8] Fix timeout issue in project tests

---

tests/v2/actions/projects/projects.go
tests/v2/validation/projects/projects.go
tests/v2/validation/projects/projects_container_default_resource_limit_test.go
tests/v2/validation/projects/projects_resource_quota_test.go
tests/v2/validation/projects/projects_test.go

Backport https://github.com/rancher/rancher/pull/47754
QA Task: https://github.com/rancher/qa-tasks/issues/1599

[2.9] Fix timeout issue in project tests

---

go.mod
go.sum
package/Dockerfile
pkg/apis/go.mod
pkg/apis/go.sum

Hotfix for https://github.com/rancher/rancher/issues/47694
Bring in hotfix version of norman: https://github.com/rancher/norman/pull/523
* Unit
* None
_TODO_
* _TODO_

[v2.9.3-hotfix-schema-leak] Bump norman version to resolve memory leak

---

pkg/api/norman/customization/globalnamespaceaccess/access_common.go
pkg/api/norman/customization/multiclusterapp/multi_cluster_app.go
pkg/api/norman/customization/multiclusterapp/validator_multiclusterapp.go
pkg/api/norman/server/managementstored/setup.go
pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go
pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/project_cluster_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementlegacy/multiclusterapp/handler_multiclusterapp.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml
pkg/settings/setting.go
pkg/systemaccount/systemaccount.go

Backport of https://github.com/rancher/rancher/pull/47723
Adds a setting to enable the feature (default to False)

[v2.8] Change the backing namespace of projects

---

pkg/api/norman/customization/globalnamespaceaccess/access_common.go
pkg/api/norman/customization/multiclusterapp/multi_cluster_app.go
pkg/api/norman/customization/multiclusterapp/validator_multiclusterapp.go
pkg/api/norman/server/managementstored/setup.go
pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go
pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/crtb_handler_test.go
pkg/controllers/management/auth/project_cluster_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementlegacy/multiclusterapp/handler_multiclusterapp.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml
pkg/settings/setting.go
pkg/systemaccount/systemaccount.go

Backport of https://github.com/rancher/rancher/pull/47723
Includes a setting to disable the feature (default to True)

[v2.9] Change the backing namespace of projects

---

tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/proxy.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go

Backport of https://github.com/rancher/rancher/pull/47808.

[v2.9] Add build tags to the proxy tests

---

tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/proxy.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go

Backport of https://github.com/rancher/rancher/pull/47808.

[v2.8] Add build tags to the proxy tests

---

go.mod
go.sum

Updated to include https://github.com/rancher/steve/pull/309 to facilitate QA testing
* Unit
Steve now reliably honors a namespace filter (during watch/list operations) that it was previously ignoring in some cases, depending on how the API request was formatted. This is strictly a bugfix, so well behaved consumers shouldn't be affected, but anything accidentally relying on the missing filter behavior may need to be adjusted.

go get steve to include refactored partitioning

---

tests/v2/actions/rbac/rbac.go
tests/v2/actions/workloads/daemonset/daemonset.go
tests/v2/validation/rbac/clusterandprojectroles/manage_workloads_role_test.go

Automate tests in https://github.com/rancher/qa-tasks/issues/1594

[main] P0 tests for GH47000

---

tests/v2/validation/Jenkinsfile.rc

Backport of https://github.com/rancher/rancher/pull/47845.

[v2.9] Report Jenkins results to Slack

---

tests/v2/validation/Jenkinsfile.rc

Backport of https://github.com/rancher/rancher/pull/47845.

[v2.8] Report Jenkins results to Slack

---

go.mod
go.sum

Related to #47788
Change for main: https://github.com/rancher/rancher/issues/46642

[v2.9] backport using sqlite to cache additional fields (retry)

---

tests/v2/actions/pipeline/clustername.go

Backports
v2.9 https://github.com/rancher/rancher/pull/47858
v2.8 https://github.com/rancher/rancher/pull/47856
v2.7 https://github.com/rancher/rancher/pull/47857

<main> Investigate recurring run failures in Workloads tests

---

.github/workflows/push-release.yml

The chart path was wrong on the upload step
Fix the chart path
* Unit
* None
_TODO_
* _TODO_

[v2.9] fix chart upload

---

go.mod
go.sum
pkg/api/norman/customization/aks/listers.go
pkg/api/norman/customization/cluster/validator.go

[v2.10] Bump azure-sdk-for-go for hosted providers

---

.github/workflows/push-release.yml

The charts distribution id was not defined
Defined the charts distribution ID
* Unit
* None
_TODO_
* _TODO_

[v2.9] define charts distribution id

---

go.mod
go.sum
pkg/api/norman/customization/aks/listers.go
pkg/api/norman/customization/cluster/validator.go

Revert "[v2.10] Bump azure-sdk-for-go for hosted providers"

---

.github/workflows/push-release.yml

The artifacts hashes script is missing the extension.
Add the extension to the script name
* Unit
* None
_TODO_
* _TODO_

add artifacts-hashes extension

---

pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/manager.go
pkg/controllers/management/auth/prtb_handler.go
pkg/crds/names.go
tests/integration/suite/test_alert.py
tests/integration/suite/test_role_template.py
tests/validation/tests/v1_api/README.md

Reverts rancher/rancher#47893 until we have a separate 2.10 branch

Revert "Remove last references to notifiers and alerts"

---

pkg/auth/cleanup/service_test.go
pkg/controllers/management/auth/legacy_grb_cleaner.go
pkg/controllers/management/auth/legacy_rt_cleaner.go
pkg/controllers/management/auth/token.go
pkg/controllers/management/auth/token_test.go
pkg/controllers/management/auth/user.go
pkg/controllers/management/auth/user_test.go

Revert "migrate management/auth from norman to wrangler"

---

.github/workflows/push-release.yml

* Artifacts were uploaded to the bucket with the tag name, instead of the actual artifact name
* Docker digests were created in a temp dir that wasn't available in other steps
* Set the artifact name on aws s3 cp
* Use a not temp dir
* Unit
* None
_TODO_
* _TODO_

set artifact name on upload and fix docker digests dir

---

tests/controllers/authconfig/authconfig_test.go

Trying to generate a large number of tokens leads to the following error:
```
authconfig_test.go:136: 
Error Trace:	/home/runner/work/rancher/rancher/tests/controllers/authconfig/authconfig_test.go:136
Error:      	Received unexpected error:
tokens.management.cattle.io "t-7p88v" already exists, the server was not able to generate a unique name for the object
Test:       	TestAuthConfigSuite/TestTokensCleanup
```
There is no point in doing so as controller integration tests are not suitable for load/stress testing.
Generating a handful of tokens suffices. 
N/A
N/A

Fix flaky TestTokensCleanup controller integration test

---

pkg/agent/cluster/cluster.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Too many secrets are created in parallel across nodes.
This uses optimistic locking to prevent the secrets from persisting.
When a secret is created for an SA, the SA is annotated with the Secret reference, if this results in a conflict, the Secret is deleted.
This allows for the first process to annotate the resource to ensure that the secret exists.
* Unit
* None
_TODO_
* _TODO_

Cache mitigation

---

.github/workflows/push-release.yml

An if statement was missing from the build-publish-chart step and the job was trying to upload charts on pushes 
Add an if statement so charts are only uploaded on tags
* Unit
* None
_TODO_
* _TODO_

[v2.9] only upload charts on tags

---

pkg/controllers/management/node/controller.go

https://github.com/rancher/rancher/issues/47940
backport of https://github.com/rancher/rancher/pull/47943

[2.9] fix RKE1 cluster provisioning failures

---

pkg/controllers/management/node/controller.go

https://github.com/rancher/rancher/issues/47941
backport of https://github.com/rancher/rancher/pull/47943

[2.8] fix RKE1 cluster provisioning failures

---

pkg/controllers/management/node/controller.go

https://github.com/rancher/rancher/issues/47948
backport of https://github.com/rancher/rancher/pull/47943

[2.7] fix RKE1 cluster provisioning failures

---

.github/actions/setup-tag-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

* After branching, the main branch should produce `v2.11` head images
* The gh cli version was outdated
* Update release references to `v2.11`
* Upgrade the gh cli version
* Unit
* None
_TODO_
* _TODO_

update release references to v2.11 and upgrade gh cli version

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go

https://github.com/rancher/qa-tasks/issues/1608
s3 for rke2 was failing
fix the lookup method on snapshots for rke2. also factored verifySnapshots to split rke1 / rke2 for readability and code clarity. 
tested locally on rke2 and rke1

[main] update s3 snapshot lookup in test.

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

[v2.10] Bump Rancher CLI to v2.10.0

---

.github/workflows/push-release.yml

* The `awk` dependency was missing from the runner for the generate docker digests job
* Install `awk`
* Unit
* None
_TODO_
* _TODO_

[main] install awk on generate docker digests

---

.github/workflows/push-release.yml

Backport: https://github.com/rancher/rancher/pull/47987
* Unit
* None
_TODO_
* _TODO_

[v2.10] install awk on generate docker digests

---

package/Dockerfile
pkg/settings/setting.go
scripts/package-env
tests/v2/codecoverage/package/Dockerfile

[v2.10] update charts to release branch

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

Updating KDM URLs to `release-v2.10` in preparation of `v2.10.0`

[2.10] update kdm branch to release-v2.10

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml

docker pulls are being rate-limited
* login into docker hub
* pull images from the suse registry, where we can
* reorganize steps to pull images after login
* Unit
* None
_TODO_
* _TODO_

[v2.10] use suse images and login to docker hub

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml

Runs are failing due to docker hub rate-limits
* Use SUSE images where it's possible
* Login into docker hub
* Unit
* None
_TODO_
* _TODO_

[v2.9] use suse registry image and login into docker hub

---

.github/workflows/push-release.yml

* Runs are failing due to docker hub rate-limits
* Login into docker hub
* Unit
* None
_TODO_
* _TODO_

[v2.9] add docker login o build server and agent

---

go.mod
go.sum

Update shepherd with newest version

Update shepherd version

---

go.mod
go.sum

unRC dynamic-listener

---

.github/workflows/pull-request.yml
.github/workflows/push-release.yml

Backport: https://github.com/rancher/rancher/pull/48045 https://github.com/rancher/rancher/pull/48046
* Unit
* None
_TODO_
* _TODO_

[v2.8] docker login

---

.github/workflows/push-release.yml

The registry on rancher agent was the local registry
Use docker io
* Unit
* None
_TODO_
* _TODO_

[v2.10] set dockerio registry

---

pkg/agent/rancher/rancher.go

#43020
Presently, when cattle-cluster-agent receives a SIGTERM, it exits with non-zero exit code instead of handling it cleanly.
The solution proposed in this PR continues the `logrus.Fatalf` behaviour if context returns an error other than `context.Canceled`.
As mentioned in #43020 
1. Built images with proposed code change using: `TAG="dev-tag" REPO=<dockerhub-username> make quick`
1. Started rancher using rancher & rancher-agent images built using the changes proposed in this PR.
1. Import the existing cluster in Rancher UI and execute the curl command presented on the UI:
```sh
$ curl --insecure -sfL https://192.168.29.16/v3/import/9lcgghmxz4fwtnmwqxrjm4czmz7hfglqx7zc4b25mckkxg4h62hj69_c-m-cjqp2626.yaml | kubectl apply -f
```
* None
* If "None" - Reason: …

Handle SIGTERM better in cluster agent

---

README.md

Update README v2.10.0 latest

---

pkg/auth/requests/authenticate_test.go

The "failed to verify token: mismatched" subtest was never updated/changed to actually check for the mismatched token.
Change the subtest to do the right thing.
* Unit
N/A
N/A

Fix token authenticator test

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

[2.10] switch KDM to the dev branch

---

pkg/agent/cluster/cluster.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Direct cherry-pick of the fix for main

[2.9] Backport Cache mitigation

---

pkg/image/origins.go

Adding new neuvector mirrored image compliance config to v2.10
* Unit
* None
_TODO_
* _TODO_

add neuvector compliance-config

---

tests/v2/validation/networking/connectivity/network_policy.go
tests/v2/validation/networking/connectivity/port_test.go
tests/validation/tests/v3_api/test_workload.py

Backports
v2.9 https://github.com/rancher/rancher/pull/47923
v2.8 https://github.com/rancher/rancher/pull/47924
v2.7 https://github.com/rancher/rancher/pull/47925

<main> Convert scale and upgrade test_wl_with_hostPort, nodePort, clusterIp and lb

---

.github/workflows/push-release.yml

Artifacts shouldn't be uploaded from the main branch, just on some specific release branches
remove the artifacts upload
* Unit
* None
_TODO_
* _TODO_

remove artifacts upload to bucket

---

pkg/controllers/management/k3sbasedupgrade/deployPlans.go

https://github.com/rancher/rancher/issues/48206
After initiating a version upgrade for an imported K3s cluster, the cluster's state fluctuates between "Ready" and "Upgrading" at the beginning of the process before stabilizing at "Upgrading" until the upgrade is complete. Please check the linked GH issue for screenshots and more details. 
It was discovered that the `modifyClusterCondition` function is sometimes called with a `mgmtCluster` object whose observed cluster version is older than the version in the master or worker plan. This causes the cluster's `Upgraded` condition to incorrectly change from `Unknown` to `Ready`. Later, when the function is called again with a `mgmtCluster` object and empty master or worker plans, the `Upgraded` condition flips back from `Ready` to `Unknown`. …

[2.10] Fix imported RKE2/K3s cluster state during upgrading

---

pkg/controllers/management/k3sbasedupgrade/deployPlans.go

https://github.com/rancher/rancher/issues/48204
Cherry-pick of  https://github.com/rancher/rancher/pull/48205 
The issue was originally logged under the v2.10 milestone so the initial PR was merged into the release/v2.10 branch.  Now we are bringing those changes into the main branch.

[main] Fix imported RKE2/K3s cluster state during upgrading

---

tests/v2/actions/charts/charts.go
tests/v2/actions/charts/stackstate.go
tests/v2/actions/observability/config.go
tests/v2/actions/observability/stackstate.go
tests/v2/actions/uiplugins/payload.go
tests/v2/actions/uiplugins/stackstate.go
tests/v2/validation/observability/README.md
tests/v2/validation/observability/rbac/stackstate_rbac_test.go
tests/v2/validation/observability/stackstate_test.go

Backport https://github.com/rancher/rancher/pull/47623

[2.10] Stackstate P0 checks

---

tests/v2/actions/charts/charts.go
tests/v2/actions/charts/stackstate.go
tests/v2/actions/observability/config.go
tests/v2/actions/observability/stackstate.go
tests/v2/actions/uiplugins/payload.go
tests/v2/actions/uiplugins/stackstate.go
tests/v2/validation/observability/README.md
tests/v2/validation/observability/rbac/stackstate_rbac_test.go
tests/v2/validation/observability/stackstate_test.go

Backport of https://github.com/rancher/rancher/pull/47623

[2.9] Stackstate P0 checks 

---

tests/v2/actions/charts/charts.go
tests/v2/actions/charts/stackstate.go
tests/v2/actions/observability/config.go
tests/v2/actions/observability/stackstate.go
tests/v2/actions/uiplugins/payload.go
tests/v2/actions/uiplugins/stackstate.go
tests/v2/validation/observability/README.md
tests/v2/validation/observability/rbac/stackstate_rbac_test.go
tests/v2/validation/observability/stackstate_test.go

Backport of https://github.com/rancher/rancher/pull/47623

[2.8]Stackstate P0 checks

---

pkg/auth/principals/handler.go

https://github.com/rancher/rancher/issues/47831
Backport of #47717
N/A
N/A

[v2.9] Make /v3/principal return 404 instead of 500 when principal can't be found

---

cleanup/user-cluster.yml

Fixes https://github.com/rancher/rancher/issues/43343
cattle-cleanup-sa service account does not have the necessary permissions to access resources in the cattle-system namespace, specifically the services resource and does not have permissions to delete resources related to mutating and validating webhook configurations in the admissionregistration.k8s.io API group.
To resolve these specific errors, should add necessary permissions for services and webhook configurations.
```
root@server-1:~# ./user-cluster.sh rancher/rancher-agent:v2.7.6 
serviceaccount/cattle-cleanup-sa created
clusterrolebinding.rbac.authorization.k8s.io/cattle-cleanup-binding created
job.batch/cattle-cleanup-job created
clusterrole.rbac.authorization.k8s.io/cattle-cleanup-role created
Error from server (BadRequest): …
```

fix-user-cluster.yml

---

pkg/controllers/management/auth/project_cluster/cluster_handler.go
pkg/controllers/management/auth/project_cluster/cluster_handler_test.go
pkg/controllers/management/auth/project_cluster/common.go
pkg/controllers/management/auth/project_cluster/project_handler.go
pkg/controllers/management/auth/project_cluster/project_handler_test.go

refact: migrate from norman to wrangler

---

pkg/agent/cluster/cluster.go
pkg/capr/common.go
pkg/controllers/capr/bootstrap/controller.go
pkg/controllers/dashboard/apiservice/apiservice.go
pkg/impersonation/impersonation.go
pkg/kontainer-engine/drivers/util/utils.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
pkg/tunnelserver/peermanager.go
pkg/utils/utils.go
pkg/utils/utils_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go
tests/v2/integration/serviceaccount/serviceaccounttoken_test.go

Backport of #47273
N/A
N/A
N/A

[v2.10] Cache mitigation

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

Same as https://github.com/rancher/rancher/pull/47787. Received ask to rebuild hotfix for `v2.9.4`

V2.9.4 hotfix schema leak fix

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go
tests/v2/validation/fleet/provisioning/airgap/README.md
tests/v2/validation/fleet/provisioning/airgap/airgap.go
tests/v2/validation/fleet/provisioning/airgap/fleet_in_airgap_test.go
tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go

backports: 
https://github.com/rancher/rancher/pull/48250
https://github.com/rancher/rancher/pull/47662
https://github.com/rancher/rancher/pull/47944

[2.10.0] fleet backports

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go
tests/v2/validation/fleet/provisioning/airgap/README.md
tests/v2/validation/fleet/provisioning/airgap/airgap.go
tests/v2/validation/fleet/provisioning/airgap/fleet_in_airgap_test.go
tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go

backports:
https://github.com/rancher/rancher/pull/48250
https://github.com/rancher/rancher/pull/47662
https://github.com/rancher/rancher/pull/47944

[2.8] fleet backports after 2.10.0

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go
tests/v2/validation/fleet/provisioning/airgap/README.md
tests/v2/validation/fleet/provisioning/airgap/airgap.go
tests/v2/validation/fleet/provisioning/airgap/fleet_in_airgap_test.go
tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go

backports:
https://github.com/rancher/rancher/pull/48250
https://github.com/rancher/rancher/pull/47662
https://github.com/rancher/rancher/pull/47944

[2.9] fleet backports after 2.10.0

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Forward port of https://github.com/rancher/rancher/pull/47253
Issue: https://github.com/rancher/rancher/issues/48265

Support Azure AD for China region (#47253)

---

cleanup/user-cluster.yml

cherry-pick from https://github.com/rancher/rancher/pull/44854
Issue https://github.com/rancher/rancher/issues/43343
* Unit
* None
_TODO_
* _TODO_

[2.9] [Cherrypick] fix-user-cluster.yml

---

main.go
pkg/features/feature.go
pkg/rancher/rancher.go
pkg/serviceaccounttoken/queue.go
pkg/serviceaccounttoken/queue_test.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_cleaner.go
pkg/serviceaccounttoken/secret_cleaner_test.go

Due to previous issues with creating service-account secrets, we have clusters with lots of secrets which need to be cleaned up.
This removes old impersonation secrets that do not have an associated ServiceAccount.
This is done in batches from a large queue.
* Unit
* None
_TODO_
* _TODO_

Clean unused secrets.

---

pkg/auth/providers/azure/clients/ms_graph_client.go
pkg/auth/providers/azure/clients/ms_graph_client_test.go

Issue: https://github.com/rancher/rancher/issues/48264
Forward Port of: https://github.com/rancher/rancher/pull/47253

[v2.10] Backport fix for Azure China

---

pkg/nodeconfig/archive.go
pkg/nodeconfig/config.go

https://github.com/rancher/rancher/issues/48342
Backport of https://github.com/rancher/rancher/pull/48328

[2.8] Fix the issue where VM not being deleted from the cloud

---

pkg/nodeconfig/archive.go
pkg/nodeconfig/config.go

https://github.com/rancher/rancher/issues/48343
Backport of https://github.com/rancher/rancher/pull/48328

[2.9] Fix the issue where VM not being deleted from the cloud

---

tests/v2/validation/Jenkinsfile.vsphere
tests/v2/validation/fleet/public_gitrepo_test.go

[2.8] add config for vsphere in jenkins, with updates.

---

tests/v2/validation/Jenkinsfile.vsphere
tests/v2/validation/fleet/public_gitrepo_test.go

partly solves https://github.com/rancher/qa-tasks/issues/1617
we currently have no way to run our tests on our infrastructure. 
use jenkins worker behind the VPN in order to run specific jobs. 
* this should give the jenkins job access to both vsphere and harvester envs. 
also updated some default branches while I'm in the code. 
This will require a jjb PR before it can be used. 
tested in jenkins

[main] add config for vsphere in jenkins, with updates.

---

tests/v2/validation/Jenkinsfile.vsphere
tests/v2/validation/fleet/public_gitrepo_test.go

port of https://github.com/rancher/rancher/pull/48290

[2.10] add config for vsphere in jenkins, with updates.

---

pkg/nodeconfig/archive.go
pkg/nodeconfig/config.go

https://github.com/rancher/rancher/issues/48341
backport of https://github.com/rancher/rancher/pull/48328

[2.10] Fix the issue where VM not being deleted from the cloud

---

go.mod
go.sum
pkg/api/norman/customization/aks/listers.go
pkg/api/norman/customization/cluster/validator.go

Bump azure-sdk-for-go for hosted providers

---

go.mod
go.sum

Bump steve to fix issue 48103

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

[v2.10] Bump gke-operator to v1.10.1-rc.3

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump Rancher CLI to v2.10.1

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Bump Rancher CLI to v2.9.5

---

pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Backport of #48429
nodesyncer panics when attempt to reconcile a `nil` node.
Add `nil` check.
* Unit
* None
_TODO_
* _TODO_

[2.10] [48431] Fix panic in nodesyncer

---

pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Backport of #48429
nodesyncer panics when attempt to reconcile a `nil` node.
Add `nil` check.
* Unit
* None
_TODO_
* _TODO_

[2.9] [48432] Fix panic in nodesyncer

---

pkg/controllers/managementuser/nodesyncer/nodessyncer.go

nodesyncer panics when attempt to reconcile a `nil` node.
Add `nil` check.
* Unit
* None
_TODO_
* _TODO_

[48428] Fix panic in nodesyncer

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/charts/pull/4885

[2.8] unRC webhook to 0.4.14

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

[v2.8] kdm release branch

---

build.yaml
pkg/buildconfig/constants.go

Contains: https://github.com/rancher/charts/pull/4891

[2.10] unRC webhook 0.6.2

---

build.yaml
pkg/buildconfig/constants.go

Includes: https://github.com/rancher/charts/pull/4893

[v2.9] unRC webhook v0.5.5

---

README.md

update v2.10.1 to stable

---

.github/workflows/integration-tests.yml
.github/workflows/validate.yml
Dockerfile-windows.dapper
Dockerfile.dapper
go.mod
hack/airgap/go.mod
package/Dockerfile
package/Dockerfile.agent
package/windows/Dockerfile.agent
pkg/apis/go.mod
pkg/client/go.mod
pkg/codegen/main.go
tests/v2/codecoverage/Dockerfile.buildcodecoverage
tests/v2/codecoverage/Dockerfile.codecoverage
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/steve/vai/scripts/script.sh

Backport of #48404
N/A
N/A
N/A

[v2.10] Bump Go to 1.23.4

---

.github/workflows/verify-generated-code-changes.yml
Dockerfile-windows.dapper
Dockerfile.dapper
go.mod
package/Dockerfile
package/Dockerfile.agent
package/windows/Dockerfile.agent
pkg/apis/go.mod
pkg/client/go.mod
pkg/codegen/main.go
tests/v2/codecoverage/Dockerfile.buildcodecoverage
tests/v2/codecoverage/Dockerfile.codecoverage
tests/v2/validation/Dockerfile.e2e
tests/v2/validation/Dockerfile.validation
tests/v2/validation/steve/vai/scripts/script.sh

Backport of #48404 
N/A
N/A
N/A

[v2.9] Bump Go to 1.23.4

---

pkg/controllers/dashboard/systemcharts/controller.go

https://github.com/rancher/rancher/issues/47914
This PR is to correct the retry-on-conflict logic in the systemcharts package, as well as to address other stylistic suggestions raised in https://github.com/rancher/rancher/pull/47894.
The PR is validated in the following way:
- Build custom Rancher and Rancher-agent images from the branch.  
- Run Rancher using the custom image.  
- Create a standalone K3s cluster and deploy a `system-upgrade-controller` deployment in the `cattle-system` namespace with the label `io.cattle.field/appId: rancher-k3s-upgrader`.  
- Import the K3s cluster into Rancher.  
- Verify that the SUC app is **not** installed in the cluster.  
- Modify the `system-upgrade-controller` deployment, such as scaling up its replicas.  
- Check the cluster-agent logs for …

[main] fix the retry-on-conflict logic

---

pkg/capr/installer/installer.go
pkg/capr/installer/installer_test.go

This is a cherry picked backport of https://github.com/rancher/rancher/pull/48500

[2.10] Fix vSphere Node Driver Windows Install Script Env Vars 

---

pkg/capr/installer/installer.go
pkg/capr/installer/installer_test.go

This is a cherry picked backport of https://github.com/rancher/rancher/pull/48500

[2.9] Fix vSphere Node Driver Windows Install Script Env Vars

---

pkg/controllers/dashboard/systemcharts/controller.go

https://github.com/rancher/rancher/issues/48057 
cherry-pick of https://github.com/rancher/rancher/pull/48111

[Backport] [2.10] fix the retry-on-conflict logic

---

go.mod
go.sum
tests/v2/actions/upgradeinput/load.go
tests/v2/validation/upgrade/kubernetes.go
tests/v2/validation/upgrade/kubernetes_test.go
tests/v2/validation/upgrade/workload_test.go

Back port of https://github.com/rancher/rancher/pull/48292

[2.9] Fixes the local upgrade failure

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh
tests/v2/validation/kdm/kdm_test.go

https://github.com/rancher/rancher/pull/48446

[release/v2.9] Change KDM URL from release-v2.9 to dev-v2.9

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

https://github.com/rancher/rancher/pull/48445

[release/v2.10] Change KDM branch from release-v2.10 to dev-v2.10

---

tests/v2/validation/networking/connectivity/network_policy.go
tests/v2/validation/networking/connectivity/port_test.go

Backports
https://github.com/rancher/rancher/pull/48450
https://github.com/rancher/rancher/pull/48451
https://github.com/rancher/rancher/pull/48452

<main> Add PNI, k3s cloud manager validations and refactor for port tests

---

pkg/auth/providers/saml/saml_client.go

https://github.com/rancher/rancher/issues/47801
After logging in, hit a 500 error. Was taken to a screen that didn't match the newer look and feel.
https://jira.suse.com/browse/SURE-9109
Update the URL in saml backend.
* Unit
* None
_TODO_
* _TODO_

fix: update redirectURL to redirect at new UI

---

go.mod
go.sum

Includes a bunch of changes for Vai

Bump steve to v0.5.0

---

chart/templates/ingress.yaml
chart/tests/ingress_test.yaml
chart/values.yaml

This is a backport of: https://github.com/rancher/rancher/pull/48508
The issue this is related to is: https://github.com/rancher/rancher/issues/48167
Once this is merged we will have fully corrected the missing patch for this on all active branches.

[Backport v2.10][CHART] Support user modifying ingress path/pathType

---

pkg/features/feature.go
pkg/rancher/rancher.go
pkg/serviceaccounttoken/queue.go
pkg/serviceaccounttoken/queue_test.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_cleaner.go
pkg/serviceaccounttoken/secret_cleaner_test.go

Backport of https://github.com/rancher/rancher/issues/48313

[2.10] Backport clean unused secrets

---

pkg/features/feature.go
pkg/rancher/rancher.go
pkg/serviceaccounttoken/queue.go
pkg/serviceaccounttoken/queue_test.go
pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_cleaner.go
pkg/serviceaccounttoken/secret_cleaner_test.go

Backport fix https://github.com/rancher/rancher/issues/48314

[2.9] Backport Clean unused secrets

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

Bump Harvester machine driver to version v0.7.1.
https://github.com/harvester/harvester/issues/6829
https://github.com/rancher/rancher/issues/47631
Bump kubernetes package version in `go.mod`. 
1. Confirm that the Harvester node driver shows up in Version v0.7.1
2. Install a Harvester cluster and import into Rancher for virtualization management
3. Create new cloud credentials
4. Create a downstream cluster using the Harvester node driver
5. Rotate cloud credentials as explained in https://harvesterhci.io/kb/renew_harvester_cloud_credentials/
6. Scale down / delete the downstream cluster. This should complete without errors.
* Unit
* None
* …

feat: bump harvester driver to v0.7.1

---

.github/actions/build-artifacts-index/action.yml
.github/workflows/push-release.yml

* When artifacts were uploaded, the artifacts index was not rebuilt
* Add the build artifacts index step
* Unit
* None
_TODO_
* _TODO_

[v2.9] add build index

---

pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/47732
This PR introduces additional explanations for the Node's Conditions and includes debug-level logging messages to assist with troubleshooting.

[main] Improve the trace logging when updating worker nodes

---

pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/48002
Backport of https://github.com/rancher/rancher/pull/47543

[2.9] Improve the trace logging when updating worker node

---

pkg/controllers/management/rkeworkerupgrader/node.go
pkg/controllers/management/rkeworkerupgrader/upgrade.go

https://github.com/rancher/rancher/issues/48001
Backport of https://github.com/rancher/rancher/pull/47543

[2.10] Improve the trace logging when updating worker node

---

pkg/controllers/capr/managesystemagent/managesystemagent.go

Backport of #48569
When the `stv-aggregation` secret changes, which is used to populate the `system-agent-upgrader` SUC plan, SUC will not check the contents of the secret, and thus the plan will not be updated.
Utilize the `secrets` feature within SUC.
Tested manually, confirming the values from the secret were used and changing the secret results in the plan being applied.

[2.10] [48440] Add stv-aggregation secret to system-agent-upgrader suc plan

---

pkg/auth/providers/publicapi/store.go
pkg/schemas/management.cattle.io/v3public/public_schema.go

The `/v3-public/authProviders` allows all resource methods.
Allow only GET method.
N/A
N/A
N/A

Fix public authProviders endpoint

---

pkg/api/norman/customization/aks/listers.go

We want to list only official Kubernetes versions and skip LTS which required additional paid support in Azure
Issue: https://github.com/rancher/aks-operator/issues/717
* Unit
* None
_TODO_
* _TODO_

[aks-operator] List only supported Kubernetes versions

---

pkg/auth/providers/publicapi/store.go
pkg/client/generated/management/v3public/zz_generated_auth_token.go
pkg/client/generated/management/v3public/zz_generated_client.go
pkg/schemas/management.cattle.io/v3public/public_schema.go

Currently GET and DELETE are allowed on the authTokens collection, which are not used.
Remove these methods for the authTokens collection.
N/A
N/A
N/A

Fix public authTokens endpoint

---

pkg/data/management/kontainerdriver_data.go
pkg/data/management/machinedriver_data.go

[2.10] [48610] Update OTC drivers (#45026)

---

pkg/data/management/kontainerdriver_data.go
pkg/data/management/machinedriver_data.go

[2.11] [48611] Update OTC drivers (#45026)

---

pkg/controllers/management/cluster/clustercontroller.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/clusterprovisioner/store.go
pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
pkg/controllers/management/etcdbackup/etcdbackup.go
pkg/controllers/managementuser/certsexpiration/certsexpiration.go
pkg/encryptedstore/secrets_store.go
pkg/nodeconfig/config.go
pkg/rkenodeconfigserver/lookup.go

Issue: https://github.com/rancher/rancher/issues/48000
Backport of: https://github.com/rancher/rancher/pull/46877

[v2.9]Backport fix: add owner reference to secret

---

pkg/serviceaccounttoken/secret.go
pkg/serviceaccounttoken/secret_test.go
tests/pkg/serviceaccounttoken/mitigation_test.go

Issue: #48469
Backport of https://github.com/rancher/rancher/pull/48422

[v2.10] Backport Prevent Concurrency Updates SA

---

pkg/kontainer-engine/drivers/util/utils.go

issue: https://github.com/rancher/rancher/issues/48420
backport PR for : https://github.com/rancher/rancher/pull/48427

[release/v2.9] updated logic for creating cattle-system namespace

---

.github/workflows/validate.yml

https://github.com/rancher/rancher/issues/48661
The python install step was failing due to a problem with a mirror.
Run an update before installing pythong
* Unit
* None
_TODO_
* _TODO_

fix python install

---

.github/workflows/validate.yml

https://github.com/rancher/rancher/pull/48662
* Unit
* None
_TODO_
* _TODO_

[v2.10] fix python install backport #48662

---

.github/workflows/validate.yml

[v2.8] fix python install backport #48662

---

go.mod
go.sum

Includes new indexed fields for https://github.com/rancher/steve/pull/433

Bump steve to v0.5.1

---

.github/workflows/integration-tests.yml
.github/workflows/validate.yml
scripts/validate
tests/integration/tox.ini

* Multiple issues when installing python on a ubuntu runner
* Outdated and mismatched python version for tox
* Use containerized runner with a bci python image
* Upgrade python version for tox
* Unit
* None
_TODO_
* _TODO_

Fix python on validate and integration tests

---

.github/workflows/integration-tests.yml
.github/workflows/validate.yml
scripts/validate
tests/integration/tox.ini

backport: https://github.com/rancher/rancher/pull/48685
* Unit
* None
_TODO_
* _TODO_

[v2.9] fix python validate backport #48685

---

.github/workflows/integration-tests.yml
.github/workflows/validate.yml
scripts/validate
tests/integration/tox.ini

backport: https://github.com/rancher/rancher/pull/48685 
* Unit
* None
_TODO_
* _TODO_

[v2.10] fix python validate backport #48685

---

pkg/api/steve/catalog/plugin.go
pkg/controllers/dashboard/plugin/controller.go
pkg/controllers/dashboard/plugin/fscache_test.go
pkg/controllers/dashboard/plugin/index.go
pkg/controllers/dashboard/plugin/index_test.go

This PR makes it possible to call `/v1/uiplugins/{name}/{version}/{rest:.*}` while the caching is in progress

Plugin endpoint works while caching

---

.github/workflows/push-release.yml

* ecm distro tools is outdated 
* bump ecm distro tools to 0.47.0
* Unit
* None
_TODO_
* _TODO_

bump ecm distro tools to 0.47.0

---

go.mod
go.sum
pkg/ext/stores/install.go

Bump which includes the changes for https://github.com/rancher/rancher/issues/48430

Bump steve to v0.5.2

---

pkg/api/steve/catalog/plugin.go
pkg/controllers/dashboard/plugin/controller.go
pkg/controllers/dashboard/plugin/fscache_test.go
pkg/controllers/dashboard/plugin/index.go
pkg/controllers/dashboard/plugin/index_test.go

Backport of https://github.com/rancher/rancher/pull/48668

2.10 plugin endpoint works while caching

---

pkg/api/steve/catalog/plugin.go
pkg/controllers/dashboard/plugin/controller.go
pkg/controllers/dashboard/plugin/fscache_test.go
pkg/controllers/dashboard/plugin/index.go
pkg/controllers/dashboard/plugin/index_test.go

Backport of https://github.com/rancher/rancher/pull/48668

2.9 plugin endpoint works while caching

---

.github/workflows/push-release.yml

backport: https://github.com/rancher/rancher/pull/48748
* Unit
* None
_TODO_
* _TODO_

[v2.8] add artifacts distribution id

---

tests/scripts/custodian/Dockerfile

there was an issue with the if statement in the dockerfile

[main] correct formatting for bash if statement in custodian dockerfile

---

go.mod
go.sum
tests/v2/integration/steveapi/steve_api_test.go

BUmp steve to include this fix: https://github.com/rancher/steve/pull/451. Also add a test for regression.

Bump Steve to v0.5.3 and add links test

---

.github/workflows/push-release.yml
pkg/image/charts.go
pkg/image/charts_test.go
pkg/image/export/main.go
pkg/image/origins.go
pkg/image/origins/main.go
pkg/image/resolve.go
pkg/image/resolve_test.go
pkg/image/system_test.go
pkg/image/utilities/utilities.go
scripts/create-components-file.sh

* system charts are no longer used
* kubelr-kubectl was missing its origin
* Linting warnings
* remove system charts
* add origin
* update where it's possible
* Unit
* None
_TODO_
* _TODO_

Remove system charts from images origins

---

go.mod
go.sum
pkg/api/norman/customization/aks/handler.go
pkg/api/norman/customization/aks/listers.go

Issue: https://github.com/rancher/aks-operator/issues/751 (cherry picked from commit 377483f49d5db29238bf91a819534478d1927596)
* Unit
* None
_TODO_
* _TODO_

Add new AKS func listRegions for proxy UI

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/controllers/management/auth/manager.go
pkg/crds/yaml/generated/management.cattle.io_roletemplates.yaml

The `Administrative` field has been deprecated.
This strips out the functionality, and logs the name of affected resources indicating that it's not being used. 
* Unit
* None
_TODO_
* _TODO_

Strip out the Administrative functionality.

---

tests/v2/actions/provisioning/creates.go
tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
tests/v2/validation/pipeline/Jenkinsfile.recurring
tests/v2/validation/rbac/README.md
tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go

Backports
v2.10 https://github.com/rancher/rancher/pull/48741
v2,9 https://github.com/rancher/rancher/pull/48742
v2.8 https://github.com/rancher/rancher/pull/48742

<frozen> <main> Removed UpdateClusterName from the validation tests

---

.github/actions/install-yq/action.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

snap isn't working in the ubuntu 22 image
use the install yq action
* Unit
* None
_TODO_
* _TODO_

use install yq and update yq version

---

.github/actions/install-yq/action.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

* use install yq instead of snap
* update yq version
* add arch and use install yq for prs
* use sudo on install yq
* update use sudo
* fix condition
* Unit
* None
_TODO_
* _TODO_

[v2.8] use install yq and update yq version (#48869)

---

.github/actions/install-yq/action.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

* use install yq instead of snap
* update yq version
* add arch and use install yq for prs
* use sudo on install yq
* update use sudo
* fix condition
* Unit
* None
_TODO_
* _TODO_

[v2.9] use install yq and update yq version (#48869)

---

.github/actions/install-yq/action.yml
.github/workflows/pull-request.yml
.github/workflows/push-release.yml

Forward-port of #48869
N/A
N/A
N/A

[main] Use install-yq and update yq version

---

package/Dockerfile
pkg/settings/setting.go
scripts/package-env
tests/v2/codecoverage/package/Dockerfile

[v2.8] update charts branch references

---

pkg/auth/providers/common/provider.go
pkg/auth/requests/authenticate.go
pkg/auth/requests/authenticate_test.go
pkg/auth/requests/impersonate.go
pkg/auth/requests/impersonate_test.go
pkg/impersonation/impersonation.go
pkg/impersonation/impersonation_test.go
pkg/multiclustermanager/routes.go

The imperative API endpoints need to know the context (the auth provider, principal) of the token used to authenticate the request.
Pass the ID of token used to authenticate the request in user's Extras.
* Unit
N/A
N/A

Pass auth token id in user extras

---

tests/v2/actions/rbac/rbac.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/validation/rbac/grb/README.md
tests/v2/validation/rbac/grb/grb.go
tests/v2/validation/rbac/grb/grb_status_field_test.go

Automate tests in https://github.com/rancher/qa-tasks/issues/1649

[main] P0 tests for GH-44668

---

README.md

Update README to v2.10.2 stable

---

tests/v2/validation/steve/vai/README.md
tests/v2/validation/steve/vai/pod_filter_test_cases.go
tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/vai.go
tests/v2/validation/steve/vai/vai_test.go

Fixing vai tests after more drastic changes from dev on DB files for caching

fix vai tests

---

tests/v2/actions/clusters/clusterconfig.go
tests/v2/actions/clusters/clusters.go
tests/v2/actions/fleet/fleet.go
tests/v2/actions/kubeapi/workloads/deployments/deployments.go
tests/v2/actions/provisioninginput/config.go
tests/v2/validation/fleet/provisioning/networkisolation.go
tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go

https://github.com/rancher/qa-tasks/issues/1528
we don't have any tests around PNI
adding PNI test to existing provisioning fleet test, which works off of calico's default PNI rules

[main] add a test for PNI to fleet

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go
tests/v2/actions/provisioning/verify.go
tests/v2/validation/certrotation/cert_rotation.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

Backport of https://github.com/rancher/rancher/pull/48942.

[v2.10] Fix flaky release testing automation and QOL updates

---

tests/v2/actions/etcdsnapshot/creates.go
tests/v2/actions/etcdsnapshot/verify.go
tests/v2/actions/provisioning/verify.go
tests/v2/validation/certrotation/cert_rotation.go
tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke1_custom_cluster_test.go
tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
tests/v2/validation/provisioning/k3s/custom_cluster_test.go
tests/v2/validation/provisioning/k3s/hardened_cluster_test.go
tests/v2/validation/provisioning/k3s/provisioning_node_driver_test.go
tests/v2/validation/provisioning/k3s/psact_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go
tests/v2/validation/provisioning/rke1/custom_cluster_test.go
tests/v2/validation/provisioning/rke1/hardened_cluster_test.go
tests/v2/validation/provisioning/rke1/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke1/psact_test.go
tests/v2/validation/provisioning/rke2/ace_test.go
tests/v2/validation/provisioning/rke2/custom_cluster_test.go
tests/v2/validation/provisioning/rke2/hardened_cluster_test.go
tests/v2/validation/provisioning/rke2/provisioning_cloud_provider_test.go
tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
tests/v2/validation/provisioning/rke2/psact_test.go

Backport of https://github.com/rancher/rancher/pull/48942.

[v2.9] Fix flaky release testing automation and QOL updates

---

pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Original/Merged PR: https://github.com/rancher/rancher/pull/48739

[v2.9.7]Backport fix: remove Drained condition from machine status if schedulable

---

pkg/controllers/managementuser/nodesyncer/cordonfieldssyncer.go
pkg/controllers/managementuser/nodesyncer/nodessyncer.go

Original/Merged PR: https://github.com/rancher/rancher/pull/48739

[v2.10.3]Backport fix: remove Drained condition from machine status if schedable

---

pkg/auth/providers/saml/saml_actions.go
pkg/auth/providers/saml/saml_client.go
pkg/auth/providers/saml/saml_client_test.go
pkg/auth/providers/saml/saml_handlers.go
pkg/auth/providers/saml/saml_handlers_test.go
pkg/auth/providers/saml/saml_provider.go

Add addional unit tests for the saml provider

Expand SAML test coverage

---

pkg/auth/providers/publicapi/store.go
pkg/schemas/management.cattle.io/v3public/public_schema.go

[v2.9] Fix public authProviders endpoint

---

pkg/auth/providers/publicapi/store.go
pkg/schemas/management.cattle.io/v3public/public_schema.go

[v2.8] Fix public authProviders endpoint

---

tests/v2/actions/workloads/cronjob/cronjob.go
tests/v2/actions/workloads/cronjob/verify.go
tests/v2/actions/workloads/daemonset/verify.go
tests/v2/actions/workloads/deployment/deployment.go
tests/v2/actions/workloads/deployment/verify.go
tests/v2/actions/workloads/statefulset/statefulset.go
tests/v2/actions/workloads/statefulset/verify.go

Main issue: https://github.com/rancher/rancher/pull/48971

[backport 2.9] Workload fix

---

pkg/controllers/management/cluster/clustercontroller.go
pkg/controllers/management/clusterprovisioner/provisioner.go
pkg/controllers/management/clusterprovisioner/store.go
pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
pkg/controllers/management/etcdbackup/etcdbackup.go
pkg/controllers/managementuser/certsexpiration/certsexpiration.go
pkg/encryptedstore/secrets_store.go
pkg/nodeconfig/config.go
pkg/rkenodeconfigserver/lookup.go

Issue: https://github.com/rancher/rancher/issues/47999
Backport of: https://github.com/rancher/rancher/pull/46877

Backport fix: add owner reference to secret

---

pkg/auth/providers/publicapi/store.go
pkg/client/generated/management/v3public/zz_generated_auth_token.go
pkg/client/generated/management/v3public/zz_generated_client.go
pkg/schemas/management.cattle.io/v3public/public_schema.go

[v2.10] Fix public authTokens endpoint

---

pkg/auth/providers/publicapi/store.go
pkg/client/generated/management/v3public/zz_generated_auth_token.go
pkg/client/generated/management/v3public/zz_generated_client.go
pkg/schemas/management.cattle.io/v3public/public_schema.go

[v2.8] Fix public authTokens endpoint

---

pkg/controllers/provisioningv2/cluster/controller.go
pkg/controllers/provisioningv2/cluster/controller_test.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go
pkg/settings/setting.go

Backport for #46672 for release 2.10.3

[2.10] Disable automatic fleet agent installation

---

tests/v2/validation/steve/vai/README.md
tests/v2/validation/steve/vai/pod_filter_test_cases.go
tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/vai.go
tests/v2/validation/steve/vai/vai_test.go

Fixing vai tests after more drastic changes from dev on DB files for caching

fix vai tests v2.10

---

tests/v2/validation/steve/vai/README.md
tests/v2/validation/steve/vai/pod_filter_test_cases.go
tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/vai.go
tests/v2/validation/steve/vai/vai_test.go

Fixing vai tests after more drastic changes from dev on DB files for caching

fix vai tests v2.9

---

tests/v2/actions/machinepools/harvester_machine_config.go

https://github.com/rancher/qa-tasks/issues/1646
harvester for rke2 isn't working
add default userdata

add default userdata for harvester machine config

---

go.mod
go.sum

[v2.11] Bump steve to access vai-based label filtering.

---

go.mod
go.sum

[main] Change lasso & apiserver with tagged release

---

pkg/auth/providers/saml/saml_actions.go
pkg/auth/providers/saml/saml_client.go
pkg/auth/providers/saml/saml_client_test.go
pkg/auth/providers/saml/saml_handlers.go
pkg/auth/providers/saml/saml_handlers_test.go
pkg/auth/providers/saml/saml_provider.go

backport https://github.com/rancher/rancher/pull/48964

[v2.9] Expand SAML test coverage (#48964)

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

https://github.com/rancher/rancher/issues/48628 
https://github.com/rancher/rancher/issues/49033

[v2.11] update kdm branch to dev-v2.11 

---

tests/v2/validation/pipeline/Jenkinsfile.multibranch.recurring

rancher/qa-tasks/issues/1614
Recurring runs multibranch job branches and versions need to be updated.
Update branches and versions in multibranch recurring job.
Will be provided offline

[main] Update recurring runs branches and versions

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

Ref: https://github.com/rancher/rancher/issues/48986
https://github.com/rancher/kube-api-auth/releases/tag/v0.2.4
* 
N/A
N/A

[v2.10] Bump kube-api-auth to v0.2.4

---

pkg/apis/management.cattle.io/v3/tools_system_images.go

Forward-port of #49052 
* 
N/A
N/A

Bump kube-api-auth to v0.2.4 (#49052)

---

go.mod
go.sum

[release/v2.10] Update frameworks dependencies with latest releases

---

pkg/auth/providers/saml/saml_actions.go
pkg/auth/providers/saml/saml_client.go
pkg/auth/providers/saml/saml_client_test.go
pkg/auth/providers/saml/saml_handlers.go
pkg/auth/providers/saml/saml_handlers_test.go
pkg/auth/providers/saml/saml_provider.go

backport https://github.com/rancher/rancher/pull/48964

Expand SAML test coverage (#48964)

---

.github/workflows/push-release.yml

Automate release notification
* Unit
* None
_TODO_
* _TODO_

Automatic notification on tag success

---

pkg/auth/providers/ldap/ldap_provider.go
pkg/auth/providers/ldap/ldap_provider_test.go

Issue https://github.com/rancher/rancher/issues/49100
Backport of https://github.com/rancher/rancher/pull/49034

[v2.10] Handle nil openldapconfigs

---

.github/workflows/push-release.yml

A release may be announced before it's actually finished
Updating the notification job to account for the last job that runs on the workflow
* Unit
* None
_TODO_
* _TODO_

add installer manifest to notify needs

---

tests/v2/actions/rbac/rbac.go
tests/v2/validation/rbac/globalroles/README.md
tests/v2/validation/rbac/globalroles/global_roles_test.go
tests/v2/validation/rbac/globalroles/globalroles.go
tests/v2/validation/rbac/globalroles/rbac_global_roles_test.go

**Issue**: https://github.com/rancher/qa-tasks/issues/1345
**Note**: Backport PRs will be created once this gets approved

Migrate RBAC Global Role Tests

---

.github/workflows/push-release.yml

https://github.com/rancher/ecm-distro-tools/issues/523
https://github.com/rancher/rancher/pull/48774
* Unit
* None
_TODO_
* _TODO_

[v2.9] add notify-release job backport #48774

---

.github/workflows/push-release.yml

https://github.com/rancher/ecm-distro-tools/issues/523
https://github.com/rancher/rancher/pull/48774
* Unit
* None
_TODO_
* _TODO_

[v2.10] add notify-release job backport #48774

---

.github/workflows/push-release.yml

https://github.com/rancher/ecm-distro-tools/issues/523
https://github.com/rancher/rancher/pull/48774
* Unit
* None
_TODO_
* _TODO_

[v2.8] add notify-release job backport #48774

---

tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go

Back port https://github.com/rancher/rancher/pull/48853

[2.8] Updating tags for the cluster templates provisioning tests

---

tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go

Back port https://github.com/rancher/rancher/pull/48853

[2.9] Updating tags for the cluster templates provisioning tests

---

tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go

Back port https://github.com/rancher/rancher/pull/48853

[2.10] Updating tags for the cluster templates provisioning tests

---

tests/v2/actions/rbac/rbac.go
tests/v2/validation/rbac/globalroles/README.md
tests/v2/validation/rbac/globalroles/global_roles_test.go
tests/v2/validation/rbac/globalroles/globalroles.go
tests/v2/validation/rbac/globalroles/rbac_global_roles_test.go

Backport https://github.com/rancher/rancher/pull/48904

[v2.10] Migrate RBAC Global Role Tests

---

tests/v2/actions/rbac/rbac.go
tests/v2/validation/rbac/globalroles/README.md
tests/v2/validation/rbac/globalroles/global_roles_test.go
tests/v2/validation/rbac/globalroles/globalroles.go
tests/v2/validation/rbac/globalroles/rbac_global_roles_test.go

Backport https://github.com/rancher/rancher/pull/48904

[v2.9] Migrate RBAC Global Role Tests

---

tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/vai_test.go

vai main updates

---

tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/vai_test.go

vai v2.10 updates

---

tests/v2/validation/steve/vai/README.md
tests/v2/validation/steve/vai/scripts/script.sh
tests/v2/validation/steve/vai/vai_test.go

vai v2.9 updates

---

package/Dockerfile
pkg/data/management/machinedriver_data.go

Bump docker-machine-driver-harvester to v1.0.0.
* Unit
* None
_TODO_
* _TODO_

feat: bump docker-machine-driver-harvester to v1.0.0

---

pkg/auth/providers/oidc/oidc_actions.go

Once this PR is merged, the UI team can start working on this: https://github.com/rancher/dashboard/issues/12853
cc @rak-phillip, @jp-gouin
We are currently overriding the `GroupSearchEnabled` attribute when we configure an OIDC auth provider.
So doesn't matter if we set `GroupSearchEnabled` to true, since this value will be override in the code if the user does not have any groups.
Remove the overriding code, and replace it with a default value when the user doesn't provide any input for the `GroupSearchEnabled`.
Setup ngrok to have a fixed endpoint for the OIDC server:
```
ngrok http http://localhost:8090
```
Setup a local OIDC server:
```
docker run -it --rm -p 8090:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KEYCLOAK_LOGLEVEL=DEBUG -e …
```

fix: allow user to set groupSearchEnabled on/off

---

pkg/image/origins.go

This adds a new image we'll soon be using to origins file.

[v2.10] Add kuberlr-kubectl to image origins file

---

pkg/image/origins.go

This adds a new image we'll soon be using to origins file.

[v2.9] Add kuberlr-kubectl to image origins file

---

tests/scripts/custodian/azure.yaml

noticed that NSGs are now our largest spend in azure, and there's support for tagging in custodian for it.

adding azure.nsg to custodian

---

pkg/controllers/capr/plansecret/plansecret.go

https://github.com/rancher/rancher/issues/49162
When a plan is failing to apply, an unfamiliar user may not be aware of the corresponding `k3s`, `k3s-agent`, `rke2-server` and `rke2-agent` services that should be checked on a node.
Add the corresponding unit for the node to the error message that is displayed in the UI
* Unit
* None
_TODO_
* _TODO_

[main] Make provisioning log messages provide which unit should be checked

---

build.yaml
pkg/buildconfig/constants.go

Per title, this is to un-RC after QA test.
https://github.com/rancher/shell/issues/314

[2.10] Unrc the Shell image version

---

build.yaml
pkg/buildconfig/constants.go

Per title, this is to un-RC after QA test.
https://github.com/rancher/shell/issues/315

[2.9] Unrc the Shell image version

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/47934
* Unit
* None
_TODO_
* _TODO_

[main] updated rancher dev version to 2.11.99

---

pkg/controllers/capr/machineprovision/args.go

https://github.com/rancher/rancher/issues/49132
https://github.com/harvester/harvester/issues/4089
The Harvester node driver requires the name of the cluster.
Add the cluster name as additional node driver argument. To simplify the implementation and to do not impact other node drivers, this argument is only added for the `Harvester` node driver.
```
Name: harv02-pool1-663190a9-xz7pk-machine-provision-fqxnb
...
Controlled By: Job/harv02-pool1-663190a9-xz7pk-machine-provision
Containers:
machine:
Image: rancher/machine:v0.15.0-rancher112
...
Args:
--driver-download-url=https://rancher.<REDACTED>.sslip.io/assets/docker-machine-driver-harvester
--driver-hash=08e6df22587687866d69be274952783d8bfbf5e6cbec0cdb3a2d95f3b42aa305
--secret-namespace=fleet-default …
```

Add cluster name as command line argument to the node driver

---

build.yaml
pkg/buildconfig/constants.go
tests/v2prov/tests/fleet/fleetcluster_test.go

Fix fleet tests

---

chart/templates/deployment.yaml
chart/tests/deployment_test.yaml
chart/values.yaml
pkg/features/feature.go

https://github.com/rancher/rancher/issues/49254
* Unit
* None
_TODO_
* _TODO_

[main] Enable imperative api

---

go.mod
go.sum

Related to #48965. (Ignore the branch name - I used the epic instead of the issue)

Bump steve to v0.5.8 so complex label names are handled correctly.

---

pkg/controllers/management/authprovisioningv2/cluster.go
pkg/controllers/management/authprovisioningv2/cluster_test.go

This refreshes cluster and project role template bindings when moving a cluster to a different namespace, regardless of the Kubernetes distribution powering that cluster.
This was previously done only for RKE clusters, but we have since discovered that not doing it for k3s clusters would subject them to issues where users would lose access to a cluster after it had been moved to a different workspace.
[fleet#3197](https://github.com/rancher/rancher/issues/49269)
After moving a cluster from one workspace to another, users lose access to the cluster.
This happens both to users listed as cluster owners or members, and to users listed as members on projects living in that cluster.
When updating a provisioning cluster, refresh both cluster role template bindings and project role template …

Enqueue role template bindings for all k8s distros

---

go.mod
go.sum

Related to #46333
Related to #48603
Related to #48965

Bump steve to v0.5.9 to fix three issues.

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

https://github.com/rancher/rancher/issues/49315
Bump the system-agent to add the support for  k8s 1.32

bump system-agent to v0.3.12-rc.1 

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/generated/management/v3/zz_generated_network_config.go

[release/v2.10] bump rke to v1.7.4-rc.3

---

build.yaml
pkg/buildconfig/constants.go

Per title, this is follow up after QA validated the RC shell image.
https://github.com/rancher/shell/issues/313

[main] Unrc the Shell image version

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

using https://github.com/rancher/charts-small-fork in TestUpgradeChartToLatestVersion

using smallfork in TestUpgradeChartToLatestVersion

---

pkg/capr/planner/certificaterotation.go
pkg/capr/planner/certificaterotation_test.go
pkg/capr/planner/planner.go
pkg/capr/planner/windows.go

This is a backport of https://github.com/rancher/rancher/pull/49071 for 2.10

[2.10] Deliver windows specific idempotent script

---

pkg/data/management/role_data.go

Backport of https://github.com/rancher/rancher/pull/49391

[v2.9] Update builtin roletemplate

---

pkg/data/management/role_data.go

Backport of https://github.com/rancher/rancher/pull/49391

[v2.8] Update builtin roletemplate

---

pkg/rancher/migrations.go
pkg/rancher/migrations_test.go

What I had worked, but was untestable without building a bunch of images from source. 
This will be testable by setting the `CATTLE_SERVER_VERSION` env var now.
Tested manually, and updated existing tests.
Rest of template can be found here: https://github.com/rancher/rancher/pull/47235

Fix version tombstone

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/client/go.mod
pkg/client/go.sum

Steve contains the fix for the issue above where we were not considering the clusterroles/roles of serviceaccounts correctly.
Also bumps apiserver and norman for newer 2.12 version

Bump Steve, norman and apiserver

---

.github/actions/setup-tag-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml

The `main` branch now points to the future v2.12 version
* Unit
* None
_TODO_
* _TODO_

update tags to v2.12

---

.github/workflows/push-release.yml

[release-v2.11] fix push-release token permissions

---

pkg/auth/providers/common/usermanager.go

Issue: https://github.com/rancher/rancher/issues/49484
backport https://github.com/rancher/rancher/pull/49476

[2.11] Always register auth.management.cattle.io/userByPrincipal index

---

.github/workflows/push-release.yml

add charts cloudfront env

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

Switch KDM branch to release-v2.10

---

tests/validation/Dockerfile.v3api

QA is pointing to the release/v2.8 branch and using the old Python ha_deploy test to create HA rancher instances. There is currently a problem with this section of the Dockerfile, as all of the jobs using it are failing with:
```
[91mE: Failed to fetch http://deb.debian.org/debian/pool/main/e/easy-rsa/easy-rsa_3.1.0-1_all.deb  Connection failed [IP: <redacted>]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/pkcs11-helper/libpkcs11-helper1_1.29.0-1_amd64.deb  Connection failed [IP: <redacted>]
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/opensc/opensc_0.23.0-0.3%2bdeb12u2_amd64.deb  Connection timed out [IP: <redacted>]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[0mThe command '/bin/bash -c if [[ -z …
```

Remove failing VPN configuration from Dockerfile

---

tests/validation/tests/v3_api/test_certificate.py

Resolve python tests to fix cert issuer change from E6 to E5

Resolve python tests to fix cert issuer changes

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

[v2.8] Bump Rancher CLI to v2.8.14

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

Rancher CLI points to an RC version.
UnRC Rancher CLI.
* 
N/A

Bump Rancher CLI to v2.11.0

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

[v2.10] Bump Rancher CLI to v2.10.4

---

build.yaml
pkg/buildconfig/constants.go

Depends on charts PR [#5419](https://github.com/rancher/charts/pull/5419)

Bump Webhook to v0.7.0 (un-rc)

---

chart/templates/extra-manifests.yaml
chart/templates/ingress.yaml
chart/templates/service.yaml
chart/tests/ingress_test.yaml
chart/tests/service_test.yaml
chart/values.schema.json
chart/values.yaml

Backport for 2.11
* Unit
* None
_TODO_
* _TODO_

[2.11][chart] Add new options for Rancher default service hardening

---

pkg/ext/certs.go
pkg/ext/extension_apiserver.go

Avoid infinite loop on Ext. API cert rotation on watcher error

---

.github/ISSUE_TEMPLATE/epic.md

Adding new issue type for project managers of Rancher.

New issue type: epic.md

---

.github/workflows/manual.yml
.github/workflows/port-issue.yml

- Fixes the secret being used, similar to rancher/fleet#2016
- Rename the file for consistency
- Use a more specific check for the comment body

ci(backports): fix backports action

---

pkg/controllers/provisioningv2/machineconfigcleanup/controller.go

https://github.com/rancher/rancher/issues/48367

[v2.11] Add context for machine config cleanup job

---

pkg/controllers/managementuser/resourcequota/resource_quota_sync.go
pkg/controllers/managementuser/resourcequota/resource_quota_sync_test.go

The user wasn't able to set Limits or Requests for namespace when it wasn't previously defined in project. 
We changed the logic to the user be able to set the values in namespace and when some value is missing, we copy it from project, this way project values work like default values.
The repro steps are in the original issue. For the testing, I suggest you to create a new project in the UI and then set some values for Limits or Requests. Then after, create a namespace in that project and add other values. The values you add in namespace will be the ones set, but in case you don't set one or more of them, it will copy it from project if you previously defined it in there.

 [v2.10] #45641 - Adjusted Resource Limit Logic

---

pkg/controllers/managementuser/resourcequota/resource_quota_sync.go
pkg/controllers/managementuser/resourcequota/resource_quota_sync_test.go

[v2.11] #45641 - Adjusted Resource Limit Logic

---

tests/v2/integration/catalogv2/cluster_repo_test.go
tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Issue: https://github.com/rancher/rancher/issues/45807
Disabling both tests while looking for a fix and disabling RancherManagedChartsTest suite

Disable `TestRancherManagedChartsSuite` and `TestGitRepoRetries` for now

---

go.mod
go.sum
pkg/api/norman/customization/aks/handler.go
pkg/api/norman/customization/aks/listers.go

issue: https://github.com/rancher/aks-operator/issues/959
backport PR for https://github.com/rancher/rancher/pull/48716

[release/v2.10] Add new AKS func listRegions for proxy UI

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml

Backport of https://github.com/rancher/rancher/pull/49760

[v2.9] Add backingnamespace field to projects

---

pkg/catalogv2/system/system.go
tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Issue : https://github.com/rancher/rancher/issues/45807

Revert change to error returned while installing chart

---

tests/v2/integration/catalogv2/rancher_managed_charts_test.go

Issue : https://github.com/rancher/rancher/issues/49457

Skip the failing test until it is resolved

---

pkg/catalogv2/git/download.go
pkg/catalogv2/git/download_test.go

Backporting this unit test fix to 2.8 since we're seeing it on other PRs like https://github.com/rancher/rancher/pull/49776
Original https://github.com/rancher/rancher/pull/49601

[v2.8] Fix download unit test

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml

Backport of https://github.com/rancher/rancher/pull/49760

[v2.8] Add backingnamespace field to projects

---

pkg/controllers/provisioningv2/machineconfigcleanup/controller.go

Backport PR for https://github.com/rancher/rancher/pull/49698. 
Issue: https://github.com/rancher/rancher/issues/49824

[v2.10] Add context for machine config cleanup job 

---

pkg/controllers/provisioningv2/machineconfigcleanup/controller.go

Forward port PR for https://github.com/rancher/rancher/pull/49698. 
Issue: https://github.com/rancher/rancher/issues/49825

[main] Add context for machine config cleanup job

---

package/Dockerfile

Update to Dashboard refs to v2.10.5-alpha2

---

package/Dockerfile

Update to Dashboard refs to v2.11.1-alpha2

---

pkg/apis/management.cattle.io/v3/authz_types.go
pkg/client/generated/management/v3/zz_generated_project.go
pkg/client/generated/management/v3/zz_generated_project_status.go
pkg/crds/yaml/generated/management.cattle.io_projects.yaml

Reverts rancher/rancher#49776
This will not be backported to 2.8

Revert "[v2.8] Add backingnamespace field to projects"

---

pkg/api/norman/customization/globalnamespaceaccess/access_common.go
pkg/api/norman/server/managementstored/setup.go
pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go
pkg/apis/management.cattle.io/v3/authz_types.go
pkg/controllers/management/auth/crtb_handler.go
pkg/controllers/management/auth/crtb_handler_test.go
pkg/controllers/management/auth/project_cluster_handler.go
pkg/controllers/management/auth/prtb_handler.go
pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/secret/secret.go
pkg/systemaccount/systemaccount.go
tests/integration/suite/test_app.py
tests/integration/suite/test_catalog.py
tests/integration/suite/test_project_catalog.py
tests/integration/suite/test_rbac.py

Backport of https://github.com/rancher/rancher/pull/49797

[v2.9] Add project namespace handling

---

go.mod

This removes no-op and not needed go.mod changes introduced in #49848
N/A

[v2.11] Undo unneeded go.mod changes

---

pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go

Issue: https://github.com/rancher/rancher/issues/49942
backport https://github.com/rancher/rancher/pull/49944

[2.10] Fix projectId for downstream clusters

---

pkg/api/norman/store/scoped/store.go
pkg/api/norman/store/scoped/store_test.go

backport https://github.com/rancher/rancher/pull/49944

[v2.9] Fix projectId for downstream clusters

---

pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go

A restricted admin can't see/edit users.
When introducing a the project backing namespace (https://github.com/rancher/rancher/pull/49797), `main` does not contain code handling restricted admin since it was deprecated and removed. That meant that I missed the code providing restricted admins access to project management plane resources, such as Users, so it was creating rolebindings in a namespace that no longer exists.
I added new code to ensure that the right namespace is used. It allows Users to be seen in the UI and fixes an issue where there was an error in the `Cluster Members` tab as well.
The steps in the issue are accurate
Create a restricted admin and some other dummy users.
Log in as the restricted admin
All the users are visible in the `Users` tab …

[v2.10] Grant RestrictedAdmin project management plane access

---

pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go

Backport of https://github.com/rancher/rancher/pull/49969

Grant RestrictedAdmin project management plane access (#49969)

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This PR un-rc's rancher-wins to version `0.5.1`

[2.11] un-rc rancher-wins v0.5.1

---

package/Dockerfile
package/windows/Dockerfile.agent
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

This PR un-rc's rancher-wins to version `0.5.1`

[main] un-rc rancher-wins v0.5.1

---

.github/workflows/push-release.yml

[v2.11] upload images files to s3

---

.github/workflows/push-release.yml

[v2.11] fix bucket secret end of line

---

pkg/catalogv2/oci/oci.go

OCI registries don't support + as a tag character. Helm adopts the convention of changing plus (+) to an underscore (_) in chart version tags when pushing to a registry. Therefore it is required to convert underscores in tags back to + same as Helm does when pulling from the registry.
Issue https://github.com/rancher/rancher/issues/48746
As described in the issue
Convert undescores back to plus when reading tags from the registry
1. Add oci://registry.opensuse.org/isv/suse/edge/factory/totest/charts/metallb-chart clusterrepo as 'metallb-obs-totest'
2. List the entries via Rancher API
```
curl 'https://<RANCHER_API>/v1/catalog.cattle.io.clusterrepos/metallb-obs-totest?link=index' -H 'Accept: application/json' -H 'Cookie: R_SESS=token-<token>' --insecure …
```

OCI: Change underscore (_) to plus (+) before checking if the tag is a valid semver

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

bump cli version to v2.10.5

---

package/Dockerfile
tests/v2/codecoverage/package/Dockerfile

bump cli version to v2.11.1

---

pkg/catalogv2/oci/oci.go

OCI registries don't support + as a tag character. Helm adopts the convention of changing plus (+) to an underscore (_) in chart version tags when pushing to a registry. Therefore it is required to convert underscores in tags back to + same as Helm does when pulling from the registry.
Cherry-picked from:  98507a569
Fixes: https://github.com/rancher/rancher/issues/50022
Original issue: https://github.com/rancher/rancher/issues/48746
Original PR: https://github.com/rancher/rancher/pull/49268

[backport 2.11] Change underscore (_) to plus (+) before checking if the tag is a valid semver

---

README.md

Update README.md to include v2.11.1 stable

---

pkg/controllers/capr/unmanaged/controller.go

**Do Not Merge Until v2.10.5 is released.** 
Issue:  https://github.com/rancher/rancher/issues/49984
Cherry-pick from https://github.com/rancher/rancher/pull/49923

[2.10] [Backport] Fix flaky-test Test_Provisioning_Custom_ThreeNodeWithTaints

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Bump system-agent to v0.3.13-rc.1

---

tests/v2/integration/catalogv2/cluster_repo_test.go

Issue https://github.com/rancher/rancher/issues/49668

When there is a failure dump the clusterRepo for debbuging the integration test

---

build.yaml
pkg/buildconfig/constants.go

https://github.com/rancher/shell/issues/343
This is for 2.11.2 - not 2.11.1.

[v2.11] Bump Shell for regular updates

---

pkg/controllers/dashboard/systemcharts/controller.go
pkg/controllers/dashboard/systemcharts/controller_test.go

[v2.11] #49252 - Uninstalling RDP when Imperative API is off

---

tests/v2prov/operations/etcdsnapshot.go

Check s3 annotation as well if target node is s3

---

scripts/gha/tests
scripts/provisioning-tests
scripts/test

Wait for the api-extension deployment for the remotedialer-proxy.

---

pkg/catalogv2/content/content.go

checking if version is dev instead of release to skip filter

---

pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/rbac/namespace_handler_test.go

If a namespace references a project that doesn't exist, this will fail to find the project, and the resulting error will continue to cause requeues.
This adds additional logging and error messages, and does not error in the not found case.
Modify a namespace to reference a non-existent project and it will fail repeatedly.
* Unit
* None
_TODO_
* _TODO_

Issue 50046 error improvements

---

pkg/catalogv2/content/content.go

Revert "checking if version is dev instead of release to skip filter"

---

.github/actions/images-files/generate/action.yml
.github/workflows/hotfix-release.yml
.github/workflows/release.yml

The shell argument was declared two times in the images files generate template and `build-server` isn't necessary to build the agent anymore.
Remove the duplicated shell arg and remove the `build-server` `needs`
* Unit
* None
_TODO_
* _TODO_

[v2.12] fix images files action

---

pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/rbac/namespace_handler_test.go

Forward port of https://github.com/rancher/rancher/pull/50110
If a namespace references a project that doesn't exist, this will fail to find the project, and the resulting error will continue to cause requeues.
This adds additional logging and error messages, and does not error in the not found case.
Modify a namespace to reference a non-existent project and it will fail repeatedly.
* Unit
* None
_TODO_
Existing / newly added automated tests that provide evidence there are no …

Handle errors issue

---

pkg/catalogv2/oci/oci.go
tests/v2/integration/catalogv2/cluster_repo_test.go

[v2.11] Backport 49929

---

pkg/catalogv2/oci/oci.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Backport of https://github.com/rancher/rancher/issues/49929 to 2.10

[v2.10] Backport 49929

---

Dockerfile.dapper
package/Dockerfile
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

https://github.com/rancher/rancher/issues/50223
Adjust KDM branch to dev-2.12 and RancherVersionDev to "2.12.99"

[v2.12] Adjust KDM branch to dev-v2.12 and RancherVersionDev to "2.12.99"

---

pkg/controllers/managementuser/rbac/namespace_handler.go
pkg/controllers/managementuser/rbac/namespace_handler_test.go

Issue https://github.com/rancher/rancher/issues/50244
Backport of https://github.com/rancher/rancher/pull/50112
Cleaned up some imports in the unit tests that hadn't previously been ported.

[v2.9] Handle errors issue (#50112)

---

.github/actions/images-digests/publish-gh/action.yml
.github/actions/images-files/publish-gh/action.yml
.github/workflows/pull-request.yml

The shell property is missing from the publish gh action
add the shell property
* Unit
* None
_TODO_
* _TODO_

[v2.12] add missing shell on artifacts upload and ignore readme on pull requests

---

.github/workflows/hotfix-release.yml
.github/workflows/release.yml

The GH cli version was not set
Add the gh cli version to the workflow 
* Unit
* None
_TODO_
* _TODO_

[main] add gh cli version to release workflows

---

.github/workflows/push-release.yml

The upload secrets were incorrect
* Unit
* None
_TODO_
* _TODO_

[v2.11] fix artifacts upload secrets

---

.github/workflows/push-release.yml

[v2.10] fix artifacts upload secrets

---

.github/workflows/push-release.yml

[v2.9] fix artifacts upload secrets

---

.github/actions/images-files/generate/action.yml
.github/actions/images-files/publish-aws/action.yml
.github/actions/images-files/publish-gh/action.yml
.github/actions/rancher-chart/publish-aws/action.yml
.github/workflows/hotfix-release.yml
scripts/artifacts-hashes.sh

The artifacts hashes script and upload secrets were not up-to-date
Update the script and secrets
* Unit
* None
_TODO_
* _TODO_

[v2.12] update artifacts hashes script and secrets

---

go.mod
go.sum

Bump steve to v0.4.7, backport 50260 fix to v2.10

---

.github/actions/build-images/installer/action.yml
.github/actions/setup-build-env/action.yml
.github/workflows/hotfix-release.yml
.github/workflows/release.yml
package/Dockerfile.installer
scripts/version

[#49738](https://github.com/rancher/rancher/issues/49738)
The chart on the installer was marked as `dirty` and some steps were just not needed anymore, as described below.
* While building the chart for the installer docker image, the repo was just partially copied, which caused the version to be marked as dirty.
* After changing the installer dockerfile to build the chart and setup helm inside the build stage, building the rancher server wasn't a dependency anymore
* update the version script to use a pre-defined chart version if it is defined
* remove the unused upload and download chart steps
* remove the rancher-server dependency from the installer build job
Build the docker image
```
export TAG=v2.12.0-debug.1
docker buildx build --build-arg VERSION=$TAG --build-arg ARCH=amd64 --tag …
```

fix rancher tag on installer

---

.github/actions/build-images/server/action.yml
package/Dockerfile
pkg/version/version.go
pkg/version/version_test.go

Forwardport: https://github.com/rancher/rancher/pull/50149
* Unit
* None
_TODO_
* _TODO_

[v2.11] forwardport update branding vars

---

.github/actions/notify-release/action.yml
.github/workflows/release.yml

Add the release notification back
* Unit
* None
_TODO_
* _TODO_

[v2.10] add notify release

---

.github/workflows/release.yml

[v2.10] fix notify indentation

---

.github/actions/build-images/server/action.yml
package/Dockerfile

Backport: https://github.com/rancher/rancher/pull/50336
* Unit
* None
_TODO_
* _TODO_

[v2.10] don't set the base registry env

---

.github/actions/build-images/server/action.yml
package/Dockerfile

The `CATTLE_BASE_REGISTRY` env var already has a default value, and setting it causes unwanted side effects.
Don't set the env var during build time
* Unit
* None
_TODO_
* _TODO_

[main] don't set the base registry env

---

.github/actions/build-images/server/action.yml
package/Dockerfile

Backport: https://github.com/rancher/rancher/pull/50336
* Unit
* None
_TODO_
* _TODO_

[v2.11] don't set the base registry env

---

build.yaml
pkg/buildconfig/constants.go

This was [signed off by QA 2](https://github.com/rancher/shell/issues/343#issuecomment-2857436769) weeks ago but slipped my mind, so here's the last minute unRC. 😅

[v2.11] unRC the Shell version

---

README.md

update stable version to v2.11.2

---

.github/actions/build-images/agent/action.yml
.github/actions/rancher-chart/publish-aws/action.yml
.github/workflows/push.yml
.github/workflows/release.yml

backport #50487
* Unit
* None
_TODO_
* _TODO_

[v2.9] use registry vars backport #50487

---

.github/actions/build-images/agent/action.yml
.github/actions/rancher-chart/publish-aws/action.yml
.github/workflows/push.yml
.github/workflows/release.yml

backport #50487
* Unit
* None
_TODO_
* _TODO_

[v2.10] use registry vars backport #50487

---

go.mod
go.sum

Bump steve to v0.5.15

---

pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler_test.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
pkg/controllers/managementuser/rbac/roletemplate_handler.go

Issue: https://github.com/rancher/rancher/issues/50536
Backport of https://github.com/rancher/rancher/pull/50533

[V2.10] Prevent unnecessary updates to promoted clusterroles (#50533)

---

pkg/controllers/managementuser/rbac/prtb_handler.go
pkg/controllers/managementuser/rbac/prtb_handler_test.go
pkg/controllers/managementuser/rbac/reconcile_roletemplate.go
pkg/controllers/managementuser/rbac/roletemplate_handler.go

Issue: https://github.com/rancher/rancher/issues/50535
Backport of https://github.com/rancher/rancher/pull/50533

[v2.11] Prevent unnecessary updates to promoted clusterroles (#50533)

---

.github/workflows/push.yml
.github/workflows/release.yml

Merge manifests jobs were renamed, and some jobs were still requiring them
Remove or rename needs options
* Unit
* None
_TODO_
* _TODO_

[main] fix merge manifests needs on release workflows

---

package/Dockerfile

Update to Dashboard refs to v2.12.0-alpha3

---

pkg/auth/providers/publicapi/login.go

If the request is prematurely canceled during the login the code that ensures the user and the corresponding userattribute exist may fail with 
```
[ERROR] API error response 500 for POST /v3-public/activeDirectoryProviders/activedirectory?action=login. Cause: error creating or updating user and/or userAttribute for activedirectory_user://<...>: context canceled
```
Don't take the request's context in into the consideration after we successfully authenticated with the provider. Additionally on the UI side we need to prevent cancellation from happening i.e. default form submission that leads to the page reload.
N/A

Fix createLoginToken

---

pkg/controllers/management/agentupgrade/controller.go
pkg/controllers/management/clusterdeploy/clusterdeploy.go
pkg/controllers/management/usercontrollers/controller.go
pkg/settings/setting.go
pkg/systemtemplate/template.go

ref: https://github.com/rancher/rancher/issues/50459

[main] remove node agent references

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

Backport of https://github.com/rancher/rancher/pull/50482 to `release/v2.11`

(backport of #50482) fix: add create secrets permissions in fleet-default namespace

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
package/Dockerfile
package/Dockerfile.installer
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/package/Dockerfile.agent

* create images files secrets were missing a `;` at the end
* bci-latest was updated and is failing 
* Unit
* None
_TODO_
* _TODO_

[v2.10] fix secrets and update bci-base versions to 15.7

---

.github/workflows/hotfix-release.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
package/Dockerfile
package/Dockerfile.installer

Backport:  #50694 
* Unit
* None
_TODO_
* _TODO_

[v2.11] Update bci-base and bci-micro to 15.7 and fix secrets

---

.github/actions/images-files/generate/action.yml

* the registry env var must be empty to create images files
* ensure the registry env var is empty in this step
* Unit
* None
_TODO_
* _TODO_

fix registry for components images files

---

pkg/catalogv2/system/system.go

Issue : https://github.com/rancher/rancher/issues/50243
Backport of #50176 to 2.11

[v2.11] Backport 50176

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

Revert "(backport of #50482) fix: add create secrets permissions in fleet-default ns"

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

Revert "fix: add create secrets permissions in fleet-default namespace"

---

.github/actions/build-artifacts-index/action.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
package/Dockerfile
package/Dockerfile.agent
package/Dockerfile.installer

Backport: https://github.com/rancher/rancher/pull/50693
Backport: https://github.com/rancher/rancher/pull/50732
* Unit
* None
_TODO_
* _TODO_

[v2.9] update bci images to 15.7 and fix artifacts index

---

.github/actions/rancher-chart/build/action.yml
.github/workflows/push.yml
scripts/chart/index
scripts/version

Using an outdated helm chart with a newer head image, could lead to failures
Build and publish a helm index for head images
When a PR is merged, a chart will be built, packaged and a new index will be pushed to the repo. Only the latest chart will be on the index.
```
└── release-2.12
├── index.yaml
└── rancher-2.12-88873acc334b7406228ece0c313e9232de2610bb-head.tgz
└── rancher-2.12-665cd3dec3cc5eaea01801931d2b81ae56a26144-head.tgz
```
* Unit
* None
_TODO_
Existing / newly added …

publish charts for head images

---

pkg/image/origins.go

add compliance-operator origin

---

pkg/ext/stores/tokens/tokens_test.go

The watch tests used a select+delay/timeout construction to wait on the channel and assert that an event was not generated or received. This made the unit tests run slow (~9*5 seconds), and on some platforms was able to trigger a global timeout/abort of the suite.
Rewriting the watch tests to not use select+timeout. Taken the idea from the ext kubeconfig tests an additional sentinel event is used to be able to always read at least one event from the channel. By verifying that the received event is the sentinel we can be sure that any preceding events were swallowed as expected.
Changed unit tests.
* Unit
* None
* _REMOVE NOT APPLICABLE BULLET …

Ext tokens - reworked watch unit tests to not require delay waiting

---

.github/actions/rancher-chart/publish-aws/action.yml
.github/workflows/push.yml
.github/workflows/release.yml
scripts/chart/index
scripts/version

Backport: #50779
* Unit
* None
_TODO_
* _TODO_

[v2.10] backport head charts

---

Dockerfile.dapper
package/Dockerfile
pkg/rkecerts/certs_test.go
pkg/settings/setting.go
scripts/gha/tests
scripts/provisioning-tests
scripts/test
tests/v2/codecoverage/package/Dockerfile
tests/v2/codecoverage/scripts/build-rancher.sh
tests/v2/codecoverage/scripts/run_provisioning_integration_tests.sh

[v2.11] update kdm branch to dev-v2.11

---

package/Dockerfile

update dashboard version to v2.12.0-alpha11

---

scripts/chart/build

Forwardport: #50888
* Unit
* None
_TODO_
* _TODO_

forwardport add registry check to chart build (#50888)

---

.github/actions/setup-build-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/provisioning-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push.yml
.github/workflows/release.yml
.github/workflows/security-release.yml

Backport: #50810
* Unit
* None
_TODO_
* _TODO_

[v2.11] backport security workflow #50810

---

pkg/controllers/management/clusterstats/statsaggregator.go

[backport v2.11] Add quiet period between clusterstats executions for the same cluster

---

.github/actions/images-files/generate/action.yml
.github/actions/rancher-chart/build/action.yml
.github/actions/setup-build-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml
.github/workflows/push.yml
.github/workflows/release.yml
.github/workflows/security-release.yml

Backport: #50810
* Unit
* None
_TODO_
* _TODO_

[v2.10] backport security workflow #50810

---

.github/workflows/release.yml
.github/workflows/security-release.yml

Backport:#50810
* Unit
* None
_TODO_
* _TODO_

[v2.9] backport security workflow #50810

---

pkg/controllers/managementuser/secret/secret.go

Backport of https://github.com/rancher/rancher/pull/50773

Use the right namespace when getting projects and namespaces (#50773)

---

pkg/apis/ext.cattle.io/v1/types.go
pkg/ext/stores/kubeconfig/store.go
pkg/ext/stores/kubeconfig/store_test.go
pkg/generated/openapi/zz_generated_openapi.go

https://github.com/rancher/rancher/issues/50934
A typo in the validation message.
Fix the typo.
* Unit
N/A

kubeconfigs: Fix typo in validation message

---

.github/workflows/push.yml

Backport: https://github.com/rancher/rancher/pull/50951
* Unit
* None
_TODO_
* _TODO_

[v2.10] backport add registry to build server

---

pkg/apis/rke.cattle.io/v1/rkemachine_types.go
pkg/crds/names.go
pkg/crds/yaml/generated/rke.cattle.io_custommachines.yaml

`kubectl explain custommachines.rke.cattle.io` does not have meaningful output
Add proper comments and kube builder markers to improve `kubectl explain custommachines.rke.cattle.io`. The only new validators added are being pulled in from upstream directly.
Confirm that `kubectl explain custommachines.rke.cattle.io` provides meaningful output. 
Test provisioning a custom cluster with one or more nodes, upgrade the k8s version of the cluster, delete the cluster.
Confirm that the `capi-controller-manager` pod in the local cluster does not report errors when processing this CRD. 
I've done the above.
* Unit
* None
* _REMOVE NOT APPLICABLE BULLET …

[main] CustomMachine public API

---

pkg/scc/controllers/common/reconcilers.go
pkg/scc/controllers/controller.go
pkg/scc/controllers/offline.go
pkg/scc/controllers/online.go
pkg/scc/operator.go
pkg/scc/suseconnect/wrapper.go
pkg/scc/systeminfo/exporter.go
pkg/scc/systeminfo/secret/metrics.go

This only seemed to be an issue where panics happened in docker deploys which UI team uses for development. So while not officially supported for end-users we need to keep it working for internal development still.
This also fixes other misc issues we found and were reported in slack threads today.
- Fix root of UI panic
- Fix missing error context for conditions
- Remove unused metrics code
- Add metrics debug secret

[main][scc] Fixes for panics seen in UI debug workflows

---

Dockerfile.dapper
dev-scripts/quick

In #51019 an error was introduced that was preventing to properly populate `TAG` env variable.
Fix the issue: use the proper `cut` field selector and don't double `-${COMMIT}-head` suffix
N/A

Fix TAG env var in quick script

---

go.mod
hack/airgap/go.mod
pkg/apis/go.mod
pkg/client/go.mod

```sh
docker inspect registry.suse.com/bci/golang:1.24 | grep GOLANG_VERSION
"GOLANG_VERSION=1.24.5",
```
Bump Go toolchain to 1.24.5.
N/A

Bump Go toolchain to 1.24.5

---

pkg/apis/scc.cattle.io/v1/types.go
pkg/scc/consts/consts.go
pkg/scc/controllers/common/deciders.go
pkg/scc/controllers/common/mutators.go
pkg/scc/controllers/common/processors.go
pkg/scc/controllers/controller.go
pkg/scc/controllers/offline.go
pkg/scc/controllers/online.go
pkg/scc/controllers/resources.go
pkg/scc/suseconnect/credentials/secrets_adapter.go
pkg/scc/suseconnect/offline/offline.go
pkg/scc/suseconnect/offline/offlinecert.go
pkg/scc/suseconnect/offline/offlinerequest.go
pkg/scc/systeminfo/secret/metrics.go

Fixes various bugs reported in recent testing:
- OfflineCertificateReady condition not updating when read - @cnotv 
- New metrics secret requested as enhancement by @l-mb not cleaned up - Self-Reported
- Offline secrets not always cleaned up fully - @cnotv 
- was related to various finalizer bugs

[main][scc] General bug fixes

---

.github/workflows/rcs-release.yml
.github/workflows/release.yml

add rcs release workflow

---

.github/workflows/rcs-release.yml
.github/workflows/release.yml

[v2.11] add rcs workflow

---

build.yaml
go.mod
go.sum
pkg/buildconfig/constants.go

[main] Bump remotedialer

---

.github/actions/setup-tag-env/action.yml
.github/workflows/integration-tests.yml
.github/workflows/pull-request.yml

After branching, `main` needs to target the next minor.
* Unit
* None
_TODO_
* _TODO_

update refs to v2.13

---

build.yaml
go.mod
go.sum
pkg/buildconfig/constants.go
pkg/settings/setting.go

[release/v2.12] Unrc remotedialer

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/51121
There was a typo in a setting name causing rancher to always use the latest version of the remotedialer-proxy chart rather than the one it is configured to use.
Fix the typo.
* Unit
* None
_TODO_
* _TODO_

[main] fix setting name typo

---

pkg/settings/setting.go

https://github.com/rancher/rancher/issues/51122
There was a typo in a setting name causing rancher to always use the latest version of the `remotedialer-proxy` chart rather than the one it is configured to use.
Fix the typo.
* Unit
* None
_TODO_
* _TODO_

[release/v2.11] Fix typo 2.11

---

build.yaml
go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum
pkg/buildconfig/constants.go
pkg/client/go.mod
pkg/client/go.sum

Also backporting bump of fleet to `-rc.3` to fix CI

Bump norman, apiserver and steve for new branching

---

pkg/catalogv2/oci/oci.go
pkg/catalogv2/oci/oci_test.go

List all oci tags fix

---

chart/templates/_helpers.tpl
chart/templates/pre-upgrade-hook-job.yaml

https://github.com/rancher/rancher/issues/51111
pre upgrade hook pod fails to get schedule due to podAntiAffinity
added different set of pod labels for pre upgrade hook job
* Unit
* None
_TODO_
* _TODO_

[main] fixed pre upgrade hook labels

---

.github/workflows/rcs-release.yml
.github/workflows/release.yml

The `REGISTRY` var is one of the build args and it wasn't present in the release workflow.
Add the `REGISTRY` var
* Unit
* None
_TODO_
* _TODO_

[v2.11] add build server registry env

---

pkg/controllers/managementuser/rbac/handler_base_test.go

`TestCompareAndUpdateClusterRole` unit test became a flaky test with the changes in this [PR](https://github.com/rancher/rancher/pull/50952) . 
This PR fixes the issue by using a mock for the `ClusterRole` client initialized for each test.

Fix TestCompareAndUpdateClusterRole unit test

---

pkg/image/origins.go

Mirroring redis image (https://github.com/rancher/image-mirror/pull/965) requires this fix.
* Unit
* None
_TODO_
* _TODO_

Add new `redis` image to image origins

---

pkg/image/origins.go

Mirroring redis image (https://github.com/rancher/image-mirror/pull/965) requires this fix.
* Unit
* None
_TODO_
* _TODO_

[release/v2.11] Add new redis image to image origins

---

pkg/image/origins.go

Mirroring redis image (https://github.com/rancher/image-mirror/pull/965) requires this fix.
* Unit
* None
_TODO_
* _TODO_

[release/v2.9] Add new redis image to image origins

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

un-rc's the `system-agent` and `rancher-wins` for the 2.12.0 release

[v2.12] un-rc system-agent and rancher-wins

---

package/Dockerfile
pkg/settings/setting.go
tests/v2/codecoverage/package/Dockerfile

Bumps to the latest released versions of the `system-agent` and `rancher-wins`

[main] un-rc system-agent and rancher-wins

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

fix: add create secrets permissions in fleet-default namespace

---

pkg/data/management/role_data.go
pkg/data/management/rolebuilder.go

Fixes https://github.com/rancher/rancher/issues/51006
Backport of https://github.com/rancher/rancher/pull/50482 to `release/v2.12`

[v2.12] fix: add create secrets permissions in fleet-default namespace

---

pkg/data/management/role_data.go

Remove not needed rule from the `cluster-member` role.
N/A

Fix cluster-member role template

---

pkg/data/management/role_data.go

[v2.11] Fix cluster-member role template

---

pkg/data/management/role_data.go

[v2.10] Fix cluster-member role template

---

pkg/catalogv2/oci/oci.go
pkg/catalogv2/oci/oci_test.go

Backport v2.12 - List all oci tags fix

---

.github/CODEOWNERS

(cherry picked from commit e2062f10b7ad6dff93b01b931a992228cdc56b23)

[ci][backport][release/v2.12] Update CODEOWNERS to include new areas O&B team manages

---

.github/workflows/rcs-release.yml
.github/workflows/release.yml

Closes: https://github.com/rancher/ecm-distro-tools/issues/619
Add registry to the helm chart
* Unit
* None
_TODO_
* _TODO_

[v2.10] add registry var to build publish chart

---

.github/workflows/rcs-release.yml
.github/workflows/release.yml

Backport: https://github.com/rancher/rancher/pull/51358
* Unit
* None
_TODO_
* _TODO_

[v2.9] add registry var to chart

---

.github/actions/images-files/build-artifacts-index/action.yml
.github/workflows/release.yml

Release chart builds were not invalidating the charts cache, and the artifacts index was not being rebuilt after uploading new artifacts.
Invalidate the cache after uploading a chart and rebuild the artifacts index after uploading new artifacts
* Unit
* None
_TODO_
* _TODO_

[v2.11] cache invalidation and artifacts index

---

hack/airgap/main.go
pkg/auth/server.go
pkg/multiclustermanager/routes.go
pkg/settings/setting.go
pkg/settings/setting_test.go
pkg/utils/handler.go
pkg/utils/handler_test.go

This limits the size of HTTP POST bodies that can be sent to public-api endpoints, other endpoints are protected by separate limiting.
This adds a new setting and limiting for /v3-public API endpoints.
There are two mechanisms for configuring some limits - the public API Server uses the settings, but due to settings being lazily loaded, we use an environment variable based value for the auth-server.
* Unit
* None
_TODO_ …

Public API body request limiting

---

hack/airgap/main.go
pkg/auth/server.go
pkg/multiclustermanager/routes.go
pkg/settings/setting.go
pkg/settings/setting_test.go
pkg/utils/handler.go
pkg/utils/handler_test.go

This limits the size of HTTP POST bodies that can be sent to public-api endpoints, other endpoints are protected by separate limiting.
This adds a new setting and limiting for /v3-public API endpoints.
There are two mechanisms for configuring some limits - the public API Server uses the settings, but due to settings being lazily loaded, we use an environment variable based value for the auth-server.
* Unit
* None
_TODO_ …

[backport v2.12] Public API body request limiting

---

pkg/auth/server.go
pkg/multiclustermanager/routes.go
pkg/settings/setting.go
pkg/settings/setting_test.go
pkg/utils/handler.go
pkg/utils/handler_test.go

This limits the size of HTTP POST bodies that can be sent to public-api endpoints, other endpoints are protected by separate limiting.
This adds a new setting and limiting for /v3-public API endpoints.
There are two mechanisms for configuring some limits - the public API Server uses the settings, but due to settings being lazily loaded, we use an environment variable based value for the auth-server.
* Unit
* None
_TODO_ …

[backport v2.9] Public API body request limiting

---

.github/workflows/release.yml

use the correct action path
* Unit
* None
_TODO_
* _TODO_

[v2.10] fix build artifacts index path

---

pkg/controllers/dashboard/helm/repo.go
pkg/controllers/dashboard/helm/repo_oci_test.go
tests/v2/integration/catalogv2/cluster_repo_test.go

Issue https://github.com/rancher/rancher/issues/49668

adding extra logs for cluster repo retries

---

.github/actions/setup-build-env/action.yml

When running setup-build-env from other repos, we need to be able to set the directory to run the commands on
* Unit
* None
_TODO_
* _TODO_

[v2.9] add rancher path input to setup build env

---

pkg/controllers/management/auth/project_cluster/project_handler.go
pkg/controllers/management/auth/project_cluster/project_handler_test.go
pkg/systemaccount/systemaccount.go

Add unit tests to project-handler

---

go.mod
go.sum

Include changes from https://github.com/rancher/steve/pull/792

[v2.12] Bump steve v0.6.36

---

.github/workflows/release.yml

[v2.9] fix build artifacts index action path

---

scripts/chart/index

The index used in v2.11 was not the same as other versions and this was causing inconsistencies.
Use the same index as older versions.
* Unit
* None
_TODO_
* _TODO_

[v2.11] update index url

---

pkg/api/steve/clusters/shell.go

https://github.com/rancher/rancher/issues/51104
* Unit
* None
_TODO_
* _TODO_

add shell-toleration

---

go.mod
go.sum

Issue : https://github.com/rancher/rancher/issues/51509

[main] Bump remotedialer to v0.5.1-rc1

---

pkg/auth/providers/oidc/oidc_provider.go
pkg/auth/providers/oidc/oidc_provider_test.go

Note: this is a _very light_ reworking of https://github.com/rancher/rancher/pull/49672
The AzureAD OIDC provider offers additional RBAC functionality that includes a `Roles` claim, but the Rancher codebase doesn't currently support using those claims.
We are configuring AzureAD to map roles like this:
```yaml
project-a-developer:
- team 1
- team b
- team 4
project-b-developer:
- team b
- team 5
- team g
```
In Rancher, this will allow us to bind ProjectRoles to AzureAD Roles and completely delegate RBAC to the OIDC provider. 
Pseudocode of the current logic:
```
Is there a `FullGroupPath` claim in the OIDC token?
yes:
populate the `groups` list with the values from the `FullGroupPath` claim
no:
populate the `groups` list with the values from the `Groups` claim
```
Additional logic to be …

[feat] add compatibility for Azure AD `roles` claims (case no. 01575183)

---

go.mod
go.sum

Issue : https://github.com/rancher/rancher/issues/51509

[release/v2.12] Bump remotedialer to v0.5.1-rc1

---

go.mod
go.sum

[Backport v2.12]  bump steve to v0.6.38 (#50968)

---

pkg/rancher/rancher.go

[v2.12] Consider empty string values for sql-cache-* settings 

---

scripts/gha/tests
tests/v2/integration/setup/README.md
tests/v2/integration/setup/main.go

There was stale code in the integration setup, and no README with how to run this environment locally. 
Cleaned up the main file and added a README
* Unit
* None
_TODO_
* _TODO_

[main] Integration test setup update

---

scripts/gha/tests
tests/v2/integration/setup/README.md
tests/v2/integration/setup/main.go

There was stale code in the integration setup, and no README with how to run this environment locally. 
Cleaned up the main file and added a README
* Unit
* None
_TODO_
* _TODO_

[V2.10] Integration test setup update

---

go.mod
go.sum

Including https://github.com/rancher/lasso/pull/175

[v2.12] Bump lasso to v0.2.4

---

pkg/ext/stores/kubeconfig/store.go
pkg/ext/stores/kubeconfig/store_test.go

[v2.12] Pass through error events when watching ext kubeconfigs

---

pkg/httpproxy/proxy.go
pkg/httpproxy/proxy_test.go

Fix /meta/proxy endpoint

---

pkg/httpproxy/proxy.go
pkg/httpproxy/proxy_test.go

[v2.12] Fix /meta/proxy endpoint

---

pkg/controllers/management/auth/globalroles/common.go
pkg/controllers/management/auth/globalroles/globalrole_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler.go
pkg/controllers/management/auth/globalroles/globalrolebinding_handler_test.go
pkg/controllers/management/auth/globalroles/register.go
pkg/controllers/managementuser/rbac/globalrolebinding_handler.go
pkg/rbac/common.go
pkg/rbac/common_test.go

[v2.12] Fix global role handlers

---

pkg/httpproxy/proxy.go
pkg/httpproxy/proxy_test.go

[v2.10] Fix /meta/proxy endpoint

---

pkg/rancher/rancher.go
pkg/utils/utils.go

[main] Ensure Telemetry manager is only setup when MCM is enabled

---

pkg/apis/management.cattle.io/v3/authn_types.go
pkg/auth/providers/oidc/oidc_provider.go
pkg/auth/providers/oidc/oidc_provider_test.go
pkg/client/generated/management/v3/zz_generated_cognito_config.go
pkg/client/generated/management/v3/zz_generated_generic_oidcconfig.go
pkg/client/generated/management/v3/zz_generated_key_cloak_oidcconfig.go
pkg/client/generated/management/v3/zz_generated_oidc_config.go

We don't allow custom claims to be specified for users/groups.
This adds custom claims support for the `name` and `email` claims.
Configure a OIDC provider with custom fields for the `name` and see that it's used for the `user.Name` field.
* Unit
* None
_TODO_
* _TODO_

Custom claim mapping

---

pkg/api/norman/customization/cluster/validator.go

- added cluster id validation for imported clusters.
- added condition to skip cluster name validation for put requests.

[main] fix cluster validation for alibaba clusters

---

chart/templates/NOTES.txt
chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/templates/post-delete-hook-job.yaml
chart/templates/pre-upgrade-hook-job.yaml
chart/tests/images_test.yaml
chart/values.schema.json
chart/values.yaml
dev-scripts/prepare-chart
scripts/chart/build

https://github.com/rancher/rancher/issues/52110
A backport of: https://github.com/rancher/rancher/pull/52109 & https://github.com/rancher/rancher/pull/52126

[backport v2.12] Ensure all r/r chart images use `systemDefaultRegistry` value

---

pkg/capr/planner/filter.go
pkg/capr/planner/filter_test.go
pkg/controllers/capr/bootstrap/controller.go
tests/v2prov/tests/machineprovisioning/machine_test.go

Backport of [#51780](https://github.com/rancher/rancher/pull/51780) to v2.12
- Same as [#51780](https://github.com/rancher/rancher/pull/51780)

[v2.12] Prevent drain when config change in a single node

---

build.yaml
pkg/buildconfig/constants.go

This is to deliver various bug fixes we targeted for this release.
- https://github.com/rancher/scc-operator/issues/28
- https://github.com/rancher/scc-operator/issues/53

Bump SCC image to new alpha build

---

pkg/data/management/machinedriver_data.go

update Nutanix node driver to v3.7.0 for rancher 2.12

update Nutanix node driver to v3.7.0 for rancher 2.12

---

pkg/data/management/machinedriver_data.go

update Nutanix node driver to v3.7.0 for rancher 2.11

update Nutanix node driver to v3.7.0 for rancher 2.11

---

pkg/image/origins.go

Adding the repo for Turtles image as it was recently introduced to Rancher.

fix: Add Rancher Turtles image origin repo
