- agent/run.sh
Added a sleep to the for loop, and have it waiting 10 minutes for the
server to come available. Also, added some additional logging to let
users know it is attempting to reach server, unable to reach or can
reach.
> Fixed #62: Rancher agent connection retry handling

- agent/run.sh
When authentication is turned on the URL used to check for server
availability was incorrect. We used the truncated version of the url
without credentials. We need to use the URL with the valid credentials
in order to register hosts with auth turned on.
This fixes issue in #142
> Fixed Bug wrong URL was used to check host availability

- server/Dockerfile
The docker-machine and go-machine-service binaries were added
to the server image. These are necessary to enable machine based
services in Rancher.
> Added new machine services to container

- agent/Dockerfile
- agent/run.sh
We need map of /dev, as well as a mount point can be shared for other containers
libaio is needed for pdata_tools, which used by volmgr for exporting device
mapper metadata
> Add volmgr support

- agent/Dockerfile
This will allow syncing/importing to ignore rancher-agent and the temporary containers created when launching it.
> Add system container label

- server/artifacts/cattle.sh
@ibuildthecloud @cloudnautique added an option enabling heapDump on OOM. Not sure if it should come as the default option though; @cloudnautique Bill, feel free to move if you think it should be set on the QA setup only
> Enabled heapDump on OOM errors

- README.md
The current instructions for setting up node on same host as management server are ambiguous in that the command snippet implies that the `--privileged` flag is not needed. It did trick me.
```bash
sudo docker run -d -e CATTLE_AGENT_IP=<IP_OF_RANCHER_SERVER> -v /var/run/docker....
```
> docs: add `--privileged flag` for node on same host as management server instructions

- agent/run.sh
make /var/lib/rancher a rancher-agent-state volume
Use one state persistence mechanism instead of two.
Fixes #936
> make /var/lib/rancher a rancher-agent-state volume

- server/Dockerfile
By putting versions as environment variables the cattle can make the
version available in the API.
> Add rancher-compose URLs and move version to env variables

- README.md
I made an ansible playbook I'm using to maintain my rancher server and it's agents,  I also have some octohost  repos to be used with http://octohost.io 
https://github.com/joshuacox/OctoRancherAgent
https://github.com/joshuacox/OctoRancherServer
But the agent will not work in octohost as is until my pull request goes through over at octohost to add in the ability for it to start images in privileged mode.  It works on mine by upgrading /usr/bin/octo to https://raw.githubusercontent.com/joshuacox/octohost/master/bin/octo
> added ansible

- server/Dockerfile
- server/artifacts/install_cattle_binaries
- server/service/.s6-svscan/finish
This PR updates the method of getting binaries from cattle-global.properties to use the common build-tool. This will now pull docker-machine and go-machine-service binaries from cattle as of PR rancherio/cattle#634
Also, setup s6 to not show crash errors on SIGTERM.
> Pull docker-machine and go-machine-service binaries from cattle

- server/Dockerfile
- server/artifacts/cattle.sh
- server/artifacts/install_cattle_binaries
To support networks that may not have access to CDN the agents
are now downloaded into the rancher/server container. They are
compressed and accessed through the CATTLE_ settings. The default
behavior will now be to use the local agents. If a user wants to
leverage the CDN versions a `-e USE_LOCAL_AGENTS=false` must be
passed when starting the container.
> [WIP] Add support to download and run local agents

- agent/Dockerfile
- agent/run.sh
This part of the process allows the agent to register and passes along what it needs to. Need to update cattle upgrade script to pass along the variable.
The variable name may need to be changed.
Also, Fixes docker redirect for binaries. New images will have an empty file for /usr/bin/docker.
> Add capability to use agent from private registry

- agent/run.sh
Fixes the docker error appearing in the rancher-agent-state container.
> Ignore docker inspect on state run

- server/artifacts/mysql.sh
This bug prevented rancher/server from starting when a non-vboxfs
directory was used as the mount point for /var/lib/mysql. In the
case of docker-machine/boot2docker any directory outside of /Users
on a Mac or non rancher/server container volumes from meet this
criteria. VBoxFS mounts do not allow changing UID/GID or permissions
of the directory. To address we change the UID of the MySQL user
to the directory owner UID.
> Fix usermod error UID 0 already exists.

- server/artifacts/cattle.sh
Put JAVA_OPTS last so that any repeated entry will override what is
in CATTLE_JAVA_OPTS
> Reverse order of JAVA_OPTS and CATTLE_JAVA_OPTS

- server/artifacts/mysql.sh
This is to address issue #2087 the single innodb file gets very large while running rancher. The innodb_file_per_table setting has been set, and is the default setting in newer versions of MySQL.
Also, to address  #2136 the binlog rotation has been shortend down to two days.
After starting a rancher server the my.cnf file should have the following entries:
expire_logs_days = 2
innodb_files_per_table = 1
This should be verified to work in the following scenarios
* container restart (my.cnf should not have changed after restart)
* Bind mounted to a host. (new and upgrade)
* Upgrade with volumes from
> MySQL updates to logs and innodb files

- Vagrantfile
- vagrant_ros_guest_plugin.rb
and pin RancherOS version. 
Also, the setup is now 2 nodes (1024MB RAM each), by default. There are a couple reasons for this:
- Rancher Server leaves very little memory for containers
- the hosts page looks way cooler with more than one node ;)
> bump RancherOS version and settings

- agent/Dockerfile
- agent/run.sh
Support for non-default docker socket via environment variable `HOST_DOCKER_SOCK`, which defaults to `/var/run/docker.sock`
Example:
`docker run -d --privileged -e HOST_DOCKER_SOCK=/var/run/docker-test.sock -v /var/run/docker-test.sock:/var/run/docker.sock rancher/agent:v0.8.2 <server-end-point>`
> Added support for non-default docker sock via HOST_DOCKER_SOCK

- agent/Dockerfile
- agent/run.sh
Updates Requests to latest version
Updates agent image to 14.04.3
Adds code to run.sh to wire up user specified CA roots to enable self signed certs or the addition of other certs not included in the base OS.
> Configure ca root bundles

- agent/Dockerfile
This is to add a newer python for SNI support brought up in issue #2185
Stopped installing Ubuntu python.
Install python 2.7.11
squashed RUN commands into a single layer.
Incremented version.
> Install python 2.7.11

- agent/run.sh
curl attempting to connect to the cattle url should follow redirection if rancher is under a reverse_proxy, adding -L to curl command
> FIX: v1 not accessible if reverse proxy

- server/build-image.sh
Added quotes to vars to prevent word splitting in case of spaces or special chars in dir names.
Ref: https://github.com/koalaman/shellcheck/wiki/SC2086
> Adding quotes for globbing

- agent/Dockerfile
- server/Dockerfile
ubuntu:16.04 bumps to openjdk-8 and has an annoying mysql issue, but otherwise is fine
> Make rancher server work in ubuntu:16.04 based container

- server/artifacts/mysql.sh
The current configuration of bin logging makes the in container DB very
slow.  If users want bin logging or more HA configuration then they
really should rely on an external database that is properly tuned.
> Remove bin logging

- README.md
I created a Salt states for Rancher installation, right now with support for Vagrant, single Rancher server with external MySQL DB and auto provisioned agents. I'm planning to add more options and also to update a documentation for installation on other providers.
> Add SaltStack installation option.

- scripts/print-tags.sh
sample output:
```
./scripts/print-tags.sh
Printing project/service tag information for Rancher tag master. (Rancher tag not specified)
Cattle Tag: v0.169.5
Other project tags:
agent.package.python.agent.url         v0.85.1 https://github.com/rancher/python-agent/releases/download/v0.85.1/python-agent.tar.gz
agent.package.agent.binaries.url          v0.1.2 https://github.com/rancher/agent-binaries/releases/download/v0.1.2/agent-binaries.tar.gz
agent.package.node.agent.url          v0.1.0 https://github.com/rancher/node-agent/releases/download/v0.1.0/node-agent.tar.gz
agent.package.rancher.dns.url          v0.9.2 https://github.com/rancher/rancher-dns/releases/download/v0.9.2/rancher-dns.tar.gz
agent.package.rancher.metadata.url          v0.5.1 …
```
> Add script to print tags of all sub-projects

- server/Dockerfile
- Use azul/zulu-openjdk:8u72 base that is based on ubuntu:14.04
- Manually Install zookeeper to avoid trusty dependencies
WIP until the zookeeper change is tested.
> WIP Add Java 8 support

- server/artifacts/cattle.sh
- server/bin/update-rancher-ssl
When running master, if you want to use a self signed cert you have to manually add to keystore. This change now always runs the update-rancher-ssl script.
Also, this addresses issue #7232 by redirecting the keystore list output to /dev/null
> Move update ssl script in server

- server/bin/entry
Add support --advertise-address "awslocal". 
This can be used to automatically detect AWS instance local host IP addresses, within an AWS host / ECS cluster.
A local host IP is useful, as users may have different security address or host binding for local IP's, and external IP's for security reasons.
Also added more details into help documentation command.
The sister issue posted is : #7343
> Added --advertise-address "awslocal"

- server/Dockerfile
- server/artifacts/cattle.sh
- server/build-image.sh
- server/service/graphite_exporter/finish
- server/service/graphite_exporter/run
This PR does 2 things.
1. ) Updates S6 to a much newer version based on the same work we
originally had pulled from.
2. ) Adds the prom/graphite_exporter binary and s6 scripts to start.
The overall process is that the user now sets
`-e CATTLE_PROMETHEUS_EXPORTER=true` variable on launch and expose the port
9108 inside the container to some place Prometheus can scrape.
> Adds graphite_prometheus exporter

- scripts/print-tags.sh
Unfortunately, this only works for v1.5.0 and greater because the structure was different before then and I didn't want to figure it out
Sample output:
```
rancher$ ./scripts/print-tags.sh v1.5.0
Printing project/service tag information for Rancher tag v1.5.0. 
Cattle Tag: v0.177.7
Other project tags:
agent.package.python.agent.url          v0.9.2 https://github.com/rancher/agent/releases/download/v0.9.2/go-agent.tar.gz
agent.package.host.api.url         v0.38.1 https://github.com/rancher/host-api/releases/download/v0.38.1/host-api.tar.gz
rancher.compose.linux.url          v0.1.0 https://github.com/rancher/rancher-compose/releases/download/v0.1.0/rancher-compose_linux-amd64
rancher.compose.darwin.url          v0.1.0 https://github.com/rancher/rancher-compose/releases/download/v0.1.0/ranche …
```
> print catalog info

- server/Dockerfile
This will make updating the Dockerfile for releases easier and less
error prone since all the typically changed environment variables will
be grouped together.
> Group commonly changed release env vars

- agent/run.sh
Discussion after https://github.com/rancher/rancher/pull/9186 and https://github.com/rancher/rancher/issues/9176:
Using `127.0.0.1` or `localhost` is not how it's done, and the debate was on wether to protect the user from this behavior or bail out with a proper error message. Taking it out of the users hand and fix it is not the way to go.
```sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher superseb/agent:v1.2.5-localhost http://127.0.0.1:8080/v1/blabla                                                                                         
Status: Downloaded newer image for superseb/agent:v1.2.5-localhost             
ERROR: CATTLE_URL cannot contain localhost or 127.0.0.1, please check the Host Registration URL.
```
> Error out when reference to localhost is found in CATTLE_URL

- server/artifacts/mysql.sh
This fixes the issue where a host bind mount of an empty directory fails.
> Update MySQL initialization for MySQL 5.7

- agent/run.sh
Related Issue: https://github.com/rancher/rancher/issues/9936
Description: We get the host info like zone and region in rancher agent, and we implement this for the different cloud provider. The flag is for control whether we enable the detect cloud provider or not.
@yasker  Could you please help to review the PR?
> add flag to control whether enable detect cloud provider, default is true

- server/bin/mysql-remote-init.sh
This remote init script is able to initialize a rancher DB. It also can create the `DATABASECHANGELOG` table with a primary key for use in strict enforcing MySQL clusters like PXC. The reason for running this out of band for startup is to prevent having DB admin password in the running Rancher server container.  
In order to create a remote DB run:
```
docker run -it -e DB_ROOT_PASSWORD=<database_admin_password> rancher/server:v1.6.11-rc4 --db-host 192.168.42.213 --db-name cattle --db-user cattle --db-pass cattle mysql-remote-init.sh
```
*Note*: the mysql-remote-init.sh position needs to come after the `--db-*` variables.
In order to use a DB that has strict_mode=enforcing like Percona PCX clusters:
```
docker run -it -e DB_ROOT_PASSWORD=<database_admin_password> …
```
> Add a remote init DB script

- app/app.go
- app/rolebuilder.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/catalog_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_global_role.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_role_template.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_template_version.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_template_version_spec.go
This will bootstrap in:
- 2 GlobalRoles: Admin and User
- RoleTemplates for the k8s builtin roles and expected rancher cluster/project roles: Cluster Owner, Project Owner, Member, Read Only
It also changes the bootstrapped Admin user to use the admin GlobalRole (and binding) instead of the builtin k8s cluster-admin role
> Bootstrap default roles

- app/app.go
Give all users CRUD access to preferences
Make Cluster Owner role own its own rules instead of deferring to
cluster-admin because it is so simple and deferring causes us to create
more roles and bindings
> Global Role changes

- app/app.go
This role isn't going to work properly because we use impersonation in our auth proxy, which as it is written now, would override any impersonation a user is trying to do
> Drop the impersonate role

- agent-windows/Dockerfile
- agent-windows/README.md
- agent-windows/build-image.ps1
- agent-windows/build-image.sh
- agent-windows/tools/cleanup.ps1
- agent-windows/tools/rancher-tools.psm1
- agent-windows/tools/run.ps1
- agent-windows/tools/startup.ps1
Related issue https://github.com/rancher/rancher/issues/10662
Add new rancher tools for common use.
Add clean up script.
Add startup script for the main entry. And Upgrading logic is in it.
The run.ps1 now will download the binaries into download folder instead of base dir for upgrading purpose.
Add a build-image.sh script for *nix to build a Windows from *nix os.
> Windows Agent Upgrade Enhancement

- agent/run.sh
Fixes https://github.com/rancher/rancher/issues/9464
```
INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.99.100:8080/v1                                                                            
INFO: Attempting to connect to: http://192.168.99.100:8080/v1                  
INFO: http://192.168.99.100:8080/v1 is accessible                              
ERROR: Failed to load registration env from CATTLE_URL=http://127.0.0.1/v1 ENV_URL=http://192.168.99.100:8080/v1                                              
ERROR: Please ensure the proper value for the Host Registration URL is set
```
> Compare Host Registration URL to input URL

- pkg/auth/tokens/route_handlers.go
Previous method for deciding whether the request was secure (and
setting the secure flag on the cookie accordingly) doesn't work
because the URL on the request is relative and thus the scheme is
not set.
Rancher will always have TLS enabled, so always setting the secure
cookie flag to true is acceptable.
> Always set token cookie as secure

- pkg/api/management/api/cluster/validator.go
As cluster.spec is not exposed in norman api; driver configs are top level fields.
> Cluster config: validate as top level field

- pkg/management/controller/clusterprovisioner/provisioner.go
- pkg/settings/setting.go
- vendor.conf
- vendor/github.com/rancher/rke/cluster.yml
- vendor/github.com/rancher/rke/cluster/defaults.go
- vendor/github.com/rancher/rke/cluster/network.go
- vendor/github.com/rancher/rke/vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_rke_system_images.go
https://github.com/rancher/rancher/issues/11231
https://github.com/rancher/rancher/issues/11232
This PR introduces 2 settings:
* `k8s-version`, default is v1.8.5-rancher4"
* `k8s-version-to-images`, default is json map of k8s version to system images
Cluster provisioner would read `k8s-version-to-images` based on cluster.version (default to `k8s-version` if not passed), and set `cluster.Spec.RancherKubernetesConfig.SystemImages` before passing cluster spec to RKE. If privateRegistry is specified, it will be prepended to every system image.
WIP as do not merge till a) we move all rke system images to rancher repo on dockerhub and b) until https://github.com/rancher/types/pull/175 is merged
@deniseschannon
> Private registry support and system images to setting

- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/controllers/user/alert/deploy/deployer.go
- pkg/controllers/user/alert/manager/manager.go
- pkg/controllers/user/alert/statesyncer/statesyncer.go
- pkg/controllers/user/alert/watcher/daemonset.go
- pkg/controllers/user/alert/watcher/deployment.go
- pkg/controllers/user/alert/watcher/event.go
- pkg/controllers/user/alert/watcher/node.go
- pkg/controllers/user/alert/watcher/pod.go
- pkg/controllers/user/alert/watcher/statefulset.go
- pkg/controllers/user/alert/watcher/syscomponent.go
1. only deploy alertmanager when notifier is configured and alert is using it.
2. if alertmanager is not deployed, all watchers and controllers just return.
> deploy alertmanager on demand

- pkg/controllers/user/logging/controller.go
- pkg/controllers/user/logging/utils/namespace.go
Related issue: https://github.com/rancher/rancher/issues/11426
Removing init cattle-logging and configmap, only create them on demand
@alena1108 @ibuildthecloud could you help review?
> remove init namespace and configmap data, only create on demand

- pkg/controllers/user/endpoints/workload_endpoints.go
- pkg/controllers/user/workload/workload.go
- pkg/controllers/user/workload/workload_common.go
* do not update endpoints on workloads that are created by controllers
* determine if service mapped to the workload, using service.targetWorkloadIds (in addition to a regular selector based check)
> Workload endpoints fixes

- pkg/api/customization/pipeline/cluster_pipeline.go
- pkg/controllers/user/pipeline/controller/clusterpipeline/clusterpipelinesyncer.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/logsyncer.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go
- pkg/controllers/user/pipeline/remote/github/github.go
- pkg/controllers/user/pipeline/utils/utils.go
1. Change sourcecodecredential name to avoid conflicts between clusters, fix https://github.com/rancher/rancher/issues/11669
2. Fix clusterpipeline panic on cluster deletion, partially fix https://github.com/rancher/rancher/issues/11648
3. Fix reference id with namespace so that pipeline/execution links can list correctly
> Pipeline fix

- k8s/embedded_none.go
building without the k8s build tag is resulting in this error:
```
rancher)rancher$ go build
k8s/config.go:21:3: not enough arguments to return
have (context.Context, *rest.Config, error)
want (bool, context.Context, *rest.Config, error)
k8s/config.go:41:2: not enough arguments to return
have (context.Context, *rest.Config, error)
want (bool, context.Context, *rest.Config, error)
```
> Fix method signature for the non-embedded verison

- agent-windows/Dockerfile
- agent-windows/build-image.ps1
Because github update tls protocal from 1.0 to 1.2, we need to set the protocal Tls1.2.
> Fix get data from github is not working while building Windows agent

- pkg/controllers/user/authz/podsecuritypolicy/cluster.go
- pkg/controllers/user/authz/podsecuritypolicy/namespace.go
- pkg/controllers/user/authz/podsecuritypolicy/project.go
- pkg/controllers/user/authz/podsecuritypolicy/serviceaccount.go
- pkg/controllers/user/authz/podsecuritypolicy/template.go
- pkg/controllers/user/controllers.go
Fixing the issue where pod security was not being reliable applied for clusters created before the pod security policy template was created.
Also added guards against panics when handler `obj` is nil.
https://github.com/rancher/rancher/issues/11159
> Fixing Pod Security Policy

- pkg/controllers/user/logging/utils/embedded.go
4G as a default request will make it hard to schedule in small envs
> Shrink the memory request down from 4G to 500M

- pkg/auth/providers/activedirectory/activedirectory_client.go
conn was nil and trying to close was causing a panic
> defer close only on no error

- pkg/auth/providers/github/github_provider.go
Have one common method for creating principals from GH.
Always fall back if the GH account does not have a display name.
> Cleanup principal creation for GH

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/indexes.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
When a PRTB/CRTB is created with userPrincipalId set, we translate
that to a userId on the backend. Previously, we were unsetting
userPrincipalId on the backend, but if it is unset, the UI has
now way to display details about the associated user. So, we'll
keep it set so that UI can continue to load the principal.
> Don't unset userPrincipalName

- pkg/controllers/user/authz/podsecuritypolicy/cluster.go
- pkg/controllers/user/authz/podsecuritypolicy/namespace.go
- pkg/controllers/user/authz/podsecuritypolicy/project.go
This fixes 3 issues:
1) When the project handler runs, it doesn't enqueue the correct service accounts to be resynced.  The namespace handlers picks up the slack most of the time, but generally not when a cluster is created with a PSPT attached, so clusterroles and rolebindings can fail to be created.
2) Changed logic in the project handler so a pod security policy did not need to be retrieved immediately after being created (sometimes causes errors if the cache(?) hasn't synced yet)
3) Optimized the namespace handler so it only syncs service accounts in its own namespace and not enqueing all of them
4) Changed confusing `cluster.Namespace` (which resolved to "" all namespaces) to "" explicitly.
Issue:
#11622
> Fixing race conditions in PSP

- pkg/api/store/namespace/store.go
- pkg/controllers/user/authz/namespace_handler.go
This change adds a status condition to namespace that indicates
its initial roles have been populated from rancher.
Namespaces do not natively support adding conditions. This change
puts a status type object into an annotation so that we can control
the rancher state.
Addresses https://github.com/rancher/rancher/issues/11350
> Dont mark ns as active until roles populated

- pkg/rbac/permission_index.go
So, for example, an RBAC rule for statefulsets is properly recognized
as authorizing statefulSets.
Addresses https://github.com/rancher/rancher/issues/11930
> Make RBAC resource type comparison case-insensitive

- pkg/api/customization/authn/rtb_store.go
- pkg/api/server/managementstored/setup.go
- pkg/auth/providers/github/github_client.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/prtb_handler.go
If a PRTB/CRTB is created with the userPrincipalId set, we will
ultimately need to ensure that the user exists in rancher. This
is done in a controller, which does not have access to the principals
API. So, set the principal's display name as an annotation on the
RTB during the API request (where we do have access to the principals
API) so that it can be used to ensure the user in the controller.
addresses https://github.com/rancher/rancher/issues/11691
> Set display name annotation on PRTB/CRTB

- pkg/controllers/user/authz/podsecuritypolicy/serviceaccount.go
When a new namespace is created and assigned to a project and that
project has a pod security policy, the pod security policy is not binding
correctly.  This is because when the service account handler looks to see
if a binding exists for a given service account in a given namespace, it
only looks for the first binding with a matching parent template
annotation and then exits.
This fixes the issue by making it compare the
name and namespace of the subject in the clusterrole and then creating
the role binding it if does not exist.
Issue:
https://github.com/rancher/rancher/issues/11887
https://github.com/rancher/rancher/issues/11971
https://github.com/rancher/rancher/issues/11973
> Fix PSP not working in non-default namespaces/projects

- pkg/controllers/user/pipeline/engine/jenkins/mappper.go
To fix https://github.com/rancher/rancher/issues/11993
using the `plugins/docker` image to do publish and it is related to an upstream issue https://github.com/drone-plugins/drone-docker/issues/52#issuecomment-215611889 that setting the registry option with `index.docker.io` will fail.
> fix publish image step with dockerhub credential

- pkg/api/customization/namespace/namespace.go
- pkg/api/store/projectsetter/store.go
so updated data can be fetched when namespace gets created from project context; and change event won't be filtered out https://github.com/rancher/rancher/issues/11957
> Keep namespace/project ownership in cache

- agent/run.sh
https://github.com/rancher/rancher/issues/12028
Discovered that if the host registration URL is not set, the current comparison will fail and this is breaking.
When Host Registration URL is set, the value ends with `/v1`. Added the check if the URL ends with `/v1`, and if true, do the comparison. Otherwise, ignore (as current behavior).
If this is not solid enough, I suggest we revert the previous change.
> Added more resilient comparison of CATTLE_URL and Host Registration URL

- agent/run.sh
Related issue: https://github.com/rancher/rancher/issues/9562
Add an option to be able to skip the host dns nameserver file check.
> add params to support skip the nameserver check

- app/app.go
- app/role_data.go
- pkg/api/customization/authn/user_store.go
- pkg/controllers/management/auth/register.go
- pkg/controllers/management/auth/user.go
- vendor.conf
- vendor/github.com/rancher/norman/httperror/error.go
This PR adds a user lifecycle to properly clean up cluster, global, and
project role bindings after a user is deleted from rancher.  This is to
prevent a user from still having access to a k8s cluster after
they have been deleted.
It also adds retry logic to user_store so that the system will retry
creating a user if it fails due to the user lifecycle updating the user
with annotations after it is created.
Also fixed a bug where the admin user would fail to be created on
cluster startup.
Issue:
#11378
Depends on:
https://github.com/rancher/norman/pull/113
> Delete user access

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/user/healthsyncer/healthsyncer.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/status/status.go
make world better by not showing error msg when provisioning. At the
time when creating a cluster, set its initial condition to Waiting and
wait for the first healthcheck check to pass to set it to true so that
once the cluster finish provisioning it will show a transition msg
instead error.
> use waiting state instead of ready

- pkg/controllers/user/authz/podsecuritypolicy/serviceaccount.go
When service account is nil in the sync handler (like when it is deleted)
the sync handler panics when a field on the svc act struct is accessed.
This fixes it by adding logic to immediately exit the handler when the
svc act is nil.
Issue:
https://github.com/rancher/rancher/issues/12351
> Fixing nil svc act panic

- app/role_data.go
- pkg/api/customization/pipeline/cluster_pipeline.go
- pkg/api/server/managementstored/setup.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/prtb_handler.go
Add rbac rules for pipeline resources. As `clusterpipelines` are visible to all cluster members now, store the clientSecret of oauthapp in secrets instead to avoid leaking the credentials. https://github.com/rancher/rancher/issues/12180
> set pipeline RBAC rules

- pkg/clustermanager/manager.go
start() method returns nil object when either underlying controller is nil, or error != nil (https://github.com/rancher/rancher/blob/master/pkg/clustermanager/manager.go#L88). Have to handle the first condition in the caller method.
https://github.com/rancher/rancher/issues/12354
> Nil check in cluster manager

- pkg/api/customization/authn/user_actions.go
- pkg/auth/providers/publicapi/store.go
- pkg/settings/setting.go
- server/server.go
Based on discussion with @cjellick, we are:
1) Adding a new setting `first-login` (true by default). 
2) UI reads this field, and automatically logs in user if the value is true.
3) Rancher code resets the value to false on ChangePassword call.
The only part that is left is, exposing settings via v3-public API. @cjellick mentioned that there might be some work done for it by @ibuildthecloud already, so we might need to change this pr to expose first-login to v3-public.
https://github.com/rancher/rancher/issues/11880
> FirstLogin settings. Reset on changePassword/setPassword and authConfig PUT

- pkg/httpproxy/proxy.go
Fixes the rewriting e.g.
from: `https:/storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`
to: `https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`
So that the `https:/` will be correctly rewritten to `https://`.
I tested three test cases as the ui driver URL:
- http://[...]
- https://[...]
- hostname.tld/component.js
all are working fine. :smile: 
Currently `http` links will work, but `https` links won't work as URL. They will get an 502 internal server error with "invalid host" message. That's because he could not parse the URL correctly with https.
> Fix: https:/ to https:// rewriting for httpproxy

- pkg/api/customization/clusterregistrationtokens/formatter.go
SELinux (well really RHELs configuration of SELinux) will not let
containers talk to docker.sock.  Adding the privileged flag will work
around that.
> Add --privileged by default

- pkg/auth/providers/common/usermanager.go
There are now two places that set the local principal on a user:
a controller and the api handler for when a user first logs in.
This leads to a scenario where the api creates the user, but the
controller is first to update the user with the principal and then
the api handler tries and gets a conflict error. This causes the
login to fail.
Solution is to remove the logic from the api handler so that it
is only performed in the controller.
Addresses https://github.com/rancher/rancher/issues/12524
> Fix login error

- pkg/controllers/user/pipeline/engine/jenkins/engine.go
15s timeout may not be sufficient before build info is ready.
Related issue: https://github.com/rancher/rancher/issues/12578
> increse get build info timeout

- pkg/api/store/ingress/store.go
related issue: https://github.com/rancher/rancher/issues/12471
We should check `defaultbackend` nil when transforming data.
> Checkout defaultbackend nil in ingress store

- pkg/dynamiclistener/server.go
This enables clients to follow the preferred order of ciphers set on the server
> Enable Forward Secrecy in the TLS config

- pkg/api/customization/namespace/link.go
- pkg/api/server/userstored/setup.go
Add yaml link to namespace
It returns yaml representation of workloads/services in the namespace given `Accept: application/yaml`, similar to service.export/workload.export
Workloads with OwnerReferences are filtered.
Related to the issue: https://github.com/rancher/rancher/issues/12371
> add namespace export support

- pkg/api/store/workload/aggregate_store.go
- pkg/controllers/user/workload/workload.go
- pkg/controllers/user/workload/workload_common.go
* generate port name differently to support "duplicates" cross port
types
* generate dnsName for the port if not specified
* cleanup services if the port no longer exists
https://github.com/rancher/rancher/issues/11761
https://github.com/rancher/rancher/issues/12546
> Fixes around workload ports

- pkg/controllers/user/nodesyncer/nodessyncer.go
As we've switched from figuring out ip from addresses instead of rke annotations, so the logic should change to:
* `machine.status.NodeConfig.address` *is not* an external address in node.status.addresses; RKE uses this ip to communicate with nodes, and it will become `node.status.addresses.internalIP` if `machine.status.NodeConfig.InternalAddress `is not set
* NodeSyncer should check `node.status.addresses.internalIP` and compare it with `machine.status.NodeConfig.internalAddress` if set, and if not, fall back to `machine.status.NodeConfig.address`
> Use node internalIP in nodesyncer

- pkg/clustermanager/manager.go
- pkg/clusterrouter/factory.go
- pkg/clusterrouter/proxy/proxy_server.go
- pkg/clusterrouter/router.go
- pkg/k8sproxy/k8s_proxy.go
The custom verify method was incorrectly be assigned to different clusters
because of tlsconfig caching that client-go uses.  Instead we will just
use DialTLS.
> client-go caches tlsconfigs across clients causing collisions

- pkg/controllers/user/rbac/handler_base.go
- pkg/controllers/user/rbac/namespace_handler.go
- pkg/controllers/user/rbac/prtb_handler.go
- pkg/controllers/user/rbac/roletemplate_handler.go
Some resources (right now PVs and storageClasses) are globally scoped but
need to be viewable by project members in ordered to be used by project
members. Therefore, the rules for these resources are defined in
project-scoped roles.
This logic creates clusterRoles and clusterRoleBindings for such situations
so that project members can properly use these resources.
Addresses https://github.com/rancher/rancher/issues/12231
> Promote rules from project roles to cluster

- pkg/controllers/management/auth/crtb_handler.go
This change gives cluster owners the ability to set the project level PSPT for a given project in a cluster they are assigned to.  It accomplishes this by moving the PSPTPB into the cluster management plane where teh cluster owner already has * permissions.
Issue:
https://github.com/rancher/rancher/issues/12160
> Adding ability for cluster owner to set project PSPT

- pkg/api/customization/pipeline/cluster_pipeline.go
- pkg/api/customization/pipeline/source_code_credential.go
- pkg/api/customization/pipeline/utils.go
- pkg/api/server/managementstored/setup.go
- pkg/controllers/user/pipeline/controller/clusterpipeline/clusterpipelinesyncer.go
- pkg/controllers/user/pipeline/controller/clusterpipeline/deploy.go
- pkg/controllers/user/pipeline/controller/pipeline/pipeline.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
1. remove NodePort for Jenkins. we don't need it since we're using dialer for connection. 
2. Merge two Jenkins services to one service with two ports(8080 & 50000).
3. filter out `AlreadyExists` error to avoid polluting logs.
4. use clusterpipeline config of the cluster instead of misuse of mockconfig, we need the config for example when connecting a private github.
> pipeline cleanup

- pkg/api/customization/podsecuritypolicytemplate/podsecuritypolicytemplate.go
- pkg/api/server/managementstored/setup.go
This change prevents the deletion of PSPTs assigend to a cluster or
project.  It accomplishes that in 2 ways: 1) by removing the delete link
on the API and 2) by verifying that no projects or clusters have a
rerefence to a given PSPT before allowing it to be deleted, and throwing
an error if that is not the case.
Issues:
#12367
#12368
> Prevent deletion of PSPTs assigned to a cluster/project

- pkg/controllers/user/rbac/podsecuritypolicy/binding.go
- pkg/controllers/user/rbac/podsecuritypolicy/serviceaccount.go
- pkg/controllers/user/rbac/podsecuritypolicy/template.go
This change prevents role bindings from being inappropriately deleted
when the logic to clean up PSPT related role bindings run.  Right now all existing role bindings are deleted, now only role bindings marked with a PSP annotation will be deleted.
Also cleaned up some bad annotation names.
Issue:
https://github.com/rancher/rancher/issues/12872
> Preventing inappropriate role binding deletion

- pkg/api/customization/podsecuritypolicytemplate/podsecuritypolicytemplate.go
This change fixes the missing remove links for PSPTs when all PSPTs are
queried at once.  Because the formatter was using the ID from the
apiContext argument instread of the resource argument, the formatter was
incorrectly showing PSPTs as being assigned to clusters and projects
that did not have PSPTs assigned.  This change fixes the formatter to use
the resource.ID instead.
Issue:
https://github.com/rancher/rancher/issues/12926
> Fixing missing removal links

- pkg/controllers/user/logging/clusterlogging.go
- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/generator/project_template.go
- pkg/controllers/user/logging/projectlogging.go
- pkg/controllers/user/logging/utils/embedded.go
- pkg/controllers/user/logging/utils/logging.go
- pkg/controllers/user/logging/utils/wrap.go
- vendor.conf
- vendor/github.com/prometheus/client_model/.project
- vendor/github.com/prometheus/client_model/bin/.project
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go
Related issue： https://github.com/rancher/rancher/issues/13039
Roll back to use sync reason: we got problem when delete logging, it take time to do the finalized, and in the UI user could still see this CRD, so we change to When user want to disable just set all target to none, so we need to when whether we need to clean the fluent both in update and delete, use sync make it simple, so I roll back to sync and change logic allowed UI set all target to null
Types https://github.com/rancher/types/pull/403
> Fix logging issue

- pkg/auth/providers/activedirectory/activedirectory_client.go
- pkg/auth/providers/providers.go
- Don't swallow error returned by auth provider when looking up principal
- Return a 404 when principal not found by AD
- Return a 500 APIError for all non-404 error responses so that the user sees
a generic error message but a detailed error is logged
Doesnt fully address https://github.com/rancher/rancher/issues/12622 but will give us better error logging to get to the bottom of the problem
> Better error handling for auth providers

- pkg/controllers/user/endpoints/endpoints.go
- pkg/controllers/user/endpoints/ingress_endpoints.go
- pkg/controllers/user/endpoints/workload_endpoints.go
when match service to workload. Also some cleanup fixes for ingress
> Endpoints: Read labels from template spec, not deployment

- pkg/image/export/main.go
Seen this error too many times when using `tar xvzf | docker load`, while not seen when using `--input`
```
Error processing tar file(exit status 1): archive/tar: invalid tar header
```
> Save REGISTRY var and load tar.gz directly into `docker load`

- pkg/controllers/user/endpoints/workload_endpoints.go
- pkg/controllers/user/ingress/ingress.go
Related issue: https://github.com/rancher/rancher/issues/13365
Add the service selector in its creation instead of
let `workloadServiceController` to add it.
This will make the service works more faster.
> Add Selector for ingress services when create

- pkg/api/customization/roletemplatebinding/validator.go
- pkg/api/server/managementstored/setup.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_role_template.go
This change prevents any roles from being assigned via a CRTB or PRTB
when their parent roletemplate has the disabled field set to true.
Issue:
https://github.com/rancher/rancher/issues/13418
Depends on:
https://github.com/rancher/types/pull/425
> Protect role templates

- package/run.sh
https://github.com/rancher/rancher/issues/13495
Tested using:
```
--address 167.99.215.47 --internal-address 10.133.50.236 --etcd --controlplane --worker --debug
time="2018-05-15T19:07:55Z" level=info msg="Option customConfig=map[address:167.99.215.47 internalAddress:10.133.50.236 roles:[etcd worker controlplane]]"
```
```
--address eth0 --internal-address eth1 --etcd --controlplane --worker --debug
time="2018-05-15T19:09:19Z" level=info msg="Option customConfig=map[address:167.99.215.37 internalAddress:10.133.50.211 roles:[etcd worker controlplane]]"
```
```
--address dopublic --internal-address doprivate --etcd --controlplane --worker --debug
time="2018-05-15T19:10:44Z" level=info msg="Option customConfig=map[address:167.99.215.16 internalAddress:10.133.50.145 roles:[etcd worker …
```
> Return given address if not dynamic

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/types/rpc_client.go
Update vendor for PR: https://github.com/rancher/kontainer-engine/pull/63
> Update vendor for kontainer-engine panic

- pkg/api/customization/roletemplatebinding/validator.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_role_template.go
Refactor to use new `lock` over `enabled` for protection of role templates.
Issue:
https://github.com/rancher/rancher/issues/13574
> Refactor to use new lock

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
Update vendor for adding AKS update capability.
Depends on:
https://github.com/rancher/kontainer-engine/pull/64
Issue:
https://github.com/rancher/rancher/issues/13199
> Update vendor for AKS update

- pkg/api/store/cluster/cluster_store.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
https://github.com/rancher/rancher/issues/13075
> Checks to ensure Cluster name unique and required

- pkg/controllers/user/targetworkloadservice/target_workload_service.go
Attempted fix for https://github.com/rancher/rancher/issues/13611 and https://github.com/rancher/rancher/issues/13649. Noticed a couple of `Failed to fetch workload` on @sangeethah setup related to the workloads that were missing as targets for an ingress service. We should ignore only not found errors; and other errors should be propagated to the framework, so the retry would happen.
> TargetWorkload svsc: ignore only not found errors

- pkg/controllers/management/auth/manager.go
- pkg/controllers/user/rbac/prtb_handler.go
- pkg/systemtemplate/template.go
This change corrects an incorrect expression that was supposed to check
if a role was not found but was not, and caused an error to appear in the
logs.
It also adds a new `cattle-admin` role to the default import template so clusters without `cluster-admin` can be imported successfully.
Issue:
https://github.com/rancher/rancher/issues/13196
https://github.com/rancher/rancher/issues/13642
> Role not found fix

- pkg/controllers/user/logging/utils/wrap.go
https://github.com/rancher/rancher/issues/13465
fix elasticsearch prefix format not match with UI show.
> fix elasticsearch format

- app/listenconfig_data.go
we can't update secret on every reload request, reverting for now
This reverts commit e50e0c53a279a335884e6e4036715c9bebcffee7.
https://github.com/rancher/rancher/issues/13619
> Revert "add selfsigned cert as k8s secret"

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- An annotation is set on the cluster when the initial creator role is
populated, but the logic was setting the annotation regardless of whether
or not the roles were populated without error. Changed this such that we
check for an error before setting the annotation on the cluster.
- The logic that created/updated the role was updating the role in a tight
loop and erroring out because of verion conflicts. Changed this such that
the role is only updated once after the loop is exited.A
addresses https://github.com/rancher/rancher/issues/12532
> Fix role creation for mgmt plane resources

- pkg/auth/providers/azure/azure_client.go
Problem:
The secret being used doesn't trigger the refresh to add the
client_secret to the request
Solution:
Change the secret type being used so refresh attaches the client_secret
to requests
> Update azure secret type

- pkg/controllers/management/test/e2e/authz_test.go
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
- vendor/github.com/rancher/kontainer-engine/vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_azure_kubernetes_service_config.go
This change adds support for specifying a virtual network and subnet to
an AKS cluster. Both a virtual network and a subnet must be specified
together or the option will be ignored.
Depends on:
https://github.com/rancher/kontainer-engine/pull/67
https://github.com/rancher/types/pull/469
Issue:
https://github.com/rancher/rancher/issues/13395
> Update vendor for AKS option update

- pkg/controllers/management/auth/manager.go
For: https://github.com/rancher/rancher/issues/14087, https://github.com/rancher/rancher/issues/14086
add project prefix to rolebinding name for prtb in cluster ns to avoid conflicts between projects.
> fix rbac issues

- server/capabilities/aks_version_endpoint.go
This change adds a filter for the k8s version that come back from the AKS version endpoint.  Before all versions were being returned instead of just the list that is valid for AKS.
Issue:
https://github.com/rancher/rancher/issues/13387
> Adding filtering for k8s versions in aks version endpoint

- pkg/controllers/management/auth/manager.go
When resolving roleBindings for a project, we check to see if a
binding exists. If none exists, then we create one. However, this
code has two indexes: one for clusterRoleBindings and one for
roleBindings. This code was incorrectly using the clusterRoleBinding
index while operating on roleBindings. This resulted in the controller
never finding the roleBinding and thus ALWAYS creating a new roleBinding,
which results in many duplicate roleBindings existing.
Addresses https://github.com/rancher/rancher/issues/14115
> Use proper index when determing if binding exists

- pkg/controllers/management/auth/globalrolebinding_handler.go
When the controller for a globalRoleBinding runs, we determine if we
need to create, update, or delete a corresponding clusterRoleBinding.
For update, if we find an existing clusterRoleBinding, we then do a
deepEquals on the binding's actual subject (that represents the user)
against the expected subject (constructed from the globalRoleBinding).
This comparison was flawed because we were not setting the APIGroup
field and so we were always performing an update on the clusterRoleBinding.
The was no user impact because the update is effectively a no-op but
it is inefficent to be performing these updates all the time. This bug
is primarily observable by multiple log entries like this on startup:
```
2018/06/20 17:13:48 [INFO] [mgmt-auth-grb-controller] Updating clusterRoleBinding …
```
> Fix subject comparison on clusterRoleBinding

- pkg/dynamiclistener/server.go
- vendor.conf
- vendor/github.com/rancher/norman/controller/generic_controller.go
http.Server will recover from panics and log the panic's goroutine
dump to its ErrorLogger. By default, the error logger uses the
log package's builtin logger, which typically just logs to stderr.
However, when running rancher in "embedded" mode, kubernetes code
runs which reconfigures the builtin logger to use glog. In this case,
glog is just writing to a file in the /tmp dir, which was causing us
to not print panics.
> Use logrus for logging http server panics

- pkg/catalog/manager/crd.go
This fixes the regression introduced in here https://github.com/rancher/rancher/commit/3c251fc2571efd05c7a077cade14a937bf7a204e#diff-95e2057234f4850727b489c63b63dbb9R122. We are supposed to use catalogNameLabel.
> fix regression on catalog

- pkg/controllers/user/endpoints/endpoints.go
- pkg/controllers/user/endpoints/ingress_endpoints.go
- pkg/controllers/user/endpoints/workload_endpoints.go
This PR gets rid of fetching single ip address in the cluster. It's done by 2 reasons:
* we derive allNodes=true based on cluster being rke, but even then nginx ingress controller might not be deployed on every node (you can pass node labels now via cluster yml config in the UI)
* nginx-ingress is supposed to populate `ingress.addresses` the same way we do derive address for the node with allNodes=true case.
https://github.com/rancher/rancher/issues/14052
WIP as we might need to revise the corresponding code in ingress-nginx @orangedeng.
> Ingress endpoints: read address from ingress

- pkg/api/customization/roletemplate/roletemplate.go
- pkg/api/server/managementstored/setup.go
Problem:
Builtin RoleTemplates can be updated through the API
Solution:
Add a Validator to ensure the only field that can be changed on a
builtin RoleTemplate is 'locked'
Issue: https://github.com/rancher/rancher/issues/13595
> Add Validator for RoleTemplate

- pkg/api/customization/node/node.go
- pkg/api/customization/node/node_driver.go
- pkg/api/server/managementstored/setup.go
- pkg/rbac/access_control.go
Problem:
Cluster owners not able to see node keys
Solution:
Update types being used to check access
Refactor access check to use ID if a namcespaceID is not available
Move node code out of node driver file
Issue: https://github.com/rancher/rancher/issues/14024
> Update node access pieces

- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
This just bumps the fluentd image to the latest v0.1.9 from v0.1.8
> Updated fluentd deps

- pkg/settings/setting.go
Use RancherOS by default instead of boot2docker.
Related to rancher/ui#1975
> vSphere, using RancherOS as default instead of boot2docker

- rke-templates/3-node-certificate-recognizedca.yml
- rke-templates/3-node-externalssl-recognizedca.yml
Without this flag, when an external load balancer is used with a certificate signed by a recognized CA, the ca-cert is not cleared up upon installation/upgrade. It leads to issues with getting correct kubectl configuration files in the UI and incorrect command lines generated to add nodes to custom clusters (and may lead to new nodes in other kind of clusters to fail being provisioned)
> Add the --no-cacerts flag to recognizedCA templates

- pkg/controllers/management/node/utils.go
- pkg/controllers/user/nodesyncer/nodessyncer.go
The node objects were constantly being updated when one of the objects
had a an empty map {} vs a nil map. This comparison takes that into account
and treats them the same. Also, if the objects are not equal a debug
statement was added to see which comparison test was false.
Tracked this down to cause of #14402
> Update isEqual method to handle nil empty maps as the same

- pkg/auth/providers/activedirectory/activedirectory_client.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
Disabling this because many users are running into problems when it is enabled. 
https://github.com/rancher/rancher/issues/14482
> Nested groups lookup disabled by default for AD/Openldap

- pkg/controllers/user/networkpolicy/netpol.go
Currently, in debug, we are logging the entire array of nodes then printing them one by one. The array is unnecessary to view and in larger clusters is difficult to grok at all and is duplicated.
So this just now outputs the length of the array as that seems like it could be correlated to cluster node count. 
I also removed the entire node output except in the case where there is an error. I also added node name to the pod error when the cidr fails just for clarity.
> clean up debug logs for netpolmgr

- pkg/controllers/user/networkpolicy/netpol.go
- pkg/controllers/user/networkpolicy/nodehandler.go
- pkg/controllers/user/networkpolicy/nssyncer.go
- pkg/controllers/user/networkpolicy/pnpsyncer.go
- pkg/controllers/user/networkpolicy/podhandler.go
- pkg/controllers/user/networkpolicy/projectsyncer.go
- pkg/controllers/user/networkpolicy/register.go
- pkg/controllers/user/networkpolicy/servicehandler.go
- pkg/controllers/user/nodesyncer/nodessyncer.go
* reduce the amount of v3.node updates by not processing pod events as k8s syncs up nodes every 5 seconds anyway
* minor performance fixes to network policy code to eliminate unnecessary updates.
* network policy fixes to return error instead of logging it, so the framework would retry the update
https://github.com/rancher/rancher/issues/14372
https://github.com/rancher/rancher/issues/14402
> Performance improvements in nodesyncer and netpolicy

- pkg/controllers/user/controllers.go
- pkg/controllers/user/ingress/ingress.go
- pkg/controllers/user/ingress/ingress_common.go
1. Fixed issue for https://github.com/rancher/rancher/issues/13717.
We will only create node port service for ingress in GKE cluster.
If there is a node port service for non-GKE cluster, we will recreate it
2. Make ingress services controller's logic more clean.
> Refector ingress service controller logic

- pkg/controllers/user/rbac/podsecuritypolicy/serviceaccount.go
This change fixes an issue where newly created service accounts sometimes
do not get a role binding created for them, and therefore cannot create
pods because they don't have an associated pod security policy. This
is happening because role bindings are being incorrectly deleted and,
coupled with a race condition in the serviceaccount.go logic, are not
recreated successfully. This change prevents those role bindings from
being deleted incorrectly and causes the service accounts to have their
psps assigned correctly.
Issue:
https://github.com/rancher/rancher/issues/14441
> Fixing issue where service account did not get PSP bound

- pkg/kubeconfig/templates.go
https://github.com/rancher/rancher/issues/14488
> Don't print empty certificate-authority-data in kubeconfig

- pkg/api/store/workload/workload_store.go
- tests/core/test_workloads.py
changing imagePullSecrets unnecessarily result into pod restart, change it when
1) image changes
2) length of containers changes, pod restart happen anyway
https://github.com/rancher/rancher/issues/13872
> refresh imagePullSecrets on image change

- app/app.go
- app/podsecuritypolicytemplate_data.go
This change adds default PSPTs for rancher.  It includes a "restricted"
and "unrestricted" PSPT.  The unrestricted PSPT is effectively the same
as having no PSP admissions controller enabled, while the "restricted"
PSPT prevents priviledge escalation and various other user actions.
Issue:
#12832
> Default PSPTs

- app/role_data.go
- pkg/controllers/management/auth/crtb_handler.go
The purpose of this PR is to define RBAC permissions for `resourceQuotaTemplate` type, so ClusterOwner/ClusterMember can do anything, and other roles can only View.
> Default RBAC permissions for resource quota template

- pkg/rkeworker/docker.go
- vendor.conf
- vendor/github.com/rancher/rke/cluster/certificates.go
- vendor/github.com/rancher/rke/cluster/network.go
- vendor/github.com/rancher/rke/cmd/config.go
- vendor/github.com/rancher/rke/docker/docker.go
- vendor/github.com/rancher/rke/hosts/dialer.go
- vendor/github.com/rancher/rke/pki/pki.go
- vendor/github.com/rancher/rke/services/controlplane.go
- vendor/github.com/rancher/rke/services/etcd.go
- vendor/github.com/rancher/rke/services/healthcheck.go
- vendor/github.com/rancher/rke/vendor.conf
This fix compares the process env by appending Dockerfile env and process env and compares it by the docker inspect env. the fix should make sure that when delete env it will be reflected in the k8s component 
https://github.com/rancher/rancher/issues/14471
> Compare env correctly

- pkg/controllers/user/namespace/namespace_utils.go
- pkg/controllers/user/rbac/handler_base.go
- pkg/controllers/user/rbac/namespace_handler.go
- pkg/controllers/user/resourcequota/register.go
- pkg/controllers/user/resourcequota/resource_quota_calculate_used.go
- pkg/controllers/user/resourcequota/resource_quota_sync.go
- pkg/controllers/user/resourcequota/resource_quota_validate.go
As we can't set rbac before init resource quota is created, it would
make sence to call the code in rbac controller, rather than make it fail
while waiting for the other controller to do the init (given rbac is a
lifecycle controller, it will always be invoked first, and fail on wait
for the first time)Init resource quota in rbac lifecycle
@dramich to address the `waiting for resource quota init` issue you've noticed
> Init resource quota in rbac lifecycle

- pkg/settings/setting.go
- pkg/telemetry/telemetry.go
- The three supported values for `telemetry-opt` are `prompt`, `in`, and `out`.
- The default setting value should be `prompt`, which makes the UI ask on login.
- The server should run only when the value is exactly `in`.
- The server should be stopped when the value is NOT exactly `in` (this is not the same as `== "false"` (or `"in"`)).
> Telemetry setting values

- pkg/api/controllers/samlconfig/samlconfig.go
- pkg/auth/providers/saml/saml_client.go
- pkg/auth/providers/saml/saml_provider.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/apis/rbac.authorization.k8s.io/v1/zz_generated_cluster_role_binding_controller.go
- vendor/github.com/rancher/types/apis/rbac.authorization.k8s.io/v1/zz_generated_cluster_role_controller.go
- vendor/github.com/rancher/types/apis/rbac.authorization.k8s.io/v1/zz_generated_role_binding_controller.go
- vendor/github.com/rancher/types/apis/rbac.authorization.k8s.io/v1/zz_generated_role_controller.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_adfs_config.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_ping_config.go
- vendor/github.com/rancher/types/vendor.conf
Two of the current SamlConfig's fields (SPSelfSignedCert and SPSelfSignedKey) don't match their json tags (spCert and spKey respectively). Because of this, mapstructure.Decode wasn't decoding them correctly, and so we were using a custom decoder. But that is causing problems with the fields like AccessMode on the embedded AuthConfig type. So this PR changes the field names to match the json tags, so there's no need to use the custom decoder, and we can switch to mapstructure.Decode
https://github.com/rancher/rancher/issues/14762
> Change SamlConfig field names to match json tags

- vendor.conf
- vendor/github.com/rancher/norman/controller/generic_controller.go
- vendor/github.com/rancher/norman/controller/noop_metrics.go
related to #14356 
Metrics are created and never deregistered whenever controllers are removed. These metrics are very large. Since we are not currently exposing a metrics endpoint, we are disabling them for now.
> Update norman dependency

- pkg/auth/providers/saml/saml_client.go
- pkg/auth/providers/saml/saml_provider.go
https://github.com/rancher/rancher/issues/14797
https://github.com/rancher/rancher/issues/14798
https://github.com/rancher/rancher/issues/14805
GetPrincipal and SearchPrincipals for all auth providers other than Ping set the principalType to "user" or "group". And Ping was setting it to ping_user/ping_group, that's why, when a member was added to a project/cluster, since the principal type would not be "user", no user would get created, unlike for any other providers like AD. This resulted in appropriate role bindings not getting created
> Change principal type to user or group

- Dockerfile.dapper
- pkg/image/export/main.go
- scripts/build-server
https://github.com/rancher/rancher/issues/14502
After updating to go1.10.3, the CGO_ENABLED=0 part of build command
in build-server script threw this error "loadinternal: cannot find runtime/cgo"
and then that would eventually lead to a segmentation fault. The build
would just freeze without running any tests. This commit removes CGO_ENABLED=0,
since cgo is disabled by default when cross compiling, as per https://golang.org/cmd/cgo/
f164240
> Update golang version to fix golang TLS issue for AD

- pkg/api/customization/project/project_store.go
- pkg/controllers/management/auth/project_cluster_handler.go
- tests/core/test_default_roles.py
Problem:
A roleTemplate set to both locked and default is being applied when a
new cluster or project is created
Solution:
Verify a roleTemplate is not locked before using it as a default
Issue: https://github.com/rancher/rancher/issues/14788
> Update roleTemplates to not use locked ones if set as default

- pkg/api/customization/cluster/formatter.go
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
- vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go
- vendor/github.com/rancher/kontainer-engine/drivers/options/options.go
- vendor/github.com/rancher/kontainer-engine/types/types.go
- vendor/github.com/rancher/kontainer-engine/vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_google_kubernetes_engine_config.go
This change adds logic to the cluster formatter to show certain nil
fields as true when they are returned from the api.  This is so that the
fields are persisted correctly after the cluster is updated.
Issue:
https://github.com/rancher/rancher/issues/13789
Depends on:
https://github.com/rancher/kontainer-engine/pull/77
https://github.com/rancher/types/pull/531
> Update vendor for GKE Option rename

- pkg/auth/providers/saml/saml_client.go
Problem:
When attempting to login with a user which is not enabled no error is
presented in the UI.
Solution:
Add a check on the user for enabled and redirect with an error.
Previously this was being caught on the token so the UI would not
show/redirect an error.
Issue: rancher/rancher/issues/10646
> Add user enabled check for saml

- pkg/controllers/user/endpoints/endpoints.go
- pkg/controllers/user/ingress/ingress.go
Refer to https://github.com/rancher/rancher/issues/14052
We should get ingress service state key as the same way we do in
ingress store.
Refer to https://github.com/rancher/rancher/issues/13743
Show host ip in public instead of node ip if host ip is set.
> Fix default backend service not create issue

- pkg/controllers/user/rbac/namespace_handler.go
The InitialRolesPopulated condition was  getting set to true
prematurely. This fixes that. Also, change the initial value
of the condition from False to Unknown because False is interpertted
as an error state in rancher.
This was previously fix but reintroduced in 2b6779719115fd4ede7ab4ec19eca19c97e4e4cb
as a result of a rebase conflict.
Addresses https://github.com/rancher/rancher/issues/13703
> Dont immediately set namespace to active

- pkg/controllers/management/nodepool/nodepool.go
Comparing roles against empty map causes node roles to update on upgrade,
which changes role order causing spec to unnecessarily change.
Resolves: #14914
> Compare node roles correctly

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
This will result into controller syncing up network policies, and setting status
to true.
https://github.com/rancher/rancher/issues/14851
> set enableNetworkPolicy of cluster spec=true for upgraded canal clusters

- pkg/clustermanager/manager.go
By default k8s client libray will cache transport based on the hash key
of tlsConfig. This will reuse the previous transport if we have the same
tls config. By making a new tranport for each rest.config so that we
don't reuse any of the cache transport.
> use new transport instead of existing cache transport

- app/role_data.go
- pkg/api/customization/authn/user_store.go
- pkg/auth/principals/handler.go
- pkg/auth/providers/common/usermanager.go
- pkg/controllers/management/auth/user.go
- tests/core/conftest.py
- tests/core/test_rbac.py
- vendor.conf
- vendor/github.com/rancher/types/mapper/container_status.go
- vendor/github.com/rancher/types/user/manager.go
Problem:
A user has too much permission to view resources such as users and
principles
User secret is not being deleted
Solution:
Remove permissions and add a clusterRoleBinding to the user so they are
still able to see themselves. This is required for login/UI and general
QOL.
Update user secret delete to be namespaced
Issue: rancher/rancher#15061
Issue: rancher/rancher#15067
> Restrict users permissions

- tests/requirements.txt
I was having runtime errors with the existing version of flake8.
Some googling yields some info here: https://gitlab.com/pycqa/flake8/issues/240.
Fixed in flake8 3.1+, so just upgrading to latest.
> Upgrade flake8 to latest (3.5.0)

- pkg/api/customization/node/node.go
- pkg/api/store/node/store.go
- pkg/controllers/user/controllers.go
- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- pkg/controllers/user/nodesyncer/nodessyncer.go
- pkg/kubectl/kubectl.go
Feature: Ability to drain node 
- `drain` action available on node 
- if drained successfully, state should show `drained`, else it'll stay in `draining` state and error message would be displayed in logs, UI and under conditions (NodeCondition `Drained`) 
- to stop the draining process, use the `stopDrain` action. 
- to call `drain` from API, the input would look like - 
```
curl -u $token --insecure -H 'Content-Type: application/json' https://localhost:8443/v3/nodes/local:machine-k6ct9?action=drain-X POST -d '{"deleteLocalData":"true","force":"false","gracePeriod":"-1","ignoreDaemonSets":"true","timeout":"20"
``` 
- Information about the params and default values - 
```
type NodeDrainInput struct {
// Drain node even if there are pods not managed by a ReplicationController, Job, or …
```
>  Adding action drain on node

- tests/core/conftest.py
when a test fails due to a failed request (for example not being able to auth), the code just continues on until it hits a miscellaneous runtime error (like a response dict not having a token)
This just adds a function to validate that a response yielded a 2XX status code, otherwise it errors out with the code and response body
> Validate response codes in tests

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- tests/core/test_default_roles.py
Problem: The UI cannot display project and cluster creator
on the members page. This is because we change the permissions
on the user role such that non-admin users can no longer list
users at /v3/users.
Solution: The UI only uses /v3/users to look up members as a
fallback. It first tries to hit /v3/principals, which normal users
DO have access to. The problem was that we were not setting the
userPrincipalId on the special "creator" CRTB/PRTBs that are
created when a project or clsuter is created.
So, we just need to set that userPrincipalId field on the CRTBs
and PRTBs to allow the UI to resolve the principal properly.
https://github.com/rancher/rancher/issues/15160
> Fix an issue where members could not be resolved

- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/generator/project_template.go
- pkg/controllers/user/logging/projectlogging.go
https://github.com/rancher/rancher/issues/15155
Unset message when disable project logging
https://github.com/rancher/rancher/issues/14465
https://github.com/rancher/rancher/issues/14464
fix syslog throw error in fluent when no program field
> improve syslog config

- pkg/controllers/user/helm/common.go
Problems: when generating notes it failed if some of answer fields are
missing
Solution: adding value answer when generating notes.(this is a bug, we
should always add that)
> add answers value when generating notes

- pkg/dialer/factory.go
- pkg/remotedialer/client/main.go
- pkg/remotedialer/client_dialer.go
- pkg/remotedialer/dialer.go
- pkg/remotedialer/dummy/main.go
- pkg/remotedialer/message.go
- pkg/remotedialer/peer.go
- pkg/remotedialer/server.go
- pkg/remotedialer/server/main.go
- pkg/remotedialer/session.go
- pkg/remotedialer/session_manager.go
- pkg/settings/setting.go
- pkg/tunnelserver/peermanager.go
- pkg/tunnelserver/tunnel.go
Adds the ability to run more that 1 Rancher server in a HA setup.
The enabling change is that the remotedialer tunnels will now call
across to peers to connect to the proper node owning the tunnel.
> Make Rancher go to 11

- pkg/api/customization/node/node.go
- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- show stopDrain when node is draining
- don't unlock map twice
https://github.com/rancher/rancher/issues/15260
> add fixes for stopDrain node

- app/machinedriver_data.go
With current version provisioning cluster failed because driver did not store the private IP address in the expected field: https://github.com/rancher/rancher/blob/4ba5297c7acdd6d1407e5d0f0d3a7a780c0b1a7d/pkg/nodeconfig/config.go#L114
> Update OTC machine driver URL

- pkg/auth/providers/common/usermanager.go
Problem:
CreateNewUserClusterRoleBinding attempts to create the role and binding
for a user, under a race this can error and return an alreadyExists
Solution:
Ignore alreadyExists errors here and continue
> Ignore alreadyExist error in usermanager

- Dockerfile.dapper
- package/Dockerfile
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/controller.go
- tests/core/common.py
- tests/core/test_app.py
- tests/core/test_catalog.py
- vendor.conf
- vendor/github.com/rancher/rke/cluster/plan.go
- vendor/github.com/rancher/rke/cluster/validation.go
- vendor/github.com/rancher/rke/cmd/config.go
- vendor/github.com/rancher/rke/docker/docker.go
- vendor/github.com/rancher/rke/hosts/dialer.go
- vendor/github.com/rancher/rke/vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
This pr fixes several issues:
1. deployApp is no longer called in create lifecycle. All the logic is
handled through update. Also we don't delete bad release if it failed to
install for the first time. Related issue:
https://github.com/rancher/rancher/issues/15264,
https://github.com/rancher/rancher/issues/15252
2. Handle the error message gracefully so that when users failed to
install, proper error message is presented. (permission and etc...)
3. Add to check to ensure the port allocated to helm and tiller is not
used.
> more improvement for app deploy

- pkg/controllers/user/helm/common/common.go
This resolves the similar issue in the [PR](https://github.com/rancher/rancher/pull/15043), but fixed for set type during install the charts. @StrongMonkey @cjellick .
comments: If we use --set-string, all the value will be considered a string. This won't be a problem for just rendering templates because they just render string, but the thing would break if you expect to compare a boolean or number. #15344
> revert use set-string in install charts

- pkg/controllers/user/nodesyncer/nodessyncer.go
we have to assert the correct role for worker nodes, as we rely on the
role to collect stats only when node has worker role. But for nodes that
belongs to cloud provider cluster, all three roles are set to false, so
we have to take it as a worker. Otherwise the stats collected to cluster
won't be correct.
> set the right role for worker

- package/run.sh
- pkg/agent/clean/clean.go
- pkg/agent/main.go
- pkg/controllers/management/usercontrollers/controller.go
- pkg/controllers/user/rbac/crtb_handler.go
- pkg/controllers/user/rbac/handler_base.go
- pkg/controllers/user/rbac/namespace_handler.go
- pkg/controllers/user/rbac/prtb_handler.go
- pkg/controllers/user/rbac/roletemplate_handler.go
- pkg/systemtemplate/template.go
rancher/rancher#14207
rancher/rancher#14848
rancher/rancher#13512
Docs: https://github.com/rancher/docs/issues/742
(copied from issue 14207)
The solution for this is to create a job that runs in the user cluster and cleans up.
To start, rancher server will create a clusterRole, clusterRoleBinding, serviceAccount and job in the user cluster that is being removed. These are all tied together with an ownerReference back to the job. The job will run the agent image with an env var that is specific to cleanup duty. Starting with the version this is released in (2.1 at this point) the job will perform additional cleanup compared to older versions. If the job runs successfully it will delete itself which in turn deletes the clusterRole, clusterRoleBinding and serviceAccount. If the job fails it …
> Cleanup imported cluster on delete

- pkg/api/customization/nodetemplate/formatter.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/nodetemplate/store.go
- tests/core/test_node.py
Problem:
A user can delete a nodeTemplate at anytime, this causes issues when
trying to scale nodes
Solution:
Check if the template is being used and if it is do not allow it to be
deleted and remove the 'remove' link from the api
Issue: rancher/rancher#13354
>  Stop in-use nodeTemplate from being deleted

- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- pkg/controllers/user/nodesyncer/nodessyncer.go
update node condition before calling kubectl drain, so that ui shows draining.
https://github.com/rancher/rancher/issues/15298
> reflect node condition draining

- Dockerfile.dapper
- pkg/api/customization/podsecuritypolicytemplate/podsecuritypolicytemplate.go
- pkg/controllers/user/alert/watcher/node.go
- pkg/controllers/user/alert/watcher/pod.go
- pkg/controllers/user/alert/watcher/syscomponent.go
- pkg/controllers/user/alert/watcher/workload.go
- pkg/controllers/user/dnsrecord/dnsrecord.go
- pkg/controllers/user/externalservice/external_ip_service.go
- pkg/controllers/user/logging/utils/daemonset.go
- pkg/controllers/user/targetworkloadservice/target_workload_service.go
- pkg/image/export/main.go
- pkg/pipeline/remote/gitlab/gitlab.go
- pkg/rkenodeconfigserver/nodeserver.go
- pkg/telemetry/telemetry.go
- scripts/build-agent
- scripts/build-server
1. I tried upgrading rancher to golang 1.11, its again failing with same error as it did for go 1.10.3/4
```
Running: go fmt
loadinternal: cannot find runtime/cgo
loadinternal: cannot find runtime/cgo
Running tests
./test: line 37: 30468 Trace/breakpoint trap   (core dumped) KUBECONFIG= ../../$CMD --add-local=true  (wd: /go/src/github.com/rancher/rancher/build/testdata)
```
2. Then I tried removing CGO_ENABLED=0 from build-server/build-agent. `make ci` was successfult, but then rancher server crashed while creating a single node DO cluster with some cgo related errors.
```
goroutine 20542 [syscall]:
runtime.cgocall(0x3d0ad10, 0xc435f24f58, 0x51c3a04)
/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc435f24f10 sp=0xc435f24ed8 pc=0x4022f4
os/user._Cfunc_mygetgrgid_r(0x0, 0xc425e7f540, …
```
> Update rancher golang version to 1.11

- pkg/api/customization/node/node.go
- pkg/api/store/cluster/cluster_store.go
Problem: since this field is on cluster level, making it true in
default setting results into error for non-RKE clusters. 
https://github.com/rancher/rancher/issues/15432
https://github.com/rancher/rancher/issues/15430
> validate enableNetpolicy only on update

- pkg/dialer/factory.go
- pkg/tunnelserver/tunnel.go
Two machines with the same hostname in two different clusters will clash for the dialer session.  The end result is if you have two clusters with nodes with the same hostname and you are using RKE, one of the clusters will not provision.
> Use cluster.Name + machine.Name for dialer session key

- pkg/api/controllers/dynamiclistener/listener_controller.go
- pkg/api/controllers/dynamiclistener/listener_controller_test.go
- pkg/dynamiclistener/server.go
- vendor.conf
- vendor/github.com/rancher/norman/parse/builder/builder.go
- vendor/github.com/rancher/norman/types/convert/convert.go
Adding logic to strip preceding and following newliens from ca certs so that
checksums are calculated properly.  This is to fix an issue where
rancher-agents could not connect to rancher.
Issue:
#13831
Depends on:
https://github.com/rancher/norman/pull/194
> CA linefeed fix

- pkg/api/store/node/store.go
On node update, requestedHostname doesn't get updated with the custom name user gives. So I think maybe we don't need to validate this name. 
@carolynhu could you check if I am missing any case? 
I found this because when an action on node tries to update the node, it's hostname is `""` and validation throws an error for empty name (https://github.com/rancher/rancher/blob/a82b46c977fd338f6a2c8040e3d10fab7fb6581b/pkg/api/store/node/store.go#L126)
(https://github.com/rancher/rancher/issues/15529).
> don't validate hostname on node update

- package/Dockerfile
Addresses https://github.com/rancher/rancher/issues/15506
We listen for a call to /usr/bin/ensure-default-admin, but we weren't actually linking that location to the binary.
> link /usr/bin/ensure-default-admin in dockerfile

- pkg/api/customization/nodetemplate/formatter.go
Fixes: https://github.com/rancher/rancher/issues/13978
Because Watch doesn't use the queryOpts to filter as expected, and because we cheat on nodetemplates by just giving everyone list access, any watcher will receive ALL new nodetemplates, instead of just those for that user. This hack uses the formatter to check if the nodetemplate should be visible, and blanks it out if not.
> Clear nodetemplate for user if their ID doesn't match the namespace

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
See https://github.com/rancher/rancher/issues/15484
This brings in changes to kontainer-engine to enable EKS eu-west-1 for new clusters. Depends on https://github.com/rancher/kontainer-engine/pull/82
This is a backend only change, the UI declares these separately and will need to be updated accordingly
> Enable eu-west-1 for new EKS clusters

- pkg/controllers/user/alert/upgrade/upgradeimpl.go
- pkg/controllers/user/logging/upgrade/upgradeimpl.go
- pkg/controllers/user/pipeline/upgrade/upgradeimpl.go
- pkg/controllers/user/systemimage/systemimage.go
https://github.com/rancher/rancher/issues/15465
Add project delete check, when the cluster is deleted, but project crd not clean yet, and the sync func may get error.
> add more check for upgrade system image

- app/ensure_admin_user.go
This performs reparations in regards to #15613
When we create a new user, the Enabled pointer is nil, it has an assumed default of true. Since we were dereferencing the pointer, it would panic if they had not previously been explicitly enabled/disabled.
> Make sure to nilcheck Enabled in enable-default-admin

- pkg/catalog/manager/manager.go
- tests/core/test_catalog.py
Adding a lock on the hash value of (git repo + branch) to prevent
concurrent operations on the same git repo.
> lock git operations on repo hash

- pkg/api/customization/node/node.go
- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- retry node update on drain if conflict error 
- allow drain again on failed drain when node is in cordoned state 
- add logs 
https://github.com/rancher/rancher/issues/15590 
https://github.com/rancher/rancher/issues/15611
> retry node update on drain if conflict error

- app/ensure_admin_user.go
See https://github.com/rancher/rancher/issues/15506#issuecomment-421504226
The labels would work because we're reaching down into a pointer within the object, but enabled would fail because we were passing a direct struct reference down so the change didn't propagate back up.
> Pass pointers to admin in ensure script

- package/Dockerfile
Added volume incase user forgets to do it, and ends up logging to a layer in the overlay.
> Add volume for audit log

- pkg/controllers/management/nodedriver/machine_driver.go
This commit sets both installed and downloaded condition to unknown so that nodeDriver can be re-downloaded if driver doesn't exist. Fix https://github.com/rancher/rancher/issues/15661
> set condition to unknown if driver doesn't exist

- pkg/auth/providers/activedirectory/activedirectory_client.go
- pkg/auth/providers/common/ldap/ldap_util.go
- pkg/auth/providers/ldap/ldap_client.go
Problem:
An error is being logged but not returned. This causes the caller to
panic when attempting to dereference the pointer
Solution:
Return the error instead of logging it allowing caller to catch the
error
Issue: https://github.com/rancher/rancher/issues/15757
> Return error in LDAP

- rke-templates/3-node-certificate-recognizedca.yml
- rke-templates/3-node-certificate.yml
- rke-templates/3-node-externalssl-certificate.yml
- rke-templates/3-node-externalssl-recognizedca.yml
When etcd rolling snapshots are attempted to be enabled with `backup: true`, RKE does not respect this parameter. We must change the rke-allinone config files to reflect `snapshot: true`
> Correcting snapshot to backup for etcd rolling snapshots

- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/generator/project_template.go
Issue: https://github.com/rancher/rancher/issues/15631
@aemneina Get log truncate in syslog-ng, update tcp max packet_size to fix it.
Details:  find that the plugin we use have a config call package_size, after some test, I find that config quite like the max size for each log. For example, the host mtu is 1500, and if I config the package_size to 1500, and the log size is 1600, this log will be separate to 2 packets, one length is 1440, another is 61(total is 1501). And the log exceeds 1500 will lost, it has been truncated before send out. So we could config default value for the packet_size to the max tcp packet and just let  lower layers protocol to split the log into several packets and deliver them.
> update tcp max package size

- pkg/controllers/user/nodesyncer/nodessyncer.go
Haven't been able to reproduce, but adding version comparisons on node sync to reflect the updated info just in case. 
https://github.com/rancher/rancher/issues/15830
> compare k8sversion on nodeStatus

- pkg/auth/providers/activedirectory/activedirectory_client.go
"Contains" match used in Active Directory for looking up groups seems to be taking long time. This PR changes the group lookup query to use "Begins-with" match
> Change AD group search query to use begins-with match

- Dockerfile.dapper
- tests/requirements.txt
- tests/tox.ini
Update the tests to use python3.7. 
This also updates all current pinned dependencies to the most recent version.
> Update tests to use python3.7

- pkg/auth/providers/azure/azure_provider.go
`groups` needs to be saved in the loop context like `i`
> Fix azure groups

- pkg/agent/cluster/controllers.go
- pkg/agent/main.go
- pkg/controllers/user/controllers.go
- vendor.conf
- vendor/github.com/rancher/types/config/context.go
Start of moving the user controllers to the agent. The controllers currently being moved do not require access back to the management plane. 
Issue: https://github.com/rancher/rancher/issues/15100
Requires https://github.com/rancher/types/pull/594
> Move user controllers to agent

- pkg/api/store/workload/aggregate_store.go
The nil check before the range loop is redundant (see https://staticcheck.io/docs/gosimple#S1031)
> Remove redundant nil checks

- pkg/controllers/management/clusterstatus/temporarycredentials.go
- pkg/controllers/management/controller.go
- tests/core/test_kontainer_engine_validation.py
This change adds a controller that looks for the `sessionToken` to be present
on the EKS config, and if it is there, add an annotation to the cluster.  The
reason this is necessary is becuase credentials that have a `sessionToken`
will expire and the UI must take additional steps to refresh the credentials
before attempting an operation on the cluster, but because `sessionToken` is a
password field, it will be hidden from the UI also.
Issue:
https://github.com/rancher/rancher/issues/16005
------------
Also contains a change that modifies how some of the kontainer-engine validation tests were
running to make sure they wait for the `provisioned` condition to appear on
the cluster before asserting that a value is present.  Before this change a
race condition was present and sometimes the …
> Adding controller to add a sec token annotation

- app/authconfig_data.go
- pkg/api/controllers/samlconfig/samlconfig.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/password/store.go
- pkg/auth/providers/activedirectory/activedirectory_actions.go
- pkg/auth/providers/activedirectory/activedirectory_provider.go
- pkg/auth/providers/azure/azure_actions.go
- pkg/auth/providers/azure/azure_provider.go
- pkg/auth/providers/common/password.go
- pkg/auth/providers/github/github_provider.go
- pkg/auth/providers/github/githubconfig_actions.go
- pkg/auth/providers/ldap/ldap_actions.go
- pkg/auth/providers/ldap/ldap_provider.go
- pkg/auth/providers/saml/saml_actions.go
- pkg/auth/providers/saml/saml_client.go
- pkg/auth/providers/saml/saml_provider.go
(Currently, this works only for authConfigs, more work to be done for 
- cluster and node types, should be done along with nodetemplate changes 
- project pipeline types, need to figure out if store can be used for them) 
`password/store.go` contains generic logic to create secret for any field that is of type password. To add a schema that has password fields, it needs to be added to `pwdTypes`. 
Create/Update would create secret and store reference to it as value, ByID puts the actual data back.
> create secrets for password fields in authconfigs 

- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/clusterstatus/temporarycredentials.go
- tests/core/test_kontainer_engine_annotations.py
- tests/core/test_kontainer_engine_validation.py
This change makes is to that the temporary security credentials annotation
displays immediately on the cluster instead of only after the cluster has
finished provisioning.
Issue:
#16005
--------
Also corrects an intermittent test failure do to the condition dict having
no `message` field on it.
> Display Temporary Security Credentials annotation immediately on cluster create

- pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/16282
This PR will prevent the agent from restarting the components containers if the private registries configuration changed. This is ok since the container doesn't use this configuration anyway, it's passed to docker earlier to be able to pull the image.
> Fix worker kubelet restart with private regsitries

- pkg/api/store/workload/transform_store.go
If `opt.Options["hidden"]` set true, replicaSets should be shown in API and hide should remain false, otherwise no replicaSets would be listed under `/revisions`. 
https://github.com/rancher/rancher/pull/16267
Issue: https://github.com/rancher/rancher/issues/16408 
Backport Issue: https://github.com/rancher/rancher/issues/16409
> hideByOwner only if opt.Options[hidden] is not set

- pkg/auth/providers/local/local_auth_provider.go
This solves the issue #15435. 
The approach to fix the timing attack is evaluating always the password, even when there is no user.
> Fix user enumeration in local auth provider

- pkg/controllers/user/endpoints/endpoints.go
- pkg/controllers/user/endpoints/pod_endpoints.go
as pod annotaitons updates are disallowed on k8s 1.12, and the pods' endpoints weren't used anywhere in the UI anyway. The workloads' endpoints should be used as a reference instead
https://github.com/rancher/rancher/issues/15963
> Do not update endpoints on pods

- pkg/catalog/git/git.go
- pkg/catalog/helm/helm.go
- pkg/catalog/manager/catalog_sync.go
- pkg/catalog/manager/cluster_catalog_sync.go
- pkg/catalog/manager/manager.go
- pkg/catalog/manager/project_catalog_sync.go
- pkg/catalog/manager/traverse.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/catalog_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_catalog.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_catalog_spec.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_catalog.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_project_catalog.go
Address #13371 
1. support http/s helm catalog server with basic auth.
2. support git clone for private repo with username and password(access token).
Types PR: rancher/types#599
UI Issue: https://github.com/rancher/rancher/issues/16244
> Add support for private catalog

- pkg/controllers/management/usercontrollers/controller.go
Sets PropagationPolicy to "background" for local cluster cleanup removal of agent deployments & daemonsets.
For rancher/rancher/issues/16571
> Set propagation policy to background for agent deletion

- pkg/api/server/managementstored/setup.go
- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/clusterprovisioner/driver.go
For existing clusters, the snapshot value for the etcd service is nil. The RKE driver will interpret this as true, but we want it to behave as false in the API. We catch it before norman applies defaults (which would cause it to show as true), and say that if it is nil, it is false. 
We also now convert a nil value for the snapshot setting as false. This only happens when we're already planning on passing the clusterspec to the driver update. This way, nil snapshot values which are considered false in the UI don't get handled as true in the RKE driver
> Fix snapshot upgrade

- pkg/controllers/user/globaldns/user_cluster_ingress.go
@alena1108 uncommented the check for multiClusterAppName in the GlobalDNS user cluster ingress controller
> Check to make sure the multiClusterAppName on globalDNS matches the app

- pkg/httpproxy/proxy.go
Drop another header that CloudFlare uses to detect loops so that User -> Rancher behind CloudFlare -> DigitalOcean behind CloudFlare works.  https://github.com/rancher/rancher/issues/11280
> Drop another cloudflare header

- pkg/controllers/management/drivers/kontainer_driver.go
- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_kontainer_drivers.py
This change renames the example driver to support the new kontainer engine
driver naming convention. The new convention is
`kontainer-engine-driver-<<driver name>>-<<extra info>>`.
Depends on:
https://github.com/rancher/kontainer-engine-driver-example/pull/3/
Issue:
https://github.com/rancher/rancher/issues/16842
> Changing kontainer engine driver naming convention

- pkg/api/customization/kontainerdriver/formatter.go
- pkg/api/server/managementstored/setup.go
- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/conftest.py
- tests/core/test_kontainer_drivers.py
This change corrects the activate/deactivate links on kontainer drivers. The
activate/deactivate links were not being shown because the kontainer driver
setup function was not being called in setup.go.  This change adds that
function call in and also adds a test to prevent a regression.
Issue:
https://github.com/rancher/rancher/issues/16858
> Fixing kontainer driver activate/deactivate links

- app/role_data.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/prtb_handler.go
Problem:
other role do not have access to cluster/project alert
Solution:
add role for clusteralertgroups, clusteralertrules, projectalertgroups, projectalertrules
Issue: 
https://github.com/rancher/rancher/issues/16954
> Config alert access for different role

- pkg/controllers/user/alert/initdata.go
Problem:
Now the etcd has leader alert is leader less than 1
Solution:
Change to not equal to 1
Issue:
https://github.com/rancher/rancher/issues/16945
> Precan alert for etcd has leader should be not equal to 1

- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
**Problem:**
`time.Sleep` will give up the time slice then cause the next goroutine
dispatch to become dull, this isn't user friendly
**Solution:**
Remove `time.Sleep`
**Issue:**
https://github.com/rancher/rancher/issues/16996
> Remove time sleeping on monitoring status detection

- pkg/settings/setting.go
Problem: The UI currently has to basically hard code the K8S
versions it allows and defaults to for the cloud providers it
integrates with.
Solution: Add settings that will allow the UI to dynamically
determine the allowed range and default version.
> Add settings for UI K8S versions

- pkg/controllers/user/rbac/namespace_handler.go
Problem:
Ocassionally we see panics in our builds bc of a concurrent read/write
on the namespace's annotation property
Solution:
Deep copy the namespace so that there is no chance of the concurrent
read/write
https://github.com/rancher/rancher/issues/16891
this is the panic we see:
```
runtime.throw(0x3437b44, 0x21)
/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:608 +0x72 fp=0xc006ace440 sp=0xc006ace410 pc=0x102e112
runtime.mapaccess2_faststr(0x2ee5560, 0xc0061128d0, 0x34245a8, 0x19, 0x0, 0x0)
/usr/local/Cellar/go/1.11.1/libexec/src/runtime/map_faststr.go:110 +0x458 fp=0xc006ace4b0 sp=0xc006ace440 pc=0x1014608
github.com/rancher/rancher/pkg/controllers/user/rbac.updateStatusAnnotation(0x0, 0xc0039bd330, 0x9, 0xc0039bd318, 0x2, 0xc0039bd340, 0x7, 0x0, 0x0, 0x0, ...) …
```
> Fix concurrent map read and map write

- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
**Problem:**
This fix doesn't work as expected and make it worse.
We need to revert it first.
**Solution:**
Revert https://github.com/rancher/rancher/pull/16997
**Issue:**
https://github.com/rancher/rancher/issues/17013
> Revert "Remove time sleeping on monitoring status detection"

- tests/core/conftest.py
- tests/core/test_kontainer_engine_validation.py
The kontainer engine validation tests are failing intermittently with a port
conflict error.  It is believed that this is due to an intermittent failure in
the GRPC connection. Because the tests are checking the first error message
returned, and not waiting for the connection to be reestablished and the
proper validation error returned, they are failing incorrectly.  This change
makes the tests poll for the correct error message and only fail when the
timeout has been reached.
Issue:
#16895
> Fix port conflict error

- pkg/pipeline/engine/jenkins/engine.go
Address issue: https://github.com/rancher/rancher/issues/17006
We use the `step-1-1` format as the preserved format to catch the step nodes from Jenkins API, for further state & log fetching.
change to use regex to filter out steps instead of hyphen splits, so as to avoid mismatching.
> Fix error when stage name is in 'x-x-x' format

- pkg/api/customization/pipeline/pipeline_execution_log.go
- pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
- pkg/pipeline/engine/engine.go
- pkg/pipeline/engine/jenkins/engine.go
- pkg/pipeline/engine/jenkins/minio.go
Address issue: https://github.com/rancher/rancher/issues/17079
Problem:
Fail to fetch pipeline log when api is handled by follower instance in HA install
Solution:
Use no cache when querying cluster resources in api handlers
> Use no cache in pipeline log api handler

- pkg/controllers/management/clusterprovisioner/provisioner.go
**Problem:**
RKE cluster provisioned by Rancher keep firing provision log like
```
Provisioning cluster [xxx]
Updating cluster [xxx]
Provisioned cluster [xxx]
```
Because cluster resource object is being updated by cluster provisioner
**Solution:**
As commit
**Issue**
https://github.com/rancher/rancher/issues/16955
> Fix rke cluster provision issue

- pkg/auth/providerrefresh/refresh_daemon.go
- pkg/auth/providers/activedirectory/activedirectory_client.go
- pkg/auth/providers/local/local_auth_provider.go
- pkg/controllers/management/auth/register.go
- pkg/controllers/management/auth/setting.go
See: https://github.com/rancherlabs/rancher-security/issues/40, https://github.com/rancherlabs/rancher-security/issues/44
Fixes a bug on AD refresh, prevents local auth from sometimes blocking refresh on long-lived tokens, and fixes a bug where auth-refresh related settings wouldn't actually take effect on change.
> Fix several auth refresh bugs.

- pkg/auth/providers/local/local_auth_provider.go
Fixes an issue where system users are logged out due to not having a `user.Username`
> Fix cluster provisioning killed by system users being logged out. 

- pkg/agent/cluster/controllers.go
Related issue: https://github.com/rancher/rancher/issues/17148
> Cluster agent controllers should only run once

- pkg/auth/providerrefresh/refresh_daemon.go
See https://github.com/rancher/rancher/issues/17249
Just checks if a user is a system user before creating a user-attribute for them.
> Don't create user-attributes (or refresh) for system users

- pkg/rkenodeconfigclient/client.go
- pkg/rkenodeconfigserver/nodeserver.go
Problems: it is not clear when agent failed to register due to etcd and
controlplane nodes missing or some random errors when failed to
construct node config which user has no idea what it is.
Solution: add proper log message.
https://github.com/rancher/rancher/issues/12548
> add proper detailed message when agent failed to register

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
See: rancher/rancher#16786, https://github.com/rancher/kontainer-engine/pull/103
When handling errors in stack creation, sometimes there is no CREATE_FAILED event, and the reason is attached to the ROLLBACK_IN_PROGRESS event.
This change still allows CREATE_FAILED events to take priority.
> bump kontainer-engine

- pkg/controllers/user/pipeline/controller/project/project.go
- pkg/pipeline/engine/engine.go
- pkg/pipeline/engine/jenkins/convert.go
- pkg/pipeline/engine/jenkins/engine.go
- pkg/pipeline/engine/jenkins/mappper.go
- pkg/pipeline/engine/jenkins/model.go
- pkg/pipeline/utils/constants.go
Address issue: https://github.com/rancher/rancher/issues/16136
~~Depending on a new tag of the slave image.~~
Edit:
Change to use init container to deal with cacerts, in this way we can avoid maintaining a customized agent image.
Change the construction of build pod template in a more "go-client-style" way, so that we can do fine-grained
tweaks more easily.
---
To integrate with self-signed certificate git service,
1. Add ca root certificate to rancher per the [instruction](https://rancher.com/docs/rancher/v2.x/en/admin-settings/custom-ca-root-certificate/)
2. configure ca root certificate in project pipeline setting, then the build pod will add it for git clone.
> Add pipeline configuration for self-signed git service

- pkg/controllers/user/alert/initdata.go
Problem:
Precan workload alert rule is bind to prometheus pod
Solution:
Change to sample pod name
Issue:
https://github.com/rancher/rancher/issues/16994
> update alert init data

- pkg/image/resolve.go
Related issue: https://github.com/rancher/rancher/issues/16666
> Add `rancher/` prefix for images from dockerhub library

- pkg/api/customization/cluster/actionhandler.go
- pkg/api/customization/cluster/formatter.go
- pkg/api/customization/project/project_actions.go
**Problem:**
- `cluster-member` can enable/disable monitoring on any levels
- `cluster-custom-member` can enable/disable monitoring on any levels
- `project-member` can enable/disable monitoring on any levels
- `project-custom-member` can enable/disable monitoring on any levels
- `project-read-only-member` can enable/disable monitoring on any levels
**Solution:**
Add `CanDo` checkign by `AccessControl`
**Issue:**
- #16888
- #16889
- #16978 
**Result:**
| roles (on Standard User) | cluster level | project level |
| ------------------------ |:-------------:|:-------------:|
| cluster-owner            |       x       |       x       |
| cluster-member           |               |               |
| cluster-custom-member    |               |               |
| project-owner            | …
> Fix monitoring deploying permissions

- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/alerting_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_metric_rule.go
update vendor to fix invalid default value for float type and no omit threshold value
Problem:
1. default value for float return zero string
2. we need threshold value to build alert expression, 0 is useful value
Solution:
1. fix float type default value in norman
2. not omit threshold value in types
Issue:
https://github.com/rancher/rancher/issues/16958
Types:
https://github.com/rancher/types/pull/647
Norman:
https://github.com/rancher/norman/pull/237
> update vendor to fix invalid default value for float type and no omit threshold value

- pkg/api/store/password/store.go
can't store password fields of cluster in secret, because dereferencing
and updating spec doesn't work if kontainer-engine doesn't use the same spec
> remove cluster from password types

- pkg/auth/providers/activedirectory/activedirectory_client.go
See https://github.com/rancher/rancher/issues/17286
Just do a basic DN search instead of a typed search, similarly to LDAP.
> More consistent search query for AD

- pkg/pipeline/engine/jenkins/engine.go
- pkg/pipeline/engine/jenkins/mappper.go
Address issue: https://github.com/rancher/rancher/issues/16683
Problem:
Pull image error when using private images as the context image of a pipeline step.
Solution:
Inject imagepullsecrets to pipeline build pod.
> Inject imagepullsecret to pipeline build pod for private images

- tests/core/cluster_common.py
- tests/core/test_cluster_auth_tokens.py
Cluster testing needs to be refactored to support:
- using arbitrary clusters which already exist on a Rancher server
(running one-off tests against various providers)
- spinning up a DinD cluster when the test script runs
(reduce total test time by provisioning in background)
> Disable DinD tests

- pkg/controllers/management/clusterprovisioner/provisioner.go
Address issue: https://github.com/rancher/rancher/issues/17355
Panic happens when updating not-rke clusters.
> Fix panic on cluster update

- pkg/audit/audit.go
Problem:
will record bad format log when the request/response body is empty
Solution:
use len to check the request/response body
Issue:
https://github.com/rancher/rancher/issues/17394
> Should use len to check empty request/response body

- pkg/api/customization/authn/user_actions.go
- pkg/api/customization/setting/setting.go
- pkg/api/server/managementstored/setup.go
- pkg/auth/providerrefresh/refresh_daemon.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_user.go
See: https://github.com/rancher/rancher/issues/17067#issuecomment-451312069
Depends on: https://github.com/rancher/types/pull/674
Provides actions for manually triggering auth refresh, as well as for validating the auth refresh related settings
> Refresh trigger action and settings validators

- .gometalinter.json
- Dockerfile.dapper
- pkg/auth/providerrefresh/refresh_daemon.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/monitoring/deploy.go
- pkg/monitoring/system.go
- scripts/validate
Doesn't do anything extra yet, still just runs `golint` and `go vet`, but this sets up the preliminaries for adding other linters like `deadcode` etc. I just figured we'd wait on those until some of the big features have landed. Some of them also have some larger change sets so probably warrant being split up anyways.
> Use gometalinter instead of golint

- package/Dockerfile
- pkg/api/server.go
- pkg/api/server/server.go
- pkg/auth/providers/publicapi/handler.go
- pkg/auth/tokens/api.go
- pkg/settings/setting.go
- server/server.go
For now, we are using the specific api ui version in
https://releases.rancher.com/api-ui/. It is not good for
air gap rancher setup. It needs to be cached in local files.
> [2.2]Cache the API UI in local file

- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
This change prevents a nil pointer from occuring if the download of a
kontainer driver fails.  The func will return the error to the lfc handler
and the normal error backoff logic will take place.
Issue:
https://github.com/rancher/rancher/issues/17425
> Prevent nil pointer if download fails

- pkg/controllers/user/pipeline/controller/pipeline/pipeline.go
Address issue: https://github.com/rancher/rancher/issues/17322
Problem:
When a  user is deleted, cannot remove the pipeline repo it configures.
Solution:
Attempt to delete hook on finalization but do not pend on it.
> Attempt to delete hook but do not pend on it on pipeline finalization

- main.go
Import the norman controller in `main.go` to ensure the `init()`
function will be run first.
Related issue: https://github.com/rancher/rancher/issues/17434
> Ensure the summary metrics is disabled

- app/role_data.go
Problem:
The base role of read-only is the default kubernetes role view. services/proxy is not in Kubernetes view role.
Solution:
Add service proxy access for manager service role
https://github.com/rancher/rancher/issues/16967
> Add service proxy access for manager service role

- pkg/api/controllers/settings/settings.go
- pkg/api/customization/setting/setting.go
- pkg/api/server.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/setting/store.go
- pkg/settings/generator/main.go
- pkg/settings/setting.go
- scripts/build-server
- scripts/version
- server/ui/ui.go
**Problem:**
For now, we don't respect the `ui-index` setting in formal
rancher version. There is no way for users to customize their UI in
those version.
Restart rancher will reset the settings value to environment variable
even the setting has value already.
**Solution:**
- Set the default values of each settings when building Rancher. We can have different default for different Rancher server version.
- ~Use `local` value in `ui-index` setting when it is a formal version. And Use CDN address when it is a dev version.~
- Set default value `local`  in `ui-index` setting when it is a formal version. And Use CDN address when it is a dev version.
- When `ui-index` setting is `local`, fetch UI and API-UI from file.
- ~Update the setting's value only when the value is empty. And the order …
> Set `ui-index` setting to local if rancher version is formal

- pkg/dynamiclistener/server.go
Mutex Lock & Unlock updateIps to prevent `concurrent map iteration and
map write` when iterating through certs.
For rancher/rancher/issues/16759
> Fix fatal error in concurrent map

- pkg/auth/tokens/manager.go
Parses input according to client spec, and passes ClientID as
ClientName to allow for creation of cluster scoped tokens.
For rancher/rancher/issues/17526
> Allow creation of cluster scoped token through API

- pkg/controllers/user/logging/configsyncer/configsyncer.go
- pkg/controllers/user/logging/utils/testwrap.go
Problem:
1. fix logging config could not sync correctly because could not detect logging app deploy
2. add header when sending test log to elasticsearch/splunk
Solution:
1. use management context to get app
2. add content-type in the request to elasticsearch header and token in the request to splunk
Issue:
https://github.com/rancher/rancher/issues/17600
https://github.com/rancher/rancher/issues/17599
> fix could logging config not sync correctly

- pkg/api/customization/namespace/link.go
- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/controllers/user/alert/deployer/notification_template.go
- pkg/controllers/user/alert/watcher/event.go
- pkg/controllers/user/alert/watcher/node.go
- pkg/controllers/user/alert/watcher/pod.go
- pkg/controllers/user/alert/watcher/workload.go
- pkg/resourcelink/resourcelink.go
Update alert notify template to support when alertmanager send multi alert in one request
Problem:
1. Alertmanager may send alert array, current notify template just use the first alert in array to contribute the notify info, not support multi alert well
2. it would help user to know the alerting pod belong to which workload if we could add workload info
3. alert name is miss for node alert
Solution:
1. Update notify template to support multi alert
2. add workload info 
3. add alert name in node alert
Issue:
https://github.com/rancher/rancher/issues/17472
https://github.com/rancher/rancher/issues/16990
https://github.com/rancher/rancher/issues/17535
> Update alert notify template to support when alertmanager send multiple alert and add workload info for pod and event alert

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/templates.go
Problem: EKS cluster creation fails due to incorrect parameter in template.
Solution: Updated kontainer-engine to latest version, which uses a correct template.
Issue: https://github.com/rancher/rancher/issues/17635
> Updated kontainer-engine to latest

- pkg/controllers/user/globaldns/globaldns_common.go
- pkg/controllers/user/globaldns/user_cluster_globaldns_controller.go
- pkg/controllers/user/globaldns/user_cluster_ingress.go
Adding new logic to usercluster controllers to watch updates on:
1) GlobalDNS updates 
- This will reconcile all ingresses under the GlobalDNS's target projects (derived either from multiclusterapp selected on GlobalDNS Or the projectNames selected)
- Then it will update the GlobalDNS endpoints by updating new ones and removing any that dont get listed anymore for the cluster
- ClusterEndpoints are also updated
2) Ingress removal
- When any ingress is deleted in a usercluster, this will trigger updates to all GlobalDNS's that target the cluster of the ingress.
This refers the types PR: https://github.com/rancher/types/pull/686
This is a PR for following issues:
https://github.com/rancher/rancher/issues/17450
https://github.com/rancher/rancher/issues/17451 …
> Controllers for reconciling all Ingresses per project and multiclusterapp of GlobalDNS

- pkg/api/customization/app/app.go
- pkg/api/server/managementstored/setup.go
**Problem:**
Can not upgrade if the creator of app is removed.
**Solution:**
If the creator of app is removed, use the user who updates the app as
the new creator. The updator needs to have the app-create privileges.
Related issue:
https://github.com/rancher/rancher/issues/17265
> Can not upgrade if the creator of app is removed

- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
problem:
After we refactored the logging, we can not deploy logging tools in an
air gap environment.
Solution:
Add the ability to use the private image registry when deploying logging
tools
Issue:
https://github.com/rancher/rancher/issues/17568
Related PR:
https://github.com/rancher/system-charts/pull/10
Test steps:
1. Set the `system-default-registry` to a private registry via the Settings menu.
2. Launch the logging.
3. Check if the rancher-logging app pulls the image from the set private registry.
> Add ability to use private image registry when deploying logging tools

- pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/user/pipeline/controller/project/project.go
- pkg/pipeline/engine/jenkins/convert.go
- pkg/pipeline/engine/jenkins/mappper.go
- pkg/pipeline/utils/constants.go
- vendor.conf
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/pipeline_types.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_step.go
Address issue: https://github.com/rancher/rancher/issues/16538
Problem:
Pipeline components fail to run when project resource quota is set.
Solution:
Add resource configurations for pipeline components, 
Add relevant settings for agent container.
Add configurations for pipeline step so that users have fine-grained control for each container in the build pod.
Notes:
1. Users change the default resource configurations of pipeline components by editing the workloads. It can be done by updating answers once pipeline components are moved to a system app.
2. ~~The resource configurations of build pods apply to every container in the pod.~~
Related types pr: https://github.com/rancher/types/pull/687
> Add resource configurations for pipeline pods

- pkg/api/customization/cluster/actionhandler.go
- pkg/api/customization/project/project_actions.go
**Problem:**
https://github.com/rancher/rancher/issues/16889#issuecomment-451589719
**Solution:**
Use meaningful object when `AccessControl.CanDo` checking
**Issue:**
- #17736
- #17737
- #16889 (Related)
**Patch:**
https://github.com/rancher/rancher/pull/17056
>  Fix owner-level roles cannot enable/disable monitoring

- pkg/controllers/user/alert/deployer/notification_template.go
- pkg/controllers/user/alert/manager/prometheus_operator.go
Problem:
prometheus use labels to identify the alert, alert keep in pending because current value label change every time, so the second event will have nothing to do with the first one
Solution:
move the current value to the annotation
Issue:
https://github.com/rancher/rancher/issues/17763
> Current value label affect alert duration calculate

- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
Problem: Default int values in driver schemas were being displayed as 0 regardless of value set in driver.
Solution: Kontainer driver now properly default int value of flag, instead of setting the default string value of flag.
Issue: https://github.com/rancher/rancher/issues/17708
> Set field default int value

- pkg/api/store/setting/store.go
**Problem:**
The source attribute is not set when listing settings.
The root cause is that `apiContext.ID` won't be set when calling list
interface.
**Solution:**
Use the `data["id"]` as key to get value from environment variable.
Related issue:
https://github.com/rancher/rancher/issues/17487
> Fix setting source attribute is not set when listting settings

- app/role_data.go
- tests/core/test_rbac.py
This change gives standard users the ability to view kontainer driver
resources.  This is important because in order to create a cluster the user
must be able to list kontainer drivers to know what options are available.
This capability is also added to the `Create Clusters` role as they also need
to be able to view kontainer drivers.
This also adds a `Manage Cluster Drivers` role to mirror the `Manage Node
Drivers` role.
Issue:
https://github.com/rancher/rancher/issues/17634
> Giving users the ability to view kontainer drivers

- pkg/controllers/user/globaldns/globaldns_common.go
- pkg/controllers/user/globaldns/user_cluster_globaldns_controller.go
- pkg/controllers/user/globaldns/user_cluster_ingress.go
- The user_cluster_ingress controller syncs updates on Ingresses that use GlobalDNS, and calls updates on the GlobalDNS object. 
- Before calling this update on GlobalDNS, we ensure that the Ingress belongs to a target project of the GlobalDNS. 
- This check was failing when the Ingress was a part of multiclusterapp due to (1. appID being wrong on Ingress and 2. Multiclusterappname comparison on globalDNS and the App was failing)
- Due to this, updates to GlobalDNS were not getting called on Ingress update.
https://github.com/rancher/rancher/issues/17507
https://github.com/rancher/rancher/issues/17748
> Corrected the checks in UserclusterIngressController 

- Dockerfile.dapper
Version 2.0.12 breaks build with the following error:
```
alecthomas/gometalinter info checking GitHub for latest tag
alecthomas/gometalinter info found version: 3.0.0 for v3.0.0/linux/amd64
alecthomas/gometalinter info installed ./bin/gometalinter
alecthomas/gometalinter info installed ./bin/gocyclo
alecthomas/gometalinter info installed ./bin/nakedret
alecthomas/gometalinter info installed ./bin/misspell
alecthomas/gometalinter info installed ./bin/gosec
alecthomas/gometalinter info installed ./bin/golint
alecthomas/gometalinter info installed ./bin/ineffassign
alecthomas/gometalinter info installed ./bin/goconst
alecthomas/gometalinter info installed ./bin/errcheck
alecthomas/gometalinter info installed ./bin/maligned
alecthomas/gometalinter info installed ./bin/unconvert …
```
> Update gometalinter to v3.0.0

- pkg/controllers/user/multiclusterapp/controller_multiclusterapp.go
- pkg/controllers/user/multiclusterapp/state.go
Issues: generating random name for app and ns causes duplicate creations,
not checking for cluster context results into wrong targets being deleted.
https://github.com/rancher/rancher/issues/17806
> change creation and remove for app of multi cluster app

- pkg/controllers/user/globaldns/user_cluster_ingress.go
This is the case when MulticlusterApp id selected for a globalDNS and then it is deleted. In this case the ingress gets deleted and the controller tries to reconcile all globalDNS of the cluster. While checking the multiclusterapp, if it gets a not found error, we should continue since the app might be marked for deletion.
https://github.com/rancher/rancher/issues/17833
> Handle not found error incase multiclusterapp is deleted

- chart/templates/deployment.yaml
- chart/tests/deployment_test.yaml
- chart/values.yaml
- scripts/chart/build
- scripts/chart/copy
- scripts/chart/index
- scripts/chart/package
- scripts/chart/test
- scripts/chart/validate
- scripts/version
- Add option to define arbitrary additional environmental variable to rancher pods for #17156 
- Minor fixes for chart build
- sed replace non-word characters in branch name with `-`
- change relative path in chart build scripts so `grep vendor.conf` in `script/version` doesn't error.
> [server-chart] add additional env variables.

- pkg/controllers/management/globaldns/cloudflare_template.go
- pkg/controllers/management/globaldns/globaldns_provider.go
- pkg/controllers/management/globaldns/route53_template.go
Add an identifier for external-dns records to avoid deleting records added by other providers
Fix for https://github.com/rancher/rancher/issues/17812
> Add an identifier for external-dns records to avoid deleting records added by other providers

- pkg/pipeline/engine/jenkins/mappper.go
Address issue: https://github.com/rancher/rancher/issues/17757
Problem:
Preserved environment variables do not get substituted in pipeline configs
Solution:
Do envvar substituion before converting to Jenkins pipeline script
> FIX env substitution in pipeline config

- pkg/api/customization/cluster/formatter.go
- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_kontainer_engine_validation.py
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
- vendor/github.com/rancher/kontainer-engine/drivers/options/options.go
- vendor/github.com/rancher/kontainer-engine/types/types.go
WIP
Problem: User wants to be able to configure node volume size.
Solution: The latest version of kontainer-engine enables the configuration of
node volume size. Formatter will automatically change values of nil to 20.
Clusters that were created before this commit will not have a value for
nodeVolumeSize in configMap, despite being set to 20 by AWS.
Depends on: https://github.com/rancher/kontainer-engine/pull/118
Issue: #16437
> Update kontainer-engine and change formatter

- tests/core/test_kontainer_engine_config.py
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/cluster/cluster.go
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
- vendor/github.com/rancher/kontainer-engine/drivers/eks/templates.go
- vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go
Problem: We would like to add user-data to EKS nodes.
Solution: Modify default cloudformation template for userData parameter.
If userData is specified then it will use that for EKS node bringup.
Update amazonElasticContainerServiceConfig schema with new userData
resourcefield. Also added integration tests to ensure EKS clusters
behave as expected.
https://github.com/rancher/rancher/issues/16300
*Dependency*
https://github.com/rancher/kontainer-engine/pull/122
> Add "user-data" to EKS nodes

- app/role_data.go
- pkg/controllers/management/auth/prtb_handler.go
- tests/core/test_catalog.py
- tests/core/test_cluster_catalog.py
- tests/core/test_project_catalog.py
https://github.com/rancher/rancher/issues/17638
Adding rule for "catalogs" for user role allows all users to list global catalogs. This will in turn let cluster and project roles list global catalogs as requested in the issue. Adding cluster-catalogs to `prtbClusterManagmentPlaneResources` will allow project roles to list cluster catalog as requested in the issue
> Allow users to select global/cluster catalog in dropdown during launch

- pkg/controllers/user/nodesyncer/nodessyncer.go
otherwise docker version change won't trigger v3.node resynchttps://github.com/rancher/rancher/issues/17902
> Compare containerRuntimeVersion on node sync

- pkg/api/customization/authn/user_actions.go
- pkg/api/server/managementstored/setup.go
- pkg/auth/providerrefresh/refresh_daemon.go
- pkg/auth/requests/filter.go
Problem: In an HA setup, the user auth refresh logic that is triggered
from an API action did not work properly. The controllers and logic
were setup such that it would only work on the "leader" node. On
non-leader nodes, the logic would panic.
This fixes the problem by move the logic to the proper API scope,
ensuring that it is available and proeprly configured on every node.
https://github.com/rancher/rancher/issues/17939
> Auth refresh in HA unreliable

- app/machinedriver_data.go
This adds the Linode machine driver to the list of drivers available for installation with Rancher.
* Machine Driver: `https://github.com/linode/docker-machine-driver-linode/releases/download/v0.1.6/docker-machine-driver-linode_linux-amd64.zip`
* UI Driver: `https://linode.github.io/rancher-ui-driver-linode/releases/v0.2.0/component.js`
* MD5Sum:  `4d53a20a6ee3090a713c48c2d3f5ed45` (Is a sha sum acceptable here? Seems both are used in the provider list)
* Whitelist Domains: `linode.github.io`
https://linode.github.io/rancher-ui-driver-linode/
https://github.com/linode/docker-machine-driver-linode/
> Add Linode.com machine driver

- pkg/auth/providerrefresh/daemon.go
- pkg/auth/providerrefresh/refresher.go
In a previous commit, we fix a problem where the refresher would not
work properly in HA setups because it was only running properly on the
leader node. We fixed that by confiugring it to run on all nodes
and by supplying a reference to a refresher to the custom api action
logic.
However, we still have a global scoped refresher that runs on the leader.
This is because it needs launched from a cron. In the previous fix,
we missed one reference to the global variable. It should have been changed
to the local function receiver varaible, but wasn't.
This commit fixes that issue by changing that reference and avoids future issues
like that by separating all the globally scoped references and logic into their
own file (daemon.go) and all the logic that is scoped solely the refresher itself
into …
> Fix panic in refresher logic

- app/role_data.go
- tests/core/test_rbac.py
Problems:
Metrics server is deployed to the cluster but users do not have access
to listing pods metrics.
Solutions:
Add permissions to access metrics group in roletemplate of
project-owner, project-member, read-only.
Issues:
https://github.com/rancher/rancher/issues/15866
> make users have access to listing pods metrics

- pkg/controllers/user/servicemonitor/utils.go
- pkg/controllers/user/servicemonitor/workloadmetricsservice.go
**Problem:**
The ServiceMonitor only applys to workloads with creatorID
**Soluetion:**
Don't need to check creatorID when reconciling ServiceMonitor
for Workload.
Related issue:
https://github.com/rancher/rancher/issues/17145
> Don't check the creator ID when reconciling serviceMonitor

- pkg/api/customization/logging/action.go
- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/generator/project_template.go
- pkg/controllers/user/logging/utils/custom.go
- pkg/controllers/user/logging/utils/elasticsearch.go
- pkg/controllers/user/logging/utils/fluentd.go
- pkg/controllers/user/logging/utils/kafka.go
- pkg/controllers/user/logging/utils/splunk.go
- pkg/controllers/user/logging/utils/syslog.go
- pkg/controllers/user/logging/utils/templatewrap.go
- pkg/controllers/user/logging/utils/testwrap.go
- pkg/controllers/user/logging/watcher/watcher.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_syslog_config.go
This is the same as https://github.com/rancher/rancher/pull/17785, but with
proper vendoring. I'm opening so that we can get the issues moved over to test.
Problem:
1. elasticsearch test func if not send the same type as config in fluentd will cause elasticsearch throw multiple type for one index error
2. watcher for check enable reachable should not send test log
3. improve test func and testWrap.go file too long
Solution:
1. improve logging test action related function
2. support when user use test action will send test log, while the watcher will only check reachable
3. separate different target test func to different files
Types:
https://github.com/rancher/types/pull/705
Issue:
https://github.com/rancher/rancher/issues/15380
https://github.com/rancher/rancher/issues/17658
> update logging test function

- app/machinedriver_data.go
Cloud credentials should include all fields necessary for authentication, adding required fields.
> add more fields to azure and vsphere cloud credential config

- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/clusterprovisioner/provisioner.go
- tests/core/test_cluster_defaults.py
Problem: The label for pending state should not be red. The "transitioning" field in API should not be error. New clusters should not start as "Active". RKE clusters were not showing "Pending" status before, but now they are.
Solution: Give ForgetError associated with pending state a reason, "Pending". Much like the provisioning state's reason, "Provisioning". The state is now blue, like provisioning and remove states. Transition field has a value of "yes". Removed pending state from non-imported drivers. This will prevent drivers from starting in "Active" state. Execute pending logic once, and return RKEdriver regardless of error. Pending will no longer hang. Driver will return despite inevitable forget error.
Issues: #17281, #15907, #17201, #17673, #17282
> Removed pending from non-imported driver and added reason to forget error.

- pkg/api/customization/monitor/metric_action.go
**Problem:**
When adding/editing alert rules in project-level alerting, there are two
same prompt expressions in Expression selection.
**Solution:**
Using String set to merge the same expression.
**Issue:**
https://github.com/rancher/rancher/issues/17999
> Fix duplicate prompt expressions when operating alert rule

- pkg/controllers/user/logging/configsyncer/configgenerator.go
- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/utils/templatewrap.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging_spec.go
This is the same as https://github.com/rancher/rancher/pull/17998
but rebased and with fixed up vendor.conf
Below is the text from the original PR
Problem:
excludeSystemComponent is a negative field
Solution:
change to includeSystemComponent and use true as default
Issue:
https://github.com/rancher/rancher/issues/15555
Types:
https://github.com/rancher/types/pull/715
> Use positive option instead of negative in cluster logging

- pkg/api/server/managementstored/setup.go
- pkg/api/store/globaldns/globaldnsprovider_store.go
- tests/core/test_globaldns.py
This is the fix to avoid deleting the GlobalDNSProvider if some entries are referencing it.
Added an integration test for the same.
https://github.com/rancher/rancher/issues/17518
> GlobalDNSProvider cannot be deleted until GlobalDNS entries referring it exist

- pkg/auth/providers/saml/saml_actions.go
- pkg/auth/providers/saml/saml_client.go
- pkg/auth/providers/saml/saml_provider.go
Change error code for incorrect attributes to 422
Redirects for login action should have /login in the route and those for testAndEnable action should have `&` before adding errorCode, because UI sets the first param to `?config=samlProviderName`
https://github.com/rancher/rancher/issues/15530
Tested with UI changes and seems to work
> Change SAML redirect and error code based on action

- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/controller.go
- tests/core/test_app.py
- vendor.conf
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_app.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_app_revision_status.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_app_spec.go
**Problem:**
user should be able to post a custom `values.yaml` to override the default one.
**Solution:**
add a new field called `valuesYaml` which allows the user to post a custom `values.yml` file to override default one, and `--set` values in the answers will override the user-supplied `values.yaml`.
**Related Issues:**
#17122 #16680 #14608
**Related PRs:**
types: https://github.com/rancher/types/pull/684
UI: https://github.com/rancher/rancher/issues/17605
> add support of custom values.yaml in catalog apps

- chart/templates/deployment.yaml
Change service health check to http `/healthz` endpoint instead of tcp check.
issue #17948
> [server-chart] change health check to http

- chart/templates/deployment.yaml
- chart/tests/deployment_test.yaml
- chart/values.yaml
Air Gap installs that want to configure the rancher audit log may need to configure the image repo for busybox container used to capture the logs for shipping.
> [server-chart] configurable busybox image

- pkg/api/controllers/dynamicschema/dynamicschema.go
- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_dynamic_schemas.py
- tests/core/test_kontainer_drivers.py
- vendor.conf
- vendor/github.com/rancher/norman/types/schemas.go
- vendor/github.com/rancher/norman/types/types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/catalog_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema_types.go
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/zz_generated_deepcopy.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_dynamic_schema.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_dynamic_schema_spec.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_app_revision_status.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_app_upgrade_config.go
This change makes it so that kontainer driver schemas will update when their
corresponding driver options update.  It works by adding a new method to the
norman Schemas struct `ForceAddSchema`.  This allows schemas that already
exist to be updated without getting stuck in endless loops.
Depends on:
https://github.com/rancher/types/pull/708
https://github.com/rancher/norman/pull/249
Issue:
https://github.com/rancher/rancher/issues/17712
> Updating dynamic schemas when kontainer drivers change

- pkg/controllers/management/globaldns/globaldns_handler.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_spec.go
This is the fix for https://github.com/rancher/rancher/issues/17871
The kubernetes-incubator/external-dns supports configuring TTL for a DNS record using an annotation:
https://github.com/kubernetes-incubator/external-dns/blob/master/docs/ttl.md
As a fix, added TTL parameter to GlobalDNS entry (types PR: https://github.com/rancher/types/pull/717) and it will get applied as an annotation to the mgmt plane ingress that the external-dns provider syncs up with.
> Configure TTL for GlobalDNS entries

- pkg/settings/setting.go
- tests/core/test_system_project.py
Fix for https://github.com/rancher/rancher/issues/17508
Upon creation of System project, the global namespace will be moved to the System project
> Move cattle-global-data to System project

- pkg/controllers/user/logging/configsyncer/configgenerator.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
- pkg/controllers/user/logging/utils/templatewrap.go
Problem:
1. old fluentd/log-aggregator, secret not be removed when upgrading rancher server with a enable logging
2. includeSystemComponent will be nil for server upgrade from old version
Solution:
1. clean old resource
2. handle nil situation
Issue:
https://github.com/rancher/rancher/issues/18054
https://github.com/rancher/rancher/issues/18055
> Fix logging upgrade bug

- pkg/api/customization/app/app.go
- pkg/controllers/user/helm/controller.go
- vendor.conf
**Problem:**
- Cannot upgrade local chart app
- Cannot rollback local chart app
**Solution:**
- Input local app templates when upgrading
- Record local app templates in `AppRevision`, restore them into `App` when rollbacking
**Issue:**
#15711
- https://github.com/rancher/types/pull/664
> Support local chart app upgrade & rollback

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go
Problem:
Rancher will crash when deleting an existing GKE cluster
Solved:
Fixed the code bug
Issue:
[rancher/rancher#18103](https://github.com/rancher/rancher/issues/18103)
Related PR:
https://github.com/rancher/kontainer-engine/pull/127
Introduced in this PR: 
https://github.com/rancher/kontainer-engine/pull/112
> Update vendor for kontainer-engine

- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_kontainer_engine_config.py
This fixes a issue with the RKE schema where it was being overwritten by a bad
set of fields coming from the RKE driver.  This was preventing existing RKE
clusters from being edited on the UI because the config was bad.  The fix
works by correcting the `rancherkubernetesengine` kontainer driver resource
name in the `hasStaticSchema` check in the kontainer driver controller so that
it will not attempt to use the rke_driver.go schema and default to the built
in RKE struct.
Issue:
https://github.com/rancher/rancher/issues/18120
> Fixing RKE edit issue

- tests/core/conftest.py
- tests/core/test_pod_security_policies.py
Problem:
Errors are being thrown in Rancher logs due to incorrect PSPT creation.
PSPTPB are not being verified to exist.
Solution:
Update test to create valid PSPs
Update test_pod_security_policy_del to test that that PSPTPB's
are being created and assigned to the correct project.
> PSPT test improvement

- pkg/controllers/user/monitoring/appHandler.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/monitoring/monitoring.go
**Problem:**
Assuming there are two clusters, monitoring is enabled. When disabling
the monitoring of cluster A, monitoring app of cluster B also be
dropped. But cluster B is still in monitoring `enabling` status.
**Solution:**
When withdrawing the monitoring app, we need to increase a `clusterID`
parameter to ensure dropping the app of expected cluster.
**Issue:**
https://github.com/rancher/rancher/issues/18146
> Resolve the confusion that occurs when disabling monitoring

- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_kontainer_drivers.py
Problem: Server would download drivers even if they were marked inactive.
This throws errors on air-gapped installations.
Solution: Server now only downloads files when they are marked as active.
https://github.com/rancher/rancher/issues/17595
> Fix server downloading inactive kontainer-engine cluster drivers

- pkg/api/customization/app/app.go
- vendor.conf
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
- vendor/github.com/rancher/types/client/project/v3/zz_generated_app_upgrade_config.go
This is a rebase of https://github.com/rancher/rancher/pull/18151
Original PR comments below:
**Problem:**
Cannot update valuesYaml field for catalog app in the upgrade
**Solution:**
Add valuesYaml filed to the catalog upgrade action.
**Issues:**
#18111
**Related PRs:**
rancher/types#723
> Add valuesYaml to the catalog upgrade action

- pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/user/resourcequota/resource_quota_sync.go
Related issue: https://github.com/rancher/rancher/issues/16538
Problem:
When resource quota is set, pipeline resource deployment can fail before ns resource quota is synced.
Solution:
Wait for namespace resourceQuotaInit condition after creating pipeline namespaces
> Wait for resourceQuotaInit condition after creating pipeline namespace

- pkg/api/server/managementstored/setup.go
- pkg/api/store/nodetemplate/store.go
we shouldn't store cred field data in nodetemplate config if credID is provided,
for instance - on nodetemplate edit of upgraded setups
https://github.com/rancher/rancher/issues/18205
> empty cloud credential fields in nodetemplate config if credID is set

- pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go
Addresses: https://github.com/rancher/rancher/issues/18229
When a target project is removed, the call to delete the namespace for the app's workloads relies on clusterContext map which is created using target projects. So this map won't have the clusterContext of the target project being removed, if no other projects from that particular cluster are listed as targets. This commit adds a check to see if the clusterContexts map has the current cluster in it, if not then adds the usercontext for it
> Ensure cluster context is set during app's namespace deletion

- pkg/api/store/nodetemplate/store.go
Earlier commit replaced the values with "", this can cause
issue if field isn't string, for eg. vcenterPort for vsphere 
https://github.com/rancher/rancher/issues/18248
> remove fields from config if credID is set

- pkg/api/customization/multiclusterapp/multi_cluster_app.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/multi_cluster_app.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_update_multi_cluster_app_targets_input.go
Address issue: https://github.com/rancher/rancher/issues/18209
Related types PR: https://github.com/rancher/types/pull/726
Problem:
The addProject action input parsed by backend is different from the Answer schema used by UI/client.
Solution:
Parse input to `client.UpdateMultiClusterAppTargetsInput` instead of `apiv3.UpdateMultiClusterAppTargetsInput`
> Update mcapp addproject input parsing

- pkg/api/customization/monitor/cluster_graph_action.go
- pkg/api/customization/monitor/handler_utils.go
- pkg/api/customization/monitor/metric_action.go
- pkg/api/customization/monitor/project_graph_action.go
- pkg/api/customization/monitor/prometheus_manager.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/controllers/user/monitoring/register.go
- pkg/monitoring/deploy.go
- pkg/monitoring/monitoring.go
**Problem:**
Based on https://github.com/rancher/rancher/issues/16932, we have addressed something that wasn't a bug. We shouldn't delete `project-level` monitoring if the user was monitoring a custom app.
**Solution:**
- Don't disable `project-level` when disabling `cluster-level`
- Don't detect `cluster-level` enabling or not when enabling `project-level`
- Ensure Prometheus Operator existent when any `project-level` is enabling Monitoring
- Use `federate` as default sync mode when `project-level` deploying
**Issue:**
- https://github.com/rancher/rancher/issues/18115
- https://github.com/rancher/rancher/issues/18218
> Refactor project level Monitoring

- pkg/controllers/user/controllers.go
- pkg/controllers/user/monitoring/controlplane_endpoint_sync.go
- pkg/controllers/user/monitoring/register.go
**Problem:**
The rancher-monitoring creates endpoints with the cluster node
addresses statically defined at monitoring activation time to
monitor etcd, kube-scheduler, and kube-controller-manager services.
If you switch out the nodes (they change ip addresses) the endpoint
objects don't get updated.
**Solution:**
Create a new controller to sync the nodes ips in the endpoints we
need.
Related Issue: https://github.com/rancher/rancher/issues/18042
> Keep node ips synchronized in service endpoints

- pkg/api/customization/multiclusterapp/store.go
- pkg/auth/providers/providers.go
A user could have turned on external auth and added some user from that external auth
provider as a member of a multiclusterapp. After this when user logs back in as local
user, searching and adding new members from the external auth provider to the existing
multiclusterapp will fail. But even upgrading the multiclusterapp is failing, because
during upgrade, there is a call to getPrincipal of the members and set their displayNames
This call can be skipped if the current auth provider found in token is for local auth,
whereas the principalIDs of the members are from an external auth provider
Addresses: https://github.com/rancher/rancher/issues/18252
> Ensure auth provider can find multiclusterapp member's principal

- app/kontainerdriver_data.go
- tests/core/test_rbac.py
This change removes import driver from the kontainer engine drivers this is
because it is unnecessary (import_driver.go is never called by Rancer) and is
causing difficulties on the UI where it has to be filtered from the list of
drivers.  Also contains cleanup logic for previous versions of Rancher to
remove the existing import driver.
Issue:
#18273
> Removing import kontainer driver as it is unnecessary

- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/clusterstatus/temporarycredentials.go
- tests/core/test_kontainer_engine_annotations.py
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
This change brings in the EKS upgrade correction from kontainer-engine (Issue: #18162) and also corrects the below issue:
---------
This change ensures that the temporary security credentials annotation is set
properly on an EKS cluster that has a session token.  Previously if the
session token field was missing or nil it would fail to be set in certain
places.  this change ensures that the temp security creds annotation will only
be set to false if the field is neither missing nor empty.
Issue:
#18285
Depends on:
https://github.com/rancher/kontainer-engine/pull/132
> Fixing eks upgrade to latest so it doesn't error

- pkg/controllers/user/logging/utils/fluentd.go
problem:
not validate ca and hostname for fluentd test function is not the same
logic as fluentd
Solution:
enable validate ca and hostname
Issue:
https://github.com/rancher/rancher/issues/18332
> enable validate fluentd ssl ca

- pkg/dialer/factory.go
- vendor.conf
- vendor/github.com/rancher/norman/pkg/remotedialer/client_dialer.go
- vendor/github.com/rancher/norman/restwatch/rest.go
- vendor/github.com/rancher/norman/store/proxy/proxy_store.go
This change addresses an issue where AKS clusters would timeout due to Azure
lbs failing to send tcpResets (RST) after an idle timeout.  This causes errors
to appear on the Rancher UI and logs.  This issue resolves that by adding a
keep alive to the dialer and changing some timeouts to prevent the errors from
appearing.
This is only for AKS cluster provisioned through the AKS Kontainer Driver
integration, imported clusters still exhibit this behavior.
Issue:
#14354 
Depends on:
https://github.com/rancher/norman/pull/254
> Adding code to fix aks timeouts

- pkg/api/customization/globaldns/action_globaldns.go
- pkg/api/customization/globaldns/validator_globaldns.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_update_global_dnstargets_input.go
1) Issue: Currently only projectIds are passed in input, so we've no
idea if user has edited mcAppID and validation always fails.
2) If new mcAppID is empty, we should not do `access.ById` else that fails in proxy_store. 
https://github.com/rancher/rancher/issues/18366
https://github.com/rancher/types/pull/735
> pass mcAppId to addProject action 

- pkg/api/customization/kontainerdriver/validator.go
- pkg/api/server/managementstored/setup.go
- tests/core/conftest.py
- tests/core/test_kontainer_drivers.py
Problem: Users are able to create duplicate drivers (same download URLs).
Solution: Add validator that checks whether the proposed driver URL already exists.
Issue: https://github.com/rancher/rancher/issues/18126
> Add custom driver validator

- pkg/controllers/user/alert/manager/alertmanager.go
Problem:
alertmanager has error log for parsing the invalid url, and it require a
global slack api url
Solution:
change the global slack api url to a valid url
Issue:
https://github.com/rancher/rancher/issues/18398
> Change alertmanager default slack api url to valid url

- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_kontainer_drivers.py
**Problem:**
1. Transition state `Downloading` is missing when activating a cloud
driver.
2. Check kontainer engine driver binary function will always return
false even the binary exists in the path.
**Solution:**
1. Move all the download logic to `Updated` and use the
`Downloaded` condition to drive the actual download process.
2. If driver's ExecutablePath exists, Use it to check binary exists
first.
Related Issue: https://github.com/rancher/rancher/issues/18211
> Refactor kontainer driver controller

- pkg/controllers/management/drivers/base_driver.go
This method is used for both node and kontainer-engine drivers but
this error was not parameterized accordingly.
https://github.com/rancher/rancher/issues/18365
> Parameterize driver error

- pkg/controllers/user/helm/controller.go
Issue: If mcApp is deleted and immediately created in same project,
there's a chance app namespace is still getting terminated.
We'd still be able to fetch it, but if it gets deleted before helm
checks, it'll create a new ns which won't have required labels.
It doesn't always reproduce, but better to add a check.
> don't attempt to deploy app in a terminating namespace

- pkg/controllers/user/pipeline/controller/pipeline/pipeline.go
Address issue: https://github.com/rancher/rancher/issues/17322
Problem:
Pipeline resource stuck in removing state in cases when gitlab credentials are revoked, gitlab instance no longer exists, etc.
Solution:
Print warning instead of returning erros when fails to clean up pipeline hooks
> Print warning instead of returning error when fails to clean up pipeline webhook

- pkg/controllers/user/alert/initdata.go
Problem:
prometheus job name changed affect precan alert rule
Solution:
remove job name
Issue:
https://github.com/rancher/rancher/issues/18434
> Remove job name from precan alert rule

- package/run.sh
https://github.com/rancher/rancher/issues/16385
Other way to fix this is no have `value: null` in the API for `cacerts`, which would involve code changes in more places.
> Only save cacerts if it actually contains something

- package/run.sh
- pkg/agent/main.go
k3s does not require a docker socket, so produce a warning instead of
error if the socket is not present when running the agent.
For rancher/k3s/issues/69
> Change agent docker socket check to warning

- pkg/controllers/management/clusterprovisioner/driver.go
- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/etcdbackup/etcdbackup.go
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/cluster/cluster.go
- vendor/github.com/rancher/kontainer-engine/service/service.go
Problem: Removing unavailable cluster causes cluster to hang in removal state in UI.
Solution: Update to latest kontainer engine which logs errors caused by driver remove instead of returning it, then proceeds to remove cluster from persist store.
Issue: https://github.com/rancher/rancher/issues/18328
> Add force remove, rename Driver, update kontainer-engine

- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/logging/configsyncer/configgenerator.go
- pkg/controllers/user/logging/generator/generator.go
Problem:
For namespaces have same prefix belong to different projects, for example project1 have namespace default, project2 have namespace
default2, fluentd not match the exact namespace which makes project1 logging could get the log from namespace default2
Solution:
update regex to match the exact namespace
> update logging namespace matching pattern

- chart/templates/deployment.yaml
Hello!
rancher fails to start when `cacerts.pem` mounted at `/etc/rancher/ssl`
```
2019/02/26 14:31:02 [INFO] Listening on /tmp/log.sock
2019/02/26 14:31:02 [INFO] Rancher version v2.2.0-rc1 is starting
2019/02/26 14:31:02 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
I0226 14:31:02.487331       5 http.go:110] HTTP2 has been explicitly disabled
2019/02/26 14:31:02 [FATAL] open /etc/rancher/ssl/cert.pem: not a directory
```
> Fix mounting cacerts.pem

- pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/user/resourcequota/resource_quota_calculate_used.go
- pkg/controllers/user/resourcequota/resource_quota_sync.go
Address issue: https://github.com/rancher/rancher/issues/16538
Problem:
When available resource quota in a project does not satisfy the default namespace quota, pipeline builds fails with error "create secret failed due to exceeding resource quota"
Solution:
Check validated condition of the namespace and show a better error message
> Improve error handling when available quota is not enough for the pipeline namespace

- pkg/controllers/user/pipeline/upgrade/upgradeimpl.go
Address issue: https://github.com/rancher/rancher/issues/18475
Problem:
When upgrading from 2.1.x to 2.2, user configured settings(e.g. pvcs) on pipeline components are removed
Solution:
Do no update on the component workloads, as it is not necessary at the moment
> Update Pipeline component upgrade

- pkg/controllers/management/clusterprovisioner/provisioner.go
Problem: 
Forget error was treated as a normal error when waiting for nodes and caused the status to be highlighted red. 
Solution:
Added reason to forget error when waiting for nodes. The status will remain its intended color.
(Additional changes made in ui PR: https://github.com/rancher/ui/pull/2709)
(Most common color issue previously resolved in: https://github.com/rancher/rancher/pull/17980)
Issue:
https://github.com/rancher/rancher/issues/18062
> Add reason to forget error

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/etcdbackup/etcdbackup.go
- Add backoff for backup save
- Add retries for s3 delete
- Handle cases where restore is done with invalid credentials. 
https://github.com/rancher/rancher/issues/18484
> Add backup save/s3 delete backoff/retry and handle misconfigured restore

- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/generator/project_template.go
- pkg/controllers/user/logging/utils/syslog.go
- pkg/controllers/user/logging/utils/templatewrap.go
Problem:
The fluentd syslog gem depends on an old gem, and it used deprecated warn instead of warning
Solution:
Add api and syslog adapter
Issue:
https://github.com/rancher/rancher/issues/18472
> Adapt syslog severity and api severity value

- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/monitoring/operatorHandler.go
Problem:
1.Project level operator withdraw check also need to check whether the
alert is enable
2.For HA mode, single isDeploy value is not good
Solution:
1.Check whether the alert is enable when withdraw the operator in
project level
2.Use the app status to check whether the alertmanager deployed
Issue:
https://github.com/rancher/rancher/issues/18478
> Improve alert deploy/upgrade logic

- pkg/controllers/user/logging/generator/cluster_template.go
- pkg/controllers/user/logging/generator/project_template.go
**Problem:**
Rancher logging to elastic doesnt support passwords with special
characters like `@` and `#`.
**Solution:**
Use `user` and `password` field in fluentd es configuration
instead of adding them to es url.
Related issue: https://github.com/rancher/rancher/issues/18389
> Fix logging to es can't use char @ in password

- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
https://github.com/rancher/rancher/issues/18641
Logging at info by default now, changing chart answers to not set the loglevel. Chart will set it to info by default.
> Change log level to info for globaldns providers

- pkg/controllers/user/pipeline/controller/project/project.go
Address issue: https://github.com/rancher/rancher/issues/18660
Do no token creation on project syncer. It will be generated when
needed. e.g., When pipeline is used; In pipeline upgrade logic.
> Create project system token on demand

- pkg/controllers/user/logging/utils/fluentd.go
- pkg/controllers/user/logging/utils/syslog.go
- pkg/controllers/user/logging/utils/testwrap.go
This issue happens when the fluentd server is configured with tls, but we try to connect to it without tls in Rancher.
In this case if you click `Test` button, the UI hangs.
Steps to check the connectivity is following:
1. Create the connection (tcp handshake, ssl handshake)
2. Read data from fluentd to get nonce from server
3. Use nonce to generate fluentd ping and send ping to fluentd server
4. Get pong from fluentd server
You can see that the tcp handshake is finished, but fluentd throw error about tls in the screenshots.
Now the step for getting nonce from fluentd get blocked.
connection status:
fluentd log:
Add a read function which supports timeout. Then we can use it when user click `Test` button in UI. The change is safe and it only impacts the `Test` feature. …
> Add timeout for read data from connection

- pkg/api/customization/kontainerdriver/formatter.go
- pkg/api/customization/kontainerdriver/store.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/cluster/clustercontroller.go
- pkg/controllers/management/clusterprovisioner/driver.go
- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
- tests/core/test_kontainer_drivers.py
Fix for cluster driver nil error
Problem: A cluster driver could be deleted when there were active
clusters that depended on that driver.
Solution: The API will not crash if a cluster driver is unable to be
removed. Kontainer drivers are no longer able to be removed via the UI
or API if there is a cluster that uses that driver.
https://github.com/rancher/rancher/issues/18460
> Cluster driver remove bug fix

- pkg/api/customization/globalnamespaceaccess/access_common.go
Addresses: https://github.com/rancher/rancher/issues/18774
Regression caused by the PR to return cumulative error.
> Check error before returning if no input cluster roles found

- pkg/controllers/management/clusterprovisioner/provisioner.go
Problem:
On upgrade, get config would return an empty interface for the old config. Consequently, new config and old config would always fail comparison. This caused the provisioner to proceed unnecessarily and contribute to the update status.
Solution:
Set generic config for applied spec and spec in the cluster and censor both specs.
Issue:
https://github.com/rancher/rancher/issues/18352
> Add generic config to applied spec and censor config

- pkg/controllers/user/nodesyncer/nodessyncer.go
**Problem:**
The rancher nodes are always getting updated becuase the conditions
of them is always different from the nodes' in user cluster. It is
because the condition lists of them are compared without sortting.
**Solution:**
Sort the condition list for both kinds of node before comparing
them.
Related issue: https://github.com/rancher/rancher/issues/18759
> Sort nodes conditions before being compared

- scripts/package
**Problem:**
We use `git clone` in package to get system charts repo and we will
get the default branch `dev` instead of `master`. We need master
branch for building release.
**Solution:**
Using git clone with `--branch master`
Related issue: https://github.com/rancher/rancher/issues/18747
> Clone system-chart repo with master branch

- app/machinedriver_data.go
The names were wrongly assigned in this pr: `https://github.com/rancher/rancher/pull/18752` 
https://github.com/rancher/rancher/issues/18802
> correct driverData field names

- package/Dockerfile
- vendor.conf
- vendor/github.com/rancher/rke/cluster/plan.go
The ETCD needs `ETCD_UNSUPPORTED_ARCH=arm64` env var to be set to run on ARM64 platform.
https://github.com/rancher/rancher/issues/16461
>  Add ETCD_UNSUPPORTED_ARCH env var for arm64 rancher image

- pkg/api/customization/project/project_actions.go
Problem: updateProjectPSPT was returning 500 errors on conflicts
Solution: updateProjectPSPT now returns 409 conflict errors
See https://github.com/rancher/rancher/issues/18743
See also https://github.com/rancher/rancher/issues/18267
> Fix updateProjectPSPT returning 500 errors

- pkg/controllers/management/clusterprovisioner/provisioner.go
Problem:
EKS is returning an error upon update. The error states that the EKS version cannot be updated from 1.11 to 1.11.
Solution:
Upon upgrade to 2.2, if version is available from cluster, set kubernetesVersion in spec and applied spec. Only compare versions of EKS clusters because it is the only field that can be updated.
Issue:
https://github.com/rancher/rancher/issues/18390
> Add version upon upgrade and only compare versions for EKS

- pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
- pkg/pipeline/engine/jenkins/convert.go
- pkg/pipeline/engine/jenkins/mappper.go
Related to:
https://github.com/rancher/rancher/issues/16538
https://github.com/rancher/rancher/issues/18716
https://github.com/rancher/rancher/issues/18727
This PR address following issues:
1. Pipeline resource creation is blocked by default zero quotas. Waiting for the namespace condition/status cannot guarantee that because there is still a gap between condition is set and the resource quota is updated. 
Solution: Do retry for resource creation to avoid that.
2. The default quota limit breaks previous pipelines that exceed the limit. There is no reasonable default quota for buildimage and runscript steps wich run user-defined scripts.
Solution: Remove the default resources for those two types.
3. Invalid resources configs cause panic
Solution: Avoid using the MustParse function
> Pipeline quota fixes

- pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
Problem:
If you deactivate and then reactivate a kontainer-engine driver,
the schema for it will not be readded. This is because there is logic
that only creates/updates the schema if the "active" condition is not
true. But, when a driver is deactivated, we do not change the value
of the active condition. So, when it is reactivated, the schema is never
recreated.
Solution:
Delete the active condition when the driver is deactivated. Settting
the condition to falst, "", or unknown is not sufficient because it causes
the state of the resrouce in the UI to go to activating.
https://github.com/rancher/rancher/issues/18800
> Fix kontainer-engine driver reactivation

- pkg/controllers/user/monitoring/metricExpression.go
**Problem:**
- Cannot see `host` and `path` in `Ingress Upstream Response Time`
- Cannot see `Number of failed proposals`
**Solution:**
- Replace `nginx_ingress_controller_ingress_upstream_latency_seconds` by `nginx_ingress_controller_response_duration_seconds_bucket`
- Replace `count(up{job="exporter-kube-etcd-cluster-monitoring"}) by (instance)` by `sum(etcd_server_proposals_failed_total)`
**Issue:**
https://github.com/rancher/rancher/issues/18624 (Patched)
> Adjust Monitoring expression

- pkg/controllers/user/monitoring/config_refresh_handler.go
- pkg/controllers/user/monitoring/register.go
**Problem:**
The project monitoring can scrape data from ns which is already moved
to another project. The prometheus operator does not refesh the
prometheus configuration after the ns label is changed.
**Solution:**
Set an annotation which contains project ns list for prometheus obj.
And update the annotation when namespace projectID label is changed.
Related issue: https://github.com/rancherlabs/rancher-security/issues/76
> Add project monitoring config refresher

- pkg/controllers/management/node/utils.go
Problem:
When we set the field of integer type, it can't be converted normally in
backend
Solution:
When we decode json data by map[string]interface{}, it is decoded to
float64 instead of int or int64
Issue:
https://github.com/rancher/rancher/issues/18822
More Info:
In v2.1.7, we store the nodeConfig and generate dynamicSchema fields from machine driver's flags in 
https://github.com/rancher/rancher/blob/release/v2.1/pkg/controllers/management/nodedriver/machine_driver.go#L111. And when we are dealing with `IntFlag` wen don't set int type for that field https://github.com/rancher/rancher/blob/release/v2.1/pkg/controllers/management/nodedriver/utils.go#L56-L59.
As a result, we store all the int flag value as string field in nodeConfig. So when it is building machine driver create command …
> Fixed the bug that node-driver can't set the integer value

- tests/core/conftest.py
Problem: When tests failed on wait_for_condition function, they did not
produce enough information to accurately debug.
Solution:
They now dump the entire object to the log
https://github.com/rancher/rancher/issues/18239
> Improve wait_for_condition

- tests/core/test_kontainer_drivers.py
This test ensures that when a kontainer driver is re-activated after
being deactivated that it is present in the schema again.
Tests 8c24298e0
> Add test for kontainer driver reactivation

- pkg/kubeconfig/kubeconfig.go
Base64 encodes cluster.LocalClusterAuthEndpoint.CACerts for use in a
kubeconfig.
For rancher/rancher/issues/18901
> Encode LocalClusterAuthEndpoint CA Certs for kubeconfig

- pkg/api/customization/cluster/actionhandler.go
With this fix, the msg shows up correctly in API and UI shows the correct text, but shows it twice. 
Waiting for UI to confirm, but submitting pr since just want to prohibit user to attempt the action with a proper msg. 
https://github.com/rancher/rancher/issues/18920
> return httperror if restoreBackup not allowed

- pkg/api/customization/cluster/validator.go
Check if we have CA Certs but no FQDN defined when validating the
LocalClusterAuthEndpoint.
For rancher/rancher/issues/18901
> Validate ClusterAuth FQDN set if CA Certs defined

- pkg/controllers/user/monitoring/metricExpression.go
**Problem:**
- Wrong use of Histogram type indicator
- Cannot recognize different hosts from ingress-controller-connections graph
**Solution:**
- Use `histogram_quantile` to wrap `*_bucket` metrics
- Enhance `legendFormat` and use `ceil` to wrap `increase`
**Issue:**
#18962
> Adjust ingress-controller expressions

- pkg/controllers/management/drivers/nodedriver/utils.go
In our v2.1 and earlier releases, we had a bug that caused machine driver
fields of type int to be presented in the Rancher API as string fields.
We fixed this on master, but later realized that it would be a breaking
API change. We could have dealt with just the breaking API change, but this
also exposed a bug that node driver schemas were not automatically updated
when Rancher was upgraded. The combination of fixing the int-to-string bug
but not fixing the update bug is too confusing. So, we are rolling back the
change to match how it was in v2.1.
We will have to fix these two bugs together at a later date.
> Revert change to nodeDriver schemas

- pkg/api/customization/monitor/cluster_graph_action.go
- pkg/api/customization/monitor/project_graph_action.go
This error will be returned to the user in the API. Capitalizing it.
> Fix capitalization

- pkg/controllers/user/alert/controller.go
Issue: Cannot remove project from upgraded cluster.
Reason: the cause is that the name of the controller was changed. Lifecycle controllers cannot have name changes bc then old finalizers will not get cleaned up.
Solution: Change the name back
https://github.com/rancher/rancher/issues/19130
> Revert the change for alert controller name

- scripts/chart/promote-to-stable.sh
Regex was grabbing rc candidates. This searches for exact tag and
grabs the most recent.
> Regex is less greedy for chart promotion script

- pkg/pipeline/engine/jenkins/convert.go
- pkg/pipeline/engine/jenkins/mappper.go
Address issue: https://github.com/rancher/rancher/issues/19220
Problem:
When users configure a custom git ca cert, it is not available for the publish catalog steps.
Solution:
Inject the custom ca cert to publish catalog containers.
> Inject custom ca cert to publish catalog containers

- pkg/controllers/user/monitoring/config_refresh_handler.go
**Problem:**
`defer sort.Strings(rtn)` cannot sort the real rtn before return, then
this cause the Prometheus CRD update loop may never stop.
**Solution:**
Use a execution function to wrap
**Issue:**
https://github.com/rancher/rancher/issues/19248
> Fix hight CPU load when enabling Monitoring in local cluster

- pkg/controllers/user/monitoring/config_refresh_handler.go
**Problem:**
`defer sort.Strings(rtn)` cannot sort the real rtn before return, then
this cause the Prometheus CRD update loop may never stop.
**Solution:**
Remove `defer`, sorting before `return`
**Issue:**
https://github.com/rancher/rancher/issues/19316
> [2.2]Fix hight CPU load when enabling Monitoring

- pkg/pipeline/engine/jenkins/convert.go
- pkg/pipeline/engine/jenkins/mappper.go
For release/v2.2
Address issue: https://github.com/rancher/rancher/issues/19313
Problem:
When users configure a custom git ca cert, it is not available for the publish catalog steps.
Solution:
Inject the custom ca cert to publish catalog containers.
> [2.2] Inject custom ca cert to publish catalog containers

- pkg/auth/providers/common/password.go
Problem:
If secretInfo has a colon in it, the split does not work properly 
Solution:
A colon is a valid value so check if the secret is prefixed with the namespace where the secret lives
https://github.com/rancher/rancher/issues/19202
> Verify prefix for secret name

- pkg/api/customization/monitor/handler_utils.go
Problem:
single pod deploy by yaml don't have ownerRef, need add check before use
pod attributes
Solution:
1. check ownerRef array len
2. add more check for arrays in case similar panic happen
Issue:
https://github.com/rancher/rancher/issues/19358
> handle pod may not have ownerRef

- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/cluster_monitoring_enabled_handler.go
- pkg/controllers/user/monitoring/handleComponents.go
- pkg/controllers/user/monitoring/register.go
**Problem:**
After enabling Monitoring, Rancher dashboard cannot perceive cluster level Prometheus is working or not. 
**Solution:**
- Don't reconcile Conditions of `MonitoringStatus`, which cause so many useless logs, https://github.com/rancher/rancher/issues/17733. Focusing on `MonitoringEnabled` condition is enought, it needs to change UI logic, @loganhz : 
- Setup a handler to watch the cluster level Prometheus StatefulSet is ready or not
**Issue:**
- https://github.com/rancher/rancher/issues/17733
- https://github.com/rancher/rancher/issues/19278
> Adjust Monitoring status detection logic

- .drone.yml
This PR addresses the following:
1. Add failure notifications to slack when non-prs fail on the publish instance of Drone.
2. Moves the chart publishing step to the manifest pipeline so that charts aren't created with missing images.
> Address Drone Yaml Issues

- pkg/api/store/service/service.go
- tests/integration/test_dns.py
Fix validation of non-special ip addresses
Problem: Validation of ip addresses was returning 500 errors
Solution: IP address validation now return 422 errors
See https://github.com/rancher/rancher/issues/18652
> Fix validation of non-special ip addresses

- pkg/api/store/pod/owner.go
Problem:
Requests are taking a long time, particularly pod requests. If there are a large amount of resources (over 1k) records are shifted out of the cache before they are ever accessed. This causes a large amount of misses, forcing the parent information to be retrieved. This retrieval can take >50ms per item.
Solution:
Increased size of parent cache to 100k from 1k. Size of cache has increased 10x and misses have been largely reduced.
_Note: object being cached has small memory footprint, and should not lead to large increase of memory_
Issues:
https://github.com/rancher/rancher/issues/18870
https://github.com/rancher/rancher/issues/18522
https://github.com/rancher/rancher/issues/18295
> Increase size of parent cache

- pkg/controllers/management/test/e2e/authz_test.go
- scripts/test
Problem:
Build not running go tests
Solution:
Enable go tests in test script. Vendor files are automatically skipped. Disable client setup in e2e package for now as config for it, and likely other dependencies, is missing.
> Run go tests

- pkg/api/store/projectsetter/project_setter_test.go
- pkg/api/store/projectsetter/store.go
- vendor.conf
- vendor/github.com/rancher/norman/store/proxy/proxy_store.go
- vendor/github.com/rancher/norman/types/server_types.go
Problem:
Requests associated with a particular project are not being filtered. Consequently, requests for projects that posses a fraction of total resources are taking longer than necessary to return.
Solution:
Identify namespaces for given project and use them to filter project related requests.
Issues:
https://github.com/rancher/rancher/issues/18870
https://github.com/rancher/rancher/issues/18522
https://github.com/rancher/rancher/issues/18295
https://github.com/rancher/rancher/issues/16605
> Add namespace filters for projects

- pkg/api/store/pod/owner.go
- pkg/api/store/projectsetter/project_setter_test.go
- pkg/api/store/projectsetter/store.go
- pkg/controllers/management/test/e2e/authz_test.go
- scripts/test
- vendor.conf
- vendor/github.com/rancher/norman/clientbase/common.go
- vendor/github.com/rancher/norman/clientbase/ops.go
- vendor/github.com/rancher/norman/parse/collection.go
- vendor/github.com/rancher/norman/store/proxy/proxy_store.go
- vendor/github.com/rancher/norman/types/server_types.go
This PR backports several API performance improvements from master to
v2.2. It also pulls in a commit that causes us to run `go test` as part
of CI builds.
https://github.com/rancher/rancher/issues/19443
> Backport performance improvements

- pkg/api/customization/podsecuritypolicytemplate/validator.go
- pkg/api/server/managementstored/setup.go
- tests/integration/test_pod_security_policies.py
Problem: Invalid pod security policy templates could be created in
Rancher.
Solution: Integrate k8s pod security policy validation logic into
Rancher as a validator within the PodSecurityPolicyTemplate schema.
https://github.com/rancher/rancher/issues/15686
> PSPT Validation

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Problem: We would like to specify the SSH key to be used.
Solution:
Add a field 'keyPairName' to the schema to support using a previously
created SSH key in EC2.
https://github.com/rancher/rancher/issues/14598
*Dependency on*
https://github.com/rancher/kontainer-engine/pull/125
> Add SSH keys to EKS nodes

- pkg/controllers/management/etcdbackup/etcdbackup.go
If someone is in us-east-1 region the domain would be https://s3-us-east-1.amazonaws.com and AWS doesn't have DNS for this. If we still wanted to use the dash it would be https://s3-external-1.amazonaws.com which is confusing. So I changed it from dash to period. So domains would now look like this https://s3.us-east-1.amazonaws.com which also conforms to AWS standards for region and is less confusing.
https://docs.aws.amazon.com/general/latest/gr/rande.html
> Changed S3 Backups Path

- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Problem:  Key pair name was shadowed causing the assignment to be
ineffective
Solution: Avoid re-declartion of keyPairName within if-statement.
Also formatting changes by gofmt -s and additonal context for
cloudformation failures.
Dependency: https://github.com/rancher/kontainer-engine/pull/150
Fixs https://github.com/rancher/rancher/issues/19483
> Fix shadowing of keyPairName

- pkg/api/customization/kontainerdriver/formatter.go
- pkg/api/customization/kontainerdriver/store.go
- tests/integration/test_kontainer_drivers.py
Problem: A cluster driver could be deleted when there were active
clusters that depended on that driver.
Solution: The API will not crash if a cluster driver is unable to be
removed. Kontainer drivers are no longer able to be removed via the UI
or API if there is a cluster that uses that driver.
Fix https://github.com/rancher/rancher/issues/18761
> Fix cluster driver delete while provisioning

- server/responsewriter/content.go
- server/server.go
Problem:
Monitoring would break on certain browsers because header was not being.
Solution:
Set use content handler in gzip chain. This handler will properly set content type header when necessary.
Refactor of:
https://github.com/rancher/rancher/pull/19497
Issue:
https://github.com/rancher/rancher/issues/19507
> Add content handler to gzip chain

- pkg/api/customization/project/project_actions.go
- pkg/controllers/user/monitoring/projectHandler.go
**Problem:**
- Cannot see the workload/container/pod metrics as `ProjectMetricGraph` has been deleted.
- Although delete monitoring action from schema resources, UI still can
seen `enableMonitoring` action link
**Solution:**
- Cannot delete `ProjectMetricGraph` directly.
- Remove actions addition from `Formatter`
**Issue:**
- https://github.com/rancher/rancher/issues/19516
- https://github.com/rancher/rancher/issues/19528
> Patch the missing Monitoring metrics

- pkg/clusterrouter/proxy/proxy_server.go
http.Transports will leak connections if they are garbage collected.  This
situation is made really bad when we are using a cluster dialer.
> Do not create http.Transports on demand

- app/app.go
- pkg/telemetry/telemetry.go
If we can't obtain a token for launching the telemetry service,
do not retry forever, give up after 3 tries.
> Don't retry telemetry forever

- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cloudflare_provider_config.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_route53provider_config.go
- vendor/github.com/rancher/types/image/mirror.go
- vendor/github.com/rancher/types/vendor.conf
Refers types: https://github.com/rancher/types/pull/778
Sets additional parameters configured on the GlobalDNSProvider Object. Also, now on update, we will update only the GlobalDNSProvider settings to the App answers and not update entire answers map - so if user has added any extra answers underneath, we dont wipe everything out.
rancher/rancher#19251
> Expose more params on GlobalDNSProvider and set them as answers to the app 

- app/machinedriver_data.go
Updates the Linode Node Driver to use docker-machine-driver-linode v0.1.7
* fixes the "Private IP" option for users that have the Linode "Network Helper" account setting disabled (https://github.com/linode/docker-machine-driver-linode/issues/13)
https://github.com/linode/docker-machine-driver-linode/releases/tag/v0.1.7
> Update the Linode Node Driver to v0.1.7

- pkg/api/customization/node/node.go
- server/responsewriter/gzip.go
- server/responsewriter/gzip_test.go
Problem:
Gzipped responses could have content-length set prematurely. Nodekeys would overwrite content-length header. This caused an error and would prevent nodekeys response from being properly interpreted when using http2.
Solution:
Removed content-length header from all gzipped responses. Also, added gzip encoding check for node keys logic.
Issue:
https://github.com/rancher/rancher/issues/19702
> Remove content-length from gzip responses

- pkg/api/customization/setting/setting.go
- tests/integration/test_settings.py
- vendor.conf
- vendor/github.com/rancher/norman/httperror/error.go
- vendor/github.com/rancher/types/vendor.conf
Problem:
Request ID is always used to query a setting. Request ID is set by parsing the request URL. It is possible for a setting request URL to not include the setting ID, and instead include it in the body.
When this was the case, the request would return with an error.
Solution:
If request ID is empty, the name will be used instead. Now, the setting can be properly set despite not having its ID in the request URL (this is the expected behavior).
Issues:
https://github.com/rancher/rancher/issues/19705
> Set ID to name if empty

- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- tests/core/test_globaldns.py
Regular user cannot create gdns provider, because it's now launched
as a catalog app, and the chart for this app needs to list clusters.
So creating a system account with right permissions solves this.
The app needs to be launched only in local cluster. So we're using
the system account for local cluster which gets created during server
start if local cluster is enabled. We also provide cluster-owner role
to this system account after creating it from cluster controller, hence
if used as the gdns provider app's creator, it has all right permissions.
https://github.com/rancher/rancher/issues/19709
> Use system account as creator of gdns provider app

- tests/integration/test_system_project.py
If clusterLogging tests run before system-namespaces test,
cattle-logging will be present in current system_namespaces.
https://drone-pr.rancher.io/rancher/rancher/1447/1/2
> remove cattle-logging from system_namespaces check

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/controllers/user/pipeline/controller/project/project.go
- pkg/systemaccount/systemaccount.go
When creating a cluster or project, we create a system user account, which creates a globalRoleBinding.
This user is not being removed when cluster/project is deleted, hence the user and corresponding globalRoleBinding are left behind.
This commit removes the user on cluster/project delete. And the user controller already removes the grb https://github.com/rancher/rancher/blob/release/v2.2/pkg/controllers/management/auth/user.go#L171
Addresses: https://github.com/rancher/rancher/issues/19018
> On cluster/project delete, remove system account created for it

- tests/integration/test_rbac.py
Problem:
Rbac tests are breaking due to an SSL issue and are not stable.
Solution:
Disabled project owner and impersonation passthrough tests for now.
> Disable broken rbac tests

- package/Dockerfile
- scripts/package
Our build scripts were not fully supporting the REPO environment
variable. It would create the images with the correct repo, but
would not inject the correct image names into the rancher server
build.
> Support custom image repo in build

- tests/integration/conftest.py
- tests/integration/test_kontainer_drivers.py
Kontainer driver tests should wait for cluster to reach a steady state
before performing actions that depend on cluster state.
> Increase timeout for kontainer driver tests

- pkg/api/customization/app/app.go
- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/controller.go
Problem: Helm/Tiller creates configmaps to track revision changes.
Rancher should use AppRevisions to do this but was not tracking AppRevisions
on failed helm upgrades. This caused rancher to run helm/tiller multiple
times on failing helm charts which created a large number of configmaps
quickly which would slow down the UI.
Solution: Rancher now correctly makes AppRevisions for failed helm
upgrades. Tiller has a max revision history of 1 (the minimum for
tiller to remain functional). Tiller will delete previous configmaps
the each time it is run. This also introduces the userTriggeredAction condition for cases where the helm controller should run regardless to carry out a user's intention. 
See https://github.com/rancher/rancher/issues/18571
See …
> Fix helm creating lots of configmaps

- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/logging/deployer/appdeployer.go
- pkg/controllers/user/logging/deployer/deployer.go
- pkg/controllers/user/logging/deployer/testerdeployer.go
- pkg/controllers/user/monitoring/appHandler.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/controllers/user/monitoring/register.go
- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- pkg/systemaccount/systemaccount.go
- tests/integration/conftest.py
- tests/integration/test_system_app_creator.py
**Problem:**
We are using cluster creator id as cluster monitoring creator. There
will be issue if the cluster creator is disabled or deleted.
**Solution:**
We should use system account to install cluster monitoring.
Related issue: https://github.com/rancher/rancher/issues/18787
> Install cluster monitoring with system account

- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/controllers/user/alert/configsyncer/configsyncer_test.go
- pkg/controllers/user/alert/deployer/notification_template.go
- pkg/controllers/user/alert/watcher/event.go
Problem:
1. Alert resolved time is 5 mins, alert get deleted in alertmanager if the same event did not happen in 5 mins. Event alert is special, an event will trigger only one time, extend the repeat interval then the event alert will be resolved after resolve time.
2. Event for the same resource with the different message will be placed to the same group, alertmanager will send notifications when new alert adds to this group, this notification includes all alerts in this group. If want user only sees current happen event without others in the same group, we need to add event message to the group key.
Solution:
1. Add default repeat time for event
2. Add message to event group key
Issue:
https://github.com/rancher/rancher/issues/19302
https://github.com/rancher/rancher/issues/19058
> improve event alert

- pkg/api/customization/app/app.go
**Problems:**
The catalog apps API didn't clear the valuesYaml or answers properties when sent as null.
https://github.com/rancher/rancher/issues/19634
**Solution:**
Clear the ValuesYaml or answers properties when the input value is null
> clear app valuesYaml or answers when is null

- pkg/controllers/management/clustergc/cluster_scoped_gc.go
- pkg/controllers/management/clustergc/cluster_scoped_gc_test.go
Problem: Cluster scoped finalizers were preventing deletion of
resources. The previous solution of manually writing cleanup code
within cluster_scoped_gc.go was difficult to maintain.
Solution: All generated handlers have an init function that adds to a
map within the norman framework. During cluster deletion this map is
iterated over and finalizers are removed as needed.
Addresses  https://github.com/rancher/rancher/issues/19900 https://github.com/rancher/rancher/issues/19899
> Backport Add check for cluster scoped finalizers

- tests/integration/suite/test_kontainer_drivers.py
Problem:
Kontainer driver tests occasionally fail regardless of changes made.
Solution:
Disable broken/flakey kontainer driver tests.
> Disable flakey kontainer driver tests

- chart/templates/_helpers.tpl
- chart/templates/ingress.yaml
- chart/tests/ingress_test.yaml
- chart/values.yaml
Add chart option to pass in additional nginx configuration snippets.
Example: Statically set a header:
```plain
helm install ./bin/chart/dev/rancher-0.0.0-dirty.c1c2e191e.tgz --name rancher \
--namespace cattle-system \
--set rancherImageTag=v2.2.2 \
--set hostname=jgreat-test-3.eng.rancher.space \
--set ingress.configurationSnippet='more_set_input_headers X-Forwarded-Host {{ .Values.hostname }};'
```
> [server-chart] add ingress config snippet

- chart/templates/_helpers.tpl
- chart/templates/ingress.yaml
- chart/tests/ingress_test.yaml
- chart/values.yaml
Add chart option to pass in additional nginx configuration snippets and clean up some extra white space in values.yaml.
Example: Statically set a header:
```
helm install ./bin/chart/dev/rancher-0.0.0-dirty.c1c2e191e.tgz --name rancher \
--namespace cattle-system \
--set rancherImageTag=v2.2.2 \
--set hostname=jgreat-test-3.eng.rancher.space \
--set ingress.configurationSnippet='more_set_input_headers X-Forwarded-Host {{ .Values.hostname }};'
```
> release/v2.2 - [server-chart] add ingress config snippet

- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/logging/deployer/deployer.go
**Problem:**
1. Logging and alerting app can't be deployed due to privileges of
account is not enough.
**Solution:**
1. Use cluster system account instead of project system account to
install them.
**Related Issues:**
master
https://github.com/rancher/rancher/issues/19971
https://github.com/rancher/rancher/issues/19959
2.2 (We need to backport to 2.2 branch)
https://github.com/rancher/rancher/issues/19974
https://github.com/rancher/rancher/issues/19970
> Install logging & alert with cluster system account

- pkg/api/customization/monitor/cluster_graph_action.go
- pkg/api/customization/monitor/metric_action.go
- pkg/api/customization/monitor/project_graph_action.go
- pkg/api/customization/monitor/prometheus_manager.go
- pkg/controllers/user/controllers.go
**Problem:**
Using Service to query metric expressions will increase the pressure on
the DNS service within the cluster
**Solution:**
Replace by ClusterIP
**Issue:**
https://github.com/rancher/rancher/issues/19292
> Adjust NewPrometheusQuery for Monitoring

- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/monitoring/deploy.go
**Problem:**
False deletion of Operator workload causes the redeployment of
Cluster Monitoring to fail.
**Solution:**
Check Operator workload isn't alive, then redeploy the App.
**Issue:**
#19209
> Redeploy Monitoring Operator when accidentally deleted

- chart/templates/_helpers.tpl
- chart/templates/ingress.yaml
- chart/values.yaml
backport for #19958
Add chart option to pass in additional nginx configuration snippets and clean up some extra white space in values.yaml.
Example: Statically set a header:
```
helm install ./bin/chart/dev/rancher-0.0.0-dirty.c1c2e191e.tgz --name rancher \
--namespace cattle-system \
--set rancherImageTag=v2.2.2 \
--set hostname=jgreat-test-3.eng.rancher.space \
--set ingress.configurationSnippet='more_set_input_headers X-Forwarded-Host {{ .Values.hostname }};'
```
> release/v2.0 - [server-chart] add ingress config snippet

- chart/templates/_helpers.tpl
- chart/templates/ingress.yaml
- chart/values.yaml
backport for #19958
Add chart option to pass in additional nginx configuration snippets and clean up some extra white space in values.yaml.
Example: Statically set a header:
```
helm install ./bin/chart/dev/rancher-0.0.0-dirty.c1c2e191e.tgz --name rancher \
--namespace cattle-system \
--set rancherImageTag=v2.2.2 \
--set hostname=jgreat-test-3.eng.rancher.space \
--set ingress.configurationSnippet='more_set_input_headers X-Forwarded-Host {{ .Values.hostname }};'
```
> release/v2.1 - [server-chart] add ingress config snippet

- pkg/api/customization/setting/setting.go
- pkg/api/store/setting/store.go
- tests/integration/suite/test_rbac.py
- tests/integration/suite/test_settings.py
Problem:
Setting tests are deleting cacert setting causing some rbac tests to fail if they are executed after.
Solution:
Disable ability to delete readonly settings with settings API. Settings tests no longer attempt remove cacert setting, aside from test for deletion. Reenabled rbac tests.
> Disable deletion for readonly settings and remove setting deletion from test

- pkg/api/customization/monitor/cluster_graph_action.go
- pkg/api/customization/monitor/metric_action.go
- pkg/api/customization/monitor/project_graph_action.go
- pkg/api/customization/monitor/prometheus_manager.go
- pkg/controllers/user/controllers.go
**Problem:**
Using Service to query metric expressions will increase the pressure on
the DNS service within the cluster
**Solution:**
Replace by ClusterIP
**Issue:**
https://github.com/rancher/rancher/issues/19999
> Backport: Adjust NewPrometheusQuery for Monitoring

- app/role_data.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/common/extra_args_injection.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/controllers/user/monitoring/register.go
- pkg/controllers/user/rbac/handler_base.go
- pkg/controllers/user/rbac/prtb_handler.go
- pkg/monitoring/deploy.go
- pkg/rbac/common.go
- pkg/rbac/common_test.go
- pkg/settings/setting.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_project_role_template_binding.go
For project monitoring fix, we have following changes:
- Update project monitoring app answers due to the charts version updated.
- Create the project role template binding for service account when enabling project monitoring.
- Support generating sa subject from PRTB.
Support helm install with app info:
Inject cluster name, project name and default registry parameters as extra answers values when helm installing.
We are no longer storing them in app answers like the old default registry parameter.
Related issues: 
- https://github.com/rancher/rancher/issues/19381
- https://github.com/rancher/rancher/issues/19674
Related PRs:
- https://github.com/rancher/types/pull/801
- https://github.com/rancher/system-charts/pull/37
> Fix project monitoring issue

- app/role_data.go
- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/common/extra_args_injection.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/project_handler.go
- pkg/controllers/user/monitoring/register.go
- pkg/controllers/user/rbac/handler_base.go
- pkg/controllers/user/rbac/prtb_handler.go
- pkg/monitoring/deploy.go
- pkg/rbac/common.go
- pkg/rbac/common_test.go
- pkg/settings/setting.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_project_role_template_binding.go
Backport PR for https://github.com/rancher/rancher/pull/19766
For project monitoring fix, we have following changes:
- Update project monitoring app answers due to the charts version updated.
- Create the project role template binding for service account when enabling project monitoring.
- Support generating sa subject from PRTB.
Support helm install with app info:
Inject cluster name, project name and default registry parameters as extra answers values when helm installing.
We are no longer storing them in app answers like the old default registry parameter.
> Fix project monitoring v2.2

- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/project_handler.go
- pkg/monitoring/deploy.go
**Problem:**
False deletion of Operator workload causes the redeployment of
Cluster Monitoring to fail.
**Solution:**
- Check Operator workload isn't alive, then redeploy the App.
- Log Monitoring Operator error info
**Issue:**
https://github.com/rancher/rancher/issues/19998
> Backport: Redeploy Operator when accidentally deleted

- tests/validation/tests/v3_api/test_app.py
Use cluster id of cluster specified in RANCHER_CLUSTER_NAME (env var param -- code uses CLUSTER_NAME set in common.py); currently the test will fail if run against a single-node install, or HA where addLocal=false
Tested on HA & single node installs.
@sangeethah @daxmc99
> QA Validation - Use cluster id of specified cluster instead of 'local'

- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
In ontag cluster matrix pipeline job: if there is an error in deleting the first rancher server, `error()` will abort the pipeline when we want to continue to the second server's deletion instead.
@sangeethah
> QA Validation - Remove script abort from error handling in delete server stage

- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
- pkg/controllers/user/logging/deployer/upgradeimpl_test.go
- pkg/settings/setting.go
Problem:
logging system chart have new version
Solution:
update init logging system version to latest one
Issue:
https://github.com/rancher/rancher/issues/19836
Charts PR:
https://github.com/rancher/system-charts/pull/38
> Changing Rancher to use a new logging system chart version

- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
- pkg/controllers/user/logging/deployer/upgradeimpl_test.go
- pkg/settings/setting.go
Problem:
logging system chart have new version
Solution:
update init logging system version to latest one
Issue:
https://github.com/rancher/rancher/issues/20046
> [release/v2.2] Changing Rancher to use a new logging system chart version

- server/responsewriter/gzip.go
- server/responsewriter/gzip_test.go
Problem:
Responses with no body were being needlessly gzipped. This generated confusion as empty responses had a length greater than zero.
Solution:
Gzip encoding is now only used once a response writer writes to body.
Issue:
https://github.com/rancher/rancher/issues/19553
> Disable empty gzip

- pkg/controllers/user/logging/utils/kafka.go
- vendor.conf
- vendor/github.com/segmentio/kafka-go/README.md
- vendor/github.com/segmentio/kafka-go/batch.go
- vendor/github.com/segmentio/kafka-go/compression.go
- vendor/github.com/segmentio/kafka-go/conn.go
- vendor/github.com/segmentio/kafka-go/deletetopics.go
- vendor/github.com/segmentio/kafka-go/describegroups.go
- vendor/github.com/segmentio/kafka-go/dialer.go
- vendor/github.com/segmentio/kafka-go/docker-compose.yml
- vendor/github.com/segmentio/kafka-go/error.go
- vendor/github.com/segmentio/kafka-go/message.go
- vendor/github.com/segmentio/kafka-go/produce.go
- vendor/github.com/segmentio/kafka-go/protocol.go
- vendor/github.com/segmentio/kafka-go/read.go
- vendor/github.com/segmentio/kafka-go/reader.go
- vendor/github.com/segmentio/kafka-go/sasl/sasl.go
- vendor/github.com/segmentio/kafka-go/saslauthenticate.go
- vendor/github.com/segmentio/kafka-go/saslhandshake.go
- vendor/github.com/segmentio/kafka-go/sizeof.go
- vendor/github.com/segmentio/kafka-go/write.go
- vendor/github.com/segmentio/kafka-go/writer.go
Problem:
Test function for sending log couldn't support auto-detect kafka broker
controller now, when user input a broker endpoint which isn't the controller couldn't create kafka topic.
Solution:
update kafka vendor and detect broker controller
Issue:
https://github.com/rancher/rancher/issues/19448
Related test PR:
https://github.com/rancher/validation/pull/159
> Update kafka vendor to support detect kafka broker controller

- package/windows/hyperkube.ps1
- package/windows/run.ps1
**Problem:**
Use `host-gw`, if passing public IP, flannel will be failed to run.
**Solution:**
- Remove `--public-ip` when flanneld starting
- `-internalAddress` should be the required option on Windows, because, on Windows, kubelet cannot confirm which nic has the correct internal address, we need to pass it into `--node-ip` as kubelet running args.
**Issue:**
https://github.com/rancher/rancher/issues/19964
> Fix Windows host-gw mode public ip issue

- tests/integration/suite/test_globaldns.py
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go
https://github.com/rancher/rancher/issues/19738
Now the GlobalDNS FQDN is of type "hostname" which is a series of dnsLabels, that can only have alphanumeric characters and hyphen(-), separated by dot(.)
rancher/types PR:https://github.com/rancher/types/pull/822
> GlobalDNS FQDN should be of type hostname

- pkg/controllers/management/cluster/clustercontroller.go
- pkg/controllers/management/cluster/clustercontroller_test.go
https://github.com/rancher/rancher/issues/18275#issuecomment-490601105
Couldn't add integration test, since the test would have to create a cluster and the final check is to see if adding an lb in this cluster's project is enabled in the ui
>  Don't default rke clusters lb cap to false

- pkg/controllers/management/auth/user.go
User controller could panic on cluster deletion due to accessing a nil
reference of cluster.Name within the set. Non-existent clusters now will
not be added to the map.
This will need to be backported as well
> Fix panic on UserController

- pkg/controllers/management/cluster/clustercontroller.go
https://github.com/rancher/rancher/issues/18275#issuecomment-490601105
> Backport: Don't default rke clusters lb cap to false

- pkg/controllers/management/auth/user.go
User controller could panic on cluster deletion due to accessing a nil
reference of cluster.Name within the set. Non-existent clusters now will
not be added to the map.
> Backport Fix panic UserController

- pkg/controllers/user/logging/utils/kafka.go
- vendor.conf
- vendor/github.com/segmentio/kafka-go/README.md
- vendor/github.com/segmentio/kafka-go/batch.go
- vendor/github.com/segmentio/kafka-go/compression.go
- vendor/github.com/segmentio/kafka-go/conn.go
- vendor/github.com/segmentio/kafka-go/deletetopics.go
- vendor/github.com/segmentio/kafka-go/describegroups.go
- vendor/github.com/segmentio/kafka-go/dialer.go
- vendor/github.com/segmentio/kafka-go/docker-compose.yml
- vendor/github.com/segmentio/kafka-go/error.go
- vendor/github.com/segmentio/kafka-go/message.go
- vendor/github.com/segmentio/kafka-go/produce.go
- vendor/github.com/segmentio/kafka-go/protocol.go
- vendor/github.com/segmentio/kafka-go/read.go
- vendor/github.com/segmentio/kafka-go/reader.go
- vendor/github.com/segmentio/kafka-go/sasl/sasl.go
- vendor/github.com/segmentio/kafka-go/saslauthenticate.go
- vendor/github.com/segmentio/kafka-go/saslhandshake.go
- vendor/github.com/segmentio/kafka-go/sizeof.go
- vendor/github.com/segmentio/kafka-go/write.go
- vendor/github.com/segmentio/kafka-go/writer.go
Problem:
Test function for sending log could support auto-detect kafka broker
controller by updating the vendor, then user don't need to input
the endpoint for kafka controler
Solution:
update kafka vendor and detect broker controller
Issue:
https://github.com/rancher/rancher/issues/20095
> Backport: Update kafka vendor to support detect kafka broker controller

- app/machinedriver_data.go
Problem:
Previous otc download url is pointing to the latest version. We cannot make sure the checksum for it always correct.
Solution:
Point it to a particular version of otc driver.
https://github.com/rancher/rancher/issues/19223
> Fix the issue OTC driver cannot be activated

- pkg/controllers/user/monitoring/clusterHandler.go
Problem:
Monitoring get redeployed due to etcd params updated. However, it is not expected as the etcd address doesn't change at all.
Solution:
Sort it before assign.
Issue:
https://github.com/rancher/rancher/issues/19945
> [2.2.3]Sorting etcd tls config before setup the config

- pkg/controllers/user/monitoring/clusterHandler.go
Problem:
Monitoring get redeployed due to etcd params updated. However, it is not expected as the etcd address doesn't change at all.
Solution:
Sort it before assign.
Issue:
https://github.com/rancher/rancher/issues/19945
> [2.2.2-patch]Sorting etcd tls config before setup the config

- package/windows/hyperkube.ps1
**Problem:**
Use the wrong separator to split the controlplanes address list
**Solution:**
Change "," to ";"
**Issue:**
https://github.com/rancher/rancher/issues/20178
> Fix cannot run Windows agent with multiple controlplanes

- pkg/controllers/user/monitoring/clusterHandler.go
Problem:
Monitoring get redeployed due to etcd params updated. However, it is not expected as the etcd address doesn't change at all.
Solution:
Sort it before assign.
Issue:
https://github.com/rancher/rancher/issues/19945
https://github.com/rancher/rancher/issues/20186
> Sorting etcd tls config before setup the config

- pkg/api/customization/cluster/actionhandler.go
- pkg/api/customization/cluster/formatter.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
The actions are currently duplicated using direct strings. Refactoring them.
Relevant types PR: https://github.com/rancher/types/pull/830
> Refactor cluster actions

- app/app.go
- app/catalog_data.go
- app/catalog_data_test.go
Problem:
Old versions of rancher may be incompatible with system charts master branch.
Solution:
Added logic for maintaining default url/branch for system-library
catalog, and its annotation.
Issue:
https://github.com/rancher/rancher/issues/20115
> Upgrade system charts

- app/catalog_data.go
- pkg/catalog/git/git.go
- pkg/catalog/helm/helm.go
- pkg/catalog/helm/setup.go
Verifies the git catalog cache is at the specified last commit for helm.New.
Makes git catalog detection more robust and adds possibility for explicitly defining the catalog kind (`helm:git` or `helm:http`).
> Fix helm-git cache updates on HA

- app/catalog_data.go
- pkg/catalog/git/git.go
- pkg/catalog/helm/helm.go
- pkg/catalog/helm/setup.go
Verifies the git catalog cache is at the specified last commit for
helm.New.
Makes git catalog detection more robust and adds possibility for
explicitly defining the catalog kind (`helm:git` or `helm:http`).
> Fix helm-git cache updates on HA (v2.2 backport)

- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/monitoring/deploy.go
**Problem:**
It is not user friendly to show the monitoring template not found
error in UI.
**Solution:**
The error for template not found is not necessary as we won't update
the existing monitoring app to the newest version. Just remove it.
Related issue:
https://github.com/rancher/rancher/issues/20309
> Remove the logic to detect monitoring charts

- package/jailer.sh
**Problem:**
Create jailer for helm install but missing the `/etc/hosts`
**Solution:**
Copy the `/etc/hosts` to `/opt/jail/$NAME/etc/` to fix the network
namespace.
https://github.com/rancher/rancher/issues/20389
https://github.com/rancher/rancher/issues/20289
> Fix Helm install error

- package/jailer.sh
Problem:
If the bin dir is empty stat fails on "*"
Solution:
Verify the dir has contents before attempting the copy
> Check if dir is empty before copy

- pkg/controllers/user/rbac/handler_base.go
- pkg/controllers/user/rbac/namespace_handler.go
**Problem:**
The project monitoring can't fetch metrics from the namespace moved
from the other project
**Solution:**
The RBAC handler should handle service account type PRTB
too.
**Issues:**
https://github.com/rancher/rancher/issues/20459
https://github.com/rancher/rancher/issues/20390
> RBAC handler should handle sa kind PRTB

- package/jailer.sh
Problem:
If the bin dir is empty stat fails on "*"
Solution:
Verify the dir has contents before attempting the copy
> Check if dir is empty before copy v2.1

- package/jailer.sh
Problem:
If the bin dir is empty stat fails on "*"
Solution:
Verify the dir has contents before attempting the copy
> Check if dir is empty before copy v2.0

- tests/validation/tests/v3_api/common.py
In ingress and port tests, fallback to ipAddress if externalIpAddress is not set on node
@drpebcak @sangeethah
> QA Validation - if node.externalIpAddress is not set, fallback to node.ipAddress

- pkg/agent/clean/clean.go
Fix variable initial problem in pkg/agent/clean.go
**Problem:**
Can't copy string slice from `nsToRemove` to `toRemove` in client.go so
the namespace cleaning logic won't clean namespaces in `nsToRemove`.
**Solution:**
We should initial the `toRemove` variable with `make([]string, len(nsToRemove))`
Related issue:
https://github.com/rancher/rancher/issues/19476
> Clean cattle-prometheus ns

- package/windows/hyperkube.ps1
- package/windows/run.ps1
**Problem:**
Windows worker cannot query GCE metadata
**Solution:**
- Add the metadata accessing route
- Add GCE cloud provider logic
- Adjust `get-hyper-vswitch`
**Issue:**
https://github.com/rancher/rancher/issues/20156
> Support Windows with GCE cloud provider

- pkg/controllers/management/node/controller.go
- pkg/controllers/management/node/utils.go
- pkg/nodeconfig/config.go
Problem: 
key name is hardcoded to 'id_rsa'
Solution:
Use the name of the file that gets generated when a user passes in an sshkey instead of using a generated one
> Use dynamic ssh key name to find key v2.2

- pkg/controllers/management/node/controller.go
- pkg/controllers/management/node/utils.go
- pkg/nodeconfig/config.go
Problem:
key name is hardcoded to 'id_rsa'
Solution:
Use the name of the file that gets generated when a user passes in an sshkey instead of using a hardcoded one
> Use dynamic ssh key name to find key master

- package/windows/hyperkube.ps1
- pkg/rkenodeconfigserver/nodeserver.go
**Problem:**
Cannot run kube-proxy on Windows with AWS cloud provider if doesn't
indicate the AWS instance internal name.
**Solution:**
Set `hostname-override` on agent side
**Issue:**
https://github.com/rancher/rancher/issues/20185
> Support run kube-proxy on Windows with AWS cloud provider

- package/windows/run.ps1
**Problem:**
- Occurring error when adding Windows node from Aliyun, it seems we could
not find the Docker named pipe from Aliyun Windows node, however, the
Docker is running.
- `[Net.ServicePointManager]::CertificatePolicy` is now obsolete:
https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.certificatepolicy?view=netframework-4.8#System_Net_ServicePointManager_CertificatePolicy.
**Solution:**
- Give a warning msg to user when we could not find the Docker named pipe.
- According to http://huddledmasses.org/blog/validating-self-signed-certificates-properly-from-powershell/,
we can hack `[Net.ServicePointManager]::ServerCertificateValidationCallback`.
**Issue:**
#20487
#20235
> Fix could not add Windows node from Aliyun

- package/run.sh
- pkg/settings/setting.go
- pkg/systemtemplate/template.go
1. Add `global-registry-enabled` setting, It is used to detect whether global registry is enabled for non-admin users.
2. Copy ca cert to `/etc/docker/certs.d/<server-host>[:port]/ca.crt` on the host([see reference](https://docs.docker.com/engine/security/certificates/)). So that nodes on clusters can connect to the global registry in custom CA root cases. CA cert locates in `/etc/kubernetes/ssl/certs/serverca` both inside node agents & on the hosts before, this keeps the same.
In this solution, `/etc/docker/certs.d` instead of `/etc/docker/certs.d/<server-host>[:port]` on the host mounts node agent containers, due to two limitations:
- Colon is not supported in kuberentes volume path, which may be needed in docker cert path. [see](https://github.com/kubernetes/kubernetes/issues/21681#issu …
> Updates for global registry support

- tests/integration/suite/test_node.py
NodeTemplateLister might not have the just created nodeTemplate,
adding retry to confirm before deleting cloud credential.
https://github.com/rancher/rancher/issues/20080
> attempt to fix flaky test_cloud_credential_delete

- pkg/controllers/user/helm/common/extra_args_injection.go
- pkg/controllers/user/helm/common/extra_args_test.go
Check len for split `catalogWithNamespace`
Check catalogName before getting the
`SystemDefaultRegistry` value from etcd.
Base on comments in PR https://github.com/rancher/rancher/pull/20184.
> Small fix for helm extra args

- tests/integration/suite/test_node.py
Problem:
It is possible that cloud credential is not immediately available. This will cause the writing config to disk test to fail.
Solution:
Create will be retried if the credential is unavailable.
Issue:
https://github.com/rancher/rancher/issues/20683
> Fix node test

- app/role_data.go
Grant istio related permissions to Project Member / Owner / Read-only.
All the added permission are namespaced scope
`networking.istio.io`, 
`config.istio.io`, 
`authentication.istio.io`
`rbac.istio.io`
Related issue:
https://github.com/rancher/rancher/issues/20666
> [Istio]Add RBAC role for istio resource

- pkg/controllers/management/node/utils.go
- pkg/controllers/user/helm/common/common.go
- pkg/jailer/jailer.go
- pkg/jailer/jailer_test.go
- pkg/settings/setting.go
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/service/service.go
Problem:
The jail clears the env and sets only ones required to run. This drops
envvars that might be needed for a proxy
Solution:
Add a whitelist of envvars to pull into the jail with a default list to
support proxies or user updated setting
Issue: https://github.com/rancher/rancher/issues/20709
> Whitelist envvars for jail

- tests/validation/tests/v3_api/common.py
@bmdepesa Can you review this PR?
Problem:
This fix is made to address random test case failures when the following validation method fails , since we assume the correct number of pods to be available as soon as the workload gets to active state.  Although this is true most of the time , we have seen random test failures around this check.
Fix:
We are now waiting for the desired number of pods to be made available for a maximum of 2 minutes, before we proceed to asserting the pod check.
```
def validate_workload(p_client, workload, type, ns_name, pod_count=1,
wait_for_cron_pods=60):
workload = wait_for_wl_to_active(p_client, workload)
assert workload.state == "active"
if type == "cronJob":
time.sleep(wait_for_cron_pods)
pods = p_client.list_pod(workloadId=workload.id).data
>       assert …
```
> Wait for pods to reach desired count after workloads get to active state.

- pkg/controllers/user/alert/config/notifiers.go
- pkg/controllers/user/alert/configsyncer/configsyncer.go
- pkg/notifiers/sender.go
Problem:
Not support http_proxy setting now
Solution:
Add http_proxy configure for slack, pagerduty, wechat, webhook
Issue:
https://github.com/rancher/rancher/issues/17885
Types:
https://github.com/rancher/types/pull/855
Test:
https://github.com/rancher/rancher/pull/20743
> [Alerting] Support set http_proxy config on Rancher notifier

- package/windows/cleanup.ps1
- package/windows/hyperkube.ps1
**Problem:**
K8S GCE cloud provider has replace `Get-GcePdName` with native windows
support of `Get-Disk`, but the GCE VMs haven't injected the new
method.
**Solution:**
Following
https://github.com/kubernetes/kubernetes/blob/f49fe2a7504c40684573f3e4928e8b0bfdfb2b30/cluster/gce/windows/k8s-node-setup.psm1#L782-L795,
we can patch the `Get-GcePdName`.
**Issue:**
https://github.com/rancher/rancher/issues/20180
> [Windows] Fix could not use GCEPersistentDisk on Windows

- .drone.yml
- manifest-agent.tmpl
- manifest.tmpl
This PR extends the functionality used to automatically build docker images when code is pushed to master so that `release/v*` branches also get created.
It also syncs the drone.yaml with the master branch to get changes that have been made there related to tagging conventions and manifests.
`master` builds are tagged `master`. `release/v*` branches have the `/` replaced with a `-` - for example `release-v2.2`
I have verified the following cases:
* We do NOT create docker images or manifests on push to branches that are not `master` or `release/v*`.
* When we tag a branch, it does NOT trigger the `head` steps.
* When we push to `master` or `release/v*` it DOES create and publish a `rancher/rancher` and `rancher/rancher-agent` image and manifest.
What I can't verify:
* Any steps that …
> publish on head of master and release branches

- .drone.yml
Update name of the agent image publish step in the arm pipeline to show it does publish on HEAD. Followup for #20678
> update step name for accuracy

- .drone.yml
This should fix the issue with the rancher-agent docker image using an invalid tag name when using a `release-v*` docker image.
> replace the / in VERSION arg

- package/jailer.sh
Problem:
ssh is not in the jail causing docker-machine to use the native go ssh package, this causes issues depending on the OS the system is running
Solution:
Pull in ssh and required supporting libs
https://github.com/rancher/rancher/issues/20985
https://github.com/rancher/rancher/issues/20987
> Update jailer script - master

- package/jailer.sh
Problem:
ssh is not in the jail causing docker-machine to use the native go ssh package, this causes issues depending on the OS the system is running
Solution:
Pull in ssh and required supporting libs
https://github.com/rancher/rancher/issues/20753
https://github.com/rancher/rancher/issues/20289
> Update jailer script

- pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/20964
bug was introduced when we refactored backup logic,  https://github.com/rancher/rancher/pull/19623/commits/37746abf15b948ba310a707ad1b821b0a17dc7b3
> check for nil enabled

- .gitignore
- tests/integration/suite/test_clustertemplate.py
Fixing the flaky test that can fail if a cluster delete remains pending, then removal of the cluster_template will error out during teardown of the test.
https://github.com/rancher/rancher/issues/20869
> Fix the test that can fail due to pending cluster delete

- pkg/api/store/clustertemplate/store.go
- pkg/controllers/management/clustertemplate/revision_controller.go
- pkg/controllers/management/controller.go
- tests/integration/suite/test_clustertemplate.py
Corresponding Types PR: https://github.com/rancher/types/pull/872
Changes:
- When the very first Cluster Template Revision is created, we set the ClusterTemplate.DefaultRevisionId if it is not set
- When the Cluster Template Revision is being deleted, we error out incase it is the revision pointed by ClusterTemplate.DefaultRevisionId
> Changes to set Default Cluster Template Revision

- tests/integration/suite/test_node.py
It is possible that cloud credential is not
immediately available. Prior, this would cause
the test to fail. Now, create will be retried if
the credential is unavailable.
> Add wait to config write test

- pkg/api/customization/globalnamespaceaccess/access_common.go
- pkg/controllers/management/cloudcredential/controller.go
- pkg/controllers/management/clustertemplate/clustertemplate_rbac.go
- pkg/controllers/management/clustertemplate/revision_controller.go
- pkg/controllers/management/globaldns/globaldns_handler.go
- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
- pkg/controllers/management/globalnamespacerbac/rbac_common.go
- pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go
- tests/integration/suite/common.py
- tests/integration/suite/test_clustertemplate.py
- tests/integration/suite/test_multi_cluster_app.py
This PR introduces two changes:
1. Multiclusterapp, global dns providers & entries are created in the cattle-global-data namespace. They can be shared by users other than their creators through the Members field. The rbac controllers create roles containing the resourceNames, and rolebindings with these roles for the members.
Now these resources can also be shared by everyone, by typing in the character `*` in the search box of members. This will translate to the `system:authenticated` k8s rbac group on the rolebinding for a role containing this resource. This will allow all authenticated users to have access to this resource.
2. Adds the same sharing logic with Members and all authenticated users for clustertemplates
> Refactor rbac for sharing global ns resources

- .drone.yml
- manifest-agent.tmpl
- manifest.tmpl
After this, tags in the docker hub will be formatted as `master-head` and `v2.2-head`
> strip "release/" and add "-head" suffix

- app/role_data.go
As a standard user, one should be able to create clustertemplates and clustertemplaterevisions
https://github.com/rancher/rancher/issues/21067
> Standard User role changes for clustertemplates resource

- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/alert/deployer/upgradeimpl.go
Problem:
System chart have bug that enable alertmanager will also deploy operator if not set false to enable operator
Solution:
Set enable operator to false, system charts bug will be fixed later
Issue:
https://github.com/rancher/rancher/issues/21113
> [2.2]Disable operator when enable alert

- pkg/controllers/user/alert/deployer/upgradeimpl.go
Problem:
Rancher 2.2.4 and 2.2.5 use monitoring chart 0.0.3, version check will
prevent app upgrade when version not change but we still want to update
the app
Solution:
Remove version check when upgrade alertmanager
Issue:
https://github.com/rancher/rancher/issues/21113
> Remove version compare when upgrade alerting

- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/alert/deployer/upgradeimpl.go
Problem:
System chart have bug that enable alertmanager will also deploy operator if not set false to enable operator
Solution:
Set enable operator to false, system charts bug will be fixed later
Issue:
https://github.com/rancher/rancher/issues/20975
> Disable operator when enable alert

- pkg/controllers/user/monitoring/clusterHandler.go
**Problem:**
Doesn't allow user to configure DNS monitoring
**Solution:**
Remove `false` configuration item from mandatory option:
- if interested in kube-dns metrics (v1.12)
+ configuring `exporter-kube-dns.enabled` item as `true` when
enabling cluster-level monitoring
+ guaranteeing the DNS service of `kube-system` namespace has:
- `k8s-app=kube-dns` label
- `dnsmasq-metrics` port with `TCP:10054`
- `skydns-metrics` port with `TCP:10055`
- if interested in coredns metrics (v1.14)
+ configuring `exporter-coredns.enabled` item as `true` when enabling
cluster-level monitoring
+ guaranteeing the DNS service of `kube-system` namespace has:
- `k8s-app=kube-dns` label
- `metrics` port with `TCP:9153`
**Issue:**
https://github.com/rancher/rancher/issues/21066
> [Monitoring] Allow users to configure DNS monitoring

- pkg/agent/main_windows.go
- pkg/rkenodeconfigclient/client.go
**Problem:**
Add back after restarting the removed Windows node
**Solution:**
Return ErrNodeOrClusterNotFound error if could not found the node or cluster
**Issue:**
https://github.com/rancher/rancher/issues/20496
**result:**
- Windows agent will stop itself after removing from UI:
- Restart the removed agent:
> [Windows] Fix removed Windows node to re-add after restarting

- app/role_data.go
- tests/integration/requirements.txt
- tests/integration/suite/pipeline_common.py
- tests/integration/suite/test_pipeline.py
Address issue: https://github.com/rancher/rancher/issues/16153
Problem:
A project-owner with custom global roles cannot fetch pipeline repositories.
Sourcecodecred/repo rule is only available in global `user`(standard) role, and
they are user-scoped resources so they are not granted by PRTB.
Solution:
Add sourcecodecredential/repository rules to user-base role
> [Pipeline]Add sourcecodecred/repo rules to user-base role

- pkg/controllers/management/nodepool/nodepool.go
- pkg/controllers/management/nodepool/nodepool_test.go
- pkg/controllers/user/nodesyncer/nodessyncer.go
Verified following:
This fix allows nodes deleted via the `kubectl delete node` to actually be deleted in Rancher. If a cloud provider is used this means that `kubectl delete node` will actually destroy the underlying infrastructure. 
This PR also includes the feature of self-healing nodepools, where nodepools can have the self-healing option set to True & configure a timeout specified in seconds to delete and attempt to recreate the node.
> Self Healing nodepools

- pkg/controllers/management/drivers/base_driver.go
- pkg/controllers/management/drivers/dynamic_driver.go
- pkg/controllers/management/drivers/nodedriver/machine_driver.go
This PR intends to fix the issue rancher/rancher#18058 .
The node driver will be downloaded if the cache version doesn't exits.
Previously, it was only checking the binary executable which doesn't contain any version information.
> Fixed issue where the node drivers where not downloaded on url update

- pkg/api/server/managementstored/setup.go
- pkg/api/store/clustertemplate/store.go
- tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/21164
Read-only members of a clusterTemplate should not be able to create revisions for it.
This is because there's a chance such a revision could get set as the default revision on clusterTemplate, thus updating it, which a read-only member should not be allowed to.
> Forbid readonly clustertemplate members from creating revisions

- app/global_namespace.go
- pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
If global namespace isn't found, we miss the init logic and then have to wait for refresh interval to take place
> sync metadata setting after ns gets created

- app/catalog_data.go
Problem:
users in dev mode were on the master system charts branch. If env
variable was forgotten, it would not have been immediately
apparent.
Solution:
Now, if in dev mode system charts default branch is set to dev.
If not in dev mode and no branch has been set to CATTLE_
_SYSTEM_CHART_DEFAULT_BRANCH, rancher will panic.
> Check dev mode for system charts

- pkg/agent/windows/remotedialer/client_windows.go
To prevent agent from being hung in the middle of Websocket Session
Handshake, We'd better to set HandshakeTimeout
Related to https://github.com/rancher/rancher/issues/21117
> Configure HandshakeTimeout in websocket.Dialer

- pkg/systemtemplate/template.go
Problem: Manually tainted nodes will not get new cattle-node-agent pods due to insufficient tolerations.
Solution: Allow all taints for cattle-node-agent. This change also prefers controlplane and etcd nodes for cattle-cluster-agent.
> [release/v2.2] Change scheduling for node/cluster agent pods

- pkg/systemtemplate/template.go
Problem: Manually tainted etcd/controlplane nodes won't get cluster-agent or kube-api-auth scheduled
Solution: Allow all taints for agents and kube-api-auth
~Possible issues here is kube-api-auth being a daemonset and being scheduled to every node in the cluster.~ After talking to Erik, we can restrict kube-api-auth to controlplane nodes. PR updated
> Allow all taints for agents and kube-api-auth

- pkg/systemtemplate/template.go
Problem: Manually tainted etcd/controlplane nodes won't get cluster-agent or kube-api-auth scheduled
Solution: Allow all taints for agents and kube-api-auth, restrict kube-api-auth to controlplane nodes
> [2.2 backport] Allow all taints for agents and kube-api-auth

- pkg/controllers/user/helm/common.go
Problem:
The helm jail is based off the app name so if multiple apps with the
same name come through the jail can get deleted out from under other
running processes
Solution:
Make the jail name unique
https://github.com/rancher/rancher/issues/21416
> Make helm jail name unique

- pkg/controllers/management/node/utils.go
- pkg/controllers/user/helm/common/common.go
- pkg/jailer/jailer.go
- pkg/jailer/jailer_test.go
- pkg/settings/setting.go
- vendor.conf
- vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
- vendor/github.com/rancher/kontainer-engine/service/service.go
Problem:
The jail clears the env and sets only ones required to run. This drops
envvars that might be needed for a proxy
Solution:
Add a whitelist of envvars to pull into the jail with a default list to
support proxies or user updated setting
https://github.com/rancher/rancher/issues/20709
> Forwardport: Whitelist envvars for jail

- pkg/controllers/user/alert/deployer/upgradeimpl.go
- pkg/controllers/user/controllers.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
- pkg/controllers/user/logging/deployer/upgradeimpl_test.go
- pkg/controllers/user/pipeline/upgrade/upgradeimpl.go
- pkg/controllers/user/systemimage/register.go
- pkg/controllers/user/systemimage/systemimage.go
- pkg/controllers/user/systemimage/upgrader.go
Problem:
only one cluster system server upgrade success when there are multiple
cluster
Solution:
this cause by only one alert/logging/pipeline upgradeService was init,
when there are multiple cluster, the former clusterName will be
overwrite by the laster one. Now change handle multiple cluster when
init upgradeService
Issue:
https://github.com/rancher/rancher/issues/21458
> For 2.2: fix upgrade system image failed when manage multiple clusters

- pkg/controllers/user/controllers.go
**Problem:**
No effect when `xip.io` suffix is changed to other suffix.
**Solution:**
The ingresshostgen controller is using the `IngressIPDomain` setting.
So the controller should run in Rancher side.
**Issue:**
https://github.com/rancher/rancher/issues/19915
> Fix dns auto generate issue

- pkg/api/customization/logging/action.go
- pkg/controllers/user/logging/deployer/testerdeployer.go
Problem:
Input fluentd configure in advance mode got crash
Solution:
This bug was introduced when update systemAccountManager for system apps, need to init systemAccountManager for tester deployer
Issue:
https://github.com/rancher/rancher/issues/20568
> [Logging]Init systemAccountManager for logging tester deployer

- pkg/controllers/user/alert/deployer/upgradeimpl.go
- pkg/controllers/user/controllers.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
- pkg/controllers/user/logging/deployer/upgradeimpl_test.go
- pkg/controllers/user/pipeline/upgrade/upgradeimpl.go
- pkg/controllers/user/systemimage/register.go
- pkg/controllers/user/systemimage/systemimage.go
- pkg/controllers/user/systemimage/upgrader.go
Problem:
only one cluster system server upgrade success when there are multiple
cluster
Solution:
this cause by only one alert/logging/pipeline upgradeService was init,
when there are multiple cluster, the former clusterName will be
overwrite by the laster one. Now change handle multiple cluster when
init upgradeService
Issue:
https://github.com/rancher/rancher/issues/21455
https://github.com/rancher/rancher/issues/21323
https://github.com/rancher/rancher/issues/20975
> fix upgrade system image failed when manage multiple clusters

- tests/integration/suite/test_istio.py
Address issue: https://github.com/rancher/rancher/issues/21492
Problem:
Tests fail when istio tests are distributed to different workers. Module-scope fixtures/teardown can run multiple times in this case, causing race condition that the 1st test may clean up istio CRDs while the
2nd test is running.
Solution:
Run istio API tests in nonparallel.
> Fix istio integration tests

- pkg/controllers/management/globalnamespacerbac/rbac_common.go
- tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/21401
If a clustertemplate was shared with a user giving "member" access, a rolebinding
was getting created with role containing "update" verb for that user. If the access
type was then switched to read-only, user still had update access. This is because
the rbac controller wasn't handling the case when there were no longer any members
for a particular access type
> Addresses a bug in updating rolebindings for clustertemplate

- pkg/api/store/clustertemplate/store.go
- tests/integration/suite/test_clustertemplate.py
Instead of checking for rolebindings, we can use CanDo to check user's
access to the clusterTemplate with "update" verb. If that's not allowed
then creation of revision for that clusterTemplate shouldn't be allowed either.
This also does group membership based access check.
https://github.com/rancher/rancher/issues/21501
> Change logic to check permissions to create clustertemplate revision

- pkg/controllers/user/helm/common.go
Problem:
The helm jail is based off the app name so if multiple apps with the
same name come through the jail can get deleted out from under other
running processes
Solution:
Make the jail name unique
https://github.com/rancher/rancher/issues/21449
#21455
#21323
#20975
> Make helm jail name unique master

- app/machinedriver_data.go
- pkg/api/customization/nodetemplate/validation.go
Creates a cloud credential for use by the Linode node driver.
Related to https://github.com/rancher/ui/pull/2834, and https://github.com/linode/rancher-ui-driver-linode/pull/7
After https://github.com/linode/rancher-ui-driver-linode/pull/7 is merged, the updated/released component.js should be [referenced](https://github.com/rancher/rancher/pull/20281/files#diff-3dda985564938bb62acd5b2d96e45aa0R58) in this PR.
> add linode driver data for cloud credentials

- pkg/api/customization/clustertemplate/utils.go
- pkg/api/store/cluster/cluster_store.go
- pkg/api/store/clustertemplate/store.go
- tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/21084
New changes to this ticket:
---- If a template specifies Kubernetes version of the format 1.14.x, a Question for the "rancherKubernetesEngineConfig.kubernetesVersion" should also be set - API will error out if a question is not added. 
---- When a cluster is created from a clusterTemplate that specifies the k8sversion of a format 1.14.x
backend will translate this to rancher supported kubernetes version on the create. If user does not provide an answer to the k8sversion Template Question, Backend will use the default value for translation.
---- On editing such a cluster, If the answer to the k8sversion Template Question is not different, no translation will be done again. This prevents the auto-upgrade to newer version as was seen on earlier …
> DeriveKubernetesVersion from the generic major.minor.patch

- pkg/controllers/user/monitoring/metricExpression.go
**Problem:**
Cluster level graph `Disk Utilization` is not the same as grafana's
graph.
**Solution:**
Modify our metrics expression.
Related issue:
https://github.com/rancher/rancher/issues/21254
> Keep metrics graph consistancy

- pkg/api/server/managementstored/setup.go
- pkg/features/feature.go
Example feature, and its assignment to kontainerdriver was intended for demonstrations and testing. It is being taken out as it does not serve a purpose.
> Remove example feature

- app/machinedriver_data.go
This reverts commit 4dc6f7c9fcb92c65fa9acf758ed9bc49e18096b0.
> Revert "mark linode active by default"

- pkg/api/customization/monitor/cluster_graph_action.go
- pkg/api/customization/monitor/project_graph_action.go
- pkg/monitoring/monitoring.go
Problem:
Istio should get metrics from cluster Prometheus when chose to re-use cluster monitoring.
Solution:
Add re-use cluster-monitoring to istio metrics
Related Issues:
https://github.com/rancher/rancher/issues/21545
> Add re-use cluster-monitoring to istio metrics

- package/jailer.sh
Problem:
Additional certs passed to rancher are not pulled into the jail
Solution:
Pull in optional rancher cert files to stop issues with self signed and
internal CAs
Issue: https://github.com/rancher/rancher/issues/21306
> Pull in certs to jail

- pkg/kubeconfig/templates.go
Currently the user name is always the same for every config you generate
(`u-xxxxx`), so the kubeconfigs for 2 clusters cannot be merged together.
Instead, Generate kubeconfigs with the User, Context, and Cluster name all
set to the cluster `name`, so that the configs of any two clusters (with
different names...) can be merged together successfully by kubectl.
> Use ClusterName for KubeConfig User's name

- pkg/controllers/user/logging/configsyncer/configsyncer.go
- pkg/controllers/user/logging/generator/templatematch.go
- pkg/controllers/user/logging/utils/fluentd.go
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_logging.py
Problem:
advance mode have support client key and certificate for fluentd logging
target but normal mode not yet
Solution:
add client key and certificate for fluentd
types:
https://github.com/rancher/types/pull/739
Issue:
https://github.com/rancher/rancher/issues/18438
Integration test pr:
https://github.com/rancher/validation/pull/161
> [Logging] add client key and certificate for logging fluentd

- package/jailer.sh
Problem:
Additional certs passed to rancher are not pulled into the jail
Solution:
Pull in optional rancher cert files to stop issues with self signed and
internal CAs
Issue: https://github.com/rancher/rancher/issues/21731
> Pull in certs to jail v2.1

- package/jailer.sh
Problem:
Additional certs passed to rancher are not pulled into the jail
Solution:
Pull in optional rancher cert files to stop issues with self signed and
internal CAs
Issue: https://github.com/rancher/rancher/issues/21729
> Pull in certs to jail - v2.2

- pkg/api/customization/cluster/actions_monitoring.go
- pkg/api/customization/project/project_actions.go
- pkg/catalog/manager/traverse.go
- pkg/catalog/utils/utils.go
- pkg/controllers/user/alert/deployer/upgradeimpl.go
- pkg/controllers/user/helm/common/extra_args_injection.go
- pkg/controllers/user/istio/appHandler.go
- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/monitoring/appHandler.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
- pkg/controllers/user/monitoring/register.go
- pkg/controllers/user/systemimage/systemimage.go
- pkg/monitoring/monitoring.go
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_monitoring_input.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_monitoring_output.go
**Problem:**
monitoring version is currently hardcoded in rancher server code.
Monitoring API should allow UI to pass the monitoring version to the backend.
**Solution:**
Add support to accept monitoring version in Rancher api
https://github.com/rancher/types/pull/909
**Issue:**
rancher#21460
> Add support to select monitoring version on deployment

- pkg/api/server/userstored/setup.go
- pkg/api/store/nocondition/store.go
- tests/integration/suite/test_hpa.py
**Problem:**
The hpa object needs conditions to indicate the state,
if there are not any, we should set it to initializing.
Related issue:
https://github.com/rancher/rancher/issues/20955
Related PR:
https://github.com/rancher/types/pull/907
> Don't set active state to newly created HPA

- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/common/common_test.go
Problem:
Values containing commas result in an installation error. This is due to helm using commas as a delimiter.
Solution:
Values that are not arrays may contain commas and they will be passed to helm in an acceptable form.
Issue:
https://github.com/rancher/rancher/issues/19737
> Escape commas in chart values

- pkg/systemtemplate/template.go
The previous permissions defaulted to 644. The permissions are now
500 (octal) which is 320 in decimal.
P.S. When modifying defaultMode use decimal always to avoid conversion
errors. chmod 500 -> defaultMode: 320
> Change permissions on cluster and node agent

- chart/templates/_helpers.tpl
- chart/templates/ingress.yaml
- chart/tests/ingress_test.yaml
- chart/values.yaml
Current behavior if you set a `configurationSnippet` that is more than one line does not respect indentation for any line after the first one:
```
annotations:
nginx.ingress.kubernetes.io/configuration-snippet: |
more_set_input_headers "foo: bar";
more_set_input_headers "bar: baz";
```
This PR fixes the helm templating so that the lines are indented properly.
```
annotations:
nginx.ingress.kubernetes.io/configuration-snippet: |
more_set_input_headers "foo: bar";
more_set_input_headers "bar: baz";
```
> fix for multiline configurationSnippet

- pkg/controllers/management/auth/crtb_handler.go
- pkg/controllers/management/auth/manager.go
- pkg/controllers/management/auth/prtb_handler.go
- tests/integration/suite/test_role_template.py
The auth controller creates rolebindings for a project member in the
project's cluster's namespace along with those in project's namespaces.
The rolebinding in cluster's ns, is either projectmember or projectowner,
depending on the prtb's roleTemplateName. This doesn't take into consideration
the inherited/cloned roles. This commit gets the parent builtin role
and creates projectmember or projectowner rb accordingly.
Same for cluster rb
https://github.com/rancher/rancher/issues/21355
The check against circular roles while getting parent roles recursively needs to be done at api level. We should disallow adding project/cluster members with roles that have circular reference here pkg/api/customization/roletemplatebinding/validator.go
Not adding this check in the controller logic, because by …
> Check inherited role for project/cluster member

- pkg/api/store/node/store.go
- pkg/controllers/management/node/controller.go
- pkg/controllers/user/nodesyncer/nodetaints.go
- pkg/taints/utils.go
**Problem:**
The node taints won't be set if there have duplicated taints in
node template and node pool.
**Solution:**
For the new node from node pool, the taints with same key and template
will respect the one from the node pool. The other taints from the node
template will be added to newly create node.
https://github.com/rancher/rancher/issues/13972
> Fix node taints not showing

- pkg/controllers/user/controllers.go
The linux node taints controller for Windows k8s cluster is not added in user controller. Fix it.
Issue
https://github.com/rancher/rancher/issues/20805
> Add windows node taint controller

- pkg/auth/providers/googleoauth/goauth_helper.go
- pkg/auth/providers/googleoauth/goauth_provider.go
https://github.com/rancher/rancher/issues/21412
This commit validates the hostname provided while configuring google oauth. When the test user logs into their google account, we get the hostname as one of the attributes of that user. So this commit checks that the hostname from user's attributes matches the hostname provided in the authconfig.
> Add hostname validation for google oauth

- pkg/controllers/management/auth/crtb_handler.go
- tests/integration/suite/test_etcdbackups.py
https://github.com/rancher/rancher/issues/20911
Although etcdbackups are scoped to a cluster, they are rancher mgmt resources,
and need to be added to the `clusterManagmentPlaneResources` list. The crtb_handler.go
ensures all cluster members get access to resources in this list by creating
role bindings.
The "user" global role has get/list/watch permissions on etcdbackups, so cluster
members with 'user" role don't need this and will be able to see etcdbackups
even without this resource being in the `clusterManagmentPlaneResources` list.
But any user having "user-base" global role or created with any custom permissions
will require this change so they can see the etcdbackups in their cluster.
> Create rolebindings for etcdbackups in cluster's ns

- pkg/websocket/handler.go
- pkg/websocket/handler_test.go
- tests/integration/suite/test_tokens.py
Problem:
Non-browser clients are not able to make websocket requests. This prevents clients from making such requests, like watching pods.
Solution
Rancher no longer performs origin check on websocket connections that are not from a browser. Now, clients with non-matching origins are permitted to make a request, as long as they are not
from a browser.
Issue:
https://github.com/rancher/rancher/issues/21777
> Only perform origin check on browser connections

- pkg/websocket/handler.go
- pkg/websocket/handler_test.go
- tests/integration/suite/test_tokens.py
Backport issue: https://github.com/rancher/rancher/issues/21940
Original PR: https://github.com/rancher/rancher/pull/21917
> Backport (2.2): Only perform origin check on browser connections

- pkg/catalog/helm/helm.go
Problem: The icon url was not returned to the template so the template
would not display icons for charts with remote icons.
Solution: Do not fetch the icon but still return the url of the icon
to the template.
> Return the icon url to the template to display in the UI

- pkg/api/customization/catalog/template.go
- pkg/catalog/helm/helm.go
Problem: The icon url was not returned to the template so the template
would not display icons for charts with remote icons.
Solution: Do not fetch the icon but still return the url of the icon
to the template
> [2.2] Return the icon url to the template to display in the UI

- pkg/websocket/handler.go
- pkg/websocket/handler_test.go
- tests/integration/suite/test_tokens.py
Backport issue: https://github.com/rancher/rancher/issues/21945
Original PR: https://github.com/rancher/rancher/pull/21917
> Backport (2.1): Only perform origin check on browser connections

- pkg/api/customization/catalog/template.go
- pkg/api/customization/catalog/template_test.go
- pkg/api/server/managementstored/setup.go
If the chart has been added previously then the url of the icon will
not be included in the iconFilename. Instead of defaulting to serving
the icons, check if they have a url for the icon in the chart. If they
do, proceed to send the url to the UI and do not serve the icon data.
> Handle upgrades with previously added charts

- pkg/features/feature.go
Problem:
An error is logged if user did not use features run flag. Now, an error will not be logged as no input is valid.
Solution:
Do not attempt to parse features flag if it is empty.
Issue:
https://github.com/rancher/rancher/issues/21321
> Do not parse empty features run flag

- pkg/controllers/user/alert/controller.go
Address issue: https://github.com/rancher/rancher/issues/21127
Problem:
When notifiers are updated, configurations of alert-manager are not
synced.
Solution:
Sync configs on notifier updates
We used to do the sync in [v2.1](https://github.com/rancher/rancher/blob/release/v2.1/pkg/controllers/user/alert/controller.go#L39). This is probably a regression if it is not intentionally dropped.
> Add notifier-config-syncer

- pkg/controllers/management/nodepool/nodepool.go
- pkg/controllers/management/nodepool/sort.go
- pkg/controllers/management/nodepool/sort_test.go
Problem: Rancher would remove "node9" instead of "node10" when decreasing
nodepool size. This was due to the alphabetical sorting of nodepool names.
Solution: Implement natural sort of nodepool names.
Addresses: https://github.com/rancher/rancher/issues/19431
> Implement natural sort for nodepools

- pkg/controllers/user/alert/deployer/notification_template.go
- pkg/controllers/user/alert/manager/prometheus_operator.go
Problem:
Now we only support compare condition and the threshold for metric alert
Solution:
Add exist condition for metric alert
Issue:
https://github.com/rancher/rancher/issues/21302
Types:
https://github.com/rancher/types/pull/914
> Support exist condition for metric alert

- package/jailer.sh
Problem:
Jailer script was verifing the cert existed so if cert is a dir cp will
fail
Solution:
Validate cert is a file before attempting to copy
Issue: https://github.com/rancher/rancher/issues/22068
> Check if cert is a file before copy

- chart/templates/deployment.yaml
- chart/tests/deployment_test.yaml
- Fixes #20573 
- Check for `.Values.tls == ingress` in addition to `Values.ingress.tls.source == "rancher"` when determining if self-signed should be used
> Helm Chart: Default to Pulbic certs when `--set tls=external`

- app/role_data.go
- pkg/api/customization/cluster/actionhandler.go
- tests/integration/suite/test_etcdbackups.py
This commit removes get/list/watch permissions on etcdbackups that "user"
globalRole had. Because this was also granting project members access to backups.
Also this commit checks if user has "create" permission for etcdbackup for the
backupEtcd actionHandler. Till now it checked if user has the permission to "update"
the cluster. Users added with "backups-manage" role won't have rights to update clusters,
hence won't be able to create etcdbackups either in spite of being granted this role.
This issue is resolved by checking for permissions on etcdbackups instead
https://github.com/rancher/rancher/issues/20911#issuecomment-518332555
> RBAC changes for etcdbackups

- pkg/api/customization/cluster/actions_yaml.go
- pkg/api/customization/cluster/formatter.go
- tests/integration/suite/test_cluster_defaults.py
Problem:
Some clusters don't support being exported so an unusable config is
being returned
Solution:
Add an error message and remove export link from non-RKE clusters
Issue: https://github.com/rancher/rancher/issues/21309
> Only allow cluster export on RKE

- package/Dockerfile
Bump Linode driver UI version to v0.3.0
https://github.com/rancher/rancher/issues/21601
https://github.com/rancher/rancher/issues/21652
> Bump Linode driver UI version to v0.3.0

- pkg/auth/providers/googleoauth/goauth_provider.go
https://github.com/rancher/rancher/issues/21409
Providing better error message for when service account credential is invalid.
The GH issue asks to do the same in case of admin email as well. But admin email is validated only when fetching user's groups during login. And in that case the golang admin library we use returns only an error string, and the error could have been due to multiple reasons at that point.
> Provide better error msg for google auth

- pkg/api/customization/roletemplate/roletemplate.go
- pkg/api/customization/roletemplate/roletemplate_test.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/roletemplate/store.go
- pkg/api/store/roletemplate/store_test.go
Problem:
Roletemplate can be delete even if another roletemplate inherits from it.
Solution:
Check whether another roletemplate inherits from roletemplate being deleted and return error if so.
Issue:
https://github.com/rancher/rancher/issues/19133
> Disable delete parent

- pkg/api/customization/cluster/actionhandler.go
- pkg/api/customization/cluster/shell.go
- pkg/auth/providers/common/usermanager.go
- pkg/auth/tokens/manager.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- pkg/controllers/management/compose/controller.go
- pkg/controllers/user/helm/controller.go
- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
- pkg/systemaccount/systemaccount.go
- pkg/telemetry/telemetry.go
- tests/integration/suite/test_auth_configs.py
- vendor.conf
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/tools_system_images.go
- vendor/github.com/rancher/types/user/manager.go
**Depends on:** Types PR: https://github.com/rancher/types/pull/940
Adds a label to Rancher management created tokens to help categorize them. Examples: 
```
Helm token: "authn.management.cattle.io/kind": "helm",
Telemetry token: "authn.management.cattle.io/kind": "telemetry",
User login: "authn.management.cattle.io/kind": "session",
```
Note
* Won't add labels to user (custom) tokens. 
* Won't add labels for existing tokens.
> Label tokens

- pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go
- pkg/controllers/user/pipeline/upgrade/upgradeimpl.go
- pkg/pipeline/engine/jenkins/engine.go
https://github.com/rancher/rancher/issues/19322
https://github.com/rancher/rancher/issues/18526
1. Adapt to newer Jenkins 2.164
- Sync timeout steps in ABORTED status
- Add hudson.model.UpdateCenter.never=true option
2. Implement pipeline components upgrade
Depend on:
types PR: https://github.com/rancher/types/pull/897
newer Jenkins image release: https://github.com/rancher/pipeline-jenkins-server/pull/3
> Pipeline components upgrade

- pkg/controllers/management/auth/project_cluster_handler.go
- pkg/controllers/management/auth/project_cluster_handler_test.go
https://github.com/rancher/rancher/issues/19589
https://github.com/rancher/rancher/issues/15819
Problem: Users added as cluster-owners cannot create apps/add members in projects added to the
cluster after they have been made cluster-owners
Cause: The crtb controller lists all existing projects and creates rolebindings
in each project for the current crtb's user. So cluster-owners get access to resources
under `projectManagmentPlaneResources` for projects that exist already in the cluster when
they are being added. The same sync needs to happen on adding a new project to the cluster
as well which wasn't happening.
Fix: On project sync, enqueue clusterroletemplatebindings of that project's cluster.
> Trigger crtb controller on project creation

- pkg/api/customization/cluster/formatter.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/cluster/cluster_store.go
- tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/21519
Answers to Questions set on ClusterTemplate are stored on the Cluster Spec when user creates the cluster with answers. If the properties set as answers are password/secret fields, we should not display such answers on API.
> Hide clustertemplate answers on clusterspec 

- package/Dockerfile.agent
- package/run.sh
To allow using custom uid/gid for etcd, we use ACLs to grant the etcd user read permissions to the certificates directory. The `chmod` this PR replaces deletes these ACLs when the node agent is switched from a container to a pod. The new function re-applies the needed acls if they where already set.
> Fix directory permissions override

- pkg/controllers/user/alert/deployer/upgradeimpl.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
Problem:
After version v1 release for deployment, statefulset, daemonset, there is some compatibility issue, like updates to deployment/statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden. So upgrade chart may get failed.
Solution:
Add force upgrade for system app
Issue:
https://github.com/rancher/rancher/issues/21770
Related Charts PR:
https://github.com/rancher/system-charts/pull/78
> Add force upgrade for system apps

- app/cluster_data.go
- pkg/controllers/user/logging/deployer/deployer.go
- pkg/settings/setting.go
Problem:
In HA installed rancher, local cluster is created by backend, not UI, field dockerRootDir may have an empty value
Solution:
Check dockerRootDir one more time when enable logging
Issue:
https://github.com/rancher/rancher/issues/21112
> Handling HA install rancher local cluster may has empty value for field dockerRootDir

- pkg/pipeline/remote/bitbucketcloud/client.go
- pkg/pipeline/remote/bitbucketserver/client.go
- pkg/pipeline/remote/github/github.go
- pkg/pipeline/remote/gitlab/gitlab.go
Address issue: https://github.com/rancher/rancher/issues/20191
Problem:
Fetching repos results in HTTP client timeout when the number is large. The cause is that paginated responses are held and not proceeded until all of them are available.
Solution:
Proceed paginated response body early.
This pr also update the HTTP client timeout to 30s to have proper tolerance to high latency network.
> Fix pipeline repos timeout

- tests/integration/suite/test_clustertemplate.py
@alena1108 @cjellick 
adding a global role to a user - then trying an operation depending on that role from the test fails intermittently - the globalrole binding does reflect on the user crd always quickly
we even try to wait for a while - but it just fails randomly. Will try to debug this separately.
> Fix flaky test for clustertemplate global role assignment

- app/catalog_data.go
- package/Dockerfile
- pkg/catalog/helm/helm.go
- pkg/catalog/helm/setup.go
- pkg/catalog/manager/catalog_sync.go
- pkg/catalog/manager/manager.go
- pkg/settings/setting.go
This adds a new setting `system-catalog` which changes the source of the catalogs. The two options are `bundled` and `external` with a default of `external`. If set to `bundled` the two rancher catalogs will only use the bundled version of the catalog from the build and will not attempt to fetch from the internet. If set to `bundled` the normal catalog will be disable by default but can be turned back on. This is to stop people from trying to install apps when the image may not be available to install. 
In order to update a catalog a new one could be copied in (not ideal) or the version of rancher updated in which case a new version could potentially be in the build. 
Issue: https://github.com/rancher/rancher/issues/20387
> Package catalog into build

- pkg/api/customization/setting/setting.go
- tests/integration/suite/test_settings.py
https://github.com/rancher/rancher/issues/20467
Remove update link on settings if user doesn't have update permissions. Without this commit, API still throws a 403 when regular user tries to update global settings. But with this fix the update link won't show in UI
> Set "update" link on setting based on user permissions

- .drone.yml
Agent image had the wrong version because of this mistake.
It is working correctly on v2.2 branch and this brings the two in line.
> Fix version for publishing

- pkg/controllers/user/alert/deployer/upgradeimpl.go
Problem:
Because we change controller name since 2.2, when delete project included legacy projectAlert obj, it will stuck in getting legacy finalizer
Solution:
Remove legacy finalizer when upgrade alert
Issue:
https://github.com/rancher/rancher/issues/22231
> Removed legacy finalizer when upgrade alert

- chart/templates/deployment.yaml
- chart/tests/deployment_test.yaml
- chart/values.yaml
**Issue:**
users should be able to configure the private registry directly when they install Rancher, instead of having to use an environment variable.
**Solution:**
Allow Rancher chart to config private registry directly using `global. systemDefaultRegistry `.
#22014
> Allow rancher chart to config private registry

- pkg/controllers/management/node/controller.go
- pkg/taints/utils.go
Not only set v3.Node.Spec.DesiredNodeTaints but also set
obj.Status.NodeConfig.Taints. So RKE will generate taints to node
after node is provisioned.
https://github.com/rancher/rancher/issues/21577
> Add taints to rke config node for new node

- pkg/controllers/management/drivers/nodedriver/machine_driver.go
- pkg/controllers/management/node/controller.go
- tests/integration/suite/test_node.py
Problem:
When using a nodetemplate and passing in file info, that file that gets
created has a hashed name which ends up coming out in the downloaded
keys for a node
Solution:
Use the hash to create the dir and name the file as related to the field
on the driver
https://github.com/rancher/rancher/issues/20576
> Update naming of files for node drivers

- app/app.go
- app/user_cleanup.go
- pkg/controllers/management/auth/project_cluster_handler.go
- pkg/controllers/user/pipeline/controller/project/project.go
- pkg/systemaccount/systemaccount.go
https://github.com/rancher/rancher/issues/19018
A system user account is created for every cluster and project.
2.2.3 and prior versions did not delete these accounts when their clusters
or projects were deleted. 2.2.4 has the fix to delete these system users.
But the system users left behind from cluster/project deletion prior to 2.2.4
need to be cleaned up. This only needs to be done once on startup.
>  Remove orphaned system account users

- package/windows/execute.ps1
**Problem:**
Windows file system doesn't allow path with colons
**Solution:**
Replace the colons with blank, details from:
https://github.com/moby/moby/issues/21189#issuecomment-234997515
**Issue:**
https://github.com/rancher/rancher/issues/22438
> Fix Windows worker adding failure

- pkg/controllers/management/node/controller.go
- pkg/controllers/management/nodepool/nodepool.go
- pkg/controllers/user/nodesyncer/nodetaints_test.go
- pkg/controllers/user/windows/linux_node_taints.go
- pkg/controllers/user/windows/node_test.go
- pkg/controllers/user/windows/register.go
- pkg/taints/utils.go
**Problem:**
Node taints syncer will remove `node-role.kubernetes.io/etcd` and
`node-role.kubernetes.io/controlplane` taints. It is because we set
taints both in RKE and Rancher side and the Rancher side will override
those taints added by RKE
**Solution:**
- Apply taints from node pool and node template to RKE config node so RKE
will add them when generating node.
- Linux node taints controller for Windows cluster add our taints to v1.Node
directly so we don't need to reuse the taints syncer logic of v3.Node.
Related issue:
https://github.com/rancher/rancher/issues/20805
> Fix system taints missing

- go.mod
- go.sum
- vendor/k8s.io/client-go/tools/cache/shared_informer.go
- vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
- vendor/k8s.io/client-go/transport/token_source.go
- vendor/modules.txt
There was two patches to client-go that were in k3s that Rancher
relied on.  Including those back.
> Use rancher fork of client-go for proxy issues

- go.mod
- go.sum
- pkg/api/customization/nodepool/formatter.go
- pkg/api/server/managementstored/setup.go
- tests/integration/suite/test_node.py
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_node_pool.go
- vendor/modules.txt
Issue: https://github.com/rancher/rancher/issues/22080
Types PR: https://github.com/rancher/types/pull/971
Adds a virtual field (not stored in db) to the nodepool resource via formatter that identifies the driver type (string). 
Hit `/v3/schemas/nodePool` to see schema
Hit `/v3/nodePool` to see resources
Schema
Resource
> Add driver type to nodePool resources

- app/setting.go
- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/controllers/management/kontainerdrivermetadata/data.go
- pkg/settings/setting.go
removing content in `app/setting.go` because this logic is already covered when metadata gets loaded and settings get updated. 
https://github.com/rancher/rancher/issues/21695
> add support for deprecating k8s versions

- pkg/controllers/user/alert/controller.go
- pkg/controllers/user/alert/initdata.go
Problem:
Window cpu don't have system mode, so can use system mode to count the cpu cores, and windows file system is different
Solution:
Improve cpu load alert and add extra windows file alert
Issue:
https://github.com/rancher/rancher/issues/20122
> Improve alert expression to work for linux and windows

- pkg/api/server/userstored/setup.go
- pkg/api/store/hpa/store.go
**Problem:**
HPA with cpu rules for newly created workload will get
`transitioning=error` because the HPA controller can't get the cpu
metrics for newly created workload.
**Solutions:**
Ignore the transitioning error for the first 60s after HPA has been
created.
Related issue:
https://github.com/rancher/rancher/issues/20955
> Ignore the first 60s error for HPA object

- pkg/controllers/management/globalnamespacerbac/rbac_common.go
The global ns rbac controller calls DeepEqual on the entire Role and
RoleBinding objects, this can cause continuous updates since some fields
such as CreationTimestamp have to be different. This commit calls DeepEqual
only on Subjects of RoleBinding, and on Rules in case of Roles.
> Call DeepEqual on select object fields

- pkg/controllers/management/node/controller.go
- pkg/rkenodeconfigserver/nodeserver.go
- pkg/rkenodeconfigserver/nodeserver_test.go
- pkg/taints/utils.go
- pkg/taints/utils_test.go
**Problem:**
Setting node pool taints and node template taints doesn't work.
**Solution:**
Add kubelet args `--register-with-taints` parameters to kubelet worker
process. So those taints will be added after kubelet is up and running.
Related issue:
https://github.com/rancher/rancher/issues/22513
> Fix worker taints not applied

- pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
Address issue: https://github.com/rancher/rancher/issues/22591
Problem:
When multiple recipients are configured in pipeline notification, one of
them get notified multiple times.
Solution:
Avoid using loop iterator variable in go routines.
> Fix notifying multiple recipients in pipeline

- pkg/settings/setting.go
**Issue:**
Create a GDNS provider, the 0.0.1 version of the rancher-external-dns being used.
**Solution:**
Update the global external-dns default to system-chart v0.0.2
Related Issue:
https://github.com/rancher/rancher/issues/21768
> Update global external-dns default to system-chart 0.0.2

- pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/19179
Problem: service-sidekick was being every plan execution, docker containers were started while already running and because of that, log-linker was run for every container that was started while it was already running
Root cause: service-sidekick was not excluded from plan execution (should be similar to share-mnt which is excluded), and there is no check for containers already running
Solution: exclude service-sidekick from being checked besides being present, check container is running before starting + running log linker, exclude service-sidekick from running log-linker
> Reduce Docker actions on workers

- pkg/api/server/managementstored/setup.go
- pkg/api/store/globalrolebindings/globalrolebinding_store.go
- pkg/api/store/roletemplate/store.go
- pkg/controllers/user/rbac/legacy_grb_cleaner.go
- pkg/controllers/user/rbac/legacy_rt_cleaner.go
- tests/integration/suite/test_users.py
Previously, this only removed finalizers from deleted grbs with a 1 hour delay.
This meant that when a user had their admin access removed it would take one hour for
the change to propogate if they had a finalizer to a non-existent cluster in their list of finalizers.
Now, we premptively remove "bad" finalziers from grbs that point to non-existent clusters so that on
change they will not need to be cleaned. This only occurs for grbs with a creation timestamp greater than
one hour to prevent interference with normal handler operations.
Similar to: https://github.com/rancher/rancher/pull/22338
Addresses: https://github.com/rancher/rancher/issues/22486
> Cleanup legacy globalrolebindings finalizers to deleted clusters

- pkg/catalog/utils/version.go
- pkg/catalog/utils/version_test.go
- pkg/controllers/user/alert/deployer/deployer.go
- pkg/controllers/user/alert/deployer/upgradeimpl.go
- pkg/controllers/user/helm/common/extra_args_test.go
- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/logging/deployer/deployer.go
- pkg/controllers/user/logging/deployer/upgradeimpl.go
- pkg/controllers/user/logging/deployer/upgradeimpl_test.go
- pkg/monitoring/monitoring.go
- pkg/settings/setting.go
Problem:
When we deploy alerting, we are using the monitoring catalog setting to decide which version we should deploy. We should use the latest version (limited by rancher min and max version) instead of hard code version in Rancher server.
Solution:
Remove monitoring catalog from setting and remove legacy code
Issue:
https://github.com/rancher/rancher/issues/22615
> Remove monitoring and logging catalog id setting

- pkg/controllers/user/alert/initdata.go
Problem:
After monitoring charts upgraded, this expression value change from no data point to 0
Solution:
Update the thredshold for this expression
Issue:
https://github.com/rancher/rancher/issues/22680
> Improve alert linux node disk running full expression

- pkg/controllers/user/alert/initdata.go
Problem:
Sometimes get etcd unhealth alert, but may cause by network or disk problem, actually etcd is health
Solution:
Improve group wait seconds to 10 mins as issue mentioned
Issue:
https://github.com/rancher/rancher/issues/19474
> Increase etcd system servce alert groupt wait seconds

- pkg/image/export/main.go
**Problem:**
If the tag variable is treated as float or int, we won't include
that image in our image list.
**Solution:**
Don't parse tag to string.
Related issue:
https://github.com/rancher/rancher/issues/22553
> Image missing in image.txt if tag is float type

- pkg/controllers/user/logging/generator/generator.go
Problem:
unsorted namespace cause useless configure update and reload
Solution:
sort namespace
Issue:
https://github.com/rancher/rancher/issues/22721
> sort grep namespace list for project logging

- pkg/controllers/management/kontainerdrivermetadata/data_getter.go
**Problem:**
Since we wrapped the name of service options with `w` twice, it was impossible to get the correct service options for Windows worker
**Solution:**
Drop the latest wrapping
> Fixed the duplicate wrapping Windows service options

- pkg/controllers/user/alert/initdata.go
**Problem:**
`node_filesystem_files_free` returns the free inodes numbers, not free disk size.
**Solution:**
Using `node_filesystem_free_bytes` instead of `node_filesystem_files_free`.
**Issue**:
https://github.com/rancher/rancher/issues/22680
> Improve linux alert expression

- app/role_data.go
- tests/integration/suite/test_clustertemplate.py
- Changing the global role name to say "Create RKE Templates" https://github.com/rancher/rancher/issues/22805
- Fix for flaky test issue https://github.com/rancher/rancher/issues/22735
> Role name changed to RKE templates and flaky test fixes

- pkg/controllers/management/kontainerdrivermetadata/data_getter.go
service options are now passed to generatePlan which happens very often,
logging it in debug and only when svcOption is passed
> change log level for getRKEServiceOption

- pkg/api/customization/logging/action.go
- pkg/controllers/user/logging/deployer/appdeployer.go
- pkg/controllers/user/logging/deployer/appdeployer_test.go
- pkg/controllers/user/logging/deployer/deployer.go
- pkg/controllers/user/logging/deployer/testerdeployer.go
Problem:
Enable logging in a PSP restricted cluster. Check that logging app is deployed but no fluentd pods are deployed due to PSP limitation, disable logging, and notice that the logging app is not removed.
Solution:
This is cause by wrong use of rancher.ticker, when the timeout, the ticker get stop, but the ticker channel isn't close cause loop
Issue:
https://github.com/rancher/rancher/issues/22797
> Improve logic for checking logging app deploy success

- pkg/api/customization/catalog/catalog.go
- pkg/api/customization/catalog/validator.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/catalog/store.go
- tests/integration/suite/test_catalog.py
Problem:
Prior, system-catalog was hidden to prevent these actions. This prevented user from viewing errors with system-catalog. Prior to that, user was able to delete system-catalog which could be dangerous.
Solution:
Allow user to view system catalog, but prevent them from deleting it.
Issue:
https://github.com/rancher/rancher/issues/22771
Related Issue:
https://github.com/rancher/rancher/issues/22490
> Disable removing system-catalog

- pkg/systemtemplate/template.go
Related issue:
https://github.com/rancher/rancher/issues/22857
> node agent windows should tolerate all taints

- chart/templates/deployment.yaml
- chart/tests/deployment_test.yaml
- chart/values.yaml
**Issue:**
Allow rancher chart to config bundled system-charts
https://github.com/rancher/rancher/issues/22823
> Allow rancher chart to config bundled system-charts

- pkg/image/export/main.go
quiet wasn't supported in < docker 19 so added redirect output instead and the $pulled param wasn't being filled the second run of the command so added logic to inspect and added the image to the tar.gz even if it was already pulled.
> removed --quiet for > /dev/null, logic to rerun command

- pkg/api/store/clustertemplate/store.go
- tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/22943
Instead of using the access.List to list the clusters using a given template/revision; we should rely on listers - since access.List would return only the results based on what the user can access/see.
> Use lister to list the clusters that are using a clustertemplate

- pkg/features/feature.go
For UI feature to toggle showing storage drivers that are not commercially supported
> Unsupported storage & network drivers feature flag

- pkg/api/customization/feature/feature.go
- pkg/api/server/managementstored/setup.go
Problem:
Value may be empty despite have a default value. This could lead to confusion.
Solution:
Assign default value to value field in feature GET responses.
Issue:
https://github.com/rancher/rancher/issues/22895
> Assign default to value if nil

- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/clusterprovisioner/provisioner.go
- tests/integration/suite/test_cluster_defaults.py
- tests/integration/suite/test_clustertemplate.py
should return deprecated err only on cluster edits by user, not
on every sync which would cause clusters to be in a
failed updating state
https://github.com/rancher/rancher/issues/21695
> move isDeprecatedCheck from controller to store

- pkg/api/customization/clusterregistrationtokens/formatter.go
- pkg/api/customization/clusterregistrationtokens/formatter_test.go
Patch the `AGENT_IMAGE` env back to the command when the setting side
agent image isn't equal to the resolved side.
**Issue:**
https://github.com/rancher/rancher/issues/23040
> Fix generating incomplete Windows command in air-gapped

- package/windows/execute.ps1
**Problem:**
the Powershell of `1903` has changed from `v5.1` to `v6.0`, and then `Set-Content` hasn't supported `Bytes` as an encoding type:
- v5.1:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-5.1#parameters
- v6.0:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-6#parameters
**Solution:**
Import the certificate after converting the bytes to string
**Issue:**
Reopen: https://github.com/rancher/rancher/issues/20436
> Patch supported intermediary certificates for Windows 1903

- pkg/controllers/user/helm/common/common.go
Problem:
Tiller can get stuck when an upgrade fails and we don't have any
versions to get back to
Solution:
Up the history count so tiller can find one that deployed successfully
to rollback to
https://github.com/rancher/rancher/issues/21070
> Turn it up to 10 TILLER_HISTORY_MAX

- tests/validation/lib/node.py
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/scripts/nfs-setup.sh
- tests/validation/tests/v3_api/test_nfs.py
An NFS server will be deployed in AWS for testing Persistent Volumes and Persistent Volume Claims.
A new configurable variable `RANCHER_DELETE_NFS` is introduced. The NFS server will be deleted automatically if `RANCHER_DELETE_NFS` is set to `True`, or be kept if `RANCHER_DELETE_NFS` is set to `False`
> provision  a NFS server when running tests for PV and PVC

- pkg/features/feature.go
Issue:
Virtual Service UI support is hidden.
Instead of removing it, we can use feature flag to turn it off. 
Users can turn it on if they want.
https://github.com/rancher/rancher/issues/23137
> Istio virtual service UI feature flag

- pkg/controllers/management/auth/legacy_grb_cleaner.go
- pkg/controllers/management/auth/legacy_rt_cleaner.go
- pkg/controllers/management/auth/register.go
- pkg/controllers/user/rbac/handler_base.go
Two handlers were incorrectly added to the user context instead
of the management context. These handlers are for mgmt plane resources:
globalRoleBinding and RoleTemplate, so they should be in the mgmt
plane.
https://github.com/rancher/rancher/issues/22512
> Move two handlers from user to mgmt context

- pkg/settings/setting.go
Changing setting to dev branch since we branched off for 2.3 and will use master branch only for releases.
> Update RKEMetadataConfig setting to use dev branch for kontainer-driver-metadata

- pkg/controllers/user/alert/watcher/node.go
https://github.com/rancher/rancher/issues/23250
This pr just fixes the situation when v3.node (machine) can't be found for v1.node. 
The reason for node missing can vary. Node might have been registered in k8s, but not propagated to rancher yet via nodesyncer. Added logging to reflect this situation.
> Handle panic is alert watch code

- README.md
The CI build badge does not load correctly
Before
Change the base url from "drone8.rancher.io" to "drone-publish.rancher.io"
After
> Fix drone CI build badge

- pkg/jailer/jailer.go
- pkg/settings/setting.go
Problem:
On some systems the default time of 10 seconds can cause the initial
jail creation to fail and Rancher won't be able to start
The error message is also not clear as to what failed
Solution:
Make the timeout a setting and also increase the default to 60 seconds
Update error message to clarify the failure is coming from the timeout
https://github.com/rancher/rancher/issues/23160
https://github.com/rancher/rancher/issues/22379
> Make jailer timeout a setting

- pkg/jailer/jailer.go
- pkg/settings/setting.go
Problem:
On some systems the default time of 10 seconds can cause the initial
jail creation to fail and Rancher won't be able to start
The error message is also not clear as to what failed
Solution:
Make the timeout a setting and also increase the default to 60 seconds
Update error message to clarify the failure is coming from the timeout
https://github.com/rancher/rancher/issues/23241
> [forwardport]Make jailer timeout a setting - master

- .golangci.json
- Dockerfile.dapper
- scripts/ci
- scripts/test
- scripts/validate
This switches rancher back to golangci and runs the same linters we were running before. It also adds a change to stop printing the rancher logs after the tests run if the tests do not fail. This saves ~6 min in build time.
> Switch back to golangci

- package/Dockerfile
- pkg/catalog/helm/helm.go
Problem:
When bind mounting /var/lib/rancher the catalog cache won't exist on the
local filesystem
Solution:
Move the catalog cache to a location we don't tell people to bind mount
like /var/lib/rancher-data
#23427
> Move location of bundled catalogs

- Dockerfile.dapper
- package/Dockerfile
- package/jailer.sh
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
Reverts rancher/rancher#23399 - This was backed out of the release branch for v2.3.1, so it needs to be added back in after v2.3.1 is released. 
Update helm version
Problem:
Helm needs to be updated and renamed to stop name colisions
Solution:
Rebase helm, update all calls to use rancher-helm
> Revert "Revert "Update helm version""

- pkg/api/customization/logging/validator.go
- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/logging/generator/generator.go
- pkg/controllers/user/logging/generator/targetwrap.go
- pkg/controllers/user/logging/generator/template.go
- pkg/controllers/user/logging/generator/templatefilter.go
- pkg/controllers/user/logging/generator/templatematch.go
- pkg/controllers/user/logging/generator/templatesource.go
- pkg/controllers/user/logging/generator/validator.go
- pkg/controllers/user/logging/generator/validator_test.go
Problem:
1. Project match source use all file under /var/log/containers which include log files not belong to this project
2. When configuring read_from_head, if target file is large, it takes a long time and starting other plugins isn't executed until reading file is finished.
3. Default file chunk size is 256M, kafka plugin will iterate over each 256M file and deliver each 1024K, it takes a long time if file is too large
Solution:
1. Only tail file belong to this project
2. Remove read_from_head
3. reduce each chunk file size for kafka, set default kafka aggregation threshold higher
Issue:
https://github.com/rancher/rancher/issues/23303
> [2.3.2] enhance logging configure

- .golangci.json
- Dockerfile.dapper
- scripts/ci
- scripts/test
- scripts/validate
This switches rancher back to golangci and runs the same linters we were running before. It also adds a change to stop printing the rancher logs after the tests run if the tests do not fail. This saves ~6 min in build time.
https://github.com/rancher/rancher/issues/18638
> [backport] Switch back to golangci

- tests/integration/suite/test_project_catalog.py
All other tests that create prtb/crtb for a user have this wait check before using the user's client. So adding the same wait check here too will fix the flakiness
> Add wait in projectcatalog access check test

- pkg/controllers/management/node/controller.go
- tests/integration/suite/test_node.py
Problem:
When parsing nodetemplates initially new lines are dropped from the end
of ssh keys
Solution:
Add them back before writing them out for docker-machine usage
This is norman parsing the initial request so there isn't a good way to just not drop them as it would affect all other parsing. 
https://github.com/rancher/rancher/issues/23511
> Add newlines to ssh keys for nodetemplates

- pkg/api/store/secret/store.go
- tests/integration/suite/test_secrets.py
The secrets store calls AddCertInfo to parse cert so it populates all the necessary
UI fields. But if the cert is malformed AddCertInfo throws an error. This also
prevents the project in which this cert exists from loading in UI.
This commit logs the error message instead of returning error. This way the cert
will still not display in UI properly since it is malformed, but this won't stop
the project from loading.
#23285
> Log cert parse error instead of returning err

- pkg/controllers/management/etcdbackup/etcdbackup.go
When looking into how rancher does etcdbackups, I found this small typo that triggered my OCD. ;)
> etcdbackup: Fix typo in variable name

- pkg/api/controllers/dynamiclistener/listener_controller.go
- pkg/api/controllers/dynamiclistener/listener_controller_test.go
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
observed on ha setup: agents get deployed with old value before
cacerts update in settings, adding updating cluster with
forceDeploy annotation to redeploy agent.
https://github.com/rancher/rancher/issues/23441
> resync cluster on cacert change

- pkg/dialer/factory.go
This reverts commit 4acfe6919cd70559c098175b4c07bb2762c8499a.
Was meant for release/v2.3.x branch
> Revert "Fall back to node dialer when cluster one fails, for imported clusters

- pkg/dialer/factory.go
https://github.com/rancher/rancher/issues/23331
* Removed legacy restriction from the times where we didn't start node agents in imported clusters
* Limit kube api endpoint override to 127.0.0.1 to rke clusters only, where every worker node has a reverse proxy that proxies 127.0.0.1:6443 to kube api.
> [forwardport] Fall back to node dialer when cluster one fails, for imported clusters

- package/windows/bootstrap.ps1
**Problem:**
The local language verification is used for avoiding the failure running
of Flannel.
**Solution:**
Repackage the Flannel with a new vendor to satisfy none English system.
https://github.com/rancher/rke-tools/pull/85
**Issue:**
https://github.com/rancher/rancher/issues/23078
> [v2.3] Drop the detecting for system locale language

- pkg/settings/setting.go
- scripts/build-server
Release branch should point to its corresponding latest ui branch so we don't have to change the ui-index tag when launching new 2.3 dev clusters.
> Update 2.3 to Correct UI Index for Head Builds

- pkg/api/customization/podsecuritypolicybinding/validator.go
- pkg/api/server/managementstored/setup.go
- tests/integration/suite/test_pod_security_policies.py
Problem:
When creating a psptBinding a template id is required but not validated
so an invalid value does not return to the user and causes the
controller to keep trying to create resources
Solution:
Validate the template ID belongs to a real template before creating the
binding
https://github.com/rancher/rancher/issues/22556
> [backport] Add validation to psptBinding creation

- pkg/api/customization/project/project_actions.go
- pkg/api/server/managementstored/setup.go
- pkg/controllers/management/cluster/clustercontroller.go
- tests/integration/suite/test_pod_security_policies.py
**Problem:**
User can set psp template even if psp is not enabled.
**Solution:**
Return error in apply psp action is psp is disabled for the cluster
**Issue:**
https://github.com/rancher/rancher/issues/21548
> Psp validator

- package/windows/bootstrap.ps1
Forwardport PR https://github.com/rancher/rancher/pull/23735
**Problem:**
The local language verification is used for avoiding the failure running
of Flannel.
**Solution:**
Repackage the Flannel with a new vendor to satisfy none English system.
https://github.com/rancher/rke-tools/pull/85
**Issue:**
https://github.com/rancher/rancher/issues/23078
> [forwardport] Drop the detecting for system locale language

- pkg/api/customization/logging/validator.go
- pkg/controllers/user/logging/config/config.go
- pkg/controllers/user/logging/generator/generator.go
- pkg/controllers/user/logging/generator/targetwrap.go
- pkg/controllers/user/logging/generator/template.go
- pkg/controllers/user/logging/generator/templatefilter.go
- pkg/controllers/user/logging/generator/templatematch.go
- pkg/controllers/user/logging/generator/templatesource.go
- pkg/controllers/user/logging/generator/validator.go
- pkg/controllers/user/logging/generator/validator_test.go
Forward port pr for #23114
Problem:
1. Project match source use all file under /var/log/containers which include log files not belong to this project
2. When configuring read_from_head, if target file is large, it takes a long time and starting other plugins isn't executed until reading file is finished.
3. Default file chunk size is 256M, kafka plugin will iterate over each 256M file and deliver each 1024K, it takes a long time if file is too large
Solution:
1. Only tail file belong to this project
2. Remove read_from_head
3. reduce each chunk file size for kafka, set default kafka aggregation threshold higher
Issue:
https://github.com/rancher/rancher/issues/23303
> [forwardport] Enhance log config

- pkg/controllers/management/kontainerdrivermetadata/data.go
old constraint: each plugin template must be present for all k8s versions
this is not very convenient if a new plugin is introduced only for new
versions, changed from error to warning
https://github.com/rancher/kontainer-driver-metadata/pull/76
> don't error out on missing template

- main.go
https://github.com/rancher/rancher/issues/20385
With --acme-domain availability as environment variable ACME_DOMAIN it's possible
to run rancher/rancher image on Azure Container Instances and get a
valid Letsencrypt certificate instead self-signed.
This helps enterprises who are using proxies which evaluate SSL certificates.
> ACME_DOMAIN environment variable missing - fixes #20385 

- pkg/controllers/user/monitoring/cluster_monitoring_enabled_handler.go
Fixed the panic observed on one of the setups:
```
E1108 00:31:41.148173       6 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ReplicationController: Get https://10.200.2.152:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0&timeout=30s: EOF 
2019/11/08 00:31:46 [ERROR] NodeController trident recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack: 
goroutine 152120 [running]: 
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc00ca2ddb0) 
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5 
panic(0x2d21360, 0x5d48e80) 
/usr/local/go/src/runtime/panic.go:522 +0x1b5 …
```
> Fixed panic in monitoring handler

- pkg/api/customization/cluster/actions_kubeconfig.go
**Problem:**
The cluster generateKubeconfig action panics if cluster contains a nil localClusterAuthEndpoint.
**Solution:**
Nil check localClusterAuthEndpoint
**Issue:**
https://github.com/rancher/rancher/issues/23783
**Notes:**
This happens because to use access.byId the client cluster struct needs to be used, opposed to the regular management struct. Typically there is a default localClusterAuthEndpoint but all struct fields on the client cluster struct are pointers, and so the default is nil. This is a generated struct.
This only occurs when the request lacks a localClusterAuthEndpoint or it is explicitly set to null in the request. The UI is currently omitting the localClusterAuthEndpoint (see following issue):
https://github.com/rancher/rancher/issues/23913
> Add nil check to generate kube config action

- pkg/auth/providers/activedirectory/activedirectory_client.go
ExternalID is the distinguishedName of a user, which is being used as the baseDN
in ldap search query in RefetchGroupPrincipals. This doesn't need to be split on `\`.
That split is only for when we're using some field that has "logindomain\username"
format. Splitting incorrectly on `\` removed a part of the distinguishedName leading
to ldap errors
https://github.com/rancher/rancher/issues/23684
forward port of https://github.com/rancher/rancher/pull/23035
> Forward port: Remove invalid parsing of distinguishedName in AD refresh principals

- scripts/istio-images-mirror
Problem:
There are some error logs in coreos-kube-state-metrics pod for monitoring
Solution:
Bump coreos-kube-state-metrics version to support k8s 1.16
Issue:
rancher/rancher#23556
> Mirror kube-state-metrics image

- pkg/api/customization/kontainerdriver/actionhandler.go
- pkg/api/server/managementstored/setup.go
- pkg/api/store/setting/store.go
- pkg/controllers/management/kontainerdrivermetadata/data.go
- pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
- tests/integration/suite/test_kontainer_drivers.py
metadata settings related to k8s versions current, default and deprecated
shouldn't get overridden once user updates them
https://github.com/rancher/rancher/issues/22572
> handle user updated metadata settings

- pkg/api/customization/project/project_actions.go
- pkg/api/server/managementstored/setup.go
- tests/integration/suite/conftest.py
- tests/integration/suite/test_pod_security_policies.py
**Problem:**
Project's action `setpodsecuritypolicytemplate` does not handle the invalid podSecurityPolicyTemplateId
**Solution:**
Return error if the podSecurityPolicyTemplate does not exist 
**Issue:**
https://github.com/rancher/rancher/issues/23931
> add check for invalid podSecurityPolicyTemplateId

- pkg/api/customization/globalrole/validator.go
- tests/integration/suite/test_global_roles.py
Problem:
Globalrole test results have been flakey. This is not due to the test. The validator is using a lister which does not always update quickly enough after object creation, leading to not found errors.
Solution:
Use client/interface instead of a lister.
Issue:
https://github.com/rancher/rancher/issues/24115
> Fix flaky globalrole test

- pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
on metadata init first time, settings can stay empty for a long time
if git clone is slow.
https://github.com/rancher/rancher/issues/24091
> update settings from vendor first before fetching url

- pkg/api/store/cluster/cluster_store.go
- tests/integration/suite/test_clustertemplate.py
https://github.com/rancher/rancher/issues/23795
This is a change to the original fix:
Earlier the fix was to throw error while upgrading to a revision that can turn off monitoring and alerting on the cluster.
Instead of erroring out, the fix now is to ignore the template revision's flag when they are false during update cluster usecase.
This will allow the cluster updates (edit cluster to change overrides or update revision) to go through but keep monitoring/alerting intact.
> Do not turn off monitoring/alerting from templateRevision during cluster updates.

- pkg/controllers/user/nodesyncer/nodessyncer.go
Looks like 2.3.0 regression introduced by https://github.com/rancher/rancher/pull/22983. NodeConfig will always be nil for non-rke clusters. Moved not nil check to the relevant method
https://github.com/rancher/rancher/issues/23840
> Node labels sync for all types of clusters

- pkg/api/server/managementstored/setup.go
- pkg/api/store/globalrolebindings/globalrolebinding_store.go
- pkg/controllers/management/auth/globalrolebinding_handler.go
- tests/integration/suite/test_global_role_bindings.py
**Problem:**
If a globalrole is deleted, globalrolebindings referencing it are left over.
**Solution:**
Add globalrole being referenced in GlobalRoleName field as an owner reference for globalrolebindings.
**Issue:**
https://github.com/rancher/rancher/issues/16216
> Add GRB cleanup for deleted GR

- pkg/controllers/management/auth/globalrolebinding_handler.go
- pkg/controllers/management/auth/legacy_grb_cleaner.go
- pkg/controllers/management/auth/register.go
- pkg/controllers/user/rbac/cluster_handler.go
- pkg/controllers/user/rbac/globalrole_handler.go
- pkg/controllers/user/rbac/handler_base.go
- pkg/rbac/common.go
Problem:
grb-sync is a cluster scoped lifecycle handler so if many clusters are
coming in all the handlers collide to try and update grbs with
finalizers
Solution:
Move grb-sync to management level and push bindings to the cluster
https://github.com/rancher/rancher/issues/23806
> Move grb-sync out of cluster level

- pkg/api/customization/globalrolebinding/validator.go
- pkg/api/server/managementstored/setup.go
- pkg/controllers/management/auth/globalrolebinding_handler.go
- pkg/controllers/user/rbac/globalrole_handler.go
- pkg/rbac/common.go
- tests/integration/suite/common.py
- tests/integration/suite/test_global_role_bindings.py
- tests/integration/suite/test_node.py
**Problem:**
Admins would like to assign AD groups to global roles so when a member is added that belongs to that group, they will inherit the global role permissions.
**Solution:**
Support assigning group principal IDs to global role bindings.
**Issue:**
https://github.com/rancher/rancher/issues/22707
> Can assign groups to global roles

- tests/validation/tests/v3_api/common.py
fix the bug that Jenkins job fails because no kubeconfig file exists
> fix the bug that Jenkins job fails because no kubeconfig file exists

- pkg/controllers/user/noderemove/nodes.go
as we do respect the special name from settings
https://github.com/rancher/rancher/issues/23983
to fix the use case described in https://github.com/rancher/rancher/issues/23983#issuecomment-559210627
> Respect ignore label on node removal

- pkg/catalog/manager/catalog_common.go
- pkg/catalog/manager/crd.go
- pkg/catalog/manager/traverse.go
- pkg/catalog/manager/traverse_test.go
- tests/integration/suite/test_catalog.py
Problems:
The count for catalog templates was increasing after create or update was called even if they threw an error. TemplateSpec value "UpgradeVersionLinks" was being set prior to DeepEquals being called during update causing the template to indicate that it needed updating when no values had changed. Long label name was erring after template was being created. 
Solution:
Increment count only where there is not an error. Move "UpgradeVersionLinks" to be set only when it is needed. Add log to indicate files had a failure. Make errors indicate when the error occurred instead of being generic. Check for label length before allowing template to create. Delete template during delete if template version doesn't exist to ensure catalog delete occurs successfully. Reduce the number of times …
> Catalog log fix

- pkg/catalog/manager/catalog_common.go
- pkg/catalog/manager/crd.go
- pkg/catalog/manager/traverse.go
- pkg/catalog/manager/traverse_test.go
- tests/integration/suite/test_catalog.py
**Problems:**
The count for catalog templates was increasing after create or update was called even if they threw an error. TemplateSpec value "UpgradeVersionLinks" was being set prior to DeepEquals being called during update causing the template to indicate that it needed updating when no values had changed. Long label name was erring after template was being created.
**Solution:**
Increment count only where there is not an error. Move "UpgradeVersionLinks" to be set only when it is needed. Add log to indicate files had a failure. Make errors indicate when the error occurred instead of being generic. Check for label length before allowing template to create. Delete template during delete if template version doesn't exist to ensure catalog delete occurs successfully. Reduce the number of …
> [v2.3] Catalog log fix

- pkg/controllers/management/auth/manager.go
**Problem**
Controller appeared to make hard create calls even when object already existed. Cache was not updating quick enough, so check for already exists was not catching when create was called close together.  
**Solution**
Add check for IsAlreadyExists for err so that it is not returned
**Issue**
#23804
> Already Exists Role

- pkg/controllers/management/node/controller.go
Problem:
The same credential used to create a node is used to delete it so if a
cloud cred is updated or keys rotated nodes will leak
Solution:
Before doing an update or delete of a node rebuild the credentials using
the latest cloud cred referenced in the template
https://github.com/rancher/rancher/issues/24234
> Refresh credentials on node removal

- app/role_data.go
Drop clustertemplaterevisions-create from user-base roletemplate and add new global role "Create RKE Template Revisions" which can be assigned separately when needed.
> Drop clustertemplaterevisions-create from user-base and add new global role

- pkg/api/store/pod/owner.go
https://github.com/rancher/rancher/issues/22106
Looking at adding a test.
> Skip setting workloadId for pods with non-workload owner refs

- app/role_data.go
[backport from  master] Drop clustertemplaterevisions-create from user-base and add it as a separate global role
> [2.3.4] Drop clustertemplaterevisions-create from user-base and add it as a separate global role

- chart/templates/deployment.yaml
Fix for issue https://github.com/rancher/rancher/issues/24518
> Set maxSurge and maxUnavailable to 1 to allow rolling upgrades when antiAffinity is set to required

- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
Added a test for testing the aws cloud provider setup scenario which was failing in issue - 24515
```
{"name": "aws",
"type": "cloudProvider"}
```
> Test for aws cloud provider

- chart/templates/deployment.yaml
Fix for issue https://github.com/rancher/rancher/issues/24518
> [2.3] Set maxSurge and maxUnavailable to 1 to allow rolling upgrades when antiAffinity is set to required

- tests/integration/suite/test_catalog.py
**Problem**
Flakey test due to catalog name randomly being too long causing the too long error to trigger when needing to test invalid catalog name error
**Solution**
Shorten the chart name
**Related PR**
https://github.com/rancher/integration-test-charts/pull/3
**Issue**
#24446
> [flakey test][v2.3] test_invalid_catalog_charts

- tests/integration/suite/test_catalog.py
**Problem**
Flakey test due to catalog name randomly being too long causing the too long error to trigger when needing to test invalid catalog name error
**Solution**
Shorten the chart name
**Related PR**
rancher/integration-test-charts#3
**Issue**
#24446
> [flakey test][forwardport] test_invalid_catalog_charts

- package/Dockerfile.agent
This can go in as soon as share-mnt 1.0.6 has been released.
https://github.com/rancher/rancher/issues/20740
> Update share-mnt to 1.0.6

- pkg/auth/providers/providers.go
https://github.com/rancher/rancher/issues/20159
The panic will occur only if the authProvider field on token is empty or the provider isn't configured.
Not sure why either of this would happen. But this commit will avoid panic and error will indicate what was causing it.
> Check token in SearhPrincipals to avoid panic

- pkg/controllers/management/globaldns/globaldns_handler.go
- pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
**Problem**
APIVersions for `github.com/rancher/types/apis/management.cattle.io/v3` were being listed at `APIVersion: "v3"`. It is common practice to list `<GROUP_NAME>/<VERSION>` as the value for APIVersion. 
**Solution**
Update APIVersion to include group name in the version. Example `APIVersion: "v3"` >> `APIVersion: "management.cattle.io/v3`
**Issue**
#24294
> [v2.3] Add api group name to apiversion

- pkg/auth/providers/googleoauth/goauth_helper.go
- pkg/auth/providers/googleoauth/goauth_provider.go
https://github.com/rancher/rancher/issues/24334
The refetch groups api for google auth wasn't checking if the nested
group membership option was enabled. This commit adds that check
to ensure nested group membership is preserved on refetch api
> Preserve nested membership on refetch principals

- pkg/auth/providers/googleoauth/goauth_helper.go
- pkg/auth/providers/googleoauth/goauth_provider.go
Forward port for https://github.com/rancher/rancher/pull/24606
The refetch groups api for google auth wasn't checking if the nested
group membership option was enabled. This membership adds that check
to ensure nested group membership is preserved on refetch api
> [Forward port] Preserve nested membership on refetch principals

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/resource/istio/bookinfo.yaml
- tests/validation/tests/v3_api/test_istio.py
* Enable Istio / cluster monitoring if not enabled
* Always deploy the latest Istio chart (can be overriden in env var)
* Create gateway, virtual service, destination rules, through API and check routing
* flake8 passes
I still need to run this against a 1.15 or lower cluster
> Istio validation test

- pkg/cluster/private_registry.go
- pkg/controllers/management/node/controller.go
Issues: 
- incorrect value of registry auth is passed so worker nodes can't create process 
- nodes created via docker-machine cannot use private registry credentials, so new node creation fails 
PR fixes: 
- registry auth creation 
- deployAgent should only use System default registry to append to agent-image 
https://github.com/rancher/rancher/issues/20029
> generate correct registry auth for private registry

- package/Dockerfile
- pkg/catalog/git/git.go
- pkg/settings/setting.go
- allow metadata branch to be set via env var `RANCHER_METADATA_BRANCH` 
- need to return error if commit is not found while loading data 
https://github.com/rancher/rancher/issues/24743
> introduce env var rancher_metadata_branch 

- tests/validation/lib/aws.py
- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
Issue: https://github.com/rancher/rancher/issues/24722
Add a pipeline file that can 
- run Rancher server
- provision clusters with different OS and docker version
- run tests on those clusters
Add the following two private images:
- RHEL7.7_Native_Docker_1.13.1
- RHEL7.7_Upstream_Docker_19.03
> automation - run tests on multiple OS and Docker version

- pkg/controllers/management/kontainerdrivermetadata/data.go
1) metadata CRDs were only updated when `sendRKELabel` was true (if they were supposed to send to RKE). We now always update the content, so in case user wants to override the values, they can simply set the label true after refresh
2) labels comparison (causing multiple REST Updates in debug logs, but never updating actual object)
a) System Images: `"cattle.io/creator": "norman"` is present in our CRD labels and it wasn't considered for comparing object labels for update
b) Addons, Service Options: we check for a label (`sendRKELabel`)'s value, but if the label is not present, it should default to true 
3) added logs for easier debugging 
https://github.com/rancher/rancher/issues/24675
> fix metadata sync

- package/run.sh
reverting https://github.com/rancher/rancher/pull/22220/
This change is reverting the permissions set by rke-tools in this PR https://github.com/rancher/rke-tools/pull/88
We no longer set the acls on the files, hence this change is no longer needed.
> Set 755 on the ssl dir so that etcd user can read the cert files

- go.mod
- go.sum
- pkg/controllers/management/clusterdeploy/clusterdeploy.go
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_spec.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_spec_base.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
- vendor/modules.txt
Adding a map in the clusterdeploy template to track the downstream agent incase of upgrade/rollback as per this bug report https://github.com/rancher/rancher/issues/21386
Read my writeup in that issue which tells you how to recreate this problem locally.
> [2.3] Downstream Agent Tracking

- pkg/controllers/management/kontainerdrivermetadata/data.go
https://github.com/rancher/rancher/issues/24675
1) metadata CRDs were only updated when `sendRKELabel` was true (if they were supposed to send to RKE). We now always update the content, so in case user wants to override the values, they can simply set the label true after refresh
2) labels comparison (causing multiple REST Updates in debug logs, but never updating actual object)
a) System Images: `"cattle.io/creator": "norman"` is present in our CRD labels and it wasn't considered for comparing object labels for update
b) Addons, Service Options: we check for a label (`sendRKELabel`)'s value, but if the label is not present, it should default to true 
3) added logs for easier debugging
> [2.3] fix metadata sync

- pkg/controllers/user/logging/configsyncer/configgenerator.go
- pkg/controllers/user/logging/generator/templatefilter.go
**1. Fixed fluentd log parsing full of backslash**
Solution:
Use multi_format plugin to avoid fluentd logging warning when parsing the log to JSON if it's not in JSON format.
Related issue:
https://github.com/rancher/rancher/issues/24545
**2. Enable sorting grep system namespace for logging**
Need to merge https://github.com/rancher/system-charts/pull/141 first
> Log json parsing format and sort namespaces

- pkg/controllers/user/logging/configsyncer/configgenerator.go
- pkg/controllers/user/logging/generator/templatefilter.go
**1. Fixed fluentd log parsing full of backslash**
Solution:
Use multi_format plugin to avoid fluentd logging warning when parsing the log to JSON if it's not in JSON format.
Related issue:
https://github.com/rancher/rancher/issues/24545
**2. Enable sorting grep system namespace for logging**
Related PR:
https://github.com/rancher/system-charts/pull/141
Need to merge https://github.com/rancher/system-charts/pull/141 first
> [2.3.4] Log json parsing format and sort namespaces

- tests/integration/suite/test_catalog.py
**Problem** 
Test was occasionally getting information from chart when it was retrying and not in error state
**Solution**
Ensure the catalog is in refreshed error and not refreshed syncing when assertions on ran
**Issue**
#24446
> [flakey test][v2.3] Ensure error state

- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
Add the ability to pass RANCHER_K8S_VERSION to downstream pipelines for clusters being provisioned. 
Changes to the pipeline configuration have been done. 
Tests are passed.
> allow setting the cluster's k8s version

- tests/integration/suite/test_catalog.py
**Problem**
Test was occasionally getting information from chart when it was retrying and not in error state
**Solution**
Ensure the catalog is in refreshed error and not refreshed syncing when assertions on ran
**Issue**
#24446
> [flakey test][forwardport] Ensure error state

- pkg/controllers/user/rbac/prtb_handler.go
- pkg/controllers/user/rbac/reconcile_roletemplate.go
- pkg/controllers/user/rbac/roletemplate_handler.go
- tests/integration/suite/test_role_template.py
https://github.com/rancher/rancher/issues/23658
When a user is added to project/cluster, based on the roleTemplate, rolebindings
and clusterrolebindings are created for that user.
When user is added to a  project, following clusterRoleBindings are created
* roleTemplate.Name-promoted: if storageClass, persistentVolumes and apiservices are
among the roles's resources
* project.Name-namespaces-edit and create-ns: if there is "create" or "*" permission on the
"namespaces" resource of any of the rules in the roleTemplate
* project.Name-namespaces-readonly: if there is no "create" permission on "namespaces" resources in any of the rules in roletemplate
Along with this, roleBindings are created in the namespaces belonging to that project:
* One with the clusterRole of the roleTemplate.Name
* …
> Update CRB and RB if roleTemplate's inherited roles are edited

- pkg/controllers/management/node/controller.go
- pkg/jailer/jailer.go
- pkg/nodeconfig/config.go
https://github.com/rancher/rancher/issues/24695
Problem: When creating multiple nodes from a node template at the same time, some node provisioning would error on first try showing `lstat: no such file or directory`
Root cause: A function (`newNodeConfig`) would create the whole jail directory structure (including parent directories), causing the actual createjail function to think the jail was incomplete (because there is no `done` file which indicates a jail is ready which is only created by the `CreateJail` function)
Solution: Move the `CreateJail` function to be the first to be called so it can be created as expected
> Create a jail first when node gets created

- pkg/controllers/management/kontainerdrivermetadata/metadata_handler.go
on metadata init first time, settings can stay empty for a long time
if git clone is slow.
https://github.com/rancher/rancher/issues/24091
> [2.3] update settings from vendor first before fetching url

- package/run.sh
https://github.com/rancherlabs/rancher-security/issues/368
This method was originally added to ensure facl permissions are set again by rancher since the dir was set at 700 permission and that would change the facl - https://github.com/rancher/rancher/pull/22220
But now rke-tools sets the dir at 755 which gives read access to all users, so we need not re-run the setfacl command. When this command is re-run it changes the file permissions to 640, but we need the files to be at 600 for CIS compliance.
> remove the script setting facl again on the certs dir

- tests/validation/lib/aws.py
- tests/validation/lib/node.py
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_bkp_restore.py
- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
Adding support to check the local filesystem snapshot files in `/opt/rke/etcd-snapshots`
Creating a AWS custom cluster to be able to ssh into the `etcd` nodes.
Iterate over the `etcd` nodes to check each node's local filesystem.
> local filesystem test for clusters snapshots

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/conftest.py
- tests/validation/tests/v3_api/test_workload.py
Changes:
- divide workload's monolithic RBAC tests into small ones
- rename arguments for RBAC-related functions
- add a description to the `remove_resource` fixture  
Jenkins run: 
- all RBAC test cases are passed.
> divide workload's monolithic RBAC tests into small ones

- pkg/controllers/user/rbac/prtb_handler.go
The error check needs to validate the error type, if the role exists no error should be returned. 
This is a 2nd piece of:
https://github.com/rancher/rancher/issues/23804
> Validate error when creating role

- pkg/api/store/namespace/store.go
The `data["projectId"]` value is empty when updates namespace with `ResourceQuota`, this cause `validateResourceQuota ` function aggregate some unexpected namespaces for validate.
Change `data["projectId"]` to `projectID` variable.
https://github.com/rancher/rancher/pull/24550
> Exclude unrelated namespaces when validate namespace's quota

- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_single_upgrade_multiple
If RANCHER_ELASTIC_SEARCH_ENDPOINT is set, enable logging for the created clusters to the specified elasticsearch endpoint.
> Add stage to enable elastic search logging in single-click-multi-cluster upgrade tests

- tests/validation/tests/v3_api/test_app.py
- Rabc code, (initial setup when RBAC is enabled) deploys a workload also in the namespace where I deploy the app.
- While querying for the app's workload with the namespace it gives 2 workloads (1 is rbac wk and 1 is app's wk)
- It failed when it was recursing rbac wk looking for a chart.
- Chart was available in the app's wk
**Fix:** Deleting all workloads in rbac Project before starting apps validation.
> Fixing failures in test_app tests

- pkg/settings/setting.go
Update the default, `master` is no longer the most current.
> Default agent image update

- tests/validation/lib/aws.py
- tests/validation/requirements_v3api.txt
* Added a method to decrypt the Windows Administrator password for AWS nodes.
* Added Windows AMI for us-east-2 region
Node must have been launched with the same `AWS_SSH_KEY_NAME, AWS_SSH_PEM_KEY` as specified in environment/parameters. 
Make sure to wait at least 5 minutes after launching the instance before decrypting password -- if not ready, the password will be blank
```
def test_windows_decrypt_password():
password = AmazonWebServices().decrypt_windows_password('i-0000000000')
print("Password: " + password)
```
> Validation - Decrypt AWS Windows password

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_cert_rotation.py
Added `test_cert_rotation.py` to `v3_api`:
Tests 7 test cases. Tests rotation on all certificates in a cluster, and rotation on 6 individual certificates.
Added `get_etcd_nodes` to `common.py`:
Returns all etcd nodes in a cluster.
> Add cert rotation tests

- package/Dockerfile
- scripts/package
I discovered this while testing https://github.com/rancher/rancher/pull/25021, the offending image (grafana) kept appearing and it seemed to default to `v2.3-dev` branch for system-charts in `master` which is pretty confusing. As we branch this to a release, rancher `master` -> system-charts `dev` seems logical. Also, this is what is currently documented.
> Change default system-charts branch to dev

- tests/validation/tests/v3_api/test_nfs.py
Problem:
When we create a pvc using an existing pv, the default storage class is used instead of the pv
Solution:
pass the `storageClassID` as an empty string in the request
Result:
the pvc is created using the pv
> fix PVC creation error  when storageClass exists 

- tests/validation/tests/v3_api/common.py
This sometimes causes the upgrade test cases to fail as when you add a catalog URL, it transitions as:
`Active --> Refreshing --> Active` **OR** `Active`
adding - catalog = catalog_data["data"][0] to fix the issue
> Fixing catalog time issue

- pkg/controllers/management/kontainerdrivermetadata/data_getter.go
- pkg/controllers/user/cis/clusterScanHandler.go
Addresses: https://github.com/rancher/rancher/issues/25179
Resolve the short k8s version before, not during fetching the CIS config
> use default when k8s version not found

- pkg/controllers/user/nodesyncer/nodessyncer.go
**Issue:** panic because canChangeValuePolicy is nil
https://github.com/rancher/rancher/issues/25164 
**Solution:** 
I'm using allowAll for annotations because didn't find any checks before refactor PR: https://github.com/rancher/rancher/pull/22866 
nodePlan initially sends the following annotations, https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/rke/cluster/plan.go#L131
```
"rke.cattle.io/internal-ip": host.InternalAddress
"rke.cattle.io/external-ip": host.Address
```
I don't know when these values on v1.Node could differ from initially set values from nodePlan..
> pass canChangeValuePolicy to avoid panic error

- tests/validation/tests/v3_api/.gitignore
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/resource/istio/crds/adapter.yaml
- tests/validation/tests/v3_api/resource/istio/crds/attributemanifest.yaml
- tests/validation/tests/v3_api/resource/istio/crds/authenticationpolicy.yaml
- tests/validation/tests/v3_api/resource/istio/crds/authorizationpolicy.yaml
- tests/validation/tests/v3_api/resource/istio/crds/destinationrule.yaml
- tests/validation/tests/v3_api/resource/istio/crds/envoyfilter.yaml
- tests/validation/tests/v3_api/resource/istio/crds/gateway.yaml
- tests/validation/tests/v3_api/resource/istio/crds/handler.yaml
- tests/validation/tests/v3_api/resource/istio/crds/httpapispec.yaml
- tests/validation/tests/v3_api/resource/istio/crds/httpapispecbinding.yaml
- tests/validation/tests/v3_api/resource/istio/crds/quotaspec.yaml
- tests/validation/tests/v3_api/resource/istio/crds/quotaspecbinding.yaml
- tests/validation/tests/v3_api/resource/istio/crds/rbacconfig.yaml
- tests/validation/tests/v3_api/resource/istio/crds/rule.yaml
- tests/validation/tests/v3_api/resource/istio/crds/serviceentry.yaml
- tests/validation/tests/v3_api/resource/istio/crds/servicerole.yaml
- tests/validation/tests/v3_api/resource/istio/crds/servicerolebinding.yaml
- tests/validation/tests/v3_api/resource/istio/crds/sidecar.yaml
- tests/validation/tests/v3_api/resource/istio/crds/template.yaml
- tests/validation/tests/v3_api/resource/istio/crds/virtualservice.yaml
- tests/validation/tests/v3_api/test_istio.py
Closes: #25097 
CRD RBAC tests added. Left the known failing ones commented out, and ignored the `certmanager` CRDs (that are also known to be failing in current state). These should be added when all of those are fixed.
Also created a test for validating all of the possible custom answers in Istio. It validates a few things:
1. Expected workloads, by name, are deployed successfully and all their pods are running.
2. There are no additional workloads deployed.
3. All of the workload containers have an image that starts with `rancher/` which is important for airgap setups.
> Add crd rbac tests and custom answers test

- pkg/api/store/cluster/cluster_store.go
- tests/integration/suite/test_kontainer_engine_config.py
https://github.com/rancher/rancher/issues/24982
https://github.com/rancher/rancher/issues/23759
My first attempt was to just remove the two functions (`setKubernetesVersion` and `validateNetworkFlag`) from `Update` but we want to keep the logic of testing for deprecated k8s versions and the logic of testing for network policy so I changed it to pass existingCluster on update so the functions can determine when its a new cluster and when its an update.
> Do not set k8s version or networkpolicy on update

- pkg/controllers/user/resourcequota/resource_quota_sync.go
- pkg/controllers/user/resourcequota/resource_quota_sync_test.go
Using `reflect.DeepEqual` to compare `resource.Quantity` can lead to the compare results are not expected. This problem is particularly acute when setting CPU related quotas. [Code Line 1](https://github.com/rancher/rancher/blob/master/pkg/controllers/user/resourcequota/resource_quota_sync.go#L103-L109) [Code Line 2](
https://github.com/rancher/rancher/blob/master/pkg/controllers/user/resourcequota/resource_quota_sync.go#L145)
Using `k8s.io/apimachinery/pkg/api/equality` [Sementic](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/equality/semantic.go#L31) Ignore formatting, only care that numeric value stayed the same. [References kubernetes quotaController code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/resourcequota/resource_quota_controller.go#L21 …
> Fix resource_quota_sync deepEqual bug

- scripts/windows/utils.psm1
**Problem:**
Windows builds succeed when the build fails
**Solution:**
Using `throw` instead of `exist`
**Issue:**
https://github.com/rancher/rancher/issues/25235
> Fixed failed Windows builds not terminated

- pkg/features/feature.go
- pkg/features/feature_test.go
This change allows the ScaledContext to be nil allowing features to be
initialized from the command line only.
> Allow initializing features without controllers

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/conftest.py
- tests/validation/tests/v3_api/resource/activedirectory.json
- tests/validation/tests/v3_api/resource/freeipa.json
- tests/validation/tests/v3_api/resource/openldap.json
- tests/validation/tests/v3_api/test_group_grb.py
This PR adds functional and RBAC tests for group global role binding.
- 3 functional tests
- 15 rbac tests
Prerequisite:
- Enable Auth in the Rancher setup 
- Optional: searching nested group enabled
It supports three Auth providers: 
- activeDirectory
- freeIPA
- openIdap
tests can be run with or without searching in nested groups.
It introduces the following global variables
- RANCHER_AUTH_USER_PASSWORD
- RANCHER_AUTH_PROVIDER
- RANCHER_NESTED_GROUP_ENABLED
> add functional and RBAC tests for group global role binding

- tests/validation/tests/v3_api/test_monitoring.py
the graph `etcd-peer-traffic ` is available only when there are more than 1 etcd node, so 
- remove it from the list if only 1 etcd node exists
- otherwise, keep it
> check the graph etcd-peer-traffic only when there are more than one etcd node

- tests/validation/lib/aws.py
Adds SUSE_12_SP5_Docker_19.03.1 - ami-01ce18de2d77aa82f to OS validation job.
> Add SUSE sp5 AMI

- pkg/app/utils/utils.go
- pkg/controllers/user/cis/clusterScanHandler.go
- pkg/controllers/user/monitoring/clusterHandler.go
- pkg/controllers/user/monitoring/operatorHandler.go
- pkg/controllers/user/monitoring/projectHandler.go
Problem:
Monitoring - app and namespace are left when deleting the project
Solution:
If the namespace's creatorID is null, it wouldn't remove the namespace when deleting the project.
https://github.com/rancher/rancher/blame/fa26eccdb1ec6d9065877340f6b90ef374969adf/pkg/controllers/user/rbac/project_handler.go#L66
so add parameter creatorID for function EnsureAppProjectName can fix it.
Related Issue: 
https://github.com/rancher/rancher/issues/23848
> Fix the problem Monitoring - app and namespace are left when deleting the project

- pkg/api/customization/workload/workload.go
- tests/integration/suite/test_workloads.py
Exposed redeploy REST API to the workload which set sets `cattle.io/timestamp` annotation to the current time.
Related issue: https://github.com/rancher/rancher/issues/23053
Related types PR: https://github.com/rancher/types/pull/1066
> Add redeploy to workload API and integration test

- app/authconfig_data.go
- pkg/api/controllers/samlconfig/samlconfig.go
- pkg/api/store/auth/store.go
- pkg/auth/providers/common/ldap/ldap_util.go
- pkg/auth/providers/ldap/ldap_actions.go
- pkg/auth/providers/ldap/ldap_client.go
- pkg/auth/providers/ldap/ldap_provider.go
- pkg/auth/providers/providers.go
- pkg/auth/providers/publicapi/handler.go
- pkg/auth/providers/publicapi/login.go
- pkg/auth/providers/saml/saml_client.go
- pkg/auth/providers/saml/saml_provider.go
- pkg/auth/providers/setup.go
- tests/integration/suite/test_auth_configs.py
Adds a new SAML auth provider for Shibboleth but couples it with OpenLDAP searching for Principals. It operates as a standalone SAML provider with no needed extra configs but if you backend Shibboleth with OpenLDAP you can configure it like a regular OpenLDAP auth provider but only works for get/search so you can find and assign principals to Clusters/Projects/etc.
This PR explicitly avoids Refetching principals, please see this Issue to track potentially adding that functionality: https://github.com/rancher/rancher/issues/25397
**Overview**
- Added Shibboleth as a new Auth Provider
- Added OpenLdapFields to Shibboleth Auth Type to store params
- Cut into functionality in SAML provider to call out to ldap provider (GetPrincipal/SearchPrincipal)
- Added store/retrieve of secrets from sub …
> Adding shibboleth + OpenLDAP Search Auth Provider

- go.mod
- go.sum
- pkg/api/customization/roletemplatebinding/validator.go
- tests/integration/suite/test_cluster_role_template_bindings.py
- tests/integration/suite/test_project_role_template_bindings.py
- tests/integration/suite/test_role_template.py
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/authz_types.go
- vendor/modules.txt
**Dependency:**
types (merge first): https://github.com/rancher/types/pull/1042
**Problem:**
CRTBs and PRTBs can currently target both, a user and a group, or neither. Those are invalid and will cause handlers to continuously fail.
**Solution:**
Add a validator to ensure CRTBs and PRTBs are target a user or (exclusive) a group.
**Issue:**
https://github.com/rancher/rancher/issues/24036
> Validate CRTB and PRTB targets

- pkg/controllers/management/clusterprovisioner/provisioner.go
- pkg/tunnelserver/tunnel.go
There can be a situation when the `cluster.status.driver` field remains empty on rke clusters even after the cluster is provisioned. The issue was addressed by @rmweir in the following commit:
https://github.com/rancher/rancher/commit/03dd1256a789ccb11299c3edea23549466a0cb04
This particular PR is to address the issue when cluster-agent on its connect sets the `cluster.status.driver` field to "imported" if the field is empty. That results in provisioning code never being invoked on subsequent cluster updates for rke clusters. 
The fix introduces a check for figuring out if the cluster really qualifies for imported, before marking it this way. So if you are upgrading from the older version of rancher where the `cluster.status.driver`  is already set to "" on rke cluster(s), it will never …
> Fix for cluster driver reset

- pkg/controllers/user/alert/deployer/deployer.go
Problem:
Alerting can not be enabled
Solution:
If it is the first time to deploy cluster-alerting, the variable “app” is null in here.
https://github.com/rancher/rancher/blob/master/pkg/controllers/user/alert/deployer/deployer.go#L288
https://github.com/rancher/rancher/blob/master/pkg/controllers/user/alert/deployer/deployer.go#L292
So we need to check if it's null.
Related Issue:  
https://github.com/rancher/rancher/issues/25507
> Fix the problem alerting can not be enabled

- pkg/api/customization/cluster/actions_etcd.go
- pkg/controllers/management/etcdbackup/etcdbackup.go
Rebase of this PR which is already approved: https://github.com/rancher/rancher/pull/25545
The snapshot process only stores some basic metadata, this will add the entire cluster object in order to help track the state of the cluster when the backup is made. A restoreRkeConfig was added to the etcd restore action which supports "all" and "kubernetesVersion" meaning during the restore you can choose to restore the entirety of the cluster config or leave the cluster config as is and only restore the kubernetes version.
#22232 
types: https://github.com/rancher/types/pull/1101
> RKE Config Added to Backups and Restore Options for version/config

- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/test_logging_e2e.py
- tests/validation/tests/v3_api/test_websocket.py
This job deploys a fluentd aggregator app in a new project/namespace in Rancher and we setup cluster logging pointing to the aggregator host and port. And then:
- Activates cluster logging
- Parses the container view logs using websocket waiting for a `log_type` or `"{log"` string indicating that the aggregator is receiving the logs from Rancher
- Removes the aggregator project and disables cluster logging.
Then we do the same with a new aggregator app but we setup the `System` project logging  pointing to the aggregator's host and port, then:
- Activates project logging
- Parses the fluentd aggregator container view logs using websocket waiting for a `log_type` or `"{log"` string indicating that the aggregator is receiving the logs from Rancher.
- Removes the aggregator project and …
> [Automation] - fluentd logging e2e test

- pkg/auth/tokens/manager.go
**Problem**
When a first time user logs in via SAML their group principals are not set, subsequent logins it does work. You can easily recreate this by logging in with a new user and going to /v3/principals, logout and login again and now groups will show up. You can delete the user via an Admin user and recreate this every time.
**Solution**
Logic is a little off in tokens.UserAttributeCreateOrUpdate. The create logic is under the update logic and the SAML user will get caught in the update logic and ultimately return without saving the UserAttribute.
> SAML Logins Group Principals Not Created on First Login

- pkg/controllers/management/clusterprovisioner/provisioner.go
K3sConfig will be populated on initiation to provide defaults for the
UI.
Part of https://github.com/rancher/rancher/issues/25371
> Set K3sConfig on init

- pkg/controllers/management/certsexpiration/certsexpiration.go
- pkg/controllers/management/controller.go
- pkg/controllers/user/certsexpiration/certsexpiration.go
- pkg/rkecerts/expiration.go
- pkg/rkecerts/expiration_test.go
Issue: https://github.com/rancher/rancher/issues/23543
Implements management controller to check for RKE's `full-cluster-state` configMap for expiring certs. Re-used lots of the user-controller code which checked downstream clusters, so I moved that into pkg to share. 
**Requires UI update**: The UI shows the warning but it also shows option to rotate certificates, which the local cluster can't do because it doesn't have an RKE Config. UI should be able to check and see if rotate action exists on the cluster, and if not then [hide the link](https://github.com/rancher/ui/blob/master/lib/monitoring/addon/components/cluster-dashboard/template.hbs#L1-L3).
> Adds cert expiration warnings for local cluster

- .drone.yml
- manifest-agent.tmpl
We need the agent tag to be unique for master builds so that when
you upgrade you always get the proper agent image pushed to the
downstream clusters.
> On master create agent image with build number in it

- tests/validation/lib/aws.py
- tests/validation/lib/node.py
- tests/validation/tests/v3_api/common.py
- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
- tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test
- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
- tests/validation/tests/v3_api/test_windows_cluster.py
Added ability to create Windows nodes and execute commands with `node.exec_command`
* Nodes must be created w/ `create_multiple_nodes`
* See example `test_windows_cluster.py`
* Windows nodes default to 100gb volume and t3.xlarge instance size
> Validation - Provision Windows custom cluster

- pkg/controllers/management/drivers/nodedriver/utils.go
array[string] in the dynamicschemas were a little annoying to edit in the api ui because they default to null when an empty array `[]` is sent over. On edit you would have to change each one to [] or "" to make it save properly.
> Nodedriver Schemas, Defaulting array[string] to Nullable

- pkg/controllers/management/clusterprovisioner/provisioner.go
When RKE up provisions cluster and Provisioned condition is set to True, cluster.Status.Driver might not have been set yet when k3sClusterConfig is called. Which causes it to return error `"waiting for full cluster configuration"`. Due to which `reconcileCluster` calls `driverCreate` again which causes RKE to consider it as a newly generated cluster and RKE regenerates certs for it.
> Skip k3sClusterConfig for RKE and hosted k8s clusters

- tests/validation/tests/v3_api/test_websocket.py
Problem:
A wrong system project is used when there are multiple clusters in the setup
Solution:
Filter projects with both project name and cluster id
> A wrong system project is used when there are multiple clusters in the setup

- Dockerfile.dapper
**Problem** 
Hitting rate limit for github api calls when helm-unittest plugin was being install
**Solution** 
Rewrite plugin install script to pull the binary down directly based on a new `HELM_UNITTEST_VERSION` env var and existing `ARCH` env var from dapper file
**Issue** 
#25660 
**Dependent on**
https://github.com/rancher/helm-unittest/pull/7
> Add helm unitttest version env var

- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
When scaling up existing node pool , it is required to pass `nodeTemplateId` without which we get the following error:
```
rancher.ApiError: (ApiError(...), "NotFound : unable to find node template []\n\t{'baseType': 'error', 'code': 'NotFound', 'message': 'unable to find node template []', 'status': 404, 'type': 'error'}")
```
Fix is made to pass  `nodeTemplateId` when scaling up existing node pool.
> Fix nodepool scaling

- pkg/rkecerts/certs.go
The SafeMarshal() function inside of rkecerts did not effectively set
the key field to nil.
> Fix ineffective assignment in rkecerts

- tests/validation/lib/aws.py
- tests/validation/tests/v3_api/test_ebs_volume_backed_instance.py
- tests/validation/tests/v3_api/test_rke_cluster_provisioning.py
This commit contains a validation test that ensures that Rancher can spin up an EC2 cluster and define a node template with encryptEbsVolume, which creates a node pool consisting of encrypted EBS volume backed EC2 instances.
Related Issue: #22691
> Add validation test for encrypted EBS volume-backed instance

- app/app.go
- main.go
https://github.com/rancher/rancher/issues/24994
Basically the same approach as described in https://github.com/rancher/rke/pull/1939#issue-383010276
It could have gone outside of the struct (`c.Bool`) but as Debug is there as well, I added it in.
> Add flag to enable TRACE logging

- .gitignore
- Dockerfile.dapper
- go.mod
- go.sum
- package/Dockerfile
- package/jailer.sh
- package/kustomize.sh
- pkg/catalog/manager/crd.go
- pkg/catalog/manager/traverse.go
- pkg/controllers/user/helm/common.go
- pkg/controllers/user/helm/common/common.go
- pkg/controllers/user/helm/controller.go
- tests/integration/suite/test_rbac.py
- vendor/github.com/rancher/types/apis/management.cattle.io/v3/catalog_types.go
- vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_catalog.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_catalog_spec.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_catalog.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_project_catalog.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_template_status.go
- vendor/github.com/rancher/types/client/management/v3/zz_generated_template_version_status.go
- vendor/modules.txt
**Problem**
Helm released Helm 3 and new applications need to be deployed using helm in order to support the newest features offered by helm 3 charts
**Solution** 
Add helm 3 to rancher while keeping currently deployed apps maintained with helm 2
**Issues** 
#25260 
#25261 
#21070 
#25262 
**Dependent on**
https://github.com/rancher/helm-unittest/pull/6
https://github.com/rancher/types/pull/1095
https://github.com/rancher/kustomizebuild/pull/1
https://github.com/rancher/types/pull/1106
> [2.4] Add Helm 3 app & multi-cluster deployment support

- pkg/auth/tokens/manager_test.go
- pkg/auth/tokens/sha256.go
- pkg/auth/tokens/sha256_test.go
- pkg/auth/tokens/token_util.go
Issue: https://github.com/rancher/rancher/issues/25786
Notes: 
* Can't use Sscanf for parsing format because go stumbles on multiple strings not delimited by spaces, so had to go the split route.
* hashedSecretKey is actually a `[]uint8` but thats basically a byte so comparison is ok. The `[:]` converts array to slice.
> Token hashing uses sha256

- pkg/rbac/access_control.go
- pkg/rbac/user_based.go
When multiple goroutines are spawned per request and access control is checked across multiple contexts there ends up being multiple locks for the same map. The fix is to have the lock instantiated at the same time as the protected map.
> Fix panic in access control lookup

- pkg/controllers/management/k3supgrade/deployPlans.go
- pkg/controllers/management/k3supgrade/k3supgrade_handler.go
- pkg/controllers/management/k3supgrade/register.go
- pkg/controllers/management/k3supgrade/template.go
K3s clusters will now correctly report their state as during an upgrade and it will be reflected in the UI.
https://github.com/rancher/rancher/issues/25371
> Fix state for upgrading k3s clusters

- pkg/controllers/management/k3supgrade/deployPlans.go
Previously, the usage of pointers was incorrect and would only point towards the last memory location pointed to by '&plan'. Now uses the memory location of elements in the slice.
Fixes only master nodes being upgraded
Fixes https://github.com/rancher/rancher/issues/25865
> Correctly update worker plans

- pkg/controllers/user/helm/common/common.go
**Problem**
Duplicate revisions were being created. Helm 3 no longer uses tiller, so max history was not being set. Helm 2 utilizes `TILLER_MAX_HISTORY`
**Solution**
Set history max for helm 3 using the `--history-max` flag to ensure the correct number of revisions were being created
**Issue**
#25846
> Add max history helm3

- pkg/agent/main.go
Problem:
Today if node is deleted from rancher, we immdiately delete v1.node from
kubernetes. Since we don't clean up agent(or did a poor job in cleaning
agent). All the system containers keep running including kubelet. This
will cause kubelet keep throwing node not found error. This is because
kubelet only register new node at start up, and without restart kubelet
it will not re-register node again. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L52
Solution:
In our agent code, add kubelet restart logic. Notice that this logic is
only added into unmanaged agent(which is only added through docker run
command). This is because once managed agents are added, kubelet should
be ready since managed agents are pods from daemonset which mean the
node is …
> Fix kubelet needs to be restart if node is deleted in UI

- pkg/controllers/management/rkeworkerupgrader/node.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
- pkg/rkenodeconfigserver/nodeserver.go
- update unavailable nodes active after reconciling
https://github.com/rancher/rancher/issues/25878 
https://github.com/rancher/rancher/issues/25872 
- nonworker nodes asking for plan 0 seconds, thanks to @superseb for testing it out
> rke worker upgrade fixes 

- pkg/controllers/management/k3supgrade/deployPlans.go
- pkg/controllers/management/k3supgrade/k3supgrade_handler.go
Previously, the state transition logic assumed that the worker plans would always be applied. That is not the case in a single-node controlplane k3s cluster.
To leave the updating state now, there is no requirement that the last plan to have been applying was a worker plan.
Addresses https://github.com/rancher/rancher/issues/25869
> Correctly transitions through upgrading states for single node k3s upgrade

- pkg/controllers/management/k3supgrade/template.go
- pkg/controllers/management/k3supgrade/template_test.go
The prepare image is no longer hardcoded and it will be parsed to
convert a k3s release tag to an k3s-upgrade image. ie v1.17.3+k3s1 => v1.17.3-k3s1
Addresses https://github.com/rancher/rancher/issues/25907
> Parse version of k3s prepare image

- pkg/encryptedstore/secrets_store.go
Throughout cluster provisioning kontainer-engine saves the cluster with different statuses by calling GenericEncryptedStore.Set
Sometimes creating/updating these secrets wasn't saving the cluster with the desired status, leading to some intermittent errors during cluster provisioning.
This commit adds the following changes to ensure cluster gets saved with the correct status
1. If cluster secret create returns IsAlreadyExists, get the secret object and update
it with current expected value
2. When updating a secret, update the object obtained from DeepCopy and not the one returned
from lister.
https://github.com/rancher/rancher/issues/25554
https://github.com/rancher/rancher/issues/25524
> Modify GenericEncryptedStore set secret logic

- pkg/controllers/user/logging/generator/templatesource.go
…(#25049)
adds skip_refresh_on_startup and read_from_head to fluentd collector
Problem: The delay between the start of the pods and the start of logging.
Fluentd collector is using the `@type tail`, which will only send new log
events. Starting with the end of file position from the when it became aware of
the log file.  This prevents centralized logging from collecting the output of
the pods starting up.
Solution: Setting `read_from_head true` causes the fluentd collector to read
the file from the beginning and forward.  `skip_refresh_on_startup true` makes
this processess start a little faster.
Issue: https://github.com/rancher/rancher/issues/25048
> Cherry-pick fix for #25048

- tests/validation/Dockerfile.v3api
- tests/validation/tests/v3_api/cli_common.py
- tests/validation/tests/v3_api/cli_objects.py
- tests/validation/tests/v3_api/scripts/build.sh
- tests/validation/tests/v3_api/scripts/configure.sh
- tests/validation/tests/v3_api/test_cli.py
- Is part of v3_api as it will use the API/rancher Client in some tests for comparisons and to retrieve object IDs that are otherwise not available in the CLI
- Uses a logging framework instead of prints
- Broken up into classes for cli object types to keep concerned areas focused in specific parts
> Initial test architecture and validation tests for rancher cli

- pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
there was a bug in kubectl related to how timeout was respected
during drain, they fixed it and also changed the err msg.
we need to include that in our ignoreErr list, so we don't retry
draining node in that scenario.
#26010
> ignore global timeout error from kubectl drain

- pkg/api/store/cluster/cluster_store.go
- pkg/controllers/management/rkeworkerupgrader/upgrade.go
With introduction of maxUnavailable, we want to make sure we check if there are ready nodes to upgrade or else just error out. 
https://github.com/rancher/rancher/issues/26005
> validate number of notReady nodes on cluster update

- pkg/controllers/management/k3supgrade/deployPlans.go
- pkg/controllers/management/k3supgrade/k3supgrade_handler.go
Problem: Previously the updating state would be set after plans were
deployed into the downstream cluster which meant that the whole helm
install would need to occur before the cluster entered upgrading.
Solution: When an upgrade is determined to be necessary, the cluster
state is updating. This is before the system-upgrade controller is
deployed.
Addresses https://github.com/rancher/rancher/issues/26024
> Set upgrading status sooner

- pkg/pipeline/remote/gitlab/gitlab.go
In recent Gitlab version, the Oauth API returns Bearer token type instead of bearer as shown in the docs, making the condition check here fails.
https://github.com/rancher/rancher/issues/25975
> [2.3] Fix Gitlab pipeline integration issue

- pkg/pipeline/remote/gitlab/gitlab.go
In recent Gitlab version, the Oauth API returns Bearer token type instead of bearer as shown in the docs, making the condition check here fails.
https://github.com/rancher/rancher/issues/25975
> Fix Gitlab pipeline integration issue
