README.md
@cloudnautique please weigh in
=> mention terraform as an installation method

agent/run.sh
addressses https://github.com/rancher/rancher/issues/10001
=> Support RANCHER_DEBUG

agent/run.sh
addresses  https://github.com/rancher/rancher/issues/8816
Supersedes https://github.com/rancher/rancher/pull/8822
Test run with:
```
http://10.0.0.1                         : bad
127.0.0.1                               : bad
4.2.2.2                                 : good
a.b.c.d                                 : bad
192.168.1.1                             : good
0.0.0.0                                 : bad
http://192.168.99.100:8080/             : bad
http://172.16.0.10:8080                 : bad
https://128.0.0.1                       : bad
255.255.255.255                         : bad
255.255.255.256                         : bad
192.168.0.1                             : good
192.168.0                               : bad
1234.123.123.123                        : bad
127.0.0.1/8 …
```
=> Add IP validation for CATTLE_AGENT_IP

agent-windows/Dockerfile, agent-windows/build-image.ps1, agent-windows/run.ps1
refer to https://github.com/rancher/rancher/issues/10448
and https://github.com/rancher/rancher/issues/10442
Add a new image to bootstrap windows host agent service.
=> Add windows bootstrap agent image

scripts/print-catalog-images/print-catalog-images.py
=> Replace template values with actual values in print-catalog-images

app/rolebuilder.go
Properly check roleTemplateNames
Set external properly
=> Fix bugs in rolebuilder

scripts/update-vendor-conf.sh
Script will update all github.com/rancher repos to HEAD of the
master branch
=> Add script to update vendor.conf

app/app.go
=> Fine-grained global permissions

server/capabilities/gke_version_endpoint.go, server/server.go
Adding capabilities endpoint for querying the available k8 zones.
=> Adding gke capabilities endpoint for querying available k8 zones

.dockerignore, .gitignore, management-state/machine-drivers/1f7058341420e2f525168052818c3f819ff78e9ca5f57d5a650a049bcd5945e9, server/capabilities/gke_version_endpoint.go, server/server.go
Reverting revert of gee compatibility endpoint, and also using a global mutex to avoid nil reference panics.
=> Revert revert of gke compatibility endpoint

server/capabilities/gke_capabilities.go, server/capabilities/gke_machine_types_endpoint.go, server/capabilities/gke_version_endpoint.go, server/capabilities/gke_zones_endpoint.go, server/server.go
Adding machine type and zones capabilities endpoints to rancher so we can display a dynamic list on the gui.
=> Machine type and zones endpoints

app/app.go, main.go, package/Dockerfile, scripts/package, server/server.go, server/ui/ui.go, vendor.conf, vendor/github.com/rancher/management-api/api/machine/machine_driver.go, vendor/github.com/rancher/management-api/controller/listener/server.go, vendor/github.com/rancher/management-api/controller/settings/settings.go, vendor/github.com/rancher/rke/cluster/reconcile.go, vendor/github.com/rancher/rke/services/kubeapi.go
=> Cleanup build scripts

scripts/print-catalog-images/print-catalog-images.py
- Recovers the fix for compatibility with templates catalog files
- Adds a flag to list Kubernetes addons images
=> Print catalog images k8s

agent-windows/tools/run.ps1
Related issue https://github.com/rancher/rancher/issues/11173
Check download folder before remove it.
=> Fix The Remove-item Error for Windows Bootstrap Script

pkg/api/management/api/authn/githubconfig_actions.go, pkg/auth/providers/github/github_client.go, pkg/auth/providers/github/github_provider.go, pkg/auth/providers/provider.go, pkg/auth/tokens/api_server.go, pkg/auth/tokens/route_handlers.go, pkg/auth/tokens/token_util.go
Adding implementation for configuring github by doing github login and fetching user/groups.
Also supports search github user/groups
@cjellick pls. review
=> Adding github provider implementation

pkg/controllers/management/clusterprovisioner/provisioner.go, scripts/validate, vendor.conf, vendor/github.com/rancher/kontainer-engine/.gitignore, vendor/github.com/rancher/kontainer-engine/drivers/import/import_driver.go, vendor/github.com/rancher/kontainer-engine/drivers/utils.go, vendor/github.com/rancher/kontainer-engine/plugin/drivers.go, vendor/github.com/rancher/kontainer-engine/service/service.go, vendor/github.com/rancher/kontainer-engine/store/clistore.go, vendor/github.com/rancher/kontainer-engine/store/filestore.go, vendor/github.com/rancher/kontainer-engine/store/types.go, vendor/github.com/rancher/kontainer-engine/utils/utils.go, vendor/github.com/rancher/kontainer-engine/utils/writer.go
Move import driver from rancher/rancher to kontainer-engine
I also added a path argument to find in the validate script, so Mac people can run it locally (it defaults to `.` on GNU distros)
=> Add import driver

pkg/api/customization/alert/alert_action.go, pkg/api/customization/alert/notifier_action.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/alert/config/config.go, pkg/controllers/user/alert/config/notifiers.go, pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/deploy/deployer.go, pkg/controllers/user/alert/manager/manager.go, pkg/controllers/user/alert/statesyncer/statesyncer.go, pkg/controllers/user/alert/watcher/daemonset.go, pkg/controllers/user/alert/watcher/deployment.go, pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/statefulset.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/controllers.go
Related issue: rancher/rancher#11170
=> add implementation for alerts

pkg/api/controllers/listener/server.go, pkg/api/server/managementstored/setup.go, pkg/api/store/userscope/store.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rke_config_node.go
Allow https to proxy http port
=> scope NodeTemplates to the user

app/rolebuilder.go, k8s/apiserver/apiserver.go, pkg/auth/principals/handler.go, pkg/catalog/helm/helm.go, pkg/catalog/manager/crd.go, pkg/catalog/manager/traverse.go, pkg/controllers/management/auth/indexes.go, pkg/controllers/user/workloadservice/workloadservice.go
Hi,
I have fixed some var declarations.
I would like you to review :smile:
=> [Fix] declare slice with nil

pkg/api/server/userstored/setup.go, pkg/api/store/ingress/store.go, pkg/controllers/user/controllers.go, pkg/controllers/user/dnsrecord/dnsrecord.go, pkg/controllers/user/ingress/ingress.go, pkg/controllers/user/util/util.go, pkg/controllers/user/workload/workload.go, pkg/controllers/user/workloadservice/workloadservice.go
1) Create headless service for every object of type workload
2) Fixed workload service (service having workloadIds) to consider other workload types, not just deployments
3) Fixed ingress to work with workloads
=> Ingress and workload service fixes

pkg/controllers/user/util/util.go
so the indication who created the service is clear.
=> Changed name generation for service created by workload controller

app/app.go, pkg/auth/requests/authenticate.go, pkg/auth/tokens/purge_daemon.go, pkg/auth/tokens/server.go, pkg/auth/tokens/token_util.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3public/authn_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rke_config_node.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rke_system_images.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_token.go, vendor/github.com/rancher/types/client/management/v3public/zz_generated_token.go
Add a daemon for purging expired tokens
Add fields for when the token will expire and if it is already
expired
=> Token expiration logic

pkg/settings/setting.go
https://github.com/rancher/types/pull/221
https://github.com/rancher/rancher/issues/11363
=> Move k8s SystemImages Defaults to types

pkg/api/store/secret/store.go, pkg/controllers/user/secret/secret.go
=> filter namespacedSecret

pkg/api/customization/alert/alert_action.go, pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/statesyncer/statesyncer.go, pkg/controllers/user/alert/watcher/daemonset.go, pkg/controllers/user/alert/watcher/deployment.go, pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/statefulset.go, pkg/controllers/user/alert/watcher/syscomponent.go, tests/core/test_node.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/alerting_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/pipeline_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_alert_status.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_alert.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_node.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_node_spec.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_notifier.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline_execution.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline_execution_status.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline_status.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_project_alert.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging.go
https://github.com/rancher/types/pull/231 change field from State to AlertState.  This PR make the corresponding change.  This should be merged immediately after the types PR is merged
=> Change field name for alert

pkg/api/customization/alert/alert_action.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/alert/manager/manager.go, pkg/controllers/user/alert/watcher/daemonset.go, pkg/controllers/user/alert/watcher/deployment.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/statefulset.go
Related issues: #11439, #11445
=> fix concurrent map writes and alertmanager cpu high

pkg/controllers/user/util/util.go
Pull from API, not cache, to ensure service existence to avoid race conditions
=> Workload services: autogenerate name

pkg/api/customization/alert/notifier_action.go
https://github.com/rancher/rancher/issues/11566
https://github.com/rancher/rancher/issues/11569
=> Fix notifier send action related issues

pkg/api/store/ingress/store.go, pkg/controllers/user/ingress/ingress.go
https://github.com/rancher/rancher/issues/11598
=> Ingress bug fixes

.gitignore, pkg/controllers/user/authz/podsecuritypolicy/cluster.go, pkg/controllers/user/authz/podsecuritypolicy/metadata.go, pkg/controllers/user/authz/podsecuritypolicy/project.go, pkg/controllers/user/authz/podsecuritypolicy/serviceaccount.go, pkg/controllers/user/authz/podsecuritypolicy/template.go, pkg/controllers/user/controllers.go
https://github.com/rancher/rancher/issues/11159
=> Pod security

pkg/api/customization/pipeline/cluster_pipeline.go, pkg/api/customization/pipeline/pipeline.go, pkg/api/customization/pipeline/source_code_credential.go, pkg/api/customization/pipeline/utils.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/pipeline/controller/clusterpipeline/clusterpipelinesyncer.go, pkg/controllers/user/pipeline/controller/pipeline/cronsyncer.go, pkg/controllers/user/pipeline/controller/pipelineexecution/logsyncer.go, pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go
1. Fix https://github.com/rancher/rancher/issues/11618
2. Fix filter for repositories for https://github.com/rancher/rancher/issues/11628
3. Fetch repositories on adding a sourceCodeCredential so that users don't need to manually refresh every time
4. Change some debug logs to avoid polluting
5. Update API handlers to use lister for get/list
=> fix pipeline cleanup and filter for repositories

pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/deploy/deployer.go, pkg/controllers/user/alert/statesyncer/statesyncer.go, pkg/controllers/user/alert/watcher/daemonset.go, pkg/controllers/user/alert/watcher/deployment.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/statefulset.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/nodesyncer/nodessyncer.go, pkg/node/node.go
1. fix issue https://github.com/rancher/rancher/issues/11608
2. add comments to controller.
=> Fix bugs in node watcher and add comments to controllers

pkg/api/customization/logging/list_handler.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/logging/utils/configmap.go
Related Issue:
https://github.com/rancher/rancher/issues/11560
Should not return error when could not get embedded deploy info.
https://github.com/rancher/rancher/issues/11563
Update configmap failed.
@alena1108 Could you help review? thank you.
=> Fix logging bug

pkg/api/customization/app/app.go, pkg/api/customization/catalog/filter.go, pkg/api/server/managementstored/setup.go, pkg/catalog/manager/crd.go, pkg/catalog/manager/manager.go, pkg/catalog/manager/sync.go, pkg/catalog/manager/traverse.go, pkg/controllers/user/helm/controller.go, pkg/controllers/user/helm/utils/utils.go
add ability to parse readme and get questions, delete user and group
code for rbac, support values.yaml as answer in the backend
=> more catalog improvements

pkg/controllers/user/secret/secret.go
=> ClusterScopedLifecycle to Lifecycle for secret

pkg/api/customization/workload/aggregate_store.go
=> match for secretName=registryName

pkg/controllers/user/workload/workload.go
instead of targetWorkloadId based, to avoid unnecessary updates
=> Create selector based services for workloads

pkg/api/server/userstored/setup.go, tests/core/test_namespaced_secrets.py
=> namespacedCertificate

pkg/controllers/user/endpoints/workload_endpoints.go, pkg/controllers/user/workload/workload_common.go
as they get translated to workload.annotation in the api
=> Set public endpoints on workload.spec.template.annotations

agent-windows/tools/crash-loop.ps1, agent-windows/tools/rancher-tools.psm1, agent-windows/tools/startup.ps1
1. Fix typo in startup script
2. Add Stop-RancherComponent function in rancher-tools.psm1. Fix bug of https://github.com/rancher/rancher/issues/10662 and https://github.com/rancher/rancher/issues/11302.
=> Windows Agent Fix issue #10662 and #11302

pkg/api/customization/workload/aggregate_store.go
=> imagePullSecret fix

pkg/api/store/ingress/store.go, pkg/controllers/user/targetworkloadservice/target_workload_service.go
https://github.com/rancher/rancher/issues/11611
https://github.com/rancher/rancher/issues/11602
=> Ingress fixes

pkg/api/customization/workload/aggregate_store.go
https://github.com/rancher/rancher/issues/11750
=> Fixed proxy schema search for workload

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
Depends on:
https://github.com/rancher/kontainer-engine/pull/34
Issue:
https://github.com/rancher/rancher/issues/11528
=> Fix azure ignoring node count

pkg/api/customization/workload/aggregate_store.go
https://github.com/rancher/rancher/issues/11731
=> Default port names if more than one and not specified

pkg/api/customization/logging/list_handler.go, pkg/api/customization/logging/validator.go, pkg/controllers/user/logging/utils/embedded.go, pkg/controllers/user/logging/utils/wrap.go
@zionwu @gitlawr 
this PR is for update endpoint validate, I just miss the validate in kafka zookeeper, not add it. And the replace url.parse with url.parserequesturi, could u you help review.
=> update logging validate

pkg/api/store/ingress/store.go
=> point certificateId correctly

pkg/controllers/user/endpoints/endpoints.go, pkg/controllers/user/endpoints/workload_endpoints.go, tests/core/test_dns.py, vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/service_spec_mapper.go, vendor/github.com/rancher/types/mapper/container_ports.go
https://github.com/rancher/rancher/issues/11786
=>  Fixes around HostPort port

pkg/controllers/user/targetworkloadservice/target_workload_service.go
https://github.com/rancher/rancher/issues/11810
=> Fixed parsing for targetWorkloadIds

pkg/auth/providers/activedirectory/activedirectory_client.go
Addresses https://github.com/rancher/rancher/issues/11804
=> set provider on AD principals

pkg/controllers/user/dnsrecord/dnsrecord.go
https://github.com/rancher/rancher/issues/11811
=> Service alias fixes

pkg/controllers/user/workload/workload_common.go, vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/mapper/workload.go
https://github.com/rancher/rancher/issues/11763
=>  Save publicEndpoints to workload annotation only

pkg/controllers/user/pipeline/controller/pipeline/cronsyncer.go, pkg/controllers/user/pipeline/controller/pipeline/pipeline.go, pkg/controllers/user/pipeline/controller/pipelineexecution/logsyncer.go, pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go, pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go, pkg/controllers/user/pipeline/engine/engine.go, pkg/controllers/user/pipeline/engine/jenkins/client.go, pkg/controllers/user/pipeline/engine/jenkins/engine.go, pkg/controllers/user/pipeline/utils/constants.go, pkg/controllers/user/pipeline/utils/utils.go
Shorten log/state sync interval
Fix fetching jenkins secret in wrong plane
Fix unmatched stage state/pipeline lasterunstate
Mark executions/logs as finished when fail connecting engine to avoid
endless retry
solve https://github.com/rancher/rancher/issues/11765 and https://github.com/rancher/rancher/issues/11787
=> pipeline fixes

pkg/controllers/user/ingress/ingress.go, vendor.conf, vendor/github.com/rancher/types/mapper/workload.go
https://github.com/rancher/rancher/issues/11848
=> Fixed parsing ingress workloads

pkg/api/customization/workload/aggregate_store.go
I forgot filtering namespaced secrets, Nothing breaks since k8s pulls secrets only from the current namespace but imagePullSecrets shows wrong value.
=> imagePullSecret only if same namespace

pkg/api/customization/workload/transform_store.go, pkg/controllers/user/endpoints/endpoints.go
https://github.com/rancher/rancher/issues/11760
=> PublicEndpoints API: set nodeId to machine id

pkg/api/server/server.go
This lets us user dynamic per-cluster access control clients
when and where necessary
Addresses https://github.com/rancher/rancher/issues/11518
=> Use proper access control manager

pkg/api/store/ingress/store.go, pkg/controllers/user/secret/secret.go
#11837 + removing an extra log line, unrelated
=> call store.update on ingress update

pkg/controllers/user/pipeline/engine/jenkins/engine.go, pkg/controllers/user/pipeline/engine/jenkins/mappper.go
To solve https://github.com/rancher/rancher/issues/11872
=> catch undetected pipeline fails and use single quotes to escape anything special

pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go, pkg/controllers/user/logging/utils/wrap.go
Related Issue: https://github.com/rancher/rancher/issues/11820
Could not send log to kafka when use zookeeper endpoint. 
before format: http://ip:port
correct format: ip:port
=> remove scheme from zookeeper config

pkg/controllers/user/controllers.go
https://github.com/rancher/rancher/issues/11726
=> disabling network policy

pkg/api/store/pod/store.go, pkg/controllers/user/alert/watcher/workload.go
https://github.com/rancher/rancher/issues/11595
https://github.com/rancher/rancher/issues/11896
=> Fix pod number issue and typo

pkg/auth/providers/common/usermanager.go
When in restricted access mode, if a user belongs to
a group that has been assigned to a project or cluster, allow
that user to log in.
Addresses https://github.com/rancher/rancher/issues/11908
=> Account for group membership in restricted mode

pkg/api/customization/pipeline/cluster_pipeline.go, pkg/api/customization/pipeline/pipeline.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/pipeline/controller/pipeline/cronsyncer.go, pkg/controllers/user/pipeline/controller/pipeline/pipeline.go, pkg/controllers/user/pipeline/hooks/drivers/github.go, pkg/controllers/user/pipeline/utils/utils.go
1. support reusing global Github config when enabling pipeline, for https://github.com/rancher/rancher/issues/11656
2. add an option to run a specific branch, for https://github.com/rancher/rancher/issues/11665
3. add pipeline validator
4. fix missing triggerUser when manually run
5. fix webhook/cron updates on pipeline updates, for https://github.com/rancher/rancher/issues/11906
=> Pipeline additional options

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
Dependent on:
https://github.com/rancher/kontainer-engine/pull/37
Issue:
https://github.com/rancher/rancher/issues/11817
=> Changing error message when azure fails

pkg/api/customization/authn/rtb_store.go, pkg/api/customization/authn/user_store.go, pkg/api/server/managementstored/setup.go
Addresses https://github.com/rancher/rancher/issues/11952
=> Filter system users and CRTB/PRTBs out of the API

pkg/api/store/workload/aggregate_store.go, pkg/controllers/user/workload/workload.go
https://github.com/rancher/rancher/issues/11871
=> Workload ports update fix

pkg/controllers/user/authz/handler_base.go
kubernetes is case sensitive for role rules. This change ensures
verbs and resources are all lowercase when syncing a roleTemplate.
=> lowercase role rules

pkg/controllers/user/authz/handler_base.go
Clean roles to make them k8s compatible (lowercarse verbs and resources)
during the gathering function so that all subsequent logic that uses
the roles gets the clean versions.
Addresses https://github.com/rancher/rancher/issues/11981
=> Move role cleaning logic

pkg/auth/providers/github/github_account.go, pkg/auth/providers/github/github_client.go, pkg/auth/providers/github/github_provider.go
Also, dont log search failures as errors in logs
=> Implement real user search in github

pkg/auth/providers/github/github_provider.go, pkg/auth/providers/github/githubconfig_actions.go
If test is successful, the current user's principal is saved to the
user, so adding it to the allowed principals is to reflect that future
state.
=> Set current user as allowedPrincipal during test

pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/watcher/event.go
related issue: https://github.com/rancher/rancher/issues/12065
=> Fix typo in alert description

pkg/controllers/user/controllers.go, pkg/controllers/user/networkpolicy/netpol.go, pkg/controllers/user/networkpolicy/nodehandler.go, pkg/controllers/user/networkpolicy/nssyncer.go, pkg/controllers/user/networkpolicy/pnpsyncer.go, pkg/controllers/user/networkpolicy/podhandler.go, pkg/controllers/user/networkpolicy/register.go, pkg/controllers/user/networkpolicy/servicehandler.go
https://github.com/rancher/rancher/issues/11726
https://github.com/rancher/rancher/issues/11776
https://github.com/rancher/rancher/issues/11777
=> network policy fixes

pkg/clusteryaml/local.go, vendor.conf, vendor/github.com/rancher/types/README.md, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rancher_kubernetes_engine_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rke_config_node.go, vendor/github.com/rancher/types/mapper/workload.go
https://github.com/rancher/types/pull/287
=> Upgrade k8s to v1.8.9-rancher1-1

pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/activedirectory/provider.go
Also minor cleanup around principal search for AD
=> Implement AD principal-by-id

pkg/api/customization/pipeline/cluster_pipeline.go, pkg/api/customization/pipeline/pipeline.go, pkg/api/customization/pipeline/pipeline_execution.go, pkg/api/customization/pipeline/source_code_credential.go, pkg/api/customization/pipeline/source_code_repository.go, pkg/api/customization/pipeline/utils.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go, pkg/controllers/user/pipeline/remote/github/github.go, pkg/controllers/user/pipeline/remote/model/model.go, pkg/controllers/user/pipeline/utils/utils.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/pipeline_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline_execution_log_spec.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline_execution_spec.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_pipeline_spec.go
Dependent on https://github.com/rancher/types/pull/286
Related issue: https://github.com/rancher/rancher/issues/11675
=> Support import/export pipeline

app/role_data.go
Addresses:
https://github.com/rancher/rancher/issues/12049
https://github.com/rancher/rancher/issues/11104
Also removes unneeded roles
Also renames the roles' ids from the form `<verb>-<resource>` to `<resource>-<verb>` to help the UI in ordering them
=> Modification to RoleTemplates and GlobalRoles

pkg/rbac/access_control.go, pkg/rbac/list_permission_store.go, pkg/rbac/permission_index.go
=> Rename RBAC functions for clarity

.gitignore
https://github.com/rancher/go-skel/pull/16
=> trash.lock to gitignore

pkg/controllers/user/authz/handler_base.go, pkg/controllers/user/authz/roletemplate_handler.go
When a RoleTemplate's rules are changed in the mgmt cluster, every
user cluster where that RoleTemplate is referenced needs to have the
corresponding ClusterRole updated.
We had logic for this before but it was not working because the handler
was registered as a "ClusterScopedLifecycle", but RoleTemplate is not
a cluster scoped resource, it is global.
To avoid propogating all RoleTemplates to all clusters, this change also
takes the logic for creating a clusterRole out of the RoleTemplate handler.
The clusterRole will be created on the fly when a PRTB/CRTB uses the RT.
Addresses https://github.com/rancher/rancher/issues/11147
=> Sync RoleTemplate and ClusterRole

pkg/controllers/management/node/controller.go, pkg/tunnelserver/tunnel.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go
Related Issue: https://github.com/rancher/rancher/issues/11341
Add support to update role for adding customer node.
=> make add customer node support update role

pkg/api/customization/cluster/formatter.go, pkg/api/server/managementstored/setup.go, pkg/kubeconfig/kubeconfig.go
https://github.com/rancher/types/pull/299
https://github.com/rancher/rancher/issues/12156
=> Kubeconfig generation on api level

pkg/api/store/pod/owner.go
Related issue
https://github.com/rancher/rancher/issues/11931
Parse owner from job to cronjob for pod.
=> Fix Can't List Pod of Cronjob

pkg/catalog/manager/traverse.go
User now can define a questions.yml under their charts and catalog service will parse it into each template version and show them in api.
=> add ability to parse questions.yml

app/role_data.go
This effectively makes them a cluster-wide read-only user
addresses https://github.com/rancher/rancher/issues/11111
=> View all projects can see into every project

app/role_data.go, pkg/controllers/management/auth/manager.go, pkg/controllers/management/auth/prtb_handler.go
This effectively makes them a cluster-wide read-only user
Addresses:
- https://github.com/rancher/rancher/issues/12035
- https://github.com/rancher/rancher/issues/12230
- https://github.com/rancher/rancher/issues/12231
=> Fix some role permissions

pkg/controllers/management/nodedriver/machine_driver.go
Fix an issue where you can't add custom node driver through API and dynamic schema won't show up.
=> use displayName for node driver

app/machinedriver_data.go
Related issue:
https://github.com/rancher/rancher/issues/10888
update the packet docker-machine driver. The latest one have some issue make it provision failed:
https://github.com/packethost/docker-machine-driver-packet/issues/22
=> update the packet driver

pkg/controllers/user/networkpolicy/netpol.go, pkg/controllers/user/networkpolicy/nssyncer.go, pkg/controllers/user/networkpolicy/pnpsyncer.go, pkg/controllers/user/networkpolicy/projectsyncer.go
https://github.com/rancher/rancher/issues/12154
=> handling objects being deleted for network policy

pkg/controllers/management/clusterprovisioner/provisioner.go
https://github.com/rancher/rancher/issues/11152
=> Set cluster updated cond to unknown once node is added/deleted

package/Dockerfile.agent, pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/watcher/event.go, pkg/systemtemplate/template.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/alerting_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_target_event.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_target_workload.go
Includes: Change from type to eventType for targetEvent
=> Fixes for kubeshell packaging

app/machinedriver_data.go, pkg/api/controllers/whitelistproxy/whitelistproxy.go, pkg/api/server/server.go, pkg/controllers/management/compose/wait.go, pkg/settings/setting.go, server/server.go, server/whitelist/whitelist.go
https://github.com/rancher/types/pull/312
=> Rewrite whitelist proxy

pkg/controllers/user/networkpolicy/nodehandler.go, pkg/controllers/user/networkpolicy/register.go, pkg/controllers/user/nodesyncer/nodessyncer.go
https://github.com/rancher/rancher/issues/12154
=> watching all nodes key, instead of individual nodes

pkg/controllers/user/logging/utils/wrap.go
Related issue: https://github.com/rancher/rancher/issues/11950
Add url access precheck in validation.
=> add reachable precheck

pkg/api/store/node/store.go, pkg/api/store/workload/transform_store.go
https://github.com/rancher/rancher/issues/12225
=> PublicEndpoint fixes for node

pkg/controllers/management/auth/user.go
Currently when a user is deleted from Rancher, their user token is not
being deleted.  This manifests as a unclear error message when the user
attempts to modify or query the k8s cluster via kubectl.
This changes the user lfc to delete the token while the other user
bindings are being deleted.
Issue:
https://github.com/rancher/rancher/issues/12287
=> Clean up user token after deletion

pkg/controllers/user/nodesyncer/nodessyncer.go
related issue: https://github.com/rancher/rancher/issues/11532
=> Set requestedHostname in nodesyncer

pkg/controllers/user/logging/generator/cluster_template.go
Related RKE PR https://github.com/rancher/rke/pull/425
Related issue https://github.com/rancher/rke/issues/412
Support collect RKE log.
=> Support collect rke log

pkg/controllers/user/networkpolicy/netpol.go, pkg/controllers/user/networkpolicy/register.go
https://github.com/rancher/rancher/issues/12154
=> switching to rancher client for network policy

pkg/controllers/user/authz/podsecuritypolicy/serviceaccount.go
Sometimes when a role binding is deleted it fails show when the delete is
followed by an immediate `.Get`.  This causes the default cluster PSP to
sometimes fail to create within a namespace.
This change adds additional checks before a role binding is deleted to prevent the default PSPT role binding from being deleted unnecessarily.
Issue:
https://github.com/rancher/rancher/issues/12342
=> Fix PSP race condition

pkg/api/customization/yaml/formatter.go, pkg/api/customization/yaml/link.go, pkg/api/server/server.go, pkg/api/server/userstored/setup.go, vendor.conf, vendor/github.com/rancher/norman/types/mapper/metadata.go, vendor/github.com/rancher/norman/types/mapper/object.go
Needs https://github.com/rancher/norman/pull/124
=> Add yaml link to k8s native objects

pkg/controllers/user/pipeline/controller/pipeline/cronsyncer.go, pkg/controllers/user/pipeline/controller/pipelineexecution/logsyncer.go, pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go, pkg/controllers/user/pipeline/engine/engine.go, pkg/controllers/user/pipeline/engine/jenkins/client.go, pkg/controllers/user/pipeline/engine/jenkins/engine.go
1. use dialer to connect Jenkins in user cluster, for https://github.com/rancher/rancher/issues/12245
2. filter resources by cluster in syncers to fix multiple instances issue.
=> Use dialer for pipeline

pkg/controllers/user/pipeline/engine/jenkins/mappper.go, pkg/controllers/user/pipeline/remote/github/github.go, pkg/controllers/user/pipeline/remote/github/webhook.go
Fix webhook trigger https://github.com/rancher/rancher/issues/12182
use `yaml` as the prefix of pipeline file, https://github.com/rancher/rancher/issues/11675
=> Pipeline fix

pkg/controllers/management/nodedriver/dynamic_driver.go, pkg/controllers/management/nodedriver/machine_driver.go, vendor.conf, vendor/github.com/rancher/types/apis/cluster.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go, vendor/github.com/rancher/types/client/cluster/v3/zz_generated_persistent_volume.go, vendor/github.com/rancher/types/client/cluster/v3/zz_generated_storage_class.go, vendor/github.com/rancher/types/status/status.go
Related Issue:  
https://github.com/rancher/rancher/issues/12269
Generate driver name for different format driver URL
https://github.com/rancher/rancher/issues/11039
Add driver executable check.
https://github.com/rancher/types/pull/319
=> Node driver

pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/utils/daemonset.go
Related issue:
bug: 
https://github.com/rancher/rancher/issues/12366
https://github.com/rancher/rancher/issues/11950
send rke log to identical target as normal container log
https://github.com/rancher/rancher/issues/12255
=> fix collect rke log bug and send rke log to same place

pkg/controllers/user/logging/clusterlogging.go, pkg/controllers/user/logging/utils/embedded.go, pkg/controllers/user/logging/utils/wrap.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_embedded_config.go
Related issue: https://github.com/rancher/rancher/issues/11779
add resource quota to embedded logging
=> Embedded resource quota

pkg/controllers/user/endpoints/endpoints.go, tests/core/test_node.py
https://github.com/rancher/rancher/issues/12470
=> Endpoint fixes around externalIP/internalIP use in address for HostPort ports

pkg/controllers/user/endpoints/endpoints.go
https://github.com/rancher/rancher/issues/12174
=> Populate ports for ingress

pkg/api/customization/pipeline/cluster_pipeline.go
For issue: https://github.com/rancher/rancher/issues/12457
=> fix capital sourcecodecredential name

pkg/auth/providers/providers.go
https://github.com/rancher/rancher/issues/11868
=> include local for get and search principals

vendor.conf, vendor/github.com/rancher/norman/controller/cluster_check.go
=> update norman 

pkg/api/customization/authn/user_actions.go
https://github.com/rancher/rancher/issues/12550
=> don't persist me field on set password

pkg/controllers/user/logging/generator/cluster_template.go
change embedded logging to use to prefix UI send
=> fix embedded index name

vendor.conf, vendor/github.com/rancher/rke/README.md, vendor/github.com/rancher/rke/cluster/defaults.go, vendor/github.com/rancher/rke/vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
https://github.com/rancher/rancher/issues/12169
=> Rke/types updates to get new ingress-controller image

pkg/controllers/user/logging/clusterlogging.go, pkg/controllers/user/logging/config/config.go, pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go, pkg/controllers/user/logging/projectlogging.go, pkg/controllers/user/logging/utils/configmap.go, pkg/controllers/user/logging/utils/daemonset.go, pkg/controllers/user/logging/utils/logging.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rancher_kubernetes_engine_config.go
Related Issue: https://github.com/rancher/rancher/issues/11625
Related types PR: https://github.com/rancher/types/pull/339
Related fluentd commit: https://github.com/rancher/fluentd/commit/5bebe9c3253eb0a21d538adb995fb952d7735ebb
Related fluentd driver commit: 
https://github.com/rancher/fluentd-helper/commit/0d3b781953101699b532b432c5dc14d159d510e0
Reload flexvolume driver repo:
https://github.com/rancher/log-aggregator
=> support custom log path

pkg/api/store/workload/aggregate_store.go
https://github.com/rancher/rancher/issues/12588
Also need norman PR for the full fix: https://github.com/rancher/norman/pull/138
=> Drop maxSurge/maxUnavailable if strategy=recreate

pkg/auth/providers/activedirectory/activedirectory_client.go
Added check for password because otherwise, the msg just returns "server error while authenticating" since it fails to bind. 
https://github.com/rancher/rancher/issues/12553 
https://github.com/rancher/rancher/issues/12421
=> escapeFilter for special chars

pkg/controllers/user/nodesyncer/nodessyncer.go
consolidate the nodeForNode logic for create and update
https://github.com/rancher/rancher/issues/12702
=> Nodesyncer bug fixes for aws cloud provider

pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/alert/watcher/workload.go
related issues:
https://github.com/rancher/rancher/issues/12680
https://github.com/rancher/rancher/issues/12679
https://github.com/rancher/rancher/issues/12678
=> Fix alert message issues

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go, vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go, vendor/github.com/rancher/kontainer-engine/drivers/util/utils.go, vendor/github.com/rancher/kontainer-engine/service/service.go
Depends on:
https://github.com/rancher/kontainer-engine/pull/44/commits/bdfb99ba76be89008e0c644fe406c93191b78d94
Issue:
https://github.com/rancher/rancher/issues/12533
=> Add labels to drivers

pkg/controllers/user/nodesyncer/nodessyncer.go
https://github.com/rancher/rancher/issues/12702
=> Read node.externalIP from status on node sync

pkg/api/store/ingress/store.go
https://github.com/rancher/rancher/issues/12644
https://github.com/rancher/rancher/issues/12334
=> Formatting fix for ingress svc name/namespace

pkg/auth/providers/common/usermanager.go
https://github.com/rancher/rancher/issues/12362
=> replace externalProvider principalIDs if they exist

app/app.go
This reverts commit 35f3e124de262ce4821b12d74f90023c1c776cd6.
=> Revert "Disable catalog by default"

pkg/api/store/workload/aggregate_store.go
similar how we do it for create.
https://github.com/rancher/rancher/issues/12581
=> Format hostname/policy on workload update

pkg/auth/providers/common/usermanager.go, pkg/auth/providers/local/local_auth_provider.go, pkg/auth/providers/providers.go
Make the logic match v1.6 such that a user attempting to login must
either be in the whitelist or explicitly added to a project or cluster.
Fixes a bug where users removed from projects/clusters could still
log in.
Addresses https://github.com/rancher/rancher/issues/12031
Addresses https://github.com/rancher/rancher/issues/12895
=> Change logic for restricted user login

pkg/api/customization/alert/notifier_action.go, pkg/controllers/user/alert/configsyncer/configsyncer.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/alerting_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_smtp_config.go
https://github.com/rancher/rancher/issues/12672
https://github.com/rancher/rancher/issues/12655
https://github.com/rancher/rancher/issues/12654
Dependent Types PR: https://github.com/rancher/types/pull/371
=> Fix issues for email notifier 

pkg/controllers/management/nodedriver/machine_driver.go
Related issue: https://github.com/rancher/rancher/issues/12549
Not manual update install condition
=> fix node driver not download

pkg/controllers/management/auth/crtb_handler.go, pkg/controllers/management/auth/project_cluster_handler.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go
This condition indicates that the creator's role of "owner" has been fully
populated. It will be used as a gate for the UI to perform further
operations as the user, such as creating a nodepool in the cluster.
=> Condition on cluster for initial role population

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Update vendor to take in changes from: https://github.com/rancher/kontainer-engine/pull/49
=> Update vendor for Robust EKS create fix

pkg/controllers/user/endpoints/endpoints.go, pkg/controllers/user/endpoints/node_endpoints.go, pkg/controllers/user/endpoints/pod_endpoints.go, pkg/controllers/user/endpoints/workload_endpoints.go
https://github.com/rancher/rancher/issues/11969
=> Endpoints update: use util for figuring out machine for host

pkg/api/server/userstored/setup.go, pkg/api/store/workload/aggregate_store.go, pkg/api/store/workload/transform_store.go, pkg/api/store/workload/workload_store.go
https://github.com/rancher/rancher/issues/12876
https://github.com/rancher/rancher/issues/12837
https://github.com/rancher/rancher/issues/12855
=> Workload schema fixes

package/Dockerfile
=> Update cli version

pkg/controllers/user/rbac/handler_base.go, pkg/controllers/user/rbac/namespace_handler.go
https://github.com/rancher/rancher/issues/12567
=> Delete Rolebindings when namespace is moved

pkg/controllers/user/nslabels/labels.go
https://github.com/rancher/rancher/issues/12568 
1) Delete project scoped secrets 
2) Move secrets of the namespace to updated project
=> Logic for secrets when namespace is moved between projects

vendor.conf, vendor/github.com/rancher/types/mapper/env.go
rancher/rancher#12779
https://github.com/rancher/rancher/issues/13012
=>  rancher/types to latest version

pkg/api/store/ingress/store.go, pkg/controllers/user/ingress/ingress_common.go
https://github.com/rancher/rancher/issues/13008
=> Ingress state annotation name change

pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go, pkg/controllers/user/logging/utils/daemonset.go
Related issue:
https://github.com/rancher/rancher/issues/12774
update fluentd splunk config
=> update not fluentd config

pkg/controllers/user/alert/config/notifiers.go, pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/deploy/deployer.go, pkg/controllers/user/alert/deploy/notification_template.go, pkg/controllers/user/alert/manager/manager.go, pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/alert/watcher/workload.go
Related issues: https://github.com/rancher/rancher/issues/12880, https://github.com/rancher/rancher/issues/12635
=> Move alert message to template

pkg/controllers/user/nodesyncer/nodessyncer.go
https://github.com/rancher/rancher/issues/13007
=> Do not create machine for node in RKE cluster

pkg/controllers/user/networkpolicy/netpol.go, pkg/controllers/user/networkpolicy/utils.go, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/12641
=> don't apply netpol on system ns

pkg/controllers/user/targetworkloadservice/target_workload_service.go, pkg/controllers/user/workload/workload.go, pkg/controllers/user/workload/workload_common.go
https://github.com/rancher/rancher/issues/13037
https://github.com/rancher/rancher/issues/13038
=> Target workload service update fixes

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Update vendor for https://github.com/rancher/kontainer-engine/pull/59
=> Fix EKS Panic

pkg/controllers/user/nodesyncer/nodessyncer.go
https://github.com/rancher/rancher/issues/12928
=> Set v3.node role based on v1.node rke label (if present)

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/13109
=> Split string on backslash during AD bind

pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/alert/watcher/workload.go
Related issue: https://github.com/rancher/rancher/issues/13105
=> Use cluster display name in alert message

pkg/controllers/user/logging/clusterlogging.go
fix bug, should not use management node, and use user cluster.
=> should use user cluster's k8s node client 

pkg/controllers/user/pipeline/controller/clusterpipeline/deploy.go
Related issue: https://github.com/rancher/rancher/issues/13068
=> set step log size cap to 1MB

pkg/controllers/user/rbac/namespace_handler.go
https://github.com/rancher/rancher/issues/13193
=> delete rolebindings when namespace is moved to none

pkg/controllers/user/endpoints/endpoints.go
Related issue https://github.com/rancher/rancher/issues/13218
1. If ingress rules without specifying hostname, shows both
http and https endpoint
2. If ingress rules with specifying hostname and SSL configured with
this hostname, shows https endpoint
3. if ingress rules with specifying hostname and no SSL configured,
shows http endpoint
=> Shows ingress endpoint with rules

pkg/controllers/user/pipeline/engine/jenkins/client.go, pkg/controllers/user/pipeline/engine/jenkins/engine.go
Fix https://github.com/rancher/rancher/issues/13248
=> Fix invalid crumb in pipeline

package/Dockerfile, package/Dockerfile.agent
Also clears the security scan on 17.10
=> Switch base image to Ubuntu 18.04

pkg/controllers/user/dnsrecord/dnsrecord.go, pkg/controllers/user/externalservice/external_ip_service.go
Requires https://github.com/rancher/norman/pull/154 
https://github.com/rancher/rancher/issues/12923
=> handle empty annotations

pkg/controllers/user/dnsrecord/dnsrecord.go, pkg/controllers/user/externalservice/external_ip_service.go
https://github.com/rancher/rancher/issues/12923
=> null annotations

pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/common/ldap/ldap_util.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rancher_kubernetes_engine_config.go
https://github.com/rancher/rancher/issues/13300
=> Change AD filter for searchPrincipal

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/13232
Pull up user's groups in batches of 50, so as to reduce time taken during login
=> Pull user groups in batches to reduce search time

package/run.sh
https://github.com/rancher/rancher/issues/13244
```
ERROR: Configured cacerts checksum (44be99d5fafe9b54256173bd239932b917c4857211470a2f3d71943dac88fadd) does not match given --ca-checksum (44be99d5fafe9b54256173bd239932b917c4857211470a2f3d71943dac88afadd)
ERROR: Please check if the correct certificate is configured at https://XXX/v3/settings/cacerts
```
=> Error out when cacerts checksum does not match when starting agent

package/run.sh
* Adds option to specify interface to get IP address from (`--address eth0`, `--internal-address eth1`)
* Adds options for all major clouds metadata IP retrieval
=> Add agent ip options

pkg/controllers/management/auth/user.go
This change adds logic to the user lifecycle to remove the user namespace
when a user is deleted.
Issue:
https://github.com/rancher/rancher/issues/12576
=> Removing user namespace on user delete

pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go, pkg/controllers/user/pipeline/controller/pipelineexecution/statesyncer.go, pkg/controllers/user/pipeline/engine/jenkins/engine.go
Fix https://github.com/rancher/rancher/issues/13013
set provisioned condition properly and clean href tag in the text.
=> pipeline execution condition fix

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/13300#issuecomment-387823228
=> Escape filter on AD query to get groups

pkg/api/store/ingress/store.go, pkg/controllers/user/ingress/ingress.go
Related issue https://github.com/rancher/rancher/issues/13144
Should delete services which are created by ingress and
no longer used.
=> Add clean up logic for ingress service

pkg/api/store/workload/transform_store.go
https://github.com/rancher/rancher/issues/13194
=> Set nodeId in scheduler in transform

agent/Dockerfile
https://github.com/rancher/rancher/issues/12750
=> adding loglevel

package/run.sh
https://github.com/rancher/rancher/issues/13308
=> Check if the cacert pulled from settings is empty

app/app.go, main.go, rke-templates/3-node-certificate-recognizedca.yml, rke-templates/3-node-certificate.yml, rke-templates/3-node-passthrough.yml, server/server.go, vendor.conf, vendor/github.com/rancher/norman/leader/leader.go
Related issue: https://github.com/rancher/rancher/issues/13292
Add parameter advertise-address in command line as identity
in leader election.
=> Should use master ip to proxy request to it.

pkg/api/customization/alert/notifier_action.go, pkg/api/store/workload/aggregate_store.go, pkg/controllers/user/alert/watcher/event.go
Relate issues:
https://github.com/rancher/rancher/issues/12618, https://github.com/rancher/rancher/issues/12619, https://github.com/rancher/rancher/issues/13414
=> Fix bugs for alerting

package/run.sh
https://github.com/rancher/rancher/issues/13397
=> Better way of determining CATTLE_ADDRESS

package/run.sh
https://github.com/rancher/rancher/issues/13486
=> Continue directly on empty agent address, and more reliable network interface check

app/machinedriver_data.go
Add TCP port 10250-10252 and 10256 into security group.
Add UDP port 4789 and 8472 into security group
=> Update aliyuncs Driver version to 1.0.2

pkg/controllers/user/nslabels/labels.go
Related issue: https://github.com/rancher/rancher/issues/13685
=> fix crash cause by lack of annotation

pkg/api/customization/project/project_actions.go, pkg/auth/providers/github/github_provider.go
Refactoring code to remove unused variable or change name to underbar
unused codes are detected by ineffassign
refer https://goreportcard.com/report/github.com/rancher/rancher#ineffassign
=> Remove ineffectual assignments

pkg/api/store/workload/transform_store.go
https://github.com/rancher/rancher/issues/12602
=> transitioning state for workload

pkg/controllers/management/auth/manager.go, pkg/controllers/user/alert/statesyncer/statesyncer.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/healthsyncer/healthsyncer.go
Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>
=> Fix misspelled English words

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/8317
https://github.com/rancher/rancher/issues/12987
As per https://msdn.microsoft.com/en-us/library/aa746475%28VS.85%29.aspx, `(member:1.2.840.113556.1.4.1941:=cn=user1,cn=users,DC=x)`
query can fetch all groups that the user is a member of, including nested groups
=> Allow nested group memberships

pkg/api/store/workload/aggregate_store.go
Relate issue: https://github.com/rancher/rancher/issues/12619
=> Add capabilitiesToUpperCase to Watch func

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/12987
=> Set groupMemberMappingAttribute for AD if not present

pkg/api/store/ingress/store.go, tests/core/test_ingress.py
for ingress rules with same host, path and port -> only one rule should be created, others will be deleted
https://github.com/rancher/rancher/issues/13185
=> convert ingress rules correctly

pkg/api/customization/node/node.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/nodesyncer/cordonfieldssyncer.go, pkg/controllers/user/nodesyncer/nodessyncer.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_node.go
https://github.com/rancher/rancher/issues/13623 
requires - https://github.com/rancher/types/pull/454
=> add cordon and uncordon action to clusternode 

pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go
add auth config for project logging template
=> update project logging auth

pkg/api/server/userstored/setup.go
https://github.com/rancher/rancher/issues/13150
=> Fix to receive resource.change events for dnsRecord

pkg/controllers/user/rbac/podsecuritypolicy/serviceaccount.go
This change makes it so that namespaces have their PSPT removed
after they are moved out of a project.  Before, when a namespace was in a
project that had a PSPT assigned to it, and the namespace was moved to
"None", it would continue to have the PSPT associated with its previous
project.
Issue:
https://github.com/rancher/rancher/issues/12833
=> Fix so project-less namespaces have their PSPT removed

README.md
change docker version from 17.03.02 to 17.03.2
=> typo fix : change docker version to 17.03.2

app/listenconfig_data.go
https://github.com/rancher/rancher/issues/13619
=> add selfsigned cert as k8s secret

pkg/api/customization/pipeline/cluster_pipeline.go
So that users can immediately see repo list when they are configuring pipelines.
For https://github.com/rancher/rancher/issues/13643#issuecomment-393222760
=> return authuser action until repos are fetched

pkg/controllers/user/approuter/core_dns_client.go, pkg/controllers/user/approuter/ingress_controller.go, pkg/settings/setting.go
fix issue [#13833](https://github.com/rancher/rancher/issues/13833)
1. Fix the approuter controller crash
2. Make sure each ingress hostname is valid
=> The approuter controller bugs fix

pkg/controllers/user/alert/watcher/node.go
https://github.com/rancher/rancher/issues/13605
node watcher crash after node is deleted
=> fix alert watcher crash bug

pkg/controllers/user/endpoints/workload_endpoints.go
https://github.com/rancher/rancher/issues/12770
=> Panic fix in workload endpoints population

pkg/api/customization/node/node.go, pkg/api/store/node/store.go, pkg/controllers/user/nodesyncer/cordonfieldssyncer.go, tests/core/test_node.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_etcd_service.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_kube_apiservice.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_kube_controller_service.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_kubelet_service.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_kubeproxy_service.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_node_spec.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_scheduler_service.go
using desiredNodeUnschedulable and setting state `cordoned`
https://github.com/rancher/rancher/issues/13623
=> cordon-uncordon fix 

pkg/clustermanager/manager.go, pkg/controllers/management/controller.go, pkg/controllers/management/usercontrollers/controller.go
https://github.com/rancher/rancher/issues/13603
=> Deregister rancher agent on cluster.remove before provisioner cleanup

pkg/auth/tokens/server.go, pkg/controllers/management/auth/register.go, pkg/controllers/management/auth/token.go
This fixe is needed to show the calculated "expiresAt" property while listing API keys after creating a new key.
https://github.com/rancher/rancher/issues/12450
@alena1108 need review pls.
=> Adding token controller to update expiresAt property upon token creation

pkg/agent/main.go, pkg/agent/node/node.go, pkg/rkeworker/docker.go
https://github.com/rancher/rancher/issues/13913
=> close docker client

pkg/controllers/user/endpoints/workload_endpoints.go
https://github.com/rancher/rancher/issues/12770
=> Nil panic fix in workloads object reference check

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Depend on:
https://github.com/rancher/kontainer-engine/pull/65
Issue:
https://github.com/rancher/rancher/issues/13857
=> Update vendor for EKS GA Fix

pkg/controllers/user/workload/workload.go
https://github.com/rancher/rancher/issues/12770
=> Another panic fix

pkg/controllers/management/usercontrollers/controller.go
Mistakenly removed this line while refactoring cluster lifecycle registration
=> Cluster lifecycle controller registration fix

pkg/catalog/manager/crd.go, pkg/catalog/manager/manager.go, pkg/controllers/user/endpoints/endpoints.go
Related issues 
Ingress public endpoint fix: https://github.com/rancher/rancher/issues/13805
leaderelection lost fix: https://github.com/rancher/rancher/issues/13446
=> Fixes for v2.0.3

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/13554
=> Add kubectl binary from upstream source and update to 1.9.8

pkg/api/store/workload/workload_store.go, pkg/controllers/user/workload/workload.go
https://github.com/rancher/rancher/issues/13426
Also put a fix into port name generation in API layer - when port's source port gets changed, the name should be regenerated
=> Node (source) port update support

pkg/controllers/user/alert/watcher/workload.go, pkg/controllers/user/rbac/handler_base.go, pkg/namespace/namespace.go
Related issue: https://github.com/rancher/rancher/issues/13183
=> only send alert when the workload is under related project

app/app.go, main.go
https://github.com/rancher/rancher/issues/14004
=> Log startup, version, args

pkg/auth/tokens/manager.go
If multiple login requests for the same user come in simultaneously, its
possbile to get a conflict on creating or updating the userAttribute
resource. This fix mitigates that by creating it in a backoff loop.
=> Add retry logic for creating/updating userAttr

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go, vendor/github.com/rancher/kontainer-engine/vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_amazon_elastic_container_service_config.go
Depends on:
https://github.com/rancher/kontainer-engine/pull/70
https://github.com/rancher/types/pull/476
Issue:
https://github.com/rancher/rancher/issues/14064
=> Update vendor for EKS Options

pkg/auth/providers/common/usermanager.go
Restricted access means that in addition to the explicitly whitelisted
set of user and groups that can log in, a user who is a meber of any
project or cluster can log in.
To accomplish the second half, we check if the user's individual and group
principals exist on any project or cluster RoleTemplateBindings (PRTB, CRTB).
However, the existing logic does not account for the CRTB/PRTB that the backend
creates for the owner of the project or cluster. That CRTB/PRTB does not
have a user or group principal field set; it just has the UserName (aka the
user ID) field set.
This change fixes the issue by also considering the user's name when determining
if the user is a member of a cluster or project.
addresses https://github.com/rancher/rancher/issues/14087
=> Fix logic around restricted access

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Depends on:
https://github.com/rancher/kontainer-engine/pull/71
Issue:
https://github.com/rancher/rancher/issues/14064
=> Update vendor for EKS error message

pkg/auth/providers/ldap/ldap_client.go
https://github.com/rancher/rancher/issues/14082
https://github.com/rancher/rancher/issues/14083
=> improve error message when login

vendor.conf, vendor/github.com/Azure/go-autorest/CHANGELOG.md, vendor/github.com/Azure/go-autorest/autorest/adal/token.go, vendor/github.com/Azure/go-autorest/autorest/azure/azure.go, vendor/github.com/Azure/go-autorest/autorest/azure/rp.go, vendor/github.com/Azure/go-autorest/autorest/validation/validation.go, vendor/github.com/Azure/go-autorest/autorest/version.go
Issue: https://github.com/rancher/rancher/issues/14131
=> Update go-autorest version

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
Depends on:
https://github.com/rancher/kontainer-engine/pull/72
Issue:
https://github.com/rancher/rancher/issues/13395
=> Update vendor for AKS decode fix

pkg/auth/providers/github/github_provider.go
https://github.com/rancher/rancher/issues/14143
https://github.com/rancher/rancher/issues/14142
=> Whoopsie daisey - Check for nil token

pkg/api/customization/cluster/actionhandler.go
=> Revert "fix export action for cluster"

pkg/auth/providers/ldap/ldap_client.go, pkg/auth/providers/ldap/ldap_provider.go
https://github.com/rancher/rancher/issues/14081
=> handle username with special characters

pkg/api/customization/cluster/actionhandler.go
This reverts commit c780c1c601d9d4f9640c06b8ce909b8765ae0ae0.
=> Revert "Revert "fix export action for cluster""

pkg/auth/providers/activedirectory/actions.go, pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/activedirectory/provider.go, pkg/auth/providers/azure/azure_actions.go, pkg/auth/providers/azure/azure_client.go, pkg/auth/providers/azure/azure_provider.go, pkg/auth/providers/common/provider.go, pkg/auth/providers/github/github_provider.go, pkg/auth/providers/ldap/ldap_actions.go, pkg/auth/providers/ldap/ldap_client.go, pkg/auth/providers/ldap/ldap_provider.go, pkg/auth/providers/local/local_auth_provider.go, pkg/auth/providers/providers.go, pkg/auth/providers/publicapi/login.go, pkg/auth/tokens/manager.go, pkg/controllers/management/auth/user.go
Problem:
Provider tokens are stored on the principal objects in k8s
Solution:
Move provider tokens to be a k8s secret
Issue https://github.com/rancherlabs/the-ranch/issues/134
=> Store providers tokens as secrets

pkg/controllers/user/ingress/ingress.go
Related issue: https://github.com/rancher/rancher/issues/14204
Our Ingress controller should not try to create a service for the rule that
is related to a existing service. Should do nothing for this rule.
=> Should not create service for the ingress rule with existing service

package/Dockerfile
https://github.com/rancher/rancher/issues/14103
=> Add env vars for Helm/machine/loglevel

pkg/agent/main.go
https://github.com/rancher/rancher/issues/14292
=> Log agent version

pkg/systemtemplate/template.go
https://github.com/rancher/rancher/issues/14296
=> Add tolerations to cattle-node-agent for etcd/controlplane

rke-templates/3-node-certificate-recognizedca.yml, rke-templates/3-node-certificate.yml, rke-templates/3-node-externalssl-certificate.yml, rke-templates/3-node-externalssl-recognizedca.yml, rke-templates/3-node-passthrough.yml
https://github.com/rancher/rancher/issues/13562
=> Add etcd snapshots to rke templates

pkg/api/customization/roletemplate/roletemplate.go
Issue: https://github.com/rancher/rancher/issues/13595
=> Update comparison to ensure ordering

tests/core/conftest.py, tests/core/test_auth_configs.py, tests/core/test_dns.py, tests/core/test_ingress.py, tests/core/test_namespaced_secrets.py, tests/core/test_node.py, tests/core/test_rbac.py, tests/core/test_secrets.py, tests/requirements.txt
- Rename and document fixutres for clarity
- Fix a bug in rancher client that was breaking the use of multiple clients
- Add a test for the above fix
- Addressed warnings in conftest.py by exporting client._token and renaming some
variables that were shadowing reserved words
=> Test improvements

pkg/controllers/user/workload/workload.go, pkg/controllers/user/workload/workload_common.go, tests/core/test_workloads.py
to allow transition from headless to regular svc, and vice versa
https://github.com/rancher/rancher/issues/14271
=> Support for clusterip change on service

pkg/auth/providers/common/ldap/ldap_util.go, pkg/auth/providers/ldap/ldap_client.go, pkg/auth/providers/ldap/ldap_provider.go
https://github.com/rancher/rancher/issues/14080
=> allow nested users to login bottom-up method for openldap/freeipa

pkg/auth/providers/common/ldap/ldap_util.go, pkg/auth/providers/ldap/ldap_client.go
for openldap/freeipa
https://github.com/rancher/rancher/issues/14287
=> batch fetching groups when users belongs to a bunch of groups

pkg/auth/providers/ldap/ldap_client.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_active_directory_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_ldap_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_open_ldap_config.go
https://github.com/rancher/rancher/issues/14364
=> NestedGroupMembership field for openldap

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/14284
=> Check option to see whether nested group memberships are enabled

vendor.conf, vendor/github.com/rancher/types/.gitignore, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/service_spec_mapper.go
https://github.com/rancher/rancher/issues/14414
=> Vendor update for types to address c clusterIP issue

pkg/auth/providers/activedirectory/activedirectory_client.go
https://github.com/rancher/rancher/issues/14429
=> fix ldap connection timeout error message for AD

pkg/api/store/cluster/cluster_store.go, pkg/controllers/management/clusterprovisioner/provisioner.go
Enusre that the kubernetes version on rkeConfig spec is set during cluster create/update. If the client passed it as empty, rancher server sets it to system default k8s version.
This step ensures that during upgrade of rancher server if the system default k8s version is updated, existing clusters' k8s version does not get auto-upgraded.
https://github.com/rancher/rancher/issues/14407
@alena1108 need a review.
=> Set the kubernetes version on rkeConfig spec during cluster create/update

agent/Dockerfile
https://github.com/rancher/rancher/issues/14450
=> change log package

pkg/auth/providers/activedirectory/actions.go, pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/activedirectory/provider.go, pkg/auth/providers/common/ldap/ldap_util.go, pkg/auth/providers/ldap/ldap_client.go
https://github.com/rancher/rancher/issues/14466
https://github.com/rancher/rancher/issues/14456
https://github.com/rancher/rancher/issues/14452
=> add testServiceAccountBind  bool of loginUser for AD/Ldap

pkg/controllers/management/clusterprovisioner/provisioner.go, pkg/controllers/management/nodepool/nodepool.go, pkg/controllers/user/nodesyncer/nodessyncer.go
https://github.com/rancher/rancher/issues/14133
=> Roles update support via nodepool update

pkg/auth/providers/common/usermanager.go
If multiple calls to generateKubeConfig action are made near simultaneously,
we can hit a race condition where the second call fails to find the token
in the cache and also fails to create it. Fix is to get the token
from the API if the create call fails with an "already exists" error.
This was manifesting itself in our drone builds where our tests are run
in parallel.
Observed in this build failure: https://drone7.rancher.io/rancher/rancher/882/3
=> Fix kubeconfig token race condtion

pkg/auth/providers/publicapi/login.go, pkg/auth/requests/authenticate.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_user.go
Problem:
Users can not be enabled or disable
Solution:
Allow setting of enabled field stopping users from logging in or using
the api
Issue: rancher/rancher#10646
=> Add check for user enabled field

tests/core/test_pod_security_policies.py
This change adds an integration test for this issue:
https://github.com/rancher/rancher/pull/14497
=> Adding tests for PSP fix

pkg/controllers/management/clusterstats/statsaggregator.go
https://github.com/rancher/rancher/issues/14459
=> Include schedulable worker nodes only to cluster capacity

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/14025
@alena1108 @superseb review pls
=> Update kubectl binary to k8s version 1.10.5

pkg/auth/providers/common/usermanager.go
Problem:
User needs to be updated with annotation and condition but can fail if
the user is modified by another process
Solution:
Add a loop to the user update to try again if a conflict is hit
Issue: https://github.com/rancher/rancher/issues/14560
=> Update usermanager to try again on user update

pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/workload.go
https://github.com/rancher/rancher/issues/13961
=> fix node delete but alert still here bug

pkg/controllers/user/nodesyncer/nodessyncer.go
Using DeepEquals on the NodeStatus fields resulted in unneeded object
updates. The list of images being compared contained the same content
but a different order which were seen as unequal. As far as Rancher is
concerned, the same content was equal. So a separate method is added
breaking out the fields into their own tests.
Also, since Images is not used at this time, we can skip it.
=> StatusEqual check fix

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/gke/gke_driver.go, vendor/github.com/rancher/kontainer-engine/vendor.conf
Depends on:
https://github.com/rancher/kontainer-engine/pull/76
https://github.com/rancher/types/pull/509
Issue:
https://github.com/rancher/rancher/issues/13789
=> Gke options

pkg/cert/cert.go
https://github.com/rancher/rancher/issues/14383
=> Add support for PKCS8 certificate

pkg/controllers/user/targetworkloadservice/target_workload_service.go, pkg/controllers/user/workload/workload_common.go
An attempt to workaround the issue happening on rancher upgrade where object can't be found in cache for some time
https://github.com/rancher/rancher/issues/13611
=> Fetch workload from api if can not be found in cache

pkg/remotedialer/session.go
https://github.com/rancher/rancher/issues/14409
=> Don't print non-printable characters

pkg/controllers/user/ingress/ingress.go, pkg/controllers/user/ingress/ingress_common.go
https://github.com/rancher/rancher/issues/13717
=> Bug fix for ingress services to work on GKE

pkg/auth/providers/publicapi/login.go
https://github.com/rancher/rancher/issues/14702
=> report error message when local user being deactivated

pkg/api/store/workload/workload_store.go, tests/core/test_workloads.py
https://github.com/rancher/rancher/issues/14061
=> throw error when statefulset volumeMounts.subPath is invalid

vendor.conf, vendor/github.com/rancher/types/status/status.go
https://github.com/rancher/rancher/issues/14658
=> update vendor for fixing duplicate transitioningMessage

pkg/controllers/management/auth/project_cluster_handler.go
Re-do of https://github.com/rancher/rancher/pull/14398
Original issue https://github.com/rancher/rancher/issues/14400
=> Change Default project prefix to 'p-' #2

pkg/embedded/embedded.go
https://github.com/rancher/rancher/issues/14662
=> disable resourceQuota and service in embedded cluster

pkg/controllers/user/resourcequota/register.go, pkg/controllers/user/resourcequota/resource_quota_validate.go, tests/core/test_project_resource_quota.py
https://github.com/rancher/rancher/issues/14768
=> Enqueue namespaces for update when corresponding project gets updated

pkg/controllers/user/networkpolicy/netpol.go, pkg/controllers/user/networkpolicy/podhandler.go, pkg/controllers/user/networkpolicy/servicehandler.go
https://github.com/rancher/rancher/issues/14769
=> allow incoming traffic from system project to user projects

pkg/auth/providers/common/ldap/ldap_util.go
https://github.com/rancher/rancher/issues/14438
=> delete unnecessary user search attributes for AD

pkg/auth/providers/saml/saml_provider.go
https://github.com/rancher/rancher/issues/14764
=> Return error if prinipal type is non saml (local)

pkg/api/controllers/samlconfig/samlconfig.go, pkg/auth/providers/saml/saml_client.go
https://github.com/rancher/rancher/issues/14794
=> Redirect to Rancher UI with errorCode in query param

scripts/build-agent
Identical to https://github.com/rancher/rancher/commit/9483b291742eb22da85523f2dd6bc4888fbc058f for server
=> Remove CGO_ENABLED=0 when compiling agent

pkg/api/store/cluster/cluster_store.go, pkg/controllers/management/clusterdeploy/clusterdeploy.go, pkg/controllers/user/networkpolicy/clusterHandler.go, pkg/controllers/user/networkpolicy/clusterNetAnnHandler.go, pkg/controllers/user/networkpolicy/netpol.go, pkg/controllers/user/networkpolicy/nodehandler.go, pkg/controllers/user/networkpolicy/nssyncer.go, pkg/controllers/user/networkpolicy/podhandler.go, pkg/controllers/user/networkpolicy/projectsyncer.go, pkg/controllers/user/networkpolicy/register.go, pkg/controllers/user/networkpolicy/servicehandler.go, pkg/controllers/user/networkpolicy/utils.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_spec.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
https://github.com/rancher/types/pull/527
https://github.com/rancher/rancher/issues/14462 
Other bugs that get fixed: 
https://github.com/rancher/rancher/issues/14826 
https://github.com/rancher/rancher/issues/14825
https://github.com/rancher/rancher/issues/14777
=> add support to disable network policies on rke clusters 

Dockerfile.dapper, pkg/image/export/main.go, scripts/build-server
=> Revert "Update golang version to fix golang TLS issue for AD"

pkg/api/store/cluster/cluster_store.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go
get plugin from rkeConfig + vendor change 
https://github.com/rancher/rancher/issues/14851
=> get plugin from rkeConfig

pkg/clustermanager/manager.go
Related issue https://github.com/rancher/rancher/issues/14910
=> Add server name for tls config in k8s rest client config

package/run.sh
https://github.com/rancher/rancher/issues/14691
Adds most common steps to resolve issues with agent:
* Print all given arguments (redacted token)
* Print all environment variables (redacted token)
* Print resolv.conf nameserver entries
* Warn when loopback address found in resolv.conf
* Accessibility check to $CATTLE_SERVER/ping, taken from 1.6 (this will show connection issues (ACL/firewall) and DNS issues (no such host))
* Check if retrieved `cacerts` is an actual certificate
Other checks like certificate checking will go in the agent binary
=> Add more info/debug on agent startup

pkg/controllers/management/auth/project_cluster_handler.go, tests/core/test_default_roles.py
https://github.com/rancher/rancher/issues/14704
=> call addRTAnnotation for projects

pkg/auth/providers/common/usermanager.go
Problem:
There is a race when creating users which can cause duplicate users
for the same principal to get created
Solution:
Use a deterministic name for the user based off the principalName so k8s
can tell us if that user already exists
Issue: https://github.com/rancher/rancher/issues/14822
=> Use principalName for creating user name

pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go
https://github.com/rancher/rancher/issues/14465
=> make syslog token keyless

vendor.conf, vendor/github.com/rancher/rdns-server/README.md, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_secret_volume_source.go
use secretName instead of secretId
=> Update vendor for types change

pkg/api/server/userstored/setup.go
Refer to issue https://github.com/rancher/rancher/issues/14367.
We should not use the same store for two types. It will cause watch func
of this store returns two datas with one of the types
instead of two data for each type.
=> Report DNSRecord and Service via websocket in the same time

pkg/controllers/management/clusterdeploy/clusterdeploy.go
network provider can be null, get name from plugin information
https://github.com/rancher/rancher/issues/15002
=> Get name from plugin

pkg/controllers/management/clusterstats/statsaggregator.go
https://github.com/rancher/rancher/issues/15018
=> don't use reflect to compare quantities

package/Dockerfile
https://github.com/rancher/rancher/issues/14881
=> telemetry v0.5.1

pkg/controllers/user/helm/common.go
This reverts commit 23eef841cc3a37c99f9be760ff635b3833257eb9.
=> Revert "use set-string"

.gitignore, tests/core/conftest.py, tests/core/test_rbac.py, tests/requirements.txt
This test validates that a user that is added a project can see the
cluster and once removed can no longer see the cluster.
=> Add test for user removed from project

pkg/controllers/user/alert/watcher/node.go
fix use wrong conditon in alert.
=> fix alert not work

pkg/controllers/user/alert/watcher/workload.go
https://github.com/rancher/rancher/issues/14790
=> change less and equal to less

pkg/api/store/service/service.go, tests/core/test_dns.py
https://github.com/rancher/rancher/issues/14457#event-1788808586
=> validate ip address when adding dns record for displaying error in UI

tests/core/test_project_resource_quota.py
Temporary fix to address intermittent TF on Drone (temporary as project resource quota is going over redesign, and test might be not relevant once its done)
=> Resource quota test fix

pkg/controllers/user/helm/common.go, pkg/controllers/user/helm/controller.go
this commit makes two changes:
1. filtering error message so that it does not include random tempfile
path.
2. use AppRevision to store the last applied template(it is for deleting
app if error happens). This avoid writing templates into app CRD(which
could also have random string generated)
This commit will stop the flapping to prevent us writing random stuff into app
CRD and causing the controller sync running forever.
=> hide random tmp file path and template from app

pkg/api/store/ingress/store.go
https://github.com/rancher/rancher/issues/14934
=> default certs to namespaced certs if edited from yaml

pkg/api/customization/alert/notifier_action.go
https://github.com/rancher/rancher/issues/13297
=> support more http webhook response

pkg/controllers/user/logging/utils/daemonset.go
https://github.com/rancher/rancher/issues/14963
=> Add tolerations to fluentd and log-aggregator ds

pkg/auth/tokens/manager.go, tests/core/conftest.py, tests/core/test_tokens.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_token.go, vendor/github.com/rancher/types/client/management/v3public/zz_generated_token.go
Part of https://github.com/rancher/rancher/issues/11182
requires https://github.com/rancher/types/pull/545
=> Add current flag to tokens

vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema_secrets.go
To get the fix for https://github.com/rancher/rancher/issues/14745
=> Types vendor update

pkg/api/controllers/settings/settings.go, pkg/api/customization/setting/setting.go, pkg/api/server/managementstored/setup.go, pkg/settings/setting.go, tests/core/test_cluster_defaults.py
https://github.com/rancher/rancher/issues/14948
=> add setting cluster-defaults

pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
https://github.com/rancher/rancher/issues/15162
=> Panic fix in cordonsync

rke-templates/3-node-certificate-recognizedca.yml, rke-templates/3-node-certificate.yml, rke-templates/3-node-externalssl-certificate.yml, rke-templates/3-node-externalssl-recognizedca.yml
https://github.com/rancher/rancher/issues/15148
=> Make rancher image version a variable in rke templates

pkg/controllers/user/resourcequota/resource_quota_sync.go
if quota is not enabled on the project
https://github.com/rancher/rancher/issues/15292
=> Do not create empty quota for ns

pkg/pipeline/hooks/drivers/github.go, pkg/pipeline/hooks/drivers/gitlab.go, vendor.conf, vendor/github.com/xanzy/go-gitlab/.gitignore, vendor/github.com/xanzy/go-gitlab/.travis.yml, vendor/github.com/xanzy/go-gitlab/README.md, vendor/github.com/xanzy/go-gitlab/award_emojis.go, vendor/github.com/xanzy/go-gitlab/commits.go, vendor/github.com/xanzy/go-gitlab/deployments.go, vendor/github.com/xanzy/go-gitlab/event_types.go, vendor/github.com/xanzy/go-gitlab/events.go, vendor/github.com/xanzy/go-gitlab/gitlab.go, vendor/github.com/xanzy/go-gitlab/group_boards.go, vendor/github.com/xanzy/go-gitlab/group_members.go, vendor/github.com/xanzy/go-gitlab/group_variables.go, vendor/github.com/xanzy/go-gitlab/groups.go, vendor/github.com/xanzy/go-gitlab/issues.go, vendor/github.com/xanzy/go-gitlab/keys.go, vendor/github.com/xanzy/go-gitlab/merge_request_approvals.go, vendor/github.com/xanzy/go-gitlab/merge_requests.go, vendor/github.com/xanzy/go-gitlab/pipelines.go, vendor/github.com/xanzy/go-gitlab/project_variables.go, vendor/github.com/xanzy/go-gitlab/projects.go, vendor/github.com/xanzy/go-gitlab/repositories.go, vendor/github.com/xanzy/go-gitlab/runners.go, vendor/github.com/xanzy/go-gitlab/services.go, vendor/github.com/xanzy/go-gitlab/tags.go, vendor/github.com/xanzy/go-gitlab/users.go
Fixed the issue: https://github.com/rancher/rancher/issues/14216
=> Filter actions for pull request events

pkg/settings/setting.go, scripts/build-server
https://github.com/rancher/rancher/issues/15192
=> add setting rke-version

pkg/controllers/management/auth/project_cluster_handler.go, pkg/controllers/user/alert/deploy/deployer.go, pkg/controllers/user/alert/upgrade/upgradeimpl.go, pkg/controllers/user/controllers.go, pkg/controllers/user/logging/clusterlogging.go, pkg/controllers/user/logging/upgrade/upgradeimpl.go, pkg/controllers/user/logging/utils/daemonset.go, pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go, pkg/controllers/user/pipeline/upgrade/upgradeimpl.go, pkg/controllers/user/rbac/namespace_handler.go, pkg/controllers/user/rbac/project_handler.go, pkg/controllers/user/systemimage/register.go, pkg/controllers/user/systemimage/systemimage.go, pkg/controllers/user/systemimage/upgrader.go, pkg/project/project.go
related issue: https://github.com/rancher/rancher/issues/14696
=> add upgrade system image support

pkg/controllers/user/resourcequota/resource_quota_sync.go
https://github.com/rancher/rancher/issues/15357
=> Do not update ns quota if not set on project

pkg/api/customization/project/project_store.go, pkg/api/store/namespace/store.go, pkg/controllers/user/resourcequota/resource_quota_calculate_used.go, pkg/controllers/user/resourcequota/resource_quota_common.go, pkg/controllers/user/resourcequota/resource_quota_sync.go, pkg/resourcequota/quota_validate.go, tests/core/test_project_resource_quota.py
https://github.com/rancher/rancher/issues/15336
https://github.com/rancher/rancher/issues/15338
https://github.com/rancher/rancher/issues/15318
https://github.com/rancher/rancher/issues/14835
=> Resource quota bug fixes

pkg/api/customization/node/node.go
https://github.com/rancher/rancher/issues/15300
=> allow cordon and drain only for worker nodes

pkg/api/customization/setting/setting.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_private_registry.go
https://github.com/rancher/rancher/issues/15256 
requires https://github.com/rancher/types/pull/561
=>  add fixes for cluster-defaults setting

pkg/api/store/node/store.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go
https://github.com/rancher/rancher/issues/14571
=> add validation dnsLabel for RequestedHostName when node creation

pkg/controllers/user/pipeline/controller/pipelineexecution/common.go, pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go, pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go, pkg/controllers/user/pipeline/controller/pipelineexecution/registrycertsyncer.go, pkg/controllers/user/pipeline/controller/project/project.go, pkg/pipeline/engine/jenkins/convert.go, pkg/pipeline/engine/jenkins/engine.go, pkg/pipeline/engine/jenkins/mappper.go, pkg/pipeline/utils/constants.go, pkg/pipeline/utils/utils.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/project.cattle.io/v3/pipeline_types.go
Related issues: https://github.com/rancher/rancher/issues/15226
Dependent types PR: https://github.com/rancher/types/pull/552
=> Security enhancement for pipeline internal registries

pkg/controllers/user/rbac/podsecuritypolicy/namespace.go
https://github.com/rancher/rancher/issues/12266
https://github.com/rancher/rancher/issues/12497
=> don't sync svcaccounts if namespace is terminating

app/ensure_admin_user.go, app/role_data.go, main.go, pkg/api/customization/authn/user_store.go, tests/core/test_users.py
https://github.com/rancher/rancher/issues/14818
There are tests for deleting yourself, but not for deleting the last admin, as the only way you could get to that point (past deleting oneself) is a race condition, where adminA deletes adminB at the same time as adminB deletes adminA (or any cycle of the sort).
=> Users cannot delete/deactivate themselves or last admin

pkg/api/customization/authn/user_store.go, pkg/controllers/management/auth/user.go
Problem:
Users created through the API are not getting a condition set so the UI
will show initializing until a refresh
Solution:
On user create through the API, create the required bindings for the
user to see themselves and once completed add the InitialRolesPopulated
condition to flip the UI to Active
Issue: https://github.com/rancher/rancher/issues/14738
=> Add condition to API created user

pkg/auth/providers/activedirectory/activedirectory_client.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_active_directory_config.go
https://github.com/rancher/rancher/issues/13656
=>  add customized user and group search query for AD auth

pkg/controllers/user/secret/secret.go
@ibuildthecloud we still end up having finalizer set on `tls-rancher` secret (residing in `cattle-system` namespace) that we create as a part of listener controller as its creation done using norman client.
https://github.com/rancher/rancher/issues/15425
=> Secrets: apply lifecycle to rancher created objects only

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/aks/aks_driver.go
=> Add EnableRBAC to AKS cluster creation

pkg/api/customization/setting/setting.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go
https://github.com/rancher/types/pull/570
https://github.com/rancher/rancher/issues/15500
=> exclude unwanted fields from cluster defaults

tests/core/test_default_roles.py
https://github.com/rancher/rancher/issues/15471
=> use wait_for_condition only for required projects

pkg/agent/clean/clean.go
A new annotation was added to namespaces that needs to be removed.
Issue: https://github.com/rancher/rancher/issues/14207
=> Add annotation that needs to be cleaned up

cleanup/user-cluster.sh, cleanup/user-cluster.yml
https://github.com/rancher/rancher/issues/15417
=> Add cleanup script and yaml for imported cluster

pkg/controllers/user/resourcequota/resource_quota_sync.go, tests/core/test_project_resource_quota.py
https://github.com/rancher/rancher/issues/15521
=> Bug fix in used quota calculation

pkg/api/customization/node/node.go, pkg/controllers/user/nodesyncer/cordonfieldssyncer.go
https://github.com/rancher/rancher/issues/15550
https://github.com/rancher/rancher/issues/15430
=> don't retry drain if user error or timeout

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go, vendor/github.com/rancher/kontainer-engine/vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/cluster_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_amazon_elastic_container_service_config.go
Update vendor to support custom AMI option for EKS driver.
Issue:
https://github.com/rancher/rancher/issues/15389
Depends on:
https://github.com/rancher/kontainer-engine/pull/83
https://github.com/rancher/types/pull/571
=> Update vendor for EKS Custom AMI

pkg/auth/providers/ldap/ldap_client.go
https://github.com/rancher/rancher/issues/15582
=> check operator search result has at least one entry

pkg/controllers/user/workload/workload.go
Related issue: https://github.com/rancher/rancher/issues/15384
=> Should not change workload service cluster ip if exist

pkg/api/customization/project/project_store.go, pkg/api/store/namespace/store.go, tests/core/test_project_resource_quota.py
https://github.com/rancher/rancher/issues/15583
=> More API validation for quota

pkg/api/customization/project/project_store.go, pkg/api/store/namespace/store.go, pkg/controllers/user/resourcequota/resource_quota_sync.go, tests/core/test_project_resource_quota.py
https://github.com/rancher/rancher/issues/15639
=> Handle case when quota limit fields get added/removed

pkg/api/customization/project/project_store.go
https://github.com/rancher/rancher/issues/15583
=> API error message fix for quota validation

pkg/controllers/user/alert/upgrade/upgradeimpl.go, pkg/controllers/user/logging/upgrade/upgradeimpl.go, pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go, pkg/controllers/user/pipeline/upgrade/upgradeimpl.go
https://github.com/rancher/rancher/issues/15641
=> upgrade only if registry versions are not same

pkg/controllers/user/rbac/namespace_handler.go
@cjellick saw ns being stuck in Activating state on qa setup, due to `"{\"Conditions\":[{\"Type\":\"InitialRolesPopulated\",\"Status\":\"Unknown\"`. This error was seen in the log `error updating ns test-75261 status: Operation cannot be fulfilled on namespaces "test-75261": the object has been modified; please apply your changes to the latest version and try again`, and it was never retried
For now handling retry in a loop as the method is being called in go routine, and we can't rely on a framework for retry. 10 attempts should be plenty, but we can think of a more reliable fix in the future.
https://github.com/rancher/rancher/issues/15467
=> Retry setting ns InitialRolesPopulated on failure

cleanup/user-cluster.sh
Issue: https://github.com/rancher/rancher/issues/15417
=> Remove specifying kubeconfig for kubectl calls

pkg/remotedialer/wsconn.go
https://github.com/rancher/rancher/issues/15310
=> Set write deadline in client/agent connections

app/app.go, pkg/api/controllers/usercontrollers/usercontroller.go, pkg/api/server/server.go, pkg/clustermanager/manager.go, pkg/controllers/management/controller.go, pkg/controllers/management/usercontrollers/controller.go, pkg/controllers/user/controllers.go, pkg/controllers/user/healthsyncer/healthsyncer.go, pkg/dialer/factory.go, pkg/remotedialer/connection.go, pkg/remotedialer/server.go, pkg/telemetry/telemetry.go, pkg/tunnelserver/peermanager.go, pkg/tunnelserver/tunnel.go, vendor.conf, vendor/github.com/rancher/types/config/context.go, vendor/github.com/rancher/types/peermanager/peermanager.go
Needs: https://github.com/rancher/types/pull/576
https://github.com/rancher/rancher/issues/15443
=> Shard user controllers

pkg/auth/providers/saml/saml_client.go, pkg/auth/providers/saml/saml_provider.go
https://github.com/rancher/rancher/issues/15724
=> Add current user principal to allowedIDs during auth setup

vendor.conf, vendor/github.com/rancher/norman/objectclient/object_client.go, vendor/github.com/rancher/norman/store/proxy/proxy_store.go
Issue: https://github.com/rancher/rancher/issues/12332
=> Vendor update

pkg/controllers/management/node/labels.go
https://github.com/rancher/rancher/issues/15709
=> fix node label cannot be changed issue when adding node with labels

package/windows/Dockerfile.agent, package/windows/hyperkube.ps1, package/windows/run.ps1, package/windows/start.ps1, pkg/agent/main_windows.go, pkg/remotedialer/client_windows.go, pkg/rkenodeconfigserver/nodeserver.go, pkg/rkeworker/execute_windows.go, scripts/windows/validate.ps1
Fix https://github.com/rancher/rancher/issues/15593
=> Add CloudProvider support to Windows

vendor.conf, vendor/github.com/rancher/norman/store/proxy/proxy_store.go
See https://github.com/rancher/rancher/issues/15719
Depends on https://github.com/rancher/norman/pull/198
Brings in changes from norman to address the above.
=> Plug memory leak in proxy_store.realWatch

pkg/api/customization/project/project_store.go, pkg/clustermanager/manager.go, tests/core/test_project_resource_quota.py
from the user cluster. There used to be a bug when the namespaces were fetched from the management plane.
The code will only be called when project resource quota is enabled, and the project update happens
https://github.com/rancher/rancher/issues/15639
=> Quota validation: ability to fetch namespaces

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Update vendor for EKS kubectl fix.
Issue:
https://github.com/rancher/rancher/issues/15716
Depends on:
https://github.com/rancher/kontainer-engine/pull/86
=> Update vendor for EKS Kubectl Fix

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/15630
=> Update kube-prompt to v1.0.4

pkg/auth/providers/saml/saml_client.go, pkg/auth/providers/saml/saml_provider.go
This reverts commit d9c16bbe34a165eb14cb854d9240b49fe1ce7e31.
=> Revert "Add current user principal to allowedIDs during auth setup"

pkg/controllers/management/clusterstats/statsaggregator.go
Issue: we don't update version info if stats hasn't changed, causing k8s version to not reflect on cluster update 
https://github.com/rancher/rancher/issues/15831
=> update cluster version info

tests/core/test_default_roles.py, tests/core/test_rbac.py
Fix two races. 
1) On a projectRoleTemplateBinding a controller runs to attach the userPrincipalId, add a wait_for to allow the controller to attempt to attach the userPrincipalId. 
2) After a user is added to a project the controllers need time to add the user to the `default` namespace before they are able to create projects. Add a wait_for that validates the error returned on project create to allow controllers time to add bindings. 
Issue: https://github.com/rancher/rancher/issues/15207
=> Fix races in tests

pkg/api/controllers/usercontrollers/usercontroller.go
Problem: 
The finalizer `controller.cattle.io/cluster-agent-controller` is added to all clusters in v2.0.8 and prior. When upgrading from v2.0.8 to a newer version that lifecycle no longer exists and is left on the controller which stops k8s from deleting the resource. 
Solution:
Add a cleanup to finalizers on cluster delete to ensure that finalizer has been removed from the cluster.
=> Add cleanup to cluster delete

pkg/controllers/user/logging/utils/daemonset.go
https://github.com/rancher/rancher/issues/15908
=> fluentd logging: sort keys before building volumes

.drone.yml
Uses google dns as primary resolver.
=> add dns entry to plugin

pkg/controllers/user/alert/watcher/node.go
Issue:
https://github.com/rancher/rancher/issues/15974
https://github.com/rancher/rancher/issues/16003
https://github.com/rancher/rancher/issues/16000
https://github.com/rancher/rancher/issues/16001
=> handle alert panic

pkg/auth/providers/activedirectory/activedirectory_client.go, pkg/auth/providers/common/ldap/ldap_util.go, pkg/auth/providers/ldap/ldap_client.go
Till now we have been using the [Microsoft recommended AD query](https://docs.microsoft.com/en-us/windows/desktop/ADSI/search-filter-syntax) for looking up nested group memberships. That query turned out to be very slow and times out on large databases on the AD server side. We even found some [links](https://serverfault.com/questions/847988/slow-ad-group-sync) where others using this query have also found it to be slow.
So we are now going to use our own logic to get a user's parent groups recursively. According to some [answers](http://dunnry.com/blog/TransitiveLinkValueFilterEvaluation.aspx) online, that is faster than MS AD query.
Openldap already had this code, so this PR uses the same code for AD. It puts the code in common package, so both OpenLdap and AD can call the common …
=> Use recursive lookup for nested group search in AD

pkg/auth/providers/azure/azure_provider.go
Problem:
If a user has many groups the server calls azureAD for all groups in
sequence which can greatly increase login time
Solution:
Async the calls to azureAD when doing login
Issue https://github.com/rancher/rancher/issues/15858
=> Async calls to get user groups for azureAD

package/Dockerfile
https://github.com/rancher/rancher/issues/15978
=> Fix UI links to CLI

server/responsewriter/cache.go, server/responsewriter/content.go, server/responsewriter/gzip.go, server/responsewriter/middleware.go, server/server.go
Related issues
https://github.com/rancher/rancher/issues/15981
https://github.com/rancher/rancher/issues/16041
=> Add gzip and cache controll for http response

.github/ISSUE_TEMPLATE.md
- Note to search existing issues and link to contributing section of docs
- Simpler basic steps (what kind/steps/result/other info)
- Basic environment info as first step
- Request for more info moved to the bottom
- Moved most of the requested info into `docker info` (contains OS and kernel)
- Placeholder code blocks for output for better formatting
=> New issue template

pkg/api/store/workload/workload_store.go
nsID is empty on update,thus no namespaced scoped registry is attached to imagePullSecrets
Looks like the bug was introduced in 2.0.7, when `setSecrets` was added for workload updates 
https://github.com/rancher/rancher/issues/15994
=> get nsID from workload id on update

pkg/auth/providers/saml/saml_client.go
https://github.com/rancher/rancher/issues/15530
=> Check if UID is present in SAML Response

pkg/controllers/user/approuter/ingress_controller.go
For issue: https://github.com/rancher/rancher/issues/16194
=> Add setting check before rdns renew

app/role_data.go
Address Issue https://github.com/rancher/rancher/issues/16153
=> fix apigroup for sourcecodecredential

pkg/pipeline/engine/jenkins/engine.go
Address issue https://github.com/rancher/rancher/issues/16187
=> secure string conversion for registry fields

package/windows/hyperkube.ps1, package/windows/run.ps1, package/windows/start.ps1, pkg/agent/main_windows.go
(*) self-signed CA will be import into Windows Certificate Manager
(*) if using recognized CA, Windows agent doesn't need to set it
into TLSConfig
(*) tweaks components restarting sequence
Issues:
- https://github.com/rancher/rancher/issues/15966
=> Add Windows support for recognized CA

pkg/controllers/user/alert/deploy/notification_template.go, pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/alert/watcher/workload.go, pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/logging_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_elasticsearch_config.go
issue:
https://github.com/rancher/rancher/issues/16042
add ssl version select for elasticsearch in logging
types: 
https://github.com/rancher/types/pull/592
=> Add ssl version in rancher

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/eks_driver.go
Update vendor to include PR: https://github.com/rancher/kontainer-engine/pull/95
Issue:
https://github.com/rancher/rancher/issues/15390
=> Update vendor for EKS cluster name fix

pkg/api/store/workload/transform_store.go
Related issue https://github.com/rancher/rancher/issues/14230
=> [2.2]Operator workload Should be displayed in Rancher UI

pkg/controllers/user/endpoints/endpoints.go, pkg/controllers/user/endpoints/pod_endpoints.go, pkg/controllers/user/endpoints/service_endpoints.go
As we do not update the endpoints on pods anymore
=> Do not push endpoints update to pod on service update

vendor.conf, vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go, vendor/k8s.io/apimachinery/pkg/util/net/http.go, vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
=> Fix ALB for 2.1

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/16481
=> Update kube-prompt to v1.0.5

pkg/settings/setting.go
https://github.com/rancher/rancher/issues/16475
=> initialize required setting for HA from env vars

app/app.go, app/cluster_data.go, pkg/controllers/management/usercontrollers/controller.go
https://github.com/rancher/rancher/issues/16522
=> removeLocalCluster if --add-local=false

pkg/agent/clean/clean.go, pkg/controllers/management/usercontrollers/controller.go
Issue: https://github.com/rancher/rancher/issues/16602
=> Add cleanup for namespaces on local cluster delete

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/templates.go
Kontainer-engine PR: https://github.com/rancher/kontainer-engine/pull/98
Related issue: https://github.com/rancher/rancher/issues/16626
=> Add support for new EC2 instance types for eks cluster

vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/eks/templates.go
Related Kontainer-engine PR: https://github.com/rancher/kontainer-engine/pull/99
Related issue: https://github.com/rancher/rancher/issues/16639
=> [2.1]Add support for new EC2 instance types for eks cluster

vendor.conf, vendor/github.com/rancher/norman/parse/builder/builder.go, vendor/github.com/rancher/norman/store/proxy/proxy_store.go, vendor/github.com/rancher/norman/types/convert/convert.go, vendor/github.com/rancher/norman/types/reflection.go
To pull in get/list retry logic when querying k8s api
=> Update norman in vendor

pkg/api/server/managementstored/setup.go, pkg/api/store/cluster/cluster_store.go
Also factor out cluster store creation so it's not done twice.
=> Make sure shellhandler is populated in cluster store

pkg/pipeline/providers/gitlab/provider.go
Address issue: https://github.com/rancher/rancher/issues/16770
=> fix gitlab provider type

pkg/api/store/auth/store.go, pkg/auth/providers/activedirectory/activedirectory_actions.go, pkg/auth/providers/github/github_provider.go, pkg/auth/providers/ldap/ldap_actions.go, pkg/auth/providers/setup.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/authn_types.go
https://github.com/rancher/types/pull/640
Issue: https://github.com/rancherlabs/rancher-security/issues/22
=> handle create/update secrets on authconfig update

pkg/auth/providers/github/github_provider.go
https://github.com/rancher/rancher/issues/16802
=> dereference secret for github config

package/run.sh
https://github.com/rancher/rancher/issues/16386
=> Add DNS resolve result in agent start log

pkg/api/store/auth/store.go, pkg/auth/providers/activedirectory/activedirectory_actions.go, pkg/auth/providers/activedirectory/activedirectory_provider.go, pkg/auth/providers/azure/azure_actions.go, pkg/auth/providers/azure/azure_provider.go, pkg/auth/providers/common/password.go, pkg/auth/providers/github/github_provider.go, pkg/auth/providers/github/githubconfig_actions.go, pkg/auth/providers/ldap/ldap_actions.go, pkg/auth/providers/ldap/ldap_provider.go, pkg/auth/providers/saml/saml_provider.go
https://github.com/rancher/rancher/issues/16804
=> store and read data from applicationSecret for azureAD

pkg/api/customization/catalog/catalog.go, pkg/controllers/management/catalog/controller.go
1. address cluster and project level catalog send nil object in framework refresh (1hr). #16721
2. fix catalog bad refresh response message.
=> address catalog send nil obj in cluster and project lvl refresh

pkg/controllers/user/multiclusterapp/controller_multiclusterapp.go
The app created in user clusters should be named after the multiclusterapp name. So user can create more apps with same templates by creating different multiclusterapps
=> Set multiclusterapp.Name as the app.Name and namespace for workloads

app/kontainerdriver_data.go
Add aliyunkubernetescontainerservice and tencentkubernetesengine
=> Add external kontainer-drivers

pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/manager/prometheus_operator.go, pkg/controllers/user/alert/statesyncer/statesyncer.go, pkg/controllers/user/monitoring/metricExpression.go
1. clean operator crd after alert is deleted
2. use sequence map key
3. update metric expression
=> clean operator crd after alert is deleted

app/role_data.go, pkg/controllers/management/auth/crtb_handler.go
Problem:
cluster owner/member and some custom role could not see cluster level metric
project custom rule could not see project level metric
Solve:
add clustermonitorgraphs access role for cluster owner/member and some custom role
add projectmonitorgraphs access role for project custom role
=> Solve cluster owner could not see metrics

pkg/rkedialerfactory/rke_dialer.go
https://github.com/rancher/rancher/issues/16976
=> always use private ip when dialing

pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/deployer/notification_template.go, pkg/controllers/user/alert/initdata.go, pkg/controllers/user/alert/manager/prometheus_operator.go, pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/workload.go
Problem:
1. don't know project, pod name, namespace in alert info
2. typo
Solution:
1. add more info for alert
2. fix typo
Issue:
https://github.com/rancher/rancher/issues/16990
https://github.com/rancher/rancher/issues/16592
https://github.com/rancher/rancher/issues/16823
=> Add more alert info

pkg/pipeline/remote/gitlab/gitlab.go
Address issue https://github.com/rancher/rancher/issues/16726
In gitlab, users can define subgroup in groups, and a valid repo url can be: `https://hostname/parentgroup/subgroup/subsubgroup/repo.git`. So the assumption to parse it in owner/repo format is not correct.
=> fix gitlab reponame parsing

pkg/auth/providers/ldap/ldap_actions.go
https://github.com/rancher/rancher/issues/17117
=> fix wrong args in saveLdapConfig

pkg/api/customization/namespace/namespace.go
Related issue https://github.com/rancher/rancher/issues/16193
=> Should get cluster id from url in namespace move action

pkg/pipeline/engine/jenkins/mappper.go
Address issue: https://github.com/rancher/rancher/issues/16624
=> do not share dockerd storage path in pipeline build pod

pkg/controllers/user/alert/config/config.go, pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/notifiers/sender.go
Related issue: https://github.com/rancher/rancher/issues/15395
Problem: current pageduty event api is v1
Solve: update to v2
=> Upgrade pageduty

vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
https://github.com/rancher/rancher/issues/17215
=> 2.1 bump vendor (types)

pkg/api/customization/cluster/actionhandler.go, pkg/api/customization/cluster/formatter.go, pkg/controllers/management/clusterprovisioner/provisioner.go, vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go, vendor/github.com/rancher/kontainer-engine/vendor.conf, vendor/github.com/rancher/rke/cluster/certificates.go, vendor/github.com/rancher/rke/cmd/cert.go, vendor/github.com/rancher/rke/cmd/common.go, vendor/github.com/rancher/rke/cmd/up.go, vendor/github.com/rancher/rke/pki/services.go, vendor/github.com/rancher/rke/vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go
https://github.com/rancher/types/pull/622
https://github.com/rancher/rke/pull/1032
https://github.com/rancher/kontainer-engine/pull/97
https://github.com/rancher/rke/issues/450
=> Add rotate cert api action

app/app.go, pkg/tls/tls.go
https://github.com/rancher/rancher/issues/15424
=> Add checks/error handling around using certificates in container

pkg/dynamiclistener/server.go
https://github.com/rancher/rancher/issues/16693
=> Don't redirect to HTTPS on /ping and /healthz

vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go
https://github.com/rancher/rancher/issues/15585
=> bump vendor (types)

app/authconfig_data.go, pkg/api/store/auth/store.go, pkg/api/store/password/password.go, pkg/api/store/password/store.go, pkg/auth/providers/common/password.go, pkg/auth/providers/setup.go
- change namespace for auth configs to global namespace from `mgmt-secrets`
- change name of secret created for password field to random name 
- while updating object, check if secret already exists - avoid creating new one 
- delete object deletes secrets 
- don't assign back value from secret (api hides it anyway) 
- for controllers use, added `GetValueForPasswordField` method
=> fix for password fields 

pkg/controllers/management/clusterprovisioner/provisioner.go
https://github.com/rancher/rancher/issues/17272
@galal-hussein
=> Fixed gke cluster provisioner regression

pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/project_template.go
Add support for milliseconds precision in Elasticsearch #17238
=> add millisecond precision

pkg/controllers/user/pipeline/controller/pipelineexecution/pipelineexecution.go
Address issue: https://github.com/rancher/rancher/issues/17232
Problem:
When a running pipeline execution is removed, the build pod is not
terminated.
Solution:
Do finalization properly on pipeline execution removal.
=> Finalize when running pipeline execution is removed

pkg/controllers/user/helm/controller.go
Problem:
Cannot delete Rancher catalog apps when their creator user is deleted
Solution:
We should fallback to use project token to remove helm
https://github.com/rancher/rancher/issues/16274
=> App cannot be removed if the creator is deleted

pkg/controllers/user/alert/deployer/upgradeimpl.go
Problem:
alert change schema in 2.2, we should not delete old alert data in case user want to downgrade
Solution:
not delete old alert data when upgrade
Issue:
https://github.com/rancher/rancher/issues/17042
=> Not delete old alert data when upgrade

pkg/pipeline/engine/jenkins/convert.go, pkg/pipeline/engine/jenkins/mappper.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/project.cattle.io/v3/pipeline_types.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_apply_app_config.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_publish_catalog_config.go
Address issue: https://github.com/rancher/rancher/issues/17277
Related types pr: https://github.com/rancher/types/pull/671
=> Rename catalog field in applyApp/publishCatalog config

pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/controller.go, pkg/controllers/user/alert/manager/prometheus_operator.go
Problem:
1. Alert rule continually updating
2. Fix alert advanced options do not work
Solution:
1. sorted before save and compare
2. not use default value in advance options
Issues:
https://github.com/rancher/rancher/issues/17114
https://github.com/rancher/rancher/issues/17029
=> Fix alert bug

app/role_data.go, pkg/api/customization/globaldns/validator_globaldns.go, pkg/api/customization/globalnamespaceaccess/access_common.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go, pkg/api/customization/multiclusterapp/store.go, pkg/api/server/managementstored/setup.go, pkg/controllers/management/controller.go, pkg/controllers/management/globaldns/globaldns_handler.go, pkg/controllers/management/globaldns/globaldns_provider.go, pkg/controllers/management/globalnamespacerbac/rbac_common.go, pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_provider.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_provider_spec.go
Rancher types PR: https://github.com/rancher/types/pull/665
=> RBAC for multiclusterapp and globaldns

pkg/api/store/service/service.go
Problem:
Rancher will always drop the ports in the payload and add a default 42 port in server side when create a service.
Solution:
We should check if there are ports defined in the payload and we should respect them if there are.
Issue:
https://github.com/rancher/rancher/issues/17288
=> Fix the issue that ports are not populated when creating service

pkg/controllers/user/dnsrecord/dnsrecord.go
Problem:
As Alias type DNS record is a service without selector. Kubernetes endpoint controller will not create the endpoints automatically for it. Rancher is responsible for creating the endpoints. However the name field of the endpoint port is wrong. It should be the same with the name defined in service port.
Solution:
Fix it by always using the ports defined in service spec
https://github.com/rancher/rancher/issues/17321
=> Fix alias type dns record issue

pkg/api/customization/setting/setting.go
Address issue: https://github.com/rancher/rancher/issues/15273
=> Make cacerts setting read-only

pkg/api/customization/multiclusterapp/multi_cluster_app.go
https://github.com/rancher/rancher/issues/17485
=> MultiClusterApp bug fixes 

pkg/controllers/user/multiclusterapp/state.go
https://github.com/rancher/rancher/issues/17483
=> MultiClusterApp State fix 

package/Dockerfile
https://github.com/rancher/rancher/issues/16981
=> v2.2.0-rc3

tests/core/test_cluster_catalog.py, vendor.conf, vendor/github.com/rancher/rke/cluster/addons.go, vendor/github.com/rancher/rke/cluster/cluster.go, vendor/github.com/rancher/rke/cluster/defaults.go, vendor/github.com/rancher/rke/cluster/network.go, vendor/github.com/rancher/rke/cmd/config.go, vendor/github.com/rancher/rke/docker/docker.go, vendor/github.com/rancher/rke/services/etcd.go, vendor/github.com/rancher/rke/util/util.go, vendor/github.com/rancher/rke/vendor.conf
And attempted TF fix https://github.com/rancher/rancher/issues/17567
=> RKE vendor update

app/machinedriver_data.go
This change adds the Cloud.ca machine driver to the list of drivers
available by default for installation with Rancher.
For /issues/15444
=> Add Cloud.ca machine driver

pkg/api/store/ingress/store.go, tests/core/test_ingress.py, vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_http_ingress_path.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_http_ingress_rule_value.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_ingress_rule.go
Issue: #17065
Related types PR: rancher/types#652
UI PR rancher/ui#2585
UI issue #17529
=> Change paths of ingressRule from map to slice

package/Dockerfile, pkg/api/customization/app/app.go, pkg/controllers/user/helm/common/common.go, pkg/controllers/user/helm/controller.go, vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_app_upgrade_config.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_rollback_revision.go
This PR is a dupe of https://github.com/rancher/rancher/pull/17193, with updated types and helm release
Problem:
Need to support helm upgrade for those immutable fields by setting an option with --force
Solution:
add options to set --force of helm upgrade.
Issue:
#16769
Related:
rancher/helm#13
rancher/types#656
=> added forceupgrade option for catalog apps

pkg/controllers/management/podsecuritypolicy/template.go, tests/core/test_pod_security_policies.py
Integration tests are also included. Issue #15728
=> Fix for incorrect PSPTPB deletion

pkg/controllers/user/logging/configsyncer/configgenerator.go, pkg/controllers/user/logging/configsyncer/configsyncer.go
Problem:
Get crash when only create project logging
Solution:
Check before directly use the clusterLoggingList
Issue:
https://github.com/rancher/rancher/issues/17606
=> Fix logging crash

pkg/controllers/user/logging/generator/project_template.go
Problem:
generate project config file failed when launching logging
Solution:
update the project config template
Issue:
https://github.com/rancher/rancher/issues/17641
=> fixed the project config template bug

package/Dockerfile
https://github.com/rancher/rancher/issues/17641
https://github.com/rancher/rancher/issues/17647
=> cli v2.2.0-rc5

pkg/api/customization/app/app.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go, pkg/controllers/user/helm/state.go, pkg/controllers/user/multiclusterapp/controller_multiclusterapp.go, pkg/controllers/user/multiclusterapp/state.go
https://github.com/rancher/rancher/issues/17687
https://github.com/rancher/rancher/issues/17483
=> Multi cluster app state conditions 

pkg/api/customization/cluster/actionhandler.go
https://github.com/rancher/rancher/issues/17702
=> Fix backupEtcd action handler response

pkg/controllers/user/multiclusterapp/controller_multiclusterapp.go
Currently, editing target projects or removing them only reflected on the multi cluster object. Adding reconcile logic to delete the unwanted apps. 
https://github.com/rancher/rancher/issues/17484
=> add logic for update/delete targets on multi cluster app

pkg/controllers/user/helm/state.go
https://github.com/rancher/rancher/issues/17768
=> don't retry if error isNotFound for app state calculation

pkg/api/customization/app/app.go, pkg/api/server/managementstored/setup.go, pkg/api/store/app/store.go, pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go
- don't allow apps controlled by multiclusterapp to be updated/deleted
- remove targets from multiclusterapp on project/cluster delete
=> Multi cluster app fix around deletion use cases 

pkg/api/customization/cluster/actionhandler.go
https://github.com/rancher/rancher/issues/17800
=> Add restriction for normal users to rotate certificates

pkg/api/customization/cluster/actionhandler.go
https://github.com/rancher/rancher/issues/17800
=> Add restriction for backup and restore action

tests/core/test_app.py
https://github.com/rancher/rancher/issues/17582
=> test_app_wordpress TF fix

pkg/controllers/management/globaldns/globaldns_handler.go
This is the fix to update the ingress's hostname and update endpoints if the globalDNS that created the ingress is updated to use a different FQDN. 
https://github.com/rancher/rancher/issues/17832
=> Update the ingress's hostname if globalDNS FQDN is changed

tests/core/test_app.py
Wait for the annotation as it's being inserted in an async way, and workload presence doesn't guarantee an immediate update
=> Fix test_app_namespace_annotation

package/kubectl-shell.sh, package/shell-setup.sh, pkg/api/customization/cluster/shell.go
=> Resend cacert after etcdbackup restore

pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/httpproxy/sign_utils.go
- credential fields are required for authentication, must be required 
- credID passed during signing should be `ns:name`
=> small api changes for cloud credential 

pkg/controllers/management/clusterprovisioner/provisioner.go
https://github.com/rancher/rancher/issues/17304
=> Reset message/reason when set ClusterConditionProvisioned to true

pkg/catalog/manager/manager.go, pkg/catalog/manager/traverse.go
https://github.com/rancher/rancher/issues/17523
=> Use deleteNamespaced while deleting templates/versions

pkg/httpproxy/sign.go
`X-Forwarded-Header` in the signed request causes issues and returns `AuthFailure: AWS was not able to validate the provided access credentials` even if the credentials are correct
=> don't consider x-forwarded-for header for awsv4 signing request

pkg/api/customization/logging/action.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/logging/config/config.go, pkg/controllers/user/logging/configsyncer/configgenerator.go, pkg/controllers/user/logging/configsyncer/configsyncer.go, pkg/controllers/user/logging/deployer/testerdeployer.go, pkg/controllers/user/logging/generator/cluster_template.go, pkg/controllers/user/logging/generator/generator.go, pkg/controllers/user/logging/generator/project_template.go
Problem:
support ssl config for custom config logging target
Solution:
add ssl fields to custom logging target
Types:
https://github.com/rancher/types/pull/702
Issue:
https://github.com/rancher/rancher/issues/17696
=> Add cert config for custom logging target

pkg/api/server/managementstored/setup.go, pkg/api/store/globaldns/globaldns_store.go, tests/core/test_globaldns.py
Now we check for FQDN being unique while creating/updating a GlobalDNS entry.
https://github.com/rancher/rancher/issues/17901
=> validate FQDN is unique while creating GlobalDNS entries

pkg/api/store/cluster/cluster_store.go
https://github.com/rancher/rancher/issues/17817
=> Enable local backup by default on API level

pkg/api/customization/cluster/actionhandler.go
https://github.com/rancher/rancher/issues/17317
=> Add rotate certificate output type

scripts/build-server
UI_INDEX needs to be set when dev version.
=> Fix UI can not open in dev version

pkg/controllers/user/alert/deployer/deployer.go
Problem:
could not only enable alert because after refactor monitoring deploy
operator logic is updated, but related deploy alertmanager code not update completely
Solution:
update deploy alertmanager logic
Issue:
https://github.com/rancher/rancher/issues/18010
=> fix regression bug: only enable alert but not monitoring not deploy prometheus

pkg/controllers/user/alert/deployer/upgradeimpl.go
Problem:
1. Project alerting can't show in UI after migrated
2. Need to delete old alertmanager when upgrade rancher
Solution:
1. use clusterName:projectName as projectId
2. we should delete old alertmanager automatically
Issue:
https://github.com/rancher/rancher/issues/17042
https://github.com/rancher/rancher/issues/18007
=> Improve Alert upgrade

pkg/api/customization/roletemplate/roletemplate.go, tests/core/test_role_template.py
Addresses: https://github.com/rancher/rancher/issues/18052
=> Get roletemplate in roletemplate validation only if method is PUT

pkg/httpproxy/sign.go
address https://github.com/rancher/rancher/pull/17983#issuecomment-462876922
=> consider only required headers for aws signing request

pkg/api/customization/multiclusterapp/multi_cluster_app.go
To fix: https://github.com/rancher/rancher/issues/18136
=> Fix panic on addProjects while checking access to targets

pkg/api/customization/cluster/formatter.go
https://github.com/rancher/rancher/issues/18133
=> Handle unset backup config on the API level

pkg/controllers/user/monitoring/projectHandler.go
**Problem:**
- Remote reader mode only allow `project-level` Prometheus to share the
metrics from `cluster-level` Prometheus
- Remote reader mode cannot save the namespace-related metrics from
`cluster-level` Prometheus
**Solution:**
Add federation support
**Issue:**
#17390
https://github.com/rancher/system-charts/pull/13
=>  Support choosing Prometheus sync mode between federate and remote

tests/core/conftest.py, tests/core/test_pod_security_policies.py
=> Revert "PSPT test improvement"

pkg/controllers/management/controller.go, pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go, pkg/controllers/management/multiclusterapp/enqueue.go, pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go, pkg/controllers/management/multiclusterapp/interval.go, pkg/controllers/management/multiclusterapp/state.go, pkg/controllers/user/controllers.go, pkg/controllers/user/helm/state.go
- move controller from user to mgmt
- enqueue mcapp on app change in mgmt
- add interval ticker for mcapp upgrade
https://github.com/rancher/rancher/issues/17856
https://github.com/rancher/rancher/issues/17818
https://github.com/rancher/rancher/issues/17701
=> mcapp controller fixes

app/kontainerdriver_data.go
Drivers:
- aliyunkubernetescontainerservice
- tencentkubernetesengine
- huaweicontainercloudengine
=> Update kontainer-engine drivers version

pkg/controllers/user/helm/state.go
https://github.com/rancher/rancher/issues/17863
=> check if app belongs to current cluster before updating state

pkg/controllers/management/drivers/nodedriver/machine_driver.go
https://github.com/rancher/rancher/issues/18194
https://github.com/rancher/rancher/issues/18201
=> update cloudCredentialSchema if it already exists and resourceFields change

pkg/controllers/user/alert/common/common.go, pkg/controllers/user/alert/configsyncer/configsyncer.go, pkg/controllers/user/alert/deployer/notification_template.go, pkg/controllers/user/alert/watcher/event.go, pkg/controllers/user/alert/watcher/node.go, pkg/controllers/user/alert/watcher/pod.go, pkg/controllers/user/alert/watcher/syscomponent.go, pkg/controllers/user/alert/watcher/workload.go
Problem:
pod and workload alert lack info
Solution:
update alert notify template
Issue:
https://github.com/rancher/rancher/issues/18156
https://github.com/rancher/rancher/issues/18160
=> fix alert notify template lack info

pkg/agent/main_windows.go, pkg/auth/providers/common/usermanager.go, pkg/controllers/management/compose/controller.go, pkg/controllers/management/test/e2e/authz_test.go, pkg/controllers/user/alert/deployer/upgradeimpl.go, pkg/controllers/user/nodesyncer/nodessyncer.go, pkg/controllers/user/pipeline/controller/pipeline/pipeline.go, pkg/controllers/user/pipeline/controller/pipelineexecution/deploy.go, pkg/pipeline/engine/jenkins/client.go, pkg/pipeline/providers/utils.go, pkg/pipeline/remote/bitbucketserver/client.go, pkg/pipeline/remote/gitlab/gitlab.go, pkg/rkenodeconfigserver/nodeserver.go
Fixes for issues reported by https://goreportcard.com/report/github.com/rancher/rancher#ineffassign
=> ineffassign fixes

pkg/controllers/user/logging/deployer/appdeployer.go
Problem:
if we don't check stale logging app, may not deploy if there is a stale
app
Solution:
check app delete timestampe
Issue:
https://github.com/rancher/rancher/issues/18214
=> need check whether there is stale app when enable logging

app/kontainerdriver_data.go
Update driver to address https://github.com/rancher/rancher/issues/18268
=> aliyun driver v0.2.4

server/responsewriter/cache.go, server/server.go, vendor.conf, vendor/github.com/rancher/norman/api/writer/html.go
Problem:
Frame-Options header is not being set, this is a potential secutiry
issue
Solution:
Set the header "X-Frame-Options:deny"
Issue: https://github.com/rancherlabs/rancher-security/issues/35
=> Add Frame-Options header

pkg/api/customization/globalnamespaceaccess/access_common.go
Addresses: https://github.com/rancher/rancher/issues/18281
=> Throw 422 when any of the mcapp.Roles is invalid/does not exist

pkg/audit/audit.go
Problem:
json response from proxy are not compacted
Solution:
compact json before write to audit log
Issue:
https://github.com/rancher/rancher/issues/18301
=> fix json response from proxy are not compacted in audit log

pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go, pkg/controllers/user/helm/controller.go
https://github.com/rancher/rancher/issues/18250
=> move namespace management to user cluster

pkg/dynamiclistener/server.go, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/15885
=> Make TLS version and ciphers configurable

pkg/controllers/management/clusterprovisioner/provisioner.go
Problem: When editing a DO cluster, the update label in the UI does not appear for approximately 30 seconds. In some scenarios it does not appear at all.
Solution: Push update to kubernetes immediately with intended changes once we know changes are to take place.
Issue: https://github.com/rancher/rancher/issues/17865
=> Display update tag soon after save

pkg/controllers/management/multiclusterapp/state.go
https://github.com/rancher/rancher/issues/17899
=> propagate app state to multi cluster app target

pkg/controllers/management/etcdbackup/etcdbackup.go
**Problem:**
RKE S3 Backup doesn't work with Aliyun S3
**Solution:**
add auto config bucketLookup type by s3 endpoint url
**Related PRs:**
https://github.com/rancher/rke-tools/pull/42
**Related PRs/issues:**
https://github.com/rancher/rancher/issues/18262
=> Add etcdbackup auto config lookup type by endpoint

pkg/controllers/management/auth/globalrolebinding_handler.go
Addresses: https://github.com/rancher/rancher/issues/18318
GlobalRoleBinding lifecycle was creating roleBindings with Roles for catalogTemplates and catalogTemplateVersions, for all globalRoles that had rules for "templates" and "templateVersions" resources. But before this logic, there was a check to see if the clusterRoleBinding for the globalRoleBinding already exists, and if it did then this method was returning, before creation of roleBindings for catalogTemplates/versions happened. So users created prior to upgrade got escaped from this roleBinding creation and didn't get access to templates after upgrade. The upgrade case was first tested with admin, and since admin has access to all resources, this problem wasn't discovered
=> Create template/version rules for users created pre-upgrade

package/Dockerfile
addresses
https://github.com/rancher/rancher/issues/17981
https://github.com/rancher/rancher/issues/17147
=> CLI v2.2.0-rc10

pkg/api/customization/multiclusterapp/store.go
https://github.com/rancher/rancher/issues/18335
=> validate duplicate targets on multiclusterapp create

app/machinedriver_data.go, pkg/controllers/management/drivers/nodedriver/machine_driver.go
https://github.com/rancher/rancher/issues/18131
=> default vcenterPort value 443

pkg/api/customization/cred/store.go, pkg/api/server/managementstored/setup.go, tests/core/test_node.py
https://github.com/rancher/rancher/issues/18039
=> don't allow cloudcredentials to be deleted if referenced by node template

pkg/api/customization/multiclusterapp/multi_cluster_app.go, pkg/api/customization/multiclusterapp/store.go
https://github.com/rancher/rancher/issues/18383
https://github.com/rancher/rancher/issues/18335
=> error 422 when duplicate projects in mcapp targets

pkg/controllers/management/globaldns/globaldns_provider.go, tests/core/test_globaldns.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_alidns_provider_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cloudflare_provider_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_provider.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_provider_spec.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_route53provider_config.go
Address issue: https://github.com/rancher/rancher/issues/18346
Dependent types PR: https://github.com/rancher/types/pull/734
=> Move globaldns RootDomain field from provider configs to generic spec

package/Dockerfile.agent, package/kubectl-shell.sh
- fixes https://github.com/rancher/rancher/issues/18363
- Add sysstat to the agent image. Needed for system-tools stats command
=> Fix agent rollback

pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go
Address issue: https://github.com/rancher/rancher/issues/18324
Dependent system-charts PR: https://github.com/rancher/system-charts/pull/20
=> Implement globaldns Alidns provider in system chart way

pkg/controllers/user/helm/common/common.go
Addresses: https://github.com/rancher/rancher/issues/18088
=> Force app install so helm takes creator's updated permissions

scripts/print-catalog-images/requirements.txt, tests/requirements.txt
pyyaml for security alerts
cryptography for failing builds
=> Pin some failing pythhon dependencies

pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go, tests/core/test_kontainer_drivers.py
This change corrects an issue where third-party drivers were not updating
their schemas after the driver binary was updated (via a url change). This
change corrects that so that the schema will update.
Issue:
#17712 
Depends on:
https://github.com/rancher/kontainer-engine-driver-example/pull/8
=> Fixing third-party cluster drivers not updating

pkg/clusterrouter/proxy/proxy_server.go, vendor.conf, vendor/github.com/rancher/norman/pkg/kwrapper/k8s/config.go
https://github.com/rancher/rancher/issues/17028
=> Assign TLS certs for fix local HA websockets

pkg/api/customization/globalnamespaceaccess/access_common.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go, pkg/api/customization/multiclusterapp/store.go, pkg/api/customization/multiclusterapp/validator_multiclusterapp.go, pkg/api/server/managementstored/setup.go, pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go, tests/core/test_multi_cluster_app.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/multi_cluster_app.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_multi_cluster_app_spec.go
Addresses: https://github.com/rancher/rancher/issues/18260
=> Multiclusterapp RBAC and api validation changes for Roles

tests/core/test_multi_cluster_app.py, tests/core/test_role_template.py
https://github.com/rancher/rancher/issues/18143
=> Add wait before updating roletemplate

pkg/api/customization/globalnamespaceaccess/access_common.go, pkg/api/customization/multiclusterapp/validator_multiclusterapp.go, tests/core/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/18326
=> Show missing roles in err msg and fix err code

vendor.conf, vendor/github.com/rancher/rke/vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go, vendor/github.com/rancher/types/vendor.conf
https://github.com/rancher/rancher/issues/18514
=> Types vendor update for 2.1.x

pkg/api/customization/globaldns/action_globaldns.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_windows_default.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_update_global_dnstargets_input.go
https://github.com/rancher/rancher/issues/18366#issuecomment-469382941 
https://github.com/rancher/types/pull/752
=> remove mcAppId validation from addProjects

pkg/api/customization/globalnamespaceaccess/access_common.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go, pkg/api/customization/multiclusterapp/store.go, pkg/api/customization/multiclusterapp/validator_multiclusterapp.go, pkg/api/server/managementstored/setup.go, pkg/controllers/management/multiclusterapp/handler_multiclusterapp.go, tests/core/test_multi_cluster_app.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/multi_cluster_app.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/schema/schema.go, vendor/github.com/rancher/types/apis/management.cattle.io/v3/zz_generated_deepcopy.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_multi_cluster_app_spec.go
Types PR: https://github.com/rancher/types/pull/751
https://github.com/rancher/rancher/issues/18521
https://github.com/rancher/rancher/issues/18494
https://github.com/rancher/rancher/issues/18495
=> Multiclusterapp Roles changes

app/kontainerdriver_data.go
Problem:
Users cannot scale up or down TKE and ACK clusters
Solution:
Update TKE and ACK which support the update
https://github.com/rancher/rancher/issues/17175
https://github.com/rancher/rancher/issues/17174
=> Update ACK and TKE version

pkg/controllers/user/logging/utils/elasticsearch.go, pkg/controllers/user/logging/utils/fluentd.go, pkg/controllers/user/logging/utils/kafka.go, pkg/controllers/user/logging/utils/splunk.go, pkg/controllers/user/logging/utils/syslog.go, pkg/controllers/user/logging/utils/templatewrap.go, pkg/controllers/user/logging/utils/testwrap.go
Improve logging test function return error message
Problem:
Error message for logging test related function will return to UI, need more clear
Solution:
improve error message
Issue:
https://github.com/rancher/rancher/issues/18546
=> Improve error message for logging test function

app/app.go, pkg/api/server/managementstored/setup.go, pkg/api/server/server.go, server/server.go
https://github.com/rancher/rancher/issues/18603
=> hide globalDNS if addLocal=false

pkg/api/customization/globalnamespaceaccess/access_common.go, tests/core/test_multi_cluster_app.py
Addresses the error message change requested in this https://github.com/rancher/rancher/issues/18326#issuecomment-470371227
=> Include cluster name with project name in err msg

pkg/api/customization/globalnamespaceaccess/access_common.go, tests/core/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/18665
=> validate projectIds for multiclusterapp

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/18676
=> Update embedded kubectl to 1.12.6

package/Dockerfile
=> cli v2.2.0-rc12

pkg/audit/filter.go
Problem:
Deleting a namespace with audit logging enabled hangs, when use kubectl to delete namespace, it will call some api, include delete namespace, get namespace, get namespace with watch=true, when call watch=true, the server will use responseWriter flush function to flush data to the client, now we don't have the flush function for auditWriter, which will hang when calling API with watch=true, in some case it will also call the closeNotify function
Solution:
Add flush and closeNotify function
Issue:
https://github.com/rancher/rancher/issues/17027
=> Add flush and close notify function to auditWriter

scripts/publish-manifests.sh
We need this to publish properly configured multi-arch images
=> Add script for publish manifest of 3rd party imgs

app/app.go, pkg/api/server/managementstored/setup.go, pkg/api/server/server.go, server/server.go
https://github.com/rancher/rancher/issues/18603
=> fixing localClusterEnabled logic for disabling globalDNS

package/Dockerfile
Issue https://github.com/rancher/rancher/issues/18670
=> cli v2.2.0-rc13

pkg/controllers/management/clusterprovisioner/provisioner.go
Problem:
On rancher upgrade clusters flip into updating when caches are not
populated with dynamic drivers
Solution:
Add a one time update to allow caches to populate before updating
cluster configs due to driver CRDs and dynamic schemas being created
=> Cluster update on upgrade

package/Dockerfile
This pr is to bring the fix for https://github.com/rancher/rancher/issues/18589 into master
=> machine v0.15.0-rancher6-1

.drone.yml, Dockerfile.dapper, package/Dockerfile, package/Dockerfile.agent, pkg/settings/setting.go, scripts/package, scripts/test, tests/core/test_kontainer_drivers.py
This PR includes the following changes:
- Update the ci scripts and dockerfile to make rancher running on ARM64 platform.
- Update `.drone.yml` to support multiarch CI/CD
Related Issue
https://github.com/rancher/rancher/issues/16461
=> Support deploying and managing ARM64 k8s cluster using docker manifest and make Rancher running on ARM64 platform 

app/machinedriver_data.go, pkg/api/customization/nodetemplate/validation.go, tests/core/test_node.py
https://github.com/rancher/rancher/issues/18731
=> make cloudCredentialID required for known node drivers

pkg/controllers/user/nodesyncer/nodessyncer.go, vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go, vendor/github.com/rancher/kontainer-engine/vendor.conf, vendor/github.com/rancher/rke/cluster/cluster.go, vendor/github.com/rancher/rke/cmd/cert.go, vendor/github.com/rancher/rke/cmd/etcd.go, vendor/github.com/rancher/rke/services/etcd.go
https://github.com/rancher/rancher/issues/18709
=>  Fix nodesyncer annotation 

pkg/api/customization/globalnamespaceaccess/access_common.go, tests/core/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/18707
=> Return cumulative error message for missing roles

pkg/api/customization/globalnamespaceaccess/access_common.go, tests/core/test_multi_cluster_app.py
Addresses: https://github.com/rancher/rancher/issues/18734
=> Relax checks during mcapp upgrade for admin

pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/18766
=> Fix double backup create issue

pkg/controllers/management/clustergc/cluster_scoped_gc.go
Problem:
remain alert finalizer cause cluster namespace stay in terminating status
Solution:
add more alert finalizer to cluster gc controller
Issue:
https://github.com/rancher/rancher/issues/18789
=> Add clean finalizer for clusterAlertGroup and projectAlertRule

pkg/controllers/user/monitoring/metricExpression.go
**Issue:**
https://github.com/rancher/rancher/issues/18624
https://github.com/rancher/system-charts/pull/26
=> Fix predefined metrics not match in monitoring

package/Dockerfile
https://github.com/rancher/rancher/issues/17981
=> cli 2.2.0-rc14

pkg/api/customization/globaldns/action_globaldns.go, pkg/api/customization/globaldns/validator_globaldns.go, pkg/api/server/managementstored/setup.go, tests/core/test_globaldns.py
To address: https://github.com/rancher/rancher/issues/18839
=> Use necessary fields to initialize MemberAccess struct for globalDNS

tests/core/test_app.py, tests/core/test_node.py
https://github.com/rancher/rancher/issues/18145
https://github.com/rancher/rancher/issues/18810
=> attempt fixing test failures

pkg/controllers/management/clusterprovisioner/provisioner.go
Problem:
On upgrade local cluster or rke will cause warnings in the logs due to
not finding the driver in the config
Solution:
Only look for a schema if we have a driver name
Stop potential panic in map lookup
Clarify log statement
Issue: https://github.com/rancher/rancher/issues/18843
=> Update upgrade update for no driver

pkg/api/customization/globaldns/action_globaldns.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go, pkg/api/customization/multiclusterapp/validator_multiclusterapp.go
To address: https://github.com/rancher/rancher/issues/18852
=> Get refreshed mcapp, gdns from etcd in actionHandlers

pkg/api/customization/cluster/actionhandler.go, pkg/controllers/management/etcdbackup/etcdbackup.go, vendor.conf, vendor/github.com/rancher/kontainer-engine/drivers/rke/rke_driver.go, vendor/github.com/rancher/rke/cluster/etcd.go
https://github.com/rancher/rancher/issues/18838
=> Handle mixed backup providers

pkg/clusterrouter/proxy/proxy_server.go, pkg/rkecerts/certs.go, pkg/rkeworker/docker.go, pkg/rkeworker/execute.go, vendor.conf, vendor/github.com/rancher/rke/cluster/addons.go, vendor/github.com/rancher/rke/cluster/cluster.go
https://github.com/rancher/rancher/issues/18805
=> check if bundle changed

pkg/controllers/management/clusterprovisioner/provisioner.go
Removed unused error check introduced by commit: a4aa3906dbd30fac94a56b06dfee36cb0ca7b2ae
=> Remove unused error check

pkg/api/customization/globaldns/action_globaldns.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go
https://github.com/rancher/rancher/issues/18897
=> Fetch mcapp/gdns separately within add/removeProjects

pkg/api/customization/globaldns/validator_globaldns.go, tests/core/test_globaldns.py, tests/core/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/18872
https://github.com/rancher/rancher/issues/18873
=> Fix mcapp and gdns flaky tests

scripts/validate
Problem:
gometalinter is timing out in CI and is being run inefficiently
Solution:
Update script to use go package listing which speeds up build times
=> Update validate script

pkg/api/customization/cluster/actionhandler.go
https://github.com/rancher/rancher/issues/18920
=> validate backup config for cluster with local backup config

pkg/api/customization/globaldns/action_globaldns.go, pkg/api/customization/multiclusterapp/multi_cluster_app.go
https://github.com/rancher/rancher/issues/18941
=> Fix regression for add/remove projects

pkg/controllers/user/monitoring/operatorHandler.go
=> Clean reason & msg after withdrawing Operator

pkg/api/store/cluster/cluster_store.go
Issue: UI currently updates cluster with replace=true, which means
if secretKey is not passed in backupConfig, it gets reset.
https://github.com/rancher/rancher/issues/18964
=> set old backupConfig secretKey if it doesn't exist in data

pkg/api/store/cluster/cluster_store.go
Problem:
When upgrading a cluster, the value of norman-password-type field will
be reset to blank.
Solution:
Set old value it it doesn't exist in data
Issue:
https://github.com/rancher/rancher/issues/19009
=> Fixed the bug of missing value of password field

pkg/controllers/management/drivers/nodedriver/utils.go
https://github.com/rancher/rancher/issues/18993
=> correctly assign value to int flag from driver

pkg/api/customization/monitor/cluster_graph_action.go, pkg/api/customization/monitor/project_graph_action.go
Related issue: https://github.com/rancher/rancher/issues/19068
=> Give a nicer error when fail to query metrics

pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/19093
=> Fix backupConfig panic

pkg/controllers/management/clusterprovisioner/provisioner.go
Problem:
All attempts to update the cluster anno can fail which causes the
cluster to never enter the update in the controller
Solution:
Add a timeout that flips the regardless after 15 seconds
Issue: https://github.com/rancher/rancher/issues/19100
=> Flip cluster anno to stop loop

app/kontainerdriver_data.go
Upgrade Huawei CCE driver
There is some API change in Huawei CCE. The optional field is required now. 
https://github.com/rancher/rancher/issues/19146
=> Upgrade Huawei CCE driver

scripts/chart/promote-to-stable.sh
Regex was grabbing rc candidates. This searches for exact tag and
grabs most recent.
=> Regex is less greedy for chart promotion script

pkg/httpproxy/sign.go
https://github.com/rancher/rancher/issues/19287
=> relax check for service and region in aws signer

pkg/api/customization/nodetemplate/validation.go
https://github.com/rancher/rancher/issues/19219
=> remove validation for cloudcredential on nodetemplate create

pkg/api/customization/nodetemplate/validation.go, pkg/httpproxy/sign.go
Backport fixes for https://github.com/rancher/rancher/issues/19219 and https://github.com/rancher/rancher/issues/19287
=> Backport PRs for 2.2 

server/responsewriter/gzip.go, server/server.go
Problem:
Norman responses are not being gzipped.
Solution:
Chain v3 and connect APIs with gzip handler.
Issue:
https://github.com/rancher/rancher/issues/19454
=> Chain gzip handler

server/responsewriter/gzip.go, server/server.go
Properly chain gzip handler with v3 handler.
backport of https://github.com/rancher/rancher/pull/19463
https://github.com/rancher/rancher/issues/19490
=> Chain gzip handler (#19463)

chart/templates/deployment.yaml
https://github.com/rancher/rancher/issues/19473
=> Add ca-additional also to /etc/ssl/certs

pkg/dynamiclistener/server.go, pkg/settings/setting.go
https://github.com/rancher/rancher/issues/19156
=> Backport: Check cert expiration and regenerate

pkg/api/customization/cluster/formatter.go, pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/18807
https://github.com/rancher/rancher/issues/18793
=> Split manual and recurring backups (#18811) + review comments

pkg/api/customization/cluster/actionhandler.go
https://github.com/rancher/rancher/issues/19659
=> Add RBAC check for rotating cluster certificates

chart/values.yaml
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
=> [chart] fix typo, keep in sync with documentation

pkg/api/store/password/store.go, tests/integration/test_password_store.py, tests/integration/test_system_project.py
https://github.com/rancher/rancher/issues/19053
=> password store changes to adjust for arrays

pkg/api/store/password/store.go, tests/integration/test_password_store.py
=> passwordFields: return if data is empty

pkg/api/customization/app/app.go, pkg/controllers/user/helm/common/common.go, pkg/controllers/user/helm/controller.go, tests/core/conftest.py, tests/core/test_kontainer_drivers.py, vendor.conf, vendor/github.com/rancher/types/apis/project.cattle.io/v3/app_types.go
backport of https://github.com/rancher/rancher/pull/19079
https://github.com/rancher/rancher/issues/19881
https://github.com/rancher/rancher/issues/19880
=> Fix helm creating lots of configmaps

pkg/controllers/management/globaldns/globaldnsprovider_catalog_launcher.go, tests/integration/suite/test_globaldns.py
https://github.com/rancher/rancher/issues/19251
https://github.com/rancher/rancher/issues/19712
The proxySetting value was not getting converted correctly while setting the answers to the provider app.
=> Fix for setting the bool value for CloudFlare provider

pkg/controllers/user/monitoring/clusterHandler.go
**Problem:**
Can't completely clean up after disabling cluster monitoring, as the
`MonitoringStatus` may be `nil` before disabling Monitoring operation
**Solution:**
- Detect the status of `MonitoringEnabled` condition
- Fill `MonitoringStatus` before Prometheus ready checking
**Issue:**
https://github.com/rancher/rancher/issues/19645
=> Disable Monitoring via detecting Condition

pkg/api/store/password/store.go, tests/integration/suite/test_password_store.py
When password fields are not present in incoming data, need to delete secrets
from existing data. Earlier cleanup was done only on object deletion, not update.
=> passwordFields: add logic to cleanup secrets on update

.drone.yml, package/windows/Dockerfile.agent, scripts/windows/package.ps1
- Change `POWERSHELL_IMG_TAG` to `SERVERCORE_VERSION` on `package.ps1`
- Add `SERVERCORE_VERSION` on `.drone.yml` when publishing Windows agent
image
=> Enhance Windows Drone

pkg/rkeworker/docker_unix.go, pkg/rkeworker/execute_unix.go
=> Fix issue when compiling rancher locally 

pkg/api/customization/logging/action.go, pkg/api/store/password/store.go, pkg/controllers/user/logging/configsyncer/configgenerator.go, pkg/controllers/user/logging/configsyncer/configsyncer.go, pkg/controllers/user/logging/passwordgetter/passwordgetter.go, pkg/controllers/user/logging/passwordgetter/passwordgetter_test.go, tests/integration/suite/test_password_store.py
Problem:
sensitive data in logging store in crd now
Solution:
integrate with password store
Issue:
https://github.com/rancher/rancher/issues/19053
Depending pr:
https://github.com/rancher/rancher/pull/19983
=> Integrating logging with password store

pkg/api/customization/project/project_actions.go, pkg/api/server/managementstored/setup.go, pkg/controllers/user/monitoring/project_handler.go
- Add project monitoring action back
- Re-enable project monitoring controller
Related issue: https://github.com/rancher/rancher/issues/19771
=> Re-enable project monitoring

tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests, tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag, tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
=> QA Validation - Update pipelines for matrix jobs to point to new jenkins jobs for repo move

pkg/auth/providerrefresh/refresher.go, pkg/clustermanager/manager.go, pkg/controllers/management/auth/register.go, pkg/controllers/management/auth/token.go, pkg/controllers/management/auth/user.go, pkg/controllers/management/controller.go, pkg/controllers/user/clusterauthtoken/cluster_user_attribute.go, pkg/controllers/user/clusterauthtoken/register.go, pkg/controllers/user/clusterauthtoken/setting.go, pkg/controllers/user/clusterauthtoken/token.go, pkg/controllers/user/clusterauthtoken/user.go, pkg/controllers/user/clusterauthtoken/user_attribute.go
Problem: Default admin user stuck in removing state due to a finalizer
not being removed.
Solution: Change lifecycle handlers to be cluster scoped so that the
finalizer are removed.
Addresses https://github.com/rancher/rancher/issues/19594
=> Fix default admin stuck in removing

pkg/auth/providerrefresh/refresher.go, pkg/clustermanager/manager.go, pkg/controllers/management/auth/register.go, pkg/controllers/management/auth/token.go, pkg/controllers/management/auth/user.go, pkg/controllers/management/controller.go, pkg/controllers/user/clusterauthtoken/cluster_user_attribute.go, pkg/controllers/user/clusterauthtoken/register.go, pkg/controllers/user/clusterauthtoken/setting.go, pkg/controllers/user/clusterauthtoken/token.go, pkg/controllers/user/clusterauthtoken/user.go, pkg/controllers/user/clusterauthtoken/user_attribute.go
Backport for original issue https://github.com/rancher/rancher/issues/19594
Backport issue https://github.com/rancher/rancher/issues/20062
=> Backport admin stuck

server/responsewriter/gzip.go, server/responsewriter/gzip_test.go
Backport: https://github.com/rancher/rancher/pull/19951
Backport Issue: https://github.com/rancher/rancher/issues/20061
=> Backport: Disable gzip for empty responses

tests/integration/suite/test_globaldns.py, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/globaldns_types.go
https://github.com/rancher/rancher/issues/20088
=> Backport fqdn dns fix

pkg/controllers/user/logging/configsyncer/configsyncer.go
Problem:
Cluster level logging password unmasked after sync because update
cluster logging cache
Solution:
Using deep copy cluster logging obj
Issue:
https://github.com/rancher/rancher/issues/19985
=> Fixing cluster level logging password not always masked

pkg/controllers/user/monitoring/clusterHandler.go
Sort etcd endpoints and controlplane endpoints.
Related issue:
https://github.com/rancher/rancher/issues/19945
=> Sort address in monitoring app answers

pkg/agent/clean/clean.go
**Problem:**
We only delete `cattle-system` ns when removing imported cluster.
**Solution:**
We should also remove `cattle-prometheus`, `cattle-logging` and
any other project monitoring namespaces.
Related issue:
https://github.com/rancher/rancher/issues/19476
=> Clean Rancher Namespaces

pkg/api/customization/setting/setting.go, pkg/api/store/setting/store.go, tests/integration/suite/test_settings.py
Backport: https://github.com/rancher/rancher/pull/19867
Backport Issue: https://github.com/rancher/rancher/issues/20129
=> Backport: Disable deletion for readonly settings and remove setting deletion from test

package/Dockerfile
https://github.com/rancher/rancher/issues/20135
=> Update telemetry v2.2

pkg/controllers/user/monitoring/clusterHandler.go
Sort etcd endpoints and controlplane endpoints.
=> [release/v2.2.2-patch] Sort address in monitoring app answers

pkg/agent/clean/clean.go
Related issue:
https://github.com/rancher/rancher/issues/20113
=> [2.2]Clean cattle-prometheus ns

package/Dockerfile
Update UI for Windows
https://github.com/rancher/rancher/issues/20119
=> Update UI 2.3.1

pkg/api/customization/multiclusterapp/validator_multiclusterapp.go, pkg/api/server/managementstored/setup.go, tests/integration/suite/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/19982
=> Upgrade mcapp's apps on mcapp role change

pkg/httpproxy/proxy.go, pkg/httpproxy/proxy_test.go
=> Changed meta proxy

pkg/controllers/user/helm/common.go
Related issue:
https://github.com/rancher/rancher/issues/19831
=> [2.2]Print error message when stopping tiller error

pkg/httpproxy/proxy.go, pkg/httpproxy/proxy_test.go
=> 2.1 Change meta proxy

pkg/httpproxy/proxy.go, pkg/httpproxy/proxy_test.go
=> 2.0/proxy fix

pkg/controllers/user/helm/common.go
Related issue:
https://github.com/rancher/rancher/issues/19831
=> Print error message when stopping tiller error

pkg/httpproxy/proxy.go, pkg/httpproxy/proxy_test.go
=> Change meta proxy

package/Dockerfile
Issue: https://github.com/rancher/rancher/issues/20040
=> Update telemetry master

pkg/controllers/management/node/controller.go, pkg/controllers/management/node/controller_test.go
Problem:
The pathing for userdata is not correct and always included a full path
Solution:
Update path based on envvar
=> Fix writing file contents to disk

pkg/image/export/main.go
Addresses rancher/rancher#19716
=> Push registry:2 to priv.repo/rancher/registry:2

pkg/controllers/user/monitoring/operatorHandler.go
**Problem:**
Cannot configure the Operator resources
**Solution:**
Get Operator configuration item when enabling Cluster Monitoring
**Issue:**
https://github.com/rancher/rancher/issues/20022
=> Support to configure the Operator resources

pkg/auth/providers/saml/saml_client.go
https://github.com/rancher/rancher/issues/20216
=> Send translation key as error message

package/jailer.sh, pkg/controllers/management/node/controller.go, pkg/controllers/management/node/utils.go, pkg/jailer/jailer.go
Problem:
Jailed did not handle multi-threaded
Solution:
Lock the jailer runs
=> Fix broken jail

package/jailer.sh, pkg/controllers/management/node/controller.go, pkg/jailer/jailer.go
Problem:
Jailed did not handle multi-threaded
Solution:
Lock the jailer runs
=> Fix broken jail master

package/jailer.sh, pkg/controllers/management/node/controller.go, pkg/jailer/jailer.go
Problem:
Jailed did not handle multi-threaded
Solution:
Lock the jailer runs
=> Fix broken jail v2.2

tests/integration/suite/test_persistent_volume.py, vendor.conf, vendor/github.com/rancher/types/apis/cluster.cattle.io/v3/schema/schema.go
https://github.com/rancher/types/pull/835 
rancher/rancher#19237
=> add test for updating persistent volume 

vendor.conf, vendor/github.com/rancher/types/apis/cluster.cattle.io/v3/schema/schema.go
https://github.com/rancher/rancher/issues/20462
=> vendor update rancher/types

pkg/controllers/management/drivers/nodedriver/machine_driver.go
Problem:
An already installed driver with an unknown condition can get stuck in
ithat condition
Solution:
If a condition is unkown force update the driver
=> Force update drivers based on condition

package/windows/run.ps1
**Problem:**
Consider only the CA chain with only one CA
**Solution:**
Split multiple CAs from `$SSL_CERT_DIR\serverca`, then import one by one
**Issue:**
https://github.com/rancher/rancher/issues/20436
=> Support self-signed server CA chain on Windows

pkg/api/customization/authn/rtb_store.go
Addresses https://github.com/rancher/rancher/issues/20531
=> Backport Errors in rancher logs when delete cluster

pkg/controllers/management/drivers/base_driver.go, pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go, pkg/controllers/management/drivers/nodedriver/machine_driver.go, vendor.conf, vendor/github.com/rancher/types/apis/management.cattle.io/v3/machine_types.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_node_driver_status.go
Problem:
Node drivers are not updated even with url changes
Solution:
Validate driver urls, hashes, and docker-machine versions to allow
schemas of node-drivers to be updated
=> Update drivers on startup master

pkg/controllers/user/endpoints/endpoints.go, pkg/controllers/user/nodesyncer/cordonfieldssyncer.go, pkg/controllers/user/nodesyncer/nodessyncer.go, pkg/node/node.go, pkg/node/node_test.go
Refactor and testing commits from https://github.com/rancher/rancher/pull/20375
=> Refactor nodesyncer

pkg/controllers/user/logging/generator/templatesource.go
Hello!
This PR increases log precision in fluentd config templates.
=> Increase log precision

scripts/package
https://github.com/rancher/rancher/issues/20696
=> Read branch from the var for rancher images generation

pkg/controllers/management/drivers/nodedriver/machine_driver.go
Problem:
Fields that were converted to take contents instead of a path are
showing as an input box but the UI doesn't know what fields to handle
differently.
Solution:
Add an annotation on the nodedriver to specify the fields and type the
UI should handle differently
=> Add annotation on nodedriver for UI

pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/management/node/controller.go
Issue: https://github.com/rancher/rancher/issues/20747
=> Add userDataFile for openstack nodedriver v2.2

pkg/controllers/management/drivers/nodedriver/machine_driver.go
Problem:
Fields that were converted to take contents instead of a path are
showing as an input box but the UI doesn't know what fields to handle
differently.
Solution:
Add an annotation on the nodedriver to specify the fields and type the
UI should handle differently
=> Add annotation on nodedriver for UI master

pkg/controllers/management/drivers/nodedriver/machine_driver.go
Problem:
driver name is not always known before the driver is staged, this can cause path errors 
Solution:
Move the driver name creation back to after the driver has been staged and move out nodeDriver object updates until after the driver is successfully installed
Issue: https://github.com/rancher/rancher/issues/20796
=> Refactor NodeDriver download

pkg/controllers/management/drivers/nodedriver/machine_driver.go
Problem:
driver name is not always known before the driver is staged, this can cause path
errors
Solution:
Move the driver name creation back to after the driver has been staged and move
out nodeDriver object updates until after the driver is successfully installed
Issue: https://github.com/rancher/rancher/issues/20799
=> Refactor NodeDriver download master

pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/20792
=> Add openstack cacert field to nodedrivers master

pkg/controllers/management/drivers/nodedriver/machine_driver.go, pkg/controllers/management/node/controller.go
https://github.com/rancher/rancher/issues/20792
=> Add openstack cacert field to nodedrivers

pkg/controllers/management/etcdbackup/etcdbackup.go
https://github.com/rancher/rancher/issues/19496
=> Add support for etcd snapshot compression

pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go, tests/integration/suite/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/20868
=> use creatorID of mcapp for mcapp revision

pkg/controllers/management/multiclusterapp/controller_multiclusterapp.go, tests/integration/suite/test_multi_cluster_app.py
https://github.com/rancher/rancher/issues/20919
=> [backport] use creatorID of mcapp for mcapp revision

tests/validation/tests/v3_api/test_eks_cluster.py
=> Add K8s cluster version

pkg/settings/setting.go
https://github.com/rancher/rancher/issues/19522
=> [release/v2.2] Add kube-node-lease namespace to System project

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/19522
=> [2.2 backport] Update embedded kubectl to 1.13

.drone.yml, manifest-agent.tmpl, manifest.tmpl
=> sync drone with changes from #20678

pkg/controllers/management/etcdbackup/etcdbackup.go
backport pr for https://github.com/rancher/rancher/issues/20964
=> [backport 2.2] check for nil enabled

.drone.yml, manifest-agent.tmpl, manifest.tmpl
Same as #20678, but for the master branch
=> sync drone.yml with master

package/Dockerfile.agent
https://github.com/rancher/rancher/issues/19522
=> Update embedded kubectl to 1.13

pkg/settings/setting.go
https://github.com/rancher/rancher/issues/19522
=> Add kube-node-lease namespace to System project

pkg/controllers/user/certsexpiration/certsexpiration.go, pkg/controllers/user/controllers.go
=> Add CertificatesExpiration to cluster status

package/Dockerfile
=> Update UI Revision

.drone.yml
Same fix as #21000, plus some standardization.
=> Fix head images VERSION arg - master

.drone.yml
=> Fix version arg - 2.0

.drone.yml
=> fix version arg

.drone.yml, manifest-agent.tmpl, manifest.tmpl
=> strip "release/" and add "-head" suffix

pkg/api/customization/app/app.go, tests/core/test_rbac.py
Backport: https://github.com/rancher/rancher/pull/20933
=> Backport: Check app update perms

app/machinedriver_data.go
Add node driver support for Pinganyun ECS
https://github.com/rancher/rancher/issues/20878
=> [master] Add Pinganyun ECS driver

app/kontainerdriver_data.go, tests/integration/suite/test_rbac.py
Add cluster driver support for Baidu CCE.
https://github.com/rancher/rancher/issues/20854
=> [master] Add Baidu CCE driver

app/machinedriver_data.go
Add node driver support for Pinganyun ECS
https://github.com/rancher/rancher/issues/21097
=> Add Pinganyun ECS driver

app/kontainerdriver_data.go, tests/integration/suite/test_rbac.py
Add cluster driver support for Baidu CCE.
https://github.com/rancher/rancher/issues/21097
=> Add Baidu CCE driver

package/Dockerfile
=> Update UI release

pkg/controllers/user/healthsyncer/healthsyncer.go
https://github.com/rancher/rancher/issues/20927
=> Fix componentstatus check for k8s v1.14

pkg/api/customization/cluster/validator.go, pkg/api/server/managementstored/setup.go, pkg/api/store/clustertemplate/store.go, pkg/controllers/management/clustertemplate/revision_controller.go, pkg/settings/setting.go, tests/integration/suite/test_clustertemplate.py
This PR will change after https://github.com/rancher/rancher/pull/20556 is merged.
=> Cluster Template Enforcement

pkg/api/customization/secret/validator.go, pkg/api/server/managementstored/setup.go, pkg/api/server/userstored/setup.go, tests/integration/suite/conftest.py, tests/integration/suite/test_rbac.py
Backport: https://github.com/rancher/rancher/pull/21052
=> Backport: Add permissions check for secrets

pkg/api/customization/secret/validator.go, pkg/api/server/managementstored/setup.go, pkg/api/server/userstored/setup.go, tests/integration/suite/conftest.py, tests/integration/suite/test_rbac.py
Problem:
Any type of secret can be created by a read-only member
Solution:
Add validator to check project permissions on secrets
Issue:
=> Add permissions check for secrets

pkg/api/customization/secret/validator.go
Backport: https://github.com/rancher/rancher/pull/21137
=> Backport: Require two part projectId

package/Dockerfile
Fixes javascript issue on cluster edit.
=> new ui release

package/Dockerfile
=> Ui Release
